### ISSUE TITLE
Extrapolation strategy of interpolation model

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1016]
Currently our interpolation model documentation says something like (see #990 )

```
+ Between the data points, the interpolation uses the neighboring points.
+ Outside the range spanned by the points, we extrapolate using a line through
+ the first and the last point.
```

I think this might not always be smart because i) it may introduce discontinuities into the model and ii) rests on only 2 datapoints. Maybe a more robust idea would be to 
- use a linear /polynomial model through all points but only apply it outside the data range
- use the last N points to fit a linear model so that the "trend at the end" is somewhat captured

**Comment by hendrikweisser** [comment]
Different options for extrapolation were added in #1713.
