### ISSUE TITLE
Protein coverage not properly calculated

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1031]
Overlapping peptides are ignored resulting in coverage potentially higher than > 100%.

**Comment by oliverschilling** [comment]
Hello, I came across this problem as well: coverage > 100% when using msgf+/fido. Would it be possible to calculate coverage based on the number of non-redundant peptides? Thanks
Oliver

**Comment by lars20070** [comment]
We see much improved protein coverage results since moving from X!Tandem to MSGF+ searches. Now we wonder if this is real or due to this bug.

**Comment by cbielow** [comment]
while this might reduce the problem, this would not solve it, since we'd 
still ignore missed cleavages, i.e. certain substrings could still be 
counted twice, leading an overestimation, e.g. >100% coverage.


Am 5/18/2015 um 5:39 PM schrieb oliverschilling:

**Comment by hendrikweisser** [comment]
@oliverschilling:
> Would it be possible to calculate coverage based on the number of non-redundant peptides?

I haven't checked the code, but I would imagine that this is already done (i.e. identical peptides are not counted more than once). The problem arises due to non-redundant, but overlapping peptides, as mentioned by @cbielow.

**Comment by timosachsenberg** [comment]
Ok I think we need to solve two problems then.
The first one is the easier one (non-redundant peptides):
A. use only non-redundant peptides - here the start end position needs to be written out by PeptideIndexer (its already calculated and stored in the PeptideEvidences object)
B. calculate coverage on the amino acid level (e.g. simply a vector<bool> for every protein and then to mark the covered amino acids; divide number marked ones by length afterwards) 

The second one is more difficult (all peptides):
1. decide how coverage is reported if we have shared peptides
2. write out the start, end information stored in PeptideEvidence in PeptideIndexer
3. do something similar as above (depending on how we determine the coverage)

Especially, 2 is a bit tricky as we probably need mzIdentML for this.
@mwalzer what is the state of our mzIdentML support on storing this information? An do we have a way to store the protein groups already?

**Comment by jpfeuffer** [comment]
Is there an update on this? Lars and I also came up with two solutions (overlapping a lot with Timo's):
1) Store start and end index in the files so they dont get lost
  a) Change idXML PeptideID
  b) Use user params
  c) Use mzIdentML (preferred)

2) Calculate them with another tool right before the exporter. This leads to duplicate effort and probably code (if not refactored really well from PeptideIndexer) and might be difficult with different databases (which is on the other hand probably difficult to handle anyhow).

Regarding how it is calculated, we agreed on counting all occurences of a peptide in a protein (also considering before and after, if available).

**Comment by lars20070** [comment]
PeptideIndexer already determines start and end positions of a peptide [1] in the protein sequence. We would like to re-use this information in a new Coverage TOPP tool (see 2 above). Unlike aa_before and aa_after, the positions are not stored in idXML.

@mwalzer  Can we make the transition to mzid, (1c) above? (1b) will bloat idXML. (1c) will modify idXML and probably break a lot.

[1] http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/classOpenMS_1_1PeptideEvidence.html#a5e31f7e4f8938fdf5ba8b22a9b8123dc

**Comment by timosachsenberg** [comment]
As a side note: aa_before and aa_after are only stored in idXML for the first evidence which is also kind of useless.

**Comment by lars20070** [comment]
Resolved in #1936 and #1954.
