### ISSUE TITLE
enable ubsan

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1053]
gcc 4.9 has a feature called ubsan "GCC Undefined Behavior Sanitizer – ubsan" which is turned on by using `-fsanitize=undefined`

we should enable that in our 4.9 builds (currently we have one on Mac OS X on cdash if I am not mistaken).

see this article: http://developerblog.redhat.com/2014/10/16/gcc-undefined-behavior-sanitizer-ubsan/

**Comment by mwalzer** [comment]
:+1:

**Comment by hendrikweisser** [comment]
Is this ticket still relevant?

**Comment by timosachsenberg** [comment]
We do ASAN. Might be worth to test it and check if we get anything meaningful back.

**Comment by timosachsenberg** [comment]
added to https://github.com/OpenMS/OpenMS/blob/develop/cmake/AddressSanitizer.cmake
