### ISSUE TITLE
MapAlignmentEvaluation has no annotated output

### ISSUE THREAD

**Issue by bgruening** [OpenMS/OpenMS#1071]
The annotation of MapAlignmentEvaluation is probably not correct. In particular an output format is missing. It's also not working in TOPPAS.

**Comment by timosachsenberg** [comment]
@hendrikweisser any insight on this issue? The tool has not been used in the last year according to the update checker so I tend to remove it. These kind of evaluations are imho better done downstream in R.

**Comment by hendrikweisser** [comment]
@timosachsenberg: Don't ask me. I have nothing to do with that tool.

But it looks to me like it covers only a very narrow use case (for the publication referenced in the docs) and is therefore not of general interest. I would be okay with removing it.

**Comment by timosachsenberg** [comment]
ok I remove it in https://github.com/OpenMS/OpenMS/pull/2620

**Comment by hendrikweisser** [comment]
Tool has been removed, so issue can be closed.
