### ISSUE TITLE
protein quantification workflows in TPP and OpenMS

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1095]
This thread continues the discussion in #1027. As part of the protein inference beta testing, we aim to reproduce roughly the results from a TPP protein quantification published in [1]. Even with a working FidoAdapter, there remain some other issues to be resolved and optimised.

In the test dataset, a wild type (wt) mouse skin sample is compared to a Cathepsin L knockout (Ctsl-/-). The two samples were dimethyl labelled heavy (+34Da) and light (+28Da) respectively, mixed and then split into eleven fractions ST366 to ST376.

The aim is to roughly re-produce the protein list of the TPP analysis. Many of the high intensity proteins have been checked independently by Western Blotting.

[1] Tholen et al. CMLS 71(5), 899–916 (Mar. 2014). http://www.ncbi.nlm.nih.gov/pubmed/23233448

**Comment by lars20070** [comment]
IMO, the problem lies already with the XTandemAdapter. @algom Let's run an XTandem search on ST366 with your exact parameters from the command line. Then we will try to replicate the results with the XTandemAdapter.

**Comment by lars20070** [comment]
In this Dropbox [1] we compared X!Tandem via the TPP web interface with XTandemAdapter. Same files (ST370, ST371, ST371). Same executable. Same database mouse (unshuffled). Same tolerances and mods. Still different number of IDs.

+++ pepXML +++
ST370  6,826 PSMs (4,957 unique)
ST371  3,423 PSMs (2,487 unique)
ST372  3,575 PSMs (2,745 unique)

+++ idXML from XTandemAdapter +++
ST370  2,051 PSMs (1,073 unique)
ST371  979 PSMs (651 unique)
ST372  879 PSMs (692 unique)

[1] https://www.dropbox.com/sh/3wwga47kt5vdyke/AAAf4ZcfrStw39m3JgxWWH3ea

**Comment by jpfeuffer** [comment]
One thing to consider is the scoring of the PSMs in XTandem. The default in TPP seems to be the "k-score" (which is a kind of extra plugin for XTandem scoring), whereas in standard XTandem that is used in the Adapter, the e-value of the hyperscore is used.
This should not affect the number of candidates that are scored, but maybe the number of candidates that are reported in the output file for a given e-value cutoff.
I don't know if we can use the k-score in the Adapter, so maybe this has to be disabled in TPP for comparison (although the k-score seems to be the better/more discriminative choice).

**Comment by hroest** [comment]
this seems an important point, here in our group we always use XTandem with
the k-score plugin and it might, at least partially, explain the
difference. For us this is default usage so it would be important to have
this in OpenMS as well

**Comment by lars20070** [comment]
Currently testing XTandemAdapter. Changing the value for max_valid_expect has no effect on result.

**Comment by lars20070** [comment]
Is it possible to inspect the *.tandem results file (which is then converted to the idXML output)?
It contains all parameters used for the search and we could directly compare to the one from the command line.

**Comment by mwalzer** [comment]
This is written into the XTandemAdapters TOPP temp directory. Setting debug_level_ >= 2 should retain this directory.

**Comment by lars20070** [comment]
Great. Works. Thanks @mwalzer.

**Comment by oliverschilling** [comment]
Thanks @mwalzer, that was helpful. 
The adapter showed:
<note type="input" label="output, results">all</note> 
This means that the e-value cutoff is ignored: http://www.thegpm.org/TANDEM/api/oresu.html

The X!tandem adapter should have the option to select options such "valid" and "stochastic" (see http://www.thegpm.org/TANDEM/api/oresu.html). These two options take the e-value cutoff into account. (or did I overlook this option?)

Thanks!

Oliver

**Comment by timosachsenberg** [comment]
I will take a look at it

**Comment by oliverschilling** [comment]
thanks timo - sorry for the incomplete "copy and paste"... i did of course mean 
	<note type="input" label="output, results">all</note>
which decides whether the e-value will be used:
	<note type="input" label="output, maximum valid expectation value">0.01</note>

**Comment by oliverschilling** [comment]
ok, third try, now without the brackets:
note type="input" label="output, results"... (all or valid or stochastic )
note type="input" label="output, maximum valid expectation value...

**Comment by timosachsenberg** [comment]
Thanks @oliverschilling I basically have the fix ready. I will keep the default on "all" for now but introduce a novel parameter that allows to switch it to "valid". If we see that "valid" is the only thing that makes sense we might think about making it the default (though it might interfere with consensus approaches)

**Comment by oliverschilling** [comment]
Hi Timo - along the same line

usage of the "parent monoisotopic mass isotope error"  cannot be de-activated in the present tandem adapter. Can this please also be fixed / made selectable? See also

http://www.thegpm.org/TANDEM/api/spmmie.html

Thanks!

Oliver

**Comment by timosachsenberg** [comment]
This parameter seems to have the potential to really make a difference as I also regularly observe false assignments.

**Comment by oliverschilling** [comment]
I fully agree; have the same experience...

**Comment by lars20070** [comment]
@timosachsenberg We just tested the reverse. XTandemAdapter search. Then the exact same parameters via the TPP interface. We can reproduce the exact results.

**Comment by timosachsenberg** [comment]
I just saw that this tolerant search for the first and second isotpic peak missasignmen is enabled by default in OpenMS. Do you need this to be disabled?

**Comment by lars20070** [comment]
Yes @timosachsenberg. Seems to make the searches worse.

**Comment by timosachsenberg** [comment]
ok will add it. It ceratinly increases the search space and might in some cases be detrimental (e.g. if very good precursor assignments are present)

**Comment by timosachsenberg** [comment]
added it in https://github.com/OpenMS/OpenMS/pull/1196

**Comment by Stortebecker** [comment]
a great feature for advanced users of the x!tandem-adapter would be to accept a tandem.params file instead of specifying every parameter in the mask. When a tandem.params file is used, it should overrule all other inputs but the input files. thus, people that used xtandem for years can just carry on with their old parameter files without having to care about the mask.

**Comment by lars20070** [comment]
+1

I added a new feature request #1234.

**Comment by algom** [comment]
+1 Very useful feature

**Comment by jpfeuffer** [comment]
An update on the ID part of the pipeline:
I ran our FidoAdapter on the converted pepXML from TPP-PeptideProphet on the LN1 data and got 178 proteins above 0.05 FDR, as opposed to 123 with ProteinProphet (minProb cutoff 0.7 equal to 0.05 FDR).
Overlap was 121 proteins. The ranking was also similar (compared by eye).
This means, on the very same input we are definitely on par with TPP. Now let's see what/if this changes, when I use our PEP Tool instead of PeptideProphet.

**Comment by timosachsenberg** [comment]
sounds great!

**Comment by lars20070** [comment]
Thanks @jpfeuffer. Let's compare our TPP analyses. In my 5% peptide FDR analysis from January, I find 970 proteins with 894 indistinguishable proteins (i.e. identical peptide evidence) in 759 protein groups, see interact.prot.csv in [1].

[1] https://www.dropbox.com/sh/bmfpru4kk23frqs/AADPZEhmaPDzV9V_BQQEDMVpa

**Comment by Stortebecker** [comment]
Hej. I made a small batch script to run X!Tandem, PeptideProphet and ProteinProphet from commandline. You will also need the generateTandemParam.pl. When I run TPP from commandline, I get exactly the same results as @lars20070 out of the GUI. You can find both scripts here: 

https://www.dropbox.com/sh/pfodvihuv5gocxt/AACdDEIN1uuB2DGyRo98Z36Ea

**Comment by Stortebecker** [comment]
Oh, and don't forget to change the paths in the batch and to copy a valid taxonomy.xml into the folder, pointing to the right database.

**Comment by jpfeuffer** [comment]
Thanks again, @lars20070 and @Stortebecker for the data and the additional script.
But I can neither find the actual input H_LN1 and L_LN1 nor your tandem.params. The thing is, that I need the decoy peptides/proteins, too and the interact.pepXML in the DB folder seems to have been run with the standard options in TPP (that removes decoys).
Could you give me a link to the input data or (even better) run (only) PepProphet with "d [report decoy hits with a computed probability based on the model learned]" once for me since I always need to refer to a slow VM for the TPP analyses?

**Comment by lars20070** [comment]
In my analysis, 5% FDR did correspond to min_prob = 0.1315, see the following line in interact.pepXML in the Dropbox.

<error_point error="0.0500" min_prob="0.1315" num_corr="3600" num_incorr="191"/>

**Comment by lars20070** [comment]
Here [2] a complete copy of directory of my TPP analysis. H_LN1 and L_LN1 are exact copies of LN1.mzXML.

[2] https://www.dropbox.com/sh/5zd4vtypgs5bcud/AACeF4mkPPKz4599Heb8NhXBa

**Comment by Stortebecker** [comment]
@jpfeuffer wrote:
> Could you [...] run (only) PepProphet with "d [report decoy hits with a computed probability based on the model learned]" once for me

Sorry, what exactly do you mean?

**Comment by jpfeuffer** [comment]
Ok. So I used your *.tandem outputs converted to pep.xml as a common base.

My TPP command:
    ./xinteract  -Ninteract_xtandem.pep.xml -p0.0 -l7 -OdARP -dSHUFFLED -X-m0.02-nK,6.031817-nn,6.031817-H  ~/TPP_analysis/*.pep.xml

I removed the cutoff for peptide probability since I don't see a reason why peptides should be excluded from the protein inference other than for computational convenience (ProteinProphet applies a 0.05 probability cutoff anyways).
Additionally, I added a "d" to the PeptideProphet options ("-O") to keep decoys after the analysis. Fido needs them to do its parameter optimization.

Then I run ProteinProphet with standard options like you did:
    ./ProteinProphet ./results_wdecoy/interact_xtandem.pep.xml result.prot.xml
Afterwards I parsed the file and filtered for probability 0.5 which should correspond to a FDR of 0.05.

In comparison I ran PeptideIndexer on the interact_xtandem.pep.xml, then Fido, FDR and also filtered with a 0.05 cutoff. I can upload my TOPPAS later.

This is the result for protein singleton groups (i.e. expanding ambiguity and indistinguishable groups) to make it comparable.
![venn](https://cloud.githubusercontent.com/assets/8102638/6253590/df222430-b7a2-11e4-9ffd-676b5cba2f67.png)

**Comment by Stortebecker** [comment]
@jpfeuffer Looks great! Your changes in the xinteract make sense. However, maybe you should keep the -p0.05 to get rid of the worst hits. I guess this will also keep the files somewhat smaller without loosing needed information.

**Comment by lars20070** [comment]
Thanks @jpfeuffer. Looks very good. Could you please send me the toppas workflow? I will try to reproduce your results.

Please use the XTandemAdapter with output_results=valid and  refinement=false. Timo recently added these two parameters. We get slightly better results with them.

**Comment by oliverschilling** [comment]
It really does look great - thanks a lot!

**Comment by Stortebecker** [comment]
I am not sure about the "output_results=valid" option. I played around with it, but did no deeper testing. What I saw was, that setting "maximum_valid_expectation_value" to 0.1 would remove almost all decoy hits, as these typically have bad expectation values. A "maximum_valid_expectation_value" of 10 would result in about 50% decoys, 50% true hits. For a start, I would guess it is easier to stay with the "output_results=all", and thoroughly test the "valid" with different maximum e-values, before using it as a standard.

**Comment by Stortebecker** [comment]
I tested now on one mzXML file several settings for PeptideProphet cutoff (-p0.05 or -p0.4, the latter being about 5% FDR cutoff), and X!Tandem settings (all, valid with maximum e-value = 10, and valid with maximum e-value = 0.1). 

Interestingly, for protein inference with ProteinProphet, it does not really make a difference. When I use 5% FDR cutoff on PROTEINS, almost all outputs are the same. They differ only in 1-3 protein IDs out of 825 to 828. 

The only exception is, when the maximum e-value is set to 0.1, much less proteins are identified. I guess that is due, because the "garbage" is filtered out on the database search level. So my conclusion is 

1) to use output_results=all
2) FDR filtering on Peptide level (after PeptideProphet) is not necessary, but also does no harm

You have to keep in mind that I ran the testing only on one file, though.

**Comment by oliverschilling** [comment]
@jpfeuffer: thanks again for the analysis. May I kindly remind you to please upload your TOPPAS workflow? It would also be great to test this workflow with tandem identifications from within OpenMS (aka using the XTandem adapter...or actually also another adapter). The results are really exciting; it would be great to see this taking shape!

**Comment by jpfeuffer** [comment]
Hey everybody.
I think everything you need should be located at [1] now.
It includes the commands to generate the interact.pep.xml from the 2 Xtandem searches and the protXML via ProteinProphet. There is also the TOPPAS workflow, that starts from the pepXML. I had to modify the names of the decoy proteins in the fasta a bit, that our Tools can handle it, so it is also included. When you executed TOPPAS and ProteinProphet you can compare the protein lists with the KNIME workflow I included. I am in the process of creating a whole KNIME-based workflow now.

[1] https://www.dropbox.com/sh/oe06fnapi3a9713/AACqFsV3-KoKCuHdmI17KCrha?dl=0

**Comment by lars20070** [comment]
Ok. - When your whole KNIME-based workflow (mzML in, proteins out, no TPP) is ready, we will replicate it in Freiburg with TOPPAS.

**Comment by jpfeuffer** [comment]
Okay my KNIME-based workflow is finished. I ported it to TOPPAS for your convenience. You can download it from [1] again (now with folders). Input is the LN1.mzML and my fasta with renamed decoys. I setup XTandem like @lars20070  and @Stortebecker suggested.
The result after KNIME analysis is this in my runs:
![fullopenms_vs_tpp](https://cloud.githubusercontent.com/assets/8102638/6358873/104fe68e-bc6f-11e4-8d31-c948e2f43c77.png)

[1] https://www.dropbox.com/sh/oe06fnapi3a9713/AACqFsV3-KoKCuHdmI17KCrha?dl=0

**Comment by oliverschilling** [comment]
Thanks jpfeuffer! Looks good to me.

**Comment by lars20070** [comment]
@jpfeuffer I reproduced the 1,061 proteins with your toppas pipeline. Great.
We will now do some further testing on other datasets.

**Comment by lars20070** [comment]
@algom @Stortebecker Julianus' workflow is on our server in
D:\data\OpenMS workflows\protein inference

**Comment by Stortebecker** [comment]
@jpfeuffer I could test the workflow on a much larger organ dataset now. It consists of about 12 MS-runs (SCX-LC-fractions). At what point would you suggest to use the "Collect"-node to combine all fractions into one file? After PeptideIndexer? Or after the FDR node behind PeptideIndexer?

**Comment by Stortebecker** [comment]
And just out of curiosity: Is it really necessary to add the FDR filtering on peptide level? Does that make a difference for Fido. I tested that on the comparable ProteinProphet, where it makes no difference at all.

**Comment by Stortebecker** [comment]
@jpfeuffer I do not understand why you use two different IDFilters after Fido. One before and one after the FDR node. What does it exactly do?

**Comment by jpfeuffer** [comment]
@Stortebecker 
> At what point would you suggest to use the "Collect"-node to combine all fractions into one file? After PeptideIndexer? Or after the FDR node behind PeptideIndexer?
I would probably go with: Tandem-IDPEP-Collect-PepIndexer-Fido.
IDPEP for every fraction, because the different runs might introduce some bias so the models are not correctly fit, when combining all the scores.
I think PeptideIndexer doesn't really care about when it associates a peptide to the protein DB. It should be faster when applying it once after collecting all the peptide IDs (because of the DB indexing).

> I do not understand why you use two different IDFilters after Fido. One before and one after the FDR node. What does it exactly do?
It filters for proteins with 0 probability. I remember at some point getting an error when using FDR afterwards but it has no real meaning since those identifications are filtered in the second step anyways. You can try to remove it.

**Comment by lars20070** [comment]
@jpfeuffer Thanks for the comment. You are right. The IDFilter before FDR with score:prot = 0.001 can go. The results are identical.

**Comment by Stortebecker** [comment]
@jpfeuffer Ok, I did the testing now with a dataset of 11 files. However, I get a strange result, which I cannot explain. I put all outputs in my Dropbox:
https://www.dropbox.com/sh/95v05enfbe9aorm/AABxg2eUcdqIWU0xAtNRjW0Ia?dl=0

I used the workflow "ProteinInferenceFido" for generating the output. If I run it on one of the fractions (test) or two of them (test2), all is fine. I get 466 and 492 protein IDs, respectively. However, if I analyze all eleven fractions, all proteins are lost during FDR filtering. After Fido, I have "Inferred 3163 proteins in 2891 groups (2 proteins with probability zero not included)." Then comes FDR filtering:  

15:25:52 NOTICE: IDFilter of node #10 started. Processing ...
Filtering by protein score > 0.05 ...
Filtering decoy proteins ...
Filtering unreferenced protein hits ...
Peptide identifications remaining: 8028 / 8028
Protein identifications remaining: 0 / 3165
IDFilter took 2.51 s (wall), 2.52 s (CPU), 0.11 s (system), 2.41 s (user).

... and all my proteins are gone. What went wrong here?

**Comment by lars20070** [comment]
In the analyses of the LN1 HEK dataset, TPP lists 44 groups of indistinguishable proteins (i.e. proteins based on the same peptide evidence), and Fido lists 38. Close enough. But the TextExporter output lists the 1,061 proteins in separate lines.

The export of the 'indistinguishable proteins' and the 'protein group' structures are still missing. In the TPP output indistinguishable proteins appear in the same line and protein groups with entry number such as 389a, 389b [1].

[1] https://www.dropbox.com/s/38mrd8sydsuj2l0/interact.prot.csv

**Comment by timosachsenberg** [comment]
Hi Lars and others. Can you provide small text files like this as gist? Dropbox files are usually not permanent and not fit for propet documentation.

**Comment by lars20070** [comment]
@timosachsenberg Here [1,2] the csv version of interact.pep.xml and interact.prot.xml from the TPP analysis we are using for beta testing and comparison.

[1] https://gist.github.com/lars20070/fad92c9d49d4f59585e5
[2] https://gist.github.com/lars20070/80be05781493270acd9a

**Comment by lars20070** [comment]
@jpfeuffer Your workflow still uses an old FidoAdapter version. For example 'fidochooseparameters_executable' instead of 'fidocp_executable' appears. Are you sure the choose parameter executable did run?

And 'prob_param' is empty in your workflow instead of the default 'Posterior Probability_score'. Did Fido really use the posterior error probabilities calculated in the step before?

**Comment by lars20070** [comment]
With the default 'prob_param' = 'Posterior Probability_score' the FidoAdapter crashes with 'unsuitable score type'.

Currently, I try to replace XTandem by MSGF+. Despite higher number of peptide hits Fido get 40% less proteins than XTandem. Seems MSGF+ scores and Fido do not work well together. The search engine independent posterior error probabilities lead to crashes for XTandem and MSGF+, see above.

**Comment by lars20070** [comment]
Can we switch on write_protein_sequence in PeptideIndexer by default? IMO, protein coverage should be standard in the OpenMS output.

**Comment by hendrikweisser** [comment]
@lars20070:
> With the default 'prob_param' = 'Posterior Probability_score' the FidoAdapter crashes with 'unsuitable score type'.

That's without updating FidoAdapter to the current version, correct?

> Currently, I try to replace XTandem by MSGF+. Despite higher number of peptide hits with MSGF+, Fido gets 40% less proteins than with XTandem. Seems MSGF+ scores and Fido do not work well together. The search engine independent posterior error probabilities lead to crashes for XTandem and MSGF+, see above.

I wouldn't expect Fido to work with raw MS-GF+ scores, because they're not probabilities. Neither are X! Tandem scores. So what do you use to calculate probabilities from the search engine scores - IDPosteriorErrorProbability?

> Can we switch on write_protein_sequence in PeptideIndexer by default? IMO, protein coverage should be standard in the OpenMS output.

I don't think we should do that until the coverage calculation is corrected (#1031).

**Comment by lars20070** [comment]
Ok. With the protein coverage we wait for #1031.

**Comment by lars20070** [comment]
The workflow should use the previously calculated posterior error probabilities. In Julianus' workflow [1] prob_param (by default 'Posterior Probability_score') is empty. Could prob_param become false/true or a dropdown box, not a string field?

[1] https://www.dropbox.com/sh/oe06fnapi3a9713/AACqFsV3-KoKCuHdmI17KCrha

**Comment by jpfeuffer** [comment]
The thing is, there are potentially infinite scores that could be used from the user params. I removed this string because the ONE score field in the PeptideIDs is already the PEProbability that we need.
The option to read the scores from a user_param was a workaround to allow other tools coming after the PEP calculation for the peptides that would override the ONE score.

**Comment by hendrikweisser** [comment]
> The workflow should use the previously calculated posterior error probabilities. In Julianus' workflow [1] prob_param (by default 'Posterior Probability_score') is empty. Could prob_param become false/true or a dropdown box, not a string field?

FidoAdapter needs to know how to find those previously calculated posterior (error) probabilities. "prob_param" is only a work-around for when they are not in the "score" of the peptide hits. Its value is the name of a UserParam (meta value) that contains the probabilities. Since that name could be basically anything, "prob_param" needs to be a string.

**Comment by jpfeuffer** [comment]
It would indeed be beneficial to show a dropdown menu of all possible user_params to use, but this would mean, that the input file needs to be read before you configure your node. I don't know if this makes sense or if it is worth the effort.

**Comment by lars20070** [comment]
Ok. I am fine with the prob_param string. But it should be empty by default as in Julianus' workflow, right? In this case the posterior error probabilities in "score" are being used.

**Comment by jpfeuffer** [comment]
Another suggestion would be to only read the "scores" when the string is empty or the user_param associated with it is not found.

**Comment by lars20070** [comment]
+1 @jpfeuffer And properly documented in the description.

**Comment by hendrikweisser** [comment]
> Another suggestion would be to only read the "scores" when the string is empty or the user_param associated with it is not found.

This is how it's already implemented. With the current default, it should work correctly out-of-the-box for the most common use cases. 

> And properly documented in the description.

The documentation already says "if available". In my opinion it is properly documented.

**Comment by lars20070** [comment]
@jpfeuffer @hendrikweisser FYI, here a comparison on the HEK LN1 dataset.

XTandem + Fido:    1,061 proteins
MSGF+ + Fido:    1,100 proteins

I expected a larger improvement, but guess the coverage will be better.

**Comment by jpfeuffer** [comment]
Have you tried ConsensusID to combine the scores? Could be worth a try.

**Comment by hendrikweisser** [comment]
@lars20070:
> XTandem + Fido: 1,061 proteins
> MSGF+ + Fido: 1,100 proteins
> I expected a larger improvement, but guess the coverage will be better.

This looks like it worked properly now. What's different from before, when you made the statement below?

> Despite higher number of peptide hits with MSGF+, Fido gets 40% less proteins than with XTandem.

**Comment by lars20070** [comment]
For the start, these are good protein number. Also in comparison with other tools. We are in the same ballpark.

TPP/X!Tandem    894 proteins
MaxQuant 1.4.1.2    926 proteins

But so far, only 450 of the 1,061 proteins can be quantified. This is despite a similar number of identified and quantified peptides.

FFMulti/X!Tandem    2,866 annotated peptides
MaxQuant 1.4.1.2    2,822 annotated peptides

I am now checking whether all of this is explained by the fact that we use only unique peptides for protein quantification, see #1210. (Note that none of the above is double checked.)

**Comment by oliverschilling** [comment]
Hello Hendrik & Co - some time ago we started to discuss which peptides should and could be used for protein quantitation ( https://github.com/OpenMS/OpenMS/issues/1210). If I understand correctly, Openms presently uses only unique peptides for protein quantitation. I consider it highly important to also have the option of including shared peptides. TPP does not automatically reject shared peptides for quantitation and MaxQuant actually allows to specify is shared peptides should be included. 

With this in mind, I would like to repeat that OpenMS urgently needs the ability to define which peptides (unique, shared, razor etc) are included for quantitation. Is it possible to include this option?

Thanks a lot!

Oliver

**Comment by lars20070** [comment]
The run time of Fido is somewhat disappointing. Here some results from our tests on our Windows server.

6-fraction sample searched with MSGF+  -->  Fido run time: 14:14 hours
11-fraction sample searched with MSGF+  -->  Fido run time: 11:16 hours
11-fraction sample searched with X!Tandem  -->  Fido run time: 9:53 hours

**Comment by jpfeuffer** [comment]
Hmm. Well, it is a computationally expensive approach.
The runtime (kind of) depends on the size of the connected components (CC). You can have a look at the sizes with the new code I introduces.
Nonetheless, Fido has a built in tweak that sets shared peptides with low probability to 0 to remove connections as an approximation. You can do that by limiting the maximal allowed size of subgraphs (i.e. set -log2_states to a value < 18).

**Comment by lars20070** [comment]
Based on three tests, the reported protein scores range from 0 to 0.04 with 70-80% of them 0. The score is not of much use to differentiate between proteins. @jpfeuffer Do you also see this in your Fido tests?

The number of peptides for each protein should also appear in the TextExporter output of idXML.

**Comment by timosachsenberg** [comment]
@lars20070 
"The number of peptides for each protein should also appear in the TextExporter output of idXML."
Did you check if this is exported by the MzTabExporter? MzTab has dedicated columns for this.
Anyway - I think less work should be spent on the TextExporter as MzTab is better suited for this in my view.

**Comment by lars20070** [comment]
+1 That will ensure more stable post-processing scripts.

The MzTabExporter output only contains meta data (MTD) and peptides (PSM), and no proteins (PRT). There are no flags in MzTabExporter. Did I miss something, or new issue?

**Comment by timosachsenberg** [comment]
ok might be that I removed this on the specification change between 0.9 and 1.0. I will try to add this in the near future.

**Comment by hendrikweisser** [comment]
Since there was no update to this discussion in almost five years, I'm going to close the ticket.
