### ISSUE TITLE
optimise FDR filtering of peptide hits

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1117]
Filtering identical X!Tandem search results for the same FDR, TPP and OpenMS report very different number of peptide hits. In this https://github.com/OpenMS/OpenMS/issues/1095#issuecomment-67474282 example, the number of unique 1% FDR peptide hits differs by about a factor 3.

Consequently, OpenMS reports far fewer proteins at the same FDR.

**Comment by hendrikweisser** [comment]
In the example you linked, who's correct? What's the fraction of decoy peptides that score above the threshold corresponding to "1% FDR" (as determined by OpenMS/TPP)?

**Comment by hendrikweisser** [comment]
Lars pointed out over the phone that the difference could come from a rescoring of the PSMs by PeptideProphet, so both FDR calculations could be correct.

**Comment by lars20070** [comment]
A way forward would be to follow the 85 missing Ctsd PSMs. (= 96 - 11) https://github.com/OpenMS/OpenMS/issues/1095#issuecomment-66917676 We know for sure that Ctsd is in the sample. These PSMs are therefore most likely TPs. Could be an error on my part, a bug in our code or simply due to better scoring in TPP.

**Comment by hroest** [comment]
would it be possible to import the TPP scoring to test that hypothesis? I
thought there should be a pep xml importer ?
