### ISSUE TITLE
labelled data analysis with ProteinQuantifier

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1132]
Currently, any consensus features annotated with two or more different peptide sequences is ignored by the ProteinQuantifier and does not contribute to the final protein list.

In the example below shows two light peptide IDs and one heavy ID mapped to a quantified peptide pair. The lysine in VMLGETNPADSKPGTIR is in two cases dimethyl-labelled with +28Da and once with +34Da. The sequences differ and the entire consensus feature is therefore ignored.

![vmlgetnpadskpgtir](https://cloud.githubusercontent.com/assets/6149805/5660020/4bcbdd5e-971b-11e4-92c3-fe6eccb900a6.png)

**Comment by lars20070** [comment]
Let's consider the case that the mapped IDs in the above example differ not only in mod/label but also in amino acid sequence. IMO, even in this case the consensus feature should not be ignored, but the ID with the highest score been used.

**Comment by hendrikweisser** [comment]
> Let us consider the case in which the mapped IDs in the above example differ not only in mod/label but also in amino acid sequence. IMO, even in this case the consensus feature should not be ignored, but the ID with the highest score been used.

There already exists a TOPP tool, IDConflictResolver, that does exactly that. Unfortunately it's currently not referenced in the ProteinQuantifier documentation. If you want to always use the single highest-scoring annotation of a feature (or consensus feature), you can just apply IDConflictResolver before ProteinQuantifier.

My proposal for the problem with labeled data would be to add a parameter "remove_mods" to IDConflictResolver, that allows the user to specify a list of modifications (like the lists of fixed/variable modifications used in search engine adapters) that should be ignored, i.e. removed from all IDs. In Lars' example above, that would be the two dimethyl labels. (Although that would make it impossible to distinguish a totally unmodified version of the peptide from a modified one. Problem?)

I personally prefer the conservative approach of ProteinQuantifier to not use features with conflicting annotations. (Which can be circumvented by applying IDConflictResolver beforehand.) However, I'm open to a discussion of whether that should be changed, i.e. whether ProteinQuantifier should include the functionality of IDConflictResolver by default. Any more opinions on this?

**Comment by lars20070** [comment]
Thanks @hendrikweisser. The IDConflictResolver resolves the problem. Then I agree with your conservative approach.

remove_mods could be advanced and list by default many of the standard labels (SILAC, dimethyl, etc). This way the labelling methods needs to be specified in only two places (search engine, feature finder).

In our dimethyl workflows, we always run two separate searches with fixed labels. Hence in our analyses, there never are unmodified peptides. So no problem.

**Comment by timosachsenberg** [comment]
Hi,
good idea. I would call the list: quantification_mod which is the modification introduced by the quantification reagent in mzTab. Just copy over the parts from the other search engine adapter. I would not hard code standard labels at this point but we might think about this in the future.

**Comment by lars20070** [comment]
Why again do we need the list quantification_mod in IDConflictResolver? Say VMLGETNPADSK(Dimethyl)PGTIR at RT = 1701s has the highest score of the three in the above example. Then the standard IDConflictResolver removes the other two IDs. For ProteinQuantifier it is enough that a single sequence is mapped to the peptide pair.

**Comment by timosachsenberg** [comment]
If that is the case then it seems sufficient.

**Comment by hendrikweisser** [comment]
The additional parameter in IDConflictResolver would allow to disregard annotation conflicts caused by labeling mods ("expected" conflicts), but still keep conflicts caused by genuinely different peptides that are mapped to the same feature. If your attitude is: "If I can't be sure which of several peptides produced a feature, I don't want to use that feature for quantification", then this would make sense.

However, since there doesn't seem to be high demand for this functionality, I wouldn't bother adding it before the coming release.

**Comment by lars20070** [comment]
@hendrikweisser Doesn't FileFilter id:keep_best_score_id the same as IDConflictResolver?

**Comment by hendrikweisser** [comment]
> Doesn't FileFilter id:keep_best_score_id do the same as IDConflictResolver?

I don't know. If it does, which of the two came first, and which should be removed/kept?

**Comment by timosachsenberg** [comment]
I like to have it in IDConflictResolver.  As we have seen. there might be more advanced ways to resolve conflicts in various settings so I guess this is to much for FileFilter.

**Comment by lars20070** [comment]
+1 It's too hidden in FileFilter and difficult to find.

**Comment by hendrikweisser** [comment]
I agree, but I think it also makes sense to have the basic functionality in FileFilter - it is a filtering operation, after all. We could keep both, but aim to avoid code duplication, i.e. move the filtering function to the library if it isn't there already.
