### ISSUE TITLE
SmallMoleculeMzTabReader broken due to MzTab specification changes

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1134]
I'm currently updating the mzTab output of AccurateMassSearch and will provide a test file to adapt SmallMoleculeMzTabReader in GKN. When I'm done I will add a link to the file here.

**Comment by timosachsenberg** [comment]
https://gist.github.com/timosachsenberg/f236d1c3c64d274433b1
I'm currently preparing the pull request so stay tuned :)

**Comment by timosachsenberg** [comment]
At some point the test data that gave rise to the example needs to be updated as it stores inchies instead of inchi keys - but that is currently not validated by our MzTab reader anyways

**Comment by aiche** [comment]
@timosachsenberg it seems like the given mzTab file is not valid. According to mzTab standard 6.3.9 `search_engine_score[1-n]_ms_run[1-n]` must be defined in the meta data section but isn't. Any plans to fix this on the OpenMS side? if so we could utilise the jMzTab library for parsing.

**Comment by timosachsenberg** [comment]
hi @aiche It is not mandatory in Summary files so the mzTab should be valid

**Comment by aiche** [comment]
should be fixed and be available in the next nightly build. two questions remain 

1. `retention_time` is a DoubleList in mzTab so it is still parsed as string
1. `best_search_engine_score[1-n]` and `search_engine_score[1-n]_ms_run[1-n]` are listed as `ParameterList`. What can we expect here?

**Comment by timosachsenberg** [comment]
Hi,
1. This is a bit unfortunate and should be usually only one representative double value. I guess it is ok if we can convert the string  to a double value in KNIME later. Does KNIME offer this functionality?
2. is a mistake in the specification. It is a Double now. I will report this as an issue.

**Comment by timosachsenberg** [comment]
I reported the issue on the mzTab page:
https://code.google.com/p/mztab/issues/detail?id=22&thanks=22&ts=1421600874

**Comment by aiche** [comment]
`best_search_engine_score[1-n`] and `search_engine_score[1-n]_ms_run[1-n]` are now also recognised as double by the reader. @timosachsenberg could you verify that the new reader works as expected together with `AccurateMassSearch` with the upcoming nightly build?

**Comment by timosachsenberg** [comment]
Will do. Thanks alot!

**Comment by FabianAicheler** [comment]
In Knime with nghtly OpenMS:
ERROR	 SmallMoleculeMzTabReader      	 Execute failed: Invalid MzTab file: Invalid entry in small molecule header: Expected 'unit_id' but got 'chemical_formula'

**Comment by aiche** [comment]
Could you try the new MzTabReader

**Comment by timosachsenberg** [comment]
I can't find it I have OpenMS 2.0.0.201501171432 installed (but  also OpenMS	1.11.1.201501182243). Could this be the Problem?

**Comment by aiche** [comment]
Please update your knime installation. Current trunk is at `de.openms_2.0.0.201501201945` and `de.openms.knime.mzTab_0.1.0.201501182243`

**Comment by timosachsenberg** [comment]
I use KNIME community contributions (nightly build) from http://tech.knime.org/update/community-contributions/trunk and we both can't update to this version (KNIME is KNIME 2.11.1)

Newest is (for both Fabian and me)     OpenMS	2.0.0.201501171432

**Comment by aiche** [comment]
I just checked the knime jenkins and it seems like the last community trunk build was done on January 18. I will contact the knime guys and report back.

**Comment by aiche** [comment]
please retry now, update site got rebuild

**Comment by FabianAicheler** [comment]
MzTabReader seems to be working (or at least finishes in knime and returns output), however the SmallMoleculeMzTabReader is still part of the OpenMS nodes and would have to be removed.

**Comment by aiche** [comment]
As soon as we declare the new one as working and OpenMS 2.0 is released I will mark the old SMMzTabReader as deprecated.

**Comment by timosachsenberg** [comment]
I closed the issue as we are now testing MzTabReader
