### ISSUE TITLE
incorrect pepXML import

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1138]
The IDFileConverter does not import the peptide-protein mappings correctly.

For example, in this pepXML [1] the peptide MGESDDSILR is correctly associated with a single protein, P63220. In the corresponding idXML [2] the peptide MGESDDSILR is mapped to PH_0 = P23588 (which does not contain the sequence) and PH_1463 = P63220 (which does).

MGESDDSILR   -->  PH_0 = P23588
MGESDDSILR   -->  PH_1463 = P63220

Here [3] the link to the complete Dropbox. Despite same IDs, same inference and many peptide quants, there are fewer proteins in LN1.csv than in interact.prot.csv. I try to figure out why.

[1] https://www.dropbox.com/s/fq3j4q2zkrjtrpp/interact.pepXML
[2] https://www.dropbox.com/s/dxj6wguf4hpn24n/interact.pep.idXML
[3] https://www.dropbox.com/sh/bmfpru4kk23frqs/AADPZEhmaPDzV9V_BQQEDMVpa

**Comment by timosachsenberg** [comment]
Having a quick look at the idXML file, 1203 peptide hits are mapped to PH_0. This seems fishy.

**Comment by lars20070** [comment]
Non-fatal error while loading '/Users/lars/Desktop/interact.pepXML': Modification '147.0354' is not uniquely defined by the given data. Using 'Oxidation (M)' to represent any of 'Oxidation (M), oxidation to L-methionine sulfoxide (M), oxidation to L-methionine (R)-sulfoxide (M), oxidation to L-methionine (S)-sulfoxide (M)'.
Non-fatal error while loading '/Users/lars/Desktop/interact.pepXML': Cannot parse modification of unknown amino acid ''
Non-fatal error while loading '/Users/lars/Desktop/interact.pepXML': Modification '156.1263' is not uniquely defined by the given data. Using 'Dimethyl (K)' to represent any of 'Dimethyl (K), Delta:H(4)C(2) (K), Ethyl (K)'.
<Non-fatal error while loading '/Users/lars/Desktop/interact.pepXML': Cannot parse modification of unknown amino acid ''> occurred 13092 times
Non-fatal error while loading '/Users/lars/Desktop/interact.pepXML': Modification '147.0354' is not uniquely defined by the given data. Using 'Oxidation (M)' to represent any of 'Oxidation (M), oxidation to L-methionine sulfoxide (M), oxidation to L-methionine (R)-sulfoxide (M), oxidation to L-methionine (S)-sulfoxide (M)'.
Non-fatal error while loading '/Users/lars/Desktop/interact.pepXML': Modification '29.0392' is not uniquely defined by the given data. Using 'Dimethyl (N-term)' to represent any of 'Dimethyl (N-term), Delta:H(4)C(2) (N-term), Ethyl (N-term), Ethyl (C-term)'.
Non-fatal error while loading '/Users/lars/Desktop/interact.pepXML': Cannot parse modification of unknown amino acid ''

There is a problem recognising the mods. @oliverschilling Why the extra proton in 29.0392 instead of 28.0313 for light dimethylation?

**Comment by timosachsenberg** [comment]
Quick update:
For MGESDDSILR 
After import of the pepXML in IDFileConverter, there are two PeptideIdentifications with one hit each. Both are referencing the correct Protein  sp|P63220|RS21_HUMAN
https://gist.github.com/timosachsenberg/e3e0aece53c14be7c845
So I guess there must be a problem during storing...

**Comment by timosachsenberg** [comment]
The problem seems to be related to multiple runs stored in one idXML. The peptide MGESDDSILR is found two times in each run. Both are correctly annotated as sp|P63220|RS21_HUMAN but mapping to the id (PH_XXX) doesn't work properly in the first run.

**Comment by lars20070** [comment]
The pepXML is based on two X!Tandem searches with fixed dimethylation light and heavy respectively. So the first MGESDDSILR has a light dimethylation at the n-Term, the second a heavy at the n-term.

**Comment by timosachsenberg** [comment]
I see. I guess the problem is that pepXML removes duplicated protein entries. Does anybody know if it would be ok to remove duplicates on a run level here (i.e. for every ProteinIdentification object separatly)

See pepXMLFile at around line 600:
```
    // clean up duplicate ProteinHits in ProteinIdentifications:
    // (can't use "sort" and "unique" because no "op<" defined for ProteinHit)
    for (vector<ProteinIdentification>::iterator prot_it = proteins.begin();
         prot_it != proteins.end(); ++prot_it)
    {
      set<String> accessions;
      // modeled after "remove_if" in STL header "algorithm":
      vector<ProteinHit>::iterator first = prot_it->getHits().begin();
      vector<ProteinHit>::iterator result = first;
      for (; first != prot_it->getHits().end(); ++first)
      {
        String accession = first->getAccession();
        bool new_element = accessions.insert(accession).second;
        if (new_element) // don't remove
        {
          *result++ = *first;
        }
      }
      prot_it->getHits().erase(result, first);
    }
```

**Comment by hendrikweisser** [comment]
@timosachsenberg: I think you're right and this has to be done per run. Can you try it and see if tests break?

**Comment by timosachsenberg** [comment]
Ok the code above was correct. But I now found the real problem: 
There are two runs in the pepXML. Both are have the search engine "X! Tandem" in their 
```
<search_summary base_name="c:/Inetpub/wwwroot/ISB/data/user-data/Lars/20141217_tMS2_tests/TPP/LN1/H_LN1" search_engine="X! Tandem" precursor_mass_type="monoisotopic" fragment_mass_type="monoisotopic" search_id="1">

<search_summary base_name="c:/Inetpub/wwwroot/ISB/data/user-data/Lars/20141217_tMS2_tests/TPP/LN1/H_LN1" search_engine="X! Tandem" precursor_mass_type="monoisotopic" fragment_mass_type="monoisotopic" search_id="1">
```

We do the mapping of peptides to proteins according to this identifier. As a result peptides from the second run are also mapped to the first run - but the first run doesn't contain the proteins (which is correct, I checked it again) so PH_0 gets assigned.

Question is how to solve this. The identifier is generated by the search engine name + date. I think we could make the identifier in line 1102 unique.
```
// generate identifier from search engine and date:
prot_id_ = search_engine_ + "_" + date_.getDate();
```

Any ideas?

**Comment by hendrikweisser** [comment]
Hm. There's already some code in IDMerger to make unique identifiers (by increasing the timestamp). Part of the problem is that the identifier isn't stored in the idXML (I think there's a long-standing ticket for that), which is why either the search engine or the date have to be made unique.

**Comment by timosachsenberg** [comment]
Is there a problem if I just append a unique id?

**Comment by hendrikweisser** [comment]
Actually, why do both searches have the same timestamp? Shouldn't they have run consecutively?

**Comment by timosachsenberg** [comment]
Timestamp in pepXML is only a date down to the day.

prot_id_ = search_engine_ + "_" + date_.getDate() + "_" + String(UniqueIdGenerator::getUniqueId());
seems to solve the problem.

**Comment by hendrikweisser** [comment]
> prot_id_ = search_engine_ + "" + date.getDate() + "_" + String(UniqueIdGenerator::getUniqueId());

How does that appear in the output idXML? What happens when that file is read again?

**Comment by hendrikweisser** [comment]
You might run into the same problem again the next time the file is read.

**Comment by timosachsenberg** [comment]
Good point. Same problem occurs. I think the problem is, that the error is on the side of the pepXML producer. I can find no information that allows to distinguish both runs.

**Comment by timosachsenberg** [comment]
For @lars20070 
as a quick hack you can change the search engine name into something unique in the pepXML file:
```
<search_summary base_name="c:/Inetpub/wwwroot/ISB/data/user-data/Lars/20141217_tMS2_tests/TPP/LN1/H_LN1" search_engine="X! Tandem" precursor_mass_type="monoisotopic" fragment_mass_type="monoisotopic" search_id="1">

<search_summary base_name="c:/Inetpub/wwwroot/ISB/data/user-data/Lars/20141217_tMS2_tests/TPP/LN1/H_LN1" search_engine="X! Tandem" precursor_mass_type="monoisotopic" fragment_mass_type="monoisotopic" search_id="1">
```
e.g. the second "X! Tandem" to "X! Tandem2"

**Comment by lars20070** [comment]
You can use the base_name. H_LN1 and L_LN1.
TPP requires two (identical) mzXML files with different names for the two search runs.

**Comment by hendrikweisser** [comment]
@timosachsenberg:
> I think the problem is, that the error is on the side of the pepXML producer. I can find no information that allows to distinguish both runs.

If that file was written by the TPP, then the format is pretty much by definition correct. We need to figure out how to read it.

You could add some seconds to the date to make a unique timestamp - zero for the first run, one for the second, etc.

**Comment by timosachsenberg** [comment]
This doesn't solve the problem as  I also need to modify the e.g. search engine name in this case.

**Comment by hendrikweisser** [comment]
> This doesn't solve the problem as I also need to modify the e.g. search engine name in this case.

Why? I thought `prot_id_ = search_engine_ + "_" + date_.getDate();` has to be unique.

**Comment by lars20070** [comment]
The two runs can be distinguished by the file base name. Why not that?

**Comment by timosachsenberg** [comment]
Making prot_id_ unique, leads to a idXML with the correct content. Rereading the idXML reintroduces the bug as the identifier is not stored in idXML.

**Comment by hendrikweisser** [comment]
> Rereading the idXML reintroduces the bug as the identifier is not stored in idXML.

I think if you make `date_` unique, it should work, because that is stored in the idXML (and used to construct the identifier).

> The two runs can be distinguished by the file base name. Why not that?

Because that won't work once the data is in idXML format.

**Comment by timosachsenberg** [comment]
Yes that is the other option - I don't really like it because it is a hack but I guess we should use it.
```
prot_id_ = search_engine_ + "_" + date_.getDate();
```

**Comment by timosachsenberg** [comment]
Yes that is probably the best option... though it is a hack. We need to store the date_ with higher resolution and just set the seconds to the count of "search_summary" nodes encountered.

**Comment by timosachsenberg** [comment]
The issue mentioned above: https://github.com/OpenMS/OpenMS/issues/70

**Comment by lars20070** [comment]
I did the "X! Tandem 2" hack that @timosachsenberg  suggested. The number of proteins in the ProteinQuantifier output increased from 322 to 692 (compared to 894 in TPP).

**Comment by lars20070** [comment]
Small correction. In TPP, only 782 of the 894 proteins report a fold change.

Comparing 692 proteins from OpenMS with 782 from TPP, we are at 88.5%. After replacing X!Tandem by MSGF+/Percolator, we should report roughly 25% more proteins. (0.885*1.4 = 1.24) Assuming Fido can reproduce the same or similar protein inference results.

**Comment by timosachsenberg** [comment]
Is this difference because of different X!Tandem parameters?

**Comment by lars20070** [comment]
No. - Both TPP and OpenMS results are based on identical IDs and inference from pepXML and protXML. The differences are due to peptide quantification (FFMulti) and protein quantification (ProteinQuantifier).

**Comment by lars20070** [comment]
Cannot parse modification of unknown amino acid ''
Modification ... is not uniquely defined.

The warnings I posted above remain. Any comments? Are the mods really that close in mass? 10E-5

**Comment by lars20070** [comment]
The protein group [P68363,Q9BQE3] is a good example for the differences. OpenMS reports plenty of peptide quants [4]. But the sequences differ minimally (see last line of sequence) and hence neither of the two proteins is quantified.

>sp|P68363|TBA1B_HUMAN Tubulin alpha-1B chain OS=Homo sapiens GN=TUBA1B PE=1 SV=1
MRECISIHVGQAGVQIGNACWELYCLEHGIQPDGQMPSDKTIGGGDDSFNTFFSETGAGK
HVPRAVFVDLEPTVIDEVRTGTYRQLFHPEQLITGKEDAANNYARGHYTIGKEIIDLVLD
RIRKLADQCTGLQGFLVFHSFGGGTGSGFTSLLMERLSVDYGKKSKLEFSIYPAPQVSTA
VVEPYNSILTTHTTLEHSDCAFMVDNEAIYDICRRNLDIERPTYTNLNRLISQIVSSITA
SLRFDGALNVDLTEFQTNLVPYPRIHFPLATYAPVISAEKAYHEQLSVAEITNACFEPAN
QMVKCDPRHGKYMACCLLYRGDVVPKDVNAAIATIKTKRSIQFVDWCPTGFKVGINYQPP
TVVPGGDLAKVQRAVCMLSNTTAIAEAWARLDHKFDLMYAKRAFVHWYVGEGMEEGEFSE
AREDMAALEKDYEEVGVDSVEGEGEEEGEEY
>sp|Q9BQE3|TBA1C_HUMAN Tubulin alpha-1C chain OS=Homo sapiens GN=TUBA1C PE=1 SV=1
MRECISIHVGQAGVQIGNACWELYCLEHGIQPDGQMPSDKTIGGGDDSFNTFFSETGAGK
HVPRAVFVDLEPTVIDEVRTGTYRQLFHPEQLITGKEDAANNYARGHYTIGKEIIDLVLD
RIRKLADQCTGLQGFLVFHSFGGGTGSGFTSLLMERLSVDYGKKSKLEFSIYPAPQVSTA
VVEPYNSILTTHTTLEHSDCAFMVDNEAIYDICRRNLDIERPTYTNLNRLISQIVSSITA
SLRFDGALNVDLTEFQTNLVPYPRIHFPLATYAPVISAEKAYHEQLTVAEITNACFEPAN
QMVKCDPRHGKYMACCLLYRGDVVPKDVNAAIATIKTKRTIQFVDWCPTGFKVGINYQPP
TVVPGGDLAKVQRAVCMLSNTTAVAEAWARLDHKFDLMYAKRAFVHWYVGEGMEEGEFSE
AREDMAALEKDYEEVGADSADGEDEGEEY

[4] https://www.dropbox.com/sh/y2y9g6e23jrk6la/AADfrTAtQJJLfaErvUSxqEO5a

**Comment by lars20070** [comment]
[P50502] is in a protein group of its own. Plenty of OpenMS peptide quants [5]. But not reported by ProteinQuantifier.

[5] https://www.dropbox.com/sh/ewz7qk37gldeip6/AACFu6HDndhFq1OVDxo267JMa

**Comment by hendrikweisser** [comment]
> Cannot parse modification of unknown amino acid ''
> Modification ... is not uniquely defined.
> The warnings I posted above remain. Any comments? Are the mods really that close in mass? 10E-5 Da

I don't see the problem. Is it not clear what the warnings are saying? You can check Unimod for the mass shifts, if you want.

**Comment by lars20070** [comment]
The mods are fine. I checked.

But the unknown amino acid '' I still do not understand.

**Comment by timosachsenberg** [comment]
I will take a look at it.
Might be related how pepXML encodes terminal amino acids:
```
<!--X! Tandem n-terminal AA variable modification-->
<terminal_modification terminus="n" massdiff="34.0632" mass="35.0711" protein_terminus="N" variable="N"/>
<terminal_modification terminus="c" massdiff="0.0003" mass="17.0031" protein_terminus="N" variable="N"/>
<terminal_modification terminus="n" massdiff="42.0106" mass="77.0817" protein_terminus="N" variable="Y" symbol="^"/>
```

**Comment by hendrikweisser** [comment]
Lars, if you want me to look at any ProteinQuantifier examples, I need all the inputs and all the outputs of that ProteinQuantifier run.

**Comment by timosachsenberg** [comment]
Yep, seems to be the case. 
```
Non-fatal error while loading 'interact.pepXML': Cannot parse modification of unknown amino acid '', delta mass: 34.0632 mass: 35.0711 variable: 0 terminus: n description:
<Non-fatal error while loading 'interact.pepXML': Cannot parse modification of unknown amino acid '', delta mass: 0.0003 mass: 17.0031 variable: 0 terminus: c description: > occurred 2981 times
<Non-fatal error while loading 'interact.pepXML': Cannot parse modification of unknown amino acid '', delta mass: 28.0314 mass: 29.0392 variable: 0 terminus: n description: > occurred 2981 times
```

**Comment by lars20070** [comment]
@hendrikweisser Here [6] the consensusXML after IDConflictResolver and [7] the idXML from protXML. These are the two inputs to ProteinQuantifier. - Guess P68363 and P50502 gonna be my last questions in this thread.

[6] https://www.dropbox.com/s/djjpdngxcc2x0hq/LN1_afterIDConflictResolver.consensusXML
[7] https://www.dropbox.com/s/v8lebxv7dngmuj2/interact.prot.idXML

**Comment by timosachsenberg** [comment]
Hi, anybody have an idea what this could be:
```
<terminal_modification terminus="c" massdiff="0.0003" mass="17.0031" protein_terminus="N" variable="N"/>
```
It's a fixed modification with delta mass of 0.0003 which is less than an electron mass by the way?

**Comment by oliverschilling** [comment]
Hi - mass="17.0031" refers top the C-terminal addition of OH upon tryptic digestion. See also "http://www.thegpm.org/TANDEM/api/pcctmc.html". Should actually be 17.00305... 

Does that help?

Oliver

**Comment by timosachsenberg** [comment]
Thank you Oliver. So I guess this might be an artefact of X!Tandem using a slightly different mass for the OH-group. I try to remove these modifications and see if that solves the problem in the files.

**Comment by hendrikweisser** [comment]
> The protein group [P50502, Q8IZP2] is based on the following peptides.
> P50502 = AIDLFTDAIK + AIEINPDSAQPYK + EWVESMGGK + LQKPNAAIR + QDPSVLHTEEMR
> Q8IZP2 = AIDLFTDAIK + AIEINPDSAQPYK + LQKPNAAIR
> EWVESMGGK and QDPSVLHTEEMR were quantified [5]. Why is P50502 not in the ProteinQuantifier output?

There's another protein in the group, "sp|Q8NFI4|F10A5_HUMAN". The two proteins you mentioned are shared between P50502 and Q8NFI4 - so no unique peptides for P50502. (This is very obvious in the peptide-level output of ProteinQuantifier, by the way.)

**Comment by hendrikweisser** [comment]
> The protein group [(P68363,Q9BQE3),A6NHL2] is based on the following peptides. (P68363,Q9BQE3) are indistinguishable. A6NHL2 has only a single peptide in common with the other two.
> P68363 = AVFVDLEPTVIDEVR + DVNAAIATIK + EDAANNYAR + EDMAALEK + IHFPLATYAPVISAEK + LISQIVSSITASLR + NLDIERPTYTNLNR + QLFHPEQLITGK + TIGGGDDSFNTFFSETGAGK + VGINYQPPTVVPGGDLAK
> A6NHL2 = EDAANNYAR
> Many peptides of (P68363,Q9BQE3) were quantified [4]. Why no fold change for (P68363,Q9BQE3) in the ProteinQuantifier output?

There are no quantified peptides that are unique to P68363 and Q9BQE3 (i.e. shared between them, but not with another protein). Again, easy to see in the peptide-level output.

**Comment by lars20070** [comment]
AVFVDLEPTVIDEVR in (P68363,Q9BQE3)?

**Comment by hendrikweisser** [comment]
> AVFVDLEPTVIDEVR in (P68363,Q9BQE3)?

Also shared with "sp|Q71U36|TBA1A_HUMAN".

**Comment by lars20070** [comment]
Ok. That answers my last question. AVFVDLEPTVIDEVR is unique within its group, but not globally unique. Thanks @hendrikweisser.

@oliverschilling would like the option to quantify based on shared peptides too. Could you add such a flag in ProteinQuantifier?

**Comment by hendrikweisser** [comment]
> @oliverschilling would like the option to quantify based on shared peptides too. Could you add such a flag in ProteinQuantifier?

What do you mean by "quantify based on shared peptides"? Just ignore that those peptides are shared and treat them like unique peptides, using their full intensities for quantification? I think it would be quite incorrect to do that, so I'd be opposed to adding such a flag to ProteinQuantifier. But maybe I misunderstand what you and Oliver are after?

**Comment by lars20070** [comment]
Currently, neither A, B or C in (f) are quantified since they are shared.

But given an 'Occam flag' is set, protein A could be quantified. That's the simplest explanation given 1, 2, 3 and 4. B and C remain unquantified.

![peptidegroupingscenarios](https://cloud.githubusercontent.com/assets/6149805/5804340/751d933a-a005-11e4-8d7f-67708302d603.png)

**Comment by oliverschilling** [comment]
Lars' feature request for an occam flag is really important. He points out an important issue and we have had long discussions about this. I fully support this feature request - thanks a lot in advance! Oliver
