### ISSUE TITLE
Peptide-protein mapping should be imported from protXML.

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1139]
Currently, only the protein grouping information such as [P22392, P15531, O60361] are imported from protXML.

The peptide-protein mappings from inference are not imported. 
P22392 = DRPFFPGLVK + GDFCIQVGR + NIIHGSDSVK + QHYIDLK + SCAHDWVYE + TFIAIKPDGVQR + VMLGETNPADSKPGTIR
P15531 = EHYVDLK + GDFCIQVGR + NIIHGSDSVESAEK + TFIAIKPDGVQR + VMLGETNPADSKPGTIR
O60361 = DRPFFPGLVK + GDFCIQVGR + NIIHGSDSVK + QHYIDLK + SCAHDWVYE + VMLGETNPADSKPGTIR

An important part of the protein inference information is therefore missing.

**Comment by lars20070** [comment]
@hendrikweisser This is just a comment on the discussion we had on the phone today.

Let x be a peptide sequence in proteins A and B. Now assume the inference algorithm decides to map x only to B and place the protein in a group of its own. (Possible, right?) The peptide x is therefore unique in the group [B] and can contribute to its quantification. But only the grouping [B] and not the mapping x --> B is read from protXML. How should the ProteinQuantifier know to use x only for the quantifcation of B but not A?

**Comment by hendrikweisser** [comment]
> Now assume the inference algorithm decides to map x only to B and place the protein in a group of its own. (Possible, right?)

I can't see how that could be considered correct. For that, the inference algorithm would have to rule out that A (in your example) is present in the sample, and I don't think that's possible.

**Comment by jpfeuffer** [comment]
Neither do I. When two proteins share a peptide and this peptide was identified with a certain probability, despite other possible unique peptides, none of those proteins should reach a probability of zero and therefore be "ruled out" of the mapping.

**Comment by lars20070** [comment]
Ok. If A and B share x, does that strictly imply that they are in the same protein group [A, B, ...]? I do not say A is absent (A could have further peptides y and z.), only that A and B could potentially be in different groups [A, ...] and [B, ...]. In this case, I would expect x to be used for the quantification of either [A, ...] or [B, ...] not both.

Anyhow, I will close the issue if this information from protXML is not needed.

**Comment by hendrikweisser** [comment]
> If A and B share x, does that strictly imply that they are in the same protein group [A, B, ...]?

I'm not sure, that depends on the ProteinProphet algorithm. Probably not.

> In this case, I would expect x to be used for the quantification of either [A, ...] or [B, ...] not both.

By default, I would expect that shared peptides can't be used for quantification at all. (Although there are exceptions: Shared between indistinguishable proteins, or in labeled experiments where there might be ways to resolve contributions from different proteins...)

**Comment by lars20070** [comment]
@hendrikweisser Let us delay this discussion until #1138 is fixed and the peptide-protein mappings from pepXML are correct. Then we can discuss specific proteins and protein groups from the LN1 dataset [1].

[1] https://www.dropbox.com/sh/bmfpru4kk23frqs/AADPZEhmaPDzV9V_BQQEDMVpa

**Comment by lars20070** [comment]
@hendrikweisser If protein grouping information [A, B, C] is imported from protXML, how do you report protein groups in the ProteinQuantifier output? A, B and C will be quantified by their unique peptides, hence have different fold changes. So A, B, and C cannot be reported in the same line.

**Comment by hendrikweisser** [comment]
@lars20070: ProteinQuantifier only supports groups of indistinguishable proteins, who all have the same "unique" (unique to the group) peptides.

Groups of distinguishable proteins could in my opinion only be quantified based on peptides that all grouped proteins share (at least in the label-free setting, which ProteinQuantifier is based on), but this is not implemented at the moment. An open question would be how to handle potential protein groups like this (A/B/C proteins, 1/2/3 peptides):

```
    1   2   3
A   x   x
B       x   x
C   x       x
```
One possibility would be to only quantify a group of two proteins based on one shared peptide, in this example, and not quantify the third protein.

**Comment by lars20070** [comment]
Peptides need to be globally unique, not merely unique within a single protein group, in order to contribute to the quantification of proteins, see https://github.com/OpenMS/OpenMS/issues/1138#issuecomment-70503225

As far as I have tested, the ProteinQuantifier output reflects correctly the pepXML and protXML from the input.
