### ISSUE TITLE
AccurateMassSearch errors (KNIME, probably also outside)

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#1178]
a) HMDB2StructMapping.tsv went missing from OpenMS/share/OpenMS/CHEMISTRY/
Is at least not in the current nightly build for KNIME. This file is essential for the AMS.

b) With manual addition (and formatting to the new HMDB:HMDB ids) of this file I got errors concerning
HMDB entries with Cs atoms (and other rare atoms):

Error: Unable to read file ('Cs' found. Please use only valid element identifiers or modify share/OpenMS/CHEMISTRY/Elements.xml! in: Unknown element 'Cs')]

So I guess some new more stringent tests were included in the AMS. The question would be whether to remove the tests, the invalid HMDB entries, or whether to add Cs and other rare atoms to element.xml

c) Another error occured if the same HMDB ID/line occurred multiple times in my own HMDB2StructMapping.tsv. Probably also a new stringent test?

**Comment by timosachsenberg** [comment]
a) @FabianAicheler can you check if this file was ever part of an official release. 
b and c) @cbielow does this ring a bell?

**Comment by cbielow** [comment]
checking....

Am 1/21/2015 um 4:15 PM schrieb Timo Sachsenberg:

**Comment by FabianAicheler** [comment]
It's part of of de.openms.win32.x86_64_1.11.1.201411121323 in the FULL KNIME installation.
(Also PositiveAdducts, NegativeAdducts, HMDBMappingFile

**Comment by cbielow** [comment]
> or whether to add Cs and other rare atoms to element.xml

+1 to that
Everything else is a hack. And yes, some parts of AMS rely on EmpiricalFormula now to ensure consistency and also speedup (compared to the implementation before).

**Comment by cbielow** [comment]
> c) Another error occured if the same HMDB ID/line occurred multiple times in my own 
> HMDB2StructMapping.tsv. Probably also a new stringent test?

Yes. The danger here was that identical ID's have different values. If need be, one could also check for identical values and allow the duplication if everything is identical. But in general, the database should be corrected, instead of the tool IMHO.

**Comment by timosachsenberg** [comment]
@FabianAicheler  what is the state of the duplicate entries? are they present in the HMDB we ship or is this your custom HMDB? Can you track down the duplicates so we can update the DB for the release

**Comment by timosachsenberg** [comment]
should be fixed with the recent merges
