### ISSUE TITLE
../share/OpenMS/PIPELINES/ 

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#1193]
.. is underpopulated (#files = 1). Workflows are scattered.

**Comment by mwalzer** [comment]
my suggestion:
- drop /share/OpenMS/PIPELINES/
- move completely to KNIME pipelines (majority is there anyways I guess)
- move these pipelines to knime://EXAMPLES/ - there is already a directory 099_community

@aiche I guess that knime://EXAMPLES/ would be publicserver.knime.org:47037 is that possible?

**Comment by aiche** [comment]
In theory we could deposit a small number of examples on the public knime server. But I think we can't put a lot of workflows there.

**Comment by mwalzer** [comment]
well, for a nice outfit, say fitting our tutorial, we do not need many.
basics, id, labelfree, qc, pyopenms, swath. Correct? 
How complicated would that be?

**Comment by aiche** [comment]
we should discuss this with the KNIME people

**Comment by hendrikweisser** [comment]
The "PIPELINES" directory has been removed. Closing this issue.
