### ISSUE TITLE
KNIME MzTabReader cant read AMS output, AMS output has to be fixed for this

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#1197]
Result from AMS  (OpenMS	2.0.0.201501221958) MzTabReader cant read AMS output:

SML	--dummy--	null	-	-	--dummy--	1.#QNAN	84.9600099846904	0	60.6279080416212	null	null	HMDB	3.5	null	[, , AccurateMassSearch, ]	null	null	null	156.123001098633	0	0	1.#QNAN	-	-1	2

'dummy' has to be replaced with 'null'
'1.#QNAN' has to be replaced with 'null'

**Comment by timosachsenberg** [comment]
"-" has to replaced by null too
charge 0 has to be replaced by "null"
I will take a look at it
