### ISSUE TITLE
Win installer wants to install to OpenMS-head directory

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1208]

**Comment by jpfeuffer** [comment]
This is because it was built from the head of develop. The installer adds the version to the Install folder.
This should change when built from the master/release branch.

**Comment by cbielow** [comment]
https://github.com/OpenMS/windows-installer/blob/master/OpenMS_installer.nsi 
defines the install directory as:
InstallDir "$PROGRAMFILES32\OpenMS-${VERSION}"

So whatever you set as VERSION (usually in https://github.com/OpenMS/windows-installer/blob/master/Cfg_Version.nsh) will be used.

Close?
