### ISSUE TITLE
Occam protein quantification in ProteinQuantifier

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1210]
Currently, ProteinQuantifier is very restrictive and bases its quantification on unique peptides only. Using all peptides, unique and shared, is clearly too lenient. This feature request suggests to make use of some of the shared peptides.

Nesvizhskii et al. [1] discusses possible protein group configuartions. In (f), ProteinQuantifier does currently not report fold changes for either A, B or C. All peptides 1, 2, 3 and 4 are shared. We suggest a new Occam flag. When this flag is set, ProteinQuantifier should quantify A based on the fold changes of 1, 2, 3 and 4. B and C will not be quantified. If say peptide 3 appears also in another protein group, it will not be used for the quantification of A.

[1] A. I. Nesvizhskii et al. (2005) Interpretation of shotgun proteomic data: the protein inference problem. MCP 4(10), 1419.

![classificationproteingroups](https://cloud.githubusercontent.com/assets/6149805/5898553/d189f096-a550-11e4-8402-d1917bfc1df4.png)

**Comment by Stortebecker** [comment]
+1. This would be comparable to TPPs ProteinProphet.

**Comment by lars20070** [comment]
MaxQuant provides three options for protein quantification:

(1) unique
(2) unique + razor (default)
(3) all

ProteinQuantifier should provide the same options and leave it to the user to choose.

**Comment by lars20070** [comment]
Protein quantification mode "greedy" as discussed with our group in Freiburg.
![screen shot 2015-04-15 at 14 19 22](https://cloud.githubusercontent.com/assets/6149805/7158457/9869ae74-e37a-11e4-8412-2ea698cbac81.png)

**Comment by lars20070** [comment]
Resolved by #1358.
