### ISSUE TITLE
OpenMS 2.0.0 RC1 win64 missing LICENSE file

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#1214]
On win7 VM, no LICENSE file installed

**Comment by timosachsenberg** [comment]
most likely applies to 32bit to

**Comment by jpfeuffer** [comment]
That's right. Currently only License.txt is shown before installing. How about including the contents of LICENSE (full BSD) into License.txt (short description of BSD + Thirdparty licenses) and then just show License.txt when installing?

**Comment by timosachsenberg** [comment]
+1

**Comment by timosachsenberg** [comment]
This would basically replace:
```
OpenMS is released under a 3 clause BSD license.
The respective license file can be found in the LICENSE file
```
at the top of the License.txt by the actual license (as in LICENSE).
The LICENSE file will be kept, of course.

**Comment by timosachsenberg** [comment]
@jpfeuffer what is the status here
