### ISSUE TITLE
IDs should be assigned to sub-features of a ConsensusFeature.

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1216]
Currently, IDs are assigned to the entire ConsensusFeature, not the individual sub features. In the case of label-free data, it is no longer clear which map the ID came from. In the case of isotopically labelled data, it is no longer clear if the ID was mapped to the light or heavy partner.

Consider a triple dimethylation experiment with the labels +28Da, +32Da and +36Da. The peptide feature detection identified many triplets [light, medium, heavy], but also a couple of doublets and singlets. Then IDs were mapped to these multiplets. Now the doublets and singlets need to be filled up with zero-intensity-peptide-features before being passed (now all of them triplets) to the ProteinQuantifier. If say a medium ID (+32Da) was mapped to the "light" partner of a +4Da doublet, the doublet needs to be extended to the left i.e. [0, "light", "heavy"]. If the medium ID was mapped to "heavy", the doublet needs to extended to the right i.e. ["light","heavy", 0]. (This is the job of a small MultiplexResolver tool I am working on.)

Is there a hack to assign IDs to the individual sub-features of a consensus using our existing data structure?

**Comment by timosachsenberg** [comment]
Hi Lars, do you mean the option:
```
  -consensus:use_subelements   Match using RT and m/z of sub-features instead of consensus RT and m/z. A consensus feature matches if any of its sub-features matches.
```
does only annotate the ConsensusFeature but not the sub features?

**Comment by timosachsenberg** [comment]
why do you need the extra tool for the zero intensites? Couldn't you just do it in the FF? He knows about the labeling channels.

**Comment by timosachsenberg** [comment]
```
 for (ConsensusFeature::HandleSetType::const_iterator it_handle = map[cm_index].getFeatures().begin();
                 it_handle != map[cm_index].getFeatures().end();
                 ++it_handle)
            {
              if (isMatch_(rt_pep - it_handle->getRT(), mz_pep, it_handle->getMZ())  && (ignore_charge_ || ListUtils::contains(current_charges, it_handle->getCharge())))
              {
                was_added = true;
                if (mapping[cm_index].count(i) == 0)
                {
                  map[cm_index].getPeptideIdentifications().push_back(ids[i]); /// <---- add userparam with handle to id here and use this information to resolve channel ambiguity
                  ++assigned[i];
                  mapping[cm_index].insert(i);
                }
                break; 
              }
```

**Comment by timosachsenberg** [comment]
AFAIK we can't annotate the sub features as these are only FeatureHandles. A quick solution would be to store the map index of the sub element in the identification.

**Comment by lars20070** [comment]
+1 as discussed with @timosachsenberg on the phone.

The new MultiplexResolver tool will then use the map index from the peptide identification.

**Comment by hendrikweisser** [comment]
@lars20070:
> Now the doublets and singlets need to be filled up with zero-intensity-peptide-features before being passed (now all of them triplets) to the ProteinQuantifier.

Why is that necessary? If there are missing features in some sub-maps, isn't the missing value already represented as zero?

**Comment by timosachsenberg** [comment]
As I understood it, the specific labeling doesn't allow to distinguish light + middle and middle + heavy pairs so an additional tool is needed to add a zero intensity to the heavy or light channel respectivly.
Adding of the zero intensity needs to be done based on the id. Same holds for singlets.

**Comment by lars20070** [comment]
As @timosachsenberg explained, the situation is unlike label-free where you know exactly which map the feature is coming from. If my FFMulti tool detects a +4Da doublet, it is still unclear whether this is the [light, medium] or the [medium, heavy] part of a triplet.

**Comment by lars20070** [comment]
@hendrikweisser I won't need to add new zero-intensity-peptide-features. But I will need to assign the correct map indices, [1,2] or [2,3] to the existing doublet.
