### ISSUE TITLE
OpenMS 2.0.0 RC1 win64 SuperHirn.dll missing

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#1217]
SuperHirn.dll wasn't found by OpenMS FeatureFinderSuperhirn (also not installed as far as I see).

(SuperHirn.dll was included in the KNIME update package for this Windows VM)

**Comment by timosachsenberg** [comment]
sorry I don't understand. It is not included in the nightly installers? What do you mean with KNIME update package?

**Comment by aiche** [comment]
`SuperHirn.dll` is missing here, https://github.com/OpenMS/windows-installer/blob/master/OpenMS_installer.nsi#L250 . @jpfeuffer this will break the old master/1.12 builds that are still running on scratchy.

**Comment by FabianAicheler** [comment]
"What do you mean with KNIME update package?" Just wanted to differentiate for possible problem sources: No .dll with the normal OpenMS installer (the standalone, outside KNIME), but the nightly installation in KNIME contains it.

**Comment by timosachsenberg** [comment]
ok added the file in: https://github.com/OpenMS/windows-installer/commit/f6b83c51974ed1428ee49614f5589c414412712b

**Comment by timosachsenberg** [comment]
fixed in current nighlties
