### ISSUE TITLE
Moving average for MS1 spectra in SpectraMerger

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1221]
The SpectraMerger tool can already sum subsequent MS1 spectra of an LC-MS experiment. But that reduces the number of spectra. SpectraMerger should also allow for a moving average of 3, 5 or 7 etc. MS1 spectra leaving the number of spectra constant.

Such a signal processing step should improve the performance of all OpenMS feature finder tools. RT profiles will be smoothed, isotope patterns in m/z will be clearer.

**Comment by hroest** [comment]
Is there any evidence in the literature that this would actually help the feature finder? Did somebody try this before? we have a function in OpenSWATH that does this but it didnt really help as far as I can remember but that might also be due to the special data we had.

**Comment by lars20070** [comment]
During beta testing we came across some low intensity peptides in QExactive data. In individual MS1 spectra some important isotopic peaks are missing. But combining three subsequent spectra would give us a very clear and complete isotope pattern. At least in this test dataset, the problem was rather common.

**Comment by timosachsenberg** [comment]
Would it be also possible to do this without filtering. e.g. add an option to only look for the peak one spectrum above or below if it is missing the peak in the current spectrum? That way intensities of good features are not disturbed by a global filtering.

**Comment by lars20070** [comment]
Yes. It is of possible. Which of these two options is best we could only find out after comparing both implementations.

I still would go for moving average preprocessing. Not on every dataset, but only where this problem occurs.

**Comment by hroest** [comment]
Seems like a smoothing operation in rt to me, so moving average is one idea
but maybe a Gaussian window might also be an idea to try. Anyways sounds
like a cool feature, looking forward to an implementation

sent from my smartphone -- you may keep any typos you find.
On Feb 4, 2015 2:21 PM, "Lars Nilse" <notifications@github.com> wrote:
>
> Yes. It is of possible. Which of these two options is best we could only
find out after comparing both implementations.
>
> I still would go for moving average preprocessing. Not on every dataset,
but only where this problem occurs.

**Comment by lars20070** [comment]
+1

The pull request should also include a Gaussian window averaging. As said above, I would like to put this  extension into SpectraMerger instead of just FeatureFinderMultiplex. I see this as a signal preprocessing step for many tools.

**Comment by hroest** [comment]
I agree, this could be useful for multiple tools so I support an
independent processing step as you suggested

sent from my smartphone -- you may keep any typos you find.

**Comment by lars20070** [comment]
Could the SpectraMerger be moved from File Handling to Signal Processing?

**Comment by hroest** [comment]
sure, makes more sense to me. Go ahead!
