### ISSUE TITLE
KNIME MapAlignerPoseClustering turns featureXML input into mzml

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#1222]
breaks our workflows. same as with mzid/idxml output.

**Comment by timosachsenberg** [comment]
what do you mean by "turns featureXML input into mzml"?

**Comment by mwalzer** [comment]
what it says, featureXML as input, output mzml (as opposed to expected featureXML output)

**Comment by mwalzer** [comment]
KNIME MapAlignerPoseClustering has output types options, default is set to mzML.
