### ISSUE TITLE
X!Tandem parameter file for X!Tandem adapter

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1234]
The current XTandemAdapter contains the complete set of parameters of the X!Tandem search engine. 

The default_input_file should be replaced by an optional in_tandem_params. If this optional input is specified, all other parameter settings are ignored and the parameters from this tandem.params file used instead.

**Comment by oliverschilling** [comment]
that would be a very useful feature; it would also help with the portability of existing workflows.

**Comment by algom** [comment]
+1 Very useful feature

**Comment by jpfeuffer** [comment]
+1 Indeed. You mean like allowing the user to specify only a subset of parameters and use a standard input for the rest?

**Comment by lars20070** [comment]
Nope.

Either (a) no in_tandem_params is specified and all parameters come from the XTandemAdapter interface. Or (b) a in_tandem_params file is specified and all parameters come from that xml file. No subset, no partial override. Either (a) or (b).

**Comment by Stortebecker** [comment]
+1, like I already commented here: https://github.com/OpenMS/OpenMS/issues/1095#issuecomment-72919252

**Comment by timosachsenberg** [comment]
@lars20070  state?

**Comment by lars20070** [comment]
Resolved in #1684.
