### ISSUE TITLE
bug in KNIME-node for IDFilter - maxLength only negative

### ISSUE THREAD

**Issue by julianu** [OpenMS/OpenMS#1235]
In the IDFilter node for version 1.11.1.201501182243 (is this the currently stable version?) the max_length parameter value range is [-inf:0]. I think this should be rather [0:inf].

**Comment by timosachsenberg** [comment]
yep. it seems to be a bug. I will fix it for the release

**Comment by timosachsenberg** [comment]
ok fixed it in #1237

**Comment by timosachsenberg** [comment]
Hi Julianus,
can you confirm from the nihtly builds that this is fixed?

**Comment by timosachsenberg** [comment]
KNIME seems to be behind our nightlies

**Comment by aiche** [comment]
@timosachsenberg the KNIME build server is currently down. I post an update here as soon as I have news from the KNIME guys.

**Comment by timosachsenberg** [comment]
can you gently poke them again?

**Comment by timosachsenberg** [comment]
fixed in current KNIME nightlies
