### ISSUE TITLE
KNIME-IDFilter: is it expected that blacklisted peptides filter on modifications, not sequence-only

### ISSUE THREAD

**Issue by julianu** [OpenMS/OpenMS#1236]
The used workflow is following:
First I have a peptide-identification. The resulting idXML is passed to to IDExtractor to get the best identifications. Aferwards, i want to get rid of these best identifications in the original idXML and use IDFilter for it, using the IDExtracor results as blacklist (port 2 in KNIME). But after filtering, I still have (differently modified) peptides of the best-ones in my idXML.
It is unclear from the documentation, if this is the desired outcome.

**Comment by timosachsenberg** [comment]
Hi @julianu 
Thanks for the report. So I guess we should rephrase the description and add a flag to overwrite the default behaviour.
```
-blacklist:peptides <file>          Peptides having the same sequence and modification assignment as any peptide in this file will be filtered out. Use with blacklist:ignore_modification flag to only compare by sequence.

-blacklist:ignore_modifications          Compare by sequence only.
```

**Comment by julianu** [comment]
Yes, sounds great!
