### ISSUE TITLE
KNIME OpenMS 2.0.0.201502031718 MzTabReader writes '?' instead 'null'

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#1238]
Writes '?' instead 'null' for:

taxid
best_search_engine_score[1]
search_engine_score[1]ms_run[1]

**Comment by aiche** [comment]
`?` is the KNIME representation of an unknown value

**Comment by timosachsenberg** [comment]
ok then it seems exactly what we want :+1:
