### ISSUE TITLE
FileInfo: memory usage reported correctly?

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1252]
FileInfo reports the memory it used after reading a file. In the case of a huge mzML file (22 GB on disk), it said:
"Mem Usage while loading: 27984 MB"
I executed this FileInfo job on our LSF cluster, which also logs the memory usage. It said:
"Max Memory :             53713 MB"
This is almost twice what FileInfo reported! Running the job with 30 GB max. memory led to a crash, indicating that indeed more memory was needed, and that there's a bug in the memory estimation in FileInfo.

**Comment by cbielow** [comment]
Mem usage is reported right after loading the file.
After that, FileInfo potentially does some other processing (collection 
of stats etc).
What happens if you

exit(0);

right after the memory usage is reported?!


Am 2/11/2015 um 3:35 PM schrieb hendrikweisser:

**Comment by hroest** [comment]
I have noticed problems with memory size as well. It seems that the total memory size that we use is actually wrong on a Linux system. Total memory size may include the mapped memory, therefore any file that is currently open will get counted too. See also here

http://stackoverflow.com/questions/1558402/memory-usage-of-current-process-in-c

I needed to get accurate memory usage for a project where I measured the memory usage of some XML parsers in OpenMS. You can have a look here where I implemented the suggested memory usage code from stackoverflow in OpenMS:

https://github.com/hroest/OpenMS/commit/ce7c90e48c685764f2e9430472bb8d3e8cd87a3c

maybe you can try this patch and see whether the reported values make more sense?

**Comment by hroest** [comment]
maybe we should consider porting this patch to here - for me this was much more accurate as it reported the "resident" size in memory: https://github.com/hroest/OpenMS/commit/ce7c90e48c685764f2e9430472bb8d3e8cd87a3c

**Comment by jpfeuffer** [comment]
@cbielow You were looking for more exact peak memory usage, too, right?

**Comment by cbielow** [comment]
yep. For Windows, this is solved now in #2861: it reports "working set" and "peak working set", and matches exactly what the Windows Task Manager is reporting.
As Hannes said, there are a hundred ways you can look at memory consumption, but this seems like a nice solution (at least for the benchmarks im running).
However, getting peak memory usage on Linux seems a little bit more complicated... sometimes even impossible.

**Comment by hroest** [comment]
I have been using https://github.com/hroest/OpenMS/commit/ce7c90e48c685764f2e9430472bb8d3e8cd87a3c for my PLOS One paper and that matches pretty well with what `top` is reporting

**Comment by timosachsenberg** [comment]
has been added at some point by chris
