### ISSUE TITLE
IsobaricAnalyzer produces features with zero intensity

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1258]
I've analyzed some TMT-6plex data with IsobaricAnalyzer. For some reason, almost half of the detected features (10504 out of 21112) have zero intensity - in the overall consensus feature and in each of the six channels. That doesn't make sense to me.

(@cbielow: Do you know why that happens?)

**Comment by timosachsenberg** [comment]
Maybe @aiche knows about this

**Comment by hendrikweisser** [comment]
Ah, it seems that IsobaricAnalyzer produces one consensus feature per MS2 spectrum, irrespective of whether any reporter ion intensity could actually be detected in the spectrum.

Somewhat confusingly, the tool writes a message like this to the log:
> IsobaricQuantifier: skipped 10504 of 21112 selected scans due to lack of reporter information:
> IsobaricQuantifier: channels with signal
>       channel 126: 7677 / 21112 (36%)
>       [...and so on for the other channels...]

The "skipped" features still appear in the output, however.

There are already parameters available to set a reporter ion intensity threshold:
- min_reporter_intensity: Minimum intensity of the individual reporter ions to be used extracted. (default: 0)
- discard_low_intensity_quantifications: Remove all reporter intensities if a single reporter is below the threshold given in min_reporter_intensity. (default: false)

I cannot set "discard_low_intensity_quantifications" because I expect zero intensities in some of the channels for some peptides. I'm not sure yet if "min_reporter_intensity" has any effect without "discard_low_intensity_quantifications" - it does not seem to remove any features, but it might change the quantification.

**Comment by hendrikweisser** [comment]
@timosachsenberg: I think you closed this prematurely. I would remove the "major" label, but I still think reporting all-zero features is misleading. At least the documentation should be extended, but in addition to that I would like an option to remove all-zero features (which maybe should even be the default behavior).

**Comment by timosachsenberg** [comment]
I agree with you that default behaviour should be to not report those features and offer an option to still report them (e.g. it is done in AccurateMassSearch that way). I just closed if for convenience. I will open a new issue with a title describing the task that should be peformed.
