### ISSUE TITLE
IsobaricAnalyzer: Refactor handling of 0 intensity channels

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1260]
see also: https://github.com/OpenMS/OpenMS/issues/1258#issuecomment-74483691

**Comment by hendrikweisser** [comment]
There's an unrelated warning produced by IsobaricAnalyzer that could be fixed together with this:
> ConsensusXMLFile::store():  found 1 invalid unique ids

**Comment by hendrikweisser** [comment]
I've fixed the warning in #1269. The actual issue here is still open. Until it gets fixed, a work-around is to filter out zero-intensity features with FileFilter by setting a minimum intensity ("int" parameter).

**Comment by jpfeuffer** [comment]
I agree that would be helpful.

**Comment by jpfeuffer** [comment]
I saw that something even annotates "all_empty". It would be one line, to remove them.

**Comment by jpfeuffer** [comment]
@timosachsenberg Would it make sense to additionally remove a channel completely if its intensity is zero to create "missing values"?

**Comment by timosachsenberg** [comment]
at the level of each consensus feature? Yes, I think these could be removed.
Removing "all_empty" consensus features also sounds like a good idea. I would like to have some second opinion on that.

**Comment by hendrikweisser** [comment]
In my opinion the "all_empty" consensus features should be removed.

Individual channels with zero intensity should stay, because "zero" is the actual readout for those channels.

**Comment by cbielow** [comment]
if all_empty means neither ID nor any kind of quant in any channel, then yes: kick it.
I would vote against single channels which are 0. This information is actually useful.

**Comment by hendrikweisser** [comment]
> I would vote against single channels which are 0.

"Vote against" having them or removing them? (I assume removing.)

**Comment by cbielow** [comment]
> 
> 
> > I would vote against single channels which are 0.
> 
> "Vote against" having them or removing them? (I assume removing.)

fixed my wording.
`I would keep single channels which are 0`

**Comment by timosachsenberg** [comment]
me too
