### ISSUE TITLE
change -fasta to -database in all tools

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1264]
Currently database input to tools are specified with -fasta or -database. It would be more consistent to use only -database instead.

**Comment by mwalzer** [comment]
This would be a nice consistency indeed, and nice if you would find time for this and the subsequent testing of all workflows.

**Comment by hendrikweisser** [comment]
How about "db" instead of "database"? It's shorter and just as clear.

**Comment by timosachsenberg** [comment]
Would have been a nice idea for the 2.0 release but as it breaks any workflow using one of those nodes without pressing need it is a thing for the 3.0 release I guess.

**Comment by timosachsenberg** [comment]
And I don't think that db is just as clear for a new user.

**Comment by lars20070** [comment]
+1 for -database

**Comment by mwalzer** [comment]
:+1:  ->3.0 
:+1:  for -fasta everywhere 
-db could be anything e.g. .dat - which we afaik do not support

**Comment by hendrikweisser** [comment]
I'm against "-fasta", because the parameter is for the protein *database*, and it doesn't really matter that it has to be in FASTA format (the file format restriction takes care of that). In MascotAdapter(Online), for example, you specify the database by name, and don't actually pass a FASTA file.
