### ISSUE TITLE
filter for protein accessions in IDFilter

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1268]
Using the IDFilter one can filter for peptide IDs of specific proteins

IDFilter -whitelist:proteins xyz.fasta

where the xyz.fasta file contains all proteins of interest. For each specific protein a new fasta file needs to be generated. It would be more convenient to simply specify the protein accessions as in

FileFilter -id:accessions_whitelist

**Comment by zonlai** [comment]
this feature would be particularly useful when checking a long list of proteins, and would save a lot of time

**Comment by lars20070** [comment]
Resolved by #1346.
