### ISSUE TITLE
Windows linking problem with boost and TopPerc

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#1272]
After moving TopPerc to Utils in this commit
https://github.com/OpenMS/OpenMS/commit/6c8862f43b9af7765de4789d422772c5a264a800,
TopPerc fails during linking with the error here: http://cdash.openms.de/viewBuildError.php?buildid=121414.
As you can see in https://github.com/OpenMS/OpenMS/pull/1270 removing certain boost calls didn't help. 

On the other hand I found a "hack" how to make the linking work again.

Somehow, cmake tries to automatically find the boost library, whose name it constructs out of the VS version it was compiled with and the boost version (like libboost_regex-vc110-mt-1_52.lib).
However the libs in the contrib on the build machines are named like libboost_regex-mt.lib.
Usually this is fine when you specify the contrib path during configuration but not in this case?!
Not after moving TopPerc to UTILS.
Now, if I set the preprocessor macro BOOST_ALL_NO_LIB, the linking works again.
I neither don't know why exactly this solves the problem and why it occured here, nor if it makes sense to include this preprocessor macro everytime. If so, I also have no clue where in the cmake scripts this would go.
Maybe @cbielow can comment on this? Help would be kindly appreciated.

**Comment by cbielow** [comment]
As soon as you include a boost header, boost will by default make the linker add some boost libs, whose name its somewhat guessing -- i.e. what you would get if we'd build a default boost with no fancy options (i.e. not what we are doing the contrib).
So boost gets the lib names wrong, hence the linker cannot find them. The macro BOOST_ALL_NO_LIB gets rid of this behaviour, but in turn expects you to tell the linker what libs to use --- but for that we have Cmake after all.

OpenMS lib and TOPP have
add_definitions(/DBOOST_ALL_NO_LIB)
somewhere defined (do a ```git grep DBOOST_ALL_NO_LIB``` to see where).

So the easiest solution is to
add_definitions(/DBOOST_ALL_NO_LIB)
to src\utils\CMakeLists.txt (compare src\topp\CMakeLists.txt).

**Comment by jpfeuffer** [comment]
Yep, this solves the problem. Thanks a lot for clarifying. I am surprised that I was actually close to solving the problem. This means, before TopPerc was moved, probably no other tool in UTILS included boost, so this was not necessary?
Await commit...
