### ISSUE TITLE
extending initiator methionine rule

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1274]
The initiator methionine cleavage rule states that N-terminal methionine can be cleaved by the ubiquitous methionine aminopeptidase (MAP). Consequently even tryptic digests can contain semi-tryptic peptides. OpenMS takes this rule into account.

In a tryptic E. coli digest I have seen cases in which not one but two N-terminal amino acids are missing. For example, the proteotypic peptide

LAQEIIR

is part of P07650 with the sequence

MFLAQEIIR...

The two amino acids MF instead of just M were cleaved. The X! Tandem search result contains five further proteotypic peptides of P07650

DENNWQEAAK
YLPTAMLTK
EAVQFLTGEYR
LGDQVDGQRPLAVIHAK
DITATVDSIPLITASILAK

which suggests that LAQEIIR is real. X! Tandem is using an extended initiator methionine rule taking not just one but the first few amino acids into account. Here a reply from Ron Beavis.

"By default X! Tandem checks for the removal of the first few residues of the protein sequences that begin with M to fix up the fact that FASTA files don't have enough nuance to record whether the M has been removed and record any raggedness/acetylation caused during the process. If you want to disable this checking, you have to set the "protein, quick acetyl" parameter to "no" (it is "yes" by default). On the web interface, it is the radio button beside "Protein N-terminal acetylation". Normally, 2-3% of identified spectra will be missed if you disable this feature."

The effect is very small but, as the P07650 example suggests, real. We might want to extend the rule in OpenMS in order not to lose these semi-tryptic peptides in tryptic digests.

**Comment by hendrikweisser** [comment]
Which tool in OpenMS does this affect? XTandemAdapter or PeptideIndexer?
If it's PeptideIndexer, can you avoid the problem by setting "enzyme:specificity" to "none" (i.e. "trust the search engine")?

**Comment by cbielow** [comment]
Am 3/2/2015 um 3:30 PM schrieb hendrikweisser:
> Which tool in OpenMS does this affect? XTandemAdapter or PeptideIndexer?

It's a missing feature in PeptideIndexer.

> If it's PeptideIndexer, can you avoid the problem by setting "enzyme:specificity" to "none" (i.e. "trust the search engine")?

While this will recover the actual N-terminal peptide in the protein of 
interest, it will also introduce false positive hits in other proteins, 
where the same sequence in present as an infix. So not an advisable 
solution, especially if you have already merged results from different 
search engines (particularly those who do not find those peptides in the 
first place).

**Comment by lars20070** [comment]
In my test dataset, 32 out of 9,937 PSMs had the N-terminal MX... sequence. In this case, 0.3% not 3% as mentioned in Beavis' email. (Very few peptides, but maybe functionally important since at the outside of the protein.) I checked some but not all 32 of them. The ones I had a closer look at were supported by other proteotypic peptides, as in the P07650 example above.

Changing the initiator methionine rule or the enzyme specificity will get us more TPs but also increase the FP rate. By how much I haven't checked yet. But I hope that changing the rule gets us fewer FPs.

**Comment by hendrikweisser** [comment]
> In my test dataset, 32 out of 9,937 PSMs had the N-terminal MX... sequence.

Just out of curiosity: For how many of those would you get "false-positive" protein associations if you used "enzyme:specificity none"?

**Comment by jpfeuffer** [comment]
This should be implemented by now.
