### ISSUE TITLE
TTD files (GenericWrapper): what's the point of "mapping" elements?

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1281]
TTD files (.ttd) mainly define a mapping between command line arguments of an external tool and parameters exposed through OpenMS. The command line is specified in the "cloptions" element (with placeholders), the exposed parameters are defined in the "ini_param" section. There is also the "mappings" section, which defines copy/move operations for files as pre-/post-conditions of command execution. "mappings" also contains "mapping" elements, which map exposed ("ini") parameters to numbers; the numbers can be referenced in "cloptions".

What is the benefit of this mapping step? Why not reference the "ini" parameters directly in the command line string? This would make it much more obvious which parameter goes where. So instead of the current:

```
<cloptions>-o "%1" "%2"</cloptions>
<mappings>
    <mapping id="1" cl="%%out" />
    <mapping id="2" cl="%%in" />
</mappings>
<ini_param>
    <ITEM name="in" value="" type="string" description="input file" tags="input file" />
    <ITEM name="out" value="" type="string" description="output file" tags="output file" />
</ini_param>
```

Why not just have:

```
<cloptions>-o "%out" "%in"</cloptions>
<ini_param>
    <ITEM name="in" value="" type="string" description="input file" tags="input file" />
    <ITEM name="out" value="" type="string" description="output file" tags="output file" />
</ini_param>
```

**Comment by cbielow** [comment]
One reason to require mappings: because they need to be reused -- see #1388 
:)
