### ISSUE TITLE
OpenSwathWorkflow error

### ISSUE THREAD

**Issue by rachelimcb** [OpenMS/OpenMS#1287]
I have the following error in processing dataset from OpenSwath Tutorial dataset. Can anyone tell me what is the problem?
Thanks!
Rachel

![openswathworkflow error on tutorial dataset](https://cloud.githubusercontent.com/assets/11286797/6456879/e53bd9ac-c1a6-11e4-84cd-d52a0f4a9309.png)

**Comment by hroest** [comment]
It seems to be a cygwin issue when converting Windows to Linux path and back, see the line `while loading /tmp/foo : unable to open primary document entity C:\openswath/tmp/foo` which is mixing Windows and Linux paths
