### ISSUE TITLE
Explicitly model enzymes in OpenMS

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1297]
Currently enzymes are not modeled as proper classes in OpenMS.
Usually strings are used instead.
see e.g.
```
const string EnzymaticDigestion::NamesOfEnzymes[] = {"Trypsin"};
const string EnzymaticDigestion::NamesOfSpecificity[] = {"full", "semi", "none"};
```

MzIdentML suggest following structure:
```
<Enzyme id="ENZ_0" cTermGain="OH" nTermGain="H" missedCleavages="1" semiSpecific="0">
    <SiteRegexp><![CDATA[(?<=[KR])(?!P)]]></SiteRegexp>
    <EnzymeName>
        <userParam name="Enzyme" value="CNBr+Trypsin"/>
    </EnzymeName>
</Enzyme>
```

The PSI ontology contains entries for several enzymes.
```
id: MS:1001251
name: Trypsin
def: "Enzyme trypsin." [PSI:PI]
is_a: MS:1001045 ! cleavage agent name
relationship: has_regexp MS:1001176 ! (?<=[KR])(?!P)
```

A potential way to model enzymes in OpenMS would be e.g.:
```
struct Enzyme 
{
  String name;
  EmpiricalFormula n_term_gain, c_term_gain;
  String site_regex;
}
```

I think this should model most enzymes of interest.

Doing the OpenMS way we could store known enzymes in a static EnzymeDB.

**Comment by hroest** [comment]
so would there be a 1:1 correspondence between PSI ontology enzymes and our objects?

**Comment by liangoaix** [comment]
Would it be possible to get enzymes directly from CV/psi-ms.odo?

**Comment by timosachsenberg** [comment]
it could be a starting point: see http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=MS&termId=MS:1001044&termName=cleavage%20agent%20details

Regular Expressions and quite some Enzymes are present in the PSI-MS obo

**Comment by liangoaix** [comment]
PSI-MS.obo has included all the digestion enzymes that present on the above webpage.  how about adding an EnzymeDB from reading  CV/psi-ms.obo, as what the ModificationDB does ?

**Comment by timosachsenberg** [comment]
Yes, I think that is in general a good idea but might pose some unwanted overhead as parsing the whole psi-ms.obo takes quite some time. @mwalzer what do you think? A bit more consistent would be to do it analogous to Elements.xml or Residues.xml in the share/CHEMISTRY folder.
For very large files we added parsing of flat csv files but as we only have a few enzymes I think xml is more appropriate.

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<PARAMETERS>
  <NODE name="Enzymes">
    <NODE name="Trypsin">
      <ITEM name="Name" value="Trypsin" type="string" />
      <ITEM name="RegEx" value="(?<=[KR])(?!P)" type="string" />
      <ITEM name="NTermGain" value="H" type="string" />
      <ITEM name="CTermGain" value="OH" type="string" />
      </NODE>
    </NODE>
```

**Comment by liangoaix** [comment]
you are right, it's not a big work of adding 20 enzymes.

**Comment by timosachsenberg** [comment]
some additional information on the pearl compatible regular expressions from the mzIdentML specification:
```
1) use the PCRE supplied negation syntax for look-ahead and look-behind
assertions and 
2) use the most compact representation possible for a regex. The start of a match specifies the
cleavage point. For example the enzyme Trypsin, which cleaves following a K or R residue unless the next residue is P, has the regular expression: (?<=[KR])(?!P)
The ?<= is a "zero-width positive look-behind assertion", and [] means one of this character set. So, this rule is to look behind for a K or R. ?! is a zero-width positive look-ahead assertion, and ?!P means any character that is  not P. 
An example of an “N-term” enzyme is Asp-N which cleaves before D or B. This can be described using the PCRE:  (?=[BD])
The ?= is a “zero-width positive look-ahead assertion.”
```

**Comment by timosachsenberg** [comment]
@liangoaix are you willing to take this task?
It would involve:
1. creating the Enzymes.xml file containing maybe 10 of the most often used enzymes.
2. creating a simple Enzyme class with Enzyme.cpp and Enzyme.h (maybe even similar to the simple struct I provided)
3. creating the EnzymesDB.cpp and EnzymesDB.h files that allow to retrieve Enzymes parsed from Enzymes.xml
4. creating the pyOpenMS pxd files
5. creating the tests for EnzymesDB and Enzyme classes

**Comment by liangoaix** [comment]
Yes, I am going to update this inside pull-request#1285.

**Comment by mwalzer** [comment]
@hroest yes, I think this would be worth aspiring
@timosachsenberg @liangoaix parsing the obo does not take long, it should be parsed anyway for most stuff. I would _not_ go the length of modeling something for ourselfs except for the object structure.

**Comment by timosachsenberg** [comment]
@mwalzer hmm PSI-MOD doesn't contain all information needed so I don't know if this is the right way to do

**Comment by timosachsenberg** [comment]
On the other hand maybe we can do without storing the information N or C term gain information.
Any experts on non-trypsin enzymes here?

**Comment by liangoaix** [comment]
so I created an enzyme.xml file as follows:
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<PARAMETERS>
  <NODE name="Enzymes">
    <NODE name="Trypsin">
      <ITEM name="Name" value="Trypsin" type="string" />
      <ITEM name="RegEx" value="(?<=[KR])(?!P)" type="string" />
      <ITEM name="RegExDescription" value="Trypsin cleaves following a K or R residue unless the next residue is P." type="string" />
      <ITEM name="NTermGain" value="H" type="string" />
      <ITEM name="CTermGain" value="OH" type="string" />
      <ITEM name="PSIid" value="MS:1001251" type="string" />
    </NODE>
    <NODE name="Arg-C">
      <ITEM name="Name" value="Arg-C" type="string" />
      <ITEM name="RegEx" value="(?<=R)(?!P)" type="string" />
      <ITEM name="RegExDescription" value="Arg-C cleaves following R residue unless the next residue is P." type="string" />
      <ITEM name="NTermGain" value="H" type="string" />
      <ITEM name="CTermGain" value="OH" type="string" />
      <ITEM name="PSIid" value="MS:1001303" type="string" />
      <NODE name="Synonyms">
        <ITEM name="Clostripain" value="Clostripain" type="string" />
      </NODE>
    </NODE>
...
```

**Comment by timosachsenberg** [comment]
nice! I think for now we should just stick with the simple solution and maybe convert it to the obo at a later point if we see benefits from it.

**Comment by liangoaix** [comment]
Except Asp-N / Asp-N_ambic cleaves at peptide bonds N-terminal, other common enzymes are all cutting at C-terminal, am I right?

**Comment by timosachsenberg** [comment]
http://www.matrixscience.com/help/enzyme_help.html has some additional enzymes that cleave at N-terminal but I don't know if we need to include them right now

**Comment by liangoaix** [comment]
thanks, I can include those present in PSI so far.

**Comment by timosachsenberg** [comment]
adressed in https://github.com/OpenMS/OpenMS/pull/1288
