### ISSUE TITLE
Third party tools are not installed by OpenMS 2.0 RC2 MacOS installer

### ISSUE THREAD

**Issue by hannesveit** [OpenMS/OpenMS#1300]
No SEARCHENGINES subfolder in OpenMS-2.0.0/TOPP (tested on MacOSX 10.8.5), empty THIRDPARTY folder.

**Comment by jpfeuffer** [comment]
Same for develop branch. I am looking into it right now.

**Comment by jpfeuffer** [comment]
Okay. Should be resolved now. I don't know what happened. Building it manually on the machine worked fine.
