### ISSUE TITLE
speed issues in indexed mzML parser

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1301]
part of the speed issue seems to us calling `offset_elems->getLength()` multiple times.

Apparently `getLength` is a rather involved operation that can be a performance issue on long lists:

https://svn.apache.org/repos/asf/xerces/c/trunk/src/xercesc/dom/impl/DOMNodeListImpl.cpp

```
// revisit
//   this implementation is too stupid - needs a cache of some kind.
//
```

-> and indeed we find that it is

**Comment by mwalzer** [comment]
:laughing: but good to know

**Comment by hroest** [comment]
I wonder why nobody bothered to implement this better ...
