### ISSUE TITLE
WIndows7 64 install Proteowizard requires MSFileReader installed (manually?)

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#1304]
(Windows 7 64 bit)
Conversion from a thermo raw file from the examples to mzML fails with

'Starting...
Opening file "C:\Users\FabianAicheler\Desktop\OpenMS Tutorial stuff\Tutorials\DataConversion\ThermoData.RAW" for read...
Failed - System.Exception: [ThermoRawFile] [RawFile::ctor] Unable to initialize XRawfile; is MSFileReader installed? Reading Thermo RAW files requires MSFileReader to be installed. It is available for download at:
http://sjsupport.thermofinnigan.com/public/detail.asp?id=703
   at pwiz.CLI.msdata.ReaderList.read(String filename, MSDataList results)
   at MSConvertGUI.MainLogic.processFile(String filename, Config config, ReaderList readers)
   at MSConvertGUI.MainLogic.Go(Config config)'

I'm not familiar what the external tools should contain, should this normally work out of the box after OpenMS install, or are people normally required to also download MSFileReader?

**Comment by FabianAicheler** [comment]
Ok, same error with the OpenMS 1.11 installation, so I guess by default people have to install MSFileReader

Failed - System.Exception: [ThermoRawFile] [RawFile::ctor] Unable to initialize XRawfile; is MSFileReader installed? Reading Thermo RAW files requires MSFileReader to be installed. It is available for download at:
http://sjsupport.thermofinnigan.com/public/detail.asp?id=703
   at pwiz.CLI.msdata.ReaderList.read(String filename, MSDataList results)
   at MSConvertGUI.MainLogic.processFile(String filename, Config config, ReaderList readers)
   at MSConvertGUI.MainLogic.Go(Config config)

**Comment by cbielow** [comment]
I would not worry about this.
The error message is pretty clear and instructive.
