### ISSUE TITLE
Wrong mass calculated for b1 ions

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1310]
The mass calculation for b1 ions (i.e. a b-ion with just one residue) seems to be off by 1 (too high), or more precisely by one proton mass. This affects `AASequence::getMonoWeight` and `AASequence::getAverageWeight`, but not `Residue::getMonoWeight` and `Residue::getAverageWeight` (as far as I can tell). Masses of longer sequences or of y-ions seem to be all correct, but I haven't checked any of the other variants (a/c/x/z/...).

Compare results from OpenMS' MassCalculator utility to the ISB's calculator: http://db.systemsbiology.net:8080/proteomicsToolkit/FragIonServlet.html

The reason for the error is that the mass calculation starts off with the masses of the protons that give the charge (e.g. https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/AASequence.cpp#L284). For peptides with several residues, this is later compensated by subtracting one hydrogen mass (https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/AASequence.cpp#L331), but for a single residue this doesn't happen (https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/AASequence.cpp#L305).

Perhaps the mass calculation code could be simplified when this gets fixed, to make sure it works correctly in all cases (e.g. in https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/AASequence.cpp#L331, first the mass of water is added, then the masses of hydroxyl and hydrogen are subtracted...).

**Comment by hendrikweisser** [comment]
This could probably be fixed by simply removing the special case for sequence length 1 (starting at https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/AASequence.cpp#L303).

**Comment by timosachsenberg** [comment]
nice catch. Any idea why anyone entered the special case for length 1?

**Comment by hendrikweisser** [comment]
> Any idea why anyone entered the special case for length 1?

I think as an optimization. For one residue you can directly get the mass of the appropriate type (e.g. ion) via `Residue::getMonoWeight`; for multiple residues, the total mass is calculated from the "internal" masses of the residues.

**Comment by mwalzer** [comment]
mh, there we go with "...optimization is the root of all evil (or at least most of it) in programming." What I wonder is, why this did not pop up in the tests.

**Comment by hendrikweisser** [comment]
@mwalzer: It should be "premature [!] optimization...", which is an important distinction.

And yes, we should make sure that this is properly covered by a test.

**Comment by hroest** [comment]
> And yes, we should make sure that this is properly covered by a test.

definitely necessary - I suggest to first write a few additional test cases also covering this case and then adopting the code to conform to the tests. Secondly, we can perform the refactoring as @hendrikweisser suggetsed

**Comment by mwalzer** [comment]
@hendrikweisser  this is why there were the '...' - because who is to decide what is premature and what not.

**Comment by timosachsenberg** [comment]
The error seems also be present for other ions
```
  // test if charged single amino acid sequences match the charged residue weight
  TEST_REAL_SIMILAR(AASequence::fromString("A").getMonoWeight(Residue::AIon, 1), 44.04947);
  TEST_REAL_SIMILAR(AASequence::fromString("A").getMonoWeight(Residue::BIon, 1), 72.04439);

  TEST_REAL_SIMILAR(AASequence::fromString("A").getMonoWeight(Residue::YIon, 1), 90.05496);
  TEST_REAL_SIMILAR(AASequence::fromString("A").getMonoWeight(Residue::ZIon, 1), 73.02900);
```

**Comment by jpfeuffer** [comment]
I created an implementation with small cleanups, but get an abs error of 0.000593 for the Z-ion in your example. What's the procedure? How much error do we allow? What causes this?

**Comment by timosachsenberg** [comment]
Hmm for single AAs there should be no numeric accumulation of errors.
Lets take a look what others predict:
http://db.systemsbiology.net:8080/proteomicsToolkit/FragIonServlet?sequence=A&massType=monoRB&charge=1&zCB=1&nterm=0.0&cterm=0.0&addModifType=&addModifVal=

from the NIST Mass and Fragment calculator software:
```
b-ion	  b(1+)   	  b(2+)   	  b(3+)   	  c(1+)   	b seq 	y-ion	  y(1+)   	  y(2+)   	  y(3+)   	  z-CID 	  z-ETD 	y seq   
 1	  -----  	  -----  	  -----  	  -----  	   	 3	  -----  	  -----  	  -----  	  -----  	  -----  
 2	 143.0815	  72.0444	  48.3654	 160.1081	AA    	 2	 161.0921	  81.0497	  54.3689	 144.0661	 145.0733	AA
 3	  -----  	  -----  	  -----  	  -----  	AAA   	 1	  90.0550	  45.5311	  30.6898	  73.0290	  74.0362	A
```

**Comment by jpfeuffer** [comment]
Yes you used that tool for the example test, right? However, in all of the ions there are numeric errors (even for a single residue).
Is residue mass calculated as sum of atom masses?

**Comment by timosachsenberg** [comment]
Yes I used the first one for the example test. The residue mass is calculated from the elemental composition.
see double Residue::getMonoWeight(ResidueType res_type) const
there we have mono_weight_ = formula_.getMonoWeight();

**Comment by jpfeuffer** [comment]
I don't know.. I checked the code multiple times. I am pretty sure that they use other masses, constants and/or consider the mass defect differently. The higher the charge, the bigger the error.

**Comment by timosachsenberg** [comment]
Hmm calculating with electrons instead of protons might be in that range of mass error. Thanks for taking a look at it. 

----- Original Message -----

**Comment by timosachsenberg** [comment]
close?

**Comment by jpfeuffer** [comment]
Yep. Although I am still of the opinion that SpectrumGenerator and AASequence could take advantage of a bigger rework. See e.g. #1685

**Comment by timosachsenberg** [comment]
good idea but maybe we need to tackle bigger (or more complex) issues like e.g. mzIdentML / small molecule support
