### ISSUE TITLE
EdwardsLippertIterator.C:134: possible wrong index in for loop ?

### ISSUE THREAD

**Issue by dcb314** [OpenMS/OpenMS#1314]
OpenMS-1.11.1/source/CHEMISTRY/EdwardsLippertIterator.C:134:34: warning: iteration 255ul invokes undefined behavior [-Waggressive-loop-optimizations]

    for (Size i = 0; i < 256; i++)
    {
      masse_[i] = source.masse_[i];
    }

but

EdwardsLippertIterator.h:    DoubleReal masse_[255];         ///< mass table

**Comment by timosachsenberg** [comment]
thanks for reporting

**Comment by hroest** [comment]
I did address this in 2bc3d1739b087c008d73b9a9fcbecc7c71cc9b36 which should resolve it. I guess the mass_ vector needs to be able to represent 8 bits as we use it as a mapping of ASCII characters to masses

however, why dont we just  use a `std::vector<double>` for this? then we should have found this when using MSVS as they do bounds check on vector

**Comment by hroest** [comment]
as we will not make  a new 1.11 release to fix this and this is already fixed in the 2.0 version, I suggest to mark it as fixed and close this in the near future

@dcb314  thanks for reporting this

**Comment by dcb314** [comment]
> with which tool did you find the issue?

gcc, the GNU C compiler.

**Comment by hroest** [comment]
not sure whether we have this turned on by default for gcc but I hoped that `-Wall -Wextra` would already do it

I added a new branch and a new travis build to see whether this flag catches more things in the code https://travis-ci.org/OpenMS/OpenMS/builds/57635293

**Comment by hroest** [comment]
not sure whether we have this turned on by default for gcc but I hoped that `-Wall -Wextra` would already do it

I added a new branch and a new travis build to see whether this flag catches more things in the code https://travis-ci.org/OpenMS/OpenMS/builds/57635293 (see also https://github.com/OpenMS/OpenMS/tree/feature/compiler_flag )
