### ISSUE TITLE
create psq files in OMSSAAdapter

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1317]
makeblast db should be called automatically if no psq, idx, etc. files are present

**Comment by cbielow** [comment]
no. please dont!
If you run multiple instances of OMSSA at once, all of them will start 
to call makeblastdb and will overwrite files etc....
The only save way is to exit with error.
Same thing for MSGF+ as discussed earlier.



Am 3/19/2015 um 10:42 AM schrieb Timo Sachsenberg:

**Comment by timosachsenberg** [comment]
couldn't we use a file lock or similar?

**Comment by cbielow** [comment]
you could, but there's so many things which can go wrong,
i.e.
- how long do you block and wait for lock release?
- what if you cannot write to the FASTA directory?
etc...
see discussion in MSGF+ thread :)

Am 3/19/2015 um 10:56 AM schrieb Timo Sachsenberg:

**Comment by timosachsenberg** [comment]
I agree. Would it hurt to have an index_create_mode option that is on "on" by default, that uses a file lock with lock release after makeblastdb process termination and which assumes that one can write to the directory? Still can fail but the amount of people already failing on OMSSA db creation might be bigger so I think it is worth to consider it.
