### ISSUE TITLE
MapAlignerPoseClustering should output statistics

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1319]
Currently its very hard to judge the quality of the alignment.
Some ideas for good statistics?
- which map has been choosen as reference map
- how many feature pairs have been matched and used in the alignment

**Comment by timosachsenberg** [comment]
as debug option: consensusXML containing the aligned features between maps would also be great

**Comment by lars20070** [comment]
Regarding a good statistics for map alignment: Look at the top 20% of features in each map and determine the median number of features per consensus.

**Comment by hroest** [comment]
or do all quantiles: 20, 40, 60, 80, 100 %, e.g. how many featuers were at least in 20% of the maps, 40% etc
