### ISSUE TITLE
Proteomic Comparison Workflow @ Freiburg

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1320]
For us in Freiburg, a stable OpenMS workflow for the analysis of SILAC and dimethyl-labeled data is of great importance. Protein identifications  with MSGF+/Fido and peptide quantifications with FeatureFinderMultiplex give us great results. But there remain a couple of unsolved issues, before we can use an OpenMS workflow for the daily analyses in our lab.
#829 protein descriptions in idXML/TextExporter and ProteinQuantifier output
#1268 a quick way to filter idXML for the peptides of specific proteins
#1210 protein quantification beyond unique peptides
#1316 export of 'protein group' and 'indistinguishable proteins' structure in both idXML/TextExporter and ProteinQuantifier

**Comment by lars20070** [comment]
While working on our workflows, we came across some further issues.

https://github.com/OpenMS/OpenMS/issues/1379 complete X!Tandem adapter (further params needed for Q Star analyses)
https://github.com/OpenMS/OpenMS/issues/1409#issuecomment-104916064 bug in MSGF+ adapter (replace tsv by mzid conversion)
https://github.com/OpenMS/OpenMS/issues/1446#issuecomment-105434137 possible bug in mzid -> idXML conversion
https://github.com/OpenMS/OpenMS/issues/1437 mzid + mzML support for IDFileConverter
https://github.com/OpenMS/OpenMS/issues/1428 IDPEP crash
https://github.com/OpenMS/OpenMS/issues/1427 ConsensusID crash
https://github.com/OpenMS/OpenMS/issues/1381#issuecomment-98085163 Fido protein score export not possible
https://github.com/OpenMS/OpenMS/issues/1031 no reliable protein sequence coverage
https://github.com/OpenMS/OpenMS/issues/1443 single protein list (both quantified and unquantified) with reason why not quantified
https://github.com/OpenMS/OpenMS/issues/1441 resolve quant/ID conflicts in multiplex experiments
https://github.com/OpenMS/OpenMS/issues/1444 script for mzTab to text conversion
https://github.com/OpenMS/OpenMS/issues/1439 pdf plots from IDPEP
https://github.com/OpenMS/OpenMS/issues/1382 fold change filter in TOPPView

**Comment by timosachsenberg** [comment]
@lars20070 can you update this issue to reflect the current state
