### ISSUE TITLE
TOPPAS failes without descriptive error message if incoming files don't match

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1321]
Forgetting to set the recycle mode for a e.g. fasta file leads to a failing pipeline without descriptive error.

ExecutePipeline contains a diagnostic message:
current dry-run state: 1
Number of rounds for incoming edges of #4 are not equal. No idea on how to combine them! Did you want to recycle this input?
Could not retrieve input files from upstream nodes...

**Comment by hannesveit** [comment]
This error message and some others are currently just written to std:cerr. Fix for release?!

**Comment by timosachsenberg** [comment]
Hmm don't think its a real blocker but has quite high prio.

----- Original Message -----
