### ISSUE TITLE
MapAlignerIdentification runs without warning on empty idXML files

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1322]

**Comment by timosachsenberg** [comment]
same for unannotated features - seems to run forever

**Comment by hendrikweisser** [comment]
I've tried this just now - MapAlignerIdentification on an empty idXML file failed with the following error: `Error: Unexpected internal error (No reference RT information left after filtering)`
Looks like the problem got solved at some point.

**Comment by timosachsenberg** [comment]
This no reference after filtering is still annoying as this also sometimes happens on non empty files
