### ISSUE TITLE
registerStringOption() to Param

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1324]
Currently, the registerStringOption() method is only available for the TOPPBase class, but not for the Param class. It would be more consistent to make this method also available in Param.

**Comment by hendrikweisser** [comment]
All of the "register...Option_" methods are specific to TOPPBase. To register a string value in Param, you use `Param::setValue(key, value, ...)` with a `value` that is a string.

**Comment by lars20070** [comment]
Thanks @hendrikweisser. But the string value should allow only for certain values ("profile", "centroid", "automatic"). Guess that can only be done with StringOption.

**Comment by hendrikweisser** [comment]
> But the string value should allow only for certain values ("profile", "centroid", "automatic"). Guess that can only be done with StringOption.

No, you can do that with `Param::setValidStrings`.

**Comment by lars20070** [comment]
You are right @hendrikweisser. Then it is not needed.
