### ISSUE TITLE
FeatureFinderMultiplex - possible error in custom label code

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1326]
Hi @lars20070 ,
I configured FFMultiplex to use 3 custom mass shifts for Arg6 Arg10 Lys4. (2,4,6 Da)
Strangely, only the 10 Da are found despite those are not present in the sample.

```
13:58:49 NOTICE: FeatureFinderMultiplex of node #4 started. Processing ...

sample 1:   Arg6 Arg10 Lys4 

mass shift 1:    0  2.0042  
mass shift 2:    0  10.021  

FeatureFinderMultiplex took 0.83 s (wall), 0.81 s (CPU), 0.02 s (system), 0.80 s (user).

```

**Comment by timosachsenberg** [comment]
Setting the mass shift to 1 still finds Arg6 labeled pairs:
![image](https://cloud.githubusercontent.com/assets/5803621/6897169/237fa13e-d6f2-11e4-8df2-861f106d707b.png)

**Comment by lars20070** [comment]
Hi @timosachsenberg, if you want to search for quadruplets with the the mass shifts 2Da, 4Da and 6Da, please use the following settings:

label: [Dimethyl0][Dimethyl4][Dimethyl6][Dimethyl8]
Dimethyl0: 0
Dimethyl4: 2
Dimethyl6: 4
Dimethyl8: 6

**Comment by lars20070** [comment]
The Arg/Lys labels are for SILAC experiments only. For missed_cleavages > 1, the possible mass shift combinations are more involved.

**Comment by timosachsenberg** [comment]
custom labels would be great, 
Still I don't get the meaning of the mass shift output - can you explain it to me?
What is special about SILAC and how does this explain the mass shifts?
