### ISSUE TITLE
Mac build error (DefaultParamHandlerDocumenter)

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1327]
After working on ConsensusID, I've been getting a strange error when trying to build OpenMS (in particular, the documentation) on my Mac (OS X 10.8.5):

> In file included from /Users/hw5/Software/OpenMS/doc/doxygen/parameters/DefaultParamHandlerDocumenter.cpp:172:
> In file included from /Users/hw5/Software/OpenMS/src/openms_gui/include/OpenMS/VISUAL/Spectrum1DCanvas.h:46:
> In file included from /Users/hw5/Software/OpenMS/src/openms_gui/include/OpenMS/VISUAL/SpectrumCanvas.h:45:
> /Users/hw5/Software/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerData.h:74:7: error: expected '}'
>       DT_UNKNOWN              ///< Undefined data type indicating an error
>       ^
> /usr/include/sys/dirent.h:126:21: note: expanded from macro 'DT_UNKNOWN'
> # define DT_UNKNOWN       0
> 
> ```
>                      ^
> ```
> 
> /Users/hw5/Software/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerData.h:68:5: note: to match this '{'
>     {
>     ^
> /Users/hw5/Software/OpenMS/src/openms_gui/include/OpenMS/VISUAL/LayerData.h:132:7: error: cannot initialize a member subobject of type 'OpenMS::LayerData::DataType' with an
>       rvalue of type 'int'
>       type(DT_UNKNOWN),
>       ^    ~~~~~~~~~~

OpenMS defines "DT_UNKOWN" as an enum value in "LayerData.h", but this conflicts with a previous macro definition in "/usr/include/sys/dirent.h"! (Although I have no idea why it would link against this file.)

I'm not getting this error on my Linux machine.

**Comment by hendrikweisser** [comment]
I have now found that the problem was caused by (indirectly) including SeqAn headers (via "SeqanIncludeWrapper.h") before "Spectrum1DCanvas.h". If I move the problematic "#include" to the bottom (after the GUI section), the conflict goes away.

**Comment by hendrikweisser** [comment]
Including any of the SeqAn headers from "SeqanIncludeWrapper.h" at the beginning of "DefaultParamHandlerDocumenter.cpp" - "seqan/index.h", "seqan/align.h" or "seqan/graph_align.h" - causes the error for me. Would be interesting if anyone else can replicate this on their Mac.

I'm closing this since I've found a work-around (moving the include to the bottom).

**Comment by hroest** [comment]
while this solves the issue I am not sure whether this requires no action. So is there actually a conflict in macros or functions?

I see that https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man5/dirent.5.html indeed defines a DT_UNKNOWN macro which will clearly lead to bad results when combined with LayerData.h https://github.com/OpenMS/OpenMS/blob/e8d0ea305916c37b624654c472afab0e47e5c4bb/src/openms_gui/include/OpenMS/VISUAL/LayerData.h 

so my suggestion is to rename the fields in in LayerData::DataType - any comments?

**Comment by cbielow** [comment]
+1 for rename

**Comment by hendrikweisser** [comment]
Is there no better solution than renaming? Namespaces, encapsulation, ...? Do we really have to ensure that none of our (top-level) identifiers are already used in some header somewhere?

**Comment by hroest** [comment]
since macros are part of the pre-processor and do not adhere to namespaces and here the macro is in the header, there is really not much we can do ..

>  Do we really have to ensure that none of our (top-level) identifiers are already used in some header somewhere?

basically yes, at least for all the headers that we pull in ourselves - but over these we have more or less control / i.e. we should know which ones these are

**Comment by hendrikweisser** [comment]
> basically yes, at least for all the headers that we pull in ourselves - but over these we have more or less control / i.e. we should know which ones these are

If by "ourselves" you mean "the OpenMS code", then "dirent.h" is actually a counter-example - it doesn't occur anywhere in our sources (according to "git grep"). It must come - directly or indirectly - from SeqAn.

> since macros are part of the pre-processor and do not adhere to namespaces and here the macro is in the header, there is really not much we can do ..

Could we add an "#ifdef/#undef" for the macro before reusing the identifier?

**Comment by hroest** [comment]
well by "ourselves" I meant direct and indirect ways (e.g. through SeqAn). However if somebody downstreams uses OpenMS + library X and finds those two are not compatible, then I would say it is not our problem. But everything that we pull in (recursively) is our problem.

> Could we add an "#ifdef/#undef" for the macro before reusing the identifier?

might be an option but I think renaming is cleaner (unless there is an important reason why we cannot change it, e.g. other ppl rely on it)

**Comment by hendrikweisser** [comment]
If we rename it, how about "DT_UNDEFINED" instead of "DT_UNKNOWN"?

**Comment by hroest** [comment]
:+1:
