### ISSUE TITLE
[BUILD] Docker integration

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1343]
Docker is nice light-weight virtualization tool that is often used on cloud / grid / cluster environments. It would be great if we could provide some ready-made images for people to use.

I started collecting some docker files here:

https://github.com/hroest/docker_files/tree/master/openms

Currently, it has a build for the dependencies, one for the lib and potentially one for all the rest. At least dependencies and library are built automatically right now, the rest should follow soon. There are several things we can do with this

(i) provide docker images for the releases, specifically Release 2.0 -- we can do this manually but it would be nice if those were available in addition to the packaged versions (that always lag behind and may not be available on all distributions and all versions of each distro

(ii) also highly interesting: we can set up docker to build a new image every time we push to a specific repo. E.g. if we place those scripts in `tools/docker/` in the main repo, we could set up docker to create a new docker image every time we push to develop. This could mean automatic deployment to linux / the cloud of the develop branch every time we push to develop! Probably we will have to fix some stuff with tags so ppl can track which version they are running and make sure we dont overload the docker servers. Alternatively, we could use a "docker repo" and push through a cron job nightly / weekly and provide fresh images of develop on a regular basis for ppl but this would for sure make deployment on Linux easier ...

**Comment by hroest** [comment]
Another option would be to use http://www.shippable.com/ for creating docker containers once we have a Dockerfile that we are satisfied with

**Comment by bgruening** [comment]
@hroest I can highly recommend the automatic build from docker hub. `develop` can become `openms/openms:dev` and stable branches can become `openms/openms:2.0`. If you are interested I have a Dockerfile for OpenMS based on an old debian Image so this binaries should be relocatable to many HPC environments.

**Comment by hroest** [comment]
@bgruening that would be great if you could share the script on gist or github somewhere. I think we really want to do this at least starting from 2.0 on and we need to discuss how much we want to include this into our continuous integration setup. If enough people are interested then we for sure can but at the moment I guess most people would already be happy to see the release versions on dockerhub?

I have set up some automatic builds with docker, the are here https://hub.docker.com/u/hroest/ and I have divided them into

- dependencies
- library
- executables

**Comment by hroest** [comment]
I have now a working 2.0 build here

https://registry.hub.docker.com/u/hroest/openms_2.0/builds_history/177361/

```

100% tests passed, 0 tests failed out of 1691

Total Test time (real) = 305.02 sec
```

sounds like a working image to me :-) the corresponding Dockerfile can be found here https://github.com/hroest/docker_files/tree/master/openms/releases/2.0

**Comment by hroest** [comment]
@bgruening @aiche @timosachsenberg  I dont know what the optimal deployment is for docker, currently all binaries are in `/openms-build/bin/` - is there a preferred way to do this for docker? We could install the libraries to `/usr/lib/` and all binaries do `/usr/bin` and then the shared files to `/usr/share` as debian does currently. However as the point of docker is not, as far as I understand it, to provide highly complex debian installs but rather "one image - one software" type. There are few things we probably would want to do, e.g. setting `ENV` and `CMD` so that ppl get dropped to a usable bash shell and have all executables in their path when they start. Then I guess it does not really matter where the build files are. We also have to think about a good `ENTRYPOINT` for the whole image, maybe even `OpenMSInfo` simply displaying some stuff about OpenMS when starting the container from scatch. The other option would be a script that gives some help on how to use the container

**Comment by bgruening** [comment]
@hroest do we have a defined target user? I assume it is a OpenMS user (not a developer) that wants to use the binaries?

The location of the binaries is not relevant at all, but we need to have a `VOLUME` defined, so the user can get the data in and out from the container. Moreover it would be nice to have the WORKDIR set to this volume.

`ENV` should at least be used to set `OPENMS_DATA_DIR`. Regarding `ENTRYPOINT` I would propose to write a small script that redirects the user to the proper Binary. If no Binary is specified we get some nice help text.

I could imagine the following to work:
`docker run openms/openms:2.0` -> prints a welcome text
`docker run -v /foo/bar/:/data/ openms/openms:2.0 FileConverter input output`

**Comment by ypriverol** [comment]
@hroest Does anybody is still working in this issue?

**Comment by hroest** [comment]
I was on vacation for a while so I did not work on it but as I understand @grosenberger has done some work with Docker.  Any updates so far from your side? Did Lorenz also have some comments?

**Comment by grosenberger** [comment]
We have worked with the docker_files from @hroest and it worked very well for us. We did not yet further investigate automated deployment.

**Comment by jpfeuffer** [comment]
I am currently in the process of trying to provide the docker images that are created during our new (not yet official) nightly Docker builds on linux.
We have a machine that provides our CI system Jenkins with as many Docker images as needed for CI or nightly builds and when finished shuts them down again.
However, I would like to publish the Docker images created that way (assuming the build was ok) so that other people can use them.
I think BioDocker would be a great place to put these images. I would want to have one image for the uptodate built contribs and at least one for the full nightly OpenMS build and one for stable OpenMS builds. Does anyone know, if this is possible with Biodocker? With whom should I talk in this regard?

**Comment by timosachsenberg** [comment]
Yasset is probably a good address.
----- Original Message -----

**Comment by bgruening** [comment]
BioDocker has already a OpenMS image:
https://github.com/BioDocker/containers/tree/master/OpenMS

Would be nice to enhance it if needed with a PR :)

**Comment by jpfeuffer** [comment]
Oh yes, I actually saw that. In short, I was mainly wondering if the Biodocker repository would also be the right place to e.g. publish also nightly builds and contrib library builds.

**Comment by bgruening** [comment]
@jpfeuffer contrib yes, nightly I don't think so. But this can be discussed in the biodocker community. Please open an issue.

**Comment by jpfeuffer** [comment]
Thanks @bgruening , sure I will. I am open for both solutions.

**Comment by hroest** [comment]
I suggest that we base our OpenMS image on the base image of biodocker, this will make it easier for us to transition once we have a release and simply upload our image to their repo. Basically, all we have to do is take the Dockerfile from https://github.com/BioDocker/containers/blob/master/OpenMS/2.0.0/Dockerfile and modify it. I have my own dockerfiles from the very beginning (see https://github.com/hroest/docker_files/tree/master/openms ) but I dont think we want to use them. 

I have also set up dockerhub to automatically build openms whenever we pushed something but their build breaks after some time since OpenMS took too long to compile. So we gave up on that but if we get a workflow going from github -> Jenkins -> dockerhub that would be great !

**Comment by FabianAicheler** [comment]
For the automated builds on dockerhub, a separation into contrib, and several build steps (as done by e,g, hannes) is necessary for the builds to succeed (afaik there is a 2 hour timeout).
However, if we really are talking about builds and not dockerfiles, I think it would be possible to push them to non-automated repositories (but they would have no validated dockerfile in dockerhub)?

I think it would be good to provide dockerfiles/images at least for biodocker.

We could also
- think about some (split up) automated builds for different linux distributions on dockerhub, in order to automate release tests. But I guess thats already part of the (internal?) CI efforts underway that Julianus talked about? So the main question would be whether we also want some publicly available proofs how to successfully install OpenMS on different distributions?
- try to optimize for size: currently public images (including the biodocker one) are above 1 gb (more like 2gb?). Then again I guess that would be mostly unneeded optimization, because multiple OpenMS instances would share the image layers? What are your feelings on the size expectations of potential Docker/OpenMS users?

Sorry if that was too much rambling^^

**Comment by hroest** [comment]
@FabianAicheler I am perfectly happy with building the images ourselves and then uploading them to dockerhub. I have done that before and it works quite well. I like it better than splitting up everything and then it still fails (as often happens on travis). 

We could think about size, is the issue some files that are not removed after compilation or packages that we install?

**Comment by FabianAicheler** [comment]
I haven't really looked into that yet for specific openms dockerfiles, it's just a commonly occuring problem of docker images and my hope would have been that room for chaining commands/joined uninstallation/squashing exists. More or less a side project I hope to look into in my free time.

**Comment by jpfeuffer** [comment]
Another way would be to release the Dockerfiles on an OpenMS git subrepository and only upload the built images to Dockerhub. Or deactivate the automated building on Dockerhub.
I will definitely look into how to push our CI or at least the nightly images there. I can easily switch the base images I am using (currently CentOS7 and Ubuntu15.04) to the BioDocker base image (or add it to the build matrix).
@FabianAicheler Yes the size reduction is of course favourable but needs quite some testing. Let me know whenever you come with something and we can include it in the scripts. For now, I will try to at least not include any garbage.

**Comment by hroest** [comment]
yes, I agree with the method to do local builds and then upload to
Dockerhub. If people dont trust our builds, they are free to download the
Dockerfiles themselves and rebuild the image. I would also de-activate the
build on dockerhub as I have fiddled with it and tried to split up the
builds in multiple parts, still I had lots of issues.

I think the BioDocker base image makes sense and aligning the community
here has some potential to have more people adopt Docker
