### ISSUE TITLE
IsobaricAnalyzer: profile or centroided data?

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1347]
The IsobaricAnalyzer documentation says the tool "extracts the isobaric reporter ion intensities from *raw* MS2 data" (emphasis mine); also the list of "potential predecessor tools" does not include a peak picker. This led me to believe that IsobaricAnalyzer was intended to work on profile (e.g. HCD fragmentation) data.

However, a colleague has now tested it on profile and centroided versions of the same data and reported strange results on the profile data. (Results on centroided data are in line with expectations.)

Does IsobaricAnalyzer need centroided data as input? If yes, this needs to be made explicitly clear (now that acquiring MS2 spectra in profile mode is becoming more prevalent).

@cbielow, can you comment?

**Comment by cbielow** [comment]
it should say centroided data

Am 4/14/2015 um 10:43 AM schrieb hendrikweisser:

**Comment by hendrikweisser** [comment]
I've extended the documentation accordingly; see #1349.
