### ISSUE TITLE
OpenMS 2.0 download zip file lacks contrib directory

### ISSUE THREAD

**Issue by Xucam** [OpenMS/OpenMS#1356]
Build instructions for linux refer to 'contrib directory at root of tar.gz (download is in fact a zip), which does not appear to exist.  Are there updated instructions for 2.0?

http://ftp.mi.fu-berlin.de/pub/OpenMS/release2.0-documentation/html/install_linux.html

Running RHEL 6.6

**Comment by hroest** [comment]
we probably should at least package the contrib git directory so that people can use cmake to download and install dependencies. so I suggest to make a new source release. what do you think?

**Comment by Xucam** [comment]
Just to clarify, I was able to download the dependencies separately and build them manually. However, a colleague build a previous version of OpenMS using cmake, and it seemed easier and much less prone to user (me) error:

cd contrib
   cmake . -DBUILD_TYPE=GLPK
   cmake . -DBUILD_TYPE=LIBSVM
   cmake . -DBUILD_TYPE=SEQAN
   cmake . -DBUILD_TYPE=BOOST

In our case we are working on a linux (RHEL 6.6) system on which we do not have root - so installing the repository versions is not always trivial.

**Comment by hroest** [comment]
I agree, the correct way to do it should be 
```
cd contrib
cmake . -DBUILD_TYPE=GLPK
cmake . -DBUILD_TYPE=LIBSVM
cmake . -DBUILD_TYPE=SEQAN
cmake . -DBUILD_TYPE=BOOST
```

and I think we should have a source code tarball that includes that contrib folder. @jpfeuffer @timosachsenberg  is it feasible to update the tarball ?

**Comment by jpfeuffer** [comment]
I added a tarball including the contrib dir to our SF page.
https://sourceforge.net/projects/open-ms/upload/OpenMS/OpenMS-2.0/

Now it should be possible to install it the way it is described in the docu (i.e. as in your comments).
However, as also mentioned, the sources of the contrib are downloaded after executing cmake, so an internet connection is still needed.

I will remove the "zip" as soon as I get some feedback on the tarball.

**Comment by hroest** [comment]
I think having an internet connection is ok as you also need one to download the original source code ...

**Comment by timosachsenberg** [comment]
related to https://github.com/OpenMS/OpenMS/issues/1375

**Comment by Xucam** [comment]
Hi,
 
  I opened the thread initially, and just wanted to post an update.  The new contrib setup worked flawlessly for me, making the build essentially 4 steps.

#download and unpack release (2.0.0)

# make all contrib
  cmake -DBUILD_TYPE=ALL

# cmake OpenMS
cmake -DCMAKE_PREFIX_PATH="/proteomics/sw/OpenMS-2.0.0/contrib/;/proteomics/sw/qt-4.8.5;/usr;/usr/local" -DBOOST_USE_STATIC=OFF ../OpenMS-2.0.0/

# make OpenMS
make

Thanks for the help.
