### ISSUE TITLE
cdash display

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1367]
could someone categorize the Python checker into the "checker" category in cdash: 

release2.0-mac-osx-10.8-clang-5.0-LLVM3.3svn-Unix_Makefiles-Release_PythonChecker info

--> these are not nightly tests but these are the pyOpenMS extension checks which ensure that we are not missing many functions

**Comment by hroest** [comment]
@jpfeuffer could you do that?

**Comment by jpfeuffer** [comment]
Sure I'll look into it. Hints are welcome if somebody had experience with it.

**Comment by hroest** [comment]
I think we once had that  going on, maybe @aiche would know how to do it?

**Comment by hendrikweisser** [comment]
Is CDash still being used or is it all Travis/Jenkins now? If the issue is no longer relevant, please close.
