### ISSUE TITLE
segfault on mac tests

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1368]
why do the OS X tests segfault for 3 tests? http://cdash.openms.de/viewTest.php?onlyfailed&buildid=127320

can somebody reproduce this on their machine?

**Comment by hendrikweisser** [comment]
The link no longer works, so it would have been useful to include in the ticket which tests fail.

Independent of that, with the current "develop" branch, I get test failures (only) for the FidoAdapter tests on my MacBook (OS X 10.8.5) - not including pyOpenMS, which I haven't built.

**Comment by cbielow** [comment]
Sidenote: I looked a couple of days ago at the Mac nighlies and a handful of tests was still segfaulting. See current cdash.
-- 
Sent via mobile phone.

Am 13. Mai 2015 17:55:49 MESZ, schrieb hendrikweisser <notifications@github.com>:

**Comment by hendrikweisser** [comment]
Is this issue still relevant?

**Comment by jpfeuffer** [comment]
Seems like only SuperHirn segfaults.
http://cdash.openms.de/viewTest.php?onlyfailed&buildid=149285
Additionally travis now also builds on Mac after every PR. So if these work fine, even less to worry.

**Comment by hroest** [comment]
strange, on travis it does not segfault with clang neither on mac nor on linux. We have even added the AddressSanitizer recently and even then it seems to work, strange.

**Comment by hroest** [comment]
close with reference to newer issue  #2549
