### ISSUE TITLE
Fido missing on Travis build servers

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#1374]
I just looked through the logs of the CI builds on Travis and it doesn't seem to find Fido.
Therefore all tests associated with the Adapter are disabled.
I think we should add it. Does anyone know how to do this? I currently don't know how to edit the Travis servers.

**Comment by timosachsenberg** [comment]
This should be already in travis
https://github.com/OpenMS/OpenMS/commit/5acd156bb110d3639da4f45347006fe72f9900d6

but the binary is missing in the SVN:
http://svn.code.sf.net/p/open-ms/code/THIRDPARTY/Linux/64bit/Fido/

**Comment by ypriverol** [comment]
@timosachsenberg where I can find the 64bit version for Fido?

**Comment by jpfeuffer** [comment]
I think we decided to leave it to the Linux users to build their own Fido from either the official sources or from hendriks git: https://github.com/hendrikweisser/Fido.
Looking at this again, I think we should maybe include at least one built executable for use with travis.

**Comment by ypriverol** [comment]
@jpfeuffer I guess is a good idea to include this a build to be consistent with the other third-party tools like xtandem, myrimatch, etc.

**Comment by timosachsenberg** [comment]
Yep. Let's do this

**Comment by jpfeuffer** [comment]
Should be resolved by now.
