### ISSUE TITLE
AccurateMassSearch should complain if no feature matched the adduct charge states

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1377]

**Comment by cbielow** [comment]
do you mean a certain adduct was never used or if no features were annotated at all?

**Comment by timosachsenberg** [comment]
If no features were annotated at all I think it should warn that no feature got annotated because feature charges did not match any possible adduct charge.
We had the case that a user thought that the charge after the ; in the adduct file describes how the charge changes.
It's a minor issue though and just an idea how a user could be pointed to the error...
