### ISSUE TITLE
MSGF+ allows Trypsin to cleave before Proline, OpenMS doesn't.

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1378]
MSGF+ reports peptides with cleavages sites before Proline. OpenMS does not allow for KP or RP cleavage sites. Therefore PeptideIndexer crashes with allow_unmatched = false.

PAASRMQIEKAVEMLIQAER

> sp|P0AEP7|GCL_ECOLI Glyoxylate carboligase OS=Escherichia coli (strain K12) GN=gcl PE=1 SV=2
MAKMRAVDAAMYVLEKEGITTAFGVPGAAINPFYSAMRKHGGIRHILARHVEGASHMAEGYTRATAGNIGVCLGTSGPAGTDMITALYSASADSIPILCITGQAPRARLHKEDFQAVDIEAIAKPVSKMAVTVREAALVPRVLQQAFHLMRSGRPGPVLVDLPFDVQVAEIEFDPDMYEPLPVYKPAASRMQIEKAVEMLIQAERPVIVAGGGVINADAAALLQQFAELTSVPVIPTLMGWGCIPDDHELMAGMVGLQTAHRYGNATLLASDMVFGIGNRFANRHTGSVEKYTEGRKIVHIDIEPTQIGRVLCPDLGIVSDAKAALTLLVEVAQEMQKAGRLPCRKEWVADCQQRKRTLLRKTHFDNVPVKPQRVYEEMNKAFGRDVCYVTTIGLSQIAAAQMLHVFKDRHWINCGQAGPLGWTIPAALGVCAADPKRNVVAISGDFDFQFLIEELAVGAQFNIPYIHVLVNNAYLGLIRQSQRAFDMDYCVQLAFENINSSEVNGYGVDHVKVAEGLGCKAIRVFKPEDIAPAFEQAKALMAQYRVPVVVEVILERVTNISMGSELDNVMEFEDIADNAADAPTETCFMHYE

PGMDSLAPEDGSHR

> sp|P21179|CATE_ECOLI Catalase HPII OS=Escherichia coli (strain K12) GN=katE PE=1 SV=1
MSQHNEKNPHQHQSPLHDSSEAKPGMDSLAPEDGSHRPAAEPTPPGAQPTAPGSLKAPDTRNEKLNSLEDVRKGSENYALTTNQGVRIADDQNSLRAGSRGPTLLEDFILREKITHFDHERIPERIVHARGSAAHGYFQPYKSLSDITKADFLSDPNKITPVFVRFSTVQGGAGSADTVRDIRGFATKFYTEEGIFDLVGNNTPIFFIQDAHKFPDFVHAVKPEPHWAIPQGQSAHDTFWDYVSLQPETLHNVMWAMSDRGIPRSYRTMEGFGIHTFRLINAEGKATFVRFHWKPLAGKASLVWDEAQKLTGRDPDFHRRELWEAIEAGDFPEYELGFQLIPEEDEFKFDFDLLDPTKLIPEELVPVQRVGKMVLNRNPDNFFAENEQAAFHPGHIVPGLDFTNDPLLQGRLFSYTDTQISRLGGPNFHEIPINRPTCPYHNFQRDGMHRMGIDTNPANYEPNSINDNWPRETPPGPKRGGFESYQERVEGNKVRERSPSFGEYYSHPRLFWLSQTPFEQRHIVDGFSFELSKVVRPYIRERVVDQLAHIDLTLAQAVAKNLGIELTDDQLNITPPPDVNGLKKDPSLSLYAIPDGDVKGRVVAILLNDEVRSADLLAILKALKAKGVHAKLLYSRMGEVTADDGTVLPIAATFAGAPSLTVDAVIVPCGNIADIADNGDANYYLMEAYKHLKPIALAGDARKFKATIKIADQGEEGIVEADSADGSFMDELLTLMAAHRVWSRIPKIDKIPA

**Comment by cbielow** [comment]
actually, since 4 days you can use PeptideIndexer with Typsin/P

https://github.com/OpenMS/OpenMS/pull/1177/files



Am 4/28/2015 um 4:50 PM schrieb Lars Nilse:

**Comment by lars20070** [comment]
Thanks @cbielow! I will update our server installation tomorrow morning.
