### ISSUE TITLE
XTandemAdapter support for X!Tandem PILEDRIVER

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1379]
On April 1, 2015 X!Tandem PILEDRIVER [1] was released. It includes support for mzIdentML and MSNumPress. If necessary, the XTandemAdapter should to be adapted. All X!Tandem parameters should be available in the adapter interface.

[1] http://www.thegpm.org/TANDEM/release.html

**Comment by lars20070** [comment]
The adapter should include a new advanced parameter with which an tandem parameter file can be specified directly. This file will override any settings in the interface.

**Comment by lars20070** [comment]
< note type="input" label="residue, modification mass" >57.021464@C,28.031300@[,28.031300@K< /note >
< note type="input" label="residue, potential modification mass" >6.031817@[,6.031817@K< /note >

The above mods are neither fixed nor variable. It allows for a light (28Da) or heavy (34Da) modification at Lysine and the N-terminus, but not for totally unmodified peptides. Probably not straightforward to model that in the XTandemAdapter user interface. But possible by specifying a tandem params file directly.

**Comment by algom** [comment]
+1 specifying the tandem parameter file would be really helpful. Specially for people that already work with it and can just import all settings.

**Comment by oliverschilling** [comment]
Hello

I think the x!tanddem adapter still lack the ability control the following options (or am I wrong?):

cyclic permutation (very useful!)

number of minimum peaks

quick acetyl / pyrolidone 

activate spectrum conditioning

All of these parameters are essential to use X!Tandem in the context of OpenMS (also with older versions of tandem...). 

Alternatively, use of a parameter file to override the GUI would be a solution.

Thanks!

Oliver

**Comment by cbielow** [comment]
I'm going to close this issue. since the main point (parameter settings) were fixed in #1684.
If the minor points are still causing trouble, please open a new ticket.

**Comment by lars20070** [comment]
We have a couple of config files from our TPP pipelines. It would be better if such files can override the interface params, not the other way around. https://github.com/OpenMS/OpenMS/issues/1379#issuecomment-99829121

**Comment by cbielow** [comment]
please read the bugfix description -- you CAN do exactly that!

**Comment by lars20070** [comment]
Ok. Thanks for the fix! - @algom Please switch `ignore_adapter_param` on to use your old config files.
