### ISSUE TITLE
protein scores not suitable to distinguish between good/bad hits

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1381]
70% to 80% of the reported protein scores are identical to zero [1]. That makes it impossible to rank the hits and distinguish between reliable and unreliable protein hits.

[1] https://github.com/OpenMS/OpenMS/issues/1095#issuecomment-95846214

**Comment by hendrikweisser** [comment]
This refers to the scores computed by Fido via FidoAdapter, correct? (If yes, please mention "Fido" in the title.)
Where do the input PSM scores come from? How are they distributed (i.e. are they already mostly close to zero)?
Did you apply any filtering to the PSMs? If not, maybe try filtering to 5% FDR to remove low-scoring hits.
What are the values of the internal Fido parameters? They appear as "UserParam" entries named "Fido_prob_..." in the output idXML.

**Comment by lars20070** [comment]
@hendrikweisser Here [1] the complete protein identification workflow. FalseDiscoveryRate is running after Fido. Since the protein scores are between 0 and 0.05 (We used a 5% FDR cutoff.), I suspect that it is not the Fido scores in the final TextExporter output.

[1] https://gist.github.com/lars20070/2239223cbe98f0eeb1b9

![msgf fido](https://cloud.githubusercontent.com/assets/6149805/7410007/5cb68f2a-ef2b-11e4-8ce7-1ca3158c987c.png)

**Comment by hendrikweisser** [comment]
After running FalseDiscoveryRate on the FidoAdapter results, your protein scores are q-values. If you then filter to 5% FDR with IDFilter, of course the remaining scores will be between 0 and 0.05 (exclusive?). These appear in the TextExporter output.

> That makes it impossible to rank the hits and distinguish between reliable and unreliable protein hits.

You have already removed the unreliable protein hits by applying the FDR filter.

**Comment by lars20070** [comment]
Fido prefers to have also bad hits in the input. Right? That's why we FDR-filter after Fido.

How can I export the original Fido scores, even though the last score calculated are the q-values?

**Comment by hendrikweisser** [comment]
> How can I export the original Fido scores, even though the last score calculated are the q-values?

Unfortunately that is currently not supported. The data structures for protein/peptide hits only have one field for the score, which gets overwritten if the scores are processed further (e.g. by FidoAdapter or FalseDiscoveryRate).

I'm not sure if FalseDiscoveryRate keeps the original (input) scores as meta information. If it does, it might be possible to change TextExporter to output that information, but I think it wouldn't be trivial to do that in a general/flexible way (i.e. that works for more than your specific use case).

**Comment by timosachsenberg** [comment]
What I did in the identification view in TOPPView is to collect common meta value keys (keys that are present in all hits) and add additional columns for these. This might be generic enough for maybe 90% of all use cases.

**Comment by lars20070** [comment]
The Identification View is greyed-out. How can I access it?

![identificationview](https://cloud.githubusercontent.com/assets/6149805/7440698/22bd4b98-f0c4-11e4-8fe0-7198d27fc137.png)

**Comment by timosachsenberg** [comment]
You need to annotate the mzML with the idXML (See menu). I think the code could be factored out and be reused so you don't need to write it.

**Comment by lars20070** [comment]
Very nice! - Refactoring and reuse sounds like a good plan.

**Comment by hendrikweisser** [comment]
> How can I export the original Fido scores, even though the last score calculated are the q-values?

I've now implemented a tool that should enable this: #1486

**Comment by hendrikweisser** [comment]
IDScoreSwitcher should cover this use case. I'm closing the ticket.
