### ISSUE TITLE
msgf+ missed cleavages

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#1384]
Maybe I am blind...but is it possible that the msgf+ adapter is missing the option for missed cleavages?

Thanks

Oliver

**Comment by hendrikweisser** [comment]
How about this one:

> -tryptic <choice>                  Level of cleavage specificity required (MS-GF+ parameter '-ntt') (default: 'fully' valid: 'non', 'semi', 'fully')

**Comment by lars20070** [comment]
MSGF+ has no missed cleavage parameter [1]. As I understand, the search engine tests for this automatically.

[1] https://bix-lab.ucsd.edu/pages/viewpage.action?pageId=13533355

**Comment by oliverschilling** [comment]
@hendrikweisser: that parameter defines the specificity of the termini, not the number of missed cleavages.  
@lars20070 : thanks... sounds like that parameter is not needed

I guess we can close issue...that was fast...,.
