### ISSUE TITLE
external / generic wrapper: raw file convert

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#1386]
Hello - it seems that the temp directory for the raw file converter (generic wrapper, very useful tool) cannot be changed. So all intermediate mxml files end up in the same directory. This causes the wrapper to crash when performing multiple analyses on the same dataset. A solution would be to have the ability to set a specific temp directory for the wrapper. 
Thanks

Oliver

**Comment by hendrikweisser** [comment]
OpenMS uses the same temporary directory for everything. The location of that can however be changed in the "OpenMS.ini" file, which (on a modern Windows system) is located in "C:\Users\[username]\.OpenMS". To change the temporary directory, look for this line:
`<ITEM name="temp_dir" value="[path]" ...`
And change [path] to where you want the temporary directory to be.

**Comment by oliverschilling** [comment]
Thanks, but I was referring to a specific directory for this wrapper for a specific openms run; different from the global temp directory. If all mzml files that the wrapper generates end up in the same (temp) directly, there can be naming conflicts or locked files, especially when performing several analyses on the same dataset.

**Comment by hendrikweisser** [comment]
> when performing several analyses on the same dataset

Why is not enough to convert each raw file only once in this case?

> there can be naming conflicts or locked files

I don't understand why that should happen. Typically newer files just overwrite older ones of the same name.

**Comment by cbielow** [comment]
I can see why the problem exists, but there are multiple things not "canonical" about this scenario.
You could (as Hendrik suggested): convert the files before and if they still happen to have identical basenames  you can keep them in separate directories.

However, #1388 should solve the problem when multiple GW instances are running concurrently with identical TEMP directories.

**Comment by lars20070** [comment]
Resolved via #1388.
