### ISSUE TITLE
new optional peptide_identification_index in FeatureHandle

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1390]
A consensus feature contains several FeatureHandle, each of them consisting of a map index, element index and element (position). The consensus feature also contains a list of peptide identification.

Could we add a new optional peptide_identification_index to FeatureHandle that points to one entry in the peptide identification list? This way we can associate peptide IDs with specific features and not just the entire consensus.

**Comment by timosachsenberg** [comment]
Why not store it the other way around? Add the map index to each PeptideIdentification entry as a user value.

**Comment by lars20070** [comment]
Good idea. That is easier. I will do that.
