### ISSUE TITLE
'use noise suppression' missing from XTandemAdapter

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1392]
The 'use noise suppression' flag [1] is missing from XTandemAdapter. It should be added to the adapter and switched off by default. Currently it's switched on.

< note type="input" label="spectrum, use noise suppression" >yes< /note >

[1] http://www.thegpm.org/TANDEM/api/

**Comment by timosachsenberg** [comment]
example how this was done for some other parameter:
https://github.com/OpenMS/OpenMS/commit/da7c9986cd257a1fb68c32a052d3e1e0f5c274c9
