### ISSUE TITLE
TextExporter: no compact output with peptide IDs for featureXML

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1393]
For feature maps, TextExporter currently offers three output options:
- the default, which generates a mix of rows with different types of information (proteins, unassigned peptides, features, assigned peptides)
- "no_ids", which writes one row per feature, but without any information about peptide IDs
- "feature:minimal", which writes only RT, m/z, and intensity for every feature

The default output cannot easily be read using e.g. R (since columns contain different types of data, depending on the rows). The other variants lose the (peptide) ID information, which is critical for many analyses. Thus, an output format with one row per feature that also includes assigned peptides would be desirable. For consensus maps, this already exists with the "consensus:features" output. (Indeed, as a work-around it is possible to convert a featureXML to consensusXML with FileConverter, then export it via "consensus:features" to get a usable result.)

**Comment by lars20070** [comment]
@hendrikweisser I agree that the text output format is very inconvenient. Maybe this is the place to discuss the text output in OpenMS.

For the next release, could we phase out TextExporter totally and replace it by the MzTabExporter plus optional R script? (The R script will be shipped similarly to the QC R scripts.) mzTab contains all information and provides a standard. Any user can modified the default R script as needed.

**Comment by hendrikweisser** [comment]
@lars20070: Doesn't mzTab also have the problem that it can't easily be read in R due to different formats in different rows?

Besides that, MzTabExporter needs to mature before it can replace TextExporter (e.g. with my current data, I get this: "Error: Unexpected internal error (the element 'Deamidated (NQ)' could not be found)").

**Comment by lars20070** [comment]
@hendrikweisser mzTab is also not much easier to read in R. But I can take care of a script doing the formatting.

I hope mzTab will be stable enough by the time of the next release, see https://github.com/OpenMS/OpenMS/issues/1095#issuecomment-95867291 Not sure how much more work is needed.

IMHO, it's a waste of time to hard-code the formatting or use regular expressions https://github.com/OpenMS/OpenMS/pull/1348#issuecomment-96235482 Once all information is in mzTab, the rest can be done by an easily editable script.

**Comment by timosachsenberg** [comment]
There are some R packages for dealing with mzTab though I am not sure if they are up to date. I will try to find some time to improve the mzTab support if you file issues.
