### ISSUE TITLE
optimal TOPP tool parameters for data from various MS machines

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1395]
This thread serves as discussion forum for optimal parameter settings for search engine and quantification TOPP tools. Experimental data from different machines (Q Exactive, Q Star ...) will require different settings.

If you can provide good parameters, please upload *.ini for individual tools or *.toppas for complete workflows to Gist [1] and link to this thread. If you are underwhelmed by your results, please post your problems.

[1] Gist https://gist.github.com

**Comment by VOOginga** [comment]
The link below [1] describes the parameters used to identify peptide features in Q_Exactive data
Charge: 1-5
RT typ: 25 secs
RT min: 3 secs
m/z tol: 10 ppm
intensity_cutoff: 1000
peptide_similarity: 0.5
averagine_similarity: 0.5
missed cleavages: 0
[1] https://gist.github.com/VOOginga/33e969917d7185f0cd90

**Comment by lars20070** [comment]
For the detection of **peptide pairs or triplets** in Q Exactive data we recommend the following settings [1].

charge: 1-5
RT typical: 50 secs
RT minimum: 5 secs
m/z tolerance: 10 ppm
intensity_cutoff: 1
peptide_similarity: 0.4
averagine_similarity: 0.3
missed cleavages: 3

[1] https://gist.github.com/lars20070/5e6103cdacaab4163361

**Comment by lars20070** [comment]
When using FeatureFinderMultiplex in combination with SpectraMerger, the accuracy of the quantification can be further increased. See the two fold change distributions without and with prior averaging (20% decrease in standard deviation of fold changes). When detecting **peptide pairs or triplets** with prior averaging, RT min and both similarities should be increased.

charge: 1-5
RT typical: 50 secs
RT minimum: 5 secs
m/z tolerance: **15 ppm**
intensity_cutoff: 1
peptide_similarity: **0.7**
averagine_similarity: **0.6**
missed cleavages: 3

![withoutaveraging](https://cloud.githubusercontent.com/assets/6149805/8251788/b9144e1c-167f-11e5-8b80-9d0e2fa6a752.png)
![withaveraging](https://cloud.githubusercontent.com/assets/6149805/8251789/bc656f92-167f-11e5-9786-4210d94b0cb3.png)
