### ISSUE TITLE
protein section in mzTabExporter output missing

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1399]
The mzTabExporter output is lacking the protein section (PRH/PRT). The complete protein lists should be exported, including the protein grouping information.

**Comment by lars20070** [comment]
At the moment, there is no way to export protein group information. Instead of adding this functionality to TextExporter, I would prefer to see the groups reported in the protein section of mzTab. Hence no need for a separate new issue.

**Comment by algom** [comment]
+1 This is of great importance, have a grasp about how the protein groups were generated.

**Comment by oliverschilling** [comment]
Dear all - this is indeed highly important...to put it a bit extreme: without info on protein groups, most protein-centric workflows are almost useless. Thanks in advance!

**Comment by timosachsenberg** [comment]
I agree. I will try to find some time to implementiert it.

**Comment by timosachsenberg** [comment]
Added intial export of protein data for idXML
https://github.com/OpenMS/OpenMS/pull/1433
Some information is not exported yet as e.g. on the oberserved modification states in all PSMs...

**Comment by timosachsenberg** [comment]
still critical?

**Comment by lars20070** [comment]
Proteins and protein groups have been added to `mzTab` in #1433.
See also R post-processing scripts for a simplified output in #2048.

For protein quantifications in `mzTab` see #1443.
