### ISSUE TITLE
ProteinHit::coverage_ not stored in file formats [140]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#140]
Submitted by hendrikweisser on 2010-03-29 18:17:15

The coverage of a protein hit does not get recorded in idXML, featureXML, or consensusXML. All other inherent attributes of a protein hit (accession, score, sequence) are stored, however.

-------------------------------------------------
Commented by cbielow on 2011-01-03 11:08:25:
** one can use ''ProteinIdentification::computeCoverage(const std::vector<PeptideIdentification>& pep_ids)'' to recompute it internally (as of [7705]), but its still not stored in the file formats.
The TextExporter will report Coverage (by recomputing it).

**Comment by lars20070** [comment]
Resolved in #1936 and #1954.
