### ISSUE TITLE
Run Progress on TOPPAS

### ISSUE THREAD

**Issue by zonlai** [OpenMS/OpenMS#1400]
As a user, it would be useful to be able to view run progress within the log. Is it possible to perhaps include a run progress (%), for example while FeatureFinderMultiplex is running?

**Comment by cbielow** [comment]
thanks for the feedback.
Reporting progress is the responsibility of the tool. I.e., FFMultiplex needs to do it -- then TOPPAS will show it.
Maybe Lars can comment.

**Comment by lars20070** [comment]
@cbielow On the command line the progress is visible, see below. But not in TOPPAS. Do I need to set the progress differently?

Progress of 'filtering LC-MS data':
  12.54 %

**Comment by cbielow** [comment]
A fix is in review (#1410) - by bad, sorry.

**Comment by lars20070** [comment]
Thanks @cbielow.

**Comment by cbielow** [comment]
So just to clarify: the fix will be available in the next OpenMS release and nightly builds (http://ftp.mi.fu-berlin.de/pub/OpenMS/nightly_binaries/).

**Comment by zonlai** [comment]
Thanks @cbielow
