### ISSUE TITLE
TheoreticalSpectrumGenerator addPeaks inefficient

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1406]
calculating the theoretical spectrum from masses of the individual prefix ions takes O(n²) time.
This should be directly be done in the theoretical spectrum generator in O(n) time.

**Comment by jpfeuffer** [comment]
We think we found another inefficiency, when calculating the loss ions.
Currently the loss is "subtracted" from the formula of the ion and then getMonoWeight is called again.
Can't we just subtract the weight of the loss? Are we missing sth?

**Comment by timosachsenberg** [comment]
Subtracting the weight of the loss is sufficient.

**Comment by hendrikweisser** [comment]
I independently discovered this problem and fixed it for theoretical spectrum generation of RNAs here: #4020
The resulting speed-up was massive. The same approach could be applied for peptide spectra.
