### ISSUE TITLE
TheoreticalSpectrumGenerator should internally generate mass vectors + annotation vectors

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1408]
For the sake of faster computation and future refactoring for new spectra classes, masses should be moved to functions that fill vector<double> and optionally vector<pair<String,String> > for annotations.

Existing methods might be preserved but use the new methods that generate vector of doubles....

**Comment by jpfeuffer** [comment]
@liangoaix Have a look here. Maybe we can solve this.
