### ISSUE TITLE
EnzymaticDigestion support for new Enzyme / EnzymeDB class

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1411]

**Comment by liangoaix** [comment]
After merging the new Enzyme class, I can open the pull request of this.

**Comment by timosachsenberg** [comment]
@liangoaix hi Xiao, I saw that the DigestionEnzyme enum is still present in ProteinIdentification and used at least in the /nfs/wsi/abi/old-data/sachsenb/OpenMS_IDE/src/openms/source/FORMAT/HANDLERS/MascotXMLHandler.cpp and MzIdentMLHandler. Could you take a look at it again and remove it (if possible).

**Comment by liangoaix** [comment]
@timosachsenberg Sure, Actually there are more using the previous enum.
