### ISSUE TITLE
Missing options in Tandem adapter - re-opened

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#1414]
I am afraid, but #1412 was closed prematurely. As far as I can see, it is still not possible to control the following parameters through the adapter:

cyclic permutation (very useful!)

number of minimum peaks

quick acetyl / pyrolidone (although these could be set off by default, as they are probably not reported in compliance to unimod...but tat is my guess only)

activate spectrum conditioning
(importnat for older TOF data, e.g from QSTAR)

Thanks

Oliver

**Comment by lars20070** [comment]
@oliverschilling This will be addressed in #1379.
