### ISSUE TITLE
feature request: meaningful names for output folders / files

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#1415]
Dear all, when setting up and testing rather complex toppas workflows, it would be a huge help to give meaningful names to output folders / files. So, rather than "015-IDFilter-out" a user-defined name (which would be here: "peptides after IDFilter").  Maybe this could be an option in the output-file module? At any rate, it would help a lot!
Thanks
Oliver

**Comment by cbielow** [comment]
since other people want this as well, here it is :) #1418

**Comment by cbielow** [comment]
Solved. Closing.

**Comment by oliverschilling** [comment]
thanks!
