### ISSUE TITLE
QSTAR / wiff data in OpenMS

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#1421]
Dear all

we are still extensively using a (rather old...) AB/SCiex QSTAR ELITE for a few projects involving tumor tissue analysis. 

Is there any lab with a functional OpenMS peptide ID workflow for QSTAR data (wiff format). Our initial attempts to use OpenMS yielded a 25 % reduction on peptides IDs (5 % FDR) compared to TPP (both using X! Tandem).  

We would appreciate any hint / idea / suggestion.  

Thanks

Oliver

**Comment by timosachsenberg** [comment]
Hi Oliver,
I guess the X!Tandem files are identical. Was the FDR calculated in OpenMS or both in OpenMS and TPP?

**Comment by oliverschilling** [comment]
Thanks for the answer, Timo. OpenMS FDR was from OpenMS, TPP FDR from TPP.

**Comment by timosachsenberg** [comment]
A possible explanation is a more conservative vs. less conservative FDR calculation.
In a forum I found some references that TPP uses the formula from:
http://www.mcponline.org/content/10/12/M111.007690.long

**Comment by jpfeuffer** [comment]
According to this formula they do not consider ALL decoys to be false and therefore multiply the FDR by an estimated fraction (~0.38). You could try doing roughly the same by dividing your threshold by this fraction (0.05/0.38=0.132) allowing more peptides to pass.
However, there are also differences in the PosteriorErrorProbability calculation that are harder to quantify. TPP uses a bit more information about the peptides for example.

**Comment by hendrikweisser** [comment]
> A possible explanation is a more conservative vs. less conservative FDR calculation.

To test this, could you convert the FDR-filtered (!) TPP results to idXML and apply PeptideIndexer/FalseDiscoveryRate/IDFilter (same FDR threshold) to them? If that removes hits, then our filtering is more aggressive. (This only works if the TPP results still contain decoys.)

**Comment by lars20070** [comment]
With Q Exactive data we see very similar results in TPP/XTandem and OpenMS/XTandem results. The FDR filtering step might not be the problem.

IMHO, it's a combination of centroiding #1419 and XTandem parameters #1379. - We just wanted to check that there isn't already an existing optimised OpenMS ID workflow for Q Star data out there.

**Comment by hendrikweisser** [comment]
> We just wanted to check that there isn't already an existing optimised OpenMS ID workflow for Q Star data out there.

Nobody has come forward with a workflow in four years, so I think it's fair to close this ticket.
