### ISSUE TITLE
Problems due to relative paths in TOPPAS

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1425]
Paths to files in "input file" nodes are stored as relative paths in TOPPAS. This leads to problems (error: "Input file names are wrong") when workflows are moved to different folders.

However, always using absolute paths is not ideal, either, as it prevents the "packaging" of workflows and input files, so that they can be moved/distributed together.

Possible solutions may be:
- add an option to switch between absolute/relative paths for a workflow or for individual "input file" nodes
- introduce a "working directory", relative to which the input file paths are stored; the working directory should be stored as an absolute path (or optionally as a relative one)

**Comment by cbielow** [comment]
As a manual fix, you can replace the relative filename in the corresponding TOPPAS file with absolute ones (a simple search&replace should suffice if you include parts of the opening HTML tag).

If this feature was to be implemented, I'd opt for a check-box somewhere within the GUI, which applies for all input nodes. I cannot think of a situation where you'd want to use abolsute paths only for a subset of input nodes. If this were required, the user should be able to overcome this by better data organization.
Am I missing something?

**Comment by hendrikweisser** [comment]
> I cannot think of a situation where you'd want to use abolsute paths only for a subset of input nodes. If this were required, the user should be able to overcome this by better data organization.

Yeah, I agree. If an important use case for a per-node switch became apparent, that could still be added later.

Can we agree that absolute paths should be the default?

**Comment by timosachsenberg** [comment]
hmm I always found it convenient for e.g. tutorials or example pipelines to have relative paths as default. wouldn't we then also need to save the information whether paths are relative or absolute in the toppas file?
