### ISSUE TITLE
Display spectrum native id in TOPPView

### ISSUE THREAD

**Issue by fcyu** [OpenMS/OpenMS#1426]
As we all know, the spectrum index in most data starts from 1. Why TOPP is so strange. Can I change the start index?

thx

**Comment by hendrikweisser** [comment]
> As we all know, the spectrum index in most data starts from 1.

Erm, no? The spectrum index in mzML files starts from zero, at least in the examples that I've checked.

I don't think it's possible to change the start index.

**Comment by fcyu** [comment]
It looks like different format have different starting index because mzXML starts from 1. Could openms directly use the 'num' attribute in mzXML or the "index" attribute in mzML to index spectra? In this way the starting index may be adjusted based on different formats.

**Comment by timosachsenberg** [comment]
Thanks for the feature request. I renamed the issue accordingly.

**Comment by hroest** [comment]
at least the spectrum "index" is defined to start from zero in mzML, see http://www.peptideatlas.org/tmp/mzML1.1.0.html#spectrum "The zero-based, consecutive index of the spectrum in the SpectrumList." so I dont think we can change that in OpenMS. 

Of course TOPPView can display whatever it wants but I agree with @fcyu that maybe we should have TOPPView behave consistently when opening the same data from mzXML and mzML

**Comment by hendrikweisser** [comment]
> I agree with @fcyu that maybe we should have TOPPView behave consistently when opening the same data from mzXML and mzML

What is "consistent" then? To always count from the same number or to count the same way as in the input file?

**Comment by fcyu** [comment]
@hendrikweisser I think the "consistent" means direct using the spectrum index (mzML) / scan num (mzXML) in the input file. Thus users won't be confused by different scan numbers of the same spectrum.
