### ISSUE TITLE
Fido, group_level flag docu

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1429]
I do not understand the group_level flag documentation

"Perform inference on protein group level (instead of individual protein level). This will lead to higher probabilities for (bigger) protein groups."

Protein groups are the result of the inference algorithm. If I already have protein groups, I no longer need to do inference. The docu does not help me to decide in what circumstances to set the flag.

**Comment by lars20070** [comment]
What does "(18)" in the log2_states docu refer to?

**Comment by hendrikweisser** [comment]
The "group_level" documentation is based on what the Fido usage output says:
> option -g uses protein group level inference

The protein grouping itself results from the peptide-protein associations. This flag affects the scoring of the groups. I think that by default, the probability for a group is the probability that a specific protein from the group is present; with this option, it's the probability for the group as a whole. But I'm not sure, so the documentation is somewhat intentionally vague. Please share your conclusions when you find out more.

For "log2_states", that part of the documentation says:
> '0' uses the default (18).

Which means that 18 is the default setting. I thought that should be reasonably clear.

**Comment by lars20070** [comment]
So 0 == 18. Why not set log2_states = 18 by default and min =1?

**Comment by hendrikweisser** [comment]
> Why not set log2_states = 18 by default and min =1?

Because the parameter is not even passed to Fido when "0" is used. In theory it shouldn't make a difference whether you use 0 or 18, but in practice I want to be sure that we can get the default behaviour of Fido.

**Comment by hendrikweisser** [comment]
Can I close this? The gist is that the FidoAdapter documentation is vague because there isn't a lot of documentation on Fido itself.
