### ISSUE TITLE
Protein coverage > 100 %

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#1431]
Dear all

when using msg/fido to analyze a Co-IP, I obtain protein coverages > 100%, see also attached a screenshot. Is it possible that identical peptides are counted multiple times? 
Best wishes

Oliver
![screen shot 2015-05-18 at may 18 2015 4 21 33 pm](https://cloud.githubusercontent.com/assets/8565908/7683835/034af1c8-fd82-11e4-8051-7889332cfce9.png)

**Comment by hendrikweisser** [comment]
Yes, this is a known problem: https://github.com/OpenMS/OpenMS/issues/1031

**Comment by oliverschilling** [comment]
ah?

**Comment by hendrikweisser** [comment]
I'm going to close this as a duplicate. @oliverschilling, could you comment on #1031 please if you have more to add?
