### ISSUE TITLE
ProteinIdentification::SearchParameters need update for relative tolerances

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1435]
http://ftp.mi.fu-berlin.de/pub/OpenMS/release2.0-documentation/html/structOpenMS_1_1ProteinIdentification_1_1SearchParameters.html

**Comment by timosachsenberg** [comment]
I marked this as major as it is needed in mzTab and other file formats...

**Comment by timosachsenberg** [comment]
also relevant for @mwalzer I guess

**Comment by timosachsenberg** [comment]
Some background information:
Modern file format like mzIdentML, mzTab want to store the search paramters including the unit.

Instead of modelling all type of units (as done via CV terms in mzIdentML, mzTab) our internal structure SearchParameters is extended to hold either absolute (Da) or relative (ppm) tolerances.
For our current viewpoint this should be sufficient.

**Comment by mwalzer** [comment]
#1471 should have resolved the issue
