### ISSUE TITLE
PeptideIndexer fails to match peptide

### ISSUE THREAD

**Issue by danielhyduke** [OpenMS/OpenMS#1436]
I'm interested in running the FalseDiscoveryRate modules on some data produced from the XTandemAdapter and I'm getting errors from PeptideIndexer about unmatched peptides.  The peptide sequence is present in the fasta database file and in the XTandem idXML file it's associated with a protein identifier so I'm wondering why PeptideIndexer doesn't match it.  This happens for more than one sequence.  I'm running TOPPAS 2.0.0 (ccd1c01) on CENTOS Linux 7.

*peptide sequence: PSKSSDTEMD

*matching protein from fasta database: 
>sp|O95843|GUC1C_HUMAN_reversed Guanylyl cyclase-activating protein 3 OS=Homo sapiens GN=GUCA1C PE=1 SV=3
KMKVKGLGAKDPSKSSDTEMDPQKGNCIVRLVNSFDFSKYVIELLDQDKAMGNIFEELTLEGDNNIDIKHFVLNIFEEPS
LTQQGNLAQVAMFMDLLENKDISGNGDADYLKFYWKLKQEMKEQMILNVAAIFELFDVFGDKNTDFTNYVQDIHKNAKQN
LGQLGLLTKFEHLTQLGSPYEMMFTRYWVHTEQTPVAKQDGAISKGNGM

*info from XTandemAdapter idXML

...
<ProteinHit id="PH_2898" accession="sp|O95843|GUC1C_HUMAN_reversed Guanylyl cyclase-activating protein 3 OS=Homo sapiens GN=GUCA1C PE=1 SV=3" score="0" sequence="" >
...
                <PeptideIdentification score_type="XTandem" higher_score_better="true" significance_threshold="0" MZ="366.153613997331" RT="994.539" >
                        <PeptideHit score="10.9" sequence="PSKSSDTEMD" charge="3" aa_before="D" aa_after="P" protein_refs="PH_2898" >
                                <UserParam type="float" name="E-Value" value="78"/>
                                <UserParam type="float" name="nextscore" value="8"/>
                                <UserParam type="float" name="mass" value="1096.4463"/>
                                <UserParam type="float" name="delta" value="-0"/>
                                <UserParam type="float" name="b_score" value="8.6"/>
                                <UserParam type="int" name="b_ions" value="3"/>
                                <UserParam type="float" name="y_score" value="8.5"/>
                                <UserParam type="int" name="y_ions" value="1"/>
                        </PeptideHit>
                        <UserParam type="int" name="spectrum_id" value="684"/>
                </PeptideIdentification>

*info from the PeptideIndexer output
                <PeptideIdentification score_type="XTandem" higher_score_better="true" significance_threshold="0" MZ="366.153613997331" RT="994.539" >
                        <PeptideHit score="10.9" sequence="PSKSSDTEMD" charge="3" >
                                <UserParam type="float" name="E-Value" value="78"/>
                                <UserParam type="float" name="nextscore" value="8"/>
                                <UserParam type="float" name="mass" value="1096.4463"/>
                                <UserParam type="float" name="delta" value="-0"/>
                                <UserParam type="float" name="b_score" value="8.6"/>
                                <UserParam type="int" name="b_ions" value="3"/>
                                <UserParam type="float" name="y_score" value="8.5"/>
                                <UserParam type="int" name="y_ions" value="1"/>
                                <UserParam type="string" name="target_decoy" value=""/>
                                <UserParam type="string" name="protein_references" value="unmatched"/>
                        </PeptideHit>
                        <UserParam type="int" name="spectrum_id" value="684"/>
                </PeptideIdentification>

**Comment by lars20070** [comment]
@danielhyduke PSKSSDTEMD is a non-tryptic peptide. By default, PeptideIndexer filters for fully tryptic peptides. It terminates if a non-tryptic sequence occurs.

enzyme:name = Trypsin
enzyme:specificity = full
allow_unmatched = false

If this does not resolve your problem, please upload your workflow to gist and provide a link here. We can then have a closer look at the parameter settings.

https://gist.github.com
