### ISSUE TITLE
mzid + mzML support for IDFileConverter

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1437]
The retention time information in mzid is optional, but can be read from the original mzML when converting to idXML. This feature is still missing, see https://github.com/OpenMS/OpenMS/issues/1409#issuecomment-104278980.

A pepXML + mzML -> idXML conversion is already possible.

**Comment by mwalzer** [comment]
See https://github.com/OpenMS/OpenMS/issues/1409#issuecomment-104278980

**Comment by hendrikweisser** [comment]
Since the "get RT information from mzML" functionality is in IDFileConverter for all the other search engine formats, I would like to have it there also for mzIdentML. I think this should be reopened.

**Comment by lars20070** [comment]
+1

**Comment by hendrikweisser** [comment]
See also #1447.

**Comment by hendrikweisser** [comment]
Solved via #1587.
