### ISSUE TITLE
IDPosteriorProbability pdf plots not written to TOPPAS_out

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1439]
IDPosteriorProbability can write gnuplot txt files to out_plot. If gnuplot is installed, a pdf is automatically generated. But this pdf is written to TOPPAS_tmp instead of TOPPAS_out, and therefore not easily accessible.

**Comment by cbielow** [comment]
This is an adapter problem. It generates the pdf without having an explicit output parameter for it.
Thus TOPPAS cannot know about it and the PDF stays where it was generated, and is not copied by TOPPAS to the next node downstream.

**Comment by lars20070** [comment]
The output is set explicitly in the gnuplot txt file.

set output 'D:\data\Lars\temp\2015-05-22_105554_ukmz1005immz_8856_1\TOPPAS_tmp\peptide_identifaction\008_IDPosteriorErrorProbability\out_plot\AGA118.idXML_tmp12.pdf'

The output path for the txt file is known. Could the same path not used for the pdf?

**Comment by cbielow** [comment]
The full file path (incl. filename and suffix) must be exposed via a 
proper outputfile argument of the tool.
Otherwise TOPPAS cannot know that a PDF exists.


Am 5/22/2015 um 3:22 PM schrieb Lars Nilse:

**Comment by timosachsenberg** [comment]
the plots are simple enough that we could just ouput a table and use an R script (e.g. in KNIME) to plot them

**Comment by lars20070** [comment]
@timosachsenberg I am also in favour of replacing any gnuplot scripts by R scripts.

@jpfeuffer But the current gnuplot solution works fine and is being used by us. It's simply inconvenient to fetch the pdf from the temp folder. So either way, choose whatever is the quickest fix.

**Comment by jpfeuffer** [comment]
I am also a fan of R, especially for usage in KNIME.
The thing about writing a table is, that the table would need to include the analytical formulation of the fitted distributions somehow (as it is done in the gnuplot file). The gnuplot file btw. includes all the steps of the fitting process.
The table must include:
Distr. types:
  Pos: Gauss
  Neg: Gauss
Distr. parameters:
  Pos:
  Step    m     sd     other
  1          2.0   1.0      -
  2          2.5   1.5      -
Neg:
  Step    m     sd     other
  1          1.0   1.0      -
  2          1.5   1.5      -

Data:
PSMIndex   Score
1                  0.5
2                  0.7

Then we would need an R script to read and plot. Coolest would be generating it on the fly.
So this would definitely not be the quickest fix, although I prefer it.

**Comment by timosachsenberg** [comment]
I generated R scripts in MetaProSIP and it worked for me.
On the other hand I think a better solution would be to come up with a general format that is easily read in R. 
If we can write tables we should write tables but for structured data like this it might be convinient to explore other possiblities.

Maybe we could just write out a json file - afaik they are relativly easily parsed in R

**Comment by hendrikweisser** [comment]
> Maybe we could just write out a json file - afaik they are relativly easily parsed in R

I think we should create a new XML format for this - IDPEPPDFXML! ;-)

**Comment by timosachsenberg** [comment]
using an XML is not totally out of the question we could indeed just write out a Param object.
I am not that into R but I know that there is a direct mapping of json to R structures which would make it easy. Maybe there is something similar for XML files...
Anyway, I think it is worth to discuss how we could pass that kind of information to KNIME for easier visualization.

**Comment by hendrikweisser** [comment]
I was only joking about the XML format before, but perhaps trafoXML (class: TransformationDescription) would actually be a good fit? It stores a model type, model parameters, and pairs of data points.

**Comment by lars20070** [comment]
+1 for a general solution using a standard (preferably not an abuse of trafoXML)

**Comment by timosachsenberg** [comment]
for that particular purpose trafoXML would probably match but I would like to have a more general solution. There are potentiall many tools out there that could write useful debug information used in data for visualization.

**Comment by hroest** [comment]
any progress here?

**Comment by timosachsenberg** [comment]
@cbielow and @mwalzer I think there have been some discussion on the retreat regarding QC and embedded plots. Without knowing the details - wouldn't something like you discussed also be useful here?

**Comment by cbielow** [comment]
I'm using R (ggplot2 to be exact)
and the images qcML of OpenMS are also produced using R 
(https://github.com/OpenMS/OpenMS/tree/develop/share/OpenMS/SCRIPTS)

Actually, I think we should create plots using external tools (R seems 
the best option to me).
To make this more convenient, we could write a minimal R wrapper class,
which accepts
1) an input string, containing the data
2) an R-function which returns a ggplot2 object
3) an output filename

the input string is converted internally into a data.frame and the 
user's plotting function (2) is called. From this, it produces a plot file.
This can be easily used by any TOPP tool that wants to plot some data.
I can write that... is should take an hour or so....


Am 4/17/2016 um 10:56 schrieb Timo Sachsenberg:

**Comment by timosachsenberg** [comment]
think this would be great. You can also check out the RIntegration class in the MetaProSIP util. I tested it on windows and linux and might also be interesting if we want to directly call R with some required packages.

**Comment by lars20070** [comment]
This plot should simply be (optionally) included in the QC reports.

**Comment by cbielow** [comment]
sidenote: I justed looked into Rserve and Rintern... both would allow to call R directly from C++.
But its another dependency and (more importantly) its GPL, so a no go for us.
Therefore: Will go forward with the plan from the post above.

**Comment by cbielow** [comment]
plotting via R is availble now.
https://github.com/OpenMS/OpenMS/pull/1981
So just use it :)

**Comment by lars20070** [comment]
Great. Thanks @cbielow. - Will test this and then close the issue.

**Comment by cbielow** [comment]
you need to write code, i.e. use rwrapper, and then test, right? :)

Am 5/13/2016 um 9:01 AM schrieb Lars Nilse:
