### ISSUE TITLE
mzTab output for ProteinQuantifier

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1443]
Most software packages, report a single list of proteins, both quantified and unquantified.

ProteinQuantifier should export the same `mzTab` as `MzTabExporter`, but in addition fill in any protein and peptide quantifications. Missing quantifications are reported as NA. If a protein is not quantified, a flag should indicate the reason why (no peptide quant in the first place, already "greedily" taken, not unique). See https://github.com/OpenMS/OpenMS/pull/1366#issuecomment-99135936.

**Comment by timosachsenberg** [comment]
I think the better way would be to export consensusXML and we add conversion to mzTab to the MzTabExporter. That way we ensure that our internal datastructures can model this information (e.g. via  meta values).

**Comment by hendrikweisser** [comment]
> I think the better way would be to export consensusXML and we add conversion to mzTab to the MzTabExporter.

I think a fundamental aspect of consensusXML is that you have consensus features with defined RT, m/z positions. The peptide and protein abundances that you get from ProteinQuantifier don't have that. This doesn't seem to be a good use for consensusXML to me.

**Comment by jpfeuffer** [comment]
Hmm, I see the problem.
What about a consensusXML where the consensus features point to the proteins (for which they were used for quantification), which then hold the (summarized) quantitative information on the protein level?
Would that make sense?

**Comment by hendrikweisser** [comment]
I just don't think we'd do ourselves any favours trying to shoehorn this kind of data into consensusXML.

**Comment by timosachsenberg** [comment]
Hi @hendrikweisser. Yes that is right. 
The meaning and usage of consensus features have changed quite a bit the last years and it is somewhat converging to a more general file format for quantification.
Question is if we can encode it in consensusXML without changing the format or if we need to reside to mzQuantML. Given that consensusXML is basically a representation of consensus maps I think that we need this transition at some point.
What I could imagine is a consensus feature that can either contain a peptideidentification or a proteinhit.

**Comment by timosachsenberg** [comment]
The concept of a consensus feature would be a a list of quantitative values from individual assays (assay as in mzQuantML / mzTab). Associated with this assays are additional annotation about the identity of  quantified proteins (as in the protein section in mzTab) or PSMs (as in the PSM section in mzTab).

**Comment by lars20070** [comment]
We would like to have a single mzTab with all ID and quant results of a workflow. (Further formatted using #1444.) That is our main motivation of this ticket. Most software packages report all proteins of an analysis (quantified or not) in a single list.

Ideally, ProteinQuantifier would write mzq. And MzTabExporter has two inputs for both mzid and mzq from which the tool compiles a complete mzTab. - Maybe it's easier for ProteinQuantifier to write mzTab directly.

**Comment by timosachsenberg** [comment]
Mathias and me have taken a closer look at ConsensusMap and ConsensusFeature and we kind of agree that encoding this information there might be bending the format too much.
The downside is that we need to come up with a consistent way to encode this information in our internal data structures (e.g. MSQuantification) and then probably use MzQuantML.

**Comment by VOOginga** [comment]
I would prefer to have the sequence coverage of proteins in the output of the protein quantifier. This would really simply the analysis part.

**Comment by oliverschilling** [comment]
Hello

I would like to come back to the original topic: is it possible to have the Proteinquantifier output directly (or indirectly through some conversion tool) in mztab format? Ideally, that output should comprise protein ratios and the underlying peptide ratios. Further information (e.g. peptide assigned by "greedy" algorithm) would be helpful but are perhaps optional at present. So: is mzTAB output (even is some basic form, but comprising protein and peptide ratios) for Proteinquantifier feasible?

Thanks

Oliver

**Comment by lars20070** [comment]
In my branch [1], the new `MzTabHelper` class [2] is used by both `MzTabExporter` and `ProteinQuantifier`. The `ProteinQuantifier`now writes `mzTab` from its `protein_groups` input. Now I will fill in the quantifications from the `PeptideAndProteinQuant` object.

IMO, some restructuring of the `MzTabHelper` class [2] will be necessary. (A set of methods that add data to an existing `MzTab` object?) Can we please discuss, before I make these changes. 

[1] https://github.com/lars20070/OpenMS/tree/fix/ProteinQuantifier
[2] https://github.com/lars20070/OpenMS/blob/fix/ProteinQuantifier/src/openms/include/OpenMS/FORMAT/MzTabHelper.h

**Comment by timosachsenberg** [comment]
PeptideAndProteinQuant are very specific to ProteinQuantifier so maybe you just add the missing information there?

**Comment by lars20070** [comment]
@hendrikweisser @timosachsenberg Let's discuss in the Gitter chat.

**Comment by timosachsenberg** [comment]
Hi, what is the current state of this issue? What about your branch @lars20070 ?

**Comment by lars20070** [comment]
https://github.com/OpenMS/OpenMS/compare/develop...lars20070:fix/ProteinQuantifier
Here my old code from a year ago.

**Comment by lars20070** [comment]
@timosachsenberg What's the state of protein `mzTab` export?
Do you plan to replace `ProteinQuantifier` by `MSStats` and export `mzTab` this way?
