### ISSUE TITLE
R script for conversion mzTab output

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1444]
The mzTab output from MzTabExporter or ProteinQuantifier #1443 contains the complete result of a workflow. But mzTab is still not a convenient format for further downstream analysis.

The R script converts mzTab into a simpler csv output, familiar from other software packages. This default R script is shipped with OpenMS, but can easily be adapted to the needs of each lab.

**Comment by jpfeuffer** [comment]
This would be very helpful also for KNIME workflows. I am looking forward to test it.

**Comment by timosachsenberg** [comment]
In KNIME this should be handled by the MzTabReader node

**Comment by lars20070** [comment]
For this R script, I will probably use readMzTabData() from MSnbase [1] for the import.

[1] http://bioconductor.org/packages/release/bioc/html/MSnbase.html

**Comment by jpfeuffer** [comment]
@timosachsenberg You are right. I guess it has to be update, too, then.

**Comment by lars20070** [comment]
Resolved by #1357.
