### ISSUE TITLE
Create library class for adding RT information to ID data

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1447]
Many file formats for search engine results, i.e. peptide/protein identification (ID) data, don't (necessarily) contain retention time (RT) information. Since this information is critical for many OpenMS processing pipelines, we have functionality to extract the RT information from spectral data (mzML) and match it to the ID results. This functionality is exposed in IDFileConverter (parameter "mz_file"), RTAnnotator (UTIL, for mzIdentML), and some search engine adapters (MSGFPlusAdapter, MascotAdapterOnline, ...?).

Problematically, this functionality is currently implemented in many places - in the tools mentioned above and/or in library classes for the respective file formats. This code needs to be refactored and moved into one class, in order to:
- avoid bad implementations
- reduce code duplication
- make the functionality easily available for future uses

**Comment by timosachsenberg** [comment]
I strongly agree.
I think we need a new label to point out refactoring tasks : "refactoring"

**Comment by hendrikweisser** [comment]
Addressed in #1587.
