### ISSUE TITLE
MzTabExporter - Missing Fields

### ISSUE THREAD

**Issue by zonlai** [OpenMS/OpenMS#1450]
Many thanks for implementing mztabexporter. I have tried to run ID searches today using via MSGF+ database. However there were missing fields under protein coverage and protein score.

Regards,
Weng

**Comment by lars20070** [comment]
Thanks for reporting @zonlai. After #1031 and #1381 are fixed, we will add this information to the mzTab output.

**Comment by hroest** [comment]
@lars20070 is done resolved now?

**Comment by timosachsenberg** [comment]
@lars20070 is this done and resolved now?

**Comment by hendrikweisser** [comment]
See also #1453.
