### ISSUE TITLE
MzTabExporter output: MSGF+ scores and other fields missing

### ISSUE THREAD

**Issue by zonlai** [OpenMS/OpenMS#1453]
I am assuming that the reported score in "best_search_engine_score[1]" are the q-values and not the original MSGF+ scores. Since majority of these values are zero, it is not possible for me rank peptides and proteins. Could we also include the original MSGF+ scores to facilitate protein ranking? Many thanks, Weng

**Comment by lars20070** [comment]
Apart from the search engine scores, other parameters such as spectra_ref, database, database_version or search_engine are null. Not the fault of the MzTabExporter tool (the columns are present), but the information is never annotated or not passed on in some of the upstream tools.

**Comment by lars20070** [comment]
An additional column opt_fraction would be very useful. It should contain the fraction (file name) to which the RT-m/z position refers to.

(In label-free experiments this corresponds to the map, in labeled experiments it does not.)

**Comment by lars20070** [comment]
An additional column `opt_protein_description` is missing, see PeptideIndexer `write_protein_description` option.

**Comment by lars20070** [comment]
`start` and `end` in the `PSM` section missing.

**Comment by timosachsenberg** [comment]
Is the column missing vor only the entry?

**Comment by lars20070** [comment]
All entries are missing. (comment updated)

**Comment by lars20070** [comment]
Somewhat unrelated: Can we set `remove_decoys = true` by default in `IDFilter`? In most cases, decoy proteins are of no interest in the final list.

**Comment by timosachsenberg** [comment]
Not only "somewhat unrelated" ;) but I guess a valid question. Maybe we could add an issue and add a label "defaults" to it in the future. That way we document the choices and arguments pro/contra.

**Comment by hendrikweisser** [comment]
@timosachsenberg:
Please also update the documentation of MzTabExporter. It currently lists ProteinQuantifier as a potential predecessor tool, but the input/output file types don't match. Also, are the different input files of MzTabExporter mutually exclusive, or how do they work together?

**Comment by timosachsenberg** [comment]
thanks. will update the documentation.
FYI the input files are mutually exclusive

**Comment by hendrikweisser** [comment]
> FYI the input files are mutually exclusive

In that case, why isn't there only one "in" parameter that allows different file extensions, like in other tools?

**Comment by timosachsenberg** [comment]
I think it is more convinient to have 4 KNIME port with fixed MIME type instead of 1 that requires to select the correct one

**Comment by hendrikweisser** [comment]
> I think it is more convinient to have 4 KNIME port with fixed MIME type instead of 1 that requires to select the correct one

I'm not using KNIME, so I can't judge that, but I don't like that you're breaking the precedent of all other TOPP tools for data conversion/export.

**Comment by timosachsenberg** [comment]
I wasn't actually suspecting anybody having a problem with that but I guess I reconsider it then.

**Comment by hendrikweisser** [comment]
> I wasn't actually suspecting anybody having a problem with that but I guess I reconsider it then.

I'm just a stickler for consistency. ;-)

**Comment by lars20070** [comment]
I do not see this as a big deal, but agree with @hendrikweisser.

**Comment by lars20070** [comment]
In the PSH section, optional columns such as `opt_global_modified_sequence` are missing.
In mzTab from idXML we cannot see the mods.

**Comment by hendrikweisser** [comment]
See also #1450.

**Comment by jpfeuffer** [comment]
@lars20070 Is this still uptodate with the latest additions?

**Comment by lars20070** [comment]
@jofeuffer I will come back to you. Still traveling and have no laptop.

**Comment by lars20070** [comment]
Guess that's fixed, see [here](https://github.com/ProteomicsScripts/ProteomicsScripts/blob/master/mzTab2PSMreport/misc/example.pdf). But let me check and then close the issue.

**Comment by lars20070** [comment]
Fixed.
