### ISSUE TITLE
change MzTabExporter output file extension from *.tsv to *.mzTab

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1462]
Currently, `MzTabExporter` writes output files with the extension `*.tsv`. It would be clearer to use the extension `*.mzTab` instead [1]. Any post-processing scripts that transform the `mzTab` to a better readable format could then use the `*.tsv` extension (`mzTab2tsv`).

[1] https://code.google.com/p/mztab/wiki/ExampleFiles

**Comment by timosachsenberg** [comment]
good idea but we need to be careful to not brake anything on the KNIME side

**Comment by lars20070** [comment]
@jpfeuffer Where in *Knime* do we need to introduce the new `mzTab` file type?

**Comment by lars20070** [comment]
Fixed in #3403.
