### ISSUE TITLE
IDFilter: remove decoy hits by default 

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1466]
Can we set `remove_decoys = true` by default in `IDFilter`? In most cases, decoy proteins are of no interest in the final list.

**Comment by cbielow** [comment]
I would expect the IDFilter to do nothing by default and only remove 
stuff which explicitly selected for removal.
But up for discussion.


Am 6/14/2015 um 13:37 schrieb Lars Nilse:

**Comment by timosachsenberg** [comment]
I think it boils down to whether we can define sensible defaults that ease the use of IDFilter while not messing with power users (e.g. introducing other sources of errors for people that don't want the default). 
what could these defaults be?
```
-score:pep 0.01
-best:n_peptide_hits 1
-remove_decoys true
-delete_unreferenced_peptide_hits true
```
Might be sensible in many cases but I think also problematic in others (for each parameter I imagine at least one common workflow that breaks if these are the defaults).

And just concentrating on remove_decoys? Would work for all cases where decoy information is not needed anymore - which is the vast majority of cases. But then again, we would have a more complicated rule than the simpler rule "IDFilter doesn't filter anything if nothing specified"

My feeling is that removing decoys as default in IDFilter is not the right choice .

**Comment by lars20070** [comment]
I think it is good to have this discussion. Should logic (IDFilter doesn't filter anything if nothing specified.) trump usability (Settings most often used are the default ones.)? Power users and developers are aware of most settings, and the first approach makes perfect sense.

On the other hand, most wet lab scientists use OpenMS for two days every four months. The fewer settings they have to be aware of and need to remember the better. For these users ready-made workflows that are never change might be the best solution. But many wet lab scientists want to understand the complete workflow and build them from scratch! For them, the first approach is an additional hurdle.

**Comment by timosachsenberg** [comment]
I see your point. The thing is that, by design, it is very difficult to choose default parameters so that just putting them in a workflow will result in something meaningful. I totally agree that ready-made workflows are the way to go for most users. For users that want to build their own workflow I think we can improve more by providing better documentation and examples.

**Comment by lars20070** [comment]
We should encourage users to understand the details of a workflow (and not blindly execute prefab pipelines). Only then can we receive useful feedback and bug reports. If we require them to read up on the documentation first, we will loose volunteers. Good software should require no manual (or at least a very thin one). In this sense, `remove_decoys` is a flag that the average user does not need to know about.

**Comment by zonlai** [comment]
For beginner users like myself, ready-made workflows with 'standard' default settings helped a lot with early learning of OpenMS.

**Comment by mwalzer** [comment]
@lars20070 
> Good software should require no manual

In science context i do not concur

> or at least a very thin one

completely on your side here!

What about having a vignette for the tool. We already started with the predecessor/successor tool documentation - I think it would be great to go on and have the parameter concisely summarised in the same brief fashion. We could aspire a tool vignette (not obligatory R style) that fits on one (recent sized) screen ...

**Comment by hendrikweisser** [comment]
I agree with Chris that filters should be "opt in" rather than "opt out". There's a much higher risk for bad surprises if something is removed by default.

**Comment by hendrikweisser** [comment]
Since there is no agreement to remove decoys by default, I propose to close this issue. Objections?

**Comment by lars20070** [comment]
Ok. It's a very minor issue. - Since there is no clear agreement, let's keep the settings as they are.
