### ISSUE TITLE
Store ms_run information in internal data structures

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1468]
MzTab, mzQuantML and mzIdentML need to store the original file name(s) of the experiment (usually the mzML). This information should be also preserved in idXML, featureXML, consensusXML.

This issue is intended to document the action needed to store this information and potential problems (e.g. automatically generated file names).

**Comment by lars20070** [comment]
+1

**Comment by timosachsenberg** [comment]
closest we have:
ConsensusMap: ConsensusMap::FileDescription (stores filename, label etc. )
MSExperiment and MSQuantification:  ExperimentalSettings class: http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/classOpenMS_1_1ExperimentalSettings.html#details

something related but different:
CM, FM, MSExp. have DocumentIdentifier which stores only the file type of the current file

**Comment by timosachsenberg** [comment]
For featureXML:
To prevent a schema change of FeatureXML I think the best way is to read the information from the dataProcessing element.
In principle, the first processingAction that contains a "parameter: in" of type mzML, mzXML etc. should contain the path to the original raw file.
One potential issue is that PeakPickerHiRes (and potentially other spectrum processing tools) currently don't fill the data processing object.

**Comment by timosachsenberg** [comment]
see also https://github.com/OpenMS/OpenMS/issues/1518

**Comment by hroest** [comment]
>  One potential issue is that data processing performed by PeakPickerHiRes (and potentially other spectrum processing tools) are currently not carried over to the data processing object of the featureXML.

thus the raw path would point to the centroided filename?

**Comment by timosachsenberg** [comment]
Yes that would be the case, but also consider that e.g. for TOPPAS pipelines these files would reside in the TMP folder while the original file is in the input folder. We should always reference back to the original files in the input folder.

**Comment by hendrikweisser** [comment]
Wouldn't it make more sense to store this information in the same way in each case - instead of having ExperimentalSettings/FileDescription/DataProcessing for MSExperiment/ConsensusMap/FeatureMap? I.e. add a meta value "primary_raw_file" that gets set once, but then just transmitted and never overwritten. Every TOPP tool would have to ensure that it adds or transfers this meta value to its output files, but there could be a function inherited from TOPPBase for that.

One difficulty with this whole approach is that a result can be derived from multiple MS runs (e.g. FeatureLinker..., FileMerger, IDMerger).

**Comment by timosachsenberg** [comment]
I also had this idea and I think it would make sense but is neither supported by featureXML nor FeatureMap.
FeatureXML can't store meta values at the map level and this is reflected in featureXML.

**Comment by hendrikweisser** [comment]
> FeatureXML can't store meta values at the map level and this is reflected in featureXML. 

Aw crap.

**Comment by timosachsenberg** [comment]
How should we proceed with this one? I think it might really make sense to support meta values at the level of a featureMap (as we have it for consensusmap). What we would have to do:
1st PR:
1. Add MetaInfoInterface to FeatureMap
2. Add optional user params to FeatureXML and create FeatureXML schema Version 1.7
3. Adapt parser to support featureXML 1.7 (older versions will most likely just ignore the user parameters)

2nd PR:
add accessor (set/getPrimaryMSRunFileLocations) to FeatureMap, ConsensusMap, MSExperiment

**Comment by hendrikweisser** [comment]
@timosachsenberg: I think that's a good plan. What about support in idXML - useful/necessary?

**Comment by timosachsenberg** [comment]
Yes I think it is absolut necessary for idXML files but I think here we have the possibility to use the meta information stored in ProteinIdentification (which currently already stores a lot of the information related to one identification run)

**Comment by timosachsenberg** [comment]
PR1 addressed in https://github.com/OpenMS/OpenMS/pull/1526

**Comment by timosachsenberg** [comment]
Ok I am nearly finished but currently thinking about how this information is carried over from the mzML file.
Here we have:
```
                <sourceFileList count="1">
                        <sourceFile id="sf_ru_0" name="KT_Pan_171114_CWC2_XL_HF_picked_ID.mzML" location="file:////nfs/wsi/abi/huperzin/sachsenb/OpenMS_IDE">
                                <cvParam cvRef="MS" accession="MS:1000569" name="SHA-1" value="18d5c837d459a07bfa4ebed1f9a15fecffe42b4a" />
                                <cvParam cvRef="MS" accession="MS:1000584" name="mzML format" />
                                <cvParam cvRef="MS" accession="MS:1000777" name="spectrum identifier nativeID format" />
                        </sourceFile>
                </sourceFileList>
```

or e.g.:
```
 <sourceFileList count="1">
                        <sourceFile id="sf_ru_0" name="Zeitz_SIP_13-II_020.RAW" location="file://C:/Users/sachsenb/Downloads/pwiz/../../Desktop/validation/Protein_SIP">
                                <cvParam cvRef="MS" accession="MS:1000569" name="SHA-1" value="bce42531503a8db2a5aad39e7860041c157d4994" />
                                <cvParam cvRef="MS" accession="MS:1000563" name="Thermo RAW file" />
                                <cvParam cvRef="MS" accession="MS:1000768" name="Thermo nativeID format" />
                        </sourceFile>
                </sourceFileList>
```

Which is pretty close to what we want.
One thing that I would like to change is to only reference mzML if possible as this will allow to carry over the name for visualization in KNIME / TOPPView etc.

**Comment by timosachsenberg** [comment]
What do you think. Should we, on reading a mzML file, change a reference to raw to point to the current mzML?
As this would only be done once (in the first OpenMS tool that encounters a reference to a raw file) I think it would work in most cases.

**Comment by mwalzer** [comment]
This might be one of the first things we could test with our workflow testing to come.

**Comment by timosachsenberg** [comment]
I think this has already been implemented... therefore I close this issue
