### ISSUE TITLE
ExperimentalSettings needs refactoring to match mzIdentML/mzTab/mzQuantML requirements

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1469]
This issue is intended to document the discussion on ExperimentalSettings refactoring and potentially interplay with ms_run modelling in our internal data structures.

Current members:

```
Sample  sample_
std::vector< SourceFile >   source_files_
std::vector< ContactPerson >    contacts_
Instrument  instrument_
HPLC    hplc_
DateTime    datetime_
String  comment_
std::vector< ProteinIdentification >    protein_identifications_
String  fraction_identifier_
```

**Comment by timosachsenberg** [comment]
related to https://github.com/OpenMS/OpenMS/issues/1468

**Comment by timosachsenberg** [comment]
I think it might be a good idea to factor out the MS run meta data (as e.g. in MzTab) and potentially others. But befor jumping horses we should check if this is part of mzML schema.

**Comment by timosachsenberg** [comment]
Currently Experimental settings is used by the MSExperiment's and MSQuantification.

**Comment by timosachsenberg** [comment]
Fields in mzTab:
```
ms_run[1-n]-location 
ms_run[1-n]-format (required if ms_run[1-n]-format reported)
ms_run[1-n]-id_format (required if ms_run[1-n]-format reported)
ms_run[1-n]-fragmentation_method
ms_run[1-n]-hash
ms_run[1-n]-hash_method
```

Minimum needed mandatory information: location of MS run 

```
best match:
std::vector< SourceFile >   source_files_
```

```
which stores:
String 	name_of_file_
String 	path_to_file_
double 	file_size_
String 	file_type_
String 	checksum_
ChecksumType 	checksum_type_
String 	native_id_type_
```

**Comment by mwalzer** [comment]
Well, I second that - back by the first implementations of mzq/mzid there was no support of changing    internal structures 'only' for the format - but I think this is not only a format issue but of important meta information for each level of analysis and reuse (as Timo listed all the different types).

**Comment by mwalzer** [comment]
mzML has an InstrumentConfiguration group defined. And our read and write of mzML uses ExperimentalSettings to cover that section. Already by the name one could agree these might be better be kept unconfused.
InstrumentConfiguration with things like:
'''<cvParam cvRef="MS" accession="MS:1000484" name="orbitrap" />'''
'''<cvParam cvRef="MS" accession="MS:1000029" name="sampling frequency" value="0" unitAccession="UO:0000106" unitName="hertz" unitCvRef="UO" />'''
ExperimentalSettings as in assay of mzq or AnalysisSampleCollection in mzid
'''<cvParam accession="MS:1002038" cvRef="PSI-MS" name="unlabeled sample"/>'''

**Comment by timosachsenberg** [comment]
I agree - this should probably also be taken out of ExperimentalSetting (also contact, hplc, date, comment, protein identification, etc.). 
Another possibility is that we rename ExperimentalSetting to something more meaningful (e.g. "MSRunMetaData") and put the other meta data also in there. So we have MSRunMetaData at the top which would include the Contact, InstrumentConfiguration etc.

**Comment by timosachsenberg** [comment]
Also ExperimentalSettings should not be a base class of MSExperiment

**Comment by mwalzer** [comment]
I concur with detaching it from MSExperiment
