### ISSUE TITLE
TOPPAS behaviour during crashes

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1473]
Multiple files can be analysed with a TOPPAS workflow. If one tool crashes during the execution of a single file, none of the results are written to the output. Could the results that have been successfully processed be written directly to the output instead?

**Comment by hendrikweisser** [comment]
I'm in favour of this. TOPPAS should either create files already at their eventual destination (why isn't this done already?) or copy temporary files to the output before exiting when an error occurs.

**Comment by hendrikweisser** [comment]
See also issue #555.

**Comment by lars20070** [comment]
It would make it considerably easier to figure out which fraction/file was responsible for the crash. As it is, one has to rerun the n fractions in n separate workflows again.
