### ISSUE TITLE
Reference from mzIdentML to mzML wrong

### ISSUE THREAD

**Issue by ypriverol** [OpenMS/OpenMS#1477]
@timosachsenberg @mwalzer We are processing a submission in PRIDE and the reference between the mzIndetML and mzML is wrong. It would be great to produce a python script to fix it. Example in this url 
   http://mab.to/CTicICLB6
   http://mab.to/LQT3HJQb1
 
The version of OpenMS that was used (1.9). Let me know if you need anything more from our side.

Regards 
Yasset

**Comment by hendrikweisser** [comment]
I think the version number 1.9 is wrong. For some reason OpenMS 2.0 writes `<AnalysisSoftware version="OpenMS TOPP v1.9" name="TOPP software" id="17557469891262375552">` to mzid.

**Comment by mwalzer** [comment]
I think https://github.com/OpenMS/OpenMS/pull/1869 solved that issue.

**Comment by lars20070** [comment]
+1

**Comment by mwalzer** [comment]
Sidenote on the sidenote regarding version number:
the handler uses ```VersionInfo::getVersion()``` and writes the correct version on my system.
But we should open another issue if the wrong version gets written in some setups.
