### ISSUE TITLE
Path to "share" directory possibly not set correctly

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1479]
I'm using a development build of OpenMS, from which I occasionally create installations (snapshots) for production. To do this I set "CMAKE_INSTALL_PREFIX" in the build configuration and run "make install". For my own uses I just create a local build using "make" (but "CMAKE_INSTALL_PREFIX" is still present in the configuration).

The problem is that the path to "OpenMS/share" is relative to "CMAKE_INSTALL_PREFIX". So the "share" for a local (development) build is the "share" of the installation - which might not be up to date (see e.g. https://github.com/OpenMS/OpenMS/pull/1474#discussion_r33136214 and the following comments).

I had a problem before where paths to "OpenMS/share" in the installation still pointed to the "share" in the development build, which led to strange errors. This was fixed, but apparently now the problem exists in the other direction.

I think setting the paths to "share" (etc.?) has to be handled differently in the case of "make" (use "share" from the source) and "make install" (use the extra copy of "share" that gets created during installation).

(As a quick fix, deleting the value of "CMAKE_INSTALL_PREFIX" in the build configuration, e.g. via "ccmake", sets "share" correctly for a local/development build.)

**Comment by cbielow** [comment]
I'd have to look up the internals of how the path to SHARE is incorporated into OpenMS binaries, but if my memory serves me correctly, its in the config.h, alas hard coded at build-time.
The usual procedure on linux is make && make install, so I don't see a way to solve the problem the way you describe (unless we rebuild upon make install -- which is highly unusual and a little wasteful?!) Maybe I get the facts wrong here -- correct me pls :)
The main problem here I think is: you are trying to use a single build tree for two purposes, i.e. deployment and development. Not a good idea. Why not use two build trees?
The only solution I can think of right now: use the ENV var "OPENMS_DATA_PATH" and set it according to your development requirements on your system, such that SHARE is found. If you ship the binaries for installation purposes you local ENV settings do not matter and the hard-coded config.h settings come into effect.

**Comment by hendrikweisser** [comment]
> unless we rebuild upon make install -- which is highly unusual and a little wasteful?!

I believe we do rebuild.

> Why not use two build trees?

Because one was enough. ;-)

> The only solution I can think of right now: use the ENV var "OPENMS_DATA_PATH" and set it according to your development requirements on your system, such that SHARE is found.

Thanks for the tip; I did not know about this.

So this isn't a huge problem because workarounds are available (delete "CMAKE_INSTALL_PREFIX" or set "OPENMS_DATA_PATH"). However I think there is still the possibility that if "CMAKE_INSTALL_PREFIX" is set, but only "make" is used, the OpenMS build will be broken because of references to a non-existing "share" directory (until "make install" is run).

**Comment by aiche** [comment]
> I believe we do rebuild.

No, we actually don't. 

> However I think there is still the possibility that if "CMAKE_INSTALL_PREFIX" is set, but only "make" is used, the OpenMS build will be broken because of references to a non-existing "share" directory (until "make install" is run).

This should not happen, since OpenMS will then probe for an alternative data path (i.e., `share` in your source folder).

The only problem you can encounter is the one you originally reported, using an outdated version of the share if your build tree points to an older installation. Solving this via the build system is quite hard since cmake targets (e.g., the OpenMS library) are not directly aware of the build command that was called. So getting some extra work done during `make install` that is directly related to building an existing target will get hacky. 

The only alternative I see is to always use a share relative to the executables. We use this solution on Mac OS X packages, since we have no fixed install path. Any opinions on that?

**Comment by hendrikweisser** [comment]
> The only alternative I see is to always use a share relative to the executables. We use this solution on Mac OS X packages, since we have no fixed install path. Any opinions on that?

I think this would be problematic, since the location of the "share" directory relative to "bin" is not the same for the local build and the installation. The local build gets built in a separate "build" directory, so the paths are "OpenMS/build/bin" and "OpenMS/share", whereas in the installation it's "OpenMS/bin" and "OpenMS/share".

**Comment by aiche** [comment]
> I think this would be problematic, since the location of the "share" directory relative to "bin" is not the same for the local build and the installation. The local build gets built in a separate "build" directory, so the paths are "OpenMS/build/bin" and "OpenMS/share", whereas in the installation it's "OpenMS/bin" and "OpenMS/share".

True but we currently also probe multiple options for the path and choose the first one that fits. But again, that is only an idea. Alternatively, we could add some sort of matching approach between the found share and the OpenMS version (e.g., embed some sort of sha1 to check if we work on the correct one) at least if we find one in the install path.

**Comment by hendrikweisser** [comment]
> True but we currently also probe multiple options for the path and choose the first one that fits. But again, that is only an idea.

Okay, then we could make "../share" (relative to "bin") the default option - which would work for any installation of OpenMS - and fall back to the absolute path of the source "share" - which would make it work for local builds. I quite like that.

**Comment by aiche** [comment]
Lets wait for some more feedback here as I'm not sure how this may impact deb packages etc.

**Comment by hroest** [comment]
should we do that? I just envision that we should also have an option to turn that off as we dont want on all debian systems to *always* check `../share` as I am sure *sometimes* there will be something unexpected there ...

**Comment by hendrikweisser** [comment]
This issue still persists, but maybe I'm the only one affected by it.
