### ISSUE TITLE
Undefined refrences when linking

### ISSUE THREAD

**Issue by s312569** [OpenMS/OpenMS#1483]
Hi

I'm trying to build on kubuntu 15 and get a linking error when I'm making OpenSwathWorkflow:

Linking CXX executable ../../bin/OpenSwathWorkflow
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::FileIO(std::string const&, int)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::operator bool() const'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Read(unsigned long, void*)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Write(unsigned long, int, void const*)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Read(unsigned long, int, void*)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Write(unsigned long, void const*)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::~FileIO()'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Close()'

Th libWm5 libraries are installed but I can't seem to get rid of this error after a day and a half of trying - any suggestions welcome!

Cheers
Jason

**Comment by grosenberger** [comment]
Hi Jason,

Wild Magic is always a bit tricky... Are you using the library provided by your distribution? Could you please try to build Wild Magic from OpenMS/contrib?

**Comment by s312569** [comment]
Yep was using the distributions libraries. Worked perfectly with the contrib. Should have followed the instructions ... 

Many thanks!

**Comment by cbielow** [comment]
sidenote:
seems like an API incompatability issue. Maybe we need to adapt the version-restrictions for WM during configure...

**Comment by sagitter** [comment]
>Yep was using the distributions libraries. Worked perfectly with the contrib. Should have followed the instructions ...

Which distribution?
Informing WM packagers is a wise choice.

**Comment by s312569** [comment]
that would make it more obvious that the contrib version should be used I guess. Will you be moving to geometric engines or keep maintaining a version of wm?

**Comment by s312569** [comment]
(k)Ubuntu 15.04  - libwildmagic5 5.13-1

Don't know a lot about it but it looks like wm isn't being updated as it is being ported to the geometric tools engine? (http://www.geometrictools.com/Downloads/Downloads.html)

**Comment by sagitter** [comment]
GTEngine should be a new era of WildMagic libraries and i think they are on testing for Linux; i talked about with upstream some time ago.
If libwildmagic5 5.13-1 on Ubuntu has "undefined reference" issues then you should inform Ubuntu folks about it with a bug ticket.

**Comment by s312569** [comment]
sweet - will do.

**Comment by sneumann** [comment]
I ran into the same issue and opened an issue at 
https://bugs.launchpad.net/ubuntu/+source/libwildmagic/+bug/1578222

I also found that ldd  ../../lib/libOpenMS.so | grep Wm5
	libWm5Mathematics.so.5 => /usr/lib/libWm5Mathematics.so.5 (0x00007fdd186ce000)
only links to libWm5Mathematics.so, but not Core. The libWm5Mathematics.so.5 
itself is not explicitly linked to libWm5Core.so
