### ISSUE TITLE
OpenMS appdata file

### ISSUE THREAD

**Issue by sagitter** [OpenMS/OpenMS#1484]
Hi all,

Can you add an appdata file (http://people.freedesktop.org/~hughsient/appdata/) to OpenMS source?

**Comment by cbielow** [comment]
like that:
https://github.com/cbielow/OpenMS/commit/507987081f1387c89167a684362a144a7e4cf6c9

??

Not sure I got the %id part correctly.
Does it matter where exactly the file resides?

Could others have a look and check the wording pls :)

**Comment by sagitter** [comment]
>Not sure I got the %id part correctly.
Does it matter where exactly the file resides?

There is no any ```OpenMS.desktop``` file. I see OpenMS source provides ```toppas.desktop``` and ```toppview.desktop``` and <id> tag is for "the installed .desktop file for the application".

So just one main ```?.desktop``` with related ```?.appdata.xml``` (they must be named with the same root); additionally, you can also make an ```?.metainfo.xml``` file. 
In Fedora we use these quick guide lines for appdata files: https://fedoraproject.org/wiki/Packaging:AppData

Thanks.

**Comment by cbielow** [comment]
mhh.. ok. So we should actually have two .appdata.xml files, one for TOPPView, the other for TOPPAS, right?!

**Comment by sagitter** [comment]
I think you could make a ```toppview.appdata.xml```, and a ```toppas.metainfo.xml``` as its extension.

**Comment by cbielow** [comment]
I added two appdata.xml's now. See #1489

**Comment by sagitter** [comment]
> I added two appdata.xml's now. See #1489

```name``` of xml files must be the same of related desktop file:

```toppview.desktop``` --> ```toppview.appdata.xml```
```toppas.desktop``` --> ```toppas.appdata.xml```

**Comment by cbielow** [comment]
so their name must be identical, but it does not matter what exactly it is?!
(because the executable is called TOPPView and not toppview)

**Comment by sagitter** [comment]
Yes. It's just a condition imposed, as http://people.freedesktop.org/~hughsient/appdata/ reports:

> Every software center that exists allows the user to look at screenshots and a long description of the application before it is installed. For most users it allows them to answer the question Do I want to install this application?
Traditionally in Linux distributions, we have none of this data for the vast majority of our desktop user-installable applications. To solve this, we have defined a new data file, which the upstream project can optionally translate using the same technique as GSetting schemas or Desktop files. Rather than create a new schema from scratch, we'll be using a subset of the AppStream metadata proposal. 

>Applications wishing to have long descriptions, screenshots and other useful things are required to ship one or more files in /usr/share/appdata/%{id}.appdata.xml. 

>The %{id} is the same name as the installed .desktop file for the application.

**Comment by cbielow** [comment]
yeah, ok.
I'm going to rename toppas.desktop and toppview.desktop to the correct upper-case. then the names are matching again.
thx.

**Comment by sagitter** [comment]
Just another commet: both screenshots are from Windows.
Better if you make a couple of them from a GNU/Linux system (i can make them for you).

**Comment by cbielow** [comment]
If you (or any other developer using Linux could do that) -- would be 
great. They should be somewhat identical in what is shown, since they 
are also embedded in the docs.



Am 7/1/2015 um 5:08 PM schrieb Antonio:

**Comment by sagitter** [comment]
Use these:

https://sagitter.fedorapeople.org/TOPPAS_simple_example_on_Linux.png
https://sagitter.fedorapeople.org/TOPPView_on_Linux.png

**Comment by cbielow** [comment]
According to http://people.freedesktop.org/~hughsient/appdata/,
the screenshots should be 16:9 (check) and not resized. However, since these images are used multiple times in the docs, they should not be full-screen sized, but rather something like
1440x900 (which is 16:10, but hey...).
Could you please re-make them, or should I rescale and/or crop?

**Comment by sagitter** [comment]
Ops! Sorry for the inconvenient.
I think 16:9 ratio is required to properly display all screenshots on the software center.

If you need screenshots in the docs, i can make them with different ratios and not full-screened.

**Comment by cbielow** [comment]
just one resolution (1440:900 (cropped to 16:9 if required) would be optimal.
Then there is no duplication of images and the URL is pointing to the official docs, i.e. we do not forget to update images (if required).

**Comment by sagitter** [comment]
Showing Projections Window on TOPPView seems prevent a good resolution setting:

https://sagitter.fedorapeople.org/TOPPAS_simple_example_on_Linux.png
https://sagitter.fedorapeople.org/TOPPView_on_Linux.png
https://sagitter.fedorapeople.org/TOPPView_w-out_projections_on_Linux.png

**Comment by cbielow** [comment]
I think it looks good. I've added the images.
