### ISSUE TITLE
OpenMS has significanceThreshold members in both PeptideIdentification and ProteinIdentification

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#1504]
OpenMS has significanceThreshold members in both PeptideIdentification and ProteinIdentification, but only one can apply. Also this would be invalid if score changes, though there is no chance to test.

**Comment by mwalzer** [comment]
I tend to see PeptideIdentification.significanceThreshold to be useless. Furthermore, such threshold is reflectable in mzid only on protocol level, i.e. applies on id runs following that specific protocol, i.e. one ProteinIdentification. Have PeptideIdentification.significanceThreshold deprecated?

**Comment by timosachsenberg** [comment]
I tend to agree though I don't know the original idea behind and would vote for deprecation.

**Comment by hroest** [comment]
is this fixed with #1505 now?

**Comment by mwalzer** [comment]
#1506 still open
