### ISSUE TITLE
OpenMS has no enduser-proof way to handle 'passed threshold' or not ids as contained in mzids

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#1506]
mzid has the attribute of pass_threshold, which is meant to maintain both evidence trace and analysis result.

**Comment by mwalzer** [comment]
https://github.com/OpenMS/OpenMS/pull/1505 solves this by reading all contents of the file and adding meta value for reading and using score and ProteinIdentification.significanceThreshold as passThresohld determination, defaulting on true. This sucks, as now evaluation code is contained in the file handler.

**Comment by mwalzer** [comment]
https://github.com/OpenMS/OpenMS/issues/1504 is also to be considered

**Comment by timosachsenberg** [comment]
I would not say it totally sucks as we currently leave it to the user if he wants to:
A. keep the complete evidence trace (e.g. without IDFilter)
B. only results (e.g. after IDFilter).
C. evidence trace and results (with ProteinIdentification.significanceThreshold set)
But I agree that this doesn't match perfectly to mzID. On the other hand, storing the complete evidence trace might be impractical and not even possible for some large/complex workflows.
