### ISSUE TITLE
MzTabExporter in KNIME tries to export tsv file but fails due to expected csv extension

### ISSUE THREAD

**Issue by weiclav** [OpenMS/OpenMS#1511]
Hi everybody,

I encountered the following warning message in MzTabExporter:
ERROR	 GenericKnimeNodeModel         	 Failing process stdout: [Warning: Unknown parameter 'MzTabExporter:1:in' in 'C:\Users\...\AppData\Local\Temp\MzTabExporter1281319938\params.ini'!, Invalid parameter: Invalid output file extension 'C:\Users\...\AppData\Local\Temp\....\knime_fs-MzTabExporter_0_33-16265\000\000\MzTabExporter_0\analysis.tsv'. Valid file extensions are: 'csv'.]
ERROR	 GenericKnimeNodeModel         	 Failing process stderr: []
ERROR	 MzTabExporter                 	 Execute failed: Failed to execute node MzTabExporter

Part of the log if debug set to level 2:
Error occurred in line 1299 of file ..\..\..\OpenMS\src\openms\source\APPLICATIONS\TOPPBase.cpp (in function: <unknown>) !]

If I process the same idXML file using TOPPAS it works and produce valid csv file.

Knime version: 2.11.3
OpenMS within KNIME: 2.0.0.201507092026

Am I missing something?

Thanks for your response!
David

**Comment by timosachsenberg** [comment]
Thanks for reporting. I think that has been recently changed in OpenMS but not yet moved to our KNIME implementation. I will check how we can fix this.

**Comment by timosachsenberg** [comment]
Coud you try to remove and readd the MzTabExporter node? .tsv seems to be the correct extension right now. If that doesn't help could you try to update OpenMS in KNIME and then remove/readd the node and try again?

**Comment by weiclav** [comment]
I created new workflow which includes only input node and MzTabExporter and it do not work. I am not able to update to greater version (still have 2.0.0.201507092026), so maybe I am using wrong site for software installation? Is this the right one: http://update.knime.org/community-contributions/trusted/2.11 ?

Thanks!
David

**Comment by timosachsenberg** [comment]
Your version seems to be ok. I tried it with the identical version and it generates the .tsv file containing the exported MzTab. (I have: Trusted Community Contributions (2.11) - http://tech.knime.org/update/community-contributions/trusted/2.11 configured in KNIME)

If you updated from an old pipeline it might be that it is still configured for the file type "csv" but removing and readding it should solve the problem.
What does it say if you right click->configure your MzTabExporter node? It should say "tsv"  in the tab "OutTypes"  for the port MzTabExporter.1.out
Do you still get the same error message (should be slightly different now)

**Comment by weiclav** [comment]
OutTypes says .tsv, ini file also says tsv. Only place where I see "csv" is the log window as reported in the first post... The log is the same for old and newly added MzTabExporter node. I tried this also on another PC where I updated OpenMS before the test and the behavior is also the same.

Can you please check whetehr this could mean something? It is part of the log that might get lost from discussion: "Error occurred in line 1299 of file ..\..\..\OpenMS\src\openms\source\APPLICATIONS\TOPPBase.cpp (in function: <unknown>) !]"

But if it works fine on your site, then I am probably doing something wrong here systematically. Is there some "update procedure" necessary after I update OpenMS within KNIME? Restart of KNIME was done, but not the whole PC was restarted. MzTabExporter node is located right after IDFilter node and idXML.

Thanks for your support!
David

**Comment by timosachsenberg** [comment]
This is kind of strange. Can you "Export" the KNIME workflow in a zip file. I will try to run it here.

**Comment by weiclav** [comment]
The workflow is pretty easy, only Input file node and MzTabExporter, so I included also idXML.

Here you can downloaded it [here] (https://filesender.cesnet.cz/?vid=1e8f49ed-51ae-fa49-da28-000030043c34).

Let me know if you need the overall workflow I used to create the idXML, but because the enclosed workflow (input node and mztabexporter node only) does not work on any idXML I tested, it sound to me like it is general behavior for my environment (Win7 and Win Server 2012).

I will try to install KNIME and OpenMS from scratch on another system and see how it performs...

Thanks,
David

**Comment by weiclav** [comment]
Hi,

any new on this topic. Today I tried updated version and the behavior including error reporting seems to be the same.

Do I miss something, or it is still under investigation?

Thanks in advance for info.

Thanks a lot!
David

**Comment by timosachsenberg** [comment]
Hi,
I am sorry but I could not reproduce it. @FabianAicheler could you try to reproduce it?

**Comment by FabianAicheler** [comment]
Also got this error, trying stuff to find the cause

**Comment by jpfeuffer** [comment]
Hi,

Might be a stupid question but it is not too obvious:
Did you already try to remove and re-add the node? As this has to be done to get the newest version of it.

**Comment by FabianAicheler** [comment]
Removing and readding didn't help for me.

**Comment by timosachsenberg** [comment]
my payload contains the newest version
```
No options given. Aborting!
MzTabExporter -- Exports various XML formats to an mzTab file.
Version: 2.0.0 Jul 23 2015, 22:43:11, Revision: 0813bbf
```

**Comment by timosachsenberg** [comment]
Ok we might have a hint.
The nightly version OpenMS 2.0.0.201507231102 appears in both the nightly KNIME builds as well as the trusted builds.
This might mean that the payload for the trusted (main builds) are taken from the release version but the CTD files from the nightly develop.

**Comment by timosachsenberg** [comment]
Quick update: this seems to be the case. Let's see if this resolves the issue when it is fixed.

**Comment by timosachsenberg** [comment]
Hi @weiclav could you check if we resolved the issue by updating your OpenMS in KNIME once again?

**Comment by weiclav** [comment]
The issue looks resolved. KNIME now showes older (201504151637) OpenMS version in trusted build.

Thanks a lot for your support!

David
