### ISSUE TITLE
Duplicated specificity group in mascot generated idXML file

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1512]
Hi,
I encountered a Mascot created idXML file that contains:
```
                <VariableModification name="Deamidated (NQ) (NQ)" />
```
This seems very wrong to me. Any idea?
Related to #387

**Comment by timosachsenberg** [comment]
@hendrikweisser any comments on that one?

**Comment by hendrikweisser** [comment]
I've looked at some of our Mascot search results (from MascotAdapterOnline) and there it looks fine:
`<VariableModification name="Deamidated (NQ)" />`

How and when was that problematic file created?

**Comment by timosachsenberg** [comment]
The files was created by a user... I try to get some additional information

**Comment by hendrikweisser** [comment]
Any progress on this one?

**Comment by timosachsenberg** [comment]
no information obtained .. close for now
