### ISSUE TITLE
TOPPAS: Visualization

### ISSUE THREAD

**Issue by zonlai** [OpenMS/OpenMS#1513]
Dear Developers,

While I am becoming more and more familiar with the OpenMS workflows and interfaces, I would like to suggest two things to improve on overall UX of TOPPAS and TOPPView:
1. Is it possible to color code the workflow-boxes according to the TOPP tools category?
2. Same goes for idXML files in TOPPView. Different colored fonts would better facilitate visualization while switching between multiple idXML layers.  

Cheers, Weng

**Comment by cbielow** [comment]
duplicate of #1515 and #1516
