### ISSUE TITLE
Spectramerger crash

### ISSUE THREAD

**Issue by ChristianPichlo** [OpenMS/OpenMS#1514]
Hello everybody,

thanks for the fast fixing the seg fault error of the Spectramerger (#1493). 
Unfortunately, I realized that the Spectramerger still sometimes crashes during averaging the profile spectra. Just before the crash the following lines are printed into the progress output: 
"Progress of 'averaging profile spectra of MS level 1':

  1.52 %               
  3.41 %               
==============================================================================
13:01:59 ERROR: SpectraMerger crashed!"

It seems that the crashes are not depent on the operating system (Windows/OS X). However, depending on the computer I used for the analysis, I observed different time points where the SPM crashes (3 - 40 %). It would be great if you could take a look onto this phenomon.

I uploaded a section of a dataset where i got crashes in my dropbox [1] as well as a workflow for testing [2]

[1] https://www.dropbox.com/s/wxmi4xgsxyxzo3q/20111214_EXQ0_NiKu_SA_HeLa_L-H_1-5_20002300.mzML?dl=0
[2] https://www.dropbox.com/s/9a2jch8vdp8rb60/test2.toppas?dl=0

**Comment by timosachsenberg** [comment]
still critical?

**Comment by lars20070** [comment]
@ChristianPichlo Does the crash still occur?

If yes, can you please provide an RT slice of the dataset and the workflow? The links are dead.

**Comment by timosachsenberg** [comment]
I close this for now as we can't confirm it for the current version
