### ISSUE TITLE
feature request TOPPView: changing font colour in idXML layers

### ISSUE THREAD

**Issue by zonlai** [OpenMS/OpenMS#1516]
Dear Developers,

Is it possible to have options for different colored fonts for opening idXML files in TOPPView? It would better facilitate visualization while switching between multiple idXML layers. 

Cheers,
Weng

**Comment by lars20070** [comment]
@ChiayiChen requested this feature as well.

@cbielow Any chance of changing the colour of `idXML` layers as is already possible for `featureXML` and `consensusXML`?
