### ISSUE TITLE
Java not found / time out

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1517]
Workflows with multiple MSGFPlusAdapter nodes crash occasionally when run with multiple threads in Windows Server 2012. The auxiliary MS-GF+ databases (*.canno etc) have been generated in previous runs. Both java and MSGFPlus.jar are installed.

![screenshot from 2015-07-15 11 01 08](https://cloud.githubusercontent.com/assets/6149805/8694672/c3d12ba2-2ae0-11e5-9d18-e81feb294149.png)

**Comment by lars20070** [comment]
Could this [1] also occur, when there is no space in the Java heap for a further process?

[1] https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MSGFPlusAdapter.cpp#L420

**Comment by hendrikweisser** [comment]
> Could this [1] also occur, when there is no space in the Java heap for a further process?

Every time you invoke "java" it creates a new process. The memory isn't shared. (I think.)

**Comment by lars20070** [comment]
Ok. Then I do not understand why Java cannot be run.

**Comment by lars20070** [comment]
After increasing the heap size (-java_memory), the crashes no longer occur. So the reported crashes seem to be related to the heap.

**Comment by lars20070** [comment]
Problem re-occurring despite re-sized heap size.

**Comment by lars20070** [comment]
@timosachsenberg Here [1] you are checking for the Java version. This check often times-out [2] on our server, which leads to `MSGFPlusAdapter` crashes. Can we call `waitForFinished(-1)`, so it no longer times-out?

[1] https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/SYSTEM/JavaInfo.cpp#L45
[2] http://doc.qt.io/qt-4.8/qprocess.html#waitForFinished

**Comment by timosachsenberg** [comment]
Why does it take longer than half a minute?

**Comment by lars20070** [comment]
I haven't figured out the why. But when the server is busy, it's common that any process (login, Word, TOPPView) can take longer than a minute.

**Comment by timosachsenberg** [comment]
I would say the problem should be addressed on the server side. Wait for ever is no option in my view and any larger constant not sufficiently justified

**Comment by hendrikweisser** [comment]
> Wait for ever is no option in my view and any larger constant not sufficiently justified

Could "wait forever" actually happen? If Java is installed, the "java -version" call should return eventually. If it's not installed, it should return pretty much immediately. Or am I overlooking anything?

**Comment by timosachsenberg** [comment]
Sure - e.g. if your server waits for ever

**Comment by lars20070** [comment]
I agree with @timosachsenberg. It's a server problem. Hope some fixes from our server admin resolved it. - If the problem does not re-occur, let's change the error message to "Java not found or time-out." and then close this issue.

**Comment by lars20070** [comment]
Just an update. If the server CPU is at 100% and a new MS-GF+ adapter process is started, the time out related crash still occurs. 

QProcess : Destroyed while process is still running. [1]

I am no Windows expert (for sure). Can we avoid that a new process is started, when CPU is already at 100% ?  We can for sure not check by hand, that we never touch the 100%.

[1] http://stackoverflow.com/questions/14504201/qprocess-and-shell-destroyed-while-process-is-still-running

**Comment by lars20070** [comment]
Memory or Swap appear not to be the problem.

**Comment by hendrikweisser** [comment]
How about adding an advanced parameter to configure the wait time for the Java check? Or just to toggle between waiting for 30 seconds or waiting forever? Or to skip the Java check altogether?

**Comment by cbielow** [comment]
We can check, but IMHO that goes way too far and might actually be 
counter-productive.

What if CPU load is only 99% because there is inaccurate data?! How do 
you count mutli-CPU systems and virtualization?! etc etc etc

It's not OpenMS' job to take care of that. If the user has problems with 
system availability, he needs to either scale up or use a scheduling 
system for distributed computing and whatnot...

Everything we do is a hack. Don't waste your time please.



Am 8/13/2015 um 4:55 PM schrieb Lars Nilse:

**Comment by lars20070** [comment]
I would prefer to just change some Windows server settings.
But if there are no such settings, @hendrikweisser suggestion is the only solution I see.

Right now the OpenMS workflows are not usable due to the timeout crashes.

**Comment by hendrikweisser** [comment]
> I would prefer to just change some Windows server settings.

Is there a way to set the priority of a process on Windows (à la "nice" on UNIX)?

Otherwise I think adding an advanced flag to skip the Java check would be useful.

**Comment by cbielow** [comment]
one can set the priority of a process using a Windows API, but thats overkill.

And how would skipping the check help? If the system is that busy , how can it possibly run MSGF afterwards?!

**Comment by hendrikweisser** [comment]
> And how would skipping the check help? If the system is that busy , how can it possibly run MSGF afterwards?!

The system may only be busy momentarily. The search takes a long time anyway, so you don't care if it takes a bit longer for the system to schedule the process. But the Java check will fail if it doesn't run within 30 seconds.

**Comment by timosachsenberg** [comment]
I agree with Chris. If you really want to force execution by waiting infinitly you can use the recently introduced -force flag common to all TOPP tools

**Comment by lars20070** [comment]
Sounds good, @timosachsenberg. I will give the `-force` flag a go.

**Comment by timosachsenberg** [comment]
So far it is not used so just query it and set the timeout accordingly.
