### ISSUE TITLE
Refactoring of code for applying RT transformations and aligning maps

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1523]
The code for applying retention time transformations - library class MapAlignmentTransformer, TOPP tool MapRTTransformer - has some problems that should be resolved:
- MapRTTransformer takes multiple inputs, but there is no interaction between them. The tool should just take one input (data + transformation) in order to avoid unnecessary complexity.
- Similarly, there are API functions in MapAlignmentTransformer that transform multiple inputs at once (`transformPeakMaps`, `transformFeatureMaps`, `transformConsensusMaps`, `transformPeptideIdentifications`). These are just for-loops wrapped around the transformation functions that actually do the work for a single input, with additional checks that the numbers of input data and transformation descriptions match. As these functions aren't commonly used, they should be removed.
- The worker functions in MapAlignmentTransformer are named according to their input data types: `transformSinglePeakMap`, `transformSingleFeatureMap`, `transformSingleConsensusMap`, `transformSinglePeptideIdentification` (the last actually transforms multiple peptide IDs). They should be turned into overloaded functions with the same name, so they can be used in template functions that work for multiple data types.

Related:
- There is set of helper functions in "src/openms/include/OpenMS/APPLICATIONS/MapAlignerBase.h", resulting from the earlier split of the MapAligner into separate tools. At least two of these functions are only used by a single TOPP tool, so they should be moved directly to the respective class: `commonMain` in MapAlignerSpectrum and `handleReference_` in MapAlignerIdentification.

**Comment by hendrikweisser** [comment]
The base class MapAlignmentAlgorithm can be removed, too. The derived algorithms (MapAlignmentAlgorithmIdentification, MapAlignmentAlgorithmPoseClustering, MapAlignmentAlgorithmSpectrum) are no longer created via a factory interface, and - maybe more importantly - they don't even implement a common interface any more.

**Comment by timosachsenberg** [comment]
+1

**Comment by hendrikweisser** [comment]
Fixed in #1531.
