### ISSUE TITLE
FeatureLinkerLabeled should provide parameter to link features without charge (z=0)

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1525]
FeatureFinderMetabo reports features with charge 0, for example [1]. For this reason, features cannot be linked.

Reported by Tim Fallon tfallon@mit.edu on the OpenMS mailing list on 22/07/15.

[1] https://gist.github.com/lars20070/39dc9ae79ad4372e77da

**Comment by lars20070** [comment]
It seems charge zero was reported, since only a single mass trace was found.

**Comment by hendrikweisser** [comment]
> For this reason, features cannot be linked.

Does that make sense? Shouldn't features be linkable if their charges match (even if both are zero)?
Maybe FeatureLinkerLabeled should be changed, not FeatureFinderMetabo.

**Comment by timosachsenberg** [comment]
I agree with @hendrikweisser

**Comment by lars20070** [comment]
The FeatureLinkerLabeled has the parameter mz_pair_dists. Its defined as mz shift for 1+ charge states, so effectively the mass shift m. I think we should rename this mass_pair_dists. The mz shifts are then calculated from the charge of the feature.

As discussed with @timosachsenberg on the phone, the FeatureLinkerLabeled could also get an additional flag assume_charge_0_is_charge_1. Guess that's roughly what @hendrikweisser has in mind.

**Comment by hendrikweisser** [comment]
> I think we should rename this mass_pair_dists.

How about just "mass_shift", which is something that every biologist understands? (Similarly, rename "rt_pair_dist" to "rt_shift".)

**Comment by lars20070** [comment]
+1 for mass_shift and rt_shift

**Comment by hroest** [comment]
wouldnt it make sense to treat charge zero as a wildcard and allow it to link to any other charge? E.g. to only allow it to link to features with charge one is quite restrictive, what about features of charge two where only one mass trace can be found?

**Comment by timosachsenberg** [comment]
Yes that would be a good option. But then we need e.g. to specify a range of charges that are tested.

**Comment by cbielow** [comment]
Actaully, charge 2 is much more likely for tryptic peptides,  but 3 or 4 are also possible . So +1 for wildcard
-- 
Sent via mobile phone.

Am 22. Juli 2015 22:03:05 MESZ, schrieb Hannes Roest <notifications@github.com>:

**Comment by lars20070** [comment]
In this case, it's metabolites not peptides.

+1 for wildcard with the possible charge range as advanced parameter
