### ISSUE TITLE
cant build pyopenms

### ISSUE THREAD

**Issue by MariusDieck** [OpenMS/OpenMS#1527]
Hi,
i am currently trying to build pyopenms on top of openms, however when i run "make pyopenms" in OpenMS-build this happens:

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make[3]: *** [src/pyOpenMS/CMakeFiles/pyopenms] Fehler 1
make[2]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/all] Fehler 2
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/rule] Fehler 2
make: *** [pyopenms] Fehler 2

More:
http://pastebin.com/1m5fL4iF

I am running Linux Mint 17.2 and i build openms from develop branch

Greets

*edit
The problem does not appear if i use master branch, so i guess this can be closed except you want to look deeper into this

**Comment by timosachsenberg** [comment]
@jpfeuffer might be related to changes you introduced to Residue

**Comment by jpfeuffer** [comment]
Yes, I guess that is the case. I have to remove the corresponding python bindings.

**Comment by hroest** [comment]
I wonder why we dont have the error messages on cdash any more: http://cdash.openms.de/buildSummary.php?buildid=136701 -- where did they go?

**Comment by MariusDieck** [comment]
Besides the building problem... I am currently doing some performance tests with pyOpenMS, will using the master branch instead of the Development branch decrease the performance (by more than like 5-10%)

**Comment by hroest** [comment]
Dear Marius

some questions

- what are your actual performance tests, e.g. what are you trying to measure?
- do you build with Debug or Release mode?
- note that Master refers to the latest release and is currently ca 600 commits behind development
- there were a few improvements in the XML parsing which are described here http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0125108 and did not make the cut for the latest release, so they are only present in the development branch - see also issue #1312  and all related issues mentioned there

**Comment by OberstHorst** [comment]
I essentially want to test the sequential parsing speed of pyOpenMS like you did on the paper mentioned above (the TIC calculator) with different methods (streaming, indexed). I thought that these methods are only available in 2.0. I dont know if debug or Release... i just used git clone to get the master branch and then build it from there on as you suggest in your documentation.

**Comment by hroest** [comment]
@MariusDieck I have now merged #1533 which fixes the compilation problem

**Comment by hroest** [comment]
@OberstHorst yes, these methods are only available in 2.0 but there have been some additional improvements since the release as we continually work to improve the code and make it faster. 

When you compile it, there is an cmake option called `CMAKE_BUILD_TYPE` which you can set to `Release` to get the fastest speed

if you want the newest code, please clone the `develop` branch and *not* the `master` branch

**Comment by MariusDieck** [comment]
Okay i could compile and install it now... Thanks for your help. According to your documentation CMAKE_BUILD_TYPE is Release by default, is that still correct?

**Comment by hroest** [comment]
Great! 

I believe that is the case, yes. If unsure, you can check with `ccmake .` to see all the config parameters.
