### ISSUE TITLE
TOPPView: entire consensusXML not shown when zoomed out

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1528]
Even when zoomed out totally, this small consensusXML file [1] cannot be viewed in TOPPView. Maybe a small margin could be added, when opening featureXML or consensusXML in TOPPView. 

Reported by Tim Fallon tfallon@mit.edu on the OpenMS mailing list on 23/07/15.

<img width="640" alt="toppview" src="https://cloud.githubusercontent.com/assets/6149805/8845118/33677804-311c-11e5-8829-aae5bfbd8993.png">

[1] https://gist.github.com/lars20070/a289c9dc7b52211f931b

**Comment by cbielow** [comment]
#1607 is merged. Closing this issue as solved.
