### ISSUE TITLE
ModificationsDB logic on terminal modification selection gives inconsistent behavior

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1530]
calling 
```
ModificationsDB::getInstance()->getTerminalModification("Carbamyl", ResidueModification::N_TERM);
```
results in:
```
ModificationsDB::getModification: more than one modification (Carbamyl) found, picking first one (Carbamyl (C),Carbamyl (M),Carbamyl (N-term),Carbamyl (Y),Carbamyl (T),Carbamyl (R),Carbamyl (K),Carbamyl (S),)
```
It should imho pick Carbamyl (N-term). 

Other (i.e. non-terminal modifications) should only be picked if no terminal modification exists.

**Comment by mwalzer** [comment]
I think the (X-term) suffix notation is younger than most of the code ... but I concur.

**Comment by timosachsenberg** [comment]
@hendrikweisser is this fixed?

**Comment by hendrikweisser** [comment]
Yes, should be fixed. If you query ModificationsDB with a term specificity, e.g. using `getModification`, it will now only consider results with exactly that term specificity.
