### ISSUE TITLE
evaluate appveyor for CI on windows

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1534]
http://www.appveyor.com/

**Comment by cbielow** [comment]
Very interesting finding.

  1 CPU core and 1.75 GB of RAM with 40min of build time could be 
problematic and we might need to split the build or run without 
optimization etc...

Nevertheless, this should be doable and a big help in reducing Windows 
nightly build errors.

Am 7/27/2015 um 10:02 AM schrieb Timo Sachsenberg:

**Comment by timosachsenberg** [comment]
See e.g. https://github.com/mamedev/mame for a project that uses both travis and appveyor in parallel

build cache seems to be restricted to 100 mb but might be extended by writing an email.

**Comment by hendrikweisser** [comment]
Is this still under consideration? If not, close ticket?

**Comment by hroest** [comment]
we have jenkins up and running now, so I dont think we need this

**Comment by hroest** [comment]
also probably Azure would be a better option: https://github.com/OpenMS/OpenMS/pull/3736
