### ISSUE TITLE
sequence whitelist in IDFilter missing

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1535]
In IDFilter, one can search for particular proteins with an accession whitelist. The equivalent whitelist for sequences is missing.

**Comment by hendrikweisser** [comment]
What's the relationship between this issue and #1536?

**Comment by hendrikweisser** [comment]
I believe you could use a FASTA file containing all peptides you want to keep together with "-whitelist:proteins" and "-whitelist:by_seq_only" to accomplish this, at least for exact matching of peptide sequences.

**Comment by lars20070** [comment]
#1535 is a feature request for a sequence whitelist. A fasta file is too cumbersome, see also #1268.

#1536 is about an extended functionality of sequence whitelists. In most cases, I do not need the supersequences but the exact matching sequence.
