### ISSUE TITLE
Invalid mzML written in test mode

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1538]
TOPP tools (in test mode, i.e. called with "-test") may create invalid mzML files due to strings that are not properly XML-encoded. In particular, something like this is written in several TOPP test files:
```
<sourceFile id="sf_ru_0" name="FileConverter_1_input.mzData" location="<TEST_DATA_PATH>">
```
The "<" and ">" in "\<TEST_DATA_PATH>" are not properly encoded ("&lt;", "&gt;").

I have not checked whether this could also happen without the test mode, when the path to the source file contains special XML characters.

**Comment by hroest** [comment]
have you looked at issues #24 and the PR #949 #955 there are already functions to do this, so best it would be a 1-line fix

**Comment by hroest** [comment]
this is actually not true, see https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FORMAT/HANDLERS/MzMLHandler.h#L3646 where the location is XML encoded. The only thing that happened is that a few of our *test* files to compare output are actually invalid XML, e.g. `src/tests/topp/FileMerger_4_output.mzML` is invalid XML. However, the output produced by `ctest -R FileMerger_4` is valid xml
