### ISSUE TITLE
clang tests do not run any more

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1543]
ever since #1491 do the clang tests only include 30 tests and do not run all tests any more. Specifically the issue occurs since 6b5cae35ddfae1134a9f8c8bf3b39c06fb5972fd

compare the following travis builds:

- https://travis-ci.org/OpenMS/OpenMS/builds/69192813
- https://travis-ci.org/OpenMS/OpenMS/builds/69243826

**Comment by cbielow** [comment]
fixed via #1543
