### ISSUE TITLE
Memory usage of mzIdentML to idXML conversion

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1548]
I'm trying to convert a large (1.1 GB) mzid file from an MS-GF+ search to idXML with IDFileConverter. The process has been running for almost one hour now and is using upwards of 16 GB of memory. I've run IDFileConverter with "-debug 10" in the hope of some diagnostic output, but all I got were these messages early on:

> Converting from mzid: you might experience loss of information depending on the capabilities of the target format.
> No retention time found for 'SpectrumIdentificationResult'

Does anyone have an explanation for why this conversion would use so much memory (and take so long)?

**Comment by hendrikweisser** [comment]
The conversion finished after 1:37 hours, using up to ~18 GB RAM. (The final idXML is 684 MB big and contains ~345,000 peptide hits for ~76,000 spectra.)

Interestingly, MSGFPlusAdapter used below 8 GB of RAM for the search and the conversion of the results to idXML (indirectly, via conversion of mzid to a tabular text format).

**Comment by mwalzer** [comment]
The explanation is the DOM parsing. Building the tree for such a huge file is very memory consuming. And most probably swapping will do its part in making it so slow.

Stream parsing is in the making.

**Comment by hendrikweisser** [comment]
> Stream parsing is in the making.

Cool. Good to see that this you're working on this.

**Comment by hendrikweisser** [comment]
There is a branch for parsing mzid using SAX now:
https://github.com/OpenMS/OpenMS/tree/mzid-sax-parser

**Comment by hroest** [comment]
@mwalzer any progress on the sax parser?

**Comment by hroest** [comment]
@timosachsenberg @mwalzer maybe also a good project for a hacker task to work as it is fairly technical and easy to show success

**Comment by timosachsenberg** [comment]
agree. I'll add the hacktoberfest label which we may (or not?) change to something else

**Comment by timosachsenberg** [comment]
@hroest or @hendrikweisser this could be a good candidate for a "Project" that we could use for google summer of code or student projects / thesis. The student would basically need to turn the prototype SAX parser into a fully tested, mzIdentML 1.2 compliant SAX parser.
I started by introducing a new label "Project" for issues; https://github.com/OpenMS/OpenMS/issues/2258
and these can be linked from the new GitHub "Projects" feature I mentioned in one of my Emails.
What do you think?

**Comment by hroest** [comment]
yes, I agree as I said it will be pretty easy for a student as it is a well defined project that can be tested whether it works or not
:+1:

**Comment by hroest** [comment]
another reason for this could be that the DomHandler is full of memory leaks, I see `XMLString::transcode` everywhere without the resulting memory being properly handled! 

```
$ grep -R XMLString::transcode src/openms | grep -v static | cut -f 1 -d ":" | uniq -c
      3 src/openms/source/FORMAT/VALIDATORS/XMLValidator.cpp
     34 src/openms/source/FORMAT/HANDLERS/MzXMLHandler.cpp
      4 src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp
      6 src/openms/source/FORMAT/HANDLERS/IndexedMzMLDecoder.cpp
      4 src/openms/source/FORMAT/HANDLERS/MzMLSpectrumDecoder.cpp
    360 src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
      1 src/openms/include/OpenMS/FORMAT/HANDLERS/XMLHandler.h

$ grep -R XMLString::release src/openms | grep -v static | cut -f 1 -d ":" | uniq -c
      3 src/openms/source/FORMAT/VALIDATORS/XMLValidator.cpp
      2 src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp
      8 src/openms/source/FORMAT/HANDLERS/IndexedMzMLDecoder.cpp
     10 src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
      1 src/openms/include/OpenMS/FORMAT/HANDLERS/XMLHandler.h
```

360 instances of grabbing memory from xerces but only 10 instances of releasing that memory? does not sound good...

**Comment by jpfeuffer** [comment]
In that regard I found some lines that might! be of a similar nature when investigating Xerces issues.
See my initial comment in https://github.com/OpenMS/OpenMS/issues/2556

**Comment by mwalzer** [comment]
That grep command is turning a blind side to *quite some* occurrences! E.g. in comments and in unused code. The actual number is way less dramatic (~55, details follow). Still some, but I can already tell you that this is not the culprit. It is rather the building of the DOM tree itself. I did some crude estimates/measurements on what the mem. cost is a while back and the prerequisite to build the complete tree seems to take the bulk of consumed memory in basic operation. 

But @hroest comment raises a valid point, that is there are unreleased instances, which is always bad, and what to do with unused code.  
Regarding 1st, I already started a [branch cleaning out the handler](https://github.com/mwalzer/OpenMS/tree/feature/mzid-dom-memfix), but regarding 2nd, I have not fully removed the writing part of the DOM handler yet, but I would consider that a failed experiment and go on removing the last bits of writing with DOM if no-one else wants a take on that?

**Comment by mwalzer** [comment]
Now, the number of transcodes in _use_ is about this:
```
$ grep -R XMLString::release src/openms | grep -v static | cut -f 1 -d ":" | uniq -c
      1 src/openms/include/OpenMS/FORMAT/HANDLERS/XMLHandler.h
      3 src/openms/source/FORMAT/VALIDATORS/XMLValidator.cpp
      8 src/openms/source/FORMAT/HANDLERS/IndexedMzMLDecoder.cpp
      2 src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp
     54 src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
$ grep -R XMLString::transcode src/openms | grep -v static | cut -f 1 -d ":" | uniq -c
      1 src/openms/include/OpenMS/FORMAT/HANDLERS/XMLHandler.h
      3 src/openms/source/FORMAT/VALIDATORS/XMLValidator.cpp
      6 src/openms/source/FORMAT/HANDLERS/IndexedMzMLDecoder.cpp
      4 src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp
      4 src/openms/source/FORMAT/HANDLERS/MzMLSpectrumDecoder.cpp
     34 src/openms/source/FORMAT/HANDLERS/MzXMLHandler.cpp
     56 src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp


```

**Comment by hroest** [comment]
this already looks much better and it would be great if we could move to the SAX handler at some point!

**Comment by hroest** [comment]
> There is a branch for parsing mzid using SAX now:
> https://github.com/OpenMS/OpenMS/tree/mzid-sax-parser

@hendrikweisser what is the status of this? Could at least the code be partially merged (without yet calling it
