### ISSUE TITLE
Validation of mzIdentML not supported out of the box

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1549]
FileInfo (with the "v" option) and XMLValidator don't yet support validation of mzIdentML out of the box. They give this message:
> Validating mzid file
> Aborted: Validation of this file type is not supported!

Validation works if the mzIdentML schema is passed explicitly to XMLValidator via the "schema" option.

**Comment by mwalzer** [comment]
Yeah, there was the consent that the only tool having mzid for the release was the IDFileConverter, because otherwise it would break the knime workflows. Which it turns out doesnt, but the OutputTypes tab at each relevant knime node has to be fitted.

**Comment by lars20070** [comment]
Can I temporarily switch on `mzid` validation? As input file type, `mzid` is already allowed.
