### ISSUE TITLE
[KNIME] Invalid Node name

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#1567]
It seems like "_" in a KNIME node is not allowed. Since the names are generated from the CTD files:
Is it possible to change LowMemPeakPickerHiRes_RandomAccess to LowMemPeakPickerHiResRandomAccess or similar?

Error:
[java] Invalid ctd-format: LowMemPeakPickerHiRes_RandomAccess.ctd
[java] Reason: The node name "LowMemPeakPickerHiRes_RandomAccess" in file "/Users/aiche/KNIME_PACKAGING/assembly/final/descriptors/LowMemPeakPickerHiRes_RandomAccess.ctd" is invalid.

**Comment by hendrikweisser** [comment]
Fixed in #3062.
