### ISSUE TITLE
[KNIME] FeatureFinderMultiplex crashes in OpenMS 2.0 installation

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1570]
Affects release version before and after yesterdays update.
Tested on mac and win

**Comment by timosachsenberg** [comment]
Same for nightly

**Comment by timosachsenberg** [comment]
```
Failing process stdout: [Progress of 'loading spectra list':, , -- done [took 0.36 s (CPU), 0.35 s (Wall)] -- , Progress of 'loading chromatogram list':, , -- done [took 0.00 s (CPU), 0.00 s (Wall)] -- , , , mass shift 1:    0  , , Progress of 'filtering LC-MS data':, ,   2.07 %               ,   15.17 %               ,   28.28 %               ,   41.72 %               ,   53.10 %               ,   64.14 %               ,   75.86 %               ,   88.28 %               ,   100.00 %               , -- done [took 8.12 s (CPU), 8.17 s (Wall)] -- , Progress of 'clustering filtered LC-MS data':, , -- done [took 2.72 s (CPU), 2.74 s (Wall)] -- ]
```

**Comment by timosachsenberg** [comment]
seems like it crashes after successful execution

**Comment by jpfeuffer** [comment]
Is there a version where it worked?

**Comment by lars20070** [comment]
I guess you mean 100%. That means the filtering step is finished. It might crash during the clustering step, or generating the output.

> On 20 Aug 2015, at 17:29, Timo Sachsenberg <notifications@github.com> wrote:
> 
> seems like it crashes after successful execution
> 
> —
> Reply to this email directly or view it on GitHub.
> 

_____________________________
email:  l.nilse@dunelm.org.uk
mobile: +49 176 44566 196

**Comment by timosachsenberg** [comment]
Are you sure it stops after filtering? I though it stops after clustering.

**Comment by lars20070** [comment]
Maybe a memory leak after clustering. Can you please send me the data and workflow?

**Comment by timosachsenberg** [comment]
I think any fails...

**Comment by lars20070** [comment]
OpenMS 2.0 or current developer version?

**Comment by timosachsenberg** [comment]
both

**Comment by lars20070** [comment]
A very early version before the 2.0 release and before #1204 worked.

<img width="353" alt="ffm_works" src="https://cloud.githubusercontent.com/assets/6149805/9598428/bc913294-508b-11e5-8f15-a67f284bb6e0.png">

**Comment by lars20070** [comment]
I looked at the temp folders. A correct param.ini is generated and looks fine. It also contains the temp folder to which the result is supposed to be written. That output folder is never created.

**Comment by lars20070** [comment]
@jpfeuffer Any further test you can suggest?

**Comment by lars20070** [comment]
Guess I found the culprit. Knime writes always all outputs, even if no output node is given. FFM has a bug when writing out_mzq. Hence Knime always crashes.

**Comment by lars20070** [comment]
@mwalzer This method generates MSQuantifications from a ConsensusMap. Now this [1] loop is no longer entered, and the ratio templates are not generated.

Nothing in the history [2] that looks problematic.

[1] https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FeatureFinderMultiplex.cpp#L984
[2] https://github.com/lars20070/OpenMS/commits/fix/FeatureFinderMultiplex_mzq/src/openms/source/METADATA/MSQuantifications.cpp

**Comment by lars20070** [comment]
The number of "Assays" in mzQuantML are the number of reported abundancies. Right?
i.e. standard SILAC should have two assays.

**Comment by mwalzer** [comment]
mh, I will have a look at it on weekend

**Comment by lars20070** [comment]
No need @mwalzer. There is nothing wrong with the mzQuantML implementation.
Hope #1585 will resolve the issue.
