### ISSUE TITLE
FileMerger crashes with ElementNotFound exception

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1577]
When merging annotated consensusXML files, the FileMerger crashes with

`Error: Unexpected internal error (the element 'Methyl:2H(2)' could not be found)`

The modification Methyl:2H(2) with Unimod accession # 284 occurs as N-terminal modification in some of the sequences.

**Comment by lars20070** [comment]
Where and how can a mod throw an ElementNotFound exception?

**Comment by cbielow** [comment]
to me this looks like a DB/Residue issue.
What happens if you call FileInfo on each file individually?

**Comment by cbielow** [comment]
If this is truly filemerger, could you provide a minimal example?

**Comment by lars20070** [comment]
You are right. FileInfo crashes with the same error. - It's not a FileMerger problem.

**Comment by lars20070** [comment]
Here [1] an example.

[1] https://gist.github.com/lars20070/8568c66b868d4110deda

**Comment by lars20070** [comment]
Unimod #284 Methyl:2H(2) allows only for mods at K, not N-term. I need to extend unimod.xml.

Shall we modify or extend the error message?
