### ISSUE TITLE
[KNIME] MapAlignerPosClustering worker crashes

### ISSUE THREAD

**Issue by iprotsyuk** [OpenMS/OpenMS#1580]
I created a workflow which calls FileConverter for each mzXML file with my samples followed by FeatureFinderMetabo, then calls MapAlignerPoseClustering. The pipeline works normally until execution reaches MapAlignerPoseClustering.
This is the output from the KNIME Console:
ERROR    GenericKnimeNodeModel           Failing process stdout: [Picking a reference (by size) ... done, Progress of 'Aligning input maps':, ,   32.53 %               ]
ERROR    GenericKnimeNodeModel           Failing process stderr: []
ERROR    MapAlignerPoseClustering        Execute failed: Failed to execute node MapAlignerPoseClustering

The crash doesn't occur if I build and run the same workflow in TOPPAS. Another way of avoiding it is reducing the amount of input files. Initially, I ran it with 83 mzXML files (each of ~2 MB). If I launch the workflow with ~40 input files it finishes correctly. Notable thing is that no high memory consumption happens during the workflow execution regardless a number of files.

I use KNIME 2.12.0 with latest OpenMS extension installed (can't find its version number). The TOPPAS version is 2.0.0.

The TOPPAS workflow: https://gist.github.com/iprotsyuk/00c552bd6173c161b431.
I can share the KNIME workflow and input data via Dropbox if necessary.

**Comment by timosachsenberg** [comment]
Thanks for reporting. Sharing the data would be great.

**Comment by iprotsyuk** [comment]
You can find a zipped file with the KNIME workflow and input files using this link: http://1drv.ms/1N3KnSv.

**Comment by timosachsenberg** [comment]
We recently had no reports about failing MapAlignerPose clustering so I close this issue. If this is still an issue please feel free to reopen and reupload the test files.
