### ISSUE TITLE
failed tests with boost >= 1.58

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1584]
I get a couple of failed tests when compiling against boost 1.58

```
99% tests passed, 5 tests failed out of 1735

Total Test time (real) = 194.53 sec

The following tests FAILED:
        326 - SvmTheoreticalSpectrumGenerator_test (Failed)
        328 - SvmTheoreticalSpectrumGeneratorSet_test (Failed)
        490 - IonizationSimulation_test (Failed)
        491 - MSSim_test (Failed)
        494 - RawTandemMSSignalSimulation_test (Failed)
Errors while running CTest
```

These are the 8 tests that fail with the current develop (Feb 2017) branch and boost 1.61:

```
99% tests passed, 8 tests failed out of 1923

Total Test time (real) =  85.79 sec

The following tests FAILED:
        336 - SvmTheoreticalSpectrumGenerator_test (Failed)
        338 - SvmTheoreticalSpectrumGeneratorSet_test (Failed)
        505 - IonizationSimulation_test (Failed)
        506 - MSSim_test (Failed)
        509 - RawTandemMSSignalSimulation_test (Failed)
        516 - MRMAssay_test (Failed)
        1676 - TOPP_FeatureLinkerUnlabeledQT_5_out1 (Failed)
        1678 - TOPP_FeatureLinkerUnlabeledQT_6_out1 (Failed)
Errors while running CTest

```

**Comment by jpfeuffer** [comment]
@andreott In the dev meeting we talked about that. Did you come up with something?

**Comment by hroest** [comment]
looks like these are some of the same tests that also failed with Ubuntu 16.04, see #2423 - maybe not a coincidence?

**Comment by hroest** [comment]
can somebody else on a different machine look into this as well? It seems that our travis uses boost 1.55 while our contrib uses boost 1.61 ...

**Comment by hroest** [comment]
seems like we changed boost from 1.52 to 1.61 a few weeks ago here: https://github.com/OpenMS/contrib/pull/22

**Comment by jpfeuffer** [comment]
Yes, I guess that is why we get similar failures on people reporting from building with MSVC2015

**Comment by hroest** [comment]
I can confirm now: Ubuntu 16.04 runs all tests through using boost (e.g. contrib 5c54339636ea128f822bdee3b53205ae55381ca5 tagged as Release 2.0.1) using boost 1.52

**Comment by hroest** [comment]
this could be related to this question on SO: http://stackoverflow.com/questions/26506550/consistent-random-number-generation-accross-platforms-with-boostrandom 

> it seems boost::random does not guarantee that you get the same sequence of numbers for certain seeds with different versions boost.

> E.g. in version 1.56 they have changed the algorithm to generate normal distributed random numbers from the Box-Muller method to the Ziggurat method:

https://github.com/boostorg/random/commit/f0ec97ba36c05ef00f2d29dcf66094e3f4abdcde

**Comment by hroest** [comment]
some attempt to fix this:  #2438

**Comment by jpfeuffer** [comment]
This is getting prominent again since 16.04 is getting more widely used and we upgraded our contrib for VS2015 and are getting these errors in Windows CI.

**Comment by hroest** [comment]
should be all fixed by 

-  #2740
-  timosachsenberg#9
-  #2744

applying these patches I can get the tests working with Ubuntu 16.04 and boost 1.58
