### ISSUE TITLE
Error in binaries.ini (to run MSGFPlus)

### ISSUE THREAD

**Issue by julianu** [OpenMS/OpenMS#1609]
In the binaries.ini is an error which causes the MS/GF+ adapter to fail (in certain environments):
The actual java executable is set in the PATH variable, whereas it should (probably) be the path only:

current:
`PATH=$ROOT/bin/:$ROOT/bin/Fido:$ROOT/bin/OMSSA:$ROOT/bin/MyriMatch:$ROOT/bin/XTandem:$ROOT/../../../jre/bin/java:${PATH}`

should be:
`PATH=$ROOT/bin/:$ROOT/bin/Fido:$ROOT/bin/OMSSA:$ROOT/bin/MyriMatch:$ROOT/bin/XTandem:$ROOT/../../../jre/bin/:${PATH}`

This typo is on Linux and Windows machines, did not check for OSX yet.
I just tested in on a Windows machine, where the error occurred, and with pointing to the path only it works. On my Linux machine it runs with the flaw.

**Comment by timosachsenberg** [comment]
fixed in #1617
