### ISSUE TITLE
msconvert / numpress generated mzML cannot be read

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1618]
ProteoWizard's msconvert allows for numpress compression [1]. For example

`msconvert --numpressPic data.wiff`

Loading such mzML files in OpenMS fails, see screenshot.

[1] http://proteowizard.sourceforge.net/tools/msconvert.html

![numpress_mzml](https://cloud.githubusercontent.com/assets/6149805/10138413/a0aae376-65fe-11e5-956c-f4f4c53ae726.png)

**Comment by hroest** [comment]
- which version of OpenMS was used?
- can you send me a sample file that fails?

**Comment by lars20070** [comment]
Here [2,3] the original wiff from a TripleTOF 6600. I used ProteWizard 3.0.8868 and the OpenMS nightly build from 23/09/15.

[2] https://www.dropbox.com/s/1knxbt8tho33woz/SILAC_2.wiff
[3] https://www.dropbox.com/s/tt4foy2d7b07hx4/SILAC_2.wiff.scan

**Comment by hroest** [comment]
I was hoping you could send the mzML file that OpenMS cannot read

**Comment by lars20070** [comment]
The 17 GB mzML is too big for my Dropbox. For the FTP download see email.

**Comment by hroest** [comment]
I downloaded a part of the file and I identified the reason when looking at the XML file:

```
  ...[snip]...
    <binaryDataArrayList count="2">
      <binaryDataArray encodedLength="192">
        <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" value=""/>
        <cvParam cvRef="MS" accession="MS:1000576" name="no compression" value=""/>
        <cvParam cvRef="MS" accession="MS:1000514" name="m/z array" value="" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
        <binary>...[snip]...</binary>
      </binaryDataArray>
      <binaryDataArray encodedLength="28">
        <cvParam cvRef="MS" accession="MS:1002313" name="MS-Numpress positive integer compression" value=""/>
        <cvParam cvRef="MS" accession="MS:1000515" name="intensity array" value="" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/>
        <binary>...[snip]...</binary>
      </binaryDataArray>
    </binaryDataArrayList>
  ...[snip]...
```

The problem lies in the fact that the provided mzML is invalid. The current mapping file ( http://www.peptideatlas.org/tmp/mzML1.1.0.html#binaryDataArray ) states for binaryDataArray:
 
- MUST supply a *child* term of MS:1000518 (binary data type) only once

However, the second array (the one with length 28) does *not* supply such a term, so OpenMS gets confused and does not know how to interpret the data. Also it seams that only the integer array gets compressed with MS Numpress and not the m/z array, not sure whether you intended to do this?

**Comment by lars20070** [comment]
The above `mzML` used only the integer compression. After #1641, I tested reading an `mzML` generated with full compression `--numpressAll`. Works fine. Some warnings due to the invalid `mzML`from ProteoWizard.

`While loading 'SILAC_2_numpressAll.mzML': Ill formed absolute or relative sourceFile path: file://.
Progress of 'loading spectra list':`
`While loading '': Invalid mzML format: Numpress-compressed binary data array 'm/z array' has no child term of MS:1000518 (binary data type) set. Assuming 64 bit float data type.`
`While loading 'SILAC_2_numpressAll.mzML': Ill formed absolute or relative sourceFile path: file://.> occurred 2 times`
`While loading '': Invalid mzML format: Numpress-compressed binary data array 'intensity array' has no child term of MS:1000518 (binary data type) set. Assuming 64 bit float data type.`

Thanks for the fix @hroest.

**Comment by lars20070** [comment]
BTW, numpress compression reduces a 22 GB `mzML` file to 7 GB.

**Comment by hroest** [comment]
> BTW, numpress compression reduces a 22 GB mzML file to 7 GB.

nice, I like it! since it is lossy compression, you should still check whether it impacts the results in any way!
