### ISSUE TITLE
mzid from Sciex ProteinPilot is invalid and cannot be read

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1619]
Sciex ProteinPilot exports `mzid`. For example [1] with many PSMs. The example file can be inspected with `ProteoIDViewer`. Conversion with `IDFileConverter` results in `idXML` [2] which contains no PSMs. Probably due to warnings such as `Found unusable modification @residue: Serine13 mod: Dehydrated`.

[1] https://www.dropbox.com/s/jfyrxdywdleicpl/SILAC_2.mzid
[2] https://www.dropbox.com/s/g8zle7ii2be7hun/SILAC_2.idXML

**Comment by lars20070** [comment]
`<PeptideIdentification>` are missing entirely in `idXML`.

**Comment by lars20070** [comment]
`mzid` from Sciex [1] checked with HUPP-PSI validator [3]. Not valid and reported to Sciex developers.

[3] https://github.com/HUPO-PSI/mzIdentML/tree/master/validator/trunk/mzIdentMLValidator

**Comment by mwalzer** [comment]
As this is no issue of OpenMS but Sciex ProteinPilot this is closed

**Comment by hroest** [comment]
@mwalzer would it be possible to still read the invalid xml and parse them? Is it possible in principle and if yes, how much work do you think that would be? I guess in the end the user is not helped if we simply say that the problem is with SCIEX, unless they are fixing this within reasonable time.

**Comment by lars20070** [comment]
Can we please keep this issue open? As a reminder for me to follow up on the discussion with Sciex.
Once we can get identifications from Sciex data #1612 https://github.com/OpenMS/OpenMS/pull/1679#issuecomment-153070360, I would like to compare to the ProteinPilot results.

**Comment by mwalzer** [comment]
@hroest I guess it would be possible, but too much work for me to patch the parser, especially for such a narrow usecase which should be a really easy fix for the ProteinPilot developers.
But I did not take a scrutinizing look at the offending file, so it might be just a few lines or a mock fix of the mzid with ```sed``` or alike

**Comment by mwalzer** [comment]
@lars20070 on your account, reopened

**Comment by lars20070** [comment]
`mzid` from Sciex ProteinPilot still invalid. I tested it at the Proteomic Forum 2017 and talked to `Christian.Baumann@sciex.com`.
