### ISSUE TITLE
MascotAdapterOnline problems with Mascot 2.5

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1624]
I'm seeing frequent problems with searching large files in Mascot 2.5 using MascotAdapterOnline (MAO). Often (but not always) MAO returns before the search is finished. I'm running MAO with the "skip_export" flag, because we use Mascot Percolator and thus need only the Mascot search number, not the exported results. In most of the failing cases, "0" is reported as the search number.

**Comment by hendrikweisser** [comment]
Based on the one example that I followed more closely, it seems that the MAO query finishes already when the Mascot search starts, i.e. as soon as the search query (data in MGF format) is uploaded to the Mascot server (which can take quite some time for a large file).

**Comment by hendrikweisser** [comment]
I've split the 2-3 GB large files into 1 GB parts and the search with MascotAdapterOnline works much better now.

**Comment by hroest** [comment]
@hendrikweisser is this resolved now?

**Comment by hendrikweisser** [comment]
It works well if input files are limited to ~1 GB.
