### ISSUE TITLE
FeatureFinderUnlabeledQT with identifications

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1648]
I have performed some major work on FeatureFinderUnlabledQT, see for example #1610 and I have now investigated some issues when using the `-algorithm:use_identifications` parameter. Using some sample data provided by Hendrik, I have run the tool on a set of 9 files using the Release 2.0 binary and the new develop version. The initial results without using `-algorithm:use_identifications` yield about 33679 features, of which 9087 are present in all runs [1] in 13 minutes using ca 890 MB of memory. Note that the behavior is identical in 2.0 and the current develop, except the current develop branch only uses 9 minutes and 330 MB of memory.  When running the Release 2.0 binary with the `-algorithm:use_identifications`, the algorithm identifies 33813 features, of which 8992 are present in all runs [2]. This decrease is expected as some of the original 9087 features likely had conflicts in their ids and thus the number is reduced by 95 features, increasing the number of total features by 134.

I have now tried to emulate this behavior with the new FeatureFinderUnlabledQT from PR #1610 and have found that it does not produce the exact same result, namely producing 33748 features, of which 9015 are in all runs. It thus only looses 72 fully linked features (as opposed to 95) and increases the total number of features only by 69 (as opposed to 134). There are basically two reasons for this:

# Bugs in the original 2.0 FeatureFinderUnlabledQT 

I have found two bugs in the FeatureFinderUnlabledQT as of Release 2.0 which were unintended errors in the code. The first error is an omission in the `element_mapping` data structure to ensure that the center point of each cluster is included in the mapping (see hroest/OpenMS@6cf78a36b31f7e637c5fff8650b4e444a2a61c77 ). The second error is a faulty assumption that the QTCluster annotations only need to be re-computed if the annotations of the removed element are equal to the annotations of the cluster. This is false as it is also possible that an un-annotated feature is currently part of the cluster  and would thus require re-computation of the whole cluster (see hroest/OpenMS@beb70dcaf0c14b554a3f886581a0c80c3065f2f6 ). Fixing these two bugs makes the behavior of the FeatureFinderUnlabledQT 2.0 binary more correct, however I discovered another issue while investigating the differences between the two tools.

# Inconsistent behavior in the original 2.0 FeatureFinderUnlabledQT 

While investigating these issues, I came across some highly peculiar behavior in the FeatureFinderUnlabledQT algorithm, namely that the annotations of a cluster with an un-annotated center feature depends highly on the order in which elements are added. Unfortunately, this invalidates one of the major guarantees of the QT algorithm, namely that a globally optimal cluster will be found. The main issues I encountered were that the first element which got added to a QTCluster whose center had no annotation determined its annotation from that point onwards. Basically, adding such an element would trigger the `changed_` flag to be set which causes the next call of `QTCluster::getAnnotations` to call `QTCluster::optimizeAnnotations_` which would then use the annotation of the recently added element as the annotation for the *whole cluster* and prevent the addition of elements with different elements. I even found cases where a cluster intermediately had an annotation, e.g. a cluster has no initial annotation and after adding a few elements "gained" an annotation by selecting neighbors with a specific peptide annotation and after adding even more elements "lost" this annotation again as the new optimal set of closest neighbors did not include any elements with peptide ids any more.

This behavior is obviously sub-optimal as the order in which elements are added to the cluster should not influence the result, in this case however it does. As I do not believe that this behavior is correct, I changed this behavior in the new version of FeatureFinderUnlabledQT to make the algorithm overall more reproducible and predictable, see [4] which in the sample dataset only slightly changes the outcome. 

# Conclusion

Overall it thus seems very hard and not advisable to emulate the exact behavior of FeatureFinderUnlabledQT as of 2.0 and to me it seems better to compare the current version in terms of "lost" clusters while still only reporting clusters without conflicts in identification. This seems to work as the new algorithm performs more reproducible, has fewer bugs and produces a larger number of fully linked features. I thus suggest to adopt the version of the algorithm that is independent of the order in which elements get added to the cluster. I have now written a PR #1647 which contain these changes and produce the result shown in [4]. 

In conclusion, the new FeatureFinderUnlabledQT seems to produce better results (more features in all samples, fewer features in total) and shows less erratic behavior. So I suggest to keep the new version.

# References

[1]

$ /usr/bin/time /home/hr/openmsall/openms_builds/release_build/bin/FeatureLinkerUnlabeledQT -in *.featureXML -out /tmp/new.consensusXML 
Progress of 'reading input':
-- done [took 24.23 s (CPU), 24.61 s (Wall)] -- 
Hashing...
Clustering...
Progress of 'linking features':
-- done [took 08:12 m (CPU), 08:14 m (Wall)] -- 
Number of consensus features:
  of size  9:   9087
  of size  8:   2317
  of size  7:   1820
  of size  6:   1745
  of size  5:   1807
  of size  4:   2020
  of size  3:   2680
  of size  2:   3727
  of size  1:   8476
  total:       33679
FeatureLinkerUnlabeledQT took 08:55 m (wall), 08:52 m (CPU), 0.00 s (system), 08:52 m (user).
532.22user 0.95system 8:55.95elapsed 99%CPU (0avgtext+0avgdata 1339888maxresident)k
18328inputs+94768outputs (12major+89071minor)pagefaults 0swaps

[2]

$ /usr/bin/time /media/data/var/openms/openms_builds/Release_2.0_py27_nnn/bin/FeatureLinkerUnlabeledQT -
in *.featureXML -out /tmp/new.consensusXML -algorithm:use_identifications
Progress of 'linking features':
-- done [took 11:48 m (CPU), 11:56 m (Wall)] --
Number of consensus features:
  of size  9:   8992
  of size  8:   2359
  of size  7:   1828
  of size  6:   1775
  of size  5:   1834
  of size  4:   2037
  of size  3:   2698
  of size  2:   3774
  of size  1:   8516
  total:       33813
FeatureLinkerUnlabeledQT took 13:06 m (wall), 12:57 m (CPU), 0.00 s (system), 12:57 m (user).
777.78user 5.37system 13:08.22elapsed 99%CPU (0avgtext+0avgdata 3667440maxresident)k
29568inputs+94848outputs (80major+237510minor)pagefaults 0swaps

[3]

$ ~/openmsall/openms_builds/release_build/bin/FeatureLinkerUnlabeledQT -in *.featureXML -out /tmp/new.consensusXML -algorithm:use_identifications
Progress of 'reading input':
-- done [took 23.91 s (CPU), 28.99 s (Wall)] -- 
Progress of 'linking features':
-- done [took 09:22 m (CPU), 09:26 m (Wall)] -- 
Number of consensus features:
  of size  9:   9015
  of size  8:   2349
  of size  7:   1835
  of size  6:   1755
  of size  5:   1820
  of size  4:   2033
  of size  3:   2700
  of size  2:   3739
  of size  1:   8502
  total:       33748

[4]

$ /usr/bin/time /home/hr/openmsall/openms_builds/release_build/bin/FeatureLinkerUnlabeledQT -in *.featureXML -out /tmp/new.consensusXML -algorithm:use_identifications
Progress of 'reading input':
-- done [took 26.12 s (CPU), 26.58 s (Wall)] -- 
Progress of 'linking features':
-- done [took 09:39 m (CPU), 09:44 m (Wall)] -- 
Number of consensus features:
  of size  9:   9018
  of size  8:   2345
  of size  7:   1842
  of size  6:   1753
  of size  5:   1819
  of size  4:   2026
  of size  3:   2696
  of size  2:   3742
  of size  1:   8509
  total:       33750

**Comment by hendrikweisser** [comment]
Wow, great work and a nice write-up. Thank you.

If your changes lead to fewer feature groups, while maintaining the constraints, then they are by definition an improvement. So naturally I agree that we should keep them.

Just out of curiosity: Are any of the differences in results between the old/new version apparent on the OpenMS test cases, or only on the bigger real-world dataset?

**Comment by hroest** [comment]
> Just out of curiosity: Are any of the differences in results between the old/new version apparent on the OpenMS test cases, or only on the bigger real-world dataset?

I think only in real-world datasets as these complicated cases where the order in which we add features is important only happen very rarely. Imaging that in most cases that it does not make a big difference since for each "true cluster" we have n chances to get it right where n = number of maps. So even if we perform sub-optimally for some clusters, usually we will get it right still.
