### ISSUE TITLE
HighResPrecursorMass-Corrector crashes when .csv output is added

### ISSUE THREAD

**Issue by Stortebecker** [OpenMS/OpenMS#1651]
Hej,
just found a minor problem: whenever I add a .csv-output as second output to the HighResPrecursorMass-Corrector, it crashes with a strange error message (see attached file).
Cheers, Florian

**Comment by lars20070** [comment]
I can reproduce the crash. Reminds me of what we had seen https://github.com/OpenMS/OpenMS/issues/1589#issuecomment-138593076

![crash](https://cloud.githubusercontent.com/assets/6149805/10394639/c8f48588-6e98-11e5-9171-d0bd47fc7376.png)

**Comment by lars20070** [comment]
The `csv` file is indeed missing from the `/tmp/.../out_csv/` folder. When run on the command line with `-out_csv` no `csv` file is written either.

**Comment by lars20070** [comment]
BTW, when loading the input `mzML` the following warning occurs.

`While loading 'test.mzML': Ill formed absolute or relative sourceFile path: file://`

https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FORMAT/HANDLERS/MzMLHandler.h#L1275

**Comment by timosachsenberg** [comment]
Hi, ok it seems this functionality is not implemented for the new mass correction algorithm that uses features. We should fix this in the future.
@lars20070 the warning is issues because the source file path is not correctly set by the conversion software.
Can you post the sourceFile location and path lines of the mzML (quite at the beginning) file so I can confirm this is the problem?

**Comment by lars20070** [comment]
`	<fileDescription>
		<fileContent>
			<cvParam cvRef="MS" accession="MS:1000579" name="MS1 spectrum" />
			<cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
		</fileContent>
		<sourceFileList count="1">
			<sourceFile id="sf_ru_0" name="MB_Uk45_P250413_020513.RAW" location="file://">
				<cvParam cvRef="MS" accession="MS:1000569" name="SHA-1" value="e0b1f0ac27bd60dc962f9c8c88a9ecc95f3ac310" />
				<cvParam cvRef="MS" accession="MS:1000563" name="Thermo RAW format" />
				<cvParam cvRef="MS" accession="MS:1000768" name="Thermo nativeID format" />
			</sourceFile>
		</sourceFileList>
	</fileDescription>`

**Comment by lars20070** [comment]
Guess `location="file://"` is the problematic part. The `mzML` stems from msconvert. Email to the ProteoWizard team?
