### ISSUE TITLE
complete PRIDE submission not possible

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1655]
A complete PRIDE submission requires `mzML`, `mgf` and `mzIdentML`. We generated `mgf` with `FileConverter` and `mzIdentML` with a standard MS-GF+ workflow. The complete PRIDE submission is not possible, see comments from the PRIDE team below.

(1) one problem seems to be that in the `<SpectraData>` element, the location is
set to "UNKNOWN":

```
<SpectraData location="UNKNOWN" id="6054996828460235736">
<FileFormat>
<cvParam accession="MS:1000584" cvRef="PSI-MS" name="mzML format"/>
</FileFormat>
<SpectrumIDFormat>
<cvParam accession="MS:1000774" cvRef="PSI-MS" name="multiple peak list
nativeID format"/>
</SpectrumIDFormat>
</SpectraData>
```

Here there should be the name of the peak list file, for instance

```
<SpectraData location="local/mgf/merge.mgf" id="SD_1" >
```

Since the location is not set, the PX submission tool cannot check, if
all the peak list files that are specified in `<SpectraData>` elements of .mzid
files are present in the upload.

(2) In addition the combination of `<FileFormat>` and `<SpectrumIDFormat>` seems not
to match:
If the FileFormat is "mzML format" then I would expect

```
<cvParam accession="MS:1001530" cvRef="PSI-MS" name="mzML unique identifier"/>
```

in `<SpectrumIDFormat>`
"multiple peak list nativeID format" means .mgf, .pkl or merged .dta files.

(3) Another sensible combination would be

```
<FileFormat>
<cvParam accession="MS:1001062" name="Mascot MGF file" cvRef="PSI-MS" />
</FileFormat>
<SpectrumIDFormat>
<cvParam accession="MS:1000774" name="multiple peak list nativeID format"
cvRef="PSI-MS" />
</SpectrumIDFormat>
```

if the peak list file is in .mgf (Mascot Generic Format)

see also http://www.ebi.ac.uk/mzidentml-documentation-developers

**Comment by lars20070** [comment]
According to @ypriverol, later this year PRIDE submissions using `mzTab` will be possible.

**Comment by lars20070** [comment]
The three points (1) to (3) above were provided by @germa. In our OpenMS analysis, the `mzIdentML` were based on multiple fractions i.e. multiple 'mzML'. As I understand, it is impossible to fill in the
```
<SpectraData location="UNKNOWN">
```
retrospectively by hand. The information in which fraction the peptide identification was seen is lost.

@mwalzer Can you please comment?

**Comment by germa** [comment]
Question of Lars: Is mgf really necessary, since the MS2 spectra are in mzML?
Yes, I think mzML is enough, so no .mgf files are recessary.

**Comment by lars20070** [comment]
@ypriverol @germa Once the fraction i.e. `mzML` file is know, how do you map identifications from `mzIdentML` to the MS2 spectra in `mzML`?

In our workflow, we correct the precursor positions i.e. shift the m/z. Is that a problem? Can the IDs still be mapped to the MS2 spectra?

**Comment by lars20070** [comment]
@timosachsenberg I will have all necessary tools to set the `file_origin` meta value as already done in `IDMerger` [1]. The `IDFileConverter` then uses the meta value in the `mzid` export.
```
<SpectraData location="file_origin">
```
Can we by default always set this meta value, and only optionally switch it off?

[1] https://github.com/OpenMS/OpenMS/blob/develop/src/topp/IDMerger.cpp#L192

**Comment by lars20070** [comment]
@mwalzer As I understand, in `mzid`
```
<SpectraData location="...">
```
is the `mzML` file associated with a PSM or peptide. A protein can originate from multiple `mzML`. Why then is
```
<SpectraData location="...">
```
fetched from the `ProteinIdentification`?
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp#L524

**Comment by timosachsenberg** [comment]
because the ProteinIdentification object stores the data associated with one identification run (=one file)

**Comment by lars20070** [comment]
Ok. - Do we need 'annotate_file_origin` flags in each relevant tools (as in `IDMerger`)? Or can we set the `file_origin` = `spectra_data` by default?

**Comment by timosachsenberg** [comment]
file origin is mainly related to merging files and usually does not refer to the original spectra files

**Comment by mwalzer** [comment]
@lars20070 SpectraData is the peak file containing referenced (in the identification) spectra. Our  storage location internally is ProteinIdentification as this object has the search parameters registered. 
@timosachsenberg in what other ways is file origin used? 
file_origin is only some metadata value and I doubt the proper way to handle.

**Comment by mwalzer** [comment]
@lars20070  were the spectra_data correct before you merged?

**Comment by lars20070** [comment]
The `spectra_data` meta value is never set by any tool and therefore never set in `mzid`.

Still confused why search params and `mzML` file appear in `ProteinIdentification`. A single protein can be based on PSMs from multiple searches and  `mzML` files. Can we talk on the phone or chat on Gitter?

**Comment by hendrikweisser** [comment]
> Still confused why search params and mzML file appear in ProteinIdentification.

The name "ProteinIdentification" is a bit misleading. Think of it as "ProteinIdentification*Run*".

> A single protein can be based on PSMs from multiple searches and mzML files.

I don't think that's possible in OpenMS. If you identify a protein in multiple searches, you will get multiple copies of it (ProteinHits) in the different ID runs (ProteinIdentifications).

**Comment by lars20070** [comment]
We can also move this to Gitter.
https://gitter.im/OpenMS/OpenMS/mzid_fix_for_PRIDE?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by hendrikweisser** [comment]
@lars20070: Can you please update this thread if any significant insights arise from the Gitter discussion? I don't like it when relevant information is scattered in many places.

**Comment by ypriverol** [comment]
@hendrikweisser @lars20070 especially if is in German.

**Comment by lars20070** [comment]
@ypriverol @hendrikweisser I gonna add the conclusion of our Gitter discussion to this thread.

**Comment by lars20070** [comment]
For a complete PRIDE submission, we need to write `<SpectraData location>` i.e. the `mzML` when exporting `mzid`.

The `mzid` structure makes sense to me. The `<DataCollection>` in `mzid` can contain multiple (!) `<SpectraData>` i.e. `mzML` = fractions. Each `<SpectrumIdentificationResult>` i.e. PSM then references `<SpectraData>` via the `spectraData_ref` identifier.

In the OpenMS data structure, the `ProteinIdentification` run has a single (!) meta value `spectra_data`. It is therefore not possible to associate multiple `mzML` with a single protein identification run. Instead, `ProteinIdentification` should have a vector of `SpectraData` which are then referenced by `PeptideHit`. Each peptide hit is then associated with a specific `mzML` i.e. fraction.

Can you please correct me, if I do not understand the OpenMS data structure correctly?

**Comment by timosachsenberg** [comment]
ProteinIdentificcation refers to a single MS run and should therefor only refer one mzML file.
If you have several fractions than you need several ProteinIdentifications

**Comment by lars20070** [comment]
Thanks @timosachsenberg. `ProteinIdentification` run == `mzML` file == fraction

We run Fido for each fraction independently, and then merge all results into a single `ProteinIdentification`.
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FidoAdapter.cpp#L607
The search engines are overwritten. How can we then fill the `<AnalysisCollection>` in `mzid`?
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FidoAdapter.cpp#L621

**Comment by timosachsenberg** [comment]
what was the difference in FIDO between using merged ProtID and several ProtIDs?
How were the files merged? IDMerger?

**Comment by lars20070** [comment]
Yes, `IDMerger`.

As I understand the API (and I don't), we need to keep a list of several `ProteinIdentifications`.

**Comment by timosachsenberg** [comment]
Hi Lars,
I merged two idXML files containing the ms_run-location metavalue and it creates two ProteinIdentifications are created each annotated with the correct (in that case the same) raw file.

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://open-ms.sourceforge.net/XSL/IdXML.xsl" ?>
<IdXML version="1.3" xsi:noNamespaceSchemaLocation="http://open-ms.sourceforge.net/SCHEMAS/IdXML_1_3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <SearchParameters id="SP_0" db="" db_version="" taxonomy="" mass_type="monoisotopic" charges="" enzyme="unknown_enzyme" missed_cleavages="0" precursor_peak_tolerance="0" precursor_peak_tolerance_ppm="false" peak_mass_tolerance="0" peak_mass_tolerance_ppm="false" >
        </SearchParameters>
        <IdentificationRun date="2015-07-29T16:03:48" search_engine="SimpleSearchEngine" search_engine_version="2.0.0" search_parameters_ref="SP_0" >
                <ProteinIdentification score_type="" higher_score_better="true" significance_threshold="0" >
                        <UserParam type="stringList" name="ms_run-location" value="[file://./KKramer_150612_yeastTAP_4_120min.raw]"/>
                </ProteinIdentification>
                <PeptideIdentification score_type="hyperscore" higher_score_better="true" significance_threshold="0" MZ="520.262817382812" RT="2655.095703125" >
                        <PeptideHit score="26.8079482457823" sequence="DFASSGGYVLHLHR" charge="3" >
                        </PeptideHit>
                </PeptideIdentification>
                <PeptideIdentification score_type="hyperscore" higher_score_better="true" significance_threshold="0" MZ="1063.20983886719" RT="4587.6689453125" >
                        <PeptideHit score="61.1557396466157" sequence="IALSRPNVEVVALNDPFITNDYAAYM(Oxidation)FK" charge="3" >
                        </PeptideHit>
                </PeptideIdentification>
                <PeptideIdentification score_type="hyperscore" higher_score_better="true" significance_threshold="0" MZ="775.38720703125" RT="4923.77734375" >
                        <PeptideHit score="57.8430927422847" sequence="RPGADSDIGGFGGLFDLAQAGFR" charge="3" >
                        </PeptideHit>
                </PeptideIdentification>
        </IdentificationRun>
        <IdentificationRun date="2015-07-29T16:03:49" search_engine="SimpleSearchEngine" search_engine_version="2.0.0" search_parameters_ref="SP_0" >
                <ProteinIdentification score_type="" higher_score_better="true" significance_threshold="0" >
                        <UserParam type="stringList" name="ms_run-location" value="[file://./KKramer_150612_yeastTAP_4_120min.raw]"/>
                </ProteinIdentification>
                <PeptideIdentification score_type="hyperscore" higher_score_better="true" significance_threshold="0" MZ="520.262817382812" RT="2655.095703125" >
                        <PeptideHit score="26.8079482457823" sequence="DFASSGGYVLHLHR" charge="3" >
                        </PeptideHit>
                </PeptideIdentification>
                <PeptideIdentification score_type="hyperscore" higher_score_better="true" significance_threshold="0" MZ="1063.20983886719" RT="4587.6689453125" >
                        <PeptideHit score="61.1557396466157" sequence="IALSRPNVEVVALNDPFITNDYAAYM(Oxidation)FK" charge="3" >
                        </PeptideHit>
                </PeptideIdentification>
                <PeptideIdentification score_type="hyperscore" higher_score_better="true" significance_threshold="0" MZ="775.38720703125" RT="4923.77734375" >
                        <PeptideHit score="57.8430927422847" sequence="RPGADSDIGGFGGLFDLAQAGFR" charge="3" >
                        </PeptideHit>
                </PeptideIdentification>
        </IdentificationRun>
</IdXML>
```

**Comment by lars20070** [comment]
@timosachsenberg Yes. `IDMerger` is fine and returns the correct fractions. But `FidoAdapter` also needs to always return n fractions when it receives n fractions as input.

@jpfeuffer Slightly off-topic: Do we need the `separate_runs` param in the adapter at all? If you want to run Fido for each fraction separately, then run `FidoAdapter/Collect/IDMerger`. If you want to run Fido once on the combined fractions, then run `Collect/IDMerger/FidoAdapter`.
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FidoAdapter.cpp#L603

**Comment by mwalzer** [comment]
So there is another FidoAdapter call on the merged?

**Comment by lars20070** [comment]
Yes. Typically protein inference runs on the combined PSMs of all fractions.
If the adapter then merges everything into one single "fraction"
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FidoAdapter.cpp#L619
then the meta info of the individual fractions for the `mzid` export are lost.

**Comment by jpfeuffer** [comment]
Okay. Currently I also do not see any advantage of an internal merging inside the FidoAdapter over a previous merge with IDMerger, but maybe I am wrong. Maybe @hendrikweisser can comment on this.

**Comment by hendrikweisser** [comment]
@jpfeuffer:
> Currently I also do not see any advantage of an internal merging inside the FidoAdapter over a previous merge with IDMerger, but maybe I am wrong.

I would leave the option because it doesn't hurt to have it. There are other cases besides multiple fractions that can lead to several ID runs in an idXML file (e.g. multiple search engines, import from pepXML), and it might make sense to treat them separately for protein inference.

@lars20070:
> But FidoAdapter also needs to always return n fractions when it receives n fractions as input.
> Typically protein inference runs on the combined PSMs of all fractions.

These two statements are somewhat contradictory. If you want to run protein inference on all fractions together, then you will get one combined protein inference result - not one per fraction. How do you propose to split that result into fractions again?

**Comment by hendrikweisser** [comment]
@lars20070 and I just talked on the phone. We came up with the following options for resolving the FidoAdapter problem:

1. Abuse idXML: In FidoAdapter, write one ID run (ProteinIdentification) with all the inferred proteins, but without PSMs; also write the input ID runs, but without protein hits, i.e. only PSMs, to the same file. Pro: All the information is in one file, no changes to schemas/data structures. Con: No other tool can deal with this kind of idXML, would need extra treatment for mzid export.
2. New tool: Add a tool ("PRIDESubmissionMaker"?) that takes all the relevant inputs and creates the necessary files for a PRIDE submission exactly as they should be. In particular, this would read both the inputs (for PSMs) and the output (for inferred proteins) of FidoAdapter. Pro: Very flexible, no (or only minimal) changes in existing code. Con: Another tool.
3. Switch to mzid as the standard format in OpenMS: This would allow us to capture all the relevant information in the output of FidoAdapter. Pro: This needs to happen anyway. Con: A huge change.

If I had to make a PRIDE submission now, I would go with option 2.
In any case, we should discuss this at the developer meeting.

**Comment by timosachsenberg** [comment]
I agree that probably 3 is the way to go for the future and option 2 probably easier to implement right now. Though I am not sure if the tool would fit other workflows than the one in question.

**Comment by mwalzer** [comment]
yeah, true. To be really flexible, some effort would have to be made. But I think it is a good intermediate solution.

**Comment by lars20070** [comment]
@germa @ypriverol In the `mzid` files, you expect to see `MS:1001530` (mzML unique identifier) in `<FileFormat>`. We are writing  `MS:1000584` (mzML format) instead. Is that ok?

Here an example
```
<SpectraData location="D:\data\Lars\temp\2016-02-18_100004_ukmz1005immz_19052_1\TOPPAS_tmp\Sciex_PeptideID\003_FileFilter\out\Yasset Perez-Riverol - 140702_0002_DC2ac_6600_G2_DDA1-DC2ac_6600_G2_DDA1.mzML" id="SDAT_5738021608842980198">
	<FileFormat> 
		<cvParam accession="MS:1000584" cvRef="PSI-MS" name="mzML format"/>
	</FileFormat>
	<SpectrumIDFormat> 
 		<cvParam accession="MS:1000774" cvRef="PSI-MS" name="multiple peak list nativeID format"/>
	</SpectrumIDFormat> 
</SpectraData>
```

**Comment by lars20070** [comment]
@mwalzer Can you please comment? `MS:1000584` or `MS:1001530`?

**Comment by mwalzer** [comment]
What we do whilst writing is 
```
         spectra_data += String("\n\t\t\t<FileFormat> \n");
          spectra_data += String(4, '\t') + cv_.getTermByName("mzML format").toXMLString(cv_ns);
          spectra_data += String("\n\t\t\t</FileFormat>\n\t\t\t<SpectrumIDFormat> \n ")
```
And I think this is perfectly legit.
However, I am also assuming that 'mzML unique identifier' (MS:1001530) might be placed somewhere other than FileFormat? @ypriverol where do you require the unique identifier?
@lars20070 next problem would be that the OpenMS data structures right now -MetaInfoInterface aside, thats rather flimsy- are incapable of carrying such information as the UID of the spectra data file along.

**Comment by timosachsenberg** [comment]
@mwalzer I think the UID of the spectra data file will not be carried by internal data structures but generated in the mzIdentML.

**Comment by mwalzer** [comment]
Sounds implausible.

**Comment by lars20070** [comment]
#1549 is related. Before attempting a complete PRIDE submission, we should validate the `mzid`.

**Comment by hendrikweisser** [comment]
I've started to work on this because I need to submit a dataset to PRIDE. I'm extending IDFileConverter to use information from a supplied mzML file ("mz_file" parameter) to set the "spectra_data" and "spectrum_reference" meta values on ProteinIdentification/PeptideIdentification objects, so that the correct information is written to the mzid. However, this will not work correctly if the input is a merged file derived from multiple fractions. (It should be possible to split such a file first using IDRipper.)

**Comment by mwalzer** [comment]
Can you be more specific about what is not working correctly?
This is also relevant in the light of the mzid 1.2 release coming up, btw.  
Sample fractions are always a crux from the handling side.
So maybe you could provide a small example ?

**Comment by hendrikweisser** [comment]
@mwalzer:
I want to deposit Percolator results in PRIDE. Currently, if I convert the Percolator .psms files to mzid with IDFileConverter, the "location" in "SpectraData" is "UNKNOWN", since there's no information about the underlying MS data file in the Percolator output. Also, the "spectrumID" in "SpectrumIdentificationResult" has the format "MZ:...@RT:...", which PRIDE won't accept, from what I understood.

I found this helpful page about valid "spectrumID" formats: http://www.ebi.ac.uk/mzidentml-documentation-developers
By the way, this seems to indicate that our use of "FileFormat": "mzML format" together with "SpectrumIDFormat": "multiple peak list nativeID format" in "SpectraData" is (at least) discouraged:
> If the source file is mzML, \<SpectrumIdentificationResult\> MUST reference the value in “id” attribute to reference the spectrum that was searched.

I've implemented some changes that I think should solve the problems above and generate mzid that can be used for a complete PRIDE submission (at least in simple cases), but I'm waiting for confirmation from @ypriverol whether the files that I create are indeed working.

I've pushed my changes to a branch and would be interested in your comments:
https://github.com/hendrikweisser/OpenMS/tree/mzid-pride

**Comment by lars20070** [comment]
FYI. @ypriverol and I had also seen problems with the [spectrum reference](https://gitter.im/OpenMS/OpenMS/mzid_fix_for_PRIDE?utm_source=share-link&utm_medium=link&utm_campaign=share-link).
Let me know if our (multi-fraction) example from May would be of any help.

**Comment by mwalzer** [comment]
So:
spectrumID is a *mandatory* attribute. Despite, that in some (many) situations **we** do not have that information. Or only "in a way". This is, why I included that fall-back of mz@rt , so you can *later* hopefully **fix** that lack - a corresponding warning is written BTW. 
With our setup right now, it is not possible to write a fully compliant mzid at *any* time, because all information is not kept all the time.
In @lars20070 complete PRIDE submission case the solution was to add the spectrum_references from the mzML together with a fix for multiple spectra_data references, if I remember correctly? 
Did this not work for you @hendrikweisser ?

**Comment by mwalzer** [comment]
That link you gave is to be taken with some grain of salt, it does not even detail which schema version.
But it is good to know.  I guess it is intended to point to specific crucial implementation issues that need to be correct for PRIDE compliance. @ypriverol? Where is the page integrated? Would there be a better heading/title for it?

**Comment by mwalzer** [comment]
Problem is -as said- our internal keeping of reference, which is too generic at times, and used in different interpretations in different parts of the code. We already made changes in reference keeping if you remember, fetching spectrum_reference as it is attributed in the mzML. What I mean is that I like @hendrikweisser changes with IDFileConverter and MzIdentMLHandler, esp. for different spectra_data format origins. You might open a PR so we can discuss in more detail.

**Comment by hendrikweisser** [comment]
> In @lars20070 complete PRIDE submission case the solution was to add the spectrum_references from the mzML together with a fix for multiple spectra_data references, if I remember correctly?
> Did this not work for you @hendrikweisser ?

I don't know. Was this functionality made available anywhere? Because that's basically what my proposed changes to IDFileConverter are doing - set "spectrum_reference" and "spectra_data" meta values according to an mzML file. (No support for multiple "spectra_data" entries at the moment, though.)

> Problem is -as said- our internal keeping of reference, which is too generic at times, and used in different interpretations in different parts of the code. We already made changes in reference keeping if you remember, fetching spectrum_reference as it is attributed in the mzML.

Absolutely agreed that this is currently an internal problem. I'm not sure about the "fetching spectrum_reference as it is attributed in the mzML" - where does that happen? I've only seen cases (in test files, I think) where the scan number was used as the "spectrum_reference".
One major issue we have at the moment is that the "spectrum_reference" attribute in idXML is defined as a uint, but the spectrum ID in mzML is a string. So if we set the meta value correctly and write out the data as mzid, that works, but we can't actually persist a "spectrum_reference" of type string in our internal file format! (Or can we?)

**Comment by hendrikweisser** [comment]
> You might open a PR so we can discuss in more detail.

Will do, but I want to hear back from @ypriverol if the changes actually enable a complete PRIDE submission first.

**Comment by lars20070** [comment]
FYI. In the [above example](https://www.dropbox.com/sh/kh4b90yf669pbmw/AABkxa9JVCqi_OrTwn3kC2Gja), the spectrum reference is empty 
```
<InputSpectra spectraData_ref="SDAT_10430546525903382050"/>
```
and neither of the two fractions/files `WL383` and `WL384` appears in the `mzid`. The workflow was run in May and I have not checked since.

**Comment by hendrikweisser** [comment]
@mwalze: I've opened a pull request now: #2097

**Comment by timosachsenberg** [comment]
Hi I am currently reviewing tasks from the last developer retreat. What is the state of this issue?

**Comment by ypriverol** [comment]
I can reply on this one. Hendrik did a complete submission to pride with mzidentml and we are scaling the pipeline because the submission is really big. But in principle in the openms side this is done. Hendrik did you use openms for this no?

**Comment by hendrikweisser** [comment]
> Hendrik did you use openms for this no?

Yes, this works with OpenMS now. When you convert your ID results to mzid using IDFileConverter, pass the original mzML file using the "mz_file" option and the spectrum references etc. are added to the output in the correct format.

Two things:
- I've just noticed that the "mz_file" parameter documentation doesn't mention this yet.
- The limitation is that (so far) this only works for one mzML file per mzid file. The case of fractionated data that is searched together, giving one mzid derived from multiple mzMLs, is not covered.

**Comment by hroest** [comment]
maybe we should document this pipeline as many people keep asking about PRIDE submissions ...
