### ISSUE TITLE
packaging MSGF+

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#1683]
What about packaging MSGF+? It is open source, but I did not find any license information in either the sources or the two websites featuring the tool.

**Comment by mwalzer** [comment]
Is anyone in contact with Sangtae Kim? I guess in terms of missing stated licensing it is a personal copyright. 
But before reaching out, would anyone oppose to the idea?

**Comment by timosachsenberg** [comment]
Is it really open-source? I did not find the source code, yet.
By the way I thought we package MSGF+

**Comment by mwalzer** [comment]
sources [here](http://bix.ucsd.edu/tmp/MSGFPlus/msgf+.zip)

**Comment by mwalzer** [comment]
we do package? the jar didn't arrive in my latest installation... :(

**Comment by timosachsenberg** [comment]
platform and version?

**Comment by mwalzer** [comment]
for linux you obviously have to take care yourself, but last installer was w32

**Comment by mwalzer** [comment]
okay, so I guess we can close that issue
