### ISSUE TITLE
TheoreticalSpectrumGenerator.addPeaks: creates spectrum with last peak missing

### ISSUE THREAD

**Issue by PetraGutenbrunner** [OpenMS/OpenMS#1685]
Calling the method addPeaks in .../CHEMISTRY/TheoreticalSpectrumGenerator.cpp for instance for peptide "TYQYS(Phospho)" generates following spectrum: 
-- MSSPECTRUM BEGIN --
-- SPECTRUMSETTINGS BEGIN --
-- SPECTRUMSETTINGS END --
POS: 265.118 INT: 1
POS: 393.177 INT: 1
POS: 556.24 INT: 1
-- MSSPECTRUM END --

The listed peaks are for the amino acids YQY, but the peak for S(Phospho) is missing. Could it be that the condition in the loop to generate the peaks is wrong: "i <= peptide.size()" instead of "i < peptide.size()", because i starts from 1 and not from 0?

case Residue::BIon:
    {
       Size i = 1;
      if (!add_first_prefix_ion)
      {
        i = 2;
      }
      for (; i < peptide.size(); ++i)
      {
        ion = peptide.getPrefix(i);
        double pos = ion.getMonoWeight(Residue::BIon, charge) / (double)charge;
        ions[pos] = ion;
        names[pos] = "b" + String(i) + String(charge, '+');
      }
      intensity = (double)param_.getValue("b_intensity");
      break;
    }

Another question is: Is there a reason why the parameter "add_first_prefix_ion" is set default to "false"? Because I would have expected to get for the peptide above 5 peaks (b1 included).

**Comment by jpfeuffer** [comment]
I think there are also methods for adding the precursor mass (i.e. full peptide).
And b1 is usually not observed in CID (it cannot be formed chemically during fragmentation because of its shortness).
I also think that addPeaks was just a subroutine for generating a complete spectrum.
I will look into the code again and report more.

**Comment by jpfeuffer** [comment]
Yes,

'''
 void TheoreticalSpectrumGenerator::getSpectrum(RichPeakSpectrum & spec, const AASequence & peptide, Int charge) const
  {
    bool add_b_ions(param_.getValue("add_b_ions").toBool());
    bool add_y_ions(param_.getValue("add_y_ions").toBool());
    bool add_a_ions(param_.getValue("add_a_ions").toBool());
    bool add_c_ions(param_.getValue("add_c_ions").toBool());
    bool add_x_ions(param_.getValue("add_x_ions").toBool());
    bool add_z_ions(param_.getValue("add_z_ions").toBool());

    for (Int z = 1; z <= charge; ++z)
    {
      if (add_b_ions)
        addPeaks(spec, peptide, Residue::BIon, z);
      if (add_y_ions)
        addPeaks(spec, peptide, Residue::YIon, z);
      if (add_a_ions)
        addPeaks(spec, peptide, Residue::AIon, z);
      if (add_c_ions)
        addPeaks(spec, peptide, Residue::CIon, z);
      if (add_x_ions)
        addPeaks(spec, peptide, Residue::XIon, z);
      if (add_z_ions)
        addPeaks(spec, peptide, Residue::ZIon, z);
    }

    bool add_precursor_peaks(param_.getValue("add_precursor_peaks").toBool());
    if (add_precursor_peaks)
    {
      addPrecursorPeaks(spec, peptide, charge);
    }

    bool add_abundant_immonium_ions(param_.getValue("add_abundant_immonium_ions").toBool());
    if (add_abundant_immonium_ions)
    {
      addAbundantImmoniumIons(spec);
    }

    return;
  }
'''

This would be the method to use to get a full spectrum. It also adds precursor peaks and immonium ions. I am almost sure that this method works fine. There are some other things to consider (e.g. there is also no x_1 and c_n fragment and some end-fragmentation are already considered when adding neutral losses of the precursor), but you can look at this test in the according test file:

'''
AASequence new_peptide = AASequence::fromString("DFPLANGER");
  /**  From http://db.systemsbiology.net:8080/proteomicsToolkit/FragIonServlet.html
   Seq    #       A            B            C            X            Y            Z         # (+1) 
    D     1     88.03990    116.03481    133.06136       -        1018.49583   1001.46928    9 
    F     2    235.10831    263.10323    280.12978    929.44815    903.46888    886.44233    8 
    P     3    332.16108    360.15599    377.18254    782.37973    756.40047    739.37392    7 
    I     4    445.24514    473.24005    490.26660    685.32697    659.34771    642.32116    6 
    A     5    516.28225    544.27717    561.30372    572.24291    546.26364    529.23709    5 
    N     6    630.32518    658.32009    675.34664    501.20579    475.22653    458.19998    4 
    G     7    687.34664    715.34156    732.36811    387.16287    361.18360    344.15705    3 
    E     8    816.38924    844.38415    861.41070    330.14140    304.16214    287.13559    2 
    R     9    972.49035   1000.48526       -         201.09881    175.11955    158.09300    1 
  **/

  double result_all[Size(52)] = { 88.03990,116.03481,133.06136,1018.49583,1001.46928,235.10831,263.10323,280.12978,929.44815,903.46888,886.44233,
    332.16108,360.15599,377.18254,782.37973,756.40047,739.37392, 445.24514,473.24005,490.26660,685.32697,659.34771,642.32116,
    516.28225,544.27717,561.30372,572.24291,546.26364,529.23709, 630.32518,658.32009,675.34664,501.20579,475.22653,458.19998,
    687.34664,715.34156,732.36811,387.16287,361.18360,344.15705, 816.38924,844.38415,861.41070,330.14140,304.16214,287.13559,
    /*972.49035 basically neutral loss of prec,*/1000.48526,201.09881,175.11955,158.09300};
  std::sort(result_all,result_all+Size(51));
  spec.clear(true);

  param.setValue("add_first_prefix_ion", "true");
  param.setValue("add_a_ions", "true");
  param.setValue("add_b_ions", "true");
  param.setValue("add_c_ions", "true");
  param.setValue("add_x_ions", "true");
  param.setValue("add_y_ions", "true");
  param.setValue("add_z_ions", "true");
  param.setValue("add_precursor_peaks", "true");
  ptr->setParameters(param);
  ptr->getSpectrum(spec, new_peptide, 1);
'''

If you still think something is wrong, I will look into it further. I agree, that it might not be as simple as possible.

**Comment by hendrikweisser** [comment]
@jpfeuffer:
Thanks for looking into this! So in the code Petra posted, the loop for the fragments doesn't iterate till the end of the peptide because that would correspond to the full peptide, and there's an extra setting for including that ("add_precursor_peaks").

**Comment by jpfeuffer** [comment]
That is correct. add_precursor_peaks also adds different neutral losses of the precursor (corresponding to other "series_1" or "series_n" fragments). And the beginning of the series is most likely omitted (by default) because of empirical experience (b_1 almost never observed).

**Comment by hendrikweisser** [comment]
> add_precursor_peaks also adds different neutral losses of the precursor (corresponding to other "series_1" or "series_n" fragments).

Hm, that is a bit too clever for my liking. How would I get just the full b/y ion ladder for a peptide?

**Comment by jpfeuffer** [comment]
You are right. Currently, how I see it, this is not easily possible.

**Comment by PetraGutenbrunner** [comment]
Thanks for your help, there is no further question about this.
