### ISSUE TITLE
Suboptimal score selected in MSGFPlusAdapter

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1691]
The `MSGFPlusAdapter` now uses internally a direct conversion from the MS-GF+ output format `mzid` to `idXML`. The scores are incorrectly imported. That leads in a standard `MSGFPlusAdapter/PeptideIndexer/IDPosteriorErrorProbability` workflow to the following `IDPosteriorErrorProbability` crash.
```
No data collected. Check whether search engine is supported.
```
See earlier discussion here https://github.com/OpenMS/OpenMS/pull/1679#issuecomment-153070360 and the following example `idXML` file.
https://gist.github.com/lars20070/cbcd3f0f623b2be074b7

**Comment by lars20070** [comment]
@mwalzer Which of the tools need to be fixed for a standard `MSGFPlusAdapter/PeptideIndexer/IDPosteriorErrorProbability` pipeline to work? Could you please comment?

**Comment by mwalzer** [comment]
The scores are not incorrectly imported. As seen [here](https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp#L1295) all scores are accounted for. 
But as all search engines are reporting a plethora of scores and interpretations of common scoring schemes, who is to say which is score* (and for which occasion anyway?). Each tool, should know which score it is expecting, and fetch it _to_ the score field, if not already there. But that is not part of the handler.
So as a compromise, the handler is doing the following:
If there is a q-value, it will take this as the score, its presence signifing that the ids have already been post-processed.  If not, one thing you can almost rely on being present in each file is the "raw score", which is assigned the score. As a last fallback solution, there are E-values which is somewhat unfavorable, as there are so many flavors to that.

**Comment by mwalzer** [comment]
I've closed the issue. We can still use this thread to talk about which tools need new issues to pull their favoured scores.

**Comment by hendrikweisser** [comment]
@mwalzer:
Thanks for the explanation. This actually seems like a pretty good heuristic to me:
> If there is a q-value, it will take this as the score, its presence signifing that the ids have already been post-processed. If not, one thing you can almost rely on being present in each file is the "raw score", which is assigned the score. As a last fallback solution, there are E-values which is somewhat unfavorable, as there are so many flavors to that.

So in order to make the pipeline work, the fix would have to be in IDPosteriorErrorProbability (IDPEP). That tool would need to check whether the correct score type is already present, and if not, look for a matching meta value. This would have to be done in a search engine-dependent manner.
In the meantime, it should be possible to make it work by adding an appropriate IDScoreSwitcher step before IDPEP.

**Comment by lars20070** [comment]
After a discussion at Gitter, @hendrikweisser and I agree that _the_ peptide score should be set by the `mzid` handler to be `MS:1002052`.

**Comment by lars20070** [comment]
Does `MS:1002052` simply need to be added here
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp#L1259
as a further e-score?

**Comment by mwalzer** [comment]
I already said that somewhere, the issue title is **totally misleading**. There is no incorrect value!
And there is no _further_ e-score, they (the scores) are **all** read into the meta info interface. 
Just switch the score member assignment to what you deem is better, just make it pretty obvious in the documentation, which type is the score member by default and how to switch.

**Comment by hendrikweisser** [comment]
Guys, I think I have the solution to the problem. (I must say I also added to the confusion, sorry about that.)

@mwalzer is right that in the MzIdentMLDOMHandler, there needs to be a general, search engine-independent (!) approach to selecting one of potentially multiple scores as *the* score of a peptide hit. I agree with his approach of trying q-value -> raw score -> E-value in this order.

However, specifically for MS-GF+, we initially want the SpecEValue as the score - not the q-value or the raw score. Still, it doesn't make sense to add the logic for this in the MzIdentMLDOMHandler.

The simple solution is to switch the score in the MSGFPlusAdapter, after reading in the mzid. Just get the SpecEValue from the meta value and set it as the score.

**Comment by hendrikweisser** [comment]
@lars20070: Maybe you could change the issue title - I agree with @mwalzer that it's misleading. "Suboptimal score selected..." or something like that?

**Comment by mwalzer** [comment]
:+1:

**Comment by hendrikweisser** [comment]
@mwalzer:
@lars20070 and I just noticed that the search engine scores that the MzIdentMLDOMHandler writes to meta values are stored as strings - which was the reason why IDScoreSwitcher didn't work for them. I can't think of any case where a score wouldn't be numeric, so shouldn't they better be stored as float meta values?

**Comment by mwalzer** [comment]
yeah, you're probably right
