### ISSUE TITLE
MzTabExporter: header columns don't match with data columns

### ISSUE THREAD

**Issue by PetraGutenbrunner** [OpenMS/OpenMS#1703]
If the number of meta values in the protein/peptide hit differs, in the output tsv file the number of header columns is not equal to the number of optional meta values.
This happends because the header information of the optional meta values is extracted of the first element (e.g. first peptide hit).
If this element doesn't contain all possible meta values, the header doesn't contain all columns.

This happened after using PhosphoScoring, because depending on the phospho site an Ascore is calculated or not.

Example: 
![mztabexport_output](https://cloud.githubusercontent.com/assets/6952271/11117997/720a70a8-8936-11e5-9923-82ac570eb7c9.PNG)
[mztabexport_idxml_example.txt](https://github.com/OpenMS/OpenMS/files/32841/mztabexport_idxml_example.txt)

**Comment by oliverschilling** [comment]
Same observation in Freiburg...

**Comment by timosachsenberg** [comment]
Thanks for fixing the issue. +1 fell free to open the pull request

**Comment by hendrikweisser** [comment]
Looks like this was fixed in #1705. Closing.
