### ISSUE TITLE
IDFilter API needs overhaul

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1706]
The IDFilter TOPP tool, and the underlying library class of the same name, provide a variety of useful filtering options for peptide and protein identification data. However, the API of the library class is not very well thought-out:
- most of the method names start with "filterIdentifications", which carries no information (since the class is already called "IDFilter")
- moreover, the "filterIdentifications" sometimes refers to peptide IDs and sometimes to protein IDs
- the method names "filterIdentificationsByX" generally don't indicate whether IDs that satisfy "X" are kept or removed
- the "filterIdentificationsBy..." methods use a const reference as input and write to a reference as output; to save lots of copying back and forth, they should simply use one reference for input/output and modify it, or be turned into predicates (returning bool) that can be used with `std::remove_if`
- most of the "filterIdentificationsBy..." methods operate on a single peptide or protein ID; in some cases (e.g. filtering based on a FASTA file) this means that lots of preprocessing is repeated for every ID

**Comment by timosachsenberg** [comment]
I agree.

"the "filterIdentificationsBy..." methods use a const reference as input and write to a reference as output; to save lots of copying back and forth, they should simply use one reference for input/output and modify it, or be turned into predicates (returning bool) that can be used with std::remove_if"

I think predicates are the way to go. (Actually, this would be such a great place for lambdas ;) which we can't use yet)

Predicates could also solve the last point as they would just need to store the preprocessed data.

**Comment by hendrikweisser** [comment]
> I think predicates are the way to go.

Yes, with predicates and a few higher-level functions ("remove hits/IDs if this predicate matches/doesn't match") we should be able to cover most of the current functionality. I'll take a stab at this over the coming weeks.

> (Actually, this would be such a great place for lambdas ;) which we can't use yet)

I just had a look at our ticket for C++11 again: #980
I think we should have a discussion about moving to C++11 at the developer meeting (if not earlier).

**Comment by hendrikweisser** [comment]
Solved via #1778.
