### ISSUE TITLE
make DecoyDatabase append "true" as default

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1711]
Based on some feedback from users I think it might be the more common use case to use DecoyDatabase in append mode.
Maybe we should make this default.

**Comment by lars20070** [comment]
+1

**Comment by hendrikweisser** [comment]
Also, shouldn't the decoy identifier in the accession ("REV" or "DECOY") be a prefix by default? I don't know anyone who uses a suffix.
Also also, the parameter controlling this should be the same in DecoyDatabase and PeptideIndexer (currently "decoy_string_position" vs. "prefix"). (Anywhere else?)

**Comment by timosachsenberg** [comment]
Another request by a user to make append the default.
He also mentioned the exact same prefix problem @hendrikweisser mentioned.
I think we should go forward with this.

**Comment by lars20070** [comment]
Can we agree on these default parameter settings?
```
append = true
decoy_string = dec_
decoy_string_position = prefix
```

**Comment by timosachsenberg** [comment]
can you give good reasons for the other two defaults that merit a chance?

**Comment by lars20070** [comment]
A prefix is easier to spot in long protein lists, see comments by @hendrikweisser. 

The `dec_` string is short and agnostic to whether a shuffled or reversed decoy database was used. For example when changing from a reversed to a shuffled decoy database, only the database not the workflows need to be modified.

**Comment by mwalzer** [comment]
:+1:
