### ISSUE TITLE
Search engine adapters should set "spectrum_reference" in idXML

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1716]
The idXML schema contains an attribute "spectrum_reference" of "PeptideIdentification" elements, that can store the "Integer reference number of the identified spectrum (or feature)". This should be supported by TOPP tools (search engine adapters and IDFileConverter) as far as possible, but currently isn't. Having this information would make it easier to link PSMs back to the spectra that generated them, and to convert idXML to file formats that need the references (mzIdentML, mzTab).

**Comment by timosachsenberg** [comment]
I think we absolutely need some spectrum_reference.
@mwalzer what is your take on this? I think you proposed once to store the native identifier.

**Comment by hendrikweisser** [comment]
> I think you proposed once to store the native identifier.

If that would allow us to convert to mzIdentML/mzTab without consulting the original mzML file again, we should absolutely do that. Currently the "spectrum_reference" attribute is only an unsigned int - so perhaps a case for the schema extension in #1671?

**Comment by mwalzer** [comment]
Absolutely. But we still have the problem that some SE adapters do not write a spectrum_reference.
Workaround would be a re-annotation with IDFileConverter (mzml+)idXML<->idXML. My experimental implementation makes a minor addition to the SpectrumMetaDataLookup class analogue to mzid RT annotation, adding a MetaValue.
Do we want a string member at PeptideIdentification? We could also parse the scan id out of the reference and reduce the string to an int, but in lookup situations we might have to parse it all again, if one side is just keeping the references (e.g. mzid references with a string, so it might be 'anything'). And we loose the additional info, which I can not foresee if would make trouble with data from some instruments.
What do you guys think?
@hendrikweisser I've seen that you did some extra work there for mascot. How do you deal with mascot results (in general, I mean)?

**Comment by hendrikweisser** [comment]
@mwalzer:
> I've seen that you did some extra work there for mascot. How do you deal with mascot results (in general, I mean)?

I don't understand the question. What's "there", and what do you want to know about Mascot?

**Comment by timosachsenberg** [comment]
hmm so we basically have to choose between the full native identifier or a condensed int like index - is this correct?

As far as I know an int index is the prefered way to identify spectra in mzML files.
Problems arise if the original spectrum is filtered and we want to preserve the original spectrum index.
One way to solve this is to have both, the native index and the current index stored in the file.

**Comment by hendrikweisser** [comment]
> hmm so we basically have to choose between the full native identifier or a condensed int like index - is this correct?

I'd say there are actually three possibilities: native ID (string), index (int), and scan number (int), to use the nomenclature from the SpectrumLookup class.
The index is not useful as a spectrum reference: Generally we only want to load MS2 spectra from the mzML files into search engine adapters, so using indexes, the numbering would already be different from the original mzML file.
The scan numbers don't have this problem, but they need to be extracted from the native ID, and the format can vary. However, this is already taken care of in `SpectrumLookup::extractScanNumber`.

**Comment by timosachsenberg** [comment]
I agree, I used the terms differently.
For reference the terms used to reference the original (native) spectra in the CV:
```
MS:1000776	scan number only nativeID format	scan=xsd:nonNegativeInteger	Used for conversion from mzXML, or a DTA folder where native scan numbers can be derived.
MS:1000777	spectrum identifier nativeID format	spectrum=xsd:nonNegativeInteger	Used for conversion from mzData. The spectrum id attribute is referenced.
MS:1001530	mzML unique identifier	xsd:string	Used for referencing mzML. The value of the spectrum id attribute is referenced directly.
```

**Comment by mwalzer** [comment]
@hendrikweisser I was wondering if you use something different than MascorAdapter...

>As far as I know an int index is the prefered way to identify spectra in mzML files.

I think this preference did not arrive with the search engine authors..

>The index is not useful as a spectrum reference

agreed
so @timosachsenberg did you refer with index to MS:1001530 ? If we can extract the scan number from the native_id with SpectrumLookup in most cases,  thats fine for me. In which cases would this fail?  
And if we would have to reannotate the identifications anyways we could also add the mzML unique identifier. Though I have not seen that CV in any mzML. But I just looked that up in the schema and it appears that the id attribute of spectrum has a doc-string which also names it 
```
The native identifier for a spectrum. For unmerged native spectra or spectra from older open file formats, the format of the identifier is defined in the PSI-MS CV and referred to in the mzML header.
```
so I guess MS:1001530 and native ID and spectrum_reference (in some mzid files) are the same ...
What about adding a int member to peptide id?

**Comment by timosachsenberg** [comment]
@mwalzer you seem to have a good overview: which search engine does write out the native id / original scan index, which one the index of the e.g. filtered mzML index and which one don't write out any information?

**Comment by hendrikweisser** [comment]
@mwalzer:
> I was wondering if you use something different than MascorAdapter...

I use MascotAdapterOnline (MAO) followed by MascotPercolator (via GenericWrapper). So I use MAO to submit the query and run the search, but I don't use the output from MAO. MascotPercolator reads the Mascot .dat file directly from the server and produces output from that.

**Comment by mwalzer** [comment]
@hendrikweisser ah, nice. Does the MascotPercolator write pep.xml then? Would you know other ways to get to the full scoring details of a PSM from mascot (or the spectrum info for that matter)? MAO is somewhat limited there.

@timosachsenberg afaik none is writing the scan_index (I think xtandem might in its own xml), msgf is writing the native ID and the pep.xml familiy is using both. And with mascot, we're rather on the blind side (MAO issues I guess).

**Comment by hendrikweisser** [comment]
> Does the MascotPercolator write pep.xml then?

No, it produces the standard tab-delimited output that you get from Percolator (see class "PercolatorOutfile").

> Would you know other ways to get to the full scoring details of a PSM from mascot (or the spectrum info for that matter)? MAO is somewhat limited there.

MAO gets data in Mascot's XML format from the Mascot server. That (temporary) file is preserved if you run MAO with a high enough debug level. Perhaps the information you want is still in that file and gets lost only on conversion to idXML?

By the way, newer version of Mascot can export to mzIdentML. At some point we could change the adapter to use that rather than Mascot's own XML format.

**Comment by mwalzer** [comment]
>That (temporary) file is preserved if you run MAO with a high enough debug level. Perhaps the information you want is still in that file and gets lost only on conversion to idXML?

Yeah, but I had hoped for some less coding effort ;)

>can export to mzIdentML

Jup, to bad though that I am limited to v2.2 - but they are doing that export like any other with pearl scripts :scream:

**Comment by hendrikweisser** [comment]
The discussion here went a bit off topic, but we should check which of our search engine adapters currently do/don't write out the spectrum references (and if they do, in which format).

**Comment by timosachsenberg** [comment]
Probably just check the thirdparty testfiles ?

**Comment by jpfeuffer** [comment]
Unfortunately they are often whitelisted. I encountered the same with the origin files. So better to look through the code.
