### ISSUE TITLE
MzTabExporter: modification "Phospho (ST)" throws error

### ISSUE THREAD

**Issue by PetraGutenbrunner** [OpenMS/OpenMS#1740]
If a MascotAdapterOnline search was done using fixed or variable modification "Phospho (ST)" as parameter the search parameters were listed in the output idXML file:

![modification_phospho_st](https://cloud.githubusercontent.com/assets/6952271/11537491/24ae381e-9915-11e5-92ca-a7ec0ca51f87.PNG)

After the search I wanted to converted the idXML to a tab delimited file using MzTabExporter and got following error:

----------------------------------------------------------------------------------------------------------
16:37:40 NOTICE: MzTabExporter of node #5 started. Processing ...
exporting identifications: "/tmp/2015-12-02_151417_gen1b_45346_1/TOPPAS_tmp/quantification/003_PhosphoScoring/out/14.idXML" to mzTab: 
Error: Unexpected internal error (the element 'Phospho (ST)' could not be found)

----------------------------------------------------------------------------------------------------------

The reason that causes this error is in:
-> topp\MzTabExporter.cpp 
-> static map\<Size, MzTabModificationMetaData> generateMzTabStringFromModifications(const vector\<String>& mods):
-> ResidueModification m = mod_db->getModification(*sit);

'Phospho (ST)' is not listed in the UniMod modifications. The modification must be separated in 'Phospho (S)' and 'Phospho (T)'.

**Comment by timosachsenberg** [comment]
@cbielow @hendrikweisser does this ring a bell? I though we had this specifity group issue before.

**Comment by hendrikweisser** [comment]
Yes, there's an advanced parameter "special_modifications" defined for MascotGenericFile that lists the problematic cases. This allows us to translate modifications set by the user to the form that Mascot understands, but apparently we don't translate them back when we generate the SearchParameters.

**Comment by timosachsenberg** [comment]
I assume this is ficed with PR #1868
