### ISSUE TITLE
ResidueDB: adding a new residue (e.g. mass tag in AASequence) triggers rewriting of all residue lookup structures

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1747]
buildResidueNames_(); is called at end of addResidue_ this is highly inefficient.
Especially if e.g. thousands of different mass tags are added

**Comment by jpfeuffer** [comment]
This function does not exist anymore. This doesn't mean adding residues is very efficient though. But I will close.
