### ISSUE TITLE
"Boost" not found error while installing

### ISSUE THREAD

**Issue by somakray** [OpenMS/OpenMS#1748]
Hi,
While installing the latest version of openMS in my Ubuntu 12.04 I get the following error:

:~/openms_utils/OpenMS-build$ cmake -DCMAKE_PREFIX_PATH="/home/pipeline/openms_utils/contrib-build;/usr;/usr/local" -DBOOST_USE_STATIC=OFF ../OpenMS-2.0.0

-- Building OpenMS 2.0.0
--   - Repository revision HEAD-HASH-NOTFOUND
--   - Repository branch HEAD-HASH-NOTFOUND
--   - Repository last change date HEAD-HASH-NOTFOUND
-- OpenMP: ON
-- Architecture: 64 bit
-- Compiler checks for conversion: OFF
-- Adding library OpenSwathAlgo
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Adding library OpenSwathAlgo - SUCCESS
-- Found XercesC: /usr/lib/libxerces-c.so (found version "3.1.1")
-- Could NOT find Boost
CMake Error at src/openms/cmake_findExternalLibs.cmake:71 (message):
  Boost or one of its components not found!
Call Stack (most recent call first):
  src/openms/CMakeLists.txt:63 (include)

-- Configuring incomplete, errors occurred!

**Comment by hroest** [comment]
did you install boost through your packaging system ? what does `dpkg -l | grep boost` tell you?

**Comment by mwalzer** [comment]
Or have a look at  [the documentation](ftp://ftp.mi.fu-berlin.de/pub/OpenMS/documentation/html/install_linux.html). As the problem seemed to not persist I will close that.
