### ISSUE TITLE
TOPPView documentation is still a buildtarget with WITH_GUI=off

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#1754]
eventually leading to a build error.

**Comment by jpfeuffer** [comment]
Could you give me your OS info and your command?

**Comment by mwalzer** [comment]
SL 6, cmake

**Comment by mwalzer** [comment]
So I guess you wanted my settings: I used the standard cmake settings like in the documentation and switched WITH_GUI=off 
As it is a builderror in the documentation part, it is not that critical as everything else did build, though it is an error
