### ISSUE TITLE
Make Trypsin without Keil rule (=may cut before proline) as default ("Trypsin/P").

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1763]
http://pubs.acs.org/doi/abs/10.1021/pr0705035

**Comment by hroest** [comment]
not sure about changing the default just yet based on one report, but we should have it as an option...

**Comment by mwalzer** [comment]
also related https://github.com/OpenMS/OpenMS/issues/590

**Comment by timosachsenberg** [comment]
the enzyme is already in EnzymesDB so this is more about if we should adapt the default
