### ISSUE TITLE
-use_ms1_traces in OpenSwathWorkflow crashes when the TraML library contains decoys generated by OpenSwathDecoyGenerator

### ISSUE THREAD

**Issue by SimionKreimer** [OpenMS/OpenMS#1769]
I'm trying to impliment the OpenSWATH workflow on an archlinux system. I successfully execute the command: 

OpenSwathDecoyGenerator -in Library.TraML -out Library_Decoys.TraML -method shuffle -append -exclude_similar -remove_unannotated

to add decoy spectra to my library. Then when I execute the command:

OpenSwathWorkflow -threads 4 -in DIA_file.mzXML -tr Library_Decoys.TraML -tr_irt PRTCFinal.TraML -out_tsv Results.tsv -rt_extraction_window -120 -mz_extraction_window 10 –ppm –use_ms1_traces

I get the following output:

Loading mzXML file UF_DIA_Good2.mzXML using readoptions normal
Progress of 'Loading metadata file UF_DIA_Good2.mzXML':
While loading 'UF_DIA_Good2.mzXML': Unexpected CV entry 'msIonization'='nanoelectrospray'
While loading 'UF_DIA_Good2.mzXML': Unexpected CV entry 'msMassAnalyzer'='quadrupole'
While loading 'UF_DIA_Good2.mzXML': Unexpected CV entry 'msDetector'='inductive detector'
Will analyze the metadata first to determine the number of SWATH windows and the window sizes.
Determined there to be 56 SWATH windows and in total 2536 MS1 spectra
Determined there to be 56 SWATH windows and in total 2536 MS1 spectra
-- done [took 2.01 s (CPU), 2.10 s (Wall)] -- 
Progress of 'Loading data file UF_DIA_Good2.mzXML':
While loading 'UF_DIA_Good2.mzXML': Unexpected CV entry 'msIonization'='nanoelectrospray'
While loading 'UF_DIA_Good2.mzXML': Unexpected CV entry 'msMassAnalyzer'='quadrupole'
While loading 'UF_DIA_Good2.mzXML': Unexpected CV entry 'msDetector'='inductive detector'
While loading 'UF_DIA_Good2.mzXML': Unexpected CV entry 'msIonization'='nanoelectrospray'
While loading 'UF_DIA_Good2.mzXML': Unexpected CV entry 'msMassAnalyzer'='quadrupole'
While loading 'UF_DIA_Good2.mzXML': Unexpected CV entry 'msDetector'='inductive detector'
-- done [took 20.11 s (CPU), 7.72 s (Wall)] -- 
Will load iRT transitions and try to find iRT peptides
Progress of 'Retention time normalization':
Warning: MRMFeatureFinderScoring received the unknown parameter 'EMGScoring:deltaRelError'!
Will analyse 3 peptides with a total of 24 transitions 
WARNING in SignalToNoiseEstimatorMedian: 1.39002% of all Signal-to-Noise estimates are too high, because the median was found in the rightmost histogram-bin. You should consider increasing 'max_intensity' (and maybe 'bin_count' with it, to keep bin width reasonable)
rsq: 0.999858 points: 3
-- done [took 0.18 s (CPU), 0.18 s (Wall)] -- 
Progress of 'Load TraML file':
-- done [took 0.18 s (CPU), 0.19 s (Wall)] -- 
Will analyze 1184 transitions in total.
Progress of 'Extracting and scoring transitions':
Segmentation fault (core dumped)

The segmentation fault error does not occur when I don't use the use_ms1_traces option or when I use a library without decoys. I plan to send the results to pyprophet so I need to include decoys, and i would also like to score based on ms1 traces. So I'm in a bit of pickle. I tried to generate decoy spectra with SpectraST but pyprophet doesn't seem to understand that the spectra are decoys. Any suggestions?

Best, Simion

**Comment by hroest** [comment]
Hi @SimionKreimer 

I would love to take a look at the input data that you used to see whether I
can recreate the segfault. I would also be happy with a debugger trace if you
can generate one. Also, did you try to run the decoy generator a second time
to see whether it fails again with a different set of random assays?

If you want to fix the output and ready it for pyProphet, i think the only
thing you need to do is write a small script that designates which assays are
target and which ones are decoys. You can do this on the input file to
pyProphet. There should be a "decoy" column in the csv file that needs to be
set. This should allow you to use decoys generated by SpectraST -- maybe @grosenberger can go into details how SpectraST decoys work with openswath?

Alternatively, you could (for now) skip the MS1 traces. This option is
currently experimental and we dont have much experience how much gain it
brings to the identification.

Best

Hannes

**Comment by SimionKreimer** [comment]
Hi Hannes,
Thank you for getting back to me. For now, I'm generating the decoys in SpectraST and then labeling them in the decoy column as you've suggested, this seems to work fairly well. I tried executing the OpenSwathWorkflow with two DIA data files and three assay libraries and in each case the workflow failed when the decoy generator peptides were added and the MS1 traces were used, in all other cases the workflow completed successfully. I think the MS1 traces are pretty useful for filtering based on precursor mass accuracy. I'm adding a link to a Dropbox folder with the inputs for the workflow. The assay library I put in has not been processed with the DecoyGenerator.
https://www.dropbox.com/sh/kt8cdm317r7axd5/AADdLu-_5Hq0mfPhuCzCFQosa?dl=0
Best, Simion

**Comment by grosenberger** [comment]
Hi Simion,
Thanks for reporting this problem. Using the OpenSWATH decoys with the MS1 scoring enabled worked in many analyses that I tried. Could you please also upload the Library.TraML and Library_Decoys.TraML that failed so I can have a look at it?

Regarding the generation of decoys using SpectraST: This might work as well and OpenSwathDecoyGenerator implements nearly the same algorithms. However, we employ some further controls to ensure that decoys are different enough from the targets. Depending on your assays and peptide sequence, you should ensure that the decoy distribution looks as expected.

Best regards,
George

**Comment by SimionKreimer** [comment]
Hi George,
Maybe it's a bug specific to my system, I'm running on ArchLinux? I just uploaded the library with decoys (just tried it and I'm still getting the segmentation fault), have a look. I can try generating a debug report, if one of you you explains how to do that.

Best, Simion

**Comment by hroest** [comment]
Hi @SimionKreimer 

I have generated a PR in  #1772 which should fix the issue from the OpenSwath side. Apparently the software choked if it was given a TraML where peptides were present but no associated transitions were in there

@grosenberger can you check why the decoy generator produces such TraML files, I dont think they are legal and make much sense. Maybe you can adopt the decoy generator to remove such peptides?

Hannes

**Comment by grosenberger** [comment]
Hey Hannes,
Thanks for patching this. I have come to the same conclusion. I will change this in OpenSwathDecoyGenerator, this should not happen. In the mean time and if anybody wants to use OpenMS 2.0, just convert the decoy TraML to CSV and back with ConvertTraMLToTSV and ConvertTSVToTraML. This will generate a valid assay library.

Best regards,
George

**Comment by hroest** [comment]
great, thanks a lot.

@SimionKreimer the solution by George also seems like a good fix in your case if you dont want to apply the patch

**Comment by SimionKreimer** [comment]
Ok the two convert steps seem like a good solution, thanks guys!
