### ISSUE TITLE
Travis OSX builds

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#1774]
Should this
https://github.com/OpenMS/OpenMS/blob/9a795431d0e8f45bc9a4a6462f3b83517b72e9b3/tools/travis/osx-cibuild.before.sh#L43
be pointing to the OSX binaries? Or are they somehow compatible with how the OSX CI builds are run on travis?

**Comment by timosachsenberg** [comment]
I fixed it in the current build script
