### ISSUE TITLE
CMake handling of Thirdparty executables

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#1775]
I find it very confusing, having to have all the single searchengine directories in the path for building OpenMS. Especially when we additionally have to specify a -DSEARCH_ENGINE_DIRECTORY parameter for when building the KNIME package.
Does anyone know if there is a reason behind that solution? How hard is it to change it (e.g. just using a -D parameter)?

**Comment by cbielow** [comment]
I guess introducing -D params is possible, but it only delays the following problem:

If you create a new XTandem/OMSSA/WHATEVER Adapter, the default executable is set to just the filename without path. If your Search engines are in the path, the adapter is ready to go without much hassle. If every user has to adapt the executable setting this means the following things will break:
- more effort to create a pipeline (i.e. more params to configure)
- pipeline exchange with other users (rather unlikely that another user has the same path to Xtandem, say)
- changing search engine versions by just modifying the PATH environment in which TOPPAS/KNIME is run (very powerful, IMHO).

In the end, I guess both approaches will work, but I think the current solution is better from a user perspective.

**Comment by jpfeuffer** [comment]
Okay, makes sense. I will nonetheless update the documentation about this. I think it is not clear enough, when to use the -D option and when and how to include the Searchengines in the path.

**Comment by timosachsenberg** [comment]
has this been documented? can we close the issue?

**Comment by hendrikweisser** [comment]
@jpfeuffer: See Timo's questions above.
