### ISSUE TITLE
Problems with file attributes in pyOpenMS

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1777]
I ran into some problems (re-)building pyOpenMS on my Mac.

When I run "make -j 4 pyopenms", after it says "created pyopenms.cpp", I get this error:
```
Traceback (most recent call last):
  File "create_cpp_extension.py", line 158, in <module>
    shutil.copy(j(QT_LIBRARY_DIR, "QtCore.framework", "QtCore"), "pyopenms")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 116, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'pyopenms/QtCore'
```
The reason is that the file "pyopenms/QtCore" was created with reading rights only and thus cannot be overwritten. The same goes for "pyopenms/QtNetwork". When I manually set writing rights for these files (`chmod u+w QtCore QtNetwork`) and restart the build process, it works.

Later, to test if everything worked, the documentation says to execute "run_nose.py" and "run_memleaks.py". However, these scripts are not flagged as executable on my system, so I can't run them as described in the documentation (I get "Permission denied"). Passing them to Python works (e.g. "python run_nose.py"), but either the documentation should be updated to reflect that or the files should be set as executable.

**Comment by hroest** [comment]
ok, can you try to run https://github.com/hroest/OpenMS/tree/fix/pyopenms_mac_fix which should address most of these issues. Basically I added 

```
+    os.chmod("pyopenms/QtCore", 0744)
+    os.chmod("pyopenms/QtNetwork", 0744)
```

to the script, I have not tested it as I dont have a mac

**Comment by hendrikweisser** [comment]
That "chmod" command seems to also set the executable flag on the Qt... files, which is not necessary. It also only works on a first install or one where the files are already readable (because the copy is executed before the "chmod"), but that's okay with me.

The mode change on the test scripts didn't seem to make a difference on my system. (I used "git pull" to merge in the changes from your branch.)

**Comment by hroest** [comment]
can you think of a better way to approach this? maybe just put it into a
try-catch block and fail with a warning. this is actually only important if
the user has updated the Qt libraries in the meantime and we could add a
comparison of checksums:

- if checksums are equal, fail silently
- if checksums do not match, try to copy and fail hard

**Comment by hendrikweisser** [comment]
I think it's okay the way it is. It's probably rare that someone has the preconditions that trigger this bug, and for the future it's fixed by your change.

**Comment by hroest** [comment]
should we close this bug?

**Comment by hendrikweisser** [comment]
I've noticed this bug again on my system. Have Hannes' changes (https://github.com/hroest/OpenMS/tree/fix/pyopenms_mac_fix) actually been integrated in OpenMS?
