### ISSUE TITLE
PeakPickerHires is picking the chromatogram come what may

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#1780]
mzML from pwiz msconvert conversion and picking:

```
Number of spectra: 19812
Number of peaks: 13143477
...
MS levels: 1, 2
Number of spectra per MS level:
  level 1: 3709
  level 2: 16103

Number of chromatograms: 1
Number of chromatographic peaks: 19812

Number of chromatograms per type: 
  total ion current chromatogram:                         1
```

mzML from pwiz msconvert without picking:

```
Number of spectra: 19812
Number of peaks: 79663137
...
MS levels: 1, 2
Number of spectra per MS level:
  level 1: 3709
  level 2: 16103

Number of chromatograms: 1
Number of chromatographic peaks: 19812

Number of chromatograms per type: 
  total ion current chromatogram:                         1
```

mzML from pwiz msconvert picking with **PeakPickerHiRes -in in.mzML -algorithm:ms_levels 1 -out out.mzML**:

```
Number of spectra: 19812
Number of peaks: 12239177
...
MS levels: 1, 2
Number of spectra per MS level:
  level 1: 3709
  level 2: 16103

Number of chromatograms: 1
Number of chromatographic peaks: 20

Number of chromatograms per type: 
  total ion current chromatogram:                         1
```

**Comment by mwalzer** [comment]
Can anyone confirm?

**Comment by mwalzer** [comment]
[confirmed](https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.h#L546) on code level.
@hroest and @grosenberger : I guess this is not *generally wanted* behaviour, but when is it wanted to pick chromatograms?

**Comment by hroest** [comment]
Depends, for some people this may be what they want, in our lab we have a lot of files that contain only chromatograms and no spectra. However, most of the time when we do chromatographic peak picking, we actually want to generate features (and featureXML) and not picked mzML. I think we can add a flag that specifies what to do in mixed cases like this and the flag could be "spectra,chromatograms,both" -- the question is what should be default behavior

**Comment by timosachsenberg** [comment]
+1 for the StringList. Spectra might be more natural as we otherwise might pick the TIC. But both is more backwards compatible. I don't mind which choice we take.

**Comment by hroest** [comment]
probably doing spectra only as the default would be wise

**Comment by timosachsenberg** [comment]
anyone who has time to take on this?

**Comment by Stortebecker** [comment]
Does the term "chromatogram" refer to the TIC, here? If so, would it ever be wanted to pick the chromatogram?
