### ISSUE TITLE
Moving THIRDPARTY Tools to GitHub

### ISSUE THREAD

**Issue by ypriverol** [OpenMS/OpenMS#1783]
@timosachsenberg can be possible to move to github as a repo the THIRDPARTY tools that are in http://sourceforge.net/p/open-ms/code/HEAD/tree/THIRDPARTY/ ?

**Comment by timosachsenberg** [comment]
Hi.
I will create the unified THIRDPARTY repo on github.
Let's see if we get into trouble with file size limits

**Comment by timosachsenberg** [comment]
seems to work: https://github.com/OpenMS/THIRDPARTY
we now probably need to adapt the travis scrips to sparse checkouts:
http://stackoverflow.com/questions/600079/is-there-any-way-to-clone-a-git-repositorys-sub-directory-only/13738951#13738951

**Comment by timosachsenberg** [comment]
addapted travis build script:
https://github.com/OpenMS/OpenMS/pull/1784

**Comment by ypriverol** [comment]
@timosachsenberg Great!!

**Comment by timosachsenberg** [comment]
BTW sparse checkouts don't seem to do checkouts on folder level so I used the svn interface of github.
