### ISSUE TITLE
Nightlies are down on cdash

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1785]
Since beginning of the mongth, the nightly builds for Linux have been failing on cdash, see for example http://cdash.openms.de/viewConfigure.php?buildid=161017

**Comment by hroest** [comment]
@jpfeuffer do you know what is going on?

**Comment by jpfeuffer** [comment]
Ah yes, there was an upgrade of this particular machine and it seems like old compiler versions (e.g. gcc4.4) were removed. I will adapt the build scripts to use the newer compiler(s).

**Comment by hroest** [comment]
it seems all gcc builds are failing on linux, only the clang build works http://cdash.openms.de/index.php?project=OpenMS&date=2016-01-26

**Comment by jpfeuffer** [comment]
Ok fixed it somewhat. Picked the wrong path for gcc4.9 but the others work again. (Could not find 4.8 anywhere. I can ask the IT to reinstall that one.)

**Comment by hroest** [comment]
ok, thanks
