### ISSUE TITLE
DigestionEnzyme / EnzymesDB has no concept of NoEnzyme

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#1798]
PSI CV: NoCleavage (MS:1001955)
Though it might be good to keep such annotation so that it is clear there was no loss of data, but there was actually no enzyme involved

**Comment by timosachsenberg** [comment]
So maybe we can add a no cleavage enzyme to EnzymesDB

**Comment by mwalzer** [comment]
:+1:

**Comment by timosachsenberg** [comment]
@liangoaix would this be easily possible or do you see some problems with it?

**Comment by liangoaix** [comment]
Hi, I added the 'no cleavage' (but not 'NoCleavage') in the Enzyme DB: https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/CHEMISTRY/Enzymes.xml#L185
Should it be without space?

**Comment by timosachsenberg** [comment]
@mwalzer seems it is already there - can we close the issue?
