### ISSUE TITLE
MzTabExporter writes peptide features without sequence information into PEP section

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1800]
The sequence column in the PEP section of `mzTab` is required. Currently, even unannotated peptide features are exported.

**Comment by jpfeuffer** [comment]
Hm.. if it is required, I think we should always exclude them.
Or does somebody see a need for an option to keep them, even if the result would be invalid mzTab?

**Comment by lars20070** [comment]
+1 for a flag to keep unassigned peptide features (by default switched off).

Hope that `TextExporter` can be removed as obsolete in the near future. Otherwise we will need to keep (and maintain) `TextExporter`.

**Comment by timosachsenberg** [comment]
The column is mandatory but the sequence may be null

**Comment by timosachsenberg** [comment]
PEP section without sequence information can be used to report features and linked features

**Comment by timosachsenberg** [comment]
The question is if we should do this in MzTabExporter. For me it seems more natural to put this functionality in FileFilter.

**Comment by timosachsenberg** [comment]
ala: -consensus:remove_unidentified                                     Consensus features without PeptideIdentification are removed

**Comment by lars20070** [comment]
I suggested this already to @ypriverol on Gitter.

The `FileFilter` solution or an additional `remove_unidentified` flag (by default true) in `MzTabExporter` is fine with me.

**Comment by ypriverol** [comment]
I'm doing that now.

**Comment by ypriverol** [comment]
But we should make available a couple of examples in the community. A consensus feature is not a peptide .. can be really difficult for the community to understand this

**Comment by lars20070** [comment]
Ok. All workflows in the repository will use `IDMapper` followed by such a `FileFilter` step. Then we do not run into this issue.

@ypriverol Can we close this?

**Comment by timosachsenberg** [comment]
the original intention was to be able to
quantify peptides if e.g. no proteins are quatnified - which basically often boils down to feature based quantification, (often involving alignment and linking)

Its not coincidence that this maps to our consensus feature so I would not call this consensus feature (as this is an OpenMS term) but something like peptide features quantified over several runs.

**Comment by ypriverol** [comment]
@timosachsenberg I just will like to highlight that in the future will be difficult to know or mztab consumers why this is PEP Sequence is null. My recommendation will be to add a Optional CvParam column that specify if the current PEPTIDE is a peptide or a Feature.

**Comment by timosachsenberg** [comment]
hmm I would argue that they would assume that the program quantified something but was not able to assign an ID. But I am open for discussion on this.

**Comment by ypriverol** [comment]
What is "would assume". This is not typed in the mztab in any part, In my opinion we should be clear with this use cases and make the life for external readers easier, and that is why we allow to provide optional fields. Make your file more verbose.

**Comment by timosachsenberg** [comment]
sure we can do this

**Comment by lars20070** [comment]
Does _required/optional_ in the specifications [1] refer to the column or all column entries?

IMO, the column i.e. missing values in the `sequence` column are allowed. In the same way as missing values in the `peptide_abundance_study_variable` column are allowed. Any downstream tool reading the `mzTab` needs to assume that `sequence` and `peptide_abundance_study_variable`can be empty.

[1] see "SC" page 6 here http://mztab.googlecode.com/svn/specification_document-releases/version-1.0.0/20minute_guide_mzTab.pdf

**Comment by timosachsenberg** [comment]
Mandatory and optional columns refers to the presence and absence of columns (not of column entries). Its better described in the specification, so in case of doubt you can look it up there instead of the 20 minutes guide.

**Comment by ypriverol** [comment]
@lars20070 and @timosachsenberg I agree with you that is supported but remember some of these features where allowed to make the file format more open and been able to support use cases. My suggestion is that the document can be at the same time more verbose. For example, if the feature do not have sequence How can I Notice that it is a feature without peptide and not e.g spectrum without identification.

**Comment by lars20070** [comment]
The `PEP` section is for quantitative information at peptide level. Hence, this entry will be a quantified peptide without sequence information. Unidentified MS2 spectra are never reported in `mzTab`.

For me, there is no ambiguity in the output.

**Comment by ypriverol** [comment]
+1 agree with you but taking into account this definition is not either a feature. Anyway, we can discuss more in details thins in the developer meeting but I would like something more verbose using a CV optional parameters..

**Comment by timosachsenberg** [comment]
Spectra are in the PSM section 
----- Original Message -----

**Comment by timosachsenberg** [comment]
Ok lets close it for now an discuss of we need additional cvs at the meeting
