### ISSUE TITLE
OpenSwathFeatureXMLtoTSV only outputs "NA" in Peak_Apex/aggr_Peak_Apex fields

### ISSUE THREAD

**Issue by burlab** [OpenMS/OpenMS#1814]
Peak apex values are present in *.featureXML files (in "peak_apex_int" elements), but are not exported to the CSV file by OpenSwathFeatureXMLtoTSV tool, no matter if short_format is set to false or true. "Peak_Apex" and "aggr_Peak_Apex" fields in the output CSV file contain only "NA" and "NA:NA...", respectively.

**Comment by timosachsenberg** [comment]
can we close this? seems to be fixed
