### ISSUE TITLE
Error: 'std::ostream& OpenMS::operator<<(std::ostream&, const

### ISSUE THREAD

**Issue by sagitter** [OpenMS/OpenMS#1817]
Hi all,

I can't build `OpenMS` on Fedora; please, take a look to this error:

```
/builddir/build/BUILD/openms-2.0.0/py2build/src/openms/source/ANALYSIS/ID/PeptideProteinResolution.cpp:47:89: error: 'std::ostream& OpenMS::operator<<(std::ostream&, const OpenMS::ConnectedComponent&)' should have been declared inside 'OpenMS'
 std::ostream& OpenMS::operator << (std::ostream& os, const ConnectedComponent& conn_comp)
                                                                                         ^
```

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/1556/12981556/build.log

Fedora 24
GCC-6.0.0
OpenMS 6f51b3f3c1eaecdb4469bdd8bd2e12949f68243a

**Comment by timosachsenberg** [comment]
Thanks for reporting,
I think it is related to:
http://stackoverflow.com/questions/4757871/gcc-failes-to-compile-operator-definition-with-prefixed-namespace
The operator needs to be defined in a namespace.
I will provide a fix for it.

@jpfeuffer

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/pull/1818 lets see if this solves the problem

**Comment by sagitter** [comment]
This problem is probably fixed.
I don't know why `make pyopenms` fails (with GCC-6):

```
virtual memory exhausted: Operation not permitted
error: command 'gcc' failed with exit status 1
```

Build log: https://kojipkgs.fedoraproject.org//work/tasks/3232/12983232/build.log

**Comment by timosachsenberg** [comment]
Building pyOpenMS is heavy on memory consumption. I don't know if there is an easy way to reduce its footprint.
Has this problem been fixed in my PR or is it obsolete?

**Comment by sagitter** [comment]
> Has this problem been fixed in my PR or is it obsolete?

The problem reported on this ticket is fixed.
Thank you.

**Comment by hroest** [comment]
@sagitter yes, pyOpenMS builds require a lot of memory so it is easy to run out. What helps is to have more memory available or to use clang
