### ISSUE TITLE
MzTabExporter crash on idXML export

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1820]
The `MzTabExporter` tool crashes on this `idXML` [1] with
```
Error: Unexpected internal error (Could not convert non-StringList DataValue to StringList)
```
[1] https://gist.github.com/lars20070/adfebc5fc6c44c641601

**Comment by ChiayiChen** [comment]
MzTabExporter also crushed in my analysis
Error: Unexpected internal error (Could not convert non-StringList DataValue to StringList)

**Comment by timosachsenberg** [comment]
ok I found the bug. Its related to using spectra_data metavalue in mzIdentML and in OpenMS. In OpenMS we allow for a StringList (as we need to e.g. support merged mgf files etc. - legacy reasons) and in MzIdentML we only allow a String in the MetaValue. I will prepare a fix when I am back at the office (probably next Tuesday). If you need to continue you can try to search and replace the "string" with "stringList" in the idXML.

**Comment by timosachsenberg** [comment]
Hi @lars20070 
In: https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MzTabExporter.cpp#L887
change to ms_runs.size() instead of number of study variables
this should fix the problem

**Comment by lars20070** [comment]
Thanks @timosachsenberg. I will do the PR.

**Comment by lars20070** [comment]
#1853 does not resolve the issue.

**Comment by timosachsenberg** [comment]
did you recreate the mzIdentM

**Comment by lars20070** [comment]
Installation was not updated in Braunschweig. Sorry.
