### ISSUE TITLE
Optimize runtime of PeptideIndexer

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1824]
PeptideIndexer can take a lot of time (many hours) to run if the sequence database (FASTA file) is large, as for example in proteogenomics applications. Most of the runtime is used by the "tolerant" (allowing mismatches) search.

There are several areas where the runtime could be improved:
- The tolerant search does not need to run at all if no mismatches or matches to ambiguous amino acids (AAAs) are allowed, i.e. if the parameters "mismatches_max" and "aaa_max" are both zero.
- If only AAAs are allowed during the tolerant search, only proteins with AAAs need to be considered.
- To consider only a subset of peptides for the tolerant search, a [Dependent StringSet](http://docs.seqan.de/seqan/master/?p=DependentStringSet) from SeqAn can be used, to avoid creating a new StringSet.

I've already addressed these points in a branch: https://github.com/hendrikweisser/OpenMS/tree/peptideindexer-optimize

Further options for improvements:
- The exact string search (Aho-Corasick algorithm) is executed once for every protein sequence (albeit potentially in multiple threads in parallel). Would it be faster to run it only once on the concatenation of the protein sequences?
- There is a lot of conversion between different formats for sequences: strings (input/output), `SeqAn::Peptide` (for searches), AASequence (for trypticity check). Could this be avoided or sped up?
- In some cases it may be enough to find one protein match for a peptide, rather than all (e.g. when matching peptides are later filtered out). How could an "early stopping" flag be added?

**Comment by timosachsenberg** [comment]
I think there might be alot of room for improvement. Maybe it would be a good idea to get some SeqAn guys on board as e.g. an updated version of SeqAn might also provide better fitting index structures. 
@jpfeuffer you are close to the source of SeqAn guys? Do you think it would be possible to pick one and kind of review how we use SeqAn in PeptideIndexer?

**Comment by timosachsenberg** [comment]
@hendrikweisser
FYI: Eugen is planning to move the PeptideIndexer functionality to a class so it can be run internally within other tools (e.g. like his cross-linking search engine). I think conflicts that might arise are between the two branches will be easy to fix - just wanted to let you know.

**Comment by mwalzer** [comment]
BTW the python find function of string is using Aho-Corasick and I've found it to make a speed increasing difference if you search only one big string. Then you also get rid of at least some of the (repeated) conversions.

**Comment by timosachsenberg** [comment]
This would be a viable option but we might also consider an algorithmic improvement e.g. the FMIndex in SeqAn 2.0 might be faster for exact and approximate string matching. This might even simplify the code.

**Comment by jpfeuffer** [comment]
But we might also need to adapt ConsensusID using the SeqAn alignment module if we update to 2.0

**Comment by timosachsenberg** [comment]
Good point. At some point, we need to upgrade to SeqAn 2.0 and it would be good to get an estimate how much work this would involve.

**Comment by hendrikweisser** [comment]
See also #1313.

**Comment by mwalzer** [comment]
always in favour of code reduction :+1:

**Comment by hendrikweisser** [comment]
Update on my original post: I've made some tests with the Dependent StringSet and unfortunately it's not a good option, because creating one (for a large protein sequence database) is painfully slow. I've changed to filtering down the original StringSet and that seems to work much better.
I've also emailed the SeqAn people about it.

**Comment by hendrikweisser** [comment]
> I've changed to filtering down the original StringSet and that seems to work much better.

Nope, filtering is also prohibitively slow. I'm getting annoyed with SeqAn.

**Comment by cbielow** [comment]
Back in the days, I tried a lot of other approaches which Hendrik mentioned already. None of them were faster than the final implementation you see now.
Let's discuss at the retreat -- Knut probably has some insight into other datastructures.

**Comment by jpfeuffer** [comment]
I talked to one of the SeqAn guys: Can't we just use a "Read"Mapper on the AminoAcid alphabet?

**Comment by hendrikweisser** [comment]
> Back in the days, I tried a lot of other approaches which Hendrik mentioned already. None of them were faster than the final implementation you see now.

I came to the same conclusion, i.e. that creating a new StringSet is much faster than filtering an existing one or creating a Dependent StringSet.
However, if the search is done in two steps (first exact, then approximate), then filtering down the protein set for the second step to only contain sequences with ambiguities did give an improvement in my case.

**Comment by hendrikweisser** [comment]
@jpfeuffer:
Thanks for getting in touch with them. I don't know about the alternative approach.

**Comment by timosachsenberg** [comment]
I think this has been discussed on the developer meeting so I close this issue. Feel free to add details on the discussion afterwards.
