### ISSUE TITLE
Missing binaries for Mac installation

### ISSUE THREAD

**Issue by gieses** [OpenMS/OpenMS#1825]
Dear all,

1)
we are currently running a MS practical with biotechnology students and use OpenMS for the analysis.
Some have Macs and couldn't get the identification pipelines to run. When I checked their installations there was no folder under share/THIRDPARTY/. E.g. on windows there is a folder 64bit/XTandem etc. where all the binaries/java files for tandem, omssa, msgfp, fido etc. are located.

They used the current stable version linked from the homepage.

2) The second issue is when I copied the MSGFPlus.java that is shipped with OpenMS to the Macs they couldn't get it to run either. Even though Java was installed and working from the terminal. THis might be somehow related to the other MSGFplus issue that others have reported here...

Cheers,
Sven

**Comment by timosachsenberg** [comment]
@jpfeuffer first time I heard about the missing X!Tandem on mac - can you confirm this?

**Comment by jpfeuffer** [comment]
On Mac they are located in TOPP/SEARCHENGINES/...
Not sure why, however.

**Comment by gieses** [comment]
@jpfeuffer first the MGFPplus Adapter failed during execution of the workflow. After replacing it with the XTandemadapter it worked for one of the two students with macs. The other student still couldn't get XTandem to run within the workflow. All I know is that one had an macbook air and the other an macbook pro (different OS?). Sorry, I don't really have much more information ):

**Comment by timosachsenberg** [comment]
I think first problem is probably related to the custom java installation paths on mac.
The second one I don't know. We should keep an eye on it.

**Comment by hroest** [comment]
@timosachsenberg is this resolved, discussed elsewhere now?
