### ISSUE TITLE
workflow tests

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1827]
Both class tests [1] and TOPP tool tests [2] are essential for the stability of the OpenMS code. Could we introduce one further set of tests that checks the performance of complete workflows?

- class tests
- TOPP tool tests
- **workflow tests**

Often basic workflows such as protein identification and feature detection fail. It is then down to users to report these bugs. Most TOPP tools work well, but are not fully integrated with other tools in a workflow. IMO, workflow tests have several advantages.

- The basic ID and quantification workflows for data from various machines are always working.
- A single workflow test covers multiple TOPP tool tests and is easier to maintain.

On the other hand, it will be difficult to integrate the processing of complete (and possibly large) datasets into the testing. 

[1] https://github.com/OpenMS/OpenMS/tree/develop/src/tests/class_tests
[2] https://github.com/OpenMS/OpenMS/tree/develop/src/tests/topp

**Comment by timosachsenberg** [comment]
This is definitely nice to have and one thing we are working towards. As you point out is a bit difficult to provide automated tests for large files. This means we need to set this up on our own infrastructure and use e.g. nightly tests.

**Comment by jpfeuffer** [comment]
This is already possible with KNIME Testflows (if we manage to setup a KNIME build system on our own that allows us to store/test with big files).
I haven't thought about a solution for our nostalgic TOPPAS users yet.

**Comment by lars20070** [comment]
Sounds good @jpfeuffer. I can convert the TOPPAS workflows from the repository [1] to KNIME and provide `mzML`.

Can we integrate the workflow tests with GitHub? Should workflow tests be able to block pull requests? Let's discuss in Northumberland.

[1] https://github.com/OpenMS/OpenMS/wiki/Workflow-Collection

**Comment by jpfeuffer** [comment]
Well, yes it will be possible to trigger everything from a pull request from here, but I am not sure if we should do this PR based as it might take quite some additional time.
I think the dev meeting is a good place to discuss.

**Comment by mwalzer** [comment]
That would be great.

**Comment by timosachsenberg** [comment]
I close this discussion as this will be done using KNIME testflows
