### ISSUE TITLE
XTandemAdapter broken in KNIME

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1828]
Somehow KNIME doesn't play well with optional input files that have a default value.

Reported by @hannesveit 

    registerInputFile_("default_config_file", "<file>",
                       "CHEMISTRY/XTandem_default_input.xml",
                       "Default parameters input file, defaulting to the ones in the OpenMS/share folder."
                         "All parameters of this adapter take precedence over this file! Use it for parameters not available here!",
                       false, false, ListUtils::create<String>("skipexists"));

The tool checks for:
if (!default_XML_config.empty())

But I suppose KNIME GKN provides the default string "CHEMISTRY/XTandem_default_input.xml".

**Comment by timosachsenberg** [comment]
@jpfeuffer do you know a simple way how we can work around this?

**Comment by timosachsenberg** [comment]
@lars20070 any progress on this issue? Did you try Stephan's fix?

**Comment by jpfeuffer** [comment]
What was Stephan's fix?

**Comment by timosachsenberg** [comment]
Ups wrong issue. There is no fix yet

**Comment by timosachsenberg** [comment]
```
    String default_XML_config = getStringOption_("default_config_file");
    if (!default_XML_config.empty())
    {
      // augment with absolute path. If absolute filename is already given, this is a no-op.
      default_XML_config = File::find(default_XML_config);
      infile.load(default_XML_config);
      //infile.setDefaultParametersFilename(default_XML_config);
    }
```

**Comment by timosachsenberg** [comment]
hmm no error in current nightly build on windows

**Comment by jpfeuffer** [comment]
Are you sure this is closed? Was @hannesveit on Windows? Can we check?

**Comment by timosachsenberg** [comment]
I talked to him and he was kind of sure that it was Windows. I checked it on my KNIME installation on windows and I had no problems so I hope the issue is fixed.

**Comment by julianu** [comment]
I just wanted to run the current trunk version of XTandemAdapter in KNIME (2.0.1.201605271126) and got some errors, which might be related to this (if not, I will open a new issue):
When not setting any default parameter file, X!Tandem ran for a while and the result was always empty (the native one, when setting the debug level to 2 and looking at the tmp file). The actual used input-params in this case are only the ones set in the KNIME node, so no defaults seemed to be used.
When using the file `/path_to_knime/plugins/de.openms.linux.x86_64_2.0.1.201605271126/payload/share/OpenMS/CHEMISTRY/XTandem_default_input.xml` as default values, the results look fine.

This was for Linux and KNIME 3.1.2.

**Comment by jpfeuffer** [comment]
I can confirm on OSX. I will try to come up with a solution. I need it for a pipeline soon.

**Comment by andreott** [comment]
Hi,

sagmal kann es sein, dass dieses Problem noch besteht. Bei mir ist gerade beim xtandemadapter von den nightly builds das result auch leer (bis auf den header).

Grüße,

Sandro


On 03 Jun 2016, at 14:57 , jpfeuffer <notifications@github.com> wrote:

> I can confirm on OSX. I will try to come up with a solution. I need it for a pipeline soon.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


- 
Freie Universität Berlin
Institut für Informatik               phone: +49 30 838 75137
AG Algorithmische Bioinformatik       room 020
Takustr. 9
D-14195 Berlin

**Comment by jpfeuffer** [comment]
Yes still is a problem. I will reopen, but not as blocker. It works (on OSX and Linux) when you put a default_parameter.xml in. For example the one in:
/path_to_knime/plugins/de.openms.linux.x86_64_2.0.1.201605271126/payload/share/OpenMS/CHEMISTRY/XTandem_default_input.xml

We should use this issue to find a good way to include this file as standard.

**Comment by cbielow** [comment]
kann sein, ich hab KNIME wie gesagt noch nie produktiv angefasst.
Nimm TOPPAS :P
Julianus hat glaub ich n Workaround fuer knime.
https://github.com/OpenMS/OpenMS/issues/1828#issuecomment-232274091


Am 7/13/2016 um 1:51 AM schrieb andreott:
> Hi,
>
> sagmal kann es sein, dass dieses Problem noch besteht. Bei mir ist
> gerade beim xtandemadapter von den nightly builds das result auch leer
> (bis auf den header).
>
> Grüße,
>
> Sandro
>
>

**Comment by jpfeuffer** [comment]
I think we have to correct 
https://github.com/OpenMS/OpenMS/blob/develop/cmake/knime_package_support.cmake#L124
to default_config_file.
Otherwise the default parameter in the Adapter will be overriden by "" and the Adapter will not find it. The question I have is why XTandem suddenly needed that default config file (I thought it was just an extension to have more config options that are not in the adapter).

**Comment by jpfeuffer** [comment]
Wow, actually this typo resulted in the deletion of the subsequent ignore_adapter_param flag. We can actually just remove this line, since file parameters are automatically ignored by KNIMe.

**Comment by jpfeuffer** [comment]
Actually this line can be removed. File params are automatically removed from CTDs for KNIME.

Memo: While fixing this, modify regex here:
https://github.com/OpenMS/OpenMS/blob/develop/cmake/knime/remove_parameter_from_ctd.cmake#L52

by prepending masked 'name="'. E.g. currently it removes all lines where the parameter occurs, even in the description. This results in removal of the ignore_adapter_param flag. However default should be false, so I still do not completely get the error.

**Comment by timosachsenberg** [comment]
I promoted this to critical because of the release

**Comment by jpfeuffer** [comment]
Okay, I am preparing a fix for the obvious errors above.
The question is, how should we present optional inputs in general to the user?
- As an optional input port?
- As an option in the config dialog?
- Current solution for e.g. Thirdparty executables: Hardcoded to the KNIME/OpenMS/share?

**Comment by timosachsenberg** [comment]
hmm I like the idea of having optional input ports but this might also be confusing for users if they have to specify i.e. executables

**Comment by jpfeuffer** [comment]
The problem with optional input ports is that they will be set to an empty string "" when they are not connected and therefore overwrite the default configuration from the CTD/Param.xml .
Quick solution: In the XTandemAdapter.cpp (and any other that uses optional inputs) fallback to default when the string is empty.
Long solution: Adapt the GKN code to store default values for optional input files.
(The default values are only stored for usual parameters by writing them initially into the config dialogue and since file ports are not in the dialogue, default values are gone).

**Comment by jpfeuffer** [comment]
See https://github.com/genericworkflownodes/GenericKnimeNodes/issues/129 for the fix on GKN side.

**Comment by timosachsenberg** [comment]
fixed
