### ISSUE TITLE
Still error in MSGFplusAdapter for Win64

### ISSUE THREAD

**Issue by julianu** [OpenMS/OpenMS#1834]
Under windows the MSGFplusAdapter is still not running without editing the binaries.ini in the stable release.
The path variables should only point to the path, not the actual java.exe. When editing the file, the adapter runs. 

The lines have to be:

> OPENMS_DATA_PATH=$ROOT\\share\\OpenMS\\
> PATH=$ROOT\\bin;$ROOT\\lib;$ROOT\\bin\\Fido;$ROOT\\bin\\OMSSA;$ROOT\\bin\\MyriMatch;$ROOT\\bin\\XTandem;$ROOT\\..\\..\\..\\jre\\bin\\
> Path=$ROOT\\bin;$ROOT\\lib;$ROOT\\bin\\Fido;$ROOT\\bin\\OMSSA;$ROOT\\bin\\MyriMatch;$ROOT\\bin\\XTandem;$ROOT\\..\\..\\..\\jre\\bin\\
> MSGFPLUS_PATH=$ROOT\\bin\\MSGFPlus\\MSGFPlus.jar

**Comment by jpfeuffer** [comment]
You mean the KNIME Node for it right?

**Comment by timosachsenberg** [comment]
in https://github.com/OpenMS/OpenMS/blob/develop/cmake/knime/binaries_win.ini
we have:
```
OPENMS_DATA_PATH=$ROOT\\share\\OpenMS\\
PATH=$ROOT\\bin;$ROOT\\lib;$ROOT\\bin\\Fido;$ROOT\\bin\\OMSSA;$ROOT\\bin\\MyriMatch;$ROOT\\bin\\XTandem;$ROOT\\..\\..\\..\\jre\\bin
Path=$ROOT\\bin;$ROOT\\lib;$ROOT\\bin\\Fido;$ROOT\\bin\\OMSSA;$ROOT\\bin\\MyriMatch;$ROOT\\bin\\XTandem;$ROOT\\..\\..\\..\\jre\\bin
MSGFPLUS_PATH=$ROOT\\bin\\MSGFPlus\\MSGFPlus.jar
```

**Comment by timosachsenberg** [comment]
and the bug was fixed in:
https://github.com/OpenMS/OpenMS/commit/25da0d5fe88489c58e6cc9903cd115aa3ddea5c2#diff-8e2aa25b7fe0e02672bf709e11413584

**Comment by timosachsenberg** [comment]
we did not provide a bugfix release but it should work in the nightlies

**Comment by julianu** [comment]
Yes, the KNIME node and I actually knew, it was fixed in the source. That's why I was wondering to still see it in the stable release, which dates definitely more recent than the this patch.
Just wanted to remind you it's still there. Hopefully finds its way into stable soon ;)

**Comment by timosachsenberg** [comment]
The stable is based on the OpenMS release. we did not backport the fix. The newer date is because the gkn part got updated

**Comment by jpfeuffer** [comment]
That is correct @timosachsenberg

**Comment by julianu** [comment]
Ok, that explains it, didn't know the stable KNIME nodes are only build when a new OpenMS version is released. Sorry for opening this up again, can be closed.
