### ISSUE TITLE
IDFileConverter crash, pepXML to idXML

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1836]
`IDFileConverter` crashes when reading this `pepXML` file [1] with
```
Error: Unexpected internal error (the Element 'Enzyme name cannot be found. " could not be found)
```
The ArgC enzyme in `pepXML` is not recognized.
```
<sample_enzyme name="argc"> 
```
[1] https://gist.github.com/lars20070/65b854d08a6a66c7e8f2

**Comment by timosachsenberg** [comment]
@lars20070 you could try to  add argc as a synonym:
```
      <NODE name="Synonyms">
        <ITEM name="Clostripain" value="Clostripain" type="string" />
        <ITEM name="argc" value="argc" type="string" />
      </NODE>
```
maybe that's already enough to register the name in EnzymesDB

**Comment by mwalzer** [comment]
any news here?
