### ISSUE TITLE
Mac building docs need update (Homebrew)

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1839]
The documentation for "[Building OpenMS on Mac OS X](http://ftp.mi.fu-berlin.de/pub/OpenMS/documentation/html/install_mac.html)" has a section "Using system libraries" that describes how to get the contrib libraries through Homebrew or MacPorts. At least the part about Homebrew is out of date:
- Installing SeqAn through Homebrew will get version 2.1, but OpenMS still needs 1.4.
- WildMagic seems to be missing from the list of packages to install (not sure if it's available).

**Comment by timosachsenberg** [comment]
@jpfeuffer you are much more into mac - can update this information in the master branch?

**Comment by jpfeuffer** [comment]
@hendrikweisser: What do you think about the updated docu?
http://ftp.mi.fu-berlin.de/pub/OpenMS/release2.0.1-documentation/html/install_mac.html

**Comment by hendrikweisser** [comment]
@jpfeuffer: Thanks for the update. Some comments (including parts that weren't changed):
- Introduction
  - first sentence, remove "addresses OpenMS users and "
  - last sentence, add a link to the mailing list (like for the issue tracker)
- Required applications:
  - `(sudo) brew install qt` - would that install Qt4 or Qt5?
  - change sentence to: Building the Python bindings pyOpenMS requires Python (> 2.6), Cython (> 0.19), NumPy and the "nose" testing framework. See [here](link!) for more detailed pyOpenMS build instructions.
  - for the Python/Cython versions: is ">" correct or should it be "... or higher" (>=)?
  - Doxygen: maybe just make 1.7.1 the required minimum?
  - capitalize "PDFs"
- Installing the contrib package
  - first sentence, change "composed" to "provide"
  - first note: change "BOOST" to "Boost", change "clang compiler" to "Clang compiler"
  - 3.: put "cmake" in typewriter font
  - second note: move that before the build instructions
- Using system libraries
  - first sentence: As an alternative to the contrib libraries shipped with OpenMS, ...
  - Homebrew: "installs all libraries" is not true!
- Installing OpenMS
  - 1.: put the path to Terminal.app in typewriter font
  - 3.: put "cmake" in typewriter font
  - first note: put "cmake" and "ccmake" in typewriter font
  - second note: If you intend to use third-party search or inference engines like X! Tandem or Fido, their binaries also need to be in the PATH. Build them or download them from our third-party Git repository and adapt the following for every third-party tool you want to use (shown for X! Tandem)
- Testing your OpenMS/TOPP installation
  - no spaces around "/" in the title
  - second sentence: put "ctest" in typewriter font
  - change the order: For example, the following command will run all TOPP tests using 4 jobs: `ctest -R TOPP_ -j 4`. For more information, consult the [ctest manual page](link!).
  - remove the last bit ("Make sure that...")
- throughout the document: make sure that Homebrew, MacPorts, GitHub and Git are consistently capitalized

**Comment by jpfeuffer** [comment]
Thanks for the comments. I included basically all of them. Actually, shouldn't we move all pyOpenMS related descriptions to the standalone pyOpenMS html page? Would be much easier to maintain and won't diverge so much. Then somebody with more knowledge about the exact requirements could update this one quickly?

**Comment by jpfeuffer** [comment]
Closed through #1945 and related PRs.
