### ISSUE TITLE
Some OpenMS classes are derived from std::vector [184]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#184]
Submitted by aiche on 2010-09-13 14:14:05

stl containers are generally not designed for inheritance, so why do we do it in the library?

Affected classes vor `std::vector` are
- ~~AcquisitionInfo~~
- ~~DoubleList~~ (see a1f2f38da80c88c7a65326f3c288c85be3867fe9)
- ~~IntList~~ (see df9ea4047b2644730475aa67ceb0f62b87d3d523)
- ~~StringList~~ (see 9e1468bf972015ff2464f4d586713236d80fd414)
- ~~ConsensusMap~~ (changed to private inheritance)
- ~~MSChromatogram~~
- ~~MSSpectrum~~
- ~~FeatureMap~~ (changed to private inheritance)
- ~~MSExperiment~~ (changed to member, see 1d6dea89a7594a2bf5d38c517109d6a03da58eb0)
- ~~SampleProteins~~ (in src/openms/include/OpenMS/SIMULATION/SimTypes.h)
- ~~SampleChannels~~ (in src/openms/include/OpenMS/SIMULATION/SimTypes.h)
- ~~MassTraces~~ (in src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmPickedHelperStructs.h) (see 69f58ce40ce65580132a912d1f1edbe4f2324d10)
- ~~TextFile~~

Other STL containers
- ~~Map (`std::map`)~~
- String (`std::string`) (see #845)
- ~~ConsensusFeature~~ (`std::set`) (see 4e20e1bb4ad5794c2f6d1fef9b24c0b55713b0d7)

**Comment by hroest** [comment]
seems like mostly resolved except for `OpenMS::String`

**Comment by hendrikweisser** [comment]
It seems that all the `vector` cases are handled. We have #448 still open to discuss the issues related to `String`. I'm closing this ticket.
