### ISSUE TITLE
Remove a modification from a residue

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1852]
@PetraGutenbrunner and I can't seem to find a way to remove a modification from a residue in an amino acid sequence (`AASequence`) in OpenMS. We need this functionality to update sequences based on the results of a PTM site-localization tool.

There seems to be no method to remove a modification in the `Residue` class, nor is it possible to replace a residue (with an unmodified one) in `AASequence`.
Our current workaround is to convert the `AASequence` to a string without modifications (`toUnmodifiedString`), then convert back to an `AASequence` and add all the modifications again, but that seems very ugly.

Are we overlooking anything? Is there a good reason why it's not possible to remove a modification? (If so: It *is* possible to overwrite a modification - are we sure that works correctly?)
If we add functionality for removing a modification to `Residue`, is that self-contained or are changes e.g. in `AASequence` necessary?

**Comment by timosachsenberg** [comment]
@hendrikweisser @PetraGutenbrunner the original design is very awkward.
The problem ist, that basically every residue is stored in ResidueDB and AASequence stores pointer to them. Adding (or removing) a modification actually changes multiple residue members (see e.g. Residue::setModification) and (if I understood it correctly) would change every AASequence that points to it.

**Comment by timosachsenberg** [comment]
we can discuss this in gitter - maybe we find together a way to solve this issue

**Comment by timosachsenberg** [comment]
I think the best work-around - given the current design - is to add a member to AASequence that allows to set the actual residue.

**Comment by timosachsenberg** [comment]
maybe we could also add a function to ResidueDB that returns the unmodified version of a modified residue

**Comment by jpfeuffer** [comment]
I guess this will be postponed to 2.1? Or is this very close to finishing?

**Comment by timosachsenberg** [comment]
For me its fine if we get it in 2.1

**Comment by timosachsenberg** [comment]
I think the functionality to return the unmodified version of a modified residue might already exist.
```
    const Residue * getResidue(const unsigned char & one_letter_code) const;
```
always returns an unmodified residue.
