### ISSUE TITLE
pyOpenMS nightly 

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1854]
It seems the nightly tests fail without an error: http://cdash.openms.de/buildSummary.php?buildid=166990

**Comment by timosachsenberg** [comment]
@jpfeuffer can we extend the time cdash reports are kept on the server? this one has already been deleted. Or should we make it mandatory to post them as e.g. gist?

**Comment by jpfeuffer** [comment]
I think we definitely can on the new server (contact Philipp in Tübingen). I would need to ask around how to do it on the current one. I guess I need to contact IT support. I think we decreased it some time ago because it was so slow and hoped that it would resolve the problem (it didn't).

**Comment by jpfeuffer** [comment]
But to the actual issue:
When I try to run
`make pyopenms`
in the very same configured build folder from where the results are uploaded to CDash on our Mac, I run into the following error (first CMake lines omitted):
```
INFO:root:parse /Users/aiche/NIGHTLY/HEAD/src/pyOpenMS/pxds/ConsensusMapNormalizerAlgorithmMedian.pxd
Traceback (most recent call last):
  File "create_cpp_extension.py", line 44, in <module>
    decls, instance_map = autowrap.parse(pxd_files, ".")
  File "/usr/local/lib/python2.7/site-packages/autowrap/__init__.py", line 51, in parse
    return DeclResolver.resolve_decls_from_files(files, root)
  File "/usr/local/lib/python2.7/site-packages/autowrap/DeclResolver.py", line 172, in resolve_decls_from_files
    decls.extend(PXDParser.parse_pxd_file(full_path))
  File "/usr/local/lib/python2.7/site-packages/autowrap/PXDParser.py", line 462, in parse_pxd_file
    result.append(handler(body, lines, path))
  File "/usr/local/lib/python2.7/site-packages/autowrap/PXDParser.py", line 264, in parseTree
    decl = MethodOrAttributeDecl.parseTree(att, lines, pxd_path)
  File "/usr/local/lib/python2.7/site-packages/autowrap/PXDParser.py", line 377, in parseTree
    tt = _extract_type(arg.base_type, argdecl)
  File "/usr/local/lib/python2.7/site-packages/autowrap/PXDParser.py", line 188, in _extract_type
    return CppType(base_type.name, template_parameters, is_ptr, is_ref, is_unsigned, is_long, is_const=is_const)
AttributeError: 'CConstTypeNode' object has no attribute 'name'
make[3]: *** [src/pyOpenMS/CMakeFiles/pyopenms_create_cpp] Error 1
make[2]: *** [src/pyOpenMS/CMakeFiles/pyopenms_create_cpp.dir/all] Error 2
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/rule] Error 2
make: *** [pyopenms] Error 2
```

**Comment by jpfeuffer** [comment]
Okay solved it by removing "const" declarations from the ConsensusMapNormalizerAlgorithmXXX.pxds and adding correct imports.

**Comment by jpfeuffer** [comment]
PyOpenMS build was filling my complete RAM and finally did not progress anymore, so I stopped and am retrying now. Is this known to be very memory consuming?

**Comment by timosachsenberg** [comment]
Yes it is very memory consuming. I can't remember the details but I think a huge header or cpp file is generated.
