### ISSUE TITLE
Generating top-down and bottom-up MS data for phosphorylated proteins

### ISSUE THREAD

**Issue by deepeshag** [OpenMS/OpenMS#1858]
Hi everyone,

Greetings !

I am trying to generate simulated MS data (Top-down and Bottom-up) for phosphorylated protein such as "platelet-derived growth factor receptor (PDGFR-B)". There are 10 tyrosine sites which are phosphorylated. Could you kindly help me out with the setting of necessary parameters and also with the following questions?

    How to tell OpenMS in the input file that there are 10 modification sites on the protein sequence in the FASTA format?
    What are the parameters required to be set for top-down and bottom-up MS separately?

Your help will be greatly appreciated.

Thank you.
Deepesh

**Comment by cbielow** [comment]
for the simulation params: the default params of MSSimulator should be a good startign point for bottom-up.

Top-down has not been tested really, but could work if you adapt the params (see
http://ftp.mi.fu-berlin.de/pub/OpenMS/documentation/html/UTILS_MSSimulator.html)
 - Digestion:enzyme - should be 'none'
 - mz:upper_measurement_limit  (increase it, just to make sure you do not loose large proteins with few charges) - you can also change 'ionization_probability' to shift the signal in m/z

**Comment by timosachsenberg** [comment]
To add a phosphorilation site at a specific position in a sequence you can add the unimod short name e.g. PEPTIY(Phospho)PEPR in the fasta file

**Comment by cbielow** [comment]
if you want all 2^10 possible combinations, you need to enumerate the mods in the FASTA file manually (its 1014, so still managable) -- works for both bottomup and top-down.
Alternatively, for bottom-up only: you can also externally digest the protein and provide two versions for each peptide (modified and unmodified sequence) in the FASTA file. e.g. using Digestor (http://ftp.mi.fu-berlin.de/pub/OpenMS/documentation/html/UTILS_Digestor.html)

**Comment by timosachsenberg** [comment]
Please feel free to reopen or create a new issue if this did not help solving your problem
