### ISSUE TITLE
tool for the conversion of TOPPAS and KNIME workflows

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1865]
Some groups are still using TOPPAS workflows for their daily analyses. Others are already working with KNIME. There exists a large number of workflows in both formats.

A tool for the conversion from one workflow format to the other would be very helpful.

**Comment by timosachsenberg** [comment]
I don't see an easy solution to this given the way workflow control is handled by TOPPAS and KNIME. Best solution is imho rebuilding the workflows by hand - which should be rather quick given the limited amount of different workflows out there.

**Comment by cbielow** [comment]
I agree with Timo that manually re-creation is the way to go and that 
our time is better spend elsewhere.
However, the biggest problem is likely go get the param settings 
mirrored correctly. This could be done via drag'n'drop of individual 
nodes (i.e. INI files if we want to go via the file system). In TOPPAS 
drag'n'drop is already supported to some extend; not sure if this can be 
done in KNIME.


Am 3/7/2016 um 7:36 PM schrieb Timo Sachsenberg:

**Comment by timosachsenberg** [comment]
I asked Luis and he says that this is not easily implemented. As far as he knows, drag and drop is not exposed by the KNIME API and would probably require a KNIME extension plugin.

**Comment by hendrikweisser** [comment]
Is it possible to read parameters for a tool from INI (or CTD) files in KNIME?

**Comment by timosachsenberg** [comment]
@jpfeuffer do you know if this would be possible?

**Comment by jpfeuffer** [comment]
Well, we create the configuration dialog with the help of the CTD. The -ini option is removed during creation of the nodes. We could add it back again and enter a path to the ini files but then the inis are always needed for this workflow. There is currently no way to automatically update the settings in an already present node configuration from outside of KNIME.
If you really want to circumvent manual setup, the best way to go would be to click the workflow to setup connections and the overall structure and then use a script to update the entries in the settings.xml of the nodes in your workflow folder on your file system.
The XML looks like this:
https://gist.github.com/jpfeuffer/98ba13a7066d72f9b13d

**Comment by lars20070** [comment]
A semi-automated conversion would be a good solution. First, the overall structure of the workflow is setup by hand. The parameters are then filled in by a script. It's this second step that is very time-consuming and error-prone.

**Comment by hendrikweisser** [comment]
> Well, we create the configuration dialog with the help of the CTD.

In TOPPAS there is the option to load tool parameters from an INI file (double-click the node, click "Load"). Is something like this possible for KNIME? If not, could it be added? If it can be added, can it be added in a way that would make it scriptable?

**Comment by timosachsenberg** [comment]
I agree with Julianus. I think this is not easily possible in KNIME and best solved using a e.g. python script that parses the TOPPAS and KNIME XML, shows differences (and potentially even allows to copy values over).

**Comment by jpfeuffer** [comment]
> In TOPPAS there is the option to load tool parameters from an INI file (double-click the node, click "Load"). Is something like this possible for KNIME?

@hendrikweisser  I see your point, now. It is currently not possible. I guess it could be added but I would have to talk to a KNIME core developer to estimate the effort.
I think making it scriptable adds another level of difficulty because in that script you would somehow have to define a mapping of an ini file to the KNIME node that should be updated with it. Which is then close to a manual update of every node with that "new manual update mechanism" I guess.

@lars20070 How many workflows do you have? Unfortunately, I doubt that the effort for automatic conversion is worth it (assuming all new workflows are done in KNIME afterwards, which I really recommend considering the upcoming global KNIME workflow repository). Keep in mind, that I assume there will be other problems during conversion that make a manual interception necessary anyways.

**Comment by hendrikweisser** [comment]
Although I wish there were an easy solution for converting my TOPPAS workflows to KNIME, I agree with this bit:

> Unfortunately, I doubt that the effort for automatic conversion is worth it (assuming all new workflows are done in KNIME afterwards, which I really recommend considering the upcoming global KNIME workflow repository).

The exception might be conversion via the Common Workflow Language (http://www.commonwl.org/). At some point it might be worth it for KNIME to add support for CWL - not just for OpenMS, but we could potentially use that functionality, too.

**Comment by timosachsenberg** [comment]
I think we agreed that a full solution is beyond our resources right now. Anyone who wants to take on it may be free to reopen the issue.
