### ISSUE TITLE
MTD section of MzTabExporter incomplete without ms_run-* information

### ISSUE THREAD

**Issue by sneumann** [OpenMS/OpenMS#1872]
Hi, if I convert from ConsensusXML to mzTab, the information between 
the samples and the data matrix, so I only have "peptide_abundance_study_variable[3]".
It would be great if there was a way to track that into the mzTab. Yours, Steffen

https://github.com/HUPO-PSI/mzTab/tree/master/examples :
```
MTD ms_run[8]-location file://L:/Paper HFD/Data/TG/20100126_TAG-41.chrom
MTD assay[8]-ms_run_ref ms_run[8]
```

**Comment by timosachsenberg** [comment]
Hi,
This should actually be possible in the current development version.
There we try to track source files through our data formats to the mzTab (in the meta value "spectra_data").
Could you check if you can upgrade to the newest version and if this problem still persists?
Best,
Timo

**Comment by sneumann** [comment]
Yes, ms_run information is included now. Bruker users will be bitten by #1983 
Yours, Steffen
