### ISSUE TITLE
mzIdentML parsing problems

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1873]
Collection of issues that I discovered while working on the SAX parser for mzIdentML (mzid):
- In mzid, the "SpectrumIdentification" element can contain multiple "SearchDatabase" elements, to represent a search run that used multiple databases. This currently can't be represented in OpenMS, as the `ProteinIdentification::SearchParameters` struct has only one string member for the database.
- The subelements "InputSpectra" and "SearchDatabase" of "SpectrumIdentification" store references to input data files and search databases, respectively, in attributes ("SpectraData_ref"/"SearchDatabase_ref"). These attributes are not marked as "required" in the mzid schema (version 1.1.0), but leaving them out doesn't make sense.

**Comment by hendrikweisser** [comment]
- In the MzIdentMLDOMHandler, there are lots of "XMLString::transcode" calls around keys used to access data (e.g. "getAttribute"). Are these actually necessary?

**Comment by hendrikweisser** [comment]
- In mzid, in "SpectrumIdentificationProtocol", there can be multiple "Enzymes", but only one enzyme per search run (`ProteinIdentification`) can be stored in OpenMS.
- In mzid, the "EnzymeName" element (in "Enzyme") is of type "ParamListType", which means it can store multiple CV or user params. What is the point of allowing multiple names for one enzyme? (Maybe synonyms?)

**Comment by timosachsenberg** [comment]
- change database field in ProteinIdentification::SearchParameters to StringList
- change enzymes field in ProteinIdentification::SearchParameters to StringList
- we should keep/fill the references to source files

**Comment by hroest** [comment]
just to clarify: currently we have a DOM parser that works (mostly) and a SAX parser that is not yet compliant?

**Comment by hendrikweisser** [comment]
There's only some very early work on the SAX parser in [this branch](https://github.com/OpenMS/OpenMS/tree/mzid-sax-parser), which I never got around to completing.
