### ISSUE TITLE
Change mode to identify correct contrib version [188]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#188]
Submitted by aiche on 2010-09-15 11:18:57

we currently check the contrib for a file 

README_contribX.X.txt

where X.X is the openms version, we should move to 

README_contribXXXX

where is the svn revision of the contrib, which is more specific and we do not have to touch every contrib each time we change the openms version.

**Comment by jpfeuffer** [comment]
Why exactly is that needed? If it is to use the right contrib for a certain OpenMS version, I guess there are better options. Since we also support contrib libraries from package managers the use is limited anyway.
BTW: the version is currently hardcoded to 1.7.

**Comment by jpfeuffer** [comment]
This should and will be solved with git tags.
