### ISSUE TITLE
MascotAdapterOnline taxonomy

### ISSUE THREAD

**Issue by hh1985** [OpenMS/OpenMS#1888]
Hi,
I found the parameter setting of MascotAdapterOnline requires users to manually type the name of the taxonomy.  Is it possible to make the 'taxonomy' a dropdown list, like what the original MascotAdapter does? Also, in the web browser interface of mascot, there is a 'decoy' checkbox, but I couldn't find similar option in the MascotAdapterOnline settings.

Thanks,

-hh1985

**Comment by timosachsenberg** [comment]
@hendrikweisser do you know if this is possible/makes sense for MascotAdapterOnline?

**Comment by hh1985** [comment]
@timosachsenberg 
Update: I added a few lines in the source code of MascotGenericFile.cpp:
Around line 61: 
`defaults_.setValue("decoy", "1", "explanation");`
Around line 273: 
```
writeParameterHeader_("DECOY", os);
os << param_.getValue("decoy") << "\n";
```
Then I modified the ini file, and insert an item specifying 'decoy' as 1.
This adds DECOY=1 tag and triggers the automatic decoy database generation. It works on our mascot server (v2.3.x).

Hope this helps.

-hh1985

**Comment by hendrikweisser** [comment]
(Not sure how relevant this is after three years...)

> Is it possible to make the 'taxonomy' a dropdown list, like what the original MascotAdapter does?

That depends on how predefined the list of available taxonomies is. If it's "hard-coded" into Mascot, we could add it to the adapter. If it depends e.g. on the installed databases, we may have no way of knowing which taxonomies are available.
