### ISSUE TITLE
TOPPAS Pipeline: Aborting a workflow does not kill java processes (MS-GF+, Luciphor), also in KNIME?

### ISSUE THREAD

**Issue by PetraGutenbrunner** [OpenMS/OpenMS#1895]
If I start a pipeline in TOPPAS and abort it, the background java processe of MS-GF+ or Luciphor were not killed, which should not be. It could be especially a problem if Luciphor was started with not optimal parameter settings which lead to high cpu and memory usage.

Is there any possibility to pass the pipeline abort status to the TOPP tool to further stop the QProcess which calls the java application?

We also should check if this problem also exists in the KNIME workflow.

Code:

```
QStringList process_params; // the actual process is Java, not LuciPHOr2!
process_params << "-jar" << executable << conf_file.toQString();                   

// execute LuciPHOr2    
int status = QProcess::execute("java", process_params);
if (status != 0)
{
  writeLog_("Fatal error: Running LuciPHOr2 returned an error code. Does the LuciPHOr2 executable (.jar file) exist?");
  return EXTERNAL_PROGRAM_ERROR;
}
```

**Comment by jpfeuffer** [comment]
Yes, in KNIME we also experienced that problem and it seems there is not much that we can do about it. Java loses control about its subprocesses, once it starts them up. Very annoying.
At least we did not find a practicable solution yet.

**Comment by cbielow** [comment]
It's not a Java problem, nor is it a TOPPAS/KNIME problem:

If you start a TOPP tool (or any executable which spawns a child process), killing that executable will not kill the child unless you do platform specific magic.
This 'magic' is a bit tricky and hard to get bug-free, so it's usually not done.

I can see Petra's point and the resource waste is unfortunate. Even worse, results of a newer instance might be overwritten by the first (aborted) child proccess if it finishes later (could easily happen if another param set was used).

**Comment by cbielow** [comment]
We could try to implement something to kill child processes into TOPPBase.
The tricky thing is to get this code executed, when the TOPP tool receives the SIGKILL/SIGTERM, because there might be no time.
Putting this code in TOPPBase is however the most general approach and works for all situations, i.e. also when the TOPP tool is called on the command line.
