### ISSUE TITLE
Reading mzML: verbose warning messages

### ISSUE THREAD

**Issue by PetraGutenbrunner** [OpenMS/OpenMS#1896]
Warning messages while reading mzML file can not be merged which leads to a very huge log file: 
[mzML_log_example.txt](https://github.com/OpenMS/OpenMS/files/197887/mzML_log_example.txt)

**Comment by hroest** [comment]
:+1: these are not really that helpful, honestly. It may even be questionable to output them unless one really wants that and turns on debugging options

**Comment by timosachsenberg** [comment]
I agree. We can handle this problem in several ways.
3 that come to my mind are.
1. provide a smarter caching logic so we output every error message at most once (including "occured X times") - I would vote for that one
2. whitelist some error messages that are known to stem from incorrect handling on vendor side
3. put them on a debug stream that only outputs the message if the debug level is raised
