### ISSUE TITLE
MSGF+ exports wrong modification

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1898]
Export of this [1] `consensusXML` leads to the following crash.
```
Error: Unexpected internal error (the element 'Gln->pyro-Glu (Q)' could not be found)
```
in e.g. `MzTabExporter`.

The mod should be `Gln->pyro-Glu (Q N-term)` [2] not `Gln->pyro-Glu (Q)`. The IDs originate from an MS-GF+ adapter search.

[1] https://gist.github.com/lars20070/7271239d2a2acd1c6f515d2ba22c61b9
[2] http://www.unimod.org/modifications_view.php?editid1=28

**Comment by timosachsenberg** [comment]
resulting e.g. in a crash of MzTabExporter on consensusXML

**Comment by timosachsenberg** [comment]
please provide suiting labels to the issue

**Comment by lars20070** [comment]
Complete [1] and tiny fixed mod Unimod #28 [2] example.

[1] https://www.dropbox.com/sh/cm7gtt7eqd2lrhw/AABO7oq4TguoofpkaLBs4AEma
[2] https://www.dropbox.com/sh/bfyj6uuqq4epyar/AAA6l16OUjirNdNYLt-QhM8ia

**Comment by timosachsenberg** [comment]
same error message still persists? or is this unrelated?

**Comment by lars20070** [comment]
Using the latest nightly build, the problem shifted.

No crash/error message as above.

Fixed dimethyl searches are fine (Unimod # 36) [1]. All N-terms dimethylated.
But fixed Unimod # 28 searches [2] look like variable. `mzid` is already wrong. Either MS-GF+ bug or wrong search submitted.

**Comment by timosachsenberg** [comment]
how are the variable ones distinguished from the fixed ones in the mzid again?

**Comment by lars20070** [comment]
All searches are run with fixed mods only (including fixed Unimod # 28 N-term mods).

But the results show sequences without # 28 N-term mods.

**Comment by hendrikweisser** [comment]
I think the original problem with the "Gln->pyro-Glu (N-term Q)" should be fixed by my improvements to mod handling in #2097.

@lars20070: Can you try running the MSGFPlusAdapter with "debug 2" and have a look at the MS-GF+ modifications file that gets created? Does the relevant modification appear there as fixed or variable?

**Comment by lars20070** [comment]
Here debug output and mod file (Why NumMods=2 ??). Otherwise looks fine.
https://gist.github.com/lars20070/70c06a197a1af13c99a31a86a769b003
https://gist.github.com/lars20070/dbde4485909c43201c1bd7bf3f6e0546

**Comment by lars20070** [comment]
BTW, can we set `max_mods=4` by default? Two is too low. Easy to overlook this parameter.

**Comment by timosachsenberg** [comment]
could one also warn if e.g. the number of Fixed modifications is already larger than NumMod?

**Comment by timosachsenberg** [comment]
did this fix your problem lars?

**Comment by lars20070** [comment]
Nope. - Looks like an MS-GF+ bug. Even from the command line I get these "variable" results.

```
java -Xmx3500M -jar MSGFPlus.jar -s CC127.mzML -mod msgfplus_mods.txt -d uniprot.fasta -t 20ppm -ti -1,2 -ntt 2 -tda 1 -o CC127.mzid
```

**Comment by hendrikweisser** [comment]
> BTW, can we set max_mods=4 by default? Two is too low. Easy to overlook this parameter.

This parameter doesn't actually work as advertised. At least with the default of 2, you still get peptides with more than two modifications from MS-GF+. Maybe it only applies to variable modifications?

**Comment by hendrikweisser** [comment]
By the way, the documentation and default value for "max_mods" just come from the MS-GF+ example file: https://bix-lab.ucsd.edu/download/attachments/13533355/Mods.txt?version=2&modificationDate=1358975546000
So it's not my fault if the documentation is inaccurate. ;-)

**Comment by lars20070** [comment]
The `Gln->pyro-Glu (N-term Q)` mod works fine in MS-GF+. I overlooked the `N-term Q (!)` specificity. My mistake, sorry. See https://github.com/sangtaekim/msgfplus/issues/1#issuecomment-242683070

**Comment by lars20070** [comment]
Can we close this issue?
