### ISSUE TITLE
Inconsistent naming (ProteinIdentification::SearchParameters)

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1900]
Some members of the class `ProteinIdentification::SearchParameters` are named inconsistently:
- double fragment_mass_tolerance
- bool fragment_mass_tolerance_ppm
- double precursor_tolerance
- bool precursor_mass_tolerance_ppm

Note the missing "mass_" in "precursor_tolerance".
Maybe this could be fixed when other changes that affect the API have to be made anyway.

**Comment by timosachsenberg** [comment]
should be fixed in https://github.com/OpenMS/OpenMS/pull/1916
