### ISSUE TITLE
Remove ComparatorUtils

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1903]
Nothing particularly wrong with them but maybe little used throughout OpenMS. Any thoughts on these?

**Comment by hroest** [comment]
I think they can go. Especially with lambda in cpp11 we don't really need
those any more

**Comment by jpfeuffer** [comment]
They gave a lot of trouble in C17 since unary and binary function were deprecated. I also think they are a bit redundant with lambdas.
