### ISSUE TITLE
Refactoring of Kernel classes: Feature

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1906]
Feature is not as lightweight as it could be as it e.g. stores subordinates.
Also:

```
/// Flag that indicates if the overall convex hull needs to be recomputed (i.e. mass trace convex hulls were modified)
    mutable bool convex_hulls_modified_; 
```

on the fly tracking if recomputation is needed (aka lazy recomputation) is often considered bad if it can be prevented.  IMHO better to give user the control to trigger recomputation and get rid of this flag.

**Comment by hroest** [comment]
Maybe we could start ripping out stuff we dont need and put it in subclasses -- or, what I prefer, create a lightweight feature class from which Feature inherits and that only has the bare necessities and then try to adopt algorithms to the new LightweightFeature ?
