### ISSUE TITLE
ResidueModification: add support for protein terminal modifications

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1913]
Currently, OpenMS only distinguishes:
no specificity ("anywhere"), C-term, N-term at the peptide level.
Protein C-term and Protein N-term are not supported.

IMHO this is an important enhancement.

**Comment by hendrikweisser** [comment]
This would affect MSGFPlusAdapter, as MS-GF+ already supports this type of specificity.

**Comment by weiclav** [comment]
For me it is also very important enhancement and would love to see it implemented!

thanks for consideration

**Comment by lars20070** [comment]
Same for us.

FYI, I tested MS-GF+ with `Gln->pyro-Glu (N-term Q)` (Unimod 28). Works fine.

**Comment by Stefan-N** [comment]
This would be an important enhancement! For example N-terminal acetylation occurs at up to 85% of **Protein N-term** in eukaryotes, while being a rather unimportant modification on peptide n-term level in most experiments. 
It also affect the TANDEM adapter. TANDEM cmdline support the quick acetyl already [http://www.thegpm.org/TANDEM/api/pqa.html](url), however this is only for n-term protein acetylation, not for other mods.

**Comment by timosachsenberg** [comment]
@enetz what is the current state of this?

**Comment by enetz** [comment]
@timosachsenberg see PRs #4060 and #4225
There is progress, our internal structures like ModificationsDB and ResidueModification can deal with Protein N/C-Terminal mods now and some tools already use them, e.g. CometAdapter.

**Comment by timosachsenberg** [comment]
I guess peptideindexer does not support it yet? @cbielow 
as this could make some difference in reported results
