### ISSUE TITLE
ConsensusID not passing on the spectra_data UserParam

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1914]
This `idXML` [1] contains the IDs from two separate MS-GF+ searches subsequently combined with `IDMerger`. The `spectra_data` UserParam specifies the original `mzML`.

Combining both searches with `ConsensusID` (best), the `spectra_data` UserParam are not written and the `mzML` reference is lost.

[1] https://gist.github.com/lars20070/0265efb13cdd83df811f0ac9667e89de

**Comment by oliverschilling** [comment]
May I add that the `spectra_data` information is essential to perform a complete PRIDE submission with OpenMS analyses, which has been a major topic at the 2016 developer meeting? At the same time, the ability to combine multiple searches / search engines with ConsensusID is a major feature of OpenMS.

**Comment by lars20070** [comment]
Resolved in #1932 and #1938.
