### ISSUE TITLE
OpenMS discards protein modification

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1922]
It seems that OpenMS does not parse any entries in UniMod files that have the string "Protein" in their position attribute:

https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/UnimodXMLHandler.cpp#L138

This means also that any peptide which has such a modification will throw an error since OpenMS does not recognize the modification and `AASequence::fromString` will fail. Specifically we have run into the issue with UniMod 313.

to reproduce, try 

```
$ git diff -U0 ./src/tests/class_tests/openms/source/AASequence_test.cpp
diff --git a/src/tests/class_tests/openms/source/AASequence_test.cpp b/src/tests/class_tests/openms/source/AASequence_test.cpp
index 3484d9a..e520c31 100644
--- a/src/tests/class_tests/openms/source/AASequence_test.cpp
+++ b/src/tests/class_tests/openms/source/AASequence_test.cpp
@@ -157,0 +158,5 @@ START_SECTION(AASequence fromString(const String& s, bool permissive = true))
+  AASequence seq19 = AASequence::fromString("PEPT(Phospho)IDEC(Carbamidomethyl)EK(UniMod:313)");
+  TEST_EQUAL(seq19.isModified(),true);
+  TEST_EQUAL(seq19.hasCTerminalModification(), true)
+  TEST_STRING_EQUAL(seq19.getCTerminalModification(), "Lys-loss")
```

somehow this seemed like a good idea in 1086f770aa021a37d700adbb354eca3b89824bdd back in 2009

**Comment by hroest** [comment]
I think there are multiple ways to approach this topic:

1. leave things as they are, which leads to unexpected failures
2. treat all Protein C/N term the same as any C/N term for now which will lead to less unexpected failure and in a few cases to the addition of a Protein C/N terminal modification to a peptide that is not actually C/N terminal of the protein
3. properly use PROTEIN_C_TERM and PROTEIN_N_TERM but in most cases we will have no information anyways whether the current peptide is C/N terminal of the protein and whether the modification is allowed. Thus we will have to fall back to 2 in most cases

I opt for solution 2 as this fixes the problem quickly and makes things work for most users. For solution 2 we could go 

- the very quick and dirt route and simply write `ResidueModification::N_TERM` everywhere
- properly read the unimod xml file and store `ResidueModification::PROTEIN_N_TERM` but then adopt ModificationsDB.cpp to "fail softly" and for all cases also allow `PROTEIN_N_TERM` when `N_TERM` is specified

the second solution would require more testing, but seems long-term more suitable and correct.

**Comment by timosachsenberg** [comment]
I think that we should solve this issue by storing PROTEIN_C_TERM and PROTEIN_N_TERM and provide fall back mechanisms.

**Comment by hroest** [comment]
@timosachsenberg any progress on this issue?

**Comment by timosachsenberg** [comment]
I think @hendrikweisser also took a look at this recently and this is still an open issue.

**Comment by cbielow** [comment]
just to collect information:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/ModificationsDB.cpp#L370 is buggy (since it should say `Protein N-term` and is attached to `specificities`, not origin in all the OBO's we have, e.g.  `property_value: specificities: "(K,S,T,Y,Protein N-term)" xsd:string`

**Comment by cbielow** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/UnimodXMLHandler.cpp#L111 should be changed to `PROTEIN_C_TERM`, but this will ripple through a few places...

**Comment by jpfeuffer** [comment]
There have been a lot of changes to modifications in the last years. Support is still not 100%. I think for example PeptideIndexer does not consider the mods when matching.
But most of this here is outdated.
Closing.
