### ISSUE TITLE
issues with OpenMS.ini

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1924]
Sometimes it seems on travis (and also on our cluster) we have failed runs due to invalid reads from OpenMS.ini - see http://cdash.openms.de/testDetails.php?test=30730828&build=172298 for example

```
Error: Unable to read file (While loading '/Users/travis/.OpenMS/OpenMS.ini': invalid document structure( in line 1 column 1)
Probable cause: The file suffix (ini) does not match the file content (unknown). Rename the file to fix this. in: /Users/travis/.OpenMS/OpenMS.ini)
/Users/travis/build/OpenMS/OpenMS/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(103): While loading '/Users/travis/.OpenMS/OpenMS.ini': invalid document structure( in line 1 column 1)
Probable cause: The file suffix (ini) does not match the file content (unknown). Rename the file to fix this.
```

not sure whether this is really a fatal error but could we try to resolve these error messages somehow?

**Comment by hroest** [comment]
one idea could be to disable 

```
Param tool_user_defaults(getToolUserDefaults_(tool_name_));
Param system_defaults(File::getSystemParameters());
```
when run in test mode ...

**Comment by hroest** [comment]
it seems to really have a  lot do with the fact that the FileCacher is one of the first tests to run - so maybe it is a concurrency issue ...

**Comment by jpfeuffer** [comment]
What is a bit confusing are these two lines in the File_test ([here](http://cdash.openms.de/testDetails.php?test=32101829&build=174688)):
```
 +  line 185:  TEST_NOT_EQUAL(File::getUserDirectory(),String()): got /home/travis/, forbidden is ' '
+  line 196:  TEST_EQUAL(File::getUserDirectory(),dirname): got /tmp/2016-04-22_030520_testing-worker-linux-docker-47e95fc0-3420-linux-11_29753_4/, expected /tmp/2016-04-22_030520_testing-worker-linux-docker-47e95fc0-3420-linux-11_29753_4/
```
This means that between line 185 and 196, the UserDirectory was reset. Which could lead to this failure. What do you think?

**Comment by hroest** [comment]
yes, I see - I feel like it is bad practice to implement file access the way we have it right now in a concurrent system. It will fail and it does fail often - the only way to keep it would be to manually have the build script create ~/.OpenMS/OpeMS.ini at some point and then still use the "read only" version

anyways, there are other reasons to dislike the approach - why have a hidden folder which sets some magic global variables? seems highly suspect to me _unless_ you specifically create and edit the file. However if you dont notice that the file exists, it only leads to unexpected failure
