### ISSUE TITLE
Linux packages

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#1925]
While going through the docu, I wondered about the install docu for Linux.
It says that there are only packages for Debian.
According to this: http://pkgs.org/search/openms
there are actually also packages for e.g. Fedora. Does anyone know, who is responsible for any of them? Do we officially support them?

**Comment by jpfeuffer** [comment]
Ah okay. So Antonio Trande is responsible for the Fedora packages. Should we include them in the docu then?

**Comment by hroest** [comment]
We had several people on the mailing list asking about packages, maybe you
can find them in the archives. I have been working with Filippo who makes
the debian packages but nothing more official than that. Most distros
anyways have dedicated people already for packaging and we can make it as
easy as possible for them and merge code back upstream if necessary.  We
now have Debian and fedora.

H

**Comment by jpfeuffer** [comment]
Good, so I add a note in the documentation on which packages we know of right now, a disclaimer about them not being maintained by us directly, and a hint to compile it by yourself when in doubt.

**Comment by hroest** [comment]
Also compile it yourself if you want the newest version

sent from my smartphone -- you may keep any typos you find.

**Comment by jpfeuffer** [comment]
Closed with #1945

**Comment by sagitter** [comment]
> there are actually also packages for e.g. Fedora. Does anyone know, who is responsible for any of them? 

Yes, OpenMS is officially packaged for Fedora: https://admin.fedoraproject.org/pkgdb/package/rpms/openms/

> Do we officially support them?

When I need help, usually I ask here on GitHub.
