### ISSUE TITLE
IDFileconverter: wrong mass of N-terminal modifications

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#1926]
Hello,

when converting from `idXML` to pepXML using `IDFileConverter`, masses of N-terminal modifications are calculated wrongly. Example
```
(Acetyl)AHLLTSGPPPDEQDFIQAYEEVR (in idXML)
```
becomes 
 mod_nterm_mass="71.0371141595" in `pepXML` 
but should be +42... 

Rather than the mass of the acetylation, the mass of the first residue -18 is reported.

The same modification (e.g. side chain acetylation) is reported correctly, this only occurs for N-termini.

Oliver

**Comment by timosachsenberg** [comment]
The relevant code is in PepXMLFile.cpp l.400 seems to confirm what Oliver is reporting:
```
          if (seq.hasNTerminalModification())
          {
            const ResidueModification& mod = ModificationsDB::getInstance()->getTerminalModification(seq.getNTerminalModification(), ResidueModification::N_TERM);
            f << " mod_nterm_mass=\"" <<
              precisionWrapper(mod.getMonoMass() + seq[(Size)0].getMonoWeight(Residue::Internal)) << "\"";
          }

          if (seq.hasCTerminalModification())
          {
            const ResidueModification& mod = ModificationsDB::getInstance()->getTerminalModification(seq.getCTerminalModification(), ResidueModification::C_TERM);
            f << " mod_cterm_mass=\"" <<
              precisionWrapper(mod.getMonoMass() + seq[seq.size() - 1].getMonoWeight(Residue::Internal)) << "\"";
          }
```

I think for both C-term and N-term modifications it should be: mod.getDiffMonoMass() only.
Can anyone who is more into PepXML confirm this?

Timo

**Comment by oliverschilling** [comment]
Hello Timo,

while I cannot really comment on the actual code, I can give you an example on how an N-terminal modification is correctly reported in pepXML:

<modification_info mod_nterm_mass="35.0711" mod_cterm_mass="17.0031" modified_peptide="n[35]IAQTK[162]AADMTGADIE">

(taken from the TPP). Does this help a bit?

Thanks

Oliver

**Comment by timosachsenberg** [comment]
I think so would be great if you could provide the file.

**Comment by oliverschilling** [comment]
Voila:
[https://www.dropbox.com/s/9av29z91kio7h8q/interact.pep.xml?dl=0](url)

Note how N-termini are described, one example:

`<modification_info mod_nterm_mass="35.0711" mod_cterm_mass="17.0031" modified_peptide="n[35]SDWDGFAYQTK[162]">
`

Please let me know if there are further questions

**Comment by timosachsenberg** [comment]
@hendrikweisser I think you are more into PepXML than I am. Given the information Oliver provided do you agree that instead of storing the mass of the first / last residue + the modification mass we need only to store the diffMonoMass?

**Comment by hendrikweisser** [comment]
@timosachsenberg: I never worked on the pepXML writing part, only on reading. I'm also not sure what exactly Oliver is saying. What seems clear to me:

The attributes "mod_nterm_mass"/"mod_cterm_mass" of "modification_info" store the mass of the modification, *not* the mass shift. Compare to the search parameters in the "terminal_modification" elements, e.g. https://gist.github.com/lars20070/001650c8b870fa6825581770e1c3aadd#file-interact-pep-xml-L2142. The number that matches is "mass", not "massdiff".
(Strangely, the "mod_nterm_mass" value in Oliver's example, 35.0711, from [here](https://gist.github.com/lars20070/001650c8b870fa6825581770e1c3aadd#file-interact-pep-xml-L2249), matches none of the search parameters - neither "mass" nor "massdiff" - so I don't understand where that's coming from.)

What happens if you take a pepXML file (e.g. Oliver's example), convert it to idXML and then back to pepXML with IDFileConverter? If the values of the "mod_nterm_mass" attributes change, then something is definitely wrong. It could be wrong in the pepXML reading or in the writing function, but I think the reading function is more well-tested, so more likely to be correct.

**Comment by oliverschilling** [comment]
Hello,

regarding the +35 mass: this is Unimed entry 510 + 1 Da which tandem adds to the N-terminus in some default settings.

I tried to convert a pepXML back and forth:
Here is one example line:

(note N-terminal modification is Unimod entry 36 (aka dimethylation) + the 1 Da add-on from X!Tandem)

Original, functional pepXML:
`<modification_info mod_nterm_mass="29.0392" mod_cterm_mass="17.0031" modified_peptide="LSELGNQYSNNVLDATMGWTK">`

in the idXML:
`<PeptideHit score="1" sequence="(Dimethyl)LSELGNQYSNNVLDATMGWTK(Dimethyl)" `
(peptide N-terminal modification correctly found)

and back-conversion to pepXML:
`<modification_info modified_peptide="(Dimethyl)LSELGNQYSNNVLDATMGWTK(Dimethyl)" mod_nterm_mass="113.0840643509">`

-> the modification text is now part of the peptide sequence
-> the mass of the N-terminal modification is wrong 

At
[http://sashimi.sourceforge.net/schema_revision/pepXML/pepXML_v118.xsd](url)
the following is specified for mod_nterm_mass in the pepXML scheme:
 `<xs:attribute name="mod_nterm_mass" type="xs:double">
<xs:annotation>
<xs:documentation>Mass of modified N terminus</xs:documentation>
</xs:annotation>
 `

So this can be the mass of the residue plus the modification (strictly speaking, the TPP output is then incorrect as well) - but as of now, IDFileconverter reports the mass of the first, N-terminal residue -18 Da.

Hope this helps
Oliver

**Comment by hendrikweisser** [comment]
@oliverschilling: Thank you for running that test. It seems that @timosachsenberg was right and storing the "diffMonoMass" is what we should do. (Although I'm now fully confused about what "mass" and "massdiff" in "terminal_modification" mean and how they relate to "mod_nterm_mass" in "modification_info".)
We should also use the unmodified peptide as value of the "modified_peptide" attribute, apparently.

I don't think we could recover the "+1 Da" add-on from X! Tandem when converting the idXML to pepXML. Would that be important for you, @oliverschilling?

**Comment by oliverschilling** [comment]
Thanks for the fast response. The +1 Da "present" can be easily switched off in the tandem parameters:
`	<note type="input" label="protein, cleavage N-terminal mass change">+1.00794</note>`

Set this to 0, that would solve, we kept it at this value for more or less historical reasons. Would that make things easier?

**Comment by hendrikweisser** [comment]
> Would that make things easier?

It shouldn't have an impact on the conversion. The problem is just that based on the information in the idXML, e.g. "(Dimethyl)" at the N-terminus, we can only recover the delta mass from Unimod, i.e. without the 1 Da add-on.

By the way, does this problem only happen for the N-terminus or also for the C-terminus?

**Comment by timosachsenberg** [comment]
I think it should happen for C-terminus as well in principle - but as we probably assign the C-terminal modification to the last residue instead of the c_term_mod in AASequence I think the error does not occur there.

**Comment by oliverschilling** [comment]
Unfortunately, we don't use C-terminal modifications, so I cannot tell...

**Comment by hendrikweisser** [comment]
> I think it should happen for C-terminus as well in principle - but as we probably assign the C-terminal modification to the last residue instead of the c_term_mod in AASequence I think the error does not occur there.

Ah, that makes a lot of sense. However there was a recent proposal to mark the C- and N-terminus of peptides, e.g. ".PEPTIDE.", which would allow us to distinguish between modifications on the C-terminus and on the last residue, at which point we might have the problem that Oliver raised also on the C-terminus.

In any case, Timo, can you make the changes to PepXMLFile?

**Comment by timosachsenberg** [comment]
I am on holiday right now so I want to keep real work to a minimum ;) But I can do so in two weeks.

**Comment by lars20070** [comment]
Can we merge this fix?
