### ISSUE TITLE
spectrast2tsv.py discards ~1/3 of spectra from SpectraST library

### ISSUE THREAD

**Issue by SimionKreimer** [OpenMS/OpenMS#1928]
I have a SpectraST consensus library containing roughly 4,500 spectra, however when I run the conversion script using 0 or 1 transition minimum and 40 transition maximum as the parameters a library of only ~3,000 assays is generated. I'm wondering where the rest of the spectra go, are there some internal filters taking stuff out? Thanks for the help. I will upload the library and the output to this folder:
https://www.dropbox.com/sh/lj3gsgmwuqldfuh/AAB85n1EVlMn6mQyg6CE43Aca?dl=0

**Comment by grosenberger** [comment]
Hi Simion,

This ticket should rather be opened in msproteomicstools as spectrast2tsv.py is part of this package: https://github.com/msproteomicstools/msproteomicstools/issues

spectrast2tsv.py applies several filtering criteria, including exclusion of transitions falling into the precursor isolation window of the swathes.txt definition file and the the type of fragment ions, e.g. default b,y. Depending on your spectral library, there could also be several entries that don't have any of the required transitions. My suggestion would be to find a few examples that were excluded and see why this was the case.

Alternatively, you can give OpenSwathAssayGenerator, part of OpenMS/develop a try. Here, you need a SpectraST .MRM file as input (spectrast -cM) and if you set the flag OpenSwathAssayGenerator -debug 10, it will tell you for each and every transition, assay, peptide or protein why it was excluded.

Best regards,
George

**Comment by SimionKreimer** [comment]
Hi George thank you for the quick response. I have posted the question to the msproteomicstools board as you've suggested and also am trying out the OpenSwathAssayGenerator approach. I was able to generate the MRM file with SpectraST but the OpenSwathAssayGenerator doesn't take it as input, it requires a TraML input. I can generate a traML assay library from SpectraST but that would require using the spectrast2tsv.py script, and defeats the purpose. Can you give a little more instruction about going from SpectraST to OpenSwathAssayGenerator?
