### ISSUE TITLE
Misleading error message in PeakPickerMRM

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1930]
PeakPickerMRM can generate the following error message:

> Found no signal. The Gaussian width is probably smaller than the spacing in your profile data. Try to use a bigger width.

This message comes from the GaussFilter class. GaussFilter or SavitzkyGolayFilter are used internally in PeakPickerMRM to smooth chromatograms. Since the filter is applied to chromatograms, the "spacing in your profile data" part of the error message is misleading.

**Comment by hroest** [comment]
the issue is a hardcoded `cerr` here : https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FILTERING/SMOOTHING/GaussFilter.h#L123

I dont think it is that useful for people to hear that message

**Comment by timosachsenberg** [comment]
so how we deal about this?
I think a message to indicate that something is wrong with your data, i.e., it is already centroided, is quite useful. Nevertheless, the message is not very informative and I don't know if this is the right place to report an error. 
Looking at the comments it seems as if originally an exception was thrown
```
      @exception Exception::IllegalArgument is thrown, if the @em gaussian_width parameter is too small.
```
which has probably been removed to make pipelines more robust.

So how should we go from here? Keep or remove the message?
If we keep it, what is your preferred phrasing?

**Comment by hendrikweisser** [comment]
Another option would be to have the "filter" function return a boolean indicating success/failure, in which case the calling class could decide how to handle that. This would allow us to differentiate between the "centroiding" and "chromatographic peak finding" use cases.

The minimal change would be to rephrase, perhaps like this:
"Warning: Found no signal. (If picking peaks in profile data, the Gaussian width is probably smaller than the spacing in the data - try to use a bigger width.)"
