### ISSUE TITLE
MapAlignerIdentification doesn't work if peptide scores are PEPs

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1939]
MapAlignerIdentification has a parameter "algorithm:peptide_score_threshold" that can be used to filter which peptide IDs should be considered for the alignment based on their scores. The default value of this parameter is zero, which should indicate that no filtering should take place. Unfortunately this does not work if the peptide scores are posterior error probabilities (PEPs), which range from zero (best) to one (worst). The way the filtering is implemented, only peptides with scores at least as good as the threshold are considered - but for PEPs, zero is the best possible score, so (almost) all peptide IDs are removed by the filter.

Is it possible to use "NaN" as the default value for a double variable in OpenMS? (That could be used to solve the problem.)

**Comment by hroest** [comment]
either negative values or use a second flag that "turns on" the filtering

**Comment by hendrikweisser** [comment]
I would like to avoid adding a flag if possible. Does anyone know of a peptide score type that can have legitimate negative values?

**Comment by cbielow** [comment]
just a thought:
  why does the filtering flag even exist here? Could that be outsourced 
using IDFilter -- it add another node in the pipeline, but seems cleaner 
to me.

Am 4/13/2016 um 12:32 PM schrieb hendrikweisser:

**Comment by timosachsenberg** [comment]
If it is possible I would also go with the removal of the flag and use IDFilter

**Comment by lars20070** [comment]
+1

**Comment by hendrikweisser** [comment]
> why does the filtering flag even exist here? Could that be outsourced using IDFilter -- it add another node in the pipeline, but seems cleaner to me.

The idea behind this was that you might want to use only a subset of the IDs (the particularly reliable ones) for the alignment, but still keep the rest (i.e. not remove them with a filter).
However, I don't think this is actually being used much ("min_run_occur" is probably the more useful filtering parameter). In addition, you could still achieve the same with a more complex pipeline, by filtering, aligning, then applying the transformations to the unfiltered data (using MapRTTransformer).

So yeah, I guess I'll remove the option.

**Comment by hendrikweisser** [comment]
Should I open a pull request against "master" and/or "develop"?

**Comment by hendrikweisser** [comment]
I've opened a pull request against "develop" now (#1943). Let me know if I should also open one against "master" to include this fix in the release.

**Comment by timosachsenberg** [comment]
develop
