### ISSUE TITLE
PeakPicker algorithms don't use Factory pattern [194]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#194]
Submitted by hendrikweisser on 2010-09-25 17:04:34

In contrast to all (?) other tools offering different algorithms (FeatureFinder, MapAligner, FeatureLinker etc.), the PeakPicker does not use the Factory design pattern.

**Comment by timosachsenberg** [comment]
@hendrikweisser I think we can close this do you agree?

**Comment by hendrikweisser** [comment]
@timosachsenberg:
Yes. Since the TOPP tools with different algorithms have been split into multiple tools, this is not as relevant any more.
