### ISSUE TITLE
List docker images as alternative to installations

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#1944]
As soon as docker images are a reliable way to use OpenMS, we should mention it in the documentation and on the website.

**Comment by hroest** [comment]
are they not reliable?

Also, I have been working with the Biodocker project which could be a nice way to distribute the docker files and we should mention it. I would prefer to have the distribution go over that project and not do it completely ourselves ... see also #1343 which contains a 2.0 build

**Comment by jpfeuffer** [comment]
Oh sorry, I should have phrased it differently. It was more of a question ;)
I was coming up with this, because I am in the process of installing nightly builds on docker containers that I intend to upload regularly soon.
I am fine with distributing this via Biodocker as long as we can share both the Dockerfiles as well as the built images (i.e. we need to "push" them somehow and need access to their repo). We can continue the discussion in #1343.
For the docu I will mention and link Biodocker somehow. The question is, if we should mention it only for Linux (which will probably be the most common platform to use the images) or make a general page about it? What do you think?

**Comment by jpfeuffer** [comment]
(Will be added to #1945.)

**Comment by jpfeuffer** [comment]
Closed with #1945 . We should keep an eye on extending the docu when the integration comes further.
