### ISSUE TITLE
Build error on MVSC10

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#1956]
I think this line
https://github.com/OpenMS/OpenMS/commit/71021da733fd666fde5376a7adf31b225d019fdc#diff-42933894e745ddadd65d78cea30d378bR92

introduced an error on MVSC10 on the build machines. Unrecognized because currently only master was built because of release process.
Results in multiple errors like this:
3>..\..\..\OpenMS\src\openms\source\CONCEPT\GlobalExceptionHandler.cpp(72): error C2065: '__PRETTY_FUNCTION__' : undeclared identifier

**Comment by jpfeuffer** [comment]
Pretty_function is no real preprocessor macro I think. I do not know if you can test if it is defined like this.

**Comment by timosachsenberg** [comment]
damn. IIRC his line fixed the issue on newer clang (in addition to older gcc) because both now implement it as macro.

**Comment by timosachsenberg** [comment]
But why does it fail? If it is not defined there should be no problem.

**Comment by timosachsenberg** [comment]
I think we can revert the change as it only generates a warning on clang

**Comment by jpfeuffer** [comment]
Hmm you are right. It was basically a sophisticated guess because the builds failed around this time and it had to do with __pretty_function__.
Was there another commit that changed something in the build system related to MSVC, PrettyFunction or another macro/define

**Comment by jpfeuffer** [comment]
Could be more this one here:
https://github.com/OpenMS/OpenMS/commit/d79663cde07ba6a3b2e185f88905be3d0110be9a#diff-3e62963ed2367d793525d25508cdb49fL63

**Comment by timosachsenberg** [comment]
yeat this is probably it. I'll close the PR and change this one

**Comment by jpfeuffer** [comment]
fixed in #1959
