### ISSUE TITLE
MascotAdapterOnline: RT precision too low when writing MGF

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1961]
MascotAdapterOnline (MAO) converts its mzML input to an MGF file, which is then transmitted to the Mascot server for searching. In order to keep the MGF file small, MAO sets the "compact" flag in `MascotGenericFile::store`. This means that RT values are written out using only six digits (in total).

For very long gradients (>10,000 s, i.e. ~3 hours) this results in too low precision for some RT values - if five digits have to be used for the integer part, there's only one digit left for the fractional part. This leads to problems e.g. in ConsensusID, where IDs from multiple searches are linked based on RT and m/z information, and some IDs may be missed due to imprecise RT values.

As a solution, writing MGF in "compact" format should use three decimal digits for the RT values in all cases.

**Comment by timosachsenberg** [comment]
can you add labels?

**Comment by hendrikweisser** [comment]
The problem affects MascotAdapterOnline, but the change would need to be made in MascotGenericFile - so I've added both "TOPP" and "library" labels.
