### ISSUE TITLE
FileConverter should read mzQuantML

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1968]
Currently the FileConverter does not read mzQuantML which makes it hard to use this format in our own pipeline. It would be nice to read in mzQuantML and convert it to featureXML / consensusXML. Is this something that we could do in theory but is not exposed in  FileConverter or is this just hard to do? It seems so far we only write out mzQuantML but do not really read it anywhere...

**Comment by hroest** [comment]
Maybe @mwalzer could comment?

**Comment by hendrikweisser** [comment]
Do we (still) have support for mzQuantML at all? I can't see it in the list of supported file types in FileConverter or FileInfo.
