### ISSUE TITLE
OpenSWATHWorkflow with overlapping windows analysis

### ISSUE THREAD

**Issue by SimionKreimer** [OpenMS/OpenMS#1969]
Hi,
I have a few data files which were acquired on an QExactive using 22m/z wide windows. The adjacent windows have no overlap but there are two sets of 28 windows which are offset by 11 m/z, so the instrument alternates between scanning 400-1016 to 389-1005 m/z. There is also an MS1 scan taken every 27 SWATH scans. When I run  the OpenSWATHWorkflow on this file, it seems to be missing a lot of the peptides in my library, I know there are some internal filters, but it seems to be missing a lot of stuff. I tried to do this analysis in Skyline and many of the peptides which were not found by OpenSWATH showed up. I'm wondering if this loss in sensitivity could be due to the offset windows, because it's treating the file as 56 SWATH windows. Even when I run the analysis across the whole range with the rt_extraction_window set to -1 many peptides are missing. I've placed the files into this dropbox folder:
https://www.dropbox.com/sh/9h22mwz8b22aiwf/AAB1WSfNM3wWEjAA4xy9YueIa?dl=0

I'm running on Archlinux 64-bit with openMS-2.0.0 also 64-bit.
Thanks for the help.

**Comment by hroest** [comment]
Currently OpenSWATH does not support the overlapping window strategy, so I dont think what you want to do will work. As you guessed, OpenSWATH will see 56 different SWATH windows and treat them individually. You would have to select each peptide to be extracted from one or the other SWATH window, so probably you can only use half of your data. You can do that with the  `-swath_windows_file` option but again, this will probably not give you optimal results.

Have you tried to write out chromatograms and check whether they look reasonable? What do you actually mean by "it misses a lot", does it still pick peaks in the chromatogams or not? Have you tried to supply a windows file with `-swath_windows_file`, does the tool recognize your windows correctly? 

What is the output of OpenSWATH, it will say something like "Determined there to be ... SWATH windows"

**Comment by SimionKreimer** [comment]
The output of OpenSWATH is "Determined there to be 56 SWATH windows". The analysis generates sensible results for high intensity peaks, but no output for low intensity peptides in the tsv result file. This makes sense if only half of the data is used to generate the peak profile, if the peaks are narrow they might not look like a real profile. When I look at the same data in Skyline with the same assay library then I detect many of the low level peptides I'm looking for. I did try running the workflow with  -swath_windows_file, but I had to put all 56 windows into the windows file for the workflow to run, which defeated the purpose, unless there is a trick to doing this that I'm not aware of? Are there any plans to adding overlap deconvolution to OpenSWATH? I'm using OpenSWATH as part of a larger automated workflow and would very much prefer to keep it automated.

**Comment by hroest** [comment]
Yes, I believe that what you are doing is probably the easiest approach in OpenSWATH. It depends what you mean by "overlap deconvolution", I think there are some proposed ideas from the MacCoss lab on how to do that. It is likely that some of these are implemented in Skyline in a similar manner as the MSX approach (https://www.ncbi.nlm.nih.gov/pubmed/23793237 ) using non-negative least squares, is this what you had in mind? So, no we dont have that in OpenSWATH and also no current plans to add it as we perform most experiments without overlapping windows. However, we would be open to incorporate code if you plan to add it yourself. 

So probably Skyline is your best bet at the moment as I am also not aware of any other tool that supports this.

**Comment by hendrikweisser** [comment]
Question has been answered.
