### ISSUE TITLE
TOPPView: opening a file on windows 10 with space in the file name leads to an error

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1974]
to be confirmed

**Comment by hroest** [comment]
FYI: works on Linux

**Comment by timosachsenberg** [comment]
hi Leon can you confirm?

**Comment by jpfeuffer** [comment]
See also #3598 if someone takes this task. I suspect it to be true tbh.

**Comment by Leon-Bichmann** [comment]
Hey ok, I'll have a look tomorrow

**Comment by jpfeuffer** [comment]
Could you test?

**Comment by Leon-Bichmann** [comment]
Tested with spaces in file and path it works on windows 10.

Currently I dont have a shared drive to test it with, so #3598 is still not clear.

**Comment by jpfeuffer** [comment]
Can you test non-ASCII characters, too?

**Comment by Leon-Bichmann** [comment]
μ did not work

**Comment by hendrikweisser** [comment]
> Tested with spaces in file and path it works on windows 10.

Closing this because the problem couldn't be confirmed.
