### ISSUE TITLE
Need to escape commas in file_origins

### ISSUE THREAD

**Issue by sneumann** [OpenMS/OpenMS#1983]
Hi,

we're running Bruker instruments, and they have the cool feature to include a lot of information 
into the filename, such as autosampler location, measurement serial number and more:

```
MSpos-Ex1-Col0-48h-Ag-1_1-A,1_01_9818.mzML
MSpos-Ex1-Col0-48h-Ag-2_1-A,1_01_9820.mzML
MSpos-Ex1-Col0-48h-Ag-3_1-A,1_01_9822.mzML
MSpos-Ex1-Col0-48h-Ag-4_1-A,1_01_9824.mzML
```

After running FeatureFinderMetabo and FeatureLinkerUnlabeled, 
the resulting consensusXML file has:

```
        <UserParam type="stringList" name="spectra_data" value="[file://.//MSpos-Ex1-Col0-48h-Ag-1_1-A,1_01_9818.mzData,file://.//MSpos-Ex1-Col0-48h-Ag-2_1-A,1_01_9820.mzData,file://.//MSpos-Ex1-Col0-48h-Ag-3_1-A,1_01_9822.mzData,file://.//MSpos-Ex1-Col0-48h-Ag-4_1-A,1_01_9824.mzData,file://.//MSpos-Ex1-cyp79-48h-Ag-1_1-B,1_01_9819.mzData,file://.//MSpos-Ex1-cyp79-48h-Ag-2_1-B,2_01_9821.mzData,file://.//MSpos-Ex1-cyp79-48h-Ag-3_1-B,1_01_9823.mzData,file://.//MSpos-Ex1-cyp79-48h-Ag-4_1-B,2_01_9825.mzData,file://.//MSpos-Ex2-Col0-48h-Ag-1_1-A,2_01_9827.mzData,file://.//MSpos-Ex2-Col0-48h-Ag-2_1-A,3_01_9829.mzData,file://.//MSpos-Ex2-Col0-48h-Ag-3_1-A,4_01_9831.mzData,file://.//MSpos-Ex2-Col0-48h-Ag-4_1-A,2_01_9833.mzData,file://.//MSpos-Ex2-cyp79-48h-Ag-1_1-B,3_01_9828.mzData,file://.//MSpos-Ex2-cyp79-48h-Ag-2_1-B,4_01_9830.mzData,file://.//MSpos-Ex2-cyp79-48h-Ag-3_1-B,3_01_9832.mzData,file://.//MSpos-Ex2-cyp79-48h-Ag-4_1-B,4_01_9834.mzData]"/>
[...]
        <mapList count="16">
                <map id="0" name="MSpos-Ex1-Col0-48h-Ag-1_1-A,1_01_9818.featureML" unique_id="9302709870205376192" label="" size="13259">
                </map>
                <map id="1" name="MSpos-Ex1-Col0-48h-Ag-2_1-A,1_01_9820.featureML" unique_id="5104118551348192009" label="" size="13056">
                </map>
                <map id="2" name="MSpos-Ex1-Col0-48h-Ag-3_1-A,1_01_9822.featureML" unique_id="14153086579297287071" label="" size="13064">
                </map>
```

Here the resulting mzTab has the wrong metadata:

```
MTD     mzTab-version   1.0.0
MTD     mzTab-mode      Summary
...
MTD     ms_run[1]-location      file://.//MSpos-Ex1-Col0-48h-Ag-1_1-A
MTD     ms_run[2]-location      1_01_9818.mzData
MTD     ms_run[3]-location      file://.//MSpos-Ex1-Col0-48h-Ag-2_1-A
MTD     ms_run[4]-location      1_01_9820.mzData
MTD     ms_run[5]-location      file://.//MSpos-Ex1-Col0-48h-Ag-3_1-A
MTD     ms_run[6]-location      1_01_9822.mzData
```

So I guess the ms_run names are taken from the `name="spectra_data"` 
and just interpreted that as comma separated list. Bruker always 
uses the comma for the autosampler location, this can't be changed by the user.

=> I think the string_list needs to properly escape special characters.

Yours,
Steffen

**Comment by hendrikweisser** [comment]
@timosachsenberg: Any update on this?

**Comment by jpfeuffer** [comment]
@timosachsenberg this seems pretty serious. Any updates?

**Comment by timosachsenberg** [comment]
Probably fixed three years ago (according to blame) in https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp#L284

**Comment by jpfeuffer** [comment]
Xmlescape escapes commas?

**Comment by timosachsenberg** [comment]
no apparently not

**Comment by timosachsenberg** [comment]
We can probably use &#44; = comma to escape commas in the individual strings

**Comment by timosachsenberg** [comment]
should be fixed in https://github.com/OpenMS/OpenMS/pull/5796

**Comment by sneumann** [comment]
Hi, could you simply paste an example mzTab file ? I'd like to see if it then has an `&#44;` in it, which would confuse the heck out of an unaware R based reader. Yours, Steffen

**Comment by cbielow** [comment]
the fix in #5796 may not be sufficient to avoid the problem, since reading data from a consensusXML file in MzTabExporter will not undo the XML escaping (if it happens at all for consensusXML, I did not check the code).

**Comment by jpfeuffer** [comment]
Yes, the PR won't fix existing files, which is fine and hard to avoid.
@cbielow Why wouldn't it work for cXML? I thought the XMLHandler with the attributesAsList_ is used in all our XML formats?

I think mzTab should be fine. We read it unescaped and should not do any escaping in mzTab. Let us double-check. @timosachsenberg probably a test would be best.

**Comment by timosachsenberg** [comment]
K will I prepare a test file

**Comment by cbielow** [comment]
> @cbielow Why wouldn't it work for cXML? I thought the XMLHandler with the attributesAsList_ is used in all our XML formats?

Mhhh.. you are probably right. I did not realize this is a userParam. But a test would be appreciated :)
This would also call for a 'pipeline' test, i.e. from mzML all the way to mzTab. Just to make sure. We had this scenario a couple of times now AFAIR, so maybe its time to get something going :)

**Comment by timosachsenberg** [comment]
Ok I looked a bit into that and it seems that a few things changed how we handle the names.
For one, we link from column header to file name in the consensus map.
This means that , now works out of the box as it only contains a string and not a string list.
Nevertheless, there seems to be issues with commas in StringLists at other places so I think a fix using an escape character is still needed.
