### ISSUE TITLE
Decharger mass accuracy option default too high(?) and uncommon unit

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#1984]
Currently mass_max_diff has a default value of 0.5 Th.
- Is it possible to adapt this option to instead use ppm? If not, I guess we should at least mention the why here.
- In case that we cannot switch to ppm: I understand that the large value comes from peptide/protein masses. But nowadays with better instruments and small molecule metabolomics, a smaller value seems sensible. Any reasons against decreasing the value? (or we could/should at least mention sensible values for metabolomics/high accuracy instruments)

... Reading up on the paper, I now got confused: What exactly is the mass_max_diff option?
- Is it the allowed error of observed mass shifts of observed features? (e.g. 21.98194 is a H+<->Na+ shift, and considered feature distances would have to be inside 21.98194+- mass_max_diff)
- Or is it the allowed error of a feature to its putative decharged M?
- Or something else?

The reason for all these questions: I am currently trying to use the Decharger for metabolomics with 30ppm quad-TOF data. Finding a good compromise between speed and performance (which I currently have problems with anyway) has not yet been very successful. Any tips  would be very appreciated.

**Comment by cbielow** [comment]
a few things to speed decharger up
 - leave 'q_try' at feature (tests only the annotated charge)
 - reduce 'retention_max_diff' as much as possible. If your chrom-apex detection is good, this should be no problem
 - reduce the number of possible adducts ('potential_adducts').. this is one of the most important parameters to reduce your search space

 - use COINOR instead of GLPK -- for large problem instances it CAN be a huge (x100) difference

**Comment by cbielow** [comment]
ahh 'max_mass_diff': `Or is it the allowed error of a feature to its putative decharged M?` thats it

**Comment by hroest** [comment]
@FabianAichele have you tried the FFMetabo and the Masstrace calculations from Erhan? How does it compare to the solution with decharching that you are looking at? As far as I can tell, the code from Erhan is newer and more optimized for high resolution data - or maybe I dont quite understand what you plan to do

**Comment by timosachsenberg** [comment]
Hi. I think he is using the decharger for adduct grouping of FFMetabo features

**Comment by hroest** [comment]
@timosachsenberg @FabianAicheler that is a cool idea, I am also interested in metabolomics so I will be interested to hear about progress in that area. As far as I could tell we dont (yet) have any solution for intrinsic grouping of adducts in the metabolomics pipeline, correct? 

@cbielow Does the algorithm take the RT elution profile into account when clustering or is it only delta-m/z based? I am wondering as we also seem to have code that does clustering of multiple isotopes based on RT and m/z profiles in the tool that @lars20070 is writing

**Comment by FabianAicheler** [comment]
Closed, Historically: Switched to Coinor, MetaboliteAdductDecharger was added for metabolomics, mass error parameters got tightened, ppm support for mz differences was added.
