### ISSUE TITLE
VS2015 support for OpenMS

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2001]
It would be great to have VS2015 support for OpenMS, see also discussion at #980

**Comment by burlab** [comment]
Hi Hannes

With some adaptations, I was able to build OpenMS 64 bit including PyOpenMS for Python 3.5 64 bit with MSVC2015. This was also successful for the current develop branch and on three different Win10 Pro systems.

There were no build errors when building all projects of OpenMS_host and PyOpenMS, but plenty of warnings, mostly with code C4244/C4267, e.g. "'initializing': conversion from 'size_t' to 'const int', possible loss of data" (see attached txt file). 

The OpenMS_tests tests mostly passed, see below. The 'LogStream_test' sometimes crashes and/or fails, sometimes passes. Most of the PyOpenMS tests passed, however test_FileIO.py fails with a lot of errors, some other tests pass but display error messages (see attached pyopenms tests failing or generating errors (see attached: pyopenms_tests_failing_errors.txt and nosetests_pyopenm_result.txt). 

Not sure about the significance of the test fails, warnings and errors mentioned above, however, the PyOpenMS Py3.5 builds work great so far. But I only used some of the core functions, as mzml/ traML file/data handling, MRMFeatureFinderScoring, MRMRTNormalizer etc

I have attached a description how I have built qt, contrib and OpenMS/PyOpenMS, did not yet add any issues or feature branches in Github, as I am fairly new to OpenMS (and C++). Will be happy to hear your comments.

Best wishes
Bo

------
OpenMS_Tests (MSVC2015, develop branch 01. Sep 2016):

99% tests passed, 8 tests failed out of 1834
Total Test time (real) = 293.58 sec
The following tests FAILED:
         15 - LogStream_test (OTHER_FAULT)
        335 - SvmTheoreticalSpectrumGenerator_test (Failed)
        337 - SvmTheoreticalSpectrumGeneratorSet_test (Failed)
        497 - IonizationSimulation_test (Failed)
        498 - MSSim_test (Failed)
        501 - RawTandemMSSignalSimulation_test (Failed)
        508 - MRMAssay_test (Failed)
        1505 - TOPP_PeakPickerWavelet_3_out1 (Failed)

Tutorial tests
1>  100% tests passed, 0 tests failed out of 29
1>  Total Test time (real) =   3.41 sec

[Building OpenMS with PyOpenMS for Python 3.5 with MSVS2015 (V1).pdf](https://github.com/OpenMS/OpenMS/files/504301/Building.OpenMS.with.PyOpenMS.for.Python.3.5.with.MSVS2015.V1.pdf)

[openms_Rel-MSVC2015-build_errors.txt](https://github.com/OpenMS/OpenMS/files/504293/openms_Rel-MSVC2015-build_errors.txt)
[pyopenm_nosetests_results.txt](https://github.com/OpenMS/OpenMS/files/504296/pyopenm_nosetests_results.txt)
[pyopenms_tests_failing_errors.txt](https://github.com/OpenMS/OpenMS/files/504297/pyopenms_tests_failing_errors.txt)

**Comment by hroest** [comment]
Thanks for your report, this is very helpful. I see from your build errors that most of them are "possible loss of data" while 2 are performance warnings (C4800) and one is unsafe use of bool (C4804) which is indeed an error (but not a grave one). 

I put up this instruction set recently on the wiki, maybe we can incorporate your experience here: https://github.com/OpenMS/OpenMS/wiki/Build-pyOpenMS-on-Windows

regarding the test failures in pyOpenMS: I believe they look like the input files do not match the expectations and it does not look like a fundamental problem with the build. I will have to look into these closer -- which version of OpenMS (e.g. git hash) did you build? Let me first check whether there all tests work on Linux... also many of the tests that you saw fail are test that we are also having trouble with on our "regular" tests

**Comment by burlab** [comment]
I used a recent version of the develop branch (88308bf7e954e1003ecc3daf16ac19426be353d4) to build OpenMS and pyopenms. For the pyopenms build I followed mostly your instructions, I can start trying to add some info on VS2015.  Wondering how many of the contrib build adaptations can easily be included in the contrib source without breaking build for previous MSVC versions?

**Comment by jpfeuffer** [comment]
I started on an update of the contrib to support newer compilers (some of the libraries had no VSProject files or were missing a configuration option for the newer compilers). See the contrib subrepository. I tested it and it was backwards compatible to VS10 (I had no earlier versions). It would be great if you could test this version of the contrib libraries, too.

**Comment by burlab** [comment]
I have tested the newerOSXDeployment branch of your contrib fork. That was the only branch with VS2015 support I found. It builds without any issue with VS2015, however subsequent build of the current develop branch of OpenMS fails with this contrib with errors such as : 
"...eigen3\eigen\src/Core/SolveTriangular.h(189): error C2280: 'Eigen::Block<Derived,-1,1,false> &Eigen::Block<Derived,-1,1,false>::operator =(const Eigen::Block<Derived,-1,1,false> &)': attempting to reference a deleted function"

Any other contrib branch I can test?

[Build errors OpenMS develop with new contrib 29Oct2016.txt](https://github.com/OpenMS/OpenMS/files/559719/Build.errors.OpenMS.develop.with.new.contrib.29Oct2016.txt)

**Comment by lars20070** [comment]
FYI, I reproduce the same error in my attempt to build with VS2015 under Windows Server 2012.

**Comment by jpfeuffer** [comment]
Thanks a ton to both for testing that branch. It seems to be a bug in Eigen ([here](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=920)). Maybe we also need to upgrade Eigen in the contrib.

**Comment by jpfeuffer** [comment]
Ok. I updated the pull request to use a newer version of Eigen (3.2.10). It seemed to work for @lars20070 .
@burlab : Can you do a git pull on your branch of my PR and re-run the contrib build and afterwards the OpenMS build?

**Comment by lars20070** [comment]
After the contrib update, I was able to build OpenMS with VS2015 under Windows Server 2012.
Thanks @jpfeuffer.

**Comment by burlab** [comment]
With your contrib update, OpenMS now also builds as release in VS2015 on Win10 without any error. Great, thanks @jpfeuffer. Tests results mostly in the same fails as @lars20070 observed and as with my previous version of contrib (see my first comment). I have used Boost 1.62.0 in that version. Let me know if should run other tests.

99% tests passed, 12 tests failed out of 1863

Total Test time (real) = 365.92 sec

The following tests FAILED:
  	 15 - LogStream_test (OTHER_FAULT)
  	335 - SvmTheoreticalSpectrumGenerator_test (Failed)
  	337 - SvmTheoreticalSpectrumGeneratorSet_test (Failed)
  	445 - TOPPBase_test (SEGFAULT)
  	497 - IonizationSimulation_test (Failed)
  	498 - MSSim_test (Failed)
  	501 - RawTandemMSSignalSimulation_test (Failed)
  	508 - MRMAssay_test (Failed)
  	1637 - TOPP_FeatureLinkerUnlabeledQT_5_out1 (Failed)
  	1799 - TOPP_MSGFPlusAdapter_1 (Failed)
  	1800 - TOPP_MSGFPlusAdapter_1_out1 (Failed)
  	1801 - TOPP_MSGFPlusAdapter_1_out2 (Failed)

**Comment by hroest** [comment]
@jpfeuffer can you comment on the pyOpenMS situation? have you tried building pyOpenMS with Python 3.5  / 3.6 ? This would be a great advantage of having MSVS 2015 and potentially a good idea to set up on Cdash as well.

**Comment by burlab** [comment]
The current develop OpenMS branch (https://github.com/OpenMS/OpenMS/commit/72b788d0ac1053cb4da8b56e1196342fa7c993d7) builds with MSVC2015 64 bit (Win10) as Release without errors . Tests result output:
``` 
1>  99% tests passed, 15 tests failed out of 1904
1>
1>  Total Test time (real) = 356.04 sec
1>
1>  The following tests FAILED:
1>  	 15 - LogStream_test (OTHER_FAULT)
1>  	336 - SvmTheoreticalSpectrumGenerator_test (Failed)
1>  	338 - SvmTheoreticalSpectrumGeneratorSet_test (Failed)
1>  	503 - IonizationSimulation_test (Failed)
1>  	504 - MSSim_test (Failed)
1>  	507 - RawTandemMSSignalSimulation_test (Failed)
1>  	514 - MRMAssay_test (Failed)
1>  	1660 - TOPP_FeatureLinkerUnlabeledQT_5_out1 (Failed)
1>  	1662 - TOPP_FeatureLinkerUnlabeledQT_6_out1 (Failed)
1>  	1669 - TOPP_IDMapper_4 (Failed)
1>  	1670 - TOPP_IDMapper_4_out1 (Failed)
1>  	1671 - TOPP_IDMapper_5 (Failed)
1>  	1672 - TOPP_IDMapper_5_out1 (Failed)
1>  	1827 - TOPP_MSGFPlusAdapter_1_out1 (Failed)
1>  	1828 - TOPP_MSGFPlusAdapter_1_out2 (Failed)
``` 

However, building pyopenms for Python 3.5.2 64 bit with MSVC2015  fails with following error:
``` 
...
...
pyopenms/pyopenms.cpp(293753): error C2664: 'void OpenMS::IDMapper::annotate(OpenMS::ConsensusMap &,const std::vector<OpenMS::PeptideIdentification,std::allocator<_Ty>> &,const std::vector<OpenMS::ProteinIdentification,std::allocator<OpenMS::ProteinIdentification>> &,bool,bool,const OpenMS::MSExperiment<OpenMS::Peak1D,OpenMS::ChromatogramPeak> &)': cannot convert argument 1 from 'OpenMS::ConsensusMap' to 'OpenMS::FeatureMap &'
        with
        [
            _Ty=OpenMS::PeptideIdentification
        ]
pyopenms/pyopenms.cpp(300529): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
...
...
pyopenms/pyopenms.cpp(890907): warning C4267: 'argument': conversion from 'size_t' to 'OpenMS::Int', possible loss of data
pyopenms/pyopenms.cpp(1114561): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
NMAKE : fatal error U1077: 'C:\WinPython35\python-3.5.2.amd64\python.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by hroest** [comment]
this may be an issue with the current develop and not with MSVS 2015. Can you try this patch: https://github.com/hroest/OpenMS/commit/45e61f94ed7d13e59906fd5066f9cbece09088ef.patch or if that doesnt work just remove the offending function "annotate" from the src/pyOpenMS/pxds/IDMapper.pxd

**Comment by burlab** [comment]
With your patch for IDMapper.pxd, pyopenms successfully builds and passes most tests. Thank you!
Output of the nosetests: [pyopenms_72b788d_Python3.5.2_64bit_MSVC2015_nosetests_results.txt](https://github.com/OpenMS/OpenMS/files/740941/pyopenms_72b788d_Python3.5.2_64bit_MSVC2015_nosetests_results.txt)

**Comment by hroest** [comment]
thanks, these are failed tests

```
======================================================================
FAIL: test_readfile (unittests.test_FileIO.TestIndexedMzMLFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Bo\Source\Repos\OpenMS\build_pyopenms\pyOpenMS\tests\unittests\test_FileIO.py", line 99, in test_readfile
    self.assertTrue(f.getParsingSuccess())
AssertionError: False is not true

======================================================================
FAIL: test_readfile_content (unittests.test_FileIO.TestIndexedMzMLFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Bo\Source\Repos\OpenMS\build_pyopenms\pyOpenMS\tests\unittests\test_FileIO.py", line 105, in test_readfile_content
    self.assertEqual( f.getNrSpectra() ,  2)
AssertionError: 0 != 2

======================================================================
FAIL: test_readfile (unittests.test_FileIO.TestIndexedMzMLFileLoader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Bo\Source\Repos\OpenMS\build_pyopenms\pyOpenMS\tests\unittests\test_FileIO.py", line 62, in test_readfile
    self.assertTrue(success)
AssertionError: False is not true

======================================================================
FAIL: test_readfile_content (unittests.test_FileIO.TestIndexedMzMLFileLoader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Bo\Source\Repos\OpenMS\build_pyopenms\pyOpenMS\tests\unittests\test_FileIO.py", line 68, in test_readfile_content
    self.assertEqual( e.getNrSpectra() ,  2)
AssertionError: 0 != 2

======================================================================
FAIL: test_readfile_content (unittests.test_FileIO.TestPepXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Bo\Source\Repos\OpenMS\build_pyopenms\pyOpenMS\tests\unittests\test_FileIO.py", line 29, in test_readfile_content
    self.assertEqual( peps[0].getHits()[0].getSequence().toString(), b'(Glu->pyro-Glu)ELNKEMAAEKAKAAAG')
AssertionError: b'.(Glu->pyro-Glu)ELNKEMAAEKAKAAAG' != b'(Glu->pyro-Glu)ELNKEMAAEKAKAAAG'

----------------------------------------------------------------------
Ran 241 tests in 12.914s

FAILED (failures=5)
```

it seems some are due to changes in OpenMS and we havent adopted the tests yet but some are more concerning and I need to look into these:

```

FIndexedMzMLDecoder::domParseIndexedEnd Error: no indexList element found:

<indexedmzML>GSxT/wkmoxXFJ/5PaSIT+i0ffX+pHULYUSADkqEtivD1LORC5SLdM60etMd5Hv8OPRw+ze0vF2cdKXEp+SXUBGUld+dRHv6EYSIr1mkebVTdLa29LSxTZYUnvwsxI9qKtRxmExEeBOZhH</binary>
                                        </binaryDataArray>
                                </binaryDataArrayList>
                        </chromatogram>
                </chromatogramList>
        </run>
</mzML>
  <indexList count="2">
    <index name="spectrum">
      <offset idRef="controllerType=0 controllerNumber=1 scan=1">10581</offset>
      <offset idRef="controllerType=0 controllerNumber=1 scan=2">332162</offset>
    </index>
    <index name="chromatogram">
      <offset idRef="TIC">651965</offset>
    </index>
  </indexList>
  <indexListOffset>655460</indexListOffset>
<fileChecksum>0</fileChecksum>
</indexedmzML>
```

there is clearly an `indexList` element here...

**Comment by jpfeuffer** [comment]
The test failures might not be related to the upgrade of MSVC but Boost. See #1584

**Comment by hroest** [comment]
any progress on this issue?

**Comment by cbielow** [comment]
I think MSVC is solved 100%.
Everything else should get a new ticket.
