### ISSUE TITLE
Usage statistics message

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2002]
After updating my OpenMS, I just saw this message about the collection of usage statistics for the first time:
```
The OpenMS team is collecting use statistics for quality control and funding purposes.
We will never give out your personal data but you may disable this functionality by 
setting the environmental variable OPENMS_DISABLE_USAGE_STATISTICS to OFF.
Connecting to REST server failed. Skipping update check.
Error: Operation canceled
```

Some comments:
- should be "usage statistics", not "use statistics"
- probably needs a comma before "but you may disable..."
- if the environment variable is called "...\_DISABLE\_...", setting it to "OFF" should *enable* the data collection, "ON" should disable it (maybe better to rename the variable to "...\_ENABLE\_...")
- the error message in the end gives the misleading impression that something important has failed (i.e. in the workflow)

**Comment by lars20070** [comment]
I agree @hendrikweisser. Especially your third point.

Can we please rename the variable to `OPENMS_ENABLE_USAGE_STATISTICS`?

**Comment by timosachsenberg** [comment]
It needs to be enabled by default (also if no env var. is set). Regarding the on off issue I will take a look at it when I'm back.

**Comment by timosachsenberg** [comment]
Thanks for the comments. Tracking should be enabled by default (i.e. no env var set). Lars what you proposed would disable it by default.

**Comment by lars20070** [comment]
Ok. - How about `OPENMS_DISABLE_USAGE_STATISTICS=ON` for switching home calling off?

I am fine with tracking on by default. Semantically, the variable does the opposite what it says.

**Comment by timosachsenberg** [comment]
yes I will chance this
