### ISSUE TITLE
IDFilter: add filters for trypticity, missed cleavages

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2004]
We should add options to IDFilter that let the user specify a digestion enzyme (perhaps with the option of reading it from the search parameters), and then filter peptides based on trypticity status (fully, semi-, non-tryptic; maybe with combinations?) and based on a range of allowed missed cleavages (e.g. 0-2).

**Comment by hendrikweisser** [comment]
With the recently improved support for enzymes and digestion, this should hopefully be very easy to implement.

**Comment by timosachsenberg** [comment]
I added the Hacktoberfest label which we might change to "entry level task" or similar in the future.

**Comment by timosachsenberg** [comment]
Ok this means we would need a parameter for the fasta file as well. 
So basically: PeptideEvidences of peptides are removed if the digest of its protein did not produce the peptide sequence (that is, we compare the result of bool EnzymaticDigestion::isValidProduct(const AASequence& protein, Size pep_pos, Size pep_length, bool methionine_cleavage))

**Comment by pati-ni** [comment]
Hi,
I am new here and I am currently working on this issue. 
On `EnzymaticDigestion::isValidProduct(const AASequence& protein, Size pep_pos, Size pep_length, bool methionine_cleavage)` how the `pep_pos` is known? I sense that this argument is missing. 
Would it be more suitable to use `EnzymaticDigestion::digest(const AASequence& protein, vector<AASequence>& output)`? The we can retrieve the peptides and filter our data. However in this case the peptides can not be filtered by their trypticity status because their position is unknown. I believe that is needed some extra functionality in class EnzymaticDigestion.

Maybe I got something terribly wrong so excuse my ignorance.

**Comment by timosachsenberg** [comment]
Hi @pati-ni .Welcome and thanks for taking a look at this issue. 
The peptide position is stored in the the PeptideEvidence object: see ftp://ftp.math.fu-berlin.de/pub/OpenMS/develop-documentation/html/classOpenMS_1_1PeptideEvidence.html
as part of a PeptideHit.

Here are some pointers to the documentation to give you a head start:
How to register parameters (for example a new input file) of a tool:
ftp://ftp.math.fu-berlin.de/pub/OpenMS/develop-documentation/html/classOpenMS_1_1TOPPBase.html

And how to load the sequence database:
ftp://ftp.math.fu-berlin.de/pub/OpenMS/develop-documentation/html/classOpenMS_1_1FASTAFile.html

Feel free to ask any questions! Some of us might also on https://gitter.im/OpenMS/OpenMS if you want to directly chat with other developers.

**Comment by pati-ni** [comment]
Take a look on this patch:
https://github.com/pati-ni/OpenMS/commit/a67e7bc17e19080acc076310569e22fa1675c9f2

There are some issues:
-   Handling unknown values in PeptideEvidence.
-   Handling PeptideEvidences with accessions that are not present in the fasta file.
-   Setting a range of missed cleavages. How this is supposed to happen?
-   Reading values from SearchParameters. I do not understand fully what they represent.

**Comment by timosachsenberg** [comment]
Hi @pati-ni,
the patch looks nice *thumbs up*. I guess there is not much to do except some minor changes and maybe adding tests.

- Handling unknown values in PeptideEvidence
I think we can assume that we have a proper mapping to the protein. So we can rely on the start and end position of the peptide in the protein. But if these are UNKNOWN we can't do more than letting the PE pass and put out a warning on LOG_WARN.

- Handling PeptideEvidences with accessions that are not present in the fasta file.
I think letting the PE pass but outputing a warning on the LOG_WARN  stream is the proper way to handle this.

- Setting a range of missed cleavages. How this is supposed to happen?

EnzymaticDigestion allows to specify the maximum number of missed cleavages but apparently, isValidProduct doesn't consider it, yet. So maybe it should consider it. In https://github.com/OpenMS/OpenMS/blob/6eea3f2ba995293dde1aa676771b50381ded02d6/src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp#L163 you have all positions where the enzyme cuts (without missed cleavages). So you can just count how many of these positions fall between pep_pos and  pep_pos + pep_length (that is, how many have been missed). If this number is equal or smaller than missed_cleavages_ it's a valid product.

- I think you don't need to handle the SearchParameters

**Comment by pati-ni** [comment]
Hi @timosachsenberg,
Any hints on the input-output files I should use for adding tests?
I will try to tackle the missed_cleavages issue and add an input parameter as well.

> I think we can assume that we have a proper mapping to the protein. So we can rely on the start and end position of the peptide in the protein. But if these are UNKNOWN we can't do more than letting the PE pass and put out a warning on LOG_WARN.

Sounds like plan. Same goes for N_TERMINAL_POSITION as well?

**Comment by timosachsenberg** [comment]
Yeah I guess only the start and end are relevant.

To extend the test of the IDFilter tool in ./src/tests/topp/CMakeLists.txt
you could use the ./src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML and the proteins.fasta file in that folder.
As these are tests for external tools you should copy and rename them to the folder where the IDFilter test files are. Probably to something like: IDFilter_XX_in.fasta and IDFilter_XX_in.idXML where XX is the number of the new test (I did not look it up in the ./src/tests/topp/CMakeLists.txt file).

**Comment by pati-ni** [comment]
@timosachsenberg have a look: https://github.com/pati-ni/OpenMS/commit/a9818474dd1a736e41807926b62b2560ff262898

But now it can not ignore missed_cleavages as it did before. Should I add a default parameter like 
'ignore_missed_cleavages' to do so?

**Comment by timosachsenberg** [comment]
Maybe we can go without an additional parameter. For the tool, one could use -1 to allow users to disable the check for missed cleavages. Internally, the tool could the set the missed cleavage parameter of the EnzymaticDigestion class to e.g., INT_MAX.

**Comment by pati-ni** [comment]
Currently the constructor sets the missed_cleavages to 0 maybe that could break the other digestion functions that use missed_cleavages or other calls of isValidProduct?

**Comment by timosachsenberg** [comment]
That's a good point and one might need to check if this interferes with how other classes used isValidProduct. If there are any, one needs to adapt them. 

I think setting it to 0 in the constructor of EnzymaticDigestion is correct because you might want to perform a digest without missed cleavages as default. The IDFilter tool is a different story. Here you would impose no restrictions on the number of missed cleavages as default and, thus, would need to **set** it to a large value before you call isValidProduct on it.

**Comment by pati-ni** [comment]
Currently isValidProduct looks like this
`EnzymaticDigestion::isValidProduct(const AASequence& protein, Size pep_pos, Size pep_length, bool methionine_cleavage = false)`
The less messy solution from the way I see it is to add an Optional parameter:
`EnzymaticDigestion::isValidProduct(const AASequence& protein, Size pep_pos, Size pep_length, bool methionine_cleavage = false, bool ignore_missed_cleavages = true)`
and return the result transparently without breaking the current API or altering the functionality.
This way passing values like INT_MAX would not be necessary.

**Comment by timosachsenberg** [comment]
sounds good

**Comment by hendrikweisser** [comment]
Looks like this was solved by #2523 (thanks @pati-ni!), so I'm going to close the issue.
