### ISSUE TITLE
FileFilter: remove redundant (nearly identical) features

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2005]
Feature request:
After merging featureXML from e.g. several feature finding runs we might end up with overlapping (nearly identical) features.
There should be an easy way to remove these.

Idea:
- run a feature linker on the original featureXMLs and generate a consensusXML
- extend FileFilter to keep / remove all features that have ids present in at least one consensus feature

**Comment by hendrikweisser** [comment]
I don't understand the use case for this. How is this not covered by FeatureLinkerUnlabeled(QT) already?

**Comment by timosachsenberg** [comment]
I guess you are right. I can link and then convert back to the featureXML. One disadvantage is that I will loose potential meta information

**Comment by timosachsenberg** [comment]
What I ideally would like to get is a merged featureXML that only contains non-redundant features

**Comment by hendrikweisser** [comment]
> What I ideally would like to get is a merged featureXML that only contains non-redundant features

But what you consider as "non-redundant" is not unambiguous, so I think you can't really avoid defining tolerances and running a feature linker.

I agree that consensusXML potentially losing information is a problem. That's an area where improvements should be made. (Perhaps using mzQuantML would help?)

**Comment by timosachsenberg** [comment]
We have some resolution code for overlapping features in FeatureFinderCentroided. Basically, this is what I would like to use in FileFilter. Maybe it can be easily factored out.
