### ISSUE TITLE
missing PSMs in prot.xml to idXML conversion using IDFileConverter

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#2011]
This [1]  `interact.prot.xml` from TPP was converted to `idXML` using `IDFileConverter`. The `idXML` contains 7,800 protein hits, 28,904 peptide hits but only one matched spectrum (= PSM).

[1] https://gist.github.com/lars20070/5b70cbee5986a86ab5811c66db3cb865
[2] https://gist.github.com/lars20070/da16ddee51c271292db1a48f098dc7ce

**Comment by mwalzer** [comment]
does running it with -debug >100 turn up more information?

**Comment by hroest** [comment]
@lars20070 can we close this?
