### ISSUE TITLE
KNIME trunk/develop uses wrong OpenMS_DATA_PATH

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#2014]
For the tutorial QC section, we require an update to the development version of OpenMS via http://tech.knime.org/update/community-contributions/trunk
However, this sets the OPENMS_DATA_PATH wrong, causing (all?) OpenMS nodes to not work anymore (failing when executing). Example for OMSSAAdapter:

ERROR OMSSAAdapter         0:3        Failing process stderr: [OpenMS FATAL ERROR!,   Cannot find shared data! OpenMS cannot function without it!,   The environment variable 'OPENMS_DATA_PATH' currently points to 'C:/dev/KNIME_PACKAGE/trunk/OpenMS/share/OpenMS', which is incorrect!,   To resolve this, set the environment variable 'OPENMS_DATA_PATH' to the OpenMS share directory (e.g., 'c:\Program Files\OpenMS\share\OpenMS')., Exiting now.]

(From the system side, the OPENMS_DATA_PATH is set to a working OpenMS instance, but I guess that KNIME sets it dynamically?)

Also see https://github.com/OpenMS/Tutorials/issues/37

**Comment by jpfeuffer** [comment]
Can we narrow this down to a Windows problem? Did you experience it on any other platform?

**Comment by FabianAicheler** [comment]
I did not test it on any other platform.

**Comment by julianu** [comment]
I just encountered this problem with the KNIME nodes for FeatureFinderMultiplex, FeatureFinderCentroided and some more randomly tested nodes. As I guess it is a general setting thing for the windows nodes, it actually makes all node unusable.
That is for windows 64bit, the same versions run fine under linux.

The error message is:
`Failing process stderr: [OpenMS FATAL ERROR!,   Cannot find shared data! OpenMS cannot function without it!,   The environment variable 'OPENMS_DATA_PATH' currently points to 'C:/dev/KNIME_PACKAGE/trunk/OpenMS/share/OpenMS', which is incorrect!,   To resolve this, set the environment variable 'OPENMS_DATA_PATH' to the OpenMS share directory (e.g., 'c:\Program Files\OpenMS\share\OpenMS')., Exiting now.]`

**Comment by julianu** [comment]
I just checked the OPENMS_DATA_PATH in the payload/binaries.ini file from GKN, but it seems to be set correctly there like this:
`OPENMS_DATA_PATH=$ROOT\\share\\OpenMS\\`

**Comment by jpfeuffer** [comment]
Weird. Works for me. Tested basic peptide ID with OMSSA (which failed for @FabianAicheler )
Installed fresh KNIME 3.1.2 core -> Installed stable plugin (works) -> Update with trunk (works)

I do not have OpenMS or any other KNIME version installed which might interfere.
It could be the changes @timosachsenberg made for having multiple installations of OpenMS but I am not sure (it affected more the OpenMS_home_path, not the OpenMS_data_path).

**Comment by jpfeuffer** [comment]
Or KNIME got confused by too many switches. Can you try a reinstall? Workspaces will be saved anyways.

**Comment by julianu** [comment]
In the installation I tested, there was also a stand-alone installation of OpenMS 2.0 and several updates performed in KNIME. Will try a clean installation next week and report back.

**Comment by julianu** [comment]
Just reinstalling KNIME (with all contributions) and then upgrading to the OpenMS nightlies was not sufficient. I had to uninstall the competing OpenMS 2.0.0 installation, which is actually sad, as I have no TOPPView on the machine now...
And still, the error message is a bit weird, as I obviously had neither the windows user variable `OPENMS_DATA_PATH` set to be `C:/dev/KNIME_PACKAGE/trunk/OpenMS/share/OpenMS`, nor did the actual dev-path exist.
The stable nodes, which automatically installed with KNIME, had no problem, regardless of any other installations on the system.

**Comment by jpfeuffer** [comment]
Aha! But that helps a lot. I bet it was @timosachsenberg s changes to actually "support" multiple installations then. We will look into it ASAP.

**Comment by timosachsenberg** [comment]
I think the relevant PR would be https://github.com/OpenMS/OpenMS/pull/1686

**Comment by timosachsenberg** [comment]
related https://github.com/OpenMS/OpenMS/pull/1689/files

**Comment by timosachsenberg** [comment]
The environment variable needs to be set:
```
    bool from_env(false);
    if (getenv("OPENMS_DATA_PATH") != 0)
    {
      path = getenv("OPENMS_DATA_PATH");
      from_env = true;
      path_checked = isOpenMSDataPath_(path);
    }
```
otherwise the error message is not produced:
```
 if (!path_checked) // - now we're in big trouble as './share' is not were its supposed to be...
    { // - do NOT use LOG_ERROR or similar for the messages below! (it might not even usable at this point)
      std::cerr << "OpenMS FATAL ERROR!\n  Cannot find shared data! OpenMS cannot function without it!\n";
      if (from_env)
      {
        std::cerr << "  The environment variable 'OPENMS_DATA_PATH' currently points to '" << path << "', which is incorrect!\n";
      }
#ifdef OPENMS_WINDOWSPLATFORM
      String share_dir = "c:\\Program Files\\OpenMS\\share\\OpenMS";
#else
      String share_dir = "/usr/share/OpenMS";
#endif
      std::cerr << "  To resolve this, set the environment variable 'OPENMS_DATA_PATH' to the OpenMS share directory (e.g., '" + share_dir + "').\n";
      std::cerr << "Exiting now.\n";
      exit(1);
    }
```

**Comment by timosachsenberg** [comment]
here is also the relevant check:
```
  bool File::isOpenMSDataPath_(const String& path)
  {
    return exists(path + "/CHEMISTRY/Elements.xml");
  }
```

**Comment by timosachsenberg** [comment]
My guess is, that the variable is set to something (from_env=true). The check fails and the fallback takes the path that has been compiled into it.

**Comment by timosachsenberg** [comment]
by the way: I think the output from
```
      if (from_env)
      {
        std::cerr << "  The environment variable 'OPENMS_DATA_PATH' currently points to '" << path << "', which is incorrect!\n";
      }
`´`
is wrong as the fallbacks might have already overwritten "path"

**Comment by timosachsenberg** [comment]
might be fixed with: https://github.com/genericworkflownodes/GenericKnimeNodes/pull/135

**Comment by timosachsenberg** [comment]
seemed to work on user meeting ;)
