### ISSUE TITLE
Error in pepXML parsing and IDFileConverter test

### ISSUE THREAD

**Issue by enetz** [OpenMS/OpenMS#2015]
One of the tests for the IDFileConverter expects a behaviour, that does not make sense.
In the list of fixed modifications each modification should appear only once, but one idXML file converted from pepXML in the tests contains the same modification and site twice (this is in the expected result of the test):

In "IDFileConverter_10_output.idXML":
                FixedModification name="Dimethyl:2H(4)13C(2) (K)"
                FixedModification name="Dimethyl:2H(4)13C(2) (K)"

The pepXML contains this line with the same modification at "K" and "[" (N-term):
parameter name="residue, modification mass" value="57.021464@C,34.063117@[,34.063117@K"

After updating the unimod.xml a new site "R" was added for this modification and a test failed, when in the idXML output the second site was written as (R) instead of (K), which are both incorrect ( #1993 ).
The N-term modification site is not written and very likely the first site defined in the unimod.xml is written instead (the order in the old file was "K" then "N-term", in the new file "R" then "K" then "N-Term"). The unimod.xml file causing this failed test is attached.

[unimod_parsing_issue.xml.zip](https://github.com/OpenMS/OpenMS/files/304472/unimod_parsing_issue.xml.zip)

**Comment by mwalzer** [comment]
@enetz can you please reference the specific test (you can get a line link from browser/desktop github)

**Comment by enetz** [comment]
here is the failed test: https://travis-ci.org/OpenMS/OpenMS/builds/131732995

**Comment by hroest** [comment]
@enetz is this still an issue?

**Comment by enetz** [comment]
No, this should be solved now. Was discussed in #1993 and the updated unimod.xml was later merged as #2338 .
Since the updated unimod.xml does not cause this problem right now, this issue should be solved.
