### ISSUE TITLE
FeatureFinderMetabo performs isotopic deconvolution incorrectly

### ISSUE THREAD

**Issue by iprotsyuk** [OpenMS/OpenMS#2016]
Often, FFM doesn't merge mass traces of low-medium intensity into features. As discussed privately with @mrurik the problem lies in the strict matching of mass traces with isotopic model that allows 3 or 5% deviation. @mrurik proposed two possible ways of fixing it:

1. option to disable matching with isotopic model
2. option to use a new model with 10% error

**Comment by FabianAicheler** [comment]
Hi, I think in relation to issue https://github.com/OpenMS/OpenMS/issues/2053 , @timosachsenberg looked at the grouping behaviour and there the traces were not grouped at all?

In the case that by incorrect grouping you mean that traces are not grouped _att all_, we think that this is probably less related to the isotopic model and more with considered trace spacings.

I think @cbielow introduced some changes to the considered spacings in his branch. Chris, are these changes included in your current pull requests concerning FeatureFinderMetabo?

**Comment by iprotsyuk** [comment]
@FabianAicheler, grouping is performed correctly, but only for high-intensity features. Most mass traces are reported separately though some of them are definitely isotopic peaks of the same molecule.
