### ISSUE TITLE
Dimethyl modifications not correctly reported in MzTabExporter output

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#2017]
Dimethyl modifications are not reported in the `modifications` column of the `PEP` section of `mzTab` written by `MzTabExporter`. See the following two examples generated from [this](https://gist.github.com/lars20070/e3ab4acd2272801b0533ca4dae22ad1c) `consensusXML`.
```
opt_global_modified_sequence = (Dimethyl:2H(6)13C(2))C(Carbamidomethyl)EEFLPR
modifications = 1-UniMod:4
``` 

```
opt_global_modified_sequence = (Dimethyl)STPPSAYGSVK(Dimethyl)AYTNFDAER
modifications = null
```

**Comment by timosachsenberg** [comment]
according to the standard:
```
Reporting of modifications in columns of the protein, peptide and PSM sections:
Fixed modifications or modifications specified as quantification_modification in the metadata
Section SHOULD NOT be reported in protein (PRT) and peptide rows (PEP). In contrast, all
variable modifications plus fixed modifications like those induced by the quantification
reagents MUST be reported in peptide spectrum match rows (PSM).
```

There seems to be an additional issue with your file:
```
			<FixedModification name="Carbamidomethyl (C)" />
			<FixedModification name="Dimethyl" />
			<FixedModification name="Dimethyl (K)" />
			<FixedModification name="Dimethyl:2H(4)" />
			<FixedModification name="Dimethyl:2H(4) (K)" />
			<FixedModification name="Dimethyl:2H(6)13C(2)" />
			<FixedModification name="Dimethyl:2H(6)13C(2) (K)" />
```
The line <FixedModification name="Dimethyl" /> doesn't look correct to me as well as
			<FixedModification name="Dimethyl:2H(4)" /> and 			<FixedModification name="Dimethyl:2H(6)13C(2)" /> as no specificity or origin is provided.

**Comment by lars20070** [comment]
The `MzTabExporter` output does comply with the `mzTab` standard.

The incorrect mods will be addressed in #2087.

**Comment by lars20070** [comment]
But out of interest: Why no fixed mods in the `PEP` section?

**Comment by timosachsenberg** [comment]
I think for better readability
