### ISSUE TITLE
pyOpenMS: no interface to access individual features in ConsensusFeature

### ISSUE THREAD

**Issue by iprotsyuk** [OpenMS/OpenMS#2028]
Cpp class ConsensusFeature contains getFeatures() method that returns list of feature handlers. However, the method is absent in pyOpenMS. Maybe there's a non-trivial way to get features, but I didn't manage to find it.

**Comment by hroest** [comment]
Thanks for your report, this has been fixed in #1660 in pyOpenMS and should be contained in release 2.0.1

we have not yet updated the binaries for pyOpenMS but you could compile release 2.0.1 yourself. We are working on the binaries for pyOpenMS at the moment.

**Comment by iprotsyuk** [comment]
It's not very urgent for me, I'll wait for the release.

**Comment by hroest** [comment]
@iprotsyuk this is now available through PyPI https://pypi.python.org/pypi/pyopenms/

**Comment by iprotsyuk** [comment]
👍
