### ISSUE TITLE
OpenMS assumes only positive ion mode in targeted mode

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2036]
This issue needs to be addressed after merging #2032 

In targeted mode, especially regarding the TargetedExperiment, OpenMS often assumes that only positive charge states are valid. Other times, the code does not check whether a valid charge state was ever set. `MRMIonSeries::annotateTransition` is one such example, but also the `TheoreticalSpectrumGenerator` and `AASequence::getMonoWeight` others should be checked how they behave with zero or negative charge.

There are several issues with the charge states right now:
1. a negative charge state is used to indicate absence of information. This is flawed as in negative ionization mode, negative charge states occur often
2. it seems that MRMIonSeries::annotateTransition will annotate transitions without checking whether the charge state is valid. This means that the charge state may be arbitrary (hopefully not zero) but potentially -1: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/ANALYSIS/TARGETED/TargetedExperimentHelper.h#L453
3. We should add a precondition, as I did here to check for valid charge states: 481f9ae6d787ab0d73c8fd0e9ab0518a8b8bed99
4. the calculation of `getMonoWeight(peptide, charge) / charge` does not consider the fact that the charge may be negative. We should consider this in  `getMonoWeight` and also divide by `fabs(charge) otherwise we get a negative

**Comment by hendrikweisser** [comment]
> 1. a negative charge state is used to indicate absence of information. This is flawed as in negative ionization mode, negative charge states occur often

Could we use zero to indicate missing, as we wouldn't be able to observe uncharged species?

> 4. the calculation of getMonoWeight(peptide, charge) / charge does not consider the fact that the charge may be negative. We should consider this in getMonoWeight and also divide by `fabs(charge) otherwise we get a negative

Could we add a convenience function for this? It seems like a simple calculation, but - as you point out - there are subtle sources for errors there. It's certainly used all over the place.
