### ISSUE TITLE
Incremental linking on Windows

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2038]
It seems that in 112221ce92c18b8dc2b1cfbc0832b645ba0652b9 and in c21fb241fdc9ffbc933f2ab8791ceb8d2e85d997 we disabled incremental linking for MSVS for the GUI library but not for OpenMS itself. I ran into some issues with 32bit MSVS 2008 which basically asked me to disable incremental linking:

```
Visual Studio Incremental Link with embedded manifests
Create ..\..\bin\OpenMSd.dll.resource.txt
RC Pass 1:
C:/Program Files/Microsoft SDKs/Windows/v6.0A/bin/RC.Exe /fo..\..\bin\OpenMSd.d
l.embed.manifest.res ..\..\bin\OpenMSd.dll.resource.txt
LINK Pass 1:
C:\PROGRA~1\MICROS~1.0\VC\bin\link.exe /nologo @CMakeFiles\OpenMS.dir\objects1.
sp /out:..\..\bin\OpenMSd.dll /implib:OpenMSd.lib /pdb:C:\openms\win32_openmsbu
ld11\bin\OpenMSd.pdb /dll /version:0.0 /machine:X86 /debug /INCREMENTAL:YES ..\
penswathalgo\OpenSwathAlgod.lib C:\Qt\4.8.4\lib\QtNetworkd4.lib C:\Qt\4.8.4\lib
QtCored4.lib C:\openms\win32_contrib_build6\lib\libsvmd.lib C:\openms\win32_con
rib_build6\lib\xerces-c_3D.lib C:\openms\win32_contrib_build6\lib\xerces-c_3D.l
b C:\openms\win32_contrib_build6\lib\libboost_iostreams-mt-gd.lib C:\openms\win
2_contrib_build6\lib\libboost_date_time-mt-gd.lib C:\openms\win32_contrib_build
\lib\libboost_math_c99-mt-gd.lib C:\openms\win32_contrib_build6\lib\libboost_re
ex-mt-gd.lib C:\openms\win32_contrib_build6\lib\Wm5Cored.lib C:\openms\win32_co
trib_build6\lib\Wm5Mathematicsd.lib C:\openms\win32_contrib_build6\lib\libbz2d.
ib C:\openms\win32_contrib_build6\lib\zlibd.lib C:\openms\win32_contrib_build6\
ib\glpkd.lib C:\openms\win32_contrib_build6\lib\glpkd.lib opengl32.lib kernel32
lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.l
b comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:..\..\bin\OpenMSd.dll.inter
ediate.manifest ..\..\bin\OpenMSd.dll.embed.manifest.res
   Creating library OpenMSd.lib and object OpenMSd.exp
LINK : fatal error LNK1210: exceeded internal ILK size limit; link with /INCREM
NTAL:NO
LINK Pass 1 failed. with 1210
NMAKE : fatal error U1077: '"C:\Program Files\CMake 2.8\bin\cmake.exe"' : retur
 code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio 9.0\VC\BI
\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio 9.0\VC\BI
\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio 9.0\VC\BI
\nmake.exe"' : return code '0x2'
Stop.
C:\openms\win32_openmsbuild11>cd C:\openms\
```

why did we enable incremental linking for the OpenMS library but not for the GUI library?

**Comment by cbielow** [comment]
mhh.. its been 5 years, but incremental linking has (usually) advantages in linking time -- but uses more RAM. This is useful when working with large libs (OpenMS main lib) and in debug mode.
The GUI lib was not that big, so I think the difference was not that big but there is no real reason to switch it off.

I think there is multiple ways to solve the linking problem, e.g. use a 64 bit linker (also works for 32bit code if I#m not mistaken; not sure what happens on 32bit OS's.), see https://blogs.msdn.microsoft.com/vcblog/2013/10/29/the-visual-c-linker-best-practices-developer-iteration/.

Maybe also freeing more before linking RAM helps on 32bit systems (not sure, but worth a try).

**Comment by hroest** [comment]
still some 32 bit windows systems have a lot of trouble when it is turned on; especially when these are VMs with relatively little memory

I suggest to use a global cmake flag for incremental linking and turn it on/off for all linking, making this a cleaner solution, see #2041

**Comment by cbielow** [comment]
How much VM RAM are we talking about?! Is 4GB such a big deal these days? Especially for a build machine?

I don't really like mirroring VS flags in the build system, but it seems there is no other way since its impossible to pass linker flags using the nmake call itself (other than editing the makefile, which seems inconvenient).

another solution is to push splitting of the library into separate parts, making linking faster and less RAM hungry.

**Comment by hroest** [comment]
We could also add a generic cmake flag to set additional linker flags which
then get added to all linking cmds

sent from my smartphone -- you may keep any typos you find.

**Comment by hroest** [comment]
PS: we have about 3 GB of RAM 

Also, I am all for splitting the libraries, that would have some other benefits as well (clearer separation of tasks and better interfaces). We talked about it in Izmir, not sure whats the status of that right now

**Comment by cbielow** [comment]
#3777 solves the same issue on X64 target builds (which by default use x32 toolchains).
This might also be an option here if a x64 development machine is available for cross-compilation.
The other option is to disable incremental linking as discussed.
Will close this issue for now.
Openning another issue for fine-grained sublibraries might be worthwhile though.
