### ISSUE TITLE
build systems aborts on windows, trying to copy files 

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2043]
When compiling OpenMS on windows (MSVS 2008, nmake, 32bit), every time a library is linked the first time, the following error occurs

```
$ nmake Makefile OpenMS
[...]
[  2%] Building CXX object src/openswathalgo/CMakeFiles/OpenSwathAlgo.dir/source
/ANALYSIS/OPENSWATH/OPENSWATHALGO/DATAACCESS/Transitions.cpp.obj
Transitions.cpp
Linking CXX shared library ..\..\bin\OpenSwathAlgod.dll
   Creating library OpenSwathAlgod.lib and object OpenSwathAlgod.exp
   Creating library OpenSwathAlgod.lib and object OpenSwathAlgod.exp
Error copying file "C:\openms\win32_openmsbuild11\bin\" to "C:\openms\win32_open
msbuild11\src\tests\class_tests\bin\\".
NMAKE : fatal error U1077: 'echo' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio 9.0\VC\BIN
\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio 9.0\VC\BIN
\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio 9.0\VC\BIN
\nmake.exe"' : return code '0x2'
Stop.
$ nmake Makefile OpenMS
[ ...  now it runs fine ... ]
```

when run the second time, it runs fine. This is annoying but means that nmake has to be run 3x to overcome this error in openswathalgo, openms and superhirn. 

It seems that the build system wants to copy some dlls which it cannot find and then aborts.

**Comment by cbielow** [comment]
the problem here is again that nmake is not supported by our build system, i.e. in ./cmake/add_library_macros.cmake
```
## @note This macro will do nothing with non MSVC generators.
macro(copy_dll_to_extern_bin targetname)
```

related to #2040

I think we should close this issue and introduce a check which does not allow nmake.
VS solution files + msbuild.exe is a proper (more powerful) alternative for the command line.
