### ISSUE TITLE
FeatureFinderMetabo skips high intensity peaks

### ISSUE THREAD

**Issue by iprotsyuk** [OpenMS/OpenMS#2053]
Sometimes it misses abundant peaks for no apparent reason, but detects peaks with lower intensity at the same time. I found that it depends on noise_threshold_int value: if I put it higher, the high intensity peaks are detected, but obviously, low ones are missing.

You can find a few examples here: [1](https://gist.github.com/iprotsyuk/3b2618d9bdb468fd4254ba81a281408d), [2](https://gist.github.com/iprotsyuk/62b1c8a0e471ae7e8d13cd5351e1d7ad), [3](https://gist.github.com/iprotsyuk/1bc92d96e43bc8c99cc087779399e121). They look a bit strange (only certain mz values are present) as it’s a simulated dataset. There’s a mass trace of mz 477.23 which gives the most intense chromatographic peak in all files. It gets detected by FeatureFinderMetabo if I set noise level to >= 40k, but it’s missing if I use lower values.

Maybe there are particular parameter values of the algorithm that can fix the issue?

**Comment by iprotsyuk** [comment]
Faced the same problem with [a real data](https://gist.github.com/iprotsyuk/2bc79c4475d6e4de6245bfed05c09d01). Here, an intense peak of caffeine (mz = 195.089, RT ~ 353 s) is missing if I set noise level value to 2500. However, it gets detected if the noise threshold is 10k.
PS: In all cases, I used chrom_peak_snr of 3.

**Comment by mwalzer** [comment]
@FabianAicheler @mrurik do you know something about this? Or maybe @cbielow?

**Comment by iprotsyuk** [comment]
I narrowed down a problem scope a little bit. It seems the issue is with the MassTraceExtractor tool which is called internally by FeatureFinderMetabo. I managed to reproduce the same behaviour with same parameter values and disabled elution profile filtering.

**Comment by timosachsenberg** [comment]
Hi I just ran the MassTraceExtractor using the default parameters (I only disabled width filtering) on one of the files and I seem to get a proper mass trace in the current OpenMS 2.0.1 version. 

![image](https://cloud.githubusercontent.com/assets/5803621/17203671/0c7ea06a-54a1-11e6-8446-21e4aea978a5.png)

**Comment by timosachsenberg** [comment]
same for the real data set using MassTraceExtractor and default settings
![image](https://cloud.githubusercontent.com/assets/5803621/17203796/c06484c8-54a1-11e6-8566-52998072b3f4.png)

**Comment by timosachsenberg** [comment]
Interestingly, in OpenMS 2.0 I get:
![image](https://cloud.githubusercontent.com/assets/5803621/17203870/37982784-54a2-11e6-8d57-58521a9ab4bb.png)

**Comment by timosachsenberg** [comment]
I think the problem is the (advanced) max_trace_length parameter that is 300 s by default in OpenMS 2.0 but in OpenMS 2.0.1 it has been disabled by default.

**Comment by timosachsenberg** [comment]
Yep, if I enter a very large value in OpenMS 2.0 (disabling it by entering -1 is not supported in 2.0) I also get the mass trace

**Comment by timosachsenberg** [comment]
So it seems this problem is solved in the newest version.

**Comment by iprotsyuk** [comment]
@timosachsenberg it seems it was my fault all along. I forgot about the upper limit on a mass trace length. Everything works fine with the previous version of OpenMS as well.
Thank you so much!

**Comment by timosachsenberg** [comment]
No problem at all and thanks for reporting. This also highlighted that there is room for improvement - both in documentation as well as e.g. automatic choice of these parameters.
By the way, the maximum mass trace parameter was originally introduced to remove contaminants that elute e.g. over the full run. In hindsight, this simple solution is not sufficient for all cases.
