### ISSUE TITLE
Add new OpenMS 2.0 paper to citable papers

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2063]
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp
- src/openms_gui/source/VISUAL/APPLICATIONS/IDEvaluationBase.cpp

as soon as we move forward with the publication  and get a citeable document

**Comment by cbielow** [comment]
this is the paper: http://www.nature.com/nmeth/journal/v13/n9/full/nmeth.3959.html

**Comment by hroest** [comment]
we could extend the current text by:

```
"Any published work based on TOPP and OpenMS shall cite these papers:<BR>"
"Sturm et al., BMC Bioinformatics (2008), 9, 163<BR>"
"Kohlbacher et al., Bioinformatics (2007), 23:e191-e197<BR>"
"Röst et al., Nature Methods (2016), 13, 741–748<BR>"
```

however, it seems that making users cite 3 papers is a bit much. Please discuss what the preferred way of citing OpenMS is in the future.

**Comment by timosachsenberg** [comment]
isn't it done on master?

**Comment by cbielow** [comment]
IMHO If the new version is used,  the new paper should be cited.
-- 
Sent via mobile phone.

Am 28. September 2016 18:06:19 MESZ, schrieb Hannes Roest <notifications@github.com>:

**Comment by hroest** [comment]
so lets just add it/replace the others for all 2.x versions, e.g. the new 2.1 and following

**Comment by hendrikweisser** [comment]
I'm also in favour of using only the new paper.

**Comment by timosachsenberg** [comment]
I just checked and I already replaced it in the new version
