### ISSUE TITLE
Error message for not finding QT on Windows.

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2065]
Somehow CMake is not reporting a failure but only an empty version when it is not finding QT.
Therefore it does not use our error message here:
https://github.com/OpenMS/OpenMS/blob/2b03d85522fcb23865eb5fceaabd8e83996dd961/src/openms/cmake_findExternalLibs.cmake#L152

The following is all I get on the console:

```
CMake Error at C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/FindQt4.cmake:1386 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  src/openms/cmake_findExternalLibs.cmake:148 (find_package)
  src/openms/CMakeLists.txt:63 (include)
```

I actually had to search the code on how the flag to set an own QT version is called, it is also not in the windows build docs.

**Comment by cbielow** [comment]
it seems that findPackage() fails, so I dont see what we can do about it (other than shipping our own findQT4 ahhhgg).
