### ISSUE TITLE
Windows 10?

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2072]
do we support Windows 10? currently our README.md says only Windows [XP, 7, 8] but I assume that OpenMS works as well under Windows 10?

**Comment by jpfeuffer** [comment]
We have a new build server with Win10. We will definitely support it after I made some tests. I don't expect much trouble (but you never know)

**Comment by hroest** [comment]
I think the point is not even to *build* it on Win 10 but simply whether the binaries *run* on Win 10 (e.g. this is in the README.md here https://github.com/OpenMS/OpenMS). I think they should run, right? so should we just add Win10 as a supported platform?

**Comment by jpfeuffer** [comment]
Most probably, yes.

**Comment by cbielow** [comment]
I downloaded the nightly installer -- it runs just fine on Win10.
Tried TOPPView and TOPPAS.
Cannot say anything about third-party tools though (e.g. MSGF+, XTandem etc).

**Comment by hroest** [comment]
Let's just claim we do/want to support Win10 and if issues do come up we
address them.

sent from my smartphone -- you may keep any typos you find.

**Comment by cbielow** [comment]
fixed in https://github.com/OpenMS/OpenMS/commit/c32a37660ed1885f44293f892f03bc434276e5b0
