### ISSUE TITLE
OS X and pyOpenMS tests

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2073]
what happened to the OS X and the pyOpenMS tests? It would be great to have those back!

**Comment by jpfeuffer** [comment]
OSX machine was not responding. They are already back up I think. http://cdash.openms.de/index.php?project=OpenMS&date=2016-07-26

**Comment by jpfeuffer** [comment]
Or do you mean the errors? I would need to do more investigation there. Solely pyopenms errors from what I saw.

**Comment by hroest** [comment]
yes, I can fix the pyopems errors
