### ISSUE TITLE
Metabolite spectral database file is missing from OpenMS KNIME extension

### ISSUE THREAD

**Issue by iprotsyuk** [OpenMS/OpenMS#2078]
MetaboliteSpectralMatcher always reports the following error message:

ERROR MetaboliteSpectralMatcher 0:388:394  Failing process stdout: [Progress of 'loading spectra list':, ,   59.62 %               , -- done [took 0.83 s (CPU), 0.82 s (Wall)] -- , Error: File not found (the file 'CHEMISTRY/MetaboliteSpectralDB.mzML' could not be found)]
ERROR MetaboliteSpectralMatcher 0:388:394  Failing process stderr: []
ERROR MetaboliteSpectralMatcher 0:388:394  Execute failed: Failed to execute node MetaboliteSpectralMatcher

Apparently, the file "CHEMISTRY/MetaboliteSpectralDB.mzML" is missing from the KNIME extension. After I downloaded from this repository and put to the OpenMS plugin folder, everything worked well.

**Comment by timosachsenberg** [comment]
Hi,
the file is rather large so we have - so far - restrained from including it in the release.

**Comment by iprotsyuk** [comment]
Hi Timo,
In this case, I'd suggest adding an additional parameter to the node: path to a file with a spectral library. The link to the missing HMDB library can be added in the node documentation so users can download it.
This apporach would also allow one to use their custom spectral library as it's fairly easy to combine a set of MS/MS spectra into an mzML file.

**Comment by hroest** [comment]
I agree, I never liked the approach with the spectral db. We also do not ship out fasta files of different organisms in the `./share/OpenMS` folder. It should be the users responsibility to download these files and of course we could put them in a convenient location -- also note that giving a PATH would make it easier to add your own metabolites / update the file.

**Comment by timosachsenberg** [comment]
adding a path  would be a good addition.
In the future, we could also think about a simple util that - on execution - pulls extra files from the internet.

**Comment by timosachsenberg** [comment]
Adding the path should now be possible with this PR: https://github.com/OpenMS/OpenMS/pull/2526

**Comment by hendrikweisser** [comment]
Fixed in #2526.

**Comment by bernt-matthias** [comment]
Just stumbled over this again, since the default value of the `-database`  refers to a non-existent file. Would make more sense to have a mandatory argument without a default?

@iprotsyuk 

> After I downloaded from this repository and put to the OpenMS plugin folder, everything worked well.

What do you mean with "this repository"? I could not find anything here.

**Comment by iprotsyuk** [comment]
@bernt-matthias unfortunately can't remember what I meant back then, and also can't find anything remotely similar to "MetaboliteSpectralDB.mzML" in this repo ¯\_(ツ)_/¯

**Comment by oliveralka** [comment]
If someone is looking for it again, the file should be available in the "Example_Data":
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Data/latest/Example_Data/Metabolomics/databases/
