### ISSUE TITLE
AASequence: parsing prefers C-terminal mod. over residue mod.

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2085]
When parsing amino acid sequences with modifications using `AASequence::fromString`, there may be ambiguities in the interpretation of a mod. at the end of the sequence: Is it a mod. of the last residue or of the C-terminus? (See also #1792.)
OpenMS currently prefers the second interpretation, i.e. it will attribute a mod. to the C-terminus if there is a possible C-term specificity. I believe this choice is suboptimal; it would be better to attribute the mod. to the residue, if the residue can accept that mod., as this seems the more likely scenario.

Furthermore, OpenMS currently doesn't check whether there is a matching residue specificity for a C-terminal mod. For example, in the peptide sequence "PEPM(Oxidation)", the "Oxidation" will be considered as C-terminal, but the only matching mod. is "Oxidation (C-term G)", which doesn't match the "M" in the sequence. Nevertheless, this mod. is assigned, as revealed by `ResidueModification::getFullId`.

**Comment by hendrikweisser** [comment]
Can somebody clarify something for me, please: If I have a modification that is C-term- and residue-specific, like "Oxidation (C-term G)" or "Arg-loss (C-term R)", should I attach it to the last residue or to the C-terminus of the peptide (in AASequence)?

**Comment by timosachsenberg** [comment]
As I understood it, the whole distinction is made by different tools to e.g. allow terminal labels (e.g. as fixed modification) and additional variable modifications at the last amino acid. So I would say the amino acid should be at the terminus whenever it is a C- or N-term modification (regardless if an origin or not is specified).

**Comment by hendrikweisser** [comment]
@timosachsenberg: Based on your comment I've made changes in #2097 to handle this more consistently. Modifications with C- or N-term specificity (including with residue specificity, e.g. "Oxidation (C-term G)") can now only apply to peptide termini. It is not possible any more to set such a modification directly on a residue.

**Comment by timosachsenberg** [comment]
cool. I think this is the correct way to handle this.
One thing I really dislike with our design is that exceptions need to be used ... - but well this is another issue

**Comment by hendrikweisser** [comment]
> One thing I really dislike with our design is that exceptions need to be used ... - but well this is another issue

Agreed, especially since different exceptions are used for pretty much the same case of "X not found" (in ModificationsDB and ResidueDB: ElementNotFound, InvalidValue, IllegalArgument).

I didn't get rid of this in my changes, but at least it should be better documented now.
