### ISSUE TITLE
MSGFPlusAdapter: modifications incorrect

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#2087]
The modifications in the MS-GF+ search result are not correctly written to the `idXML` output.

See also #2010 and #2017.

**Comment by lars20070** [comment]
Might be an `mzIdentML` import bug. Probably introduced with #1679.

**Comment by timosachsenberg** [comment]
some more details?

**Comment by timosachsenberg** [comment]
@lars20070 can you provide some more details i.e. a mzIdentML that is wrongly converted.

**Comment by lars20070** [comment]
I see no further problems with mods in the MS-GF+ adapter results.
