### ISSUE TITLE
Update MSGFPlus for OpenMS 2.1

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2092]
current version: v2016.06.29, released June 29, 2016
available at: https://omics.pnl.gov/software/ms-gf
source code available at: https://github.com/sangtaekim/msgfplus

**Comment by timosachsenberg** [comment]
@hendrikweisser can you take a look at this version of MSGFPlus? You know the internals best and it might be a good idea to update the version we ship to the newest one.
See also the changelog: https://raw.githubusercontent.com/sangtaekim/msgfplus/22dac9b7563c61bd40159105809937d9045ad045/doc/Changelog.html
Which indicates some nice fixes (i.e. retention times are now stored in the mzID)

**Comment by hendrikweisser** [comment]
@timosachsenberg: Cool, I wasn't aware that newer version of MS-GF+ were available, so thanks for pointing that out.

Unfortunately I'm really busy at the moment and will be on holiday next week, so it may be better if someone else could test if the new version works with our adapter. Should be simple enough.

**Comment by timosachsenberg** [comment]
for now I downloaded it and put it into the OpenMS/THIRDPARTY

**Comment by timosachsenberg** [comment]
```
MS-GF+ ChangeLog
Added by Sangtae Kim, last edited by Sangtae Kim on Jul 16, 2014
MS-GF+ Documentation home
06/29/2016 v20160629

Clean up the mzid output a little, reducing file size (v20160615 introduced a change that resulted in larger mzid files)
Reduced the amount of unnecessary data in the .jar file, cutting size by ~1/2
06/15/2016 v20160615

Fix the mzid output when the modification is unknown to unimod. (cvRef now correctly references PSI-MS, and the value will be the name provided in the Mods.txt file)
Update the unimod.obo to date 2016:02:01, and change code to parse it properly after updating
Bump some dependencies to a newer version, and change code to properly work with those changes.
05/25/2016 v20160525

Output the residue letter and mass of any custom amino acids to the "MassTable" portion of the mzid.
Update the URIs for the ontologies to their current locations (psi-ms.obo and unit.obo).
02/12/2016 v20160212

Ensure that ETciD and EThcD are handled as ETD when using a _dta.txt file with a _ScanType.txt file
01/29/2016 v20160129

Added ability to enter custom amino acids using the Mods.txt file.
01/21/2016 v20160121

Changed the versioning system - SVN revisions don't work for Git repositories. Now commit date is used for the version.
Improve the overall progress reporting.
Cause entire search to fail if a thread exits with a failure.
Retention Time/Scan Start Time is now output to the mzid file for searches performed on mzML files, as long as the data is available.
```

**Comment by lars20070** [comment]
Important changes in MS-GF+. - Let's see if user-defined mods (which are consequently not in UniMod and `unimod.obo`) are correctly searched and parsed.

**Comment by timosachsenberg** [comment]
the new MSGFPlus version seems to work but we get a test error related to the scan time (MS:1000016) cv parameter now present in the mzIdentML.

See the generated idXML:
```

in1:  /home/travis/build/OpenMS/OpenMS/_build/src/tests/topp/MSGFPlusAdapter_1_out1.tmp   (line: 49, position/column: 4/26)
			<!
			 UserParam type="string" name="MS:1000016" value="4587.669"/>

in2:  /home/travis/build/OpenMS/OpenMS/src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML   (line: 49, position/column: 3/18)
		<!
		 /PeptideIdentification>
```
