### ISSUE TITLE
XTandemAdapter: change default output to mzid

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2098]
PILEDRIVER version now supports native mzid output

**Comment by hroest** [comment]
@timosachsenberg is this still an issue?

**Comment by timosachsenberg** [comment]
addressed with Hendriks rework of XTandemAdapter

**Comment by hendrikweisser** [comment]
Apparently mzid will not be supported by X! Tandem going forward. See here: https://github.com/OpenMS/OpenMS/issues/2406#issuecomment-279343474
