### ISSUE TITLE
use ModificationDefinitionSet from search engine settings

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2110]
to reduce ambiguities in Modification assignments (i.e. if a terminal mod. or a modification at the terminus was searched)

**Comment by hroest** [comment]
is this addressed by  #1970 ?

**Comment by timosachsenberg** [comment]
Only partially. 
Other types of ambiguities are several possible modifications if only a modification mass is given.

**Comment by hroest** [comment]
yes, in this case we should try and use the information which modifications were actually searched. sounds like a nice idea for an enhancements -- but how often is it a problem in practice? I have seen a few cases so far and mostly it seems to work. 

Also, then we have to hope the information is correct...

**Comment by hendrikweisser** [comment]
I've used that approach for X! Tandem in the recent update of XTandemAdapter. Implementation (via `ModificationDefintionsSet::findMatches`) is in XTandemXMLFile.
