### ISSUE TITLE
ModificationDB N-terminal mod not found by mono mass

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2115]
Only works if diff mono mass is used:

```
          mod_db->searchModificationsByDiffMonoMass(term_mods, mod_mass, tolerance, "",
                                                  ResidueModification::N_TERM);
```

Tried:
the mass of the modification and the mass of the modification + the N terminus (~1 H) as query.

**Comment by timosachsenberg** [comment]
also seems to be a problem with internal mods e.g. "PEPM[147]R" for M(Oxidation)

**Comment by hroest** [comment]
well that is why its called "ByDiffMonoMass" - it works just as it should!
