### ISSUE TITLE
MascotAdapterOnline does not use title setting (in KNIME)

### ISSUE THREAD

**Issue by julianu** [OpenMS/OpenMS#2117]
The current nightly version does no longer use the title setting. This might be related with #1627 , but that's only a guess, as the title now is always set to the file name.

I added a params.ini file, which creates a run with the name "QEXI13620" instead of the desired "titel".
- [params.ini.txt](https://github.com/OpenMS/OpenMS/files/422344/params.ini.txt)

**Comment by jpfeuffer** [comment]
I think you are right and I think it does not only affect KNIME. The title parameter should imo only be overwritten when it is not empty/default.

**Comment by timosachsenberg** [comment]
yep  its 'OpenMS_search' by default so we should check for this.
I can prepare a fix.
-Mascot_parameters:search_title <text>               Sets the title of the search. (default: 'OpenMS_search')

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/pull/2118

**Comment by hendrikweisser** [comment]
I think I overlooked that there was a parameter to set the title when I made the "use filename as title" change (#1627).

Thanks for the fix, Timo. But wouldn't it be better to have an empty default now, rather than "OpenMS_search" (since that value is never used as the actual title)?

**Comment by timosachsenberg** [comment]
yes we can do so - though I would not give it maximum priority before the release

**Comment by hendrikweisser** [comment]
Fixed in #2118.
