### ISSUE TITLE
MSGFPlus stores scan start time in minutes

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2127]
Reading mzids generated by current MSGFPlus have the wrong rt scaling as they use minutes instead of seconds.
see e.g. http://www.filedropper.com/rtmin

What is the best way to fix this?

**Comment by timosachsenberg** [comment]
@lars20070 I assigned this to Mathias as he probably knows best how to fix it.
Easiest might be to report it to the MSGFPlus guys and use a new version for the release...

**Comment by timosachsenberg** [comment]
as far as I can see they never specify the unit (but please double check) of scan start time

**Comment by lars20070** [comment]
Complete [1] and tiny [2] example.

[1] https://www.dropbox.com/sh/cm7gtt7eqd2lrhw/AABO7oq4TguoofpkaLBs4AEma
[2] https://www.dropbox.com/sh/bfyj6uuqq4epyar/AAA6l16OUjirNdNYLt-QhM8ia

**Comment by timosachsenberg** [comment]
should be fixed in https://github.com/OpenMS/OpenMS/pull/2134

**Comment by timosachsenberg** [comment]
I am a bit puzzled as:
```
           switchScores_(*pep_it);

+          pep_it->setRT(pep_it->getRT() * 60.0);
         }
```
fixes the problem but then old tests fail. 
```
1789: in1:  /nfs/wsi/abi/old-data/sachsenb/OpenMS_IDE/src/tests/topp/MSGFPlusAdapter_1_out1.tmp   (line: 35, position/column: 130/145)
1789:           <PeptideIdentification score_type="SpecEValue" higher_score_better="false" significance_threshold="0" MZ="1063.20983886719" RT="!
1789:                                                                                                                                           275260.14" spectrum_reference="spectrum=1" >
1789:
1789: in2:  /nfs/wsi/abi/old-data/sachsenb/OpenMS_IDE/src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML   (line: 35, position/column: 130/145)
1789:           <PeptideIdentification score_type="SpecEValue" higher_score_better="false" significance_threshold="0" MZ="1063.20983886719" RT="!
1789:                                                                                                                                           4587.6689453125" spectrum_reference="spectrum=1" >
1789:
```

Also - according to the documentation in msjava, the Rt should be seconds by default in MSGFPlus.
@hendrikweisser can you shed some light on this?

**Comment by hendrikweisser** [comment]
@timosachsenberg: The MSGFPlusAdapter looks up the RT values in the raw data (mzML), if they are not present in the search results. Do you apply the check and multiplication after that point?

**Comment by timosachsenberg** [comment]
I do it before.
My last change to the MzIdentML handler was to read the RT if entries are present (or in the case of MSGFPlus if "scan start time" is present).
Then I multiply them with 60.0 and only do the lookup if there are still some with missing (NaN) RTs.
In the THIRDPARTY test it works without the multiplication but the files Lars provided have RTs that look like minutes.
Did I overlook something obvious?
```
      else
      {
        vector<ProteinIdentification> protein_ids;
        vector<PeptideIdentification> peptide_ids;
        MzIdentMLFile().load(mzid_temp, protein_ids, peptide_ids);
        // set the MS-GF+ spectral e-value as new peptide identification score
        for (vector<PeptideIdentification>::iterator pep_it = peptide_ids.begin(); pep_it != peptide_ids.end(); ++pep_it)
        {
          switchScores_(*pep_it);

          // MSGFPlus doesn't store the unit (minutes) used for retention times. Convert it to the default (seconds).
          pep_it->setRT(pep_it->getRT() * 60.0);
        }
        SpectrumMetaDataLookup::addMissingRTsToPeptideIDs(peptide_ids, in, false);
        IdXMLFile().store(out, protein_ids, peptide_ids);
      }
```

**Comment by hendrikweisser** [comment]
In the "MSGFPlusAdapter_1" test, the mzid file produced by MS-GF+ ("MSGFPlusAdapter_1_out.mzid") contains "scan start time" CV params, but the values seems to be in seconds. Perhaps MS-GF+ just reads the entries from the mzML, but there different units are possible?

**Comment by hendrikweisser** [comment]
@lars20070: Can you check how the scan times appear in your mzML input file?

**Comment by lars20070** [comment]
Yes, it does. `90 * 60 = 5,700`

<img width="802" alt="screen shot 2016-08-23 at 14 57 58" src="https://cloud.githubusercontent.com/assets/6149805/17892525/0c2afe5a-6942-11e6-9727-29bbec8438d3.png">

**Comment by timosachsenberg** [comment]
in the text file. TOPPView does the correct Unit conversion but maybe not MSGF+

**Comment by hendrikweisser** [comment]
@lars20070: Can you look in the text of the actual mzML file for the RT values, please?

**Comment by lars20070** [comment]
Times in `mzML` in seconds. See for example
```
<cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="1500.021" unitAccession="UO:0000010" unitName="second" unitCvRef="UO" />
```

**Comment by hendrikweisser** [comment]
> Times in mzML in seconds.

This is puzzling. So MS-GF+ sometimes writes out seconds and sometimes minutes, even though the input is in seconds? That doesn't make sense.

**Comment by timosachsenberg** [comment]
strange... let's take a step back and create a minimal test case.
@lars20070 can you create a mzML that contains only one spectrum (FileFilter) that gets identified  by MSGFPlus (ideally with a fasta file that contains only one protein) and shows that behavior?

**Comment by lars20070** [comment]
Here a small 10 sec example. With the correct RT in seconds. Run on OS X. Current OpenMS developer version.
https://www.dropbox.com/sh/bfyj6uuqq4epyar/AAA6l16OUjirNdNYLt-QhM8ia
Hmm strange.

**Comment by timosachsenberg** [comment]
can you try to narrow down when the bug appears? Are you sure that the complete workflow used the same OpenMS and MSGFPlus version?

**Comment by timosachsenberg** [comment]
in principle filtering the mzML by OpenMS could result in an mzML that is compatible with MSGFPlus. I can't check it right now but did you directly feed in the msconvert mzML? this could explain different behavior

**Comment by timosachsenberg** [comment]
Now you managed to confuse me completely ;) . I took a look at your mzML file and there we have:   
```
      <cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="1.001647" unitCvRef="UO" unitAccession="UO:0000031" unitName="minute"/>
```
as opposed to what you wrote above.
Anyway, my working hypothesis is now that MSGFPlus does not correctly convert the mzML with scan start time in minutes to seconds.

**Comment by timosachsenberg** [comment]
The workaround in OpenMS is to process the file first with one of our tools.
afterwards I get:
```
 <cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="60.09882" unitAccession="UO:0000010" unitName="second" unitCvRef="UO" />
```

**Comment by mwalzer** [comment]
Maybe a short sum-up from the beginning would help?

**Comment by timosachsenberg** [comment]
its a MSGFPlus problem

**Comment by lars20070** [comment]
In case we want to open a new MS-GF+ issue, here a Java command line example with the complete `CC127` file. http://bit.ly/2bQsJEa That's the file leading to retention times in minutes.

**Comment by timosachsenberg** [comment]
yes please do so

**Comment by lars20070** [comment]
@mwalzer As discussed on the phone, here the three links:

complete CC127 via adapter
https://www.dropbox.com/sh/gus47ay2refg70x/AAB5BMhKN-xDNmkFfKMpHtUDa

10sec slice of CC127 via adapter
https://www.dropbox.com/sh/bfyj6uuqq4epyar/AAA6l16OUjirNdNYLt-QhM8ia

complete CC127 direct MS-GF+ from command line
https://www.dropbox.com/sh/bhz0vm442icogf5/AABkKdDBRM-VliyfQIWL7JDwa

**Comment by timosachsenberg** [comment]
scan start time in mzML (note: the unit is minutes):
```
        <spectrum index="23301" id="controllerType=0 controllerNumber=1 scan=23302" defaultArrayLength="377">
          <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" value=""/>
          <cvParam cvRef="MS" accession="MS:1000511" name="ms level" value="2"/>
            <scan>
              <cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="51.05031" unitCvRef="UO" unitAccession="UO:0000031" unitName="minute"/>
```

scan start time in mzID (note: here the unit is seconds!):
```
      <SpectrumIdentificationResult spectrumID="controllerType=0 controllerNumber=1 scan=23302" spectraData_ref="SID_1" id="SIR_23302">
        <SpectrumIdentificationItem chargeState="3" experimentalMassToCharge="1047.16796875" calculatedMassToCharge="1047.18505859375" peptide_ref="SERVEDDMDSFRYFKELAFAETKNK" rank="1" passThreshold="true" id="SII_23302_1">
          <PeptideEvidenceRef peptideEvidence_ref="PepEv_26508972_VEDDMDSFRYFKELAFAETKNK_86"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002049" name="MS-GF:RawScore" value="27"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002050" name="MS-GF:DeNovoScore" value="306"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002052" name="MS-GF:SpecEValue" value="1.2631749E-6"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002053" name="MS-GF:EValue" value="56.02739"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002054" name="MS-GF:QValue" value="0.9872756"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002055" name="MS-GF:PepQValue" value="0.9687363"/>
          <userParam name="IsotopeError" value="0"/>
          <userParam name="AssumedDissociationMethod" value="HCD"/>
        </SpectrumIdentificationItem>
        <cvParam cvRef="PSI-MS" accession="MS:1001115" name="scan number(s)" value="23302"/>
        <cvParam cvRef="PSI-MS" accession="MS:1000016" name="scan start time" value="51.05031"/>
      </SpectrumIdentificationResult>
```

**Comment by timosachsenberg** [comment]
The problem seems to be that MSGFPlus reads the mzML with scan start time unit in minutes but threads them like seconds.
To be confirmed with MSGFPlus guys...

**Comment by lars20070** [comment]
New MS-GF+ issue. https://github.com/sangtaekim/msgfplus/issues/2

**Comment by lars20070** [comment]
@mwalzer Sangtae will add the RT units to the `mzid` output. That will resolve the issue.

**Comment by timosachsenberg** [comment]
if we parse them in the MzIdentMLHandler (which I think we don't ;)

**Comment by hendrikweisser** [comment]
I think for the moment we still have the problem that we get bad results at least for some MS-GF+ versions. Should we add a heuristic to decide whether the RT values are in minutes or seconds? We could look at the spacing between scans - that can't be less than an instrument's cycle time. (Although this might not work for merged mzML files...)

**Comment by timosachsenberg** [comment]
Actually, there is no heuristic required as you could deduce this information from the mzML (there you have the unit).

**Comment by mwalzer** [comment]
Yep, unit is quite important for a number of CVs - that is how RT is represented in mzid, as a CV term.
Upcoming problem is that as of mzid1.2 RT will not be required anymore and we (or our workflows) are required to regain that info from spectrum reference and mzml file) - which should be possible already.

@timosachsenberg: Regarding the handler, as far as I can see, the adapter uses subsequently the handler.

**Comment by timosachsenberg** [comment]
I think we don't support units in the mzid handler right now

**Comment by timosachsenberg** [comment]
I don't see a problem if tools still write out the (optional) rt.

**Comment by lars20070** [comment]
FYI, there is a new MS-GF+ version v2016.10.10 out.
https://omics.pnl.gov/software/ms-gf

**Comment by timosachsenberg** [comment]
tks. added dit
