### ISSUE TITLE
CDASH: MzIdentMLFile_test failed (bad lexical cast)

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2130]
In CDASH we get an: Test: MzIdentMLFile_test (Failed) 
Build: win8-VS10_x64-Release (scratchy.imp.fu-berlin.de)

Can someone confirm this is reproducible and e.g. Win/VS related (e.g. cast from different, platform specific NAN notations or similar)

 +  line 231:  TEST_EQUAL(peptide_ids[2].getHits()[1].getPeptideEvidences()[i]==peptide_ids2[2].getHits()[1].getPeptideEvidences()[i],true): got 1, expected 1
: passed

checking ([EXTRA] multiple runs) ... <'PeptideEvidence' without reference to the position in the originating sequence found.> occurred 6 times
No retention time found for 'SpectrumIdentificationResult'

    creating new temporary filename 'MzIdentMLFile_test_241.tmp' (line 241)
Error: Caught std::exception
 - Message: bad lexical cast: source type value could not be interpreted as target
: failed
Warning: no subtests performed in '([EXTRA] multiple runs)' (line 251)!

**Comment by cbielow** [comment]
I can confirm this (VS2010, x64)


Am 8/23/2016 um 8:50 AM schrieb Timo Sachsenberg:

**Comment by timosachsenberg** [comment]
Cool. Can you debug into it?

**Comment by cbielow** [comment]
I knew that would happen...

**Comment by cbielow** [comment]
well.. it throws a std::exception, so the stack trace is gone once I set a break point when its caught...
but the output file (which is loaded again) contains a lot of
`<cvParam accession="MS:1000894" cvRef="PSI-MS" name="retention time" value="1.#QNAN"/>`
that should be your culprit

**Comment by cbielow** [comment]
indeed, when I replace them with a real number, e.g. "5", the load() succeeds.

**Comment by cbielow** [comment]
The reason why this is so hard to debug: the DOMHandler still uses `boost::lexical_cast<double>` directly. Very bad. `String::toDouble()` is much better (and faster).

**Comment by timosachsenberg** [comment]
ok I replace them and we will see if this helps the issue

**Comment by cbielow** [comment]
replacing will not do it -- its just better for future debug

You need to get rid of QNAN's during writing the mzId

**Comment by timosachsenberg** [comment]
ok as a quick workaround I can just extend next line
```
        if (!ert.empty() && ert != "nan" && ert != "NaN")
        {
          sidres +=  "\t\t\t\t" + cv_.getTermByName("retention time").toXMLString(cv_ns, ert) + "\n";
        }
```

**Comment by cbielow** [comment]
this line is ... complicated...
should be much easier to check for isnan on the double directly 
(it->getRT()) instead of the converted string?!

Am 8/23/2016 um 10:59 AM schrieb Timo Sachsenberg:

**Comment by timosachsenberg** [comment]
yep I am doing this
