### ISSUE TITLE
General handling of optional outputs of TOPP tools

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2135]
Recently, some issues with KNIME were reported with nodes that provide options to produce additional optional output files.
The problem with KNIME is that it always creates a temporary file store for any possible output and some of the tools automatically activate their optional subroutine when the optional output file parameter is given. Although we are currently working on a fix that allows the user to deactivate this behaviour of KNIME separately for every port, I wanted to evaluate the usage of optional in/outputs for TOPP tools in general.
It would be very beneficial for users if our tools would follow a certain behaviour when dealing with these optional parameters. I would like to discuss here:
- When should optional parts of algorithms be triggered? E.g. by certain combinations of parameter settings or solely by giving an additional optional output filepath (Example: FileMerger)
- How complex may the parameter logic inside a tool be (in the worst case)? (Affects tools with many optional outputs like InternalCalibration, TopPerc, ProteinResolver; I have not deeply looked into the logic there, yet)

I created a list of tools that have optional output parameters and maybe we can discuss and fix some of the pathologic cases here.

**Checked (file always created if optional parameter set):**

```
./HighResPrecursorMassCorrector.ctd
out_csv (file can be empty 
"LOG_WARN << "Output file 'out_csv': No data collected since 'nearest_peak:mz_tolerance' was not enabled. CSV will be empty." << endl;")
./FeatureFinderMultiplex.ctd
out out_features out_mzq
./MassCalculator.ctd (if empty, output is written on screen)
out
./SequenceCoverageCalculator.ctd (if empty, output is written on screen)
out
./MultiplexResolver.ctd
out_conflicts
./FeatureFinderCentroided.ctd
out_mzq
./AccurateMassSearch.ctd (Filetype of input file determines filetype of outputfile) 
out_annotation
./EICExtractor.ctd (only created if in addition the auto_rt:enabled flag is set)
out_debug_TIC
    if (!getFlag_("auto_rt:enabled") && !out_TIC_debug.empty())
    {
      LOG_FATAL_ERROR << "Error: TIC output file requested, but auto_rt is not enabled! Either do not request the file or switch on 'auto_rt:enabled'." << std::endl;
      return ILLEGAL_PARAMETERS;
    }
./MapStatistics.ctd
out
./FFEval.ctd (no error if all empty, no output)
out out_roc
./ProteinResolver.ctd (error if protein_groups peptide_table protein_table are all empty)
protein_groups peptide_table protein_table additional_info
./CVInspector.ctd (prints to cmd line if param empty)
html
./FileInfo.ctd (prints the respective info to screen if its param empty)
out out_tsv
./ITRAQAnalyzer.ctd  (no error if all empty, no output)
out_mzq out_stats
./PrecursorIonSelector.ctd (no error if all empty, no output)
out next_feat
./MSSimulator.ctd (error if all empty)
out out_pm out_fm out_cm out_lcm out_cntm out_id
./TransformationEvaluation.ctd (prints the respective info to screen if its param empty)
out
./IDSplitter.ctd
out id_out (error if all empty)
./Decharger.ctd
out_fm outpairs
./MapRTTransformer.ctd (error if both empty)
out trafo_out
./MRMPairFinder.ctd
feature_out
./ERPairFinder.ctd
feature_out
./TMTAnalyzer.ctd
out_mzq out_stats
./InternalCalibration.ctd
lock_out lock_fail_out models models_plot residuals residuals_plot
./TopPerc.ctd
X J w B
```

**Checked (file list created if optional parameter set):**

```
./FileMerger.ctd (number of output files must match number of input files)
trafo_out
```

**Checked (medium problematic):**
These are usually "either or, or multiple" output cases. I think it would be enough if we could decide on standard configurations here and add a standard output file there to symbolize the standard usage. If not possible, we can just leave it as is and in KNIME, disable all outputs from the start and the user will immediately notice that he has to make a choice.

```
./ProteinQuantifier.ctd (either one of the two parameters must be provided)
out peptide_out 
    if (out.empty() && peptide_out.empty())
    {
      throw Exception::RequiredParameterNotGiven(__FILE__, __LINE__,
                                                 __PRETTY_FUNCTION__,
                                                 "out/peptide_out");
    }

./MSGFPlusAdapter.ctd (out, mzid_out): either one or both can be specified. Is it really used that 
both will be specified? If not, we could handle it like with other tools and infer the output type from 
the mime type of the file (in KNIME this can be done in the special OutputType Register dialog)

./OpenSwathWorkflow.ctd ( "Either out_features or out_tsv needs to be set (but not both)");)
out_features out_chrom (out_tsv?)
```

Creation of files not tracked/registered by TOPPAS

```
./IDMassAccuracy.ctd (creates fragment_out_file + "_gnuplot.dat" and fragment_out_file + "_gnuplot.gpl" if generate_gnuplot_scripts is set, no error if both fragment or precursor out not set)
precursor_out fragment_out
./IDRipper.ctd (out (file) is placeholder for out_path (string) where all extracted id files are stored - probably also quite problematic)
out
./IDPosteriorErrorProbability.ctd
out_plot (txt file (if gnuplot is available, a corresponding PDF will be created as well.))
./MapAlignerPoseClustering.ctd  (no error if all empty, no output but calculations are performed (bug?))
out trafo_out
./MapAlignerSpectrum.ctd (no error if all empty, no output)
out trafo_out
./MapAlignerIdentification.ctd  (no error if all empty, no output but calculations are performed (bug?))
out trafo_out
```

**Checked (very problematic):**

```
./RTPredict.ctd (different behavior depending on provided output parameter, presence of one output
 parameter depends on presence of other, not all combinations of present output parameter are 
valid - aka cmd line interface from hell)
file positive negative file
./TextExporter.ctd (Output file (mandatory for featureXML and idXML (what about mzid?))
out centroids elements features
```

Not needed in KNIME?

```
./INIUpdater.ctd
out
```

**Comment by timosachsenberg** [comment]
@jpfeuffer can you provide/highlight the ones with non-empty defaults, too? Or do they only exist for input files?

**Comment by jpfeuffer** [comment]
Good question, I would guess (hope) that this is only done for optional input files but I think I can adapt the script.

**Comment by timosachsenberg** [comment]
@hendrikweisser 
How does naming of the transformation files work with the current code if no output files are specified?
see:
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FileMerger.cpp#L191-L201

**Comment by hendrikweisser** [comment]
> How does naming of the transformation files work with the current code if no output files are specified?

In that case no outputs are written (see https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FileMerger.cpp#L159-L162).

**Comment by timosachsenberg** [comment]
ok - maybe this could already be documented at the resize() part (so one doesn't need to look into the called function)

**Comment by hendrikweisser** [comment]
It seemed obvious to me that no output would be written if the output parameter wasn't set, but feel free to add a comment in the code.

**Comment by jpfeuffer** [comment]
@timosachsenberg If my script was correct, there are no optional output-file parameters with standard values (after CTD postprocessing for KNIME). The problems only arise through logics involving other parameters and outputs that exclude each other.

**Comment by timosachsenberg** [comment]
I think https://github.com/OpenMS/OpenMS/blob/develop/src/topp/PTPredict.cpp#L97
is wrongly declared as optional.
Standard code path always reaches:
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/PTPredict.cpp#L274
Anyone used that tool and can confirm this?

**Comment by hroest** [comment]
@jpfeuffer can we close this?

**Comment by jpfeuffer** [comment]
Since the fix for KNIME is implemented it is certainly not a major defect anymore. Still room for improvement. It is very easy to do things wrong with optionality at this point.

**Comment by mwalzer** [comment]
Then I'll remove the major label. Can you link the fix somehow for accessibility?

**Comment by timosachsenberg** [comment]
https://github.com/genericworkflownodes/GenericKnimeNodes/pull/137
