### ISSUE TITLE
Documentation about maximum path length for building on Windows?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2136]
Is it somewhere documented that the path to your build directory can be maximally 42 characters (to be safe, even less)?

It comes from the fact that the longest executable name that we have results in an even longer folder structure from the CMake/Visual Studio combination:

`\src\tests\class_tests\superhirn\FeatureFinderAlgorithmSHSuperhirnClusteredMS2ConsensusSpectrum_test.dir\Release\FeatureF.BB40B300.tlog\FeatureFinderAlgorithmSHSuperhirnClusteredMS2ConsensusSpectrum_test.lastbuildstate`

I think in general, we should avoid such long names but at a certain point there is nothing that we can do but warn users.
Workarounds might include mapping/linking the build folder to a drive or a shorter folder. Or hoping for an easy way to enable long paths in Windows10.

**Comment by cbielow** [comment]
you are referring to the Win API limit of 255/260 characters per path?
The path stated above has 218 chars, leaving 42 for the path to the build-tree.

I would not bother with links/mapping (especially on Windows), but rather change the name of the test (which consumes 68x2 chars alone in this case).

Another option is to add a check to the build system, but we'd need to hardcode the limit of '42' and check from time to time if it still applies (in case someone came up with an even uglier name for a class or test or subdir structure).

What is the actual consequence of stepping over this limit?! The file cannot be created and the developer is left with a weird cmake error message?

**Comment by jpfeuffer** [comment]
Yes the cause is the Windows path limit and the result is a rather well written CMake error:
`C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(308,5): error MSB3491: Could not write lines to file "FeatureFinderAlgorithmSHSuperhirnconsensIsotopePattern_test.dir\Release\FeatureF.E4D91F8E.tlog\FeatureFinderAlgorithmSHSuperhirnconsensIsotopePattern_test.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\dev\jenkins-tuebingen\workspace\openms_win\e9f1ff5e\build\src\tests\class_tests\superhirn\FeatureFinderAlgorithmSHSuperhirnconsensIsotopePattern_test.vcxproj]`
Nevertheless, it means that the object will not be created and therefore the executable and the tests will fail.

**Comment by cbielow** [comment]
Ok, since the error message is really clear, a small sentence in the build-docs for Windows should do the job just fine here. Maybe we can think of renaming some of the most prominent tests, but 42 sounds like enough room to me.
