### ISSUE TITLE
pyOpenMS doesn't find libWm5Core (on OS X)

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2139]
I've built pyOpenMS successfully on my Mac and installed it via `sudo python setup.py install`. However, when I try `import pyopenms` in Python (2.7.10), I get the following error:

```
import pyopenms
determination of memory status not supported on this 
 platform, mesauring for memoryleaks will never fail


======================================================================


maybe you miss some libraries. please run ldd (on linux) or
dependency walker (on windows) on 


/Library/Python/2.7/site-packages/pyopenms-2.0.1-py2.7-macosx-10.10-intel.egg/pyopenms/pyopenms.so


======================================================================


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pyopenms-2.0.1-py2.7-macosx-10.10-intel.egg/pyopenms/__init__.py", line 52, in <module>
    raise e
ImportError: dlopen(/Library/Python/2.7/site-packages/pyopenms-2.0.1-py2.7-macosx-10.10-intel.egg/pyopenms/pyopenms.so, 2): Library not loaded: libWm5Core.dylib
  Referenced from: /Library/Python/2.7/site-packages/pyopenms-2.0.1-py2.7-macosx-10.10-intel.egg/pyopenms/libOpenMS.dylib
  Reason: image not found
```

The message says what to run on Linux or Windows, but nothing about OS X.

**Comment by hendrikweisser** [comment]
I think the relevant tool to run on OS X is "otool -L". Results:
```
$ otool -L /Library/Python/2.7/site-packages/pyopenms-2.0.1-py2.7-macosx-10.10-intel.egg/pyopenms/pyopenms.so
/Library/Python/2.7/site-packages/pyopenms-2.0.1-py2.7-macosx-10.10-intel.egg/pyopenms/pyopenms.so:
	@loader_path/libOpenMS.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/libOpenSwathAlgo.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/libSuperHirn.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

$ otool -L /Library/Python/2.7/site-packages/pyopenms-2.0.1-py2.7-macosx-10.10-intel.egg/pyopenms/libOpenMS.dylib 
/Library/Python/2.7/site-packages/pyopenms-2.0.1-py2.7-macosx-10.10-intel.egg/pyopenms/libOpenMS.dylib:
	/Users/hw5/Software/OpenMS/build/lib/libOpenMS.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/libOpenSwathAlgo.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/QtNetwork (compatibility version 4.8.0, current version 4.8.6)
	@loader_path/QtCore (compatibility version 4.8.0, current version 4.8.6)
	/Users/hw5/Software/Homebrew/opt/libsvm/lib/libsvm.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/hw5/Software/Homebrew/opt/boost/lib/libboost_iostreams-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/hw5/Software/Homebrew/opt/boost/lib/libboost_date_time-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/hw5/Software/Homebrew/opt/boost/lib/libboost_math_c99-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/hw5/Software/Homebrew/opt/boost/lib/libboost_regex-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	libWm5Core.dylib (compatibility version 0.0.0, current version 0.0.0)
	libWm5Mathematics.dylib (compatibility version 0.0.0, current version 0.0.0)
	libbz2.1.0.5.dylib (compatibility version 0.0.0, current version 1.0.5)
	/Users/hw5/Software/OpenMS-contrib/build/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1151.16.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 62.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

There is a part of the pyOpenMS build process that "fixes" the shared library files, but     "libWm5Core.dylib" and "libWm5Mathematics" are not affected by that.

**Comment by hendrikweisser** [comment]
Note that in order to get OpenMS itself to work, I have to set the environment variable "DYLD_LIBRARY_PATH" (to point to the "lib" directory in my contrib). It seems that Python doesn't take this setting into account.

**Comment by hroest** [comment]
I remember that last time George managed to get it to work on OS X and it was some extra script that unpacks it all and packs it in again. maybe @grosenberger and @uweschmitt can comment?

**Comment by grosenberger** [comment]
Sorry for the delayed response...

For 1.11 and 2.0 we generated the OS X packages by patching according to this guide: https://github.com/OpenMS/OpenMS/issues/602

It might be that with the more recent changes and tools that this is not necessary anymore. For 2.1, we should definitely check and update the instructions.

**Comment by hroest** [comment]
@grosenberger do you think somebody has time to make OS  X builds again for pyOpenMS ? I dont have access to a Mac so I think it will be hard for me to do, maybe @grosenberger and @hendrikweisser can collaborate on this?

**Comment by hendrikweisser** [comment]
Update: I got it to work after using `install_name_tool -change` to put absolute paths to "libWm5Core.dylib", "libmWm5Mathematics.dylib" and "libbz2.1.0.5.dylib" (not sure if the last one is necessary) in "libOpenMS.dylib" and "libSuperHirn.dylib" in the pyOpenMS build directory, and to "libWm5Core.dylib" in "libmWm5Mathematics.dylib" in the contrib's lib directory.
Thanks for the pointers, Hannes and George!

**Comment by hendrikweisser** [comment]
By the way, the root cause of this problem, as well as of #1829, seems to be that some libraries do not get linked into other libraries/executables correctly on my system. Someone posted a CMake configuration on StackOverflow that solved similar problems for him; that might be worth looking into: http://stackoverflow.com/a/35406018

**Comment by jpfeuffer** [comment]
Yes, the thing is that the MACOSX_RPATH is a "newer" feature of CMake and is not compatible with the minimum CMake version that we require. I am already in favour of upgrading that minimum version. See also #2164

**Comment by jpfeuffer** [comment]
What's the status here? I think it was solved right? We will check it again in the course of the qt5 packaging upgrade.

**Comment by grosenberger** [comment]
It should work now. I put prebuilt packages for pyOpenMS 2.3 on #3202.
