### ISSUE TITLE
FeatureFinderMetabo in KNIME builds is incompatible with linux distros

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#2144]
`libgomp.so.1: version `GOMP_4.0' not found`
 although it is installed in version 4 (linux mint, ubuntu, debian) - so it works fine with the self compiled version.

**Comment by timosachsenberg** [comment]
is this a new problem? I always had the impression the tutorial workflows were tested on various (emulated) linux systems in the past.

**Comment by timosachsenberg** [comment]
which KNIME/OpenMS version? stable or nightly?

**Comment by timosachsenberg** [comment]
@FabianAicheler did you also test linux or only windows?

**Comment by mwalzer** [comment]
both de.openms.linux.x86_64_2.0.0.201605271126 and newest de.openms.linux.x86_64_2.0.0.201607151403

**Comment by mwalzer** [comment]
Okay, this might be worse. This is every KNIME node in the 2.1 build for linux.
Installed library version is /usr/lib/x86_64-linux-gnu/libgomp.so.1 4.8.4-2ubuntu1~14.04.3

**Comment by mwalzer** [comment]
There is mentioning in the tutorial handout faq which is a **red herring** as far as I see, since my gcc version is > 4.8 as is the compiler used for the repository library.
```
Q: Whenever I try to execute an OpenMS node I get an error similar to these:
/usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found
A: We currently build the binaries shipped in the OpenMS KNIME plugin with gcc 4.8. We will try to extend our support for older compilers.
Until then you either need to upgrade your gcc compiler
or at least the library that the tool complained about or you need to build the
binaries yourself (see OpenMS documentation) and replace them in your KNIME binary folder\\
```

**Comment by mwalzer** [comment]
@jpfeuffer could this be coming from our build?

**Comment by jpfeuffer** [comment]
It most definitely is. Compiler is meanwhile gcc (Debian 4.9.2-10). It seems to link to a newer version of OpenMP than you have.
I downgraded to the oldest on the machine: gcc-4.8 (Debian 4.8.4-1) 4.8.4 but I cannot guarantee that it then links to an older library version. We will see. We can use arbitrary Docker containers for the KNIME builds soon, but it is not yet ready.
How do you know, that you have the correct version? Can you post the output of
`nm -D /usr/lib/x86_64-linux-gnu/libgomp.so.1 | grep ".*A\ GOMP*"`

**Comment by mwalzer** [comment]
>How do you know ...

Well, I thought that the repository libraries would be complete, but looking at nm I see 
``` 
 A GOMP_1.0
 A GOMP_2.0
 A GOMP_3.0
``` 
but no 4.0 - which would be coherent with the repository lib being compiled by gcc4.8 and 4.0 being fully supported only with gcc4.9.
I think, this then is related to this [knime forum entry](https://tech.knime.org/forum/openms/openms-nodes-are-not-working-for-knime-on-linux-mint-172) ?

**Comment by hendrikweisser** [comment]
Is this issue still relevant? If not, please close.
