### ISSUE TITLE
Convert mzML file (or other) to CSV file using FileConverter executable

### ISSUE THREAD

**Issue by felixveysseyre** [OpenMS/OpenMS#2156]
Hello,

I am trying to convert some mass spectrometry data stored as mzml files (but also mgf, dta, dta2d, ms2, fid, peplist) to CSV. [mzml -> CSV]

Reading the FileConverter executable help (available here: http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/TOPP_FileConverter.html), I should be able to convert my mzml file into a csv file using this command:
`/Applications/OpenMS-2.0.0/TOPP/FileConverter -in ChromatogramExtractor_input.mzML -out ChromatogramExtractor_input.csv`

Executing the previous command results the following error:

> FileConverter can only convert consensusXML files to ibspectra format.

Looking at the code, the CSV file output is only available when the input is a consensusXML file.
I tried to convert my file to CSV using a consensusXML file intermediate [mzml -> consensusXML -> CSV], but I got another error:

> Warning: Converting consensus features to peaks. You will lose information! 
> Invalid parameter: Given ConsensusMap does not hold any isobaric quantification data.
> 

Is any way to convert my files to CSV, using FileConverter or any other tool ?

Thanks for your time.

**Comment by timosachsenberg** [comment]
Hi,
If you are mainly interested in easily parsable MS2 data then you could convert it to mgf (its strictly speaking on csv). Otherwise, I think you could use dta2d which should output all peaks.

**Comment by felixveysseyre** [comment]
Thanks @timosachsenberg, dta2d file format seems to do the work !

I would like to display an usual mass spectrometry graph such as this one: 

![2etmeam1](https://cloud.githubusercontent.com/assets/4909259/18123321/aa8d5076-6f6d-11e6-9fda-5471ac00bc16.gif)

I do have a column for MZ and for Intensity, but I also have a third column named SEC which apparently corresponds to the retention time.

Do you know how I can compute a such graph from these data ?

**Comment by timosachsenberg** [comment]
Yes, the SEC column corresponds to retention time in seconds.
To generate these kinds of plots you probably need some scripting and custom scripts.
e.g. you could take a look at pyOpenMS which should allow you to directly parse the spectra without conversion to dta2d or similar formats. Then use python's matplot lib or similar to plot the results.
You can also directly view the spectra in TOPPView and export them manually to a vector graphic or raster graphic file which you could manually edit in a graphic program.

**Comment by felixveysseyre** [comment]
That exactly what I want to do.

My question was more related to the mathematical point of view.
Considering we have multiple series, one for each retention time, how do we compute the series displayed on my previous graph.

I am sure this information is available somewhere but I have difficulty to find the correct terms to search.

**Comment by hendrikweisser** [comment]
@felixveysseyre:
The graph that you showed is simply a mass spectrum. If you want to bring in the retention time, you need a third dimension in your representation. You can do that by representing intensities on a colour gradient in an m/z-by-RT map, or you can create a 3D plot. Both are offered in TOPPView.

**Comment by felixveysseyre** [comment]
@hendrikweisser I want to display only a 2D mass spectrum. Retention time information not interest me.

I suppose the mass spectrum is a combination of the series obtain for various retention times, or I am completely wrong ?

**Comment by hendrikweisser** [comment]
> I suppose the mass spectrum is a combination of the series obtain for various retention times, or I am completely wrong ?

No, you'd get one mass spectrum per time point. (If your spectra are all of the same compound, I guess you could aggregate multiple measurements into one spectrum, but that's not typically done.)

**Comment by timosachsenberg** [comment]
A spectrum is recorded at a certain retention time and consists of mass-to-charge and intensity pairs.
See e.g. https://en.wikipedia.org/wiki/Mass_spectrum
Single runs often contain tens of thousands of spectra and experiments easily millions of spectra.

**Comment by felixveysseyre** [comment]
Thanks for your time guys, I got it !
