### ISSUE TITLE
[BUILD] make final_package can only be executed once

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2165]
During `make final_package` on Mac, CMake seems to change the RPATH of the DocumenterHandler binaries to e.g. `@executable_path/../lib/libOpenMS.dylib` such that during a second run of `make final_package`, the OpenMS-preinstall Component fails at the doc_param generation (whyever this is necessary).
If possible, CMake should not try to invoke the parameter doc generation again. In any case, we should prevent that the path of the DocumenterHandlers will be modified. They are not in the bin folder, where it would make sense to do such a thing.
Related is the problem that we always have to set the correct name of the bundle in the fix_dmg.sh script. It should get configured by CMake for example.

**Comment by jpfeuffer** [comment]
Okay concerning the docs being always built, no matter if anything changed, I found that we should use add_custom_command together with add_custom_target since custom targets are always out of date.
Something along the lines of https://nazavode.github.io/blog/2013/01/documentation-with-doxygen-and-cmake-a-slightly-improved-approach/ would be great. I don't know if this is possible with our setup and the many doc targets.

**Comment by jpfeuffer** [comment]
Solved by applying install_name_tool AFTER installation. Keeps the binaries in the build tree clean.

**Comment by hroest** [comment]
@jpfeuffer close this?

**Comment by jpfeuffer** [comment]
Not sure. The main error is fixed. We could still use some improvements in the CMake dependencies between packaging and documentation. Maybe rename or open another issue?

**Comment by hendrikweisser** [comment]
Closing as mainly fixed and inactive.
