### ISSUE TITLE
Missing tools in ToolHandler?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2169]
When creating the CTDs for the KNIME package (strangely only under Windows; maybe I have some debug settings activated?) I get the following warnings and errors:

```
EXEC : warning : Message to maintainer - If 'MultiplexResolver' is an official TOPP tool, add it to the tools list in ToolHandler. If it is not, set the 'official' flag of the TOPPBase constructor to false.

165>EXEC : warning : Message to maintainer - If 'TICCalculator' is an official TOPP tool, add it to the tools list in ToolHandler. If it is not, set the 'official' flag of the TOPPBase constructor to false.
165>   Memory consumption before 2328
165>EXEC : error : Unexpected internal error (The value 'TICCalculator' was used but is not valid! Requested tool 'TICCalculator' does not exist!)
165>   Memory consumption final 2360
```
I am not sure why one raises an error and the other doesn't. The binary of TICCalculator was built, is present and works. I guess it is only about registering them correctly.

**Comment by jpfeuffer** [comment]
Ok it also happens on the other platforms but it seems like the script does not abort like on Windows.

**Comment by timosachsenberg** [comment]
should be fixed with https://github.com/OpenMS/OpenMS/pull/2170
