### ISSUE TITLE
IDPosteriorErrorProbability fails for OMSSA

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2172]
I worked with OMSSAAdapter followed by IDPosteriorErrorProbability in OpenMS version 2.0.0 without any problem. But if I run the exact same pipeline on 2.0.1 or 2.1.0, I’m getting “Unable to fit data. Algorithm did not run through for the following search engine: OMSSA” from IDPosteriorErrorProbability. This only happens to OMSSA and not other engines. The only fix I could find was to centroid the data but I prefer not to do as I miss a lot.

**Comment by jpfeuffer** [comment]
Wow. I do not remember any changes to IDPEP since 2.0.1.

**Comment by jpfeuffer** [comment]
It would be interesting to see the OMSSA output before and after.
I actually think that this must have changed. Potentially, it could be every tool upstream of OMSSA, too.

**Comment by petercim** [comment]
Encountered the same problem (using release 2.0.1). But only with one of the 12 mzML input files (different biological replicates). Any ideas what could be going wrong?

**Comment by PayamEmami** [comment]
@hendrikweisser, yes. It is related. It seems like  introducing the lowest e value (lowest double 4.94065645841247e-324) causes the problem. I just put 1e-20 back and recompiled and it worked perfectly. I went as low as -e100 without problem.

**Comment by jpfeuffer** [comment]
Well then the algorithm needs to store the outliers (to calculate a score later) but should not include them in the fitting.
This tool is a project for itself. Many improvements there, maybe we get a student working on this.

**Comment by jpfeuffer** [comment]
I added some outlier handling to IDPEP a while ago. Might be fixed.
