### ISSUE TITLE
FileConverter should convert to CSV

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2175]
apparently the FileConverter right now does not convert mzML to csv, however it converts to DTA  / DTA2D which is basically csv. This is confusing for users

```
Executing the previous command results the following error:

        FileConverter can only convert consensusXML files to ibspectra format.


Looking at the code, the CSV file output is only available when the input is a consensusXML file.
I tried to convert my file to CSV using a consensusXML file intermediate [mzml -> consensusXML -> CSV], but I got another error:

        Warning: Converting consensus features to peaks. You will lose information! 

        Invalid parameter: Given ConsensusMap does not hold any isobaric quantification data.


Is any way to convert my files to CSV, using FileConverter or any other tool ?
```

we should make the error message more intuitive or simply output DTA2D if a user requests mzML -> csv.

**Comment by hroest** [comment]
see also #2156 this would just make it more intuitive for OpenMS users

**Comment by amnamasood** [comment]
Hello!
I was thinking if it would be possible to define a method similar to EDTAFile::store() which would convert the loaded file to csv, with a warning that this file is not an IBspectra file?

**Comment by timosachsenberg** [comment]
Hi @amnamasood . Let me make sure I understood correctly.
You want to add the possibility to convert mzML files to EDTA.
I think that is a good idea and you could extend the EDTAFile class with a store function that takes a PeakMap (a MSExperiment).
To make most of the EDTA data one has to add some metadata columns that allow distinguishing different spectrum and chromatogram types. But we can add these step-by-step.

**Comment by amnamasood** [comment]
I have updated my previous comment. Can you take a look? I can also work on the function you suggested.

**Comment by timosachsenberg** [comment]
Maybe the other one is a bit better because a proper implementation of this feature requires some insight into how different level of MS spectra or chromatograms are stored.

**Comment by amnamasood** [comment]
I am afraid I don't have much knowledge in this domain, but maybe I can start working on it step-by-step.

**Comment by timosachsenberg** [comment]
No problem. We can do this step-by-step

**Comment by amnamasood** [comment]
Thank you. Can you help me a little? I cannot find where is the conversion from mzml to DTA or DTA2D, because wherever mzml is processed as an in_type, there is an associated condition of out_type.

**Comment by timosachsenberg** [comment]
The logic is:
- read mzML file into an MSExperiment (internal data structure to store all spectra)
- store an MSExperiment into a DTA2D or other format

For DTA2D, the conversion happens in the store function.
line https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FileConverter.cpp#L468 calls:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FORMAT/DTA2DFile.h#L270
Which iterates through the spectra of the MSExperiment and writes out the peaks.

**Comment by hroest** [comment]
it looks like https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FORMAT/DTA2DFile.h#L270 does not write out any chromatograms, is that correct behavior?

**Comment by amnamasood** [comment]
Hello!
I was thinking that maybe if instead of making a new function I could convert the MSExperiment exp to consensus map like here: https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FileConverter.cpp#L560
and then store the edta file.

**Comment by tentrillion** [comment]
I would be interested in having `FileConverter` write .csv as well.  (Optionally, perhaps relatedly, `EICExtractor` should either provide an option to output EICs instead of peak integration results.  I found the name of the `EICExtractor` function to be very confusing.  I thought it would output chromatogram data instead of peak areas for a long time.)
