### ISSUE TITLE
FFMultiplexRequant

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2182]
From UM2016: Create new util that quantifies undetected features based on information from a consesusXML.

Input: consensusXML, list of mzML files
Output: consensusXML with extended consensus features

Algorithm: e.g. extract all peaks that match into isotopic trace positions (charge is known from cf) + window and quantify using the same functions as FFM

**Comment by hendrikweisser** [comment]
See also #1952 (first point).

**Comment by timosachsenberg** [comment]
Probably easiest to integrate into FFM. Just using XIC extractor will probably not result in meaningful quantifications

**Comment by hroest** [comment]
> Probably easiest to integrate into FFM. Just using XIC extractor will probably not result in meaningful quantifications

depends, if you extract at the correct position then yes :-) this is basically what #1952 suggests and demix-q describes in the paper.

**Comment by timosachsenberg** [comment]
I would suspect that the peak summation method must be identical (which differs for FFC and EICExtractor). But I have to look at the actual publication. Maybe they are doing something to deal with this.
