### ISSUE TITLE
Does MSGF+ have a (hidden?) missed_cleavages option?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2184]
We found this [Galaxy toolshed](https://toolshed.g2.bx.psu.edu/repository/display_tool?repository_id=27734fe7ae83d0a6&render_repository_actions_for=tool_shed&tool_config=%2Fsrv%2Ftoolshed%2Fmain%2Fvar%2Fdata%2Frepos%2F000%2Frepo_335%2Fmsgfplus_search.xml&changeset_revision=0cfe768bbda1) that exposes a missed cleavage option for MSGF+.

Does anyone know it MSGF+ still supports this? Or do they use e.g. 2 as a standard now?

**Comment by hendrikweisser** [comment]
I've opened an issue on the MS-GF+ project about this: https://github.com/sangtaekim/msgfplus/issues/3

**Comment by jpfeuffer** [comment]
Thanks a lot. Let's keep this issue open to also potentially track an implementation of the exposition of this parameter (if present).

**Comment by timosachsenberg** [comment]
Answer is:
MS-GF+ does not have any limitation on the number of missed cleavages; this is something that you would have to compute and filter on post-search. The only restrictions on peptides that are applied are minimum and maximum length, and enzyme specificity, plus also the maximum number of dynamic (optional) modifications.

**Comment by hendrikweisser** [comment]
See also #2004.
