### ISSUE TITLE
Empty file test using file size is bad (can't read from named pipes)

### ISSUE THREAD

**Issue by mcapuccini** [OpenMS/OpenMS#2188]
Hi! I am trying to reproduce a study in a distributed cloud environment using OpenMS. I have developed a tool to execute trivially parallelizable tasks in Spark (https://github.com/mcapuccini/EasyMapReduce). You have an empty file test in most of your tools, that checks the size of the file. This is making my life hard, as my parallelization tool uses named pipes to pass the data to OpenMS. Named pipes will always have file size equal to 0, but this doesn't mean that they are empty. It would be nice if you could fix this, in a way that your tools can read from named pipes.

**Comment by hroest** [comment]
this would actually be really cool but there are some limitations as some file formats require the computation of hashes across the whole datafile - not sure whether that would be a problem. I really like the idea to be able to do this - I guess this would be Linux only? 

do you have an example of which tools use the empty file test that causes problems? Is it only the tests that cause problems or do the tools also fail to work? can you post the error messages you get? are these `Error: File empty` - can you run with `-debug 10` and report the results? I think we check 

`src/openms/source/APPLICATIONS/TOPPBase.cpp: TOPPBase::inputFileReadable_`

here we check `File::exists`, `File::readable` and `File::isDirectory` and `File::empty`

where probably the last one causes issues, see https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/SYSTEM/File.cpp#L126

**Comment by hroest** [comment]
also it seems that in XMLFile.cpp we open the file to peek whether it is compressed and then close the file again. Also there are some cases where we expect to read multiple times from a file (e.g. indexed mzML). I am not sure how these would work with named pipes, but I dont have much experience here.

**Comment by cbielow** [comment]
another issue is `FileTypes::Type FileHandler::getTypeByContent(const String& filename)`, which reads the first couple of lines for files where we cannot derive the format from the suffix.

**Comment by mcapuccini** [comment]
@hroest and @cbielow, thanks for the quick answer. You can run this snippet to reproduce the the issue, with OpenMS 1.11.1:

```bash
# Get a sample from Metabolights
wget ftp://ftp.ebi.ac.uk/pub/databases/metabolights/studies/public/MTBLS233/040_CRa_H9M5_M470_L03_K1_alternate_neg.mzML 
# Make a named pipe
mkfifo named_pipe
# Copy the sample in the name pipe (it's important to run this in background, as it is blocking)
cp 040_CRa_H9M5_M470_L03_K1_alternate_neg.mzML named_pipe &
# Run PeakPickerHiRes
PeakPickerHiRes -in named_pipe -out out.mzML -debug 10
```

That's the output that I get with the -debug 10 option:

```bash
Debug level: 10
 >> PeakPickerHiRes -in named_pipe -out out.mzML -debug 10
Value of string option 'test': 0
Log file: 
Writing to ''
Debug level (after ini file): 10
Value of string option 'no_progress': 0
Value of string option 'in': named_pipe
Checking input file 'named_pipe'
Error: File empty (the file 'named_pipe' is empty)
Error occurred in line 1864 of file /build/buildd/openms-1.11.1/source/APPLICATIONS/TOPPBase.C (in function: void OpenMS::TOPPBase::inputFileReadable_(const OpenMS::String&, const OpenMS::String&) const) !
Cannot read input file given from parameter '-in'!
```

@hroest your observation "some file formats require the computation of hashes across the whole datafile" is very good. I have a --wholeFile flag in EasyMapReduce for that purpose. In fact, with a little workaround for the "named pipes issue", I was able to run PeakPickerHiRes and FeatureFinderMetabo in a Spark cluster with a very good speedup. 

For the current study I am working too, running in Spark the next step: FeatureLinkerUnlabeledQT, is now very interesting, as after the feature finding the dataset can fit the memory of a single computer. But, in other studies being able to parallelize the feature linking over multiple nodes might be crucial. 

So my next question is, can I parallelize the feature linking using a reduce approach? Meaning that I would run the feature linking on couples of samples (on different nodes), and then run again the feature linking on the intermediate results, until I get a single consensusXML file. Would this give a consistent result?

**Comment by mcapuccini** [comment]
@hroest and @cbielow, the other question is why to check if the file is empty at all? I mean, isn't it better to let the program fail on the XML parsing instead?

**Comment by hroest** [comment]
@mcapuccini I guess the only reason is to provide a better error message to users -- in this case, it may be a bit overzealous and I am in favor of removing the empty file check.

@mcapuccini regarding the parallelization of the feature linking: this will generally *not* produce a consistent result as the status of which feature gets selected depends on all other maps. There is, however, a way to produce consistent results: if you partition the m/z space such that there is no overlap between the partitions. This is generally possible for high resulution instruments, almost allowing binning for each unit m/z : we already do this here: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/ANALYSIS/MAPMATCHING/QTClusterFinder.cpp#L133

**Comment by mcapuccini** [comment]
The problem with the named pipes is still there, but I figured out  a workaround for if (which wastes some memory copying the file in a tmpfs mount inside the container). I guess I'll end up commenting that, and recompiling OpenMS. However, it would suggest to remove the file size check in the next releases if this doesn't cause too much problems.

Actually, if the way the feature is selected is a commutative and associative operator, the results should be consistent. I don't split the m/z space, but I split by sample instead:

 Split 1
| sample_000.featureXML |
| sample_001.featureXML | \ 
                                           \
 Split 2                                 / intermediate01.consensusXML\
| sample_000.featureXML | /                                                  \
| sample_001.featureXML |                                                      \
                                                                                                \
 Split 3                                                                                        result.consensusXML
| sample_000.featureXML |                                                        /
| sample_001.featureXML | \                                                     /
                                           \                                                  /
 Split 4                                 / intermediate02.consensusXML/
| sample_000.featureXML | /
| sample_001.featureXML | 

For example this would work if the feature is selected by maximum intensity, as "maximum" is a commutative and associative operation. I am risking to be naive here :-).

**Comment by hroest** [comment]
@mcapuccini I dont think this is guaranteed to work as the current QT algorithm is global and tries to find a globally optimal solution. However, in practice, it may be that you wont find large differences

maybe @hendrikweisser or even @hannesveit can comment with regards to their respective algorithms in OpenMS but my general opinion is that splitting it the way you are doing may produce different results than analyzing all results together.

**Comment by hendrikweisser** [comment]
> my general opinion is that splitting it the way you are doing may produce different results than analyzing all results together

This is definitely true for FeatureLinkerUnlabeledQT. Features are linked based on proximity in RT, m/z space. In an intermediate consensus map, a feature group is represented by a centroid, whose position is different from that of the original features (unless they coincide exactly). In addition, the QT clustering is greedy, so what is considered as the best feature group in each step potentially depends on the previous steps, so it matters whether you can look at all of the data or only at parts of it.

That doesn't mean that it's wrong to apply the algorithm in a hierarchical fashion - especially if you can follow a hierarchical structure in the dataset, e.g. technical replicates -> biological replicates -> different conditions. It means however that you'll get different results, and - considering the same quality measure applied by the algorithm - you should always get the best result on the full data.

**Comment by hendrikweisser** [comment]
> It means however that you'll get different results, and - considering the same quality measure applied by the algorithm - you should always get the best result on the full data.

Now that I think about it, since the algorithm is greedy there is actually no guarantee of this. However, normally it should be the case.

**Comment by mcapuccini** [comment]
@hroest and @hendrikweisser thanks! I'll give it a try since it doesn't cost anything I guess, but it's good to know that the results are most likely not going to be consistent. 

Is there any tool in OpenMS that can split the data in a way that allows to do feature liking on different machines?

**Comment by hannesveit** [comment]
@mcapuccini no, there's no such tool yet. It would be straightforward to make one, though, using the m/z partitioning idea that @hroest mentioned earlier (https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/ANALYSIS/MAPMATCHING/QTClusterFinder.cpp#L133). However, I'm not sure if this would save you a significant amount of resources compared to using FLQT with the partitioning approach on a single machine. How big are your data sets?

**Comment by mcapuccini** [comment]
I think this can be closed :)
