### ISSUE TITLE
travis fails to upload log

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2191]
If the build of the OpenMS library fails, then travis will not upload a log file to cdash, see for example https://travis-ci.org/OpenMS/OpenMS/builds/163158681

apparently, travis terminates the build if too much output is generated. We would have to either
- abort and upload the log to cdash without attempting to run the tests
- reduce the verbosity of the failed tests (e.g. dont print where you were looking for the test file)

**Comment by hendrikweisser** [comment]
@jpfeuffer: Is this issue still relevant? (If not, please close.)

**Comment by jpfeuffer** [comment]
This should be still an issue I think.
It could be as easy as adding another ctest_submit right after the build step:
https://github.com/OpenMS/OpenMS/blob/develop/tools/travis/cibuild.cmake#L92

But needs to be tested. Maybe some parameters are necessary there.
