### ISSUE TITLE
upgrade Cython on cdash

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2192]
right now, pyopenms builds fail on cdash. I think upgrading Cython to 0.23 should resolve the issue...

**Comment by hroest** [comment]
basically these errors are generated by a problem with Cython < 0.23:

```
/.../HEAD/src/pyOpenMS/pxds/SpectrumAccessQuadMZTransforming.pxd:14:41: no matching function for call to SpectrumAccessTransforming::SpectrumAccessTransforming()

/.../HEAD/src/pyOpenMS/pxds/Modification.pxd:10:21: no matching function for call to SampleTreatment::SampleTreatment()
```

it has something to do with how Cython handles abstract base classes (which both of these have)

**Comment by jpfeuffer** [comment]
I just upgraded machine to Cython 0.24.

**Comment by hroest** [comment]
thanks, lets see whether it works!

**Comment by jpfeuffer** [comment]
Argh.. I am on a seminar right now and forgot that they had a planned power shutdown at university yesterday. I will try to set the machine(s) up again after my colleagues started them.

**Comment by timosachsenberg** [comment]
is this resolved?
