### ISSUE TITLE
TOPPAS failed to build correct filenames

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2200]
I've run into an issue with a TOPPAS pipeline, which gives me the following error when I try to run it:

> ERROR: IDFilter failed!
> TOPPAS failed to build correct filenames. Please report this bug, along with your Pipeline
> !

An example pipeline is here: https://gist.github.com/hendrikweisser/eb22315020966ea75179cf188e00a9fc
What I want to do is filter every file in input 2 according to every whitelist in input 1. To make this work I included every file [number of files in input 1] times in input 2. Unfortunately TOPPAS doesn't like it.

**Comment by cbielow** [comment]
Jep. That;s a problem, but the optimal solution is not straight forward IMHO.

One could
1) let TOPPAS solve it (by appending a unique suffix to the filename for example), but this requires work (implementation) and has the disadvantage that identical files are processed twice -- depending on the pipeline.

2) let the user handle it, i.e. process the files until the duplication is required and duplicate them manually. This way, you can also control the renaming scheme.

Currently, 2) is your only option.

Do you see any other applications for this use case? It seems a rather special case.

**Comment by timosachsenberg** [comment]
I think KNIME could handle this if this is an option

**Comment by hendrikweisser** [comment]
> 1) let TOPPAS solve it (by appending a unique suffix to the filename for example), but this requires work (implementation) and has the disadvantage that identical files are processed twice -- depending on the pipeline.

Yes, that's what I was after. Regarding "the disadvantage that identical files are processed twice" - I would assume the user has a reason if they do that.
