### ISSUE TITLE
contributing guidelines

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2203]
hey, did you see that we now have "guidelines for contributing" ?

![screenshot from 2016-09-30 15 44 07](https://cloud.githubusercontent.com/assets/464014/19009112/68c3437e-8725-11e6-8fde-156d7a20eeba.png)

however, they are not yet very ... sophisticated ... as this is the first thing a new developer sees when opeing a PR we should think about this some more: 

https://github.com/OpenMS/OpenMS/blob/develop/CONTRIBUTING.md

**Comment by timosachsenberg** [comment]
I updated it a bit in https://github.com/OpenMS/OpenMS/pull/2226
Do we also want to directly link to the "how to create commit messages" and related topics in the developer wiki that are relevant when opening a pull request.
We could also suggest that "Allow edits from maintainers" need to be checked

**Comment by hroest** [comment]
>  Do we also want to directly link to the "how to create commit messages" and related topics in the developer wiki that are relevant when opening a pull request.

yes, I think this is what I would expect in such a "guidelines" document

**Comment by mwalzer** [comment]
> however, they are not yet very ... sophisticated ...
I guess it would be good though to get not too sophisticated to avoid TL;DR reactions
Linking out to a more elaborate document seems a valid option here. GitHub md supports that.

**Comment by hendrikweisser** [comment]
The guidelines look fine to me and there hasn't been any more discussion here. Closing.
