### ISSUE TITLE
FeatureLinkerUnlabeledQT -nr_partitions has impact on results when ppm is used for m/z tolerance

### ISSUE THREAD

**Issue by hannesveit** [OpenMS/OpenMS#2206]
On a dataset with 15 maps and m/z tolerance set to 20 ppm, I get different results for different values of -nr_partitions.

For 50 partitions, I get 14145 consensus features of size 15, for 100 partitions I get 14130, and for 9999 partitions I get only 9014.

At first glance, it looks as if the reason might be the following call of setParameters(): https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/ANALYSIS/MAPMATCHING/QTClusterFinder.cpp#L106

which leads to max_diff_mz_ being computed as my_ppm_tol * max_mz * 1e-6, where max_mz = 1.

**Comment by hannesveit** [comment]
fixed by #2207

**Comment by hroest** [comment]
@hannesveit did you verify that the bug is gone after the fix?

**Comment by hannesveit** [comment]
@hroest I did. Works as expected with ppm now.
