### ISSUE TITLE
INFO:root:attach to QcMLFile: errorString triggers error in test

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2216]
probably a refined check needs to be introduced.
@jpfeuffer I think this was also pointed out by you

**Comment by timosachsenberg** [comment]
From CDASH:
Site: microcebus.imp.fu-berlin.de
Build Name: mac-osx-10.8-clang-5.0-LLVM3.3svn-Unix_Makefiles-Release
Build Time: 2016-10-04T04:43:25 CEST
Found 2 Errors
Warnings are here.

Build Log Line	2600
Error	
 INFO:root:attach to QcMLFile: errorString

Build Log Line	2601
Error	
 INFO:root:attach to QcMLFile: error
 INFO:root:add_inherited_methods for QcMLFile
INFO:root:attach to QcMLFile: getVersion
INFO:root:add_inherited_methods for QcMLFile
INFO:root:attach to QcMLFile: getLogType
INFO:root:attach to QcMLFile: startProgress
INFO:root:attach to QcMLFile: setProgress
INFO:root:attach to QcMLFile: setLogType
INFO:root:attach to QcMLFile: endProgress
INFO:root:resolve_inheritance for QualityParameter
INFO:root:resolve_inheritance for QTCluster

**Comment by timosachsenberg** [comment]
@hroest do you know where this is generated?

**Comment by hroest** [comment]
@timosachsenberg this is a log message produced by the build process that cdash (erroneously) interprets as error as it contains the string "error"

**Comment by timosachsenberg** [comment]
Sorry I meant: do you know if this is generated in the pyOpenMS part (or e.g. doxygen). But no worries I can look it up.

**Comment by timosachsenberg** [comment]
this seems to be a duplicate of the "resolved" issue: https://github.com/OpenMS/OpenMS/issues/1893
@jpfeuffer

**Comment by jpfeuffer** [comment]
Yes it occurred as part of the mentioned issue. It is not fixed yet. Good to have a separate issue.
I addressed it right now in the build scripts. Let's see if it works in the nightlies.

**Comment by jpfeuffer** [comment]
Worked. Closing.
