### ISSUE TITLE
Averagine approximation doesn't adjust the # of H's to match the requested mass

### ISSUE THREAD

**Issue by DennisGoldfarb** [OpenMS/OpenMS#2222]
Currently, the approximate number of each element is essentially determined by 
1) Dividing the input average mass by the averagine average mass to determine the number of averagines needed.
2) For each element, multiplying the number of averagines by the corresponding element count in the averagine model.
3) Rounding the results for each element.

The rounding leads to slight differences in approximated average mass vs the input mass.

In the original Senko paper that describes the Averagine method, the number of expected C,N,O,P,S get rounded to integers, and then the remaining mass is filled with H's. In terms of the isotopic distributions that get generated, the differences are pretty minor, but I get slightly better results using the Senko method.

Here are some plots showing the mass differences between the requested mass and approximated mass for human tryptic peptides. The current method in OpenMS can be off by 20 daltons, while the Senko method is dead on for average mass, and can be a little more off for the monoisotopic mass.

![openmsaverage](https://cloud.githubusercontent.com/assets/8868522/19121818/dcc4de1c-8af5-11e6-8ccd-620ca29d55e7.png)
![openmsmono](https://cloud.githubusercontent.com/assets/8868522/19121822/e0738838-8af5-11e6-82a1-c37eb254e1ab.png)
![senkoaverage](https://cloud.githubusercontent.com/assets/8868522/19121826/e31c4020-8af5-11e6-880d-53a2f26f617a.png)
![senkomono](https://cloud.githubusercontent.com/assets/8868522/19121831/e4d47022-8af5-11e6-8523-f06500612c1d.png)

The difference in the resulting approximated isotopic distributions is very minor, but it is an improvement. I calculated pearson's correlation, chi-squared, and total variation distance (i.e. sum(abs(Xi-Yi)) ) between the exact isotope distribution and the approximate isotope distribution for human tryptic peptides (excluding peptides containing selenocysteines).

OpenMS:
pcc: 0.99882353
chi-sqr: 0.00841315
TVD: 0.04444828

Senko:
pcc: 0.998829488 (ever so slightly better)
chi-sqr: 0.008321031 (ever so slightly better)
TVD: 0.044294637 (ever so slightly better)

And I ran a HeLa lysate through FeatureFinderCentroided using the two methods.

OpenMS:
Found 206581 seeds for charge 1.
Found 30000 feature candidates for charge 1.
Found 137120 seeds for charge 2.
Found 26797 feature candidates for charge 2.
Found 56734 seeds for charge 3.
Found 8269 feature candidates for charge 3.
Found 8560 seeds for charge 4.
Found 764 feature candidates for charge 4.
Removed 26460 overlapping features.
39370 features left.

Abort reasons during feature construction:
- Could not extend seed: 82063
- Could not find good enough isotope pattern containing the seed: 18356
- Feature quality too low after fit: 5072
- Invalid feature after fit - too few traces or peaks left: 120547
- Invalid fit: Center outside of feature bounds: 2366
- Invalid fit: Fitted model is bigger than 'max_rt_span': 31451
- Invalid fit: Less than 'min_rt_span' left after fit: 33
FeatureFinderCentroided took 18:00 m (wall), 17:56 m (CPU), 0.00 s (system), 17:56 m (user).

Senko:
Found 206552 seeds for charge 1.
Found  29988 feature candidates for charge 1.
Found 137165 seeds for charge 2.
Found  26828 feature candidates for charge 2.
Found  56850 seeds for charge 3.
Found   8285 feature candidates for charge 3.
Found   8640 seeds for charge 4.
Found    769 feature candidates for charge 4.
Removed 26470 overlapping features.
39400 features left.

Abort reasons during feature construction:
- Could not extend seed: 82075
- Could not find good enough isotope pattern containing the seed: 18412
- Feature quality too low after fit: 5094
- Invalid feature after fit - too few traces or peaks left: 120366
- Invalid fit: Center outside of feature bounds: 2365
- Invalid fit: Fitted model is bigger than 'max_rt_span': 31663
- Invalid fit: Less than 'min_rt_span' left after fit: 35
FeatureFinderCentroided took 17:42 m (wall), 17:38 m (CPU), 0.00 s (system), 17:38 m (user).

Again, a very minor improvement that went from 39370 features to 39400.

I can submit a pull request with the senko method, but it currently breaks a few tests that rely on the approximation. This is because those functions were difficult to test and appear to be compared against the results of the current averagine method, which are now slightly different and need to be updated. Please let me know what you think, thanks!

**Comment by hroest** [comment]
Probably @cbielow is the best person to answer this but I am definitely in favour of correcting the method. Please create the PR and we can discuss the failing tests, possibly we can just change the tests in case they are just black-box tests / regression tests. In this case it is completely fine to change the tests :-)

**Comment by cbielow** [comment]
The improvements are visible, so im in favour of using the new scheme.
However, the inaccuracies in intensity of real world data are probably the biggest contributor to bad matches.

Also, there is the fractional averagine approach (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2655099/#__sec19title) by Renard and Kirchner. It's computationally a little more expensive, but could be a marked improvement.

**Comment by timosachsenberg** [comment]
just for reference: The original link to the source code was broken. Its now located at: https://hci.iwr.uni-heidelberg.de/hci/softwares/nitpick
