### ISSUE TITLE
TOPPView help does not work

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2233]
Currently TOPPView (2.0.1) help links to http://www.openms.de/current_doxygen/html/index.html which is a 404. This is pretty bad as this link seems to be hardcoded in TOPPView

**Comment by jpfeuffer** [comment]
I added a quick redirect to the website but this should be additionally fixed in TOPPView.
I think e.g. your OpenMS2.0 paper links to www.openms.de/documentation. Maybe we should introduce this short link as the standard from now on.

**Comment by hroest** [comment]
yes, it works now. The issue is that people install TOPPView once and if the link suddenly stops working then it is a big issue for them. So we have to be backwards compatible here.

sure, I think www.openms.de/documentation makes more sense
