### ISSUE TITLE
Deployment on 32 bit / 64 bit platforms

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2247]
We are currently facing the problem that third-party executables are not provided for 32-bit versions (e.g. tandem on windows).
While I think it is a good idea to support 32bit on the library level for some additional time it might be a good idea to restrict our deployment to 64bit platforms.
Please post your opinions here.

**Comment by hendrikweisser** [comment]
What are the differences between the 32 and 64 bit versions on the library level?

**Comment by timosachsenberg** [comment]
here we don't have additional maintenance effort. for deployment we would need to compile our own executables

**Comment by timosachsenberg** [comment]
looking at our update statistics it seems that 32 bit are not used at all (though it's only since 2.0.1 - half a year after it has been enabled)

**Comment by hendrikweisser** [comment]
> looking at our update statistics it seems that 32 bit are not used at all

Based on what sample size is that? (How many OpenMS installations that report statistics?)

**Comment by hendrikweisser** [comment]
> Based on what sample size is that? (How many OpenMS installations that report statistics?)

That's just out of interest, by the way.

I agree with the suggestion - provide binaries only for 64 bit, as long as people can still build OpenMS themselves on 32 bit if necessary.

**Comment by timosachsenberg** [comment]
I will try to come up with a better script to do the analysis (right now I just do some grep and sort while removing some of the obvious ips). From external, there were only about a dozen using 2.0.1 in October.

**Comment by cbielow** [comment]
IMHO 32bit support must be kept at the CI-level -- when porting from 32 to 64 bit we found some interesting bugs. I strongly suspect the same it true vice versa, so keeping 32bit seems essential to me (for the time being).
Concerning 32bit deployment: we could potentially clean up a lot of biolerplate code if we remove 32bit support -- and I see no good reason to keep it.

**Comment by lars20070** [comment]
+1 (no support for 32bit deployment necessary)

**Comment by mwalzer** [comment]
I agree with what many other SW vendors are doing - ditching their 32bit stuff. We have our hands full with platform support as is without deprecated architectures. @cbielow raises a good point, though. 

Assuming we ditch support, this would mean minimal invasion, right? Keep the builds for debug usage on all architectures (no action needed) and just do not link/bundle the 32bit builds.

**Comment by timosachsenberg** [comment]
exactly - we create builds of our OpenMS libraries and executables for 32 bit but don't ship full installers that include third-party software

**Comment by mwalzer** [comment]
:+1:

**Comment by hroest** [comment]
I agree, we should still run tests and builds on 32bit but not ship full installers. If people need 32 bit executables, there are older versions which they can download.

**Comment by timosachsenberg** [comment]
ok so we decided to only ship 64 bit but still support 32 bit
