### ISSUE TITLE
InternalCalibration: Problems with R scripts

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2251]
I'm having some trouble with the functionality for generating quality control plots using R scripts in InternalCalibration.

First, I tried running it on a server that had the "Rscript" executable, which however turned out to be broken (due to a missing library). The log messages in that case were confusing:
```
Could not find 'Rscript' executable. Make sure it's in your system path and try again.

Calibration failed. See error message above!
Running R script '/nfs/t17_project/OpenMS/share/OpenMS/SCRIPTS/InternalCalibration_Models.R' ...
```
The first problem is that the "Running R script" message should not appear if "Rscript" didn't work. The second problem is that the output of trying to run "Rscript" is not available, which makes it hard to diagnose what the problem is without digging through the OpenMS code.
The third (minor) problem is that the calibration actually worked, only generating the quality control plot didn't, so "Calibration failed" is not really true.

I then moved to a server with a functioning "Rscript", where the first quality control plotting script ran through successfully and generated the "models" plot:
`Running R script '/nfs/t17_project/OpenMS/share/OpenMS/SCRIPTS/InternalCalibration_Models.R' ... success`
However, after that the process stalled, there was no further log output, and I stopped it after about an hour. A PNG file for the "residuals" plot was created, but was completely white.

**Comment by cbielow** [comment]
I'll look into it

**Comment by cbielow** [comment]
> The first problem is that the "Running R script" message should not appear if "Rscript" didn't work.

mhh.. well,  `Running R script ...` should be read as `About to run an R script ..` but ok, I'll fix it.

>The second problem is that the output of trying to run "Rscript" is not available, which makes it hard to diagnose what the problem is without digging through the OpenMS code.

If `Rscript` is present or broken (i.e. cannot be invoked) there is no error proper way to tell why exactly this is (at least on Windows, no QtProcess stream will contain any information). The error message in a fixed version will say 
```Finding R interpreter 'Rscript' ... failed
Error: Could not find or run 'Rscript' executable (FailedToStart).
Please install 'Rscript', make sure it's in PATH and is flagged as executable.```

> The third (minor) problem is that the calibration actually worked, only generating the quality control plot didn't, so "Calibration failed" is not really true.

Well, again... if you requested a QC plot, and did not get one, I'd consider calibration failed. Also when considering workflow systems which expect the output to be present, this is a fail.

For all the above I've prepared a fix which provides better error messages, but I'll wait with a PR until:

> However, after that the process stalled, there was no further log output, and I stopped it after about an hour. A PNG file for the "residuals" plot was created, but was completely white.

Can you give more details here? Was R still running?

**Comment by hendrikweisser** [comment]
Thanks for looking into it, Chris.

> mhh.. well, Running R script ... should be read as About to run an R script .. but ok, I'll fix it.

In RWrapper, just moving the `LOG_INFO << "Running R script '" ...` line after the `if (!findR())` block would be fine.

> If Rscript is missing or broken (i.e. cannot be invoked) there is no proper way to tell why exactly this is (at least on Windows, no QtProcess stream will contain any information).

In my case, running `Rscript --vanilla -e "sessionInfo()"` on the command line gave:
> /software/R-3.1.2/lib/R/bin/exec/R: error while loading shared libraries: libicuuc.so.48: cannot open shared object file: No such file or directory
I think it should be possible to capture that via Qt, but don't know how.

> Can you give more details here? Was R still running?

I haven't checked. Would you expect that script to take a long time if a large file (~30,000 peptide hits) is passed via "cal:id_in"?

**Comment by cbielow** [comment]
In my case, running Rscript --vanilla -e "sessionInfo()" on the command line gave:

> /software/R-3.1.2/lib/R/bin/exec/R: error while loading shared libraries: libicuuc.so.48: cannot open shared object file: No such file or directory
> I think it should be possible to capture that via Qt, but don't know how.

Ok, I capture the output, but that needs testing on Linux to see if it works. Don't fix your system :)

> I haven't checked. Would you expect that script to take a long time if a large file (~30,000 peptide hits) is passed via "cal:id_in"?

Mhh... ggplot is slow, but not that slow. Can you send me the output table which R reads?
Alternatively, please check again if its R or C++ which causes the stalling. My guess is R, since you have an empty PNG, but just to make sure.

**Comment by hendrikweisser** [comment]
> Mhh... ggplot is slow, but not that slow. Can you send me the output table which R reads?
Alternatively, please check again if its R or C++ which causes the stalling. My guess is R, since you have an empty PNG, but just to make sure.

R is running (and using more and more memory: ~600 MB after 6 minutes), so I guess it's a problem with the script.
I'm going to email you the CSV file.

**Comment by hendrikweisser** [comment]
R is still running after half an hour, using almost 2 GB of memory now.

**Comment by cbielow** [comment]
problem of long run time is fixed.
Nice data btw :)
![image](https://cloud.githubusercontent.com/assets/6008722/19679104/e1c379ea-9aa0-11e6-9d8f-9f3aec6660fa.png)

**Comment by hendrikweisser** [comment]
> problem of long run time is fixed.
> Nice data btw :)

Thanks, Chris. (The data is from the iPRG-2015 study: https://abrf.org/research-group/proteome-informatics-research-group-iprg)
