### ISSUE TITLE
Implement De Novo Peptide Search

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2265]
In mass spectrometry, de novo peptide sequencing is the method in which a peptide amino acid sequence is determined from tandem mass spectra.

Knowing the amino acid sequence of peptides from a protein digest is essential to study the biological function of the protein. Today, analysis by a tandem mass spectrometer is the most common method to solve the sequencing of peptides. Generally, there are three approaches: database search, spectral library search and de novo sequencing. Database search and spectral library search finds a match with a known peptide sequence or previously measured spectrum. De novo sequencing is an assignment of fragment ions from a mass spectrum without knowledge on the database. 

In OpenMS there are some implementations of de novo search engines that might be worth to reevaluate in a student project.

**Comment by lars20070** [comment]
Anyone currently working on de-novo sequencing? Evaluation of our existing algorithms and comparison to other external tools would be interesting for us. Perhaps we could collaborate.

**Comment by timosachsenberg** [comment]
No currently we have nobody assigned to this project. Once an adapter is available We could help with integrating the executables into the packages and knime  builds.

**Comment by lars20070** [comment]
Ok. Thanks @timosachsenberg.
More IDs than `PEAKS` and 10x faster very sounds interesting.

**Comment by hroest** [comment]
seems to make sense to create an adaptor but it also does not seem to be open-source, see https://www.rapidnovor.com/download/ so we cant really distribute it as far as I can tell

**Comment by hroest** [comment]
@lars20070 @timosachsenberg lets move discussion of writing adapters to existing de novo search engines over here: #2266
