### ISSUE TITLE
Integrate De Novo Peptide Search

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2266]
In mass spectrometry, de novo peptide sequencing is the method in which a peptide amino acid sequence is determined from tandem mass spectra.

Knowing the amino acid sequence of peptides from a protein digest is essential to study the biological function of the protein. Today, analysis by a tandem mass spectrometer is the most common method to solve the sequencing of peptides. Generally, there are three approaches: database search, spectral library search and de novo sequencing. Database search and spectral library search finds a match with a known peptide sequence or previously measured spectrum. De novo sequencing is an assignment of fragment ions from a mass spectrum without knowledge on the database.

In addition, one could think about wrapping existing de novo engines like novor.

**Comment by timosachsenberg** [comment]
Publication:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4604512/
Binaries: (free for academic use)
https://www.rapidnovor.com/novor-cmd/

**Comment by hroest** [comment]
Alternatively we could use deepnovo:

- Github: https://github.com/nh2tran/DeepNovo
- Paper: http://www.pnas.org/content/114/31/8247.abstract

it seems they perform equal/better than rapidnovor and substantially better than PEAKS

**Comment by Leon-Bichmann** [comment]
I had a look at Novor to integrate it during the EuBic2018 meeting:

- I guess the advantage of Novor over DeepNovo, is its super fast runtime ( 300 spectra / second)
- However its accuracy is worse than DeepNovo
- The executable is a jar file
- A handful of parameters can be passed in a parameter.txt file:
  - enzyme = Trypsin   (**Disadvantage: Enzyme only trypsin is supported currently**)
  - fragmentation = CID   (CID, HCD)
  - massAnalyzer = Trap   (Trap, TOF, FT)
  - fragmentIonErrorTol = 0.5Da
  - precursorErrorTol = 15ppm
  - variableModifications = Oxidation (M)   (comma-delimited list of IDs can be used here)
  - fixedModifications = Carbamidomethyl (C) (See http://rapidnovor.com/wiki/Built-in_PTMs)
  - forbiddenResidues = I,U
  - novorFile = external.novor (a customized ML param set can be used trained on special data)

**Comment by timosachsenberg** [comment]
DeepNovor seems also allow non commercial use only. According to their github it seems also that they did not reach a state to be useful / robust for general data.

**Comment by hroest** [comment]
> I guess the advantage of Novor over DeepNovo, is its super fast runtime ( 300 spectra / second)

sounds good to me

> However its accuracy is worse than DeepNovo

I wonder whether that is true on all types of data or only if the data is very similar to the training data. Did you compare the results yourself or is this based on their paper?

> The executable is a jar file (free academic licence)
> Input are mgf files

that sounds both very promising. 

> licence

I guess the licence situation is equally bad with both projects, right? No real free licence in either one?

**Comment by Leon-Bichmann** [comment]
Example output of novor:

```
#=================== N-O-V-O-R ===================
#   NOVOR: Real-time Peptide de Novo Sequencing   
#              v1.06.0634 (stable)
#             Free Academic License               
#============== www.rapidnovor.org ===============
#
# This result file was generated by a free academic license of Novor software at 2018-01-04 15:34:07
# and can be used for educational and academic research purposes only.

# input file = test.mgf
# enzyme = Trypsin
# fragmentation = CID
# massAnalyzer = Trap
# fragmentIonErrorTol = 0.5Da
# precursorErrorTol = 15ppm
# fixedModifications = Carbamidomethyl (C)
# variableModifications = Oxidation (M)
# forbiddenResidues = I, U

# id, scanNum, RT, mz(data), z, pepMass(denovo), err(data-denovo), ppm(1e6*err/(mz*z)), score, peptide, aaScore, 
1, 0, 786.8, 630.2375, 2, 1258.4772, -0.0168, -13.3, 14.6, C(Cam)DDGYSTEGQK, 32-1-1-1-2-1-1-33-3-30-37
2, 0, 787.2, 492.2714, 2, 982.5382, -0.0100, -10.1, 16.6, LC(Cam)VTHVVR, 24-34-30-3-5-9-19-10
3, 0, 789.9, 647.8013, 2, 1293.5733, 0.0148, 11.4, 13.5, GNYLYTASMM(O)K, 2-11-11-1-1-1-2-55-4-30-37
4, 0, 790.7, 610.1832, 2, 1218.4935, -0.1416, -116.0, 2.3, M(O)EGGGAAPGDDAR, 12-1-1-1-2-1-1-1-2-1-1-1-14
```

**Comment by timosachsenberg** [comment]
Cool looks rather simple to parse. Good task for the short time we have on the hackathon

**Comment by timosachsenberg** [comment]
Successor of DeepNovo:
https://github.com/nh2tran/DeepNovo-DIA

**Comment by timosachsenberg** [comment]
we have NovorAdapter
