### ISSUE TITLE
Integrate De Novo Identification (Small Molecules / Metabolomics)

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2268]
De novo identification of metabolites has matured to the point that user would greatly benefit from methods that go beyond accurate mass search.

CSI:FingerID (Compound Structure Identification: FingerID) is a method for searching a tandem mass spectrum of a small molecule (metabolite) in a database of molecular structures. 
It provides an offline module for molecular formula determination (based on combinatorial fragmentation trees) and an online module for online database search.

It would be great to wrap the command line java application in OpenMS.

Details on the method can be found in the publications:
Kai Dührkop, Huibin Shen, Marvin Meusel, Juho Rousu, and Sebastian Böcker
Searching molecular structure databases with tandem mass spectra using CSI:FingerID
PNAS 2015 ; published ahead of print September 21, 2015, doi:10.1073/pnas.1509788112

Huibin Shen, Kai Dührkop, Sebastian Böcker and Juho Rousu.
Metabolite Identification through Multiple Kernel Learning on Fragmentation Trees.
Bioinformatics, 30(12):i157-i164, 2014. Proc. of Intelligent Systems for Molecular Biology (ISMB 2014).

**Comment by hroest** [comment]
:+1:

**Comment by oliveralka** [comment]
The integration of SIRIUS will be updated with the release of a new SIRIUS Version in the future. In general, the integration can be labelled as finished.
