### ISSUE TITLE
InternalCalibration: Rscript not found in 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2269]
To be confirmed on Windows:

Current KNIME installer: http://update.knime.org/community-contributions/trunk/
Fails on execution of Rscript.

Failing process stderr: [Error: Could not find or run 'Rscript' executable (FailedToStart)., Please install 'Rscript', make sure it's in PATH and is flagged as executable., The R interpreter is required to create PNG plot files. To avoid the error, either do not request 'quality_control:*_plot' (not recommended) or fix your R installation., , Calibration failed. See error message above!]

RScript is in path and can be executed from any folder in the command prompt

**Comment by jpfeuffer** [comment]
With "in the path" you mean in the PATH environment variable of the system?
Because this would not be recognized by KNIME. KNIME reads the PATH from the binaries.ini.

**Comment by timosachsenberg** [comment]
snap... I though it appends it. but you are right. I think we need to expose the executable as parameter

**Comment by timosachsenberg** [comment]
I can do this

**Comment by jpfeuffer** [comment]
There were problems with e.g. the OpenMS Data Path, if we let it append it. Maybe we can find a solution that works with both at some point.

**Comment by timosachsenberg** [comment]
possibly fixed with https://github.com/OpenMS/OpenMS/pull/2270

**Comment by cbielow** [comment]
is this fixed now?
close?

**Comment by timosachsenberg** [comment]
tested and works now
