### ISSUE TITLE
MzIdentMLFile class test fails under VS2015

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#2274]
After building OpenMS under VS2015 (debug mode) in Windows Server 2012, the `MzIdentMLFile` class test fails as seen in the screenshot below.

![screenshot from 2016-10-31 16-56-06](https://cloud.githubusercontent.com/assets/6149805/19882929/80d23222-a011-11e6-93b7-810054f19580.png)

**Comment by timosachsenberg** [comment]
Hi. Can you provide the stack trace? For the other issues as well ...

**Comment by hendrikweisser** [comment]
@lars20070: Is this ticket still relevant? Please close if not.

**Comment by lars20070** [comment]
I did not build under Windows since then. But I close.
