### ISSUE TITLE
Make LogStream thread-safe

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#2275]
After building OpenMS under VS2015 (debug mode) in Windows Server 2012, the `LogStream` class test fails as seen in the screenshot below.

![screenshot from 2016-10-31 17-01-41](https://cloud.githubusercontent.com/assets/6149805/19883008/f1582f1a-a011-11e6-8d2c-8c6c8fea1e04.png)

**Comment by timosachsenberg** [comment]
@lars20070 is this still an issue? if yes could you debug into it and post the stack trace?

**Comment by jpfeuffer** [comment]
I don't know what exactly changed but we get this now too on our build machines. Seems to be an OpenMP problem.

**Comment by timosachsenberg** [comment]
maybe change
#pragma omp parallel
to
#pragma omp parallel for
?

**Comment by timosachsenberg** [comment]
hmm locking at the code more closely, there seem to be some
critical sections missing.
E.g. LogStreamBuf::overflow doesn't seem to be thread safe etc.

**Comment by jpfeuffer** [comment]
Hm yes maybe (but did you see that it calls sync, which is critical? I'm not very trained in parallel programming though)
But the pragma seems definitely wrong doesn't it? What does just parallel do with the for loop?

**Comment by hendrikweisser** [comment]
Let's assume this got fixed in #3126 and close this ticket until we hear otherwise.
