### ISSUE TITLE
PepXMLFile class test fails under VS2015

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#2276]
After building OpenMS under VS2015 (debug mode) in Windows Server 2012, the `PepXMLFile` class test fails as seen in the screenshot below.

![screenshot from 2016-10-31 17-26-08](https://cloud.githubusercontent.com/assets/6149805/19883046/28ca9488-a012-11e6-8069-b9af5a2429b9.png)

**Comment by hroest** [comment]
can you press "retry" to start debugging? this hopefully helps us to figure out where the problem occurs

**Comment by hendrikweisser** [comment]
@lars20070: Is this ticket still relevant? Please close if not.

**Comment by lars20070** [comment]
I did not build under Windows since then. But I close.
