### ISSUE TITLE
GenericWrapper chokes on 'required' Input/Output-Lists

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#2277]
reported by Mike Rightmire on mailing list:

>In the previous *.ttd file (see previous email reply) is I set 'required' to true (as in):
> <ITEMLIST name="in" type="input-file" description="Input file(s) separated by blanks. 
> MGF files are required." required="true" advanced="false"></ITEMLIST>
>
> ... OpenMS chokes on the GenericWrapper with the error message that the 'file does not exist' (even 
> though it does exist). If I set it to 'false' the Python script runs fine (using the file locations passed in).

**Comment by cbielow** [comment]
The reason for the bug is that File:exists() is called on the value of the parameter. In case of a StringList, the concatenated String is checked, i.e. `[fileA, fileB]', which does not exist...

**Comment by hendrikweisser** [comment]
Nice find, Chris!

**Comment by cbielow** [comment]
@rightmirem

**Comment by cbielow** [comment]
slightly off topic:

@rightmirem, I modified you ttd a little (removing file-post moving instructions.... they were dead code IMHO) and added 'require' attributes to your parameters. If you use the bugged version of GW, change to 'false' for the ITEMLIST. The other single files however, can carry the 'true'. no matter the OpenMS version -- its much safer this way, since GenericWrapper will check and warn if the input/output is missing, so you don't have to wait for Python to tell you something is wrong.

```<ttd>
    <tool status="external">
        <category>does not really matter</category>
        // multiple of these are allowed
        <type>maracluster_python</type>
        #name# -- for internal only
        // multiple of these allowed (same # as 'types') - for external only
        <external>
                <text>
                    <onstartup>STarting maracluster_python</onstartup>
                    <onfail>Something went wrong.</onfail>
                    <onfinish>Tool finished successfully.</onfinish>
                </text>
            <e_category>Postprocessing</e_category>
            <cloptions>"%1" --input %2 --out "%3"</cloptions>
            <path>python</path>
            <mappings>
                <mapping id="1" cl="%%file_script" />
                <mapping id="2" cl="%%in" />
                <mapping id="3" cl="%%out" />
            </mappings>
            <ini_param>
                <ITEM name="file_script" value="" type="string" description="input Python script" tags="input file" required="true"/>
                <ITEMLIST name="in" type="input-file" description="Input file(s) separated by blanks" required="true" advanced="false"></ITEMLIST>
                <ITEM name="out" value="" type="string" description="Output file which your R script writes to" tags="output file" required="true" />
            </ini_param>
        </external>
    </tool>
</ttd>```
