### ISSUE TITLE
Windows installer architecture

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#2281]
Is the installer a bit confused about the architecture?
I came across this during the installer tests on a mint win8.1
![media-20161020](https://cloud.githubusercontent.com/assets/5859205/20008796/3c4b9e7a-a2a2-11e6-95e1-d01a7fa087bd.png)
![media-20161104](https://cloud.githubusercontent.com/assets/5859205/20008797/3c4f28d8-a2a2-11e6-8686-ed41e03e5090.png)

**Comment by mwalzer** [comment]
Seems that this does not affect functionality in my tests. Might be different for high-memory demanding use-cases?
Or is this just a hard coded and deprecated string somewhere in the installer build?

**Comment by jpfeuffer** [comment]
I am not sure but it could be that the architecture in parenthesis is added by Windows itself and comes from the fact, that the installer is a 32bit program?
Does everything work after installation?

**Comment by mwalzer** [comment]
Yes, tests seemed fine.

**Comment by cbielow** [comment]
Don't worry.
As jpfeuffer said, its only the NSIS binary which is 32bit.
To determine if the OpenMS binaries are 32 or 64 bit, just run `objdump -a "drive:\path\to\OpenMS.dll"`

(or see #2283)

**Comment by cbielow** [comment]
closing, since seems to resolved?!
