### ISSUE TITLE
Apply PeptideIndexer to feature/consensusXML?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2284]
Is there a workaround to apply the PeptideIndexer to feature or consensusXML?
I know that I could extract the IDs from them but how can I put the annotation back to the features?

**Comment by hendrikweisser** [comment]
Incidentally, I had the same problem recently, but couldn't think of a workaround within OpenMS. (I ended up using PeptideIndexer on a merged idXML file and adding the proteins to peptides after data export in R.)

Is there a reason why you can't use PeptideIndexer earlier in your pipeline, before you annotate the features with IDs?

**Comment by hendrikweisser** [comment]
> Is there a workaround to apply the PeptideIndexer to feature or consensusXML?

There seems to be no way to do this at the moment, but having the ability would be useful. I'll turn this ticket into a feature request.
