### ISSUE TITLE
[OpenMS 2.1.0] PyOpenMS compilation error

### ISSUE THREAD

**Issue by sagitter** [OpenMS/OpenMS#2286]
Hi all.

`pyOpenMS` does not compile with this error:

```
pyopenms/pyopenms.cpp:54469:111: error: no matching function for call to 'OpenMS::InternalCalibration::applyTransformation(boost::shared_ptr<OpenMS::MSSpectrum<> >::element_type&, boost::shared_ptr<OpenMS::MZTrafoModel>::element_type&)'
     OpenMS::InternalCalibration::applyTransformation((*__pyx_v_spec->inst.get()), (*__pyx_v_trafo->inst.get()));
                                                               
```               

OpenMS 2.1.0
Fedora 26 64-bit
GCC 6.2.1
Boost 1.60.0
Full log: https://kojipkgs.fedoraproject.org//work/tasks/5839/16355839/build.log

**Comment by hroest** [comment]
this is probably due to 67751af0264365cf1228a93305ed434889b2762d in #2272 

I will have a look at it and propose a fix

**Comment by sagitter** [comment]
Error fixed for me; however I can't complete `pyopenms` build for a `virtual memory exhausted: Operation not permitted`. Can i do something to fix this issue?

Build log: http://koji.fedoraproject.org/koji/getfile?taskID=16384161&name=build.log

**Comment by hroest** [comment]
there is currently not much we can do, it takes about 5 -6 GB of memory to build
