### ISSUE TITLE
pyopenms builds for 2.1 Release

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2288]
For 2.1 I believe I will be able to make the pyopenms builds for Windows and Linux. However for OSX we would need some volunteers as I am not familiar with the platform. Maybe @uweschmitt @grosenberger or others are interested?

**Comment by mortonjt** [comment]
Possibly relevant - is there any interest in creating a [conda recipe](https://conda-forge.github.io/)?  conda is compatible with Windows, Linux and OSX, and makes it really easy to deploy in a new environment.

**Comment by jpfeuffer** [comment]
I think this is a great idea, however, since I saw that conda is using the usual suspects when it gets to CI (Travis, Appveyor, ...), I doubt they will handle our pyOpenMS builds without reaching their time/memory limits but we would have to see.

**Comment by grosenberger** [comment]
I can build the OS X builds for the shipped version of python. This should be compatible with OS X 10.9 - macOS 10.12.

**Comment by hroest** [comment]
I also dont think we can do conda recipes due to the memory constrains that these CI have

@jpfeuffer however if we can get it to work with our nightly build infrastructure where we already build a nightly OS X version, maybe that would work? what do you think?

**Comment by grosenberger** [comment]
I built the pyOpenMS wheel for macOS on a native system, see attachment:
[pyopenms-2.1.0-cp27-cp27m-macosx_10_12_intel.whl.zip](https://github.com/OpenMS/OpenMS/files/613776/pyopenms-2.1.0-cp27-cp27m-macosx_10_12_intel.whl.zip)

By unpacking and renaming this file to pyopenms-2.1.0-cp27-cp27m-macosx_10_9_intel.whl, this binary should be compatible with all recent macOS versions, however, I could only test 10.11 and 10.12.

@uweschmitt Would it be possible to push this to PyPI?

**Comment by uweschmitt** [comment]
I just uploaded the Mac wheels and updated installation instructions. Could you also build the wheel for Python 3.5 and maybe Python 3.4 ?

**Comment by hroest** [comment]
@grosenberger can you quickly state which git hash you used for the build? is it f755ffeb2e82607facf9a6b6429f97d0cc6eefa2  ?

**Comment by hroest** [comment]
@grosenberger @uweschmitt how do we deal with the "phone home" feature in OpenMS - I think that is only for the TOPP tools right? so starting up PyOpenMS is not affected and will not result in a phone call home?

**Comment by grosenberger** [comment]
@hroest Yes, it is https://github.com/OpenMS/OpenMS/commit/f755ffeb2e82607facf9a6b6429f97d0cc6eefa2.
Regarding telemetry: I also thought that this is only relevant for the TOPP tools.

@uweschmitt I will provide the build for Python 3.5.2 from Python.org as well.

**Comment by grosenberger** [comment]
@uweschmitt I encountered a challenge with generating the wheel for Python 3.5.2. Since Python 3.5, it seems that they include tags for extensions: 

> Extension modules now include a platform information tag in their filename on some platforms (the tag is optional, and CPython will import extensions without it, although if the tag is present and mismatched, the extension won’t be loaded): https://docs.python.org/3/whatsnew/3.5.html

Did you by chance encounter and solve this problem already?

**Comment by oliveralka** [comment]
@grosenberger @uweschmitt The installation of pyopenms-2.1.0-cp27-cp27m-macosx_10_9_intel.whl worked fine, but after trying to import pyOpenMS in python I get the following error (any ideas?):
```
ImportError: dlopen(/Library/Python/2.7/site-packages/pyopenms/pyopenms.so, 2): 
Library not loaded: /Users/openms/Downloads/OpenMS/contrib/lib/libz.1.dylib
Referenced from: /Library/Python/2.7/site-packages/pyopenms/libOpenMS.dylib
Reason: image not found
```
Used: Python 2.7.10 (OS X 10.11.6)

**Comment by grosenberger** [comment]
@oliveralka Thanks for reporting. I will have a look, at which step did this happen? Directly after "import pyopenms"?

**Comment by uweschmitt** [comment]
Looks like the `libz.1.dylib` is not included in the wheel.

**Comment by uweschmitt** [comment]
I get

```
$ otool -L libOpenMS.dylib
libOpenMS.dylib:
        /Users/openms/Downloads/OpenMS/lib/libOpenMS.dylib (compatibility version 0.0.0, current version 0.0.0)
        @loader_path/libOpenSwathAlgo.dylib (compatibility version 0.0.0, current version 0.0.0)
        @loader_path/QtNetwork (compatibility version 4.8.0, current version 4.8.7)
        @loader_path/QtCore (compatibility version 4.8.0, current version 4.8.7)
        /Users/openms/Downloads/OpenMS/contrib/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1348.15.0)
        /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 775.8.2)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

Suprisingly I can import `pyopenms` without errors, although the referenced file `libz.1.dylib` does not exist as linked.

**Comment by grosenberger** [comment]
Same for me. I will provide a patched build.

**Comment by oliveralka** [comment]
@grosenberger Just for completeness:
The error on my side appears directly after import of pyopenms.
```
>import pyopenms
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/Library/Python/2.7/site-packages/pyopenms/__init__.py", line 52, in <module> raise e
ImportError: dlopen(/Library/Python/2.7/site-packages/pyopenms/pyopenms.so, 2): Library not loaded: /Users/openms/Downloads/OpenMS/contrib/lib/libz.1.dylib
 Referenced from: /Library/Python/2.7/site-packages/pyopenms/libOpenMS.dylib
 Reason: image not found
```
Thank you for the patch!

**Comment by hroest** [comment]
I have built the Windows wheels here  https://www.dropbox.com/sh/uk5a604xnzy1lxq/AAAfQ2Yuapvd1lXQ3kadJE99a?dl=0 for release 2.1 and if somebody wants to test these it would be great. I could only test 32 bit versions as I dont have a 64bit virtual machine here

**Comment by grosenberger** [comment]
@oliveralka Could you please test whether the attached wheel solves your problem? 
[pyopenms-2.1.0-cp27-cp27m-macosx_10_12_intel.whl.zip](https://github.com/OpenMS/OpenMS/files/622939/pyopenms-2.1.0-cp27-cp27m-macosx_10_12_intel.whl.zip)

**Comment by oliveralka** [comment]
@grosenberger Solved the Problem!

**Comment by grosenberger** [comment]
Great, thanks for checking. @uweschmitt Could you please push the new build to PyPI? Thank you.

**Comment by iprotsyuk** [comment]
I'm getting an error message, when using pyopenms 2.1.0, with both the wheel published on 2016-11-26 on pypi and the one @grosenberger sent to this thread on Nov 30.

`determination of memory status not supported on this

platform, mesauring for memoryleaks will never fail



======================================================================



maybe you miss some libraries. please run ldd (on linux) or

dependency walker (on windows) on



/Library/Python/2.7/site-packages/pyopenms/pyopenms.so



======================================================================



Traceback (most recent call last):

  File "test.py", line 1, in <module>

    import pyopenms as ms

  File "/Library/Python/2.7/site-packages/pyopenms/__init__.py", line 52, in <module>

    raise e

ImportError: dlopen(/Library/Python/2.7/site-packages/pyopenms/pyopenms.so, 2): Library not loaded: /usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Versions/4/QtCore

  Referenced from: /Library/Python/2.7/site-packages/pyopenms/QtNetwork

  Reason: image not found`

For the record, I don't have Qt installed on my mac computer.

Another thing, which probably deserves a separate issue, is the first part of the message `determination of memory status not supported on this

platform, mesauring for memoryleaks will never fail`. It always shows up upon `import pyopenms` in a script on mac. Unfortunately, KNIME shows this message as an error if such a python script is used in a KNIME workflow, and it looks misleading that there's an error in KNIME console, but the workflow continues execution. It'd be nice to suppress this message somehow.

**Comment by hroest** [comment]
@grosenberger can you look into the Qt error?

**Comment by grosenberger** [comment]
Yes, I will look into this issue this week.

**Comment by galeymm** [comment]
@grosenberger did you ever determine what the cause/fix for the Qt error is? I'm encountering this issue.

**Comment by grosenberger** [comment]
As I wrote in the other thread, I unfortunately did not get to fix this yet. It is very strange that it works on some systems but not on all. @oliveralka, is the build still working for you? Are you still on 10.11 or did you upgrade to 10.12 meanwhile?

**Comment by grosenberger** [comment]
I'm trying to fix the issues in PR https://github.com/OpenMS/OpenMS/pull/2821.

**Comment by jpfeuffer** [comment]
This most probably has to be checked for qt5 now.

**Comment by jpfeuffer** [comment]
I'll open a new issue.

**Comment by hroest** [comment]
@grosenberger can you give an update for the 2.3 release and also whether it does / does not work with the new Qt5 branch? We have collected some information here https://github.com/OpenMS/OpenMS/wiki/Preparation-of-a-new-OpenMS-release#pyopenms_release and maybe you could add some wisdom on how to do it on OSX

**Comment by grosenberger** [comment]
I built the 2.3 release version for macOS a few months ago and I believe it is also on PyPI: https://github.com/OpenMS/OpenMS/issues/3202

I'm frequently building pyOpenMS from OpenMS/develop with Qt5 now and this also seems to work so far. With the recently updated scripts by @jpfeuffer, building and deploying on macOS is fully automated now as well. I believe we don't test the macOS builds though, thus sometimes things brake, but usually it's a small fix.

**Comment by hroest** [comment]
@grosenberger  great, maybe you can just edit the wiki document and state the process? Right now it says

Basically build the pyopenms target on OSX and use the src/pyOpenMS/fix_pyopenms_dependencies_on_mac.sh script to fix the builds.
