### ISSUE TITLE
OpenMS-2.1.0 appdata files

### ISSUE THREAD

**Issue by sagitter** [OpenMS/OpenMS#2290]
Hi all.

Image links in `share/OpenMS/DESKTOP/TOPPAS.appdata.xml` and `share/OpenMS/DESKTOP/TOPPView.appdata.xml` are broken.

Please, fix them.

**Comment by jpfeuffer** [comment]
Thanks a lot for reporting. Should be fixed via better redirection rules on our webpage. Can you check?

**Comment by timosachsenberg** [comment]
Please note that the current 2.1.0 tag is not the official one yet but for the pre-release. There might still be small, nearly neglectable changes (e.g. the CHANGELOG).

**Comment by sagitter** [comment]
>Thanks a lot for reporting. Should be fixed via better redirection rules on our webpage. Can you check?

It's okay now.

>Please note that the current 2.1.0 tag is not the official one yet but for the pre-release. There might still be small, nearly neglectable changes (to e.g. the CHANGELOG or internal tests).

Okay, but i don't see any `pre-release` tag; wouldn't be better use it in future?

**Comment by timosachsenberg** [comment]
agreed and sorry for any inconvinience

**Comment by sagitter** [comment]
[Current release](https://github.com/OpenMS/OpenMS/releases/tag/Release2.1.0) is the stable one?

**Comment by timosachsenberg** [comment]
Hi @sagitter, yes this is the official one.
