### ISSUE TITLE
 MetaboliteSpectralMatcher Failing 

### ISSUE THREAD

**Issue by JDDQ** [OpenMS/OpenMS#2293]
Hello,
I am trying to use the MetaboliteSpectralMatcher node in Knime but it keeps failing giving the following error:

ERROR MetaboliteSpectralMatcher 0:380      Failing process stdout: [Progress of 'loading spectra list':, ,   59.77 %               , -- done [took 0.85 s (CPU), 0.87 s (Wall)] -- , MetaboliteSpectralMatcher took 1.05 s (wall), 1.01 s (CPU), 0.00 s (system), 1.01 s (user)., The given file does not contain any conventional peak data, but might contain chromatograms. This tool currently cannot handle them, sorry.]
ERROR MetaboliteSpectralMatcher 0:380      Failing process stderr: []
ERROR MetaboliteSpectralMatcher 0:380      Execute failed: Failed to execute node MetaboliteSpectralMatcher

I previously added the database into the "chemistry" folder and the MS data being used was converted from mzdata to mzML using the newly installed KNIME 3.2.1 and openms plugin.

Please post any any ideas that may help! 

Thanks in advance,
JDD

**Comment by timosachsenberg** [comment]
Just an idea... maybe it chokes on a chromatogram.
You can remove it by applying FileFilter with the option -no_chromatograms

**Comment by hroest** [comment]
many files converted by pwiz contain a TIC chromatogram, we should handle that transparently

**Comment by hendrikweisser** [comment]
Since there was no follow-up, I assume the problem got resolved.
