### ISSUE TITLE
Evaluate CircleCI

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2297]
They have free plans for open-source projects and currently no build time limitation afaiks

**Comment by cbielow** [comment]
not a lot of examples for C++ projects.

Found
https://github.com/tjun/googletest-circleci
though.

**Comment by cbielow** [comment]
even better:
https://www.brendanlong.com/circleci-makes-automated-builds-easy-but-not-as-easy-as-they-could-be.html

**Comment by hroest** [comment]
the yaml file looks simple enough: https://github.com/tjun/googletest-circleci/blob/master/circle.yml

**Comment by hendrikweisser** [comment]
Is this still on the agenda?

**Comment by hroest** [comment]
we have a working example here, but we dont need travis and CircleCI https://github.com/OpenMS/OpenMS/pull/3921
