### ISSUE TITLE
FileConverter KNIME node default mime type

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#2299]
Came across this on all platforms:
![screenshot from 2016-11-17 11 34 35](https://cloud.githubusercontent.com/assets/5859205/20386135/845115fc-acba-11e6-97a7-6027c100dab9.png)
So what the warning is saying is actually a workflow breaker:
```WARN  FeatureFinderCentroided 2:148      Invalid MIMEtype at port number 0 : has extension: [application/x-mzdata]; expected on of:[[mzml]]```

**Comment by timosachsenberg** [comment]
needs to be changesd in OutputTypes tab. Can We change the default order in the TOPP Tool? maybe via setValidFormats

**Comment by mwalzer** [comment]
would it help if we'd change the order [in this list?] (https://github.com/OpenMS/OpenMS/blob/36ccb5c6d443b4ec59b18a6c1cc315e29b516b9c/src/topp/FileConverter.cpp#L167)
It would be really helpful to have mzML as a default.

**Comment by mwalzer** [comment]
Also, it might be a good idea to note that somewhere in either the node or some other prominent part of the  corresponding documentation, that ```output_type``` is *not* controlling the mime type of the node, but ```OutputTypes```

**Comment by jpfeuffer** [comment]
Yes, I think the order is taken over from the order in the TOPP parameters. But I would need to look in the code to be 100% certain.
Concerning docu: Can you think about a prominent place, where we would not need to mention this in every node that supports multiple outputs? Just brainstorming.

**Comment by timosachsenberg** [comment]
yeah I think we need to remove the output_type parameter when we build the KNIME nodes

**Comment by hendrikweisser** [comment]
Is this still a problem? If not, please close.
