### ISSUE TITLE
Automatic recycling 

### ISSUE THREAD

**Issue by BioComSoftware** [OpenMS/OpenMS#2302]
I'm curious if there's value in adding some form of 'Automatic recycle toggling' to nodes? Or perhaps just change how some nodes 'see' recycling?

Here is an example of why. I'm in the process of developing a rather large pipeline. As such, I'm trying to avoid having redundant input nodes...for fear that one will be missed during editing, and we end up with two nodes expecting the same (in this case *.FASTA) file...but get two different ones (an updated one, and the old one that someone forgot to change). 

However (see image), the xTandemAdapter requires the FASTA input node to be 'Recycled' since more than one mzML file is coming in. 

However, the DecoyDatabase Node gets confused if the I attach the recycled node to it, saying "At least one input node must be 'non.recycled'." 

As a result I have to have two FASTA input nodes...one recycled and one not. 

Perhaps a solution would be an advanced parameter in the DecoyDatabase node that say ignore recycling or perhaps a different advanced option in the xTandemAdapter of 'Automatic Recycling' which tells the adapter, if you get 2+ files...behave as though recycling is off (including erroring out if the 2+ files do not match the 2+ files of other nodes) 

But if there's one-and-only-one file, automatically recycle it, if the advanced option 'Automatic recycling' is checked.

Just a thought :D 
<img width="1044" alt="screen shot 2016-11-17 at 14 04 39" src="https://cloud.githubusercontent.com/assets/6683102/20390663/29e3c108-acd0-11e6-8b13-8e2a10ae0987.png">

**Comment by cbielow** [comment]
this logic will not always work, but to cut a long story short:
![image](https://cloud.githubusercontent.com/assets/6008722/20392133/c6edd924-acd6-11e6-9654-4a3a9d85bfa1.png)

**Comment by cbielow** [comment]
:)

**Comment by cbielow** [comment]
closing this issue. Please re-open if questions remain.
