### ISSUE TITLE
trouble converting a TraML file to CSV

### ISSUE THREAD

**Issue by malmstroem** [OpenMS/OpenMS#2304]
Hi OpenMS,

I am trying to convert a TraML file to CSV using:

/usr/local/openms/OpenMS/bin/ConvertTraMLToTSV -in new.TraML -out bs.csv -debug 20

and I get the following error:

Debug level: 20
 >> /usr/local/openms/OpenMS/bin/ConvertTraMLToTSV -in new.TraML -out bs.csv -debug 20
Value of string option 'test': 0
The OpenMS team is collecting usage statistics for quality control and funding purposes.
We will never give out your personal data, but you may disable this functionality by
setting the environmental variable OPENMS_DISABLE_USAGE_STATISTICS to ON.
Connecting to REST server successful.
Log file:
Writing to ''
Debug level (after ini file): 20
Value of string option 'no_progress': 0
Value of string option 'in': new.TraML
Checking input file 'new.TraML'
Value of string option 'out': bs.csv
<Checking input file 'new.TraML'> occurred 2 times
Checking output file 'bs.csv'
Reading new.TraML
Found duplicate peptide id (must be unique): LTIHENK_2
Error: Unexpected internal error (Your input file contains invalid references, cannot process file.)
<Checking output file 'bs.csv'> occurred 2 times
Error occurred in line 1435 of file /usr/local/openms/OpenMS/src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVReader.cpp (in function: void OpenMS::TransitionTSVReader::convertTargetedExperimentToTSV(const char*, OpenMS::TargetedExperiment&)) !

This is trunk:

commit fe04535dacb36af21222c7dad302ad822f700b0f
Merge: 14643ac c8c9f42
Author: Timo Sachsenberg <timosachsenberg@users.noreply.github.com>
Date:   Fri Nov 18 19:59:05 2016 +0100

What is my best option in trying to debug this?

Thanks!
Lars

**Comment by timosachsenberg** [comment]
Hi Lars,
I have to admit that I am not very familiar with the tool but the message: Found duplicate peptide id (must be unique): LTIHENK_2 might indicate an invalid entry in the TraML file.
Maybe @hroest or @grosenberger know more about this. If possible you can also provide a file to reproduce the error and I can take a look at it.
Best,
Timo

**Comment by hroest** [comment]
@malmstroem  Hi, can you upload the file?

I agree with @timosachsenberg the problem is likely a duplicate ID which does not conform to the TraML standard, was the file produced by OpenMS? In the latter case we also need to debug how the file was created

**Comment by malmstroem** [comment]
Hi Timo and Hannes,

We do indeed have duplicate IDs, it works once they are removed. Thanks for the help and sorry for posting such trivial issues.

Best regards,
Lars
