### ISSUE TITLE
Conflicting typedefs (int8_t)

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2318]
While compiling pyopenms for 2.1, I got the following error on MSVS 2008:

```
C:/openms/contrib_build_2008_64bit/include\seqan/platform/windows_stdint.h(84) : error C2371: 'int8_t' : redefinition; different basic types
        c:\openms\contrib_build_2008_64bit\include\wildmagic\Wm5CoreLIB.h(72) : see declaration of 'int8_t'
```

the issue seems to be that in one place the `int8_t` datatype is defined as (seqan)
```
typedef signed __int8 int8_t
```
 while in the other place (wildmagic) it is 

```
typedef __int8 int8_t
```

not sure why the compiler complains but it seems to be pendantic about such things. We should probably patch this and change it to `signed` in both places.

**Comment by hroest** [comment]
this is also what other people recommend, e.g. here http://stackoverflow.com/questions/16415058/visual-studio-2008-error-c2371-int8-t-redefinition-different-basic-types/16418544#16418544

**Comment by cbielow** [comment]
+1 for patching WildMagic

**Comment by hendrikweisser** [comment]
Is this still a problem? If not, please close.
