### ISSUE TITLE
Undefined references when linking libwm5 during OpenMS build in ubuntu

### ISSUE THREAD

**Issue by mwang87** [OpenMS/OpenMS#2331]
When I attempt to make OpenMS I get this linking error:

/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::operator bool() const'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Read(unsigned long, void*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Write(unsigned long, int, void const*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::FileIO(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Read(unsigned long, int, void*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Write(unsigned long, void const*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::~FileIO()'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Close()'

This is on an ubuntu system 16.04 64-bit. I attempted to use the contrib, I executed these commands:

cmake -DBUILD_TYPE=SEQAN ../contrib
cmake -DBUILD_TYPE=WILDMAGIC ../contrib
cmake -DBUILD_TYPE=EIGEN ../contrib

I used these commands to build:

cmake -DCMAKE_PREFIX_PATH="/home/mingxun/SourceCode/OpenMS_Build/contrib-build;/usr;/usr/local" -DBOOST_USE_STATIC=OFF ../OpenMS

make

One thing I noticed is that the build is looking for libWm5Mathematics.so (a dynamic lib), whereas what is generated by the contrib is a static lib libWm5Mathematics.a. Could this cause some issues? 

-Ming

**Comment by mwang87** [comment]
I have also attempted removing the wildmagic packages all together from my system. Specifically:

sudo apt-get remove libwildmagic-dev
sudo apt-get remove libwildmagic5v5

Upon doing this, and doing

cmake -DCMAKE_PREFIX_PATH="/home/mingxun/SourceCode/OpenMS_Build/contrib-build;/usr;/usr/local" -DBOOST_USE_STATIC=OFF ../OpenMS
make

I receive this error:

In file included from /home/mingxun/SourceCode/OpenMS_Build/OpenMS/src/openms/include/OpenMS/MATH/STATISTICS/LinearRegression.h:41:0,
                 from /home/mingxun/SourceCode/OpenMS_Build/OpenMS/src/openms/source/MATH/STATISTICS/LinearRegression.cpp:36:
/home/mingxun/SourceCode/OpenMS_Build/OpenMS/src/openms/include/OpenMS/MATH/STATISTICS/RegressionUtils.h:39:24: fatal error: Wm5Vector2.h: No such file or directory
compilation terminated.
src/openms/CMakeFiles/OpenMS.dir/build.make:869: recipe for target 'src/openms/CMakeFiles/OpenMS.dir/source/MATH/STATISTICS/LinearRegression.cpp.o' failed


It seems that cmake cannot find the appropriate header files in the contrib directory during the compilation step. 

-Ming

**Comment by mwalzer** [comment]
Yeah, so ubuntu's repository version of libwm5 seems incompatible with our libwm5. So it didn't make it into the install [documentation](ftp://ftp.math.fu-berlin.de/pub/OpenMS/release2.1.0-documentation/html/install_linux.html) for Linux. I am not sure if it is really necessary to remove the system lib as long as you make sure the paths are right, tricky sometimes, though.

Two things, you might try are 
* getting rid of /usr;/usr/local in CMAKE_PREFIX_PATH and to
* start from an empty build directory. CMake sometimes clings to its old configurations.

**Comment by hroest** [comment]
what sneumann discovered in #1483 seems to be the main issue, namely an ubuntu bug:  https://bugs.launchpad.net/ubuntu/+source/libwildmagic/+bug/1578222

**Comment by jpfeuffer** [comment]
We added this to our docu. We cannot fix it ourselves. The fix seems to be still not backported to ubuntu 16.04. Solution: use contrib and do not have the buggy one installed.
