### ISSUE TITLE
Expand FileInfo default output

### ISSUE THREAD

**Issue by okohlbacher** [OpenMS/OpenMS#2342]
While FileInfo currently provides some key quantitative values on the file content, it fails to report some things that are of broad interest when working with the files:
- What instrument was used to generate the data?
- What fragmentation was used (on which level? Mixed fragmentation types?)?
- Is the data profile data or centroided (on both levels)?
- What is the gradient length (min/max in seconds is inconvenient, one wants to see something like 90 min instead)?

Adding these simple outputs should be rather straight-forward and would be very valuable, in particular when you think about how often this output would save a lot of trouble downstream.

**Comment by okohlbacher** [comment]
Yes, but it is not reported for both levels and it could be presented in a more concise manner.
If the metadata and the estimate agree, why mention them independently?
What I'd rather like to see is something like this
--
  - MS1 data is profile data
  - MS2 data is centroided (based on metadata)
--
Or summarize it:
--
File contains
   5,757 MS1 spectra (profile mode)
   12,8273 MS spectra (centroided)
--

**Comment by lars20070** [comment]
One further suggestion for `FileInfo` on `idXML`.  We currently report
```
peptide hits
non-redundant peptide hits (only hits that differ in sequence and/or modifications)
```
In addition, the number of unique sequence hits would be very useful. In labelled experiments, light and heavy hits should not be double counted.
```
non-redundant peptide hits (only hits that differ in sequence)
```

**Comment by cbielow** [comment]
as of (plus some minor changes coming up in a future PR) FileInfo currently reports

```
c:\dev\openms_test_build19>bin\Release\FileInfo.exe -in c:\TEMP\BSA\BSA1.mzML
Progress of 'loading spectra list':
-- done [took 0.33 s (CPU), 0.32 s (Wall)] --


Memory usage (loading MS data): 14 MB (working set delta), 23 MB (peak working set delta)

-- General information --

File name: c:\TEMP\BSA\BSA1.mzML
File type: mzML

Instrument: LTQ Orbitrap XL
  Mass Analyzer: Orbitrap (resolution: 0)

MS levels: 1, 2
Total number of peaks: 479455
Number of spectra: 1684

Ranges:
  retention time: 1501.41 .. 2499.52 sec (16.6 min)
  mass-to-charge: 85.81 .. 799.95
  intensity:      0.67 .. 11977811.00

Number of spectra per MS level:
  level 1: 564
  level 2: 1120

Peak type from metadata (or estimated from data)
  level 1: Centroid (Centroid)
  level 2: Centroid (Centroid)

Activation methods
    MS-Level 2 & CID (Collision-induced dissociation): 1120

Precursor charge distribution:
  charge 2: 679x
  charge 3: 399x
  charge 4: 33x
  charge 5: 8x
  charge 6: 1x
```

which should satisfy all wishes for raw data.
