### ISSUE TITLE
Review licenses of all distributed things

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2347]
While checking the Linux packages that are available for OpenMS, I stumbled across the following [issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822412) posted on a Debian package bug tracker. Seems like no one notified us but it might be worth investigating. It seems like someone was concerned about some cmake-plugins and schemas we distribute.

**Comment by hroest** [comment]
interesting, what do we need the `WSDL_20030211` schema for? I see its only use is in `writeWSDL_` and if debian is really concerned, they could remove it and simply not offer `writeWSDL_`, correct? I also found this email that basically says to remove it for debian as the file cannot legally be modified: https://lists.debian.org/debian-legal/2014/07/msg00005.html

what about the cmake files? 

```
    cmake/modules/CppcheckTargets.cmake
    cmake/modules/Findcppcheck.cmake
    cmake/modules/GetGitRevisionDescription.cmake
    cmake/modules/GetGitRevisionDescription.cmake.in
```

they are under the boost licence which I think should be fine for debian, right?

**Comment by jpfeuffer** [comment]
My understanding was that he complains about missing license texts in our Copyright file.
I am not sure if that is the rule or even mandatory to be legally correct?
About wsdl, I agree, it probably needs to be removed for distribution. I also do not see its use case, yet.

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/blob/2bcec96a828df8b7d10376bcf644936ecb14e52c/src/tests/topp/CMakeLists.txt#L88
I think this line is the only usage of the write_wsdl command line option.

**Comment by cbielow** [comment]
is there any use-case for wdsl? its been available forever, yet noone seems to Need it.... remove entirely?

**Comment by jpfeuffer** [comment]
It seems to be only used for the report of AdditiveSeries.

**Comment by cbielow** [comment]
for the cmake modules: do we still Need them? sometimes they are included in newer CMake Releases and could be removed.

**Comment by jpfeuffer** [comment]
Or maybe AdditiveSeries was just chosen for this test because it was one of the first TOPPtools in the alphabet...

**Comment by cbielow** [comment]
> Or maybe AdditiveSeries was just chosen for this test because it was one of the first TOPPtools in the alphabet...

yes

**Comment by hroest** [comment]
this issue came up again during an internal review by debian and I suggested to just remove the .xsd and the WSDL support from the debian package. It seems it was initially added here 85cb194e1dbef63a44bacf67f811c9cb1ca52f22 by Marc Sturm over 9 years ago. Given that apparently nobody used it for 9 years and it creates licencing problems, I am for either (i) removing it or (ii) providing a cmake flag that can cleanly compile it out.

**Comment by jpfeuffer** [comment]
Yes I vote for complete removal, too. All the webservices are gone anyway.

**Comment by hendrikweisser** [comment]
Any updates here?

**Comment by jpfeuffer** [comment]
WSDL seems to have been removed.
I'll check the rest.
