### ISSUE TITLE
[Migration] Old Sourceforge page redirects to non-existent subpage

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2348]
Specifically www.openms.de/about which does not exist. I tried to upload things to the sourceforge web SFTP server but I do not have permissions.
See http://open-ms.sourceforge.net

**Comment by jpfeuffer** [comment]
Okay. Figured out how to get access but I can't find where it redirects.

**Comment by jpfeuffer** [comment]
In general, the redirection rules from the old sourceforge page are not great. The homepage open-ms.sourceforge.net redirects to the above mentioned wrong link, while e.g. subpages like open-ms.sourceforge.net still show the old content which is not really kept uptodate anymore.
I did a google search and there are still some references to sourceforge on tool collection websites, papers and so on. Most of them point to the sourceforge homepage, some to /downloads/ or /downloads/workflows. I guess a regex redirection substituting the root to openms.de will not work since subpages are called differently now. I could add redirects to the most important subpages, though.

**Comment by jpfeuffer** [comment]
We even have spam news on there by now.

**Comment by jpfeuffer** [comment]
One problem with a complete transition might be, that the TOPPAS workflows under /download/workflows are not yet transferred to my knowledge.

**Comment by mwalzer** [comment]
@lars20070 do you know about those workflows? Are they featured somewhere else already?

**Comment by mwalzer** [comment]
@jpfeuffer 
> The homepage open-ms.sourceforge.net redirects to the above mentioned wrong link, while e.g. subpages like open-ms.sourceforge.net still show the old content which is not really kept uptodate anymore.

I can't follow you there. But that raises another question, why don't we just have an about page (or a redirect under that name to say http://www.openms.de/publications/ or any other)

**Comment by jpfeuffer** [comment]
@lars20070 After conversion from lennard. Are there still workflows that we need?

**Comment by jpfeuffer** [comment]
There are also prerequisite binaries and the Thermo PD/CD plugin binaries on SF. I would like to see them being moved so we have everything in less places. But also the download counts from SF are nice...
@timosachsenberg What do you think?

**Comment by timosachsenberg** [comment]
so we would move them to our build archive server? Fine with me.

**Comment by hroest** [comment]
@jpfeuffer @timosachsenberg can we fix this before the release?

**Comment by timosachsenberg** [comment]
Do we need the download counts for the KPIs?

**Comment by jpfeuffer** [comment]
If there is still stuff downloaded from there, it would be nice. But if we shut it down completely, no one can download from there anymore.

**Comment by timosachsenberg** [comment]
I think we can move that stuff to build archive but I am not sure if we can disable the sourceforge site because of the mailing lists.

**Comment by hendrikweisser** [comment]
http://open-ms.sourceforge.net now just redirects to https://www.openms.de/, so it looks like the original problem is resolved. Closing this ticket.
