### ISSUE TITLE
Include EDAM Ontology Terms in our CTD format

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2349]
For unique annotation of functions, data types and data formats. Could be worthwhile. We could then easily and automatically register every tool in the biotools [registry](https://bio.tools/).
We have something similar already in the "description" and "category" attributes (but they are arbitrary strings).
The ontology is searchable [here](https://www.ebi.ac.uk/ols/ontologies/edam).

**Comment by jpfeuffer** [comment]
Potential topic/task for OpenMS dev meeting.

**Comment by mwalzer** [comment]
:+1:
