### ISSUE TITLE
Test parameters of TOPP/UTILS before running them

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#2351]
as suggested on the mailing list by Florian Sigloch, it would be nice if a TOPP tool could be tested for having proper parameters before it is called with actual data.
This mostly affects pipelines, where the TOPP tool might not be called for hours or even days after the pipeline is started.

The most fragile config is usually for third party executables, which may or may not be installed on the target system. One workaround is to specify the executable via input-nodes, instead of via INI.

More robust options could be:
a) have TOPPAS check the existance any non-empty inputfile parameters before running the pipeline. This might not work for other pipeline engines which simply do not support this.

b) give each TOPP tool a -check flag which implicitly requires -ini to be given as well. The TOPP tool itself will then check all non-default INI params. This could also be used to check ranges, integer parameter values etc. Could be implemented in TOPPBase. Also here, pipelines other  than TOPPAS might not support this, since it would need an extra call before the actual invocation.

Any thoughts?

**Comment by jpfeuffer** [comment]
I think option b) would also be supported in KNIME with some changes in the generic node source code. When you dropping a node and reconfiguring are separate events that could trigger calling the tool with the -check option.
Currently I think it is used to determine if our C++ binaries can be found (does of course not include thirdparty tools which are currently checked at execution).

**Comment by jpfeuffer** [comment]
Question: How would you differentiate between input data files (which might not be present in the beginning) and input executable files?

**Comment by jpfeuffer** [comment]
Another question is, how far the preliminary checks should go: Do they execute the thirdparty executables? Do they check their output (e.g. version)?

**Comment by cbielow** [comment]
I would invoke -check when the Pipeline is about to run, i.e. all Input* should be present already.

On implementation Level, the TOPP tool will only check non-empty Inputs, i.e. intermediate files -- the ones coming from edges-- should be ignored. In TOPPAS this works nicely because the command line call consists of a INI file, with "static" params and "dynamic" params from the incoming/outgoing edges which are added via command line.

As for the checks itself: I would only check for file existance. I remember testing executability to already be troublesome, but that Needs verification. I would not test Version, since this would imply that we Need some tool-specific code. We might allow this as optional, e.g. as overridden function 'bool checkInput()_', which every tool may implement.

*) except for the intermediate files, but lets assume that a workflow engine can successfully handle those... thats it Basic Task after all.
