### ISSUE TITLE
Consistent naming of enzymes in tool parameters (i.e. MSGFPlusAdapter)

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2355]
I think we should change the valid names available for selection in the MSGFPlusAdapter (parameter "enzyme") to be consistent with the other search engines.
**Especially** because if you select "trypsin" for MSGF+ the rule it uses is [KR] (i.e. what is in OpenMS internally called Trypsin/P).
Maybe also create an own parameter category as in the other adapters.

**Comment by timosachsenberg** [comment]
This bug does not seem too minor. Just got a report that PeptideIndexer did not annotate some peptides because they were rejected by the enzyme filter.
So we should also definitely write out that Trypsin/P was used

**Comment by timosachsenberg** [comment]
I promote it to a bug. Seems easy to fix and already caused a bit of headache :)

**Comment by jpfeuffer** [comment]
Hm yes I started on it but it is a bit tedious because you have to go through the MSGF source code to actually see what kind of cutting rules they enforce, map this to our enzymes, add new enzymes and at best also add these enzymes to the PSI.obo

**Comment by jpfeuffer** [comment]
The thing is that MSGF has no knowledge about blocking residues -> no proline rule in any of the enzymes.

**Comment by jpfeuffer** [comment]
I am actually not sure anymore if the mapping to our enzymes without proline rule is a good idea. Seems like it was an intentional decision of them to not have restricting AAs. They even refer to enzymes with proline rules in PSI.obo.. just weird.

**Comment by cbielow** [comment]
I just ran into the same issue with typsin.
The straight forward solution seems to be to rename the parameter value to trypsin/p in the adapter.
Since trypsin is probalby used 99% of the time, this would solve the majority of headaches.
@jpfeuffer other enyzme names which are worth changing?

If a perfect mapping of names is not possible, we should augment the parameter docs and the tool description.

**Comment by jpfeuffer** [comment]
I mean potentially you have to add a "/P" to all of them. It's just a shame that we can't use our entries in EnzymeDB because they do not agree.

**Comment by jpfeuffer** [comment]
Maybe we can map them to the enzymes with proline rule and add an option to peptide indexer that disables proline rule when looking up the DB?
