### ISSUE TITLE
PeakPickerHiRes INI/CTD entry for report_FWHM_unit produces error

### ISSUE THREAD

**Issue by blankclemens** [OpenMS/OpenMS#2358]
The CTD/INI entry for PeakPickerHiRes specifies as default and possible value `relative(ppm)`. This value, however, produces an error in bash, since parentheses aren't allowed. Using only `ppm` or `relative` does work however. Would it be possible to change this in Order to help with automatic command generation?

```
<ITEM name="report_FWHM_unit" value="relative(ppm)" type="string" description="[...]" required="false" advanced="false" restrictions="absolute,relative(ppm)" />
```

Yes, it would work to put the command into quotation marks, but for automatism I would have to do this for every parameter in all tools -  I'd say automatically generated values should be safe to use without quotation marks. ;-)

**Comment by cbielow** [comment]
you'd have to use Quotation marks for Input and Output files anyway, right?
Another alternative is to write this params to an INI file and read that via bash.

The disadvantage of changing the allowed values here is that it breaks the CLI and leads to upgrade/downgrade problems for all existing pipelines. In your case, I'm not sure if the benefits outweight the disadvantages. I also think that the Parameter value is more descriptive the way it is now.
However, just my personal opinion.

**Comment by blankclemens** [comment]
Would it actually lead to issues? Since right now, everything is accepted and treated as `relative` - only `absolute` and `"absolute"` would change this parameter - and this wouldn't be touched.

So I could imagine that changing this value to `relative` or `ppm` would break anything, but I'm not sure. And of course, it would be possible to just put everything in quotation marks (Input and Output can be easily detected, so that's no issue to handle anyways).

Just not sure at the moment if quoting everything would create problems with numbers, but if they are marked as such they shouldn't be affected.

**Comment by blankclemens** [comment]
While I do think that command line parameters shouldn't contain characters which have to be escaped in order to use them in the command line, I admit that it's pretty easy to work around this and it can be closed.

**Comment by cbielow** [comment]
> Would it actually lead to issues? Since right now, everything is accepted and treated as relative - only absolute and "absolute" would change this parameter - and this wouldn't be touched.

True, in this case it would be backwards compatible.

> Just not sure at the moment if quoting everything would create problems with numbers, but if they are marked as such they shouldn't be affected.

Thats no problem. Incoming CLI params are always strings, in C(++) at least, so no worries there.

I'll go ahead and make the change.
