### ISSUE TITLE
RTModel silently produces files with additional parameters

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2361]
Which is a problem for usage in KNIME. When you save the output, only the registered output file is copied. If you then use RTPredict, the additional file is missing.
Solutions:
- Multiple outputs
- Output prefix

**Comment by timosachsenberg** [comment]
hmm I think multiple outputs are better

**Comment by cbielow** [comment]
related to #632

and also voting for multiple outputs
