### ISSUE TITLE
ID score visualisation in TOPPView

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#2370]
Currently, PSMs are visualised in the `idXML` layer of `TOPPView` with small crosses.

Using the same coloured dots as in `featureXML` and `consensusXML` would allow the visualisation of the ID scores. In addition that would allow for the filtering of PSMs using the `Data filter` tab.

<img width="700" alt="screen shot 2017-01-27 at 16 29 37" src="https://cloud.githubusercontent.com/assets/6149805/22376602/f6be3ac6-e4ae-11e6-917c-abe10e183d44.png">
  
<img width="700" alt="screen shot 2017-01-27 at 16 29 48" src="https://cloud.githubusercontent.com/assets/6149805/22376619/06e6dab6-e4af-11e6-8e4e-64c4912168ed.png">

**Comment by jpfeuffer** [comment]
I like this. If it is not too crowded when zoomed out. Choosing which score to display would be even nicer!

**Comment by Stortebecker** [comment]
+1

This would not only allow for visualization of scores, but also for the exact m/z and RT values. Currently, those have to be manually extracted out of the list, which is not very convenient.
