### ISSUE TITLE
pyOpenMS tests

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2375]
what happened to the pyOpenMS tests, I dont see them in cdash any more?

**Comment by hroest** [comment]
@jpfeuffer can you maybe re-enable them?

**Comment by jpfeuffer** [comment]
Yes I changed the script already. I remember disabling them during the last days before the release because they paralysed the machine with their RAM usage such that multiple builds per day were not possible.

**Comment by hroest** [comment]
great, thanks!
