### ISSUE TITLE
LuciphorAdapter/Luciphor2 

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#2381]
I ran into an issue trying to run the LuciphorAdapter. 

Following error occurred several times and the LuciphorAdapter failed:

```
 ERROR:QExactiveHF02_03926.mzML Scan: 12873
 # of mz values != # intensity values: 1830 != 457
 Skipping this scan...
```
The mzML I was using had a 64-bit float, m/z array and a 32-bit float, intensity array. After conversion of both arrays to 32-bit the LuciphorAdapter worked without problems. This seems to be related to LuciPhor2, which may only take 32-bit or 64-bit arrays [1].

The Question is what to do about that? Maybe a check in the LuciphorAdapter if the arrays have the same precision. If this is not true - is there an OpenMS Tool for conversion?

Opened an issue on the luciphor page [2]. 

[1] https://github.com/dfermin/lucXor/commit/24c4b69acbebec5bac82075f3943c26f5e28f439
[2] https://github.com/dfermin/lucXor/issues/2

**Comment by hroest** [comment]
@oliveralka yes, there is a tool called `FileFilter` that allows you to set `peak_options:mz_precision` and `peak_options:int_precision` which could produce the file you want. In the long run it would be good if OpenMS could check this and either provide a sensible error message or directly convert it for the user.
