### ISSUE TITLE
Xtandem Error

### ISSUE THREAD

**Issue by jotes35** [OpenMS/OpenMS#2382]
I run into this error when executing the TOPPAS Workflow. I have attached the files i used. Below is the error message.

Number of rounds for incoming edges of node #4 are not equal. No idea on how to combine them! Did you want to recycle its input?

==============================================================================
13:50:11 ERROR: XTandemAdapter failed!
Number of rounds for incoming edges of node #4 are not equal. No idea on how to combine them! Did you want to recycle its input?

**Comment by oliveralka** [comment]
Hello jotes35,

it seems there is something wrong with the attachment.

If you are using your decoy database for several nodes in your workflow you have to switch on recycling mode. Right-click on the input node of your decoy database and click on "Toggle recycling mode". You will see a small recycling symbol on top of the node. 

I hope that helps, if not please try to upload your workflow again.

**Comment by jotes35** [comment]
Now after turning on recycling for the decoy database this is the error message i am getting

15:01:15 ERROR: FalseDiscoveryRate failed!
Number of rounds of node #10 cannot be determined since all input nodes have recycling enabled. Disable for at least one input!


![labelfree workflow](https://cloud.githubusercontent.com/assets/14283733/22512079/b0f6c190-e88f-11e6-9b1c-32e73a1b0765.png)

**Comment by jpfeuffer** [comment]
Why did you turn on recycling in node #9 (could be FidoAdapter but can't really read it)?
What happens if you turn it off?

**Comment by jotes35** [comment]
Thanks everybody. Now when it runs it stops at the mapalignerposeclustering. How to i edit the ini parameter. Below is the error message . 
![label free exp](https://cloud.githubusercontent.com/assets/14283733/22513340/dc0df96c-e893-11e6-8470-430d67c03b02.png)



15:28:10 NOTICE: MapAlignerPoseClustering of node #17 started. Processing ...
Error: The required parameter 'in' was not given or is empty!

==============================================================================
15:28:10 ERROR: MapAlignerPoseClustering failed!

**Comment by oliveralka** [comment]
It seems that there is an "in" file missing. Do you have the right input slot active for node 17? Please try to connect node 16 and 17 again and choose "-in" which should have the format mzML or featureXML. If that doesn't do it please check if the node 16 has the right output format mzML or featureXML and if an output is written.

**Comment by lars20070** [comment]
@oliveralka You are right. The collector before `MapAlignerPoseClustering` is missing.
The tool expects a file list of `n` input files.
![mergecollectsplit](https://cloud.githubusercontent.com/assets/6149805/22543051/050efdac-e92f-11e6-87d5-377402b9dbec.png)

**Comment by jpfeuffer** [comment]
@lars20070 Nice visualization. Maybe you can put it in some Tutorial of ours.

**Comment by jotes35** [comment]
Thanks lars. i am testing them right now and will give you a feedback

**Comment by jotes35** [comment]
i just test the knwf workflow and it stops at the mapalignerposeclustering node below is the error message

ERROR MapAlignerPoseClustering 3:21       Failing process stdout: [Picking a reference (by size) ... done, , ---------------------------------------------------, FATAL: uncaught exception!, ---------------------------------------------------, last entry in the exception handler: , exception of type Exception occured in line 753, function <unknown> of ..\..\..\OpenMS\src\openms\source\ANALYSIS\MAPMATCHING\PoseClusteringAffineSuperimposer.cpp, error message: unknown error, ---------------------------------------------------]
ERROR MapAlignerPoseClustering 3:21       Failing process stderr: []
ERROR MapAlignerPoseClustering 3:21       Execute failed: Failed to execute node MapAlignerPoseClustering
ERROR MapAlignerPoseClustering 3:21       Failing process stdout: [Picking a reference (by size) ... done, , ---------------------------------------------------, FATAL: uncaught exception!, ---------------------------------------------------, last entry in the exception handler: , exception of type Exception occured in line 753, function <unknown> of ..\..\..\OpenMS\src\openms\source\ANALYSIS\MAPMATCHING\PoseClusteringAffineSuperimposer.cpp, error message: unknown error, ---------------------------------------------------]
ERROR MapAlignerPoseClustering 3:21       Failing process stderr: []
ERROR MapAlignerPoseClustering 3:21       Execute failed: Failed to execute node MapAlignerPoseClustering





![knimelabelfree](https://cloud.githubusercontent.com/assets/14283733/22556512/4e08443e-e95f-11e6-9f21-79dd1e727fc7.png)

**Comment by jpfeuffer** [comment]
Hm.. somehow the Exception is not passed to the command line but the line in the code says this:
`"One of the input maps is empty! This is not allowed!"`

Since you use a file filter beforehand please check that it is not too strict.

**Comment by jpfeuffer** [comment]
In general please inspect your files (e.g. FileInfo or OutputFile(s)) in each step to find the broken step.

**Comment by jotes35** [comment]
Thanks i will get on it now

**Comment by lars20070** [comment]
@jotes35 Please set the intensity cutoff in the `FileFilter` before `MapAlignerPoseClusterung` to zero.
```
int = :
```

**Comment by oliveralka** [comment]
@jotes35 Was the issue resolved? Then this issue can be closed.

**Comment by jotes35** [comment]
Hi, i realised one of the file generated was empty and that is what was making the mapalignerposeclustering to fail. I solved that issue. However when it got to the featurelinkerunlabelledQt it failed again . below is the workflow


![featerlinker](https://cloud.githubusercontent.com/assets/14283733/23135698/87eb1e20-f791-11e6-9c54-fb6b9deb1191.png)

**Comment by jpfeuffer** [comment]
Hey, we are getting further ;)
Can you post the new error, too?

**Comment by jotes35** [comment]
ERROR FeatureLinkerUnlabeledQT 0:19       Failing process stdout: [Progress of 'reading input':, ,   0.00 %               , -- done [took 1.92 s (CPU), 1.91 s (Wall)] -- , Error: Unexpected internal error (At least two maps must be given!)]
ERROR FeatureLinkerUnlabeledQT 0:19       Failing process stderr: []
ERROR FeatureLinkerUnlabeledQT 0:19       Execute failed: Failed to execute node FeatureLinkerUnlabeledQT

**Comment by jotes35** [comment]
i think no intensity was picked from one of my datafiles and that was what made the mapalignerposeclustering failed

**Comment by jpfeuffer** [comment]
Ok. The error indicates that your last loop with the MapRTTransformer only was executed for one iteration, collecting only one result file.
Either because there was only one file going into the ZipLoopStart (more likely) or the loop did not finish all its iterations (in that case you would probably see another error).
How many input files do you have?

**Comment by jotes35** [comment]
It has worked now. 
First , i changed the intensity cutoff to 0 as suggested . I also removed the data which had no intensity picked.  Now my abundances has been generated. You can close this issue now.

**Comment by jotes35** [comment]
Thanks for your contributions everyone
