### ISSUE TITLE
Missing pthread symbols during compilation with clang3.5

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2390]
On Ubuntu14.04.
Error:
`[ 50%] Linking CXX executable ../../bin/FeatureFinderSuperHirn
/usr/bin/ld: /home/jenkins/ws/openms_all/117bf32c/contrib_build/lib/libxerces-c.a(PosixMutexMgr.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Self compiled xerces from contrib with same compiler.
Other executables build fine.

**Comment by cbielow** [comment]
http://stackoverflow.com/questions/22180354/why-am-i-getting-undefined-reference-to-pthread-mutexattr-settype

--> fix: pass `-pthread` as CXX flag ?

**Comment by jpfeuffer** [comment]
Thanks, I'll try that next. I always wonder, why this happens in such rare cases.
E.g. not with gcc, not on Travis with clang3.4. Same flags.
Well..
I guess this does not justify adding "-pthread" as global compilation flag?

**Comment by jpfeuffer** [comment]
Yep.
```
export CFLAGS="-pthread"
export CXXFLAGS="-pthread"
```
works

**Comment by hroest** [comment]
so should we add this flag through CMake?

**Comment by hendrikweisser** [comment]
Is this issue still relevant? Please close if not.
