### ISSUE TITLE
PeakPickerHiRes update fails on KNIME nightly build

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2391]
![image](https://cloud.githubusercontent.com/assets/5803621/22648487/39752382-ec77-11e6-85d0-95ad687fecef.png)

**Comment by timosachsenberg** [comment]
happened for me when I used the drag-and-replace feature in KNIME. Removing the node and readding it solved the issue.

**Comment by jpfeuffer** [comment]
Hmm I would have thought that drag and replace actually does the same.
Did you update the nightlies between the drag-and-replace and the actual remove and readd?
Last days we had some problems with old nodes getting used as fallback because I messed up the packaging.

**Comment by timosachsenberg** [comment]
Hmm can't reproduce the problem now. Might also be related to a fallback mechanism. Though I am pretty sure that I tested it before and after the update. I close this issue - just wanted it to pop up once in the issue lists.
