### ISSUE TITLE
PeakPickerHiRes fails to read mzML profile data

### ISSUE THREAD

**Issue by isaphan** [OpenMS/OpenMS#2394]
I used msconvert to convert raw Orbitrap LTQ MS/MS data to mzML, using the default settings, which should yield profile data.

- PeakPickerHiRes fails with
Error: Unexpected internal error (Error: Centroided data provided but profile spectra expected.)

I removed the PeakPickerHiRes node and used directly FeatureFinderCentroided on the exact same mzML file. I get the error:
Error: Unexpected internal error (Error: Profile data provided but centroided spectra expected. To enforce processing of the data set the -force flag.)

How do I get PeakPickerHiRes to read my file?
Running TOPPAS 2.1.0 on MacOS 10.11.6

**Comment by hendrikweisser** [comment]
What does FileInfo say about the file, especially the peak type?

**Comment by isaphan** [comment]
This is the FileInfo output:

File type: mzML

Peak type (metadata): Unknown
Peak type (estimated): Raw data
Estimated raw data spacing: 0.0008432 (min: 1e-05, max: 46.8346)

Number of spectra: 28111
Number of peaks: 232061015

**Comment by isaphan** [comment]
For what it's worth, I've managed to get PeakPickerHiRes to work by:
a) converting the raw file first to mzXML using msconvert (default options)
b) adding a step in my OpenMS pipeline to convert the mzXML into mzML

The conversion was a very slow process, several hours per file... It would be really helpful to be able to read the msconvert-generated mzML files directly.

**Comment by timosachsenberg** [comment]
Did you check if PeakPickerHiRes is configured to pick only MS1 ? Maybe the MS2 is already recorded in centroided mode

**Comment by isaphan** [comment]
aargh, well spotted, I should have checked that with our mass spec folks, my bad. Yes you are absolutely right. Thank you so much for your help.

**Comment by hendrikweisser** [comment]
@timosachsenberg: I think we should add an explicit message to PPHR, if it fails due to a mix of profile and centroided spectra at different MS levels.

**Comment by hroest** [comment]
also FileInfo could say something about that ...

**Comment by timosachsenberg** [comment]
yes I think we should add a more explicit warning
