### ISSUE TITLE
PeptideIndexer memory consumption in the presence of many XXXX

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2395]
Hi,
I am currently indexing against a 4gb microbial proteome database that contains proteins with large stretches of X
```
LKRRLNPQASAQTPASISIXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXVTPLMLA
GXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
RKFYGKKNWQSSKNGCNFPLSSNLKTRKTNWXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
SXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXS
```
Memory consumption is very high (>100gb) and indexing takes about a day.

What would be a good way to handle this situation in PeptideIndexer?
e.g., collapse stretches of 'XXX...' to a single X ?

**Comment by cbielow** [comment]
the high memory consumption is most likely due to the suffix array.

options: 
1. use exact search only 
2. reduce AAs (i.e. allowed number of AAs `-aaa_max`)
3. use `-filter_aaa_proteins`

You could also collapse "xxx...", but that has some restrictions, i.e. bridging distant sequences should be avoided.

What parametes did you use?

**Comment by cbielow** [comment]
can you try what happens with the new AC-PeptideIndexer?
Memory consumption should be very low now, since it loads FASTA files chunkwise and jumps over stretches of X which are longer than the allowed number of ambiguous AAs

**Comment by cbielow** [comment]
I ran the current (#3258)  PeptideIndexer with default settings (max 3 ambiguous AA's) on 9 GB 160406_Uniprot_Proteome_Bacteria_FWBW.fasta file using an idXML with ~50k peptides.
I took 9 minutes (single threaded) and about 2.5 GB RAM.

Closing as solved, please re-open if needed.

**Comment by timosachsenberg** [comment]
thanks!
