### ISSUE TITLE
escape strings for writing XML [24]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#24]
Submitted by OpenMS Retreat on 2009-10-09 13:56:53

special chars like "&" e.g. in user-params are dangerous and will create an error when reading the file back in (Andreas idXML, ... ALLE)   

=> implement "static String XMLFile::escape(const String&) const" which uses uses xerces::xmlformatter()

---

Commented by andreas_bertsch on 2009-10-28 16:01:33:
implemented and seems to work

---

Commented by cbielow on 2011-02-18 12:54:01:
- we currently do not to this for mzML... enquiry ongoing...

---

Commented by herrzweiblum on 2012-09-04 09:23:56:
commit 9872 for MzML: Fixed in writeUserParam function so writing invalid userparams will not be possible. To be generalised for XML

**Comment by timosachsenberg** [comment]
Hi Hannes, I will set priority down from blocker to major. Do you know what still needs to be done?

**Comment by hroest** [comment]
Im on vacation but basically we need to go through every line of every xml
writer systematically and identify instances where unsafe xml may be
written from a string and pipe it through an escape function. So far I only
fixed the most obvious cases of userparam and cv param and a few others

sent from my smartphone -- you may keep any typos you find.

**Comment by timosachsenberg** [comment]
Any progress on this? I changed state from major enhancement to minor defect.

**Comment by hroest** [comment]
well if OpenMS writes invalid XML files that even OpenMS itself  cannot write again, this is a major problem. I believe that we have fixed it many places now but so far all fixes have been "partial".

**Comment by timosachsenberg** [comment]
We can also promote this to a major defect if you want but major enhancement was probably the wrong label. If we promote it to major then we should ideally have a plan or anybody willing to take the lead on this. Without looking at the code, would it be possible to wrap the operator to always call writeXMLEscape ?

**Comment by hroest** [comment]
yes, that might be an idea but it seems very invasive

**Comment by cbielow** [comment]
not sure if thats a good idea.
I remember fixing some formats, and I vaguely recall an issue with 
double escaping. Apart from that, its overhead :)

Am 11/10/2016 um 12:32 AM schrieb Hannes Roest:

**Comment by cbielow** [comment]
closing this, this there seems to be no immediate problem.

**Comment by hroest** [comment]
@cbielow given that the latest bugfix for this issue was less then 16 days ago, this seems optimistic #3321
