### ISSUE TITLE
FeatureFinderMultiplex crash

### ISSUE THREAD

**Issue by hannesveit** [OpenMS/OpenMS#2401]
FeatureFinderMultiplex crashes on one of my simulated mzML files. This doesn't occur on hundreds of other simulated files which are essentially all the same (only difference is some minor random variation introduced by MSSimulator).

Minimal example: [FFMPX_crash.mzML.zip](https://github.com/OpenMS/OpenMS/files/765775/FFMPX_crash.mzML.zip)

Parameters: 

>$ FeatureFinderMultiplex -algorithm:labels "" -algorithm:intensity_cutoff 0.0001 -in FFMPX_crash.mzML -out_features test.featureXML
>Progress of 'loading spectra list':
>-- done [took 0.06 s (CPU), 0.06 s (Wall)] -- 
>Progress of 'filtering LC-MS data':
>-- done [took 0.16 s (CPU), 0.16 s (Wall)] -- 
>Progress of 'clustering filtered LC-MS data':
>Error: Unexpected internal error (This position (x,y)=(300.144,614) is outside the range of the grid. (300.144 < x < 319.939, 550 < y < 749))

**Comment by jpfeuffer** [comment]
A <= vs < problem?

**Comment by hannesveit** [comment]
At least that's what it looks like... @lars20070, could you maybe have a closer look at this?

**Comment by lars20070** [comment]
Seems the same problem as in #2027. I had hoped that was resolved in #2069.
@hannesveit  I will have a look.
