### ISSUE TITLE
Reading of modifications in mzIdentML: terminal specificity lost

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2404]
Terminal specificity of modifications in the search parameters is not read correctly from mzIdentML. This causes the loss of the specificity information and possibly problems in dealing with the resulting data.
This happens in IDFileConverter and in MSGFPlusAdapter.
Common modifications that are affected include: Acetyl (N-term), Gln->pyro-Glu (N-term Q), Glu->pyro-Glu (N-term E)

For example, "Acetyl (N-term)" in the search parameters would be represented in mzIdentML as such:
```
                        <SearchModification fixedMod="false" massDelta="42.010565" residues=".">
                                <SpecificityRules>
                                        <cvParam accession="MS:1001189" cvRef="PSI-MS" name="modification specificity peptide N-term"/>
                                </SpecificityRules>
                                <cvParam accession="UNIMOD:1" cvRef="PSI-MS" name="Acetyl"/>
                        </SearchModification>
```

However, after conversion to idXML, the terminal specificity is lost:
`<VariableModification name="Acetyl" />`

In the case of the pyro-Glu conversions, this results in invalid modifications ("Gln->pyro-Glu (Q)", "Glu->pyro-Glu (E)"), which cause e.g. a reconversion from idXML to mzIdentML to fail with the following error:
`Error: Unexpected internal error (the element 'Gln->pyro-Glu (Q)' could not be found)`

**Comment by mwalzer** [comment]
this looks like it is related to #1509 and #1550

**Comment by mwalzer** [comment]
But I cannot recreate your error. Can you please share one of the offending files?

**Comment by hendrikweisser** [comment]
> Can you please share one of the offending files?

Not easily (too big). Can't you just copy the snippet above (with the "Acetyl") into an example mzid file? The important point would be that after conversion to idXML, the modification appears as `<VariableModification name="Acetyl (N-term)" />`, i.e. with the "N-term".

**Comment by mwalzer** [comment]
Okay, searchparameter reading has to be fixed. One thing I cannot check like this is whether the sequence mods are affected as well. Can you please check in your files?
