### ISSUE TITLE
XTandemAdapter crash on "Deamidated (N)" modification

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2405]
XTandemAdapter crashed, after completion of the X! Tandem search, with the following error messages:

```
Error: Unexpected internal error (The value 'Deamidated (N)' was used but is not valid! Retrieving the modification failed. It is not available for the residue 'S' and term specificity 0.)
XTandem config file: Duplicate modification assignment to origin '['. X!Tandem will ignore the first modification '42.0106'!
<XTandem config file: Duplicate modification assignment to origin '['. X!Tandem will ignore the first modification '42.0106'!> occurred 2 times
```

The following modifications were used in the search:
- fixed: Carbamidomethyl (C)
- variable: Oxidation (M), Deamidated (N), Deamidated (Q), Gln->pyro-Glu (N-term Q), Glu->pyro-Glu (N-term E), Acetyl (N-term)

Looking at the output file produced directly by X! Tandem ("_tandem_output_file.[...].t.xml"), something seems to be seriously wrong with some of the modifications:
`<aa type="M" at="6" modified="-18.01056" />` appears for many different amino acids and positions, but the mass shift only matches "Glu->pyro-Glu (N-term E)"!
Interestingly, only the "-18.01056" modification seems to be obviously misassigned. I couldn't find any instance of the case that the error message complains about, i.e. "Deamidated (N)" (mass shift 0.98402) being assigned to an "S".

**Comment by jpfeuffer** [comment]
@enetz Could this be related to your changes?

**Comment by enetz** [comment]
My pull request is not merged yet, so I doubt this is a new issue,
but I encountered similar issues while tinkering with ModificationsDB.
Weird stuff happens, when we can only search by mass.
It looks like the file produced by X! Tandem does not store the names or accessions of the mods.
Does it have an attribute for term specificity?

I encountered this issue with pepXML parsing: when only the mass is given, side chain mods are searched by mass. Only if this search does not find anything, a second search looks at all mods including n-term and c-term.
In my case this search found a list of side chain mods with a certain mass shift and did not try to find terminal mods. Then it compared this list with the list of searched variable mods and did not find a match, leading to an error. Weird things like that happened with IDFileConverter tests on my branch, if the mods were not specified precisely enough in a file.
But I have not worked with the XTandemAdapter and can not say for sure if this is actually a similar issue.
Maybe you are just searching for an unfortunate combination of mods, e.g. for "-18.01056" the tool might have found the other not terminal specific mod: "Dehydrated" would fit and also can be assigned to "S".

**Comment by hendrikweisser** [comment]
> Looking at the output file produced directly by X! Tandem ("_tandem_output_file.[...].t.xml"), something seems to be seriously wrong with some of the modifications:
<aa type="M" at="6" modified="-18.01056" /> appears for many different amino acids and positions, but the mass shift only matches "Glu->pyro-Glu (N-term E)"!

Okay, I figured out that the position ("at" in the XML) refers to the position in the protein sequence. From what I've seen this is always after a trypsin cleavage site, so it seems to be correctly localized on the peptide N-terminus. The amino acid specificity is wrong, but that information didn't get carried over into the X! Tandem (parameter) input file generated by XTandemAdapter:

`<note type="input" label="residue, potential modification mass">+42.010565@[,+0.984016@N,+0.984016@Q,-17.026549@[,-18.010565@[,+15.994915@M</note>`

I'll see what happens when I fix this modification definition.

**Comment by hendrikweisser** [comment]
Apparently the "pyro-Glu" modifications are not needed explicitly, since X! Tandem will include them by default:

http://www.thegpm.org/TANDEM/api/rpmm.html (see "NOTE:" at the bottom)
http://www.thegpm.org/TANDEM/api/pqp.html
