### ISSUE TITLE
Update X! Tandem and XTandemAdapter

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2406]
A new version of X! Tandem is out ("ALANINE"): http://www.thegpm.org/TANDEM/index.html
We should test it and possibly update the version used by OpenMS.

Also, X! Tandem supports mzML as input format and mzIdentML as output format - and has since "PILEDRIVER" (April 2015)! Our XTandemAdapter still uses mzData and X! Tandem's own XML format for input/output. We should switch to mzML/mzid to simplify the code and reduce maintenance.

**Comment by hendrikweisser** [comment]
Also note this update from the "VENGEANCE" version (2015-12-15):
> The legacy command "spectrum, use noise suppression" has been removed from the project: the original method was created for LCQ spectra and it no longer had any practical utility.

**Comment by hendrikweisser** [comment]
I emailed the X! Tandem developers with a question about the support for mzIdentML output. (I had found that it didn't work when the option "output, results": "all" was set.) I go this reply from Ron Beavis:
> I stopped development when I found that mzindentML was simply too restrictive to properly record results, lacking any good methods for recording protein assembly information, statistical confidence evidence, quantitation, etc. It is also rather poorly designed: the cumbersome, fragile mechanism of tying results together through hashed id values is hard to test (and easy to get wrong). I will probably be removing the mzidentML option all together in the next release.

So it seems having X! Tandem generate mzIdentML directly is currently not a viable option.

**Comment by hendrikweisser** [comment]
Switch to mzML input (without conversion to mzData) is in #2428.

**Comment by hroest** [comment]
@hendrikweisser I wonder why developers of search engines find mzIdentML not suitable, wasnt the whole point to develop a format that is standard and unambiguous? This is somewhat worrisome to me if even search engine developers do not adopt the format - is this a single minority opinion or is there indeed something going on with the format? maybe @mwalzer can comment on this as well ?

**Comment by mwalzer** [comment]
> even search engine developers do not adopt the format

Well, they do. Just took them a while, as it is complex. In the end, it has to cover a lot of ground .. Though, it is sad, that developers think of removing support.
As to protein assembly information and the like, my guess is that at the time the format was conceived, there was not such a clear notion of how to best approach the documentation of evidence trail of such analyses. These were also not well established then at all. And quant simply does not belong in mzid.
>> the cumbersome, fragile mechanism of tying results together through hashed id values

I think, mzid could use some information/PR campaign. Also, to approach SE developers and get them involved, since it is supposed to evolve with new use cases. Will try to push it to the agenda of nexts PSI meeting.

**Comment by hendrikweisser** [comment]
> I wonder why developers of search engines find mzIdentML not suitable, wasnt the whole point to develop a format that is standard and unambiguous? This is somewhat worrisome to me if even search engine developers do not adopt the format - is this a single minority opinion or is there indeed something going on with the format?

It may be a minority opinion, but it seems to be a sizeable minority. People are struggling with the complexity of mzIdentML. The PRIDE people prefer to use mzTab; validating large mzIdentML submissions required too much computational resources (at least until recently, when they improved their parser). MassIVE apparently uses mzTab "for everything" internally (@mwalzer, did you tell me that?). In OpenMS, we had the discussion about how to store small molecule results, and chose to extend idXML over mzIdentML (@timosachsenberg).

That said, I don't think the alternatives are better. mzTab is too redundant and gets complex as well if you actually want to store all the information from an mzid. X! Tandem's XML format (see http://www.thegpm.org/docs/X_series_output_form.pdf) is very much tailored to what X! Tandem needs, but isn't great to work with.

**Comment by timosachsenberg** [comment]
I agree and also think the complexity of mzIdentML reflects, to a certain degree, the complexity of proteomic searches. A format tailored for a single feature set is always "lighter" and less complex. That being said, some details could have been fleshed out better in retrospect but I think it solved the main issue of archiving various search engine results.
(BZW MassIVE also uses mzIdentML internally (e.g., from MSGF+ searches, but store final results as mzTab.)

**Comment by jpfeuffer** [comment]
Since #2098 is closed as "thirdparty" wontfix, I will close this too for now. Everything but mzid support seems to be addressed.
