### ISSUE TITLE
FileInfo: print protein database statistics from fasta files

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2411]
e.g.,: 
- number of proteins
- number of amino acids
- amino acid counts (including the special ones 'X', 'B', ...)
- warn if duplicate sequences
- warn if duplicate headers

**Comment by lukaszimmermann** [comment]
How can I set myself as assignee? I wanted to work on FileInfo anyway.

**Comment by lukaszimmermann** [comment]
Is it correct that `FileInfo` then would accept  FASTA as a new valid input format?

**Comment by hendrikweisser** [comment]
> Is it correct that FileInfo then would accept FASTA as a new valid input format?

Yes.

**Comment by amnamasood** [comment]
Hello!
I have added some functionality to do [this](https://github.com/amnamasood/OpenMS/commit/1ae4159c1503fa33c10f92189bd6dbb25578f808)

Can you take a look and suggest further improvements?

**Comment by cbielow** [comment]
I've added some comments. Nice code so far, please open PR when ready :)

**Comment by amnamasood** [comment]
Thank you. I have read your comments. Will do something in the morning as it is very late here.
