### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2413]
Hey all,
this is an issue to collect possible improvements for the website, as also suggested for the Dev Meeting. Also for future problems, I created a label "Website".

- [x] Add OpenMS2.0 to the main citations (or replace)
- [x] Clicking on citation years does not work anymore
- [x] Add new members
- [ ] Add sidebar to Training
- [ ] Merge People and Contributors

**Comment by cbielow** [comment]
also improve wording/categories? e.g. `contributing` indicates `How can I contribute?`, but what it should say is `Contributors`, i.e. people already contributing.

**Comment by lars20070** [comment]
Some non-technical [*] users cannot easily find their way to the installers. It requires four clicks to start the download. Instead, a clear download link should appear on the front page.

[*] who do not know what binaries are

**Comment by jpfeuffer** [comment]
Good suggestions, keep 'em coming.

**Comment by cbielow** [comment]
`training` category has mutlitple problems:
1) on the page itself its called `tutorials`
2) the page is highly confusing. To much mentioning of KNIME, not enough content.
The `old` section is not very concise.

We should also mention on the GitHub page, that there is a compiled version on the homepage. So people do not try to build it themselves. Also the checked in PDF should be removed. People might think thats the compiled result (which it is NOT).

**Comment by lars20070** [comment]
At the Proteomic Forum I saw again that people cannot find their way to the installers [1]. See my comment above.

[1] https://sourceforge.net/projects/open-ms/files/OpenMS/OpenMS-2.1/

**Comment by jpfeuffer** [comment]
Ok. Should we rename "OpenMS binaries" to "OpenMS Installers"?
Because the Download page with the different categories is actually very easy to reach.

**Comment by hendrikweisser** [comment]
> Because the Download page with the different categories is actually very easy to reach.

I agree with Lars. The links in the menu bar are still relatively hidden. I would be in favour of a big "Download OpenMS" button under the "What is OpenMS?" section.

**Comment by hendrikweisser** [comment]
Under "How to cite OpenMS", there's a question mark in one of the author names: "Malmstr?m, L."
(Strange, since the "ö" in "Röst" appears correctly.)

**Comment by jpfeuffer** [comment]
Ah thanks. I corrected that manually :D Did not see Malmstr?m.

**Comment by jpfeuffer** [comment]
@cbielow Concerning Training content. I can give you access to Wordpress. It would be easy to edit plain content.
