### ISSUE TITLE
Non-meaningful errors when reading ascii encoded files 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2414]
I recently encoutered an UTF-16 (LE) encoded fasta file that leads to a crash of DecoyDatabase (in SeqAn fasta reader).

the ff fe indicates the UTF-16 encoding and byte order:
```
hexdump -C trunc.fasta
00000000  ff fe 3e 00 74 00 72 00  7c 00 53 00 36 00 43 00  |..>.t.r.|.S.6.C.|
00000010  4b 00 54 00 33 00 7c 00  53 00 36 00 43 00 4b 00  |K.T.3.|.S.6.C.K.|
00000020  54 00 33 00 5f 00 39 00  41 00 43 00 54 00 4e 00  |T.3._.9.A.C.T.N.|
00000030  20 00 50 00 68 00 6f 00  73 00 70 00 68 00 61 00  | .P.h.o.s.p.h.a.|
00000040  74 00 65 00 20 00 61 00  63 00 79 00 6c 00 74 00  |t.e. .a.c.y.l.t.|
00000050  72 00 61 00 6e 00 73 00  66 00 65 00 72 00 61 00  |r.a.n.s.f.e.r.a.|
00000060  73 00 65 00 20 00 4f 00  53 00 3d 00 41 00 64 00  |s.e. .O.S.=.A.d.|
```

**Comment by timosachsenberg** [comment]
workaround:
```
iconv -f UTF-16LE -t ASCII//TRANSLIT in.fasta > out.fasta
```

**Comment by cbielow** [comment]
I guess this issue applies to all our files? I just tried to `FileInfo -in ` a UTF-16 encoded mzML and it will fail with `XMLHandler.cpp(103): While loading 'BSA1_UTF16.mzML': invalid document structure( in line 1 column 44)
Probable cause: The file suffix (mzML) does not match the file content (unknown). Rename the file to fix this.`

**Comment by jpfeuffer** [comment]
Yes, see also the issue with the Unimod database.

**Comment by timosachsenberg** [comment]
I think using utf-8 is reasonable but who would use UFT-16 anyway? it will just double the size of the fasta file

**Comment by cbielow** [comment]
correction: if the encoding in the XML file is correct, our Xerces Parser will produce the correct results for mzML files. In particular, using 'encoding="ISO-8859-1"' even though the file is UTF-16 will lead to an error (see above), but if the encoding-spec corresponds to the actual encoding, it works smoothly. Also removing the encoding-spec from the XML-header line produces the correct results.

So I guess, if we parse FASTA files using Xerces, it will figure out the encoding correctly.
Alternatively we could peek the first bytes of each file ourselves, but thats no fun.

**Comment by timosachsenberg** [comment]
I think we might need to check back with the seqan guys. We use their parser so maybe they can handle it

**Comment by jpfeuffer** [comment]
All I know is that they restructured their I/O module completely in 2.x.
@rrahn

**Comment by cbielow** [comment]
SeqAn cannot handle it. Its all ASCII (just talked to the core devs)

**Comment by hroest** [comment]
> correction: if the encoding in the XML file is correct, our Xerces Parser will produce the correct results for mzML files. 

yes, if by "correct" you mean that we can read and write them again? I dont think we can really do much with the string itself (since it is stored as `std::string`)

> In particular, using 'encoding="ISO-8859-1"' even though the file is UTF-16 will lead to an error (see above), but if the encoding-spec corresponds to the actual encoding, it works smoothly. Also removing the encoding-spec from the XML-header line produces the correct results.

this is actually expected behavior, almost all software will fail if you give it the wrong encoding information (e.g. web browsers)

**Comment by hroest** [comment]
PS: @timosachsenberg  regarding usage of UTF16 - actually xerces internally uses UTF16 http://stackoverflow.com/questions/9826518/purpose-of-xmlstringtranscode

so basically whatever format we have on disk (ASCII, UTF8, UTF16) gets converted to UTF16 in xerces and we then use the `transcode` function to convert it all to the local format (mostly UTF8 I guess) and then store it as `char *` in OpenMS. This explains why our XML parsing can be painfully slow as there are multiple conversions going on. It also explains why I was able to speed up Base64 encoding substantially since it is *extremely* wasteful to `transcode` these Base64 strings assuming they are UTF16 when in fact we know they are Base64 and only contain ASCII characters.

**Comment by hroest** [comment]
PPS: just another reason why storing GBs of data in XML format is a bad idea ...

**Comment by mwalzer** [comment]
@hroest 
>PPS: just another reason why storing GBs of data in XML format is a bad idea ...

Mh, I don't know, isn't this like saying tall split-level homes (or any other) are bad, just because we only know how to enter these *walking backwards*.
But yeah, encoding and transcoding is a pain.

**Comment by rrahn** [comment]
Hi, I just looked again deeper into the SeqAn code. 
For a fact, the pretty ```FormattedFile``` interface does not allow to handle value types other than ```char```, but we do have a ```VirtualStream``` class, that potentially work on any character type. It simply uses ```std::basic_streambuf``` implementation in the backend. We then have some undocumented API interfaces, that allow to read fasta format from an iterator of that ```VirtualStream```. If you guys, are interested in a internal solution for OpenMS, I can talk to @jpfeuffer or @cbielow. But it requires SeqAn 2.x. Also, this is not yet really tested or tried out, so I can't promise anything.

**Comment by hroest** [comment]
@mwalzer transcoding is especially a pain when you *know* that all Base64 is in pure ASCII but you still spend all the effort to properly transcode it ... so its more like you take a landmine detector with you wherever you go and check every step extra careful, taking a really long time to walk, someplace in the middle of a city where there are no landmines

**Comment by hroest** [comment]
PS: for the matter at hand, since this wont happen very often, why not just give out a sensible error message and tell the user how to convert the file to something seqan can read? I am not sure its worthwhile to spend too much effort to code a solution for a rare edge case (who stores their fasta files in non-ASCII ?)

**Comment by timosachsenberg** [comment]
I agree und this would also be my preferred solution

**Comment by mwalzer** [comment]
haha, yeah, how many landmines are out there? But I would not want to stir up a movement away from XML and esp. the PSI formats as exchange format.
In my view, such sensible error message would be an apt solution. :+1:
