### ISSUE TITLE
indexed mzML output has incorrect checksum

### ISSUE THREAD

**Issue by jvolkening** [OpenMS/OpenMS#2418]
Using OpenMS 2.1, PeakPickerHiRes produces an indexed mzML with a `<fileChecksum>` value of 0. This element should contain the SHA-1 checksum of the file up to that point -- the output file file thus fails validation.

Is this a known shortcoming or bug? I couldn't find it mentioned anywhere in my search.

**Comment by hroest** [comment]
this is indeed a known limitation - but not a well documented one https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzMLHandlerHelper.cpp#L145

so far nobody has implemented the checksum feature, I guess we would have to pipe all output through a class that calculates SHA1 on the stream (it is possible to do that, as SHA1 operates on blocks). I guess its quite a bit of work and so far nobody has done it.

**Comment by timosachsenberg** [comment]
found a commit that implements SHA-1 calculation in FileHandler https://github.com/OpenMS/OpenMS/commit/d0c7c3fff30243403082c975d28cb01a4de79ae4

**Comment by cbielow** [comment]
the Qt function is certainly useful. We just need to figure out how it deals with newlines etc.
i.e. when the stream receives '\n', it might end up being '\r\n' on disk on Windows.

**Comment by hroest** [comment]
@cbielow so how does proteowizard handle this problem? 

to me it seems still like a somewhat clunky way of doing checksums, I feel its much better to do it like everybody else: have a separate file with full-file checksums to validate complete downloads. I have never seen anybody else who would think putting the checksum inside the file is a good idea

**Comment by jvolkening** [comment]
> @cbielow so how does proteowizard handle this problem?

Proteowizard uses LF for all newlines, regardless of platform (at least it appears so based on the files I have at hand).

I have software that can insert the proper checksum prior to the next step of the workflow in order to allow the file to validate, so it's not a big deal. I really just wanted to confirm that this was a known issue and not a bug per se. I will leave the issue open as a marker for someone to possible fix this in the future, but feel free to close it if you wish.

**Comment by hroest** [comment]
yes, lets leave this open as a reminder

@jvolkening just out of curiosity, what is your usecase for needing the correct checksum in the files? Do you have software that validates the the checksum and rejects the file otherwise? 

Also @jvolkening would you mind sharing the script that you use for fixing the checksum in case someboy else needs it as well? I guess the other workaround would be to use proteowizard to "fix" the files

**Comment by jvolkening** [comment]
> @jvolkening just out of curiosity, what is your usecase for needing the correct checksum in the files? Do you have software that validates the the checksum and rejects the file otherwise?

Yes, but since I wrote the software I can make it less strict. Again, it's really not a big deal. Apparently Proteowizard doesn't even bother to check the SHA-1 sum.

> Also @jvolkening would you mind sharing the script that you use for fixing the checksum in case someboy else needs it as well? I guess the other workaround would be to use proteowizard to "fix" the files

I put the code [here](https://gist.github.com/jvolkening/1a5ebbe5ff635f79843885c5c7a3d432) - I use this to re-calculate the index offsets as well as the checksum if I need to modify the mzML headers. Running it back through `msconvert` works too, although as I understand pwiz unpacks and repacks the array data if you're using Numpress compression, and I'm not sure of the potential ramifications of this as they are lossy algorithms.

**Comment by hroest** [comment]
great, I guess these are workarounds for now and will work for people that need the checksums.

yes, also OpenMS re-packs the numpress arrays. I have not looked into this but it is possible that you loose accuracy each time you read and store the data (similar to other lossy compression).
