### ISSUE TITLE
ModificationsDB has no names

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#2421]
Seems like ModificationsDB does not contain anything for any mod in the name member.
You could try something like:
```
String TEST = "Carbamidomethyl";
ResidueModification m = ModificationsDB::getInstance()->getModification(TEST, "C", ResidueModification::N_TERM);
LOG_ERROR << "?" << m.getName() << " - "<< m.getFullId() << " - "<< m.getFullName() << "!"<< endl;
```
Also, it appears, 'residue' parameter is overridden by 'terminal' parameter in the getModification function. That should go into the documentation.

Can anyone confirm?

**Comment by hendrikweisser** [comment]
> Also, it appears, 'residue' parameter is overridden by 'terminal' parameter in the getModification function. That should go into the documentation.

I'm not sure if I understand you correctly. If both `residue` and `term_spec` are set, only modifications matching both specificities should be found. Do you have a counter-example?

**Comment by hendrikweisser** [comment]
> If both `residue` and `term_spec` are set, only modifications matching both specificities should be found.

I should have rather said "modifications compatible with both specificities". Using your example: If you have a "C" at the N-terminus with a carbamidomethylation, both "Carbamidomethyl (C)" and "Carbamidomethyl (N-term)" would be compatible, but "Carbamidomethyl (C)" should be given preference. "Carbamidomethyl (N-term A)" (which doesn't exist) would *not* be compatible.

**Comment by mwalzer** [comment]
No, the point is ```m.getName()``` - the name member
