### ISSUE TITLE
OpenMS on Ubuntu 16.04

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2423]
It seems that compiling OpenMS 16.04 works pretty much out of the box except for Wildmagic. 

This has been reported here 

- https://github.com/OpenMS/OpenMS/issues/2331
- https://github.com/OpenMS/OpenMS/issues/1483
- https://bugs.launchpad.net/ubuntu/+source/libwildmagic/+bug/1578222

but due to some unfortunate circumstances, the default package on 16.04 is still `5.13-1ubuntu1` and not the fixed `5.13-1ubuntu2`. As this has already bitten a few people, we should include this into the install instructions and maybe (I guess that would be hard to do) add a check to cmake.

Apart from that `seqan-dev` and `libeigen3-dev` on Ubuntu 16.04 seem to work very well. However, when running all the tests I see the following tests fail

```
The following tests FAILED:
        336 - SvmTheoreticalSpectrumGenerator_test (Failed)
        338 - SvmTheoreticalSpectrumGeneratorSet_test (Failed)
        505 - IonizationSimulation_test (Failed)
        506 - MSSim_test (Failed)
        509 - RawTandemMSSignalSimulation_test (Failed)
        516 - MRMAssay_test (Failed)
        1676 - TOPP_FeatureLinkerUnlabeledQT_5_out1 (Failed)
        1678 - TOPP_FeatureLinkerUnlabeledQT_6_out1 (Failed)
Errors while running CTest
```

there seems to be something not quite right about randomization as for example the FeatureLinkerQT files only differ in output order.

**Comment by hroest** [comment]
Interestingly, quite a few of the tests also fail with MSVS 2015 see #2001

**Comment by hroest** [comment]
for FFQT compare http://pastebin.com/ZCXsw4GT with our current expected output http://pastebin.com/2VxJeFD8 its basically the same clusters but the `PeptideIdentification` are in a different order (same for the test `TOPP_FeatureLinkerUnlabeledQT_6_out1`)

**Comment by jpfeuffer** [comment]
Yes I remember these tests failing with MSVC2015. I have the same guess about randomisation.
I will see what I can do about Wildmagic in the build system and I will update the docu.

**Comment by hroest** [comment]
it basically seems to be the simulation and some other code that uses randomization

@grosenberger can you look into the MRMAssay part? It looks to me like a an issue with the UIS transition generate
```
$ diff  ./src/tests/class_tests/openms/MRMAssay_test_641.tmp /home/hr/openmsall/source/OpenMS/src/tests/class_tests/openms/data/MRMAssay_uisTransitions_output_2.TraML | less

10186c10186
<     <Transition id="UISDECOY_{LHIN(Deamidated)QAR|LHINQ(Deamidated)AR|LHINQAR}_381.6818_101.5749_-39.95_y2-C1H2N1O1^2" peptideRef="1_sp|P0C0L4|CO4A_HUMAN_AAAN(Deamidated)QMR_2_-39.95">
---
>     <Transition id="UISDECOY_{NENN(Deamidated)QER|NENNQ(Deamidated)ER|NENNQER}_381.6818_130.5776_-39.95_y2-C1H2N1O1^2" peptideRef="1_sp|P0C0L4|CO4A_HUMAN_AAAN(Deamidated)QMR_2_-39.95">

```

**Comment by grosenberger** [comment]
The randomisation in MRMAssay is done very similarly as in MRMDecoy and I only used boost functionality. I will try to fix the problem ASAP, but it might take a few days.

**Comment by hroest** [comment]
sure, there is no hurry. Ubuntu 16.04 has been out for 9 months so there is
no immediate need but I think there may be an underlying bug in this code
which would be good to fix anyways. Could someone else look at the
simulation code and the SVM code?
