### ISSUE TITLE
[DOC] Feature Finders

### ISSUE THREAD

**Issue by Stortebecker** [OpenMS/OpenMS#2424]
Hej all.

OMS features quite  a lot of different Feature Finders (FF). Are there any recommendations which FF is best used for specific vendors or experiment types? What were the different tools designed for and tested on? 

An example (correct me @lars20070 , if I am wrong):
`FeatureFinderMultiplex` was originally designed for stable-isotope-labelling (SIL), but labelfree has been integrated later on. Also, it has mostly been used on Thermo machines, but @lars20070 told me that he is working to improve on Bruker and Sciex as well.

Can the tool developers please comment? Thanks a lot!

**Comment by Stortebecker** [comment]
One more question: are you planning to maintain / improve all of the FFs in future?

**Comment by hendrikweisser** [comment]
The most used feature finder, and probably still the default option at the moment, is FeatureFinderCentroided. It is intended for high-res data that has been centroided (e.g. using PeakPickerHiRes). The relevant publication is linked in the documentation.

FeatureFinderIsotopeWavelet is an older approach. It's also applicable to low-res data (probably not so important nowadays), but very slow on high-res data, unless you have specialized hardware (it can run on - some - GPUs). This is probably not a relevant option for most applications.

"My" feature finder is FeatureFinderIdentification. It's new and not widely tested (only on Thermo data for now), but we have had some very good results with it (manuscript in preparation). If you have a fixed set of peptides that you want to quantify (e.g. if you ran a shotgun experiment with a database search), give it a try. The caveat is that it's currently not very fast, if applied to peptide IDs from multiple runs.

FeatureFinderMetabo and FeatureFinderMRM are specialized tools for metabolomics and MRM data, respectively, so they fall into different categories than the rest.

**Comment by hendrikweisser** [comment]
> are you planning to maintain / improve all of the FFs in future?

FFIsotopeWavelet has not been updated for some years now, at least the actual algorithm. I think we should consider deprecating it.

FFCentroided is pretty stable, but not actively worked on. It may be superseded by FFMultiplex in the future.

FFMultiplex and FFIdentification are probably going to be maintained/improved (depending on developer availability) until somebody comes up with something even better. I would assume the same goes for FFMetabo and FFMRM, but I know less about them.

**Comment by hendrikweisser** [comment]
Oh, there's also FeatureFinderSuperHirn (in the UTILS category) - a port of the original SuperHirn code to OpenMS. I don't know how well it works and have suggested removing it before (#2094).

**Comment by hroest** [comment]
@hendrikweisser the main problem is that there isnt a place where we clearly state which one is the "default" FF - so if I am new to OpenMS I guess I just see a bunch of tools called featurefinder and it is not clear which ones are under development, which ones are stable and which ones are basically deprecated. Would it maybe help to add to the doc something like "unless you know what you are doing, use FF Centroid"?

**Comment by timosachsenberg** [comment]
maybe a cheat sheet would be cool to list most commonly used tools. e.g., for feature detection, linking, Id etc.

**Comment by Stortebecker** [comment]
Hej @hendrikweisser !

Thanks for the answer. To include my two cents: why not integrate the ideas of FFMult and FFIdent? That is, do a first round of Quant with FFMult, based solely on the raw data, not on peptide IDs. Then do a second search with FFIdent after having identified the peptides. There are good reasons for both kinds of approaches, which I will not elaborate on here. I guess you know them better than I do. 

I guess combining both tools either in a workflow or on the long run even into a single tool (but still keeping the dual quantitation approach with two separate algorithms) which then takes both raw and peptide IDs as an input may be extremely powerful.

Flo

**Comment by Stortebecker** [comment]
> FFIsotopeWavelet has not been updated for some years now, at least the actual algorithm. I think we should consider deprecating it.

If FFCentroided also runs fine with input from older machines, I agree.

> Oh, there's also FeatureFinderSuperHirn (in the UTILS category) - a port of the original SuperHirn code to OpenMS. I don't know how well it works and have suggested removing it before (#2094).

Yes, this algorithm is pretty old, I think. I do not know, if it is still maintained or improved. I guess your own algorithms will do a better job. Did not test it, though.

> "My" feature finder is FeatureFinderIdentification. It's new and not widely tested (only on Thermo data for now), but we have had some very good results with it (manuscript in preparation). If you have a fixed set of peptides that you want to quantify (e.g. if you ran a shotgun experiment with a database search), give it a try. The caveat is that it's currently not very fast, if applied to peptide IDs from multiple runs.

Then good luck with the paper! And I do not care about performance, I am working on the HUGE Freiburg Galaxy server...

**Comment by hendrikweisser** [comment]
>  if I am new to OpenMS I guess I just see a bunch of tools called featurefinder and it is not clear which ones are under development, which ones are stable and which ones are basically deprecated

This is a good point. I've added it to the agenda for the developer meeting (https://github.com/OpenMS/OpenMS/wiki/Retreat-Spring-2017#guidance-on-toolalgorithm-alternatives).

**Comment by hendrikweisser** [comment]
@Stortebecker:
> To include my two cents: why not integrate the ideas of FFMult and FFIdent?

I think it's a bit early to talk about that. Both algorithms need to be published and more widely tested first. ;-)

Also, there is an inherent trade-off: Detecting features just based on the raw data is more difficult, but you can use the results to aid in peptide identification (e.g. by doing precursor mass correction or generating inclusion lists). On the other hand, if you can use peptide IDs that you already have, feature detection can become easier, but you lose the other advantages.
(Maybe this is what you meant by "good reasons for both kinds of approaches".)

There is a case to be made for tighter coupling of identification and quantification - which is what e.g. MaxQuant does with Andromeda, if I'm not mistaken.

**Comment by Stortebecker** [comment]
>(Maybe this is what you meant by "good reasons for both kinds of approaches".)

Exactly. That's why I want to combine both approaches. Getting the benefits of both approaches while cancelling out the drawbacks.

> There is a case to be made for tighter coupling of identification and quantification - which is what e.g. MaxQuant does with Andromeda, if I'm not mistaken.

What **DO** they do with MQ / Andromeda anyway? I was trying to find out, but did not succeed so far. Did they describe this crosstalk in some paper?

**Comment by Stortebecker** [comment]
> maybe a cheat sheet would be cool to list most commonly used tools. e.g., for feature detection, linking, Id etc.

This would be very helpful!

**Comment by Stortebecker** [comment]
> Are there any recommendations which FF is best used for specific vendors or experiment types? What were the different tools designed for and tested on?

Could you elaborate a bit more on this, @hendrikweisser ?

**Comment by hendrikweisser** [comment]
@Stortebecker:
All the "normal" feature finders (except FFMRM and FFMetabo) are intended for label-free (shotgun) data. I've only worked with Thermo data, but the data should look pretty much the same for any instrument/vendor, except for differences in mass accuracy (for which there are usually one or more parameters). You can get issues with the dynamic range (for extremely high-abundant peptides) and with stability of the electrospray, both of which can cause problems for feature detection because they distort peak shapes, but those are independent of the instrument type.

@hroest, @grosenberger: In your experience with Sciex Triple-TOF data, do the MS1 maps look different than those from Thermo instruments?
