### ISSUE TITLE
pyOpenMS build error

### ISSUE THREAD

**Issue by dmccloskey** [OpenMS/OpenMS#2440]
SYSTEM INFORMATION:
64 bit
OpenMS 2.0.0 Release
Ubuntu 14.04
Docker 1.13.1
Dockerfile: https://github.com/dmccloskey/docker_openms/Dockerfile
Error: https://github.com/dmccloskey/docker_openms/pyOpenMS/pyopenms_error

ERROR REPORT FROM BUILD:
...
INFO:root:create wrapper for free function removeOutliersRANSAC
INFO:root:create wrapper for free function writable
Autwrap has wrapped 452 classes, 4585 methods and 69 enums
created pyopenms.cpp

platform  linux not supported yet

[100%] Built target pyopenms_create_cpp
Extracting in /tmp/tmp6dhb5r2o
Traceback (most recent call last):
  File "/home/user/openms-build/pyOpenMS/distribute_setup.py", line 150, in use_setuptools
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    distribute_setup.use_setuptools()
  File "/home/user/openms-build/pyOpenMS/distribute_setup.py", line 152, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/user/openms-build/pyOpenMS/distribute_setup.py", line 132, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/home/user/openms-build/pyOpenMS/distribute_setup.py", line 105, in _build_egg
    _extractall(tar)
  File "/home/user/openms-build/pyOpenMS/distribute_setup.py", line 500, in _extractall
    self.chown(tarinfo, dirpath)
TypeError: chown() missing 1 required positional argument: 'numeric_owner'
make[3]: *** [src/pyOpenMS/CMakeFiles/pyopenms] Error 1
make[2]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/all] Error 2
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/rule] Error 2
make: *** [pyopenms] Error 2

**Comment by hroest** [comment]
maybe @uweschmitt  can comment on this issue?

**Comment by hroest** [comment]
@dmccloskey can you provide the output of 
```
sys.platform
```

on your system? With which version of Python are you building?

**Comment by dmccloskey** [comment]
I am not sure what you mean by the command sys.platform, but the output of
lscpu is the following:

Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 4
On-line CPU(s) list: 0-3
Thread(s) per core: 1
Core(s) per socket: 4
Socket(s): 1
NUMA node(s): 1
Vendor ID: GenuineIntel
CPU family: 6
Model: 45
Stepping: 7
CPU MHz: 2981.367
BogoMIPS: 5985.59
Virtualization: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 256K
L3 cache: 10240K
NUMA node0 CPU(s): 0-3

I was using Python 3.5.1 to build.

**Comment by hroest** [comment]
yes, so Python 3 is not supported yet by OpenMS 2.0.0 - you would have to use 2.0.1

**Comment by dmccloskey** [comment]
I re-built pyopenms using openMS 2.1.0 and python 3.6.0 and it seems to
work.

Thanks for all of your help!

Douglas

**Comment by hroest** [comment]
great to hear!
