### ISSUE TITLE
Doc improvements

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#2441]
this Issue collects Documentation issues. Feel free to add things. we will look at them during Dev Retreat

http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/TOPP_MassTraceExtractor.html
has no detailed parameter list (the orange stuff at the bottom) and the docs are mediocre.

**Comment by oliveralka** [comment]
http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/TOPP_IsobaricAnalyzer.html

- if necessary example for conversion product data sheet to correction matrix - see tool description
- show mass mapping (?)
