### ISSUE TITLE
Loss of MZ precision through MSGF Search

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2442]
The experimental and calculated MZs that are exported from MSGF+
are single-precision float values cast to doubles before writing.
See e.g.
https://github.com/sangtaekim/msgfplus/blob/949350676c7ad8acf9f2058e6eb6dbffb1291889/src/main/java/edu/ucsd/msjava/mzid/MZIdentMLGen.java#L336

I stumbled across this when analysing precursor mass deviations of an MSGF+ search, with artefacts in the distributions.
For the calculated MZ it's not so bad because you can recalculate them with our methods but it also affects the experimental precursor mass which we need to look up again in the mzML to get the full precision.
What's the standard precision coming out of the RAW files by the way?

**Comment by hendrikweisser** [comment]
@jpfeuffer: Have you opened an issue with MS-GF+?

@ypriverol: You said you were working on the MS-GF+ code. Would you be able to have a look at this?

**Comment by jpfeuffer** [comment]
I looked a bit deeper into the code and it seems like everything is based on floats in there.
When they read the experimental precursor mz it is already a float.
https://github.com/sangtaekim/msgfplus/blob/949350676c7ad8acf9f2058e6eb6dbffb1291889/src/main/java/edu/ucsd/msjava/msutil/Spectrum.java#L75
Therefore my question on what precision is actually usually stored in the raw or mzML. Do floats suffice for current instruments and theoretical atom/residue masses?

Of course what I could and probably will ask, is that they should not just fake-increase the precision when writing their outputs.
