### ISSUE TITLE
psi.hupo.org

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2446]
Currently our link to the XML namespace goes to `http://psi.hupo.org/ms/mzml`, as seen here:

```
os << "<mzML xmlns=\"http://psi.hupo.org/ms/mzml\" 
```

however, `psi.hupo.org` does not resolve any more:

```
$ host psi.hupo.org
Host psi.hupo.org not found: 3(NXDOMAIN)
```

does anybody know whats going on? Interestingly, the xsd file is given with two locations: `xsi:schemaLocation=http://psi.hupo.org/ms/mzml      http://psidev.info/files/ms/mzML/xsd/mzML1.1.0.xsd` of which only the latter works. So is the psi.hupo.org only there for historic reasons?

**Comment by jpfeuffer** [comment]
@mwalzer Do you know something about this?

**Comment by mwalzer** [comment]
Well, I don't know about `psi.hupo.org` in the first place.
