### ISSUE TITLE
MSStats integration

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2454]
this issue is intended to collect discussions and work regarding MSStats integration

**Comment by hroest** [comment]
I guess one of the first issues will be the licence. It used to have a licence on github and on Bioconductor it is listed as "Artistic-2" https://bioconductor.org/packages/release/bioc/html/MSstats.html but the license is now gone from github.

Furthermore, the Artistic-2 allows re-licencing:

> (ii) a license that permits the licensee to freely copy, modify and redistribute the Modified Version using the same licensing terms that apply to the copy that the licensee received, and requires that the Source form of the Modified Version, and of any works derived from it, be made freely available in that license fees are prohibited but Distributor Fees are allowed.

however I dont think that that **requires that [...] be made freely available** is applicable to BSD so I dont think we can relicence Artistic to BSD. Probably easiest would be to write to the authors and ask them whether they would clarify the license terms and consider re-licencing under BSD. If not, we can just distribute under Artistic-2 I think, that should not be a problem, right?

**Comment by timosachsenberg** [comment]
I contact Mee or Olga on this. I think distributing it under Artistic-2 would not be a problem.

**Comment by mwalzer** [comment]
See here (https://gist.github.com/mwalzer/427e14807ef96c9d5bbedaef63dea1ab) for a R based converter from our TextExporter csv to MSstats input after initial consultation with Meena. 
One crucial thing missing is the information about the experimental setup, of which our output exempt for now. I think it would be really good to weave it into mzTab to get that info to properly reflect the BioReplicate and Run columns.

**Comment by mwalzer** [comment]
Not sure, where we should weave-in transition information.

**Comment by timosachsenberg** [comment]
Thanks!  So this takes the default TextExporter output? Can you give me a hint what these duplicate observations are? Do you have a complete example that reads the TextExporter file and runs msstats analysis?

**Comment by hroest** [comment]
some people at ETH also use https://bioconductor.org/packages/release/bioc/html/SWATH2stats.html which could be included in the pipeline here as well for SWATH-MS data. MAybe @grosenberger can comment whether it would make sense to include this here as well in the discussion.

**Comment by timosachsenberg** [comment]
Would be great to have complete workflows with downstream analysis. Probably KNIME would provide a good integration platform that support anyways.

**Comment by hendrikweisser** [comment]
I found that the output of `ProteinQuantifier -filter_charge -peptide_out ...` gives you a table that is easy to transform into what MSstats needs.

> See here (https://gist.github.com/mwalzer/427e14807ef96c9d5bbedaef63dea1ab) for a R based converter from our TextExporter csv to MSstats input after initial consultation with Meena.

@mwalzer: To what extent are the non-standard libraries needed there? Would it be better to provide an implementation that doesn't need them, or is that just me being old-fashioned? ;-)

**Comment by mwalzer** [comment]
Yeah, dplyr/tidyr is pretty common. Do it yourself would mean a lot more of code.

**Comment by mwalzer** [comment]
@timosachsenberg the duplicates are sequence duplicates (in different features/charges). To avoid that they are all 'gathered' in one row, I introduce that temporary col.

**Comment by jpfeuffer** [comment]
I also have a KNIME workflow that takes the ProteinQuantifier output and a table that annotates the input raw/mzML files and gives you MSStats output. The only R function used is "stack". But I would also like to have that experimental design in mzTab.

**Comment by tjeerdijk** [comment]
Hi Julianus,

Can you share your workflow? I'm in discussion with Meena here at the ASMS conference so would be nice to show your solution before we all go home.

Take care from Tjeerd (from Indianapolis)

**Comment by jpfeuffer** [comment]
Hi Tjeerd,
I uploaded the workflow including some really bad example data under the following link:
https://mab.to/240SOedvX
The workflow should include the data as tables but I included the input mzTab files, too.
The protein grouping part is rather new but should do what it is supposed to do. Concerning the last MSStats scripts, Meena should be the expert there.
I expect a lot to get easier in the future (integration of exp. design, ProteinQuantifier mzTab support) but this is what we got for now.

Cheers to Indianapolis
Julianus

Attached the WF without data for reproducibility. Link expires.
[iPRG2015-MSstats_nodata.zip](https://github.com/OpenMS/OpenMS/files/1059579/iPRG2015-MSstats_nodata.zip)

**Comment by timosachsenberg** [comment]
I think we should merge (and extend) the fraction / experimental design support PR to get this information into protein quantifier.

**Comment by tjeerdijk** [comment]
I discussed this with Meena and I think the solution that is currently offered for the MaxQuant-MSStats integration is good enough. Basically it is a csv file linking (raw) spectra files to experimental conditions and biological replicates. What do you think? @julianus: I'll look at your workflow after my poster presentation, thank you for your quick reply.
[annotation.csv.zip](https://github.com/OpenMS/OpenMS/files/1061255/annotation.csv.zip)

**Comment by jpfeuffer** [comment]
Yes, exactly, that is what I did in the workflow. You extract the raw filenames from the mzTab metadata header and create a table (e.g. directly KNIME, or Excel and read it in) that describes every raw file with the descriptors that MSStats expects (BioReplicate, Run, ...). This is then integrated into the tables that contain quantitation information (wherever they may come from)

**Comment by lukaszimmermann** [comment]
@jpfeuffer  could you maybe again upload the workflow with the example data? Not sure where I saved it back then....

**Comment by lars20070** [comment]
@tjeerdijk Does the MaxQuant-MSStats integration allow the import of protein groups to MSStats?

About two years ago I tried, but could not find suitable protein group data structures in MSStats. Is it now possible to import the complete `mzTab` content to MSStats?

**Comment by lukaszimmermann** [comment]
So I'd go with writing an util which consumes the protein inference (idXML, mzid,..), the consensusXML, and the experimental design in some TSV format and writes the input table for MSstats. Does that make sense?
If so @jpfeuffer , could you perhaps provide the original consensusXML and idXML from Fido (or whatever), which you used in the iPRG2015 workflow? This is probably more useful for the util than the mzTab stuff. Then I could work an test with those files. Thanks!

**Comment by jpfeuffer** [comment]
Ah yes. Forgot about it. But I am not sure if that is a good sample dataset since it does not contain any fractions and is very large. So you get high execution times with not even full complexity.
Will appear there:
https://mab.to/U98xOV6Ia

**Comment by jpfeuffer** [comment]
Experimental design is in the workflow.

**Comment by lars20070** [comment]
FYI @LucasKook. Maybe we can contribute to the integration.

**Comment by lukaszimmermann** [comment]
Ok thanks. Let's see how far I get.

**Comment by lars20070** [comment]
@lukaszimmermann As I understand, you plan to interface with OpenMS formats such as `idXML`, `consensusXML` etc.

Why not using pure `mzTab` only? What information is not in `mzTab`?

**Comment by lukaszimmermann** [comment]
I guess that this is also possible. Probably both input methods should be supported.

**Comment by jpfeuffer** [comment]
I think the use case would be to use such a tool instead of ProteinQuantifier. Where it doesn't do quantification but just merges, maps and transforms the inputs. I agree that in theory both mzTab and internal formats could be used. I guess I am slightly in favor of starting with out internal formats?

**Comment by lukaszimmermann** [comment]
Ok, for now I am going to proceed with the internal formats.

**Comment by lars20070** [comment]
Ok. - FYI, some of [our post-processing scripts](https://github.com/ProteomicsScripts/ProteomicsScripts) in Freiburg are also still based on internal `consensusXML` but we are in the process of converting everything to `mzTab`.

**Comment by jpfeuffer** [comment]
I see and that's okay. I mean the new one wouldn't be a real post-processing "script" since it will be an integrated TOPP tool, that's why I think it makes sense to start with the internal formats.

**Comment by lars20070** [comment]
Ok, now I get it. *Final results* could still leave our workflow as `mzTab`.

**Comment by pavel-shliaha** [comment]
Has anyone run TMT analysis in OpenMS with subsequent protein inference in MSStats?

**Comment by jpfeuffer** [comment]
We now have working KNIME and nextflow workflows for TMT with MSstatsTMT
