### ISSUE TITLE
PeakPickerHiRes signal to noise estimator

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2459]
Hi,
1. I made the experience that the default signal to noise setting of PeakPickerHiRes often looses good features or mass traces on orbitrap and SCIEX instruments.
I would vote for disabling it by default but would like to hear about your experience.
Hi,
2. I made the experience that the most common configuration are profile MS1 peaks and centroided MS2.
I would vote for making this the default.
3. Also, if a spectrum is annotated as centroided, we could just issue a warning and omit picking for that spectrum. Note that we should still stop processing if it is not annotated but has to be estimated from the spectrum.

@hendrikweisser @hannesveit @hroest @cbielow @lars20070 @mwalzer

**Comment by lars20070** [comment]
+1

I always switch the noise estimation off, `signal_to_noise = 0`.

**Comment by hroest** [comment]
I think it depends on the kind of data you have - for TOF data, low res data and for chromatographic data it does make sense to have a S/N cutoff. In my workflow for chromatographic data I set it to a low value, generally to `0.1` for chromatographic data

> Also, if a spectrum is annotated as centroided, we could just issue a warning and omit picking for that spectrum. Note that we should still stop processing if it is not annotated but has to be estimated from the spectrum.

I would include a `force` flag then that still allows you to pick -- nothing more annoying than a software that thinks it knows better what you want and makes the wrong decision!

**Comment by hannesveit** [comment]
1. I agree with changing the default setting to S/N = 0. Of course, as @hroest pointed out, there are various use cases where an S/N cutoff makes sense. But when it comes to choosing a default, at least in my experience, S/N = 0 is probably the safer option.

2. I agree with picking only MS1 by default.

3. I agree with @hroest. Better safe than sorry.

**Comment by mwalzer** [comment]
1. I usually switched S/N off, so I can only support the notion of default ```signal_to_noise = 0```.
2. That's what I experienced as well.
3. I like Hannes' suggestion of a force flag

**Comment by timosachsenberg** [comment]
Note: I did not implement the special handling of already picked spectra.
