### ISSUE TITLE
Cross-Link classes specification

### ISSUE THREAD

**Issue by lukaszimmermann** [OpenMS/OpenMS#2460]
Hi everybody,

I am currently working on FDR estimations for cross-linked peptides and also in this context writing an util for doing such FDR. This currently requires the classification of peptide hits into different types (based on the matched database (target/decoy) and the proteins associated with each peptide of the peptide pair).
One can distinguish between target/decoy hits and also between inter, intra, mono, and loop links. How a particular PeptideHit is classified in this way depends on the associated meta values, as such information currently employs the MetaInfoInterface for Peptideidentification and PeptideHit.

As I do not want to hard-code the relationship between these meta values and the grouping into the cross-link classes, therefore I made up a file format for specifying these relationships. See this link here:
https://www.dropbox.com/s/nw7ekhzqy127xtc/classes.dat?dl=0

Class specifications are delimited via '$' and each resulting block reads as a DNF, where '>' separates the clauses.  I have written a parser for this format.

Advantages are:
- There is no need to hard-code the meta value string in the source code.
- When the names of the meta value change, only the file needs to be adapted, not the sources.

Disadvantages:
- The file rarely changes if the class specifications do not change.
- Related: The file needs to be passed as argument each time the util is executed.

I am unsure about the following points:
- Should the current file format be kept, or is there are better suited alternative? (I looked at Param files, but I do not think that this would work well). 
- Should the file be passed to the util for each invocation or can it be placed at a certain location within an OpenMS installation, such that it can be read by the util automatically? (and be overridden by argument if necessary).

Thanks!

**Comment by timosachsenberg** [comment]
Hi @lukaszimmermann,
I think the approach you took solves a specific design problem very well: you want to maximize flexibility in defining and changing terms related to cross-linking types as well as the use of meta values and introduce a semantic ruleset to tighten and validate the use of these terms.
My personal opinion (and I may misjudge this) is that this is a bit over overdesigned.
My feeling is, that these terms rarely change (particularly after the release of the software), increase complexity and requires more documentation. It comes also with the need for additional file access. I know that some parts of OpenMS rely heavily on external files but these were, imho, at least in parts suboptimal design decisions.
Defining predicates (e.g. isHybridDecoysIntraLinks) in C++ is as expressive and faster (but only configurable at compile time) and I would probably choose to do so.

**Comment by hroest** [comment]
I am in favour of a flexible solution and there would be two ways of doing that:

- the algorithm just expects a metavalue "FDR_group_xxx" where xxx is an identifier and all hits with the same identifier are in the same class
- you provide the sort of mapping based on combinations of meta-values as you suggest

in my view, option 1 seems more flexible and potentially more adaptable to other use-cases (e.g. lets say we want to do FDR for targeted MS or for regular shotgun without any cross-links, we could just use different identifiers, right?). Also it would be trivial to write a short Python program to change the classes if you wish and then call the algorithm on it. Can you comment on whether your algorithm would also work with a simple target-decoy design as used for shotgun proteomics and only 2 FDR groups?

I agree with Timo that the current system seems a bit over-designed.

**Comment by lukaszimmermann** [comment]
Thank you very much @timosachsenberg  and @hroest  for your suggestions.
I also agree that the current system is overdesigned. I tend to do that. 

The problem is reduced to the question of how false positives are counted.  In essence, one defines a function that inspects all hits with the "FDR_group_xxx"  identifiers as meta values and returns 
`((no_target_hits_1, no_fp_hits_1), (no_target_hits_2, no_fp_hits_2), ... , (no_target_hits_n no_fp_hits_n))`
in shotgun proteomics one would have `n = 1` and for cross-linking you may have  `n = 3`, because you might want to distinguish inter/intra/monolinks. 
So given meaningful identifiers and a way of counting targets and fps based on those, the algorithm can work and produce FDRs. 

The "FDR_groups_xxx" are only used for the FDR calculation, so IMO the algorithm/util needs to assign those itself based on the meta values (is_decoy, is_inter ....). The question is where to do that. The first solution was this file, but I think there is nothing wrong doing the grouping internally and put the group assignments into the sources. The idea was that one could also calculate statistics based on the groups (such as score distributions), but still I think the file is overkill, as there probably won't be too many groups. The user will also lose the ability to define custom groups, but I currently doubt that this is of much use.

**Comment by hroest** [comment]
@lukaszimmermann my idea was that the tool that produces the input to your FDR-Util would write these meta-values. But I am also open to using the param file as one for shotgun for example would be quite simple and only have a single group defined. As I said, I would be in favor of the flexibility and against hardcoding as there maybe new usecases in the future

**Comment by lukaszimmermann** [comment]
@hroest Ok, I am going to think more about this. I currently work on getting a first version finished (Writng output is still missing), then we might look again in the PR.
