### ISSUE TITLE
review FalseDiscoveryRate tool

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2465]
As always just a suggestion open for discussion.

What about:
  -in_target <file>  Identification input file containing a search against a target-only database. (valid formats: 'idXML')
  -in_decoy <file>   Identification input file containing a search against a decoy-only database. (valid 

If there is no good reason for them I would remove them. They only complicate the interface and make integration into workflow systems more difficult (e.g., the engine can't check the semantics "Either specify '-in' alone or 'in_target' together with 'in_decoy' as input.")

Make following parameter advanced:
  -proteins_only     If set only the FDR on protein level is calculated
  -peptides_only     If set only the FDR on peptide (PSM) level is calculated

```
Options (mandatory options marked with '*'):
  -in <file>         Identification input file containing a search against a concatenated sequence database. Either specify '-in' alone or 'in_target' together with 'in_decoy' as input.
                     (valid formats: 'idXML')
  -in_target <file>  Identification input file containing a search against a target-only database. (valid formats: 'idXML')
  -in_decoy <file>   Identification input file containing a search against a decoy-only database. (valid formats: 'idXML')
  -out <file>*       Identification output with annotated FDR (valid formats: 'idXML')
  -proteins_only     If set only the FDR on protein level is calculated
  -peptides_only     If set only the FDR on peptide (PSM) level is calculated
```

**Comment by hendrikweisser** [comment]
> Make following parameter advanced:
> -proteins_only If set only the FDR on protein level is calculated
> -peptides_only If set only the FDR on peptide (PSM) level is calculated

I think these parameters are too important to make them advanced. I don't use the FDR tool often, but when I do, I only want to calculate FDRs for one of the levels.

**Comment by jpfeuffer** [comment]
Yes, please leave it. I agree with @hendrikweisser

**Comment by timosachsenberg** [comment]
sure. I just scanned the top used tools and wanted to bring these parameters to discussion

**Comment by timosachsenberg** [comment]
what about the other ones I mentioned?
