### ISSUE TITLE
Add command line section to 'Installing OpenMS' section of 'Building OpenMS on Windows'?

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#2474]
The Visual Studio (GUI) approachs seems to slow building down for me.

Would it be useful/simple/sensible to add a short description of the ms_build commandline approach? Possibly mentioning how to parallelize it (for OpenMS, can we simply use 'MSBuild /m' ?)? Are there any pitfalls?

**Comment by jpfeuffer** [comment]
There should be a script by Chris in the tools folder.

**Comment by jpfeuffer** [comment]
But yes, we should add that to the documentation if not present.

**Comment by cbielow** [comment]
no pitfalls AFAIK
script: https://github.com/OpenMS/OpenMS/blob/develop/tools/build.bat
call without arguments to see a usage help text
additions always welcome :)
