### ISSUE TITLE
App issue MacOS Sierra (10.12)

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#2488]
After installing OpenMS via the installer following Problem occurs:
(This issue does not occur if OpenMS is build directly via github)

`OPEN TOPPView.app`
`LSOpenURLsWithRole() failed with error -10810 for the file /Applications/OpenMS-2.1.0/TOPPView.app.`

This happens because the archives get quarantined (flagged with com.apple.quarantine). macOS 10.12 (Sierra) treats quarantined apps differently than older versions of OS X and isolates them from their parent folder, when they are launched [1].

```
File in quarantine: drwxrwxr-x@
File without quarantine: drwxrwxr-x
```

This can be fixed by the following command:
`sudo xattr -r -d com.apple.quarantine /path/to/app/TOPPView.app`

[1] https://www.oxygenxml.com/forum/topic13639.html

**Comment by jpfeuffer** [comment]
I am not sure if this is related, but if I download the nightly DMG from here:
http://ftp.mi.fu-berlin.de/pub/OpenMS/nightly_binaries/

I can not mount it via Finder. If I then mount the DMG via hditutil, I can not open e.g. TOPPAS.app from Finder but have to this again from the command line.

**Comment by jpfeuffer** [comment]
I guess my comment was not really related but just a hickup of my Finder.
But the quarantine problem is a real one and quite serious. I am not sure if every user trusts us enough to go to the command line and remove all the quarantine flags from our apps.

**Comment by jpfeuffer** [comment]
I guess we have to go through the full process of code signing our app.
Of course this could break automation because it seems heavily XCode dependent. I am still so disappointed that you can't even install XCode from the command line only.

**Comment by jpfeuffer** [comment]
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html#//apple_ref/doc/uid/TP40012582-CH12-SW5

**Comment by hroest** [comment]
we recently installed the 2.1 OpenMS on an OSX 10.12 and ran into the same issues. Interestingly what worked was to fire up the TOPP shell and launch TOPPView from there. Also the command above fixed the issue here.

**Comment by hroest** [comment]
so how does this work, do we pay for a key to sign?

**Comment by jpfeuffer** [comment]
Signing with an Apple Developer ID seems to be enough. It is free with an Apple ID and XCode.

**Comment by jpfeuffer** [comment]
Does not work.. I guess we really need to pay for an official Developer ID.
Problem seems to be the Gatekeeper Path Randomization:
Workarounds (after drag'n'drop of the OpenMS folder from the dmg to the Applications folder):
- Move TOPPAS.app and TOPPView.app outside and back into the OpenMS folder
- Run `xattr -d com.apple.quarantine TOPPAS.app` and `xattr -d com.apple.quarantine TOPPView.app`

**Comment by oliveralka** [comment]
@jpfeuffer 
May have a look here:

https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

Topic: Signing an Installer Package
Not sure if we have the right certificate 
We can have a short look on it next week, when you are in Tübingen.

**Comment by jpfeuffer** [comment]
Yes I came across the guide. I think you are right. Currently I am wondering though, why the apps do not open, even if you accept the security risk message. It should remove the quarantine flag.
Let's investigate next week!
Can you confirm that moving the apps to Desktop and back solves the problem, too? People might be more comfortable with that.

**Comment by jpfeuffer** [comment]
Found the problem. Due to Gatekeepers path randomization, the apps are executed outside of the OpenMS folder in a secure read-only mount and do not find the OpenMS share anymore.
So another solution arose:
- `export OPENMS_DATA_PATH=/Applications/OpenMS-2.3.0/share/OpenMS` before executing

**Comment by jpfeuffer** [comment]
Anyone has a good idea to automate this?

**Comment by jpfeuffer** [comment]
We have an Apple Developer Account now. Signing with this solves the issue on my Mac.
@oliveralka or others, can you confirm with the release candidate?
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/RC/2.3.0/

**Comment by jpfeuffer** [comment]
A colleague confirmed that it works now.
