### ISSUE TITLE
X!Tandem reporting of non-tryptic peptides not reported/considered

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#2497]
Running X!Tandem (Vengeane 2015.12.15.2) in KNIME using `Trypsin` as enzyme yields peptides such as
`AKIDELINND`, which is clearly not tryptic on either C or N Terminus.
The N-Terminus I can understand somewhat, but why is 'D' (aspartate) considered a valid cutting site?
The protein is here:
```
>sp|Q12051|GGPPS_YEAST .... GN=BTS1 PE=1 SV=1
ME*AKIDELINND*PVWSSQNE....
```

I've searched for an explanation, and found `[X]|[D]` in the Tandem docs (http://www.thegpm.org/TANDEM/api/pcs.html) as possible cutting rule (aspn), but thats the N-terminal, not C-terminal and even checking the default.xml seems to specifiy Trypsin only.

So why does XTandem report these peptides? This has implications for PeptideIndexing, but if we dont understand the reasons, its hard to model why this should be allowed.

**Comment by julianu** [comment]
I can confirm this behaviour of the recent X!Tandem releases (also see #2505) and would be interested in the reasoning behind it as well.

**Comment by jpfeuffer** [comment]
First thing again: You say KNIME. Is it reproducible outside of KNIME? Plugin version: Stable or trunk?

Another thing is, that during refinement it checks for point mutations (if activated).

We really need to output the actual used parameters of XTandem if possible (see e.g. the output, parameters option). We could do this in debug mode only or add another parameter to the adapter.
I still haven't seen any real proof (e.g. in the source code) of the rumors that XTandem by default considers weird modifications etc. Actually I think it is all about the correct settings.
Maybe @hendrikweisser can comment on this, since he recently modified the adapter

We need to think about this for the upcoming release.

**Comment by jpfeuffer** [comment]
Maybe in KNIME we still read the default_configuration file?
It says there:
```<note type="input" label="refine, unanticipated cleavage">yes</note>```

**Comment by jpfeuffer** [comment]
That might be it. See the referenced issue.

**Comment by julianu** [comment]
I used the stable KNIME releases.
The "refine, unanticipated cleavage" is, at least in my case, in the unused parameters section. Nevertheless, will make a test run with X!Tandem alone and come back here.

**Comment by julianu** [comment]
Ah, reading the manual helps:
http://www.thegpm.org/tandem/release.html

Cyclone  (2011.12.01) release:
`Additional testing for adventitious cleavage at Asp-Pro residues. These tests are made for all enzyme cleavage types, except [X]|[X] (cleavage at all residues). Testing Asp-Pro cleavage does not affect the "missed cleavage" count in an analysis.`

At least for my cases, the weird cleavages were Asp-Pro cleavages. So I just never stumbled upon them before...

**Comment by jpfeuffer** [comment]
Ah great. That also explains one of @cbielow's cleavages. What do you mean by unused parameters section? Did you put it manually there?

**Comment by cbielow** [comment]
nice. Thanks for the heads up.

Any ideas on our policy of what to do with these Asp/Pro peptides?! Discard automatically or accept automatically? or leave as it is (not favourable, since user will be even more confused).

**Comment by julianu** [comment]
I would vote for leaving these peptides in the results. It is a feature and influences the scoring of X!Tandem. Only, it should be documented better and probably there is a (hidden) why to turn the testing off.

@jpfeuffer: With the unused parameters section I just meant the respective section in the output. So even though the "refine, unanticipated cleavage" might be yes, it should not have been used during the actual search. Also, refinement was turned off.

Anyways, regarding the N-terminal cleavage:
I once (some years ago) had an e-mail answer, why these are plausible and also default in X!Tandem. But I don't find them any more and forget the exact reasoning. I am just writing them another mail and ask again. Will post the answer here.

**Comment by julianu** [comment]
All right, here the summarized answer from Ron Beavis:

X!Tandem does not only check the first aminoacid, but does it like this:
>1. test the peptide with and without N-terminal acetylation;
>2. remove the N-terminal residue;
>3. test the new peptide with and without N-terminal acetylation;
>4. remove the N-terminal residue; and 
>5. test the new peptide with and without N-terminal acetylation.
>
>From information I had in GPMDB at the time, it seemed that some protein N-terminal sequences had a tendency to lose both the M1 and X2 residues, especially when X2 was a bit bulkier, e.g., L or V. The loss of the X2 residue usually wasn't complete: the protein would end up with a slightly ragged N-terminus.

**Comment by jpfeuffer** [comment]
Ah okay. That explains the first cleavage then. If this is not documented at XTandem, we should do it clearly in our Adapter. There are also some comments from Ron Beavis in our Adapter code. We should compile them and write something to the Adapter docu.
And we probably need to discuss how we recommend to handle it. It has of course implications for PeptideIndexing.

**Comment by jpfeuffer** [comment]
Oh btw.. now that I look through old issues. This was discussed twice already. #580 #590 
Maybe we should add this somewhere more prominent in the adapter docu and/or indeed use the SearchParameters in PeptideIndexer to consider the undocumented special cases of XTandem.

**Comment by jpfeuffer** [comment]
I actually made this a blocker now. Three strikes and it is out.

**Comment by cbielow** [comment]
Since users currently have a hard time getting the correct parameters of PeptideIndexer for XTandem idXML, i'd suggest we simply 

1) allow the extended N-terminal protein cleavage of XTandem within EnzymaticDigestion::isValidProduct(), when methionine_cleavage is true (while renaming the parameter to allow_nterminal_protein_cleavage).
-- this should not lead to any false positives, even for other search engines

2) allow the 'adventitious cleavage at Asp-Pro residues.' as well (via another flag in `EnzymaticDigestion::isValidProduct(, bool allow_asp_pro_cleavage)`). By default PeptideIndexer allows this for all search engines. I'm even tempted to hard-code this, since I don't see how this could generate false-positives.

Both these measures should allow PeptideIndexer to match all peptides (thus avoiding the usual error message), while at the same time stopping users from using 'specificity:none' (which solves the problem as well, but potentially introduces a lot of false positives).

**Comment by timosachsenberg** [comment]
this is still a blocker so how should we proceed here?

**Comment by jpfeuffer** [comment]
@cbielow Did you decide on any of the methods in the new PeptideIndexer?
In case you did, we could think about including it in the release.
Otherwise we can either postpone the issue (I mean it was there for a long time) or create a hotfix.

**Comment by cbielow** [comment]
is there a volunteer for the EnzymaticDigestion:: side of things (incl. tests)?
If so, I can make the changes to PI.

**Comment by jpfeuffer** [comment]
I'm working on it.

**Comment by jpfeuffer** [comment]
Ok since there are some more discussions about how to proceed and it makes sense to include this with the new PeptideIndexer we decided not to include this in the release.

**Comment by timosachsenberg** [comment]
is this done?

**Comment by jpfeuffer** [comment]
Changes to EnzymeDigestion yes. But I don't think it is used in PI yet.

**Comment by timosachsenberg** [comment]
any update here?

**Comment by jpfeuffer** [comment]
Should be done:
by default the indexer allows Protein N-Term cleavage and with XTandem also spurious Asp/Pro cleavages.
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h#L995
