### ISSUE TITLE
some ConsensusID algorithms discard ID information [250]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#250]
Submitted by cbielow on 2011-01-17 09:52:16

"ConsensusID-Tool - wenn ich als Algorithmen Average oder Ranked verwende - die Ladungen und die Schnittstellen, also nach und vor welcher AS geschnitten wurde, verloren. "

Bug reported by Marcel Kwiatkowski.
(mkwiatkowski _at_ hotmail _dot_ de)

**Comment by timosachsenberg** [comment]
@hendrikweisser do you know if this is still relevant?

**Comment by hendrikweisser** [comment]
@timosachsenberg:
Neighboring amino acid information should be lost, because the protein-level information is lost (but that's deliberate and documented).
Charge information should be correctly preserved now (as of #1328).

I think this can be closed.
