### ISSUE TITLE
XTandemAdapter in KNIME: Retrieving the modification failed

### ISSUE THREAD

**Issue by julianu** [OpenMS/OpenMS#2505]
I stumbled upon a problem with the XTandemAdapter (in KNIME) with OpenMS version 2.1.0.201703301405:

The search fails with the following error:
<pre>
Error: Unexpected internal error (The value 'Carbamidomethyl (C)' was used but is not valid! Retrieving the modification failed. It is not available for the residue 'L' and term specificity 0.)
</pre>

I ran the identification with a higher log level, using trying to run the X!Tandem XML file through the IDFileConverter, but with the same result:
<pre>
ERROR IDFileConverter      3:127      Failing process stdout: [Debug level (after ini file): 10, Value of string option 'no_progress': 0, Value of string option 'in': /filepath/_tandem_output_file.2017_04_07_17_19_47.t.xml, Checking input file '/filepath/_tandem_output_file.2017_04_07_17_19_47.t.xml', Value of string option 'mz_file': , Progress of 'Loading...':, <Checking input file '/filepath/_tandem_output_file.2017_04_07_17_19_47.t.xml'> occurred 2 times, Error: Unexpected internal error (The value 'Carbamidomethyl (C)' was used but is not valid! Retrieving the modification failed. It is not available for the residue 'L' and term specificity 0.), Error occurred in line 117 of file /home/jenkins/workspace/openms_all/40c74027/source/src/openms/source/CHEMISTRY/ModificationsDB.cpp (in function: const OpenMS::ResidueModification& OpenMS::ModificationsDB::getModification(const OpenMS::String&, const OpenMS::String&, OpenMS::ResidueModification::TermSpecificity) const) !]
ERROR IDFileConverter      3:127      Failing process stderr: [Non-fatal error while loading '/filepath/_tandem_output_file.2017_04_07_17_19_47.t.xml': More than one modification found which fits residue 'M' with mass '15.99492': Oxidation (M),oxidation to L-methionine (R)-sulfoxide (M),oxidation to L-methionine (S)-sulfoxide (M),oxidation to L-methionine sulfoxide (M). Using first hit: 'Oxidation (M)'., <Non-fatal error while loading '/filepath/_tandem_output_file.2017_04_07_17_19_47.t.xml': More than one modification found which fits residue 'M' with mass '15.99492': Oxidation (M),oxidation to L-methionine (R)-sulfoxide (M),oxidation to L-methionine (S)-sulfoxide (M),oxidation to L-methionine sulfoxide (M). Using first hit: 'Oxidation (M)'.> occurred 1881 times]
ERROR IDFileConverter      3:127      Execute failed: Failed to execute node IDFileConverter
</pre>

I had Carbamidomethyl (C) as fixed and Methylation (M) as variable mod, the measurements are from an LTQ Velos and run perfectly using Mascot alone. Attached is the X!Tandem XML file. Actually, this file also confirms the problem shown in #2497.

Cheers,
Julian

[tandem_output_file.zip](https://github.com/OpenMS/OpenMS/files/906095/tandem_output_file.zip)

**Comment by jpfeuffer** [comment]
Are both of these problems specific to the usage in KNIME?
@cbielow

**Comment by jpfeuffer** [comment]
```<domain id="877.1.1" start="3" end="14" expect="2.0e+00" mh="1403.742" delta="0.831" hyperscore="25.4" nextscore="23.8" y_score="12.7" y_ions="6" b_score="5.2" b_ions="2" pre="[ME" post="RWYA" seq="LAKSFEPAEIEK" missed_cleavages="1">
<aa type="L" at="3" modified="42.01057" />
</domain>```
All I can say is that all the occurences of the modified L are N-term acetylated residues.
There seems to be a TODO after @hendrikweisser s changes to the Adapter.

@julianu Which plugin? Stable or trunk?

**Comment by jpfeuffer** [comment]
Can you try adding N-term Acetylation to the list of modifications in your configuration?

**Comment by jpfeuffer** [comment]
Maybe in KNIME we still read the default_input file?
It says there:
```<note type="input" label="refine, potential N-terminus modifications">+42.010565@[</note>```

**Comment by julianu** [comment]
Both problems occurred in KNIME, whether they are specific, I cannot tell. I used the stable versions this time.
The refinement was not turned on, and in the output file the line you highlighted was under the unused terms.

I could try turning on N-term acetylation, but actually I expect it to be considered by Tandem as default, as "protein, quick acetyl" is on by default. Likewise the "protein, quick pyrolidone".
I think it might be better to make the adapter aware of these modifications again, if it somehow lost this in a recent update.

**Comment by hendrikweisser** [comment]
> I used the stable versions this time.

Have you tried it with a current nightly version? I think your problem is the same that I had in #2405, but that should be fixed in the meantime.

When you use the new version of the XTandemAdapter, can you set "default_config_file" to the empty string, so we can exclude that errant settings from this file are causing problems?

> Can you try adding N-term Acetylation to the list of modifications in your configuration?

With a current OpenMS version, that definitely shouldn't be necessary.

**Comment by timosachsenberg** [comment]
can someone confirm this is fixed with the current nightly versions?
