### ISSUE TITLE
Convenience functions for PeptideIdentification and ProteinIdentification

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#2509]
as discussed in #2495, it would be much better to have a defined interface for common operations on `vector<PeptideIdentification>` or `vector<ProteinIdentification>`.
All occurences could (gradually) be replaced by the new classes (one for `vector<PeptideIdentification>`, one for `vector<ProteinIdentification>`).
We'd probably need to forward STL common functions like push_back(), begin(), end() etc.

Advantages:
  - avoid code repetitive bloat (see below)
  - shorter class names, less typing
  - better docu of capabilities (esp. for newbies)

ideas for member functions:
1. ::assignRanks() --> `for (vector<PeptideIdentification>::iterator it = pep_ids.begin(); it != pep_ids.end(); ++it)  it->assignRanks();`

Please list more ideas here.

**Comment by timosachsenberg** [comment]
Would it make sense to go one step further and have an
_Identifications_ object that is a composition of a _PeptideIdentification_**s** and _ProteinIdentification_**s** object?

**Comment by hroest** [comment]
another thing to think about are the Python bindings, currently it is quite straight forward to pass around vectors of `object`, we should make sure that PyOpenMS still has full access to the data structure. E.g. the object may still want to return a `vector<ProteinIdentification>` and a `vector<PeptideIdentification>` just for access through PyOpenMS

**Comment by timosachsenberg** [comment]
Thanks for the input:
Ok, I get started with something random we can build upon;) 

without extra classes:
```
class Identifications
{
  public:
    const vector<ProteinIdentification> & getProteinIdentifications() const;
    void setProteinIdentifications(const vector<ProteinIdentification> & pis);
    void setProteinIdentifications(const vector<ProteinIdentification> && pis);  // efficient move

    const vector<PeptideIdentification> & getPeptideIdentifications() const;
    void setPeptideIdentifications(const vector<PeptideIdentification> & pis);
    void setPeptideIdentifications(const vector<PeptideIdentification> && pis);  // efficient move   
     
    // TODO: add helper
  private:
     vector<ProteinIdentification>prot_ids;
     vector<PeptideIdentification>pep_ids;
}
```

and with extra classes (my preferred solution):

```
class Identifications
{
  public:
    const ProteinIdentifications & getProteinIdentifications() const;
    void setProteinIdentifications(ProteinIdentifications & pis);
    void setProteinIdentifications(ProteinIdentifications && pis);  // efficient move

    const PeptideIdentifications & getPeptideIdentifications() const;
    void setPeptideIdentifications(const PeptideIdentification> & pis);
    void setPeptideIdentifications(const PeptideIdentification> && pis);  // efficient move   
     
    // TODO: add helper
  private:
     ProteinIdentifications prot_ids;
     PeptideIdentifications pep_ids;
}

// variant with simple set and get (no forwarding required)
class ProteinIdentifications
{
  public:
    const vector<ProteinIdentification> & get() const;
    void set(const vector<ProteinIdentification> & pis);
    void set(const vector<ProteinIdentification> && pis);  // efficient move
//TODO add helper
  private:
    vector<ProteinIdentification>prot_ids;
}

// variant with forwarding (bad for pyOpenMS)
class ProteinIdentifications
{
  public:
    typedef std::vector<ProteinIdentification>::iterator iterator;
    typedef std::vector<ProteinIdentification>::const_iterator const_iterator ;

    iterator begin() { return m_container.begin(); }
    iterator end() { return m_container.end(); }

    const_iterator cbegin() const { return prot_ids.begin(); }
    const_iterator cend() const { return prot_ids.end(); }

    size_t size() const { return prot_ids.size(); }

//TODO add helper
  private:
    vector<ProteinIdentification>prot_ids;
}

// or a mixture
class ProteinIdentifications
{
  public:
    typedef std::vector<ProteinIdentification>::iterator iterator;
    typedef std::vector<ProteinIdentification>::const_iterator const_iterator ;

    const vector<ProteinIdentification> & get() const;
    void set(const vector<ProteinIdentification> & pis);
    void set(const vector<ProteinIdentification> && pis);  // efficient move

    iterator begin() { return m_container.begin(); }
    iterator end() { return m_container.end(); }

    const_iterator cbegin() const { return prot_ids.begin(); }
    const_iterator cend() const { return prot_ids.end(); }

    size_t size() const { return prot_ids.size(); }

//TODO add helper
  private:
    vector<ProteinIdentification>prot_ids;
}

```

**Comment by hendrikweisser** [comment]
Just to get the terminology clear for everyone, in the current design:
- `ProteinIdentification` corresponds to one protein identification *run* (e.g. database search) and can contain multiple `ProteinHit`s (plus meta data)
- `ProteinHit` corresponds to an identified protein
- `PeptideIdentification` stores peptide identification results from one MS2 spectrum and one search run; can contain multiple `PeptideHit`s
- `PeptideHit` corresponds to one peptide-spectrum match

Some problems with this design that came up in previous discussions:
- allowing multiple protein identification runs in one file (or `Identifications` object) causes ambiguities - better to only have one set of identified proteins per analysis
- peptides are stored redundantly in the `PeptideHit`s (compare to the structure in mzIdentML, that decouples identified peptides from the originating spectra)
- no support for multiple peptides identified from one (mixed) spectrum, nor for one peptide identified based on evidence from multiple spectra

If we're redesigning the data structures, we should think about addressing these issues (especially allowing only one `ProteinIdentification` instance per `Identifications` object).

**Comment by timosachsenberg** [comment]
You are right about these problems but I am a bit reluctant that we will solve all these problems in one go. I would prefer to address this gradually in several steps. Given that we discussed this a few times already and basically nobody is willing to take on such a  big task I think breaking it down in manageable refactorings is probably better. Except if you volunteer ;)

**Comment by hendrikweisser** [comment]
@timosachsenberg: I don't disagree. My approach would be to design an `Identifications` class that breaks with the old structures, but still provides the "old" interfaces (i.e. getter/setter for `vector<PeptideIdentification>` and `vector<ProteinIdentification>`) for compatibility.

**Comment by timosachsenberg** [comment]
Can you add them here when you fleshed out an initial design?

**Comment by mwalzer** [comment]
@hendrikweisser I really like the idea. It would play well with @cbielow idea of gradually phasing out the old stuff with misleading nomenclature

**Comment by hendrikweisser** [comment]
> Can you add them here when you fleshed out an initial design?

Oh no, what have I done? ;-)
I'll do it over the Easter weekend.

**Comment by hroest** [comment]
I just started working on some work using identifications. I found that the documentation is a bit lacking, e.g. there are some weird things that one needs to do; such as setting the `spectrum_reference` meta value in peptide id. Also it is somewhat unintuitive that each entry in the `vector<ProteinIdentification>` vector leads to the creation of a new identification run - I wonder whether it would make sense to have a more clear structure and introduce an actual `IdentificationRun` object that each has protein and peptide ids.

I think some of these concerns are addressed by @hendrikweisser 

Also another thing to think about is DIA / SWATH-MS data where a protein id/quant is not associated with a specific spectrum any more but its basically a N:M mapping where each peptide is identified over multiple spectra and each spectrum can contain multiple identified peptides. Maybe something to think about in the future!

**Comment by timosachsenberg** [comment]
I think it would make a lot of sense to do so. Maybe there is a way we can share the workload.

**Comment by hendrikweisser** [comment]
Okay, I've made a design attempt and uploaded it to a Gist:
https://gist.github.com/hendrikweisser/43ba787125beca02dea2aa05378cfdfc

Importantly, in this structure every piece of information is only stored in one place, ensuring consistency. There is one set of identified proteins and one set of identified peptides for every `Identifications` object.

The design looks a bit complicated, and it is, but that's because some of the use cases get complicated. E.g. if you do a search run with Mascot and one with X! Tandem, calculate PEPs for both, and combine them with ConsensusID, you end up with PSMs that do not have all scores common - but that shouldn't be a problem because they all have a PEP. Cases like that should be representable.

The overall vision would be that you have some classes that fill/manipulate the whole `Identifications` class - e.g. search engine adapters, IDFileConverter, IDFilter, ConsensusID. Other classes would just include `const Identifications` objects and reference data in them; e.g. feature maps would include (potentially multiple) `Identifications` objects and reference PSMs in them (via their IDs) that are assigned to features.

**Comment by hroest** [comment]
Esp for alignment etc we should take care that the new data structures do
not take up more memory than the old ones - or even save some memory if
possible.

**Comment by hendrikweisser** [comment]
This issue should be addressed in the context of moving to the new `IdentificationData` structure.
