### ISSUE TITLE
TOPPAS - crash on long filenames on MacOS

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#2513]
TOPPAS checks the length of paths to avoid file system limits (usually >255 chars in total).

An exception is thrown if the paths are too long (e.g. long input filenames and deep output path structure etc).
On MacOS, this exception is not caught, but rather leads to a SegFault.
which is only leaving this `Qt has caught an exception thrown from an event handler. Throwing exceptions from an event handler is not supported in Qt. You must reimplement QApplication::notify() and catch all exceptions there.` on the command line.
`notify()` is already re-implemented in TOPPAS and everything works as expected on non-MacOSX.
MacOSX has a Qt Bug: https://bugreports.qt.io/browse/QTBUG-15197 -- which is only fixed in Qt 5.5

This issue is just to inform everyone of the bug. It will remain open until we switched to Qt 5, where homebrew will hopefully offer Qt > 5.5 to make the problem disappear.

@jpfeuffer @lars20070 @oliveralka

**Comment by whench18** [comment]
hello, to avoid problems concerning path too long issues, I suggest the use of the long path tool. this is used by many people and was proven good.

**Comment by lars20070** [comment]
+1

Then let's wait for the Qt5 upgrade. Homebrew offers [Qt >5.5](http://stackoverflow.com/questions/40149391/how-to-install-qt-5-6-1-1-via-homebrew) under `macOS`.

**Comment by jpfeuffer** [comment]
We require Qt 5.6 now. Closing.
