### ISSUE TITLE
Cannot use FileObject in pyopenms

### ISSUE THREAD

**Issue by OnlyBelter** [OpenMS/OpenMS#2515]
I installed pyopenms by pip in windows 7(64bit). I only got v2.0.1, not the newest v2.1. My code is very simple:

```
import pyopenms
filter = pyopenms.FileObject(r'E:\openMS\Example_Data\Introduction\datasets\small\velos005614.mzML')

```
But I got `AttributeError: 'module' object has no attribute 'FileObject'`

**Comment by hroest** [comment]
Hi, I think there was some ambiguity in the manual, I think what you want is 

```
from pyopenms import *
file = MzMLFile()
exp = MSExperiment()
filename_in = "input.mzML"
filename_out = "output.mzML"
file.load(filename_in, exp)
# process
file.store(filename_in, exp)
```

see also section 1.7 of the manual

**Comment by timosachsenberg** [comment]
I think this issue is resolved. Feel free to reopen if not.

**Comment by OnlyBelter** [comment]
I got it, `where FileObject can be any of DTA2DFile, DTAFile, mzXML, mzML.`, thanks!
