### ISSUE TITLE
Add new enzymes to PSI MS Ontology

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2519]
This issue is to gather enzymes that should be added to PSI MS Ontology.
http://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1001045

For MSGF+ and Comet we want to include the enzymes in our Enzymes.xml but there is currently no entry for some of them.
Let us collect them here @Leon-Bichmann.

**Comment by Leon-Bichmann** [comment]
OK so Lys-N (N-terminal cleavage after K) would be the first one

**Comment by timosachsenberg** [comment]
cool. I can propose them at the PSI meeting
