### ISSUE TITLE
FalseDiscoveryRate tool - add filter

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2531]
I know this might be a bit controversial but we repeatably observe users that apply the FalseDiscoveryRate tool but struggle with the IDFilter step afterward. 
Here, the user has to set score:pep to match a q-value threshold. This is poorly documented in the tool parameters alone because the score filter can be so generically applied to any type of (main) score.

One simple solution would be to add a filter option (maybe subsection "FDR control" and name them "peptide" and "protein") to FalseDiscoveryRate.

I'm not a fan of duplicating functionality in TOPP tools but in this case, I think this might be a good idea.

**Comment by hroest** [comment]
sounds reasonable to me and filtering is not such a difficult task that there will be lots of duplicated code

:+1:

**Comment by jpfeuffer** [comment]
see #2953
