### ISSUE TITLE
mass of AA "X"

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2532]
currently the "special" amino acid "X" has a mass of zero which leads to problems when used as an internal residue since OpenMS assumes that amino acids get hydrolized and loose the mass of H2O when being incorporated into an Amino Acid sequence. This leads to the following counterintuitive behavior:

```
+    AASequence aa_original = AASequence::fromString("DFPANGER");
+    TEST_REAL_SIMILAR(aa_original.getMonoWeight(), 904.4038997864)
+
+    AASequence aa_withX_original = AASequence::fromString("DFPANGERX");
+    TEST_REAL_SIMILAR(aa_withX_original.getMonoWeight(), 904.4038997864  - 18.0105650638)
+    AASequence aa_withX2_original = AASequence::fromString("DFPANXGER");
+    TEST_REAL_SIMILAR(aa_withX2_original.getMonoWeight(), 904.4038997864  - 18.0105650638)
```

where adding an X to a peptide string reduces its mass by 18. This is probably surprising to many people and not what should happen.

One solution is to change the mass of "X" to have the mass of 18, basically giving it the sum formula "H2O". So when this "AA" gets "hydrolyzed", the water gets removed and it contributes a net 0 to the mass of the peptide such that DFPANGER and DFPANGERX have the same mass. It still does not really make sense to ask for the mass of a peptide with an unknown amino acid but at least the answer is less surprising.

The second solution is to basically throw an exception when trying to get the mass of DFPANGERX (note however that DFPANGERX[180] should work as it is well defined).

I would be in favor of the first solution and just give X a mass of 18. I had a discussion with @jpfeuffer which boiled down to this.

**Comment by timosachsenberg** [comment]
ok so the "mass tags" with X + brackets would not be affected.  only X without brackets. right? so basically X and X[0.0] would both add 0 to the peptide weight. but The residue X has a mono Weight of 18.01...

**Comment by hroest** [comment]
yes, exactly. 

Basically before PEPTIDEX was equal to PEPTIDEX[-18.0] while now it would be equal to PEPTIDEX[0.0]

**Comment by hroest** [comment]
I could potentially add this to PR #2530 if people agree

**Comment by hendrikweisser** [comment]
How about giving "X" by itself an average amino acid mass (taking the distribution of the different amino acids in the proteome into account)?

**Comment by hroest** [comment]
that sounds like a bad idea that would lead to a lot more surprises - also often X represents an unknown AA with modifications and there is no way to tell what the mass of that would be

**Comment by timosachsenberg** [comment]
yes please add  your solution to the PR +1 from me

**Comment by hendrikweisser** [comment]
Do we actually see uses of "X" (without mass information) "in the wild"? If yes, where? If no, I would prefer the "throw an exception" route.

**Comment by timosachsenberg** [comment]
I think it might happen quite frequently that we parse sequences with X from fasta files or third-party results.

**Comment by hendrikweisser** [comment]
> I think it might happen quite frequently that we parse sequences with X from fasta files or third-party results.

FASTA files I agree, but we wouldn't parse those sequences directly and generate AASequence instances from them, right?
And do any search engines actually generate hits with "X" in them? If so, what mass do they use for it?

**Comment by jpfeuffer** [comment]
Also deNovo sequencing approaches use that commonly to represent gaps in the sequence.

**Comment by timosachsenberg** [comment]
I am pretty sure that most search engines just ignore the X.
I think we can just call for a vote:
1. fail with exception
2. print out warning (release)
3. print out warning (debug only)

One thing we might also need to consider is how we handle X in our theoretical spectrum generators. For example, it would be bad if, say 3 times the same peak is generated if two XX follow a normal amino acid.

I would vote for (2) printing a warning in release mode. If we see that this is not that big of a problem in practice we should switch to (1) later.

**Comment by hendrikweisser** [comment]
> I would vote for (2) printing a warning in release mode. If we see that this is not that big of a problem in practice we should switch to (1) later.

I like this suggestion.

**Comment by hroest** [comment]
ok, this sounds great but then I probably wont add it to #2530 any more since it is a larger change.

also when people have X in their fasta file, it is quite unlikely that they will get peptides with the right masses. Same for TSG, I dont think it should even work because how will you get a theoretical spectrum unless you have a mass. I dont think it makes sense for any search engine to write out X without a mass, e.g. `X[123]` makes sense but not `X` by itself.

@timosachsenberg I think it may make sense to have two X in a row if they both have a mass, e.g. `X[123]X[456]` makes sense but not `XX`

**Comment by hroest** [comment]
> I am pretty sure that most search engines just ignore the X.

I think ignoring it, e.g. option 2 or 3 will not break things for the user if the input is slightly unexpected, I think option 1 is bad since you may have a single error in your fasta file and then OpenMS will just break and stop? People may not appreciate that.

**Comment by hendrikweisser** [comment]
> I think option 1 is bad since you may have a single error in your fasta file and then OpenMS will just break and stop?

That wouldn't happen because FASTA file sequences are not parsed into AASequence.

**Comment by mwalzer** [comment]
>>> People may not appreciate that.

Yeah, but people should also not appreciate their fasta files having an error. That can very well lead to further unexpected but (possibly) unobtrusive 'errors'. 
So I would definitively not go for 3. Basically I tend to 1. but see 2. as the less intrusive way.

**Comment by jpfeuffer** [comment]
I agree with @hendrikweisser . X's in fasta database are not so much of a concern. I think you will find them quite frequently and they should not lead to an exception. Since they are usually not parsed into AASequences we should focus on what X's without masses mean in an identification context, where I would vote for at least (2).

**Comment by hroest** [comment]
ok, I implemented suggestion (2) which seems to be what most people prefer in #2545 and we can always switch to throwing an exception - its just one un-comment action away
