### ISSUE TITLE
Can TOPPView show chromatogram plot?

### ISSUE THREAD

**Issue by OnlyBelter** [OpenMS/OpenMS#2535]
TOPPView is really a great tool to visualize LC-MS data. I want to ask if it can show chromatogram plot, like below([from here](http://mzmine.github.io/features.html#3D)), so we can see TIC((Total Ion Chromatogram) ) and EIC(Extracted Ion Chromatogram)?

![chromatogram](https://cloud.githubusercontent.com/assets/16537617/25225940/c169f12a-25f5-11e7-8f35-c5ec4ceb31f7.png)

**Comment by hroest** [comment]
yes, it can but only if you provide it with a mzML file that is chromatograms only. Basically it will either show chromatograms OR spectra but there is no good way to do both (and also does not really make sense). 

In case you simply want to visualize the TIC there is a button on top that does "Projections" and looks like a 2D map with blue (top) and red (right) peaks that you can use. In case you want to visusalize multiple TIC from your files you may need to filter each file, remove all spectra and only keep the TIC (which proteowizard writes out) and then load all these into TOPPView.

**Comment by OnlyBelter** [comment]
@hroest I find it in view 2D, thank you very much!
