### ISSUE TITLE
Nightly tests for TOPPAS example pipelines [254]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#254]
Submitted by cbielow on 2011-01-28 14:07:23

to see if any relevant parameters of TOPP tools etc were changed, and if the examples need attention.
Also not all files required to run the examples are present (eg. 18Protein_SoCe_Tr_detergents_trace_target_decoy.fasta)
---

Commented by johannes_junker on 2013-07-18 00:15:23:
Added TOPPAS pipeline tests in r11580.

**Comment by jpfeuffer** [comment]
I will close this. We have a rudimentary Execute_Pipeline test and will switch to KNIME anyway.
