### ISSUE TITLE
IsobaricAnalyzer results empty when used with MS3 data

### ISSUE THREAD

**Issue by gPirkes** [OpenMS/OpenMS#2540]
Hi, 
I was trying to extract MS3 TMT10-plex quantification data from a mzML file, but the IsobaricAnalyzer doesn’t seem to catch it.
I don’t get an error when running the pipeline (it makes no difference whether I run it from TOPPAS or via ExecutePipeline) but I do get the following warning message: 
`Warning: Empty iTRAQ container. No quantitative information available!`
The output of the IsobaricAnalyzer looks like this: 
```
current dry-run state: 1
current dry-run state: 0
IsobaricAnalyzer started. Processing ...
Warning: Empty iTRAQ container. No quantitative information available!
Selecting scans with activation mode: High-energy collision-induced dissociation
IsobaricAnalyzer took 31.58 s (wall), 30.48 s (CPU), 0.00 s (system), 30.48 s (user).
IsobaricAnalyzer finished!
Output file '...' written.
ExecutePipeline took 32.09 s (wall), 0.05 s (CPU), 0.00 s (system), 0.05 s (user).
```
I then end up with an “empty” .consensusXML file – it just has all the parameters set in the IsobaricAnalyzer but no data.
FileInfo on the input file returns the following information: 
```
Progress of 'loading spectra list':
-- done [took 27.10 s (CPU), 27.68 s (Wall)] -- 
Progress of 'loading chromatogram list':
-- done [took 0.01 s (CPU), 0.00 s (Wall)] -- 

Mem Usage while loading: 886 MB

-- General information --

File name: ./in.mzML
File type: mzML

Peak type (metadata): Peak data
Peak type (estimated): Peak data

Number of spectra: 50178
Number of peaks: 48239009

Ranges:
  retention time: 0.15 .. 7199.85
  mass-to-charge: 111.55 .. 1999.98
  intensity:      0.00 .. 3821166080.00

MS levels: 1, 2, 3
Number of spectra per MS level:
  level 1: 5345
  level 2: 22421
  level 3: 22412

Number of chromatograms: 1
Number of chromatographic peaks: 50178

Number of chromatograms per type: 
  total ion current chromatogram:                         1

FileInfo took 29.90 s (wall), 28.58 s (CPU), 0.00 s (system), 28.58 s (user).
```
For the sake of simplicity I have reduced the workflow: 
![workflow](https://cloud.githubusercontent.com/assets/22030970/25280821/30ef0352-26a3-11e7-9b8c-b91f048a902e.png)

The settings I used for the IsobaricAnalyzer are:
![isobaricanalyzer_config_2](https://cloud.githubusercontent.com/assets/22030970/25280887/67356e42-26a3-11e7-9099-551a68dcebf1.png)

I have tried to replace all occurrences of “ms3” with “ms2”. FileInfo then shows that only MS2 and MS3 spectra are in the file, but the result is the same. 
Converting the .mgf file directly in OpenMS didn’t change the results either. 

Cheers, 
Georg

**Comment by jpfeuffer** [comment]
Hey,

from how I understand the code and documentation, the tools is quite specific to MS1/MS2 labeled quantification.
It goes through the list of spectra from top to bottom, remembers the last MS1 spectrum, assumes it is the precursor and processes all following MS2 spectra with that assumption.

I am not sure if you can preprocess your data in such a way that it works.
Maybe removing MS1 and setting MS2->MS1 and MS3->MS2 might work but that is just random guessing.

Maybe @cbielow has more insights.

Cheers
Julianus

**Comment by hendrikweisser** [comment]
> It goes through the list of spectra from top to bottom, remembers the last MS1 spectrum, assumes it is the precursor and processes all following MS2 spectra with that assumption.

Why is there a connection to the MS1 spectrum? Isn't all the relevant information in the MS2?

**Comment by jpfeuffer** [comment]
It seems to look at the precursor purity. MAybe one can turn it off?
https://github.com/jpfeuffer/OpenMS/blob/e857a2ad01aceb9c73a8ffdfb8adbbae963b2c34/src/openms/source/ANALYSIS/QUANTITATION/IsobaricChannelExtractor.cpp#L453-L453

**Comment by hroest** [comment]
why not just remember which was the last spectrum with a MS-level one higher than the current one, basically keep a list of the last MS1, the last MS2, the last MS3 etc encountered?

PS: replacing MS3 with MS2 will only work if you replace the `value` of the CVParam `1000511` from 3 to 2 which is basically what OpenMS reads when setting the MS-level.

**Comment by hendrikweisser** [comment]
> why not just remember which was the last spectrum with a MS-level one higher than the current one, basically keep a list of the last MS1, the last MS2, the last MS3 etc encountered?

I don't think that's even necessary in this case. If understand correctly (@cbielow?), the precursor purity should always derive from the MS1 spectrum. But calculating it should be optional in any case.
I think it should be sufficient to change on which spectrum level the reporter ions are looked up.

**Comment by gPirkes** [comment]
I now tried: 
- keeping all spectra, converting MS3 to MS2 
- keeping all spectra, converting MS2 to MS1 and MS3 to MS2
- removing MS1, converting MS2 to MS1 and MS3 to MS2
- removing MS2, converting MS3 to MS2
- removing MS1 & MS2, converting MS3 to MS2

In all of the above cases I filtered with a FileFilter and replaced the `ms level` CVParam with a `sed` command.
FileInfo on any of the files results in what I expected (e. g. showing only MS2 spectra in the last case and the number of those match up with the number of MS3 spectra in the original file).
When running the pipeline, I get the same warning
`Warning: Empty iTRAQ container. No quantitative information available!` 
and end up with empty output files.

**Comment by cbielow** [comment]
hey Georg,
could you send a few dozen scans of your mzML file please. I'll have a look.

**Comment by cbielow** [comment]
e.g. FileFilter -in in.mzML -rt 1000:1100 -out chunk.mzML

**Comment by gPirkes** [comment]
Hi, 
here you go: https://drive.google.com/file/d/0B0SZYkAHoYvzSHhfMzFwNDE3SEU/view?usp=sharing
hope this helps!

**Comment by cbielow** [comment]
I have a working solution ready. While at it, I've changed the way of quantification, i.e. only use peak closest to the theoretical mass instead of summing everything up in the given tolerance window (this is prone to wrong parametrization by the user).

General question: is someone against removing ITRAQAnalyzer and TMTAnalyzer? Except for the explicit name they add no value. The IsobaricAnalyzer subsumes both and has more/better functionality. So there is no reason to keep three tools which do similar things. 
I'll open a PR which contains the fix and removes the other tools. Doing it separately is hard (due to shared tests and diverged algorithms).

**Comment by cbielow** [comment]
hey Georg,
the PR is out (see above).
On your test data chunk, the reporter ion m/z's looked very strange. Maybe thats because its only some random spectra from low-intensity regions which to not really contain TMT labels?!

cheers
Chris

**Comment by gPirkes** [comment]
Hi, 
I've been trying to get the PR running, but am currently struggling with a boost dependency while linking - I don’t think I'll be able to finish it up today and am not at work tomorrow, but will keep working on it and let you know as soon as I have results. 
Thanks in advance for addressing this issue!

Cheers, 
Georg

**Comment by cbielow** [comment]
the PR is merged now.
I'm closing this issue (because they tend to stay open and unchecked).
Please report issues with the current implementation in a new ticket.
Thanks! :)

**Comment by gPirkes** [comment]
Thank you for dealing with the problem - I have not yet managed to install and test it as I get errors when trying `make` the executables. Seems like it has something to do with linking the boost library, but I think this thread is the wrong place to discuss that!

cheers 
georg

**Comment by jpfeuffer** [comment]
Regarding this issue, see #2562 and related issues. For now, please make sure you only have one boost installed (preferably the one built with the contrib).
You might be affected by this.
