### ISSUE TITLE
Handling of optional parameters in ini files

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2544]
I am in the process of fixing a bug in KNIME where we do not write e.g. an optional input file to the ini file, when it is not given.
This results in inis like the following:
https://gist.github.com/jpfeuffer/7cee69eb5c269ccf91e0ee6cded5f97b

Unfortunately the tool (IDMapper) crashes because the spectra category is now basically empty.
Whose fault is it and which rules should we enforce from now on?
Potentially there is a difference in adding the parameter with e.g. an empty string and I am not sure if all our tools take an empty string as a "missing" parameter.
I mean on the CLI you wouldn't add the parameter neither.
@timosachsenberg @cbielow

**Comment by jpfeuffer** [comment]
Based on my own opinion that an empty section should not be an error, I prepared a fix to the ParamFile handling (where sections and items are added in strange orders).
BTW: I saw that we are abusing the ParamXMLFileHandler for reading our "databases" (like ResidueDB.xml). Not sure how to feel about that.

**Comment by cbielow** [comment]
TOPPBase should internally generate the full set of params and augment them with whatever the INI is providing. So why does this fail here? And empty is equal to missing... at least in theory.

**Comment by jpfeuffer** [comment]
It fails because it does not generate sections (per se) while reading a paramXML file. It first adds all the ParamEntries (items) and creates sections on the fly based on their prefixes. If a section does not have any entries it will not be added and the code fails in setSectionDescription. So more of a bug right? I already have a fix coming.
