### ISSUE TITLE
Error building pyopenms from branch develop

### ISSUE THREAD

**Issue by dmccloskey** [OpenMS/OpenMS#2546]
[pyopenms_error_2.txt](https://github.com/OpenMS/OpenMS/files/949733/pyopenms_error_2.txt)

**Comment by hroest** [comment]
it seems that this is the problem

```
^
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
error: command 'gcc' failed with exit status 4
```

after some googling it seems that you simply dont have enough memory to compile it. Increase the RAM of your machine or use a swap file/partition and it will likely work. Note that it generally takes up to 6-8 GB of RAM to compile pyOpenMS directly.

**Comment by dmccloskey** [comment]
Ok thanks for spotting that. That is quite odd. The PC I was compiling it
on had 16 GB if RAM.  I will try compiling on a different machine to see if
that fixes the issue.

Douglas

**Comment by dmccloskey** [comment]
That fixed the issue.  I ended up having to build it on a server with 32 GB
of RAM.

Thanks!

Douglas
