### ISSUE TITLE
Build problems on OSX 10.12 

### ISSUE THREAD

**Issue by christineyyeh** [OpenMS/OpenMS#2558]
I just ran into a suite of problems compiling the developer version of OpenMS on OS X 10.12. 

**1. The first problem was finding the right version of qt.** 
I found out that OS X 10.12 has retired qt4 due to security issues and you cannot access it with:

`$ brew install qt`

You can now only access qt4 in cartr/qt4/qt@4 through homebrew with the --force flag. Since I then had both versions of qt, I also had to make sure that the /usr/local/bin/qt linked to this version of qt before calling cmake. 

After fixing the version issue, I found that even with the force download, the cmake could not find a field to go in QT_QTWEBKIT_INCLUDE_DIR=PATH. This was because the webkit has been retired and no longer comes with qt4 either. So then, I ran: 

`$ brew install qt-webkit@2.3`

which retrieved the webkit files from the Homebrew boneyard. It came with some warning messages about compromised security and video not working. The cmake command still could not find it initially - so then I specified the QT_QTWEBKIT_INCLUDE_DIR=PATH flag in the cmake command. 

**2. Problems concerning other dependencies**

It seemed that during the configuration, the cmake found paths to newer versions of: seqan, glpk, eigen3 that I installed with homebrew rather than in the ../contrib_build

I uninistalled these one by one. Not really sure why cmake is looking for these dependencies in /usr/local/include

**3. Linker problem with Boost** 

I then got some linker error with boost when linking the OpenMS library itself: 

```
Undefined symbols for architecture x86_64:
  "boost::re_detail_106400::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)", referenced from:
      bool boost::regex_search<char const*, std::__1::allocator<boost::sub_match<char const*> >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(char const*, char const*, boost::match_results<char const*, std::__1::allocator<boost::sub_match<char const*> > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags, char const*) in IndexedMzMLDecoder.cpp.o
      bool boost::regex_search<char const*, std::__1::allocator<boost::sub_match<char const*> >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(char const*, char const*, boost::match_results<char const*, std::__1::allocator<boost::sub_match<char const*> > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags, char const*) in ConsensusMapNormalizerAlgorithmMedian.cpp.o
  "boost::re_detail_106400::get_mem_block()", referenced from:
      boost::re_detail_106400::perl_matcher<std::__1::__wrap_iter<char const*>, std::__1::allocator<boost::sub_match<std::__1::__wrap_iter<char const*> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find_imp() in SpectrumLookup.cpp.o
      boost::re_detail_106400::perl_matcher<std::__1::__wrap_iter<char const*>, std::__1::allocator<boost::sub_match<std::__1::__wrap_iter<char const*> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_all_states() in SpectrumLookup.cpp.o
      boost::re_detail_106400::perl_matcher<std::__1::__wrap_iter<char const*>, std::__1::allocator<boost::sub_match<std::__1::__wrap_iter<char const*> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_startmark() in SpectrumLookup.cpp.o
      boost::re_detail_106400::perl_matcher<std::__1::__wrap_iter<char const*>, std::__1::allocator<boost::sub_match<std::__1::__wrap_iter<char const*> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_alt() in SpectrumLookup.cpp.o
      boost::re_detail_106400::perl_matcher<std::__1::__wrap_iter<char const*>, std::__1::allocator<boost::sub_match<std::__1::__wrap_iter<char const*> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_rep() in SpectrumLookup.cpp.o
      boost::re_detail_106400::perl_matcher<std::__1::__wrap_iter<char const*>, std::__1::allocator<boost::sub_match<std::__1::__wrap_iter<char const*> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_char_repeat() in SpectrumLookup.cpp.o
      boost::re_detail_106400::perl_matcher<std::__1::__wrap_iter<char const*>, std::__1::allocator<boost::sub_match<std::__1::__wrap_iter<char const*> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_set_repeat() in SpectrumLookup.cpp.o
```
We went in the boost folder within the /contrib_build and removed the original libboost_regex-mt.a file and instead symlinked it to the copy installed through brew on my local system: 

`libboost_regex-mt.a -> /usr/local/lib/libboost_regex-mt.a`

This seemed to work, and we ran tests on the programs we needed! These errors seem related to the ones discussed in #1829.

**Comment by christineyyeh** [comment]
The issue seems to be that it first looks in `/usr/local/include` for libraries and then looks for libraries in the contrib folder - so if boost is also installed there its a big issue (see the `-isystem /usr/local/include` below which comes first). 

```
Scanning dependencies of target OpenMS
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/openms/CMakeFiles/OpenMS.dir/build.make src/openms/CMakeFiles/OpenMS.dir/build
[  4%] Building CXX object src/openms/CMakeFiles/OpenMS.dir/source/FORMAT/MzIdentMLFile.cpp.o
cd /Users/christineyeh/Projects/openms_development/openms_build3/src/openms && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DBOOST_ALL_NO_LIB -DOpenMS_EXPORTS -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -isystem /usr/local/include -iframework /usr/local/lib -isystem /usr/local/include/QtNetwork -isystem /usr/local/lib/QtCore.framework/Headers -I/Users/christineyeh/OpenMS/src/openms/include -I/Users/christineyeh/Projects/openms_development/openms_build3/src/openms/include -isystem /usr/local/include/QtDesigner -isystem /usr/local/include/QtDeclarative -isystem /usr/local/include/QtScriptTools -isystem /usr/local/include/QtDBus -isystem /usr/local/include/QtXml -isystem /usr/local/include/QtSql -isystem /usr/local/include/QtOpenGL -isystem /usr/local/include/QtMultimedia -isystem /usr/local/include/QtXmlPatterns -isystem /usr/local/include/QtWebKit -isystem /usr/local/include/QtHelp -isystem /usr/local/include/QtUiTools -isystem /usr/local/include/QtTest -isystem /usr/local/include/QtScript -isystem /usr/local/include/QtSvg -isystem /usr/local/include/Qt3Support -isystem /usr/local/include/QtGui -isystem /usr/local/Cellar/qt@4/4.8.7_1/mkspecs/default -isystem /Users/christineyeh/Projects/openms_development/contrib_build/include -isystem /Users/christineyeh/Projects/openms_development/contrib_build/include/eigen3 -isystem /Users/christineyeh/Projects/openms_development/contrib_build/include/WildMagic -isystem /Users/christineyeh/OpenMS/src/openswathalgo/include -isystem /Users/christineyeh/Projects/openms_development/openms_build3/src/openswathalgo/include -isystem /Users/christineyeh/OpenMS/src/openms/thirdparty/eol-bspline  -O3 -DNDEBUG -fPIC   -Weverything -Wno-sign-conversion -Wno-long-long -Wno-padded -Wno-global-constructors -Wno-exit-time-destructors -Wno-weak-vtables -Wno-documentation-unknown-command -Wno-undef -Wno-documentation -Wno-source-uses-openmp -Wno-old-style-cast -Wno-conversion -Wno-float-equal -Wno-switch-enum -Wno-missing-prototypes -Wno-missing-variable-declarations -fPIC -o CMakeFiles/OpenMS.dir/source/FORMAT/MzIdentMLFile.cpp.o -c /Users/christineyeh/OpenMS/src/openms/source/FORMAT/MzIdentMLFile.cpp
```


this was using the following cmake command 

```
cmake -DCMAKE_PREFIX_PATH='/Users/christineyeh/Projects/openms_development/contrib_build/' -DQT_QMAKE_EXECUTABLE=/usr/local/bin/qmake -DBOOST_USE_STATIC=OFF ~/OpenMS/
```

which probably should not include /usr/local in the search paths

**Comment by jpfeuffer** [comment]
Hey Christine,

thanks for your extensive report. We are aware of some of the issues but unfortunately do not have a **clean** macOS 10.12.2 to reproduce these errors and give instructions, yet.
**QT**: We are in the process of upgrading to QT5 without WebKit so we hope to be able to sort this out soon. Similar issues arise on Linux where they dropped support, too.
**Linker order**: I agree with you that it could be done better. Luckily you seem to have found the workaround of not mixing system libraries and contrib where possible by yourself. #2562
**Boost**: We need to investigate this. http://stackoverflow.com/questions/7752609/cmake-ordering-of-include-directories-how-to-mix-system-and-user-based-includ

**Comment by oliveralka** [comment]
I ran in this issue as well, an easy solution is to uninstall boost in brew if possible and use the contrib for the building process. This can be seen as an alternative work around but not as final solution.

**Comment by jpfeuffer** [comment]
Can someone try the following brew option:
`option "with-icu4c", "Build regexp engine with icu support"`

**Comment by jpfeuffer** [comment]
And you probably should make sure that boost is not built with c++11 std.

**Comment by hroest** [comment]
Christine is a student working with me here in Stanford and installing OpenMS unfortunately required quite some efforts. I dont think uninstalling boost is a good solution as you may need it for other software that you also want to compile. We should be able to figure out a way to have boost installed and still use the correct headers.

On Linux that works pretty well, I have reorganized the first comment to show the issue in the `c++` call using `VERBOSE=1` which I also ran on Linux and I get

```
[  0%] Building CXX object src/openms/CMakeFiles/OpenMS.dir/source/FORMAT/MzIdentMLFile.cpp.o cd
/home/hr/openmsall/builds/openms_experimental/src/openms && 
/usr/bin/c++ -DBOOST_ALL_NO_LIB -DOpenMS_EXPORTS -DQT_CORE_LIB -DQT_NETWORK_LIB
-DQT_NO_DEBUG 
-isystem /usr/include/qt4 
-isystem /usr/include/qt4/QtNetwork
-isystem /usr/include/qt4/QtCore
-I/home/hr/openmsall/source/OpenMS_experimental/src/openms/include
-I/home/hr/openmsall/builds/openms_experimental/src/openms/include 
-isystem /usr/include/qt4/QtDesigner 
-isystem /usr/include/qt4/QtDeclarative 
-isystem /usr/include/qt4/QtScriptTools 
-isystem /usr/include/qt4/QtDBus 
-isystem /usr/include/qt4/QtXml 
-isystem /usr/include/qt4/QtSql 
-isystem /usr/include/qt4/QtOpenGL 
-isystem /usr/include/qt4/QtXmlPatterns 
-isystem /usr/include/qt4/QtWebKit -isystem /usr/include/qt4/QtHelp 
-isystem /usr/include/qt4/QtUiTools -isystem /usr/include/qt4/QtTest 
-isystem /usr/include/qt4/QtScript -isystem /usr/include/qt4/QtSvg 
-isystem /usr/include/qt4/Qt3Support -isystem /usr/include/qt4/QtGui 
-isystem /usr/share/qt4/mkspecs/default 
-isystem /home/hr/openmsall/builds/contrib-all-old/include 
-isystem /home/hr/openmsall/builds/contrib-all-old/include/eigen3 
-isystem /home/hr/openmsall/builds/contrib-all-old/include/WildMagic 
-isystem /home/hr/openmsall/source/OpenMS_experimental/src/openswathalgo/include
-isystem /home/hr/openmsall/builds/openms_experimental/src/openswathalgo/include
-isystem /home/hr/openmsall/source/OpenMS_experimental/src/openms/thirdparty/eol-bspline
-fopenmp  -O3 -DNDEBUG -fPIC   -Wall -Wextra -fvisibility=hidden
-Wno-non-virtual-dtor -Wno-unknown-pragmas -Wno-long-long -Wno-unknown-pragmas
-Wno-unused-function -Wno-variadic-macros --pedantic -fPIC -o
CMakeFiles/OpenMS.dir/source/FORMAT/MzIdentMLFile.cpp.o -c
/home/hr/openmsall/source/OpenMS_experimental/src/openms/source/FORMAT/MzIdentMLFile.cpp
```

if you compare the two `c++` calls you notice they are almost the same -- except that the first two lines on Linux is

```
-isystem /usr/include/qt4 
-isystem /usr/include/qt4/QtNetwork
```

while on OSX it is these three lines

```
-isystem /usr/local/include 
-iframework /usr/local/lib 
-isystem /usr/local/include/QtNetwork 
```

and obviously if the first include line is `/usr/local/include` then its not
wonder why glpk.h, boost headers etc are chosen from there first and not from
the contrib paths that are further down. Note that the order really matters, its pretty easy to see furhter

```
$ cpp -isystem /tmp/tmp1 -isystem /tmp/tmp2 -v
[...]
#include "..." search starts here:
#include <...> search starts here:
 /tmp/tmp1
 /tmp/tmp2
 /usr/lib/gcc/x86_64-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```

e.g. it will search in the system folders anyways but after first searching in
user specified folders. So by first including `/usr/local/include` in OSX we
cause the problem. Maybe somebody with a Mac can investigate why this include
occurs only on OSX and not on Linux?

**Comment by jpfeuffer** [comment]
Yes sure, I can investigate. I also think it comes from QT. Maybe I find something on the flight tomorrow.

**Comment by jpfeuffer** [comment]
Might have been solved too with the linked PR. We also updated the docu for QT4 Webkit.
