### ISSUE TITLE
Enforce certain include/linking orders

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2562]
Assume you have boost and eigen installed in the system paths (let's say /usr/local/include).
Also both in the contrib (/Users/user/contrib-build/include).
If they do not provide subdirectories (which some of them do not), it means that whatever library is included first in CMake:
https://github.com/jpfeuffer/OpenMS/blob/2080ba2f015ab28d0b6e31063fc2f181a8edae75/src/openms/CMakeLists.txt#L118-L118
determines both of their fate because it implicitly includes the other at the same time and comes first in the compiler command when creating the objects.

Not sure if we can do much about it. Maybe we should check if any of the includes directly lies in a system path and put it last.

This might help:
http://stackoverflow.com/questions/7752609/cmake-ordering-of-include-directories-how-to-mix-system-and-user-based-includ

**Comment by jpfeuffer** [comment]
Maybe we also need to force our contrib to lay the libraries/includes into subdirectories.

**Comment by cbielow** [comment]
where is the problem here? As far as I understand, `include_directory()` is always preferred over standard system includes. Hence, if we include the contrib like that, our contrib will be preferred (if the libs were build) -- and that sounds like a reasonable thing to do.
Is there a case where this goes wrong?

**Comment by jpfeuffer** [comment]
Ok, I try again. Not sure if there is really a problem but I will try :)
Assume you have boost only in system and boost is first in the EXTERNAL_INCLUDES of the OpenMS library.
But you also have eigen in system. AND in contrib. You want to use eigen from contrib.
The problem is, if boost and eigen are not in subdirectories under /usr/local/include,
then /usr/local/include is included when boost is included and automatically includes the eigen headers with it.
Yes CMake will add /contrib-build/include as another directory, but the compiler will probably choose the headers from the first include, which is from the system.
-> CMake says it found the contrib Eigen but the system Eigen is actually included

**Comment by hroest** [comment]
even worse, from what I have seen is that the compiler will include the *headers* from /usr/local/include but try to link against the files in your contrib. At least this is what happened in #2558 and was no fun

**Comment by hroest** [comment]
I wrote a lengthy analysis over here https://github.com/OpenMS/OpenMS/issues/2558#issuecomment-298067569 it really looks like a CMake issue on OSX only.

I wonder where the extra include come from but likely they are in `QT_INCLUDES` -- can somebody on a OSX print out that variable why configuring? Also maybe we can solve the issue by simply moving the QT_INCLUDES to the end of include list?

**Comment by hroest** [comment]
see http://commandlinefanatic.com/cgi-bin/showarticle.cgi?article=art026 for more information on header include order

**Comment by hroest** [comment]
@jpfeuffer on Linux this setup works pretty well and without issue as long as the contrib search path is first. I have this on my system and no issue at the moment, I can easily have contrib boost and system boost installed at the same time and tell Cmake which one to choose.

**Comment by jpfeuffer** [comment]
So I looked at it. And /usr/local/include is actually added by almost all libraries that were installed with homebrew. For me this is at least boost and seqan. Since boost is the second include in the list of external includes the aforementioned problems arise. The thing is, although these library includes are in a subfolder, the folder that is given to Openms is the basefolder (I.e. /Usr/local/include) and we just reference the headers with includes which then use the subfolder (e.g. #include <boost/Regex.h>). I think as long as such "basefolders" are included by OpenMS there is no way to mix contrib and systemwide includes. It has to be clearly decided by CMake if we prefer system or contrib. I do not think there can be exceptions, except if you deinstall the unwanted librarytype.

**Comment by hroest** [comment]
well I think there are a few things we can do:

- order the includes in a "smart" way such that it is very likely that the contrib path is first
- on OSX simply force the contrib path as the first include path

so the first solution is appealing as we dont need to change much, e.g. if we move up WildMagic as the first include path we know that it will take contrib first since there is no wildmagic in homebrew. Sounds like a hack but it would work (at least in my opinion). Of course if qt is first, the error is basically guaranteed.

**Comment by jpfeuffer** [comment]
Yes but QT is a framework on Mac and is located in another folder something with /Frameworks :)

**Comment by hroest** [comment]
so where does the initial `-isystem /usr/local/include ` come from?

**Comment by jpfeuffer** [comment]
Boost in my case.

```
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# compile CXX with /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXX_FLAGS =   -g -fPIC   -Weverything -Wno-sign-conversion -Wno-long-long -Wno-padded -Wno-global-constructors -Wno-exit-time-destruct

CXX_DEFINES = -DBOOST_ALL_NO_LIB -DOpenMS_EXPORTS -DQT_CORE_LIB -DQT_NETWORK_LIB

CXX_INCLUDES = -isystem /usr/local/Cellar/qt/4.8.6/include -iframework /usr/local/Cellar/qt/4.8.6/lib -isystem /usr/local/Cellar/qt/4.

```

**Comment by jpfeuffer** [comment]
Argh.. it does not display (or copy) the full file.
[flags.txt](https://github.com/OpenMS/OpenMS/files/968620/flags.txt)

**Comment by hroest** [comment]
so what if you move boost includes to the end? e.g. just change this line https://github.com/OpenMS/OpenMS/blob/develop/src/openms/CMakeLists.txt#L120 and move Qt and Boost to the end such that seqan and WM5 comes first?

**Comment by jpfeuffer** [comment]
Considering that seqan 1.4 is not in homebrew anymore this could solve it. But as you already said, this would be more of a hack since it depends on the availability of the contribs in brew etc.

**Comment by jpfeuffer** [comment]
Basically moving everything that could be installed globally to the end right?
I could also go through all includes and if I find a system include I move it to the end or something. But we should say in the docu somewhere, that we will always prefer contrib libraries (although this might be implicit since contribs are preferred during library finding)

**Comment by hroest** [comment]
yes, I agree its a hack but it works! also it people manage to install seqan 1.4 into /usr/local/include than they are proficient enough to figure this out :-)

**Comment by hroest** [comment]
@jpfeuffer thinking about this some more, I would actually now prefer a clear-cut solution where we add an additional cmake config parameter that is guaranteed to come first in the include order. Usually that would be the contrib folder. I think with this we could solve all of these problems and also address potential future problems on other setups. The idea of re-ordering we can still do but it seems a bit hack-ish and its only going to work in some of the cases...

**Comment by jpfeuffer** [comment]
I think @lars20070 had the same problem now. So you mean a separate flag during the cmake command line call (e.g. -DOPENMS_CONTRIB_DIR/DIRECTORY/LOCATION) that is added to the CMAKE_PREFIX_PATH and its ./include is added in the beginning of the include_directories?
Sounds good for me.

**Comment by hroest** [comment]
exactly! I think that would solve most of these problems here (since actually the linking and the libraries that get linked are correct!) - its just the order of the header directories that is the problem

**Comment by cbielow** [comment]
Does it make sense to make this new flag mandatory? AFAIK there is no system which works without contrib anyway, right?
This would make it easier to report incomplete calls to cmake (e.g. "You forgot to specify '-DCONTRIB_PATH=...').
On most systems the change is anyway not drastic in terms of the installation procedure, we just replace CMAKE_PREFIX_PATH with CONTRIB_PATH and the rest is done internally.

**Comment by jpfeuffer** [comment]
That is a good point. I am in favour of creating a mandatory flag.

**Comment by hroest** [comment]
well but we should still allow for CMAKE_PREFIX_PATH, e.g. for Linux we recommend:

```
-DCMAKE_PREFIX_PATH="/PATH/TO/contrib-build;/usr;/usr/local"
```

so maybe we just prepend the new flag to CMAKE_PREFIX_PATH so that the above is functionally equivalent to 
```
-DCMAKE_PREFIX_PATH="/usr;/usr/local" -DCONTRIB_PATH="/PATH/TO/contrib-build"
```
and internally we combine the two?

**Comment by jpfeuffer** [comment]
Hmm.. actually it is a bit weird that you have to specify this at all on Linux. "/usr/local" and "/usr" should be included by default in the CMAKE_SYSTEM_PREFIX_PATH (which is searched last by e.g. find_package).
But in general, yes, we should add the value of this mandatory new option to the beginning off the project specific CMAKE_PREFIX_PATH.

**Comment by hroest** [comment]
yes, not sure whether it is really necessary but at least it says so in our documentation. I think I remember having problems once when I did not include it

so it seems like we have a workable solution! :+1:

**Comment by jpfeuffer** [comment]
Seems to work quite well with the new flag. I will close for now.
