### ISSUE TITLE
IDFileConverter detects the input type according to the file extension

### ISSUE THREAD

**Issue by Stortebecker** [OpenMS/OpenMS#2563]
Therefore, the tool is not easy to integrate into frameworks like Galaxy. Integration would be improved by an additional param where the input file format can be determined. Or is it also possible to read the file format from metadata somehow?

**Comment by cbielow** [comment]
IDFileConverter will inspect the first lines of the file to determine the file type if the extension is unknown!
e.g.
```
c:\TEMP\idxml>idfileconverter -in small.idXML.bla -out small.pepXML
Progress of 'Loading...':
-- done [took 0.14 s (CPU), 0.14 s (Wall)] --
Progress of 'Storing...':
-- done [took 0.00 s (CPU), 0.01 s (Wall)] --
IDFileConverter took 0.15 s (wall), 0.14 s (CPU), 0.00 s (system), 0.14 s (user).
```

This might not work for every type, since it might still be ambiguous.

So what file types are we talking about in your case?

**Comment by blankclemens** [comment]
As an example: A `mzid` file starting with

```
<?xml version="1.0" encoding="UTF-8"?>
<MzIdentML id="PeptideShaker v0.33.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psidev.info/psi/pi/mzIdentML/1.1 http://www.psidev.info/files/mzIdentML1.1.0.xsd" xmlns="http://psidev.info/psi/pi/mzIdentML/1.1" version="1.1.0" creationDate="2014-08-23T04:42:21">
	<cvList>
		<cv id="PSI-MS" uri="http://psidev.cvs.sourceforge.net/viewvc/*checkout*/psidev/psi/psi-ms/mzML/controlledVocabulary/psi-ms.obo" version="2.25.0" fullName="PSI-MS"/>
		<cv id="UNIMOD" uri="http://www.unimod.org/obo/unimod.obo" fullName="UNIMOD"/>
		<cv id="UO" uri="http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/phenotype/unit.obo" fullName="UNIT-ONTOLOGY"/>
		<cv id="PRIDE" uri="http://code.google.com/p/ebi-pride/source/browse/trunk/pride-core/schema/pride_cv.obo" fullName="PRIDE"/>
	</cvList>
	<AnalysisSoftwareList>
[...]
```

Does not work ending in `.dat`, but runs without problems ending as `.mzid`.

**Comment by cbielow** [comment]
ouch. That should work,
The reason it does not is rather 'unfortunate': OpenMS checks for `<mzIdentML...>` with a lower-case 'mz...' 
Most tools seems to be writing `<MzIdentML....` which seems correct according to the schema.

Fix coming up.

**Comment by cbielow** [comment]
just in case: XML is case sensitive (see https://www.w3schools.com/xml/xml_syntax.asp)
schema: http://www.psidev.info/sites/default/files/mzIdentML1.1.0.xsd

**Comment by blankclemens** [comment]
Thanks, good to keep in mind! :)

**Comment by Stortebecker** [comment]
Cool, thanks for the quick fix @cbielow !

**Comment by cbielow** [comment]
thanks for reporting :)
