### ISSUE TITLE
SQLite not found

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#2564]
CMake errors when configuring OpenMS-dev
```
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find SQLITE (missing: SQLITE_INCLUDE_DIR) (Required is at least
  version "3.15.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindSQLITE.cmake:54 (find_package_handle_standard_args)
  src/openms/cmake_findExternalLibs.cmake:140 (find_package)
  src/openms/CMakeLists.txt:63 (include)
  ```

only when I explicitly use
 
`cmake -DSQLITE_INCLUDE_DIR=c:\dev\contrib_build\include\sqlite .`

it configures successfully.
This should not be required (all the other contrib libs are found when simply giving the contrib include by CMAKE_PREFIX_PATH (which is what I did).

**Comment by jpfeuffer** [comment]
It might be the subfolder. FindSQLITE seems to only search directly in the CMAKE_PREFIXES (e.g. contrib-build/include).
Either try not installing it into the subfolder or add another path in the Find module to search for. (If this was the reason)

**Comment by cbielow** [comment]
during linking i get:

```Error	LNK2001	unresolved external symbol sqlite3_close	OpenMS	C:\dev\OpenMS_build\src\openms\TransitionPQPReader.obj	1	
Error	LNK2001	unresolved external symbol sqlite3_close	OpenMS	C:\dev\OpenMS_build\src\openms\OpenSwathOSWWriter.obj	1	```

**Comment by hroest** [comment]
maybe @grosenberger can comment

@cbielow can you see whether the variable ${SQLITE_LIBRARY} is set in cmake and whether it is set correctly?

**Comment by cbielow** [comment]
//Path to a library.
SQLITE_LIBRARY:FILEPATH=C:/dev/contrib_build/lib/sqlite3.lib

seems correct and is also showing up in OpenMS_LIBRARIES:INTERNAL

However
```
dumpbin /EXPORTS sqlite.lib
Microsoft (R) COFF/PE Dumper Version 14.00.23918.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file sqlite.lib

File Type: LIBRARY

  Summary

          C3 .debug$S
          14 .idata$2
          14 .idata$3
           8 .idata$4
           8 .idata$5
           C .idata$6
```
i.e. the lib exports nothing...

**Comment by hroest** [comment]
strangely it worked yesterday: http://cdash.openms.de/index.php?project=OpenMS&date=2017-04-27

but today the windows builds are broken... :-(

**Comment by cbielow** [comment]
but we did not change anything in the build system. @jpfeuffer ideas?

**Comment by cbielow** [comment]
I have a fix for the missing symbols coming up. The way that sqlite is trying to figure out the dll-exports from its own .c file is just breathtaking: 
```
sqlite3.def:	Replace.exe $(LIBOBJ)
	echo EXPORTS > sqlite3.def
	dumpbin /all $(LIBOBJ) \
		| .\Replace.exe "^\s+/EXPORT:_?(sqlite3_[^@,]*)(?:@\d+|,DATA)?$$" $$1 true \
		| sort >> sqlite3.def
```

i.e. they are shipping an executable just to do some regex magic.
And of course that fails for newer versions of VS since the schema of mangled names changed (I guess).

**Comment by cbielow** [comment]
https://github.com/OpenMS/contrib/pull/40

**Comment by jpfeuffer** [comment]
Yes guys, I did a change on Windows yesterday. The errors in "update" showed that he was not git pulling the latest changes.
So now the Win builds reflect the current state again. Let's see if your fix fixes it.

**Comment by jpfeuffer** [comment]
But do I have to build all 4 contribs again? :(

**Comment by cbielow** [comment]
unfortunately, yes.
But `cmake -DBUILD_TYPE=SQLITE .` should suffice -- its really fast

**Comment by jpfeuffer** [comment]
Should be installed. Let's have a look.

**Comment by hroest** [comment]
can we close this? @cbielow @jpfeuffer
