### ISSUE TITLE
Missing util description

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2580]
+  - TODO we need descriptions for all of these
 +  - @subpage UTILS_MetaProSIP - xxx
 +  - @subpage UTILS_MultiplexResolver - xxx
 +  - @subpage UTILS_OpenMSInfo
 +  - @subpage UTILS_SimpleSearchEngine
 +  - @subpage UTILS_TopPerc
 +  - @subpage UTILS_RNPxlSearch - Tool for RNP

**Comment by hroest** [comment]
most of these are missing a `@page` inside the tool itself
