### ISSUE TITLE
libgsl conflict

### ISSUE THREAD

**Issue by olcc** [OpenMS/OpenMS#2584]
Hello,
I wanted to install OpenMS on Debian Linux, but it seems to conflict with Inkscape

- OpenMS requires libgsl0ldbl
- Inkscape requires libgsl2

Both versions of libgsl can not be installed concurrently on Debian, and as I want to keep Inkscape I can't install OpenMS unfortunately. Shouldn't OpenMS use libgsl2?

Olivier

**Comment by hroest** [comment]
this is more of an issue of the distribution than OpenMS, as they chose the library against which to link. I assume you want to install OpenMS 1.11 : https://packages.debian.org/jessie/libopenms1.11

you could try and install OpenMS 2.0 from here https://packages.debian.org/sid/libopenms2.0 which does not have this dependency any more or build OpenMS yourself

**Comment by olcc** [comment]
You are right! Pulling OpenMS out of the Debian "unstable" distribution was successful:
`$ sudo apt-get install openms/unstable`
Thank you.
