### ISSUE TITLE
OpenSwathWorkflow median rightmost histogram bin

### ISSUE THREAD

**Issue by PaulPyl** [OpenMS/OpenMS#2586]
Hello,

I see the following message in some of my OpenSwathWorkflow runs:
```
WARNING in SignalToNoiseEstimatorMedian: 1.26414% of all Signal-to-Noise estimates are too high, because the median was found in the rightmost histogram-bin. You should consider increasing 'max_intensity' (and maybe 'bin_count' with it, to keep bin width reasonable
```

Eventually those runs will fail with the following message:
```
Error: Unexpected internal error (WARNING: rsq: 0.85837066229807013 is below limit of 0.94999999999999996. Validate assays for RT-peptides and adjust the limit for rsq or coverage.)
```

I am wondering if the two are related?

Also, I cannot find a way of specifying the indicated 'max_intensity', 'bin_count', rsq or coverage options in the command line parameters of the OpenSwathWorkflow program.

I user OpenSwathWorkflow with parameters as specified in the tutorial here: http://www.openswath.org/openswath_instructions.html

Best,
Paul

**Comment by grosenberger** [comment]
Hi Paul,

You can find the extended parameters using ``OpenSwathWorkflow --helphelp``. For example the RT calibration parameters can be found under the subsection ``-outlierDetection``. You might want to set the parameter ``-outlierDetection:estimateBestPeptides``, which will select RT peptides in a more robust fashion. This is particularly useful if you don't use the Biognosys RT-kit, but either endogenous iRT peptides or the [ciRT](https://www.ncbi.nlm.nih.gov/pubmed/26199342) list.

Best regards,
George

**Comment by hroest** [comment]
Hi Paul

Just to follow up, no these are *generally* not related as the median computation on chromatograms complains if there is lots of zero. However in your case you seem to have found peaks but it just seems there is no linearity

Can you try with `-debug 10` and then you should see a file debug_irts.mzML in the current folder which contains the extracted chromatograms for the provided iRT peptides. Maybe this helps to see what goes wrong in your case?
