### ISSUE TITLE
AccurateMassSearch defaults findfile mapping struct

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#2590]
I ran into an issue using AccurateMassSearch. It seems that the default values for the positive and negative adduct files are working fine CEMISTRY/... . But it is not able to find the files for the mapping and struct.

```
AccurateMassSearch of node #3 started. Processing ...
Error: File not found (the file 'CHEMISTRY/HMDBMappingFile.tsv' could not be found)
Cannot read input file given from parameter '-db:mapping'!
```

If the static path is used for mapping & struct - it works like a charm. 

May you can have a look on it.

**Comment by cbielow** [comment]
fixed in #2602
