### ISSUE TITLE
MSGFPlusAdapter fails with N-term modification

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2591]
Giving Diethyl (N-term) as (e.g. fixed) modification in MSGFPlusAdapter (with version v2017.01.13)
results in the following line in the temporary msgfplus_mods.txt:
`56.0626, X, fix, N-term, Diethyl    # Diethyl (N-term)`
and fails with:
`AminoAcidSet: Invalid Residue(s) at line 7: 56.0626, X, fix, N-term, Diethyl]`

**Comment by jpfeuffer** [comment]
One of the latest nightly builds from end of April. From inside KNIME. I will try to update to latest and retry.

**Comment by hendrikweisser** [comment]
This should be fixed already (#2538).

**Comment by jpfeuffer** [comment]
Ah okay. Sorry, I had a quick look for recent MSGF tagged issues/PRs. Too quick probably. I will test it, thanks.

**Comment by jpfeuffer** [comment]
They should introduce regex search on github..

**Comment by jpfeuffer** [comment]
Yes. It is fixed. Thanks.
