### ISSUE TITLE
idXML: protein references written in wrong order or missing

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2596]
When writing idXML, protein accessions for peptide hits are collected via `PeptideHit::extractProteinAccessions` (https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/IdXMLFile.cpp#L301). This function collects the accessions from all "peptide evidences" associated with the hit into a `set<String>`. Problematically, this operation:
1. potentially reorders the accessions relative to the order of the evidences;
2. removes duplicates (a peptide can match in different locations on the same protein).

This means that the references in the "protein_refs" attribute in the idXML may no longer correspond to the "aa_before"/"aa_after" and "start"/"end" attributes.

For peptides that match multiple times in the same protein, this can lead to crashes when converting the idXML to mzIdentML using IDFileConverter (because protein accessions are "missing" due to the de-duplication).

**Comment by hendrikweisser** [comment]
Fix in preparation.

This problem may explain the discrepancies between protein lengths and peptide start/end positions e.g. in #2343.

**Comment by timosachsenberg** [comment]
fixed in #2592
