### ISSUE TITLE
ConvertTraMLToTSV not in development branch?

### ISSUE THREAD

**Issue by PaulPyl** [OpenMS/OpenMS#2599]
Hi guys,

I have a quick question, I was looking into issues I had with ConvertTSVToTraML and the reverse and realised that it is in the master branch but not in the development branch. Have these tools been removed or did something go wrong? I can still find some tests for them in the development branch:

```
paul@Cthulhu:/deadpool/software/sources/OpenMS-GitHub$ grep -r "ConvertTSV" src/
src/tests/topp/CMakeLists.txt:  add_test("TOPP_ConvertTSVToTraML_test_1" ${TOPP_BIN_PATH}/TargetedFileConverter -test -in ${DATA_DIR_TOPP}/ConvertTSVToTraML_1_input.tsv -out ConvertTSVToTraML_output.TraML.tmp -out_type TraML)
src/tests/topp/CMakeLists.txt:  add_test("TOPP_ConvertTSVToTraML_test_1_out1" ${DIFF} -in1 ConvertTSVToTraML_output.TraML.tmp -in2 ${DATA_DIR_TOPP}/ConvertTSVToTraML_output.TraML)
[...]
```
Best,
Paul

**Comment by grosenberger** [comment]
Hi Paul,

``ConvertTraMLToTSV`` and ``ConvertTSVToTraML`` have been unified in the tool ``TargetedFileConverter`` in OpenMS/develop.

Best regards,
George

**Comment by PaulPyl** [comment]
I see, thanks for the quick reply. I have a related question now that I am using the TargetedFileconverter. I see the following error when trying to convert this ([iRTs.traml.zip](https://github.com/OpenMS/OpenMS/files/993476/iRTs.traml.zip)) traml file:

```
paul@Cthulhu:/deadpool/projects/paul/M3_OpenMS/MSFragger$ /deadpool/software/sources/OpenMS-Devel/bin/TargetedFileConverter -in iRTs.traml -out iRTs.tsv -debug 40
Debug level: 40
 >> /deadpool/software/sources/OpenMS-Devel/bin/TargetedFileConverter -in iRTs.traml -out iRTs.tsv -debug 40
Value of string option 'test': 0
Log file: 
Writing to ''
Debug level (after ini file): 40
Value of string option 'no_progress': 0
Value of string option 'in': iRTs.traml
Checking input file 'iRTs.traml'
Value of string option 'in_type': 
<Checking input file 'iRTs.traml'> occurred 2 times
Input file type: traML
Value of string option 'out': iRTs.tsv
Checking output file 'iRTs.tsv'
Value of string option 'out_type': 
<Checking output file 'iRTs.tsv'> occurred 2 times
Value of string option 'legacy_traml_id': 0
Progress of 'converting to OpenSWATH transition TSV format':
Error: Unexpected internal error (unknown error)
Error occurred in line 145 of file /deadpool/software/sources/OpenMS-GitHub/src/openms/include/OpenMS/DATASTRUCTURES/Map.h (in function: const T& OpenMS::Map<Key, T>::operator[](const Key&) const [with Key = OpenMS::String; T = std::vector<OpenMS::CVTerm>]) !
```

I can interpret the error as the program trying to access a map of CVTerms with an invalid key, so I assume the file doesn't contain a key that is absolutely necessary?  Since most calls to getCVTerms are typically preceded by a call to hasCVTerms and otherwise use some default value I guess this is a case where this check is not performed.

Is there a way to get a more detailed trace of where the map access occurs (I am not sure how much more I can get by using -debug with a higher value) / did anyone encounter this error before and knows where it comes from?

I have attached the file so that someone more knowledgeable can have a look.

Btw.: It would be really nice to have a set of tools that can verify files against their specifications and point out any problems, e.g. a tools called FileValidator that can take various input files and check that they conform to the specifications / requirements for OpenMS. An option to fix easy problems on top of that would be even better :)

Does something like that exists, otherwise I think it would make a great addition to the toolset. 

Best,
Paul

**Comment by hroest** [comment]
Hi Paul

It seems that your problem is caused by data in the traml such as `sequence="L(UniMod:1)GGNEQVTR"` which OpenMS tries to parse and fails. I am not really sure why that is in the iRT peptides, but it seems like an N-terminal modification. If there is indeed an N-terminal modification here, then the correct terminology should be `"(UniMod:1)LGGNEQVTR_2"` or even better `"(UniMod:1).LGGNEQVTR_2"`

I will continue to look into this

**Comment by hroest** [comment]
after replacing the following in the TraML file it works with #2607 

```
121,122c121,122
<     <Peptide id="L(UniMod:1)GGNEQVTR_2" sequence="LGGNEQVTR">
<       <userParam name="full_peptide_name" type="xsd:string" value="(UniMod:1)LGGNEQVTR"/>
---
>     <Peptide id="L(UniMod:1)GGNEQVTR_2" sequence="L(UniMod:1)GGNEQVTR">
>       <userParam name="full_peptide_name" type="xsd:string" value="L(UniMod:1)GGNEQVTR"/>
247,248c247,248
<     <Peptide id="L(UniMod:1)GGNEQVTRGAGSSEPVTGLDAK_4" sequence="LGGNEQVTRGAGSSEPVTGLDAK">
<       <userParam name="full_peptide_name" type="xsd:string" value="(UniMod:1)LGGNEQVTRGAGSSEPVTGLDAK"/>
---
>     <Peptide id="L(UniMod:1)GGNEQVTRGAGSSEPVTGLDAK_4" sequence="L(UniMod:1)GGNEQVTRGAGSSEPVTGLDAK">
>       <userParam name="full_peptide_name" type="xsd:string" value="L(UniMod:1)GGNEQVTRGAGSSEPVTGLDAK"/>
```

if you really want modifications in your traml file,I think you need to use the `Modification` tag: http://www.peptideatlas.org/schemas/TraML/1.0.0/TraML1.0.0.html#Modification
