### ISSUE TITLE
TheoreticalSpectrumGenerator documentation is outdated

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#2609]
after #2472, documentation to TSG is outdated and needs to be updated.

some examples:
* there is no documentation on the use of the DataArrays and metaInfo
* documentation states for `getSpectrum`  'returns a spectrum with b and y peaks' - which is certainly not true in that fixed down sense but depends on the settings ParamHandler extension.

**Comment by jpfeuffer** [comment]
@enetz Can this be closed with the PR? Or is more to come?

**Comment by enetz** [comment]
right, I think this can be closed for now
