### ISSUE TITLE
www.openms.de uses Flash

### ISSUE THREAD

**Issue by olcc** [OpenMS/OpenMS#2619]
Hello,
The website [www.openms.de](https://www.openms.de/getting-started/command-line-and-visualisations/) uses Flash for the videos. However Flash is deprecated and should be eliminated from the web. Could you please integrate the videos without Flash?
Thank you,
Olivier
Source (example): https://www.theverge.com/2015/12/1/9827778/stop-using-flash

**Comment by timosachsenberg** [comment]
thanks for reporting. we will consider alternatives when we update our website

**Comment by jpfeuffer** [comment]
Which videos do you mean?

**Comment by olcc** [comment]
It's about all the videos on page https://www.openms.de/getting-started/command-line-and-visualisations
The first one is "Panning / Zooming (1D View)", and my browser reads "This page requires Adobe Flash Player".

**Comment by hroest** [comment]
:+1: I agree HTML5 would be great...

**Comment by jpfeuffer** [comment]
done.

**Comment by olcc** [comment]
Well done! Thank you.
