### ISSUE TITLE
Update Google Scholar account and upload to homepage

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2631]
Can someone update our Google Scholar account and send me a complete 2016.bib file?

**Comment by jpfeuffer** [comment]
Preferably  also a 2017.bib if there are any noteworthy publications.

**Comment by timosachsenberg** [comment]
can do

**Comment by jpfeuffer** [comment]
Great. Publications up-to-date.

**Comment by hroest** [comment]
Only two publications in 2016, is that correct? https://scholar.google.ch/citations?hl=en&user=tQ26gxIAAAAJ&view_op=list_works&sortby=pubdate

**Comment by hendrikweisser** [comment]
> Only two publications in 2016, is that correct?

Mine is missing!
https://www.ncbi.nlm.nih.gov/pubmed/27786492
http://pubs.acs.org/doi/abs/10.1021/acs.jproteome.6b00765

**Comment by timosachsenberg** [comment]
ok sorry my fault... will look at this more closely after the long weekend. was kind of a last minute action before I left.

**Comment by hroest** [comment]
can you add these as well

https://www.ncbi.nlm.nih.gov/pubmed/28379341
https://www.ncbi.nlm.nih.gov/pubmed/28188537
https://www.ncbi.nlm.nih.gov/pubmed/27701404

I think the comparison study is fair to be classified partly as OpenMS manuscript. Not sure about biodocker but I think it also makes sense as we were part of it.
