### ISSUE TITLE
Error with windows header from CoinOR inclusion?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2649]
Unfortunately I think it happened what I saw when testing the CoinOR inclusion branch of @FabianAicheler.
With unity builds we can not include CoinOR because it somehow includes the windows headers.
Not 100% sure that it was this pull request, but maybe 80%.

```
Repository	https://github.com/OpenMS/OpenMS/blob/master/src/openms/source/KERNEL/ConsensusFeature.cpp
Build Log Line	116
Error	
 /.../OpenMS/src/openms/source/KERNEL/ConsensusFeature.cpp(224): error C2059: syntax error : '::' [C:\dev\NIGHTLY\builds\win8-VS10_x64-Debug\src\openms\OpenMS.vcxproj]
```

**Comment by jpfeuffer** [comment]
I am not sure if we can give up on Unity builds. I need to compare the speed at some point. Windows is taking ages anyway and we need every second here if we want to add CI soon.

**Comment by FabianAicheler** [comment]
So from eg https://stackoverflow.com/questions/27442885/syntax-error-with-stdnumeric-limitsmax my understanding is that we could try to #undef max whereever we find a problem or wrap the max call in parentheses.

Would that suffice? How would I test it/what is the difference between the travis builds (which the pull request passed) and the unity build?

**Comment by jpfeuffer** [comment]
Travis is without windows unfortunately. Please add the label Windows-CI to your PR when you try to fix it. You will be the first tester.

**Comment by jpfeuffer** [comment]
I found the problem... The build machine had an old contrib installed. The old CoinOR version defined its own min and max, while the new one actually uses the ones from the stdlib.
Good that we upgraded Coin. I will reopen until I installed new contribs.

**Comment by jpfeuffer** [comment]
Worked.
