### ISSUE TITLE
Grouping of coeluting based on Chromatogram and samplewise-intensity correlation alone

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#2660]
We would like to add functionality for cooperation partners to group coeluting features without regarding mass differences, i.e. only by retention time/intensity information.

Ideally, we would beforehand do Decharging with known adducts, FeatureLinking(QT), and then group the linked consensus features (with their linked features for which we somehow get the chromatogram informations ). So we would do it for only one consensusXML with hopefully reduced/grouped data.

Currently, we are wondering which approach would be computationally feasibly. Naively, we thought to use the Decharger or the FeatureLinkerUnlabeledQT and remove their mz-difference criteria? Which method would be less likely to blow up, if we adapt it to
- consider ALL features, but in a very small retention time window for the computation of pairwise (chromatogram+intensity) correlation
- add edges/pairings for those which fullfil a score threshold (i.e., what are common numbers of pairs(?) at which point the two methods break down)
- solve the optimization/clusterin(?)

Any feedback recommendations is greatly appreciated.

**Comment by timosachsenberg** [comment]
What happens if you set RT to a small window and m/z to a very large one? maybe you also need to set -algorithm:nr_partitions <number> to 1 
as well as
Distance component based on m/z differences:
  -algorithm:distance_MZ:weight <value>                 Final m/z distances are weighted by this factor (default: '1' min: '0')
to 0

**Comment by hroest** [comment]
we have thought about this quite bit for SWATH analysis and there are a few papers out there that to this. I suggest to look at DIA-Umpire paper. Also some of the OpenSwath scores that we have may be useful (based on cross-correlation) to identify edge weights. I even have some code that works with the output of Masstraces from the metabolite FF. I could try and digg that up.

I think the best approach is to build a graph with weighted edges but dont allow any edge if delta_rt is larger than a certain number. I think by just looking at the RT (eg the apex) you will not be able to be specific enough. also we should look at what CAMERA is doing https://www.ncbi.nlm.nih.gov/pubmed/22111785
