### ISSUE TITLE
Special symbols in filenames

### ISSUE THREAD

**Issue by Leon-Bichmann** [OpenMS/OpenMS#2663]
Not sure if this would be worth fixing but Filenames containing '%' or '#' cant be read..

Best,
Leon

**Comment by timosachsenberg** [comment]
can you give some additional information if this problem occurs on the command line, in ini files, TOPPView, TOPPAS, KNIME?

**Comment by Leon-Bichmann** [comment]
Seems like this was only happening on our linux cluster with TOPPAS ExecutePipeline..
On my local mac TOPPAS and TOPPView open the file.

**Comment by lukaszimmermann** [comment]
Is this still an issue?
