### ISSUE TITLE
[master] String representation XMLHandler 

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2666]
```
C:/jenkins/ws/openms_windows_ci/c2e226b2/source/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(110): While loading 'C:/jenkins/ws/openms_windows_ci/c2e226b2/source/src/tests/topp/IDMapper_4_input.idXML': string representation overflows output binary result( in line 4 column 276)
Error: Unable to read file (While loading 'C:/jenkins/ws/openms_windows_ci/c2e226b2/source/src/tests/topp/IDMapper_4_input.idXML': string representation overflows output binary result( in line 4 column 276) in: C:/jenkins/ws/openms_windows_ci/c2e226b2/source/src/tests/topp/IDMapper_4_input.idXML)
```

I remember this from some issue recently I think. Is there a commit missing in master?

**Comment by jpfeuffer** [comment]
@mwalzer @timosachsenberg

**Comment by timosachsenberg** [comment]
probably the fix I applied to master: https://github.com/OpenMS/OpenMS/pull/2626/files

**Comment by jpfeuffer** [comment]
yes, 4 and 5 are failing. You will probably see it in the nightlies.

**Comment by timosachsenberg** [comment]
should I merge master into develop?

**Comment by timosachsenberg** [comment]
you mean these are failing on master or on develop?

**Comment by jpfeuffer** [comment]
They failed on my PR to fix NOMINMAX, which I based on master.

**Comment by jpfeuffer** [comment]
But he fails in reading the INPUTS

**Comment by jpfeuffer** [comment]
Ah yes you changed something there, too.

**Comment by timosachsenberg** [comment]
hmm in github I don't see changes if I click on blame

**Comment by jpfeuffer** [comment]
right.. then let's wait for nightlies. currently it is shadowed by the NOMINMAX error.

**Comment by jpfeuffer** [comment]
Okay with #2679 the symptoms are gone. We should investigate why that happened, though.

**Comment by paul-abraham** [comment]
All,
I appear to be having a similar issue, but with PeptideIndexer. Any help would be greatly appreciated.

ERROR PeptideIndexer       2:108      Failing process stdout: [Error: Unable to read file (While loading 'C:\Users\pav\AppData\Local\Temp\1\knime_Workflow Manage9603\knime_fs-ZipLoopStart_2_104-9617\000\000\0_0_MyriMatchAdapter_0\20170127_Easy_nLC_BSA_100fmol_AC40cm_01.idXML': string representation overflows output binary result( in line 4 column 320) in: C:\Users\pav\AppData\Local\Temp\1\knime_Workflow Manage9603\knime_fs-ZipLoopStart_2_104-9617\000\000\0_0_MyriMatchAdapter_0\20170127_Easy_nLC_BSA_100fmol_AC40cm_01.idXML)]

ERROR PeptideIndexer       2:108      Failing process stderr: [..\..\..\OpenMS\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(103): While loading 'C:\Users\pav\AppData\Local\Temp\1\knime_Workflow Manage9603\knime_fs-ZipLoopStart_2_104-9617\000\000\0_0_MyriMatchAdapter_0\20170127_Easy_nLC_BSA_100fmol_AC40cm_01.idXML': string representation overflows output binary result( in line 4 column 320)]

ERROR PeptideIndexer       2:108      Execute failed: Failed to execute node PeptideIndexer

**Comment by paul-abraham** [comment]
All,

I was able to identify the issue. The Myrimatch parameter "max missed cleaveages" set at infinity, (i.e., "-1") caused the above issue. Setting this parameter to a value, such as 5, fixed the problem. Hope this helps.
