### ISSUE TITLE
Fast base64 encoding

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2673]
We could use some faster base64 encoding as this is generally the bottleneck when reading XML files: 

* http://www.alfredklomp.com/programming/sse-base64/
* https://github.com/aklomp/base64

on the other hand with sqmass we may not need it any more

**Comment by cbielow** [comment]
running `perf` shows about 16% of time spend in decoding base64 with the current implementation (no SSE) and 5% of time in encoding. Reference (100%) is the loading/storing of a DIA mzML file of 2 GB size.

**Comment by cbielow** [comment]
we have base64 SIMD now. Closing.
