### ISSUE TITLE
Variable swath windows in OpenSwathWorkflow

### ISSUE THREAD

**Issue by kaehwan** [OpenMS/OpenMS#2676]
Hi all,

I am new to Github as well as OpenSWATH. I tried to analyze my SWATH results but failed. My data has 100 swath_windows, ranging from 400 - 1250 m/z. Is it the reason causing the failure?

Determined there to be 100 SWATH windows and in total 2017 MS1 spectra
Determined there to be 100 SWATH windows and in total 2017 MS1 spectra
-- done [took 06:30 m (CPU), 10:49 m (Wall)] --
Progress of 'Loading data file CHOK1-iRT.mzML':
Read chromatogram while reading SWATH files, did not expect that!
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(
196): Finished parsing Swath file
..\..\..\OpenMS\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(103): While loa
ding '/tmp/openswath_tmpfile_ms1.mzML': unable to open primary document entity '
C:\TPP\data\params//tmp/openswath_tmpfile_ms1.mzML'
Error: Unable to read file (- due to that error of type Parse Error in: ..\..\..
\OpenMS\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp@104-<unknown>)
Error occurred in line 151 of file ..\..\..\OpenMS\src\openms\source\FORMAT\MzML
File.cpp (in function: <unknown>) !
<While loading 'CHOK1-iRT.mzML': Ill formed absolute or relative sourceFile path
: file://c:\TPP\data\Swath> occurred 6 times

Best,
KH

**Comment by grosenberger** [comment]
Hi Kaehwan,

Did you supply an already extracted chromatographic mzML ``CHOK1-iRT.mzML`` to OpenSwathWorkflow or is this raw profile DIA data? Did you use a recent version of ProteoWizard/msconvert to convert the data? If you did, make sure that you do not provide a ``swath_windows_file``, the windows will be correctly read from the mzML file.

Best regards,
George

**Comment by kaehwan** [comment]
Hi George,

I converted the data with a recent version of msconvert and tested the OpenSwathWorkflow again without providing a swath_windows_file. Same error was identified.

Determined there to be 100 SWATH windows and in total 2017 MS1 spectra
Determined there to be 100 SWATH windows and in total 2017 MS1 spectra
-- done [took 03:33 m (CPU), 04:25 m (Wall)] --
Progress of 'Loading data file CHOK1-iRT.mzML':
Read chromatogram while reading SWATH files, did not expect that!
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(196): Finished parsi
ng Swath file
..\..\..\OpenMS\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(103): While loading '/tmp/openswath
_tmpfile_ms1.mzML': unable to open primary document entity 'C:\TPP\data\params//tmp/openswath_tmpfil
e_ms1.mzML'
Error: Unable to read file (- due to that error of type Parse Error in: ..\..\..\OpenMS\src\openms\s
ource\FORMAT\HANDLERS\XMLHandler.cpp@104-<unknown>)
Error occurred in line 151 of file ..\..\..\OpenMS\src\openms\source\FORMAT\MzMLFile.cpp (in functio
n: <unknown>) !
<While loading 'CHOK1-iRT.mzML': Ill formed absolute or relative sourceFile path: file://C:\TPP\data
\Swath> occurred 6 times

Best,
KH

**Comment by hroest** [comment]
Hi KH

can you please provide the full command line that you are using? Is it
possible  that you work on Windows and did not provide the "-tempDirectory"
option? If so, please use a file path  appropriate for Windows, such as
"C:\temp"

Best

Hannes

**Comment by kaehwan** [comment]
Hi Hannes,

Below was the full command line. I work on Windows and provide ### -tempDirectory option on C:\temp\

c:\OpenSwath>OpenSwathWorkflow -in CHOK1-iRT.mzML -tr SpecLib.TraML -tr_type TraML -tr_irt iRT.TraML
 -out_tsv output.tsv -out_chrom chrom.mzML -log log.txt -debug 10 -force
Debug level: 10
Writing to 'log.txt'
 >> OpenSwathWorkflow -in CHOK1-iRT.mzML -tr SpecLib.TraML -tr_type TraML -tr_irt iRT.TraML -out_tsv
 output.tsv -out_chrom chrom.mzML -log log.txt -debug 10 -force
Value of string option 'test': 0
Log file: log.txt
Writing to 'log.txt'
Debug level (after ini file): 10
Value of string option 'no_progress': 0
Value of string option 'in': CHOK1-iRT.mzML
Checking input file 'CHOK1-iRT.mzML'
Value of string option 'tr': SpecLib.TraML
<Checking input file 'CHOK1-iRT.mzML'> occurred 2 times
Checking input file 'SpecLib.TraML'
Value of string option 'tr_type':
<Checking input file 'SpecLib.TraML'> occurred 2 times
Input file type: traML
Value of string option 'out_features':
Value of string option 'out_tsv': output.tsv
Value of string option 'tr_irt': iRT.TraML
Checking input file 'iRT.TraML'
Value of string option 'rt_norm':
<Checking input file 'iRT.TraML'> occurred 2 times
Value of string option 'out_chrom': chrom.mzML
Checking output file 'chrom.mzML'
Value of string option 'ppm': 0
<Checking output file 'chrom.mzML'> occurred 2 times
Value of string option 'split_file_input': 0
Value of string option 'use_elution_model_score': 0
Value of string option 'force': 1
Value of string option 'sort_swath_maps': 0
Value of string option 'use_ms1_traces': 0
Value of string option 'enable_uis_scoring': 0
Value of double option 'min_upper_edge_dist': 0
Value of double option 'mz_extraction_window': 0.05
Value of double option 'rt_extraction_window': 600
Value of double option 'extra_rt_extraction_window': 0
Value of string option 'extraction_function': tophat
Value of string option 'swath_windows_file':
Value of int option 'batchSize': 0
Value of int option 'debug': 10
Value of double option 'min_rsq': 0.95
Value of double option 'min_coverage': 0.6
Value of string option 'readOptions': normal
Value of string option 'mz_correction_function': none
Value of string option 'tempDirectory': /tmp/
Loading mzML file CHOK1-iRT.mzML using readoptions normal
Progress of 'Loading metadata file CHOK1-iRT.mzML':
While loading 'CHOK1-iRT.mzML': Ill formed absolute or relative sourceFile path: file://C:\OpenSwath

Will analyze the metadata first to determine the number of SWATH windows and the window sizes.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 404.5 m/z with an isolation window of 400 to 409 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 413 m/z with an isolation window of 408 to 418 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 421.5 m/z with an isolation window of 417 to 426 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 429.5 m/z with an isolation window of 425 to 434 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 437 m/z with an isolation window of 433 to 441 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 444 m/z with an isolation window of 440 to 448 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 450.5 m/z with an isolation window of 447 to 454 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 456.5 m/z with an isolation window of 453 to 460 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 462 m/z with an isolation window of 459 to 465 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 468 m/z with an isolation window of 464 to 472 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 474 m/z with an isolation window of 471 to 477 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 479 m/z with an isolation window of 476 to 482 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 484 m/z with an isolation window of 481 to 487 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 489 m/z with an isolation window of 486 to 492 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 494 m/z with an isolation window of 491 to 497 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 499 m/z with an isolation window of 496 to 502 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 504 m/z with an isolation window of 501 to 507 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 509 m/z with an isolation window of 506 to 512 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 514 m/z with an isolation window of 511 to 517 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 519 m/z with an isolation window of 516 to 522 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 524 m/z with an isolation window of 521 to 527 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 528.5 m/z with an isolation window of 526 to 531 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 533 m/z with an isolation window of 530 to 536 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 537.5 m/z with an isolation window of 535 to 540 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 542 m/z with an isolation window of 539 to 545 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 547 m/z with an isolation window of 544 to 550 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 551.5 m/z with an isolation window of 549 to 554 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 555.5 m/z with an isolation window of 553 to 558 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 559.5 m/z with an isolation window of 557 to 562 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 564 m/z with an isolation window of 561 to 567 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 568.5 m/z with an isolation window of 566 to 571 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 572.5 m/z with an isolation window of 570 to 575 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 576.5 m/z with an isolation window of 574 to 579 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 580.5 m/z with an isolation window of 578 to 583 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 585 m/z with an isolation window of 582 to 588 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 589 m/z with an isolation window of 587 to 591 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 593 m/z with an isolation window of 590 to 596 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 597.5 m/z with an isolation window of 595 to 600 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 601.5 m/z with an isolation window of 599 to 604 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 605.5 m/z with an isolation window of 603 to 608 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 609.5 m/z with an isolation window of 607 to 612 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 613.5 m/z with an isolation window of 611 to 616 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 618 m/z with an isolation window of 615 to 621 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 622.5 m/z with an isolation window of 620 to 625 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 626.5 m/z with an isolation window of 624 to 629 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 631 m/z with an isolation window of 628 to 634 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 635.5 m/z with an isolation window of 633 to 638 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 640 m/z with an isolation window of 637 to 643 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 644.5 m/z with an isolation window of 642 to 647 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 648.5 m/z with an isolation window of 646 to 651 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 653 m/z with an isolation window of 650 to 656 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 658 m/z with an isolation window of 655 to 661 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 663 m/z with an isolation window of 660 to 666 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 668 m/z with an isolation window of 665 to 671 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 673 m/z with an isolation window of 670 to 676 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 678 m/z with an isolation window of 675 to 681 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 683 m/z with an isolation window of 680 to 686 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 688 m/z with an isolation window of 685 to 691 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 693 m/z with an isolation window of 690 to 696 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 698.5 m/z with an isolation window of 695 to 702 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 704 m/z with an isolation window of 701 to 707 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 709 m/z with an isolation window of 706 to 712 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 714.5 m/z with an isolation window of 711 to 718 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 720 m/z with an isolation window of 717 to 723 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 725.5 m/z with an isolation window of 722 to 729 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 731 m/z with an isolation window of 728 to 734 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 736.5 m/z with an isolation window of 733 to 740 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 742.5 m/z with an isolation window of 739 to 746 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 748.5 m/z with an isolation window of 745 to 752 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 755 m/z with an isolation window of 751 to 759 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 761.5 m/z with an isolation window of 758 to 765 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 767.5 m/z with an isolation window of 764 to 771 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 773.5 m/z with an isolation window of 770 to 777 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 780 m/z with an isolation window of 776 to 784 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 787 m/z with an isolation window of 783 to 791 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 794 m/z with an isolation window of 790 to 798 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 801 m/z with an isolation window of 797 to 805 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 808 m/z with an isolation window of 804 to 812 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 815.5 m/z with an isolation window of 811 to 820 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 823.5 m/z with an isolation window of 819 to 828 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 831.5 m/z with an isolation window of 827 to 836 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 839.5 m/z with an isolation window of 835 to 844 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 848 m/z with an isolation window of 843 to 853 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 857 m/z with an isolation window of 852 to 862 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 866 m/z with an isolation window of 861 to 871 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 875.5 m/z with an isolation window of 870 to 881 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 886 m/z with an isolation window of 880 to 892 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 897 m/z with an isolation window of 891 to 903 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 908.5 m/z with an isolation window of 902 to 915 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 921 m/z with an isolation window of 914 to 928 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 934.5 m/z with an isolation window of 927 to 942 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 949.5 m/z with an isolation window of 941 to 958 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 966 m/z with an isolation window of 957 to 975 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 984 m/z with an isolation window of 974 to 994 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 1004 m/z with an isolation window of 993 to 1015 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 1027.5 m/z with an isolation window of 1014 to 1041 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 1058 m/z with an isolation window of 1040 to 1076 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 1098 m/z with an isolation window of 1075 to 1121 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 1149.5 m/z with an isolation window of 1120 to 1179 m/z.
C:\dev\AUTO_PACKAGE\release\OpenMS\src\openms\include\OpenMS/FORMAT/SwathFile.h(339): Adding Swath c
entered at 1214 m/z with an isolation window of 1178 to 1250 m/z.
Determined there to be 100 SWATH windows and in total 2017 MS1 spectra
Determined there to be 100 SWATH windows and in total 2017 MS1 spectra
-- done [took 03:54 m (CPU), 04:59 m (Wall)] --
Progress of 'Loading data file CHOK1-iRT.mzML':

**Comment by hroest** [comment]
> The program ended unexpectedly due to low memory.

there is the problem.

I suggest to follow the instructions here http://openswath.org/en/latest/docs/openswath.html and take the commands from  http://biorxiv.org/content/early/2016/03/19/044552

you should use

```
-sort_swath_maps
-readOptions cache
-tempDirectory C:\Temp
-batchSize 1000
```
