### ISSUE TITLE
Continuous Integration and Nightly builds

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2680]
Hey @OpenMS/developers 

to advance with our new CI platform Jenkins, I would like to ask on your input to the actual build matrix.

What would you like in the nightlies, what for every pull request, what during release testing. We can also mark specific pull requests with a comment if we want to save resources (which is the main reason why I open this issue).

We have:
  - 1 docker server with 16 cores (shared, can provide different Linux flavours)
  - 2 win VMs with 2 cores each (dedicated, VS2013 and VS2015)
  - 1 win physical machine with 4 (or 8?) cores (shared)
  - 2 mac minis with 4 cores each (shared, Sierra and El Capitan)
  - I will add our old Mac soon, so we have another dedicated machine.

With shared, I mean shared with BALL AND SeqAn. You might also want to consider that a Windows build with tests and documentation on 2 cores takes 1:30h (not very "continuous").
Looking forward to your input.

**Comment by timosachsenberg** [comment]
Would be great to have in our nightlies:
- AddressSanitizer
- pyOpenMS
- checker.php
- spell check

**Comment by hroest** [comment]
I agree with timo, but from past experience the most needed one is the pyOpenMS -- all the others have only seldomly caused real problems. checker.php is anyways part of the current nightlies, right? Also the spellcheck is not really automatic, so there is no real automatic check here ...

**Comment by FabianAicheler** [comment]
Is the documentation OS specific/is there anything that can break just for Windows?

**Comment by jpfeuffer** [comment]
Usually not. If Latex is installed properly with the needed packages, it should build the same on all platforms.

**Comment by FabianAicheler** [comment]
Maybe no doc on Windows then, and can we intialize Windows builds only if the other OSs passed?
