### ISSUE TITLE
ADDRESS_SANITIZER does not work on mac

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2684]
Can't find the Asan library during linking.
https://stackoverflow.com/questions/44320465/whats-the-proper-way-to-enable-addresssanitizer-in-cmake-that-works-in-xcode

**Comment by hroest** [comment]
well you have to turn it on specifically on mac OSX so there is not really
a chance somebody would do that by mistake?

**Comment by jpfeuffer** [comment]
Sorry for being brief yesterday. Well I mean with the current implementation in CMake and Address_sanitizer=On, it does not work. It correctly compiles with the flags but during linking it is missing symbols from the Asan library like _Asan_init_. I think the SO thread linked above defines our options. The thing is, we usually do not use XCode, so not sure if setting XCode flags has an effect.
