### ISSUE TITLE
FileHandler should issue error if extension matches a different FileType

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2692]
e.g.
- storing a consensusXML as t.featureXML should result in an error
- storing a consensusXML as t.tmp is fine (e.g. our tests write a lot of .tmp files)

**Comment by jpfeuffer** [comment]
I agree. This would prevent errors in e.g. KNIME in nodes where the output type depends on the input type and users make errors in specifying the output type.

**Comment by timosachsenberg** [comment]
potentially one could enforce the ending if "-test" is not set.
@cbielow do you recall other situations when the file ending output by a tool does not match the file format extension?

**Comment by cbielow** [comment]
> potentially one could enforce the ending if "-test" is not set.

why allow it for -test? seems unnecessary.

> @cbielow do you recall other situations when the file ending output by a tool does not match the file 
> format extension?

ehhm.. no

**Comment by timosachsenberg** [comment]
*could* be dangerous if users use a system with name mangling that includes extensions 
and might be quite some work to adapt all tests.
but I guess then could still work around it and use e.g. the force flag

**Comment by timosachsenberg** [comment]
If I add the check to idXML (only) I get 190 tests failed out of 1986 so its a bit of work to change all tests files

**Comment by timosachsenberg** [comment]
```
diff --git a/src/openms/source/FORMAT/IdXMLFile.cpp b/src/openms/source/FORMAT/IdXMLFile.cpp
index c8e1eb5..5a7f045 100644
--- a/src/openms/source/FORMAT/IdXMLFile.cpp
+++ b/src/openms/source/FORMAT/IdXMLFile.cpp
@@ -33,6 +33,7 @@
 // --------------------------------------------------------------------------

 #include <OpenMS/FORMAT/IdXMLFile.h>
+#include <OpenMS/FORMAT/FileHandler.h>
 #include <OpenMS/SYSTEM/File.h>

 #include <OpenMS/CONCEPT/LogStream.h>
@@ -99,6 +100,12 @@ namespace OpenMS
     {
       throw Exception::UnableToCreateFile(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION, filename);
     }
+
+    if (FileHandler::getTypeByFileName(filename) != FileTypes::IDXML)
+    {
+      throw Exception::UnableToCreateFile(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION, filename  + " has invalid file extension. Should be: '" + FileTypes::typeToName(FileTypes::IDXML) + "'");
+    }
+
```

**Comment by cbielow** [comment]
`+    if (FileHandler::getTypeByFileName(filename) != FileTypes::IDXML)` should be extended to check for UNKNOWN - which should not trigger an exception (since we should allow myidxml.tmp as being valid)

**Comment by timosachsenberg** [comment]
I can do that.
