### ISSUE TITLE
Experience building OpenMS with Visual Studio 2017

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2693]
Somewhat naively, I installed the newest version of Microsoft Visual Studio, VS 2017, on my new Windows 10 laptop and tried to build OpenMS (64 bit) with it. I succeeded in the end, but some tinkering was necessary, since OpenMS only supports VS up to 2015 out of the box. I thought it might be useful to share my experiences here.

1. Building Qt 4.8.7:
Follow the process described in the OpenMS documentation (http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/install_win.html) under "QT installation". Importantly, apply the patch from the "contrib" package and set `-platform win32-msvc2015` in the "configure" call. (Qt 4.8.7 doesn't know about MSVC 2017, but using the 2015 platform seems to have worked.)
Once installed, Qt cannot be moved (without breaking path references in "qmake"), so make sure to install it in the desired place using `-prefix` with an absolute (!) path in the "configure" call.

2. Building the "contrib":
My CMake version (3.8.2) has support for the "Visual Studio 15 2017 Win64" generator, so I used that. (I haven't tried the "Visual Studio 14 2015 Win64" generator; maybe that would have been easier.) I had to adapt the "CMakeLists.txt" in the "contrib" to make the build system aware of that version. Around line 275, I added:
```
  elseif (CMAKE_GENERATOR MATCHES ".*Visual Studio 15.*")
    set(TMP_MSVC_VERSION "15")
```
This already made it work for some "contrib" libraries, but not all:
- Boost: The version currently shipped with OpenMS (1.61) doesn't support VS 2017. I replaced it with version 1.64 (which does). I manually downloaded the "tar.gz" file from the Boost website and put it in my "contrib-build\archives" folder. I also replaced the occurrences of "boost_1_61_0" with "boost_1_64_0" in the "CMakeLists.txt" and adapted the SHA1 hash (run CMake once, it will complain about the SHA1 mismatch, giving you the expected one that you can copy over).
- Xerces-C++ and CoinMP: These use VS solution (.sln) files to build on Windows, but the latest ones they include are for VS 2015 (VC 14). To get ones that work in VS 2017, I opened the solutions in VS and used the "Retarget" function to port them to VS 2017 and the Windows 10 SDK. I saved the updated solution files in new folders: `contrib-build\src\xerces-c-3.1.1\projects\Win32\VC15\xerces-all\serces-all.sln`  for Xerces-C++ and `contrib-build\src\CoinMP-1.8.3\CoinMP\MSVisualStudio\v15\CoinMP.sln` for CoinMP. (I may have just replaced some of the other solution files; not sure if it matters.)

3. Building OpenMS:
That worked fairly easily using "cmake" and the "build.bat" script, once the dependencies were sorted out and relevant entries were added to the "Path" environment variable (see documentation). Note that in the "cmake" call, `-D OPENMS_CONTRIB_LIBS="..."` should be used now (instead of `CMAKE_PREFIX_PATH`); the documentation is outdated in that regard.

Caveats:
- I haven't really used this OpenMS installation yet (beyond opening an example file in TOPPView).
- Some of the tests are failing (but most pass).
- I don't know if pyOpenMS could be built.

**Comment by jpfeuffer** [comment]
Cool! Thanks for testing this.

1.) You can move QT if you add a qt.conf file in your build folder with the following contents (replace prefix with your new one):
```
[Paths]
Prefix = c:/dev/qt-4.8-vs2015-64bit 
```
Check with qmake.exe --query if it worked. This will be checked by CMake.

2.) You can open a PR against OpenMS/contrib. I can upload boost to the FTP. I think retargeting the sln files is also the right way, but could you copy them first into a v15 subfolder and then retarget. Maybe that is safer? Remember to remove any temporary files (from e.g. a test build) before zipping and sending it to me for upload.
We should think about a more generic way to get the MSVC version instead of adding an if case everytime but I was lazy, too that last time. Do not forget to add vc15 in the warning message.

3.) Where exactly is the docu outdated for the new flag? Maybe I forgot some parts but I think I updated it in the install docus at a least.

**Comment by hendrikweisser** [comment]
@jpfeuffer: Thanks for the comments!

> 1.) You can move QT if you add a qt.conf file in your build folder

That is really good to know and could have saved me a lot of (re-)compile time. ;-)

> 2.) You can open a PR against OpenMS/contrib.

Not sure if I'll get to it before I go on holiday on Saturday.

> 3.) Where exactly is the docu outdated for the new flag?

It's on this page, under "Installing OpenMS": http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/install_win.html
I haven't checked the sources - perhaps the webpage is just not up-to-date?

**Comment by jpfeuffer** [comment]
1) Damn, a shame. After the 5th build I also started looking for this solution.
2) It is not time-sensitive but it would be a waste if these efforts are forgotten.
3) Yes, that is probably it.

**Comment by jpfeuffer** [comment]
Hey @hendrikweisser . Since we introduced C11 now and probably need to drop support for <=2013, it would be nice to support the newest version 2017, too.
Could you create a PR to contrib with your changes?

**Comment by hroest** [comment]
Also, can we try and use boost 1.62 or 1.63 for different platforms as these are currently supported by debian/ubuntu - it would make life for everybody a bit easier to have the same boost versions across platforms. @hendrikweisser do any of these work with MSVS 2017 ?

**Comment by hendrikweisser** [comment]
I'll have a look at it next week.

**Comment by hendrikweisser** [comment]
Sorry, I didn't have much for it this week. With `git diff` I only get the changes in the "CMakeLists.txt" (since only that comes directly from the repository). What should I do about Xerces-C++ and CoinMP?

**Comment by hendrikweisser** [comment]
> Also, can we try and use boost 1.62 or 1.63 [...] do any of these work with MSVS 2017 ?

Not tested, but 1.64 lists "Visual C++ 14.1" (which corresponds to Visual Studio 2017) under "Boost's additional test compilers", while 1.63 does not. :-(
(http://www.boost.org/users/history/version_1_64_0.html and http://www.boost.org/users/history/version_1_63_0.html, at the bottom.)

**Comment by hroest** [comment]
> Not tested, but 1.64 lists "Visual C++ 14.1" (which corresponds to Visual Studio 2017) under "Boost's additional test compilers", while 1.63 does not. :-(

seems like you are right and getting it to work may not be trivial https://stackoverflow.com/questions/41464356/build-boost-with-msvc-14-1-vs2017-rc

well I guess that eventually 1.64 will also show up in the debian repos...

**Comment by jpfeuffer** [comment]
hey @hendrikweisser can you upload your modified contrib sources somewhere?
For the git diff, just open a PR to contrib. I can do the rest.

**Comment by jpfeuffer** [comment]
We have a build machine with VS2017 now. We could proceed.

**Comment by hendrikweisser** [comment]
@jpfeuffer: Done. I've opened the pull request (https://github.com/OpenMS/contrib/pull/44) and emailed you the updated project files.
