### ISSUE TITLE
MSFragger Adapter

### ISSUE THREAD

**Issue by klemens1** [OpenMS/OpenMS#2694]
We have been using `MSFragger` in combination with `IDFileConverter` with great success. 
We would however greatly appreciate it, if we could directly include `MSFragger` into the OpenMS workflow. This would also be interesting for the community, since the speed of MSFragger allows for open searches and could also be used to get a very fast overview of labeling efficiency, missed cleavages etc. 
We're happy to help testing the beta-adapter.

**Comment by timosachsenberg** [comment]
This is a great idea we have also been thinking about recently. I think @Leon-Bichmann volunteered to take a look at it once he finds some time.

**Comment by Leon-Bichmann** [comment]
Yep, I can do it on the long term but as a warning I think it might take a while until Ill have some time for it.

**Comment by hroest** [comment]
can we even legally distribute the executable? it seems to be a non-standard licence: https://secure.nouvant.com/umich/technology/7143/license/633

**Comment by jpfeuffer** [comment]
See #2969 . We have a private repository for the nightly tests. Unless we hear back, we cannot distribute it with our packages.
