### ISSUE TITLE
Evaluate https://github.com/marketplace/codacy

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2698]

**Comment by mwalzer** [comment]
worth to point out, that c++ is [user supported](https://support.codacy.com/hc/en-us/articles/207994735-Supported-Languages), whatever that means

**Comment by timosachsenberg** [comment]
I tentatively added codacity.
Access via badge in  #2699 
or https://www.codacy.com/app/timosachsenberg/OpenMS/dashboard

**Comment by timosachsenberg** [comment]
We can use this issue to discuss disabling of specific tests.
E.g., "file name too long" etc.

**Comment by timosachsenberg** [comment]
@cbielow @jpfeuffer @hroest @hendrikweisser @mwalzer I add you here in case you want to discuss checks

**Comment by hroest** [comment]
did the check find anything useful so far?

**Comment by timosachsenberg** [comment]
I think it is pretty useful as it gets regularly updated and in the future we might expect more checks that can easily be turned on/off. So far, some smaller issues popped up we might want to take a look at (e.g., a potential memory leak). Can you check the python issues and disable the patterns (I think I added you as a collaborator) that cause a lot of false positives. Alternatively, disable the check for single files?

**Comment by jpfeuffer** [comment]
I like it, too.
What was the consensus on the min/max macros.
What do you think about negation in short form ('!'). I think we could whitelist that, too.

**Comment by timosachsenberg** [comment]
I think we can disable the min/max macros as well as the negation short form warning.
Will do so...

**Comment by timosachsenberg** [comment]
```
full block {} expected in the control structure
if (cnt == 1) second_xcorr = xcorr;
```
we widely allowed single line constructs like this. so I removed it. Fine with everyone?

**Comment by cbielow** [comment]
yeah, makes sense.
Can it mark dangerous linebreaks though?
e.g.
``` if (true)
x = 1;
```

**Comment by timosachsenberg** [comment]
No these are not checked if the pattern is disabled.

**Comment by hroest** [comment]
> No these are not checked if the pattern is disabled.

I think in that case we should leave them. At least it will detect if *new* issues arise and maybe we can clean the code at some point. I think detecting the linebreaks @cbielow pointed out is more important than disabling the warning.

I agree with the `!` operator, we can disable that warning

**Comment by timosachsenberg** [comment]
ok I reenabled the check
Examples:
```
if (x) foo();     // bad style
if (x) { foo(); } // OK

if (x)
    foo();        // again bad style

if (x)
{                 // OK
    foo();
}

if (x)
    while (y)     // bad style
        foo();    // bad style

if (x)
{                 // OK
    while (y)
    {             // OK
        foo();
    }
}

for (int i = 0; i = 10; ++i);  // oops!
    cout << "Hello\n";

for (int i = 0; i = 10; ++i)   // OK
{
    cout << "Hello\n";
}
```

**Comment by hroest** [comment]
sounds good to me...

**Comment by hendrikweisser** [comment]
We could also consider updating the coding conventions (https://github.com/OpenMS/OpenMS/wiki/Coding-conventions) to be in line with what is checked.

**Comment by timosachsenberg** [comment]
I changed it. In the long run we might think about linking to the (extensive) rule set on codacy and just provide a correct example as template. Explicitly listing all rules in the wiki might be a bit overkill.
