### ISSUE TITLE
pyopenms fails

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2705]
http://cdash.openms.de/viewBuildError.php?buildid=227307

**Comment by hroest** [comment]
This could be solved with #2647 and has mostly to do with installing a newer version of autowrap - does it happen on develop or master? Can you check whether this fixes the issue:

```
-        MSSpectrum[Peak1D] operator[](int)      nogil except + # wrap-upper-limit:size()  # TODO deprecate for 1.12
+        MSSpectrum[Peak1D] operator[](int)      nogil except + # wrap-upper-limit:size()   
```

**Comment by jpfeuffer** [comment]
Cool. It is on master. I thought I upgraded autowrap. Let me check that. Which version would be needed?
And in case it is uptodate: Just remove the comment?

**Comment by jpfeuffer** [comment]
[microcebus ~]$ pip install -U autowrap
Requirement already up-to-date: autowrap in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: Cython>=0.19 in /usr/local/lib/python2.7/site-packages (from autowrap)

**Comment by jpfeuffer** [comment]
Try removing the comment now.

**Comment by hroest** [comment]
well its more like that autowrap is too new ... the older autowrap had no problem with that comment but with newer autowrap you need to remove ` # TODO deprecate for 1.12`

**Comment by jpfeuffer** [comment]
yes. removal of the deprecation comments solved it. But if it is a deprecation TODO for 1.12, should we get rid of it completely? Or what was the comment for?
