### ISSUE TITLE
Support for TMT 11-plex

### ISSUE THREAD

**Issue by glormph** [OpenMS/OpenMS#2706]
Apparently TMT now comes in 11-plex, so this is to ask if there will be support for it "soon". Our lab is planning to use it, but I have unfortunately no spectra yet to supply for this feature.

**Comment by glormph** [comment]
I should add that the difference with 10plex is that 11-plex will have 131N and 131C ions, as opposed to the single 131 reporter ion from the 10plex.
https://www.thermofisher.com/order/catalog/product/A34808

**Comment by hroest** [comment]
@cbielow @timosachsenberg what do we need to support this?

**Comment by timosachsenberg** [comment]
I think https://github.com/OpenMS/OpenMS/pull/965 is a good reference to see what needs to be added.

**Comment by cbielow** [comment]
I don't think its that much effort, but we'd need a volunteer to do it :)

**Comment by lukaszimmermann** [comment]
Will have a look

**Comment by lukaszimmermann** [comment]
Included by #2804
