### ISSUE TITLE
Most probably sqlite3 missing for pyOpenMS on Windows

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2713]
https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/setup.py#L139

In general. Can't we build sqlite statically? Or can we automate the process of including shared libraries in our many packaging types?
If we agree that all of this is not worth the effort for a rare task of a new contrib library, we should write an extensive documentation on which places to change for future updates.

**Comment by hroest** [comment]
probably also for OSX and Linux, right?

**Comment by jpfeuffer** [comment]
Hm actually looking at my built contrib, on macOS it is built statically.

**Comment by jpfeuffer** [comment]
But yes in general we might not be able to guarantee in which state the libraries are found therefore this might be a potential place for improvement since this affects also the other packages.
We could require certain types of the libraries when we are packaging for example.

**Comment by jpfeuffer** [comment]
Fixed in #2792
