### ISSUE TITLE
XQuestResultXMLHandler error on Windows.

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2718]
Errors while compiling #2717 which means it probably fails on develop (without ASan or similar):

```
 4>C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\source\src\openms\include\OpenMS/FORMAT/HANDLERS/XQuestResultXMLHandler.h(69): error C2144: syntax error: 'char' should be preceded by ')' [C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\build\src\openms\OpenMS.vcxproj]

     4>C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\source\src\openms\include\OpenMS/FORMAT/HANDLERS/XQuestResultXMLHandler.h(69): error C2144: syntax error: 'char' should be preceded by ';' [C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\build\src\openms\OpenMS.vcxproj]

     4>C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\source\src\openms\include\OpenMS/FORMAT/HANDLERS/XQuestResultXMLHandler.h(69): error C2059: syntax error: ')' [C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\build\src\openms\OpenMS.vcxproj]

     4>C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\source\src\openms\include\OpenMS/FORMAT/HANDLERS/XQuestResultXMLHandler.h(69): error C2208: 'char': no members defined using this type [C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\build\src\openms\OpenMS.vcxproj]

     4>C:/jenkins/ws/openms_pr_windows_ci/c2e226b2/source/src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp(57): error C2144: syntax error: 'char' should be preceded by ')' [C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\build\src\openms\OpenMS.vcxproj]

     4>C:/jenkins/ws/openms_pr_windows_ci/c2e226b2/source/src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp(57): error C2144: syntax error: 'char' should be preceded by ';' [C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\build\src\openms\OpenMS.vcxproj]

     4>C:/jenkins/ws/openms_pr_windows_ci/c2e226b2/source/src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp(57): error C2761: 'void OpenMS::Internal::XQuestResultXMLHandler::removeSubstring(OpenMS::String &,const OpenMS::String &)': member function redeclaration not allowed [C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\build\src\openms\OpenMS.vcxproj]

     4>C:/jenkins/ws/openms_pr_windows_ci/c2e226b2/source/src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp(57): error C2059: syntax error: ')' [C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\build\src\openms\OpenMS.vcxproj]

     4>C:/jenkins/ws/openms_pr_windows_ci/c2e226b2/source/src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp(58): warning C4091: '': ignored on left of 'char' when no variable is declared [C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\build\src\openms\OpenMS.vcxproj]

     4>C:/jenkins/ws/openms_pr_windows_ci/c2e226b2/source/src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp(58): error C2143: syntax error: missing ';' before '{' [C:\jenkins\ws\openms_pr_windows_ci\c2e226b2\build\src\openms\OpenMS.vcxproj]

     4>C:/jenkins/ws/openms_pr_windows_ci/c2e226b2/source/src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp(58): error C2447: '{': missing function header (old-style formal list?) 
```

**Comment by hroest** [comment]
did you really mean  #2717 - that seems like an unrelated PR?

**Comment by jpfeuffer** [comment]
Well I linked it since it was the first and only place where it came up (and where one could look up the error messages). And nightlies are currently building master (until tomorrow probably).
But yes the changes in the PR are unrelated.

See also here:
https://abibuilder.informatik.uni-tuebingen.de/jenkins/view/OpenMS/job/openms_pr_windows_ci/12/compiler=msvc-14,os_label=win10_64/artifact/

**Comment by jpfeuffer** [comment]
Can one remove links by editing?

**Comment by enetz** [comment]
@lukaszimmermann 
The lines causing these errors look like this:
in the header:
`static void removeSubstring(String & large, const String & small);`
in the cpp:
```
void XQuestResultXMLHandler::removeSubstring(String & large, const String & small)
{
...
```

Could it be because of the spaces around the '&s' ?
Otherwise I do not see anything there, that could cause syntax errors.

**Comment by jpfeuffer** [comment]
I am not sure. Let's try it. You will have Windows CI. It could be that there are two spaces in the implementation of the function instead of one?? But then msvc would be really stupid.

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp#L488
You might also not need to use the scope operator here (488ff) but I am not sure.

**Comment by lukaszimmermann** [comment]
I do not think that it is the spaces. Whitespace between tokens is discarded anyways. I am currently trying to reproduce that error on my Windows machine.

**Comment by jpfeuffer** [comment]
Ok. Yes try it first. Maybe it is false alarm.

**Comment by lukaszimmermann** [comment]
So I built the branch `hroest:feature/chrom_dataprocessing` on Win10_x86_64 with msvc-14 on Release mode without any errors.

**Comment by jpfeuffer** [comment]
Can you build it with "-DENABLE_UNITY_BUILD=On" again? Then I will close.

**Comment by lukaszimmermann** [comment]
Ok, now I indeed get this error. Let me see if I can figure that out.

**Comment by lukaszimmermann** [comment]
Not sure what sinister things are going on there, but apparently the parameter name 
"small" caused this error. I renamed it and now it works. Gonna prepare a fix.

**Comment by hroest** [comment]
Nice find, got to love the fun complexity of the issues we are dealing with
today

sent from my smartphone -- you may keep any typos you find.

**Comment by jpfeuffer** [comment]
Crazy... maybe that is the reason?
https://stackoverflow.com/questions/27793470/why-does-smallgive-an-error-about-char

**Comment by lukaszimmermann** [comment]
Most likely.

**Comment by hroest** [comment]
wow, how wonderful - apparently rpcndr.h defines
```
#define small char
```
