### ISSUE TITLE
QT5 for Windows

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2720]
Mainly @cbielow 
I want to start installing QT5 on the build machines to be ready when we merge.
- Do you have experience with this?
- How did you proceed? Could you use the qt5 web installer?
- I downloaded it and am thinking to install QT5.9 (msvc2013-64bit, msvc2015-32bit/64bit, msvc2017-64bit available) with QTWebEngine and NetworkAuth maybe? Otherwise I probably have to build from source again. Do you have scripts for this?

**Comment by hroest** [comment]
related to #2241

**Comment by jpfeuffer** [comment]
It's quite easy to install. See docu added in #3226
