### ISSUE TITLE
Problems with small molecule ID (AccurateMassSearch)

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2725]
I've started to use AccurateMassSearch to identify small molecules following a PeakPickerHiRes -> FeatureFinderMetabo -> FeatureLinkerUnlabeledQT workflow (in KNIME). This seems like a promising approach and works in principle, but there are aspects that could be improved:

1. AccurateMassSearch fails with an error if the "db:mapping" input file doesn't contain the "database_name" header line. However, this isn't documented; the parameter documentation makes it sound like only the data columns are needed.

2. The parameter "db:struct" in AccurateMassSearch should be optional. I've created my own database ("db:mapping") file with sum formulas and compound names. (By the way, the option to compute the mass from the sum formula is great!) I don't have SMILEs or INCHIs for most of the compounds and don't need them, but annoyingly I still have to create the "structures" file to very exact specifications.

3. The parameters "positive_adducts_file" or "negative_adducts_file" in AccurateMassSearch should be optional. If I'm using positive mode, I shouldn't have to specify a negative adducts file. (By the way, usually we don't put "file" in the parameter name for input files.)

For 2. and 3., I would propose to change the semantics of these parameters to be optional, have a default value pointing to the respective "share/CHEMISTRY" file (or is that not possible in KNIME?), and handle an empty value as "data not needed".

4. The parameter "keep_unidentified_features" in AccurateMassSearch doesn't affect the consensusXML output ("out_annotation"). It would be quite useful if it could be used to include/exclude unidentified (consensus) features, especially since:

5. AccurateMassSearch adds "PeptideIdentification" entries (empty in most cases!) to every (consensus) feature in the "out_annotation" output. This makes it impossible to use "FileFilter -id:remove_unannotated_features" to get rid of (consensus) features without annotation. A PeptideIdentification should only be added to (consensus) features that gave rise to an ID.

The following may be problems of our mzTab implementation, not of AccurateMassSearch itself:

6. The SmallMoleculeMzTabReader in KNIME can't read the output of AccurateMassSearch. The error message is:
`Execute failed: Invalid MzTab file: Invalid entry in small molecule header: Expected 'unit_id' but got 'chemical_formula'`
Indeed, the "unit_id" column is not present in the mzTab output file.

7. Alternative explanations for a peak (i.e. different compounds with the same mass) are listed in multiple rows in the mzTab output. This is confusing, as it seems like two compounds were quantified independently, when in fact there is ambiguity in the assignment. If I understand the mzTab standard correctly, alternative identifications should appear in one line, with IDs separated by "|" (http://www.psidev.info/sites/default/files/R2_mzTab_format_specification.pdf, page 30).

8. This is a minor issue: In sum formulas, OpenMS doesn't require the elements to be in any specific order. However, mzTab does: "elements in the order C, H and then alphabetically all other elements". When necessary, it would be good if the elements could be reordered for the mzTab output.

**Comment by hendrikweisser** [comment]
Another suggestion:

9. In the mzTab output of AccurateMassSearch, when consensusXML is used as input, there are multiple "study variables" with quantitative information (corresponding to the different sub-maps in the consensus map). Currently, the same uninformative description is used for all of them:
`MTD	study_variable[1]-description	Accurate mass search result file.`
It would be helpful to include the filenames of the sub-maps (from the "mapList" element in the consensusXML, `ConsensusMap::getFileDescriptions`) in the descriptions.

**Comment by timosachsenberg** [comment]
@hendrikweisser sorry I am kind of busy so I probably will get to this later. Feel free to fix these issues. I think they are valid points and just have not been addressed so far.

1 - 3. valid and should be fixed (actually I though I added the optional input - maybe it is not in the nightly builds as these are broken)

4 - 5. @oliveralka do you recall if we addressed this already or at least talked about it?

6. SmallMoleculeMzTabReader is deprecated. Use MzTabReader instead. @jpfeuffer we should remove it from next release if not already done.

7. I think this is not really feasible because the theoretical masses might differ. In a future version of the standard I think some group identifier is used in an extra column (we could add the feature ID in an optional column)

8. sounds good. Output in proper Hill's notation

**Comment by hendrikweisser** [comment]
Thanks for the comments, Timo.

Regarding 7: I was referring to entries from the same row in the search database, i.e. where the mass and sum formula are the same, but different molecules (structures) are possible. These should definitely appear together, in my opinion.

**Comment by timosachsenberg** [comment]
hmm I think this may complicate visualization. For example, in KNIME you can directly visualize the SMILES column. If you now put multiple of them into a single cell, this would not work out of the box.

**Comment by oliveralka** [comment]
@timosachsenberg As far as I remember we have not looked into these specific issues. Our problem was that the files were not in the right location of share/chemistry - so more in the direction of 2 & 3.
