### ISSUE TITLE
Qt5 errors on travis

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2726]
currently we get a lot of config/linking errors on travis on the qt5 branch:

- http://cdash.openms.de/viewConfigure.php?buildid=228719
- http://cdash.openms.de/viewBuildError.php?buildid=228719

```

CMake Warning (dev) at src/topp/CMakeLists.txt:47 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "DTAExtractor" links to target "Qt5::Network" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

[...]
/usr/bin/ld: cannot find -lQt5::Network
```

it seems like `Qt5::Network` is not properly found and resolved and this not linked properly. This only happens in the debug builds for some reason ...

**Comment by hroest** [comment]
related to #2241

**Comment by timosachsenberg** [comment]
did you try to increase cmake_minimium_required?

**Comment by timosachsenberg** [comment]
just another guess: maybe the qt5 debug libraries are not properly installed

**Comment by hroest** [comment]
> did you try to increase cmake_minimium_required?

yes, its part of this PR. not sure whether it helped but it did not hurt - in our case we have an issue with `CMP0028` which is not part of the BALL policies

> just another guess: maybe the qt5 debug libraries are not properly installed

not sure whether that is the case as it seems all the class_tests are linked properly and only the TOPP/UTILS are affected by this. I am not sure I fully understand the issue myself though

**Comment by hroest** [comment]
Lets see what #2728 does...

**Comment by hroest** [comment]
seems like #2728 worked
