### ISSUE TITLE
ImageCreator crashes for very large pixel widths

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#2730]
For ultra high resolution images (>100,000 pixels) such as 
```
ImageCreator -height 7000 -width 100000 -in example.mzML -out example.png
```
`ImageCreator` crashes with
```
QImage::setPixel: coordinate (72873,3) out of range
```

**Comment by timosachsenberg** [comment]
most likely a Qt or operating system limitation

**Comment by hroest** [comment]
same here, I see huge memory consumption and then the same message - not sure whether it would eventually terminate but I aborted the program before I could find out. I agree with @timosachsenberg that its probably an inherent limitation of either Qt of the OS

**Comment by cbielow** [comment]
why these high-resolutions?
if really needed, svg might be the way to go...
