### ISSUE TITLE
Visualization of RT transformations (trafoXML) [274]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#274]
Submitted by hendrikweisser on 2011-02-25 21:35:15

For quality control of MapAligner results, it would be very useful to get a visualization of the computed transformations.

This could be done by adding another output ("-plots") to MapAligner, producing one plot per output file.
Alternatively, the ability to display trafoXML files could be added to TOPPView.

In both cases, a plot of "adjusted RT" against "input RT" should be produced. The data points from which the transformation was computed ("TransformationDescription::data_") should be shown as a scatterplot, together with a line indicating the result of applying the transformation.

In the case of output directly from MapAligner, the results on the input data can be used for the "result line".
In TOPPView, the "input RT" range would have to be sampled to generate that data. The range should be extended by 10% (or so) in the beginning and end to include some extrapolation in the visualization.

**Comment by timosachsenberg** [comment]
@hendrikweisser can this be closed now?

**Comment by hendrikweisser** [comment]
I think it would still be nice to have. I have R code to generate the plots that could potentially be integrated in the same way as in InternalCalibration.

**Comment by hroest** [comment]
@hendrikweisser why not just add them  to the `./tools/scripts` folder?

**Comment by hendrikweisser** [comment]
> why not just add them to the ./tools/scripts folder?

Can do, but I'd have to make the script a bit more user-friendly first.
"tools/scripts" or "share/OpenMS/SCRIPTS", though?

**Comment by timosachsenberg** [comment]
I think share/OpenMS/SCRIPTS would be more fitting.

**Comment by jpfeuffer** [comment]
Seems to be addressed sufficiently. Please reopen if not.
