### ISSUE TITLE
COMPARISON/CLUSTERING/GridBasedClustering.h: compiler error

### ISSUE THREAD

**Issue by sagitter** [OpenMS/OpenMS#2750]
Hello.

`OpenMS-2.2.0` does not compile on fedora with following error:

```
In file included from /builddir/build/BUILD/openms-2.2.0/py2build/src/openms/source/COMPARISON/CLUSTERING/GridBasedClustering.cpp:35:0:
/builddir/build/BUILD/openms-2.2.0/py2build/src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h: In member function 'void OpenMS::GridBasedClustering<Metric>::cluster()':
/builddir/build/BUILD/openms-2.2.0/py2build/src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h:186:52: error: no matching function for call to 'OpenMS::GridBasedClustering<Metric>::startProgress(int, OpenMS::Size&, const char [11])'
       startProgress(0, clusters_start, "clustering");
                                                    ^
In file included from /builddir/build/BUILD/openms-2.2.0/py2build/src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h:40:0,
                 from /builddir/build/BUILD/openms-2.2.0/py2build/src/openms/source/COMPARISON/CLUSTERING/GridBasedClustering.cpp:35:
/builddir/build/BUILD/openms-2.2.0/py2build/src/openms/include/OpenMS/CONCEPT/ProgressLogger.h:112:10: note: candidate: void OpenMS::ProgressLogger::startProgress(OpenMS::SignedSize, OpenMS::SignedSize, const OpenMS::String&) const
     void startProgress(SignedSize begin, SignedSize end, const String& label) const;
          ^~~~~~~~~~~~~
/builddir/build/BUILD/openms-2.2.0/py2build/src/openms/include/OpenMS/CONCEPT/ProgressLogger.h:112:10: note:   no known conversion for argument 3 from 'const char [11]' to 'const OpenMS::String&'
make[3]: *** [src/openms/CMakeFiles/OpenMS.dir/build.make:12153: src/openms/CMakeFiles/OpenMS.dir/source/COMPARISON/CLUSTERING/GridBasedClustering.cpp.o] Error 1
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/5831/20365831/build.log
Dependencies list: https://kojipkgs.fedoraproject.org//work/tasks/5831/20365831/root.log
Used hardware: https://kojipkgs.fedoraproject.org//work/tasks/5831/20365831/hw_info.log

**Comment by hroest** [comment]
hmm interesting, we have not touched that part of the code since years. Well, we anyways have to prepare a 2.2.1 release ... 

it seems like this must be the compiler, @jpfeuffer have you ever tried GCC 7.1

**Comment by jpfeuffer** [comment]
I think we had a non-specific complaint with gcc6+ before.

**Comment by jpfeuffer** [comment]
What if we use the explicit constructor in that method? E.g. OpenMS::String("clustering")?

**Comment by jpfeuffer** [comment]
But this is most likely not the only case where we use it like this?

**Comment by timosachsenberg** [comment]
alternatively one could also change startProgress argument list to (..., const String label) const;

https://stackoverflow.com/questions/4369807/c-passing-a-string-literal-instead-of-a-const-stdstring

**Comment by timosachsenberg** [comment]
Preparing a fix (currently for develop)
https://github.com/OpenMS/OpenMS/pull/2754

**Comment by timosachsenberg** [comment]
@sagitter can you check if https://github.com/OpenMS/OpenMS/pull/2754 solves all compile issues on gcc 7? otherwise we might need to create a new build setup here.

**Comment by hroest** [comment]
@jpfeuffer this may actually be a good use-case for our container architecture where we could test gcc7 builds...if it is indeed only a gcc issue!

**Comment by sagitter** [comment]
https://github.com/OpenMS/OpenMS/issues/2756 resolves the error reported in https://github.com/OpenMS/OpenMS/issues/2750#issue-241041706.

**Comment by hroest** [comment]
> But this is most likely not the only case where we use it like this?

but it seems the only place the compiler complains! strange, also clang4 or other gcc versions never complained ... maybe its because it is a template class?
