### ISSUE TITLE
sqlite CMake version check malfunctioning

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2755]
I currently encounter some errors related to sqlite.

1482: Error: Unexpected internal error (database is locked)
1/1 Test #1482: TOPP_TargetedFileConverter_test_1_prepare ...***Failed    6.27 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   6.39 sec

The following tests FAILED:
        1482 - TOPP_TargetedFileConverter_test_1_prepare (Failed)
Errors while running CTest

**Comment by hroest** [comment]
are you using multiple threads?

**Comment by hroest** [comment]
PS: which sqlite version are you using? from contrib?

**Comment by jpfeuffer** [comment]
Still occurs?

**Comment by hroest** [comment]
hmm it is possible that you have a version less than 3.15? though cmake should check for that

```
find_package(SQLITE 3.15.0 REQUIRED)
```

**Comment by timosachsenberg** [comment]
That might be the case. Will check on monday

**Comment by timosachsenberg** [comment]
yep still have SQLITE 3.7
wonder why cmake did not complain

**Comment by hroest** [comment]
yes, it should, why else have the `REQUIRED`? so I guess the `find_package` is broken?

**Comment by jpfeuffer** [comment]
Hmm yes it seems a bit simple but I did not completely check it. The following seems to care about the version:
https://git.reviewboard.kde.org/r/105464/diff/1/download/71545/new/
BSD License

**Comment by hroest** [comment]
can Timo test it with his setup to check that it fails? if so, we can copy
it over (BSD licence)
