### ISSUE TITLE
Travis timeouts on QT5 branch

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2759]
It seems like the new Travis containers/machines are prohibitively slow.
Even by downloading a ready-made docker container lets us build maybe 20% of the library only.
Any ideas?

**Comment by hroest** [comment]
hmm not sure why we wont just use the solution from here with precise:

https://github.com/OpenMS/OpenMS/pull/2728

and I am sure we can use the "sourceline" cmd also to make it work in trusty? Or is there a specific need to use docker containers (except speed which apparently doesnt work out).

**Comment by jpfeuffer** [comment]
No. I even moved the docker stuff to a new branch now. Was only a try for speed.
Based on the outcome we can try to apply your suggestion.

**Comment by hroest** [comment]
yes, why not move the feature/qt5 branch back again to where it was before?

**Comment by jpfeuffer** [comment]
that's what I did. moved my commits to feature/qt5-docker in case we want to try something similar in the future.

**Comment by hroest** [comment]
so I guess this is not really a blocker any more ...
