### ISSUE TITLE
AccurateMassSearch cannot write output file (regression)

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2783]
I've just updated OpenMS in KNIME and found that the AccurateMassSearch node in an existing workflow doesn't work anymore. The output in the KNIME log was:
> ERROR AccurateMassSearch   0:16       Failing process stdout: [Read 54 entries from mapping file!, Read 1 entries from adduct file 'C:\Users\hendrik.weisser\Data\Nucleotide-MS\pos_adducts.tsv'., Read 15 entries from adduct file 'C:\Users\hendrik.weisser\Software\OpenMS\share\OpenMS\CHEMISTRY\NegativeAdducts.tsv'.]
> ERROR AccurateMassSearch   0:16       Failing process stderr: []
> ERROR AccurateMassSearch   0:16       Execute failed: Failed to execute node AccurateMassSearch

So no useful information.

I then updated my local OpenMS installation and tried AccurateMassSearch there. I got the following (weirdly worded) error:
> Error: Unable to write file (the file 'While storing 'Search\results.csv'. Invalid file extension. Should be: 'tsv'' could not be created)

If I try to write to an output file with ending ".tsv", I get this instead:
> Invalid parameter: Invalid output file extension 'Search\results.tsv'. Valid file extensions are: 'csv'.

So it seems that two different parts of the code can't agree on what the file extension should be.
(Using ".tmp" as the extension makes it work on the command line - which is also why the test still works! However, that doesn't help with KNIME.)

I'm going to prepare a fix on the OpenMS side. For KNIME, it would be good to know why the error message from the tool doesn't appear anywhere. (I'm assuming the failure in KNIME is caused by the same bug - any way I can test that?)

**Comment by timosachsenberg** [comment]
maybe related to my change that forces checks of file extensions?

**Comment by hendrikweisser** [comment]
> maybe related to my change that forces checks of file extensions?

Yep! See PR #2784.
