### ISSUE TITLE
Percolator requires system library

### ISSUE THREAD

**Issue by Leon-Bichmann** [OpenMS/OpenMS#2800]
Building OpenMS 2.2 on our cluster results in the following error trying to run percolator:

percolator: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by percolator)

**Comment by jpfeuffer** [comment]
I guess you need a newer compiler. It was probably with a newer one than what's on the cluster.

**Comment by jpfeuffer** [comment]
Of course you could also built Percolator on your own and add that more compatible version to the THIRDPARTY instead. I think we used the downloaded ones.

**Comment by Leon-Bichmann** [comment]
Ok, the complier was gnu4.9

**Comment by jpfeuffer** [comment]
Hmmm.. sounds like it should have 2.14.

**Comment by jpfeuffer** [comment]
Which Linux?

**Comment by Leon-Bichmann** [comment]
Scientific Linux 6.6

**Comment by jpfeuffer** [comment]
Hmm.. well the Percolator  executable is built for Ubuntu.

**Comment by jpfeuffer** [comment]
Maybe we should switch to the CentOS binary in general. It has a much lower GLIBC dependency. Works on my Debian, too.

**Comment by hroest** [comment]
this is anyways a good idea since projects like manylinux also need to work on CentOS 5 - so having OpenMS compile there would be great

**Comment by lukaszimmermann** [comment]
PR with alternative executable for Linux open.

**Comment by jpfeuffer** [comment]
Should be fixed with https://github.com/OpenMS/THIRDPARTY/pull/15. Thanks

**Comment by hroest** [comment]
@jpfeuffer in case you are interested, I have a CentOS 5 version with gcc 4.8 running here - I think whatever we build here should run anywhere (it was literally designed for that purpose). I installed all the contrib and qt 4.8 on it:

https://hub.docker.com/r/hroest/manylinux_qt_contrib/
