### ISSUE TITLE
Problems with Linux (Ubuntu 16.04) build instructions

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2803]
I just finished installing OpenMS on a fresh Ubuntu 16.04.2 LTS system. Following the build instructions [here](http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/install_linux.html), I noticed the following discrepancies:
1. In the "list of required packages and libraries", for "Ubuntu/Debian (>= 16.04 <= 16.10)", instead of "libsvn-dev libgsl-dev", it should say "libsvm-dev libglpk-dev".
2. The new SQLite dependency is not listed. Installing the "libsqlite3-dev" package worked.
3. The WildMagic version installed via the "libwildmagic-dev" package (5.13) didn't work. (The build instructions say: `# use from contrib for compatibility: ... WILDMAGIC`, but they also list the WildMagic package as to be installed.) I got compilation errors during the `make` step for OpenMS:
```
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Read(unsigned long, void*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Write(unsigned long, void const*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::~FileIO()'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Close()'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::operator bool() const'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Write(unsigned long, int, void const*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::FileIO(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libWm5Mathematics.so: undefined reference to `Wm5::FileIO::Read(unsigned long, int, void*)'
collect2: error: ld returned 1 exit status
src/openms_gui/CMakeFiles/TOPPAS.dir/build.make:114: recipe for target 'bin/TOPPAS' failed
make[2]: *** [bin/TOPPAS] Error 1
```
After removing the package and building the contrib version, I had to change the "WM5_INCLUDE_DIR" in the OpenMS CMake settings. Note that "WM5_INCLUDE_DIR" wants the subdirectory ("WildMagic"), while "SEQAN_INCLUDE_DIR" doesn't! (I removed the "CMakeCache.txt" file and "CMakeFiles" folder and ran `cmake -DOPENMS_CONTRIB_LIBS=...` again to update the WildMagic settings. So this shouldn't be a problem if the contrib version is used from the beginning.)

After that, it worked!

**Comment by jpfeuffer** [comment]
Can confirm. Updated the documentation. Maybe we can try full apt-get builds at some point.
Seqan should be available too in 1.4 now. Also coinor is theoretically available.

**Comment by hroest** [comment]
This is a known bug and only fixed in 16.10 and higher: https://bugs.launchpad.net/ubuntu/+source/libwildmagic/+bug/1578222 it seems they forgot to link the libraries...

> After removing the package and building the contrib version, I had to change the "WM5_INCLUDE_DIR" 

sometimes these values are cached and you need to delete the build folder and start from scratch if you change anything its generally a good idea to make a clean start with cmake

@jpfeuffer we should make sure our build instructions are mirrored with https://github.com/OpenMS/dockerfiles as these docker files for sure are tested and work. Maybe we can even link from the docu to the docker files?

**Comment by hroest** [comment]
@hendrikweisser from 17.04 we should be able to get everything from the package manager again: https://github.com/OpenMS/dockerfiles/blob/master/contrib/Dockerfile-bleeding

**Comment by hendrikweisser** [comment]
Thanks for updating the documentation, Julianus. How/when is that going to be reflected on the FTP server (http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/install_linux.html)?

Can we unify whether the "..._INCLUDE_DIR" settings point to "include" or to the subdirectory in it?

**Comment by hroest** [comment]
@jpfeuffer I thought that the ftp server gets updated nightly with the newest docu? did that happen here?

**Comment by hroest** [comment]
@jpfeuffer @timosachsenberg why does the server at http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/install_linux.html not get updated nightly doc-builds any more?

**Comment by jpfeuffer** [comment]
Migrated to https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/index.html
Only updated if nightlies are successful. Also access via openms.de/develop-doxygen/
or redirect from old FU.
