### ISSUE TITLE
Travis timeouts

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2815]
We could address the travis timeouts by using the caching system smartly:

- they offer directory cache
- they offer `ccache`

https://docs.travis-ci.com/user/caching/

**Comment by hroest** [comment]
currently with ccache I can get the gcc builds down to 10 minutes: https://travis-ci.org/OpenMS/OpenMS/builds/259547633

**Comment by hroest** [comment]
@timosachsenberg @jpfeuffer we are now getting regular travis timeouts for clang builds, so there is a real question how useful these builds really are for us

**Comment by jpfeuffer** [comment]
We have pyopenms builds from a docker file now. Maybe we can substitute one travis gcc run with a clang run. And maybe we can add a debug build in travis? or do you expect timeouts?
see #3246

**Comment by hroest** [comment]
I looked at debug builds a few times but in my hands they create timeouts. You can try again, but already now we have trouble with the release builds if we have to start from scratch and cant use ccache
