### ISSUE TITLE
OpenMS on macOS Sierra not working

### ISSUE THREAD

**Issue by koenvanderdrift** [OpenMS/OpenMS#2816]
I'm trying to run OpenMS on macOS 10.12.6 - I have not used it before, so cannot say if this happens with older versions of the OS or OpenMS as well.

I am using the OpenMS 2.1.0 binary, and added these two lines in my .bash_profile:

`export OPENMS_TOPP_PATH=/Applications/OpenMS-2.1.0`
`source $OPENMS_TOPP_PATH/.TOPP_bash_profile`

When I double-click TOPPAS, nothing happens, if I go to the Mac console, I see this error message:

`Jul 31 19:31:56 MacBook-Pro-13-inch-Late-2011 com.apple.xpc.launchd[1] (de.openms.TOPPAS.50172[89269]): Service exited with abnormal code: 1
`

I can run TOPP Shell, and OpenMSInfo gives me:

OpenMS Version:
==================
Version      : 2.1.0
Build time   : Nov 22 2016, 02:03:13
Git sha1     : f755ffe
Git branch   : heads/Release2.1.0

Installation information:
==================
Data path    : /Applications/OpenMS-2.1.0/share/OpenMS
Temp path    : /var/folders/b_/ct449q_j6tbd4xvpjw79bg8w0000gp/T
Userdata path: /Users/koenvanderdrift/

Build information:
==================
Source path  : /Users/aiche/NIGHTLY/RELEASE/src/openms
Binary path  : /Users/aiche/NIGHTLY/builds/RELEASE/release2.1.0-mac-osx-10.8-clang-5.0-LLVM3.3svn-Unix_Makefiles-Release/src/openms

OS Information:
==================
Name: MacOS
Version: 10.12.6
Architecture: 64bit

Has anyone had any luck with running OpenMS on macOS Sierra?

Any assistance appreciated, thanks.

**Comment by koenvanderdrift** [comment]
Additional info: I am using the OpenMS 2.1.0 binary, and added these two lines in my .bash_profile:

`export OPENMS_TOPP_PATH=/Applications/OpenMS-2.1.0`
`source $OPENMS_TOPP_PATH/.TOPP_bash_profile`

**Comment by hroest** [comment]
have you tried starting TOPPAS from the TOPP commandline? we have had issues with OSX blocking TOPPAS as it is not signed with a valid apple key

**Comment by koenvanderdrift** [comment]
Yes, that works. Thanks!

**Comment by jpfeuffer** [comment]
Also fixed in upcoming versions. See #2488. But only in the inofficial nightly installers, yet.
