### ISSUE TITLE
RNPXL Tests failing in nightlies on macOS

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2828]
https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_nightly_packaging/compiler=appleclang-7.3.0,os_label=elcapitan/lastCompletedBuild/testReport/

**Comment by jpfeuffer** [comment]
Because of fragment annotation changes.

**Comment by jpfeuffer** [comment]
Could be set ordering issues.

**Comment by jpfeuffer** [comment]
Still not fixed on Linux gcc4.8
nightly branch, sha 52ce45bd334514bb17144032b0b5009a6cd5d148

**Comment by jpfeuffer** [comment]
Labelled it blocker because I want to enforce test error free nightly packages before the release.

**Comment by timosachsenberg** [comment]
passes on my gcc 4.8.5

**Comment by timosachsenberg** [comment]
when I cklick on https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_nightly_packaging/compiler=appleclang-7.3.0,os_label=elcapitan/lastCompletedBuild/testReport/ I don't see it failing. Am I looking in the wrong spot?

**Comment by jpfeuffer** [comment]
Yes now it only fails on linux. https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_nightly_packaging/compiler=g++-4.8,os_label=ubuntu_1404/lastCompletedBuild/testReport/
