### ISSUE TITLE
autowrap issues not captured in cdash

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2835]
We had an error in autowrap and the output of the Python script is not captured by cdash:

http://cdash.openms.de/index.php?project=OpenMS&date=2017-08-07 -- see travis-ci-OpenMS_OpenMS-fix_debug_py-265573a037ac...37272cc3ff24-clang++-noGUI info

cdash output is only the following C++ compilation and its errors:

```
clang: error: no such file or directory: 'pyopenms/pyopenms_1.cpp'
```

and you have to change tools/travis/lnx-cibuild.sh to see what is wrong: https://travis-ci.org/OpenMS/OpenMS/jobs/262024145

It would be nice if these errors were also reported in cdash

**Comment by jpfeuffer** [comment]
Any idea on how to do that best?

**Comment by hroest** [comment]
we generally have problems to capture pyOpenMS build problems in cdash, this week we just had issues where we thought that the build timed out but actually there was an error. Not sure how to approach this - maybe we could run it on jenkins?

**Comment by hroest** [comment]
it now works through the docker container, but there are still issues in travis which reports warnings as errors
