### ISSUE TITLE
Rework checker script [284]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#284]
Submitted by aiche on 2011-03-04 17:23:10

The checker script needs some redesign, like 
- switch from line based parsing to regular expressions
- use xml ([http://public.kitware.com/Wiki/CDash:XML Dart format]) as output to be able to visualize test results in CDash
- ... 

ideas should be collected in this ticket

---

Commented by aiche on 2011-03-04 17:25:50:
just some ideas; CTEST_TEST macro can be overwritten and the parameter can be used to pass the user name to the checker (user specific checker results in cdash)

**Comment by jpfeuffer** [comment]
The checker uses XML output by now. Are the features sufficient? Do people look at the checker in the nightlies?

**Comment by timosachsenberg** [comment]
I think this can be closed.

**Comment by jpfeuffer** [comment]
I think so too. User-specific checking is not used anyway. The rest seems to be solved by now.
