### ISSUE TITLE
Website: add publications

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2848]
It would be great if my last two OpenMS-related papers could be added to the list on the website (http://www.openms.de/publications/):

- https://www.ncbi.nlm.nih.gov/pubmed/27786492
- https://www.ncbi.nlm.nih.gov/pubmed/28673088

Could they also be linked on the relevant workflow pages, please?
- for the first: http://www.openms.de/workflow/proteogenomics/
- for the second: http://www.openms.de/workflow/targeted-feature-detection-for-lfq/

(Also, please fix formatting of the "í" in "Vizcaíno" in the current top entry of the publications list.)

**Comment by jpfeuffer** [comment]
@timosachsenberg Can you add this to our google scholar and export the bib files, then I put it on the website.

**Comment by timosachsenberg** [comment]
Ok here it is:
https://gist.github.com/anonymous/ac5cc2627b54f56731261c7ab9e14215

**Comment by jpfeuffer** [comment]
@hendrikweisser How are you envisioning the linking? Is the ncbi link on the workflow page enough? Or do you want the bibtex to show up there?

**Comment by jpfeuffer** [comment]
By the way @timosachsenberg.  The deNBI paper is missing, too.

**Comment by timosachsenberg** [comment]
damn...

**Comment by jpfeuffer** [comment]
I added it to the website bib. But it needs to go to Gscholar (and potentially to the current deNBI reports ;) )

**Comment by jpfeuffer** [comment]
Otherwise. Finished here.
