### ISSUE TITLE
Canceling dialog during loading of files [285]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#285]
Submitted by cbielow on 2011-03-07 14:26:40

when a large file is opened TV cannot be stopped while loading is in progress.
Loading might be too slow, so the user would like to cancel - it might even lead to out-of-memory for certain files.

The loading dialog should have a cancel-button and loading should stop if its used.

---

Commented by timosachsenberg on 2011-04-07 17:05:14:
OpenMS XML file handling doesn't support abort so there is no quick fix for this.

**Comment by hroest** [comment]
#3401 is related
