### ISSUE TITLE
pyopenms install error with Anaconda v2.7 Python

### ISSUE THREAD

**Issue by tantrev** [OpenMS/OpenMS#2869]
When trying to install pyopenms on a Python v2.7 installation (Anaconda - Mac OS v10.12.6 or Windows 2008 R2 Server Enterprise) via pip with the following commands:

```
pip install env
pip install six pandas protobuf pymspec pyopenms
```

the following error results:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b5/s8ym8f_51816vv4gyxk0v7_c0000gn/T/pip-build-ZWze9x/pyopenms/setup.py", line 9, in <module>
        from env import  (OPEN_MS_SRC, OPEN_MS_BUILD_DIR, OPEN_MS_CONTRIB_BUILD_DIRS,
    ImportError: cannot import name OPEN_MS_SRC
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/b5/s8ym8f_51816vv4gyxk0v7_c0000gn/T/pip-build-ZWze9x/pyopenms/
```

Any idea what's going wrong?  Thank you in advance.

**Comment by tantrev** [comment]
For what it's worth, only installing with the latest pyopenms causes the issue.  Everything goes smoothly when the following command is used:

```
pip install pyopenms==2.0
```

**Comment by grosenberger** [comment]
We did have problems with the macOS 2.1 and 2.2 builds and are working on a fix. Could you please try the development wheel from https://github.com/OpenMS/OpenMS/pull/2821 and let me know whether it worked? We will then upload the 2.2 builds to PyPI.

**Comment by tantrev** [comment]
That did the trick for my mac, thank you!  Unfortunately, the Windows version with Python v2.7 still doesn't seem to work on Windows 2008 R2 Server Enterprise (same ImportError as above).  It seems that most of the current wheels for Windows are only for Python v3?

**Comment by hroest** [comment]
Sorry to hear about your troubles, a few points

- yes, Python 2.x support is discontinued as this is technically impossible with newer versions of OpenMS (switch to C++11)
- we will also only support 64bit architecture from 2.2 onwards

can you let us know whether you are using a 32bit or 64bit system? can you test with which versions the error occurs:
```
pip install pyopenms==2.1.0
pip install pyopenms==2.0.1
pip install pyopenms==2.0.0
```

**Comment by tantrev** [comment]
Thank you both for the kind help, @hroest and @grosenberger.

The following commands are successful on my Mac's 64-bit v2.7 python installation (from Anaconda):
```
pip install pyopenms==2.0.0
pip install pyopenms==2.1.0
```
This command is unsuccessful:
```
pip install pyopenms==2.0.1
```
returning the following error:

> Collecting pyopenms==2.0.1
>   Could not find a version that satisfies the requirement pyopenms==2.0.1 (from versions: 1.11, 2.0, 2.1.0a0, 2.1.0, 2.2.0)
> No matching distribution found for pyopenms==2.0.1

Thanks also for the heads-up about the discontinuing v2.7 python support - I was just been trying to maintain compatibility with [Optimus](https://github.com/MolecularCartography/Optimus).

**Comment by hroest** [comment]
@tantrev any chance that Optimus will also be available for Python 3.x in the future?
