### ISSUE TITLE
Compile warnings [-Wdouble-promotion]

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#2876]
There are a lot of 
`warning: implicit conversion increases floating-point precision: 'IntensityType' (aka 'float') to 'double' [-Wdouble-promotion]` warnings related to `getIntensity()`, 

e.g.
```
OpenMS/src/openms/source/FORMAT/MSPFile.cpp:408:28: warning: implicit conversion increases floating-point precision: 'IntensityType' (aka 'float') to 'double' [-Wdouble-promotion]
            max_int = sit->getIntensity();
```

What is the reason that mostly float is used in the case of PEAK1D IntensityType instead of double? 

I can static_cast<> a few of those warnings, but I'm wondering if there is a better solution.

**Comment by hroest** [comment]
I think the reason is that somebody agreed that we would store intensity as 32bit float in mzML and thus the default data type would be flota (m/z is stored by defauly as 64bit double). I dont think we need 64bit accuracy for intensity, so it saves some space on disk and in memory.
