### ISSUE TITLE
X! Tandem version for release 2.3

### ISSUE THREAD

**Issue by lukaszimmermann** [OpenMS/OpenMS#2883]
For the 2.3 release, do we want to switch to X!Tandem ALANINE or rather stick with VENGEANCE? It might be the case that the XTandemAdapter might need to be adjusted, but I don't know yet.

**Comment by timosachsenberg** [comment]
I think it performed worse so we did not include it

**Comment by lukaszimmermann** [comment]
Ah, I think I remember the discussion. Then I guess  we stick with VENGEANCE.
