### ISSUE TITLE
missing C++11 compile flag

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#2897]
older but still supported compilers, namely g++ 4.8 and 4.9 require '-std=c++11' flag to be set, otherwise openms compilation will fail.
For g++ 5 this problem does not exist, since C11 is the default (g++ 6 even has C14).

We need to decide if we support g++ 4.8+ (and hence need the flag in cmake/compiler_flags.cmake)
or require g++ 5.x.
In any case, Linux install instructions need updating.

**Comment by hroest** [comment]
this is a very good point and we do need g++ 4.8 for a couple of things, among other the manylinux wheels that we build (see #2820) which are based on CentOS 5 - see here for a rationale: https://github.com/pypa/manylinux#docker-images this docker image provides g++ 4.8 as the default compiler

I think with g++ 4.8 we support all of C++11 (see https://gcc.gnu.org/projects/cxx-status.html "GCC 4.8.1 was the first feature-complete implementation of the 2011 C++ standard, previously known as C++0x.") but basically none of C++14

therefore :+1: for updating compiler_flags.cmake

**Comment by timosachsenberg** [comment]
I thought cmake would take care of this by requiring  c11?

**Comment by hroest** [comment]
yes, when looking at the actual code produced, this does indeed seem to be the case

**Comment by hroest** [comment]
Yes, this seems indeed to be the case, so I guess we do not need to change anything. I am testing on CentOS 5.11 right now to test this

$ make VERBOSE=1 OpenMS


[  4%] Building CXX object src/openms/CMakeFiles/OpenMS.dir/source/CONCEPT/Constants.cpp.o
cd /openms-build-cp27-cp27mu/src/openms && /opt/rh/devtoolset-2/root/usr/bin/c++  -DBOOST_ALL_NO_LIB -DOpenMS_EXPORTS -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -isystem /qt/include -isystem /qt/include/QtNetwork -isystem /qt/include/QtCore -I/OpenMS/src/openms/include -I/openms-build-cp27-cp27mu/src/openms/include -isystem /qt/include/QtDesigner -isystem /qt/include/QtXml -isystem /qt/include/QtSql -isystem /qt/include/QtOpenGL -isystem /qt/include/QtMultimedia -isystem /qt/include/QtXmlPatterns -isystem /qt/include/QtWebKit -isystem /qt/include/QtHelp -isystem /qt/include/QtUiTools -isystem /qt/include/QtTest -isystem /qt/include/QtSvg -isystem /qt/include/Qt3Support -isystem /qt/include/QtGui -isystem /qt/mkspecs/default -isystem /contrib-build/include -isystem /contrib-build/include/eigen3 -isystem /contrib-build/include/WildMagic -isystem /OpenMS/src/openswathalgo/include -isystem /openms-build-cp27-cp27mu/src/openswathalgo/include -isystem /OpenMS/src/openms/thirdparty/eol-bspline  -fopenmp  -O3 -DNDEBUG -fPIC   -Wall -Wextra -fvisibility=hidden -Wno-non-virtual-dtor -Wno-unknown-pragmas -Wno-long-long -Wno-unknown-pragmas -Wno-unused-function -Wno-variadic-macros --pedantic -fPIC -std=gnu++11 -o CMakeFiles/OpenMS.dir/source/CONCEPT/Constants.cpp.o -c /OpenMS/src/openms/source/CONCEPT/Constants.cpp

**Comment by hroest** [comment]
ok, I just tried building on CentOS 5.11 and it works perfectly, -std=gnu++11 gets added automatically for OpenMS (but not OpenSwathAlgo)
