### ISSUE TITLE
XMAn Mutated-Peptide database

### ISSUE THREAD

**Issue by kernursula** [OpenMS/OpenMS#2904]
I would like to use the XMAn mutated-peptide database (PMID: 25211293) in OpenMS workflows.
The header of the entries look like this: 
```>CANCER_sp_Q969R8,ITFG2_HUMAN Integrin-alpha FG-GAP repeat-containing protein 2|c.560C>T|p.S187L|DSLLVTL|Missense|COSMIC|Large intestine(1)```
Unfortunately peptide indexer doesn`t work with this kind of header. Is it possible to change the rules for  protein identifiers in the fasta database, so that for example the whole header would be considered as the protein identifier? 
Other ideas of how to work with this database are very welcome!

**Comment by zaidurrehman** [comment]
This [python script](https://github.com/ProteomicsScripts/ProteomicsScripts/pull/4) should modify the headers.

**Comment by cbielow** [comment]
the rules for parsing FASTA files are pretty universal. For the headers: Everything up the first (white)space character is the identifier, everything that follows is description.
This also applies to our parser.

So, if you want the whole header to serve as identifier, you can simply remove all spaces (e.g. replace by underscore or some special character). That should solve the problem.

**Comment by kernursula** [comment]
Thank you cbielow for the info. As a Biologist using OpenMS I think it would be very user friendly if there was an option to change the name parse rule if needed (in case you don`t have someone in the lab like zaidurrehman who can reformat a database)

**Comment by cbielow** [comment]
@kernursula The point is understandable, but exposing a parse rule only fixes a problem which should not be there in the first place, i.e. the identifier should tell everything relevant to the problem (algorithmically speaking). The database was clearly 'custom-made', so it should be possible to get it right or use the approach I suggested above.
The Maxquant community has a long and mixed-success story with custom identifier parse rules (using regular expressions). This led to a lot of confusion and wrong results, so I think its best to stick to the one universal rule: `>[identifier] [description] ` and everyone should be happy. (just my 50 cents)
