### ISSUE TITLE
Annotate peaks in an mzML file?

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2911]
In TOPPView it is possible to put annotations (labels) on individual peaks in a spectrum. Can such annotations be written to/read from mzML files? (In my tests using right click -> "Save" -> "Visible layer data" in TOPPView this didn't work.)

I would like to annotate peaks in MS2 spectra that match theoretical spectra of RNA sequences. Unfortunately I can't use the "Identification view" in TOPPView because idXML only supports peptide sequences.

(@timosachsenberg, @enetz: You've worked on this topic, do you have an answer?)

**Comment by timosachsenberg** [comment]
Hi Hendrik,
I think mzML is not primarily intended for this and a better solution would be to add support to our internal data structures and idXML. We sketched this some time ago in https://github.com/OpenMS/OpenMS/pull/1659

That being said - we are now supporting loading/storing/manual editing of fragment annotations using the fragment_annotation vector in PeptideHits. A quick hack would probably be to put the annotations in a dummy PeptideHit.
