### ISSUE TITLE
Support for absolute quantitation

### ISSUE THREAD

**Issue by dmccloskey** [OpenMS/OpenMS#2918]
Support absolute quantitation by e.g., IDMS

**Comment by dmccloskey** [comment]
dmccloskey is currently working on this issue.

**Comment by timosachsenberg** [comment]
I think I now gave you permission to assign yourself

**Comment by dmccloskey** [comment]
Cool.  Thanks!

**Comment by dmccloskey** [comment]
Is there a preference for small incremental PRs even if all methods for a class to add are not complete (i.e., the classes as is can currently support half of the quantitation workflow), or a large PR once everything is in place?

**Comment by hroest** [comment]
both work fine, but I prefer smaller PR as it is easier to discuss and potentially improve the direction of the work when we see it early on. It is much harder to rewrite a very large PR if we think it should have been implemented differently
