### ISSUE TITLE
AASequence doesn't provide getModification(Size index) [292]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#292]
Submitted by timosachsenberg on 2011-03-11 10:10:04

Looking at the getter/setter for modifications:
void    setNTerminalModification (const String &modification)
const String &  getNTerminalModification () const
void    setCTerminalModification (const String &modification)
const String &  getCTerminalModification () const
void    setModification (Size index, const String &modification)

AASequence should also provide:
const String &  getModification (Size index) const

---

Commented by hroest on 2012-09-18 11:46:40:
rather, we should provide a getModifications() function which returns all modifications, however the modifications are currently stored in the residues and need to be fetched from those...

**Comment by cbielow** [comment]
you can simply do `aa[index].getModification()`
