### ISSUE TITLE
StringView::substr API doesn't agree with String::substr and std::string::substr

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2920]
The second argument to `String::substr` and `std::string::substr` gives the length of the desired substring. In `StringView::substr`, the second argument is `end_index`, which gives the end position of the substring (undocumented whether it's at-the-end or past-the-end). If the starting position (first argument) isn't zero, then the semantics are different, which can lead to confusion.
`StringView::substr` should be changed to support the expected interface.

**Comment by timosachsenberg** [comment]
sounds reasonable. see also http://en.cppreference.com/w/cpp/string/basic_string_view/substr which eventually will replace our StringView
