### ISSUE TITLE
IDFileConverter - error with PeptideShaker mzident output

### ISSUE THREAD

**Issue by blankclemens** [OpenMS/OpenMS#2921]
Hello,

it seems like the mzidentML output from PeptideShaker can't be converted with `IDFileConverter` due to strings being used in value tags, I always get an error like the following:

```
Error: Unexpected internal error (Could not convert string 'Confident' to a double value)
```

`Confident` can be something different of course, in this case probably coming from

```
<cvParam cvRef="PSI-MS" accession="MS:1002540" name="PeptideShaker PSM confidence type" value="Confident"/>
```

in the mzid file.

Is this an error in the converter or should a mzid file never contain strings as values?

**Comment by Stortebecker** [comment]
I had the same problem, but only for `value="Not Validated"`, while `value="Confident"` and `value=""Doubtful"` in the same file did not throw errors.

**Comment by lars20070** [comment]
@blankclemens A similar example is given in the [`mzid` specification](https://github.com/HUPO-PSI/mzIdentML/blob/master/specification_document-releases/specdoc1_2/mzIdentML1%202.0-release.pdf) page 56. Looks like a bug on the OpenMS side.

@mwalzer Any comments?

**Comment by timosachsenberg** [comment]
@enetz Mathias is not easy to reach. Can you take a look at that?

**Comment by enetz** [comment]
@blankclemens  can you provide some more context, e.g. the position of this line in an mzIdentML file?
Assuming it is inside a `<SpectrumIdentificationItem` it is interpreted as a score.
It looks like OpenMS currently assumes all scores can be read as `double` numbers.
So this is not an issue for cvParams in mzIdentML in general but only for scores specifically.
This is where "search engine specific" scores are parsed:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp#L2032

If the cvParam is recognized as a "search engine specific score for PSMs" based on the accession, it is parsed as a `double` number,
otherwise it is ignored and not read at all.

A hack to make it work in the current OpenMS version would be to turn the keywords `Confident`, `Doubtful` etc. into a number scale and replace them in your files.

**Comment by blankclemens** [comment]
Yes, it is inside a `<SpectrumIdentificationItem>`.

Here is an example: https://gist.github.com/blankclemens/653d4180bf09a84fe9364fd9d28e9a28#file-sample-mzid-L88

> A hack to make it work in the current OpenMS version would be to turn the keywords Confident, Doubtful etc. into a number scale and replace them in your files.

Yes, that's working. If it could be part of the next release that'll be great though!

**Comment by hroest** [comment]
turns out the cv param is not guaranteed to be a number:

```
[Term] 
id: MS:1001143 
name: PSM-level search engine specific statistic
def: "Search engine specific peptide spectrum match scores." [PSI:PI]
is_a: MS:1002347 ! PSM-level identification statistic
```

so should we just look for these specific terms Confident, Doubtful etc and convert them to numbers in our parser?

**Comment by enetz** [comment]
I will do this for now, but this will mean, that post-processing tools will simply see it as another numerical score. I will also try to "keep track" of this conversion and convert back whenever another mzid file is written out again after a processing step.

I found this list of descriptions somewhere, is this the full list of expected terms?

1. `Confident`, score=2: validated confident matches.
2. `Doubtful`, score=1: doubtful matches, meaning proteins, peptide and PSMs that have passed the validation filter, but where the amount of evidence is low. For example a protein identified by only one validated peptide. 
3. `Not Validated`, score=0: matches that did not pass the statistical validation.

**Comment by Stortebecker** [comment]
@enetz Yes, only these three outputs are expected.

**Comment by mwalzer** [comment]
@hroest yeah, I'd say that this is actually a defect of the CV categorisations. I.g. I would expect a number behind a statistic, but the name 'type' hints differently. 
Adding a label or hierarchical dependence in the CV would mean we'd have to check for each cv param...
@enetz thanks for taking on the issue
@blankclemens @enetz I have my doubts about ```MS:1002540``` selected to be *the* score of our peptidehit in any case. I guess this was not intentionally (scoreswitcher)? All the other 'score' params get written into our metadata section (where this would not be a problem for reading or writing). And there should be a choice of others to be the score. Maybe the most **sustainable** solution would be to blacklist in the parser such cv params (e.g. w/o numbers) to be the score for our peptidehits. If no other cv param would be available to be the score that would fail the reading, but with good reason, I would not accept a PSM *just* with ```confident/doubtful/not validated```.

**Comment by enetz** [comment]
@mwalzer thanks for the explanation. This confidence level is not the main score in this case. I realized, that the whole problem is that we transform all the scores we store as metadata into `double` as well.

@blankclemens So if nobody is planning to do any statistics / maths / thresholding on these string confidence levels we may just read them in as strings.

@mwalzer would it be better to make a specific exception for this score, or should I just remove the `.toDouble()` call and read all secondary metadata scores as strings? I will try the latter first and see if it breaks any tests.

**Comment by blankclemens** [comment]
Sounds good to me, I don't use them for specific calculations - thanks a lot!
