### ISSUE TITLE
FalseDiscoveryRate filter option does not work for proteins

### ISSUE THREAD

**Issue by Stortebecker** [OpenMS/OpenMS#2942]
Hi.

I like the [filter option](https://github.com/OpenMS/OpenMS/issues/2531) added to FalseDiscoveryRate. However, I recognized that the output when filtering for 0.01 peptide FDR is not exactly the same as when filtering with IDFilter. 

Also, in my hands the FDR filtering on protein level does not work at all inside the FalseDiscoveryRate node. When I use the option `-FDR:protein 0.01`, I get the following error: `Error: File not found (the file '' could not be found)`.

Using OpenMS release v2.2 on Linux 64bit.

**Comment by timosachsenberg** [comment]
thanks for reporting.
Looking at the code again, it seems to directly call the IDFilter code if -protein "true" is passed and FDR:protein is set to a value < 1
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FalseDiscoveryRate.cpp#L168
Can you provide an example file and command line that triggers the error message?

**Comment by Stortebecker** [comment]
Hi.
Here is a [test file](https://gist.github.com/Stortebecker/66a19d6d614b82896f4875adddf55c60). Sorry for the size. 
I ran `FalseDiscoveryRate -in FidoAdapter_out.idxml -out output.idxml -protein true -FDR:protein 0.01`

**Comment by Stortebecker** [comment]
Interestingly, the FDR filtering on protein seems to start, but then it stops:
```
FDR control: Filtering proteins...
Error: File not found (the file '' could not be found)
```

**Comment by timosachsenberg** [comment]
ok tks I can reproduce the problem. will look into it

**Comment by timosachsenberg** [comment]
I also get the Segmentation Fault if I use -score:pep so it is most likely something going wrong during parsing...

**Comment by Stortebecker** [comment]
I do not get errors running FileInfo or IDFilter on that file:

````
IDFilter -in FidoAdapter_out.idxml -out output_IDFilter
Removing unreferenced protein hits...
Warning: While updating protein groups, some proteins were removed from groups that are still present. The new grouping (especially the group probabilities) may not be completely valid any more.
Before filtering:
1 protein identification(s) with 1357 protein hit(s),
3565 peptide identification(s) with 3565 peptides hit(s).
After filtering:
1 protein identification(s) with 1152 protein hit(s),
3565 peptide identification(s) with 3565 peptides hit(s).
IDFilter took 2.20 s (wall), 2.04 s (CPU), 0.00 s (system), 2.04 s (user).

**Comment by timosachsenberg** [comment]
Yes you ar right. After a clean rebuild that error disappeared

**Comment by mafreitas** [comment]
I am having the same issue (i.e. FDR filtering after fido)

stdio gives:
FDR control: Filtering proteins...
Error: File not found (the file '' could not be found)

The command I am using is:

docker run --rm -it -v /data:/data mfreitas/openms:2.3 FalseDiscoveryRate -in /data/work2/fido.idXML -out /data/work2/fido-fdr.idXML -protein true -FDR:protein 0.01 -debug 0 -threads 1

I am running the command in a docker container built from the nightly executables with thirdparty tools and pwiz binaries added.

Dockerfile
===============
FROM hroest/openms-executables-nightly
COPY pwiz/bin/ /tools/
WORKDIR /
ENV PATH="/openms-build/bin/:/tools/:${PATH}"

OpenMSInfo gives:

OpenMS Version:
==================
Version      : 2.3.0
Build time   : Nov  8 2017, 01:10:00
Git sha1     : b907ff19b7d7a881b5527daa94386f5819612943
Git branch   : HEAD-HASH-NOTFOUND

Installation information:
==================
Data path    : /OpenMS/share/OpenMS
Temp path    : /tmp
Userdata path: /root/

Build information:
==================
Source path  : /OpenMS/src/openms
Binary path  : /openms-build/src/openms
Binary arch  : 64 bit

OS Information:
==================
Name: Linux
Version: unknown
Architecture: unknown
