### ISSUE TITLE
Percolator discrepancies between Unix and Windows

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2950]
Seems like the results are just not comparable.
Versions:
Windows:
```
Percolator version 3.01, Build Date Nov 16 2016 08:43:34
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
```
Unix:
```
Percolator version 3.01, Build Date Jul 31 2017 10:51:02
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
```

We use fixed seeds in both cases.
We have to investigate.

**Comment by jpfeuffer** [comment]
Both versions are the newest for their platform by the way.

**Comment by jpfeuffer** [comment]
Problem is that results FDRs are quite different for all peptides.

**Comment by mwalzer** [comment]
Is this the same for from-source builds? (I have never compiled percolator on windows :no_mouth: but maybe their release build sources are differing somehow)
Can you post the seed input?

**Comment by jpfeuffer** [comment]
I was thinking that too. We probably have to build ourselves to check.
Seed should be = 1 according to the test inis.

**Comment by hroest** [comment]
does the *number* of results also vary or just the FDR values. Maybe we can ask @MatthewThe and he may have some insight into the differences between the builds

**Comment by MatthewThe** [comment]
We have slightly different numbers of PSMs and peptides at 1% FDR on windows and unix for our own test sets as well. As far as I remember, it's because windows and unix floating point operations are slightly different, also depending on the optimization compilation flags, though we haven't investigated this in much detail. How big are the differences for you?

**Comment by MatthewThe** [comment]
We think we found the reason for the discrepancy now. There was a bug in the pseudo random number generation on Windows. We pushed the fix to the percolator master branch, but for the moment there is no official release with binaries available for it.

**Comment by jpfeuffer** [comment]
Thanks a lot for keeping us uptodate. I think we will disable the test with a warning until we update our thirdparties (either selfbuilt or with your new release). See #3028

**Comment by jpfeuffer** [comment]
We have an own percolator build in the thirdparties now.
