### ISSUE TITLE
Request by tool provider - citations 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2955]
Display a Message in cmdline and knime on what to cite

**Comment by cbielow** [comment]
so on cmdline we go for the NMeth Paper? Gui tools usually have a separate help window, so no need to mention TOPPView/TOPPAS on cmd.
I can prepare a PR...

**Comment by timosachsenberg** [comment]
cool tks. Also for the third-party tools if possible.

**Comment by jpfeuffer** [comment]
Where should we put that in KNIME?

**Comment by hroest** [comment]
if possible, yes

**Comment by timosachsenberg** [comment]
can this be put into the node configuration dialog? e.g. at the top?

**Comment by jpfeuffer** [comment]
Ok possible. Do we already write the citations to the CTD?
Which citations do we add in the Adapters? The underlying tool or OpenMS or both?

**Comment by jpfeuffer** [comment]
Our TOPPBase class should probably have OpenMS as a citation in a member and we should provide a way to add to this citation in the derived classes.

**Comment by jpfeuffer** [comment]
I'm preparing a PR for the GKN to support the citation tag of the CTD and display it in the config dialog.

**Comment by timosachsenberg** [comment]
I would say the underlying tool
