### ISSUE TITLE
Fragment annotations also applied in precursor isolation window view (MS1)

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2957]
![image](https://user-images.githubusercontent.com/5803621/31672264-5ec5cdb0-b35c-11e7-94d7-c0d2eaf8200d.png)

**Comment by enetz** [comment]
@timosachsenberg 
I cannot reproduce this with the current develop branch version and my own data.
What are the conditions under which this happens?
I think the mz tolerance for mapping annotations onto peaks is very stringent (1e-6) and the chance that MS2 annotations can be mapped onto peaks in MS1 is very low (if that is what is happening here).
I could not reproduce this even with precursor peaks that have the same theoretical mass in MS2 and the corresponding MS1.

Do you have any example files?
When is this a bug and when is this a feature? :) 
I guess if it would only map annotations that make sense, e.g. precursor masses, it might be considered a feature. But what are the chances it maps an annotation that is actually wrong? Maybe these ions are seen in the MS1?

I confirmed that manually adding MS1 peak annotations works, but those are not written to idXML.

**Comment by timosachsenberg** [comment]
Thanks for looking into that. I don't know the details but just got the screenshot - I guess we need access to the original idXML and raw data.

I would say that fragment annotations should not be used to annotate MS1 peaks.

Lets keep it open for now and see if we get more data on that.

**Comment by hroest** [comment]
> I would say that fragment annotations should not be used to annotate MS1 peaks.

but it would be nice to have precursor annotations :-)

**Comment by timosachsenberg** [comment]
hehe yes that is true... I think we need to add this to Precursor.h and add support in TOPPView
