### ISSUE TITLE
MetaProSIP in KNIME: R error

### ISSUE THREAD

**Issue by scouvy** [OpenMS/OpenMS#2982]
Hi,
I am trying to get a workflow working for MetaProSIP in KNIME. The MetaProSIP node fails to execute with this error, although I have R installed in my computer and have added it to the system path variable. Any suggestions? 
Also, is there a workflow available for MetaProSIP in KNIME that I can download? It would be very useful to have that for new users to be able to use the software.

ERROR MetaProSIP           0:7        Failing process stdout: [Checking R... failed, There was a problem detecting R and/or of one of the required libraries. Make sure you have the directory of your R executable in your system path variable., MetaProSIP took 0.02 s (wall), 0.02 s (CPU), 0.02 s (system), 0.00 s (user).]
ERROR MetaProSIP           0:7        Failing process stderr: [Can't execute R. Do you have R installed? Check if the path to R is in your system path variable.]
ERROR MetaProSIP           0:7        Execute failed: Failed to execute node MetaProSIP

**Comment by timosachsenberg** [comment]
Hi,
I manually set the R executable in the MetaProSIP node to the R.exe on your computer and it worked for me. Just add an Input File node, add the executable in it, and connect it to the port 3 of MetaProSIP.
![image](https://user-images.githubusercontent.com/5803621/32166929-a6b883aa-bd67-11e7-8c18-c56177de39ce.png)
I will put together the workflow and upload it...

**Comment by scouvy** [comment]
Hi Timo,

Thanks for responding. Yes that did fix the R problem. I am attaching my workflows that I am trying to use for analyzing data with MetaProSIP. First , I create a decoy database from the fasta which I then use in the input file (node 12). I enter a single mzml file (unable to input multiple-gives an error) in Input files (node 8).
After I resolved the R error, the MetaProSIP node still does not run. The error is,

ERROR MetaProSIP           0:7        Failing process stdout: [Checking R... success, Checking R dependencies. If package is not found we will try to install it in your temp directory... success, loading sequences..., loading feature map..., Error: Unable to read file (While loading 'C:\Users\couv810\AppData\Local\Temp\40\knime_ MetaProSIP21288\knime_fs-IDMapper-21295\000\000\IDMapper_0\HLP_SIP_13C_AceBT4_01_21May14_Tiger_14-03-03.featureXML': Unexpected UserParam in tag 'consensusXML', Probable cause: The file suffix (featureXML) does not match the file content (consensusXML). Rename the file to fix this. in: C:\Users\couv810\AppData\Local\Temp\40\knime_ MetaProSIP21288\knime_fs-IDMapper-21295\000\000\IDMapper_0\HLP_SIP_13C_AceBT4_01_21May14_Tiger_14-03-03.featureXML)]
ERROR MetaProSIP           0:7        Failing process stderr: [..\..\..\OpenMS\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(103): While loading 'C:\Users\couv810\AppData\Local\Temp\40\knime_ MetaProSIP21288\knime_fs-IDMapper-21295\000\000\IDMapper_0\HLP_SIP_13C_AceBT4_01_21May14_Tiger_14-03-03.featureXML': Unexpected UserParam in tag 'consensusXML', Probable cause: The file suffix (featureXML) does not match the file content (consensusXML). Rename the file to fix this.]
ERROR MetaProSIP           0:7        Execute failed: Failed to execute node MetaProSIP

I tried changing the name of the file to have a .consensusXML extension but that did not work either. Is there a parameter I must change in the IDMapper node or the MetaproSIP node?
Also, any suggestions on what I can do to process multiple mzmL files instead of one?

Thanks,
Sneha

**Comment by jpfeuffer** [comment]
Hi Sneha,

I am not familiar with MetaProSIP but it could be that you have to set the output type of the IDMapper to consensusXML.
Doubleclick on IDMapper, switch the tab in the upcoming config dialog to OutputTypes and use the dropdown menu to set it to consensusXML.

**Comment by scouvy** [comment]
Tried that but did not work. MetaProSIP node input port 2 is specified as: Feature data annotated with identifications (IDMapper) [featureXML]

**Comment by timosachsenberg** [comment]
Hi, can you contact me via the email address on: https://abi.inf.uni-tuebingen.de/People/sachsenb
I can send you the workflow (github doesn't seem to like the upload here)
