### ISSUE TITLE
ProteinInference and FidoAdaptor from Percolator output not working

### ISSUE THREAD

**Issue by thinkle12** [OpenMS/OpenMS#2983]
Hello, my name is Trent and I have been attempting to use OpenMS in Knime as well as the command line package to do Protein Inference on results from Percolator.

In regards to the ProteinInference class, when I run my analysis it outputs the same protein score for every protein an example protein entry looks as follows:
```
<ProteinHit id="PH_35864" accession="Q9Y452_HUMAN|Q9Y452" score="0.519702911376953" coverage="17.9775280898876" sequence="SHSMRYFYTSVSRPGRGEPRFISVGYVDDTQFVRFDSDAASPREEPRAPWIEQEGPEYWDRNTQIYKTNTQTYRESLRNLRGYYNQSEA" >
				<UserParam type="string" name="target_decoy" value="target"/>
				<UserParam type="float" name="_score" value="0"/>
			</ProteinHit>
```
Where, score="0.519702911376953" is the same for every protein.

My workflow is as follows:
Run percolator, generate tab delimited output of targets and decoys. 

[peg10pepscombinedd.psms.zip](https://github.com/OpenMS/OpenMS/files/1423657/peg10pepscombinedd.psms.zip)

I take this file and run:
`IDFileConverter -in peg10pepscombinedd.psms  -out peg10combined.idxml`

output is then:
[peg10combined.idxml.zip](https://github.com/OpenMS/OpenMS/files/1423658/peg10combined.idxml.zip)

With this file I run the following Knime Workflow
with the input files to peptide indexer being  "peg10combined.idxml" and the following database:
https://nofile.io/f/A2C0fkcN9to/UniprotKBConcat1708_HUMAN-reformatted.fasta

![knimeproteininferenceworkflow](https://user-images.githubusercontent.com/5289095/32128211-e502fc3c-bb30-11e7-8c47-0bee52db638a.jpg)

PeptideIndexer has the following params:
![peptideindexerparams](https://user-images.githubusercontent.com/5289095/32128301-8cd44b6e-bb31-11e7-99b3-d14b330c2d84.jpg)

FalseDiscoveryRate has the following params:
![falsediscoveryrateparams](https://user-images.githubusercontent.com/5289095/32128308-98d41688-bb31-11e7-8b40-5090554f0609.jpg)

IDPosteriorErrorProbability has the following params:
![idposteriorerrorprobabilityparams](https://user-images.githubusercontent.com/5289095/32128309-9bc139ca-bb31-11e7-9ea9-476309dc31a4.jpg)

ProteinInference has the following params:
![proteininferenceparams](https://user-images.githubusercontent.com/5289095/32128312-9f330c6e-bb31-11e7-8193-1c8dbcc6bada.jpg)

FidoAdaptor has the following params:
![fidoadaptorparams](https://user-images.githubusercontent.com/5289095/32128320-a52a3dea-bb31-11e7-90e7-c6066de08252.jpg)

Output of Protein Inference is:
[peg10combined.idXML.zip](https://github.com/OpenMS/OpenMS/files/1423697/peg10combined.idXML.zip)
Proteins all receive the same score. And I am not sure what to make of this?

As far as the fido results I get the following error:
```
ERROR FidoAdapter          3:14       Failing process stdout: [Reading input data..., Protein identification run 1:, Generating temporary files for Fido..., Error: Unexpected internal error (Error: Unsuitable score type for peptide-spectrum matches detected (problem: lower scores are better)., Fido requires probabilities as scores, e.g. as produced by IDPosteriorErrorProbability with the 'prob_correct' option.)]
ERROR FidoAdapter          3:14       Failing process stderr: [Error: Unsuitable score type for peptide-spectrum matches detected (problem: lower scores are better)., Fido requires probabilities as scores, e.g. as produced by IDPosteriorErrorProbability with the 'prob_correct' option.]
ERROR FidoAdapter          3:14       Execute failed: Failed to execute node FidoAdapter
```

In regards to the FidoAdaptor in the Knime node, do we need a local installation of Fido? I currently do not have an installation but I also do not see an option in the parameters to point to an installation?

The Fido error seems weird to me as I definitely run IDPosteriorErrorProbability with 'prob_correct' as true.

I am not really sure where to go forward with this. Any help would be much appreciated.

**Comment by jpfeuffer** [comment]
Hi,

The problem is, that if you execute PosteriorErrorProbability after FDR, it tries to calculate PEPs based on the q-values instead of the searchengine scores.
Can you remove the FDR tool?
And the ProteinInference tool does not assign meaningful scores to proteins since it just uses rule-based binary protein inference (not recommended).
