### ISSUE TITLE
Support for HPLC (UV/RI) and GC-MS data processing

### ISSUE THREAD

**Issue by dmccloskey** [OpenMS/OpenMS#2984]
@hroest and @timosachsenberg What are your thoughts on how best to add in support for general HPLC and GC-MS data processing.  As I see it, If it would be possible to modify the OpenSwath workflow so that it can work with MS1 data (without a MS2 data can) and generalize precursor mass to UV wavelength, RI frequence, etc., this should be possible.

**Comment by hroest** [comment]
I have never worked with GC data myself but we can for sure adopt the workflow. I think it sounds interesting but I would first need some education in the data structure and the questions we can ask of the data. Is it also mzML data? 

Currently, OpenSWATH already supports MS1 only workflows (there is an ms1only option) but I dont think we have any of the other suggested options (UV, RI etc). We also have the FeatureFinderIdentification by @hendrikweisser that has proven to work well for peptides

**Comment by timosachsenberg** [comment]
@oliveralka I think you gained some initial experience with GC MS and conversion of files. Would be great to add this information here.

**Comment by dmccloskey** [comment]
We are able to use either proteoWizard to convert it the files to mzML or the onboard vendor conversion tool to export the data as mzXML and then to mzML using proteoWizard.  All of the data appears to be retained in the conversions.

**Comment by dmccloskey** [comment]
OK thank you for that tip.  Most of our GC-MS instruments are unit resolution, but we operate them in both SRM mode and full scan mode.  For quantitation in full scan mode, we take ratios of product ion.

**Comment by hroest** [comment]
so you want to use the same OpenSWATH tools for data analysis of GC MS data? Or do you want to use untargeted feature finders? Maybe we can schedule a Skype call?

**Comment by dmccloskey** [comment]
The former (i.e., use OpenSWATH for data analysis).  Pasquale is currently working on a feature that will add in support for DIA and DDA https://github.com/biosustain/OpenMS/tree/feature/SpectrumExtractor.  This will allow for quantitative flux analysis by LC-MS/MS and with a bit of help, quantitative metabolomics analysis and flux analysis by GC-MS.

**Comment by dmccloskey** [comment]
We can definitely discuss more on Skype if that works for you.  What is your availability?

**Comment by hroest** [comment]
@dmccloskey @biosustain @pasqoo I would love to talk on Skype about the branch and the requirements. I remember that I once had some questions about GC-MS and correlation profiling - I even have some code for this. I would like to understand what `SpectrumExtractor.h` is doing. This week is not great as I am at a conference, so next week would be better for me.

**Comment by dmccloskey** [comment]
Next week should work.  What time zone are you in now?

**Comment by hroest** [comment]
lets discuss via email

**Comment by dmccloskey** [comment]
#2999 adds in support for GC-MS SRM conversion.  #3029 will add in python support for conversion.
