### ISSUE TITLE
OpenMS only allows limited control over TMPDIR

### ISSUE THREAD

**Issue by BioWu** [OpenMS/OpenMS#2995]
Hi,
  I built the OpenMS (2.2.0)
```
Installation information:
==================
Data path    : /home/xxx/software/OpenMS-2.2.0/share/OpenMS
Temp path    : /tmp
Userdata path: /home/xxx/
```

But, I can not find the ```OpenMS.ini``` at both ```${HOME}/.OpenMS/``` and ```${HOME}```. So, I failed to changed the ```tmp_dir```, and I wonder how could I change the default tmp path. 
Thanks!

**Comment by cbielow** [comment]
use the environment variable TMP/TEMP (depending on your system)
on Windows, this works:
```
c:\>set TMP=c:\TEMP

c:\>openmsinfo
OpenMS Version:
==================
Version      : 2.2.0
Build time   : Oct 19 2017, 14:12:00
Git sha1     : disabled
Git branch   : disabled

Installation information:
==================
Data path    : C:/dev/OpenMS/share/OpenMS
File 'C:/Users/bielow/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in 'C:/Users/bielow/.OpenMS/OpenMS.ini' with defaults!
Temp path    : C:/TEMP
Userdata path: C:/Users/bielow/

Build information:
==================
Source path  : C:/dev/OpenMS/src/openms
Binary path  : C:/dev/OpenMS_build/src/openms
Binary arch  : 64 bit

OS Information:
==================
Name: Windows
Version: 6.1
Architecture: 64 bit
```

**Comment by BioWu** [comment]
Thanks for your reply. But it seems like does not work well in Linux. I tried both ```export TMP=${HOME}``` and ```export TEMP=${HOME}```.

**Comment by hroest** [comment]
> Setting linux tmp directory should work as well: export TMP=/home/user/tmp

no this does not seem to work unfortunately, see https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/SYSTEM/File.cpp#L450

I think almost the only thing you can do is control it through `~/.OpenMS/OpenMS.ini` which is horrible and does not work well on cluster / multithreaded environments. However for local installs it should work.
