### ISSUE TITLE
OpenMS 2.2.0 does not compile with current contrib

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#2998]
the source code tarball is some fixes to work with a newer boost version which is now in contrib, see #2790 basically

- #2837 
- #2838
- #2793

-- can we add that to the release code? otherwise it is very frustrating. Basically we need to fix

- "src/openms/source/FILTERING/NOISEESTIMATION/SignalToNoiseEstimatorMedianRapid.cpp" 
- "src/openms/include/OpenMS/MATH/STATISTICS/StatisticFunctions.h" 
- "src/tests/class_tests/openms/source/UniqueIdGenerator_test.cpp"

**Comment by hroest** [comment]
I added a blocker label to this as this means that we currently *cannot* compile the latest OpenMS 2.2 version when following the instructions and doing everything as in the instructions.

**Comment by hroest** [comment]
@timosachsenberg @jpfeuffer

**Comment by timosachsenberg** [comment]
sure. 
So, we cherry-pick:
https://github.com/OpenMS/OpenMS/pull/2837/commits/204552f28f4e7cb1cdac110dbb49c9fec1b6151c
https://github.com/OpenMS/OpenMS/pull/2837/commits/88ffe8dae4dacc0cf37e6d920ba1a83a71f731d5
https://github.com/OpenMS/OpenMS/pull/2838/commits/cb21532cb2570d8742d9bbf4263b12468afc6618
https://github.com/OpenMS/OpenMS/pull/2793/commits/8a5b5eb967b797df6fdd08c6b8498b5080a82eaf
https://github.com/OpenMS/OpenMS/pull/2793/commits/e30fee79552b2282b0229a0ead137d9822a21d5b

and need to update the tag? right?

**Comment by hroest** [comment]
yes, and please also update sourcefourge tar files -- and I suggest to use 2.2.0-1.tar.gz in case somebody is already using these tar balls

**Comment by hroest** [comment]
also it seems that it is *not* in the source tarballs from github or sourceforge

- https://sourceforge.net/projects/open-ms/files/OpenMS/OpenMS-2.2/OpenMS-2.2.0-src.tar.gz/download :-1: 0a4dc7f31dad59a60ee8fd5b27fb7610 (downloaded before)
- https://github.com/OpenMS/OpenMS/archive/Release2.2.0.tar.gz :-1: 73f1fe2d691019a2badba99d3b4f0a83 (downloaded now)
- https://github.com/OpenMS/OpenMS/releases/download/Release2.2.0/OpenMS-2.2.0-src.tar.gz :-1: 0a4dc7f31dad59a60ee8fd5b27fb7610 (downloaded now)

as you can see, the md5sum is still the same as before of the 2.2.0 release

**Comment by jpfeuffer** [comment]
I created the new source packages. It is probably because "OpenMS-2.2.0-src.tar.gz" contains the contrib etc. while GitHub only packages what is in the repo.

**Comment by hroest** [comment]
ok, if the contrib is in there then its probably find as the 2.2.0 contrib works with the 2.2.0 release, right?

**Comment by jpfeuffer** [comment]
Ah was it only about the boost update in the contrib? If so, yes, the contrib cmakes in the 2.2.0 release include a link to the old boost (1.6.1) which is also still saved on our servers.

**Comment by timosachsenberg** [comment]
is this still relevant for the 2.3 release?

**Comment by jpfeuffer** [comment]
I am planning to release the new release with the contrib as submodule. Then we should always know about with which contrib a certain release was built and working.

**Comment by jpfeuffer** [comment]
We updated the source package on the release page for 2.2.0.
Should not happen anymore with contrib and thirdparty as submodule.
