### ISSUE TITLE
Peak integration using the trapezoidal rule

### ISSUE THREAD

**Issue by dmccloskey** [OpenMS/OpenMS#3003]
Peak integration is currently done by summing the intensities over the peak.  If points are not uniformly sampled across all chromatograms or spectra, this will make comparison by peak area problematic.  An approximation to the true area that is agnostic to the sampling rate is via integration by the trapezoidal rule.  

Future enhancements could use a Gaussian model or similar to more accurately capture the true peak shape that is independent of the number points acquired across the peak.

**Comment by dmccloskey** [comment]
@hroest Should this just be an option in the peakPickerMRM (e.g., Integration by summation or integration by the trapezoid rule)?

**Comment by hendrikweisser** [comment]
Good suggestion. Is this only an issue in PeakPickerMRM or also in other tools (e.g. feature finders)? Especially in the latter case, an implementation of this feature should offer a clean interface and allow reuse.

**Comment by dmccloskey** [comment]
I am not sure.  However, I think it general a class that just has methods to determine the peak area, shape, etc., that could be called by multiple tools would be useful.  We added a method called "calculatePeakShapeMetrics_" to MRMTransitionGroupPicker just for the purpose of characterizing a peaks shape for QC purposes.  We added some background estimation methods as well. Expanding these with methods to determine peak area into a general class would probably make things much easier and more standardized.  It is highly important at least for accurate quantitation in metabolomics.

**Comment by dmccloskey** [comment]
I will take a stab at this over the coming weeks.  The interface will take in raw/smoothed/etc., MSChromatogram/MSSpectrum and left/right positions identified by a peakPicker, and then calculate the area, background, and peak shape metrics based on parameters.

Let me know how that sounds.

**Comment by hendrikweisser** [comment]
> Future enhancements could use a Gaussian model or similar to more accurately capture the true peak shape that is independent of the number points acquired across the peak.

I've made a helper class "[ElutionModelFitter](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1ElutionModelFitter.html)" for fitting Gaussian or EGH models to features in FeatureFinderIdentification (FFId). The current implementation makes some assumptions that are specific for FFId (see documentation of [this](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1ElutionModelFitter.html#a7e8c82aac8dd9f2b64af59610d8f02e9) function), but it may be a useful starting point.

**Comment by dmccloskey** [comment]
OK thanks for that suggestion.  @pasqoo and I may need to ask you some questions when we get to the point that we implement those, which will hopefully be quite soon  :)

**Comment by pasqoo** [comment]
This adds functionality for the trapezoid and for simpson's rule: 
https://github.com/OpenMS/OpenMS/pull/3090

EMG will come next.
