### ISSUE TITLE
cpplint / cppcheck and C++11

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3010]
We have a few false positives with cpplint:

- #2969
- #3007 

```
/home/travis/build/OpenMS/OpenMS/src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp:864:  Storage class (static, extern, typedef, etc) should be first.  [build/storage_class] [5]
Done processing /home/travis/build/OpenMS/OpenMS/src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
Total errors found: 1
```

**Comment by hroest** [comment]
probably our version of cppcheck is also too old: 
https://github.com/danmar/cppcheck/commit/9d3359177d68f2236245fa1104e87672fe9b503b

**Comment by hroest** [comment]
1.65: Update Makefile

    master 

    1.81 

    1.65 

1 parent c0131ee commit 9d3359177d68f2236245fa1104e87672fe9b503b danmar danmar committed on May 10, 2014

**Comment by jpfeuffer** [comment]
What's the status? Do we still need to upgrade?

**Comment by hroest** [comment]
yes this has been merged in #3011

**Comment by hroest** [comment]
seems like we did not update cpplint, its still on a very old version 9bc8d670e939bc5dc77c34ba09eccb62054aad6d

**Comment by hroest** [comment]
we probably should replace it with a new version https://raw.githubusercontent.com/cpplint/cpplint/master/cpplint.py

**Comment by jpfeuffer** [comment]
see #3334

**Comment by hroest** [comment]
Merged in 

- #3011
- #3334
