### ISSUE TITLE
Nightlies and release branch failing

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3019]
To bring forward the release again, we need to fix some failing tests:
macOS:
  - SVM_Wrapper (Unknown older problem. Random generator?)
  - FeatureFinderIdentification @hendrikweisser 

Win:
  - on develop/nightly compile error
 ```C:\jenkins\ws\openms_nightly_packaging\c2e226b2\source\src\openms\source\FORMAT\HANDLERS\MzMLSqliteHandler.cpp(1024): error C3016: 'k': index variable in OpenMP 'for' statement must have signed integral type [C:\jenkins\ws\openms_nightly_packaging\c2e226b2\build\src\openms\OpenMS.vcxproj]```
@hroest
  - PercolatorAdapter (see #2950, either we wait for release and adapt the tests until then or build ourselves)
  - FeatureFinderIdentification (see #2747) @hendrikweisser

**Comment by hroest** [comment]
Hi

yes, we need to fix these. I have a patch here
https://github.com/OpenMS/OpenMS/pull/3020

Hannes

**Comment by jpfeuffer** [comment]
Thanks for the quick fix @hroest. Looks good!

**Comment by jpfeuffer** [comment]
There is another error that I now remember after seeing Windows building again:
- RNADigestor and related classes fail compilation:
```
ProteaseDB_test.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class OpenMS::DigestionEnzymeProtein const * __cdecl OpenMS::DigestionEnzymeDB&lt;class OpenMS::DigestionEnzymeProtein,class OpenMS::ProteaseDB&gt;::getEnzymeByRegEx(class OpenMS::String const &amp;)const " (__imp_?getEnzymeByRegEx@?$DigestionEnzymeDB@VDigestionEnzymeProtein@OpenMS@@VProteaseDB@2@@OpenMS@@QEBAPEBVDigestionEnzymeProtein@2@AEBVString@2@@Z) referenced in function main [C:\jenkins\ws\openms_pr_windows_ci\979a8a2f\build\src\tests\class_tests\openms\ProteaseDB_test.vcxproj]
```
@hendrikweisser

**Comment by cbielow** [comment]
`ProteaseDB_test.obj:` 
  - wow, the breaking change was made in September. Wonder how it lasted that long undetected.
and `MzMLSqliteHandler.cpp(1024): error C3016: 'k': index variable in OpenMP 'for'`
both solved in #3022

**Comment by hroest** [comment]
@jpfeuffer for both breaking changes it would be nice if they were detected by the CI - was the problem that we did not look properly and merged even though we had breaking changes or that they were not detected by the CI?

**Comment by hroest** [comment]
> PercolatorAdapter (see #2950, either we wait for release and adapt the tests until then or build ourselves)

I suggest to turn off the test for the Windows build for now until we have the new binaries

**Comment by jpfeuffer** [comment]
@hroest I think both problems were swallowed because of the "exit status" problem we had. This resulted in green blobs on GitHub. But on CDash and the actual Jenkins job it should (and should have) always show(n) all the problems.

**Comment by timosachsenberg** [comment]
OpenMp is still at 2.0 in vs so we need to address that

**Comment by jpfeuffer** [comment]
IDFileConverter_23_test (the newest one) fails on macOS because PeptideHits are (at the first glance randomly) swapped with neighboring ones. Map/set sorting issues during reading? Should we sort during reading or writing?

[IDFileConverter_23_output.diff.txt](https://github.com/OpenMS/OpenMS/files/1503053/IDFileConverter_23_output.diff.txt)

**Comment by jpfeuffer** [comment]
Ok with the sorting of PeptideHits the IDFileconverter failure is gone.
We are currently ignoring the FFID failures and the Percolator RNG Win failures.
We will try to incorporate a source build of the newest Percolator, then we can reactivate.
Otherwise, the release branch builds now without errors.

**Comment by jpfeuffer** [comment]
After syncing I am positive that also the nightlies will succeed.

**Comment by jpfeuffer** [comment]
Ok. Apart from the fact that we had to disable the FFID tests, everything seems to be running again. Closing. Feel free to reopen if you notice sth different.
