### ISSUE TITLE
improve TOPPView tutorial

### ISSUE THREAD

**Issue by Stortebecker** [OpenMS/OpenMS#3033]
Dear OpenMS developers,

I really think that you need to improve your TOPPView tutorials. At the moment, you provide much more functions than you explain in the tutorial. Important features like annotating `mzML` or `featureXML` files with peptide identifications, then visualizing the peptide IDs mapped to a feature by clicking `Show feature annotation` -> `peptide identification` are not covered at all. 

TOPPView is very powerful, but it is not very intuitive. To attract more users, I would recommend to work on more and higher quality [video tutorials](https://www.openms.de/getting-started/command-line-and-visualisations/).

Greetings, Florian

**Comment by timosachsenberg** [comment]
Thanks for the feedback! We are constantly improving the documentation and tutorials for our workshops but usually only do that once for each full release. @jpfeuffer would it be possible to include the generation of handouts (from the head of the Tutorial master branch) and provide the pdf?

**Comment by jpfeuffer** [comment]
You can find it here: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/

**Comment by timosachsenberg** [comment]
Ah cool. Didn't realize that this is already linked. So we just need to make sure we don't forget to merge the new material from our last workshops.

**Comment by jpfeuffer** [comment]
Yes. But I think Florian is also right about the TOPPView tutorial and the videos.
