### ISSUE TITLE
TargetedExperimentHelper::getRetentionTime() assumes "MS:1000896" exists

### ISSUE THREAD

**Issue by pasqoo** [OpenMS/OpenMS#3038]
While working on https://github.com/OpenMS/OpenMS/pull/3014 I noticed that `TargetedExperimentHelper::getRetentionTime()`
https://github.com/OpenMS/OpenMS/blob/cfcf9ff09613191aa3502dbf5c6df9a613379376/src/openms/include/OpenMS/ANALYSIS/TARGETED/TargetedExperimentHelper.h#L384
assumes that the RT info is saved in `"MS:1000896"`.
In the comment inside the code it is reported that it is a "guesstimate", but the code actually accesses the key before verifying it exists in the map (for example with a `.hasCVTerm("MS:1000896")` or `getCVTerms().has("MS:1000896")`).

One case where the RT info is saved somewhere else is when one sets `retentionTimeInterpretation` parameter from `TransitionTSVReader` as `"minutes"` or `"seconds"`. In those two cases, the RT info is saved in `"MS:1000895"`.
Here the code: https://github.com/OpenMS/OpenMS/blob/2eb48eac4dbd03b7e7ededb4d6e8dd64f92edb25/src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVReader.cpp#L1016

More info:
OpenMS version: the issue is present in `master` and `develop`
Platform: Ubuntu 17.10

**Comment by hroest** [comment]
Yes, this is an open problem and something I already started working on.
