### ISSUE TITLE
TransitionTSVReader::createPeptide_: Problem with E(Cation:Cu[I])

### ISSUE THREAD

**Issue by grosenberger** [OpenMS/OpenMS#3042]
This issue was originally reported by @bretttully. TargetedFileConverter parses modified peptide sequences with support for various formats.

- TSV/CSV files can contain modifications in TPP, UniMod or PSI-MOD formats.
- TraML files store modifications as UniMod (e.g. S(UniMod:21)) modifications
- PQP files currently employ PSI-MOD modifications (e.g. S(Phospho))

When generating a PQP file from TSV or TraML, OpenMS::AASequence converts all potential formats to PSI-MOD, which is then stored. However, when converting back, TargetedFileConverter runs into problems with complex modifications, e.g. E(Cation:Cu[I]) as it wants to parse the brackets as well in TransitionTSVReader::createPeptide_.

How should we store PTMs in OpenMS in general (and in PQP files)? Is PSI-MOD or UniMod preferred?

**Comment by timosachsenberg** [comment]
I repeatedly heard that PSI-MOD is basically dead/unmaintained.

**Comment by grosenberger** [comment]
Alright, then I guess that storing PTMs in UniMod format would be preferable (and consistent with TraML) and I will prepare a PR accordingly.

**Comment by hroest** [comment]
yes, I would also suggest UniMod only and otherwise we just store the mass, e.g. E[34.45545]

**Comment by hroest** [comment]
PS: it would also be nice if the parser would not break on things like `E(Cation:Cu[I])` - so maybe we need to correctly parse square brackets inside round brackets, right? Basically would a test be something like  `AASequence("PE(Cation:Cu[I])PTIDE` to check this?
