### ISSUE TITLE
Developers Doc not build

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#3044]
http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/index.html
last update was in June. Something seems broken :/

**Comment by jpfeuffer** [comment]
It moved to:
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/

Do you still see the old link somewhere? It is hard to get it out of google though :/

**Comment by cbielow** [comment]
I have it bookmarked :)
And the data at ftp.mi.fu-berlin.de/pub/OpenMS/ is still there. The Release Docs are meant to stay in the same position (i,e, http://ftp.mi.fu-berlin.de/pub/OpenMS/release2.2.0-documentation/... ?). If yes, it would make sense to add a link for the developer docs there as well.

**Comment by cbielow** [comment]
ok, I think we solved it.
http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/ now forwards to the new location.
