### ISSUE TITLE
distinction between mod specificity "N-term (Anywhere)" and "N-term (Protein N-term)" not possible

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3050]
Take for example Acetylation [1]. Either all peptide N-termini could be acetylated (Anywhere) or merely the protein N-termini (Protein N-term). Right now we cannot distinguish between these two cases in the search engine adapters where the mod is only listed as simply "N-term".

[1] http://www.unimod.org/modifications_view.php?editid1=1

**Comment by timosachsenberg** [comment]
see e.g. https://github.com/OpenMS/OpenMS/issues/1922 
https://github.com/OpenMS/OpenMS/issues/1913
