### ISSUE TITLE
MzTab : link PSM entries to spectrum and ms run 

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3052]
`mzTab` does not require an `MS run` column in the `PSM` section.
Could we add an optional `opt_ms_run` column to the output?

**Comment by timosachsenberg** [comment]
spectra_ref should contain the run number

**Comment by lars20070** [comment]
It's `null` in my OpenMS 2.1 output. I will check if this was updated since then.

**Comment by timosachsenberg** [comment]
ok please do. also check if the idXML contains the file name and in each PeptideIdentification the spectrum index in the meta data

**Comment by timosachsenberg** [comment]
The Problem:
PSM rows in mzTabs (e.g., exported from a consensusXML) should link to the MS run and spectrum in the spectra_ref column. While this should be pretty straightforward (e.g., adding it in https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MzTabExporter.cpp#L651) I think this information might not be directly available at the ID level.

@Matthias313 can you provide a e.g. trimmed down consensusXML file as github gist so I can check if this is also your problem?

**Comment by timosachsenberg** [comment]
Probably also for idXML file (but there it should be easier to implement)

**Comment by timosachsenberg** [comment]
addressed in https://github.com/OpenMS/OpenMS/pull/3198

**Comment by lars20070** [comment]
@timosachsenberg Are `PEP` entries also linked to the `ms run` by #3198?

**Comment by timosachsenberg** [comment]
hmm how do you mean? PEP entries report quant value columns which are associated with an assay (= channel in a ms run)

**Comment by lars20070** [comment]
For example, SILAC (two channels i.e. two abundances) in 10 fractions i.e. ms runs. After FileMerger all results are in a single mzTab.

**Comment by timosachsenberg** [comment]
Not sure for Silac. Can you point me to a good fractionated example dataset + fasta + workflow? I will try to run this through my extended proteinquantifier Export branch.

**Comment by lars20070** [comment]
@timosachsenberg [Here](https://www.dropbox.com/s/cjz87xv8p0xb9ki/mzTab_PEP_20180305.zip?dl=1) a minimal example. In the `mzTab` I would like to see if the peptide was quantified in `AGA210`, `AGA211` or `AGA212`. Of course the peptides could also be annotated.

**Comment by lars20070** [comment]
Here another example. I would prefer to work with a single `mzTab` instead of 54 separate ones.
But the current `mzTab` output does not list the original file i.e. run name in the `PEP` section.

<img width="1078" alt="screen shot 2018-03-20 at 14 25 37" src="https://user-images.githubusercontent.com/6149805/37657321-efee1ec0-2c4a-11e8-81ca-1385722e9389.png">

**Comment by timosachsenberg** [comment]
@lars20070  I don't understand. Do you mean PSM section?

**Comment by lars20070** [comment]
That's an LFQ analysis with 54 MS runs. I map IDs to peptide features (Node 3). I am interested in annotated peptide features (Node 7) in each of the runs. In Node 9, I have 54 separate `mzML` files with `PEP` sections. The file name gives me the run, the `PEP` section the quantified sequence.

In Node 16, I have got a single `PEP` section, but no longer know in which MS run the peptide was quantified/identified.

**Comment by timosachsenberg** [comment]
I see. This is a bit different from the normal mzTab use case so easiest would be to just annotate the file origin in a meta value using IDMapper.
Then export the individual PEP tables, read them back in in KNIME and merge them.

**Comment by algom** [comment]
I would disagree, on the contrary, fractions are the normal use case. This is a common procedure and not having annotated in mztab, differs its use as fractions are not technical nor experimental replicates but are an intrinsic part of an experiment.

**Comment by timosachsenberg** [comment]
Me too. Just speaking for the current version of mzTab :P
