### ISSUE TITLE
IDPosteriorErrorProbability sometimes reports probabilities outside of [0,1]

### ISSUE THREAD

**Issue by mafreitas** [OpenMS/OpenMS#3053]
I am performing a multi search consensus workflow and want to add Fido at the end.  The PEPmatrix requires PEP scores in the search files.  When I try to run Fido I get the following errors.

FidoAdapter -in input.idxml -out {output.idxml -fido_executable /tools/Fido -fidocp_executable /tools/FidoChooseParameters -all_PSMs -greedy_group_resolution -no_cleanup
Reading input data...
Generating temporary files for Fido...
Warning: Scores of peptide hits seem to be posterior error probabilities. Converting to (positive) posterior probabilities.
Error: Unsuitable score type for peptide-spectrum matches detected (problem: score < 0).
Fido requires probabilities as scores, e.g. as produced by IDPosteriorErrorProbability with the 'prob_correct' option.
Error: Unexpected internal error (Error: Unsuitable score type for peptide-spectrum matches detected (problem: score < 0).
Fido requires probabilities as scores, e.g. as produced by IDPosteriorErrorProbability with the 'prob_correct' option.)

I was wondering if there was a way to include PP and PEP in the idxml and switch the scores with IDScoreSwitcher before fido?

Running using a nightly build docker container.
FidoAdapter = Version: 2.3.0 Nov  8 2017, 01:10:00, Revision: b907ff19b7d7a881b5527daa94386f5819612943

**Comment by jpfeuffer** [comment]
Hmm.. It actually tries an automatic conversion but finds scores with PEP < 0.
Can you upload the data?

**Comment by mafreitas** [comment]
The consensus idxml is 1.1Gb.

**Comment by jpfeuffer** [comment]
Hm ok. Can you check locally if you actually have such scores < 0 and maybe paste an excerpt?

**Comment by mafreitas** [comment]
I will give that a try!

**Comment by jpfeuffer** [comment]
Any updates? Could you get rid of negative values? Do you know how they ocurred?

**Comment by mafreitas** [comment]
I used a script to delete them manually.  Not sure how they occurred.  I have run into some issues with myrimatch and IDPosteriorErrorProbability giving peptide scores > 1 (which I filter out with IDFilter).  If you want more details I can try and put together some very specific test cases.

Mike

Michael A. Freitas, PhD
Associate Professor, Cancer Biology and Genetics
Director Proteomics Shared Resource, OSUCCC
460 West 12th Ave. | Room BRT 906 | Columbus, OH 4321

**Comment by jpfeuffer** [comment]
Hi Mike. 
Interesting. Sure, that should not happen. If you find such a case, please report them. I am happy to have a look at it.

**Comment by poshul** [comment]
Closed. Stale
