### ISSUE TITLE
Make versions of third party tools easily accessible in Knime 

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3057]
In Knime, the version of the third party tools is not easily accessible for end users. It would be helpful if these versions could be shown in the Knime GUI, for example in the description as shown in the screenshot below.

<img width="736" alt="screen shot 2017-12-01 at 13 34 46" src="https://user-images.githubusercontent.com/6149805/33484080-23010660-d6a1-11e7-9535-18823f51d4f8.png">

**Comment by timosachsenberg** [comment]
You can add them yourself in https://github.com/OpenMS/OpenMS/blob/develop/cmake/knime/LICENSE

The downside is that we have yet another place where we need to update these numbers. Not a big deal but it should then also be documented on the wiki: https://github.com/OpenMS/OpenMS/wiki/Preparation-of-a-new-OpenMS-release

**Comment by jpfeuffer** [comment]
Maybe we should have a License file in the Thirdparty repo that will be concatenated into the OpenMS License during packaging? What do you think?

**Comment by timosachsenberg** [comment]
This sounds like a good solution that is easier maintainable
