### ISSUE TITLE
ProteinQuantifier: resolve ambiguous annotation of features [306]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#306]
Submitted by hendrikweisser on 2011-05-13 19:58:52

Features with ambiguous annotation (where peptide IDs with different sequences were mapped) are currently ignored by ProteinQuantifier, i.e. not used for quantification. The reason is that it's not clear to which peptide the feature intensity should be attributed in such a case.

However, some workflows - that are more prone to producing ambiguities - would benefit from less "restrictive" approaches. E.g. in phosphorylation studies, it is quite common that search engines mis-identify the phosphorylation site in a peptide with several possible sites. If a feature from such a peptide contains multiple IDs, the probability of a mismatch (due to different phospho sites) is relatively high.

Possible resolution strategies for ambiguous features:
1. use the ID with the best score
2. use the ID that occurs the highest number of times
3. use the ID closest to the feature centroid
4. ignore (the position of) modifications
5. split up the feature intensity among the different IDs

One or several of these strategies should be added as options to ProteinQuantifier.

---

Commented by hendrikweisser on 2011-09-27 13:59:18:
Partially fixed with the addition of IDConflictResolver (new TOPP tool) in rev. 8889. So far, only strategy 1 (see above) is implemented.

**Comment by jpfeuffer** [comment]
Also related to #2605
