### ISSUE TITLE
add docu on how to check out submodules to build docu

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3064]
e.g.

 git submodule update --init --recursive

**Comment by timosachsenberg** [comment]
also I think we might need to update the tools/quickbuild(-osx).sh and (potentially) build.bat

**Comment by jpfeuffer** [comment]
By the way: Do people experience problems if they do not specify clang as compiler on macOS? I think I do not. Then we could remove one quickbuild.

**Comment by timosachsenberg** [comment]
@hroest I think you added the mac script. Do you know if this is needed?

**Comment by oliveralka** [comment]
Both quickbuild scripts work in my case (OSX 10.13.2).

**Comment by jpfeuffer** [comment]
Ok we can think about removing one then.

**Comment by hroest** [comment]
> @hroest I think you added the mac script. Do you know if this is needed?

I never used the osx one, so feel free to remove it

**Comment by timosachsenberg** [comment]
Also checked the quickbuild.sh on Mac. Worked like a charm.
