### ISSUE TITLE
MSChromatogram and MSSpectrum peak range tests

### ISSUE THREAD

**Issue by pasqoo** [OpenMS/OpenMS#3067]
While working on https://github.com/OpenMS/OpenMS/pull/3066 I noticed that some sections don't actually test for the desired method.

Example:
https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/MSChromatogram_test.cpp#L460
That section is supposed to test for `RTEnd()`, but `RTBegin()` is used within the body, instead. Maybe a copy/paste error?

The same can be seen here for `MSSpectrum`:
https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/MSSpectrum_test.cpp#L665

**Comment by timosachsenberg** [comment]
yes look like a copy and paste error to me

**Comment by hroest** [comment]
sure, that does look like its wrong - seems like somebody just copy-pasted the test! Can you fix it and add the changes to #3066 please?

**Comment by pasqoo** [comment]
Done: https://github.com/OpenMS/OpenMS/pull/3066/commits/10305d4ad7f14300b49ce3117485e54a0e19e8cf
