### ISSUE TITLE
PSMFeatureextractor and Percolator

### ISSUE THREAD

**Issue by algom** [OpenMS/OpenMS#3071]
Dear all,

I have been trying to use the new Percolator adapter with no luck. I do searches with Comet, using the Comet adaptor in both OpenMS 2.2 (using TOPPAS) and the 2.3 nightly builds (last of 05.12.2017) in both TOPPAS and Knime.

Briefly my workflow is as follows, CometAdpator -> Peptideindexer -> PSMFeatureextractor -> Percolator.

If I run it in TOPPAS the PSMFeatureExtractor always crashes without any information. In Knime, PSMFeatureExtractor passes but Percolator always crashes. What I can get out of the log is: Merging Peptides IDs, merging Proteins IDs, Percolator problem... and then crashes.

If I use then the PSMFeatureExtractor result from Knime and use it as input for PercolatorAdapter in TOPPAS, I can run Percolator, however it always uses the -U option, even if I select -Y option (tdc true):
which my guess should be used as the search in Comet was done using a database containing decoys, and this should be indexed when using PeptideIndexer. Moreover, Percolator reports:
"Separate target and decoy search inputs detected, using target-decoy competition on Percolator scores", even though the -Y option is seen. Nonetheless it continues and finish. However if I then do IDFilter on that (q < 0.01) everything is gone. If I run Percolator including the -f option (Protein inference) I also can't filter the file. However, if I export this file doing text export without  IDFilter and filter manually for proteins with q-value of less than 0.01 and compare this with the same search files processed with PeptideProphet/ProteinProphet I get an overlap of ~80% at the protein level. However, I would need to have the filtered file as input for IDMapper, to only map peptides at 1%FDR to features.

Maybe somebody has more experience on running PercolatorAdapter and I might be using it wrong.

Cheers,

Alejandro

**Comment by jpfeuffer** [comment]
@Leon-Bichmann can you comment on how you use it?

**Comment by jpfeuffer** [comment]
@algom Can you upload your KNIME workflow and data somewhere? It seems to be small enough to check.

**Comment by Leon-Bichmann** [comment]
@algom,

Nice that you are trying the Comet Percolator combination. It has worked great with my data using an openMS workflow.

You need to calculate an FDR before PSM feature extraction and Percolator Adapter, as the Percolator only refines an existing FDR. Important is also that you activate the algorithm:add_decoy_peptides flag in the FDR node.

Here is an existing KnimeWorkflow for this combination:

https://cibi.uni-konstanz.de/socialworkflows/workflows/OpenMS:MHCLigandomics_new

Let me know if this solved the issue.

**Comment by algom** [comment]
@Leon-Bichmann and @jpfeuffer 

I've already across your workflow while trying to test it (Thanks!!) However, that workflow was written in OpenMS 2.2, and its giving an error in the Percolator adapter as the osw_level function is not included I guess so I can't open it, and all nodes have default values.

In any case I reproduce your workflow, but i still get the same error, i.e. PercolatorAdapter crashes. While taking the PSMFeatureExtractor result file, and then using it with PercolatorAdapter with TOPPAS (2.3 nightly 05.12.2017) it warns that decoy and target =* so I should activate the -Y option (tdc) I do it, and it runs but if I do text export of that file all peptides have a q-score of 1, but at the protein level I do see q-scores from 0 to 1.

I also tried just to search for one file (Only heavy label) but then PSMFeatureExtractor fails. I don't know if it is that is not recognizing the decoy string "dec_" in my case, or if it is thinking when doing separate heavy and light searches that one is the traget and the other is the decoy.

I have uploaded my KNIME wrikflow, I could also send you a part of the file if you need, as the file is 1GB.

Thannks for the help! I really look forward to using the Comet/Percolator in OpenMS.

[Comet_percolator_test.zip](https://github.com/OpenMS/OpenMS/files/1539579/Comet_percolator_test.zip)

**Comment by timosachsenberg** [comment]
hmm q-score of 1 sounds bad. Just an idea, we changed the decoy prefix to "DECOY_" by default. Maybe this parameter change is not reflected in your workflow? Just an idea...

**Comment by jpfeuffer** [comment]
Can you maybe send the Comet output only? Should be reduced quite a bit. Then we can start the workflow from there.

**Comment by algom** [comment]
I sent it internally through Gitter. @Leon-Bichmann a general question, why would one need the FDR if Comet can be used directly with Percolator (command line), using the pin file?

**Comment by algom** [comment]
I have continue to test it but I have not been able to go any further. I also have come to suspect that if the PSMs have a different file origin name they are interpreted in Percolator as target and decoy, and no matter if the -Y option is selected (tdc) it will process them as target and decoy, thus for example the light labeled will only be considered as decoy and only the heavy will be considered targets, and as they could be similar, then all the heavy end up ending with q score 1. 
Unfortunately, I also have not been able to run it just with a file with no major modifications.
@Leon-Bichmann are you able to run your workflow with the current nightly builds? or in which OpenMS have you run it successfully? (own build?)

**Comment by Leon-Bichmann** [comment]
Thats true you can also use the pin option to work with the percolator in commandline. However I haven't tested it and I think the OpenMS Percolator Adapter is doesn't take pin files.

The version I was using is: Version: 2.3.0 Sep 12 2017, 13:44:55, Revision: ee08c12

Moreover I am not using and haven't tested it in knime thoroughly since it was easier to wrap the openMS tools in a python script for us.

**Comment by Leon-Bichmann** [comment]
Here is part of the python script that im using to run the percolator adapter maybe that helps.. sorry im not aware of the -Y option..

 ```
idresult_fdr = os.path.join(result_path, identifer_for_file.replace('.idXML', '_fdr.idXML'))
    falseDiscovery = 'FalseDiscoveryRate -in {f} -out {o}  -algorithm:add_decoy_peptides'.format(f=idresult,o=idresult_fdr)
    subprocess.call(falseDiscovery.split(),stderr=logfile, stdout=logfile)

    #extract Percolator Features with PSMFeatureExtractor
    idresult_fdr_psm = os.path.join(result_path, identifer_for_file.replace('.idXML', '_fdr_psm.idXML'))
    PSMFeat = 'PSMFeatureExtractor -in {f} -out {o} -threads 20'.format(f=idresult_fdr,o=idresult_fdr_psm)
    subprocess.call(PSMFeat.split(),stderr=logfile, stdout=logfile)

    # run Percolator with PercolatorAdapter
    idresult_perc = os.path.join(result_path, '{}_perc.idXML'.format(identifer_for_file))
    Percolator = 'PercolatorAdapter -in {f} -out {o} -decoy-pattern DECOY -debug 10 -enzyme no_enzyme -trainFDR 0.05 -testFDR 0.05'.format(f=idresult_fdr_psm,o=idresult_perc)
    subprocess.call(Percolator.split(),stderr=logfile, stdout=logfile)

```

**Comment by hroest** [comment]
Hi Leon

Have you considered adding the functionality of FDR tool and PSMExtractor
directly to the PercolatorAdapter such that we could run search engine and
then Percolator directly with only two steps?

**Comment by Leon-Bichmann** [comment]
Hi, true that might be an option that would make it easeir but at the moment I dont think ill have the time to work on it.

**Comment by MFreidank** [comment]
Hi, I have similar issues as @algom trying to run a KNIME workflow that uses Percolator. 

In my case the workflow is even more "standard", I run MSGFPlus before Percolator:
MSGFPlus -> PeptideIndexer -> FalseDiscoveryRate -> PSMFeatureExtractor -> Percolator

When i execute my workflow, Percolator crashes and I only get the following output:
```
ERROR PercolatorAdapter    2:12       Failing process stdout: [File 'C:/Users/moritz/.OpenMS/OpenMS.ini' is deprecated., Updating missing/wrong entries in 'C:/Users/moritz/.OpenMS/OpenMS.ini' with defaults!, Loading input file: C:\Users\moritz\AppData\Local\Temp\26\knime_MSGFplusSearch_99775\knime_fs-PSMFeatureExtractor-99780\000\000\PSMFeatureExtractor_0\HEK1.mzid, <File 'C:/Users/moritz/.OpenMS/OpenMS.ini' is deprecated.> occurred 2 times, Converting from mzid: possible loss of information depending on target format., <Updating missing/wrong entries in 'C:/Users/moritz/.OpenMS/OpenMS.ini' with defaults!> occurred 2 times, No DatabaseName element found, use read in results at own risk., Merging peptide ids., Merging protein ids.]
ERROR PercolatorAdapter    2:12       Failing process stderr: [No name/version found for 'AnalysisSoftware':SOF_4818953978181165463.]
ERROR PercolatorAdapter    2:12       Execute failed: Failed to execute node PercolatorAdapter
```


@MatthewThe @Leon-Bichmann 
Can you spot the reason for this error trace? Do you have any MSGFPlus -> Percolator workflows in KNIME -- maybe the way mine is set up is wrong?

Best,
MFreidank

**Comment by Leon-Bichmann** [comment]
Not sure about this error message maybe @jpfeuffer has an idea..

Important for working with MSGFPlus is that you need to enable the flag -add_features to add the psm features  to the idXML for the psm feature extractor

**Comment by Leon-Bichmann** [comment]
Hey,
I recently tried to reproduce my results from a previous analysis using Percolator and Comet with OpenMS and it seems that now Percolator is massively overfitting...

Previous analysis:
Version: 2.2.0 Aug  1 2017, 15:32:54, Revision: 14bb753
Recent analysis:
Version: 2.3.0 Apr 19 2018, 09:13:58, Revision: df2dc9a

Is anyone aware of a change that we did to the Adapter that might have caused this?

**Comment by MatthewThe** [comment]
Perhaps #3462 ?

**Comment by Leon-Bichmann** [comment]
Good point, but I think this even too recent.. In any case, I should probably check the latest version again.

**Comment by timosachsenberg** [comment]
@Leon-Bichmann do you use PEP?

**Comment by hroest** [comment]
@timosachsenberg here it would be helpful to have integration tests that use semi-large datasets to test a specific workflow and ensure there are no regressions ...
