### ISSUE TITLE
OpenSwathDIAPreScoring Tool category clash

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3074]
`warning : Message to maintainer - If 'OpenSwathDIAPreScoring' is an official TOPP tool, add it to the tools list in ToolHandler. If it is not, set the 'official' flag of the TOPPBase constructor to false.`

**Comment by timosachsenberg** [comment]
fixed in https://github.com/OpenMS/OpenMS/pull/3077
