### ISSUE TITLE
[Error about IDPEP]: Unable to fit data. Algorithm did not run through for the following search engine: XTandem

### ISSUE THREAD

**Issue by BioWu** [OpenMS/OpenMS#3075]
Hello,
  I met one strange problem as described in title. I want to commbined searching results from Xtandem [Vengeance && Alanine were all tested] and omssa, and before the IDMeger step,  the IDPEP tool was applied to each of their results. But the ```Unable to fit data``` occurred in one of Xtandem result and the pipeline crashed.
  I had checked possible solutions, but no one could work. 
 OpenMS [2.2.0] in Linux with commandlines.
Could anyone meet such problem? Thanks.

**Comment by jpfeuffer** [comment]
Hi,

This usually indicates suboptimal search parameters that lead to unexpected/biased score distributions.
I would need to have a look at the distribution to say more.
One problem someone encountered recently was that the precursor tolerance was too narrow to have enough bad hits.
If that is the case, you could try to widen the precursor tolerance.
Could be something else though too.

**Comment by BioWu** [comment]
@jpfeuffer Thanks! The distribution of e-values in the Xtandem sample was below:
![image](https://user-images.githubusercontent.com/10484714/33719009-06bafef6-db25-11e7-840b-35d30a6c6fed.png)
And these is one passed sample:
![image](https://user-images.githubusercontent.com/10484714/33719398-2f1499d8-db26-11e7-8201-45b4de88e6c8.png)

I think I should give larger e-value cutoff in ```XtandemAdapter```, maybe 1000 ?

**Comment by BioWu** [comment]
@jpfeuffer , Besides, I wonder if there exist any other way to commbine OMSSA and XTandem results. Because, after the above ```bad``` date was removed, another error of the same type error occurred in results of OMSSA. It likes that the e-values of my sample all do not fit the build-in distribution?

**Comment by jpfeuffer** [comment]
Wow thank you for the detailed information. I think you found the reason for the failure. If I remember correctly, XTandem has a certain cutoff for "best" evalues. At some point they don't get better=lower that is why they accumulate at low evalues. I overcame the problem once by widening/loosening the search parameters to allow more candidates to be scored. Including more bad ones. Did you try that yet? Unfortunately  there is no other way to combine them. You have to calculate probabilities to bring the scores of the different engines to a comparable scale.

**Comment by jpfeuffer** [comment]
Is there any update on this? Could you solve the problem?

**Comment by jpfeuffer** [comment]
We have a project that would make the fitting procedure more robust but it seems to be most likely an XTandem settings problem.
