### ISSUE TITLE
xerces-c_3_1.dll not found for manual Win build (has to be added to PATH)

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#3101]
Tried to build OpenMS on Windows following https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/RC/2.3.0/html/install_win.html

After Tool building, the tools don't find xerces-c_3_1.dll.

It was located in contrib/lib (manual building of contrib), manual addition to the PATH solved the problem.

**Comment by timosachsenberg** [comment]
I think it is in the build instruction:
"Add the <path_to_contrib_build>/lib directory to your PATH Environment Variable (this is so Windows can find the DLL's when running our executables)."
Can you confirm?

**Comment by FabianAicheler** [comment]
Yep, apparently I just overlooked the lib part for the path in the documentation.
