### ISSUE TITLE
have "RUN_TESTS"/"test" target depend on "test_build" [311]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#311]
Submitted by cbielow on 2011-06-06 13:50:18

currently the "RUN_TESTS" (Visual Studio name) or "test" (Makefile name) targets are created by CMake automatically, to run all tests created by "add_test()". However, one cannot enforce building all tests beforehand in an automatic fashion, as these targets are not available at CMake runtime (thus ADD_DEPENDENCY (test_build, test) ) is not valid.
This is a known CMake bug:

http://public.kitware.com/Bug/view.php?id=8438

Once its fixed, we should add this dependency.

---

Commented by cbielow on 2013-06-13 14:32:40:
reminder: as of 2013-06 this features request is still pending and not actively pursued by CMake developers

**Comment by jpfeuffer** [comment]
We could redefine the add_test behaviour to create another target like "make build_and_test". Is still still wanted?
