### ISSUE TITLE
update links to documentation in wiki

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3135]
e.g., https://github.com/OpenMS/OpenMS/wiki
points to ftp at fu

**Comment by oliveralka** [comment]
https://github.com/OpenMS/OpenMS/wiki (Home) [updated]
https://github.com/OpenMS/OpenMS/wiki/Building-OpenMS (Building OpenMS) [updated]

**Comment by hroest** [comment]
it would be great if we had some rewrite rule on the openms server that would translate 

* http://www.openms.de/develop_doxygen/ to wherever it needs to go, similar to what 
* http://www.openms.de/current_doxygen/ at the moment does (this points to the latest release docu)

**Comment by jpfeuffer** [comment]
Done.
