### ISSUE TITLE
Mascot Online Adapter testing

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3138]
We should have at least one test using `-DWITH_MASCOT_TEST=On` - either in the nightlies or in the travis CI. Maybe we can ask the Mascot guys whether they mind when we do that? I guess we have to follow their restrictions:

> You are welcome to submit searches to this free Mascot Server. Searches of MS/MS data are limited to 1200 spectra and some functions, such as no enzyme searches, are unavailable. Automated searching of batches of files is not permitted. If you want to automate search submission, perform large searches, search additional sequence databases, or customise the modifications, quantitation methods, etc., you’ll need to license your own, in-house copy of Mascot Server.

http://www.matrixscience.com/search_form_select.html

I guess what we do falls under "automate search submission" but our goal is not to abuse their server to perform searches but rather test our integration. Maybe send them a nice email about this?

**Comment by jpfeuffer** [comment]
I got a nice reply from their support:

"If the test files are small and it is only a few searches per day, that is fine. Thanks for checking."

**Comment by jpfeuffer** [comment]
How do we proceed @hroest ?

**Comment by hroest** [comment]
@jpfeuffer I suggest to turn it on in the nightly tests, either on cdash or in travis. What do you think makes more sense?

**Comment by jpfeuffer** [comment]
Should be run in the nightlies now. Seems to work.
