### ISSUE TITLE
MRMScoring compile error

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3141]
I get a compile error in method:
https://github.com/OpenMS/OpenMS/blob/3fd677a2d8333a832749b29e32681d45d6cd3d8d/src/openswathalgo/include/OpenMS/ANALYSIS/OPENSWATH/OPENSWATHALGO/ALGO/MRMScoring.h#L148
when a nullptr is returned for the string (before a 0 was returned which is also wrong)

a quick fix would be to return an empty string but the method looks a bit fishy.
@grosenberger can you give this method a quick check? is it really needed? wouldn't returning a double be more appropriate?

**Comment by jpfeuffer** [comment]
Can you see why it was not found in CI or nightlies?

**Comment by timosachsenberg** [comment]
maybe because I use clang 7. 
Before, the method it returned 0 converted to a string. Probably interpreted as (char* = 0) and converted to the empty string. Then I merged the nullptr changes by clang-tidy.
Seems that this now triggers a compile error.
