### ISSUE TITLE
Python_Executable Cmake variable ignored?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3142]
Could this be the case? It somehow always takes /usr/bin/python. Although the Variable is clearly set in the cmakecache.
It could be overwritten by the find_package(Pythoninterp) Command.

**Comment by hroest** [comment]
what exactly did you try? `-DPYTHON_EXECUTABLE:FILEPATH=` is the canonical way of specifying the Python executable. Did you forget about "FILEPATH" maybe?

**Comment by jpfeuffer** [comment]
I was trying to set it via writing it to the CMakeCache. Yes I indeed forgot the FILEPATH. I will try again and set it even earlier in the script.

**Comment by jpfeuffer** [comment]
Yes I think writing it to the cache earlier and adding FILEPATH worked. Sorry for the fall alarm.
