### ISSUE TITLE
Tools scripts not compatible with Python 3

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3144]
I was trying to build pyOpenMS on Windows and tried to run the PythonChecker.
Since I was using python3 as the PYTHON_EXECUTABLE I just used that for the checker, too. There I noticed that it of course was written for python2.
Now just the question how we should go about this? Especially with a virtualenv e.g. to keep build machines clean, it would be nicer to be able to use the same python interpreter/virtualenv for the scripts. Which probably means that we have to duplicate all the scripts with py3 versions?
What do you think?

**Comment by hroest** [comment]
well I guess we have to bite the bullet at some point and rewrite it for Python3
