### ISSUE TITLE
pyOpenMS failing on Windows

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3151]
http://cdash.openms.de/viewBuildError.php?buildid=253119
@hroest Do I have to build OpenMS statically for pyOpenMS? Why does it look for the lib file?

Have you seen the below error before?
`1>pyopenms/pyopenms_2.cpp(36150): error C3431: 'RTUnit': a scoped enumeration cannot be redeclared as an unscoped enumeration [C:\jenkins\ws\openms_nightly_packaging\c2e226b2\build\src\pyOpenMS\pyopenms.vcxproj]`
But let's try to fix the first one first.. not sure if they are related.

**Comment by hroest** [comment]
have you tried to look at https://github.com/OpenMS/OpenMS/wiki/Build-pyOpenMS-on-Windows ? I am pretty sure that you should be able to build 2.2 as I was successful doing it following these instructions last time. 

the last time I compiled pyOpenMS successfully was last summer after I introduced the split build (e.g. August 2017)

**Comment by hroest** [comment]
maybe you can try and remove the code I introduced here 8045c59bcba1001aaa0e494d9739b9f552c4189b and the RTUnit error goes away?

**Comment by jpfeuffer** [comment]
Ah hm could be nmake vs VS generator then. I guess that is the only difference. I can have a look.

**Comment by jpfeuffer** [comment]
Ok seems like VS puts the corresponding include libraries "*.lib" into build / src / openms / $CONFIG /. Which is not considered in setup.py https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/setup.py#L109
But maybe we should put the libs together with the dlls anyway by setting CMAKE_ARCHIVE_OUTPUT_DIRECTORY. Have to see if it breaks anything else though.

**Comment by jpfeuffer** [comment]
See #3156 
Somehow the RTUnit errors are gone..

**Comment by hroest** [comment]
great, does it now work on your system with this patch? If so we can just merge as its only Python

**Comment by jpfeuffer** [comment]
I needed another patch. #3164 
This needs another fix for the tests though.
I also get an error
```
ERROR: test_spectrum (unittests.test_DIAScoring.TestDIAScoring)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\jenkins\ws\openms_nightly_packaging\c2e226b2\build\pyOpenMS\tests\uni                      ttests\test_DIAScoring.py", line 35, in test_spectrum
    p_dia.setValue("dia_extraction_unit", "Th");
  File "pyopenms\pyopenms_8.pyx", line 6683, in pyopenms.pyopenms_8.Param.setVal                      ue
Exception: can not handle type of ('dia_extraction_unit', 'Th')
```
And three FileIO ones when I run nose.

**Comment by jpfeuffer** [comment]
Ok compiles on Windows now. The errors above persist.
But the pychecker doesn't run because the doc_xml target does not build. There is an Access Violation reported by doxygen.

**Comment by jpfeuffer** [comment]
Was a doxygen bug. After upgrade the xml docu builds. I think there are some false positive warnings now. I will add them to ignore. Pychecker still seems to have problems.

**Comment by hroest** [comment]
> Pychecker still seems to have problems.

can you send me a log and we can have a look at them

**Comment by jpfeuffer** [comment]
`C:\jenkins\ws\openms_nightly_packaging\c2e226b2\pyopenms_venv\lib\site-packages\wheel\pep425tags.py:75: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect`
`C:\jenkins\ws\openms_nightly_packaging\c2e226b2\pyopenms_venv\lib\site-packages\wheel\pep425tags.py:79: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect`

I get this when building the wheel. Is this severe or should I add it to ignore?

**Comment by jpfeuffer** [comment]
```
importing breathe.parser.doxygen.compound failed, try new API
Found 2606 doxygen xml files
Creating pxd file map
Found 459 matching pxd files
Unknown namespace eol_bspline::BSpline
```
And this is the error for the pyChecker on win. With Python 3.5. The venv is here:
https://abibuilder.informatik.uni-tuebingen.de/jenkins/view/OpenMS/job/openms_nightly_packaging/compiler=msvc-14,os_label=win10_64/ws/pyopenms_venv/Lib/site-packages/

**Comment by jpfeuffer** [comment]
Ok checked the breathe git. Starting from 4.2.0, the doxygen subfolder was removed. The parser is under breathe.parser.compound.

**Comment by hroest** [comment]
yes, the package did change and I therefore try to support both API, I have version 4.6.0 working here

**Comment by jpfeuffer** [comment]
Seems like the CMake script does not capture / nor forward the error output properly:
```
Traceback (most recent call last):
  File "source/tools/PythonExtensionChecker.py", line 1164, in checkPythonPxdHea                                            der
    pxd_class = PXDFile.parse_multiple_files(pxdfiles, comp_name)
  File "source/tools/PythonExtensionChecker.py", line 720, in parse_multiple_fil                                            es
    raise PXDFileParseError(error_str)
__main__.PXDFileParseError: Could not find a match for class OpenMS::IDFilter::P                                            eptideDigestionFilter in file source\src/pyOpenMS/pxds\IDFilter.pxd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "source/tools/PythonExtensionChecker.py", line 1229, in <module>
    main(options)
  File "source/tools/PythonExtensionChecker.py", line 1208, in main
    options.generate_pxd, options.verbose)
  File "source/tools/PythonExtensionChecker.py", line 1168, in checkPythonPxdHea                                            der
    msg = "Skip:: No-pxd :: " + e.message + " for %s (in pxd file %s)" % (comp_n                                            ame, pxdfiles)
AttributeError: 'PXDFileParseError' object has no attribute 'message'
```

**Comment by jpfeuffer** [comment]
> RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Can you comment on these errors I mentioned before @hroest ? I don't know much about their severity.

**Comment by hroest** [comment]
@jpfeuffer can we close this issue?
