### ISSUE TITLE
Bug in TransitionTSVFile not reading the protein name

### ISSUE THREAD

**Issue by bretttully** [OpenMS/OpenMS#3172]
Looking at lines 373 and 374 in comparison with other lines around them -- should they have a `!extractName` (note the `!`)? Adding this in means that the protein name will be read when it is called `ProteinId`. 

https://github.com/OpenMS/OpenMS/blob/6edaa6492cd6d50d5e6e677e0df576d641bdba08/src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp#L373

cc @hroest

**Comment by bretttully** [comment]
This also means that when running the `TargetedFileConvertor` converting tsv to pqp the ProteinId is not copied across

**Comment by grosenberger** [comment]
Thank you, indeed this is a bug. This should be fixed in the PR linked below.
