### ISSUE TITLE
Feature request: viewer for sequence coverage

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#3174]
In TOPPView, it would be great if the sequences of identified proteins could be visualized, highlighting the parts that are covered by identified peptides and giving the percentage coverage.

**Comment by cbielow** [comment]
Is there another software package which can accomplish this? We could just export the positional information straight from PeptideIndexer and be done.

**Comment by jpfeuffer** [comment]
I guess PRIDEInspector can.

**Comment by jpfeuffer** [comment]
But one thing that would be nice is an actual correct coverage calculation (in IdXML). I think this is not yet fully implemented.

**Comment by hendrikweisser** [comment]
> But one thing that would be nice is an actual correct coverage calculation (in IdXML). I think this is not yet fully implemented.

We have `ProteinIdentification::computeCoverage`, and I hope that it's correct (looks like it can deal with overlapping sequences):
https://github.com/OpenMS/OpenMS/blob/265a9b6b1834b2e66b1ceb5271a1a78acd6b4cd2/src/openms/source/METADATA/ProteinIdentification.cpp#L339

**Comment by jpfeuffer** [comment]
Aah sorry. Exactly the overlap handling was what I thought was missing. Maybe there were some inconsistencies with certain tools that I remembered.

**Comment by hendrikweisser** [comment]
@cbielow: The point of this would be to make TOPPView more useful for reviewing identification results (of RNAs, in our case). It would be good to know if there's a separate (stand-alone) tool that can do this, but having the functionality in TOPPView would be better.

**Comment by jpfeuffer** [comment]
This is available now.
