### ISSUE TITLE
FeatureFinder(Centroided) does not complain on 0 intensity peaks but just performs poorly

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3193]
See discussion on Gitter https://gitter.im/OpenMS/OpenMS?at=5a65f971ae53c159031ce9d8

**Comment by jpfeuffer** [comment]
In general after looking at the code I think FFC needs to be improved to handle edge cases better or throw better exceptions.

**Comment by jpfeuffer** [comment]
Also an issue seems to be that TOPPView does not load features with negative intensities. Maybe it should give warnings instead. Or the feature finders should not print them out. Although with the absolute value it might be solved. Affected features look good by the way. Ones that were negative before are in the range of surrounding features with similar intensity profiles.

**Comment by IceFreez3r** [comment]
Old issue, but is probably now fixed: #4652
