### ISSUE TITLE
pyOpenMS 2.3 for macOS

### ISSUE THREAD

**Issue by grosenberger** [OpenMS/OpenMS#3202]
Hi all,

I built the release version of pyOpenMS 2.3 for macOS in Python 2.7 and 3.6 flavors. Before we push this to PyPI, would anybody have a chance to test this on their system?

Thanks for your help!

[pyopenms-2.3.0-cp27-cp27m-macosx_10_12_intel.whl.zip](https://github.com/OpenMS/OpenMS/files/1674393/pyopenms-2.3.0-cp27-cp27m-macosx_10_12_intel.whl.zip)

[pyopenms-2.3.0-cp36-cp36m-macosx_10_12_x86_64.whl.zip](https://github.com/OpenMS/OpenMS/files/1674396/pyopenms-2.3.0-cp36-cp36m-macosx_10_12_x86_64.whl.zip)

**Comment by jpfeuffer** [comment]
For the 3.6 version:
```
Determination of memory status is not supported on this
 platform, measuring for memoryleaks will never fail


======================================================================


maybe you miss some libraries. please run ldd (on linux) or
dependency walker (on windows) on


/Users/pfeuffer/.virtualenvs/py3pyOMSTesting/lib/python3.6/site-packages/pyopenms/pyopenms.so


======================================================================


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pfeuffer/.virtualenvs/py3pyOMSTesting/lib/python3.6/site-packages/pyopenms/__init__.py", line 52, in <module>
    raise e
  File "/Users/pfeuffer/.virtualenvs/py3pyOMSTesting/lib/python3.6/site-packages/pyopenms/__init__.py", line 22, in <module>
    from .all_modules import *
  File "/Users/pfeuffer/.virtualenvs/py3pyOMSTesting/lib/python3.6/site-packages/pyopenms/all_modules.py", line 1, in <module>
    from .pyopenms_1 import *
ImportError: dlopen(/Users/pfeuffer/.virtualenvs/py3pyOMSTesting/lib/python3.6/site-packages/pyopenms/pyopenms_1.cpython-36m-darwin.so, 2): Library not loaded: /Users/gr2578/Downloads/py36/lib/libOpenMS.dylib
  Referenced from: /Users/pfeuffer/.virtualenvs/py3pyOMSTesting/lib/python3.6/site-packages/pyopenms/pyopenms_1.cpython-36m-darwin.so
  Reason: image not found
```

**Comment by jpfeuffer** [comment]
Seems like it still points to your local paths for the dylibs.
Did the install_name_tool routine run through successfully?

**Comment by grosenberger** [comment]
Thanks for testing. There seems to be a bug in the macOS patching script and I will make PR. Could you please test the updated packages again?
[pyopenms-2.3.0-cp27-cp27m-macosx_10_12_intel.whl.zip](https://github.com/OpenMS/OpenMS/files/1767553/pyopenms-2.3.0-cp27-cp27m-macosx_10_12_intel.whl.zip)
[pyopenms-2.3.0-cp36-cp36m-macosx_10_12_x86_64.whl.zip](https://github.com/OpenMS/OpenMS/files/1767556/pyopenms-2.3.0-cp36-cp36m-macosx_10_12_x86_64.whl.zip)

**Comment by jpfeuffer** [comment]
Yes, both work now. Tested rudimentary file loading.

**Comment by jpfeuffer** [comment]
By the way, can we require numpy somehow, so that pip installs it as dependency?

**Comment by jpfeuffer** [comment]
I needed to do that beforehand.

**Comment by grosenberger** [comment]
Great, thanks for testing! @hroest, could you please push the two packages to PyPI? Regarding the numpy dependency, we should be able to include this in the `setup.py` file.

**Comment by hroest** [comment]
ok, its online https://pypi.python.org/pypi/pyopenms/2.3.0

**Comment by grosenberger** [comment]
Excellent, thank you very much!

**Comment by jpfeuffer** [comment]
I'll open a new issue for the numpy dependency.

**Comment by tabaspki** [comment]
Hi all,

I just installed pyopenms 3.6.0 on my mac (version 11.1) using Python 3.8 through pip, and I'm having this exact same issue:
`Determination of memory status is not supported on this 
 platform, measuring for memoryleaks will never fail`

Any help on this?

Thanks

**Comment by jpfeuffer** [comment]
This is just a warning, you can ignore it. The troublesome part was the subsequent lines. Are you getting them, too?

**Comment by tabaspki** [comment]
You're right, I only get the warning, not the error.

**Comment by amnahsiddiqa** [comment]
Hi I get the same error on Mac ;

`Determination of memory status is not supported on this 
 platform, measuring for memoryleaks will never fail
/Users/runner/work/OpenMS/OpenMS/OpenMS/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(107): While loading 'mzML/MT_20210801_015_chrom.mzML.xz': exceeded byte limit at byte '�' in a 6-byte sequence( in line 1 column 1)
Traceback (most recent call last):
  File "process_masstraces_mzlist_AS.py", line 60, in <module>
    L = chromatograms2mz( os.path.join(DIR, f) )
  File "process_masstraces_mzlist_AS.py", line 34, in chromatograms2mz
    MzMLFile().load(infile, exp)                                                                            
  File "pyopenms/pyopenms_6.pyx", line 4554, in pyopenms.pyopenms_6.MzMLFile.load
RuntimeError: - due to that error of type Parse Error in: /Users/runner/work/OpenMS/OpenMS/OpenMS/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp@108-void OpenMS::Internal::XMLHandler::fatalError(OpenMS::Internal::XMLHandler::ActionMode, const OpenMS::String &, OpenMS::UInt, OpenMS::UInt) const`

**Comment by jpfeuffer** [comment]
As mentioned above, the first sentence is just a warning that always occurs on macOS and can be ignored. The rest of the message displays the problem. Please open another issue for that. (From the file ending "xz" it is probably an unsupported compression software; try to unzip it first).

**Comment by amnahsiddiqa** [comment]
Thanks. It worked with mzML file.
