### ISSUE TITLE
QT5: TOPPAS open online repository/tutorial/etc. doesn't work

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3208]
we removed qtwebkit dependency (and really don't want this dependency back).

**Comment by jpfeuffer** [comment]
They have Webengine and Webview now. Which seem to be more tightly integrated, maintained and more easily deployed.

**Comment by timosachsenberg** [comment]
they are also pretty big. I would prefer just opening the webpage via finder / explorer
