### ISSUE TITLE
Status of IDEvaluator

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3215]
I am currently updating packaging for QT5. Everything seems to work except
IDEvaluator and IDEvaluatorGUI.
They need GUI libraries but are not bundled as apps.
To work, the non-GUI version should not have dependencies on GUI libraries and the GUI one should go into an app.

Is anyone using this?
@cbielow you are the maintainer and author.

**Comment by timosachsenberg** [comment]
According to update statistics it is not used at all.
I would vote for remove.

**Comment by timosachsenberg** [comment]
The IDEvaluatorGUI has been executed a few times (~10), though. Still would vote for remove.

**Comment by timosachsenberg** [comment]
QCoreApplication would not be enough I guess?

**Comment by jpfeuffer** [comment]
It's solved by some weird QT library path magic in the code. Since our additional path is only added it should interfere with personal paths (that only experts would set) and is only needed for shipping.
Nonetheless I do not like that TOPP tools depend on OpenMS_GUI. I removed all of them from the KNIME packaging now btw.

**Comment by cbielow** [comment]
we can remove the tools. The functionality can easiliy be reproduced with a few lines of R code.

**Comment by hroest** [comment]
so it seems this is a packaging issue only, should we just remove it from packaging or from the code completely? It seems @cbielow is arguing to remove them completely?

**Comment by timosachsenberg** [comment]
it has been removed
