### ISSUE TITLE
Toppview goes black when switching to 3D view for a second time

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3216]
Branch: `feature/qt5` ae0baaf40e51b359b2565873457e7e3b8b69f329
System: Linux

Problem: Toppview goes black when switching to 3D view for a second time
Reproduce problem: 
- Open TOPPView, select 2D view
- Right click, click "open 3D view"
- Go back to previous tab
- Right click, click "open 3D view"
- Result: black window, no work possible

![toppview](https://user-images.githubusercontent.com/464014/35651918-6b3ade54-06af-11e8-9c68-19e2528b3fae.png)

**Comment by jpfeuffer** [comment]
Interesting. Can't confirm on Mac.

**Comment by timosachsenberg** [comment]
can't confirm on Linux.

**Comment by timosachsenberg** [comment]
Qt issues sometimes a warning that the paint device is not ready. I check this now explicitly and the warning goes away. https://github.com/OpenMS/OpenMS/pull/3217
Might be (probably not) connected to this issue

**Comment by hroest** [comment]
definitely something weird going on here, I still have this issue on the newest branch. However I see a difference on Linux between Intel and NVIDIA gpu, on Intel I see white flickering while on NVIDIA I see black screens. Still while moving the cursor and switching tabs I see a black window:

https://www.dropbox.com/sh/fu87nvwi3z25shf/AACKKq6MzV12RnJh2fHXExWqa?dl=0

**Comment by hroest** [comment]
it seems this is related to the `glEnable(GL_DEPTH_TEST);` call which is called in `paintGL();` and `initializeGL();`
