### ISSUE TITLE
Question: cool (but probably unintended feature) of IdentificationView

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3219]
I just wanted to document @Leon-Bichmann finding a potentially unintended (at least undocumented) feature that is also very cool ;)

To Reproduce;
In TOPPView,open BSA1.mzML, and annotate with identification BSA1.idXML
Open File->BSA2.mzML open as new layer (!)
Flip BSA2.mzML downwards
Annoate BSA2.mzML with BSA2.idXML

You get a view that allows you to directly compare annotated spectra in BSA1.mzML and annotated spectra in BSA2.mzML.
A great application is the comparison of peptide spectra with their synth-pepitde spectra.

![image](https://user-images.githubusercontent.com/5803621/35684275-ab89d7dc-0766-11e8-944e-c7dd134d4f3a.png)

**Comment by timosachsenberg** [comment]
might be of interest to @hendrikweisser and @enetz

**Comment by jpfeuffer** [comment]
Very nice! Well then this issue should be about documenting it or maybe make it more easily accessible (e.g. with a selection and Right-click -> compare)

**Comment by timosachsenberg** [comment]
I agree!
For the identification view, we could rethink/replace the layer widget. 
Maybe something that displays the primary mzML file + current annotation spectrum like we do now.
But optionally, the user can add a second mzML + idXML for spectra vs spectra comparison? 
Including displaying another "annotation layer" for the second file.

It would also be then more convenient to split the table of spectra in half (if the second file is provided) to easily navigate both files.

Something in that lines...

**Comment by timosachsenberg** [comment]
actually, the splitting would also be great for the default "Spectra View". Here opening another layer doesn't allow to select any other spectrum except the first.

**Comment by hroest** [comment]
another nice visualization could be something along the lines of what the TPP uses: https://db.systemsbiology.net/sbeams/cgi/PeptideAtlas/ShowConsensusSpectrum?consensus_library_spectrum_id=245327;ymax=11000

basically have a different color for matching ions and make the rest grey

**Comment by hendrikweisser** [comment]
> basically have a different color for matching ions and make the rest grey

That's unfortunately not possible at the moment, because there can be only one peark colour per layer. See also here: https://github.com/OpenMS/OpenMS/pull/3007#issuecomment-344298798
