### ISSUE TITLE
pyopenms packaging of QT5

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3232]
Since the normal packaging was quite affected by the change to QT5 (with its plugins) someone needs to check if this applies to pyopenms packaging.
Maybe it is only the names.

**Comment by jpfeuffer** [comment]
See here
https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/create_cpp_extension.py#L263
Btw I included static builds for xerces and zlib on win.

**Comment by grosenberger** [comment]
I can take a look at it.

**Comment by hroest** [comment]
it works out of the box for Linux right now, but I havent looked at Windows yet

**Comment by jpfeuffer** [comment]
Yeah right, linux uses system qt. Since mac QTs name is version agnostic, it should work, too.
I guess it is just windows.

**Comment by hroest** [comment]
still, the docker files will be impacted and the automated wheel build

**Comment by sagitter** [comment]
@jpfeuffer 

>Since the normal packaging was quite affected by the change to QT5 (with its plugins) someone needs to check if this applies to pyopenms packaging.

What commit do you need testing?

**Comment by jpfeuffer** [comment]
Since we did not have any complaints since then, I guess it is fine.
