### ISSUE TITLE
Add VS user config files or target properties to tests on Win

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3241]
So that dlls like OpenMS, OpenSwath, QT are found right away and one does not have to manually
readd this in VS after every CMake generation step.

Just a thought that I had when debugging on the build machines.

**Comment by cbielow** [comment]
what exactly is the problem?
Building or running the tests?

**Comment by jpfeuffer** [comment]
Running tests and debugger
