### ISSUE TITLE
Private Thirdparty tests

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3244]
I added Msfragger and novor to the nightlies but they fail. On win the allocated jvm memory is probably too high for both. For Mac/Linux there are some differences in the results like missing search engine parameters. Not sure what XTandem is doing there.

**Comment by hroest** [comment]
thanks, that would be great to have as nightly test.

**Comment by jpfeuffer** [comment]
Ok novor should be solved. What about MSFragger @lukaszimmermann ?
```
Offending lines:			(tab_width = 8, first_column = 1)

in1:  /Users/builder/jenkins/ws/openms_nightly_packaging/4a4a5dc9/build/src/tests/topp/MSFraggerAdapter_7_out_tmp.pepXML   (line: 4, position/column: 75/76)
<msms_run_summary base_name="spectra" raw_data_type="raw" raw_data=".mzXML"!
                                                                           >

in2:  /Users/builder/jenkins/ws/openms_nightly_packaging/4a4a5dc9/source/src/tests/topp/THIRDPARTY/MSFraggerAdapter_7_out.pepXML   (line: 4, position/column: 75/76)
<msms_run_summary base_name="spectra" raw_data_type="raw" raw_data=".mzXML"!
                                                                            search_engine="X! Tandem">


Easy Access:
/Users/builder/jenkins/ws/openms_nightly_packaging/4a4a5dc9/build/src/tests/topp/MSFraggerAdapter_7_out_tmp.pepXML:4:76:
/Users/builder/jenkins/ws/openms_nightly_packaging/4a4a5dc9/source/src/tests/topp/THIRDPARTY/MSFraggerAdapter_7_out.pepXML:4:76:
```

**Comment by oliveralka** [comment]
Maybe related to this:
"X!Tandem as the search engine in pepXML output
Peptide validation tools do not currently have support for MSFragger so MSFragger masquerades as X!Tandem for compatibility with tools like PeptideProphet. As the hyperscore calculated by MSFragger is slightly different than that of X!Tandem, this may be suboptimal in certain situations. We hope to change this in the future once there is support for MSFragger in peptide validation tools." - http://www.nesvilab.org/msfragger.html

**Comment by hroest** [comment]
@jpfeuffer can we close this?

**Comment by jpfeuffer** [comment]
Almost. Or yes, for now. So, the only problem left is the memory allocation for MSFragger. We talked to the devs and they hardcoded 2.4GB as minimum jvm mem (no matter how small the file). Somehow our Windows VM seems to have problems allocating it from time to time (although it has 8gig). We deactivated the test for now.
