### ISSUE TITLE
MzTab export for quantitative data not compatible with PRIDE

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3248]

**Comment by sureshhewabi** [comment]
In your mzTab peptide section, some data are missing for certain columns. Number of peptide headers should be equal to number of data columns. For example, in https://raw.githubusercontent.com/timosachsenberg/OpenMS/feature/PQmzTab/t.mzTab file, it has 43 fields in the header(line number 506), but it has only 41 data values in the first row of the peptide table (line number 507).

Secondly, Peptide header in line number 506 has a field called "Probability_score", which does not match with the mzTab specification. If you need to introduce as a optional field, then please prefix with "opt_". For more details, please refer following link: https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-releases/version-1.0.0/20minute_guide_mzTab.pdf 
(Page 6)

**Comment by timosachsenberg** [comment]
Thanks for your feedback. I will address these issues in my branch...

**Comment by timosachsenberg** [comment]
Ok, these issues should be fixed and I updated the test file:
https://github.com/timosachsenberg/OpenMS/blob/feature/PQmzTab/t.mzTab
Would be great if you could run it through the validator again.

**Comment by sureshhewabi** [comment]
Thanks, I have re-validated your modified file and I found another issue which is Modifications should be reported in Uppercase. For example, in peptide section, Modification field of line number 521 has a value "0-UniMod:28" which should be "0-UNIMOD:28". I guess there are few more errors, which I will get back to you soon

**Comment by timosachsenberg** [comment]
Thanks! Fixed in my local branch.

**Comment by sureshhewabi** [comment]
Issue No: 4

I found that `ms_run[1..n]_location` metadata (in line number 24-26) refers to the raw files which are not allowed. It should be mzML in your case.

I tried to replace them with the mzML files you send me, however it fails. In PSM table, spectra_ref (for example, `ms_run[3]:controllerType=0 controllerNumber=1 scan=6120`) should refer to the spectra file and the spectra location.

**Comment by timosachsenberg** [comment]
1. this is a known issue and will be adresed.

2. how does spectra_ref fail? is there no scan 6120? This is the native id as specified by thermo

**Comment by ypriverol** [comment]
@timosachsenberg @sureshhewabi the mztab file should contains the format of the reference to the spectra: 
```
MTD ms_run[1]-format [MS, MS:1001062, Mascot MGF file, ]
MTD ms_run[1]-id_format [MS, MS:1000774, multiple peak list nativeID format, ]
```
The format defines the type of the file-format, the id_format is the type of the reference. This is missing in the current example.

**Comment by timosachsenberg** [comment]
ok I see! thanks for clarifying

**Comment by sureshhewabi** [comment]
as you have mzML files, you need to add following:
MTD	ms_run[1]-format	[PSI-MS, MS:1000584, mzML file, ]
MTD	ms_run[2]-format	[PSI-MS, MS:1000584, mzML file, ]
MTD	ms_run[3]-format	[PSI-MS, MS:1000584, mzML file, ]

MTD	ms_run[1]-id_format	[PSI-MS, MS:1000768, Thermo nativeID format, ]
MTD	ms_run[2]-id_format	[PSI-MS, MS:1000768, Thermo nativeID format, ]
MTD	ms_run[3]-id_format	[PSI-MS, MS:1000768, Thermo nativeID format, ]

**Comment by timosachsenberg** [comment]
Thanks. Yes, that is useful information. @ypriverol let's make this mandatory in the next mzTab-P

**Comment by timosachsenberg** [comment]
@sureshhewabi would it be possible to add these lines to the mzTab file and run the validation again? just to see if there are other errors before I get back to that?

**Comment by sureshhewabi** [comment]
I fixed those lines and files got validation. However it has to be verified with our submission pipeline. Once I validate it through submission pipeline, I will get back to you.

**Comment by timosachsenberg** [comment]
Sounds awesome. I think that is an important step forward. Let me know if validation fails and I can fix the issues

**Comment by sureshhewabi** [comment]
Issue no: 5

Missing title in mzTab metadata section. Eg:
MTD    title    YourTitleHere

Test submission is in progress..

**Comment by timosachsenberg** [comment]
Hi @sureshhewabi the title is not mandatory. Can you confirm that this is required for the submission or maybe an oversight in your submission tool?
(It's no problem to add it on my side - just want to check if this is really mandatory from the PRIDE side)

**Comment by sureshhewabi** [comment]
Unfortunately, You need to add the metadata - title to upload the mzTab file via PX submission tool and it is required for the submission. I think we need to update the mzTab specification and make it mandatory. 

After fixing the 5 issues I mentioned above, mzTab file(and mzML) got successfully validated.

**Comment by lars20070** [comment]
@sureshhewabi Is there a place to collect updates to the `mzTab` specification?
Say for a future `mzTab 1.1`.

**Comment by timosachsenberg** [comment]
https://github.com/HUPO-PSI/mzTab

**Comment by lars20070** [comment]
@timosachsenberg Let's see if more [proposals](https://github.com/HUPO-PSI/mzTab/wiki/mzTab-improvement-proposals) will come up.

**Comment by timosachsenberg** [comment]
maybe better to put this in an issue instead of the wiki. easier to track

**Comment by lars20070** [comment]
Maybe a label for specification updates would be helpful. But I guess only you can add one.

**Comment by jpfeuffer** [comment]
As far as I know we are PRIDE compatible by now. Reopen if something else shows up.
