### ISSUE TITLE
CruxAdapter issues

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3252]
- When running percolator, the merging of target and decoy does not work. Decoys are appended as empty protein hits. (see the second one in the example, it is the border between targets and decoys)
```
			<ProteinHit id="PH_1651" accession="CON_A2AB72" score="0" sequence="YETELALR" >
				<UserParam type="string" name="isDecoy" value="false"/>
			</ProteinHit>
			<ProteinHit id="PH_1652" accession="" score="0" sequence="" >
			</ProteinHit>
```
Reason might be https://github.com/OpenMS/OpenMS/blob/develop/src/topp/CruxAdapter.cpp#L439 does not behave as was expected when called multiple times.
- No information about the tools is written to mzID. We need it to fill the type of "search_engine".
- Same holds for the database in our "db" field. I think these two should be read from the mzID ideally but until they fix their mzID, I think we have to add it manually.
- Not sure if we should deviate from other search engines and by default append a decoy database.
- Maybe for consistency we should use our UNIMOD modifications as a selection. We can still have a parameter for additional free-type modifications that will be appended.

**Comment by jpfeuffer** [comment]
One huge problem that confuses our parser is that in the mzID of the Crux-Percolator output they only put the sequence of the hit into the DBSequence object, which is wrong. Maybe it is the same for the tide-search output.

**Comment by jpfeuffer** [comment]
Sometimes ProteinHits occur twice. Sometimes ProteinHits have no decoy annotation. I mean it is not so bad if your run PeptideIndexer on top. But you can not do this if you e.g. create an intermediate decoy database with crux (which brings us to one of the other mentioned issues).

**Comment by jpfeuffer** [comment]
I also found that tide-search ignores the decoy-prefix when writing the mzID. Everything is assigned to be a target. Maybe decoy-prefix was only designed to work with "decoy-format != none"?

**Comment by jpfeuffer** [comment]
I think this issue might need too much work for this release. But until this is resolved you always need peptideindexer afterwards and cant use the Percolator option inside crux but need to run Percolator separately.

**Comment by timosachsenberg** [comment]
anyone who wants to take over that issue for the 2.4 release? otherwise we postpone it to milestone 2.5

**Comment by poshul** [comment]
This is still open and marked critical what is the state of it?

**Comment by jpfeuffer** [comment]
I think the adapter is very limited in its capabilities with these problems. I would not recommend its usage to anyone. Would be a nice option in my opinion but it is more complex than other adapters due to its "multitool" nature.
Maybe we should strictly warn against the usage or even hide it somehow.

**Comment by poshul** [comment]
moot by https://github.com/OpenMS/OpenMS/pull/6230
