### ISSUE TITLE
Trouble Averaging Many scans into a single scan.

### ISSUE THREAD

**Issue by WaqasAwan00** [OpenMS/OpenMS#3256]
Not sure if this is the proper place to ask questions, but here goes:
I am having trouble trying to average together consecutive scans in a single .mzML file. I have around 300 individual indices and putting this single file through the SpectraMerge block (using averageGaussian or otherwise) does not seem to generate a single index, but rather the same number of indices with numbers being altered.
Is there a way to average together many scans into a single spectra using the workflow?
This is the workflow I am using:
![image](https://user-images.githubusercontent.com/34248727/36395287-76e597cc-1586-11e8-80e2-675d22df40c5.png)
And this is the resulting output:
![image](https://user-images.githubusercontent.com/34248727/36395300-84ec6436-1586-11e8-9146-38d752b93c39.png)
As you can see, there is still the entire set of scans in the final file. Any help would be appreciated.

**Comment by lars20070** [comment]
Please try
```
merging_method = block_method
```
The first two methods (`average_gaussian` and `average_tophat`) are *moving averages* for smoothing in RT direction, i.e. the number of spectra remains constant. On the other hand `block_method` and `precursor_method` combine multiple spectra to a single one.

**Comment by WaqasAwan00** [comment]
It was a bit confusion at first but now I get it, thanks so much!
