### ISSUE TITLE
Combine traML transition lists

### ISSUE THREAD

**Issue by eseble** [OpenMS/OpenMS#3257]
Hi,
I have two traML transition lists that I would like to combine into a consensus one. Is this possible? 

Best wishes,

Edith

**Comment by hendrikweisser** [comment]
Have you tried the FileMerger tool (https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_FileMerger.html)?

**Comment by eseble** [comment]
Does this tool concatenate the files? or does it create a new consensus one with no repeated transitions?

**Comment by hendrikweisser** [comment]
I don't know. @hroest or @grosenberger should know.
Or you could just try it and report back.

**Comment by grosenberger** [comment]
Hi Edith,

Unfortunately we don't support such a workflow yet. If you used SpectraST for library generation, I would use the sophisticated merging and consensus library generation tools provided there. Alternatively, it might be an option to convert the TraMLs to TSV transition lists, merge them in Skyline and reconvert the list back to TraML.

**Comment by hroest** [comment]
Yes, the current file merger is only able to concatenate TraML files but does not perform any further computation on it. As @grosenberger said, we suggest to use SpectraST for the purpose of consensus library generation.
