### ISSUE TITLE
SpectraMerge Creating Large files

### ISSUE THREAD

**Issue by mafreitas** [OpenMS/OpenMS#3259]
Using SpectraMerge in Release 2.3.0 creates mzML files ~5X larger than the originals.  I am using the command with default options on a Q-Exactive SILAC data set.  Any suggestions? I can share an expt file if that would help.

**Comment by timosachsenberg** [comment]
@lars20070 I think this might be related to some interpolation code Lars added while ago. Right?

**Comment by lars20070** [comment]
@mafreitas By default, the `SpectraMerger` uses the `average_gaussian` method. The number of spectra remains constant, but the spectra are smoothed in RT direction with a moving window with a Gaussian profile. In *Q Exactive* data it is often the case that you have peaks in one spectrum which are totally absent in the neighbouring spectra. Such a  peak then *"bleeds"* into the neighbouring spectra, i.e. totally new peaks are introduced. If this happens with two spectra above and two below, you get a factor 5x.

They point is to fill in *missing* MS1 peaks before [feature detection](https://www.dropbox.com/s/0275v59zinfs38o/2651C77C-D219-4DC9-91EA-1A1D315EA24B.pdf?dl=1). An updated version of the feature detection will look into neighbouring spectra automatically, making RT smoothing superfluous.

**Comment by mafreitas** [comment]
Great explanation.  Thanks so much for the reply.  For now we will take it out of the workflow.
