### ISSUE TITLE
PyOpenMS installation windows 10

### ISSUE THREAD

**Issue by Berni133** [OpenMS/OpenMS#3260]
I tried to install pyopenms  with pip install pyopenms on two different windows 10 PCs. 
I always got the same error massage:

Collecting pyopenms
Could not find a version that satisfies the requirement pyopenms (from versions: 2.3.0.linux-x86_64, 2.3.0.1.linux-x86_64, 2.3.0.2.linux-x86_64, 2.3.0.3.linux-x86_64)
No matching distribution found for pyopenms

Thanks

**Comment by jpfeuffer** [comment]
Which Python version do you use?

**Comment by Berni133** [comment]
I´m using Python 3.6.2

C:\Users\retzl>python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by hroest** [comment]
>  Python 3.6.2 (v3.6.2:5fd33b5, Jul 8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32

yes, we do not support 32 bit versions on Windows any more.

can you try and install older versions, e.g. 

```
pip install pyopenms==2.2.0
pip install pyopenms==2.1.0
pip install pyopenms==2.0.1
pip install pyopenms==2.0.0
```

**Comment by hroest** [comment]
Note that the last version where we had full support for 32bit platforms was for pyOpenMS version 2.1 - have since dropped support for 32bit platforms and for Python 2.7.
