### ISSUE TITLE
Setting OPENMS_DATA_PATH required in OpenMS-2.3.0-Linux.deb

### ISSUE THREAD

**Issue by sneumann** [OpenMS/OpenMS#3280]
Hi, installing `OpenMS-2.3.0-Linux.deb` on Ubuntu17.10 
I need to manually set `OPENMS_DATA_PATH=/usr/share/OpenMS`.
Users might expect e.g. `FileInfo` to just work. This issue could be related to #1479.
Yours, Steffen

**Comment by jpfeuffer** [comment]
Yes you are right and it is on our list. I have to look up if and how a deb package can do e.g. postinstall commands and how we get it into our build system.

**Comment by jpfeuffer** [comment]
In the long term we also wanted to get rid/reduce the dependency on this Share path being set, I think.

**Comment by jpfeuffer** [comment]
https://askubuntu.com/questions/652151/adding-path-to-path-environment-variable-using-bash-script-in-etc-environment
https://cmake.org/pipermail/cmake/2009-October/032669.html

(for further reference for myself)

**Comment by cbielow** [comment]
i vaguely remember that we had a check for default locations such as `/usr/share/OpenMS`... I assume that would solve the problem with negligible extra effort (for standard installations)

**Comment by jpfeuffer** [comment]
The above fix should even work after relocation now since it uses a relative path from the binary that is called. We probably have to test it with the nightly installer though.

**Comment by sneumann** [comment]
You might want to have a cookie value in the binaries and a matching file with the same cookie in the `OPENMS_DATA_PATH`,
to give a warning if the binary and shared data are from different sources (https://github.com/OpenMS/OpenMS/issues/399)
