### ISSUE TITLE
OpenMS installation on Linux

### ISSUE THREAD

**Issue by eudesbarbosa** [OpenMS/OpenMS#3286]
Hi,

I had some PATH issues while installing openMS on Ubuntu and running TOPPView. See system information and errors below:

# System Summary
  _Percona Toolkit System Summary Report ######################
        Date | 2018-03-06 10:21:45 UTC (local TZ: CET +0100)
    Hostname | eudes
      Uptime | 51 min,  1 user,  load average: 1,40, 0,58, 0,39
    Platform | Linux
     Release | Ubuntu 16.04.3 LTS (xenial)
      Kernel | 4.13.0-36-generic
  Architecture | CPU = 64-bit, OS = 64-bit
   Threading | NPTL 2.23
     SELinux | No SELinux detected
 Virtualized | No virtualization detected
 Processor ##################################################
  Processors | physical = 1, cores = 2, virtual = 4, hyperthreading = yes
      Speeds | 4x2700.000
      Models | 4xIntel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Caches | 4x3072 KB
 Memory #####################################################
       Total | 7.7G
        Free | 474.4M
        Used | physical = 2.9G, swap allocated = 7.9G, swap used = 0.0, virtual = 2.9G
     Buffers | 4.3G
      Caches | 3.9G
       Dirty | 520 kB
     UsedRSS | 5.0G
  Swappiness | 60
 DirtyPolicy | 20, 10
 DirtyStatus | 0, 0_

--
# Installation 

Path Error. I had to manually include the following line on '.bashrc'
_export OPENMS_DATA_PATH="/usr/share/OpenMS/"_

--

# TOPPView 

While trying to convert RAW files...

 **From program**
_11:15:43 ERROR: Error while loading file:
- due to that error of type Parse Error in: /home/jenkins/ws/openms_release_packaging/40c74027/source/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp@111-void OpenMS::Internal::XMLHandler::fatalError(OpenMS::Internal::XMLHandler::ActionMode, const OpenMS::String&, OpenMS::UInt, OpenMS::UInt) const_

**From console**
_/home/jenkins/ws/openms_release_packaging/40c74027/source/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(110): While loading '/media/eudes/68D8-0B87/Example_Data/Introduction/datasets/small/velos005614.mzML': invalid character 0x19( in line 193517 column 1798)_

**Comment by hroest** [comment]
> While  loading  '/media/eudes/68D8-0B87/Example_Data/Introduction/datasets/small/velos005614.mzML':  invalid character 0x19( in line 193517 column 1798)

can you check the file, especially line 193517 whether there is anything special there that cannot be parsed? If there is indeed a character 0x19 in there, then the file is invalid: https://stackoverflow.com/questions/1325379/hexadecimal-0x19-is-an-invalid-character how did you generate the file?

**Comment by cbielow** [comment]
I'm closing this due to lack of further information. Please re-open if its still of interest.
Please provide the installation source and how OpenMS was build (this looks like a package with a wrong install prefix!?)

**Comment by jpfeuffer** [comment]
This was our Debian package. I fixed the standard lookup paths for the OpenMS Data path, so this might be fixed in newer packages.

**Comment by jpfeuffer** [comment]
#3280
