### ISSUE TITLE
MzTab exporter

### ISSUE THREAD

**Issue by jlparkI** [OpenMS/OpenMS#3297]
Hi All,

I would like to take featureXML data (i.e. identified features) from openMS and import them into another program that has some good visualization features I would like to use. This other program will only import peak lists in the form of either MzTab or XML files. In theory that should be straightforward -- just use MzTab exporter. When I have used MzTab exporter, however, it exports the data as a .tsv, not as MzTab, and my other program doesn't recognize it as a valid import.

Any suggestions on how I can take a featureXML and either export it as or convert it to MzTab or XML?

Thanks!
J

**Comment by timosachsenberg** [comment]
Does it work if you change the extension from tsv to mzTab?

**Comment by jlparkI** [comment]
I have tried that, yes, and I still get an error when I try to import, to the effect that:

"MTDpeptide_search_engine_score[1] value "null" is not a valid parameter

MTDpsm_search_engine_score[1] value "null" is not a valid parameter"

**Comment by jlparkI** [comment]
So I think the problem is that this is not REALLY exported in mzTab format and as such is not read-able by other applications that use mzTab.

**Comment by jpfeuffer** [comment]
It seems to be that your program expects that a peptide search engine was run on your data before export.
You can do that with XTandem, OMSSA, ...

**Comment by jlparkI** [comment]
Trouble is it's metabolomics data.

**Comment by timosachsenberg** [comment]
Hi @jlparkI . The current mzTab version (1.0) does not properly support exporting feature information for small molecules. It supports a single table for small molecules summaries though. This will be subject to change in the next version update of MzTab (termed MzTab-M).  
What you could do right now to obtain at least that single small molecule table is is to run the AccurateMassSearch tool on the featureXML. It will produce a mzTab file (parameter  -out <file>*               MzTab file) containing accurate mass search results for your features. Would be interesting to see if this can be parsed by mzmine.

**Comment by jlparkI** [comment]
That makes sense. Looks like the Accurate Mass Search tool is having some trouble as well however. When I run that, it does the adduct finding just fine, then it errors out when it tries to read the Elements.xml file with the following message:

"Unable to read file ('Re' found. Please use only valid element identifiers or modify share/OpenMS/CHEMISTRY/Elements.xml! in: Unknown element 'Re' "

Looking through the Elements.xml file I don't see any invalid elements in there...not sure what happened THERE

**Comment by jpfeuffer** [comment]
I am not sure but it sounds like it is complaining about your input data.
It tries to look up that invalid element but does not find it.
Can you check your input?

**Comment by jpfeuffer** [comment]
Inputs include the featureXML, as well as the database and adducts.
