### ISSUE TITLE
[QT5] pyopenms compilation issue on travis

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3301]
http://cdash.openms.de/viewBuildError.php?buildid=261128
http://cdash.openms.de/viewBuildError.php?buildid=261130

It sometimes just does not find QDate.h. Sometimes restarts help, sometimes they don't.
@hroest Any idea?

**Comment by jpfeuffer** [comment]
I changed the title. I found out that actually all of the failing runs are from the qt5 branch. So it's a qt5 issue. And it seems to occur always.

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/commit/d32a07a8073368f0038e0d6455bda2faac7952b9

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/commit/33a5cede872965bbe6f3903ea8251141d82a366d too

**Comment by jpfeuffer** [comment]
Fixed by the above commits.

**Comment by hroest** [comment]
@jpfeuffer isnt that going to be a problem with newer Qt versions where QDate.h is not  under QtCore, or did I misunderstand something in d32a07a8073368f0038e0d6455bda2faac7952b9 - see http://doc.qt.io/qt-5/qdate.html

**Comment by jpfeuffer** [comment]
Hmm yes. You are right. If we prefix, the header should be found even when it changes the module (as long as we adapt cmake). In this case I don't think it changed why it does not matter. There are other includes like qstring where we use the prefix.
If we use the module prefixes however users would only need one include Path for QT (although we export all of them anyway)
So hmm slightly in favor of changing all of them to non-prefixed.

**Comment by hroest** [comment]
>  So hmm slightly in favor of changing all of them to non-prefixed.

however then we need to find a way to make pyopenms compile for the non-prefixed version

**Comment by jpfeuffer** [comment]
Ah, in the end that did not matter for pyopenms (but the new way of handling QT_INCLUDES).
I kept it for consistency. It was (I think) the only QT include that had no prefix.

**Comment by grosenberger** [comment]
I'm having problems with building pyOpenMS on macOS due to the Qt5 merge with OpenMS/develop. It seems to be related to the added prefix in d32a07a. Are others experiencing the same issues?

**Comment by jpfeuffer** [comment]
Weird. It compiled on travis back then. Feel free to remove it of course if that solves it alone.

**Comment by hroest** [comment]
@grosenberger which Qt version are you using? It seems that the location of QDate.h was changed at some point. We removed the prefix because it did not compile on travis and the include paths were not pointing to the correct folder.

**Comment by grosenberger** [comment]
I'm using the latest Qt version 5.10.1.

**Comment by hroest** [comment]
hmm so it seems like we dont have a version that works on travis and OSX - that is annoying. On Linux it compiles using the current develop version. @jpfeuffer how are our tests servers using OSX configured?

**Comment by grosenberger** [comment]
The problem is resolved with #3318.
