### ISSUE TITLE
What is crawdad and why do we need it?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3303]
See title. And can we get rid of it?

**Comment by hendrikweisser** [comment]
It's used by OpenSWATH in one of the MRM feature detection algorithms. @hroest and @grosenberger should know more.

**Comment by hroest** [comment]
yes its an alternative peak picker also used by Skyline

**Comment by jpfeuffer** [comment]
Ah ok. So it is useful as an alternative. Since it is not a big chunk of code in CMake I'll leave it.
