### ISSUE TITLE
Remove unused code/classes

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#3311]
candidates:
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1PepIterator.html
and subclasses

please add more here. We should have a short discussion during retreat and remove classes or TOPP tools accordingly.

**Comment by timosachsenberg** [comment]
Inspect et al.

**Comment by timosachsenberg** [comment]
maybe superhirn

**Comment by timosachsenberg** [comment]
replace BinaryComposeFunctionAdapter.h use with lambda

**Comment by cbielow** [comment]
fixed in #2560
