### ISSUE TITLE
Windows builds might require OpenSSL

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3322]
We got a build error on win with a selfbuilt QT5. We need to update docu on how to build QT5 with OpenSSL support and mechanisms to ensure that the dlls are found. And either ship them (license?) or add the OpenSSL installer to the Windows installer and knime prerequisites. It comes from the connectWithEncrypted call from mascotgenericquery.

**Comment by jpfeuffer** [comment]
Btw: Is https access really necessary? If we can avoid checking another dependency I would be glad.
http://doc.qt.io/qt-5/ssl.html#enabling-and-disabling-ssl-support

**Comment by jpfeuffer** [comment]
We probably should at least make it optional. I think there is an "if SSL available"  somewhere in QNetwork.

**Comment by jpfeuffer** [comment]
We need  to use:
https://stackoverflow.com/questions/35035508/relation-between-qt-no-ssl-and-qsslsocketsupportsssl

**Comment by hroest** [comment]
well if you are sending username and password over the network then SSL is at least desirable. I assume people tend to pay a lot of money for access to Mascot. But necessary? No

**Comment by jpfeuffer** [comment]
see #3330
