### ISSUE TITLE
OpenMS tools do not report progress in Knime GUI

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3323]
Even if `no_progress = false` is set, the tools do not report progress in the *Knime Console*.

Note that if multiple tools report progress in the same console, it can be very confusing (c.f. in `TOPPAS`). In workflows with parallel loops (i.e. not simple `ZipLoop`) it is not clear to me how to best report the progress of multiple tools running simultaneously.

**Comment by jpfeuffer** [comment]
https://github.com/genericworkflownodes/GenericKnimeNodes/issues/174

**Comment by jpfeuffer** [comment]
At least the progress logger should be visible as the output is continuously parsed.
Parsing the percentages and setting the node progress in the GUI progress bar is probably out of scope.
