### ISSUE TITLE
QT -> libpng -> zlib version clashes?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3329]
Did anyone think about what happens when the zlib version in libpng is not compatible with ours?
This might lead to problems.

**Comment by jpfeuffer** [comment]
Actually reports of this error increased to two. I think ubuntu 18.04 with qt 5.10 is affected. It includes a libpng that is compiled against system zlib which is 1.2.9. If we compile against our 1.2.8 it breaks.
Solutions:
- Add libpng to our contrib
- Update our zlib

**Comment by hroest** [comment]
so what will happen to people on 16.04 which have zlib 1.2.8 when we update? Are there going to be problems for these people? What about not linking against contrib zlib by default on Linux and use systems zlib by default?

**Comment by jpfeuffer** [comment]
I _think_ it should be backwards compatible (if they use proper semantic versioning).
But yes we could also adapt the quickbuild scripts and the docu for not using the ALL target of contrib OR make the ALL target in contrib not build zlib by default.

**Comment by hroest** [comment]
if it is backwards compatible then I am happy, maybe lets test this first? e.g. in a docker container?

**Comment by jpfeuffer** [comment]
yes that is our best bet. we just figured that not building zlib in contrib is not so easy since we let boost  depend on it, since it suffers from a similar potential incompatibility.

**Comment by hroest** [comment]
@jpfeuffer fixed?

**Comment by jpfeuffer** [comment]
yes we use a new zlib now. But we have to keep an eye on that. Might happen again.
Maybe this also only happens when you link it statically.
