### ISSUE TITLE
intensity scale in TOPPView 3D view broken

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3354]
The scaling of intensities in 3D view is incorrect, see screenshot. Tested under macOS.
![screen shot 2018-04-04 at 12 24 35](https://user-images.githubusercontent.com/6149805/38305106-83dafe78-3803-11e8-8d03-60d7a2d75376.png)

**Comment by timosachsenberg** [comment]
hi @lars20070 do you know if this is a regression or an old bug?

**Comment by lars20070** [comment]
Regression.

**Comment by jpfeuffer** [comment]
@timosachsenberg didn't you reimplement the renderText function? maybe it needs to consider scaling?

**Comment by timosachsenberg** [comment]
works with current develop on my ubuntu.
A MacOS thing?

**Comment by jpfeuffer** [comment]
Can reproduce it on macOS Sierra.
What happens is that the x and y axes scale and "zoom" when you scroll but the plot does not update (and therefore also the z axis does not scale).
Also: It does not cutoff the axes labels that are out of the plotting range after scaling. (Might be solved by a correct plot updating altogether)

**Comment by hroest** [comment]
I had a similar issue with Ubuntu and I fixed it with #3400 - maybe have a look at `void Spectrum3DCanvas::update_` and the currently commented out code to see whether its necessary?
