### ISSUE TITLE
1D tabs in TOPPView broken 

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3355]
When opening 1D spectra from 2D view, two tabs are opened instead of one, see screenshot.
![screen shot 2018-04-04 at 13 07 46](https://user-images.githubusercontent.com/6149805/38306844-bad12fe6-3809-11e8-92e0-0606d3153f5c.png)

**Comment by timosachsenberg** [comment]
hi @lars20070 do you know if this is a regression or an old bug?

**Comment by hroest** [comment]
cannot reproduce this on Windows or on Linux

**Comment by jpfeuffer** [comment]
I can confirm on macOS Sierra.

**Comment by timosachsenberg** [comment]
Can reproduce on Linux by opening the 2D view and richt-click "show survey scan"

addLayer seems to be called multiple times but I currently can't see where

**Comment by timosachsenberg** [comment]
Thanks! By the way how did you turn on function calls or did you do that in the debugger? 
I agree there should be only one showSpectrumAs1D be called and think both ways of doing the calls are fine: deciding in TOPPViewBase whether to call SpectraView/IdentificationViewBehavior or treating the Behaviors as distinct controllers without going through TOPPViewBase (except for managing connections). Actually, I think it's not a bad idea to separate the logic into controller classes and only perform connections in TOPPViewBase but given the current state of logic/model separation I agree that this would require additional refactoring. So will remove the extra line and decide what to call.
