### ISSUE TITLE
preferences in TOPPView broken

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3356]
Global preferences such as `mapping of mz` are not stored and lost when re-starting `TOPPView`.
![screen shot 2018-04-04 at 13 12 49](https://user-images.githubusercontent.com/6149805/38306977-2840f6e2-380a-11e8-8c26-0278d43e9c29.png)

**Comment by timosachsenberg** [comment]
hi @lars20070 do you know if this is a regression or an old bug? maybe the .TOPPView folder is missing? can you create it and check if it then works?

**Comment by lars20070** [comment]
Qt-unrelated regression. `.TOPPView.ini` is there. Occurs on different OS (macOS  & Ubuntu).

**Comment by hroest** [comment]
can you check the entry `mapping_of_mz_to` in `.TOPPView.ini` ? I found that changing the setting only takes effect for newly loaded files, have you tried to change the setting and then load a new file? It seems more like a missing feature at this point, e.g. changing the setting should take immediate effect on all layers

**Comment by lars20070** [comment]
Appears to be resolved. Changes in `TOPPView` preferences have an effect in `.TOPPView.ini`.
Tested under *Ubuntu* and *macOS*.
