### ISSUE TITLE
Colour changes of consensus/feature maps are reset when opening additional layers

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3357]
Colours of feature and consensus maps are reset to the default pallet when opening a new layer. For the inspection of label free data (different colours for different maps) this is inconvenient.
<img width="1215" alt="screen shot 2018-04-04 at 13 15 46" src="https://user-images.githubusercontent.com/6149805/38307149-b4486b98-380a-11e8-8263-3ca4fe98c379.png">

**Comment by timosachsenberg** [comment]
hi @lars20070 do you know if this is a regression or an old bug?

**Comment by lars20070** [comment]
Qt-unrelated regression.

**Comment by hroest** [comment]
there are a few things here:

- setting color preferences by right-clicking on a canvas only changes it for that canvas (is a nice feature, allows individual settings -- I think it is a good feature but may not make sense for everybody)
- setting color preferences globally through File->Preferences does not change any of the current layers (may be surprising)
- setting color preferences globally through File->Preferences will set the color gradient for all maps (peak / feature / consensus)

I can confirm all this behavior on Linux and I am not quite sure which behavior this issue relates to. Can you try to use File->Preferences, change the gradient and then load new files?

**Comment by lars20070** [comment]
Duplicate. See #3012.
