### ISSUE TITLE
No RUN_ID in OpenSwathWorkflow .osw output

### ISSUE THREAD

**Issue by vdemichev** [OpenMS/OpenMS#3365]
It seems that OpenSwathWorkflow does not include run_id information in its .osw output (at least when processing a single run). The same command to produce .tsv does generate a table with run_id there. Due to run_id being absent pyprophet cannot be used:
`pyprophet merge --out=merged.osw *.osw`
produces "sqlite3.OperationalError: no such table: RUN"
and 
`pyprophet score --in=merged.osw`
produces "no such column: RUN_ID".

**Comment by grosenberger** [comment]
Unfortunately, OpenMS 2.3 does not yet include support to report the run_id in OSW files. The latest OpenMS/develop however does. Can you try to use OpenMS/develop either by compiling the sources or using one of the latest nightly builds? Alternatively, we provide Docker containers.

**Comment by vdemichev** [comment]
Thank you!
