### ISSUE TITLE
zlib is not correctly exported or wrapped

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3373]
Since standard python usually links to it. Forcing us to use a compatible version again.
I encountered problems when trying to link a static zlib on windows.
Just to let people know. Is this somewhere in the pyOpenMS docu?

Related:
https://stackoverflow.com/questions/16841674/python-c-extension-link-with-a-custom-shared-library

**Comment by jpfeuffer** [comment]
I am not sure what the exact reason is. I just can't get pyOpenMS to work on Windows anymore.
No matter if I use zlib dynamic or statically, it just does not find its symbols (e.g. compress).
The thing is, we never explicitly linked to zlib in setup.py. I wonder how this ever worked. I just assume that we depended on zlib being linked into python (which it is not on my windows here).
Then the question is, why it does not work with static zlib. Here my guess is, since we only use compress in static methods, maybe the linker strips the symbols. But I am hesitant to use a custom solution for zlib (e.g. specifying --whole-archive for it).

**Comment by jpfeuffer** [comment]
And actually, if I use zlib.dll for linking it does not even show up as a dependency in the OpenMS.dll. Probably because the same sources were compiled into boost iostreams already..

**Comment by jpfeuffer** [comment]
Ok if I randomly link to zlib.dll although it is nowhere in the dependencies, it works. But this is imho not a solution. We should make sure that if we link zlib or boost or whatever comes with zlib, that the symbols are exposed by the OpenMS library.

**Comment by hroest** [comment]
> I am wondering what part in pyOpenMS is requiring the compress symbol. Shouldn't it suffice to call our wrapper function.

pretty sure that its not pyOpenMS but probably some OpenMS header that pulls in a zlib header, for example:

https://github.com/OpenMS/OpenMS/blob/b3c4e72094a1211942d207ebaa285d39d87b6165/src/openms/include/OpenMS/FORMAT/Base64.h#L54

```
$ grep -R zlib.h OpenMS/
OpenMS/FORMAT/Bzip2Ifstream.h:#include <bzlib.h>
OpenMS/FORMAT/GzipIfstream.h:#include <zlib.h>
OpenMS/FORMAT/Base64.h:#include <zlib.h>
```

so its probably not pyOpenMS but any external code that i) links against OpenMS and ii) includes any of these headers will run into these issues, right? pyOpenMS is just a special case because it basically includes all the OpenMS headers at some points because it wraps them. the solution would be to not include the zlib headers in any of the OpenMS headers, right?

**Comment by hroest** [comment]
in any case we probably should write a small class that abstracts code like this:

https://github.com/OpenMS/OpenMS/blob/b3c4e72094a1211942d207ebaa285d39d87b6165/src/openms/include/OpenMS/FORMAT/Base64.h#L557

and only includes zlib in the .cpp and keeps the headers clean

**Comment by hroest** [comment]
I am pretty sure https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FORMAT/GzipIfstream.h does not need the include in the header!

**Comment by jpfeuffer** [comment]
> so its probably not pyOpenMS but any external code that i) links against OpenMS and ii) includes any of these headers will run into these issues, right? pyOpenMS is just a special case because it basically includes all the OpenMS headers at some points because it wraps them. the solution would be to not include the zlib headers in any of the OpenMS headers, right?

Yep. I think that is exactly it. It currently comes up on win-only though. I could overcome it on win by explicitly exporting the compress symbol with
```
#ifdef OPENMS_COMPILER_MSVC
#pragma comment(linker, "/export:compress")
#endif
```
I think I will propose a patch for this for now until we find time to tackle a better wrapping of zlib as you described.
