### ISSUE TITLE
Error in multithreading.cmake

### ISSUE THREAD

**Issue by bretttully** [OpenMS/OpenMS#3382]
On linux (at least, don't have other systems to hand) this `/DOPENMS_HAS_TBB` needs to be `-DOPENMS_HAS_TBB`

https://github.com/OpenMS/OpenMS/blob/207614542166080d373c5b874c0447ea32c18ee5/cmake/multithreading.cmake#L54

**Comment by jpfeuffer** [comment]
Oh yes! Thanks for letting us know. I will fix it, but be aware that since it wasn't caught for a long time, it is probably not well tested.

**Comment by hroest** [comment]
maybe @timosachsenberg @aiche remembers the time when we had TBB - it may be useful to use the TBB data structures even together with OpenMP - especially for some of our singletons! https://stackoverflow.com/questions/9448613/are-tbb-data-objects-usable-with-openmp

**Comment by hroest** [comment]
>  Does this perhaps suggest a wider issue with the TBB build?

yes, mainly that it has not been used and tested since a couple of years!
