### ISSUE TITLE
build.bat doesnt work out of the box

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3405]
I am trying to build OpenMS on Windows and I have installed all the dependencies and everything, but `build.bat` does not work out of the box. I create a new folder with the current OpenMS develop, cd to it and call 

```
$ tools\build.bat TOPPView r
...
The .sln file 'OpenMS_host.sln' was not found. This script should be invoked from the root of the build tree. Change CWD and try again!
```

what am I doing wrong?

**Comment by cbielow** [comment]
'build.bat' substitutes nmake/Visual Studio.
You still need to create a build tree and invoke cmake.
After that, cd to the root of the build tree and call `build TOPPView r` (build.bat is copied to the build tree by cmake)

**Comment by hroest** [comment]
ok, I think the problem was that I used the nmake generator
