### ISSUE TITLE
Fix documentation for source build on Windows

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3406]
I was trying to follow the instructions in the documentation but I could not build Qt with MSVS 2015. However, the following worked:

```
PATH=%PATH%;C:\Python27\
configure -opensource -skip speech -skip location -nomake tests -nomake examples -confirm-license -opengl desktop -prefix C:\qtbuild\build_vs2015_opengl
nmake
nmake install
```

note that `-nomake tests` does not work any more with Qt 5.9 since that option vanished. Also I got compile errors at the very end when compiling the GUI since apparently on Windows QT uses ANGLE by default and not OpenGL and then TOPPView does not compile (at least not the 3D part). I still have trouble to use the 3D rendering on Windows, but I found that `-opengl desktop ` was necessary to make OpenMS compile. This was quite annoying as I noticed this at the very end and had to go back and re-compile Qt. Also I noticed that in my case `-skip speech` was necessary as otherwise I would run into compilation issues. Finally it seems that Qt now requires a working Python installation to compile and will fail if `python.exe` is not in the Path.

Maybe others here can confirm and clear up some confusion regarding OpenGL and whether `-opengl desktop `  is the right option here?

**Comment by jpfeuffer** [comment]
I think this part of the docu is pre-QT5.
I only added the part that suggests to just use the QT5 installer:
Contra:
- You have to sign up
- It might build a little bit more than we need
Pro:
- You can choose between different versions and compilers easily
- Fast
- JustWorks™
 
Feel free to update the docu according to your findings. I think it is a little weird that the standard "-opengl dynamic" does not work as it seems to have multiple fallbacks but I can not say the contrary either.

**Comment by hroest** [comment]
@jpfeuffer @timosachsenberg is this addressed now?
