### ISSUE TITLE
Deploy OpenMS on Windows

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3409]
I have a question I hope somebody can help me with. I am trying to provide a collaborator with a custom-built version of TOPPView so that they can look at their data. Since we have to work with them in the future, I would like to set up a pipeline where we can build on our Windows boxes and then ship them an updated version quickly. I wonder how to best go about this - is there a simple command that produces an installable version of OpenMS with all the correct libraries included? The alternative is to manually copy all libraries into a zip file and ship that zip file over to the collaborator?

**Comment by cbielow** [comment]
the installer basically provides the following functionality:
 - ships the executables + libraries
 - sets OPENMS_DATA_PATH as environment variable (so /share is found)
 - registers file extensions (mzML, ...) with TOPPView, to enable open by double-clicking a file
 - installs the Visual Studio runtime

The 'clean' way of doing this, would be to set up the installer on your build machine. This way, we'd also have an independent test if the thing works in other environments. If you ship a new installer, it will automatically uninstall the previous version.

The dirty way which has all the benefits from above is to have the collaborator install the latest default OpenMS release, and then simply send them a zip file with your executables + libraries (OpenMS.dll should suffice, maybe extra contrib libs if you have them) which he just uses to overwrite whatever the installer put in /bin.
This assumes that you did not change the content of /share (or you'd have to include /share as well).

The manual way is to ship the zip file which contains share, bin, contrib-libs, qt-libs; the collaborator would need to manually set OPENMS_DATA_PATH to whereever the extracted the zip. Additionally run the VS-runtime installer once. File extension registration has to be done manually (not a big deal, but extra work).

**Comment by hroest** [comment]
Great, I have it now working with option (2), the "dirty way" which is to provide a separate .zip file with the dlls and TOPPView in it. I think this makes it also way faster to update if we send them a new version. 

To test the installer process, I would love to get it working correctly, is there any documentation on how to create a full Windows installer?

**Comment by jpfeuffer** [comment]
In theory it should be as easy as "make dist" with -DPACKAGE_TYPE="nsis" and -DSEARCH_ENGINES="yourFlattenedTPFolder". But a correct NSIS version with long path support needs to be installed.
