### ISSUE TITLE
warning during OpenMS build on Debian testing

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#3411]
Greetings, 

I get this warning that might be a hint of something potentially problematic:

[ 30%] Building CXX object src/openms/CMakeFiles/OpenMS.dir/source/CHEMISTRY/RNaseDigestion.cpp.o
cd /home/rusconi/devel/packaging/openms/development/debian/build/src/openms && /usr/bin/c++  -DBOOST_ALL_NO_LIB -DOpenMS_EXPORTS -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/home/rusconi/devel/packaging/openms/development/debian/build/src/openms -I/home/rusconi/devel/packaging/openms/development/src/openms -I/home/rusconi/devel/packaging/openms/development/debian/build/src/openms/OpenMS_autogen/include -I/home/rusconi/devel/packaging/openms/development/src/openms/include -I/home/rusconi/devel/packaging/openms/development/debian/build/src/openms/include -isystem /usr/lib -isystem /usr/lib/x86_64-linux-gnu -isystem /lib/x86_64-linux-gnu -isystem /lib/x86_64-linux-gnu/include -isystem /home/rusconi/devel/packaging/openms/development/src/openswathalgo/include -isystem /home/rusconi/devel/packaging/openms/development/debian/build/src/openswathalgo/include -isystem /usr/include/libsvm -isystem /usr/include/eigen3 -isystem /usr/include/libwildmagic -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /home/rusconi/devel/packaging/openms/development/src/openms/thirdparty/eol-bspline  -g -O2 -fdebug-prefix-map=/home/rusconi/devel/packaging/openms/development=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fopenmp    -O3 -DNDEBUG -fPIC   -Wall -Wextra -fvisibility=hidden -Wno-non-virtual-dtor -Wno-unknown-pragmas -Wno-long-long -Wno-unused-function -Wno-variadic-macros -fPIC -std=gnu++11 -o CMakeFiles/OpenMS.dir/source/CHEMISTRY/RNaseDigestion.cpp.o -c /home/rusconi/devel/packaging/openms/development/src/openms/source/CHEMISTRY/RNaseDigestion.cpp
In member function 'void OpenMS::RNaseDigestion::digest(const OpenMS::String&, std::vector<OpenMS::String>&, OpenMS::Size, OpenMS::Size) const':
cc1plus: warning: 'void* __builtin_memset(void*, int, long unsigned int)': specified size 18446744073709551612 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]

Compiler version >= 7.3.0

Cheers
Filippo

**Comment by hroest** [comment]
is there a specific line this points to?

**Comment by jpfeuffer** [comment]
Just today @pasqoo reported that too with a new GCC

**Comment by hroest** [comment]
is it a false positive? the first google entry when searching this is a gcc bug about a false positive. I think we may have noticed in our tests if we tried to do a `memset` that is as large as claimed here.

**Comment by hroest** [comment]
The warning may potentially relate to 

https://github.com/OpenMS/OpenMS/blob/d3258b908484e577bfccc9ee2b8f0f483956f5ca/src/openms/source/CHEMISTRY/RNaseDigestion.cpp#L72

which would be a problem in case `fragment_pos.size()` is zero and we subtract 1 from an unsigned int that is zero - however on line 64 we check that `fragment_pos.size()` is larger than 1. It seems likely to be a false positive as in the gcc bug report

**Comment by pasqoo** [comment]
These are the warnings I encountered, with gcc 7.3.0 compiled from sources with flags `--enable-languages=c,c++ --disable-multilib`:
```
[177/2110] Building CXX object src/openms/CMakeFiles/OpenMS.dir/source/CHEMISTRY/RNaseDigestion.cpp.o
In member function ‘void OpenMS::RNaseDigestion::digest(const OpenMS::String&, std::vector<OpenMS::String>&, OpenMS::Size, OpenMS::Size) const’:
cc1plus: warning: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551612 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
[539/2110] Building CXX object src/openms/CMakeFiles/OpenMS.dir/...MATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp.o
In file included from /home/user/OpenMS/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp:51:0:
/home/user/OpenMS/src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmIdentification.h: In instantiation of ‘void OpenMS::MapAlignmentAlgorithmIdentification::align(std::vector<T>&, std::vector<OpenMS::TransformationDescription>&, OpenMS::Int) [with DataType = std::vector<OpenMS::PeptideIdentification>; OpenMS::Int = int]’:
/home/user/OpenMS/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp:224:53:   required from here
/home/user/OpenMS/src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmIdentification.h:115:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (reference_index >= data.size())
```

And:
```
The following tests FAILED:
     49 - LPWrapper_test (SEGFAULT)
    388 - FeatureDeconvolution_test (SEGFAULT)
    432 - MetaboliteFeatureDeconvolution_test (SEGFAULT)
    1086 - TOPP_Decharger_1 (SEGFAULT)
```

**Comment by lopippo** [comment]
To answer the question of Hannes: no, there is no line associated with the warning message, unfortunately. 
Cheers,
Filippo
