### ISSUE TITLE
TOPPView crashes when uses 3D View

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#3413]
TOPPView is crashing when switching to 3D view.

```
macOS High Sierra
Version 10.13.4
```

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000248
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]
```

**Question from @hroest** 

@oliveralka so the 3D view was broken beforehand already? I guess that was due to the switch to Qt5 - do you know which Qt version was used?

I have similar issues on Windows with QT 5.9 to get the 3D view working, even though it does not crash, the window is just blank.

**Comment by oliveralka** [comment]
@hroest I am using QT 5.10.1

**Comment by lars20070** [comment]
FYI, any panel switches do lead to TOPPView crashes under macOS in my case.

**Comment by hroest** [comment]
> I have similar issues on Windows with QT 5.9 to get the 3D view working, even though it does not crash, the window is just blank.

I also just ran into similar issues, in our case the window was black. It turned out to be an issue with the ANGLE library and how we compiled Qt (you have to use either `-opengl dynamic` or `-opengl desktop`).

**Comment by hroest** [comment]
@timosachsenberg @oliveralka can we close this?

**Comment by timosachsenberg** [comment]
Let’s close and reopen if not fixed on all systems.

**Comment by jpfeuffer** [comment]
Fixed it on my mac, too. BUT: zooming is almost impossible. I see no pattern in what goes wrong it just arbitrarily zooms in and out when I touch the mouse wheel.

**Comment by jpfeuffer** [comment]
At least it seems to scale correctly again, too.

**Comment by hroest** [comment]
also it seems that in the 3D view, the mouse wheel is the only way to zoom and Ctrl - / Ctrl + do not work as they do in 1D and 2D view @timosachsenberg is that expected behavior?

@jpfeuffer does Ctrl and then selecting an area with your mouse work for zooming?

**Comment by timosachsenberg** [comment]
Not sure would need to check the key bindings

**Comment by hroest** [comment]
> Not sure would need to check the key bindings

they are kind of broken on Linux anyways, at least I have always trouble to Alt-Tab to a different window when using TOPPView. That is pretty annoying. Where exactly do we create key bindings, is that in TOPPViewBase ?

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/blob/0bdfc055cc904ab892c314965d50d65081179410/src/openms_gui/source/VISUAL/SpectrumCanvas.cpp#L634

**Comment by jpfeuffer** [comment]
Yes, Ctrl (in my case Cmd) and selecting a range in the bird view while holding it works for zooming.
I encountered a different issue though:
When you want to reset zoom with Backspace, it does not work right away but you have to move the mouse or do something first.
