### ISSUE TITLE
Show all the `peak annotation m/z` at once in MS/MS spectra 

### ISSUE THREAD

**Issue by wenjiebi** [OpenMS/OpenMS#3418]
Until now, TOPPView does not support adding `peak annotation mz` for all peaks in an MS/MS spectra. It would be really nice if someone can add this function in the newer version.

**Comment by timosachsenberg** [comment]
I think I might be addressing something similar in https://github.com/OpenMS/OpenMS/pull/4126 
I don't annotate all peaks but exclude isotopic peaks and low intensity peaks for now.
