### ISSUE TITLE
How to handle strings for pyopenms in Python3?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3429]
```python
fh.loadExperiment("/Users/pfeuffer/svn/OpenMS/Tutorials/UM_2015/Example_Data/Labelfree/lfq_spikein_dilution_1.mzML", input_spectra)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Argument 'in_0' has incorrect type (expected bytes, got str)

fh.loadExperiment(b"/Users/pfeuffer/svn/OpenMS/Tutorials/UM_2015/Example_Data/Labelfree/lfq_spikein_dilution_1.mzML", input_spectra)

True
```

**Comment by jpfeuffer** [comment]
I mean basically: Can we or do we want to accept the non-byte strings in our functions?

**Comment by jpfeuffer** [comment]
It was the latest pyopenms for python3 on Mac. Basically pip3 install pyopenms.

**Comment by hroest** [comment]
ok, since this is `std::string` and not `OpenMS::String`, automatic conversion will not work https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/FileHandler.pxd#L15 -- it should work for `MzMLFile` though: https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/MzMLFile.pxd#L17

**Comment by jpfeuffer** [comment]
I see! Thanks! That explains it.

**Comment by hroest** [comment]
feel free to change `libcpp_string` to `String` to avoid this issue in the future:

```
$ grep -R cpp_string src/pyOpenMS/pxds/* | wc
     87     527    8298
```
