### ISSUE TITLE
Error with Singleton factory & OpenSwath

### ISSUE THREAD

**Issue by bretttully** [OpenMS/OpenMS#3431]
We are getting intermittent and unpredictable failures on runs when the EMG scoring is switched on that are coming from within the Singleton factory.
```
error message: the value 'EmgModel' was used but is not valid; This FactoryProduct is not registered!
```
My best guess is that this approach isn't thread safe and we've got a race condition where one thread is creating the singleton and the other is trying to use it?

https://github.com/OpenMS/OpenMS/blob/0f6f4e3c2ac9380eccaf6c7e74efec2b2c63ac13/src/openms/include/OpenMS/CONCEPT/Factory.h#L120

**Comment by hroest** [comment]
we hardly ever use the EmgModel, so this may not have come in our work. I will look into this issue

**Comment by bretttully** [comment]
Thanks @hroest -- we are just testing the EmgModel to see if it makes a difference. The failure rate for this line seems to be about 1%

**Comment by bretttully** [comment]
I went looking for where the BaseModel::registerChildren was being called from, but I'm not with an IDE at the moment and it wasn't obvious

**Comment by hroest** [comment]
The call that is failing may be this one: 

https://github.com/OpenMS/OpenMS/blob/805431ece9fab42ac02924ff4643ce88d8c09a22/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/EmgFitter1D.cpp#L201

the `BaseModel::registerChildren ` call should be this one:

https://github.com/OpenMS/OpenMS/blob/805431ece9fab42ac02924ff4643ce88d8c09a22/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/Fitter1D.cpp#L78-L85

**Comment by hroest** [comment]
maybe @cbielow could comment on this - sounds like a potential race condition? @bretttully does this happen in a multithreaded environment -- when should the registration happen?

**Comment by hroest** [comment]
it sounds like this could be a race condition in `Factory` - I dont quite understand this code but what happens when multiple threads call `static Factory * instance_()` at the same time? What if `instance_ptr_` is present but the registration is not finished yet?

**Comment by bretttully** [comment]
Yes, happening in multi-thread, although only 8 threads, so not massive.

```
What if instance_ptr_ is present but the registration is not finished yet?
```
This is exactly my concern with the use of Singletons in a multi-threaded environment. In this case, you would have to make sure that the `registerChildren` call was made during the serial part of the application, but it isn't clear to me how the architecture would allow for this.

**Comment by cbielow** [comment]
IMHO there are two options to fix this:
a) manually call `Factory<BaseModel<1>>::registeredProducts()` (or a related function) which builds up the factory instance in single threaded code before entering parallel sections
b) protect the instance_() method with a mutex, but that might have a performance hit and (more importantly) we do not know if std::thread, OpenMP, TPP, or whatnot will be used, and its generally inadvisable to mix them. So, I'd go with option a)

**Comment by hroest** [comment]
> a) manually call Factory<BaseModel<1>>::registeredProducts()

Probably we can do that in TOPPBase - didnt we anyways have an idea of creating an `OpenMS::init()` that would do some of these jobs?

**Comment by timosachsenberg** [comment]
Can't we just get rid of the singleton?
another possibility could be using http://en.cppreference.com/w/cpp/thread/call_once

**Comment by hroest** [comment]
This is related to #957 - lets get a quick fix in with calling either the suggested methods a) or b) but  remove the singleton in the long run

**Comment by hroest** [comment]
@cbielow basically what you are saying:

```
    static Factory * instance_()
     { 
       static Factory * instance_ptr_ = static_cast<FactoryType *>(SingletonRegistry::getFactory(myName));
```
I dont think that will work here, since only creation will be atomic but all the other code under `if (!instance_ptr_)` is not. I guess we would have to move that into the constructor?
