### ISSUE TITLE
RTPredict in KNIME is confusing due to Input/Output nodes

### ISSUE THREAD

**Issue by bpalanski** [OpenMS/OpenMS#3436]
I have setup a simple workflow to predict retention times using RTmodel and RTpredict (shown below).
My input is a .txt file of peptide sequences and retention times, and I have specified NU_SVR as the svm_type in RTmodel, which seems to run properly.

However, RT predict, gives an error that it "cannot perform peptide retention time prediction with a model trained for peptide separation prediction". I believe I have setup RTmodel to output an SVM file with retention time prediction.

Any suggestions? Running OpenMS 2.3 on Mac.

<img width="507" alt="screen shot 2018-05-04 at 11 53 27 am" src="https://user-images.githubusercontent.com/32470376/39646882-c73875ba-4f91-11e8-8a90-2f898afdf222.png">

<img width="706" alt="screen shot 2018-05-04 at 11 54 26 am" src="https://user-images.githubusercontent.com/32470376/39646927-ee7ae77a-4f91-11e8-8f46-7a5a457ab8cc.png">

**Comment by jpfeuffer** [comment]
I think you have to deactivate the optional outputs of RTPredict. Otherwise it thinks you want that separation output and goes into separation prediction mode.

**Comment by bpalanski** [comment]
Yes, this fixed the issue. Perhaps it is worth making this the default behavior or noting it in the documentation?

As always, thanks for the helpful reply!

**Comment by jpfeuffer** [comment]
No problem! Indeed the in/output logic could be improved in this node especially. I'll see what I can do.
