### ISSUE TITLE
Drag & Drop of single spectrum opens as chromatogram

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3441]
Dragging a single spectrum from "layers" will open it as chromatogram regardless of being a e.g. MS/MS

**Comment by hroest** [comment]
hmm that should not happen unless the data is annotated as being chromatogram data:

https://github.com/OpenMS/OpenMS/blob/4d645a698ea3694e8921e5ad73462cc1c04691a7/src/openms_gui/source/VISUAL/TOPPViewSpectraViewBehavior.cpp#L66

**Comment by hroest** [comment]
can you elaborate on this, is the x-axis "Time [sec]" or is it "MZ [Th]"? What are you actually dragging? A spectrum layer into a new tab?

**Comment by hroest** [comment]
I dont think I am able to reproduce, if I grab a layer and drop it to a new tab, it opens as 2D view. If I grab a spectrum from the "SpectraView" tab and drop it to the top bar, a new 1D view opens but as spectrum. If I open a file with only a single spectrum and drag the layer and drop it to a new tab, then it opens as 1D view but still as spectrum.
