### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3456]
Currently on an older CentOS machine, the build fails with

```
$ make 
../../lib/libOpenMS_GUI.so: undefined reference to `xercesc_3_1::SAXParseException::~SAXParseException()'
../../lib/libOpenMS_GUI.so: undefined reference to `typeinfo for xercesc_3_1::SAXParseException'
../../lib/libOpenMS_GUI.so: undefined reference to `xercesc_3_1::SAXParseException::SAXParseException(xercesc_3_1::SAXParseException const&)'
```

**Comment by jpfeuffer** [comment]
Full contrib? Then I guess it's the include order problem. We have xerces 3.2. I'll merge my open PR tomorrow.

**Comment by hroest** [comment]
yes, full contrib. So I think its a problem with GUI only, the regular OpenMS library works fine. It finds the system 3.1 xerces and then looks for it at link time and cannot find it.

**Comment by hroest** [comment]
Yes, I think it works. Let me just test again

**Comment by hroest** [comment]
I can confirm, it now works!
