### ISSUE TITLE
XFDR Debug mode tests fail

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3459]
Not sure if this related to the issue adressed by @cbielow 
```
XFDR: /home/jenkins/ws/openms_nightly_supplement/fd57e9df/source/src/utils/XFDR.cpp:796: virtual OpenMS::TOPPBase::ExitCodes TOPPXFDR::main_(int, const char**): Assertion `delta_scores.size() > rank_one_ids[order_score[i]]' failed.
```
see here https://abibuilder.informatik.uni-tuebingen.de/jenkins/view/OpenMS/job/openms_nightly_supplement/compiler=g++-4.9,os_label=ubuntu_1604/lastCompletedBuild/testReport/

**Comment by cbielow** [comment]
yep. I added the assert in #3453

**Comment by lukaszimmermann** [comment]
I am now looking into this  issue

**Comment by timosachsenberg** [comment]
I think this is resolved. please reopen if this is not the case
