### ISSUE TITLE
Zooming in 3D View

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3463]
3D View works quite well now. The only thing (on macOS) making problems is the zooming. If you zoom via mouse wheel or the backspace (reset) key, you have to move your mouse again before it updates the plot.

**Comment by timosachsenberg** [comment]
Should be fixed in https://github.com/OpenMS/OpenMS/pull/3465
There was no paintGL triggered.
Rotation etc. that includes mouse movement internally trigger paintGL so these did not have the problem
