### ISSUE TITLE
suggestion on default `spectrum_batch_size` in CometAdapter

### ISSUE THREAD

**Issue by jvolkening** [OpenMS/OpenMS#3470]
First of all, it's great to see Comet in OpenMS.

The default setting for `--spectrum_batch_size` results in a severe slowdown in running CometAdapter, at least on our server. A 'typical' complex 4-hr run from our Elite, ~ 60k spectra, took 34 minutes to search using the default settings and 4 minutes with batching turned off. The runs used 4.0 GB and 1.6 GB max memory, respectively.

Given that a major advantage of Comet is speed, I wonder if enabling this batching feature by default is too conservative. Might it not be better to disable it by default and let users turn if on if they find they are running out of memory? It would be a shame to have new Comet users turned off by unnecessarily slow performance.

**Comment by hroest** [comment]
I agree, I think we should use something that balances memory and speed. Btw: What is the default recommended setting from the tool developer?

**Comment by jvolkening** [comment]
> What is the default recommended setting from the tool developer?

The default in vanilla `comet` is 0 (in other words, load everything at once). The default in CometAdapter is 1000. This parameter is actually specifically discussed in a recent Comet paper, and the figure [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4607604/figure/F3/) shows the effect of batch size on speed. I would say it's pretty clear that, in any case, 1000 is too small for the default. If you didn't want to disable it by default, maybe 10,000 would be more appropriate -- it's unlikely that 2GB memory usage will pose a problem to many users.

**Comment by hroest** [comment]
seems like 10k to 20k is a reasonable number
