### ISSUE TITLE
store precursor intensity

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3486]
add method to extract the precursor intensity on a precursor.
Or do we already have something like this?

**Comment by hroest** [comment]
> is exported by the different instruments?

I dont know and it may vary from vendor to vendor. It may make sense to actually ask pwiz because they are the ones that write those attributes, but naively I would assume it is based on the last MS1 scan. It would be easy to check and correlate `precursors[0].getIntensity();` with the intensity of the previous MS1 spectrum at that m/z position?

**Comment by hroest** [comment]
for mzML files we set it here https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp#L1561 but this attribute is optional and actually missing in quite a few files including our sample files:

```
grep -c 1000042 share/OpenMS/examples/*.mzML
share/OpenMS/examples/LCMS-centroided.mzML:0
share/OpenMS/examples/peakpicker_tutorial_1_baseline_and_noise_filtered.mzML:0
share/OpenMS/examples/peakpicker_tutorial_1_baseline_filtered.mzML:0
share/OpenMS/examples/peakpicker_tutorial_1.mzML:0
share/OpenMS/examples/peakpicker_tutorial_1_picked.mzML:0
share/OpenMS/examples/peakpicker_tutorial_2.mzML:0
share/OpenMS/examples/peakpicker_tutorial_2_picked.mzML:0
hr@hr-Precision-5520:~/openmsall/source/OpenMS$ grep -c 1000042 share/OpenMS/examples/BSA/*.mzML
share/OpenMS/examples/BSA/BSA1.mzML:0
share/OpenMS/examples/BSA/BSA2.mzML:0
share/OpenMS/examples/BSA/BSA3.mzML:0
```

it seems like something left over from the time of mzXML where the attribute was usually present: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzXMLHandler.cpp#L220

so to answer your question: it seems like in many cases it is unset and then has its default value `0`
