### ISSUE TITLE
FalseDiscoveryRate add_decoy_peptides

### ISSUE THREAD

**Issue by Leon-Bichmann** [OpenMS/OpenMS#3488]
For me the FDR node does not keep decoy peptides in the output .idXML even after setting the add_decoy_peptides flag.

A brief debugging showed that the parameter is correctly read by the tool and converted to a boolean value. Therefore, Im not sure where the problem arises.

Id appreciate if u experience the same problem.

**Comment by timosachsenberg** [comment]
Ok so this might potentially be related to filtering of decoys because there are not decoy proteins left.

**Comment by timosachsenberg** [comment]
I think this might be the culprit:
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FalseDiscoveryRate.cpp#L201
It removes all peptide hits that don't reference a protein. I will prepare a fix

**Comment by jpfeuffer** [comment]
Hmm.. I would say it is a relatively rare case that you would want decoy peptides but not the associated proteins. But I guess I would be okay with another parameter.
What are the defaults? Are the defaults not both true?

**Comment by Leon-Bichmann** [comment]
Created Pull Request #3516
