### ISSUE TITLE
Possible missing header include on TOPPASVertexNameDialog.cpp & ui_TOPPASVertexNameDialog.h

### ISSUE THREAD

**Issue by yd8012mw2** [OpenMS/OpenMS#3497]
Version : OpenMS 2.3
Platform : Ubuntu 14.04 64bit
Problem Occured when self-compiling

Error Message : 
make : TOPPASVertexNameDialog.cpp Error 
/home/enol/nDev/OpenMS/src/openms_gui/source/VISUAL/DIALOGS/TOPPASVertexNameDialog.cpp: In constructor ‘OpenMS::TOPPASVertexNameDialog::TOPPASVertexNameDialog(const QString&, const QString&)’:
/home/enol/nDev/OpenMS/src/openms_gui/source/VISUAL/DIALOGS/TOPPASVertexNameDialog.cpp:51:7: error: ‘QRegExpValidator’ was not declared in this scope
       QRegExpValidator* v = new QRegExpValidator(rx, ui_->line_edit);
       ^
/home/enol/nDev/OpenMS/src/openms_gui/source/VISUAL/DIALOGS/TOPPASVertexNameDialog.cpp:51:25: error: ‘v’ was not declared in this scope
       QRegExpValidator* v = new QRegExpValidator(rx, ui_->line_edit);
                         ^
/home/enol/nDev/OpenMS/src/openms_gui/source/VISUAL/DIALOGS/TOPPASVertexNameDialog.cpp:51:33: error: expected type-specifier before ‘QRegExpValidator’
       QRegExpValidator* v = new QRegExpValidator(rx, ui_->line_edit);
                                 ^
/home/enol/nDev/OpenMS/src/openms_gui/source/VISUAL/DIALOGS/TOPPASVertexNameDialog.cpp:51:33: error: expected ‘;’ before ‘QRegExpValidator’
make[2]: *** [src/openms_gui/CMakeFiles/OpenMS_GUI.dir/source/VISUAL/DIALOGS/TOPPASVertexNameDialog.cpp.o] Error 1 

Additional information :
I have handled this problem by manually adding 
'#include <QtGui/QRegExpValidator>'
at ui_TOPPASVertexNameDialog.h

If it's considered as a bug, and if this solution is applicable for the bug, please update the source for the better OpenMS!

**Comment by hroest** [comment]
thanks for reporting this. I cannot reproduce this on Ubuntu 16.04 with qt 5.5, the code compiles even without the include.

- which Qt version did you use?
- can you check whether  #3503 solves your problem?

**Comment by hroest** [comment]
did you by any chance use Qt 5.11 ? It seems that other projects have the same issue with Qt 5.11 : https://github.com/KDE/print-manager/commit/9172f63f16a663b58de919e485579453e12d5560

**Comment by yd8012mw2** [comment]
I'd really like to check, but it would take 3 or 4 more months to check the system, as I'm serving mandatory military service right now (I'm returning to the base) and the next short vacation would be 3 or 4 months later. (In fact, I also cannot log into the github anymore in that season)

If anybody suffers from the same problem, please feel free to experience the update and join this talk.

Thanks for the fast reply & fix!
