### ISSUE TITLE
FeatureFinderMultiplex clustering

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3508]
a student just got this error message.
Sounds related to the magic constants used in the hash grid.
![image](https://user-images.githubusercontent.com/5803621/40800088-ab163596-650f-11e8-803a-af1c2856dc07.png)
Or has this been fixed?

**Comment by jpfeuffer** [comment]
At some point I thought there was a fix. Which commit was built?
I remember a non-threshold double comparison, too.

**Comment by lars20070** [comment]
The [margin](https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp#L68) is now `0.01`. So `5400.28 < 5400.28` should not be possible now.

**Comment by timosachsenberg** [comment]
Hmm I think it is merged but maybe @NantiaL can check. I'm not an expert how these number representations are created from the double but are you sure this can't happen with 0.01? I don't know the details of the algorithm but isn't there a way to handle this properly and independent of the floating point resolution? This code changed half a dozen times because there was always some data that resulted in an error. Would be great to find a solution that does not involve increasing the margin from 0.01 to 0.02 ;)

**Comment by timosachsenberg** [comment]
and it seems not to be chagned everywhere https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp#L118
