### ISSUE TITLE
The list of available tools is hard coded in ToolsDialog.C [353]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#353]
Submitted by aiche on 2011-09-22 14:42:32

The list of available tools is hard coded in ToolsDialog.C, so changing the tool names or adding new tools also triggers a change in  ToolsDialog.C, which is not known to most of the developers. 

Can we generate the list from the ToolHandler ..

**Comment by cbielow** [comment]
its not that easy, since ToolsDialog is a special "hand-picked" subset which is reasonable to have in TOPPView for each Layer datatype. This information is simply not available in ToolHandler and would be overkill to add.
