### ISSUE TITLE
Installing new version using NSIS installer did remove files but not OpenMS 2.3 folder

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3535]

**Comment by timosachsenberg** [comment]
win 10

**Comment by jpfeuffer** [comment]
Hmm line is still here: https://github.com/OpenMS/OpenMS/blob/develop/cmake/Windows/NSIS.template.in#L766
I dont know why it does not work anymore. Did you try to reboot?
Is there an uninstall log?

**Comment by timosachsenberg** [comment]
seems to work now
