### ISSUE TITLE
Task: implement cyclic loess normalization in MapNormalizer

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3537]

**Comment by hroest** [comment]
we currently have a loess implementation - what exactly do you mean with cyclic? Crossvalidated loess?

**Comment by timosachsenberg** [comment]
http://web.mit.edu/~r/current/arch/i386_linux26/lib/R/library/limma/html/normalizeCyclicLoess.html

I saw it used on an ASMS poster and it seemed to perform often better than quantile normalization or median scaling (both supported in OpenMS. This is mainly intended as a personal note but I am happy to have a more general discussion.
