### ISSUE TITLE
Thirdparty Adapter failures

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3545]
After my little effort to correctly read error codes and outputs from our thirdparty tools,
several errors showed up.
**MascotOnline:** They sent us a one-time verification e-mail to openms@openms.de. Maybe we should put a real email there and verify us, if we want to use their server for nightly testing.
**Percolator:** Not sure if these errors were just masked before by not querying the exit status or if they are related to my changes.
**Sirius:** Only fails on win. I have to debug since it does not seem to forward the error output to the executable (it's a java wrapper).

**Comment by oliveralka** [comment]
@jpfeuffer Does the "Sirius" command line tool (not the Adapter) fails on windows as well? Then it is not an Adapter issue. (Can test it at home.)

**Comment by jpfeuffer** [comment]
Actually.. the errors are gone now ?!
But what I saw when I tried to execute the test manually:
You get a weird error when the executable was not found (e.g. mistyped). I think it is from the code trying to resolve it to an absolute path. Can you try it on your computer and add a reasonable error message?
Maybe there was a hiccup when checking out thirdparties and it was not found.

**Comment by jpfeuffer** [comment]
I added a real email for Mascot. Let's see if I can accept it.

**Comment by oliveralka** [comment]
@jpfeuffer
Test: Windows - Version 10.0.17134 Build 17134 - SiriusAdapter
OpenMS 2.3.0: Everything works fine (Thirdparty executable is alright).
OpenMS 2.4.0 (nightly 2018-05-30): 
If the output is set to mzTab (output for SiriusAdapter):
`Invalid parameter: Invalid output file extension 'C:\Users\Desktop\OpenMS_Sirius_test\SiriusAdapter_test\win_out\thirdparty_sirius.mzTab'. Valid file extensions are: 'tsv'.`

If the output is set to tsv:
`Error: Unable to write file (the file 'C:\Users\Desktop\OpenMS_Sirius_test\SiriusAdapter_test\win_out\thirdparty_sirius.tsv' could not be created; invalid file extension, expected 'mzTab')`

Any idea what happened here? 

SiriusAdapter fails in the current KNIME-Version (OpenMS 2.3.0 plugin).
`  OpenMS	2.3.0.201712211252`

Any ideas?
