### ISSUE TITLE
Building OpenMS 2.40 on Linux Missing "GLIBCXX_3.4.20..."

### ISSUE THREAD

**Issue by abisarvepalli** [OpenMS/OpenMS#3549]
<img width="933" alt="screen shot 2018-06-15 at 2 26 24 pm" src="https://user-images.githubusercontent.com/7587923/41490267-20d311a2-70a8-11e8-9c78-8878d6939c15.png">

When trying to building an OpenMS dev environment, I seem to run into the issue where I'm missing this GLIBCXX_3.4.20 library required by CMake.
I am trying to build command line tools via miniconda and trying to install most of the contrib library thought the tutorial and running most of the required packages by installing them locally.

Are there any solutions to debug this issue?

Thanks
Abi Sarvepalli

**Comment by jpfeuffer** [comment]
Hi,

where did you get your cmake from?
You should use the one from anaconda to be consistent with their compiler version. https://anaconda.org/anaconda/cmake

**Comment by abisarvepalli** [comment]
I am using conda's cmake ver 3.11.1 and am still facing the same error. I also went ahead and installed qt from conda that recognized the QByteArray::fromStdString method.

Is there any possible way to properly debug this issue?

**Comment by oliveralka** [comment]
@abisarvepalli 
Please have a look here an see if you can upgrade the libstdc++.

The same issue seems to have happened with cmake3.9.1:
https://github.com/ContinuumIO/anaconda-issues/issues/6529

**Comment by abisarvepalli** [comment]
I am currently running CentOS 6.6. I will take a look at this thread and see if I can debug the issue. 

Thanks!

**Comment by abisarvepalli** [comment]
This is the issue that I am currently facing right now:

![image](https://user-images.githubusercontent.com/7587923/41814092-788f17be-76f8-11e8-862b-4422934f616e.png)

**Comment by hroest** [comment]
can you describe which version of OpenMS you are trying to build and which version of Qt you are using? It is likely that you are using a version of Qt that is too old. 

Have you considered following the installation guidelines from our online documentation? It explains how to install the dependencies and build OpenMS (but does not cover conda) https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/install_linux.html

**Comment by abisarvepalli** [comment]
Although I have qt5 installed through conda, i am having issues with executing cmake to build the OpenMS files as there is an issue with locating the qt5 install location. 

Is there a user variable that I should initialize with the proper qmake path?

**Comment by lfnothias** [comment]
Anyone would know if there is a solution to this issue ?
@hroest, is that new [issue](https://github.com/OpenMS/OpenMS/issues/3571) related to the present issue ?

**Comment by jpfeuffer** [comment]
Concerning "Finding QT5": The path to the root directory of QT5 (the one where lib, bin, include, ... are located) needs to be in the list of paths the CMake searches (which can be specified during the cmake call):
`cmake -DCMAKE_PREFIX_PATH="/path/to/qtroot"` and then the rest of your options.

**Comment by jpfeuffer** [comment]
Concerning the QT version: We need the version of Qt that you have installed to see if it could be the problem.

**Comment by abisarvepalli** [comment]
This issue was resolved by relinking the libstdc++.so that I had installed via miniconda
