### ISSUE TITLE
MSGFPlus(Adapter) NullPointerException and Error reporting

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#3576]
When processing https://zenodo.org/record/892005/files/qExactive01819_profile.mzml MSGFPlusAdapter prints: 

```
Fatal error: Running MS-GF+ returned an error code '255'. Does the MS-GF+ executable (.jar file) exist?
```

it also prints the actual error message to stderr:

```
Fatal error: Exit code 9 ()
java.lang.NullPointerException
	at edu.ucsd.msjava.msutil.Spectrum.getCharge(Spectrum.java:124)
	at edu.ucsd.msjava.msutil.SpecKey.getSpecKeyList(SpecKey.java:91)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:220)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:105)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:56)
```

I'm wondering about the mismatch between the reported exit code 255 and the actual exit code 9? 

See also https://github.com/MSGFPlus/msgfplus/issues/39

**Comment by jpfeuffer** [comment]
It think that MSGFPlus cannot find an annotated precursor charge.
The mismatch arises from our own ExitCodes. MSGF reports 255, we report 9 (error in external process).

**Comment by jpfeuffer** [comment]
There are definitely some entries without annotated charge state. Maybe it tries to infer the charge but fails because the spectra still seem to be in profile mode (not centroided).

**Comment by bernt-matthias** [comment]
Thanks for the comments. The explanation fits to the code line that causes the error where the charge or a precursor is returned. 

But the stack trace that I find in stderr comes from MSGFPlus, which suggests that also the exit code 9 comes from MSGFPlus...? 

Anyway, I was really confused by: `Does the MS-GF+ executable (.jar file) exist?` :)

**Comment by jpfeuffer** [comment]
Ah, yes, that was actually our default message just because it is 90% of the reasons for failure. But I agree, there could be better error handling. We just updated adapter error reporting a bit. I think it might be better in the develop branch but maybe not perfect.

**Comment by bernt-matthias** [comment]
Wonderful. Every improvement is welcome. Thanks for your efforts. 

You might close this issue .. or watch the up / downstream issues and decide later :)
