### ISSUE TITLE
Average weight calculations

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3589]
Dear developers

I have an issue where I dont quite understand how isotopic distributions and average weight are calculated in OpenMS. Specifically I am looking at BSA using pyOpenMS:

```
>>> from pyopenms import *
>>> import urllib
>>> urllib.urlretrieve ("http://www.uniprot.org/uniprot/P02769.fasta", "bsa.fasta")
>>>
>>> bsa = "".join([l.strip() for l in open("bsa.fasta").readlines()[1:]])
>>> bsa_prot = AASequence.fromString(bsa, True)
>>> bsa_processed = AASequence.fromString(bsa[24:], True)
>>>
>>> bsa_prot.getAverageWeight(Residue.ResidueType.Full, 0)
69292.88650621701
>>> bsa_processed.getAverageWeight(Residue.ResidueType.Full, 0)
66432.45593654823
>>>
>>> seq_formula = bsa_processed.getFormula(Residue.ResidueType.Full, 0)
>>> isotopes = seq_formula.getIsotopeDistribution(80)
>>> max( isotopes.getContainer(), key=lambda x : x[1] )
(66399, 0.05713559158303688)
>>> for iso in isotopes.getContainer()[-10:]:
...     print (iso)
...
(66427, 7.452259391000588e-05)
(66428, 4.8067464291277997e-05)
(66429, 3.0645369519834025e-05)
(66430, 1.931540348099346e-05)
(66431, 1.2037621963010855e-05)
(66432, 7.419015362283155e-06)
(66433, 4.522610417503779e-06)
(66434, 2.7273207269190423e-06)
(66435, 1.627242728505254e-06)
(66436, 9.607287237740715e-07)
```

so what I dont understand are two things: first, why the average weight iof BSA is 66432.45593654823 which is close to the literature value of 66430.3 [1] but not exactly the same as the literature value. Secondly, and  more strangely, the maximum of the isotopic distribution is at 66399 with 5.7% while the average value has 1.9e-5 probability. I expected the maximum of the isotopic distribution to be close to the average weight.

1. https://www.ncbi.nlm.nih.gov/pubmed/2260975

**Comment by timosachsenberg** [comment]
For the difference between average weights, it might that different natural abundances are assumed (these vary quite a bit depending on the source and where/in what system they were measured). 
Regarding the maximum, I would take a look at the distribution. The average can be a bit off - though I don't know if the difference can be so severe. What do the other online calculators suggest?

**Comment by timosachsenberg** [comment]
e.g., http://rna.rega.kuleuven.be/masspec/pepcalc.htm gives molecular mass : 66433.2117

**Comment by timosachsenberg** [comment]
and https://www.genscript.com/tools/peptide-property-calculator
Chemical Formula: C2934H4615N781O897S39
Molecular Weight: 66432.60

**Comment by DennisGoldfarb** [comment]
The isotope distributions are of interest to me, so I just checked this as well. The issue seems to be with the masses in the isotope distribution container. The first mass of the isotope distribution starts at 66357 instead of the monoisotopic mass of ~66390. That's a 23 Da difference, if you add that to where your max isotope was 66399 + 23 = 66432 which is around what the average mass should be. Maybe the probabilities are correct but the masses are wrong?

**Comment by hroest** [comment]
I looked at one of the few online calculators I could find quickly. For the same formula C2934H4615N781O897S39, we get with http://education.expasy.org/student_projects/isotopident/htdocs/

```
TitleText: Isotopic distribution
YRange: 0,1
XLabel: m/z
YLabel: Intensity
Marks: points
Lines: off
Impulses: on
DataSet: peak
66402.86		0.000002701
66403.86		0.000008045
66404.86		0.000021539
66405.86		0.000053620
66406.86		0.000125693
66407.86		0.000279064
66408.86		0.000589002
66409.86		0.001185316
66410.86		0.002280126
66411.86		0.004202170
66412.86		0.007434723
66413.86		0.012651404
66414.86		0.020741175
66415.86		0.032811564
66416.86		0.050158567
66417.86		0.074193686
66418.86		0.106323644
66419.86		0.147786221
66420.86		0.199455361
66421.86		0.261638282
66422.86		0.333894491
66423.86		0.414909270
66424.86		0.502450889
66425.86		0.593431324
66426.86		0.684075883
66427.86		0.770190282
66428.86		0.847497590
66429.86		0.912005257
66430.86		0.960356599
66431.86		0.990122771
66432.86		1.000000000
66433.86		0.989890969
66434.86		0.960865872
66435.86		0.915014959
66436.86		0.855217512
66437.86		0.784860432
66438.86		0.707542143
66439.86		0.626794747
66440.86		0.545850454
66441.86		0.467469034
66442.86		0.393833096
66443.86		0.326509068
66444.86		0.266464840
66445.86		0.214130690
66446.86		0.169488409
66447.86		0.132174051
66448.86		0.101581833
66449.86		0.076959778
66450.86		0.057490973
66451.86		0.042357454
66452.86		0.030786255
66453.86		0.022079007
66454.86		0.015627631
66455.86		0.010919167
66456.86		0.007532808
66457.86		0.005131922
66458.86		0.003453343
66459.86		0.002295686
66460.86		0.001507890
66461.86		0.000978759
66462.86		0.000627897
66463.86		0.000398157
66464.86		0.000249580
66465.86		0.000154660
66466.86		0.000094747
66467.86		0.000057380
66468.86		0.000034351
66469.86		0.000020326
66470.86		0.000011886
66471.86		0.000006826
66472.86		0.000003779
66473.86		0.000001965
```

where again the unit masses used above seem to correspond well with the average mass that we also calculate: `66432.86`

and it seems that I can indeed get comparable values by shifting the distribution : 

```
>>> for iso in isotopes.getContainer()[38:50]:
...   print iso[0]+34, iso[1]/0.057135591583
... 
66429 0.853748937267
66430 0.917565931233
66431 0.964604307139
66432 0.992481133653
66433 1.0
66434 0.987220263353
66435 0.955399547368
66436 0.906824405693
66437 0.844557546
66438 0.772137901005
66439 0.693271533083
66440 0.611547447917
```

**Comment by DennisGoldfarb** [comment]
After a little more digging, it looks like it's because the nominal masses of individual elements are used to determine the nominal masses of the coarse isotope distribution. For such a large molecule, the rounding errors become significant. One way to get around this is to use the same calculation as EmpiricalFormula::getMonoWeight() to get the mono mass and use that as the first nominal mass in IsotopeDistribution.

**Comment by DennisGoldfarb** [comment]
For example, with 4615 hydrogens if you used the actual mono mass of 1.0078 then you'd get 4651 da, but since the nominal mass of hydrogen is used (1 da) you only get 4615 da.

**Comment by hroest** [comment]
seems to make sense, however we are still one off even with a correction factor - interestingly we are almost exactly one off:

```
>>> isotopes = seq_formula.getIsotopeDistribution(160)
>>> mono_w = bsa_processed.getMonoWeight(Residue.ResidueType.Full, 0)
>>> corr_factor = mono_w - isotopes.getContainer()[0][0]
>>> for iso in isotopes.getContainer():
...   if iso[1]/0.057135591583 > 1e-2:
...     print iso[0]+corr_factor, iso[1]/0.057135591583
... 
66412.8628297 0.0120532666079
66413.8628297 0.0199626627128
66414.8628297 0.0318619223654
66415.8628297 0.0490840122168
66416.8628297 0.0730878911917
66417.8628297 0.1053330078
66418.8628297 0.147106605952
66419.8628297 0.199317887461
66420.8628297 0.262283556462
66421.8628297 0.335537094277
66422.8628297 0.417696888232
66423.8628297 0.506424520479
66424.8628297 0.598493958553
66425.8628297 0.689976516954
66426.8628297 0.776528086113
66427.8628297 0.853747820022
66428.8628297 0.917564730475
66429.8628297 0.964603044825
66430.8628297 0.992479834859
66431.8628297 0.999998691367
66432.8628297 0.987218971443
66433.8628297 0.9553982971
66434.8628297 0.906823218992
66435.8628297 0.844556440784
66436.8628297 0.772136890559
66437.8628297 0.693270625845
66438.8628297 0.611546647626
66439.8628297 0.530203639294
66440.8628297 0.45196336235
66441.8628297 0.378935877405
66442.8628297 0.312592529827
66443.8628297 0.253795808395
66444.8628297 0.202871204657
66445.8628297 0.159704974742
66446.8628297 0.123852741159
66447.8628297 0.0946464614167
66448.8628297 0.0712906819465
66449.8628297 0.0529425277364
66450.8628297 0.0387730556514
66451.8628297 0.0280101231322
66452.8628297 0.0199646753999
66453.8628297 0.0140433574605

```

e.g. comparing OpenMS:

```
66412.8628297 0.0120532666079
66413.8628297 0.0199626627128
66414.8628297 0.0318619223654
```

with isotopeident:
```
66412.86		0.007434723
66413.86		0.012651404
66414.86		0.020741175
66415.86		0.032811564
```

**Comment by DennisGoldfarb** [comment]
At this point I think it might be differences in isotope abundances. Their table is definitely different from the one used in OpenMS:

http://education.expasy.org/student_projects/isotopident/htdocs/motza.html
For example, they have hydrogen as:
Mass | Probability
1.0078250321 | 99.984426
2.0141017780 | 0.015574

While OpenMS has:
1.0078250319 | 99.9885
2.01410178 | 0.0115

And for Carbon they have:
12.0000000 | 98.8922
13.0033548378 | 1.1078

vs OpenMS:
12.0 | 98.93
13.003355 | 1.07

**Comment by DennisGoldfarb** [comment]
I tried OpenMS using their elemental isotope probabilities and it matches much better:

```
23 66412.8628306115 0.00741538325125179
24 66413.8628306115 0.012619591737677
25 66414.8628306115 0.0206909876924299
26 66415.8628306115 0.0327354788454476
27 66416.8628306115 0.0500475630674628
28 66417.8628306115 0.0740376655688962
29 66418.8628306115 0.106112199806698
30 66419.8628306115 0.147509759895422
```

**Comment by hroest** [comment]
also to consider is that the "best value" here is the best measurement of a reference compound, here NBS19 which is a limestone and not an organic compound (most people are interested in organic compounds here). So just because it is the best measurement of a reference compound does not mean that this reference is representative of the actual natural abundance. In fact, the NBS19 reference has an exceptional high ratio of 13C in it - see https://en.wikipedia.org/wiki/Reference_materials_for_stable_isotope_analysis and https://en.wikipedia.org/wiki/%CE%9413C#Reference_standard which states 

The standard established for carbon-13 work was the Pee Dee Belemnite (PDB) and was based on a Cretaceous marine fossil, Belemnitella americana, which was from the Peedee Formation in South Carolina. This material had an anomalously high 13C:12C ratio (0.0112372), and was established as δ13C value of zero.

note that NBS19 has an *even higher* C13 ratio - 195 ppm higher. Also the description of the material is quite peculiar and does not inspire confidence:

The reference material NBS 19 (in literature also referred to as TS-Limestone) was obtained from a single slab of white marble of an unknown origin. It was crushed by H. Friedrichsen, University of Tübingen, Federal Republic of Germany. 

https://nucleus.iaea.org/rpst/referenceproducts/referencematerials/Stable_Isotopes/13C18and7Li/NBS_19.htm

**Comment by DennisGoldfarb** [comment]
I don't think you can really say one is correct or not because the elemental isotope distributions will depend on the source of your samples. For example, plants have different carbon isotope distributions because photosynthesis favors C12 over C13.

**Comment by hroest** [comment]
@DennisGoldfarb I agree, however I still dont think that using a single reference material is the optimal choice and we should use column 9 from http://education.expasy.org/student_projects/isotopident/htdocs/iso.pdf and not column 6 since 

- Column 6: The best measurement from a single terrestrial source.
- Column 9: Representative Isotopic Composition. In this column are listed the values which, in the opinion of SIAM, represent the isotopic composition of the chemicals and/or materials most commonly encountered in the laboratory.

so while Column 6 is a single good measurement, Column 9 is the most likely isotopic composition of the most common materials found in the lab. Again, most people will want to analyze organic material from current species and not a particular limestone (higher C13) or fossils (lower C13) for which they may have to use a different model.

**Comment by timosachsenberg** [comment]
Yes, I agree that column 9 is more sensible for most purposes. I think I played around with changing our abundances (I think they are derived from column 9) in MetaProSIP a bit but it had only marginal effects on peptides.

**Comment by hroest** [comment]
@DennisGoldfarb or @timosachsenberg does one of you have time to fix the issue with the masses not being correct. I think the correct tuple should be

```
(monoWeight + i, probability)
```

where i is an integer. For backwards compatibility there could be an option to round `(monoWeight + i)` to the nearest integer.

**Comment by DennisGoldfarb** [comment]
@hroest Yup I can work on it

**Comment by hroest** [comment]
this should definitely get into 2.4 as this is a major error when looking at isotopic distributions

**Comment by hroest** [comment]
@DennisGoldfarb any update on this?

**Comment by DennisGoldfarb** [comment]
@hroest I'm nearly done! I should have my initial pull request ready tonight.
