### ISSUE TITLE
xtandemAdapter reports incorrect protein evidance 

### ISSUE THREAD

**Issue by PayamEmami** [OpenMS/OpenMS#3594]
Hello,

It seems like xtandemAdapter reports wrong proteins for peptides in idXML (OpenMS version 2.3.0). 

I have attached a very small example of XTandem xml file. The workflow is simply an IDConverter followed by TextExporter. 

It reports that peptide VPLRSILE is coming from sp|Q03517|SCG2_MOUSE and sp|Q99JA0|CALCA_MOUSE but it should report CALC_MOUSE and CALCA_MOUSE. 

In version 2.1.0 it works good. 

[test.zip](https://github.com/OpenMS/OpenMS/files/2166295/test.zip)

Best,
Payam

**Comment by jpfeuffer** [comment]
Hi payam!

So the pepXML out of XTandem is still correct, but after converting to idXML the associations get messed up?

**Comment by PayamEmami** [comment]
Yes. Exactly. You can see it in the file i attached. We realized that the behavior is inconsistent when running different files. So given two mzML files, we ran xtandem on them, and an identical peptide in both of them. But in one, the peptide was reported to originate from protein X; Y and in another one X,Z.

**Comment by jpfeuffer** [comment]
In general for a short solution, we suggest to use PeptideIndexer on top, which should redo the whole associations but yes, we have to have a look into this, not that other things are wrongly parsed.
