### ISSUE TITLE
TOPPView improve precursor ion name format

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3597]
It is always [M+H], regardless of charge state and the number of “+” that specify the charge is between the [M+H] and the adduct (eg. [M+H]-H2O++ U'+ ; [M+H]+ U'-H2O+)
 
Its really cosmetic but of course most correct formatting from a mass spectrometric point I suppose would be [M+zH + or - adducts/losses]z(times)”+”  (z =charge charge).

**Comment by timosachsenberg** [comment]
![image](https://user-images.githubusercontent.com/5803621/52223508-0b40f780-28a6-11e9-84e3-43df008a7914.png)

**Comment by hendrikweisser** [comment]
My suggestion is to just use "M" for the precursor. The number of "+"/"-" for the charge already implies addition/loss of protons. It's the same for the fragment ions, where we also just use e.g. "y1+", not "[y1+H]+".

**Comment by timosachsenberg** [comment]
I think "[M+3H]3+" (actually with the 3+ in upper letters) is standard notation.

**Comment by hendrikweisser** [comment]
Okay, but a) it's more work to implement, b) it's inconsistent with the fragment annotations, and c) it's harder to read without the superscripts. (For RNA I've settled on just using "M", although currently we explicitly don't consider precursor peaks in NucleicAcidSearchEngine.)

**Comment by timosachsenberg** [comment]
We can discuss that at the developer meeting if you like (e.g., jointly with proteomic / metabolomic guys).

**Comment by timosachsenberg** [comment]
For proteomics, we will use the standard notation but don't intend to enforce that in the other areas. So feel free to decide for yourself.
