### ISSUE TITLE
XML Parsing from network drives on Win

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3598]
I currently have a user complaining about not being able to read files in TOPPView from a shared drive on Windows like
"\\\\foo\bar\baz.mzml"

I am not sure about the permissions of the user on that drive but it can be copied from there so it should be readable at least.
It seems like Qt loads it fine but Xerces complains later before parsing.

```
14:37:20 ERROR: Error while loading file:

- due to that error of type Parse Error in: 
src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp@105-void __cdecl OpenMS::Internal::XMLHandler::fatalError(enum OpenMS::Internal::XMLHandler::ActionMode,const class OpenMS::String &,unsigned int,unsigned int) const
```

In general path issues (also non-ASCII characters or permissions) are the most common issues for new users and questions/frustration could be avoided by better error messages.

**Comment by jpfeuffer** [comment]
Mapping the shared drive (i.e. associating a drive letter to it) solved the issue. Nonetheless we could make it more robust.

**Comment by hroest** [comment]
> Mapping the shared drive (i.e. associating a drive letter to it) solved the issue. Nonetheless we could make it more robust.

so the problem was that it was not mounted? Can we use Qt to check whether the file exists and is accessible and give a sensible warning?
