### ISSUE TITLE
Nightlies fail emg peakmodel

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3602]
http://cdash.openms.de/viewBuildError.php?buildid=277105

**Comment by jpfeuffer** [comment]
@pasqoo ?

**Comment by timosachsenberg** [comment]
are all OPENMS_DLLAPI in place? Maybe the EMG_friend also needs one?

**Comment by pasqoo** [comment]
@jpfeuffer the problem with emg might lie in the template definition within the cpp file. maybe the windows compiler doesn't like it
Even though https://docs.microsoft.com/en-us/cpp/cpp/source-code-organization-cpp-templates makes me think it should be ok.
What do you think?

**Comment by timosachsenberg** [comment]
hmm I am still not sure if the specialisation in the cpp needs the dll export via OPENMS_DLLAPI
@cbielow do you know if that is the case?

**Comment by jpfeuffer** [comment]
Yes I think the instantiations need to be explicitly exported, too.

**Comment by pasqoo** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by hroest** [comment]
this is still now working: http://cdash.openms.de/viewBuildError.php?buildid=276996


EGHFitter1D_test.cpp    166>Link:          C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\jenkins\ws\openms_nightly_packaging\c2e226b2\build\src\tests\class_tests\bin\Release\EmgGradientDescent_test.exe" /INCREMENTAL:NO /NOLOGO ..\..\..\..\lib\Release\OpenMS.lib ..\..\..\..\lib\Release\OpenSwathAlgo.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libCbc.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libCgl.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libClp.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libCoinUtils.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libOsi.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libOsiClp.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libsvm.lib "C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\xerces-c_3.lib" "C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libboost_iostreams-mt.lib" "C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libboost_date_time-mt.lib" "C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libboost_math_c99-mt.lib" "C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libboost_regex-mt.lib" C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\Wm5Core.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\Wm5Mathematics.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\libbz2.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\zlibstatic.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\sqlite.lib C:\jenkins\ws\openms_nightly_packaging\c2e226b2\contrib_build\lib\glpk.lib C:\dev\Qt\5.10.1\msvc2015_64\lib\Qt5Network.lib C:\dev\Qt\5.10.1\msvc2015_64\lib\Qt5Core.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"/.../build/src/tests/class_tests/bin/Release/EmgGradientDescent_test.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"/.../build/lib/Release/EmgGradientDescent_test.lib" /MACHINE:X64  /machine:x64 EmgGradientDescent_test.dir\Release\EmgGradientDescent_test.obj                            

166>EmgGradientDescent_test.obj : error LNK2019: unresolved external symbol "public: void __cdecl OpenMS::EmgGradientDescent::fitEMGPeakModel<class OpenMS::MSChromatogram>(class OpenMS::MSChromatogram const &,class OpenMS::MSChromatogram &,double,double)const " (??$fitEMGPeakModel@VMSChromatogram@OpenMS@@@EmgGradientDescent@OpenMS@@QEBAXAEBVMSChromatogram@1@AEAV21@NN@Z) referenced in function main [C:\jenkins\ws\openms_nightly_packaging\c2e226b2\build\src\tests\class_tests\openms\EmgGradientDescent_test.vcxproj]

**Comment by hroest** [comment]
@jpfeuffer sorry, am I looking at the previous nightlies and it is fixed now?

**Comment by jpfeuffer** [comment]
Ah yes, the CI for the PR was successful today. Maybe I was closing it a bit prematurely but let's hope the best ;)

**Comment by pasqoo** [comment]
Oh right, I also did not think about waiting for the nightly build, on gitter. Sorry :smiley:
