### ISSUE TITLE
KNIME and MascotAdapterOnline fails for Mascot 2.6

### ISSUE THREAD

**Issue by julianu** [OpenMS/OpenMS#3611]
Hej OpenMS Team,

We just updatet our Mascot server to version 2.6.2 (from 2.5) and are running into problems with the stable KNIME nodes (2.3.0.201712221504):
The Mascot node is starting the search and it is finishing on the server, but the transfer back to OpenMS does not work. Errors on the nodes are:

Standard output:
> [...]
> Submitting Mascot query (now: 2018-07-10 10:54:02)...
> Mascot query finished
> An error occurred during the query: MascotRemoteQuery: The server returned an error status code '404': Not Found
> Try accessing the server
>   mascot/mascot
>  from your browser and check if it works fine.
> MascotAdapterOnline took 7.14 s (wall), 1.65 s (CPU), 0.02 s (system), 1.63 s (user).
> Peak Memory Usage: <unknown>

Error output:
> MascotRemoteQuery: An error occurred (requestId=8): Request aborted (QT Error Code: 7)
> MascotRemoteQuery: An error occurred (requestId=10): Request aborted (QT Error Code: 7)

Obviously, accessing the server via the browser does work at the indicated addresses.

I may have pinned the problem down to a change in the export behavior of Mascot, as the call of
> GET /mascot/cgi/export_dat_2.pl?file=..%2F ....
Gets redirected to a caching-site:
> GET /mascot/cgi/nph-cache_families.pl?file=..%2Fdata%
and the node seems to not expect this.

Is this already fixed in the nightlies and maybe coming to the stable branch soon? Or is there another way to get the KNIME nodes working with Mascot 2.5 again?
For some reasons I don't like to use the nightlies branch on the stable workflows ;)

**Comment by julianu** [comment]
Any information on whether Mascot 2.6 and the stable OpenMS 2.3 should work together?

**Comment by jpfeuffer** [comment]
I don't know.  All I can say is that we do queries to the mascot example server for the nightly tests. Seems to work fine. I don't know which version they use though.

**Comment by julianu** [comment]
After 2.4 became stable (in KNIME), I tried the new version, which sadly still does not work. The error the KNIME node gives me states the following 
`Error transferring http://mascot//cgi/nph-cache_families.pl?fi`
which is curious, as the `server_path` seems to be ignored. `hostname` and `server_path` are both mascot in our environment, but the latter seems to be empty in the error message.

Furthermore: when skipping the export (great new feature btw, which saves me a lot of time), the node finishes correctly.

**Comment by jpfeuffer** [comment]
I had a short look.
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/MascotRemoteQuery.cpp#L300

This might the problem. Might only occur if hostname=mascot

**Comment by julianu** [comment]
Yes, could well be. Thus it could also be totally unrelated to the version, as we changed the hostname  incidentally during the upgrade of Mascot to 2.6
