### ISSUE TITLE
FFMultiplex broken

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3616]
I get some weird results in label-free analysis. Maybe related to the refactoring into a class.

![image](https://user-images.githubusercontent.com/5803621/42642071-4a90eb32-85f6-11e8-8db6-a2d828e8cca0.png)

**Comment by hroest** [comment]
can you check whether v2.3 was still working?

**Comment by timosachsenberg** [comment]
One problem is related to the automatic determination of centroided vs. profile in
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderMultiplexAlgorithm.cpp#L971

Checking the meta data first is usually better than relying on estimation from MS1 or MS2 (whatever is in the 0th spectrum):
          // determine type of spectral data (profile or centroided)
          SpectrumSettings::SpectrumType spectrumType = s.getType();
          if (spectrumType == SpectrumSettings::CENTROID)
{

**Comment by timosachsenberg** [comment]
but there seems to be another problem, e.g. visible in the BSA1.mzML in our examples.
Even with disabling the new rt_band parameter I get:
![grafik](https://user-images.githubusercontent.com/5803621/42748681-547d0052-88e1-11e8-9bc8-a96df8ef50a4.png)

Feature boundaries are totally off

**Comment by timosachsenberg** [comment]
I can prepare a fix for the centroided detection

**Comment by hroest** [comment]
> I can prepare a fix for the centroided detection

is there a force flag to override manual detection?

**Comment by timosachsenberg** [comment]
I think I found the problem. It was not related to centroided / profile mode as first supposed.
The real problem seem to be data sets with a lot of 0 intensities. @lars20070 can you check if this is the case? I filtered the data with a threshold of 10000  and I get very nice results now.

**Comment by timosachsenberg** [comment]
And that is the case for the iPRG2016 file and the BSA1.mzML file in our examples

**Comment by timosachsenberg** [comment]
removing only the zeros doesn't seem enough (just tested by setting the threshold to 0.05) unfortunately.

**Comment by timosachsenberg** [comment]
fixed with lars PR
