### ISSUE TITLE
PercolatorAdapter: parameter train-best-positive doesn't seem to work

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3628]
xception caught: Percolator version 3.01.nightly-22-2f4e2a6-dirty, Build Date Nov 29 2017 18:07:41
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.

Usage:
   percolator [-X pout.xml] [other options] pin.tsv
pin.tsv is the tab delimited output file generated by e.g. sqt2pin;
  The tab delimited fields should be:
    id <tab> label <tab> scannr <tab> feature1 <tab> ... <tab>
    featureN <tab> peptide <tab> proteinId1 <tab> .. <tab> proteinIdM
  Labels are interpreted as 1 -- positive set and test set, -1 -- negative set.
  When the --doc option the first and second feature should contain
  the retention time and difference between observed and calculated mass;
pout.xml is where the output will be written (ensure to have read
and write access on the file).

ERROR: the option --train-best-positive is invalid.

**Comment by timosachsenberg** [comment]
so I don't know if this is a bug. @jpfeuffer do you know about this?

**Comment by jpfeuffer** [comment]
Is this fixed with the new version?

**Comment by timosachsenberg** [comment]
yep seems to work
