### ISSUE TITLE
Doxygen html pages are missing javascript

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3631]
This happens for nightly and past builds:

- http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/classOpenMS_1_1ReactionMonitoringTransition.html
- https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1ReactionMonitoringTransition.html

```
Uncaught ReferenceError: $ is not defined
    at classOpenMS_1_1React…gTransition.html:30
```

so this means that we do not have a navigation tree (I am fine with that), but also no expanding of inherited members (that is annoying). 

it seems that jquery is missing and you can manually get it all working without errors if you include the following in your html:

```
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" type="text/javascript"></script>
    <script src="navtreedata.js" type="text/javascript"></script>
    <script src="navtree.js" type="text/javascript"></script>
    <script src="dynsections.js" type="text/javascript"></script>
```

**Comment by hroest** [comment]
Similarly, `doc/html/annotated.html` is also completely unusable since it does not expand.

**Comment by hroest** [comment]
This issue is only partially fixed, see https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/index.html and I still see some errors in the chrome console:

```Failed to load resource: the server responded with a status of 404 (Not Found)
searchdata.js Failed to load resource: the server responded with a status of 404 (Not Found)
search.js Failed to load resource: the server responded with a status of 404 (Not Found)
index.html:41 Uncaught ReferenceError: SearchBox is not defined
    at index.html:41
index.html:50 Uncaught ReferenceError: init_search is not defined
    at HTMLDocument.<anonymous> (index.html:50)
    at e (jquery.js:44)
    at Object.fireWith (jquery.js:44)
    at Function.ready (jquery.js:44)
    at HTMLDocument.e (jquery.js:44)
mag_sel.png Failed to load resource: the server responded with a status of 404 (Not Found)
close.png Failed to load resource: the server responded with a status of 404 (Not Found)
search.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

which leads to somewhat strange visualization bug: 

![screenshot from 2018-08-14 14-14-15](https://user-images.githubusercontent.com/464014/44109988-7fa7e66e-9fcc-11e8-9cfe-21f14ece3974.png)

where the search field is huge and creates a bug

**Comment by hroest** [comment]
@timosachsenberg @jpfeuffer it looks like #3654 is only a partial fix - on my computer it looks great and works but the online nightly docu does have the bug where the search js and css does not get copied

**Comment by jpfeuffer** [comment]
True. I was collapsing the folder structure in the html before since it didn't make a difference. Now it should work.
