### ISSUE TITLE
Codacy works on test files, not header files

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3640]
Again in #3639 codacy complains about the function signature in the `src/tests/class_tests/openms/source/PrecursorCorrection_test.cpp` file but *not* about the actual function signature in `src/openms/include/OpenMS/FILTERING/CALIBRATION/PrecursorCorrection.h ` which is the one that matters. 

What is happening here? Wrong configuration?

This is the link: https://app.codacy.com/app/hroest/OpenMS/pullRequest?prid=1949836

**Comment by timosachsenberg** [comment]
hmm the annoying thing about codacy is that it uses your configuration now.
I wrote them a while ago how to restore the original settings but they couldn't really help.
Can you check if there is something fishy in your configuration?

**Comment by hroest** [comment]
maybe its the file extensions?

```
C
Supported: .c, .h

CPP
Supported: .cpp, .hpp, .cc, .cxx
```
