### ISSUE TITLE
SpecLibCreator adapter: info.csv file :: question/help

### ISSUE THREAD

**Issue by Fr4nc3sc0xyz** [OpenMS/OpenMS#3675]
Dear all,
I'm trying to use the SpecLibCreator adapter to generate a spectral library (.msp) to import in Skyline.
Despite several attempts, the adapter does not accept the info.csv file containing information about peptide id, sequence , retention time.., etc. Indeed, the process quits with the following message:

Error: The required parameter 'unclear which parameter is retention time' was not given or is empty!

I organized the csv file in columns in which each header correspond to id, sequence, retention time, etc. That's the same csv output format obtained from the Text Exporter adapter.
I understand that the problem is in the structure of the csv file but I can not figure out at which point.
Please could you give me some hints on how to structure the csv info file? In case, could you provide me a template of it?

Another question: is it possible to generate a specral library in mzid or sptxt formats that can be subsequently imported to PeakView (ABSciex) without resorting to the spectrast TPP adapter? If yes, could you explain me how to proceed?

Thank you in advance.

Francesco

**Comment by hroest** [comment]
Hi Francesco, maybe you could explain directly what it is you are trying to achieve? If you want to create a spectral library, I suggest to follow the protocol of Schubert et al 2015 https://www.ncbi.nlm.nih.gov/pubmed/25675208 which explains all the individual steps. I am not sure whether you can import a sptxt or mzid library into PeakView, you will have to ask SCIEX customer support for that.

**Comment by Fr4nc3sc0xyz** [comment]
Hi Hannes,
I ll try to clarify my point. So, I already used the protocol of Schubert et al. to create a spectral library (sptxt file) for my SWATH analysis and it works very well. In this pipeline you need to pass through several steps that rely on an identification step on X!Tandem and/or Comet modules in TPP, the refinement through Xinteract and protein Prophet, the calculation of FDR through Mayu and finally the generation of an assay spectral library for SWATH data through Anaconda (spectrast2tsv.py) that allow you to generate a file either for peakview (sptxt) or for Skyline and OpenMS (Traml).
My aim is to find other ways to generate spectral libraries to upload in Skyline or peakview. I explored the overall decision tree of OpenMS and in fact I did not find any module that convert idXML (identification) results into a sptxt or mzid spectral library.
The only adapter I found is called SpectraLibCreator that, if I well understood, it allows you to create a spectral library file in the msp format (that can be imported to Skyline). In order to work, it needs of an info file (csv) that contains the peptide sequence, retention time, id informations of the identification results. The problem here is that the structure of the csv file I created is not correct because the process stops after few seconds (with the error message I wrote above). I am wondering if there is some documentation that may explain how to write this file (which should be the structure of this file). 
In general, is there any other way to create a spectral library  by just using the OpenMS (Toppas) pipeline?
Thank you so much for your kind reply.
Regards,

Francesco

**Comment by hroest** [comment]
Hi Francesco

Unfortunately the SpectraLibCreator was not designed for this purpose or for any DIA spectral library generation, it pre-dates this purpose. I think with Skyline the best approach is through step 37B in the protocol using `C:\Anaconda\Scripts\spectrast2tsv.py`, do not try to use SpectraLibCreator as it will not work. Maybe @grosenberger can comment on whether there is a way to use OpenMS to generate assays and export to Skyline format?
