### ISSUE TITLE
OpenSwathWorkflow file format

### ISSUE THREAD

**Issue by mchiapello** [OpenMS/OpenMS#3676]
Is it OpenSwathWorkflow able to handle mzIdentML or idXML files? If not, is there the idea to implement it?

**Comment by grosenberger** [comment]
As input, OpenSWATH requires spectral libraries and it supports HUPO-PSI TraML, which can be generated from pepXML/mzIdentML/idXML via SpectraST.

As output, OpenSWATH does currently not support mzIdentML/mzQuantML. Although some of the scores and properties could be translated, the files would become extremely large and I'm not sure if any other tools downstream could process them directly.

**Comment by mchiapello** [comment]
thank you
