### ISSUE TITLE
FeatureLinkerUnlabelledQT writes no file names by default

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3683]
Following tools such as `FileFilter` complain with
```
Map descriptions (file name + label) in ConsensusMap are not unique:
  file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label:   file: UNKNOWN label: 
The ConsensusXML file contains invalid maps or references thereof. Please fix the file or notify the maintainer of this tool if you did not provide a consensusXML file! Note that this warning will be a fatal error in the next version of OpenMS!
```

**Comment by rickhelmus** [comment]
Hello,

Not sure if this is fully related. I just switched to OpenMS 2.4 and `FeatureLinkerUnlabeled` (and QT) now complain with `No MS run annotated in feature map. Setting to 'UNKNOWN'` and then (if >1 featureXML is given as input) followed by the same message as above.

**Comment by m-jahn** [comment]
I can confirm this for both `FeatureLinkerUnlabeledQT` and `FeatureLinkerUnlabeledKD`. The problem is that the missing run annotation is propagated through the rest of the pipeline. Then it's not obvious any more which runs are which in output from following nodes, e.g. ProteinQuantifier. Is at least the order of featureXML files preserved, so that A.featureXML, B.featureXML and so on correspond to UNKNOWN 1, UNKNOWN 2 and so on? 

BTW the previous node in my pipeline is FeatureFinderIdentification, maybe this module fails to add metadata for the runs?

**Comment by jpfeuffer** [comment]
Hmm unfortunately we cannot reproduce this on fresh mzML files (like our tutorial data).
It could be mzML files from old msconvert versions not carrying a sourceFile entry.
However: FeatureFinderIdentification actually takes the sourceFile from the "-in" parameter that you provided so we don't know what is happening here. Can you send us / upload some example files? 
At least the upper part of the mzML as well as one of the featureXMLs.

**Comment by m-jahn** [comment]
Thanks for looking into that. Here's the head of the first featureXML file and the consensusXML file (consensus of 10 runs) as output from `FeatureLinkerUnlabeledKD`. I just copied the first 120 lines of both files. The msConvert version we used was the recent  [docker container for linux](https://hub.docker.com/r/chambm/pwiz-skyline-i-agree-to-the-vendor-licenses). Let me know if you need more info.

[20190103_A1_0_featureXML_head.txt](https://github.com/OpenMS/OpenMS/files/3057678/20190103_A1_0_featureXML_head.txt)
[20190103_consensusXML_head.txt](https://github.com/OpenMS/OpenMS/files/3057679/20190103_consensusXML_head.txt)

**Comment by oliveralka** [comment]
Would it be possible to send us one or two example mzMLs - then we will try to reproduce the issue. 
Which version of OpenMS are you currently using?

**Comment by m-jahn** [comment]
I'm using KNIME version 3.7.0 (Dec 2018) and openMS version 2.4.0. Sure I can send you some mzML files but they are quite big so mail won't do. I could send you a google drive link if you give me your mail address.

**Comment by oliveralka** [comment]
@m-jahn Ok, thank you - would you please send the link to alka@informatik.uni-tuebingen.de

**Comment by oliveralka** [comment]
@m-jahn Thank you for the files. 

It seems that the 2.4.0 release branch was split before the function was introduced for FeatureFinderIdentifcation. 

The are two possible options:
1) Use the current nightly release (there it should work without any issues)
KNIME: `http://update.knime.com/community-contributions/trunk`

2) Wait for the next OpenMS 2.5.0 release (which will be out soon)

**Comment by m-jahn** [comment]
Then I know. I think for now I will simply wait for the next release. But can anybody comment on my previous question, if the order of input files and output is conserved? In this case, do the featureXML files 1, 2, 3 and so on correspond to the same sections in the consensusXML file, or the same columns in a *.csv text output?

**Comment by jpfeuffer** [comment]
Yes via TextExporter and FeatureTextReader the numbers in the column headers correspond to the order of the input files given to the feature linker.
Via MzTabExporter and MzTabReader the numbers in the study_variable[n] columns correspond to the ms_runs in the Metadata header. (Not sure what happens if the file references are missing though).
