### ISSUE TITLE
GluC enzyme specificity

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3686]
We allow (among others) for the following enzymes
```
glutamyl endopeptidase
V8-E
V8-DE
```
Are two of them identical/double?

**Comment by timosachsenberg** [comment]
Hi Lars. I think you can check the regex stored in the EnzymesDB

**Comment by hroest** [comment]
> Hi Lars. I think you can check the regex stored in the EnzymesDB

that is not a great documentation, we should have an easier way to document these. Either use doxygen or use pyOpenMS to print out a summary.

**Comment by lars20070** [comment]
@timosachsenberg The issue is just a reminder for myself.

**Comment by lars20070** [comment]
@Matthias313 @oliverschilling
`V8-DE`    -->    `[BDEZ]|{P}`
`V8-E`    -->    `[EZ]|{P}`
`glutamyl endopeptidase`    -->    `[DE]|[X]`
On the right-hand side you can see the *XTandem* cutting rules. `X` stands for *anything*. What does `B` and `Z` stand for?

For our Glu-C digestions we should consequently use the last rule `[DE]|[X]`. Correct?

**Comment by lars20070** [comment]
`Z` = `E (Glu)` or `Q (Gln)`
`B` = `D (Asp)` or `N (Asn)`
@DilzaTrevisan Thanks.

**Comment by lars20070** [comment]
The rules are accessible in [`Enzymes.xml`](https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/CHEMISTRY/Enzymes.xml) and not hard-coded. IMO, that's fine and no further docu is needed.
