### ISSUE TITLE
OpenMS 2.4 is now available on the Debian repositories

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#3687]
Greetings,

just to let you know that OpenMS is now available in Debian (sid) as version 2.4.

Thanks for such an awesome mass spec package.

Cheers,
Filippo

**Comment by lopippo** [comment]
Update:

the build of OpenMS fails on the armhf platform. If anybody is interested in fixing the build this is the log url:

https://buildd.debian.org/status/fetch.php?pkg=openms&arch=armhf&ver=2.4.0-1&stamp=1534525425&file=log

Cheers,
Filippo

**Comment by AdrianBunk** [comment]
On the armel and armhf ports in Debian (and on the armhf and arm64 ports in Ubuntu) Qt5 is compiled with OpenGL ES.

The only way to fix these builds would be to make (and keep) all OpenGL code in OpenMS compatible with OpenGL ES.

**Comment by DarioS** [comment]
How is it possible if it hasn't been released as a source version on GitHub nor the OpenMS website?

**Comment by lopippo** [comment]
Is not this enough ?

https://github.com/OpenMS/OpenMS/tree/release/2.4.0

**Comment by DarioS** [comment]
I'm not sure but I don't see it in the [release listing](https://github.com/OpenMS/OpenMS/releases) and it appears to be only [28% complete](https://github.com/OpenMS/OpenMS/milestone/13).

**Comment by lopippo** [comment]
What is that "28% complete" metric ? This is odd, since the build went flawlessly. Hmm, can anybody tell if the release/2.4.0 nomenclature actually corresponds to a release that is ready or not ? If not, then that is misleading.

**Comment by hroest** [comment]
Dear Dario and Filippo

The official releases of OpenMS are here:
https://github.com/OpenMS/OpenMS/releases while what Filippo was using
was a "branch" in git which was forked from the main development
branch some weeks ago, however it does not mean that this is a
finished and tested release. I suggest to use the above link to obtain
official releases and monitor the open-ms-announcements list to obtain
information about new releases.

The 28% complete metric is a way for us to track issues and feature
requests for the release that we may want to implement.

Best

Hannes

**Comment by hroest** [comment]
> So, what now ? I'll refrain from packaging any non-Qt5 version.

I suggest you wait until we have a release version from https://github.com/OpenMS/OpenMS/releases 



> It's incredible that with this low value, the whole project builds perfectly fine with the Qt 5 port code enabled.

yes, we have continuous integration, so the project should build at all times. The 28% is basically there because we have a bunch of old issues that we need to roll over and decide whether we will implement them for this release (critical issues) or defer to the next release. I think in the next couple of days that value will go up to 100% quickly.

**Comment by lopippo** [comment]
Hello Hannes,

On Wed, Aug 22, 2018 at 09:37:24AM -0700, Hannes Roest wrote:
>> So, what now ? I'll refrain from packaging any non-Qt5 version.
>
>I suggest you wait until we have a release version from https://github.com/OpenMS/OpenMS/releases
>
>
>
>> It's incredible that with this low value, the whole project builds perfectly fine with the Qt 5 port code enabled.
>
>yes, we have continuous integration, so the project should build at all times. The 28% is basically there because we have a bunch of old issues that we need to roll over and decide whether we will implement them for this release (critical issues) or defer to the next release. I think in the next couple of days that value will go up to 100% quickly.

... As usual, so kind. Thank you for the details.

Cheers,
Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
          http://www.debian.org

**Comment by jpfeuffer** [comment]
Hi @lopippo.

We tagged the head of the release/2.4.0 branch to mark it as stable and created an official GitHub release. You can proceed with the release procedure on your side. The rest of the issues will have to be postponed (we think it is stable enough).

Cheers
Julianus

**Comment by lopippo** [comment]
Greetings,

On Tue, Oct 30, 2018 at 05:06:53AM -0700, jpfeuffer wrote:
>We tagged the head of the release/2.4.0 branch to mark it as stable and created
>an official GitHub release. You can proceed with the release procedure on your
>side. The rest of the issues will have to be postponed (we think it is stable
>enough).

Thank you for the update. May I suggest that the .git directory has not its
place in the source tar.gz, or... is it there on purpose?

Anyways, I am starting work on the soft right now.

Thanks again for pinging me!

Cheers,
Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
          http://www.debian.org

**Comment by jpfeuffer** [comment]
> May I suggest that the .git directory has not its place in the source tar.gz, or... is it there on purpose?

Good point, no I also think it is not needed. I will add the removal to our packaging script.

**Comment by lopippo** [comment]
Greetings,


On Tue, Oct 30, 2018 at 08:07:45AM -0700, jpfeuffer wrote:
>> May I suggest that the .git directory has not its place in the source tar.gz, or... is it there on purpose?
>
>Good point, no I also think it is not needed. I will add the removal to our packaging script.

This is the output of my "purification" script:

Now removing all the .exe files
removed './cmake/Windows/FolderList.exe'
removed './cmake/Windows/install.exe'

Now removing all the .dll files
removed './cmake/Windows/Plugins/x86-ansi/INetC.dll'
removed './cmake/Windows/Plugins/x86-ansi/UAC.dll'
removed './cmake/Windows/Plugins/x86-unicode/INetC.dll'
removed './cmake/Windows/Plugins/x86-unicode/UAC.dll'
removed './cmake/Windows/Plugins/amd64-unicode/INetC.dll'

Now removing all the .pyc files
removed './src/pyOpenMS/pyTOPP/common.pyc'

Now removing all the .git* files
removed './doc/code_examples/data/.gitattributes'
removed './src/openswathalgo/thirdparty/MIToolbox/.gitignore'
removed './src/pyOpenMS/tests/memoryleaktests/.gitignore'
removed './src/tests/topp/.gitattributes'
removed './src/tests/class_tests/openms/data/.gitattributes'
removed './.gitmodules'
removed './.gitignore'

file ./doc/code_examples/Tutorial_Enzyme.cpp not binary. Running chmod a-x on it.
tons of these...

Cheers,
Filippo
-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
          http://www.debian.org

**Comment by lopippo** [comment]
Greetings,

going on with work... I wanted to let you know of this bug, now that the Qt5
port is released: 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=%23906666

Could you check into it and tell me if there is a solution to it?

Depending on your answer I'll have to configure the packaging in different
ways...

Cheers,
Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
          http://www.debian.org

**Comment by lopippo** [comment]
Greetings, 

going on. Please tell me if this is not right channel to discuss the issues with
packaging.

For the time being, here is another technical mail:

in Debian, we prefer having license/copyright notices in code programs. While a
majority of cmake files have one, the following ones miss one (if I am not
mistaken). 

Would you try to fix these ?

The following files have no copyright notice.
=============================================

OpenMSConfig.cmake.in
OpenMSConfigVersion.cmake.in
OpenMSPackageDescriptionFile.cmake
package_components.cmake
package_deb.cmake
package_nsis.cmake
package_rpm.cmake

Thank you,
Cheers,
Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
          http://www.debian.org

**Comment by jpfeuffer** [comment]
Hmm interesting.. I think I changed it to a fixed OpenGL version because of some problems on macOS.
We could try to revert that change to the Canvas here, maybe it was not only the versioning change that fixed our problems:
https://github.com/OpenMS/OpenMS/pull/3451/commits/83ff208224ae848fc18e3a3c5f9fe9050e413385

**Comment by lopippo** [comment]
On Tue, Oct 30, 2018 at 08:48:46AM -0700, jpfeuffer wrote:
>Hmm interesting.. I think I changed it to a fixed OpenGL version because of some problems on macOS.
>We could try to revert that change to the Canvas here, maybe it was not only the versioning change that fixed our problems:
>https://github.com/OpenMS/OpenMS/pull/3451/commits/83ff208224ae848fc18e3a3c5f9fe9050e413385

I am not sure if that modification is related to building against OpenGL ES
instead of against OpenGL. If you think so, that would be very cool. Could you
try a build? I have no Mac setup ready for that.

Keep me posted on the results, so that I can perform the choice...

Cheers,
Filippo
-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
          http://www.debian.org

**Comment by timosachsenberg** [comment]
I think I tried once to restrict us to OpenGL ES and it didn't build.  We are still using fixed-function functions not supported by ES. Would be some work to change that. On the other hand, we still need to figure out a way to deal with the removal of OpenGL on Mac, so we currently see no clear way how to proceed. For now, I think we need to go without OpenGL ES.

**Comment by lopippo** [comment]
Greetings, Timo,

On Tue, Oct 30, 2018 at 06:18:58PM +0000, Timo Sachsenberg wrote:
>I think I tried once to restrict us to OpenGL ES and it didn't build.  We are still using fixed-function functions not supported by ES. Would be some work to change that. On the other hand, we still need to figure out a way to deal with the removal of OpenGL on Mac, so we currently see no clear way how to proceed. For now, I think we need to go without OpenGL ES.

It's fine, I'll configure the packaging accordingly.

Sincerely,
Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
          http://www.debian.org
