### ISSUE TITLE
Expose CI/CD scripts as much as possible

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3698]
Please upgrade autowrap on the docker pyopenms machines: https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_pr_docker_pyopenms/852/console

```

-- Adding library SuperHirn - SUCCESS
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Python found at /usr/bin/python with version 2.7 (if this is wrong, configure with -DPYTHON_EXECUTABLE:FILEPATH=/path/to/python)
-- Looking for Cython - found Cython 0.25.2, version ok
-- Found autowrap version 0.13.1. The version is too old (>= 0.18.1 is required)
CMake Error at src/pyOpenMS/CMakeLists.txt:167 (message):
  Please upgrade autowrap or disable pyOpenMS.


-- Configuring incomplete, errors occurred!
See also "/home/jenkins/ws/openms_pr_docker_pyopenms/OpenMS-build/CMakeFiles/CMakeOutput.log".
See also "/home/jenkins/ws/openms_pr_docker_pyopenms/OpenMS-build/CMakeFiles/CMakeError.log".
make: *** No rule to make target `pyopenms'.  Stop.
   Site: 8f96c8db485a
   Build name: Linux-c++
```

**Comment by jpfeuffer** [comment]
I install it via pip. Does it make sense to install it without a fixed version so that it always takes the newest?

**Comment by hroest** [comment]
> install it without a fixed version so that it always takes the newest?

hmm, in principle yes but I would even more prefer an option where we can set the version, such as in travis https://github.com/OpenMS/OpenMS/blob/develop/tools/travis/lnx-cibuild.before.sh#L37 -- however in absence of that, the newest version should also do.

**Comment by jpfeuffer** [comment]
I am now pulling the latest version everytime. I will try to expose the scripts better, too.
