### ISSUE TITLE
Jenkins does not report failure

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3699]
I have recently seen this here https://github.com/OpenMS/OpenMS/pull/3697 (see https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_pr_docker_pyopenms/852/):

```
  | This run spent:28 sec waiting;7 min 34 sec build duration;8 min 3 sec total from scheduled to completion.
  | Test Result (no tests)

```

which is reported as a success even though no tests were run and nothing was built. I think this should be reported as a failure.

**Comment by jpfeuffer** [comment]
I see. I think I fixed this for the regular tests but not for the "newer" pyopenms ones. I will have a look at it.

**Comment by jpfeuffer** [comment]
I think so. We do this:
```
make -j6 pyopenms
MAKE_RESULT=$?
ctest -j6 -T Test -R "pyopenms"
TEST_RESULT=$?
if [ $MAKE_RESULT == 0 ] && [ $TEST_RESULT == 0 ]; then
  exit 0
else
  exit 1
fi
```
