### ISSUE TITLE
SiriusAdapter tests fail

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3709]
see nightlies:
http://cdash.openms.de/testDetails.php?test=51878897&build=284389

**Comment by oliveralka** [comment]
Did this happen again?

All tests pass in my case (macOS & Scientific Linux)
Will check ubuntu later!  

Please let me know if that happens again - maybe another sorting issue?

**Comment by hroest** [comment]
> Did this happen again?

yes, I see it in about 30-50% of travis runs. It does look like a sorting issue:

```

in1:  /home/jenkins/ws/openms_nightly_packaging/40c74027/build/src/tests/topp/SiriusAdapter_1_output.tmp   (line: 11, position/column: 10/18)
SML	null	C!
   	    	 15H18ClN3O	null	null	null	null	null	null	null	null	null	null	null	null	null	16.2856533099491	-0.755534207033779	17.0411875169828	null	[M + H]+	1	1	0	6	5	null

in2:  /home/jenkins/ws/openms_nightly_packaging/40c74027/source/src/tests/topp/THIRDPARTY/SiriusAdapter_1_output.mzTab   (line: 11, position/column: 10/18)
SML	null	C!
   	    	 16H13N5O	null	null	null	null	null	null	null	null	null	null	null	null	null	0.960779286846719	0.960779286846719	0	null	[M + H]+	1	1	0	2	4	null
```

**Comment by hroest** [comment]
yes, seems to happen quite often, e.g. 7 times over the last week alone: http://cdash.openms.de/testSummary.php?project=3&name=TOPP_SiriusAdapter_1_out&date=2018-09-11

**Comment by timosachsenberg** [comment]
resolved? if not please reopen
