### ISSUE TITLE
OpenSWATH Outputs Inconsistently Formatted Intensity Values

### ISSUE THREAD

**Issue by DarioS** [OpenMS/OpenMS#3711]
I'm exploring the file named all_sites_global_q_0.01_applied_to_local_global.txt from the eleven-site study of HEK293 cells with spike-ins. Sometimes the Intensity value is stored as a number like 123701 whereas in other cases, it is 1e+05. Could OpenSWATH output consistently formatted numbers, to make ease-of-use better with other software, such as R? The values like 1e+05 are being converted into NA (missing data) by the text table import function I use.

**Comment by tjeerdijk** [comment]
Dear Dario,

When I use the command:
Y <- read.table("test.txt", header = TRUE)

to read in the file test.txt:
————————————————
# test.txt file with double number in both exponential and non-exponential notation
# Version 0.1, 4 Sept 2018 by Tjeerd Dijkstra
A	B
1	-0.3
2	0.00001
3	12345.6789
4	0.123e+12
5	0.456e-04
————————————————

I have no problem in R version 3.4.2 under OSX 10.13.6.

What function are you using to read in values in R?

Best,
Tjeerd

**Comment by DarioS** [comment]
I used readr's `read_delim` function.

```
$ cat numbers.txt 
Score
1050
2e+04
```

These scientific notation number is converted to NA.

```r
library(readr) # For speed.
read_delim("numbers.txt", delim = '\t', guess_max = 1)
Parsed with column specification:
cols(
  Score = col_integer()
)
Warning: 1 parsing failure.

  Score
  <int>
1  1050
2    NA
```

The import function works by sampling the first few rows, detects and expects all integers, but then, when reading the entire file, first encounters a floating point number which is really an integer in row 428422 of all_sites_global_q_0.01_applied_to_local_global.txt and subsequently in a few dozen other rows. If OpenSWATH consistently wrote numbers like 10000 and 13275 to the text file as integers (assuming the text file which I downloaded was not edited after creation with OpenSWATH), it would not be an issue.

**Comment by grosenberger** [comment]
I believe that OpenSwathWorkflow actually reports the full numeric values, but after processing with PyProphet, the values are reported in mixed formats.

Since we have moved on to a new SQLite-based file format, the respective fields can be directly accessed in the OSW files.

**Comment by tjeerdijk** [comment]
Hi Dario,

I would leave guess_max at its default value. Better yet, I would prescribe the format of the variables using the col_types parameter (this is a bit of work but pays off in terms of faster reading time)

Hope this helps,

Tjeerd

**Comment by DarioS** [comment]
Oh, so the problem described is no longer is applicable to the current version of OpenSWATH.
