### ISSUE TITLE
Evaluate the Azure CI/CD pipeline

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3727]
https://blog.github.com/2018-09-10-azure-pipelines-now-available-in-github-marketplace/

Free for non-commerical projects. No build time limit. Linux, Mac, Windows. 10 parallel jobs.
The numbers sound good and might be worth a try.

**Comment by jpfeuffer** [comment]
Works. See the azure-pipelines branch, where I tested it for Windows. But IIRC it takes over 2 hours. We might need to look into more caching etc.
