### ISSUE TITLE
MSGFPlus Memory Requirements

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#3741]
I'm running MSGFPlus on a 1.7G protein DB and 1G izid xml file. It seems that MSGFPlus uses quite a lot of memory: 

VIRT 29.2g  RES 17g

(according to top) 

Is this expected?

**Comment by timosachsenberg** [comment]
Hi, that's also what I observed. It's pretty heavy on resources if large databases are used.

**Comment by hendrikweisser** [comment]
I believe the question has been answered.

**Comment by bernt-matthias** [comment]
You are right -- thanks.
