### ISSUE TITLE
[Linux packaging] Missing packages/wrong softlinks

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3753]
Something is wrong with the KNIME plugin on linux. It links to libQt5 with a specific version but we only ship the file without version suffix.
Also there is a lib missing which is not installable anymore on newer ubuntus and the new versions are not really backwards compatible because the maintainers decided to encode the minor version in the library name. Forgot which one it was, willl look it up.

**Comment by jpfeuffer** [comment]
Ok I fixed the softlinks. But I have a general opionion question for the linux users here
@hroest , @timosachsenberg 

In the debian package for example, we are calculating/defining dependencies on other deb packages. A little problem arises when we use the packages from the thirdparty beineri repository. It will show up as a dependency in the generated package and users have to add that repository first before installing our package.
In newer ubuntus of course the standard qt5base package is sufficient.
So I see four options now:
1) ship Qt5 in our package
2) do not add Qt5 as a dependency and expect users to have a matching version to be installed
3) have all the different packages as alternatives in the dependencies (e.g. qt57base | qt58base | qt59base | qt510base | qt511base | qtbase5-dev, 
, qt57svg | qt58svg | qt59svg | qt510svg | libqt5svg5)
4) drop support (in the package only) for older linuxes and just add the standard package as dependency (this is probably what the deb maintainers do, too)

**Comment by timosachsenberg** [comment]
I would probably go with the standard package

**Comment by jpfeuffer** [comment]
Ok for our own packages which are mainly intended for testing and quick distribution I implemented solution 3. I add the dependencies manually again, since with automatic generation the dependency list is a bit too long and is not easily modifiable by us anymore (e.g. to add alternatives or remove things). The downside is, as soon as something changes on the build machines (e.g. some shared dep. is added or something can/is not built static anymore) this has to be changed, too.

**Comment by jpfeuffer** [comment]
Currently I am thinking on how to ensure that Qt is correctly installed when you distribute pyOpenMS or the KNIME plugin. Any ideas? Just give a warning during installation?

**Comment by jpfeuffer** [comment]
For now I package everything but system libraries (for the KNIME plugin). Usually when users use KNIME, they are not very familiar with installing libraries, so I think this is our best bet for now.
