### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3754]
I am trying to understand memory allocation in C++ and I was hoping somebody has some insight:

```C++
#define SHOW_ISSUE

int main(int argc, const char** argv)
{ 
  SysInfo::MemUsage mu;
  std::vector<PeptideIdentification> pep_ids2;
  { 
    std::vector<PeptideIdentification>* pep_ids = new std::vector<PeptideIdentification>();
    for (Size k = 0; k < 1e6; k++)
    { 
      PeptideIdentification p;
      p.insertHit(PeptideHit());
      pep_ids->push_back(std::move(p));

    }

#ifndef SHOW_ISSUE
    delete pep_ids;
#endif
    pep_ids2.reserve(1e6);
    for (Size k = 0; k < 1e6; k++)
    { 
      PeptideIdentification p;
      p.insertHit(PeptideHit());
      pep_ids2.push_back(std::move(p));
    }
#ifdef SHOW_ISSUE
    delete pep_ids;
#endif
  }
  std::cout << "\n" << pep_ids2.size() << std::endl;
  std::cout << "\n" << mu.delta("loading data") << std::endl;
}
```

my observations

- `#define SHOW_ISSUE`
```
Memory usage (loading data): 437 MB (working set delta)
```

- `// #define SHOW_ISSUE`
```
Memory usage (loading data): 299 MB (working set delta)
```

so depending on whether the `delete pep_ids` statement is before or after the second loop, the memory requirement changes. However, when measuring memory consumption the only data in memory should be 1e6 elements of `PeptideIdentification` which should always take the same amount of memory. So I am not sure whether that is an issue with the measurement technique and how my OS (Linux) reports memory consumption, whether its the memory allocator that keeps around extra memory (with the idea that future objects may fit in there) or whether its some strange behaviour of std::vector. Happy to hear any insight / tests from other platforms (OSX / Windows) or explanations.

For reference:

# Only first loop
```C++
int main(int argc, const char** argv)
{ 
  SysInfo::MemUsage mu;
  std::vector<PeptideIdentification> pep_ids2;
  { 
    std::vector<PeptideIdentification>* pep_ids = new std::vector<PeptideIdentification>();
    for (Size k = 0; k < 1e6; k++)
    { 
      PeptideIdentification p;
      p.insertHit(PeptideHit());
      pep_ids->push_back(std::move(p));

    }
    std::cout << "\n" << pep_ids->size() << std::endl;
    delete pep_ids;
  }
  std::cout << "\n" << mu.delta("loading data") << std::endl;
}
```

outputs `Memory usage (loading data): 2 MB (working set delta)` and 

# Only second loop

```C++
int main(int argc, const char** argv)
{ 
  SysInfo::MemUsage mu;
  std::vector<PeptideIdentification> pep_ids2;
  {
    pep_ids2.reserve(1e6);
    for (Size k = 0; k < 1e6; k++)
    { 
      PeptideIdentification p;
      p.insertHit(PeptideHit());
      pep_ids2.push_back(std::move(p));
    }
  }
  std::cout << "\n" << pep_ids2.size() << std::endl;
  std::cout << "\n" << mu.delta("loading data") << std::endl;
}
```

outputs `Memory usage (loading data): 299 MB (working set delta)`

So therefore it really seems to the combination of the two loops and the placement of the delete operator. So under these circumstances, the `delete` operator does what it is supposed to do.

**Comment by cbielow** [comment]
what is surprising here is that the preallocated `pep_ids2` takes 299 MB, whereas the growing `pep_ids` only takes 147?
Would be interesting to see: 
1) what happens if you prealloc also the heap version
2) what does MU say in the case of "only first loop" before the `delete`.

**Comment by cbielow** [comment]
In terms of memory model... this gets complicated rather quickly, and I don't know what MU actually measures on Linux. My understanding (please correct me) is that delete (with underlying free) will return the memory to the OS. However, the OS keeps track of which pages have been allocated to each program (since upon first allocation the OS will 'null' the memory [otherwise you could read memory from old pages of other processes]). So depending on what MU counts as memory 'assigned' to the process, you get different results.

**Comment by hroest** [comment]
I have now tested

> what happens if you prealloc also the heap version

basically adding `pep_ids->reserve(1e6);` after creation, right?
- `#define SHOW_ISSUE` gives `437 MB (working set delta)`
- `//#define SHOW_ISSUE` gives `299 MB (working set delta)`

so it does not make a difference at all.

> what does MU say in the case of "only first loop" before the `delete`.
```C++
int main(int argc, const char** argv)
{ 
  SysInfo::MemUsage mu;
  std::vector<PeptideIdentification> pep_ids2;
  { 
    std::vector<PeptideIdentification>* pep_ids = new std::vector<PeptideIdentification>();
    for (Size k = 0; k < 1e6; k++)
    { 
      PeptideIdentification p;
      p.insertHit(PeptideHit());
      pep_ids->push_back(std::move(p));

    }
    std::cout << "\n" << pep_ids->size() << std::endl;
    // delete pep_ids;
  }
  std::cout << "\n" << mu.delta("loading data") << std::endl;
}
```

gives `Memory usage (loading data): 306 MB (working set delta)` while



```C++
int main(int argc, const char** argv)
{ 
  SysInfo::MemUsage mu;
  std::vector<PeptideIdentification> pep_ids2;
  { 
    pep_ids->reserve(1e6);
    std::vector<PeptideIdentification>* pep_ids = new std::vector<PeptideIdentification>();
    for (Size k = 0; k < 1e6; k++)
    { 
      PeptideIdentification p;
      p.insertHit(PeptideHit());
      pep_ids->push_back(std::move(p));

    }
    std::cout << "\n" << pep_ids->size() << std::endl;
    // delete pep_ids;
  }
  std::cout << "\n" << mu.delta("loading data") << std::endl;
}
```

gives `Memory usage (loading data): 299 MB (working set delta)`
