### ISSUE TITLE
Check for gcc version

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3756]
Just a question, do we currently check for a minimal gcc version? It may actually be a good idea instead of having the user walk into problems down the road. See https://stackoverflow.com/questions/14933172/how-can-i-add-a-minimum-compiler-version-requisite

The other approach is `try_compile()`

**Comment by hroest** [comment]
> Depends on why you want to check it. We do set the required CXX standard which should fail if the flags (and maybe even some features) do not exist. But it seems it might not work for MSVC. See https://stackoverflow.com/questions/10984442/how-to-detect-c11-support-of-a-compiler-with-cmake

also it is not complete, e.g. for gcc 4.8 it passes even though it only supports part of the standard, see https://github.com/OpenMS/OpenMS/pull/3755

**Comment by hroest** [comment]
However, as discussed here https://github.com/OpenMS/OpenMS/issues/980#issuecomment-198783912 we probably want / need to support gcc 4.8 for a while in the future - otherwise people will have trouble to compile OpenMS on a HPC cluster.

**Comment by jpfeuffer** [comment]
Hmm ok.. what about the conditional macro for the non-supported specifiers that you proposed? Would that solve it?
