### ISSUE TITLE
MetaValue crashes

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3765]
There are a few failing ASan tests here:
http://cdash.openms.de/viewTest.php?onlyfailed&buildid=287658

All the tests boil down to that "BaseLabeler" fails in mergeProteinIdentificationMaps_.
It might have something to do with copy constructing an object that has a MetaInfoInterface (here a ProteinHit).
So this might be related to the PR here: https://github.com/OpenMS/OpenMS/pull/3733

This is interesting and I took a look. Basically I took a look at the lines:
```
// Line 1: src/openms/source/ANALYSIS/ID/PercolatorFeatureSetHelper.cpp:529
hit->setMetaValue("CONCAT:" + search_engine, hit->getMetaValue("MS:1002049"));  // rawscore
// Line 2: src/openms/source/SIMULATION/LABELING/BaseLabeler.cpp:105
protHit.setMetaValue("intensity_" + String(channel_index), protHit.getMetaValue("intensity"));
```

which are all occurences of 
```
x.setMetaValue("something", x.getMetaValue("somethingelse"));
```

it turns out that this construct is not safe! What actually happens is `x.getMetaValue("somethingelse")` returns a reference to a `DataValue` that has been allocated by the boost flat_map, however then `setMetaValue` executes this line:

```
index_to_value_[index] = value;
```

which causes ` OpenMS::DataValue::operator=(OpenMS::DataValue const&)` to be called.  think what happens is that the reference to the old data value ` x.getMetaValue("somethingelse")` becomes invalid if the underlying container has to allocate new data to make space for the value. Its probably a bit like 

```
vec.push_back(vec[0])
```

In practice there are no consequences since the memory *literally* was just occupied by the object and all objects have moved to a new location in memory but all the data is still there. However, of course, we are now accessing invalid, freed memory. So the proper solution would be to always use
```
// x.setMetaValue("something", x.getMetaValue("somethingelse")); // wrong
DataValue tmp = x.getMetaValue("somethingelse"); // right
x.setMetaValue("something", tmp); // right
```

PS: note that we dont use `auto` or `const DataValue&` but we actually have to copy the `DataValue` here

The issue is that when using a `std::map` this was safe to do but not any more with the flat_map -- see https://stackoverflow.com/questions/18788780/is-it-safe-to-push-back-an-element-from-the-same-vector and http://www.drdobbs.com/cpp/copying-container-elements-from-the-c-li/240155771

**Comment by hroest** [comment]
Note that in the code there are more examples of this pattern, but I guess not all of them are on the same object and not all of them result in re-allocation of memory:

```
$ grep -R setMetaValue src/openms | grep getMetaValue | wc
     29     131    4475
```

**Comment by jpfeuffer** [comment]
Interesting! Yes if flatmap is based on a vector on some kind of dynamically growing  structure, your explanation makes a lot of sense. Thanks for looking into it.

**Comment by hroest** [comment]
> Interesting! Yes if flatmap is based on a vector on some kind of dynamically growing structure, your explanation makes a lot of sense. Thanks for looking into it.

however, it seems that `std::vector` and `std::map` are specifically safe for this use-case. 

> In this case, I am tempted to just copy the DataValue in the specific cases where ASan detected the problem.

well, we could

- simply change all these cases `$ grep -R setMetaValue src/openms | grep getMetaValue | wc`
- have a non-ref version `DataValue getMetaValueCopy(String)` that we could use here for these cases, add to the documentation that you cannot do `x.setMetaValue("something", x.getMetaValue("somethingelse"));`
- create a copy in `setMetaValue` which would solve the problem but incur quite a bit of overhead
- maybe a smarter version of the above with some trickery : check for capacity and if re-allocation is likely then make the copy? e.g. `if (this->size() == this->capacity())` which still incurs overhead for all cases where we are not storing something from the same vector
- do none of the above and hope for the best, which for sure will crash -- actually I am kind of wondering what would happen if the underlying `std::vector` now starts to `move` elements to new memory location: then the reference to the old `DataValue` is not just point to a copy in freed memory, but that reference its also *not in the same state* as the original data. So things will just get worse and worse...

**Comment by timosachsenberg** [comment]
And return a copy by default in getMetaValue?

**Comment by hroest** [comment]
> And return a copy by default in getMetaValue?

that will lead to a lot of copying ... but it would also be safe

**Comment by timosachsenberg** [comment]
I would probably go with the copy as the object is pretty small and probably neglectable compared to lookup and conversions

**Comment by timosachsenberg** [comment]
wouldn't:
```
DataValue tmp = value;
auto it = index_to_value_.find(index);
if ( it != index_to_value.end()) 
{
  it->second = tmp; 
}
else
{
  index_to_value_.insert({index,  tmp});
}
```
be more efficient? About shrink_to_fit... could safe memory but might come with quite some overhead (moving of all elements).

**Comment by hroest** [comment]
> be more efficient? About shrink_to_fit... could safe memory but might come with quite some overhead (moving of all elements).

yes, it would be. I have just taken the current implementation and added a `tmp` object
