### ISSUE TITLE
TOPPView: "Identification view" may require extra prodding

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#3792]
The "Identification view" in TOPPView is not working properly any more for me. Running "Annotate with identification" on an mzML file still works and populates the "Identification view" window on the right, but clicking on a row in the "Identification view" table does nothing. (It used to show the corresponding MS2 spectrum or precursor ion.)

This is with the current "develop" version on Ubuntu 18.04.1 with Qt 5.9.5. The problem can be reproduced e.g. with the "BSA" example data.

Possibly related to #3424, where another TOPPView feature stopped working.

**Comment by hroest** [comment]
I have tried this on Ubuntu Linux 16.04 with Qt 5.5 and it seems to work fine for me. I did notice a minor bug #3793 though but apart from that it seems to work.

**Comment by hendrikweisser** [comment]
I tested an older OpenMS revision (b3c4e7 from 9 April) and with that it works. So luckily it seems to be a recent OpenMS bug, not (entirely) a problem with the Qt version.

**Comment by hendrikweisser** [comment]
I'll try to find the commit that caused the problem.

**Comment by hendrikweisser** [comment]
It appears that there's a workaround again: After the annotation, if you click on the "Scan view" and then back to the "Identification view", it works (with the strange caveat that Hannes found in #3793).

**Comment by hendrikweisser** [comment]
Git bisect result (@timosachsenberg):

```
9cf4fdcfa7d9624b54ca6ffb6af4746bbb464a49 is the first bad commit
commit 9cf4fdcfa7d9624b54ca6ffb6af4746bbb464a49
Author: Timo Sachsenberg <sachsenb@informatik.uni-tuebingen.de>
Date:   Fri May 18 12:31:25 2018 +0200

[FIX] don't create extra layer but directly annotate to observed spectrum

:040000 040000 bf0a999a955c165103eed29cb8a358fb06d29947 3d9fd88dbc0c0a95e8835498eb3a89a27fd71f6d M	src
```

Since that commit, TOPPView switches to the "Identification view" tab automatically after the "Annotate with identification" step, but (under Qt 5.9.5) clicking on a row in the table doesn't show the annotated spectrum any more.
