### ISSUE TITLE
Identification View: fragmentation indicator only appears on second navigation

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3793]
I tried out the Identification View and noticed something odd: when opening the BSA example for the first time, I got this view: 
![screenshot from 2018-10-12 09-45-00](https://user-images.githubusercontent.com/464014/46873013-a5ff5d00-ce03-11e8-8248-19efd0758947.png)

however when going one peptide up and then *back to the same peptide* I suddenly got a nice fragmentation indicator on the top right that was not there before. I tried this a few times and it seems when opening the PSM for the *first time* its always absent, but always present for subsequent views:

![screenshot from 2018-10-12 09-45-19](https://user-images.githubusercontent.com/464014/46873082-ca5b3980-ce03-11e8-80a8-aec7328069ca.png)

also it seems like the colors are different the second time around. System: Linux 16.04 with Qt 5.5

**Comment by hendrikweisser** [comment]
Two things I've noticed:
1. Initially a second layer will be created (see first screenshot), which is gone when the spectrum is revisited (second screenshot).
2. Clicking in a different cell in the same row in the "Identification view" table already has the update effect. It is not necessary to switch to a different row/spectrum.

**Comment by hendrikweisser** [comment]
Interestingly, this problem doesn't occur on my RNA test data. I believe the difference is that there, peak annotations are available directly in the idXML input file. In contrast, in the BSA example, a theoretical spectrum is first generated from the peptide sequence and matches between peaks and ions are detected. (The second layer that comes up initially shows the whole theoretical spectrum, when activated.)

**Comment by timosachsenberg** [comment]
I think if Fragment annotations are already present it works fine. If not they *should* be generated using the settings in the Id dialog preferences. Maybe just an updating issue...

**Comment by hendrikweisser** [comment]
@timosachsenberg:
> If not they should be generated using the settings in the Id dialog preferences.

Yes, that happens, there's just something weird about how they are displayed (initially).

**Comment by timosachsenberg** [comment]
I think a proper solution is to generate the fragment annotations once (e.g., when the id file is annotated).
Currently its done on the fly

**Comment by timosachsenberg** [comment]
@enetz do you think that creating the fragment annotations in addTheoreticalSpectrumLayer_ in TOPPViewIdentificationViewBehavior is a viable solution?

**Comment by hendrikweisser** [comment]
Looks like this got fixed in #3821.
