### ISSUE TITLE
Build Mac distribution with OpenMP enabled?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3798]
Does anything speak against it?

**Comment by timosachsenberg** [comment]
I did not find any negative reports so far... I am for enabling it on mac

**Comment by jpfeuffer** [comment]
Ok on Linux I found why it was not picking OpenMP up (#3824 ).
Concerning macOS the Segfaults seem random and only seem to occur shortly before exiting the program. I think it might not even be just in OpenMP-enabled tests (like ProteinInference (here)[https://abibuilder.informatik.uni-tuebingen.de/jenkins/view/OpenMS/job/openms_pr_ci/compiler=appleclang-9.0.0,os_label=highsierra/lastCompletedBuild/testReport/] )

**Comment by jpfeuffer** [comment]
Unless someone has a good idea, I will disable it again. Maybe AppleClang 9.2 is just not ready for that yet.
One could of course set up gcc there..

**Comment by jpfeuffer** [comment]
I am seeing exactly the same bugs as here:
https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=29031&sid=38a1699621bc1edbd62cb9c72d929b71&start=15

Seems to be fixable, but not easily. They are semirandom failures, only on darwin. They could have to something with OpenMP shutting down before our last locks are used (e.g. in the destructor of LogStream).

**Comment by jpfeuffer** [comment]
Actually, if I remove the omp critical sections in sync and the d'tor of LogStream, the error in a lot of tests goes away.

**Comment by hroest** [comment]
ok, but does this cause any problems? 

https://github.com/OpenMS/OpenMS/blob/8345b7be5f8875c2346dbcd4bc3345f77695988f/src/openms/source/CONCEPT/LogStream.cpp#L81-L94

I mean the LogStream is *generally* a global constant that gets destroyed at the end of the execution? In that case we cannot be in a parallel section anymore anyhow, right?

**Comment by jpfeuffer** [comment]
Yes right, occasionally it also segfaulted in sync then, when it tried to acquire the lock.
Seems like the omp library is sometimes closed before some of the destructors are called.
A workaround that I found was to override the "<<" operator for our LogStream class and put it into a critical section and instead remove the other ones.
Since this is the only thing what all our classes call, this works well.

**Comment by hroest** [comment]
>  In that case we cannot be in a parallel section anymore anyhow, right?

what I mean here is also that at this stage of the program execution, there should be no more threads, right?

**Comment by jpfeuffer** [comment]
Enabled a while ago and fixed in #3829
