### ISSUE TITLE
MapAlignerPoseClustering: -use_identifications considered harmful [380]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#380]
Submitted by johannes_junker on 2011-12-15 22:17:49

When -use_identifications ("Never link features that are annotated with different peptides (only the best hit per peptide identification is taken into account)") is set to "true", an alignment of two small featureXMLs can take 30 min instead of 5 sec when it is set to "false". There is no output saying what's going on... it just takes ages.

The results, however, are almost identical (differences only in the decimals of RT values).

Does this parameter even make sense for a map aligner that only tries to find an affine transformation?
---

Commented by hendrikweisser on 2012-01-16 18:32:49:
You're probably right that the "use_identifications" parameter doesn't help a lot in this algorithm. It comes from the StablePairFinder, which is also used in FeatureGroupingAlgorithmUnlabeled (TOPP tool: FeatureLinkerUnlabeled), where it _does_ make sense. (Still, it's "false" by default.)

In the alignment algorithm, pair finding is done in the refinement step, to restrict the set of data points (to which the RT transformation is fit) to those that match nicely. In theory, it could thus make sense to also test the ID, because features with different annotations don't "match nicely".

It would be interesting to see whether such a huge time difference also occurs if you apply FeatureLinkerUnlabeled (with and without "use_identifications") to the results of the alignment. If yes: optimize the checking of IDs in StablePairFinder; if no: that's strange and should be investigated further.
Also, is there still a significant delay if the feature maps don't contain any IDs? (That would be bad.)

By the way, since OpenMS 1.8, the "pose clustering" algorithm can also be used with non-linear transformations.

**Comment by timosachsenberg** [comment]
@hannesveit can this be closed?

**Comment by hannesveit** [comment]
I haven't kept track of what has been done here, but it seems as if the problem has disappeared. Just tested it with two ID-mapped featureXMLs (fulls runs) with and without -algorithm:pairfinder:use_identifications. The runtime was basically identical (~33 secs).

So yes, I think this can be closed.

**Comment by timosachsenberg** [comment]
cool thanks for checking!
