### ISSUE TITLE
downgrading OpenMS in Knime

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3810]
Please allow downgrading of OpenMS without prior de-installation [1]. Or at least guide the user to the uninstall functionality.

[1] Help -> About Knime -> Installation Details -> Uninstall

![img_3447](https://user-images.githubusercontent.com/6149805/47216417-2e9e7000-d3a5-11e8-9191-8753dbf72610.jpeg)

**Comment by jpfeuffer** [comment]
It's an eclipse feature. We can't do anything about that.
Where should we put such information?

**Comment by lars20070** [comment]
The Details message cannot be extended with for example
```
Please first uninstall the current version in
Help -> About Knime -> Installation Details -> Uninstall
```
?

**Comment by jpfeuffer** [comment]
Nope, also Eclipse. We are working on a plugin structure that allows multiple versions. But downgrade will never be possible. We will put it in the FAQ of the KNIME tutorial but that is all we can do.

**Comment by lars20070** [comment]
:+1: Yep, fine with me. Thought we could simply extend the dialog.
