### ISSUE TITLE
Automatic SE detection in PeptideIndexer does not work

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3811]
with
```
ERROR FalseDiscoveryRate   0:42       Failing process stdout: [FalseDiscoveryRate took 0.61 s (wall), 0.59 s (CPU), 0.01 s (system), 0.58 s (user).]
ERROR FalseDiscoveryRate   0:42       Failing process stderr: [/Users/builder/jenkins/ws/openms_nightly_packaging/4a4a5dc9/source/src/openms/source/ANALYSIS/ID/FalseDiscoveryRate.cpp(154): Meta value 'target_decoy' does not exists, reindex the idXML file with 'PeptideIndexer' first (run-id='XTandem_2018-10-19T13:54:52, rank=1 of 1)!, /Users/builder/jenkins/ws/openms_nightly_packaging/4a4a5dc9/source/src/topp/FalseDiscoveryRate.cpp(191): FalseDiscoveryRate failed due to missing information (see above).]
ERROR FalseDiscoveryRate   0:42       Execute failed: Failed to execute node FalseDiscoveryRate
```

https://www.dropbox.com/s/2gejuftgvss4p07/20181018_Knime_SimplePeptideID_Test.zip?dl=1

**Comment by jpfeuffer** [comment]
Hmm.. Which build exactly?

**Comment by timosachsenberg** [comment]
Meta value 'target_decoy' does not exists

**Comment by lars20070** [comment]
@jpfeuffer Last nightly build 22/08/18.

**Comment by lars20070** [comment]
@timosachsenberg There are `target_decoy` entries in the `idXML`.
Works fine when reverting to 2.3. Works fine when replacing XTandem by MS-GF+ in nightly.

**Comment by jpfeuffer** [comment]
... rejected by enzyme filter: 1418
Unmatched peptide: ETLSFPDQFD
Unmatched peptide: SNDKSFD
Unmatched peptide: EGRGCSDVD
Unmatched peptide: RPTDLDVDTLASLLSSNGCPD
Unmatched peptide: EHNFFHLD
Unmatched peptide: EAADYD
Unmatched peptide: .(Gln->pyro-Glu)QTLAISTDTLVAGNHFLPDID
Unmatched peptide: SQAGDVEGPSTGD
Unmatched peptide: SQSAGTASDELSVYPD
Unmatched peptide: SLAINPKD
Unmatched peptide: SLTLEPD
Unmatched peptide: EDEKGDDVDD
Unmatched peptide: TQPCACCGMPADD
Unmatched peptide: PDEEMDD
Unmatched peptide: ...
--------------------------------

**Comment by jpfeuffer** [comment]
That's why I was asking for PeptideIndexer output. Obviously not all are matched. Therefore not all will have a TD annotation.

**Comment by jpfeuffer** [comment]
Set specificity in Indexer to semi.

**Comment by lars20070** [comment]
In 2.3 they are deleted i.e. filtered out. How in the current nightlies? Should work by default.

**Comment by lars20070** [comment]
semi = false in XTandem

**Comment by jpfeuffer** [comment]
Yes but as always, it has specific cleavage rules.

**Comment by jpfeuffer** [comment]
Automatic detection would be in there, if the nightlies would work.

**Comment by lars20070** [comment]
But how do I run a full tryptic search? i.e. filter the semi out?

**Comment by jpfeuffer** [comment]
Full tryptic is not possible with XTandem currently . You have to filter manually afterwards.
