### ISSUE TITLE
XTandemAdapter: m/z unit allows empty setting

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3813]
The precursor/fragment tolerance m/z unit is either `Da` or `ppm` [1]. But the setting also allows the setting `empty`. IMO, this setting can be removed.

Several users picked this setting by accident which did lead to crashes.

[1] https://github.com/OpenMS/OpenMS/blob/develop/src/topp/XTandemAdapter.cpp#L149

**Comment by hroest** [comment]
> Can you elaborate? How can it be empty?

I agree, the only allowed settings are "ppm" or "Da"  - see line 151 here:
https://github.com/OpenMS/OpenMS/blob/c71c0d52b5858dc61a0375e25166aa12999d4e4e/src/topp/XTandemAdapter.cpp#L149-L153

**Comment by lars20070** [comment]
<img width="525" alt="screenshot 2018-12-20 at 09 57 15" src="https://user-images.githubusercontent.com/6149805/50274654-0df2a500-043e-11e9-8da6-6606bed5c80d.png">
<img width="530" alt="screenshot 2018-12-20 at 09 58 19" src="https://user-images.githubusercontent.com/6149805/50274659-0fbc6880-043e-11e9-8923-c8a8dc0548f2.png">
It's an UI issue (see screenshots) that not only affects `XTandemAdapter`.

**Comment by jpfeuffer** [comment]
I agree that in a GUI environment, not specifying a parameter that has a default does not make much sense since it does not save any time.
But we still have some parameters that do have a default that is not in the restrictions list and unspecified has a different meaning than default (see the output_type parameters in our converter).

**Comment by lars20070** [comment]
> But we still have some parameters that do have a default that is not in the restrictions list and unspecified has a different meaning than default (see the output_type parameters in our converter).

Do we want to remove `unspecified` in the long run? If yes, let's change the title of the issue.
