### ISSUE TITLE
GUI freezes under Windows

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3814]
Repeatedly, we could not change param settings of tools under Windows. The param `value` could not be selected. Other elements fine. Only restarting Knime helped.

<img width="522" alt="screenshot 2018-10-19 at 15 55 12" src="https://user-images.githubusercontent.com/6149805/47222599-70381680-d3b7-11e8-8994-2511e6f9eb19.png">

**Comment by jpfeuffer** [comment]
I would need a video for this.
