### ISSUE TITLE
SpectrumLookup::extractScanNumber wiff-format

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#3825]
```
[Term]
id: MS:1000770
name: WIFF nativeID format
def: "Native format defined by sample=xsd:nonNegativeInteger period=xsd:nonNegativeInteger cycle=xsd:nonNegativeInteger experiment=xsd:nonNegativeInteger." [PSI:MS]
is_a: MS:1000767 ! native spectrum identifier format
```

Right now:
```
    // "experiment=NUMBER"
    else if (native_id_type_accession == "MS:1000770")
    {
      regexp = std::string("experiment=(?<GROUP>\\d+)");
    }
```

It seems that "cycle" would be the right expression (see Fig)

![spectrumlookup_ms1000770_wiff](https://user-images.githubusercontent.com/15729190/47488020-dc959880-d843-11e8-8449-abe3ffd010f7.png)

Affected test:
SpectrumLookup
SiriusAdapter
OpenSWATH (?)

**Comment by timosachsenberg** [comment]
@hroest

**Comment by hroest** [comment]
what is it that you want to extract? why not simply use the scan index? Neither the `cycle` nor `experiment` are unique numbers in my data. My data it looks like this:

```
<spectrum index="430" id="sample=1 period=1 cycle=12 experiment=14" defaultArrayLength="123">
```

so I guess a unique number would be a combination of `cycle` and `experiment` as the experiment counts up to `N` and then rolls over, a new cycle starts and experiment gets set to 1 again. Unless each cycle has the same number of experiments, there is no way to compute a unique number from this. 

Why not use the scan index in each mzML file?

**Comment by hendrikweisser** [comment]
> Maybe @hendrikweisser can explain why this design was chosen in SpectrumLookup and what the use-case is to look up spectra by scan number rather than by index?

It makes a difference once you deal with spectra that may be pre-filtered. The index just applies to the current set of spectra, while the scan number (as part of the native ID) should stay constant even if you filter. (Merging is more problematic and not really considered.)

**Comment by hroest** [comment]
> It makes a difference once you deal with spectra that may be pre-filtered. The index just applies to the current set of spectra, while the scan number (as part of the native ID) should stay constant even if you filter. (Merging is more problematic and not really considered.)

ok, that makes sense. However in this case a single number is not sufficient to describe the spectra and at least 2 numbers are required for SCIEX data. There are 2 ways out of this

- disable query by scan number
- allow query by a string or multiple ints

**Comment by oliveralka** [comment]
Ok, I guess for SCIEX there are two different scenarios depending on the type of data (DDA, DIA).

DDA: In one specific file cycle is increased as the _nativeID index_.
DIA: From your example, it seems that cycle and experiment are the important values. 

What would be the best option for the: 
`Int SpectrumLookup::extractScanNumber(const String& native_id, const String& native_id_type_accession)`

This particular function is only used in classes related to the SiriusAdapter. I am not sure if someone else need it? For the SiriusAdapter it does not really matter I can use the whole nativeID as String, without extracting the integer value.

**Comment by hroest** [comment]
> DDA: In one specific file cycle is increased as the _nativeID index_.

did you look at DDA data with MS2 in them? It looks like all your data is MS1 only?

Do you need a query by scan number? I think for now we could just disable it and throw an exception if someone tries to access scans by scan number -- I guess that would mean some functionality of the SpectrumIndexer would break @hendrikweisser what would that mean for the functionality of OpenMS with wiff files

another "hack" would be to simply use a large integer and compute a new scan number `cycle * N + experiment` which is unique if our number "N" is larger than the number of experiments in a cycle. Setting N = 1000 should be sufficient for probably all (including DIA experiments)

**Comment by oliveralka** [comment]
@hroest 
I like the idea with the large int.

It is for the SiriusAdapter output to have a unique identifier for a spectrum - right know the index and the ScanNumber (nativeID value) is reported - since mz and rt are not given (which will be changed with SIRIUS 4.0.4 Version).

**Comment by oliveralka** [comment]
I made the changes as discussed above. 
In generell it may be better to use the nativeID as String in the future - to be on the save side.

**Comment by hendrikweisser** [comment]
> I made the changes as discussed above.

@oliveralka: Can this issue be closed?
