### ISSUE TITLE
VS2017, coinor, debug

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#3833]
It seems that the debug libraries of coinor have the same name as the release and are overwritten in the build process (contrib). 

```
vcvarsx86_amd64.bat
cmake -DBUILD_TYPE=COINOR -DNUMBER_OF_JOBS=4 -G "Visual Studio 15 2017 Win64" "c:\OpenMS\contrib"
```
> Build:
![coin_1](https://user-images.githubusercontent.com/15729190/47798790-45d84880-dd29-11e8-89f5-9ae6f9735538.png)

> lib
![coin_2](https://user-images.githubusercontent.com/15729190/47798820-55579180-dd29-11e8-873b-087877837ae6.PNG)

`\OpenMS\contrib_build_debug\src\CoinMP-1.8.3\CoinMP\MSVisualStudio\v15\x64`

> 1) release
![coin_3_release](https://user-images.githubusercontent.com/15729190/47798911-7a4c0480-dd29-11e8-8d73-3ac1b43decae.png)

> debug
![coin_4_debug](https://user-images.githubusercontent.com/15729190/47798928-820ba900-dd29-11e8-91b5-86917ea721c9.png)

**Comment by jpfeuffer** [comment]
The solutions need to be adapted so that they add a "d" suffix to the debug versions.
Then they need to be reuploaded.

**Comment by oliveralka** [comment]
see: https://github.com/OpenMS/contrib/pull/83
