### ISSUE TITLE
Simpson's Rule in PeakIntegrator() reports negative areas for strictly positive input

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3845]
For some chromatograms with positive peak intensities, the Simpson's rule reports negative areas.
See code example below.
```
 MSChromatogram c;
 c.push_back(ChromatogramPeak(2270.93, 410430.0));
 c.push_back(ChromatogramPeak(2272.86, 166125.0));
 c.push_back(ChromatogramPeak(2273.16, 896669.0));
    
 PeakIntegrator pi;
 Param par = pi.getDefaults();
 par.setValue("integration_type","simpson"); 
 pi.setParameters(par);

 PeakIntegrator::PeakArea pa = pi.integratePeak(c, 2270.93, 2273.16);
 double area = pa.area;
```

**Comment by timosachsenberg** [comment]
Can you add this to a PR against PeakIntegrator_test ?

**Comment by timosachsenberg** [comment]
Doesn't the formula on wikipedia work in these cases?
![image](https://user-images.githubusercontent.com/5803621/48473163-36143600-e7f8-11e8-93d0-86ef2b21d236.png)

**Comment by timosachsenberg** [comment]
E.g., in your example the second and third point are super close in x value but quite different in y value. Fitting the parabola through all three points will overshoot, hence the negative values.
I think if the two dx are too different (in this case the left interval is about 8 times as large as the right one!) as Pasquale also pointed out, a fallback to trapezoid rule would be better.

**Comment by lars20070** [comment]
Ok. Fitting anything to very low intensity chromatograms makes probably no sense.

![img_0142](https://user-images.githubusercontent.com/6149805/48475505-437fef00-e7fd-11e8-9955-d49c3eb7ab2c.jpeg)

**Comment by lars20070** [comment]
Close issue?

**Comment by timosachsenberg** [comment]
hmm I don't know. we could still discuss if the simpson code needs some special treatment for these cases.

**Comment by lars20070** [comment]
I wish there was an automatic fall back.
bad fit => simpson --> trapezoid

**Comment by hroest** [comment]
I am not sure about an automatic fallback, this may be surprising to people. Couldnt this lead to some very degenerate cases where one trace gets integrated with Simpsons rule and another trace with trapezoid rule, leading to a scenario where the intensities are suddenly reversed and the results become inconsistent?

**Comment by timosachsenberg** [comment]
If we strive for consistency this might be indeed the case. Hmm tough call. Maybe just document it and prefer trapezoid in our tools?

**Comment by lars20070** [comment]
I will look into this a bit further (error bounds, other options etc.).
Guess for now trapezoid is save and good enough.
