### ISSUE TITLE
NULL accession in mzTab output of XTandem search workflow

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#3853]
Dear all, 
in a simple peptide ID workflow (tandem or msgf) -> PeptideIndexer ->FDR->IDFilter the mzTAB does not contain accession numbers; all entries in that column state "NULL". This is the case for various databases and tandem as well as msgf+. Any help is highly appreciated. Example output is attached. 

Maybe I am missing some parameters in PeptideIndexer or IDFilter?

Thanks, Oliver
[ColiT_A1.tsv.zip](https://github.com/OpenMS/OpenMS/files/2593163/ColiT_A1.tsv.zip)

**Comment by enetz** [comment]
I used the same pipeline with X!Tandem just recently and it works fine. Your file also lacks all the pre, post, start and end values that PeptideIndexer should provide, so I think the problem lies there. Can you post your PeptideIndexer parameters? And check whether you used the same database for the search and PeptideIndexer.

**Comment by oliverschilling** [comment]
Thanks; that will be helpful. I am using the same db for PI and tandem. I have attached screenshots of the workflow, PI settings, and sequence file. Note that setting "write sequences = true" leads to the error message "Error: Unexpected internal error ( ProteinHits do not contain a protein sequence. Cannot compute coverage! Use PeptideIndexer to annotate proteins with sequence information.)"
I have also attached zipped files of the mzml, the toppas workflow, and the actual sequence file.
Thanks again for any help!

[EColi_uniprot_Nov_2014-plus-CON_plus-shuffled_and_revesred_decoy.zip](https://github.com/OpenMS/OpenMS/files/2598307/EColi_uniprot_Nov_2014-plus-CON_plus-shuffled_and_revesred_decoy.zip)
[tandem-T.toppas.zip](https://github.com/OpenMS/OpenMS/files/2598308/tandem-T.toppas.zip)

![database](https://user-images.githubusercontent.com/8565908/48755017-27b09900-ec94-11e8-81cd-84e1313788c9.png)
![pi_settings](https://user-images.githubusercontent.com/8565908/48755018-27b09900-ec94-11e8-851d-24b0a2e6a3ed.png)
![workflow](https://user-images.githubusercontent.com/8565908/48755019-27b09900-ec94-11e8-90c4-c1075fa6b60a.png)

**Comment by enetz** [comment]
You use OpenMS 2.3 right? The parameters `filter_aaa_proteins` and `full_tolerant_search` don't exist anymore in OpenMS 2.4.
If `allow_unmatched` is set to false, it should terminate with an error when it can't match a peptide to any protein, so the matching itself does not seem to be the problem.
Maybe you can check out the idXML coming out of the PI to see whether the protein annotations are correct there.
Also what happens when you run it with `write_protein_description` and `keep_unreferenced_proteins` set to false?

**Comment by oliverschilling** [comment]
Thanks, that was helpful. I lose the accession numbers etc in the IDFilter step. I can fix this behavior by running PeptideIndexer after IDFilter, so there is a workaround. For your information, I have added a screenshot of the IDFilter settings. Let us wait and see how this behaves in any upcoming release. 
<img width="1951" alt="id-filter" src="https://user-images.githubusercontent.com/8565908/48776736-e38fb980-ecd0-11e8-9f00-ee30d6731717.png">

**Comment by enetz** [comment]
I had a similar problem recently, where my IDs were all completely removed by IDFilter by filtering with both PSM and Protein FDR thresholds. If you set the protein FDR threshold to 1.0, it should work on the PSM level.
If you run IDFilter before PeptideIndexer, you don't have target-decoy info and can't do FDR calculation right? I guess the IDFilter then just lets everything through?
Do you compute Protein FDR or peptide FDR with FalseDiscoveryRate? I am not sure what it does, if you set both to true or how it stores the Protein FDR. IDFilter may have filtered out all proteins for you for some reason. Try the previous pipeline with only using PSM/peptide FDR in the FDR tool and IDFilter.

**Comment by oliverschilling** [comment]
Done as suggested ("Try the previous pipeline with only using PSM/peptide FDR in the FDR tool and IDFilter.") - yes, that fixed it. Thanks again!

**Comment by lars20070** [comment]
Standard `XTandemAdapter`, `PeptideIndexer`, `FalseDiscoveryRate`, `MzTabExporter` workflow works for me. See last workflow in [1] and [2,3].

[1] https://github.com/OpenMS/OpenMS/wiki/Workflow-Collection#thermo-q-exactive

[2] Freiburg server D:\data\OpenMSworkflows\peptide identification\XTandem_OpenMS23_20181126.toppas

[3] Freiburg server D:\data\sgbm\2018\ID-example\Lars

**Comment by oliverschilling** [comment]
Meci

siehe https://github.com/OpenMS/OpenMS/issues/3853 <https://github.com/OpenMS/OpenMS/issues/3853>

das Problem war, dass auch Protein FDR berechnet wurde…aus einem unbekannten Grund führt das zu dem berichteten Problem.

**Comment by lars20070** [comment]
In `FalseDiscoveryRate`, the parameters `PSM` and `protein` switch the FDR calculation on/off, and the parameters `FDR:PSM` and `FDR:protein` set the FDR cutoff.

@enetz @oliverschilling Is there a bug or can we close the issue?

**Comment by lars20070** [comment]
`NULL` accessions in `mzTab `are resolved.

Simultaneous PSM/protein FDR are further discussed in #3869.
