### ISSUE TITLE
Erroneous GitHub tag

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#3854]
On the top of the main GitHub repository page, https://github.com/OpenMS/OpenMS, there's a list of tags associated with OpenMS. One of them is "clause-bsd", for which OpenMS is the only result. It should probably be "3-clause-bsd" or "three-clause-bsd" (if tags have to start with a letter). This should be fixed, but I couldn't see how to do it myself.

**Comment by timosachsenberg** [comment]
done. thanks!
