### ISSUE TITLE
pqp MIMEType missing

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#3855]
It seems that the TargetedFileConverter is missing the .pqp MIMEType:

`MIMEType not registered for extension '.pqp'. Proceeding, but this might lead to problems connecting to the affected FileStoreURIPort.`

**Comment by hroest** [comment]
what do we need to do here? Can we introduce a new type?

**Comment by oliveralka** [comment]
@hroest I think so.
@jpfeuffer Do we have to edit additional files or are the following enough?
```
cmake/knime/mime.types
cmake/knime/mimetypes.xml
```

**Comment by jpfeuffer** [comment]
That should be enough.
