### ISSUE TITLE
Bioconda thirdparty packages

### ISSUE THREAD

**Issue by Leon-Bichmann** [OpenMS/OpenMS#3856]
In order to make OpenMS including its thirdparty tool available via bioconda and to simplify containerization it would make sense to release bioconda packages for all THIRDPARTY tools.

Available right now:
- Percolator
- Comet
- MS-GF+
- Fido
- XTandem
- Crux

Missing:
- SpectraST
- Sirius
- more?

**Comment by bernt-matthias** [comment]
Exactly. Just started my own lsit here: https://github.com/bioconda/bioconda-recipes/issues/18953

In particular it would be nice to know the versions supported by the OpenMS adapters.

**Comment by jpfeuffer** [comment]
There is an openms-thirdparty package now and the versions seem all to work. Thanks to @bernt-matthias also.
But for the next release we should update thirdparties and accordingly double check the versions in the bioconda recipe.

**Comment by jpfeuffer** [comment]
@oliveralka Sirius could need an update on bioconda. Maybe you could ask the developers.
I think there is also a newer comet version. I could try to update that.

For the rest, I updated our nightly conda recipe to the newest versions on conda (which mostly should be the newest available).

**Comment by bernt-matthias** [comment]
ThermoRawFileParser also just had an update (also in bioconda) that is important (it removes the BOM from the produced mzML files https://github.com/compomics/ThermoRawFileParser/issues/109)

**Comment by jpfeuffer** [comment]
Yup. Was waiting for another issue as well ;) . I could not see it on the web search yet but it is on my TODO list to update in oms-thirdparty

**Comment by jpfeuffer** [comment]
For reference: https://github.com/jpfeuffer/bioconda-recipes/blob/nightly/recipes/openms-meta/meta.yaml

**Comment by bernt-matthias** [comment]
Excellent. Is there already a plan for a release. Maybe I can start to work on the Galaxy wrappers some weeks before the release?
