### ISSUE TITLE
OpenSwath Issue

### ISSUE THREAD

**Issue by srithegreat** [OpenMS/OpenMS#3857]
I am running openswathworkflow with osw output and get the following error:
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type IllegalArgument occured in line 585, function void OpenMS::OpenSwathOSWWriter::writeLines(const std::vector<OpenMS::String>&) of /opt/OpenMS/src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathOSWWriter.h
error message: no such column: nan
---------------------------------------------------
Aborted (core dumped)

Version 2.4.0-HEAD-2018-11-19 of OpenSwathWorkflow is available at www.OpenMS.de

**Comment by grosenberger** [comment]
Can you please provide more details, e.g. the used parameters and data type?

**Comment by grosenberger** [comment]
I recently encountered a similar issue, but I did not yet have time to fully investigate it. This branch (https://github.com/grosenberger/OpenMS/tree/fix/sangle_nan) resolved the issue, does that work for you too?

**Comment by grosenberger** [comment]
This issue has been fixed here: https://github.com/OpenMS/OpenMS/pull/3864
