### ISSUE TITLE
RANSAC fails

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3858]
```
250               r = Math::RANSAC<Math::RansacModelQuadratic>().ransac(pairs, *ransac_params_);
(gdb) print pairs
$7 = std::vector of length 15, capacity 16 = 
{{first = 404.20341232807095, second = -1.0128523670398526},
{first = 379.71510077282096, second = -0.67688332762515591}, 
{first = 487.73253447162097, second = -0.66884951258731495}, 
{first = 461.74765303542097, second = -0.33671384351978711}, 
{first = 379.71510077282096, second = 0.046443720607350171}, 
{first = 461.74765303542097, second = -0.20453091714994964},
{first = 554.26060201207099, second = -0.40781449759225408}, 
{first = 379.71510077282096, second = 0.76977076883985618}, 
{first = 421.75835453542095, second = -0.70631628928191581}, 
{first = 554.26060201207099, second = -0.077454612165315656}, 
{first = 435.91022882090425, second = -0.8665699043027143}, 
{first = 464.25036251947097, second = -0.32072441079355074}, 
{first = 464.25036251947097, second = -0.71513545224899844}, 
{first = 464.25036251947097, second = -0.05778371791840084}, 
{first = 501.79513472682095, second = -0.48499752611439595}}

(gdb) print *ransac_params_
$8 = {n = 3, k = 70, t = 10, d = 30, relative_d = true, rng = 0x0}
```

fails with an exception

**Comment by timosachsenberg** [comment]
Hi. I regularly get some exceptions ins RANSAC (maybe because I have filtered data and produce some kind of corner case). See above the data that triggered the exception. Maybe there is something obvious wrong and could be checked/filtered before.

**Comment by grosenberger** [comment]
I believe that ``Math::RansacModelQuadratic`` was contributed by @cbielow, in the OpenSWATH modules we only use the base model. Does the exception also appear with the other RANSAC variants?

**Comment by timosachsenberg** [comment]
looking at the data we see that some x values are duplicated. Don't know how this happens in internal calibration but I guess the code should be safe against that. @cbielow any ideas?

**Comment by cbielow** [comment]
using this data and parameters, RansacModelQuadratic runs through on my machines (VS2015 and GCC 7.1).
Any further hints where the problem might be?
