### ISSUE TITLE
CometAdapter fixed modifications not properly working

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#3861]
specifically, _fixed modifications_ seem to be **ignored**:
```
Warning - invalid parameter found: add_X_unspecified/unknown.  Parameter will be ignored.
```
(Comet version "2016.01 rev. 3")

**Comment by mwalzer** [comment]
`CometAdapter -in BSA.mzML -database proteins.fasta -out BSA.idXML -variable_modifications 'Carbamidomethyl (C)' 'Oxidation (M)' -fixed_modifications 'Acetyl (N-term)'`

**Comment by jpfeuffer** [comment]
Weird.. it doesn't find our own modifications? Which OpenMS commit/tag?

**Comment by mwalzer** [comment]
I think it happens during the transition from TOPP parameters to the comet param.txt
