### ISSUE TITLE
Add pyOpenMS to jenkins deploy matrix 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3866]
src/pyOpenMS/dist-scripts/create-manylinux.sh

**Comment by jpfeuffer** [comment]
It is added to our automated release pipeline now. For Linux, based on the dist script and the manylinux docker image. Needs some testing still and I have to check how to upload the wheels to pip in the end.
@oliveralka wanted to look at deployment on macOS

**Comment by hroest** [comment]
>  how to upload the wheels to pip in the end.

you can use `twine` but I need to provide you with access
