### ISSUE TITLE
FalseDiscoveryRate, Peptide and Protein FDR at the same time removes all hits

### ISSUE THREAD

**Issue by enetz** [OpenMS/OpenMS#3869]
This issue was discovered in #3853.
It affects both OpenMS 2.3 with FDR and IDFilter for filtering, and OpenMS 2.4 with FDRs new filter settings.

Setting it to compute PSM and protein level FDR at the same time and then applying cut-offs to both of them at the same time, either using FDRs filter or the IDFilter tool, results in a idXML without any hits.
This happens even with high cut-offs of 20% on a data set with hundreds of hits below 5% PSM FDR.

Is `FalseDiscoveryRate` not meant to compute both at once and is this the expected behaviour?
In OpenMS 2.3 the parameters were called `proteins_only` and `peptides_only`, so it might be expected, that they don't work together, although it is not explained very well in the param description. In OpenMS 2.4 they are just called `protein` and `PSM` and the description does not mention that they are mutually exclusive either.

**Comment by enetz** [comment]
Here my stdout after running OpenMS 2.4 FDR with filtering with 10% PSM and 20% protein FDR cut-off after an X!Tandem search:

```
FDR control: Filtering proteins...
FDR control: Filtering PSMs...
Before filtering:
1 protein identification(s) with 23865 protein hit(s),
17418 peptide identification(s) with 20978 pep_ids hit(s).
After filtering:
1 protein identification(s) with 0 protein hit(s),
0 peptide identification(s) with 0 pep_ids hit(s).
Writing filtered output...
FalseDiscoveryRate took 3.97 s (wall), 3.97 s (CPU), 0.04 s (system), 3.93 s (user).
```

**Comment by lars20070** [comment]
I have not checked the code, but would also expect this behavior. In the second (protein) FDR filtering step, there is no longer a target-decoy distribution and you loose everything.

Should the API be changed to PSM *or* protein FDR filtering, and not allow both?

**Comment by jpfeuffer** [comment]
What is the status here? The code is very simple and I can't find anything wrong with it.
Does anyone have a small example?

**Comment by lars20070** [comment]
Here the original post with example. https://github.com/OpenMS/OpenMS/issues/3853

**Comment by jpfeuffer** [comment]
But there wasn't any protein inference run, right? How can you filter proteins then (except for with "extrapolation" approaches like Mayu).

**Comment by jpfeuffer** [comment]
they  will all have a score of 0. So FDR will be around 0.5 depending on your T/D ratio.

**Comment by jpfeuffer** [comment]
I think I see the confusion now. If you want to filter proteins based on the remaining peptides after PSM-level FDR filtering, the only option is IDFilter on PSM-level with "removeUnreferencedProteins".
If you want to filter proteins by protein-level FDR, you need protein scores first from any kind of protein inference.

**Comment by lars20070** [comment]
As far as I can see, no bug. But maybe warnings or user interface changes would be helpful.

**Comment by jpfeuffer** [comment]
I see. Any suggestions? I will definitely add a check if inference was performed before protein level FDR filtering.

**Comment by lars20070** [comment]
:+1: Protein FDR filtering should be disabled if no inference has been performed. Good idea.
