### ISSUE TITLE
FalseDiscoveryRate paramter 'flags' are no flags

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#3885]
Should be `registerFlag_`? https://github.com/OpenMS/OpenMS/blob/e5c775cb55d2b95a8f037accaf9c82c3b39e92f0/src/topp/FalseDiscoveryRate.cpp#L114

This 'false' flag (needs a string representation of a bool) causes trouble with the OpenMS integration in var. frameworks (like CWL or galaxy). How is this handled in the knime integration? Are there other instances of parameters like this? @jpfeuffer can you help here?

**Comment by mwalzer** [comment]
If you compare it to e.g. FileInfo's `-m` parameter, both result in similar ctd entries, making it quite hard to read from that what is supposed to be delivered to the commandline.
FileInfo: `<ITEM name="m" value="false" type="string" description="Show meta information about the whole experiment" required="false" advanced="false" restrictions="true,false" />`
FalseDiscoveryRate: `<ITEM name="PSM" value="true" type="string" description="Perform FDR calculation on PSM level" required="false" advanced="false" restrictions="true,false" />`

**Comment by timosachsenberg** [comment]
I think we generally move a bit away from flags to the bool parameters. We had some troubles with flags in the past because they were never distinguished from true false string parameters.

**Comment by timosachsenberg** [comment]
I would need to look it up but maybe -option1 and -option1 "true" are  treated the same way for backward compatibility
