### ISSUE TITLE
TargetedFileConverter error with exported Skyline file

### ISSUE THREAD

**Issue by sjr24** [OpenMS/OpenMS#3887]
Greetings,
I am trying to create a spectral library for OpenSWATH from Skyline data.  I exported the transition data using the OpenSwath.skyr file for appropriate columns.  I get the following error when I try to convert the .tsv file to .TraML.

TargetedFileConverter -in openswath.irt.tsv -out openswath.irt.TraML 
Error: Unexpected internal error (I determined that your your csv/tsv file has the delimiter 't'.
But the parsed header does not have the required field "transition_name". Please check your input file.)

How can I get the software to write the transition_name column?

Thanks,
Shawn

**Comment by grosenberger** [comment]
Hi Shawn, which version of OpenMS are you using? Improved transition list support is only available in OpenMS >=2.4 and OpenMS/develop.

**Comment by sjr24** [comment]
George,
Thank you for the response.  I am using OpenMS 2.3.  I’ll update and give it a try.

Thanks,
Shawn

**Comment by hroest** [comment]
> I’m not sure if this is a TargetedFileConverter bug that can be fixed or a Skyline issue.

It looks like an incompatibility between the two

**Comment by hroest** [comment]
this should be fixed in upcoming versions of OpenMS (or the nightly build) through #3964

**Comment by Clovernana** [comment]
Bother you to ask how to use openswath.skyr.Thanks.

**Comment by sjr24** [comment]
Clover,

Download the openswath.skyr

Open a blank document in Skyline.

File -> Export -> Report -> Edit list -> Import

Then navigate to the saved openswath.skyr file and hit open.

Now when you go to File -> Export -> Report -> Edit list -> Import, you will see OpenSwath as a report type option.  It should export all the columns needed to make a library.

Hope that helps.

Thanks,
Shawn

**Comment by sjr24** [comment]
Clover,

For the exported transition list to work with the file converter you need to change the UniMod identifiers.  Open the transition list .csv file in Excel -> use the ‘find and replace’ function -> find ‘UniMod’ and replace it with ‘unimod’.  You will have to check the file, I cannot remember if skyline exports as UniMod or unimod, but whichever is in the file it needs to be changed to the other.  Then save the document, and it should now work with the converter.

Thanks,
Shawn

**Comment by jpfeuffer** [comment]
Dear Shawn,

was this "case-specificity" problem reported already? Sounds like a problem on our side. Might be an easy fix. Usage might become much more streamlined then.

Thanks for helping out here!

**Comment by sjr24** [comment]
I do not believe it was.  I may have just added the step to the workflow without bringing up the issue.  If it could be fixed that would be great.

Thanks,
Shawn

**Comment by Clovernana** [comment]
Ok， I have tried that.And I find that in the columns "library intensity" that there were some "#N/A"s and openswathworkflow will produce  errors.And I just replaced them to 0. I guess it's not detected in the MS spectrometer . Can I perform that like this？Is it right?
Thanks！
Clover
On 7/15/2020 20:30，sjr24<notifications@github.com> wrote：

Clover,

For the exported transition list to work with the file converter you need to change the UniMod identifiers. Open the transition list .csv file in Excel -> use the ‘find and replace’ function -> find ‘UniMod’ and replace it with ‘unimod’. You will have to check the file, I cannot remember if skyline exports as UniMod or unimod, but whichever is in the file it needs to be changed to the other. Then save the document, and it should now work with the converter.

Thanks,
Shawn

**Comment by sjr24** [comment]
Clover,

You can delete all rows with N/A.  These occur because you told Skyline to report precursors and transitions.  The N/As are from the parent ions.  You can adjust your skyline document.  Adding a value of 0 could possibly take care of the problem, but I have not tried that.  My suggestion would be to use the filter function in excel to remove N/As or eliminate precursor ions from the skyline document.

Thanks,
Shawn

**Comment by Clovernana** [comment]
Ok，thank you!




On 7/15/2020 21:00，sjr24<notifications@github.com> wrote：

Clover,

You can delete all rows with N/A. These occur because you told Skyline to report precursors and transitions. The N/As are from the parent ions. You can adjust your skyline document. Adding a value of 0 could possibly take care of the problem, but I have not tried that. My suggestion would be to use the filter function in excel to remove N/As or eliminate precursor ions from the skyline document.

Thanks,
Shawn

**Comment by Clovernana** [comment]
Hi，
In  the step"OpenSwathWorkflow",can I write a cycle for multipul runs(no replicates or fraction )?
Thanks!

**Comment by Clovernana** [comment]
Which skyline version are you using ?Thanks so much!

发送自 Windows 10 版邮件应用

发件人: sjr24
发送时间: 2020年7月15日 10:07
收件人: OpenMS/OpenMS
抄送: Clover; Comment
主题: Re: [OpenMS/OpenMS] TargetedFileConverter error with exported Skylinefile (#3887)

Clover, 

Download the openswath.skyr 

Open a blank document in Skyline. 

File -> Export -> Report -> Edit list -> Import 

Then navigate to the saved openswath.skyr file and hit open. 

Now when you go to File -> Export -> Report -> Edit list -> Import, you will see OpenSwath as a report type option. It should export all the columns needed to make a library. 

Hope that helps. 

Thanks, 
Shawn

**Comment by Clovernana** [comment]
Hi,
I doubt that is the skyline version makes the error.And the question is that if I manually export the columns descried in skyline, the openMS2.5.0 still reported the error.
Thanks！



 


发送自 Windows 10 版邮件应用

发件人: sjr24
发送时间: 2020年7月15日 10:07
收件人: OpenMS/OpenMS
抄送: Clover; Comment
主题: Re: [OpenMS/OpenMS] TargetedFileConverter error with exported Skylinefile (#3887)

Clover, 

Download the openswath.skyr 

Open a blank document in Skyline. 

File -> Export -> Report -> Edit list -> Import 

Then navigate to the saved openswath.skyr file and hit open. 

Now when you go to File -> Export -> Report -> Edit list -> Import, you will see OpenSwath as a report type option. It should export all the columns needed to make a library. 

Hope that helps. 

Thanks, 
Shawn

**Comment by sjr24** [comment]
Clover,

I am using Skyline-daily (64-bit) 20.1.1.196.

Thanks,
Shawn
