### ISSUE TITLE
Website problem with plugin

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3891]
I get a warning on top of the page:
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; sidebar_generator has a deprecated constructor in /web/www.openms.de/wp/wp-content/themes/Avada/framework/plugins/multiple_sidebars.php on line 29

**Comment by oliveralka** [comment]
It seems to be in one of the Themes (Avada). We are currently using the OpenMS Theme - so I am not sure if that will be a problem in the future. 

To remove the error me may have to remove the Theme. Is there anyone who knows more about that? 
(@jpfeuffer )

**Comment by jpfeuffer** [comment]
We cant remove the theme. We can try to update but we have to pay and I am pretty sure it will break something.

**Comment by timosachsenberg** [comment]
do you know if we can make a backup, update the plugin, and if it fails revert?

**Comment by jpfeuffer** [comment]
I did it manually. It affected just one class.
