### ISSUE TITLE
Add Thermo RAW to mzML conversion 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3894]
There now seems to be a solution that works on all platforms (e.g. with mono).
Would make sense to include that to FileConverter
https://github.com/compomics/ThermoRawFileParser

**Comment by hroest** [comment]
How would you add that to the FileConverter? Would you simply wrap the commandline call for docker/mono and produce an output mzML? E.g. similar to how we use the other Adaptor tools? 

I think that is quite a different beast than the FileConverter, maybe we need a RawFileConverter for this. We can also consider doing this for some other vendors, e.g. Bruker has a API for their new TDF format that also works on Linux, not sure about other vendors though.

**Comment by timosachsenberg** [comment]
As a start, I would have probably just wrapped the call like in the Adaptor tools.
Other software do something similar: https://github.com/compomics/moFF
see also https://github.com/compomics/moFF/blob/master/RawFileRdr_License_Agreement_RevA.txt

There are some restrictions (show in about box, let user agree to a separate license agreement).

**Comment by lars20070** [comment]
The FGCZ tool [`rawDiag`](https://github.com/fgcz/rawDiag) is also using the Thermo [`RawFileReader`](http://planetorbitrap.com/rawfilereader) directly. It's incredibly fast!

**Comment by timosachsenberg** [comment]
I think this is currently the most appropriate one:
https://github.com/compomics/ThermoRawFileParser

**Comment by jpfeuffer** [comment]
Done
