### ISSUE TITLE
PeakPickerWavelet Failing with .mzml

### ISSUE THREAD

**Issue by gamebr8ker** [OpenMS/OpenMS#3901]
Hello,

I am trying to create a workflow to quantitate Waters UHPLC/MS .raw files automatically in a KNIME workflow. (Working with LCMS metabolite quantitation, specifically for drug metabolites in urine samples).
I'm using ProteoWizard to convert the Waters .raw files to .mzML. I then use the following nodes:
**[Input Files] > [ZipLoopStart] > [NoiseFilterGaussian] > [Resampler] > [PeakPickerWavelet] > [ZipLoopEnd] > [OutputFolder]** 

Everything seems to function except for **[PeakPickerWavelet]**, which gives the following error message:

---------------------------------------
_ERROR PeakPickerWavelet    5:5        

Failing process stdout: [Debug level (after ini file): 1, 

Value of string option 'no_progress': 0, 

Value of string option 'in': C:\Users\admin001\Desktop\Advanta Analytical - Ascent Files Initial\Ascent - Waters\02 - Waters P60 Batch 1\170916 W3 A P60 KNW PNA 1_01.mzML, 

Value of string option 'out': C:\Users\admin001\AppData\Local\Temp\knime_Workflow Manage47367\knime_fs-ZipLoopStart_5_8-47378\000\000\2_0_PeakPickerWavelet_0\170916 W3 A P60 KNW PNA 1_01.mzML, 

Value of string option 'write_peak_meta_data': 0, 

C:\jenkins\ws\openms_release_packaging\c2e226b2\source\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(144): While loading 'C:\Users\admin001\Desktop\Advanta Analytical - Ascent Files Initial\Ascent - Waters\02 - Waters P60 Batch 1\170916 W3 A P60 KNW PNA 1_01.mzML': Ill formed absolute or relative sourceFile path: file://C:\Users\admin001\Desktop\Advanta Analytical - Ascent Files Initial\Ascent - Waters\02 - Waters P60 Batch 1\170916 W3 A P60 JF PNA 1 Raw Folders\170916 W3 A P60 KNW PNA 1_01.raw, 

Progress of 'loading chromatogram list':, 

C:\jenkins\ws\openms_release_packaging\c2e226b2\source\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(144): While loading 'C:\Users\admin001\Desktop\Advanta Analytical - Ascent Files Initial\Ascent - Waters\02 - Waters P60 Batch 1\170916 W3 A P60 KNW PNA 1_01.mzML': Unhandled cvParam 'MS:1000130' in tag 'chromatogram'.,

 ,

-- done [took 0.02 s (CPU), 0.01 s (Wall)] -- , PeakPickerWavelet took 0.13 s (wall), 0.13 s (CPU), 0.02 s (system), 0.11 s (user)., Peak Memory Usage: 24 MB, 

**The given file does not contain any conventional peak data, but might contain chromatograms. This tool currently cannot handle them, sorry.]**

ERROR PeakPickerWavelet    5:5        Failing process stderr: []
ERROR PeakPickerWavelet    5:5        Execute failed: Failed to execute node PeakPickerWavelet_

-----------------------------------------------

Oddly, **[PeakPickerHiRes]** doesn't throw any errors, but it does take my data from nice, complete peaks to choppy, unfinished triangles. I'm not sure how/ if it can be configured for my data.

I would really appreciate some help on this. I am getting a strong vibe that this problem needs to be solved for me to get the **[FeatureFinderMetabo]** node working as well, which is the next step in my workflow.

**Comment by timosachsenberg** [comment]
Hi, can you post a link of the choppy triangles? Maybe it is just a visualization issue in TOPPView e.g. it displays the picked spectra as continuous lines (as it should do in profile mode only)

**Comment by gamebr8ker** [comment]
I can post that, however I believe that my problem may be more related to the following:

I have .raw files from a Waters UHPLC-MS/MS instrument. 
These files are converted into .mzML files via ProteoWizard.
I cannot view these files in 1D format in ToppView (I get the error: "This widget supports peak data only. Aborting!"). I can view them in 2D format, but I'm thinking that my inability to view them in 1D is integral to my problem. The PeakPicker_Tutorial files are viewable in 1D view. 

Would you or anyone else have any advice on how to convert these .raw files so that they can be read as 1D files, and consequently, be more likely to contain the data in the format that my KNIME nodes are looking for? 

I am attaching a .raw file, and the .mzML file (that I get when I use proteowizard).

[170916 W3 A P60 KNW PNA 1_36.raw.zip](https://github.com/OpenMS/OpenMS/files/2687452/170916.W3.A.P60.KNW.PNA.1_36.raw.zip)
[170916 W3 A P60 KNW PNA 1_36.mzML.zip](https://github.com/OpenMS/OpenMS/files/2687454/170916.W3.A.P60.KNW.PNA.1_36.mzML.zip)

**Comment by cbielow** [comment]
The problem is that your data is pure SRM, i.e. MS2 chromatograms.
`FileInfo` says:
```
c:\TEMP>c:\dev\openmsqt5_build\bin\Release\FileInfo.exe -in "170916 W3 A P60 KNW PNA 1_36.mzML"
Progress of 'loading chromatogram list':
-- done [took 0.02 s (CPU), 0.02 s (Wall)] --


Memory usage (loading MS data): 2 MB (working set delta), 13 MB (peak working set delta)

-- General information --

File name: 170916 W3 A P60 KNW PNA 1_36.mzML
File type: mzML

MS levels:
Number of spectra: 0
Number of peaks: 17289

Ranges:
  retention time: 12.06 .. 185.97
  mass-to-charge: 42.39 .. 302.10
  intensity:      0.00 .. 3502080.00

Peak type metadata (estimated)
Number of chromatograms: 167
Number of chromatographic peaks: 23529

Number of chromatograms per type:
  total ion current chromatogram:                         1
  selected reaction monitoring chromatogram:                         166


FileInfo took 0.18 s (wall), 0.19 s (CPU), 0.02 s (system), 0.17 s (user).
```

And PP currently cannot handle that.
`MSConvert` has a flag `--srmAsSpectra`, but it does not seem to do anything (at least using my old version of ProteoWizard release: 3.0.10577 (2017-3-6)).

You should be able to use msconvert to peak picking though, but FFMetabo will not work on SRM data (AFAIK). Basically, you already have the assay. Why use FF?

**Comment by gamebr8ker** [comment]
The goal of my project is to quantitate our Waters UHPLC-MS/MS assay via the OpenMS/KNIME automated workflow and output to a GUI that is a little more suited to our needs (we would like to be able to review multiple peaks at once, set up warnings when certain peaks are out of range, and have a tie-in with our database which provides previous testing information about a given sample when said sample is selected). 

It seemed like the Waters interface was too rigid to accommodate that, and I've personally never had good experience talking to Waters about anything that wasn't hardware-related anyway.

As far as using FF, it really just stems from some confusion surrounding exactly which nodes I need to implement in order to get the data yield I'm looking for (at the end of the day, use something like my existing assay method to process my files, albeit through KNIME). 
@cbielow Your information is very helpful in increasing my understanding of the process. If you have any additional thoughts on how I might proceed, I'd be grateful for your help.

**Comment by hroest** [comment]
@gamebr8ker It seems that what you actually would like to do is targeted analysis (SRM / MRM like analysis) of the data. We have support for this type of analysis as well mainly through the OpenSWATH module inside OpenMS (which was designed for DIA analysis but can also handle other types of targeted workflows). If you need help or would like to discuss this further, feel free to talk to me directly on gitter or via email

**Comment by hroest** [comment]
PS: the tool you probably want to use is MRMTransitionGroupPicker, see https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/experimental/feature/msstats/html/UTILS_MRMTransitionGroupPicker.html

**Comment by cbielow** [comment]
will close for now. It seems this is just a case of data<>tool mismatch. Feel free to re-open if something new comes up/
