### ISSUE TITLE
MSSimulator crash: `Aborted (core dumped)`

### ISSUE THREAD

**Issue by jspmccain** [OpenMS/OpenMS#3902]
I'm running into an error when I run MSSimulator on an Ubuntu (18.04) computer. 

I'm using this sequence file Mock_Comm_RefDB_V3.fasta (https://www.ebi.ac.uk/pride/archive/projects/PXD006118/files). I have set abundance using the script included in OpenMS:

`python FASTAProteinAbundanceSampling.py ../data/Mock_Comm_RefDB_V3.fasta ../data/Mock_Comm_RefDB_V3_abundance.fasta`

I added a `random.seed(1111)` to this python script.

I then used:

`MSSimulator -in ../data/Mock_Comm_RefDB_V3_abundance.fasta -out ../data/Mock_Comm_RefDB_V3_abundance_debug.mzML -out_id ../data/Mock_Comm_RefDB_V3_abundance_debug.idXML -threads 24 -algorithm:MSSim:RawTandemSignal:status "precursor"  -algorithm:MSSim:RawTandemSignal:Precursor:Exclusion:use_dynamic_exclusion -algorithm:MSSim:RawTandemSignal:Precursor:Exclusion:exclusion_time 30 -debug 10 -algorithm:RandomNumberGenerators:biological reproducible
-algorithm:RandomNumberGenerators:technical reproducible`

Here is the error I get:

```
---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler:
exception of type InvalidValue occured in line 121, function
static FactoryProduct* OpenMS::Factory<FactoryProduct>::create(const OpenMS::String&) [with FactoryProduct = OpenMS::BaseModel<1u>]---------------------------------------------------
 of /home/jenkins/ws/openms_release_packaging/40c74027/source/src/openms/include/OpenMS/CONCEPT/Factory.h
error message: the value 'GaussModel' was used but is not valid; This FactoryProduct is not registered!FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler:
exception of type InvalidValue occured in line
121---------------------------------------------------
, function static FactoryProduct* OpenMS::Factory<FactoryProduct>::create(const OpenMS::String&) [with FactoryProduct = OpenMS::BaseModel<1u>] of /home/jenkins/ws/openms_release_packaging/40c74027/source/src/openms/include/OpenMS/CONCEPT/Factory.h
error message: the value 'GaussModel' was used but is not valid; This FactoryProduct is not registered!
sim_mssimultator.sh: line 14: 71949 Aborted                 (core dumped) MSSimulator -in ../data/Mock_Comm_RefDB_V3_abundance.fasta -out ../data/Mock_Comm_RefDB_V3_abundance_debug.mzML -out_id ../data/Mock_Comm_RefDB_V3_abundance_debug.idXML -threads 24 -algorithm:MSSim:RawTandemSignal:status "precursor" -algorithm:MSSim:RawTandemSignal:Precursor:Exclusion:use_dynamic_exclusion -algorithm:MSSim:RawTandemSignal:Precursor:Exclusion:exclusion_time 30 -debug 10 -algorithm:RandomNumberGenerators:biological reproducible -algorithm:RandomNumberGenerators:technical reproducible
```

Any help with this is greatly appreciated!

**Comment by jpfeuffer** [comment]
Hi there,
One little thing to try: Does it run with just one thread (e.g. without the threads parameter or threads=1)?

Cheers
Julianus

**Comment by cbielow** [comment]
I ran MSSimulator with your flags and abundance settings (using another FASTA file though) with 24 threads and I did not observe the error.
(I found something else though, but this is unrelated to this issue).
Does it happen every time you run it or only spuriously? What is the console output up to this point?
And what OpenMS Version is it? (OpenMSInfo executable will tell you -- or the KNIME plugin version).

**Comment by cbielow** [comment]
nah, its probably not your workstation.
A race condition on our side is more likely :)

**Comment by jpfeuffer** [comment]
That's what I had in mind. Thanks @cbielow .

**Comment by jspmccain** [comment]
Great, thanks for this! Do you know if there are update instructions for OpenMS? Or should I just build it again from scratch?

**Comment by cbielow** [comment]
you can do `git pull ... ` in the src directory and `make` in the build directory. That should do it. The contrib might have changed as well in the meantime (depends on what version you have).

I'll close this issue since updating should solve it. Feel free to reopen if it does not :)
