### ISSUE TITLE
TargetedFileConverter error when converting published human library 

### ISSUE THREAD

**Issue by JeBu42** [OpenMS/OpenMS#3909]
Hi, I am trying to convert the publicly available spectral library for SWATH (phl004_canonical_s64_osw_decoys from doi 10.1038/sdata.2014.31 (2014)) into .pqp format. However receive the following: 

```
>TargetedFileConverter -in phl004_canonical_s64_osw_decoys.TraML -out phl004_canonical_s64_osw_decoys.pqp


Error: Unexpected internal error (the value 'UniMod:35' was used but is not valid; Retrieving the modification failed. It is not available for the residue 'M' and term specificity 1.)
```

I have used targetedfileconverter to convert some of our in house generated spec libraries before, and it seems to work fine. 
I am running OpenMS 2.4 - assuming an older OpenMS version was used to create this library, I am wondering if this is a compatibility issue?
If so is there any way to work around this without replacing my current version of OpenMS.

Jess

**Comment by JeBu42** [comment]
I get the same error when attempting to do this (at the OpenSwathAssayGenerator stage):

```
>OpenSwathAssayGenerator -in phl004_canonical_sall_osw.TraML -out phl004_canonical_sall_osw_optimised.TraML -swath_windows_file swathwindows.txt

Validate provided Swath windows file:
Read Swath window header start  end
Read Swath window file with 32 SWATH windows.
Read Swath maps file with 32 windows.
Loading phl004_canonical_sall_osw.TraML
Annotating transitions
Progress of 'Annotating transitions':
-- done [took 02:46 m (CPU), 02:46 m (Wall)] --
Annotating detecting transitions
Progress of 'Restricting transitions':
-- done [took 33.06 s (CPU), 33.07 s (Wall)] --
Writing assays phl004_canonical_sall_osw_optimised.TraML
Error: Unexpected internal error (the value 'UniMod:35' was used but is not valid; Retrieving the modification failed. It is not available for the residue 'M' and term specificity 1.)
```

Best,
Jess

**Comment by grosenberger** [comment]
Do you have SpectraST installed? Then I would use the ``sptxt`` file to generate a MRM file (http://openswath.org/en/latest/docs/tpp.html) that should be fully compatible.

**Comment by JeBu42** [comment]
I do have SpectraST - will do this.
Thanks

**Comment by hroest** [comment]
@grosenberger can we update the PanHuman library so that it is compatible?

**Comment by grosenberger** [comment]
Good point. I just converted the data (including proteotypic subsets) and requested uploading at SWATHAtlas.

**Comment by hroest** [comment]
> Good point. I just converted the data (including proteotypic subsets) and requested uploading at SWATHAtlas.

@grosenberger is this done now? can we close the issue?

**Comment by tomcorwin** [comment]
Hello, 
When testing the OpenSWATH workflow using the pan human library I ran into the same problem(s) as stated above when I wanted to run PyProphet on the results. It would be great and save time if the library can be provided in .pqp format. Is the converted library available elsewhere or any update on this?
Best regards,
Tom

**Comment by grosenberger** [comment]
There are two new files on SWATHAtlas: ``phl004_consensus_openms24.TraML`` and ``phl004_consensus_proteotypic_openms24.TraML`` that are compatible with the newer OpenMS versions.

Since nowadays many different data acquisition schemes are in use, my suggestion would be to download the TraML from above and convert to PQP using ``TargetedFileConverter``. The tools are much faster since OpenMS > 2.4 and since PQP is still a somewhat evolving format, this guarantees that the version is consistent within your workflow. Please let me know if you run into any issues.

**Comment by tomcorwin** [comment]
@grosenberger Thank you very much!
