### ISSUE TITLE
OpenMS 2.4 TOPPView and TOPPAS not launching on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by grzsko** [OpenMS/OpenMS#3923]
When I try open TOPPView or TOPPAS on Mac OS X 10.11.6 I get a message, that I cannot run app on this version of OS X and I require OS X version at least 10.12.

What's interesting when I run specific binary from terminal (e.g. /Applications/OpenMS-2.4.0/TOPPView.app/Contents/MacOS/TOPPView), it works.

**Comment by jpfeuffer** [comment]
Hi!
Hmm.. Can you post the exact error or a screenshot of it? I can't find it on the internet and on top of my head I have no idea on where to start debugging.

**Comment by grzsko** [comment]
![image](https://user-images.githubusercontent.com/5202791/51236662-06f28000-1973-11e9-89af-fca96701dd2a.png)

**Comment by jpfeuffer** [comment]
Thanks! Although my Polish is not so great, I found something with your help ;)
https://stackoverflow.com/questions/39310079/mac-app-package-backwards-compatibility-error-you-cant-use-this-version-of-t

I will see what we can do. Although we will never be able to provide full backwards compatibility to all older versions.

**Comment by timosachsenberg** [comment]
any update on this? still critical?

**Comment by jpfeuffer** [comment]
I just set the macOS deployment target to 10.9, the first one with libc++ (so it should not cause too much trouble and should be enough for 99% of the people).
I will update here if it works.

**Comment by timosachsenberg** [comment]
Hi Julianus did you get any chance to take a look at that?

**Comment by jpfeuffer** [comment]
I don't know anyone who has 10.11 but in theory it should work now. It definitely works on 10.12.

**Comment by yhsongk** [comment]
ToppView and Toppas are not launching on MacOS 12.3. However there is no error message either. How can I fix it.

**Comment by jpfeuffer** [comment]
In the foreseeable future, we will not be able to provide notarized apps for macOS. You will need to remove it from quarantine like here: https://github.com/OpenMS/OpenMS/issues/4357#issuecomment-581397460 or deactivate your gatekeeper.
