### ISSUE TITLE
NoiseFilterGaussian doesn't smooth the data and output a broken line

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#3932]
What can I do to make my data smoothed?

**Comment by mash23** [comment]
This is Gaussian 
![screenshot](https://user-images.githubusercontent.com/46929174/51542618-426ade00-1e8e-11e9-98aa-96120a3c9843.jpg)
And here SavitzkyGolay
![screenshot_golay](https://user-images.githubusercontent.com/46929174/51543109-65e25880-1e8f-11e9-8330-20ab3b8c704e.jpg)

**Comment by timosachsenberg** [comment]
what gaussian width did you choose? might be too large

**Comment by mash23** [comment]
At the picture width = 0.2.
I tried different widths, but it didn't get better.

**Comment by mash23** [comment]
Here width=0.01
![screenshot3](https://user-images.githubusercontent.com/46929174/51549893-ce383680-1e9d-11e9-9f4e-348625f5662f.jpg)

**Comment by lars20070** [comment]
Nope. Not relevant for modern Thermo data. Might be different for Bruker, Waters et al.
