### ISSUE TITLE
Fail using PeakPickerWavelet

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#3934]
I apply PeakPickerWavelet and get this:
![screenshot_pp1](https://user-images.githubusercontent.com/46929174/51555909-55d87200-1eab-11e9-80db-f61bb36d5c3b.jpg)

Is it ok? What can I do to make it look better?

**Comment by timosachsenberg** [comment]
@mash23 may I ask on what instrument that data was aquired?

**Comment by mash23** [comment]
You mean where did I get raw files ?

**Comment by timosachsenberg** [comment]
yes. I am asking to assess if the PeakPickerWavelet is the correct choice for that data

**Comment by mash23** [comment]
What are other ways?

**Comment by oliveralka** [comment]
@mash23 

You can try the PeakPickerHiRes:
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_PeakPickerHiRes.html

It depends on the instrument the data was acquired from (high, low resolution). 
Another option is to perform the peak picking together with the data conversion via msconvert/ProteoWizard. 

Another question - do you mean centroiding of the data by peak picking (OpenMS) or feature finding   - just to be on the same page?

**Comment by mash23** [comment]
I mean centroiding by peak picking. 
I tried PeakPickerHiRes and here is what I got
![screenshot_hires](https://user-images.githubusercontent.com/46929174/51674684-f2158c80-2003-11e9-96c1-474a21daa6c7.jpg)

**Comment by timosachsenberg** [comment]
Ok great. The 2D view is not very indicative. Please take a look at the 1D visualization.
You can overly the profile data and the centroided data as in https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Handout/master/TOPP_tutorial.pdf page 19

**Comment by mash23** [comment]
![screenshot6](https://user-images.githubusercontent.com/46929174/51988437-3f4b9f80-24d7-11e9-988c-7886c4fe3615.jpg)
At the picture blue is for the initial data, yellow - PeakPickerHiRes and green - PeakPickerWavelet.

**Comment by hroest** [comment]
>  At the picture blue is for the initial data, yellow - PeakPickerHiRes and green - PeakPickerWavelet.

If you do have high resolution data (e.g. TOF or Orbitrap data) then I suggest to use the PeakPickerHiRes - potentially after SGolay smoothing or Gaussian smoothing in the case of TOF data.
