### ISSUE TITLE
target-decoy column in PSM section of mzTab

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3943]
According to mzTab 1.0.0 specs 5.12.5, target-decoy information can/should be stored in a column `opt_global_cv_MS:1002217_decoy_peptide` with boolean values `(0, 1)`. This column is implemented in MaxQuant 1.6.3.3. OpenMS writes this information in a column `opt_global_target_decoy` with values `(target, decoy, target+decoy)` instead.

Can we add a column `opt_global_cv_MS:1002217_decoy_peptide` as suggested in the specs? The column is optional, but our `mzTab` would become more compliant to the standard.

**Comment by timosachsenberg** [comment]
sure if you want you can remove our column and add the opt_global_cv_MS:1002217_decoy_peptide yourself

**Comment by lars20070** [comment]
Our column is not binary. So I intend to map.
```
target --> 0
decoy --> 1
target + decoy --> 0
```
The last case is very unlikely, [0.1%](https://github.com/ProteomicsScripts/ProteomicsScripts/blob/master/mzTab2PSMreport/misc/example.pdf) of all PSMs in many analyses.

**Comment by lukaszimmermann** [comment]
I took the liberty to address this

**Comment by lars20070** [comment]
@lukaszimmermann Thank you! Very helpful.

**Comment by jpfeuffer** [comment]
Should be done, right? Reopen if not.
