### ISSUE TITLE
How to understand what gaussian width to use for NoiseFilterGaussian?

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#3944]

**Comment by timosachsenberg** [comment]
Hi,
please see the documentation of NoiseFilterGaussian https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/TOPP_NoiseFilterGaussian.html
If something is not clear please let us know so we can improve the documentation.

**Comment by mash23** [comment]
I only know that it was a LC-MS system.

**Comment by timosachsenberg** [comment]
Without additional information, it is probably very difficult or impossible to analyze or process the data. Is there a way how we can shed some light on that?

**Comment by hroest** [comment]
@mash23 @timosachsenberg it should actually say what instrument it was in the mzML file if you have converted it through proteowizard

**Comment by mash23** [comment]
I learned that the data was taken from here: https://www.ebi.ac.uk/pride/archive/projects/PXD003348.

**Comment by timosachsenberg** [comment]
For LTQ Orbitrap Velos you don't need the noise filter gaussian.

**Comment by mash23** [comment]
So I can use PeakPicker directly?

**Comment by timosachsenberg** [comment]
Yes, PeakPickerHiRes
