### ISSUE TITLE
Where is the file "OpenMS/OPENSWATHALGO/OpenSwathAlgoConfig.h"?

### ISSUE THREAD

**Issue by Reliacrt** [OpenMS/OpenMS#3951]
The file is included in every openSWATH's code, but I can't find this file in such directory.

**Comment by cbielow** [comment]
The file is generated by CMake build system when building OpenMS.
You can find it in `your_build_tree\src\openswathalgo\include\OpenMS\OPENSWATHALGO\OpenSwathAlgoConfig.h`

**Comment by hroest** [comment]
Hi

I have some more information on how the file is generated in case anyone is
interested. The file is autogenerated, see this commit
https://github.com/OpenMS/OpenMS/commit/3e442e8eaf1e353df6803cd44b with

include(GenerateExportHeader)

which is documented here:
https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html - you
can find the generated file in your build tree as indicated by Chris but
you will *not* find it in the source tree as it does not exist (it will
only be generated in the build tree). Basically the file defines a few
useful macros such as OPENSWATHALGO_DLLAPI and OPENSWATHALGO_NO_EXPORT

I hope that helps

Best

Hannes

**Comment by cbielow** [comment]
closing. Re-open if something remains unclear.
