### ISSUE TITLE
Update UNIMOD: IDFileConverter cannot process 15N-label

### ISSUE THREAD

**Issue by Stortebecker** [OpenMS/OpenMS#3960]
Hi.

I tried converting an idXML file to mzid with IDFileConverter. The idXML came from an original MSGF+ search, where I used 15N-labels. 
All amino acids were labelled, so I used Unimod 994, 995, 996 and 897. The labels were processed so far without any error by several Toppas Tools.

However, IDFileConverter gave the following:
`Error: Unexpected internal error (the value 'UNIMOD:994' was used but is not valid; Invalid CV identifier!)`
The error does not occur, when converting into `pepXML`, though.

To reproduce the error, use this [input file](https://gist.github.com/Stortebecker/38440a267892d81b917c063643932ec2) and run `IDFileConverter -in INPUT_FILE.idXML -out INPUT_FILE.mzid`

used version: 2.3
platform: win10

**Comment by lukaszimmermann** [comment]
Here's your file: https://www.dropbox.com/s/1vqnrotw02s1uco/IDFileConverterError.mzid?dl=0
