### ISSUE TITLE
Faster Number -> String conversion

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#3962]
Similar to switching to Boost:Qi for String->Number some time ago (#692), I did some microbenchmarks for converting a number (int, float, double) to String.
We are currently using std::stringstream, which is about the worst in terms of performance one could imagine.

I only tested converters which are readily available in OpenMS with C++11 and contrib. There are others (FMT lib for example), but I did not want to introduce yet another dependency.

Candidates:

- **stringstream** -- standard stringstream without precision modifiers (everything has precision of 6)
- **stringstreamFP** -- also a stringstream but using precision of 6 (for float) and 15 (for double); 
- **sprintf** -- the good old plain C function
- **std::to_string** -- available from C++11 onwards for all relevant types, but not really a viable candidate since we have no control how the string is formatted; basically, as [printf with format '%f'](http://www.cplusplus.com/reference/string/to_string/). e.g. the double `8.592e307` becomes a string with 308 chars!
- **boost::karma** -- sibling of boost::Qi, very fast, but different notion of precision; we use up to three decimal digits (default) here ***
- **boost::karmaFP** -- full precision variant, using 6 (float) and 15 (double) **_decimal_** digits
- **boost::lexical_cast** -- no control over precision [https://www.boost.org/doc/libs/1_65_0/doc/html/boost_lexical_cast.html)[docs], but included for completeness
- **boost::format** -- similar to sprintf with formatting allowed

In OpenMS we currently use a mixture of stringstream and stringstreamFP, depending on how an outputstream is used. If just operator << is used, precision is 6; however, when using String(double/float) or precisionWrapper(double/float), we get 6/15 precision. Note that precision in terms of stringstream means up to 6 or 15 digits in total (not only fractional(decimal) digits).
For Boost::Karma, we get something sligthly different, i.e. 6/15 fractional digits, no matter how large the integer part is (i.e. potentially larger strings).

Here is the plain benchmark data for converting 100000 numbers in the range of [0,1e6] to strings.
Length at each lines gives the summed length of the generated strings.
```
**Windows, VS14**
Bench for int:
stringstream: 112ms length: 888705
stringstreamFP: 113ms length: 888705
sprintf: 16ms length: 888705
to_string: 3ms length: 888705
karma: 13ms length: 888705
karmaFP: 11ms length: 888705
boostLC: 16ms length: 888705
toBoostFmt: 211ms length: 888705


Bench for float:
stringstream: 178ms length: 1088320
stringstreamFP: 178ms length: 1088320
sprintf: 39ms length: 1088320
to_string: 77ms length: 1588823
karma: 22ms length: 789115
karmaFP: 24ms length: 1088995
boostLC: 86ms length: 890343
toBoostFmt: 274ms length: 1088320


Bench for double:
stringstream: 179ms length: 1088298
stringstreamFP: 191ms length: 1588857
sprintf: 45ms length: 1088298
to_string: 87ms length: 1588915
karma: 22ms length: 788984
karmaFP: 44ms length: 1989101
boostLC: 106ms length: 1789059
toBoostFmt: 284ms length: 1088298

**Linux, GCC6.3**

Bench for int:
stringstream: 64ms length: 888895
stringstreamFP: 64ms length: 888895
sprintf: 12ms length: 888895
to_string: 12ms length: 888895
karma: 9ms length: 888895
karmaFP: 9ms length: 888895
boostLC: 5ms length: 888895
toBoostFmt: 89ms length: 888895


Bench for float:
stringstream: 143ms length: 1088217
stringstreamFP: 133ms length: 1088217
sprintf: 51ms length: 1088217
to_string: 68ms length: 1588892
karma: 24ms length: 789092
karmaFP: 30ms length: 1088906
boostLC: 80ms length: 890331
toBoostFmt: 162ms length: 1088217


Bench for double:
stringstream: 140ms length: 1088474
stringstreamFP: 177ms length: 1588928
sprintf: 51ms length: 1088474
to_string: 87ms length: 1589034
karma: 25ms length: 788890
karmaFP: 58ms length: 1988858
boostLC: 120ms length: 1788872
toBoostFmt: 165ms length: 1088474

```

Boost::Karma is the clear winner in almost all benchmarks (only beaten by to_string for int conversion on VS).

As a real world example switching from StringStream to Karma in OpenMS by writing a 300/100MB idXML file yields the following timings (before -> after):
Windows, VS14: `21.98 s --> 16.95 s` (~23% improvement)
Linux, GCC6.3: `5.94 s --> 4.61 s` (~23% improvement)

The code is basically finished at this point (it uses Boost::Karma), only a few dozen tests remain to be fixed.
However, we need to live with the fact that precision means something different for stringstream vs. karma (see above).
The way the new OpenMS behaves is (in terms precision for floats/doubles, everything else stays the same, e.g. ints).
 - if you write a `os << 1.234` , thats default precision as before but bad performance (similar to stringstream)
 - if you write `os << String(1.2345)` you get Karma performance, but with default fractional precision of 3 (i.e. `1.234` will be written); in the current OpenMS, you would actually get full precision! The reason I did not do that, is because you do not have a way to convert with low precision then (e.g. when you only store RT's)
 - if you write `os << precisionWrapper(1.2345)` or equivalently `os << String(precisionWrapper(1.2345))` you get Karma performance with maximum precision (15 in this case, since its a double). In the current OpenMS, you would get the same value, but slower.
 - when using `os << DataValue.toString()`, you get Karma performance but which precision is up for discussion. One could argue that it should behave as String(DataValue) or String(double), i.e. low precision. However, when writing a DataValue to a stream, they are usually MetaValues, and you don't know what the user put in there. So full precision is the better=safer choice. We could introduce another function for that or provide a default bool parameter `DataValue::toString(bool fullPrecision = false);`

Comments/ideas?

**Comment by timosachsenberg** [comment]
Cool thanks for the analysis. I am a bit concerned about the small precision as default. 
What would be the downside of a constructor String(float f, bool fullPrecision = true);` ?

**Comment by cbielow** [comment]
there is a slight performance cost (compare Karma vs KarmaFP above) and our files get larger by default (up to 12 chars per double and up to 3 chars per float). Apart from that, its the saver route, which I'm happy to take. Using a default is usually only problematic when we want to change it from true to false at some point...

**Comment by timosachsenberg** [comment]
Then let's be more conservative now and keep full precision. I imagine that 3 digits is way to small for e.g. matching by m/z

**Comment by oliveralka** [comment]
Thanks a lot for the benchmark! 
I would go for the full precision as well (at least for the DataValue). 

How much bigger would a standard file be using KarmaFP in general? -
Since the speed would still be a reasonable improvement.

**Comment by jpfeuffer** [comment]
I vote for full precision as default, too, also important for discriminating scores.

**Comment by hroest** [comment]
> there is a slight performance cost (compare Karma vs KarmaFP above

I think it is still much better than what we have now and I think the performance cost is justified for being more precise and not loosing data
