### ISSUE TITLE
ProteinQuantifier: fill in missing values [397]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#397]
Submitted by hendrikweisser on 2012-02-20 12:31:50

Missing values in peptide/protein abundances computed by ProteinQuantifier could be filled in with background values.

Values to fill in could be computed e.g. by fitting a normal distribution to the abundance values and selecting a point some standard deviations below the mean.

However, if the same fill value is used in all cases, certain statistical methods (e.g. correlation) will be affected. If noise is added, how to distinguish between a "true" and a "filled-in" value?

---

Commented by hroest on 2013-06-18 18:27:33:
See also this recent publication:

https://www.ncbi.nlm.nih.gov/pubmed/23176322

Another question is whether to this in C++ or R (seems less painful). Also one has to be very careful about the assumptions, e.g. are the missing values randomly distributed or not?

---

Commented by hendrikweisser on 2013-06-18 22:46:49:
It would definitely be easier to implement in R, but might be nicer for users to have directly in OpenMS. (The same applies to normalization of abundances from different samples.)

I consider this quite low priority.

**Comment by jpfeuffer** [comment]
I know that @timosachsenberg was working on this as a tool in C++.

**Comment by timosachsenberg** [comment]
Its currently in https://github.com/timosachsenberg/OpenMS/tree/feature/imputation as part of ConsensusMapNormalizer

**Comment by hroest** [comment]
@timosachsenberg any plans to merge this soon? It would be nice to have but imputation is really hard and it would take quite a bit of time to evaluate different imputation methods properly. In MS there are also different categories of missing values, namely MCAR and MNAR depending on the reason they are missing (especially in DDA).

**Comment by timosachsenberg** [comment]
I have a branch using singular value thresholding. I think Tjeerd benchmarked it and it performed quite well but more tests would be necessary.

**Comment by hroest** [comment]
@timosachsenberg would it make sense to merge it to have it in there instead of letting it sit outside `develop` ? then people at least could use it if they wanted to?

**Comment by jpfeuffer** [comment]
@timosachsenberg do you still plan to merge this or are we directing users to MSstats with our compatible output now?
