### ISSUE TITLE
FeatureFinderCentroid failed 

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#3974]
I apply FeatureFinderCentroid to the picked (with PeakPickerHiRes) data, but it failed with the output:

Abort reasons during feature construction:
- Could not extend seed: 135
- Could not find good enough isotope pattern containing the seed: 1
- Invalid feature after fit - too few traces or peaks left: 44
- Invalid fit: Center outside of feature bounds: 2
- Invalid fit: Fitted model is bigger than 'max_rt_span': 23
FeatureFinderCentroided took 0.65 s (wall), 0.65 s (CPU), 0.01 s (system), 0.64 s (user).

What can be done to fix this?

**Comment by hroest** [comment]
>  FeatureFinderCentroided took 0.65 s (wall), 0.65 s (CPU), 0.01 s (system), 0.64 s (user).

I don think it failed, this is normal output. It did not actually fail, this is only informative output telling you that there are only some seeds that could not "promoted" to a feature. Can you please post the whole output? Did you look at your data, is the data different from what you expected?

**Comment by mash23** [comment]
Here's the whole output: 

Version 2.4.0-develop-2018-10-24 of FeatureFinderCentroided is available at www.OpenMS.de
Progress of 'loading spectra list':
-- done [took 2.03 s (CPU), 2.03 s (Wall)] -- 
Progress of 'loading chromatogram list':
-- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
Progress of 'Precalculating intensity scores':
-- done [took 1.32 s (CPU), 1.33 s (Wall)] -- 
Progress of 'Precalculating mass trace scores':
-- done [took 4.01 s (CPU), 4.00 s (Wall)] -- 
Progress of 'Precalculating isotope distributions':
-- done [took 0.02 s (CPU), 0.03 s (Wall)] -- 
Progress of 'Calculating isotope pattern scores for charge 1':
-- done [took 5.76 s (CPU), 5.75 s (Wall)] -- 
Progress of 'Finding seeds for charge 1':
-- done [took 0.14 s (CPU), 0.14 s (Wall)] -- 
Found 70096 seeds for charge 1.
Progress of 'Extending seeds for charge 1':
-- done [took 01:35 m (CPU), 01:35 m (Wall)] -- 
Found 7395 feature candidates for charge 1.
Progress of 'Calculating isotope pattern scores for charge 2':
-- done [took 6.68 s (CPU), 6.69 s (Wall)] -- 
Progress of 'Finding seeds for charge 2':
-- done [took 0.16 s (CPU), 0.15 s (Wall)] -- 
Found 39639 seeds for charge 2.
Progress of 'Extending seeds for charge 2':
-- done [took 42.68 s (CPU), 42.70 s (Wall)] -- 
Found 3672 feature candidates for charge 2.
Progress of 'Calculating isotope pattern scores for charge 3':
-- done [took 7.34 s (CPU), 7.34 s (Wall)] -- 
Progress of 'Finding seeds for charge 3':
-- done [took 0.11 s (CPU), 0.11 s (Wall)] -- 
Found 20874 seeds for charge 3.
Progress of 'Extending seeds for charge 3':
-- done [took 23.48 s (CPU), 23.49 s (Wall)] -- 
Found 1524 feature candidates for charge 3.
Progress of 'Calculating isotope pattern scores for charge 4':
-- done [took 7.87 s (CPU), 7.87 s (Wall)] -- 
Progress of 'Finding seeds for charge 4':
-- done [took 0.10 s (CPU), 0.11 s (Wall)] -- 
Found 12309 seeds for charge 4.
Progress of 'Extending seeds for charge 4':
-- done [took 4.94 s (CPU), 4.94 s (Wall)] -- 
Found 747 feature candidates for charge 4.
Progress of 'Resolving overlapping features':
Removed 4390 overlapping features.
-- done [took 3.27 s (CPU), 3.27 s (Wall)] -- 
8948 features left.

Abort reasons during feature construction:
- Could not extend seed: 58890
- Could not find good enough isotope pattern containing the seed: 18613
- Feature quality too low after fit: 3235
- Invalid feature after fit - too few traces or peaks left: 24069
- Invalid fit: Center outside of feature bounds: 527
- Invalid fit: Fitted model is bigger than 'max_rt_span': 6608
- Invalid fit: Less than 'min_rt_span' left after fit: 12
FeatureFinderCentroided took 03:27 m (wall), 03:27 m (CPU), 0.34 s (system), 03:26 m (user).

**Comment by mash23** [comment]
And this is what it looks like in the TOPPView:
![feature](https://user-images.githubusercontent.com/46929174/52997738-f80c5b00-3453-11e9-86ea-9d72d04afffd.jpg)

**Comment by timosachsenberg** [comment]
Looks good to me. As a user, how would you like the log message to be phrased to reduce confusion?

**Comment by mash23** [comment]
Well, I was confused by the word "abort"... Looks like FeatureFinder didn't actually finished.
