### ISSUE TITLE
Creating a target-decoy database for peptide identification

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#3986]
Hi, I'm trying to create a target-decoy database for peptide identification. I have downloaded a fasta file with chicken proteome from UNIPROT.
As I understand I need to cut all proteins in the proteome to peptides and generate a database with all those peptides and add a decoy to each of them. How can make that?

**Comment by timosachsenberg** [comment]
Hi,
You can directly feed the database into the DecoyDatabase tool of OpenMS (without prior digestions) 
to generate a target-decoy database.
you can find the OpenMS documentation at: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/2.4.0/html/index.html
Particularly, https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/2.4.0/html/UTILS_DecoyDatabase.html
will explain how to create a decoy database.
Also consider taking a look at the OpenMS tutorial: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Handout/master/handout.pdf
Best,
Timo

**Comment by mash23** [comment]
Thank you for your response!
So I can run search engines with the database I obtained with DecoyDatabase tool? It worked for XTandemAdapter but didn't work for OMSSA, it asked for some .psq file..
I tried to use makeblastbd like this "makeblastbd -in db_decoy.fasta -bdtype prot". After that OMSSA finished successfully, but it's output was empty.

**Comment by mash23** [comment]
Hello again!
I've recently ran into another problem: I applied XTandem to several different MS experiments and it worked great for some of them (the needed proteins were identified) but for others it gave me either an empty list of identifications or a list full of DECOYs... Why can this be and what can be done to avoid this ?

**Comment by jpfeuffer** [comment]
Yes, could be many things: modifications, incomplete database, search tolerances, problems during posterior probability/fdr calculation. Closing for now.
