### ISSUE TITLE
Fail using IDPosteriorErrorProbability

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#3991]
Hi!
I applied IDPosteriorErrorProbability after using OMSSAAdapter and it worked good, but it didn't work for XTandemAdapter.. It crashes with the fillowing:

Version 2.4.0-develop-2018-10-24 of IDPosteriorErrorProbability is available at www.OpenMS.de
Unable to fit data. Algorithm did not run through for the following search engine: XTANDEM
IDPosteriorErrorProbability took 2.32 s (wall), 2.32 s (CPU), 0.04 s (system), 2.28 s (user).

**Comment by hendrikweisser** [comment]
See also #4022.

**Comment by jpfeuffer** [comment]
We did some recent changes to IDPEP for stability. You could try again. If it still does not work don't hesitate to send us your input file and reopen the issue.

**Comment by cherrypas** [comment]
Could you please explain how one can update the tool ? I have the same problem with IDPEP.

**Comment by jpfeuffer** [comment]
If you are using the installers just download the newest nightly version from our server.
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/

But I have to say, IDPEP has its limits. If the score distribution is weird, it might just not be able to separate good from bad scores.
You can output the histogram for plotting with gnuplot by setting the out_plot paramater.
