### ISSUE TITLE
Add missed cleavages and masserrors to OSW files in OpenSwathWorkflow

### ISSUE THREAD

**Issue by somnja** [OpenMS/OpenMS#4000]
For a QC tool/ python script for OpenSwathWorkflow, that plots some QC metrices from the output of 
- OpenSwathWokflow (from files in format: tsv or osw) (branch: develop)
- pyprophet (tsv or osw)
- and TRIC (tsv)

it would be great to add the parameters 'MC' (missed cleavage) and 'masserror' to the osw files. 
They seem to be currently missing from the SQlite based workflow and I can only find them in tsv or featureXML files. 

Maybe MC could be added to the FEATURE table? But i am not sure if that is the right place. 
Wouldn't know how to place the masserrors, though. And also if/ how that effects the subsequent workflow with pyprophet etc. ?

**Comment by hroest** [comment]
> Maybe MC could be added to the FEATURE table?

yes, that is one option. But it sounds more like an attribute of the peptide , feel free to add that

> Wouldn't know how to place the masserrors, though.

maybe FEATURE_MS1 would be the right place, even though that already contains VAR_MASSDEV_SCORE which is probably what you are looking for?



> And also if/ how that effects the subsequent workflow with pyprophet etc. ?

that should not be affected

**Comment by hroest** [comment]
@cbielow is that question now resolved?

**Comment by cbielow** [comment]
@oliveralka can probably help here

**Comment by oliveralka** [comment]
The question is resolved, unfortunately, the student did not proceed with this side of the project.
