### ISSUE TITLE
make CMakeList ccache compatible

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4004]
Adding 
set(CMAKE_AUTOMOC_COMPILER_PREDEFINES OFF)
to top of main CMakeList.txt seems to fix the issue

**Comment by jpfeuffer** [comment]
How did you figure that this was a problem?

Is there an explanation? I found the following, so it seems to be true:
https://github.com/ros-visualization/rviz/issues/1261

Unfortunately I never used ccache, so it would take some time until I can test potential fixes.
But if you tried it and it worked (without breaking QT-related stuff), it seems like a reasonable change.

**Comment by timosachsenberg** [comment]
I updated my ubuntu and got the same ccache error.
I added that line and everything worked like a charm... so I guess it is ok?

**Comment by jpfeuffer** [comment]
But should be fixed with CMake 3.13. Make a comment at least.

**Comment by timosachsenberg** [comment]
ok, I'll add a comment that it is only required for CMake < 3.13 .

**Comment by jpfeuffer** [comment]
What's the status on this? Did you add some lines? Is it resolved with newer cmakes?

**Comment by hroest** [comment]
@timosachsenberg fixed?
