### ISSUE TITLE
IDFileConverter mzML reindex -1 problem

### ISSUE THREAD

**Issue by Leon-Bichmann** [OpenMS/OpenMS#4011]
Hi,

I was converting idXML to pepXML using the -mz_file option to reannotate scans by nativeID.

This worked out for most scans however, for some scans the scan number is shifted by -1.

It resulted in an error when trying to generate a spectral library using spectraST:
PEPXML IMPORT: Cannot find MS2+ scan #10198 in file
>> the actual scan is #10199 in the idXML prior to conversion

Any idea why this is the case?

**Comment by Leon-Bichmann** [comment]
Some times even more scans than -1:
PEPXML IMPORT: Cannot find MS2+ scan #17186
>>  the actual scan is #17189

**Comment by timosachsenberg** [comment]
can you add some additional data e.g., the relevant sections in the idXML and pepXML file? maybe also of one scan before or after? are these merged files? there can be many reasons - need more data :P

**Comment by hroest** [comment]
best would be if you can provide a small sample file where it fails and we can reproduce the issue

**Comment by Leon-Bichmann** [comment]
Ok for example spectraST complains PEPXML IMPORT: Cannot find MS2+ Scan #10737

pepXML scanID is 10737
`        <spectrum_query spectrum="170407_AM_BD-ZH12_Lung_W_10%_DDA_#1new_400-650mz_msms50.10737.10737.2" start_scan="10737" end_scan="10737" precursor_neutral_mass="1141.5767795201" assumed_charge="2" index="10736" retention_time_sec="2900.80252651577" >
        <search_result>
                <search_hit hit_rank="1" peptide="TAIREVYQY" peptide_prev_aa="C" peptide_next_aa="M" protein="sp|O14910|LIN7A_HUMAN" num_tot_proteins="1" num_matched_ions="0" tot_num_ions="0" calc_neutral_pep_mass="1141.5767795201" massdiff="0.0" num_tol_term="1" num_missed_cleavages="0" is_rejected="0" protein_descr="Protein No. 1">
                        <search_score name="xcorr" value="1.846"/>
                        <search_score name="deltacn" value="0.348"/>
                        <search_score name="deltacnstar" value="0"/>
                        <search_score name="spscore" value="392.2"/>
                        <search_score name="sprank" value="1"/>
                        <search_score name="expect" value="0.0169"/>
                </search_hit>
        </search_result>
        </spectrum_query>
`
idXML scanID is 10738
`                <PeptideIdentification score_type="q-value" higher_score_better="false" significance_threshold="0" MZ="571.7962640319" RT="2900.80252651577" spectrum_reference="controllerType=0 controllerNumber=1 scan=10738" >
                        <PeptideHit score="0.000486751" sequence="TAIREVYQY" charge="2" aa_before="C" aa_after="M" start="62" end="70" protein_refs="PH_1179" >
                                <UserParam type="string" name="target_decoy" value="target"/>
                                <UserParam type="string" name="MS:1002258" value="10"/>
                                <UserParam type="string" name="MS:1002259" value="16"/>
                                <UserParam type="string" name="num_matched_peptides" value="15293"/>
                                <UserParam type="float" name="MS:1002252" value="1.846"/>
                                <UserParam type="float" name="MS:1002253" value="0.348"/>
                                <UserParam type="float" name="MS:1002254" value="0"/>
                                <UserParam type="float" name="MS:1002255" value="392.2"/>
                                <UserParam type="float" name="MS:1002256" value="1"/>
                                <UserParam type="float" name="MS:1002257" value="0.0169"/>
                                <UserParam type="string" name="protein_references" value="unique"/>
                                <UserParam type="float" name="COMET:deltCn" value="1"/>
                                <UserParam type="float" name="COMET:deltLCn" value="0"/>
                                <UserParam type="float" name="COMET:lnExpect" value="-4.08044165705311"/>
                                <UserParam type="float" name="COMET:lnNumSP" value="9.63515048634812"/>
                                <UserParam type="float" name="COMET:lnRankSP" value="0"/>
                                <UserParam type="float" name="COMET:IonFrac" value="0.625"/>
                                <UserParam type="float" name="MS:1001492" value="0.365087"/>
                                <UserParam type="float" name="MS:1001491" value="0.000486751"/>
                                <UserParam type="float" name="MS:1001493" value="0.00479528"/>
                        </PeptideHit>
                </PeptideIdentification>
`
mzML scan 10737
`                        <spectrum id="controllerType=0 controllerNumber=1 scan=10737" index="10736" defaultArrayLength="681">
                                <cvParam cvRef="MS" accession="MS:1000127" name="centroid spectrum" />
                                <cvParam cvRef="MS" accession="MS:1000511" name="ms level" value="1" />
                                <cvParam cvRef="MS" accession="MS:1000579" name="MS1 spectrum" />
                                <cvParam cvRef="MS" accession="MS:1000130" name="positive scan" />
                                ....
`

mzML scan 10738
`
                        <spectrum id="controllerType=0 controllerNumber=1 scan=10738" index="10737" defaultArrayLength="168">
                                <cvParam cvRef="MS" accession="MS:1000127" name="centroid spectrum" />
                                <cvParam cvRef="MS" accession="MS:1000511" name="ms level" value="2" />
                                <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" />
                                <cvParam cvRef="MS" accession="MS:1000130" name="positive scan" />
                                ....
`

**Comment by jpfeuffer** [comment]
@timosachsenberg shouldn't this be the default?

**Comment by timosachsenberg** [comment]
Yeah, probably. If it is a proper native id I would definitely say so. Maybe we were just cautious, or it did break something.
