### ISSUE TITLE
ambiguity_members column missing in PRT section of mzTab

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#4021]
According to 6.3.14 of the mzTab 1.0 specification, `ambiguity_members` in the PRT section is mandatory. But it is missing in [this example output](https://github.com/ProteomicsScripts/ProteomicsScripts/blob/master/mzTab2PRTreport/misc/example_1.mzTab) from Fido.

**Comment by jpfeuffer** [comment]
Hmm but official mzTab 1.0.0 specification example on page 14 does not list the representative protein itself in the ambiguity members, so for single proteins what should it be?
I think "null" is a valid entry then.

**Comment by lars20070** [comment]
My bad. The non-trivial entries (real protein groups) appear further down. Sorry.

**Comment by jpfeuffer** [comment]
But wait, IMHO it is inconsistent that in the non-trivial entries the representative is repeated in the ambiguity members.
