### ISSUE TITLE
[FeatureFinderRaw] features truncated [403]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#403]
Submitted by aly_st on 2012-02-27 12:02:13

FeatureFinderRaw of OpenMS 1.9 works really nice, but I have noticed that it truncates the start and end of the features.

My guess is it uses lower boundary of 'peak_per_peptide' as a criterion for the feature start detection. What we observe in our data is that sometimes the real start of the feature contains less peaks (1-2) than its most intensive region and therefore it's not recognized by FFR.

On top of that our instrument is set up to fragment the candidates quite early and often it happens that the scan even falls outside of the feature region predicted by FFR.

The example chromatogram (Orbitrap Velos) is attached.

Is there a possibility to ehnance the sensitivity of feature boundaries prediction? For example, extend the RT boundaries of the detected feature by tracking further its most intense peak(s) and allowing the less intense to be missing?

**Comment by hroest** [comment]
FeatureFinderRaw is not used any more
