### ISSUE TITLE
ConsensusID crashes with unexpected internal error

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4032]
Hi, 
here is the problem: I consistently apply IDPosteriorErrorProbability (with prob_correct flag turned off), PeptideIndexer, FalseDiscoveryRate and IDScoreSwitcher to the outputs of the OMSSAAdapter and the CometAdapter. After all that I merge them via the IDMerger.

I want to use ConsensusID next, but it works **only** for the "average" algorithm. If I run it with PEPMatrix it throws out the next message: 
Error: Unexpected internal error (the value 'Posterior Error Probability_score' was used but is not valid; Score type must be 'Posterior Error Probablity')

So, how can I remove the "_" from the parameter's name ?

**Comment by oliveralka** [comment]
You can probably use the IDScoreSwitcher again to set the score type to Posterior Error Probability.

**Comment by jpfeuffer** [comment]
Or you could also calculate the FalseDiscoveryRate after aggregating with ConsensusID (if that fits your intentions). Then you do not need any ScoreSwitcher.

**Comment by mash23** [comment]
Thank you for your responses!

I applied the  IDScoreSwitcher to the merged file and ConsensusID worked well after that. 
But now I have another problem: the FidoAdapter tool chrashes with the following:
Error: No target proteins found. Fido needs both targets and decoys.
Error: Unexpected internal error (Error: No target proteins found. Fido needs both targets and decoys.)

**Comment by jpfeuffer** [comment]
Do you have decoys in your protein database? If you just downloaded them from UniProt, there are none by default. Then you need to generate them with the DecoyDatabase tool in the very beginning.

**Comment by mash23** [comment]
Yes, I have done it in the first place.

**Comment by jpfeuffer** [comment]
Ok then they either get filtered out somewhere (do you have an IDFilter anywhere) or target-decoy annotation gets overwritten somewhere (then you need to rerun PeptideIndexer).
I would rethink the order of the tools and maybe have a look at the [tutorial workflow](https://github.com/OpenMS/Tutorials/blob/feature/Boston2018/Workflows/consensus_peptide_identification.knwf) for ConsensusID (produced with an older OpenMS version but you should only get some minor parameter warnings).

**Comment by mash23** [comment]
Thank you, the PeptideIndexer have solved the problem!

But I get some warnings in the FidoAdapter after all:
Warning: There are not enough false positives; needed 50 and was only given 2 (will proceed using largest available value).

It finished successfully but why can this be?

**Comment by jpfeuffer** [comment]
This means that in the file going into FidoAdapter, there are only two decoy proteins that can potentially be identified by spectra (which is too few to calibrate the algorithm). Can you post the StdOut of the last PeptideIndexer (right-click -> View Standard Output)? Do you have any filter in your workflow?

**Comment by mash23** [comment]
No, there are no filters. 
The output of the PeptideIndexer:

Progress of 'Loading idXML':
-- done [took 0.20 s (CPU), 0.20 s (Wall)] -- 
Using prefix decoy string 'DECOY_'
Mapping 57 peptides to 58948 proteins.
Searching with up to 3 ambiguous amino acid(s) and 0 mismatch(es)!
Building trie ... done (0s)
Progress of 'Aho-Corasick':
-- done [took 0.45 s (CPU), 0.45 s (Wall)] -- 
Merge took: 0.00 s (wall), 0.00 s (CPU), 0.00 s (system), 0.00 s (user)
Memory usage (Aho-Corasick): 2 MB (working set delta)

Aho-Corasick done:
  found 67 hits for 57 of 57 peptides.
Peptide hits passing enzyme filter: 67
     ... rejected by enzyme filter: 1
-----------------------------------
Peptide statistics

  unmatched                : 0 (0 %)
  target/decoy:
    match to target DB only: 56 (98 %)
    match to decoy DB only : 1 (1 %)
    match to both          : 0 (0 %)

  mapping to proteins:
    no match (to 0 protein)         : 0
    unique match (to 1 protein)     : 50
    non-unique match (to >1 protein): 7
-----------------------------------
Protein statistics

  total proteins searched: 58948
  matched proteins       : 10 (10 new)
  matched target proteins: 8 (80 %)
  matched decoy proteins : 2 (20 %)
  orphaned proteins      : 0 (all removed)
-----------------------------------
Progress of 'Storing idXML':
-- done [took 0.00 s (CPU), 0.08 s (Wall)] -- 
PeptideIndexer took 1.84 s (wall), 1.77 s (CPU), 0.06 s (system), 1.71 s (user).

**Comment by jpfeuffer** [comment]
Yes, as you can see there is probably something wrong. You seem to have only 57 spectra left. They get lost somewhere on the way. Since you have a FalseDiscoveryRate node somewhere: Can you set the options "add_decoy_proteins" and "add_decoy_peptides" to "true"?

**Comment by mash23** [comment]
"add_decoy_peptides" was set initially. I ran the FDR with "add_decoy_proteins" but nothing has changed.

**Comment by jpfeuffer** [comment]
Ok, one more guess: Did you set the same parameters in your search engines (same tolerance, same enzyme, ..)? Which ones do you use?

Can you also send the output of the first PeptideIndexer(s) to see how many spectra were identified by each of the search engines?

**Comment by mash23** [comment]
I use OMSSA and Comet. Both with the default parameters so they are slightly different..
The output of the PeptideIndexer for the OMSSAAdapter:

Progress of 'Loading idXML':
-- done [took 0.43 s (CPU), 0.42 s (Wall)] -- 
Using prefix decoy string 'DECOY_'
Mapping 4429 peptides to 58948 proteins.
Searching with up to 3 ambiguous amino acid(s) and 0 mismatch(es)!
Building trie ... done (0s)
Progress of 'Aho-Corasick':
-- done [took 0.69 s (CPU), 0.70 s (Wall)] -- 
Merge took: 0.00 s (wall), 0.01 s (CPU), 0.00 s (system), 0.01 s (user)
Memory usage (Aho-Corasick): 16 MB (working set delta)


Aho-Corasick done:
  found 7823 hits for 4429 of 4429 peptides.
Peptide hits passing enzyme filter: 7823
     ... rejected by enzyme filter: 553

Peptide statistics

  unmatched                : 0 (0 %)
  target/decoy:
    match to target DB only: 2131 (48 %)
    match to decoy DB only : 2284 (51 %)
    match to both          : 14 (0 %)

  mapping to proteins:
    no match (to 0 protein)         : 0
    unique match (to 1 protein)     : 2711
    non-unique match (to >1 protein): 1718

Protein statistics

  total proteins searched: 58948
  matched proteins       : 5738 (5738 new)
  matched target proteins: 2784 (48 %)
  matched decoy proteins : 2954 (51 %)
  orphaned proteins      : 5648 (all removed)

Progress of 'Storing idXML':
-- done [took 0.16 s (CPU), 0.15 s (Wall)] -- 
PeptideIndexer took 2.58 s (wall), 2.50 s (CPU), 0.08 s (system), 2.42 s (user).

The output of the PeptideIndexer for the CometAdapter:

Progress of 'Loading idXML':
-- done [took 2.90 s (CPU), 2.91 s (Wall)] -- 
Using prefix decoy string 'DECOY_'
Mapping 23595 peptides to 58948 proteins.
Searching with up to 3 ambiguous amino acid(s) and 0 mismatch(es)!
Building trie ... done (0s)
Progress of 'Aho-Corasick':
-- done [took 1.38 s (CPU), 1.39 s (Wall)] -- 
Merge took: 0.01 s (wall), 0.01 s (CPU), 0.00 s (system), 0.01 s (user)
Memory usage (Aho-Corasick): 62 MB (working set delta)


Aho-Corasick done:
  found 43797 hits for 23595 of 23595 peptides.
Peptide hits passing enzyme filter: 43797
     ... rejected by enzyme filter: 8240

Peptide statistics

  unmatched                : 0 (0 %)
  target/decoy:
    match to target DB only: 11102 (47 %)
    match to decoy DB only : 11668 (49 %)
    match to both          : 825 (3 %)

  mapping to proteins:
    no match (to 0 protein)         : 0
    unique match (to 1 protein)     : 13325
    non-unique match (to >1 protein): 10270

Protein statistics

  total proteins searched: 58948
  matched proteins       : 21238 (21238 new)
  matched target proteins: 10526 (49 %)
  matched decoy proteins : 10712 (50 %)
  orphaned proteins      : 215 (all removed)

Progress of 'Storing idXML':
-- done [took 1.32 s (CPU), 1.32 s (Wall)] -- 
PeptideIndexer took 7.15 s (wall), 7.15 s (CPU), 0.24 s (system), 6.91 s (user).


Here are idXMLs for each of the engines:
[comet.zip](https://github.com/OpenMS/OpenMS/files/3035126/comet.zip)
[omssa.zip](https://github.com/OpenMS/OpenMS/files/3035127/omssa.zip)

**Comment by mash23** [comment]
I tried another sequence of commands: Search engine -> IDPEP -> IDMerger -> ConsensusID -> PeptideIndexer -> FDR -> IDFilter.
All worked well, but what am I supposed to do next ? I applied FidoAdapter, but it crashed with
_Error: Unexpected internal error (Error: Unsuitable score type for peptide-spectrum matches detected (problem: lower scores are better).
Fido requires probabilities as scores, e.g. as produced by IDPosteriorErrorProbability with the 'prob_correct' option.)_

However it is not something unexpected as I ran IDPEP without prob_correct. But if I turn the flag on then the ConsensusID step doesn't work and throws out an error:
_Error: Unexpected internal error (the value 'Posterior Probability' was used but is not valid; Score type must be 'Posterior Error Probablity')_

**Comment by jpfeuffer** [comment]
The problem is, that Fido works on PEPs but the last "scoring" tool that you used was FDR.
You can either omit filtering before inference (strict filtering is not recommended anyway because it might be too restrictive) or use the IDScoreSwitcher (changing from q_value to PosteriorErrorProbability).

**Comment by mash23** [comment]
Well, I removed IDFilter and switched the scores after FDR and Fido worked almost well, but I still get warning: 

Warning: There are not enough false positives; needed 50 and was only given 2 (will proceed using largest available value)

**Comment by jpfeuffer** [comment]
Do you have any filter set in the FDR node? E.g. "-FDR:PSM"? And "add_decoy_proteins" is still set to true, right?

If not, I think your search engines just do not have enough overlap in their identifications so most of them get thrown out and therefore most of the proteins, too.

**Comment by mash23** [comment]
Yes, I have -FDR:PSM 0.01 and "add_decoy_proteins" and "add_decoy_peptides".

**Comment by jpfeuffer** [comment]
I think a filtering for 1% PSM FDR is too restrictive. With Bayesian methods like Fido you barely need any filtering before inference. You can filter _after_ inference on protein level and remove all peptides not belonging to the kept proteins.

**Comment by mash23** [comment]
Yes, it did the trick, now I understand.
 
Thanks a lot for your help!

**Comment by mash23** [comment]
Could you please answer one more question about ConsensusID: how does actually work the PEPMatrix algorithm ?

**Comment by jpfeuffer** [comment]
The publication is here: https://www.ncbi.nlm.nih.gov/pubmed/21644507
It combines identifications for the same spectra by different search engines
while also considering amino acid substitutions (scored based on a substitution matrix).
It works best if you have multiple candidates for a spectrum for each search engine. It only works
as well as the worst result so make sure that each of the search engines alone produce good results first.

**Comment by hendrikweisser** [comment]
Based on [this comment](https://github.com/OpenMS/OpenMS/issues/4032#issuecomment-480929694) I assume the issue has been resolved. Feel free to re-open the ticket if that's not the case.
