### ISSUE TITLE
Unintended copies due to C++ auto loop

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#4049]
a recent PR got me thinking that its very easy to write

```
for (auto var : arr)
```

instead of the intended

```
for (const auto& var : arr)
```

which leads C++ to copy every element of the array `arr` instead of an efficient iteration. I checked in OpenMS and indeed there is a bunch of instances. We should

- fix these instances
- add a style check so that new code gets a warning if it attempts to use `for (auto var : arr)`

**Comment by hroest** [comment]
we should probably run this script regularly (nightly) or even better as part of our travis run with the style checking. @cbielow @jpfeuffer would it be easy to add a regex like this one and ensure that it returns zero results:

```
$ grep -R for src/openms | grep auto | grep -v begin | grep ":" | grep -v '&' | grep -v '//' | grep "for[ ]*(" 
```

of course we would have to first weed out and annotate false positives

**Comment by jpfeuffer** [comment]
Yes that would certainly be possible. There are multiple possibilities:
1) We report every single file as part of our style build (on travis). Basically we create a shell script and create a test for each of the files.
2) We report a single test as part of the test suites. Then we can report it in Ctest.xml format or plaintext somewhere in the Jenkins/Travis console or CDash.
3) We check if one of our style checkers (cpplint, codacy) (potentially in newer versions) support checking for that.
4) We use a new style checker since I know that my Clang-Tidy complains about it.

**Comment by hroest** [comment]
I would prefer 3/4 since my regex is not perfect and relies on some assumptions (e.g. if `begin` is on the same line its more likely a construct of `for (auto it = v.begin(); it != v.end(); it++)` which should not be `const auto&` so anything that does some real static analysis would be much better. However in the meantime, I think number 2 is the best compromise, just run the regex once over all the files and report that in travis. What do you think?

**Comment by jpfeuffer** [comment]
I started on a job for clang-tidy. It is relatively slow and takes 7h with also clang-analyzer checks enabled. So it is nothing for PRs right now. We could export a compilation database from CMake, cache it and then use the clang-tidy-diff tool, that only checks the files that actually diff'ed in a PR. But that will be some work.
So, yes maybe for now we could include at least your regex on travis as a single test. I will look at that next. In the meanwhile maybe the results of clang-tidy are interesting:
https://abibuilder.informatik.uni-tuebingen.de/jenkins/job/openms_CI_jobs/job/openms_ci_clangtidy/6/clang-tidy/#categoryContent

**Comment by hroest** [comment]
> So, yes maybe for now we could include at least your regex on travis as a single test.

lets do that, after making sure the `develop` passes the test

> In the meanwhile maybe the results of clang-tidy are interesting:

looks like a lot:  Total | 19780

:-)

**Comment by jpfeuffer** [comment]
Yes, I am in the process of removing some checks. Some are definitely overly restrictive. Some mordernizers are nice-to-have but not necessary.
Most important are the clang-analyzer-*, bugprone-* and performance-* checks. I saw some false positives in conjunction with OpenMP sometimes, too, so we should deactivate it for that build.

**Comment by jpfeuffer** [comment]
There is even a "-fix" option that does automatic fixes for some of the checks.
