### ISSUE TITLE
ASAN error in AASequence

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4061]
Also: There is way too much debug output that prevents actually seeing the error.

http://cdash.openms.de/testDetails.php?test=56187641&build=307525

**Comment by jpfeuffer** [comment]
might be resolved in the newest run. Let's await the next one to confirm.

**Comment by timosachsenberg** [comment]
Just a timeout? I can reduce the number of sequences in the multi threaded test

**Comment by jpfeuffer** [comment]
Yes maybe a good idea, also bc of the debug output it generates.

**Comment by hroest** [comment]
Probably that's it because ASan is so much slower

**Comment by jpfeuffer** [comment]
@timosachsenberg Any updates? It probably was a timeout but I think a reduction in output and time is still a very good idea.

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/pull/4154
