### ISSUE TITLE
Error in FeatureLinkerUnlabeledQT

### ISSUE THREAD

**Issue by stephanieherman** [OpenMS/OpenMS#4064]
There seem to be an error in FeatureLinkerUnlabeledQT version 2.4.0. When I link my .featureXML files using v2.4.0 followed by TextExporter to convert it to a .csv file, the identifiers "MAP0" "MAP1" etc are followed by UNKNOWN instead of the file paths to the origin files. When I downgraded my OpenMS (KNIME extension) installation to version 2.3.0 running the same files, this problem was solved.

**Comment by timosachsenberg** [comment]
Hi Stephanie,
I think the semantics of origin changed at some point. Now it needs to point to the mzML file that gives rise to the quantitative value in MAP X. If you recreate the featureXML it should properly annotate the consensusXML.

**Comment by stephanieherman** [comment]
Ah I see. Upgraded to v2.4.0 again and ran a test. Yes, the semantic of origin is changed (to the raw files actually). I will reprocess my data from the beginning in v.2.4.0. Thanks!
