### ISSUE TITLE
PD isolation windows

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4075]
MzMLs exported from PD seem to wrongly annotate the isolation window offset in absolute values.
See https://gist.github.com/timosachsenberg/1dc4cb32ebf8820dbef2a7d5dd0a15b3
We could potentially correct for that in the mzML handler by checking if the isolation width roughly matches the to the offsets.

**Comment by hroest** [comment]
seems like they also interpret the standard incorrectly: https://github.com/OpenMS/OpenMS/issues/639 - we currently solve that issue by providing a "swath_windows_file" to properly annotated the windows in OpenSwath which could be a solution here too.

**Comment by timosachsenberg** [comment]
in my case I know I am dealing with DDA data so I can correct the values but would be nice to have a general solution. The mzML isolation window width cv term has the correct value so this case could be detected.

**Comment by hroest** [comment]
What if you convert the data with proteowizard instead of PD? Does it
annotate correctly?

**Comment by hroest** [comment]
PS your idea won't work for DIA data since the offsets can be large eg. 100
or more Da. But adding a flag to FileConverter may work

**Comment by hendrikweisser** [comment]
> What if you convert the data with proteowizard instead of PD? Does it annotate correctly?

Based on a single recent example, ProteoWizard seems to do it correctly.

**Comment by hroest** [comment]
@timosachsenberg @hendrikweisser any further action required here?

**Comment by hendrikweisser** [comment]
Nothing from my side.
