### ISSUE TITLE
Rename: IDFilter unique option

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4089]
We should rename the unique option in IDFilter to unique per spectrum and make it an advanced option. 

The more important option is IMHO unique_per_protein which is used much more often and having two options is really confusing.

**Comment by jpfeuffer** [comment]
Yes I agree. It could use a bigger overhaul. Also "thresh" vs "score" is very confusing.

**Comment by oliveralka** [comment]
@jpfeuffer.

unique -> tophit (do you have a better idea?) - If a peptide hit occurs more than once per peptide ID, only one instance is kept.

Was or is the thresh option in the IDFilter in use - if not we could deprecate the option since usually, you would always filter by score (i guess).
