### ISSUE TITLE
Hdf5 debug lib on Windows not built or found

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4091]
http://cdash.openms.de/viewBuildError.php?buildid=310973

Some mismatch occurs. I can investigate next time I am on the Win machines.
@hroest did you test it in debug mode too?

**Comment by hroest** [comment]
>  @hroest did you test it in debug mode too?

no, I did not

**Comment by hroest** [comment]
pretty sure this only supports release builds at the moment

https://github.com/OpenMS/contrib/blob/65374475278f7191be9dcc0be7205d5dfaeb83fe/libraries.cmake/hdf5.cmake#L72-L77

but probably `--config Debug` should do the trick?

**Comment by cbielow** [comment]
> but probably `--config Debug` should do the trick?

yes

**Comment by hroest** [comment]
> yes

ok, I can have a look at it

**Comment by hroest** [comment]
@cbielow can you look at https://github.com/OpenMS/contrib/pull/87 - does this fix the issue?
