### ISSUE TITLE
SIRIUS failed with java not available 

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4099]
SIRIUS is not able to find Java (no java installed). 
After installing java (jre) - SIRIUS it is not working, even after JAVA_HOME was set. 

I am currently no able to reproduce the issue - does anyone had this issue before? 

SIRIUS is available in THIRDPARTY as 64 bit version. JRE 64 bit has to be installed. 

SIRIUS 4.0.1 manual:
>Java Runtime Environment (JRE) version 7 or higher
installed. If you run a 64-bit operating system, you also have to install a 64-bit Java runtime environment!

> Probably, deleting the JAVA_HOME environment variable will solve the problem, see the instructions for the PATH
variable above.

**Comment by jpfeuffer** [comment]
Please double-check this problem for the release. Unfortunately it was hard to reproduce right?

**Comment by oliveralka** [comment]
I actually was not able to reproduce it at all.

**Comment by oliveralka** [comment]
Windows 10 (10.0.17763 Build 17763)
SIRIUS 4.0.1 (build 9 - sirius-win64-headless-4.0.1)

Error (reproducable):
```
C:\Users\User\Desktop\sirius-win64-headless-4.0.1>sirius-console-64.exe
This application requires a Java Runtime Environment 1.8.0 (64-bit)
```

To fix this it is important to download the "right" version of java depending on SIRIUS and the system. Here 64bit:
`jre-8u221-windows-x64`
This has to be selected form "show all available downloads" at https://java.com

In addition a path can be set to the SIRIUS executable in windows. 

Please see the SIRIUS manual:
https://bio.informatik.uni-jena.de/repository/dist-release-local/de/unijena/bioinf/ms/sirius/4.0.1/sirius-4.0.1-manual.pdf
