### ISSUE TITLE
MSGFPlusAdapter throws out an exception

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4119]
Hi, 
I run the MSGFPlusAdapter:
MSGFPlusAdapter -in input.mzML -database database.fasta -out msgf.idXML

but it crashes with:
java.io.FileNotFoundException: database.cseq (Permission denied)

What can be done to fix this ? What is it the ".cseq" file and how can I obtain it ?
I have ran the adapter on several other input files but there were no exceptions and all worked good...

**Comment by jpfeuffer** [comment]
Hi,

the ".cseq" file is an index file that is built on the first run by MSGF+ itself and reused in future runs.
Problems were reported with parallel runs but only if the index was not created yet.
Did you check that you have permissions in the folder of database.fasta and enough space?

**Comment by mash23** [comment]
Thank you for the response!
I copied the database to the folder I'm sure I have permissions to. Now it gives another exception:

java.lang.NullPointerException

**Comment by jpfeuffer** [comment]
Great. Is there more info about the exception or just that line?
We heard about exceptions when the database contained unexpected characters for example.

**Comment by timosachsenberg** [comment]
Please also report that to the MSGF+ github repository. Maybe they include more detailed error messages in the future.

**Comment by mash23** [comment]
Here is the whole output: 

MS-GF+ Release (v2019.02.28) (28 February 2019)
Loading database files...
Warning: Sequence database contains 22 counts of letter 'B', which does not correspond to an amino acid.
Warning: Sequence database contains 18 counts of letter 'U', which does not correspond to an amino acid.
Warning: Sequence database contains 5646 counts of letter 'X', which does not correspond to an amino acid.
Warning: Sequence database contains 28 counts of letter 'Z', which does not correspond to an amino acid.
Loading database finished (elapsed time: 5.05 sec)
Reading spectra...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/home/mapopova/Downloads/MSGF/MSGFPlus.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.NullPointerException
	at edu.ucsd.msjava.msutil.Spectrum.getCharge(Spectrum.java:125)
	at edu.ucsd.msjava.msutil.SpecKey.getSpecKeyList(SpecKey.java:91)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:238)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:109)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:57)

**Comment by jpfeuffer** [comment]
Ah. Yes, we had that before. I think it was forwarded to the MSGF developers.
See https://github.com/OpenMS/OpenMS/issues/3576

**Comment by jpfeuffer** [comment]
I think the most likely reason is that your spectra are still in profile mode. Then you need to centroid them during conversion with msConvert or our PeakPickers.

**Comment by mash23** [comment]
I have already centoided it using PeakPickerWavelet. I applied OMSSA on the data and it worked well. But doesn't work with MSGF+.

**Comment by jpfeuffer** [comment]
I think unfortunately our PeakPickers do not add a charge. You would need to use our HighResPrecursorMassCorrector for this, which does a reassignment based on the MS1 scan.
