### ISSUE TITLE
ConsensusID crashes with an exception

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4122]
Hi everyone, 
I am trying to apply ConsensusID to the merged results of OMSSAAdapter, CometAdapter and MSGFPlusAdapter but it crashes:
Error: Unexpected internal error (the value 'expect' was used but is not valid; Score type must be 'Posterior Error Probablity')

I have three different projects and two of them have this problem at this step. The third doesn't have it but there is no difference between the pipelines..

**Comment by jpfeuffer** [comment]
If you want to merge different search engines you need to convert their scores to probabilities first,
e.g. by using IDPosteriorErrorProbability or (more robust) Percolator.
Not sure why it ever worked for some of your pipelines.
