### ISSUE TITLE
Circular dep hell while installing on ubuntu18.04

### ISSUE THREAD

**Issue by svaksha** [OpenMS/OpenMS#4124]
Hi,

Is there a .deb for installing OpenMS on Ubuntu-18.04? I installed the deps with: 

```
   sudo apt-get -y install build-essential cmake autoconf patch libtool git automake
    sudo apt-get -y install qtbase5-dev libqt5svg5-dev
    sudo apt-get install -y libeigen3-dev libsqlite3-dev libwildmagic-dev libboost-random1.62-dev libboost-regex1.62-dev libboost-iostreams1.62-dev libboost-date-time1.62-dev libboost-math1.62-dev libxerces-c-dev libglpk-dev zlib1g-dev libsvm-dev libbz2-dev seqan-dev coinor-libcoinmp-dev

``` 

but hit a circular dependency hell with the libopenms /TOPP installation with the .deb file,

```

$ sudo dpkg -i openms_2.4.0-1_all.deb 
Selecting previously unselected package openms.
(Reading database ... 231125 files and directories currently installed.)
Preparing to unpack openms_2.4.0-1_all.deb ...
Unpacking openms (2.4.0-1) ...
dpkg: dependency problems prevent configuration of openms:
 openms depends on libopenms2.4.0 (>= 2.4.0-1); however:
  Package libopenms2.4.0 is not installed.
 openms depends on topp (>= 2.4.0-1); however:
  Package topp is not installed.

dpkg: error processing package openms (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Errors were encountered while processing:
 openms

```

Tried to fix the unmet dependencies but an update/upgrade uninstalls OpenMS. 

Is there a way to overcome this deps error without having to compile from source? 

Thanks In Advance.

**Comment by jpfeuffer** [comment]
Hi!

I don't think it's a circular dependency. The openms package is the parent package and depends on its two components, the library (libopenms) and the tools/binaries (topp).
Can you try to get those packages, too and install them first?

**Comment by svaksha** [comment]
I did and this was the error:

```
$ sudo apt-get -y install libopenms2.4.0 
Package libopenms2.4.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

**Comment by jpfeuffer** [comment]
Ah no, I mean the same way you tried to install the "openms" package via dpkg.
I assume you downloaded it from the ubuntu repository from another distro version?
Just download the deb packages for the "libopenms" and the "topp" package, too.

**Comment by svaksha** [comment]
Hi @jpfeuffer, 
Do you have a link for the .deb files for "libopenms" and "topp"? Debian does not have stable versions, just 'testing' : https://packages.debian.org/buster/libopenms2.4.0, so I edited the /etc/apt/sources.list for non-free testing packages but could not locate both packages.

**Comment by jpfeuffer** [comment]
Hmm yes I found them in the Ubuntu repositories here:
https://packages.ubuntu.com/cosmic/libopenms2.4.0
Same for topp.

But: I now doubt that this is an efficient solution. Different Ubuntu versions use different versions of the dependencies so you have to somehow get newer versions of boost anyway. Also the Ubuntu maintainers seem to have openms split up further (openms-common etc.) so you need to install all of this too.

Further Options:
- Build yourself (it's easier than it looks)
- Try our own Debian package (I think it is for 16.04 though) here: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/2.4.0/
- use a Docker container (you need to setup xforwarding if you want to use the GUI)
- use the python based package manager Bioconda (I am not sure if they package our GUI programs though)

**Comment by svaksha** [comment]
On Fri, May 24, 2019 at 10:09 AM jpfeuffer <notifications@github.com> wrote:
>
> Hmm yes I found them in the Ubuntu repositories here:
> https://packages.ubuntu.com/cosmic/libopenms2.4.0
> Same for topp.

but, as suspected, not for bionic:
https://packages.ubuntu.com/bionic/libopenms2.4.0
Ditto for topp.

>
> But: I now doubt that this is an efficient solution. Different Ubuntu versions use different versions of the dependencies so you have to somehow get newer versions of boost anyway. Also the Ubuntu maintainers seem to have openms split up further (openms-common etc.) so you need to install all of this too.
>

No, the split is from Debian (seen in jessie version:
https://packages.debian.org/jessie/openms-common)

Ubuntu is Debian-based, so I dont think its worth the trouble to split
and maintain niche software programs unless the core-devs are also the
long term DDs (read, maintainers) or its a highly used package.  And,
if there is no Debian package it is rare to see it in Ubuntu unless
someone (usually a core-dev) does a PPA (which also needs to be
maintained so a ppa is not very reliable between ubuntu versions) .


> Further Options:
>
> Build yourself (it's easier than it looks)

Sigh...I dont know if its worth the trouble as I just need it for
reading a single file. Fighting with the base system for one-time use
seems like a huge time-sink and I have been at this since yesterday.

> Try our own Debian package (I think it is for 16.04 though) here: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/2.4.0/

I am using 18.04 (LTS) so it would be nicer if you had an LTS tested
version for Ubuntu. I could not find one for 18.04 and dont want to
upgrade to 18.10 as it would break other packages that only support
LTS versions.

PS: A friendly suggestion: In future, please support and test your
software on the LTS versions and not the point releases in Ubuntu as
you would need to provide support over a shorter (9-month) release
cycle) while Ubuntu LTS has longer support - 2 to a max of 5 years for
packages, deps included.

> use a Docker container (you need to setup xforwarding if you want to use the GUI)
> use the python based package manager Bioconda (I am not sure if they package our GUI programs though)
>

I can do without the GUI as I just need to extract some information -
if there is a command line way to parse the *.raw files for info, its
fine too.

॥ SVAKSHA ॥ स्वक्ष ॥ Bio(& blog):: http://svaksha.com/pages/BIO ॥ T::
https://twitter.com/svaksha ॥ Git:: https://svaksha.github.io,
https://gitlab.com/svaksha ॥

**Comment by jpfeuffer** [comment]
Hi @svaksha !
Sorry to hear that it did not work.

> No, the split is from Debian (seen in jessie version:
> https://packages.debian.org/jessie/openms-common)

Ah, I did not know that the split was introduced by Debian and I know that it probably makes sense to do so but I just wanted to say that it will be cumbersome to install without automatic dependency resolution.

> Ubuntu is Debian-based, so I dont think its worth the trouble to split
> and maintain niche software programs unless the core-devs are also the
> long term DDs (read, maintainers) or its a highly used package.  And,
> if there is no Debian package it is rare to see it in Ubuntu unless
> someone (usually a core-dev) does a PPA (which also needs to be
> maintained so a ppa is not very reliable between ubuntu versions) .

Indeed it would preferable to have packages for all LTS versions but we currently do not have the manpower to provide Debian-conform packages by ourselves. 

> I am using 18.04 (LTS) so it would be nicer if you had an LTS tested
> version for Ubuntu. I could not find one for 18.04 and dont want to
> upgrade to 18.10 as it would break other packages that only support
> LTS versions.

However, we do provide a self-made debian package for non-system-wide installation on 16.04, which is LTS, too (right?). We will try to improve on that and add newer versions in the future, too.

> I can do without the GUI as I just need to extract some information -
> if there is a command line way to parse the *.raw files for info, its
> fine too.

It was important that you wrote that since we do not support parsing of Raw files on Linux. Vendor file formats like Raw files require the use of the vendors libraries which were until recently only available only on Windows. Nowadays you can do it on Linux via wine or Docker containers (https://hub.docker.com/r/chambm/pwiz-skyline-i-agree-to-the-vendor-licenses) or in the case of Thermo Raw files with the parser here (which depends on mono):
https://github.com/compomics/ThermoRawFileParser

**Comment by svaksha** [comment]
Hi @jpfeuffer,

> Indeed it would preferable to have packages for all LTS versions but we currently do not have the manpower to provide Debian-conform packages by ourselves.

Ofcourse, I understand that FOSS is a lot of work :-)


> However, we do provide a self-made debian package for non-system-wide installation on 16.04, which is LTS, too (right?). We will try to improve on that and add newer versions in the future, too.

Thanks, I hope there is one for Ubuntu 18.04, or perhaps 20.04 in less
than a year ;-)

> It was important that you wrote that since we do not support parsing of Raw files on Linux.

Oh, I didnt know that. A search for reading  RAW files led me to
OpenMS. Sorry for all the noise.


> Vendor file formats like Raw files require the use of the vendors libraries which were until recently only available only on Windows. Nowadays you can do it on Linux via wine or Docker containers (https://hub.docker.com/r/chambm/pwiz-skyline-i-agree-to-the-vendor-licenses) or in the case of Thermo Raw files with the parser here (which depends on mono):
> https://github.com/compomics/ThermoRawFileParser
>

Thanks for that link.

॥ SVAKSHA ॥ स्वक्ष ॥ BIO: http://svaksha.com/pages/BIO ॥ PUB:
http://svaksha.com/pages/PUB ॥ Git:: https://svaksha.github.io,
https://gitlab.com/svaksha ॥ T:: https://twitter.com/svaksha ॥
