### ISSUE TITLE
OpenSwathWorkflow runs slowly

### ISSUE THREAD

**Issue by nathemie** [OpenMS/OpenMS#4130]
Hi, when running this version of OpenSWATH（Version: 2.4.0-develop-2019-04-21 Apr 23 2019, 06:48:20, Revision: 968846f, we found it is super slow in searching one file: more than a day comparing with the older version 2 hours, though we can still have result after more than twenty hours. The running code is:
`OpenSwathWorkflow -in xxxxxx.mzXML -tr xxxx.PQP -tr_irt iRT_library.TraML -out_osw test.osw -threads 20 -min_upper_edge_dist 1 -mz_extraction_window 30 -mz_extraction_window_unit ppm -mz_extraction_window_ms1 20 -mz_extraction_window_ms1_unit ppm -mz_correction_function regression_delta_ppm -use_ms1_traces -irt_mz_extraction_window 50 -irt_mz_extraction_window_unit ppm -rt_extraction_window 600 -RTNormalization:estimateBestPeptides -RTNormalization:alignmentMethod lowess -RTNormalization:outlierMethod none -Scoring:stop_report_after_feature 5 -Scoring:TransitionGroupPicker:compute_peak_quality false -Scoring:Scores:use_ms1_mi -Scoring:Scores:use_mi_score  -batchSize 1000 -ms1_isotopes 3`

 We suspected it would be the number of threads and file formatting issues and have changed the parameters of number of threads  20, 30, 40 and input file format (gz, mzXML) but it was still not speeding up.

We are running on the clusters and normally it should have occupied all the available 8-core CPU 800% but it was only used one core of it. Could it also be the problem of physical memory? 97% of the memory was used.
![image](https://user-images.githubusercontent.com/51101922/58444046-bb25c380-8128-11e9-9ae0-e6818d2d3dba.png)

**Comment by hroest** [comment]
thanks for reporting this, it is odd and not what I would expect. It looks like you are not actually at full CPU load, maybe this is an IO issue? Are you using `-readOptions cacheWorkingInMemory -tempDirectory $TMPDIR` - what `readOptions` are you using?

**Comment by nathemie** [comment]
Thanks for  fast   reply. We used the default setting for `-readOptions` as `normal`. Will switching on the `cache` options accelerate the computation ? It seems this will use the slower hard disk instead of faster accessed memory or it uses more real ‘cache memory' for computation?
On the other hand, could it be the limitation of memory space? We have used up 97% memory out of 128GB. How much memory is `OpenSwathWorkflow` required and recommended?

**Comment by hroest** [comment]
>  On the other hand, could it be the limiting memory space? We have used up 97% memory out of 128GB. How much memory is `OpenSwathWorkflow` required and recommended?

yes, that clearly seems to be the problem. If you load all the data into memory then you start swapping and all data acess becomes IO bound and very slow. How much memory you require depends on the files that you have, in general we dont recommend to use `normal` exactly to avoid this problem but suggest `cacheWorkingInMemory` : this option will cache all data to disk and then load one SWATH at a time in memory which means that for each thread you only have 1/32 of all data in memory. All threads share a single MS1 representation so your memory requirement is = `MS1_size + n * MS2_size` where `n` is the number of threads. For us usually 24 GB is sufficient.

**Comment by nathemie** [comment]
We tested with `cacheWorkingInMemory`, however, it doesn't help much and is not compatible for large scale analysis. We have to change to the older version OpenSWATH or other software solutions. Thanks for the reply

**Comment by hroest** [comment]
> We tested with `cacheWorkingInMemory`, however, it doesn't help much and is not compatible for large scale analysis.

is there a timeframe / commit you can identify where the problem first occurs?

**Comment by hroest** [comment]
@nathemie is this fixed with https://github.com/OpenMS/OpenMS/pull/4172 ? I think one of the main differences was that you are using MS1 isotope traces which used to be slow in previous OpenSWATH versions.
