### ISSUE TITLE
TOPPView 3D view crashes when using X over ssh [414]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#414]
Submitted by hroest on 2012-03-23 16:35:34

TOPPView works perfectly fine with X over ssh, one can view 2D maps, 1D spectra and even apply TOPPAS tools. However the 3D view crashes when using TOPPView over ssh [1]. This was done with revision 9574.

This is probably not a usecase that many people encounter but it's still annoying for those that do and I may not even be a problem of OpenMS. However it is especially annoying because everything else works so well and can be used.

[1]

$ /opt/imsb/hroest/openms/OpenMS/bin/TOPPView /opt/imsb/hroest/openms/OpenMS/source/TEST/data/MzMLFile_1.mzML 
virtual bool OpenMS::Spectrum3DCanvas::finishAdding_()
Segmentation fault (core dumped)

-------------------------------------------------
Commented by cbielow on 2012-03-28 10:07:33:
mmhh I was about to close this ticket, but then found this:

http://www.qtforum.org/article/34954/qglwidget.html

and

http://www.qtcentre.org/archive/index.php/t-35638.html

I unfortunately cannot test the proposed solution as my client (XMing) gives:
Xlib:  extension "NV-GLX" missing on display "localhost:10.0".

right of the start of TOPPView (so OpenGL is seems not an option at all) and then crashes on 3D View with
TOPPView: Fatal IO error: client killed

**Comment by hendrikweisser** [comment]
I've just tested this with a current OpenMS and it worked just fine - i.e. no crash when using the 3D view in TOPPView via "ssh -X" (on Ubuntu 12.04). Perhaps this can be closed?

**Comment by hroest** [comment]
+1
We have lots of old tickets where we don't really know whether the problem
still exists

sent from my smartphone -- you may keep any typos you find.
