### ISSUE TITLE
PSMFeatureExtractor crashes 

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#4140]
Hello; PSMFeatureExtractor crashes for a search with msgf+; no ,modifications other iodoacteamide. Based on some other reports, I am have also tried to include IDFilter and other measures to prevent that non-mapped peptides from PeptideIndexer are piped to PSMFeatureExtractor. Output / error message is:
Loading input file: /tmp/20190531_152416_12646_1/msgf-percolator_idxml-input/005_IDFilter/out/java.idXML
MS-GF+ PSM with missing NumMatchedMainIons skipped.
Error: File not found (the file '/tmp/20190531_152416_12646_1/msgf-percolator_idxml-input/006_PSMFeatureExtractor/out/java.unknown' could not be found)
<MS-GF+ PSM with missing NumMatchedMainIons skipped.> occurred 4 times

Thanks for support!

**Comment by MatthewThe** [comment]
It seems something is going wrong with the file extension. From the error message it seems it tries to look for the file "java.unknown" instead of "java.idXML". I think we encountered and solved this issue before, but apparently it returned. I'll have to check if somebody made some changes to the interface that could have caused this.

**Comment by MatthewThe** [comment]
I can see there have been some changes to the file interface of PSMFeatureExtractor but I don't see an obvious culprit. Could you provide a workflow where you encounter this problem?

**Comment by oliverschilling** [comment]
Hello, here is a dropbox link to the workflow, idxml file, etc. Please let me know if anything else is needed or if there is an issue with the link.
https://www.dropbox.com/s/nbmrsjkv3hq9frg/Percolator-test_PSMFeature-Extractor.zip?dl=0
