### ISSUE TITLE
rt and dm columns for percolator

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#4141]
Hello, when using PercolatorAdapter with the option for "description of correct features", the following error message appears: ERROR: Could not find column with name "rt"/"retentiontime" and "dm"/"deltamass" necessary for the calculation of DOC features.

How can these columns be added? I tried IDFileConverter with an additional mzML input, but to no avail.

Thanks for any support!

**Comment by MatthewThe** [comment]
The columns should be added by percolator itself (not even by the PercolatorAdapter) so it's very puzzling that it doesn't work. Do you have the stderr output of the percolator run that ends with the error message?

**Comment by oliverschilling** [comment]
Dear Matthew
[percolator-problems.zip](https://github.com/OpenMS/OpenMS/files/3268669/percolator-problems.zip)

, thanks for the response. I have attached the (1) the toppas workflow; (2) the idxml file; (3) the entire toppas log containing all output and error messages (all together in one zipped file). I hope these files provide the required information; please let me know if this does not suffice. 

Thanks

Oliver

**Comment by MatthewThe** [comment]
Thanks for the files, I got myself confused the columns should be added by PercolatorAdapter and they currently are indeed not added. It should not be too hard to do this, I will try to create a pull request in the next few days.

**Comment by oliverschilling** [comment]
Thanks a lot; highly appreciated!
