### ISSUE TITLE
Identified MS2 spectra = 0%

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4149]
Hi everyone! 
I am trying to restore the protein sequence from the MS data. Here is the project I use :
https://www.ebi.ac.uk/pride/archive/projects/PXD004971

I consiquently applied NoiseFilterGaussian, BaselineFilter and PeakPickerWavelet and next I use OMSSAAdapter to identify peptides but it gives me a bad result: 
Statistics:
  identified MS2 spectra: 3 / 505 = 0% (with e-value < 1000)

What can I do to increase the number of identified spectra ?

**Comment by jpfeuffer** [comment]
Hi!

1) I think for a Thermo Scientific LTQ FT Ultra you could use a PeakPickerHiRes. Or even enable peakpicking during conversion with msConvert.
2) If you do not see heavy noise in the data, I would maybe skip the two Filters first.
3) The dataset is labelled with a variable modification that is also seen in the fragment scans. You need to include this modification in your OMSSA search. It seems that this carbene modification is not in unimod so you have to create an entry by yourself.
4) This dataset is analysing mutants, you have to include the mutations in your fasta database, too.
