### ISSUE TITLE
CometAdapter crashes with an error

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4151]
Hi everyone!

I use CometAdapter like this:
CometAdapter -in .mzML -database .fasta -out .idXML -default_params_file comet.params

Here is the whole output: 

Comet is writing the default parameter file...
Executing: comet.exe
Executed comet.exe successfully!
Warning: Could not determine format of input file 'comet.params'!
Progress of 'loading spectra list':
-- done [took 0.17 s (CPU), 0.18 s (Wall)] -- 
Executing: comet.exe
Executed comet.exe successfully!
Error: File not found (the file '/tmp/20190614_155639_bison_1787_2/result.pep.xml' could not be found)

Could you tell me what is result.pep.xml and how can I avoid the problem ?

**Comment by jpfeuffer** [comment]
Hi!
How did you generate your comet.params file?
If you are unsure, leave the parameter empty, the adapter will generate one for you.

And did you give actual filepaths for -in and -out or just the endings? You need to specify which files to use. The type is determined automatically.

**Comment by mash23** [comment]
For the parameters -in and -out I write the full path, just wrote it here in a short form.
If I leave the parameter -default_params_file empty, I get an error:

Comet is writing the default parameter file...
Executing: comet.exe
Executed comet.exe successfully!
Progress of 'loading spectra list':
-- done [took 0.18 s (CPU), 0.18 s (Wall)] -- 
FATAL: External invocation of comet.exe failed. Standard output and error were:

<Executing: comet.exe> occurred 2 times
 Comet version 2018.01 rev. 2

 The comet.params file is from version 2016.01
 Please update your comet.params file.  You can generate
 a new parameters file using "comet -p"

1
CometAdapter took 0.39 s (wall), 0.32 s (CPU), 0.02 s (system), 0.30 s (user).

**Comment by jpfeuffer** [comment]
I see. It seems like you use your own version of Comet? In this case you have to give the version in the comet_version parameter. In your case "2018.01 rev. 2".

**Comment by mash23** [comment]
It doesn't make any better..

**Comment by jpfeuffer** [comment]
Closing due to lack of further info. Feel free to reopen.
