### ISSUE TITLE
Clean-up IDFilter params

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4156]
Hello everyone, 

I had some problems running the IDFilter due to its abundance on parameters with their respective sometimes cryptic explanation. 

For example, the "unique" option, which I think should always mean "unique per protein". Seems to remove duplicate peptide hits for a peptide identification (not sure how often that happens).

Additional the "thresh" and "score" possibility, where usually only "score" is used to filter based on an FDR threshold. 

It would be great if we could collect some ideas, which params are usually used and which should be renamed and marked as advanced or even be deprecated. Please let me know what you think.   

Related see #2464, #4089

**Comment by hroest** [comment]
there is clearly too many options in the regular output: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_IDFilter.html

also the online documentation could be improved using a better description or even potentially a few example use cases of how this could be used to achieve a certain result

**Comment by hroest** [comment]
Btw: I just opened https://github.com/OpenMS/OpenMS/pull/4157 so that now a link to the online docu should appear to help people with the plethora of options

**Comment by hroest** [comment]
@oliveralka I started some cleanup here: https://github.com/OpenMS/OpenMS/tree/feature/idfilter_params

This boils down the parameters a lot, I think we could also have the whitelist/blacklist parameters go. What do you think?

**Comment by jpfeuffer** [comment]
I'm all up for clean up but I would probably keep a white/black listing functionality. If not in Idfilter, then in a separate tool. I've seen quite some people using it.
We could rename it to "match_reference" and have a bool for include or exclude to trim it down a little.
