### ISSUE TITLE
--help and --helphelp

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#4158]
Just a question: why do we have double dash for help / helphelp options and single dash for everything else? Eg why dont we use `-help` and `-helphelp` for all tools to be consistent? Are there any reasons why we dont migrate to the single dash solution?

**Comment by timosachsenberg** [comment]
@cbielow do you know sth about that?

**Comment by cbielow** [comment]
historically, I guess.
There seems to be no convention (especially across platforms), but looking at posix, it seems that single-dash options are usually also single-character (with exceptions), and double-dash are more verbose equivalents (see https://askubuntu.com/questions/492544/what-are-the-differences-between-and-in-commands).
So technically, we should do `-h` and `--help`, but that would wreak havoc on our INI generation, so if we stick with one of both, `--help` is actually better, but somewhat inconsistent with the other flags.
(That is not to say we should use double-dash everywhere).

**Comment by Ozzard** [comment]
--help follows the conventions of pretty much every other command-line application out there, and is thus discoverable for people like me who are new to OpenMS but have 30+ years experience of command-line applications.  Given that OpenMS otherwise uses non-standard options, *please* do not remove your only discoverable way of finding out that the other options aren't standard.  Please keep --help.

**Comment by hroest** [comment]
> --help follows the conventions of pretty much every other command-line application out there, and is thus discoverable for people like me who are new to OpenMS but have 30+ years experience of command-line applications. Given that OpenMS otherwise uses non-standard options, _please_ do not remove your only discoverable way of finding out that the other options aren't standard. Please keep --help.

Good point, I agree that we should probably have used double dash for all out options to start with and not used single dashes. 

Also, it seems that `--help` does not work everywhere, e.g. for `OpenMSInfo` it does not work. Also, for most tools `TOPPTool` and `TOPPTool --help` are identical.

**Comment by cbielow** [comment]
> Also, for most tools `TOPPTool` and `TOPPTool --help` are identical.
Not quite. The return code is 6 (error) and 0 (success) :)

OpenMSInfo does not obey `--help` because its not a TOPP tool (since its not meant for being executed in a pipeline) -- we could change that, but there is little benefit.
