### ISSUE TITLE
Misleading MS2 precursor m/z information

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#4168]
It's a commonly observed problem in DDA experiments that MS2 precursor m/z values can differ from the monoisotopic m/z values of the corresponding peptides (or RNA oligonucleotides) because the precursors can get selected from higher-intensity isotopologue peaks. So it's quite normal to see precursor m/z values that are higher than the monoisotopic m/z values, and there are methods to correct for that (e.g. HighResPrecursorMassCorrector or the "precursor:isotopes" parameter in NucleicAcidSearchEngine).

However, I've now observed cases where the precursor m/z values (as represented in OpenMS) are *lower* than the monoisotopic m/z values, and are thus moved outside the boundaries of the chromatographic peak (feature). See the screenshot from TOPPView below, where the black MS2 indicators are below the feature in the main window; some precursor locations don't even have a data point (peak). The data is from a Thermo Q Exactive HF, centroided and converted to mzML with ProteoWizard.

![TOPPView_precursor_problem](https://user-images.githubusercontent.com/2251068/60273649-7b502880-98ee-11e9-882a-d26677863a8c.png)

Looking in the mzML file, the problem seems to be due to conflicting/misleading information in the precursor section:
```
          <precursorList count="1">
            <precursor spectrumRef="controllerType=0 controllerNumber=1 scan=5762">
              <isolationWindow>
                <cvParam cvRef="MS" accession="MS:1000827" name="isolation window target m/z" value="763.83056640625" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                <cvParam cvRef="MS" accession="MS:1000828" name="isolation window lower offset" value="0.699999988079" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                <cvParam cvRef="MS" accession="MS:1000829" name="isolation window upper offset" value="0.699999988079" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
              </isolationWindow>
              <selectedIonList count="1">
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="763.45484085234" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                  <cvParam cvRef="MS" accession="MS:1000041" name="charge state" value="8"/>
                  <cvParam cvRef="MS" accession="MS:1000042" name="peak intensity" value="2.3541556e07" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/>
                </selectedIon>
              </selectedIonList>
              <activation>
                <cvParam cvRef="MS" accession="MS:1000422" name="beam-type collision-induced dissociation" value=""/>
                <cvParam cvRef="MS" accession="MS:1000045" name="collision energy" value="22.0" unitCvRef="UO" unitAccession="UO:0000266" unitName="electronvolt"/>
              </activation>
            </precursor>
          </precursorList>
```

In particular, there are two different m/z values in "isolationWindow" ("isolation window target m/z") and in "selectedIon" ("selected ion m/z"). OpenMS apparently reads the precursor m/z from "selectedIon", but the centre of the isolation window from which ions were fragmented is given by the other value. I assume there's some kind of mechanism in the (Thermo) instrument software that attempts to infer the monoisotopic m/z (but gets it wrong in some cases) and writes that into "selectedIon".

The question is how OpenMS should deal with this. Is it intentional that we get the precursor information from "selectedIon", not "isolationWindow"? Should that be changed? Is there a way to get the other m/z value in OpenMS code?

**Comment by timosachsenberg** [comment]
Can you check what the ThermoRawFileConverter puts there? It uses a more recent thermo library afaik

**Comment by hendrikweisser** [comment]
ThermoRawFileConverter writes the same information (two different m/z values).

**Comment by timosachsenberg** [comment]
In pwiz filtering methods, the default seems to be indeed "selected ion m/z"

**Comment by hendrikweisser** [comment]
@timosachsenberg:
I don't understand - the default for what?

**Comment by timosachsenberg** [comment]
I just found it used in some filtering methods in the github repo.
I think the way we use it now is probably correct and in some cases there is a wrong annotation by the Thermo Firmware. See e.g.:
https://github.com/ProteoWizard/pwiz/commit/21348409662a2c3c8c48958b81f3a9ecca2a1fec#diff-aa2fb548073be2aff4402c56522f0a9aR499

**Comment by hendrikweisser** [comment]
> I think the way we use it now is probably correct

I'm not so sure and would like to hear some more opinions on this, if possible.

For one, it depends on what we use the information for. For example, when you draw the precursor isolation window in the "Identification view" in TOPPView, I'm pretty sure you want to draw it around the "isolation window target m/z" value (not the way it's done now).

If you run a search, maybe you'd prefer to use the "selected ion m/z" value, in the hope that it gets the monoisotopic m/z value correct more often than not.

Second, there's the question of consistency. Looking through the OpenMS test and example files, I haven't found any yet where the two m/z values differ. However, there are some that only have "isolationWindow" information, no "selectedIon", in which case I assume the precursor m/z value is read from there (although I haven't checked in the code).

In any case, we should expose both values somehow - at least if they're different.

**Comment by hendrikweisser** [comment]
Relevant code for reading mzML is here:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp#L1651-L1657

**Comment by hendrikweisser** [comment]
There's an existing test file that has cases of different m/z values in "isolationWindow" and "selectedIon":
https://raw.githubusercontent.com/OpenMS/OpenMS/develop/src/tests/topp/OpenPepXLLF_input2.mzML

**Comment by timosachsenberg** [comment]
you could add a peak file option to toggle storing these values in a meta value:
pec_.getPrecursors().back().setMetaValue(...)

**Comment by hendrikweisser** [comment]
Wouldn't a member variable be better? It seems quite fundamental to me that you can actually have two different precursor m/z values with slightly different meanings. A meta value isn't very obvious.

**Comment by timosachsenberg** [comment]
I personally only care about precursor m/z and start+end of the isolation window. And that's what I would like to expose primarily through the API. How this is stored by different instrument vendors and what kind of firmware specific problems seems more like an implementation detail. But I would like to hear other opinions ...

**Comment by hroest** [comment]
@timosachsenberg @hendrikweisser also for SWATH-MS it makes more sense to report to report start+end of isolation window; for SWATH-MS there is no "selected ion" since we dont select a single ion but multiple ions. So we would like to display the start/end of the window

**Comment by hendrikweisser** [comment]
> I personally only care about precursor m/z and start+end of the isolation window.

You still have the problem that start/end of the isolation window are currently expressed relative to the precursor m/z (see e.g. #4075). If that m/z value is off, your isolation window will be wrong - which is exactly what I currently see in the "Identification view" in TOPPView.

In my opinion it would be better to store absolute values for the isolation window start/end to avoid this problem. That way, we could properly capture both the "selected ion" and "isolation window" m/z information, even if they differ.

**Comment by hroest** [comment]
> In my opinion it would be better to store absolute values for the isolation window start/end to avoid this problem

Unfortunately that is not what the standard says, but you can easily calculate this from the center and start/end

> That way, we could properly capture both the "selected ion" and "isolation window" m/z information, even if they differ.

maybe I misunderstood your comment above, but isnt this exactly what you are suggesting as you say the information

"isolation window target m/z" +/- "isolation window lower offset" 

would be correct? and we just ignore the "selected ion" ?

**Comment by hendrikweisser** [comment]
> Unfortunately that is not what the standard says, but you can easily calculate this from the center and start/end

The standard is for mzML. We are free to deviate from it in our data model if we so choose. (In fact, judging by how often the absolute values are used in mzML contrary to the standard, doing it that way may actually be more intuitive.)

> and we just ignore the "selected ion" ?

The "selected ion" information is probably useful, so I wouldn't just ignore it. (In NucleicAcidSearchEngine, it actually works well for database searching if we include a negative "isotope offset". However, I haven't compared it to what would happen if we used the "isolation window" m/z value for the precursor instead.)

For me, either of the following solutions would be desirable (and each has some pros and cons):
1. Use absolute values for isolation window start/end (calculated from the "isolation window target m/z" value), and keep storing the "selected ion m/z" (if available) as the precursor m/z.
2. Add a member `window_center_` (or something like that) and corresponding `get/setIsolationWindowTargetMZ` functions to `Precursor` to specifically store the "isolation window target m/z", and keep storing the "selected ion m/z" (if available) as the precursor m/z.
3. Always store the "isolation window target m/z" as the precursor m/z, and add a new member (or meta value?) for the "selected ion m/z".

**Comment by timosachsenberg** [comment]
I would vote for 2.

**Comment by hendrikweisser** [comment]
Based on a comment from Timo above, I thought of another alternative:
4. Add a peak file option to decide which value to use preferentially as the precursor m/z; if the other one differs, store it in a meta value. (What should the default be - "isolation window target m/z" for consistency or "selected ion m/z" for backwards compatibility?)

The problem with options 1 and 2, as I now realise, is that our implementations of all raw data file formats would have to be changed/extended to support them. That's not something I want to do.

**Comment by timosachsenberg** [comment]
I still think that "selected ion m/z" is more often the correct precursor m/z so it's not only for backward compatibility
