### ISSUE TITLE
Support for mzTab-M for metabolomics

### ISSUE THREAD

**Issue by nilshoffmann** [OpenMS/OpenMS#4169]
In light of the release of mzTab-M for metabolomics, is there a plan or timeline to support it in OpenMS as an output format for metabolomics analyses?

https://github.com/HUPO-PSI/mzTab
https://hupo-psi.github.io/mzTab/2_0-metabolomics-release/mzTab_format_specification_2_0-M_release.html

**Comment by oliveralka** [comment]
Hi Nils,

thanks for asking! There is a plan for supporting mztab-m in the future in OpenMS. Unfortunately, we currently are not able to give you a proper estimate on the time frame, due to a lot of different projects at hand. We are on it!

**Comment by oliveralka** [comment]
This is still in active development and will be included with the introduction of the new identification data format in OpenMS Metabolomics.

**Comment by oliveralka** [comment]
Current progress: https://github.com/OpenMS/OpenMS/tree/idf_ams
