### ISSUE TITLE
TOPPView leaves a small window when switching back from 3d view (Mac OS X) [417]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#417]
Submitted by aiche on 2012-03-30 13:17:37

When switching back from the 3d view TOPPView leaves a small window on top of all the others, that still shows the 3d view (see attached Screenshot).

---

Commented by aiche on 2012-03-30 13:23:36:
This error is confirmed on 
- Mac OS X 10.6 and 10.7
- Qt 4.7 and 4.8

**Comment by hroest** [comment]
a minor nuisance, only one platform affected - maybe goes away with Qt5?

**Comment by timosachsenberg** [comment]
yes, I think it is fixed in the Qt5 branch.

**Comment by timosachsenberg** [comment]
please reopen if not fixed
