### ISSUE TITLE
MapAlignerPoseClustering + FeatureLinkerUnlabeledQT errors

### ISSUE THREAD

**Issue by hhabra** [OpenMS/OpenMS#4175]
Hi,

I'm using OpenMS through KNIME 4.0.0 for the first time and I'm unable to make this workflow for metabolomics proceed.

After proceeding with the following steps:

**Input Files -> ZipLoopStart -> FeatureFinderMetabo -> ZipLoopEnd -> MapAlignerPoseClustering -> ...**

I'm halted with this error:

> ERROR MapAlignerPoseClustering 2:5 Failing process stdout: [Picking a reference (by size) … done, Progress of ‘Aligning input maps’:, FeatureXMLFile::store(): found 1 invalid unique ids, , ---------------------------------------------------, FATAL: uncaught exception!, ---------------------------------------------------, last entry in the exception handler: , exception of type IllegalArgument occured in line 742, function void __cdecl OpenMS::PoseClusteringAffineSuperimposer::run(const class std::vector<class OpenMS::Peak2D,class std::allocator > &,const class std::vector<class OpenMS::Peak2D,class std::allocator > &,class OpenMS::TransformationDescription &) of C:\jenkins\ws\openms_release_packaging\c2e226b2\source\src\openms\source\ANALYSIS\MAPMATCHING\PoseClusteringAffineSuperimposer.cpp, error message: One of the input maps is empty! This is not allowed!, ---------------------------------------------------]
> ERROR MapAlignerPoseClustering 2:5 Failing process stderr: 
> ERROR MapAlignerPoseClustering 2:5 Execute failed: Failed to execute node MapAlignerPoseClustering

When I replace MapAlignerPoseClustering and try to do feature matching (FeatureLinkerUnusedQT) without RT correction, e.g. perform these steps:

**Input Files -> ZipLoopStart -> FeatureFinderMetabo -> ZipLoopEnd -> FeatureLinkerUnusedQT -> ...**

I get this error:

> ERROR FeatureLinkerUnlabeledQT 2:6 Failing process stdout: [Linking 2 featureXMLs., Progress of ‘reading input’:, , – done [took 0.00 s (CPU), 0.00 s (Wall)] – ]
> ERROR FeatureLinkerUnlabeledQT 2:6 Failing process stderr: 
> ERROR FeatureLinkerUnlabeledQT 2:6 Execute failed: Failed to execute node FeatureLinkerUnlabeledQT

What can be going wrong here?

**Comment by cbielow** [comment]
The error message is a bit lengthy, but it says `One of the input maps is empty! This is not allowed!`.
That could be either because the data is really bad, or the FFMetabo params are not optimal.
If the former case, you'll have to identify the culprit and remove it from the list of inputs.

**Comment by hhabra** [comment]
Hi cbielow, thank you for the reply. I used different combinations of input files and even used .mzML files I ran successfully using other programs (XCMS, MZMine2, etc...). The outcome is always the same, so I don't think it's the files themselves that are the problem.

Per the advice of another forum, I took a look at the Standard Output of FFMetabo. The complaints I see are about this "Unknown parameter noise_threshold_int". It's rather strange to see it being called an "Unknown Parameter." I tried changing its value (1000 -> 10 -> 5), but still the same result.

I also see this "invalid unique ids" message and I'm very unclear about that means.

Thanks for any help.

![featurefindermetabo std output](https://user-images.githubusercontent.com/8129799/60823630-f7abfc80-a175-11e9-92f1-3c54aef519fa.png)

**Comment by hhabra** [comment]
Here is the full set of parameters I'm using for FFMetabo. Do you see anything that sticks out as suboptimal? 

<img width="479" alt="Screen Shot 2019-07-08 at 11 29 11 AM" src="https://user-images.githubusercontent.com/8129799/60824145-1363d280-a177-11e9-956b-877c84449716.png">
<img width="480" alt="Screen Shot 2019-07-08 at 11 29 28 AM" src="https://user-images.githubusercontent.com/8129799/60824146-1363d280-a177-11e9-930e-7eea442394fb.png">

**Comment by oliveralka** [comment]
Do you get any other error message or warning from the FeatureFinderMetabo? 

Could you please try to set the "epd" -> "with_filtering" -> "fixed" (and set the parameter according to your data). 

If it does not help, would you be able to share a few mzML files, then we can have a closer look.

**Comment by hhabra** [comment]
I have shown everything from FeatureFinderMetabo above and have no additional errors or other problems listed in the console.

I followed the suggestion with respect to width_filtering and still had the same bad luck.

What would be the best way to share the files? They are quite large (over 100MB each).

**Comment by oliveralka** [comment]
I will shoot you an email regarding the file exchange. 
Maybe you can drop your workflow as well. 
Thanks a lot!

**Comment by oliveralka** [comment]
The issue seems the be related to the fixed issue of FeatureFinderMetabo reporting zero intensities, which leads to "nan" values in the linear transformation and failure of MapAlingerPoseClustering. In the second output port has to be inactive. If not, FFM will try to report the chromatograms which seem to fails in some cases, which may have something to do with the filtering of the traces - I will have to look further into that issue. 

The original issue should be fixed using the current nightly version and inactivating the optional output port of the FeatureFinderMetabo.
