### ISSUE TITLE
output-file without supported_formats in ctd

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4183]
In OpenMS 2.4 the following tools produce ctd files with an `output-file` field without `supported_formats`:

- InspectAdapter
- MascotAdapter
- PercolatorAdapter
- SvmTheoreticalSpectrumGeneratorTrainer

I guess this is a bug...?

**Comment by bernt-matthias** [comment]
Also some `input-files` miss this attribute. Mostly its executables. But also a few others:

```
ctd/FuzzyDiff.ctd:      <ITEM name="in1" value="" type="input-file" description="first input file" required="true" advanced="false" />
ctd/FuzzyDiff.ctd:      <ITEM name="in2" value="" type="input-file" description="second input file" required="true" advanced="false" />
ctd/InspectAdapter.ctd:      <ITEM name="inspect_input" value="" type="input-file" description="name for the input file of Inspect (may only be used in a full run)" required="false" advanced="false" />
```

**Comment by jpfeuffer** [comment]
Hmm in general this has to be a bug since this attribute is mandatory right?
Do you know if there is any standard way on how to define supported-formats= ANY ? I.e. no restrictions.

I remember that we fixed it at least for PercolatorAdapter already.
FuzzyDiff input has to be unrestricted but I agree it should have the attribute since it is in the standard.

**Comment by bernt-matthias** [comment]
For the bash `*.*` or `*`  seems appealing. But can really anything be passed to those tools?

Btw. are there cases where the format of an output depends on the format of input(s)?

**Comment by jpfeuffer** [comment]
For FuzzyDiff yes, kind of. It just checks file contents line by line. For the others it was just forgotten I think or left open somehow.

In general there can be cases where the out format depends on the in format but this is hard to encode in a tool description so for now we have to throw a "runtime" error when specified in and thereby allowed out (based on extension/mimetype) dont match.

**Comment by jpfeuffer** [comment]
Did we get all of them by now? I think so. Please reopen if not.
