### ISSUE TITLE
Does string with restrictions allow to specify how many options can be selected

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4184]
That is: is it possible if 0, 1, or many option can/must be selected?

**Comment by jpfeuffer** [comment]
This is currently not possible. If this would be implemented, this would go to a StringList parameter.
String is implicitly only one. StringList is implicitly one or more.

**Comment by jpfeuffer** [comment]
I guess this would need to be encoded somewhere here at the ITEMLIST type
https://github.com/WorkflowConversion/CTDSchema/blob/master/Param_1_7_0.xsd#L62

**Comment by hroest** [comment]
the question is whether this should be part of the CTD or simply the tool that checks the parameters and throws an error if something unexpected was selected - I would opt for the second.

**Comment by bernt-matthias** [comment]
Got it. Forgot about the ITEMLIST. For your info why I have so many questions: I'm currently working on improving the (Galaxy part of the) CTDConverter, e.g. https://github.com/WorkflowConversion/CTDConverter/pull/50

Thanks a lot.
