### ISSUE TITLE
How to use idXML in pyopenms ?

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4186]
Hi all!
I need some help with idXML files handling in pyopenms. 
I use it like this:
prot_ids=[]
pep_ids=[]
oms=IdXMLFile().load("omssa.idXML", prot_ids, pep_ids)

Is there a way to access the data? E.g. if I want to compare the scores with those from other idXMLs ?

**Comment by timosachsenberg** [comment]
Hi,
check out https://pyopenms.readthedocs.io/en/latest/datastructures_id.html
Hope that helps!

**Comment by mash23** [comment]
Thank you for your response! 
Now I've figured it out.

**Comment by timosachsenberg** [comment]
Hi @mash23 . 
There should be exactly one PeptideIdentification per identified spectrum.
These parameters are filled by the search engine results and correspond to the RT and precursor m/z information.
These peptide identifications should be the same for different search engines, though there might be small numerical floating-point style differences.
You can also take a look at the ConsensusID tool which merges different peptide identification results.

**Comment by hroest** [comment]
>  These peptide identifications should be the same for different search engines, though there might be small numerical floating-point style differences.

To clarify: the (RT, MZ) values should be the same for different search engines, but the identification result (e.g. the peptide sequence that scored best) can be different. I also suggest to look at the already available algorithms that deal with output from different search engines

**Comment by mash23** [comment]
Ok, thank you all for your help.
