### ISSUE TITLE
Building 2.4.0 on CentOS 7: linker errors linking first binary, have I missed a step?

### ISSUE THREAD

**Issue by Ozzard** [OpenMS/OpenMS#4194]
I'm following https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/install_linux.html on a fresh CentOS 7.6 (current) install, patched with yum update and rebooted immediately before starting these steps.

From there, I've done the following, logged in as root and therefore with /root as ~:

```
sudo yum groupinstall 'Development Tools'
sudo yum install git tar
sudo yum install epel-release
sudo yum repolist
sudo yum install cmake3 qt5-qtbase-gui qt5-qtbase-devel qt5-qtsvg qt5-qtsvg-devel python-devel boost-devel libsvm-devel glpk-devel libzip-devel zlib-devel xerces-c-devel bzip2-devel
mkdir ~/Development
cd ~/Development
curl -o OpenMS-2.4.0-src.tgz https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/2.4.0/OpenMS-2.4.0-src.tar.gz
tar xvf OpenMS-2.4.0-src.tgz
mkdir contrib-build OpenMS-build
cd contrib-build
cmake3 -DBUILD_TYPE=ALL ../OpenMS-2.4.0/contrib
cd ../OpenMS-build
cmake3 -DOPENMS_CONTRIB_LIBS="/root/Development/contrib-build" -DBOOST_USE_STATIC=OFF -DWITH_GUI=off -DHAS_XSERVER=off -DENABLE_UPDATE_CHECK=off ../OpenMS-2.4.0
make TOPP
```

... then got a fail in ublast, fixed by the workaround at https://stackoverflow.com/questions/44534516/error-make-array-is-not-a-member-of-boostserialization , and reran make...

... then got a fail linking the first built binary, which is MapAlignerSpectrum.  The command line, extracted from deep within the make system, is:

`(cd src/topp; /bin/c++   -fopenmp  -O2 -DNDEBUG  -rdynamic -fopenmp CMakeFiles/MapAlignerSpectrum.dir/MapAlignerSpectrum.cpp.o  -o ../../bin/MapAlignerSpectrum -Wl,-rpath,/root/Development/OpenMS-build/lib:/root/Development/contrib-build/lib: ../../lib/libOpenMS.so ../../lib/libOpenSwathAlgo.so /root/Development/contrib-build/lib/libCbc.a /root/Development/contrib-build/lib/libCgl.a /root/Development/contrib-build/lib/libClp.a /root/Development/contrib-build/lib/libCoinUtils.a /root/Development/contrib-build/lib/libOsi.a /root/Development/contrib-build/lib/libOsiClp.a /root/Development/contrib-build/lib/libsvm.a -lxerces-c -lboost_iostreams-mt -lboost_date_time-mt -lboost_math_c99-mt -lboost_regex-mt /root/Development/contrib-build/lib/libWm5Core.a /root/Development/contrib-build/lib/libWm5Mathematics.a /root/Development/contrib-build/lib/libbz2.a /root/Development/contrib-build/lib/libz.so /root/Development/contrib-build/lib/libsqlite3.a /root/Development/contrib-build/lib/libglpk.a /usr/lib64/libQt5Network.so.5.9.2 /usr/lib64/libQt5Network.so.5.9.2 /usr/lib64/libQt5Core.so.5.9.2 /usr/lib64/libQt5Core.so.5.9.2)`

... which throws a load of undefined references to a namespace xerces_c_3_2, and more to a namespace boost::re_detail_106400, for example:

```
MapAlignerSpectrum.cpp:(.text._ZN11xercesc_3_214DefaultHandler10fatalErrorERKNS_17SAXParseExceptionE[_ZN11xercesc_3_214DefaultHandler10fatalErrorERKNS_17SAXParseExceptionE]+0x2b): undefined reference to `typeinfo for xercesc_3_2::SAXParseException'
../../lib/libOpenMS.so: undefined reference to `boost::re_detail_106400::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
../../lib/libOpenMS.so: undefined reference to `xercesc_3_2::BinInputStream::getEncoding() const'
```

I can get round the Xerces errors by replacing -lxerces-c with the full path to the built .a path in the contribs:

`(cd src/topp; /bin/c++ -O2 -DNDEBUG -rdynamic -fopenmp CMakeFiles/MapAlignerSpectrum.dir/MapAlignerSpectrum.cpp.o  -o ../../bin/MapAlignerSpectrum -Wl,-rpath,/root/Development/OpenMS-build/lib:/root/Development/contrib-build/lib: ../../lib/libOpenMS.so ../../lib/libOpenSwathAlgo.so /root/Development/contrib-build/lib/libCbc.a /root/Development/contrib-build/lib/libCgl.a /root/Development/contrib-build/lib/libClp.a /root/Development/contrib-build/lib/libCoinUtils.a /root/Development/contrib-build/lib/libOsi.a /root/Development/contrib-build/lib/libOsiClp.a /root/Development/contrib-build/lib/libsvm.a /root/Development/contrib-build/lib/libxerces-c-3.2.a -lboost_iostreams-mt -lboost_date_time-mt -lboost_math_c99-mt -lboost_regex-mt /root/Development/contrib-build/lib/libWm5Core.a /root/Development/contrib-build/lib/libWm5Mathematics.a /root/Development/contrib-build/lib/libbz2.a /root/Development/contrib-build/lib/libz.so /root/Development/contrib-build/lib/libsqlite3.a /root/Development/contrib-build/lib/libglpk.a /usr/lib64/libQt5Network.so.5.9.2 /usr/lib64/libQt5Network.so.5.9.2 /usr/lib64/libQt5Core.so.5.9.2 /usr/lib64/libQt5Core.so.5.9.2)`

... but this still leaves the Boost errors, and leaves me wondering what I should have done earlier in the process such that this build isn't such a pain.

What have I missed in the above commands?  Is there a "make install" somewhere, or something I should be doing to set up libraries in cmake so that they work with contrib?

Once I've got a working build script, I'll write it up so that future CentOS users have something to go from.

**Comment by Ozzard** [comment]
Incidentally, it's not obvious in the wall of text above, but I had to add cmake3 and qt5-qtsvg-devel to the installed packages on CentOS 7, as its default cmake is 2.x and there's not quite enough qt5 SVG support without the -devel package as well.

**Comment by timosachsenberg** [comment]
@jpfeuffer shouldn't the ublas error be fixed by the patch?

**Comment by jpfeuffer** [comment]
@timosachsenberg The patch was only for the usage of make_array in OpenMS.
Not for other libraries. Where is ublas used? Never encountered it. Probably as an optional dependency of some of our dependencies.


In general I assume the problem here is that many libraries were installed twice (once via yum as once via contrib with BUILD_TYPE=ALL) Since it seems like you have full control over the machine and the libraries are not meant to be shared, I recommend to just use the libraries we ship in contrib (correct versions, correct configuration of optional dependencies, etc.). You only need to install QT (and qt svg  as you pointed out correctly) which is not in the contrib.


The problem with mixing is, that some system libraries have to be included via adding /usr/include to the header paths (depending on how the header are then actually included in the sources). Although we try to give preference to the contrib libraries (which didn't work for xerces and boost [which could be further investigated, especially since for xerces it seemed to pick the contrib headers but link the system library]), as soon as one (affected) system library is chosen by CMake all the other headers in /usr/include are available to the compiler as well and it depends on include orders which are used.

Since you perfectly shared the commands used I can try to reproduce on a docker image and improve on the find mechanisms and/or include orders (again). Until then, try to only have one version installed.

**Comment by Ozzard** [comment]
Thanks, Julianus - I'll chase that on Rocky*.  I wonder whether it's worth making the build instructions a little more explicit that you probably don't want to follow both the top part (install dependencies) and the bottom part (build dependencies).

Is there a "make clean" equivalent so that I can rebuild from scratch, or shall I just nuke the file hierarchy and go again?

* The test machine** - a physical box with SSD, spinning rust, and enough RAM to test tmpfs for intermediate files in TOPP workflows, because our cluster has an odd configuration and I want some numbers before recommending changes.

** "Come up to the lab, see what's on  the slab..."

**Comment by jpfeuffer** [comment]
Hm I agree we could separate the two mechanisms of getting the dependencies ready more clearly, although most people will need to use both mechanisms to get all the needed libraries (thanks to Qt).
Unfortunately I don't think the "clean" target in contrib (if present at all?) knows about all the files installed by the sub-build systems so it won't remove enough.
I would nuke the folder or at least all the subfolders inside if you want to keep the configuration. But a clean build with just the missing libs is probably best.

**Comment by Ozzard** [comment]
I can confirm that the following "works" (at least compiles!) on CentOS 7.6; this may be helpful to anyone else in the same situation.
```
sudo yum groupinstall 'Development Tools'
sudo yum install git tar
sudo yum install epel-release
sudo yum repolist
sudo yum install cmake3 qt5-qtbase-gui qt5-qtbase-devel qt5-qtsvg qt5-qtsvg-devel python-devel boost-devel libsvm-devel glpk-devel libzip-devel zlib-devel xerces-c-devel bzip2-devel
mkdir ~/Development
cd ~/Development
curl -o OpenMS-2.4.0-src.tgz https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/2.4.0/OpenMS-2.4.0-src.tar.gz
tar xvf OpenMS-2.4.0-src.tgz
mkdir contrib-build OpenMS-build
cd contrib-build
# cmake3 -DBUILD_TYPE=ALL ../OpenMS-2.4.0/contrib
cmake3 -DBUILD_TYPE=SEQAN ../OpenMS-2.4.0/contrib
cmake3 -DBUILD_TYPE=COINOR ../OpenMS-2.4.0/contrib
cmake3 -DBUILD_TYPE=EIGEN ../OpenMS-2.4.0/contrib
cmake3 -DBUILD_TYPE=WILDMAGIC ../OpenMS-2.4.0/contrib
cmake3 -DBUILD_TYPE=SQLITE ../OpenMS-2.4.0/contrib
cmake3 -DBUILD_TYPE=KISSFFT ../OpenMS-2.4.0/contrib
cd ../OpenMS-build
cmake3 -DOPENMS_CONTRIB_LIBS="/root/Development/contrib-build" -DBOOST_USE_STATIC=OFF -DWITH_GUI=off -DHAS_XSERVER=off -DENABLE_UPDATE_CHECK=off ../OpenMS-2.4.0
make TOPP
```

**Comment by cbielow** [comment]
So ublast and linker errors went away with the above config?

**Comment by Ozzard** [comment]
Linker: yes.  ublast: don't know; I didn't go right back to unpatched source.

Two failed tests:
```

99% tests passed, 2 tests failed out of 2149

Total Test time (real) = 265.94 sec

The following tests FAILED:
        452 - PrecursorIonSelectionPreprocessing_test (Failed)
        527 - DetectabilitySimulation_test (Failed)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by hroest** [comment]
@jpfeuffer @timosachsenberg can we add the above instructions to the documentation, maybe use ` cmake3 -DBUILD_TYPE=ALL ../OpenMS-2.4.0/contrib` instead?
