### ISSUE TITLE
What to use for file tracking between tools (file names vs mzML sourceFile entry)

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#4197]
Hmm unfortunately we cannot reproduce this on fresh mzML files (like our tutorial data).
It could be mzML files from old msconvert versions not carrying a sourceFile entry.

_Originally posted by @jpfeuffer in https://github.com/OpenMS/OpenMS/issues/3683#issuecomment-480906764_

**Comment by FabianAicheler** [comment]
So basically, what do we really want to use to keep track of which featureXmls, consensusXml entries belong to which mzML file.

Personally I would have thought that it makes a lot more sense to simply chain through the original mzML file name:
a) because apparently we have the problem with older/differently converted files missing the sourceFile entry
b) I/people are interested in the pipeline from "arbitrarily (re)named mzML" to the end, and as such don't really care per se how the original raw file was named

**Comment by timosachsenberg** [comment]
Tracking the first (primary) mzML file should be implemented in all relevant tools.
Where is this missing?

**Comment by FabianAicheler** [comment]
As far as I understood from issue #3683 
- currently the tracking is done via extracting the mzML sourceFile entry, which is (afaik) based on the name of the original raw file.
- This fails if the converter fails to write that info (e.g. older raw file formats didn't contain that (?), also depends on conversion tool (e.g., CompoundDiscoverer 2.0 exporter apparently stores a list of sourceFiles, thus violating mzML standard?))
-That then results in 'UNKNOWN' map entries in the at least FeatureLinkerUnlabeled, QT, KD

**Comment by timosachsenberg** [comment]
Hmm I thought it uses the mzML filename if there is only a raw file referenced

**Comment by timosachsenberg** [comment]
Ok I think we need to get such a raw file and see what featurefindermetabo annotates in the featureXML. Then we might come up with a workaround for the faulty annotation of source files

**Comment by jpfeuffer** [comment]
It definitely differs from featurefinder to featurefinder.
FFC uses whatever is in the mzML
FFID annotates whatever is in the "-in" (i.e. the mzML file name)
etc..

**Comment by timosachsenberg** [comment]
I think we should add 
```
      // annotate mzML file
      StringList feature_msfile_ref;
      feature_msfile_ref.push_back("file://" + in);
      features.setPrimaryMSRunPath(feature_msfile_ref);
```
to the FFC. Which else?

**Comment by cbielow** [comment]
can we please handle this uniformly across all TOPP tools?
e.g. create a function
`static void TOPPBase::annotatePrimaryMSRunPath(const MSExperiment& source, const& String alt_input_filenames, FeatureMap& target)` and call that whenever relevant?

**Comment by timosachsenberg** [comment]
why not just: 
features.setPrimaryMSRunPath({"file://" + feature_msfile_ref);
as we already have it?
I guess you want to prevent the case if there is already a valid file set. But handling this is a bit difficult as you might need to check for the fallback:
- if file in MSExperiment is an open file format like mzML (easy)
- if file exists on file system (can we enforce that for distributed workflow systems etc.?)

**Comment by cbielow** [comment]
as I understood, we should check if the annotation in the MSExperiment is empty (in case old Raw file formats or converters did not provide the information). If empty, use the fallback, i.e. the current input filename (usually mzML).
I dont think we should check for file type or existence in the file system, since these files are meant for sharing, i.e. the path will almost always be invalid. All that counts in the actual filename, which serves as the identifier.

**Comment by timosachsenberg** [comment]
- these are often not empty but contain some .RAW entry
- I think we struggled with this a bit and I think it doesn't work in all cases. E.g., some tools at the end of the pipeline need to read in the original existing mzML files and match them e.g., to the experimental design. At least for the execution of the pipeline, I think we need to ensure that the full path is the identifier and the files and be read until execution finishes.

**Comment by cbielow** [comment]
ok, then this suggest the following:
 - if the MSExperiment contains a non-mzML: replace with `alt_input_filename`
 - if the MSExperiment contains an mzML: verify its readable; if not readable replace with `alt_input_filename`

**Comment by timosachsenberg** [comment]
We already have features.setPrimaryMSRunPath(feature_msfile_ref);
so I think we could just add another Parameter with default MSExperiment()
```
features.setPrimaryMSRunPath(feature_msfile_ref, ms_exp);
```
That way it also works (as before) if no MSExperiment is at hand.

**Comment by jpfeuffer** [comment]
I think it would be feasible to fix some of the tools for release 2.5. Any volunteers?

**Comment by timosachsenberg** [comment]
Ok then we should add the:
- features.setPrimaryMSRunPath(feature_msfile_ref, ms_exp); method to ID, feature, consensus feature, MSExperiment
- find out where it is missing (e.g. FFC sets it differently)

**Comment by timosachsenberg** [comment]
I'll take on the first issue

**Comment by timosachsenberg** [comment]
addressed in https://github.com/OpenMS/OpenMS/pull/4210
