### ISSUE TITLE
pyopenms  issue with Param.setValue

### ISSUE THREAD

**Issue by jylanwhu** [OpenMS/OpenMS#4203]
I tried to use function FeatureFindingMetabo(), and use p.setValue('enable_RT_filtering', "false")
It gives an error of Exception: can not handle type of ('enable_RT_filtering', 'false')

Could you please help me fix this issue?

Best,
JL

**Comment by oliveralka** [comment]
Depending on your code it looks correct. It may be the case that you have to give the 'enable_RT_filtering' as byte instead of str: 
```
>>> ffm = pyopenms.FeatureFindingMetabo()
>>> p = ffm.getDefaults()

# similar error occured here:
>>> p.get('enablte_RT_filtering')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Argument 'key' has incorrect type (expected bytes, got str)

>>> p.get(b'enable_RT_filtering')
'true'
>>> p.setValue(b'enable_RT_filtering','false')
>>> p.get(b'enable_RT_filtering')
'false'
>>> ffm.setParameters(p)
```

**Comment by jylanwhu** [comment]
problem solved, thanks!
