### ISSUE TITLE
The fdr filtering for the protein and peptide levels.

### ISSUE THREAD

**Issue by cherrypas** [OpenMS/OpenMS#4212]
Hi, 
Can anybody help me to understand what the allowed level of FDR is ? 
How can I perform the FDR filtering to allow the level of false positive results no more than 0.01 for both peptides and proteins ? 
I've found a tool in OpenMs "FalseDiscoveryRate" but It's not clear for me how it must be used. 
By now I've only applied OmssaAdapter, IDPEP and PeptideIndexer.

**Comment by jpfeuffer** [comment]
Hi!

First of all, OpenMS unfortunately does not support peptide FDRs. All you can do is filtering on the PSM level.

To calculate an FDR on protein level (in OpenMS) you have to perform a protein inference first.
In the 2.4 release your only option is the FidoAdapter here which could be the next step in your pipeline. I would not filter the PSMs to 0.01 FDR before inference since it might result into too few data. Instead do both filters after.

Afterwards the filtering can be done on both levels. I think in the 2.4 version you can even do it simultaneously with the FalseDiscoveryRate tool.

To do this you can add the FDR tool after the FidoAdapter and set -PSM and -protein to true for the calculation and  -FDR:PSM and -FDR:protein to your cutoff that you decided on.

**Comment by cherrypas** [comment]
Thank you for your response, 
I did as you suggested. Here is what I got after FidoAdapter: 
![fido](https://user-images.githubusercontent.com/54020956/63076511-b3273400-bf5f-11e9-9b69-6ef5c9caf750.jpg)
And here is what I got after applying the FDR to it: 
![fido_fdr](https://user-images.githubusercontent.com/54020956/63076584-e36ed280-bf5f-11e9-9cba-450effb2f1e0.jpg)
The score of each protein became now a zero, but they got the posterior_error_probability score. How am I to analyze them now ? I should take the pep for the new score and sort proteins in ascending order ?

**Comment by cherrypas** [comment]
I applied IDScoreSwitcher on the protein level to switch the score to Posterior Probability and then sorted all protein hits via the IDFilter. guess, that solved my problems.

**Comment by jpfeuffer** [comment]
Hmm yes, sorting and doing a cutoff based on probabilities is an option but not always ideal. It is better to double check the amount of decoys identified at the same time (with the FDR).
An FDR of 0 among the top probable proteins is not unusual, however it seems in your case you also get FDRs of 0 at very low scoring proteins. This might be an indicator that you had no (or only very few) decoys during the FDR calculation which in turn might hint to an error in the pipeline. Maybe you can find something about the number of decoys in the standard output from the tools printed to the console (or standard output view in Knime). Additionally you can run the FileInfo tool after some steps in the pipeline.

**Comment by cherrypas** [comment]
I've looked through the Fido's output, there were about 11000 decoys with nonzero scores out of about 74200 protein hits with nonzero scores.

**Comment by jpfeuffer** [comment]
Hmm a bit low assuming that you started with an equal amount but not necessarily an error. The next tool is FDR with a filter on PSM and protein level?

**Comment by cherrypas** [comment]
I use IDFilter after FidoAdapter to sort the protein hits but the next is FDR with a filter on PSM and protein level.

**Comment by jpfeuffer** [comment]
Aah hmm can you check that IDFilter does not remove anything? What are its settings and what is its output?

**Comment by cherrypas** [comment]
I used it without setting any parameters except -in and -out and I set the same names for both of them.

**Comment by jpfeuffer** [comment]
What does its output say? I think it tells you things like "#proteins before" and "#proteins after".
When in doubt if the Filter removes things by default, I would wait until the very end with sorting.

**Comment by jpfeuffer** [comment]
FDR might even sort the data already.

**Comment by cherrypas** [comment]
The output of the IDFilter:

Before filtering:
1 protein identification(s) with 27998 protein hit(s),
30747 peptide identification(s) with 30747 peptides hit(s).
After filtering:
1 protein identification(s) with 27998 protein hit(s),
30747 peptide identification(s) with 30747 peptides hit(s).

I understand it did not remove any of the data.

So you suggest to skip the IDFilter step in my pipeline and to apply FDR right after FidoAdapter ?

**Comment by jpfeuffer** [comment]
Right, I would try that to see if it changes your observations of every protein getting assigned an FDR of 0 (which seems implausible.

**Comment by cherrypas** [comment]
There are only 282 proteins with zero score after IDFilter and 2113 of them after FDR (if applied to the FidoAdapter output).

**Comment by jpfeuffer** [comment]
Ah okay, well that seems much more plausible. I misunderstood something then. Seems like IDFilter is working correctly and not filtering anything.

**Comment by cherrypas** [comment]
So I did all correctly and my results are valid and reliable?

**Comment by jpfeuffer** [comment]
In my opinion, the numbers seem reasonable now.

**Comment by cherrypas** [comment]
Ok than, thank you for your help.
