### ISSUE TITLE
error running FeatureFinderCentroided

### ISSUE THREAD

**Issue by im281** [OpenMS/OpenMS#4219]
Installed all dependencies per prescription on a Linux box inside a container and getting this error. Any suggestions would be appreciated

Note that when I run FeatureFinderMetabo I do NOT get the same error!

root@d6fe313f6115:/app# ./FeatureFinderCentroided -in testdata/FeatureFinderMetabo_input.mzML -out test.featureXML
./FeatureFinderCentroided: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.9' not found (required by ./FeatureFinderCentroided)

**Comment by jpfeuffer** [comment]
Hi!
Which Linux and version are you on?
Did you try the deb package or did you build from scratch? Or if you are using a base container, which one?

**Comment by im281** [comment]
Hello, I have attached 2 docker files. The first is built and is called
'linuxbase'

The second is built on top of that:

FROM linuxbase AS base

#make /app the working directory
WORKDIR /app

#copy all the files from the /app directory to the working directory
copy /app/ ./

#custom script to run
copy ./script_runner.sh ./

#make script executable
RUN chmod 755 script_runner.sh

# Change to your application name, sets additional permissions to run in
linux
RUN chmod 755 /app/FeatureFinderCentroided
RUN chmod 755 /app/FeatureFinderMetabo

ENV PATH "$PATH:/app/lib"
ENV PATH "$PATH:/app/share/OpenMS"
ENV LD_LIBRARY_PATH '/app/lib'
ENV OPENMS_DATA_PATH='/app/share/OpenMS'

RUN apt-get update
RUN apt-get update && apt-get install -y qt5-default libqtwebkit-dev
RUN apt-get update && apt-get install -y libeigen3-dev libsqlite3-dev \
      libboost-regex1.62-dev libboost-iostreams1.62-dev
libboost-date-time1.62-dev libboost-math1.62-dev libboost-random1.62-dev\
      libxerces-c-dev libglpk-dev libsvm-dev libbz2-dev libwildmagic-dev
seqan-dev \
      coinor-libcoinutils-dev coinor-libcgl-dev coinor-libcbc-dev
coinor-libclp-dev coinor-libosi-dev coinor-libvol-dev



ENTRYPOINT ["/app/script_runner.sh", "/app/FeatureFinderCentroided", "
-algorithm:isotopic_pattern:charge_low 2
-algorithm:isotopic_pattern:charge_high 4 -out localfile.output -in
/appinputs/@FILE1", ""]

**Comment by im281** [comment]
of note again. FeatureFinderMetabo works but FeatureFinderCentroided does
not

**Comment by im281** [comment]
Perhaps you can point me to a base image where I can build on top of. I place all the OpenMS files in my 'app' directory and then set the environmental variables (which works for FeatureFinderMetabo)

ENV PATH "$PATH:/app/lib"
ENV PATH "$PATH:/app/share/OpenMS"
ENV LD_LIBRARY_PATH '/app/lib'
ENV OPENMS_DATA_PATH='/app/share/OpenMS

**Comment by jpfeuffer** [comment]
Hmm copying executables to the container and installing the dependencies seperately is tricky. 
I would build the executables where they are executed. I don't know why one executable works. You would need to debug with ldd or something similar.
You can look at docker hub or https://github.com/OpenMS/dockerfiles for examples on how to build containers. Unfortunately quite some of them might be outdated.

**Comment by jpfeuffer** [comment]
Did you have any success? I am glad to help if something is missing/ not working.

**Comment by im281** [comment]
Unfortunately now. It would be nice if there was a container with all the dependencies installed. I am now trying pyopenms and that seems like to does work. Is there a forum that one can discuss algorithm parameters etc?

**Comment by jpfeuffer** [comment]
There is, but I agree that they are a bit hard to find.
Do you need any modifications to the tools or is the release version fine?
For the 2.4 release there is a nice docker file [here](https://hub.docker.com/r/mwalzer/openms-batteries-included).
Just run
`docker pull mwalzer/openms-batteries-included:V2.4.0`
and to login
`docker run -it mwalzer/openms-batteries-included:V2.4.0 /bin/bash`
then every tool is in your path and you can just run e.g.
`OpenMSInfo` or `FeatureFinderCenroided`. You can of course mount your data or
for inclusion in other Dockerfiles, just do a
`FROM mwalzer/openms-batteries-included:V2.4.0`

**Comment by jpfeuffer** [comment]
Dockerhub images should be up-to-date. We also have biocontainers on quay.
