### ISSUE TITLE
Add MSExperiment.getSpetra()

### ISSUE THREAD

**Issue by fkromer** [OpenMS/OpenMS#4222]
Seems like `pyopenms` v2.4.0 does not provide [openms MSExperiment.getSpetra()](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/classOpenMS_1_1MSExperiment.html#ab2e0f5201addaf2709ffc866ac6aeb23) yet. I should be fine following the [How to wrap new methods in existing classes](https://pyopenms.readthedocs.io/en/latest/wrap_classes.html#how-to-wrap-new-methods-in-existing-classes) docs and create a PR, right? Have you already scheduled the release of `pyopenms` v2.5.0 which could potentially contain the PR's code?

**Comment by hroest** [comment]
Can you use list() instead?

**Comment by fkromer** [comment]
I don't think so. According to the interactive Jupyter tab completion/documentation the MSExperiment instance provides `getSpectrum()`, `getChromatograms()` and `getNrSpectra()` only.

**Comment by fkromer** [comment]
`MSExperiment.list()` returns a list containing spectrums. For some reason the interactive tab completion does not work. Thx.

**Comment by fkromer** [comment]
Sorry, I mixed this up with something else. There is no `list()` for `MSExperiment`:

```
[10]: import pyopenms
      exp = pyopenms.MSExperiment()
      pyopenms.MzMLFile().load(<PATH-TO-MZML-FILE>, exp)

      ---------------------------------------------------------------------------
      AttributeError                            Traceback (most recent call last)
      <ipython-input-12-8e5f06fdf7fb> in <module>
      ----> 1 exp.list()

      AttributeError: 'pyopenms.pyopenms_5.MSExperiment' object has no attribute 'list'
```

**Comment by jpfeuffer** [comment]
I think he means the global conversion function list(), as in:
```python
exp = MSExperiment()
MzMLFile().load("/Users/pfeuffer/Downloads/118B7.mzML", exp)
l = list(exp)
print(l[0].getRT())
```

**Comment by fkromer** [comment]
Works. Thx.

**Comment by hroest** [comment]
PS: there should be a `getSpectra` function at least since 2.4

https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/MSExperiment.pxd#L56


```
>>> import pyopenms
>>> pyopenms.MSExperiment.getSpectra
<method 'getSpectra' of 'pyopenms.pyopenms_2.MSExperiment' objects>
>>> pyopenms.MSExperiment().getSpectra()
[]
>>> pyopenms.__version__
'2.4.0'
```
