### ISSUE TITLE
FeatureFinderMetabo in pyopenms

### ISSUE THREAD

**Issue by jylanwhu** [OpenMS/OpenMS#4235]
I would like to use the OpenMS function FeatureFinderMetabo in pyopenms but there is no implementation. Will it be implemented recently?

**Comment by hroest** [comment]
Currently the Python bindings do not re-implement a complete TOPP-Tool but they provide access to the underlying C++ library functions. TOPP tools like FeatureFinderMetabo use the library functions to achieve a certain goal and you can re-implement these calls to the library in Python by looking at https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FeatureFinderMetabo.cpp -- however we do not plan to reimplement all TOPP tools at this point. However, using `pyopenms.MassTraceDetection` and `pyopenms.ElutionPeakDetection` and `pyopenms.FeatureFindingMetabo` in the right order in Python should get you 99% there.
