### ISSUE TITLE
Compare SourceFile mzML and featureXML (setPrimaryMSRunPath)

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4239]
I check the accordance of the source file names in the AssayGeneratorMetabo. 

```
      StringList mzml_primary_path;
      StringList featurexml_primary_path;
      spectra.getPrimaryMSRunPath(mzml_primary_path);
      feature_map.getPrimaryMSRunPath(featurexml_primary_path);

      if (mzml_primary_path != featurexml_primary_path)
      {
        throw Exception::MissingInformation(__FILE__,
                                            __LINE__,
                                            OPENMS_PRETTY_FUNCTION,
                                            "Path of the original input file do not match in the .mzML and .featureXML files. \n Please check and provide the corresponding files.");
      }
```

With the change in the function "setPrimaryMSRunPath", this does not work anymore. 
The issue is that FFM sets its StringList in as new "PrimaryMSRunPath" in the featureXML. 

So the path from the source file in the mzML (path/File.wiff) does not correspond to the spectra_data in the featureXML (path/File.mzML) anymore. 

One fix would be to use the "in" parameter of the AssayGeneratorMetabo and see if the "PrimaryMSRunPath" of the feautreXML matches. This works as long as everything is run in the same workflow. If the mzML is copied to another location and used with the previous featureXML it does not work anymore. 

I am actually not sure what to do about that since the current setPrimaryMSRunPath would like to have an mzML and an existing source file.

I would need the reference to the original file. Any suggestions?   

```
  void FeatureMap::setPrimaryMSRunPath(const StringList& s, MSExperiment & e)
  {
    StringList ms_path;
    e.getPrimaryMSRunPath(ms_path);
    if (ms_path.size() == 1 && ms_path[0].hasSuffix("mzML") && File::exists(ms_path[0]))
    {
      setPrimaryMSRunPath(ms_path);
    }
    else
    {
      setPrimaryMSRunPath(s);
    }        
  }
```

**Comment by timosachsenberg** [comment]
maybe just turn the exception into a warning if featureXML primaryMSRunPath and in are different?

**Comment by oliveralka** [comment]
Ok, I will check accordance of the input and the feautreXML primaryMSRunPATH and give a warning if it does not match - this should work in my case.  - Thanks!
