### ISSUE TITLE
Support for TMT 16-plex (IsobaricAnalyzer)

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4242]
TMT(16-plex) is out - should we support it in the IsobaricAnalyzer?

How hard would the implementation be? e.g. Hacktoberfest? 

https://www.thermofisher.com/order/catalog/product/A44520

**Comment by poshul** [comment]
Do we have any 16plexed data that I can test changes on?

**Comment by poshul** [comment]
The Isotopic distribution matrix for this product is different from previous ones (https://www.thermofisher.com/order/catalog/product/A44520#/A44520) neither the -2 or +2 shifts detail which mass they look like. I've updated the matrix in the software to match (with the exception of the 127N nitrogen loss, since it was not included in the other existing files). @cbielow any thoughts?

**Comment by pavel-shliaha** [comment]
@poshul I can provide a 16plex file if you would like to have a look. Please provide your email

On an unrelated note @oliveralka could you please share your TMT pipeline? my email is pavels@bmb.sdu.dk

**Comment by oliveralka** [comment]
There is an open PR on OpenMS/Tutorials, which needs to be finalized. 
https://github.com/OpenMS/Tutorials/pull/166

**Comment by jpfeuffer** [comment]
How was TMT 16 plex handled/tested without the support for the TMTPro modification due to our very outdated Unimod.xml?
Or was just the theoretical quantification tested?

**Comment by pavel-shliaha** [comment]
I think I made a mistake and ran it with TMT11 plex, hence I had problems with the results of course. When will the 16plex be implemented? On a related note, is there a search engine that allows adding custom modifications?

**Comment by jpfeuffer** [comment]
Only the support for the modification is missing. You could probably customize one of the 10 CUSTOM modifications that we add to each Unimod.xml in case a new modification is needed between two releases.
Otherwise, it will be fixed with #4803
