### ISSUE TITLE
What are the scores in the FidoAdapter output?

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4271]
Hi, 
When I run the FidoAdapter it outputs the file with a list of proteins and each protein has a score in range from 0 to 1. Am I right that the score is the posterior probability and the higher the score, the greater the probability that this protein was presented in the sample ? So if the score is equal to 0 that means that the protein was not found ? Than what does mean a score equal to 0.5 ? How should I interpret it ?

**Comment by jpfeuffer** [comment]
Hi,

yes the output are posterior probabilities (higher = better). The interpretation of the probabilities however depends on the parameter set that Fido chose as the best, therefore probabilities are not always comparable across different pipelines/datasets. In general, of course the idea is that proteins with probability of 1 are certainly there and proteins with score 0 are definitely not there but this is hard to achieve. Probabilities of 1 are usually artefacts of rounding/scaling, you will never be able to call a protein with 100% certainty. Also a 0 probability does not necessarily mean that no evidence for this protein was found at all. But maybe the scores for its found peptides were so low that they did not pass an initial threshold.
Usually you would now calculate a protein level FDR to calculate how many decoy proteins are among the top probable proteins. And then choose the top scoring proteins until a certain FDR cutoff for reporting.

**Comment by mash23** [comment]
And what does it mean if a protein and the corresponding decoy are both found with similar scores?

**Comment by jpfeuffer** [comment]
In general our FDR approach does not care about _pairs_ of target proteins and respective decoy proteins. Decoy proteins are used in their entirety to estimate the amount of false targets.
As long as you do not have too many decoy proteins on top of your list (sorted descending by probability) the analysis should be fine.

**Comment by mash23** [comment]
Ok, thank you very much.

**Comment by mash23** [comment]
Can I somehow understand what score is relatively good and what is not? I mean if a protein has a score 0.6 or 0.7 may I assume in my issue that this protein was presented in the sample ? Or I should not rely on such low scores ? 
Can I draw such conclusions or I definitely have to present the FDR correction before making any decisions?

**Comment by jpfeuffer** [comment]
Hi!
I would mainly rely on the FDR estimates.

Although e.g. Fido tries to calibrate the probabilities to follow the FDR, this does not always succeed. They also may change drastically from dataset to dataset. FDR would be a more robust way to compare across datasets.

**Comment by mash23** [comment]
Does the FDR leave only target proteins in the resulting list ?

**Comment by jpfeuffer** [comment]
By default our FDR tool only leaves targets, yes. If you do postprocessing or inference with any OpenMS tool, please set "add_decoys" to true.
