### ISSUE TITLE
Normalization in Isobaric experiments avoiding ratios ?

### ISSUE THREAD

**Issue by aalvarezf** [OpenMS/OpenMS#4282]
Dear all, 
I'd like to normalize isobaric data from a TMT experiment at the PSM level, after running isobaricAnalizer
I notice is possible to normalize at this step using the reference channel as denominator, however I'd like to avoid ratios. 
I'm looking for some tool like the normalise() function in the MSnbase R package. 
Is ConsensusMapNormalizer the correct tool for that purpose with labelled data?  Do you have any suggestion about the algorithm to use? 

Sorry if my questions are very basic, i'm new in the field and trying to learn about it.  

Thank you!

**Comment by jpfeuffer** [comment]
Hi!

Yes, I think the ConsensusMapNormalizer should be able to do basic normalization methods per file/sample (without a reference channel).
Could you test it already?
