### ISSUE TITLE
How to choose a threshold value for the protein scores?

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4288]
Hi,
I have an idXML file with the list of proteins. Each protein has a score. How can I choose the threshold for the scores ? Which parameters does this threshold depends on ?

**Comment by timosachsenberg** [comment]
It depends on the type of score your proteins have. If these are already q-values you can filter by a fixed q-value threshold (e.g., 0.05 for 5%) to control the False Discovery Rate (FDR) at the 5% level.

**Comment by mash23** [comment]
And if scores are posterior probabilities ?

**Comment by hroest** [comment]
Then I suggest to convert them to q values and use those

**Comment by mash23** [comment]
How can I do that ?

**Comment by jpfeuffer** [comment]
With the FalseDiscoveryRate tool. Set the protein parameter to true and set the cutoff score to 0.01 or 0.05 or however many false positives you might tolerate.
