### ISSUE TITLE
Building OpenMS with Visual Studio 2019

### ISSUE THREAD

**Issue by nateglasser** [OpenMS/OpenMS#4290]
Hello,

I was able to build OpenMS with Visual Studio 2019 on Windows 10, but a few source changes were required. I'm including my notes here to hopefully help with supporting VS2019 for the next release.

_contrib dependencies_
CMake: The path to MSBuild.exe changed between VS2017 and 2019 so I had to update the path in CMakeLists.txt. The default is now at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin

CoinMP: Needs the solution and project files for VS2019. I copied the v15 folder in /contrib/src/CoinMP-1.8.3/Coin/MP/MSVisualStudio . I renamed it to v16, opened the .sln file in VS 2019, converted the project and saved. Everything built as expected.

No issues otherwise.

_OpenMS_
There were some compiler errors related to std::string being undefined, resulting from the headers in the projects:
* OpenSwathAlgo: MockObjects.h, ITransition.h
* OpenMS: EmpiricalFormula.h

These classes expose std::string in their public interface but the headers do not include string. In VS2017 and below, vector pulled along xstring, but this was refactored in VS2019: https://devblogs.microsoft.com/cppblog/cpp17-20-features-and-fixes-in-vs-2019/

The source files that use these headers include string _after_ including the problematic headers. To fix this, the string include statement could be moved earlier...but since the classes defined in these headers depend on std::string anyway, it was simpler to just include string in the header files.

_tests_
CrossLinksDB_test and ModificationsDB_test failed to build because the comparison operator for ResidueModificationOriginCmp wasn't declared const. Easily fixed by changing to: bool operator() (const ResidueModification* a, const ResidueModification* b) const

_failing tests_
The following tests fail: ConvexHull2D_test, Map_test, MRMFeature_test, ConsensusFeature_test

The failures are all related to the fact that the MSVC implementation of std::map does not support a noexcept move constructor. The C++ standard doesn't require one, but it may have some unexpected performance problems on Windows.

Other than that, all the tests pass and I can run TOPPView and TOPPAS (linked against QT 5.13).

**Comment by cbielow** [comment]
perfect. Thanks for the in-depth description!
For extra bonus points, do you happen to have a patch/PR at hand which you could submit? :)
(the contrib is somewhat harder, so we'd probably redo that on our own).

**Comment by jpfeuffer** [comment]
That is great indeed! Yes, I think we can provide the changes to the contrib ourselves (involves uploading to our servers etc) but if you could provide a pull request for the changes to the source code it would be great.
@cbielow @hroest I was wondering if we have the choice to override "noexcept"ness if we go back to manually specified constructors (before the changes in https://github.com/OpenMS/OpenMS/pull/4276). And if so, if we should go this potentially dangerous route. According to https://developercommunity.visualstudio.com/content/problem/425370/c11-noexcept-implementation-still-a-performance-lo.html (and the linked slides) manual noexcept in MSVC can even lead to worse performance in some cases.
If we leave it like it is now, I think we need a platform-specific test case in our test suite.

**Comment by nateglasser** [comment]
Yes I'd be happy to make the pull request. I was trying to get this set up on my second machine where things didn't go so smoothly... It has an older version of Anaconda3 on it which was polluting the CMAKE search directories and messing up the dependencies. Once I can reproduce the build, I will get the pull request ready!

**Comment by hroest** [comment]
>  @cbielow @hroest I was wondering if we have the choice to override "noexcept"ness if we go back to manually specified constructors (before the changes in #4276). And if so, if we should go this potentially dangerous route. According to https://developercommunity.visualstudio.com/content/problem/425370/c11-noexcept-implementation-still-a-performance-lo.html (and the linked slides) manual noexcept in MSVC can even lead to worse performance in some cases.

yes, we can do this and I think we have in some instances already - I think it would be ok to have a platform-specific test for these cases at least until we have a solution for MSVS

**Comment by jpfeuffer** [comment]
Hi everyone. Was there any progress on this issue? We now need VS2019 due to bugs in OpenMP.

**Comment by jpfeuffer** [comment]
Done
