### ISSUE TITLE
Constants.py missing in pyopenms pip installer

### ISSUE THREAD

**Issue by JeeH-K** [OpenMS/OpenMS#4293]
pyopenms through pip installer didn't include Constants.py, so I had to copy the file from OpenMS/src/pyOpenMS/pyopenms. Maybe a bug?

**Comment by hroest** [comment]
yes, this seems like a bug, sorry about that

**Comment by timosachsenberg** [comment]
does this need to be fixed in our build scripts?

**Comment by jpfeuffer** [comment]
Probably. Where does it have to go in the pip package?

**Comment by timosachsenberg** [comment]
maybe the setup.py script? https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/setup.py

**Comment by jpfeuffer** [comment]
yes probably but what needs to be the location in the end?

**Comment by poshul** [comment]
@JeeH-K where is Constants.py supposed to be in the installed package?

**Comment by JeeH-K** [comment]
Where the setup.py file is located is fine as the file, [https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pyopenms/Constants.py](https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pyopenms/Constants.py).

**Comment by hroest** [comment]
yes, it should be in the main folder and should get imported here

https://github.com/OpenMS/OpenMS/blob/f531f2fda5833ce1be284c50e798a0b999c0528d/src/pyOpenMS/pyopenms/python_extras.py#L1

**Comment by poshul** [comment]
I can confirm that the current pip egg doesn't have Constants.py, and that building the egg myself results in a product that does include Constants.py. Where does the pip version come from?

**Comment by timosachsenberg** [comment]
Ok so this seems to be fixed? Or does something unexpected happen on the build machines for pip?

**Comment by timosachsenberg** [comment]
@hroest I will close this as fixed. Feel free to reopen if you think this is still an issue.
