### ISSUE TITLE
Luciphoradapter crashes

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#4301]
Hello,

when using Luciphoradapter, the tool/adapter crashes. 
This is with the latest Luciphor version (Luciphor2). There error message is: 
"Error: File not found (the file 'D:\data\Oliver\OMS-tmp\20191011_135928_27612_1\luciphor-trial\004_LuciphorAdapter\out\AD2_KsAmt5_wt_LB.idXML' could not be found)"

...this looks like a problem with id-file conversion. Luciphor2 expects pepxml, so I assume (but do not for sure) that the adapter might perform a conversion of the idxml input. 

Thanks for your support!

**Comment by oliveralka** [comment]
This is the current version in the THIRDPARTY module:

https://github.com/OpenMS/THIRDPARTY/tree/master/All/LuciPHOr2

luciphor2 (JAVA-based version of Luciphor)
Version: 1.2014Oct10

Could you give it a try e.g. run your version and the THIRDPARTY one using -debug to see if there are any additional error messages?

**Comment by oliverschilling** [comment]
Good morning and thanks for the swift response. Below is the output with debug =3. Towards the end, you will see an error message.

Thanks!

08:14:14 NOTICE: LuciphorAdapter of node #4 started. Processing ...
File 'C:/Users/oliver2/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in 'C:/Users/oliver2/.OpenMS/OpenMS.ini' with defaults!
Default-Parameter 'home_dir' overridden: '' --> 'D:\data'!
Default-Parameter 'temp_dir' overridden: '' --> 'D:\data\Oliver\OMS-tmp'!
Debug level (after ini file): 3
Value of string option 'no_progress': 0
Value of string option 'java_executable': java
Value of string option 'force': 0
File 'C:/Users/oliver2/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in 'C:/Users/oliver2/.OpenMS/OpenMS.ini' with defaults!
Default-Parameter 'home_dir' overridden: '' --> 'D:\data'!
Default-Parameter 'temp_dir' overridden: '' --> 'D:\data\Oliver\OMS-tmp'!
Creating temporary directory 'D:\data\Oliver\OMS-tmp\20191015_081415_ukmz1005immz_28676_1\'
Value of string option 'id': D:\data\AD_Agostina\AD1_10\tandem.idXML
Checking input file 'D:\data\AD_Agostina\AD1_10\tandem.idXML'
Value of string option 'in': N:\AD_Agostina\AD1_10\AD2_KsAmt5_wt_LB.mzML
Checking input file 'N:\AD_Agostina\AD1_10\AD2_KsAmt5_wt_LB.mzML'
Value of string option 'out': D:\data\Oliver\OMS-tmp\20191011_135928_27612_1\luciphor-trial\004_LuciphorAdapter\out\AD2_KsAmt5_wt_LB.idXML
Checking output file 'D:\data\Oliver\OMS-tmp\20191011_135928_27612_1\luciphor-trial\004_LuciphorAdapter\out\AD2_KsAmt5_wt_LB.idXML'
Value of double option 'rt_tolerance': 0.1
Progress of 'loading spectra list':

  3.81 %               
  15.15 %               
  26.15 %               
  37.28 %               
  48.00 %               
  58.52 %               
  68.67 %               
  78.71 %               
  87.98 %               
  96.26 %               
-- done [took 9.45 s (CPU), 9.81 s (Wall)] -- 
Progress of 'loading chromatogram list':

-- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
<Checking output file 'D:\data\Oliver\OMS-tmp\20191011_135928_27612_1\luciphor-trial\004_LuciphorAdapter\out\AD2_KsAmt5_wt_LB.idXML'> occurred 2 times
Value of string option 'target_modifications': Phospho (S)
Value of string option 'target_modifications': Phospho (T)
Value of string option 'target_modifications': Phospho (Y)
Value of string option 'target_modifications': Phospho (H)
Value of string option 'fragment_method': HCD
Value of double option 'fragment_mass_tolerance': 20.0
Value of string option 'fragment_error_units': ppm
Value of double option 'min_mz': 150.0
Value of double option 'decoy_mass': 79.966330999999997
Value of int option 'max_charge_state': 5
Value of int option 'max_peptide_length': 50
Value of int option 'max_num_perm': 16384
Value of double option 'modeling_score_threshold': 0.95
Value of double option 'scoring_threshold': 0.0
Value of int option 'min_num_psms_model': 50
Value of int option 'num_threads': 6
Value of string option 'run_mode': 0
Value of string option 'neutral_losses': styh -H3PO4 -97.97690
Value of string option 'decoy_neutral_losses': X -H3PO4 -97.97690
Value of int option 'java_memory': 14500
Value of int option 'java_permgen': 0
Value of string option 'executable': C:\Program Files\OpenMS-2.4.0-nightly-2019-08-28\share\OpenMS\THIRDPARTY\LuciPHOr2\luciphor2.jar
C:\jenkins\ws\openms_nightly_packaging\c2e226b2\source\src\openms\source\APPLICATIONS\TOPPBase.cpp(1653): COMMAND: java -Xmx14500m -jar C:\Program Files\OpenMS-2.4.0-nightly-2019-08-28\share\OpenMS\THIRDPARTY\LuciPHOr2\luciphor2.jar D:\data\Oliver\OMS-tmp\20191015_081415_ukmz1005immz_28676_1\luciphor2_input_template.txt
Executing: java
Executed java successfully!
Error: File not found (the file 'D:\data\Oliver\OMS-tmp\20191011_135928_27612_1\luciphor-trial\004_LuciphorAdapter\out\AD2_KsAmt5_wt_LB.idXML' could not be found)
Error occurred in line 65 of file C:\jenkins\ws\openms_nightly_packaging\c2e226b2\source\src\openms\source\FORMAT\TextFile.cpp (in function: void __cdecl OpenMS::TextFile::load(const class OpenMS::String &,bool,int,bool)) !
Keeping temporary files in directory 'D:\data\Oliver\OMS-tmp\20191015_081415_ukmz1005immz_28676_1\'. Set debug level to 2 or lower to remove them.

==============================================================================
08:14:39 ERROR: LuciphorAdapter failed!

**Comment by oliveralka** [comment]
Currently the "Value of string option 'neutral_losses': ", seems to be `styh -H3PO4 -97.97690` instead of`sty -H3PO4 -97.97690` is that intentional? 

If the change of the string option does not fix it, would you be able to provide a small example set for debug purposes?

**Comment by oliverschilling** [comment]
Hello

yes, those settings were intentional. But I have now all tried with the default settings; same problem. Data/ workflow etc are here: https://www.dropbox.com/s/mg09r2qox2vn5x9/luciphor-adapter.zip?dl=0

I have also tried it directly from the command line - in this case Luciphor works, but there are insufficient phospho-peptides (which make sense)(see picture)
![IMG_3297](https://user-images.githubusercontent.com/8565908/66843841-9e6e1900-ef6d-11e9-982b-5880979423d2.JPG)
. Would that cause the error in the OMS tool? If yes, a somewhat clearer error message would help...

**Comment by oliveralka** [comment]
So there is no output produced by LuciPhor2 in the end. 

You are right a less cryptic error message would be useful. I will think about it. 
At least something like "LuciPhor2 did not generate any output." (maybe add the java command for testing purposes).

**Comment by oliveralka** [comment]
@jpfeuffer 
LuciphorAdapter uses  `runExternalProcess_(java_executable.toQString(), process_params)`
which already is able to report the stdout/stderr of the qprocess. Currently report setting needs `debug > 10`.  Would it make sense to set it to a lower number e.g. 3 ?

**Comment by jpfeuffer** [comment]
Yes, fine with me. It was a relatively arbitrary decision. It should be a bit higher than the normal OpenMS debug output, other than that it does not matter.
But I think a check for empty output should always be there. And I usually choose to fail although in very rare case you might want to continue with empty output. (One could use the --force flag to overwrite this behaviour).

**Comment by oliveralka** [comment]
The problem here is that the pepXML, is not empty, even if LuciPhorAdapter reports:

`You do not have enough PSMs with a score > 0.95 to accurately model the data. (Minimum number of PSMs required per charge state: 50)`

So I have to check what the easiest way around that would be.

**Comment by oliveralka** [comment]
@oliverschilling 
It seems we do not have a THIRDPARTY test for LuciPhor2. Would it be ok for you, if we use a small subset of your example data for that purpose?

**Comment by oliverschilling** [comment]
of course!

**Comment by oliveralka** [comment]
We added an example and the error message for this case should be clearer now - thanks for pointing that out. Do you have any additional questions or can we mark the issue as resolved?

**Comment by oliverschilling** [comment]
Thanks; pls mark the issue as resolved.
