### ISSUE TITLE
What is the meaning of the IDFilter's output ?

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4313]
Hi, 
What does the output of the IDFilter mean ? It says:

Before filtering:
1 protein identification(s) with 7839 protein hit(s)
....

What is protein identification ? And what is it's difference from protein hit ?

**Comment by jpfeuffer** [comment]
Hi,

Yes the term "protein identification" is a bit confusing. It means one "run" of a peptide and protein identification pipeline.
You only might have multiple protein identification (runs) if you merged multiple files or ran multiple search/inference engines on a file.
Protein Hits are the actual number of proteins matched in your database that have a score better than the one you filtered for.

**Comment by mash23** [comment]
Ok but the IDFilter also prints "25351 peptide identification(s) with 25351 peptides hit(s)".
What is "peptide identification" here ?

**Comment by timosachsenberg** [comment]
A peptide identification usually corresponds to a spectrum and a peptide hit is a PSM.
In your case, each of the 25351 identified spectra had one PSM.
@OpenMS/core what about changing the output into something more beginner-friendly like in https://github.com/OpenMS/OpenMS/pull/4320

**Comment by hendrikweisser** [comment]
Question has been answered and Timo's improvement has been merged, so I believe this can be closed.
