### ISSUE TITLE
AccurateMasssearch : Isotope Intensities not exported as advertised

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#4314]
The parameter `exportIsotopeIntensities` in `AccurateMasssearch` claims that extra columns will be added to the mzTab output:

defaults_.setValue("mzTab:exportIsotopeIntensities", 0, "[featureXML input only] Number of extra columns in mzTab output, which provide intensities up to the x'th isotope. '0' to deactivate, '1' for monoisotopic peak, etc. If a feature does not have a certain isotope, 'null' will be reported.");
    defaults_.setMinInt("mzTab:exportIsotopeIntensities", 0);

However, from the code it looks like only one column gets added, namely `opt_global_MTint`

https://github.com/OpenMS/OpenMS/blob/ecf1a5d4b7a0b56d158b0c4032ae54b766137a5d/src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp#L1196-L1213

**Comment by oliveralka** [comment]
This was changed in a PR in Juli 2018. It should report a comma-separated list, which I guess is more mzTab like. 

The parameter description seems to have been forgotten at that point.

**Comment by oliveralka** [comment]
I would suggest a bool value, which then writes all in one column in a comma-separated fashion. 
@timosachsenberg What do you think? Or revert to original mztab multi-column output? 
```
opt_global_MTint
--
12743.5571
77075.707501,13072.681000
```
