### ISSUE TITLE
question: use OpenMS.dll on windows

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4318]
Hi @cbielow 
what are the possibilities to ship the OpenMS.dll on windows for external use?
I guess either compiling it as a lib and then linking against it or using the DllLoadLibrary glory on windows?

**Comment by cbielow** [comment]
That depends a bit what you mean by `external use`.
If you want to link against it, you need to ship the dll and the .lib, plus making sure that you use the same toolset (i.e. version of visual studio) to link (see https://docs.microsoft.com/en-us/cpp/porting/overview-of-potential-upgrade-issues-visual-cpp?view=vs-2019). 

And if you just want dynamic linking at runtime (e.g. for usage in C#), then use `DllLoadLibrary`, as mentioned.
https://docs.microsoft.com/en-us/windows/win32/dlls/run-time-dynamic-linking
