### ISSUE TITLE
a bug for OpenSwathDecoyGenerator using shuffle method

### ISSUE THREAD

**Issue by lifeinfo** [OpenMS/OpenMS#4319]
OpenSwathDecoyGenerator
Version: 2.4.0-HEAD-2018-10-26 Feb  9 2019, 01:15:06, Revision: 9690d06
let all parameters default, we found
target PeptideSequence: SRPPFLPLPLTKPR
decoy PeptideSequence: STPPLFLGPCAKPK
the  amino acids in two sequences are different, e.g. why 'A'  appear in decoy? It dose not in target sequence. And not just these two, all the amino acids in target/decoy paired sequences are not the same.

**Comment by grosenberger** [comment]
This is intended behavior in OpenSwathDecoyGenerator. For DIA/SWATH, we typically do not only do reversing/shuffling of the target sequences, but also "mutations" to decrease the similarity of decoys. This process is described in more detail in these papers:

- https://pubs.acs.org/doi/abs/10.1021/pr900947u
- https://www.nature.com/articles/nbt.2841
- https://doi.org/10.1074/mcp.RA117.000314

**Comment by lifeinfo** [comment]
Thank you very much

**Comment by lifeinfo** [comment]
I have look through these papers, but I still don't find the any description about 'mutations' method and it's performance. How can we trust the 'mutations' stratge is effective?

**Comment by grosenberger** [comment]
The supplementary notes of the 2014 OpenSWATH and the 2017 Biognosys MCP papers describe the methods and validation in more detail. Note: We modified the shuffle algorithm a few months ago to improve robustness.

**Comment by lifeinfo** [comment]
So, actually, the problem I met is because you modified the shuffle algorithm.  I know the original shuffle algorithm will not 'mutation'. I mean it will not add new amino acids.

**Comment by grosenberger** [comment]
The original algorithm for 'shuffle' in OpenSwathDecoyGenerator was adapted from SpectraST. There, additional amino acids are added to the sequence if a sequence can not be shuffled sufficiently, e.g. 'AAAAAAAAAAK'. This was also the case in earlier versions of the decoy generator, but now we modified the algorithm to have a higher success rate in generating decoy PQP or assays that represent the targets optimally but don't capture actual signals.

**Comment by hroest** [comment]
@grosenberger this is not documented but I think you can disable that behavior if you set `-max_attempts ` less than 9 (e.g. to 8)

**Comment by lifeinfo** [comment]
"mutation" strategy changed the m/z of precursors. How could you make sure the distribution of decoy and target are the same? And how can you measure similarity  between decoy and target?
