### ISSUE TITLE
pyOpenMS: provide numpy accessors for Matrix class

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4322]
for speed reasons it would be beneficial to provide a getter to a numpy matrix.
Similar to get_peaks in MSSpectrum

**Comment by timosachsenberg** [comment]
E.g. this currently takes several minutes:
```
        data = np.ndarray(shape=(int(rows), int(cols)), dtype=np.float64)
        for i in range(int(rows)):
            for j in range(int(cols)):
                data[i][j] = bilip.getData().getValue(j,i)
       img.setImage(data) # for visualization in pyqtgraph
```

**Comment by hroest** [comment]
Yes, this is currently not implemented in

https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/Matrix.pxd

You would have to create an addon file and do something similar to this for `Matrix.pyx`: 

https://github.com/OpenMS/OpenMS/blob/9d92d1863dc8cb7c0c8590a54d62da92245ab0d5/src/pyOpenMS/addons/MSSpectrum.pyx#L11-L35

basically create a numpy array in C and then copy the data into it = very fast

**Comment by hroest** [comment]
> E.g. this currently takes several minutes:

how large are your matrices? I just did some performance testing of this code 

```
import pyopenms
import numpy as np
m = pyopenms.MatrixDouble()
N = 9000
m.resize(N+1, N+1, 5.0)

rows = N
cols = N
data = np.ndarray(shape=(int(rows), int(cols)), dtype=np.float64)
for i in range(int(rows)):
            for j in range(int(cols)):
                data[i][j] = m.getValue(j,i)
```

this is about 617 MB of data and takes on my computer about 42 seconds (so not minutes)

```
$ time python /tmp/test1.py 

real	0m42.964s
user	0m42.448s
sys	0m0.752s
```

**Comment by hroest** [comment]
@timosachsenberg  can you try https://github.com/OpenMS/OpenMS/pull/4453 - it should be 60x faster using a memory view in numpy
