### ISSUE TITLE
build error beyond my (limited) abilities

### ISSUE THREAD

**Issue by abelew** [OpenMS/OpenMS#4324]
Hello,
  I just updated my sources to commit 9d92d1863dc8cb7c0c8590a54d62da92245ab0d5.  I created a fresh build tree and started a new compile and received the following:

openms/source/ANALYSIS/OPENSWATH/IonMobilityScoring.cpp:315:93: error: no matching function for call to ‘OpenSwath::MRMScoring::initializeXCorrPrecursorContrastMatrix(<brace-enclosed initializer list>, std::vector<std::vector<double> >&)

openms/source/ANALYSIS/OPENSWATH/IonMobilityScoring.cpp:334:89: error: no matching function for call to ‘OpenSwath::MRMScoring::initializeXCorrPrecursorContrastMatrix(<brace-enclosed initializer list>, <brace-enclosed initializer list>)’

openms/source/ANALYSIS/OPENSWATH/IonMobilityScoring.cpp:467:56: error: no matching function for call to ‘OpenSwath::MRMScoring::initializeXCorrMatrix(std::vector<std::vector<double> >&)’

gcc provided the potentially relevant note:
include/OpenMS/OPENSWATHALGO/ALGO/MRMScoring.h:126:10: note:   candidate expects 3 arguments, 2 provided

The full set of commands run were:
git pull
git submodule update --init contrib
rm -r contrib-build build
cd contrib-build
cmake -DCMAKE_INSTALL_PREFIX=/sw/local/openms -DBUILD_TYPE=ALL \
  ../contrib
make
cd ../build
cmake -DCMAKE_INSTALL_PREFIX=/sw/local/openms/201904 \
  -DOPENMS_CONTRIB_LIBS="../contrib-build" -DBOOST_USE_STATIC=OFF \
  ..
make

Thank you for your time.

**Comment by cbielow** [comment]
thanks for reporting this.
which version of g++ are use using?

**Comment by hroest** [comment]
is this a fresh checkout? I think someting is wrong with your checkout:


```
 include/OpenMS/OPENSWATHALGO/ALGO/MRMScoring.h:126:10: note: candidate expects 3 arguments, 2 provided
```

however, in 9d92d18 the line 126 is empty: 

https://github.com/OpenMS/OpenMS/blob/9d92d1863dc8cb7c0c8590a54d62da92245ab0d5/src/openswathalgo/include/OpenMS/OPENSWATHALGO/ALGO/MRMScoring.h#L126

so it seems that you are working with an older version of MRMScoring.h which causes the issue. Can you please check whether your version is the same as the one here: https://github.com/OpenMS/OpenMS/blob/9d92d1863dc8cb7c0c8590a54d62da92245ab0d5/src/openswathalgo/include/OpenMS/OPENSWATHALGO/ALGO/MRMScoring.h

**Comment by abelew** [comment]
Hello,
  I just downloaded the raw MRMScoring.h from HEAD and did a diff of my copy to it and came up empty.  I am guessing the Line 126 note from gcc is referring to initialXCorrPrecursorMatrix above (I also tested by doing a vi +126 of the header, and observed an empty line as well.).

**Comment by abelew** [comment]
Oh crap in a hat, I see what is happening.  The compilation is pulling headers from the previous installation rather than keeping it in the build tree.

**Comment by hroest** [comment]
this is indeed strange, especially as there are 2 functions (overloaded) for `initializeXCorrPrecursorContrastMatrix` one of which accepts 2 arguments:

https://github.com/OpenMS/OpenMS/blob/9d92d1863dc8cb7c0c8590a54d62da92245ab0d5/src/openswathalgo/include/OpenMS/OPENSWATHALGO/ALGO/MRMScoring.h#L128-L131

So I still suspect that somehow your compiler is using an outdated header file. Can you try to make a new build folder, run cmake again and compile again? I see that you worked in an old build folder, so maybe that was the issue? make sure your build folder is empty before you start.

just to be sure I was compiling here again with gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609 and it all worked. We also have nightly tests that all seem to work as well.

**Comment by abelew** [comment]
Linking did indeed fail for TOPPAS, invoking ldd on my freshly generated libOpenMS.so I see that it was linked using a bunch of OS installed libraries (libboost most notably, but also libhdf5) rather than the ones in my contrib-build directory.  I assume therefore that this is a problem with my cmake invocation.  This at least I should know enough about to diagnose and solve.  I am sorry for the trouble.

**Comment by hendrikweisser** [comment]
Thanks for the update, @abelew. Seems like the problem is solved.

**Comment by abelew** [comment]
It is indeed solved.  I am not sure if it is trivial, but I think it would be worth while to have cmake set CXX flags appropriate to keep gcc from using out of tree OpenMS-specific headers like /usr/include/OpenMS.
