### ISSUE TITLE
OpenSwathWorkflow error: " Found SWATH scan (MS level 2 scan) without a precursor. Canno t determine SWATH window."

### ISSUE THREAD

**Issue by GregStacey** [OpenMS/OpenMS#4331]
I'm trying to use OpenMS to identify proteins in a DIA file. We've successfully created the spectral library from a separate DDA file with Mobi-DIK, but we're having errors when trying to run OpenSwathWorkflow with the spectral library on the DIA file. The command and error are below.

We have the same error when searching the mzXML and mzML versions of the DIA file. Both filetypes were made by converting Bruker data (.d format) using proteoWizard/MSconvert (version 3.0.19295 64-bit). We're using OpenMS-2.4.0-nightly-2019-06-27

C:\Program Files\OpenMS-2.4.0-nightly-2019-06-27\bin>OpenSwathWorkflow.exe -in E
:/Greg/spectral_library/data/search_files/24Sept19.mzXML -tr E:/Greg/spectral_li
brary/library_all5.tsv -out_tsv E:/Greg/spectral_library/search_24Sept19_all5.ts
v -force
Since neither rt_norm nor tr_irt is set, OpenSWATH will not use RT-transformatio
n (rather a null transformation will be applied)
Progress of 'Load TSV file':
-- done [took 23.30 s (CPU), 23.30 s (Wall)] --
Loaded 12972 proteins, 44802 compounds with 1119915 transitions.
Loading mzXML file E:/Greg/spectral_library/data/search_files/24Sept19.mzXML usi
ng readoptions normal
Progress of 'Loading metadata file E:/Greg/spectral_library/data/search_files/24
Sept19.mzXML':
Will analyze the metadata first to determine the number of SWATH windows and the
 window sizes.
Invalid parameter: Found SWATH scan (MS level 2 scan) without a precursor. Canno
t determine SWATH window.

**Comment by hroest** [comment]
Hi Greg

This seems to be an issue with proteowizard, I am not sure that it currently supports DIA PASEF correctly. Can you look into the mzML file to see whether the DIA windows are correctly annotated with a precursor isolation window?

We are currently using diapysef for data conversion: http://openswath.org/en/latest/docs/dataconversion.html which is what I would recommend at this point, the easiest approach would be to follow the documentation page linked here and then it should work.
