### ISSUE TITLE
pyOpenms: is there any method of getting protein id and value (target/decoy)?

### ISSUE THREAD

**Issue by cherrypas** [OpenMS/OpenMS#4335]
Hi everyone!
I have a problem with handling protein information in idXML file. Here is an example of a protein hit:

<ProteinHit  **id="PH_0"** accession="sp|ACCESSION|NAME" score="1" sequence="" >
 <UserParam type="string" name="target_decoy" **value="target"**/> </ProteinHit>

In the pyOpenms documentation I've found that the accession, the score and the sequence might be obtained by the corresponding methods: getAccession() etc. 
But there also are some other parameters so is there any easy way of getting them as well ? I am mostly interested in getting the "id" and the "value".

I can use the xml.etree.ElementTree package for example to handle this but I wonder if such a thing exists in the pyOpenms package.

**Comment by timosachsenberg** [comment]
Hi,
there is no need to fiddle around with the XML.
If links between PSMs (PeptideHits) and Proteins are present (e.g., PeptideIndexer has been executed). You can query the target_decoy information via protein_hit.getMetaValue("target_decoy")
If you have a peptide hit (PSM) you can query to which protein accession it matches using
something like:
```
for i in len(ph.getPeptideEvidences()):
  ph.getPeptideEvidences()[i].getProteinAccession() 
```
as well as the position it matches to in the protein, the flanking amino acids etc.

Let me know if that works if you add that to the code in:
https://pyopenms.readthedocs.io/en/latest/datastructures_id.html#storage-on-disk

**Comment by hroest** [comment]
@cherrypas I dont think there is currently a way to retrieve the id but I dont think you need it since the id is simply a number that starts from 1 and goes to N. Regarding the user params, they are stored in meta values and should be accessible as follows:

```
>>> protein_hit.getMetaValue("target_decoy")
b'target'

```

@timosachsenberg seems like a good idea to add this to the documentation?

**Comment by cherrypas** [comment]
Thank you both very much for your answers! Really helping.

@hroest The id shows the position that a protein holds in the resulting list, doesn't it ? Are there no cases when it may be useful to know this position ?

**Comment by timosachsenberg** [comment]
@cherrypas the id is really just used to reference between the PSM and protein part in the XML file.
In the actual data structures, this mapping is done via the accessions. The order in the XML file is also kind of arbitrary so you can, e.g., not really deduce that the first entry has the best score. Also, note that the same data structures can be filled either by idXML, pepXML or mzIdentML file (each has different XML structure). So best is to only work on the data structures after reading them in.
