### ISSUE TITLE
SiriusAdapter keeps temporary files in -converter_mode

### ISSUE THREAD

**Issue by alexeigurevich** [OpenMS/OpenMS#4337]
Background: `-converter_mode` is added to SiriusAdapter in the `developer` branch of OpenMS. It is not available in 2.4.0 release and in the `master` branch. The goal of the option is just to create `.ms` file and reset further execution of the adapter. This `.ms` can be later processed with `sirius` binary.

Problem: whenever you run SiriusAdapter in `-converter_mode` you will get your temporary directory messed up with a new `.ms` which would never be removed. On Linux, it is just under `/tmp/`, on macOS, it is a bit more complicated, for myself they were stored under `/private/var/folders/b_/b_vxbtn56h7ffb8jssmbb1qc0000gn/T/`.

Reason: temporary file is copied [here](https://github.com/OpenMS/OpenMS/blob/develop/src/utils/SiriusAdapter.cpp#L226) but not removed afterward since the adapter finishes execution just [few lines after](https://github.com/OpenMS/OpenMS/blob/develop/src/utils/SiriusAdapter.cpp#L229) this.
Note: removing of temp files and dirs in SiriusAdapter is [here](https://github.com/OpenMS/OpenMS/blob/develop/src/utils/SiriusAdapter.cpp#L295) but this section never reached in `-converter_mode`.

@oliveralka please take a look!

**Comment by oliveralka** [comment]
I will take a look, thanks for pointing that out!

**Comment by jpfeuffer** [comment]
Seems to be fixed.
