### ISSUE TITLE
No matching distribution found for pyopenms for Windows 10 x86_64

### ISSUE THREAD

**Issue by BorderCloud** [OpenMS/OpenMS#4344]
I read in the [last documentation](https://pyopenms.readthedocs.io/en/latest/installation.html) that pyopenms 2.4 is available for Windows 64 but pip cannot found the version 2.4.

```
> systeminfo
Microsoft Windows 10.0.17763 version 17763 AMD64

>python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32

>pip install pyopenms
ERROR: Could not find a version that satisfies the requirement pyopenms
 (from versions: 2.3.0.linux-x86_64, 2.3.0.1.linux-x86_64, 2.3.0.2.linux-x86_64, 2.3.0.3.linux-x86_64)
ERROR: No matching distribution found for pyopenms
```
Have you an idea to resolve this installation problem ?
Thanks

**Comment by hroest** [comment]
this is because we dont support Python 3.8 yet (we only have packages for 3.5, 3.6 and 3.7): https://pypi.org/project/pyopenms/2.4.0/#files

**Comment by BorderCloud** [comment]
Thanks, It works with the version 3.7.5 of Python.

**Comment by RmStorm** [comment]
Hi I'm running into the same problem on linux and I'm wondering if it's possible to get support for python 3.8? I imagine that for someone with the right knowledge it's possible to create binaries for 3.8 and push them to pypi.

Is it possible to get this issue re-opened until 3.8 binaries are uploaded to pypi?

I've tried building pyopenms myself but I'm getting some errors:
```
FROM python:3.8-buster

RUN apt-get -y update
RUN apt-get -y install build-essential cmake autoconf patch libtool git automake
RUN apt-get -y install qtbase5-dev libqt5svg5-dev libqt5opengl5-dev
RUN apt-get -y install libboost-regex-dev libboost-iostreams-dev libboost-date-time-dev libboost-math-dev libboost-random-dev \
	libsvm-dev libglpk-dev zlib1g-dev libxerces-c-dev seqan-dev libbz2-dev coinor-libcoinmp-dev libhdf5-dev


WORKDIR /home
RUN mkdir contrib-build
RUN mkdir OpenMS-build
RUN git clone --depth=1 --branch Release2.4.0 https://github.com/OpenMS/OpenMS.git

WORKDIR /home/OpenMS
RUN git submodule update --init contrib

WORKDIR /home/contrib-build

RUN cmake -DBUILD_TYPE=SEQAN ../OpenMS/contrib
RUN cmake -DBUILD_TYPE=WILDMAGIC ../OpenMS/contrib
RUN cmake -DBUILD_TYPE=EIGEN ../OpenMS/contrib

WORKDIR /home/OpenMS-build

RUN pip install cython nose numpy autowrap
RUN cmake -DOPENMS_CONTRIB_LIBS="/home/contrib-build" -DBOOST_USE_STATIC=OFF -DPYOPENMS=ON /home/OpenMS
RUN make pyopenms
```
Maybe this will be a good starting point for someone that is willing to pick this up?

**Comment by jpfeuffer** [comment]
See also #4387 you can also solve it by pinning autowrap to a previous version 0.19.0

**Comment by RmStorm** [comment]
I tried pinning autowrap to 0.19.0 but there is still errors happening.

**Comment by hroest** [comment]
solved with https://github.com/OpenMS/OpenMS/pull/4486 and the wheel is available on PyPI https://pypi.org/project/pyopenms/2.4.0/#files
