### ISSUE TITLE
Linking CXX shared library fails in compilation

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#4347]
Dear all

I am trying to compile OpenMS on Ubuntu v 18.04. ...this used to work fine earlier this year but now I am constantly running into this error:
[27%] Linking CXX shared library ../../lib/libOpenMS.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libboost_regex.a(regex.o): relocation R_X86_64_PC32 against symbol `_ZTVN5boost11regex_errorE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/openms/CMakeFiles/OpenMS.dir/build.make:17383: recipe for target 'lib/libOpenMS.so' failed
make[2]: *** [lib/libOpenMS.so] Error 1
CMakeFiles/Makefile2:1146: recipe for target 'src/openms/CMakeFiles/OpenMS.dir/all' failed
make[1]: *** [src/openms/CMakeFiles/OpenMS.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Here are the commands:
sudo apt-get install libboost1.62-dev
sudo apt-get install build-essential cmake autoconf patch libtool git automake
sudo apt-get install qtbase5-dev libqt5svg5-dev
sudo apt-get install libeigen3-dev libsqlite3-dev libwildmagic-dev libboost-random1.62-dev \
     libboost-regex1.62-dev libboost-iostreams1.62-dev libboost-date-time1.62-dev libboost-math1.62-dev \
     libxerces-c-dev libglpk-dev zlib1g-dev libsvm-dev libbz2-dev seqan-dev coinor-libcoinmp-dev

cd OpenMS
git submodule update --init contrib

cd ..
mkdir contrib-build

cd contrib-build
cmake -DBUILD_TYPE=ALL -DNUMBER_OF_JOBS=8 -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang /home/oliver/openms-compilation/OpenMS/contrib 

cd ..
mkdir OpenMS-build
cd  OpenMS-build
cmake -DQt5_DIR=/usr/local/Cellar/qt/5.10.1/lib/cmake/Qt5 -DOPENMS_CONTRIB_LIBS=/home/oliver/openms-compilation/contrib-build /home/oliver/openms-compilation/OpenMS 

make -j 8

The error occurs in the final make command

As always, your support is greatly appreciated!

**Comment by jpfeuffer** [comment]
Hi!

It looks like the build system confuses the different boost versions that are available on your system. (Detail: ubuntu's static boost is built without the _fpic_ flag).
You might solve it by adding -DBOOST_USE_STATIC=OFF but I would also suggest that you only build/install one version of each dependency library (_either_ from out contrib package _or_ from your packaging system). The suggested way for everything except for QT is to use whatever is already installed on your system and build only the rest via the contrib.

We recently updated the (develop) documentation by adding a Warning in the corresponding section.
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/a16077.html

Let us know if you can resolve it with this.

**Comment by hroest** [comment]
@jpfeuffer shouldnt cmake check whether the correct version (shared / static) of the library is present?

**Comment by jpfeuffer** [comment]
CMake FindBoost in the legacy mode as we use it, searches for both shared and static. There is no "correct" version. Depends on how you want to build. If you have a preference, please always set BOOST_USE_STATIC as ON or OFF.
