### ISSUE TITLE
A little bug in the scan_regex of IDFileConvertor related to PercolatorOutfile.cpp

### ISSUE THREAD

**Issue by BioWu** [OpenMS/OpenMS#4350]
```
    if (lookup.reference_formats.empty())
    {
      // MS-GF+ Percolator (mzid?) format:
      lookup.addReferenceFormat("_SII_(?<INDEX1>\\d+)_\\d+_\\d+_(?<CHARGE>\\d+)_\\d+");
      // Mascot Percolator format (RT may be missing, e.g. for searches via
      // ProteomeDiscoverer):
      lookup.addReferenceFormat("spectrum:[^;]+[(scans:)(scan=)(spectrum=)](?<INDEX0>\\d+)[^;]+;rt:(?<RT>\\d*(\\.\\d+)?);mz:(?<MZ>\\d+(\\.\\d+)?);charge:(?<CHARGE>-?\\d+)");
      // X! Tandem Percolator format:
      lookup.addReferenceFormat("_(?<INDEX0>\\d+)_(?<CHARGE>\\d+)_\\d+");
    }
```
to 
```
    if (lookup.reference_formats.empty())
    {
      // MS-GF+ Percolator (mzid?) format:
      lookup.addReferenceFormat("_SII_(?<INDEX1>\\d+)_\\d+_\\d+_(?<CHARGE>\\d+)_\\d+");
      // Mascot Percolator format (RT may be missing, e.g. for searches via
      // ProteomeDiscoverer):
      lookup.addReferenceFormat("spectrum:[^;]+[(scans:)(scan=)(spectrum=)](?<INDEX0>\\d+)[^;]+;rt:(?<RT>\\d*(\\.\\d+)?);mz:(?<MZ>\\d+(\\.\\d+)?);charge:(?<CHARGE>-?\\d+)");
      // X! Tandem Percolator format:
      lookup.addReferenceFormat("_(?<INDEX0>\\d+)_(?<CHARGE>\\d+)_\\d+$"); // the $ is added here now.
    }
`
``
A bug occures when the names of your mzML files is like: XXX_[0-9]. The IDFileConvertor tool will report: `XXX peptide hits without charge state information.
XXX peptide hits without mass-to-charge information.`
It was because that the scan ids were not decoded correctly. 
Hope this will help you.
:)

**Comment by enetz** [comment]
@BioWu Thank you for pointing this out! Can you elaborate on the workflow you used to find this error?
1. Using mzML input files with names like XXX_0, XXX_1, XXX_2, etc.
2. Analyzing them with X!Tandem, outside of OpenMS. (Do you think this is X!Tandem specific?)
3. Using Percolator on the output, outside of OpenMS.
4. Running IDFileConverter to convert Percolator .psms files into idXML or mzid?

Is this correct?

**Comment by enetz** [comment]
@BioWu I am having trouble reproducing this error.
Can you provide a psms and mzML file and the parameters for IDFileConverter to reproduce this?

**Comment by Leon-Bichmann** [comment]
Alright so I also tested Percolator with the OpenMS THIRDPARTY test files renaming them to `XXX_0.idXLM` and variants of this, but can not reproduce this error.

The temporary pin and pout files are parsed correctly, as far as I can see...

**Comment by jpfeuffer** [comment]
I think this issue is mainly about files from external Percolator runs.
Try
1) Standalone XTandem on an mzML
2) Standalone Percolator on the tandemxml
3) IDFileConverter from "psms" to "idXML" 

In general, I don't think that the proposed change will hurt. So why not just implement it and make sure that tests pass?

**Comment by Leon-Bichmann** [comment]
ok will give it a try

**Comment by Leon-Bichmann** [comment]
Ok tested it once more with a freshly run idXML from XTandem:
1,2,3) all worked for me.
