### ISSUE TITLE
OpenMS MacOS Catalina (10.15) - Identity of the developer cannot be confirmed

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4357]
I tested one of our nightly installers with MacOS Catalina 10.15.1 (OpenMS-2.4.0-nightly-2019-11-01).  

TOPPView and TOPPAS are working upon approval: 
`TOPPAS.app is an app downloaded from the internet. Are you sure you want to open it? - Open`

All the other programs in ./bin can not be accessed. 
`"Tool x" can’t be opened because the identity of the developer cannot be confirmed`
 You can either push it into the trash or press ok. 

All of them show the signs of being in quarantine again (which was fixed for High Sierra https://github.com/OpenMS/OpenMS/issues/2816, https://github.com/OpenMS/OpenMS/issues/2488) 
`File in quarantine: drwxrwxr-x@`

This may indicate an issue with the signing on our Catalina build machine.

@jpfeuffer any ideas?

edit: Info:

> The app has been modified, and its code does not match the original signed code. The app may be broken or corrupted, or it may have been tampered with. If you think that an app has been damaged or tampered with, you should delete it by dragging it to the Trash.
> 
> Some apps and tools, such as AppleScript or JavaScript applications and some legacy tools, modify themselves after signing. These types of apps cannot be opened unless you override the security settings on your Mac. See Open an app by overriding security settings.

Override security settings:

> In the Finder  on your Mac, locate the app you want to open.
> 
> Most apps can be found in the Applications folder.
> 
> Control-click the app icon, then choose Open from the shortcut menu.
> 
> Click Open.
> 
> The app is saved as an exception to your security settings, and you can open it in the future by double-clicking it, just as you can any authorised app

This works but is not a viable solution.

**Comment by jpfeuffer** [comment]
https://stackoverflow.com/questions/58749789/how-do-determine-why-gatekeeper-is-rejecting-a-signed-executable
https://forums.developer.apple.com/thread/125567

Let's follow these discussions with exactly the same problem.

**Comment by oliveralka** [comment]
> If you distribute your software via a custom third-party installer, you need two rounds of notarization. First you notarize the installer’s payload (everything the installer will install). You then package the notarized (and stapled, as described in Staple the Ticket to Your Distribution) items into the installer and notarize it as you would any other executable. If you use a network installer, separately notarize both the installer and the items it downloads.

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/resolving_common_notarization_issues

It seems we have to somehow notarize all command-line tools (executables)

**Comment by oliveralka** [comment]
It seems that the executables can be used from the command line and in TOPPAS/TOPPView if the quarantine was removed recursively starting in the OpenMS directory:

```
cd OpenMS-2.5.0
sudo xattr -r -d com.apple.quarantine *
```

**Comment by jpfeuffer** [comment]
Cool! Thank you for investigating. Let's add this to the docu until we find time to switch to a better solution.

**Comment by lfnothias** [comment]
I had the same issue with version OpenMS >= 2.6 on macOS 11.6. The suggestion by @oliveralka worked. Thanks a lot !

**Comment by poshul** [comment]
Stale. Closing
