### ISSUE TITLE
Fix Ascore score calculation and improve performance

### ISSUE THREAD

**Issue by AnthonyOfSeattle** [OpenMS/OpenMS#4358]
Ascore is getting on in its years but it is still used in some pipelines (our lab's included) and as a baseline for new localization algorithms. So it is nice that OpenMS has a common implementation that can be drawn upon. There are just a couple issues that I would like to address.

Score calculation error:
 - The probability of a match in AScore::calculatePermutationPeptideScores_ and in AScore::compute should be multiplied by 2 * fragment_mass_tolerance to make the scores correct for a specific precision.
https://github.com/OpenMS/OpenMS/blob/3bf32aec5510faed51846a4673d33b7ea8d9cc18/src/openms/source/ANALYSIS/ID/AScore.cpp#L572-L573
https://github.com/OpenMS/OpenMS/blob/3bf32aec5510faed51846a4673d33b7ea8d9cc18/src/openms/source/ANALYSIS/ID/AScore.cpp#L167
 - The AScore::peptideScore_ function should be a weighted average but is not. This is does not affect final results but would be good for consistency.
https://github.com/OpenMS/OpenMS/blob/3bf32aec5510faed51846a4673d33b7ea8d9cc18/src/openms/source/ANALYSIS/ID/AScore.cpp#L383-L397

General enhancements:
 - In the algorithm, AScore::computeCumulativeScore_ computes the cumulative binomial probability every time it is called. This leads to a lot of slow downs, especially for high precision instruments since you spend more time only having a couple of matches (not 0 matches, because this automatically returns 1 and so is fast). We solved this before in our internal version of the algorithm by caching the probability calculations in an unordered_map. If this kind of idea works with the style of the code, it may be a good way to get fairly large speed up (like at least an order of magnitude or more).
 - Purely from a style standpoint, it seems that the ambiguity score portion of the AScore::compute could just be made its own function and AScore::getSpectrumDifference_ might be better placed in the .cpp file

I work a lot with this algorithm and would be happy to put in some pull requests to fix these, if you like.

**Comment by timosachsenberg** [comment]
Sounds great! We would be happy to integrate those fixes via a PR.

**Comment by AnthonyOfSeattle** [comment]
I'm looking to do a single PR for the fixes to the score calculation and I ran into a question about the score probabilities. The way the original paper defines them is for the Da case, where the fragment tolerance is constant. The ppm case is a bit trickier, since the window size technically changes with the mz. The way it is implemented now, it seems best to just define a single probability value for this setting. I think something conservative would be good, such as,

```
new_multiplier = 2 * fragment_mass_tolerance  * 1e-6 * max_fragment_mz 
p = new_multiplier * depth  / 100.0;
```

**Comment by timosachsenberg** [comment]
Sounds good to me! ADAIK there are other approaches to calculate the probabilities for relative tolerances taken in other scoring methods. But if we want to stick with AScore I think it is fine to choose max fragment mz as reference.

**Comment by AnthonyOfSeattle** [comment]
Sorry this took a while to get to. I was experimenting with caching strategies on the current implementation but my attempts seemed to slow down the code instead of helping. So the speed issue probably lies somewhere else. I'll keep experimenting and see if I can come up with something.

In the meantime, I wanted to at least address the scoring issues that I mentioned above, which are part of my PR.
