### ISSUE TITLE
FeatureFinderCentroided is too slow

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#4359]
using a single thread takes over 4h on a rather simple dataset.
There is definitely room for performance improvements there.

```
05:54:39 NOTICE: Output file '...\iPRG2015\JD_06232014_sample4_C.idXML' written.
Found 240664 seeds for charge 3.
Found 42727 feature candidates for charge 2.
Found 223719 seeds for charge 3.
Found 15634 feature candidates for charge 3.
Found 48480 seeds for charge 4.
Found 1302 feature candidates for charge 4.
Removed 43561 overlapping features.
65424 features left.

Abort reasons during feature construction:
- Could not extend seed: 583362
- Could not find good enough isotope pattern containing the seed: 131674
- Feature quality too low after fit: 26119
- Invalid feature after fit - too few traces or peaks left: 731121
- Invalid fit: Center outside of feature bounds: 5568
- Invalid fit: Fitted model is bigger than 'max_rt_span': 30451
- Invalid fit: Less than 'min_rt_span' left after fit: 34
FeatureFinderCentroided took 04:36:41 h (wall), 04:36:25 h (CPU), 16.08 s (system), 04:36:09 h (user).
```

**Comment by timosachsenberg** [comment]
Ok stupid question but was that run on the centroided data?

**Comment by cbielow** [comment]
yes (you almost scared me for a sec there, since I uses PPHR in auto-mode and thought it maybe did not detect the data correctly -- but it did).
Inspecting the input, the problem might be that there are a lot of 0 intensity peaks shouldering real peaks. When removing 0-intensity peaks before FF, the runtime drops to 39:16 m (wall). This is still quite long, but at 4x better than before... its a start...

**Comment by hroest** [comment]
@cbielow maybe we can remove zeros by default when (i) peak-picking and (ii) before starting the FFC

**Comment by timosachsenberg** [comment]
Note: This can be done by calling ThresholdMower without parameter

**Comment by mafreitas** [comment]
FWIW.  As @timosachsenberg mentions using ThresholdMower before FFC greatly speeds up the processing.  It would be nice if there were an option in FFC to set a threshold (relative or absolute).

For example, a 3 Gb mzML with ~6000 MS1 and total ~200,000 scans took only 8 minutes to run on an m5.large ec2 instance using 2 CPUs and 8GB ram

"FeatureFinderCentroided took 08:09 m (wall), 11:29 m (CPU), 1.44 s (system), 11:27 m (user)."

**Comment by timosachsenberg** [comment]
can you check if PR with the intensity filtering during loading fixes the issue and reopen if that is not the case?
