### ISSUE TITLE
PQP file definition

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4365]
For the integration in Galaxy I have a question regarding the pqp datatype (for which I could not find much information). 

For SQLite files galaxy identifies the type based on the set of tables in the data base. Is is a good idea to assume the following tables in a pqp file?

```
'COMPOUND', 'PEPTIDE', 'PEPTIDE_PROTEIN_MAPPING', 'PRECURSOR',                            'PRECURSOR_COMPOUND_MAPPING', 'PRECURSOR_PEPTIDE_MAPPING', 'PROTEIN',                            'TRANSITION', 'TRANSITION_PEPTIDE_MAPPING', 'TRANSITION_PRECURSOR_MAPPING'
```

In general, is there a good source of information for the data types used in OpenMS (besides https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/tutorial.html#tutorial_fileformat)

**Comment by bernt-matthias** [comment]
Since the help often mentions that file extension is used to determine the file type I would be interested to know the exact strings of the used file extensions.

**Comment by grosenberger** [comment]
Unfortunately, the documentation for ``PQP`` and ``OSW`` files is still rudimentary, as the new file formats are still work-in-progress (although we use them in production already). We are working towards more extensive documentation, however that will take a few more months.

We currently use ``PQP`` files for both proteomics and metabolomics applications and the populated tables slightly differ between the two. The data structure of the PQP files is defined [here](https://github.com/grosenberger/OpenMS/blob/develop/src/openms/source/ANALYSIS/OPENSWATH/TransitionPQPFile.cpp#L264) and I think any of the tables should help for identification. Please not that the associated ``OSW`` will have the exact same structure and in addition the scored features.

**Comment by hroest** [comment]
We have some documentation here in the `TransitionPQPFile` class:

https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/a07316.html#details

which is based on this part of the documentation in the code itself:

https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/ANALYSIS/OPENSWATH/TransitionPQPFile.h#L47

**Comment by bernt-matthias** [comment]
Does this mean that osw will have additional table(s) or just additional data. In the latter case wouldn't it be a good idea to store the type of database somewhere (e.g. in the version table)

**Comment by bernt-matthias** [comment]
After checking the links it seems that the tables VERSION GENE PEPTIDE_GENE_MAPPING were missing in my original list of tables. I extracted the list from a files in the OpenMS test data dir (OpenSwathWorkflow_13_input.pqp.tmp  OpenSwathWorkflow_14_input.pqp.tmp  TargetedFileConverter_1_output.pqp.tmp  TargetedFileConverter_3_output.pqp.tmp  TargetedFileConverter_9_output.pqp.tmp). Since none  of these files have these tables I guess I should ignore them for now?

**Comment by hroest** [comment]
> Does this mean that osw will have additional table(s) or just additional data. In the latter case wouldn't it be a good idea to store the type of database somewhere (e.g. in the version table)

yes, basically pqp is the spectral library and the input to OpenSWATH. On the other hand `osw` is the output of OpenSwath and for each assay in the `pqp` file it will contain identification results. So these are two different data types.



> After checking the links it seems that the tables VERSION GENE PEPTIDE_GENE_MAPPING were missing in my original list of tables. I extracted the list from a files in the OpenMS test data dir (OpenSwathWorkflow_13_input.pqp.tmp OpenSwathWorkflow_14_input.pqp.tmp TargetedFileConverter_1_output.pqp.tmp TargetedFileConverter_3_output.pqp.tmp TargetedFileConverter_9_output.pqp.tmp). Since none of these files have these tables I guess I should ignore them for now?

yes these tables were added recently

**Comment by bernt-matthias** [comment]
Thanks for the explanations

So it seems that osw files have the following tables in common with pqp files (checked for one file from the OpenMS tests): 

osw common tables: 
COMPOUND
PEPTIDE
PEPTIDE_PROTEIN_MAPPING
PRECURSOR
PRECURSOR_COMPOUND_MAPPING
PRECURSOR_PEPTIDE_MAPPING
PROTEIN
TRANSITION
TRANSITION_PEPTIDE_MAPPING
TRANSITION_PRECURSOR_MAPPING

and the following are unique to osw: 

FEATURE
FEATURE_MS1
FEATURE_MS2
FEATURE_TRANSITION
RUN

So I guess that I can make osw a "generalization" of pqp (ignoring the tables that are unique to pqp at the moment (VERSION GENE PEPTIDE_GENE_MAPPING) .. maybe they are added later).

**Comment by grosenberger** [comment]
Yes, that is correct.
