### ISSUE TITLE
pyOpenMS macOS Catalina 10.15.1

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4366]
Building pyOpenMS fails, due to SDK changes in macOS Catalina (10.15.1).

`xcrun --show-sdk-path:  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`
Headers can be found here: 
`/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include`

General: Check for specific MacOS Version from 10.15.* 
```
import platform
platform.mac_ver()[0] 
```
-> `'10.15.1'`

There are multiple possibilities to fix the SDK in src/pyOpenMS/setup.py:

1) add `-isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk ` to compile.args

The issue here is that this might be different in other versions or if the Xcode.app is installed, then the SDK seems to be in a different path:
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`

2) add python package e.g. subprocess, call `xcrun --sdk macosx --show-sdk-path` and add it to the `-isysroot`

Which one would be preferable or is there a better option available?

**Comment by jpfeuffer** [comment]
Which compiler binary is it using?
AFAIK the wrapper at /usr/bin/clang++ should have the current sysroot as default header path.
This is not true if you are using the `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/.../clang``

We can also just configure the setup.py with CMake (since CMake automatically determines the default sysroot of the used compiler executable), then we do not have to rely and parse the output of xcrun manually.

**Comment by oliveralka** [comment]
hm, I am using: 

`/Library/Developer/CommandLineTools/usr/bin/c++ ` which points to clang in the same directoy. 
`/usr/bin/clang++` also refers to InstalledDir: `/Library/Developer/CommandLineTools/usr/bin`

You are right, in the OpenMS cmake the sysroot was set correctly to `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk`   

As far as I know, env.py is created by our current cmake (environment variables for pyopenms setup.py).
We could add a variable for the sysroot there and add it to the compiler variables in setup.py if macOS is used, this should then work independent of the macOS version, or?

**Comment by jpfeuffer** [comment]
Yes that is a good idea.
Note that although /usr/bin/clang++ also refers to /Library/...... it has its specific sysroot hardcored in its environment. So if you force the use of this "symlink" it should work as well.

**Comment by oliveralka** [comment]
Closed via #4398
