### ISSUE TITLE
FeatureFinderMetabo - Using the peak height instead of peak area 

### ISSUE THREAD

**Issue by lfnothias** [OpenMS/OpenMS#4371]
I want to use the LC-MS peak height instead of the peak area in FeatureFinderMetabo.
There is a "quant _method"=median parameter but it is not clear from the description if this would actually do this ? Anyone has insight in this ?

**Comment by timosachsenberg** [comment]
It is used for direct injection data only where no elution profile is present.
Peak height is not directly supported but it wouldn't be too difficult to add if you need it.

**Comment by lfnothias** [comment]
That would be great ! Note that both methods are commonly used in metabolomics data analysis. In some application, peak height is sometime more robust than peak area, like in HILIC mode.

**Comment by timosachsenberg** [comment]
Probably add new quant method and string around here:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/KERNEL/MassTrace.h#L66
And adapt the MassTrace method to retrieve the "Area"

**Comment by poshul** [comment]
Merged into develop.
