### ISSUE TITLE
outdated / wrong test data

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4386]
In this file: https://github.com/OpenMS/OpenMS/blob/develop/src/tests/topp/FeatureFinderMetabo_2_noEPD.ini

For instance: `quant_method` should be in the node `mtd` but it is in `ffm`. Strange thing is that the works when the ini file is used in the test, but certainly not on the command line (and in the end it completely confuses my testing strategy for the Galaxy tools).

Suggestions are welcome, maybe I find the time to prepare a PR. 

(If I remember correctly I have seen some messages on outdated ini files when running the tests).

**Comment by cbielow** [comment]
this is intended behaviour to allow usage of `old` ini files. It comes with a warning which goes something like this
```
1842: Warning: Parameters file version (2.1.0) does not match the version of this tool (2.4.0-disabled-20191122).
1842: Your current parameters are still valid, but there might be new valid values or even new parameters. Upgrading the INI might be useful.
```

If an INI files contains parameters which are not a valid anymore, they are simply ignored. You should see a corresponding warning when running the tool with `-debug 10` for example (I dont remember the exact debug level required).

**Comment by bernt-matthias** [comment]
Good to know. Lets see if I can cope with this for the automatic generation of tests for the Galaxy OpenMS tools.

**Comment by bernt-matthias** [comment]
Just found a case where a parameter in the correct node: 

https://github.com/OpenMS/OpenMS/blob/38489c526d885a53f5de6f77caf70b1205a13019/src/tests/topp/MassTraceExtractor_2.ini#L23

gets overwritten by the same parameter in the wrong node:

https://github.com/OpenMS/OpenMS/blob/38489c526d885a53f5de6f77caf70b1205a13019/src/tests/topp/MassTraceExtractor_2.ini#L30

If I reorder the nodes (make epd before mtd) it does not happen.

For my work I will simply remove this test.

**Comment by bernt-matthias** [comment]
In https://github.com/OpenMS/OpenMS/blob/develop/src/tests/topp/MascotAdapter_1_parameters.ini it seems that 2 sets of Parameters are specified. In the execution only the 1st one is used.

**Comment by cbielow** [comment]
> 
> 
> In https://github.com/OpenMS/OpenMS/blob/develop/src/tests/topp/MascotAdapter_1_parameters.ini it seems that 2 sets of Parameters are specified. In the execution only the 1st one is used.

This is a remnant of an old design, where you could pass another `instance` (strange term, but thats what its called) and it would select the other set. By default `instance = 1`. The commandline param `-instance` is still present. So you can try to pass `2` and see what happens, but I'm not sure it will work. This has not been used in ages (but also not been cleaned up -- since this would mean changing ALL ini files, i.e. remove one enclosing `<node>`).
