### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by little-jun** [OpenMS/OpenMS#4391]
the releases of my amake is 3.11.4, when i input the command 
"cmake -DBUILD_TYPE=LIST ../OpenMS-2.4.0/contrib",
there exists an error "The source "/mnt/hdisk1/jinjun/OpenMSInstaller/OpenMS-2.4.0/contrib/CMakeLists.txt" does not match the source "/mnt/hdisk1/jinjun/OpenMSInstaller/cmake-3.11.4/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory."
i want to know which source directory i should choose. Thanks.

**Comment by jpfeuffer** [comment]
It depends. It looks like you are trying to build OpenMS in a CMake build folder that was previously used (or was tried to be used) to build the contrib.
Note the subtle difference in your paths:
/mnt/hdisk1/jinjun/OpenMSInstaller/OpenMS-2.4.0/**contrib**/CMakeLists.txt
/mnt/hdisk1/jinjun/OpenMSInstaller/cmake-3.11.4/CMakeLists.txt

If you built your contrib already, then just choose a different build folder now for OpenMS.

**Comment by little-jun** [comment]
> It depends. It looks like you are trying to build OpenMS in a CMake build folder that was previously used (or was tried to be used) to build the contrib.
> Note the subtle difference in your paths:
> /mnt/hdisk1/jinjun/OpenMSInstaller/OpenMS-2.4.0/**contrib**/CMakeLists.txt
> /mnt/hdisk1/jinjun/OpenMSInstaller/cmake-3.11.4/CMakeLists.txt
> 
> If you built your contrib already, then just choose a different build folder now for OpenMS.
> 
> EDIT: Now looking at the two paths, it seems like the first Cmake run was pointing to a completely different directory. Maybe it is best to delete your _build_ folder and run CMake freshly.

thank you
