### ISSUE TITLE
Decoy, sp and tr proteins

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4392]
Hi, 
I've noticed that in the results of Fido a protein can have of four prefixes: tr,sp DECOY_tr and DECOY_sp. 
So, what is the meaning of the prefixes?

**Comment by jpfeuffer** [comment]
Hi!

tr and sp are prefixes that are added by the specific database maintainer (here: UniProt) where you (or your collaborator) got the information about the protein sequences.

Here, tr means TrEMBL and symbolizes unreviewed protein sequences (e.g. inferred from translating genome sequences). Whereas sp stands for SwissProt and comprises reviewed sequences that are more or less experimentally validated.

DECOY is a prefix added by a decoy generation method (e.g. DecoyDatabase) which adds reversed or shuffled proteins that are most likely absent in the sample to later estimate the false discovery rate among the results.

Both prefixes can vary and might not be present at all, depending on the source of the database and how you generate and add your decoys.

**Comment by jpfeuffer** [comment]
I guess this explained it? Feel free to open again if not.
