### ISSUE TITLE
Errors occur when I test OpenMS/TOPP installation

### ISSUE THREAD

**Issue by little-jun** [OpenMS/OpenMS#4396]
I have configured and built OpenMS/TOPP , however, when I test my OpenMS/TOPP installation, there occur some errors: 
         ###  The following tests FAILED:
        597 - TOPPView_test (Failed)
        2080 - UTILS_INIUpdater_1 (Failed)
        2081 - UTILS_INIUpdater_1_out (Failed)
        2083 - UTILS_INIUpdater_3 (Failed)
        2084 - UTILS_INIUpdater_3_out (Failed)
        2142 - TOPP_ExecutePipeline_1 (Failed)
Errors while running CTest
Makefile:129: recipe for target 'test' failed
make: *** [test] Error 8

    I want to know how can i solve these problems.Thanks.

**Comment by jpfeuffer** [comment]
Hi!

It seems like you are missing an X-Server on that machine. Could it be the case that this is a headless server?

If so, can you re-configure OpenMS by changing into your build directory and running `cmake -DWITH_GUI=OFF .` and build it again with make?

**Comment by little-jun** [comment]
> Hi!
> 
> It seems like you are missing an X-Server on that machine. Could it be the case that this is a headless server?
> 
> If so, can you re-configure OpenMS by changing into your build directory and running
> `cmake -DWITH_GUI=OFF .` and build it again with make?

Thank you. According your suggestions, i recmake my OpenMS with command   "cmake -DOPENMS_CONTRIB_LIBS="/mnt/hdisk1/jinjun/OpenMSInstaller/OpenMS-build" -DBOOST_USE_STATIC=OFF -DWITH_GUI=Off -DHAS_XSERVER=Off ../OpenMS-2.4.0",  the result is perfect, thank you again.

**Comment by jpfeuffer** [comment]
You are welcome :)
