### ISSUE TITLE
mzTab import?

### ISSUE THREAD

**Issue by bittremieux** [OpenMS/OpenMS#4417]
As far as I could discern mzTab is only available as an export option, but not as an import option. For example, `IDFileConverter` doesn't seem to support mzTab to idXML conversion.

What is the recommended way to import PSMs from an mzTab file for downstream processing (i.e. FDR filtering and protein inference)? Thank you.

**Comment by timosachsenberg** [comment]
I just checked and so far one can only read back mzTab in C++ and then manually fill the id-data structure. IIRC mzTab as intended to be the final report so I guess we neglected to add proper support for converting it to other id formats. 
If I would need to get For FDR and protein inference running on mzTab quickly I guess I would parse the PSM section in python and create the id data structure in pyOpenMS  see https://pyopenms.readthedocs.io/en/latest/datastructures_id.html write it out to idXML and use the existing tools for FDR and inference.

**Comment by bittremieux** [comment]
Thank you for the suggestion. I'm trying to figure out which information is required for the idXML export. Notably, my mzTab file only contains PSM information without a mapping to proteins the peptides correspond to. I was hoping to use the `PeptideIndexer` tool to do that. However, when I try to export only PSM to idXML I get the following error message:

> Omitted writing of 4256 peptide identifications due to wrong protein mapping.

This is the code I used to try to convert my mzTab file to idXML:

```
import pandas as pd
import pyopenms


filename = 'filename.mztab'

run_name = 'unknown'
skiplines = 0
with open(filename) as f_in:
    line = next(f_in)
    while line.split('\t', 1)[0] != 'PSH':
        if 'ms_run[1]-location' in line:
            run_name = line.split('\t')[2]
        line = next(f_in)
        skiplines += 1

psms = pd.read_csv(filename, sep='\t', header=skiplines, index_col='PSM_ID')
peptide_ids = []
for _, psm in psms.iterrows():
    peptide_id = pyopenms.PeptideIdentification()
    peptide_id.setRT(psm['retention_time'])
    peptide_id.setMZ(psm['exp_mass_to_charge'])
    peptide_id.setScoreType('q-value')
    peptide_id.setHigherScoreBetter(False)
    peptide_id.setIdentifier(psm['spectra_ref'])
    peptide_hit = pyopenms.PeptideHit()
    peptide_hit.setScore(psm['search_engine_score[1]'])
    peptide_hit.setRank(1)
    peptide_hit.setCharge(psm['charge'])
    peptide_hit.setSequence(pyopenms.AASequence.fromString(psm['sequence']))
    peptide_id.setHits([peptide_hit])
    peptide_ids.append(peptide_id)

protein_id = pyopenms.ProteinIdentification()
protein_id.setIdentifier(run_name)
pyopenms.IdXMLFile().store(filename.replace('.mztab', '.idXML'), [protein_id], peptide_ids)
```

How can I properly export only PSMs to idXML?

**Comment by timosachsenberg** [comment]
Looks nearly correct. I think the identifier in the PeptideIds must match the one in proteinid.

**Comment by bittremieux** [comment]
Indeed, that did it. Thanks!
