### ISSUE TITLE
MSSim with pyopenms

### ISSUE THREAD

**Issue by iquasere** [OpenMS/OpenMS#4420]
Greetings!

I am trying to simulate MS data with MSSim, but don't really understand how to do it. As the help from the function pyopenms.MSSim presents several methods but nothing about initializing it, I assume I must initialize an MSSim object.
```
>>> pyopenms.MSSim()
```
This, however, gives me
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyopenms/pyopenms_6.pyx", line 5469, in pyopenms.pyopenms_6.MSSim.__init__
RuntimeError: the file 'examples/simulation/RTPredict.model' could not be found
```
Is this a default of the function? How do I input my FASTA file of protein sequences to simulate MS data?

**Comment by hroest** [comment]
hmm yes, I have not really tried that before and I get the same results. This is indeed a bug. Can you try the following workaround:

```
>>> import pyopenms
>>> pyopenms
<module 'pyopenms' from '/media/doc/pyenv/py37_bleeding/lib/python3.7/site-packages/pyopenms/__init__.py'>
>>> 
```

then go to the path where pyopenms is installed and copy the required files
```
cd /media/doc/pyenv/py37_bleeding/lib/python3.7/site-packages/pyopenms/
mkdir -p share/OpenMS/examples/simulation
cd share/OpenMS/examples/simulation
wget https://raw.githubusercontent.com/OpenMS/OpenMS/develop/share/OpenMS/examples/simulation/RTPredict.model
wget https://raw.githubusercontent.com/OpenMS/OpenMS/develop/share/OpenMS/examples/simulation/DTPredict.model
```

this works for me

@cbielow why does this code require stuff from the `examples` folder? We usually delete them in order to save space

**Comment by cbielow** [comment]
> @cbielow why does this code require stuff from the `examples` folder? We usually delete them in order to save space

for RT prediction, the simulator needs some kind of RT-model. You can provide your own (which takes some time to train), but the default is the one in the example folder.

**Comment by iquasere** [comment]
This indeed allowed to initialize it! Now, I wanted to know if there is some place where this function is documented. Best thing I found, besides the help function on the instance, is the [pyOpenMS manual](http://proteomics.ethz.ch/pyOpenMS_Manual.pdf), but is even less informative than the built in documentation. So, if documentation is unavailable, I have several questions in the face of the possibilities:
1. How should I go about building a model for simulating MS data?
2. Is there a way to use MSSim to simulate differentially abundant proteins? Or all have to be in the same level of detection?
3. Can I add PTMs, digestion and the likes?

I really did not want to find this by myself, but if needs be... Thank you for your attention, at least now it is functional.

**Comment by cbielow** [comment]
The UTIL/TOPP `MSSimulator` tool is probably a good place to start:
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/a16237.html

Is there a specific reason to use python instead of just running the TOPP tool? Any customization you need?

**Comment by iquasere** [comment]
I haven't been able to use MSSim in any other way. For example, using your docker
```
docker pull hroest/openms-executables-2.2
docker run -it hroest/openms-executables-2.2 /bin/bash
```
and inside it
```
root@e2276387aa3a:/# find OpenMS -name "*MSSim*"
OpenMS/src/openms/source/SIMULATION/MSSim.cpp
OpenMS/src/openms/include/OpenMS/SIMULATION/MSSim.h
OpenMS/src/pyOpenMS/pxds/MSSim.pxd
OpenMS/src/tests/class_tests/openms/source/MSSim_test.cpp
OpenMS/src/utils/MSSimulator.cpp


root@e2276387aa3a:/# gcc OpenMS/src/utils/MSSimulator.cpp
OpenMS/src/utils/MSSimulator.cpp:38:42: fatal error: OpenMS/APPLICATIONS/TOPPBase.h: No such file or directory
 #include <OpenMS/APPLICATIONS/TOPPBase.h>
                                          ^
compilation terminated.
```
This is too cryptic to me. At least in Python I can crawl to the answers.

**Comment by jpfeuffer** [comment]
There should be a `bin` folder on that container which contains pre-built executables, that you can
just invoke in your shell via:
`./OpenMS-build/bin/MSSimulator -in foo -out bar`

**Comment by iquasere** [comment]
Ahah now that is better! openms-build/bin/MSSimulator is there. I'll investigate this then. Thank you very much!
