### ISSUE TITLE
Differential expression in spectra simulation

### ISSUE THREAD

**Issue by iquasere** [OpenMS/OpenMS#4421]
Greetings

Now that MSSim is running, I am wondering how can I simulate differentially expressed proteins. I haven't found any option for that on the tool. However, one of the parameters in the ini configuration XML is the "Detectability" model, which lies in the "examples/simulation/DTPredict.model" file. Can I use this file, by tweaking the detection level of proteins, to simulate differential expression? Is this something that has been tried before?

Thank you for your attention!

**Comment by jpfeuffer** [comment]
Hi!
According to: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/a16237.html
you can specify the abundance of the proteins by adding a suffix to your fasta header entries.
Together with the signal to noise parameter(s) it might be possible to simulate such things.

If you want sampled intensities for proteins in the samples , you could use this python script:
https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/examples/simulation/FASTAProteinAbundanceSampling.py

**Comment by iquasere** [comment]
Holy smokes, I missed that! Thank you very much, gonna try it right away!

**Comment by iquasere** [comment]
So, this intensity value: is it the intensity of the peptides originating from that specific protein? Or will it be reflected in a combination of the MS1 and MS2 spectra? From what I understand (very little, for notice), I think it would not make a difference if noise correction is in place - thus an intensity of 1 for normal proteins and 3 for overexpressed would be the same as 100 and 300. Or should the base intensity always be added? In that case, I do need a reference value...

**Comment by iquasere** [comment]
By what I see from the FASTAProteinAbundanceSampling, it set intensity according to a random gaussian distribution. So it probably can't be used to simulate explicitly defined differential expression

**Comment by iquasere** [comment]
Seems like any values of intensity I use, I always get mzML files with no intensity at both MS levels. 
The sampling script did only add values randomly from a normal distribution.
```
python FASTAProteinAbundanceSampling.py input_proteome.fasta output_proteome.fasta
```
Using this FASTA file as input produced mzML spectra with no MS events.
```
openms-build/bin/MSSimulator -in output_proteome.fasta -out output_spectra.mzML -ini ini.config
```
Has this been tested? If I could get a working example, it would be great, and probably would solve my problems.

**Comment by jpfeuffer** [comment]
I think @cbielow used it successfully recently (maybe he can add something to the discussion).
We also used it for testing a new tool here: https://github.com/OpenMS/OpenMS/blob/develop/src/tests/topp/ProteomicsLFQTestScripts/create_sim_data.sh

What do you mean by:

> I always get mzML files with no intensity at both MS levels.

Can you elaborate (maybe also by adding an example file and output log of the tool)?

**Comment by iquasere** [comment]
Good suggestion on the elaborating. Maybe there is some step I am missing. I submitted [proteomes.fasta](https://github.com/OpenMS/OpenMS/files/4029860/proteomes.fasta.txt) to the python script that samples intensities.
```
docker run -it hroest/openms-executables-2.2 -v /path/to/work_dir:/work_dir -c "python FASTAProteinAbundanceSampling.py work_dir/proteomes.fasta work_dir/with_intensities.fasta"
```
Then, I submitted that file with intensities to MSSim.
```
docker run -it hroest/openms-executables-2.2 -v /path/to/work_dir:/work_dir -c "openms-build/bin/MSSimulator -in work_dir/with_intensities.fasta -out work_dir/spectra.mzML -ini test_ms/ini.config"
```
I wanted to explore the file, so I used MS convert to save to MGF format. It could not end the job, but reported to have 501 MS events. Using the [mz2db](https://github.com/mzdb/pwiz-mzdb) tool, I try to organize the MS events into SQL format, for easy queries.
```
raw2mzDB_0.9.10_build20170802\raw2mzDB.exe -i path/to/spectra_db.mzML -o path/to/spectra_db.mzML.mzDB
```
It reports that simulated mzML is in CENTROID. Using the --safeMode option, it reads the file in centroid mode, and [kinda](https://github.com/mzdb/pwiz-mzdb/issues/68) builds the database. Performing the queries on this, I get no events at the MS1 and MS2 level.
```
# in R
library(RSQLite)
library(rmzdb)

sqlite <- dbConnect(RSQLite::SQLite(), "path/to/spectra_db.mzML.mzDB")

# MS 2
ms2_count <- dbGetQuery(sqlite, "SELECT count(*) as n FROM spectrum WHERE ms_level = 2")
barplot(ms2_count$n, main="MS/MS events",  xlab="Number of MS/MS spectra", names.arg=c("count"))

# MS 1
ms1_tic <- dbGetQuery(sqlite, "SELECT (time / 60) as rt, tic as intensity FROM spectrum WHERE ms_level = 1")
plot(ms1_tic$rt, ms1_tic$intensity, type="l", col="yellow", lwd=1, xlab="Retention time (min)", ylab="MS Intensity", main = "MS1 total ion chromatograms")
```
![MS1](https://user-images.githubusercontent.com/16226371/71886155-9d472500-3133-11ea-9c83-42b888cfd271.jpeg)

**Comment by jpfeuffer** [comment]
Ah ok thanks for the extensive elaboration. Indeed there are quite some steps, where it could go wrong.
How big is the resulting mzML from:
`docker run -it hroest/openms-executables-2.2 -v /path/to/work_dir:/work_dir -c "openms-build/bin/MSSimulator -in work_dir/with_intensities.fasta -out work_dir/spectra.mzML -ini test_ms/ini.config"`
Could you share it? Or visualize/open it without conversion?
And are you able to get the log of the MSSimulator tool inside the container? Maybe it reports something?

**Comment by iquasere** [comment]
The log from MSSimulator, shortened in the repeat regions. Tomorrow I'll share the spectra!
```
Version 2.2.0 of MSSimulator is available at www.OpenMS.de
Loading sequence data from /work_dir/protpy.fasta ...
done (41403 protein(s) loaded)
Starting simulation
2020/01/08, 15:23:43: Digest Simulation ... started
2020/01/08, 16:00:25: RT Simulation ... started
2020/01/08, 16:35:38: Predicting RT ... done
2020/01/08, 16:35:53: RT prediction gave 'invalid' results for 802049 peptide(s), making them unobservable.
2020/01/08, 16:35:53:   (List is too big to show)
2020/01/08, 16:36:38: Creating experiment with #501 scans ... done
2020/01/08, 16:36:38: Detectability Simulation ... started
2020/01/08, 16:36:45: Ionization Simulation ... started
esi_impurity_probabilities_[0]: 1
weights[0]: 10
2020/01/08, 16:36:52: Simulating 1229467 features
Progress of 'Ionization':
-- done [took 1d 07:43:14 h (CPU), 02:41:57 h (Wall)] --
2020/01/08, 19:18:58: #Peptides not ionized: 0
2020/01/08, 19:18:58: #Peptides outside mz range: 374059
2020/01/08, 19:19:31: Raw MS1 Simulation ... started
2020/01/08, 19:19:32:   Simulating signal for 3412286 features ...
Progress of 'RawMSSignal':
  24.88 %               2020/01/08, 19:27:09: Compressed data to grid ... 2518441 --> 2381544 (94%)
2020/01/08, 19:27:09: Compressed data to grid ... 2568583 --> 2438207 (94%)
...
2020/01/08, 19:27:09: Compressed data to grid ... 35297235 --> 33053517 (93%)
  49.20 %               2020/01/08, 19:34:59: Compressed data to grid ... 34654062 --> 32428478 (93%)
2020/01/08, 19:34:59: Compressed data to grid ... 34476271 --> 32264719 (93%)
...
2020/01/08, 19:34:59: Compressed data to grid ... 43328473 --> 40996645 (94%)
  73.78 %               2020/01/08, 19:43:20: Compressed data to grid ... 41267448 --> 38906600 (94%)
2020/01/08, 19:43:20: Compressed data to grid ... 44094331 --> 41700616 (94%)
...
2020/01/08, 19:43:20: Compressed data to grid ... 48959796 --> 46546277 (95%)
  98.35 %               2020/01/08, 19:53:19: Compressed data to grid ... 48167968 --> 45776151 (95%)
2020/01/08, 19:53:19: Compressed data to grid ... 49105829 --> 46673527 (95%)
...
2020/01/08, 19:53:19: Compressed data to grid ... 53109232 --> 50660217 (95%)
-- done [took 07:11:40 h (CPU), 38:56 m (Wall)] --
2020/01/08, 20:00:33: Compressed data to grid ... 53566045 --> 51049191 (95%)
...
2020/01/08, 20:00:33: Compressed data to grid ... 52367820 --> 49984114 (95%)
2020/01/08, 20:00:33: Contaminants out-of-RT-range: 204 / 486
2020/01/08, 20:00:33: Contaminants out-of-MZ-range: 111 / 486
2020/01/08, 20:04:02: Compressed data to grid ... 711903462 --> 107250908 (15%)
2020/01/08, 20:04:02: Adding white noise to spectra ...
2020/01/08, 20:04:02: Adding detector noise to spectra ...
2020/01/08, 20:04:02: Detector noise was disabled.
2020/01/08, 20:05:07: Tandem MS Simulation ... disabled
2020/01/08, 20:06:47: Final number of simulated features: 3412286
2020/01/08, 20:06:47: Simulation took 16984.385535 seconds
2020/01/08, 20:06:47: Storing simulated raw data in: /work_dir/spectra.mzML
2020/01/08, 20:07:41: MSSimulator took 04:43:59 h (wall), 1d 16:16:50 h (CPU), 0.09 s (system), 1d 16:16:50 h (user).
```

**Comment by jpfeuffer** [comment]
Ok. Informative, thanks. Two things:
- 501 is the number for the MS1 scans I think and is determined by the total retention time and the cycle duration. It would be good if you can share the ini as well.
- it says tandem simulation disabled, so it is not expected to see any MS2 scans.

But it looks like the MS1 should definitely be filled though (also considering the size of the mzml, without seeing it). Also my guess is that the simulation is pretty compressed since 501 scans are probably too few for this database size.
Did  this "workflow" work with smaller test files? I see in the linked issue that you tried it with two proteins for example? Maybe the SQL conversion was not really successful in the end.

**Comment by iquasere** [comment]
[Link](https://we.tl/t-K1WrVLSyfb) for the configuration file and the mzML spectra.

The INI file is the standard configuration file, outputed with `MSSimulator -write_ini `. The workflow didn't work with only two proteins, as well. I tried to do a full standard approach first, just to see the simulation working. 
The SQL conversion did present some errors, but I think that might be due to not finding any spectra to report, and lacking the handling of that possibility.
I also tried to use MS convert to get to MGF format, but it got stuck midway through.

**Comment by jpfeuffer** [comment]
I looked into the file with our TOPP View, and it looks fine.
There are 501 MS1 spectra and no MS2 spectra as expected.
All the spectra are filled (as I thought even a bit too full). So I suspect that it indeed is an error during conversion.

Regarding settings:
If you use the default values, you do not need to pass the ini file. Nonetheless you can use it since I would definitely tweak the parameters.
Have a look at the many parameters 
[here](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/UTILS_MSSimulator.html)
Especially the RT scan_window, the Detectability min_detect and RawTandemSignal (if you want MS2 scans).

**Comment by jpfeuffer** [comment]
Also, do you really want all the 41000 proteins to show up in the experiment? It sounds a bit much for a single sample. Maybe you want a subsample of it.
Later on you can still use the full DB to benchmark things (or whatever you want to do with the simulation).

**Comment by iquasere** [comment]
Thank you a lot for the help! I already put two new simulations running, for "precursor" and "MS^E" settings in the "RawTandemSignal". When this is finished I will put feedback here and hopefully close the issue.
I really don't know if I want all proteins to show. I am trying to simulate MS data reflecting a complex microbial community, so I joined all their proteomes and created that file. I thought all of their proteins should be considered for the simulation. I also want to simulate the differential expression as reference in the begining of this issue. My goal is to benchmark the metaproteomics workflow of my pipeline by identifying the proteins simulated, and correctly measuring differential abundance.
The fact that the MS1 had no intensity might really be because of a wrong conversion to SQL. When I have simulated spectra with MS2 events, I will know if that is the case. With real datasets it always worked.

**Comment by jpfeuffer** [comment]
Hmm ok.
- MS^E is probably used for anything higher than MS2 (e.g. often used in TMT)
- I have never seen metaproteomics mzMLs but probably they are also heavily fractionated? Maybe you can simulate fractionation by splitting the database into proteins with specific properties. Or just use a very long simulated gradient.
- Even if you consider their whole proteome, I would assume that not all possible proteins are present at the same time in the cells (maybe you can add a subsampling procedure to the python script, which does not consider this yet). Play around with it.

**Comment by iquasere** [comment]
Damn, thanks for all the insight! I still lack much experience in proteomics, it is much more complex than nuleotidic omics... if I end up digging deep on this, I'll try to improve the tool to consider for all these details.

**Comment by iquasere** [comment]
So, setting "RawTandemSignal" to "precursor" finally got me MS2 events! But surprisingly, MS1 is still silent - no intensity to report. Very strange that the tool allows for MS2 to happen without MS1. Also, converting it to MGF and submitting that to SearchGUI worked, but failed when I tried to browse the results on Peptide-Shaker. So something is still very wrong here...

**Comment by jpfeuffer** [comment]
The thing is, in our viewer, the MS1 is not silent. Maybe the conversion is not able to handle the very full spectra. Or one of the parts does not fully conform to the mzML schema that we write.

![Bildschirmfoto 2020-01-09 um 19 10 22](https://user-images.githubusercontent.com/8102638/72092954-bb6b7b80-3313-11ea-80a5-208ebb0f8d8e.png)

You could also update your docker container. 2.2 is pretty outdated. Maybe there were some fixes.
`docker pull openms/executables`

**Comment by iquasere** [comment]
Sorry for the absence, but had to do some classes from the PhD. TOPPVIEW can see the events in the MS1 and I think in the MS2 as well, great tool by the way. It seems the problem here really is the [format](http://www.codems.de/reports/mzxml_for_maxquant/). The mzML schema doesn't seem to be compatible with MaxQuant, I thought mzML was already enough established that this wouldn't happen between different softwares, but it seems each may have its own schema?

**Comment by cbielow** [comment]
> 
> 
> Sorry for the absence, but had to do some classes from the PhD. TOPPVIEW can see the events in the MS1 and I think in the MS2 as well, great tool by the way. It seems the problem here really is the [format](http://www.codems.de/reports/mzxml_for_maxquant/). The mzML schema doesn't seem to be compatible with MaxQuant, I thought mzML was already enough established that this wouldn't happen between different softwares, but it seems each may have its own schema?

Try converting to mzXml using our TOPP `FileConverter -in simulated.mzML -out simulated.mzXML -force_MaxQuant_compatibility`. 

Both the mzML and mzXML are pretty well defined and you can verify that the OpenMS implementation adheres to the schemata by validating them (`FileInfo -v -in simulated.mzML`). MaxQuant's implemenation is very sensitive to what data it expects (even though its optional by the standard) and even where linebreaks appear...

**Comment by iquasere** [comment]
Using the FileConverter, MaxQuant did accept the input. So that is one step forward, I guess. I removed any modifications from the search parameters, since they were not included in the simulation. However, MaxQuat still can't identify any peptides.

**Comment by iquasere** [comment]
Greetings! I have, in the meantime, read this [AAR](http://www.codems.de/reports/mzxml_for_maxquant/) regarding submitting mzXML to MaxQuant, written by you! It would seem that simulation tools from OpenMS would be adequate to simulate mzXML for MaxQuant 1.5 at least, which were tested for this. However, using MaxQuant 1.5.3.30, I still couldn't have results with simulated datasets.
Running ```openms-build/bin/FileInfo -v -in spectra.mzML``` reports the file as a valid XML schema version 1.1.0. After running the FileConverter, I get an mzXML, but MaxQuant claims it appears to be corrupt.
Chris, did you guys ever used simulated datasets? Maybe my only option here is to test these datasets with tools of OpenMS, since none of the proteomics workflows I am used to use can handle these files.

**Comment by jpfeuffer** [comment]
Maybe you can start from the peak picked files then? I think there is an option to output the picked files (maybe this is even the default in the Simulator - need to check.)

@cbielow definitely has a lot of experience in conversion to MaxQuant compatible mzXMLs.

**Comment by iquasere** [comment]
Great idea, didn't know that MSSim could output peak picked data! Simulating with ```openms-build/bin/MSSimulator -in outside/proteomes.fasta -ini outside/ini.config -out_pm proteomes_pp.mzML``` got me a new file. This was much larger than the other attempts, don't understand why peak picked data would be bigger. 

However, SearchGUI + PeptideShaker could read and analyse!! MaxQuant still failed, but having a proteomics workflow working is a breakthrough. The results were very suboptimal - only doubtful and rejected identifications - but that may be because this time I was using the files with 90k proteins again. 

I'm starting to dig in the OpenMS tools, by what I see there is no automated workflow but rather many tools at our disposal to make our own workflows. May try those next, since this automated workflows are really not paying off.

**Comment by iquasere** [comment]
It works if simulating using 4000 proteins in one run! Many proteins identified with confidence, using SearchGUI and Peptide-Shaker. Thank you very much for all the help, couldn't have done it without you guys @jpfeuffer and @cbielow ! Will probably still dig into the OpenMS tools, since the tools from Compomics don't quantify at the MS1 level...

**Comment by jpfeuffer** [comment]
Hi, glad that it helped. We are currently developing a hopefully similarly easy-to-use nextflow workflow, where all the tools needed for an LFQ analysis are chained in a predefined/curated manner such that you don't need to worry about which tools to pick.
We will release it together with the next OpenMS release in the upcoming week or so: https://nf-co.re/proteomicslfq
You can give it a try then, would be interesting to see how it works on simulated data. We are currently using ground-truth only to benchmark.
