### ISSUE TITLE
DigestorMotif fails with seqfault

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4426]
I tried `DigestorMotif -in random.fa  -out test.idXML` with a randomly generated protein sequence

**Comment by hroest** [comment]
can confirm with the following example
```
$ cat /tmp/test.fa 
>test
A
$ ~/openmsall/builds/release_2.4/bin/DigestorMotif -in /tmp/test.fa -out /tmp/test.idXML
Segmentation fault (core dumped)
```

**Comment by bernt-matthias** [comment]
Also for this tool a test is missing

**Comment by hroest** [comment]
@bernt-matthias NOTE: this tool is in the utils folder where tests are not required and experimental tools live

**Comment by hroest** [comment]
I found the issue:

https://github.com/OpenMS/OpenMS/blob/d86cc483929c61b631c2501688de8a6d374493aa/src/utils/DigestorMotif.cpp#L352

this needs to be changed to

```
for (UInt a = 0; a + 1 < PROTEINS.size(); ++a)
```

but there is a more general question @timosachsenberg @jpfeuffer whether we need this tool at all? Also the documentation is out of sync, it says "At the moment only trypsin is supported." when this is actually not the case

**Comment by bernt-matthias** [comment]
> @bernt-matthias NOTE: this tool is in the utils folder where tests are not required and experimental tools live

Thanks for the information -- I guess adding tests is still worth the effort.

**Comment by timosachsenberg** [comment]
I think this tool is pretty old and I never used it. We might want to mark it as deprecated.

**Comment by jpfeuffer** [comment]
I'm ok with at least deprecating it. Removing would be okay for me as well though. Do we have statistics Timo?
