### ISSUE TITLE
Posttranslational modifications in OpenMS

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4437]
Hi everyone!
How can I analyze posttranslational modifications using OpenMS ? 
There is a possibility of adding fixed and variable modifications in every search engine adapter, but how can I analyze them afterall ? 
And what is the difference between fixed and variable modifications?

**Comment by iquasere** [comment]
Can't answer for the tool, but when a modification is set as "fixed", the search engine will only consider the version of the protein/peptide/fragment with the modification. If the modification is set as "variable", the search engine will consider all cases with and without the modification. Thus, this kind of modifications increase exponentially the size of the database. You can analyze PTMs with [SearchGUI ](https://compomics.github.io/projects/searchgui) and [Peptide-Shaker](https://compomics.github.io/projects/peptide-shaker), which are very intuitive and interactive tools. I still haven't explored OpenMS enough, though.
