### ISSUE TITLE
Decharger problems on VS2019

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4439]
Looks like most of them are related to the potential_adducts parameter 
No idea why though.

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/blob/199d2768be639a51b1c313c0e937440e5cb58c7b/src/openms/source/ANALYSIS/DECHARGING/MetaboliteFeatureDeconvolution.cpp#L226

I am not sure if you can assume that the first part will always be executed before the second part. That might be something to look into.

**Comment by cbielow** [comment]
> https://github.com/OpenMS/OpenMS/blob/199d2768be639a51b1c313c0e937440e5cb58c7b/src/openms/source/ANALYSIS/DECHARGING/MetaboliteFeatureDeconvolution.cpp#L226
> 
> I am not sure if you can assume that the first part will always be executed before the second part. 

Good spotting. The compiler can do as it pleases so that's undefined behaviour.

**Comment by timosachsenberg** [comment]
for reference https://en.cppreference.com/w/cpp/language/eval_order
