### ISSUE TITLE
I/O performance

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#4445]
A few pointers which might help improving I/O performance (for writes), especially on Windows:

One fact to realize is that every call to `operator<<` causes creation of a `sentry` object (basically a mutex), to avoid race conditions when multiple threads write to the same stream (you can still get output mixed up, but never undefined behaviour).

1. This implies that creating larger strings and calling `operator<<` fewer times should increase throughput (see https://stackoverflow.com/questions/51149880/fprintf-fputs-vs-cout-performance-for-large-strings)

2. Maybe use async I/O, likely via a separate I/O thread (or using [boost asio](https://stackoverflow.com/questions/8522475/intro-to-non-threaded-async-io-for-c/8522563#8522563), but that will make code complex)

3. avoid std::endl since it flushes the stream (this should not happen in our writers, but good to check).

4. set a write buffer for MSVC (see https://stackoverflow.com/a/39387362). This may or may not help these days. Also Win uses an intermediate OS buffer (https://docs.microsoft.com/en-us/cpp/c-runtime-library/commit-to-disk-constants?view=vs-2019, but it might not be used with ostreams)
Actually, buffering seems a rather tricky field: https://stackoverflow.com/questions/11563963/writing-a-binary-file-in-c-very-fast

5. try `ofstream::write()` (this also constructs a sentry, but some benchmarks suggest it might be faster ...)

6. use `std::ios_base::sync_with_stdio(false);`
(this should only affect standard streams, such as cin and cout, but some sites suggest to try it anyway -- unlikely to help IMHO since we are using file ofstreams/ifstreams)

Some more links:
https://codeforces.com/blog/entry/5217

**Comment by hroest** [comment]
@cbielow can you provide some I/O benchmarks? Eg we could try and use a large (several GB) file with a "NOP" `FileConverter` and see how long it takes on different OS to read, process and write the file.  If write performance is substantially different from the other two (relative) then we know its an OS effect.

Finally: compared to file reading/parsing is writing even a big performance issue?

**Comment by cbielow** [comment]
this is IM-LC/MS data?
numbers are impressive, maybe due to the better ratio of data vs metadata?!

Anyway, on VS2015 the numbers are not that good (12 sec read + 6.6 sec write for 1.5GB).
However, I just tried VS2019 for the first time and it delivers 11 sec read + 3.5 sec write, without any code changes from our side.
So maybe we just keep the ticket as a reminder and focus on other things :)

**Comment by hroest** [comment]
@cbielow yes this IM-LC-MS/MS data from a timsTOF. I am happy to send you the test data if you like to have a look. But note how this is only 100 seconds of data. 

Btw I just realized my file is only 577M, I think I grabbed the wrong file. So there are more data with the small 577M file and the larger 3 GB file. Also I dont think you can compare the file sizes easily since the timsTOF data is stored with a float array:

```
$ FileConverter -in 20180323_AnBr_SA_diaPASEF_200ng_HeLa_Rost_Method_2_b_TIMSon_02_A2_01_2166.RT30003500.mzML -out /tmp/test.mzML
Progress of 'loading spectra list':
-- done [took 27.45 s (CPU), 47.89 s (Wall)] -- 
Progress of 'storing mzML file':
-- done [took 4.48 s (CPU), 5.02 s (Wall)] -- 
FileConverter took 01:29 m (wall), 46.02 s (CPU), 5.24 s (system), 40.78 s (user).

$ FileConverter -in 20180323_AnBr_SA_diaPASEF_200ng_HeLa_Rost_Method_2_b_TIMSon_02_A2_01_2166.RT30003100.mzML  -out /tmp/test2.mzML
Progress of 'loading spectra list':
-- done [took 3.92 s (CPU), 3.92 s (Wall)] -- 
Progress of 'storing mzML file':
-- done [took 0.88 s (CPU), 1.08 s (Wall)] -- 
FileConverter took 6.80 s (wall), 6.50 s (CPU), 0.79 s (system), 5.71 s (user).
```

but clearly on Linux the read : write time ratio is is between 4-6 while on Windows its closer to 3, so it does look like it performs better on Linux.
