### ISSUE TITLE
Neutral Losses of Arginine

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#4448]
Why does Arginine have a CONH2 loss in Residues.xml? that does not make sense to me chemically I have not found any evidence for this in the literature:
 
https://github.com/OpenMS/OpenMS/blob/4ce809c5be3852358876b159523321b33d48d741/share/OpenMS/CHEMISTRY/Residues.xml#L287-L288

ther is no CONH2 that can be lost from the sidechain. Maybe that was supposed to be Glutamine or Asparagine?

**Comment by hroest** [comment]
It seems like our Residues.xml mostly follows the rules from [1]

_In low energy CID (i.e. collision induced dissociation in a triple quadrupole or an ion trap) a peptide carrying a positive charge fragments mainly along its backbone, generating predominantly b and y ions. In addition, for fragments containing RKNQ, peaks are seen for ions that have lost ammonia (-17 Da) denoted a*, b* and y*. For fragments containing STED, loss of water (-18 Da) is denoted a°, b° and y°. Satellite ions from side chain cleavage are not observed._

except for a few exceptions which is mainly Arginine and a few N-terminal losses. Arginine has loss of NH3, NHCNH and CONH2 which do not appear to be "canonical". Does anybody know where these come from, e.g. @cbielow or @timosachsenberg ?

1. http://www.matrixscience.com/help/fragmentation_help.html

**Comment by timosachsenberg** [comment]
No idea

**Comment by hroest** [comment]
@cbielow any ideas?

**Comment by cbielow** [comment]
nope. This looks weird indeed.
I'd say ditch them -- given some extra time we could check if there are actually matches to these losses in real spectra. I know that Andreas put quite a lot of effort into his search engine and talked to a lot chemists. So this might also just make sense of other kinds of fragmentation (ETD etc?).

**Comment by timosachsenberg** [comment]
yep let's ditch them. 
In general it would probably be better to define neutral losses dependent on the fragmentation method.

**Comment by timosachsenberg** [comment]
I removed the loss (but accidentally pushed on develop). Let's see if it still builds
