### ISSUE TITLE
Too few proteins are kept after FDR filtration

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4458]
Hi all, 
in the next ID workflow: (Comet, OMSSA, MS-GF+) -> IDPEP -> IDMerger -> ConsensusID -> PeptideIndexer ->FDR->IDSwitcher->Fido->FDR->IDSwitcher the resulting idXML file contains  only 1 protein identification without any protein hits and 0 peptide identifications. 

I used the same pipeline for several times before and it always worked fine. What might have caused the problem ?

**Comment by timosachsenberg** [comment]
Hard to debug but loosing all proteins is often a problem of the database or the search settings.
e.g., wrong database, modifications, or sometimes creating a target-decoy database from a database that already contained decoys

**Comment by jpfeuffer** [comment]
I would first look at the log/scores from IDPEP for each search engine. If it can't fit well for one, it might heavily affect the whole outcome.

**Comment by mash23** [comment]
IDPEP worked didn't throw any warnings. Doesn't that mean that it worked well enough ?

**Comment by jpfeuffer** [comment]
Not always. Have a look at the gnuplot output. In 2.5 we also implemented some outlier removal that might improve fitting.
