### ISSUE TITLE
Make code changes so that DefaultParameterHandler can be used without inheriting from it [446]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#446]
Submitted by witek96 on 2012-08-15 14:57:53

Currently one has to inherit from DefaultParameterHandler to add parameter to defaults_ or to call defaultsToParam_.

---

Commented by aiche on 2012-08-15 17:32:45:
This is something we should consider for OpenMS 2.0. We actually started the planing so we should include this in the discussion.

---

Commented by witek96 on 2012-08-24 13:44:25:
Documentation need to be fixed too.
@brief A base class for all classes handling default parameters.

**Comment by hendrikweisser** [comment]
If there are no plans to actually do this, we should close the issue.
