### ISSUE TITLE
Retrieve meta value: file_origin after using IDMerger on multiple fractions

### ISSUE THREAD

**Issue by Matthias313** [OpenMS/OpenMS#4460]
Hi,

I used the IDMerger to merge multiple fractions belonging to one experiment.
I specified the flag -annotate_file_origin which is supposed to store the original filename in each peptide/protein identification.

However, I can´t find the file_origin in either the TextExporter or the MzTabExporter output.

Any ideas on how to retrieve the original filename of the respective peptide identification?

**Comment by jpfeuffer** [comment]
Hi, I think the file origins are metavalues and you have to specifically activate the writing of metavalues in the exporters.

I need to check the exact metavalue for IDs.

**Comment by jpfeuffer** [comment]
The flag for TextExporter should be "-id:add_metavalues 0"

**Comment by Matthias313** [comment]
Thank you very much it worked out but i needed to specifiy "-id:add_metavalues 100".

With "-id:add_metavalues 0" the file_origin was not written in the ouTput.

Is there also an option to output the meta values using the mzTabExporter?
