### ISSUE TITLE
Misclassified tool documentation

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4472]
There are a few tools in 2.4. where the documentation is misclassified (TOPP / UTILS): 

Resulting in 404 for the following URLs:

- https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/UTILS_MSFraggerAdapter.html - http://www.openms.de/documentation/UTILS_MSFraggerAdapter.html
- https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/UTILS_SimpleSearchEngine.html - http://www.openms.de/documentation/UTILS_SimpleSearchEngine.html
- https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/UTILS_ClusterMassTraces.html - http://www.openms.de/documentation/UTILS_ClusterMassTraces.html
- https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/UTILS_ClusterMassTracesByPrecursor.html - http://www.openms.de/documentation/UTILS_ClusterMassTracesByPrecursor.html
- https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/UTILS_RNPxlSearch.html - http://www.openms.de/documentation/UTILS_RNPxlSearch.html
- https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/UTILS_MetaProSIP.html - http://www.openms.de/documentation/UTILS_MetaProSIP.html

**Comment by bernt-matthias** [comment]
Forgot one: 

https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/TOPP_FeatureFinderSuperHirn.html - http://www.openms.de/documentation/TOPP_FeatureFinderSuperHirn.html

**Comment by bernt-matthias** [comment]
Actually SimpleSearchEngine seems to miss html documentation at all.

**Comment by bernt-matthias** [comment]
A complete list is contained in this test output: https://travis-ci.org/galaxyproteomics/tools-galaxyp/jobs/659610410?utm_medium=notification&utm_source=github_status

(Galaxy tool tests check for dysfunctional links)

**Comment by jpfeuffer** [comment]
@timosachsenberg Ping for SimpleSearchEngine.

**Comment by jpfeuffer** [comment]
Everything is there in the nightly docs.
