### ISSUE TITLE
Python 3.8 wheel for PyPi

### ISSUE THREAD

**Issue by RmStorm** [OpenMS/OpenMS#4477]
Hello!

Could you please provide a wheel for Python 3.8 for easy installation of pyOpenMS from PyPI?
Currently, there are wheels for 2.7, 3.4, 3.5, 3.6 and 3.7. This was discussed in #4344 as well but the author of that issue closed it. I'm on Linux Mint and I couldn't get pyOpenMS compiled myself.

**Comment by hroest** [comment]
We are currently working on a Linux version for Python 3.8, we have already uploaded the Windows version. @oliveralka can you upload a OSX version for Python 3.8 ?

**Comment by hroest** [comment]
@RmStorm can you try this version: https://www.dropbox.com/s/fvgww2xizufxl8u/pyopenms-2.4.0.1-cp38-cp38-manylinux2014_x86_64.whl?dl=0 and let me know if it works (works here on Ubuntu)

**Comment by RmStorm** [comment]
@hroest, hi thank you for the quick response! I forgot to test this today but I see that there is also a 3.8 image on pypi. Is there any difference between the 2.4.0 image on pypi and this 2.4.0.1 image in dropbox?

Eitherway, first thing monday morning I will test this! Again thanks for the quick response!

**Comment by hroest** [comment]
@RmStorm there should not be a difference, the dropbox version was created by hand using trial and error and the PyPI version was created by running the script in #4486 to get a reproducible result. I suggest to use the PyPI version just so you get what everybody else also uses...

**Comment by RmStorm** [comment]
Great, this works as expected! Tested and ran in the `python:3.8-buster` docker image.
