### ISSUE TITLE
suffix _REVERSED not automatically recognized by PeptideIndexer as Decoy position and string

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4478]
_REVERSED

**Comment by jpfeuffer** [comment]
add to:
https://github.com/OpenMS/OpenMS/blob/b1bde1639b16b2298fd363c0ff4897e2f2f9c490/src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h#L363

but is it really a suffix? Sometimes external tools put it after the database part but before the annotation
e.g. "sp|foo_rev|baz"
I remember that we currently do not handle this.

**Comment by timosachsenberg** [comment]
Just came up in one example file. I will add it because it might not hurt
