### ISSUE TITLE
Add information how to install conda packages

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4481]
related to #4362
conda config --add channels defaults 
conda config --add channels bioconda 
conda config --add channels conda-forge

**Comment by jpfeuffer** [comment]
If you click on the badge in our readme which says "install with bioconda" you see a great overview of installation instructions and depenendcies. There is also a link on how to set up the channels for a general bioconda environment.

**Comment by timosachsenberg** [comment]
ok maybe also put it in the README.md as some here had troubles (e.g. missing conda-forge)

**Comment by timosachsenberg** [comment]
ah  he was mainly referring to pyOpenMS

**Comment by hroest** [comment]
I think you can do

```
$ sudo docker pull quay.io/biocontainers/pyopenms:2.4.0--py36h9de70de_3
$ sudo docker run -it quay.io/biocontainers/pyopenms:2.4.0--py36h9de70de_3 python -c "import pyopenms; print(pyopenms)"
<module 'pyopenms' from '/usr/local/lib/python3.6/site-packages/pyopenms/__init__.py'>
```

it seems to work at least through docker
