### ISSUE TITLE
MaRaClusterAdapter provide option for writing the original output

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4485]
Provide optional outputfile parameter to keep the MaRaCluster output file: 
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MaRaClusterAdapter.cpp#L366

**Comment by Leon-Bichmann** [comment]
Maracluster has two modes of running batch and consensus, which files would you like to keep:

`echo "Clustering spectra"
maracluster batch -b file_list.txt -f ./clusters -a sample -t -10 -c -10,-15,-20

echo "Creating consensus spectra"
maracluster consensus -l ./clusters/sample.clusters_p10.tsv -f ./consensus -o ./consensus/sample_consensus.ms2
`

**Comment by Leon-Bichmann** [comment]
In case both, I would suggest to register two string options for the /clusters and /consensus directories and then copy the temp directories there.

Would this work?
```
String temp_directory_body = makeAutoRemoveTempDirectory_();

File::copyDirRecursively(temp_directory.toQString(), maracluster_cluster_directory.toQString());
```

**Comment by Leon-Bichmann** [comment]
#4490
