### ISSUE TITLE
PeptideIndexer crashes on the MSGF output

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4496]
Hi, 
I have processed the data using MSGFAdapter and the obtained .mzid file I converted to .idXML using IDFileConverter. It works well but it writes a worning: No DatabaseName element found, use read in results at own risk.

After that I apply IDPEP and PeptideIndexer but it also throws a worning: PeptideIndexer found unmatched peptides, which could not be associated to a protein. And that is a problem becouse I want to use ConsensusID afterall but it crashes due to the missing target/decoy information. 

I had some positive expirience with MSGFAdapter and ConsensusID and it was never a problem.

**Comment by jpfeuffer** [comment]
Hi! 
Hmm which enzyme are you using in PeptideIndexer? Be aware that MSGF does not support Proline rules (e.g. only enzymes with "/P" in the end).

**Comment by jpfeuffer** [comment]
The database element should be just a warning. Don't worry about that.

**Comment by mash23** [comment]
I use trypsin. 
Well, I understand that is just a warning, but I can't apply FDR after that because there are too much unmatched peptides/

**Comment by jpfeuffer** [comment]
Can you try Trypsin/P in PeptideIndexer instead?
If this does not help you can still allow "specificity" to be semi or none.

**Comment by mash23** [comment]
I've tried Trypsin/P and different variations of "specificity" but the warning is still and FDR doesn't work.

**Comment by cbielow** [comment]
can you upload the database and the idXML file somewhere?
I'll have a look.

Changing specificity only allow PI to finish but will upset the FDR (because there will be unannotated peptides).

**Comment by mash23** [comment]
Here are the files. 
[](https://drive.google.com/open?id=1nmMLdHeWgH6CNWgkQb-BPgOv7ibrEObB)

**Comment by cbielow** [comment]
ok, thanks.
With the current development version of OpenMS this runs through nicely:
```
15:35:05 NOTICE: PeptideIndexer of node #3 started. Processing ...
Using prefix decoy string 'DECOY_'
MSGFPlus detected but enzyme cutting rules were set to Trypsin. Correcting to Trypsin/P to copy with special cutting rule in MSGFPlus.
Mapping 36140 peptides to 147856 proteins.
Searching with up to 3 ambiguous amino acid(s) and 0 mismatch(es)!
Building trie ... done (0s)
Merge took: 0.02 s (wall), 0.02 s (CPU), 0.00 s (system), 0.02 s (user)
Memory usage (Aho-Corasick): 140 MB (working set delta), 259 MB (peak working set delta)


Aho-Corasick done:
  found 73161 hits for 36140 of 36140 peptides.
Peptide hits passing enzyme filter: 73161
     ... rejected by enzyme filter: 789
-----------------------------------
Peptide statistics

  unmatched                : 0 (0 %)
  target/decoy:
    match to target DB only: 18200 (50 %)
    match to decoy DB only : 17750 (49 %)
    match to both          : 190 (0 %)

  mapping to proteins:
    no match (to 0 protein)         : 0
    unique match (to 1 protein)     : 19208
    non-unique match (to >1 protein): 16932
-----------------------------------
Protein statistics

  total proteins searched: 147856
  matched proteins       : 39867 (39867 new)
  matched target proteins: 19899 (49 %)
  matched decoy proteins : 19968 (50 %)
  orphaned proteins      : 0 (all removed)
-----------------------------------
PeptideIndexer took 15.84 s (wall), 15.84 s (CPU), 1.06 s (system), 14.78 s (user).

==============================================================================
15:35:21 NOTICE: PeptideIndexer finished!
```

Note that it corrected the enzyme automatically after detecting MSGF+.

Compared to OpenMS 2.4, there are a number of other fixes which are probably the reason why this works now.
Can you upgrade using the current nightly installers or wait for Release 2.5 (soon).

**Comment by mash23** [comment]
Ok, I'll do that. Thank you for the help!

**Comment by mash23** [comment]
PeptideIndexer works without wornings now but FDR still crashes with 
"FalseDiscoveryRate failed due to missing information:
Meta value 'target_decoy' does not exist!"

**Comment by cbielow** [comment]
are you sure you used the updated tools and new output files?
It works here.
I'm attaching the TOPPAS pipeline (renamed to `.txt` to allow for upload in GitHub), with PI and FDR nodes. Everything is default except FDR:protein=false (i.e. no protein inference was done)
[FDR.toppas.txt](https://github.com/OpenMS/OpenMS/files/4123543/FDR.toppas.txt)

**Comment by mash23** [comment]
Hmm.. I tried to merge comet and msgf file (IDPEP was applied to both of them). After IDMerger I use ConsensusID and the next step is PeptideIndexer. PeptideIndexer crashes with the warning: 

Potential solutions:
   - check your FASTA database for completeness
   - set 'enzyme:specificity' to match the identification parameters of the search engine
   .........

But There are no warnings or errors when I apply PeptideIndexer to each of the files separetly.

**Comment by jpfeuffer** [comment]
I thought FDR is crashing? Now I am confused. Did you ignore the errors in PeptideIndexer?

If you merge search engines, it can't auto detect the settings for PeptideIndexer. You have to choose the most lenient ones.
enzyme = Trypsin/P

If that does not help:
enzyme:specificity = semi

**Comment by mash23** [comment]
Setting the enzim name to Trypsin/P solved the problem. Thank you for the help!
