### ISSUE TITLE
Writing mzTab requires too much RAM

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#4501]
Peak Memory Usage before calling
`MzTab mztab = MzTab::exportConsensusMapToMzTab(cmap, in_cm, true, true, true, true);`: 4112 MB
Peak Memory Usage after: 26961 MB

This seems very suboptimal.

The final mzTab file is about 3 GB in size. The ConsensusXML is a bit smaller.

**Comment by hroest** [comment]
it seems strange that this produces an object instead of streaming the data to disk like all other implementations in `FORMAT` do -- and a highly inefficient one as well.

**Comment by hroest** [comment]
probably the data structures used in mzTab are simply not efficient, see for example

MzTabPSMSectionRow -> sizeof 704
PeptideEvidence -> sizeof 48
PeptideHit -> sizeof 136

which is empty and almost one 1kb and that is before any data is added in there, eg modification, search engine scores etc. @cbielow can you maybe comment out some code and check at which point the increase in RAM really happens, is it when adding the PSM row or somewhere else?

**Comment by jpfeuffer** [comment]
We are streaming the data now (except metadata). But it is still not the most efficient writer.
