### ISSUE TITLE
Refactor PyOpenMS into separate CMake project?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4503]
While restructuring conda packages, I was wondering if it would be possible to refactor
pyOpenMS into a separate project.
What does pyOpenMS need from OpenMS/SWATH?
Would it work with already installed OpenMS libraries?
Does it need more than the libraries, the headers and some extras (which could be installed into the share)?
Does it need OpenMS to be compiled in a certain way?

My initial gut feeling is that it would work. Maybe this could be tackled then one day.

On a related note, I started on a branch to build pyopenms with CMake to skip some of the distutils hacks that we are doing. It built the Cython libraries but I did not get the packaging to work yet. https://github.com/jpfeuffer/OpenMS/tree/feature/pyopenmsCMake

**Comment by hroest** [comment]
Seems like a good idea, basically building pyOpenMS can be done manually with 

```
python create_cpp_extension.py
python setup.py
```

the main caveat is that it relies on `env.py` to store current build instructions which is then re-used. This contains things like links to the contrib dir, qt-directory etc which should all be the same as the OpenMS build itself. This is generated through CMake:

https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/env.py.in 

so we need to find another way to pass these CMake build variables and do this in a more generic format. This would be a good time to this anyways and introduce a ProjectConfig file (see https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-to-create-a-ProjectConfig.cmake-file ) that can pass internal state variables to other CMake projects. I think if we do that, then it should be straight forward

**Comment by jpfeuffer** [comment]
This was done now.
