### ISSUE TITLE
AMS and FFM use different rounding cutoffs of doubles when writing outputs

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4518]
This makes it impossible to join tables via exact matching of RT and m/z.
If you should do that is debatable, but this is how we currently do it in the tutorials
and it fails miserably.

**Comment by jpfeuffer** [comment]
Could also be TextExporter, since the other should actually use the same ConsensusXML class for writing.

**Comment by oliveralka** [comment]
Example:
ColumnFilter (before joiner - statistical analysis): 125.181508667581
ColumnRename (before joiner - AccurateMassSearch): 125.18150866758

ColumnFilter (statistical analysis) reports one more decimal - can that be enough to throw it off?

**Comment by jpfeuffer** [comment]
yes, it is a join by _exact_ match

**Comment by jpfeuffer** [comment]
we can introduce a rounding in the workflow but I would be in favor of a unified rule for writing floating point decimals of at least the values in features and identifications.

**Comment by jpfeuffer** [comment]
@cbielow suggested to pass doubles to the file/out stream only after internal conversion to our String. This might not have been done yet in TextExporter.
