### ISSUE TITLE
Too bad result from ConsensusID

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4519]
Hello,
I performed protein inference on a sample using each of the three search engines (OMSSA, Comet and MS-GF+) separately as well as using the consensus algorithm. So I got four protein lists. The initial protein mixture was enriched with a known protein, so I expect to get this protein with a score of 1. This happens in OMSSA but the score of this protein is incredibly low in the results of two other engines. The consensus result is also very poor despite the good OMSSA's result.

Is there any way to deal with this? What could be the reason for such varied results? And why does the consensus make so bad ?

You may have a look at the obtained scores below:
omssa 1
comet 0.108371168375015
ms-gf+ 0.26129087805748
consensus 0.159245908260345

**Comment by jpfeuffer** [comment]
Hi,

I assume you are using FidoAdapter?
As mentioned in #4271 you cannot compare the protein scores directly across different runs.
You need to look at the rank or at least compare them via q-values.

**Comment by mash23** [comment]
And q-values are calculated in the FDR ?
Is there any difference if I filter the results in FDR setting pep=0.01 and prot=0.01 or if I do the same in the IDFilter after FDR ?

**Comment by jpfeuffer** [comment]
Yes, they are calculated in the FDR node.
No, filtering in FDR and filtering with IDFilter should be the _same_.

**Comment by mash23** [comment]
I applied FDR to the result of Fido in order to calculate q-values. In the results of OMSSA and MSGF q-value is equal to 0. In the results of Comet and ConsensusID the needed protein isn't presented at all

**Comment by jpfeuffer** [comment]
Ok, then I would look at the scores that Comet assigns to the peptides of this protein.
You can do that by exporting the idXML with Text- or MzTabExporter and look at the protein or accession columns of the peptides.

**Comment by jpfeuffer** [comment]
It might be that Comet pulls down the other search engines.
