### ISSUE TITLE
does it matter if a parameter in a CTD file is float or double

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4539]
I noticed that with OpenMS 2.5 `-write_ctd` will produce paramaters with double instead of float. 

I'm asking because CTDopts currently does not care and transforms everything to float.

**Comment by jpfeuffer** [comment]
Hi. I think they were always doubles, but the precision changed with which we write them out.
So, they should always be parsed to double in the end.
There can only be problems with integers, since we parse as int. If you pass a long, you will have a problem.
