### ISSUE TITLE
command line argument order

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4545]
I noticed that the command line parser of OpenMS uses the value of the first argument if the same argument is given twice. For instance in this test 

https://github.com/OpenMS/OpenMS/blob/d17cc251fd0c4068eb253b03c9fb107897771fdc/src/tests/topp/CMakeLists.txt#L2331

`PeptideIndexer ...  -aaa_max 0 ... -aaa_max 4` is called. According to `-debug 3` the value 0 is used. 

This is might be fine (even if contrary to the usual behaviour of command line tools) but I need to know this for the https://github.com/WorkflowConversion/CTDopts project.

**Comment by jpfeuffer** [comment]
Yes, you were correct. Seems like we parse the CL in reverse order to ease parsing (having the arguments before the parameters). Everything that comes later (i.e. in an earlier position) will be overwritten.

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/APPLICATIONS/TOPPBase.cpp#L2365

for reference

**Comment by bernt-matthias** [comment]
Fine for me now, since I use now ini files f(except for in/output files). Thanks.
