### ISSUE TITLE
FlashDecov viewer

### ISSUE THREAD

**Issue by Dmorgen** [OpenMS/OpenMS#4547]
Hi,

any suggestions how to view the data? any application or R script?

Thanks!
David.

**Comment by JeeH-K** [comment]
Hi David,

Developing FLASHDeconv viewer is in progress.
https://github.com/OpenMS/pyopenms-extra/blob/master/src/apps/FLASHDeconvViewer.py
The current program can be found here. As FLASHDeconv outputs tsv file, using excel or numbers for modifying can be a solution for now. 

Best,
Kim

**Comment by Dmorgen** [comment]
Thanks!

David.
