### ISSUE TITLE
FeatureFinderIdentification and Protein quantifier not working in OpenMS 2.5

### ISSUE THREAD

**Issue by giangiacomoberetta1** [OpenMS/OpenMS#4548]
Dear all,

I will be greatful for any help regarding the following problems.

After updating to OpenMS 2.5 (2.5.0.202002241222) in KNIME (ver. from KNIME 4.1.1) update tool, while running a workflow that was functioning smoothly in OpenMS 2.4, I encountered the following unexpected issues:

FFid: error message

ERROR FeatureFinderIdentification 3:42       Failing process stderr: [Found no signal. The Gaussian width is probably smaller than the spacing in your chromatogram data. Try to use a bigger width., C:\jenkins\ws\openms_release_packaging\9447518b\source\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(107): While storing '': ProteinIdentifications are not unique, which leads to loss of unique PeptideIdentification assignment. Duplicated Protein-ID is:unique_run_identifier., The random chance of this error occuring is 1:2^64. Re-run the last tool and if the error occurs again, please report this as a bug, <Found no signal. The Gaussian width is probably smaller than the spacing in your chromatogram data. Try to use a bigger width.> occurred 3452 times]
ERROR FeatureFinderIdentification 3:42       Return code: 3
ERROR FeatureFinderIdentification 3:42       Execute failed: Failed to execute node FeatureFinderIdentification

Increasing peak_width to 100 from the default 60 didn't solve the problem.

ProteinQuantifier: after replacing FFid with FeatureFinnderSuperhirn, I got the following error message:

ERROR ProteinQuantifier    3:35       T, m/z) 1937.4, 351.729, spectrum_reference not set in ID with precursor (RT, m/z) 1930.1, 351.729, spectrum_reference not set in ID with precursor (RT, m/z) 6828.4, 502.811, spectrum_reference not set in ID with precursor (RT, m/z) 6924.9, 728.057, spectrum_reference not set in ID with precursor (RT, m/z) 3136.3, 530.297, spectrum_reference not set in ID with precursor (RT, m/z) 2229.3, 357.693, spectrum_reference not set in ID with precursor (RT, m/z) 6997.3, 797.863, spectrum_reference not set in ID with precursor (RT, m/z) 5107.5, 441.265, spectrum_reference not set in ID with precursor (RT, m/z) 4141.1, 384.718, spectrum_reference not set in ID with precursor (RT, m/z) 4145.3, 384.718, spectrum_reference not set in ID with precursor (RT, m/z) 6961.3, 525.768, spectrum_reference not set in ID with precursor (RT, m/z) 6189.8, 616.853, spectrum_reference not set in ID with precursor (RT, m/z) 4455.5, 379.749, spectrum_reference not set in ID with precursor (RT, m/z) 3516.1, 467.738, spectrum_reference not set in ID with precursor (RT, m/z) 4528.5, 481.276, spectrum_reference not set in ID with precursor (RT, m/z) 5516.7, 894.431, spectrum_reference not set in ID with precursor (RT, m/z) 2021.5, 373.706, spectrum_reference not set in ID with precursor (RT, m/z) 3963.1, 356.669, spectrum_reference not set in ID with precursor (RT, m/z) 3594, 420.787, spectrum_reference not set in ID with precursor (RT, m/z) 4218.3, 477.305, spectrum_reference not set in ID with precursor (RT, m/z) 2883.9, 416.25, spectrum_reference not set in ID with precursor (RT, m/z) 2625.9, 449.708, spectrum_reference not set in ID with precursor (RT, m/z) 7171.8, 709.887, spectrum_reference not set in ID with precursor (RT, m/z) 2840.8, 568.298, spectrum_reference not set in ID with precursor (RT, m/z) 5532.6, 388.737, spectrum_reference not set in ID with precursor (RT, m/z) 5533.4, 388.737, spectrum_reference not set in ID with precursor (RT, m/z) 1888.8, 358.719, spectrum_reference not set in ID with precursor (RT, m/z) 6542.2, 469.279, spectrum_reference not set in ID with precursor (RT, m/z) 2695.1, 462.228, spectrum_reference not set in ID with precursor (RT, m/z) 2690, 375.711, spectrum_reference not set in ID with precursor (RT, m/z) 2633.4, 483.748, spectrum_reference not set in ID with precursor (RT, m/z) 3689.4, 379.731, spectrum_reference not set in ID with precursor (RT, m/z) 6968.4, 564.766, spectrum_reference not set in ID with precursor (RT, m/z) 5425.6, 619.316, spectrum_reference not set in ID with precursor (RT, m/z) 3514.3, 466.782, spectrum_reference not set in ID with precursor (RT, m/z) 7080.4, 631.314, spectrum_reference not set in ID with precursor (RT, m/z) 5249.8, 445.759, spectrum_reference not set in ID with precursor (RT, m/z) 7293, 1080.08, spectrum_reference not set in ID with precursor (RT, m/z) 7194.4, 540.651, spectrum_reference not set in ID with precursor (RT, m/z) 3054.3, 401.745, spectrum_reference not set in ID with precursor (RT, m/z) 1938.4, 568.239, spectrum_reference not set in ID with precursor (RT, m/z) 5230.9, 803.402, spectrum_reference not set in ID with precursor (RT, m/z) 3029.1, 510.732, spectrum_reference not set in ID with precursor (RT, m/z) 1529.7, 424.208, spectrum_reference not set in ID with precursor (RT, m/z) 4580.6, 542.277, spectrum_reference not set in ID with precursor (RT, m/z) 2955.7, 488.742, spectrum_reference not set in ID with precursor (RT, m/z) 4221.3, 465.242, spectrum_reference not set in ID with precursor (RT, m/z) 2438, 592.825, spectrum_reference not set in ID with precursor (RT, m/z) 2770.2, 490.263, spectrum_reference not set in ID with precursor (RT, m/z) 2577.8, 433.741, spectrum_reference not set in ID with precursor (RT, m/z) 3909.3, 575.308, spectrum_reference not set in ID with precursor (RT, m/z) 1444.3, 422.73, spectrum_reference not set in ID with precursor (RT, m/z) 2692.6, 508.743, spectrum_reference not set in ID with precursor (RT, m/z) 2084.7, 458.23, spectrum_reference not set in ID with precursor (RT, m/z) 3572.9, 438.253, spectrum_reference not set in ID with precursor (RT, m/z) 5835.9, 814.914, spectrum_reference not set in ID with precursor (RT, m/z) 1424.7, 431.229, spectrum_reference not set in ID with precursor (RT, m/z) 3699.5, 508.292, spectrum_reference not set in ID with precursor (RT, m/z) 4047.6, 459.229, spectrum_reference not set in ID with precursor (RT, m/z) 2714.6, 508.744, spectrum_reference not set in ID with precursor (RT, m/z) 2382.2, 403.219, spectrum_reference not set in ID with precursor (RT, m/z) 3729.1, 562.303, spectrum_reference not set in ID with precursor (RT, m/z) 2398.9, 598.296, spectrum_reference not set in ID with precursor (RT, m/z) 5175.9, 517.766, spectrum_reference not set in ID with precursor (RT, m/z) 1402.6, 431.23, spectrum_reference not set in ID with precursor (RT, m/z) 4197.3, 600.827, spectrum_reference not set in ID with precursor (RT, m/z) 2956.1, 672.362, spectrum_reference not set in ID with precursor (RT, m/z) 3396.1, 519.266, spectrum_reference not set in ID with precursor (RT, m/z) 3124.2, 398.193, spectrum_reference not set in ID with precursor (RT, m/z) 3234.3, 534.314, spectrum_reference not set in ID with precursor (RT, m/z) 2256.2, 377.694, spectrum_reference not set in ID with precursor (RT, m/z) 2487.1, 506.757, spectrum_reference not set in ID with precursor (RT, m/z) 2422, 493.771, spectrum_reference not set in ID with precursor (RT, m/z) 2193.1, 399.676, spectrum_reference not set in ID with precursor (RT, m/z) 2411.7, 420.258, spectrum_reference not set in ID with precursor (RT, m/z) 3414.7, 578.321, spectrum_reference not set in ID with precursor (RT, m/z) 5851.7, 736.39, spectrum_reference not set in ID with precursor (RT, m/z) 3837.1, 617.327, spectrum_reference not set in ID with precursor (RT, m/z) 4268.7, 465.766, spectrum_reference not set in ID with precursor (RT, m/z) 4339.6, 474.26, spectrum_reference not set in ID with precursor (RT, m/z) 1915.4, 410.693, spectrum_reference not set in ID with precursor (RT, m/z) 3577.6, 523.254, spectrum_reference not set in ID with precursor (RT, m/z) 1981, 378.7, spectrum_reference not set in ID with precursor (RT, m/z) 3200.1, 603.833, spectrum_reference not set in ID with precursor (RT, m/z) 3611.7, 454.244, spectrum_reference not set in ID with precursor (RT, m/z) 1262.4, 398.227, spectrum_reference not set in ID with precursor (RT, m/z) 3435.9, 451.224, spectrum_reference not set in ID with precursor (RT, m/z) 2037.2, 458.746, spectrum_reference not set in ID with precursor (RT, m/z) 4790.1, 566.311, spectrum_reference not set in ID with precursor (RT, m/z) 3471.9, 472.229, spectrum_reference not set in ID with precursor (RT, m/z) 2580, 447.212, spectrum_reference not set in ID with precursor (RT, m/z) 4270.7, 436.237, spectrum_reference not set in ID with precursor (RT, m/z) 2003.1, 507.252, spectrum_reference not set in ID with precursor (RT, m/z) 2272.4, 511.269, spectrum_reference not set in ID with precursor (RT, m/z) 4106.6, 562.299, spectrum_reference not set in ID with precursor (RT, m/z) 4048.5, 691.814, spectrum_reference not set in ID with precursor (RT, m/z) 5505.9, 594.823, spectrum_reference not set in ID with precursor (RT, m/z) 3307.9, 516.234, spectrum_reference not set in ID with precursor (RT, m/z) 2199.3, 357.693, spectrum_reference not set in ID with precursor (RT, m/z) 2765.7, 495.721, spectrum_reference not set in ID with precursor (RT, m/z) 5266.6, 521.758, spectrum_reference not set in ID with precursor (RT, m/z) 3374.9, 487.256, spectrum_reference not set in ID with precursor (RT, m/z) 2949.8, 476.753, spectrum_reference not set in ID with precursor (RT, m/z) 3510.8, 467.737, spectrum_reference not set in ID with precursor (RT, m/z) 3363.7, 519.267, spectrum_reference not set in ID with precursor (RT, m/z) 3349.2, 490.752, spectrum_reference not set in ID with precursor (RT, m/z) 3189, 534.315, spectrum_reference not set in ID with precursor (RT, m/z) 2921.8, 416.25, spectrum_reference not set in ID with precursor (RT, m/z) 2508.6, 440.214, spectrum_reference not set in ID with precursor (RT, m/z) 2727.6, 462.227, spectrum_reference not set in ID with precursor (RT, m/z) 3050.6, 383.22, spectrum_reference not set in ID with precursor (RT, m/z) 2873.6, 521.262, spectrum_reference not set in ID with precursor (RT, m/z) 3560.4, 466.781, spectrum_reference not set in ID with precursor (RT, m/z) 2383.2, 558.306, spectrum_reference not set in ID with precursor (RT, m/z) 1975.4, 568.239, spectrum_reference not set in ID with precursor (RT, m/z) 3779.7, 461.237, spectrum_reference not set in ID with precursor (RT, m/z) 5207.6, 505.277, spectrum_reference not set in ID with precursor (RT, m/z) 3769, 474.743, spectrum_reference not set in ID with precursor (RT, m/z) 4730.1, 740.362, spectrum_reference not set in ID with precursor (RT, m/z) 2931.8, 559.29, spectrum_reference not set in ID with precursor (RT, m/z) 2712.1, 445.758, spectrum_reference not set in ID with precursor (RT, m/z) 2176.3, 404.713, spectrum_reference not set in ID with precursor (RT, m/z) 5151.1, 511.289, spectrum_reference not set in ID with precursor (RT, m/z) 5568.4, 677.362, spectrum_reference not set in ID with precursor (RT, m/z) 4409, 514.808, spectrum_reference not set in ID with precursor (RT, m/z) 2365.4, 351.738, spectrum_reference not set in ID with precursor (RT, m/z) 4134.5, 526.284, spectrum_reference not set in ID with precursor (RT, m/z) 5086.4, 717.324, spectrum_reference not set in ID with precursor (RT, m/z) 6002.6, 680.358, spectrum_reference not set in ID with precursor (RT, m/z) 1688.7, 402.213, No fractions annotated in consensusXML. Assuming unfractionated., Error: Unexpected internal error (PSM  does not map to an MS file registered in the quantitative metadata. Check your merging and filtering steps and/or report the issue, please.), <No fractions annotated in consensusXML. Assuming unfractionated.> occurred 4 times]
ERROR ProteinQuantifier    3:35       Failing process stderr: []
ERROR ProteinQuantifier    3:35       Return code: 8
ERROR ProteinQuantifier    3:35       Execute failed: Failed to execute node ProteinQuantifier

Thnks in advance !

**Comment by timosachsenberg** [comment]
Hi,
thanks for reporting. Can you make me the workflow available so we can check? Maybe it's just related to some new or changed parameters in 2.5.

**Comment by giangiacomoberetta1** [comment]
Thank you so much Timo!

I am going to send you the workflow trough wetransfer.

I will send the raw and accessory files too, separately.

G

**Comment by timosachsenberg** [comment]
can you try a quick workaround? right click on the FeatureFinderIdentification node, output file types, then deaktivate the candidates_out port

**Comment by giangiacomoberetta1** [comment]
Hi!I try immediately!Il 28 feb 2020 14:02, Timo Sachsenberg <notifications@github.com> ha scritto:can you try a quick workaround? right click on the FeatureFinderIdentification node, output file types, then deaktivate the candidates_out port

**Comment by giangiacomoberetta1** [comment]
Super! Deactivation of candidates_out  in FFId solved the issue!

ProteinQuantifier is still sending the same error message

**Comment by timosachsenberg** [comment]
Ok another idea... can you deactivate the two other unused output ports of ProteinQuantifier?
If ProteinQuantifier doesn't generate a mzTab file it should not care if some ID files have missing spectrum_references.

**Comment by giangiacomoberetta1** [comment]
After deactivation of the two unused ports, the error disappears and the node works fine. At the subsequent csv reader the output results nice, one just have to change the column delimiter into "\t" to get the correct data table layout.

Thank you so much for help!

**Comment by timosachsenberg** [comment]
You are welcome! Hope we can fix this nuisance soon.
