### ISSUE TITLE
TOPPView silently fails to create vector image on Linux without explicit svg extension

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#4554]
Exporting an image with **Right-click**->Save->as image->vector images does not create the image file unless it has SVG at the end of the filename. I can confirm this effects Ubuntu 18.04 (and earlier) as well as Ubuntu 19.10

**Comment by timosachsenberg** [comment]
I think SVG is the only one that Qt supports so enforcing that extension should work.
