### ISSUE TITLE
ProteomicsLFQ

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#4558]
ProteomicsLFQ crashes when I set "Transfer IDs" to either "merged" or "SVM". The error message is "Error: Unexpected internal error (Using seeds and external ids is currently not supported.)
<Warning: no MS1 spectrum for this precursor> occurred 9 times
<Found no signal. The Gaussian width is probably smaller than the spacing in your chromatogram data. Try to use a bigger width.> occurred 235 times"

...is this parameter not yet supported? ProteomicsLFQ works fine Transfer IDs" set to "False".

**Comment by timosachsenberg** [comment]
Yes this one is very experimental. We currently can’t advice to use it.

**Comment by timosachsenberg** [comment]
@oliverschilling I just checked and it seems that this error should (in principle) only occur if the SVM option is selected. Can you quickly check if it also happens for the "merged" option?

**Comment by christinaca** [comment]
Selecting „merged“ leads to an Error, too. In my case the error message is the same as in the SVM case, <no MS1 spectrum for this persecutor>

**Comment by timosachsenberg** [comment]
Thanks! we will look into that

**Comment by christinaca** [comment]
Thank you very much

**Comment by timosachsenberg** [comment]
I will add this to the other issue and close this one
