### ISSUE TITLE
Some Elements missing in in Elements.xml

### ISSUE THREAD

**Issue by jamesETsmith** [OpenMS/OpenMS#4563]
Hello, 

I'm using `pyOpenMS` to help build some data analysis tools for a MS experiment involving inorganic compounds. When trying to predict the isotopic abundance of Indium containing compound I noticed that indium and several other elements were missing from the `Elements.xml` file. Is this intentional? If not, would it be possible to add them? I'm happy to make a pull request if you want. 

I understand that I can modify the file locally, but it would be a better long term solution, in my opinion, if `pyOpenMS` contained elements like Indium natively.

Here is a minimal example to reproduce the error:

```python
>>> from pyopenms import EmpiricalFormula, CoarseIsotopePatternGenerator
>>> wm = EmpiricalFormula("In")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyopenms/pyopenms_4.pyx", line 2778, in pyopenms.pyopenms_4.EmpiricalFormula.__init__
  File "pyopenms/pyopenms_4.pyx", line 2757, in pyopenms.pyopenms_4.EmpiricalFormula._init_1
RuntimeError: 'In' found. Please use only valid element identifiers or modify share/OpenMS/CHEMISTRY/Elements.xml! in: Unknown element 'In'
```

Thanks,
James

**Comment by timosachsenberg** [comment]
Hi, thanks for reporting! We would be really happy if you could open a PR and add the missing elements.

**Comment by hroest** [comment]
We currently only represent 63 out of 118 elements:

```
$ grep -I AtomicNumber share/OpenMS/CHEMISTRY/Elements.xml   | sort | uniq | wc
     63     311    3578
```

and we are missing 21, 36, 39, 41, 43, 45, 49, 54, 59 (Sc, Kr, Y, Nb, Tc, Rh, In, Xe, Pr) and then whole bunch after. Granted, not the most important ones but still we should add a few more in that range

**Comment by jpfeuffer** [comment]
We should decide which other Elements we would like and add them, too.

**Comment by poshul** [comment]
@cbielow I see you have a comment in the Elements.xml about Deuterium and Tritium causing mem-leaks. Can you expand on that. Is this something that means that we should limit the addition of new elements?

**Comment by poshul** [comment]
Elements have been moved to:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/ElementDB.cpp
