### ISSUE TITLE
pyopenms dist scripts do not work

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4567]
https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/dist-scripts/create-manylinux.sh#L35

`/data/create-manylinux.sh: line 36: /opt/python/cp27*/bin/pip: No such file or directory`

Seems like they dropped support for py2?
@hroest should we just remove the py2 parts?

**Comment by jpfeuffer** [comment]
After removing py2:
`ImportError: cannot import name 'open_for_csv' from 'wheel.util' (/opt/_internal/cpython-3.7.6/lib/python3.7/site-packages/wheel/util.py)`

**Comment by hroest** [comment]
yes, I noticed that too. It can be fixed as follows

```
install -U wheel==0.31.1
```

when you do pip install of the wheel
