### ISSUE TITLE
Running TextExporter without output file

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4572]
Just silently does nothing.

**Comment by jpfeuffer** [comment]
Then "out" is not mandatory?

**Comment by timosachsenberg** [comment]
It says: Output file (mandatory for featureXML and idXML) (valid formats: 'csv')
but this is not tested

**Comment by timosachsenberg** [comment]
if we agree on something we can add it to: https://github.com/OpenMS/OpenMS/pull/4573

**Comment by jpfeuffer** [comment]
make it mandatory. How would it work without an output??

**Comment by timosachsenberg** [comment]
need to check... maybe the mzML input has some special logic. e.g., just prints on screen
