### ISSUE TITLE
Trouble compiling WildMagic

### ISSUE THREAD

**Issue by mboisson** [OpenMS/OpenMS#4581]
Hi,
I am trying to compile WildMagic manually, without using the contrib folder, because we have as a policy to avoid installers that download dependencies, we want to have dependencies as standalone modules instead of bundled. 

Unfortunately, WildMagic's build system is terrible (just hard-coded makefiles). However, it seems that your contrib script uses cmake to somehow rebuild those makefile ? Is that correct ?

Do you have pointers on how to compile WildMagic correctly manually ? 

Right now, I am stuck between needing to compile it as a Dynamic library, and compiling it as a Static library. If I compile it as a static library, then OpenMS complains that the `.a` files are not compiled with position independent code. If I compile it as a static library, then OpenMS goes further and links against the `.so`, but it later complains that it can not find the static archives (`.a` files).

**Comment by jpfeuffer** [comment]
Hmm it might be that we are using the sources from a fork with Cmake support (e.g. here https://github.com/bazhenovc/WildMagic)

But if you want, you can also download the sources that we are using manually, check them for viruses or whatever needs to be done and drop them in a "contrib-build/archive" folder. If our CMake system finds them, it does not download them again.

The contrib sources are here:
http://ftp.mi.fu-berlin.de/pub/OpenMS/contrib-sources/

**Comment by mboisson** [comment]
Thanks. This should help. I also notice that your cmake build applies patches. Where are those ?

**Comment by jpfeuffer** [comment]
Correct. They are here: https://github.com/OpenMS/contrib/tree/master/patches
Or in the corresponding folder of your cloned repo.

**Comment by mboisson** [comment]
Mmm, it appears that the sources from the fork of CMake just don't work. They use a cmake function that does not exist : 
CMake Error at SampleGraphics/CMakeLists.txt:1 (ADD_WM5_APP):
  Unknown CMake command "ADD_WM5_APP".

**Comment by jpfeuffer** [comment]
The same problem? When I download the tarball, the SampleGraphics folder does not even exist.

**Comment by jpfeuffer** [comment]
Just follow the steps:
1) Download http://ftp.mi.fu-berlin.de/pub/OpenMS/contrib-sources/WildMagic5.tar.gz
2) ungzip, untar
3) Replicate the following copy operations:
  configure_file(${PROJECT_SOURCE_DIR}/patches/wildmagic/root_CMakeLists.txt ${WILDMAGIC_DIR}/CMakeLists.txt COPYONLY)
  configure_file(${PROJECT_SOURCE_DIR}/patches/wildmagic/libcore_CMakeLists.txt ${WILDMAGIC_DIR}/LibCore/CMakeLists.txt COPYONLY)
  configure_file(${PROJECT_SOURCE_DIR}/patches/wildmagic/libmath_CMakeLists.txt ${WILDMAGIC_DIR}/LibMathematics/CMakeLists.txt COPYONLY)

4) Apply patches
5) mkdir build && cd build
6) cmake -DCMAKE_INSTALL_PREFIX="where you want" ../
7) cmake --build . --target install --config Release

This is all we do in the contrib.

**Comment by mboisson** [comment]
ok, that got me further, but now it wants to build documentation and wants to use an external display, which we don't have (we're on a cluster, and we are building in an automated way)... any way to disable building documentation ? 

It seems like the generated makefile for OpenMS has tens or hundreds of targets, and no way to disable just one. 

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Creating the algorithm parameter and TOPP parameter documentation

Note: A functioning OpenMS/TOPP installation and a running X-server (Unix) is required for this step!
      Windows only: OpenMS and Open_GUI.dll's need to be accessible by the Documenter executables in
      doxygen/parameters/. If the automatic CMake post build copy step did not work, try to add them
      to your Path variable.
      If this step fails, use the target 'doc_minimal'.

Building OpenMS parameter docu:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
QXcbConnection: Could not connect to display
Child aborted
make[2]: *** [doc/CMakeFiles/doc_param_internal.dir/build.make:71: doc/CMakeFiles/doc_param_internal] Error 1
make[1]: *** [CMakeFiles/Makefile2:35208: doc/CMakeFiles/doc_param_internal.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by mboisson** [comment]
ok, this seems to have allowed me to build it. What is the exact version of that WildMagic source ? It only says WildMagic 5...

**Comment by jpfeuffer** [comment]
Great! According to the header files, it should be 5.0.

**Comment by mboisson** [comment]
Any reason not to use a more recent version ? Latest version is 5.17, from what I found.

**Comment by jpfeuffer** [comment]
No, I would hope that it works with them, too. We would need to look into how to incorporate the new sources in the contrib build script though.

**Comment by mboisson** [comment]
I tried with the same instructions, with version 5.17 from their download website (https://www.geometrictools.com/Downloads/) and the CMakeFile and the patches have worked apparently correctly. Trying to rebuild OpenMS with that version now.

**Comment by jpfeuffer** [comment]
Cool yeah I think we only need the Core and Mathematics sublibrary. And as long as there were no files added in them, the CMake scripts should still work.

**Comment by mboisson** [comment]
ah.... OpenMS does not build with that version :/ 
```../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<double>::GetEigenvectors(double*) const »```

**Comment by jpfeuffer** [comment]
Hmm, it seems like it uses the old library to look up symbols. The SymmetricEigensolver only exists in 5.17. So it definitely tries to use it.

**Comment by mboisson** [comment]
Since this is for GUI, I am attempting a build without GUI... GUI should not be used on a cluster anyway.

**Comment by jpfeuffer** [comment]
For this, we have a flag "-DWITH_GUI=OFF".

**Comment by mboisson** [comment]
> For this, we have a flag "-DWITH_GUI=OFF".

yes, I figured it out through `ccmake ..`

**Comment by mboisson** [comment]
but that just delays the issue to another library... 
```
[ 32%] Building CXX object src/superhirn/CMakeFiles/SuperHirn.dir/source/TRANSFORMATIONS/FEATUREFINDER/SUPERHIRN/MSPeak.cpp.o
../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<double>::GetEigenvectors(double*) const »
../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<double>::SymmetricEigensolverGTE(int, unsigned int) »
../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<float>::GetEigenvalues(float*) const »
../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<double>::IsRotation() const »
../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<float>::IsRotation() const »
../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<float>::SymmetricEigensolverGTE(int, unsigned int) »
../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<double>::Solve(double const*, int) »
../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<float>::Solve(float const*, int) »
../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<float>::GetEigenvectors(float*) const »
../../lib/libOpenMS.so : référence indéfinie vers « Wm5::SymmetricEigensolverGTE<double>::GetEigenvalues(double*) const »
```

**Comment by jpfeuffer** [comment]
I just built it successfully with this version. You probably should clean all your build folders since especially the CMakeCache might still have references to the old library. And also CMake won't build/install the new libraries if there are others in the same folder.

**Comment by mboisson** [comment]
Mmm, that is strange. I build in a "build" directory, which I completely erase before rerunning cmake...

**Comment by jpfeuffer** [comment]
Did you clean both the contrib and OpenMS?

**Comment by mboisson** [comment]
I don't use the contrib, unless it silently does ? 

I install dependencies on the side, and I cmake with 
```
rm -rf *; cmake .. -DSEQAN_INCLUDE_DIR=$EBROOTSEQANMINLIBRARY/include -DLIBSVM_INCLUDE_DIR=$EBROOTLIBSVM/include -DCMAKE_SYSTEM_PREFIX_PATH=$NIXUSER_PROFILE -DLIBSVM_LIBRARY=$EBROOTLIBSVM/lib/libsvm.so.2 -DLIBSVM_LIBRARY_RELEASE=$EBROOTLIBSVM/lib/libsvm.so.2 -DCOIN_ROOT_DIR=$EBROOTCOINMP -DGLPK_ROOT_DIR=$EBROOTGLPK -DEIGEN3_INCLUDE_DIR=$EBROOTEIGEN/include -DWM5_DIR=$EBROOTWILDMAGIC -DENABLE_DOCS=OFF -DWITH_GUI=OFF
```

**Comment by jpfeuffer** [comment]
Ah hmm ok. No, it does not silently use the contrib. But CMake will look for system-wide libraries in case you (accidentally?) installed the earlier WM in /usr/lib or something.

I can also double-check again. Maybe it cached something on my computer.

**Comment by mboisson** [comment]
We don't install anything in default paths. It does not find anything unless I point it to explicit paths.

**Comment by mboisson** [comment]
After the above `cmake` command, I just used `make -j 20` to build. Is there any chance this is a difference that might explain that it works for you and not for me ?

**Comment by lopippo** [comment]
mboisson: Did you solve the undefined reference linker errors ? I have found the problem, I guess, while packaging OpenMS.

**Comment by mboisson** [comment]
I did manage to install it, although I don't recall what I did exactly.

**Comment by poshul** [comment]
We no longer require WM
