### ISSUE TITLE
pyopenms: method should be static

### ISSUE THREAD

**Issue by uweschmitt** [OpenMS/OpenMS#4585]
This is a declaration for a member method, but underlying C++ method is static:

https://github.com/OpenMS/OpenMS/blob/e26c2ced530423f0c3fcfa077e38d41da1cb12dd/src/pyOpenMS/pxds/TransformationModelLowess.pxd#L16

**Comment by jpfeuffer** [comment]
Thanks a lot for reporting this. The underlying method must have changed in the past.
How did you find out? Would there be a way to automatically test the correctness for every method?
We have some tests for after loading the module in python but they surely do not cover everything.

**Comment by hroest** [comment]
@jpfeuffer we do have a script that tests the bindings and produces a report: https://github.com/OpenMS/OpenMS/blob/develop/tools/PythonExtensionChecker.py which performs validation and checking of the extensions. Also, what really matters are the tests and if we can use the functions and they work that is probably the most important part.
