### ISSUE TITLE
PeptideIndexer crashes with MSGFPlusAdapter output

### ISSUE THREAD

**Issue by Monod79** [OpenMS/OpenMS#4614]
:\jenkins\ws\openms_release_packaging\9447518b\source\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(107): While loading 'D:\Downloads\OF_20181027_LEC_02_HeLa_Cyto_n1.idXML': string representation overflows output binary result( in line 4 column 336)

Maybe related to https://github.com/OpenMS/OpenMS/issues/2666 ?

**Comment by jpfeuffer** [comment]
Hi! Yes, this is possible. Which version of MSGFPlus are you using?

**Comment by Monod79** [comment]
I’m using the latest version: Release 2020.03.14

I guess I’ll have to reinstall the default version coming with the 2.5.0 release.

Jonathan Boulais, PhD

Analyste en bio-informatique & protéomique
Computational analyst in proteomics

Institut de recherches cliniques de Montreal (IRCM)
Montreal Clinical Research Institute
110 avenue des Pins Ouest
Montreal (Qc) H2W 1R7
Canada

Phone: 514 987-3245
Fax: 514 987-5624
[cid:AAECBC98-01EE-4DD5-ABEF-7A30D9A3C997@ircm.priv]

De : jpfeuffer <notifications@github.com>
Envoyé : Monday, March 30, 2020 5:12 AM
À : OpenMS/OpenMS <OpenMS@noreply.github.com>
Cc : BOULAIS Jonathan <Jonathan.Boulais@ircm.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [OpenMS/OpenMS] PeptideIndexer crashes with MSGFPlusAdapter output (#4614)


Hi! Yes, this is possible. Which version of MSGFPlus are you using?

**Comment by jpfeuffer** [comment]
I'm afraid so. Unless you manually want to find/replace the entry from "-1" to "1000" as with the old version. Or use the nightly version when the fix is merged.

**Comment by Monod79** [comment]
I confirm that the MSGFPlus version was the problem. Everything runs smoothly now.


Thanks for the great work guys !!!


Jonathan


Jonathan Boulais, PhD

Analyste en bio-informatique & protéomique
Computational analyst in proteomics

Institut de recherches cliniques de Montreal (IRCM)
Montreal Clinical Research Institute
110 avenue des Pins Ouest
Montreal (Qc) H2W 1R7
Canada

Phone: 514 987-5647
Fax: 514 987-5624
________________________________

**Comment by jpfeuffer** [comment]
In the nightly installer it should work with newer msgfplus versions now.
