### ISSUE TITLE
[Win] Comet and MSGF secondary outputs locked/unreadable/broken

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4617]
This affects CometAdapter_1_out_{1,2,3}.tmp.tsv and MSGFPlusAdapter_1_out2.tmp.mzid

@cbielow Any idea? Can you reproduce that? On the build machines, the build user does not have GUI access, so I can only check with another user. When I want to read them with e.g. Notepad++, it says "Can not open file"

Happens with the new and the old version of Comet. And since it affects MSGF as well, it is probably our way of moving the file or our temporary folder creation/deletion.

**Comment by jpfeuffer** [comment]
This also means they cannot be deleted and this might cause problems when testing again in the same folder, since by default we do not overwrite. @timosachsenberg

**Comment by timosachsenberg** [comment]
ok I see. Do you think this is specific to our build machine?

**Comment by timosachsenberg** [comment]
Otherwise I would suggest to merge the THIRDPARTY so we can test them

**Comment by jpfeuffer** [comment]
I don't even know if that is the cause. If those files are still present, the tool should actually fail. And not produce empty IdXMLs.

**Comment by jpfeuffer** [comment]
In any case I think we should not write the idXML output if we are not sure if we fail yet here:
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/CometAdapter.cpp#L621

And probably we should actually make overwriting a default and not fail.

**Comment by cbielow** [comment]
I cannot reproduce the `cannot-delete` issue, but the tests spuriously fail because Comet generates output pep.xmls with no PSMs.
I've opened an issue on the Comet Google group: https://groups.google.com/forum/#!topic/comet-ms/-vuB2b8nfCE

**Comment by cbielow** [comment]
I found the bug in Comet (https://github.com/cbielow/comet-ms/pull/1/files). Lets update to the new Comet once its released officially.

**Comment by cbielow** [comment]
I think this is resolved using the latest comet. reopen if not.
