### ISSUE TITLE
LuciPhor2 Version Bioconda

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4622]
Hi @bernt-matthias,

do you by chance know which luciphor2 version is currently in bioconda? 
It is already the mavenised version from
https://github.com/dfermin/lucXor/tree/mavenize

Which is currently in the "new" OpenMS Thirdparty 
https://github.com/OpenMS/THIRDPARTY/pull/60

This should fix some issues with higher java versions and probably some mzML parsing issues. 

As discussed here:
https://github.com/dfermin/lucXor/issues/2
https://github.com/dfermin/lucXor/issues/4

**Comment by bernt-matthias** [comment]
I don't think so. I just took it from https://downloads.sourceforge.net/project/luciphor2/luciphor2.jar .. and in order to have a stable download link I deposited in the Galaxy depot https://github.com/galaxyproject/cargo-port/pull/164

I guess one could make a bioconda release bound to a commit of this project, but a proper release would be better.

**Comment by oliveralka** [comment]
@bernt-matthias 
It seems there is a new release now: https://sourceforge.net/projects/luciphor2/files/luciphor2_1.jar/download 

Would it be possible to add it to bioconda (I can help here as well!). 
Should the file be renamed to luciphor2.jar before uploading to cargo-port?

**Comment by bernt-matthias** [comment]
Step 1 started https://github.com/galaxyproject/cargo-port/pull/168

**Comment by bernt-matthias** [comment]
ping @oliveralka 

step 2 bioconda https://github.com/bioconda/bioconda-recipes/pull/21375

**Comment by oliveralka** [comment]
New Version is integrated and can be installed via conda/bioconda:

`conda install -c bioconda luciphor2`

Thanks @bernt-matthias

**Comment by bernt-matthias** [comment]
Just a question. The openms third party requirement will be updated with the next release?

**Comment by jpfeuffer** [comment]
Yeah right. Although Luciphor in particular might work, for others we had to fix littler things and support new features. So we will update them in batch to make sure everything is working together.
