### ISSUE TITLE
Drop support for older compilers and up the C++ version to 14 or 17 ...

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#4624]
to enable support for C++14 or maybe even C++17 in OpenMS and avoid bugs in older compilers such as g++4.9 (see e.g. #4610) lets collect information on what the currently common denominator/requirement is for compilers we need to support.

I will update this page with information we collect below.

We need support to build:

## pyOpenMS using Python 3 
Python 2.7 and 3.5 is end-of-life. We should start at 3.6.

## manylinux.2014 (g++8)
uses: Red Hat 8.3.1-3 and  8.3.1 and thus supports C++17. We just upgraded our manylinux+contrib container.

## Linux:
Oldest LTS Redhat that we want to support is .... and requires g++ ???
Oldest LTS Ubuntu would probably be 16.04 which has g++-5.4 -> C++14 (if we go with 18.04 it has g++8 -> C++17)

## Windows
C++17: since VS2019
C++14: since Visual Studio 2015 Update 3
We use VS2019 for (nightly) pyopenms already.

We recently found an OpenMP compiler bug in VS15 and VS17 (see #4389), which would support to switch to VS2019 as minimal requirement.

## MacOS
Let's say we support until High Sierra (10.13), then the last/newest compatible XCode (or its command line tools) would be 10.1 which has
an AppleClang based on LLVM 6.0.1 which according to https://clang.llvm.org/cxx_status.html has full ISO C++17 support.
If we go back one more, Sierra, we would need to stick to C++14.

**Comment by timosachsenberg** [comment]
:heart_eyes: C++17 :heart_eyes:

**Comment by jpfeuffer** [comment]
I added my comments.

**Comment by cbielow** [comment]
so 17 it is? :)

**Comment by cbielow** [comment]
@hroest can you give some feedback on the matter :)

**Comment by cbielow** [comment]
some advantages of C++17:
 - support for `if constexpr(...)`, e.g. `if constexpr(std::is_arithmetic_v<type>)` 
 - auto-return types 
 - much better lambdas
 - template argument deduction (`std::pair p(2, 4.5);`)
 - structured bindings `auto [a, i, b] = mytuple();`
 - and many smaller API improvements for STL: vector::emplace_back with return type

there is probably much more...

**Comment by jpfeuffer** [comment]
Don't forget std::variant/optional, parallel STL algorithms and stringviews (e.g. for our digestion classes)

**Comment by cbielow** [comment]
Since there are no objections, lets go for C++17.

I volunteer to replace all the GCC4.7 annotations, where we needed to hack around some compiler limitations.

**Comment by cbielow** [comment]
we have a PR coming up which requires C17 (`if constexpr...`)

**Comment by poshul** [comment]
Can we mark this as complete now?

**Comment by cbielow** [comment]
IMHO yes.
Re-open if I missed something.
