### ISSUE TITLE
QTCluster happily working with exceptions

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4625]
making it impossible to use exception breakpoints.
https://github.com/OpenMS/OpenMS/blob/d17cc251fd0c4068eb253b03c9fb107897771fdc/src/openms/source/ANALYSIS/MAPMATCHING/QTClusterFinder.cpp#L457

**Comment by timosachsenberg** [comment]
thrown from here 

https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/COMPARISON/CLUSTERING/HashGrid.h#L429
