### ISSUE TITLE
[Discussion] Unreasonable output precision of our new boost::karma generators?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4627]
https://github.com/jpfeuffer/OpenMS/blob/master/src/openms/include/OpenMS/DATASTRUCTURES/StringUtils.h#L63-L63

Imho this should be writtenDigits() - log10(n)

We are having problems with other languages parsing our output since the precision is too high.

**Comment by jpfeuffer** [comment]
See https://www.boost.org/doc/libs/1_72_0/libs/spirit/doc/html/spirit/karma/reference/numeric/real_number.html

which defines precision as the precision of the fractional part only. However, (AFAIU) writtenDigits() gets the number of maximally representable digits (including non-fractional parts).

**Comment by oliveralka** [comment]
This plays a role in the case of LuciPhor2 which does not seem to be able to parse such high precision values (independent of their usefulness):
https://github.com/dfermin/lucXor/issues/6

**Comment by jpfeuffer** [comment]
While I don't think a library should fail reading longer numbers (IEEE765 can represent decimal numbers up to [767](https://www.exploringbinary.com/maximum-number-of-decimal-digits-in-binary-floating-point-numbers/) significant digits), it is true that 17 is enough to uniquely read them back in.
So I vote for limiting the precision to that (although at a little cost of calculating a log10 for every write).

**Comment by jpfeuffer** [comment]
For reference, some experiments: https://godbolt.org/z/aYQgcv

**Comment by cbielow** [comment]
Log is very expensive. This might void the speed advantage why we introduced it in the first place.
This needs benchmarking!

**Comment by jpfeuffer** [comment]
They use log10 already in the source code for generating the fractional part. And the approach does not really work anyway since the library is bugged. It hard-limits precision at 16 fractional digits although you need more to uniquely do a round-trip double-string-double (e.g. for numbers between 0.01 and 0.0001 where scientific notation does not yet kick in).

**Comment by jpfeuffer** [comment]
Also, when not writing useless junk, we are saving several divisions by ten, so it amortizes.
