### ISSUE TITLE
TOPPBase does not check if files in InputFileList exist

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4632]
see
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/APPLICATIONS/TOPPBase.cpp#L1373

it passes an INPUTFILE_LIST but the code only handles INPUT_FILE

**Comment by timosachsenberg** [comment]
@cbielow you probably know that code better than us. Can you have a quick look at those lines? If you agree that this is the case I can provide a simple fix.

**Comment by cbielow** [comment]
yep. looks buggy.
