### ISSUE TITLE
MapAlignerPoseClustering issue

### ISSUE THREAD

**Issue by giangiacomoberetta1** [OpenMS/OpenMS#4638]
Hi !

Time ago, I noticed that for unknown reasons, when using MapAlignerPoseClustering for map alignment, ProteinQuantifier produces identical numbers for proteins across samples.

I thought that the issue would be solved in OpenMS 2.5 version (it was present already in 2.4 and in 2.3 if I well remember), but actually still there is the problem.

Thanks!

G

**Comment by jpfeuffer** [comment]
Is there a minimal reproducible dataset (e.g. filtered data set with two samples) that you could provide?

**Comment by jpfeuffer** [comment]
Or does it maybe happen with the BSA dataset in our examples? In this case, could you elaborate on where you would expect different values?

**Comment by giangiacomoberetta1** [comment]
Data analysis just finished (I run raw data already processed successfully with the same workflow with exclusion of MapAlignerPoseClustering.

Now the situation is different, I dont know why. In spite of the n=4 submitted input files, in the ProteinQuantifier output appears only one column with quantitative data.

Down here come the outputs of nodes in between MapAlignerPoseClustering node (its out option signs correctly n=4 outputs)

**FeatureLinkerUnlabeledQT:**

Linking 4 featureXMLs.
Progress of 'reading input':

  0.00 %               
  25.00 %               
  50.00 %               
  75.00 %               
-- done [took 31.86 s (CPU), 31.85 s (Wall)] -- 
Progress of 'linking features':

  0.00 %               
  27.45 %               
  52.94 %               
  80.39 %               
-- done [took 3.56 s (CPU), 3.55 s (Wall)] -- 
Map descriptions (file name + label) in ConsensusMap are not unique:
  file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label: 
Number of consensus features:
  of size  4:  16462
  total:       16462
FeatureLinkerUnlabeledQT took 42.47 s (wall), 41.66 s (CPU), 1.06 s (system), 40.59 s (user).


**ConsensumMapNormalizer**
Progress of 'loading consensusXML file':
......
-- done [took 6.75 s (CPU), 6.75 s (Wall)] -- 
Map descriptions (file name + label) in ConsensusMap are not unique:
  file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label: 

Using 16462/16462 consensus features for computing normalization coefficients

Progress of 'normalizing maps':

-- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
Progress of 'storing consensusXML file':
....
-- done [took 3.41 s (CPU), 3.41 s (Wall)] -- 
ConsensusMapNormalizer took 12.97 s (wall), 12.16 s (CPU), 0.44 s (system), 11.72 s (user).
<  file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label: > occurred 2 times
<Map descriptions (file name + label) in ConsensusMap are not unique:> occurred 2 times

IDConflictResolver

Map descriptions (file name + label) in ConsensusMap are not unique:
  file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label: 
IDConflictResolver took 11.54 s (wall), 10.72 s (CPU), 0.69 s (system), 10.03 s (user).
<  file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label:   file: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li32012\fs-ZipLo_2-4-32065\000\000\6_3_MapAlignerSpectrum_0\total2.mzML label: > occurred 2 times
<Map descriptions (file name + label) in ConsensusMap are not unique:> occurred 2 times

**Comment by giangiacomoberetta1** [comment]
PS. total2 is the last mzML file in list

**Comment by giangiacomoberetta1** [comment]
After removal of MapAlignerPoseClustering node:

**FeatureLinkerUnlabeledQT:**

Linking 4 featureXMLs.
Progress of 'reading input':

  0.00 %               
  25.00 %               
  50.00 %               
  75.00 %               
-- done [took 53.67 s (CPU), 53.68 s (Wall)] -- 
Progress of 'linking features':

  1.96 %               
  4.90 %               
  5.88 %               
  6.86 %               
-- done [took 02:52 m (CPU), 02:52 m (Wall)] -- 
Number of consensus features:
  of size  4:    904
  of size  3:    855
  of size  2:  13860
  of size  1: 108545
  total:      124164
FeatureLinkerUnlabeledQT took 04:04 m (wall), 04:04 m (CPU), 2.19 s (system), 04:01 m (user).

**ConsensusMapNormalizer:**

Progress of 'loading consensusXML file':
................
-- done [took 15.89 s (CPU), 15.89 s (Wall)] -- 

Using 124164/124164 consensus features for computing normalization coefficients

Progress of 'normalizing maps':

-- done [took 0.02 s (CPU), 0.01 s (Wall)] -- 
Progress of 'storing consensusXML file':
.......
-- done [took 7.69 s (CPU), 7.69 s (Wall)] -- 
ConsensusMapNormalizer took 34.71 s (wall), 33.92 s (CPU), 1.23 s (system), 32.69 s (user).

**IDConflictResolver:**

IDConflictResolver took 25.72 s (wall), 24.91 s (CPU), 1.61 s (system), 23.30 s (user).

**Comment by jpfeuffer** [comment]
Hmm it seems like it picks up the same (last) file 4 times. All the following results "make sense" since the sample names are the same in the file so it assumes they all belong to the same sample. Initially, the four files are different right?
And probably there is a ZipLoopEnd between the FeatureFinder and the MapAlignerPC? Or is there maybe a more complex looping structure?

**Comment by giangiacomoberetta1** [comment]
Yes exactly, files are from different runs and than one loop somewhat like in https://peerj.com/preprints/27766.pdf.

Simplifying: Input Files - ZipLoopStart - FeatureFinderIdentification -ZipLoopEnd - ZipLoopStart - PIA - ZipLoopEnd - MapAlignerPoseClustering

**Comment by giangiacomoberetta1** [comment]
I tried MapAlignerIdentification too, same results, one column only...

mmmm....

**Comment by giangiacomoberetta1** [comment]
Hi !

I found the way (it took a bit of time, but better late than never). More simple than expected. Running MapAlignerPoseClustering in between ZipLoopStart and ZipLoopEnd. By iteration, the filenames are correctly assigned into the features map file so that ProteinQuantifier can report the correct data/results.

**Comment by giangiacomoberetta1** [comment]
w
