### ISSUE TITLE
pyopenms-nightly builds broken

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4650]
Conda installation on win and mac not working anymore.

Also we have to fix the overnight day-change bug for pip.

And unify the contribs installation: on mac it still uses a cached version but probably should download as well.

**Comment by oliveralka** [comment]
> Also we have to fix the overnight day-change bug for pip.
What was that about?

**Comment by oliveralka** [comment]
Ok, so it is split into multiple packages after uploading since part of the packages have been build e.g. late 20200405 and the other half 20200406. 

I will take a look, maybe it is possible to set a fixed date in the GitHub actions.
