### ISSUE TITLE
NovorAdapter: maximum number of MGF spectra exceeded

### ISSUE THREAD

**Issue by giangiacomoberetta1** [OpenMS/OpenMS#4655]
Hi !

While running a search using NovorAdapter, I got the following error message.

The input raw file was converted in centroid mode, so it seems that the problem I related to the  number of spectra that can be written as MGF has exceeded the maximum set value (10.000).

Is it possible to confirm this? In affirmative case, is it possible to increase this upper limit?

Thanks in advance and take care,

GB

ERROR NovorAdapter         0:9        Failing process stdout: [Executable is: D:/KNIME_project/OpenMS-2.4.0/NovorAdapter/novor/lib/novor.jar, Progress of 'loading spectra list':, ,   2.06 %               ,   4.94 %               ,   7.59 %               ,   10.29 %               ,   14.44 %               ,   23.71 %               ,   33.06 %               ,   39.75 %               ,   45.83 %               ,   52.13 %               ,   57.08 %               ,   61.56 %               ,   64.92 %               ,   68.18 %               ,   71.33 %               ,   77.15 %               ,   80.60 %               ,   84.10 %               ,   87.33 %               ,   90.46 %               ,   93.74 %               ,   96.05 %               ,   98.78 %               , -- done [took 10.39 s (CPU), 23.28 s (Wall)] -- , Progress of 'loading chromatogram list':, , -- done [took 0.00 s (CPU), 0.01 s (Wall)] -- , Progress of 'storing mascot generic file':, ,   8.59 %               ,   21.59 %               ,   31.35 %               ,   37.80 %               ,   43.84 %               ,   49.33 %               ,   54.40 %               Error: Unexpected internal error (Spectrum to be written as MGF has 10142 peaks; the upper limit is 10,000. Only centroided data is allowed - this is most likely profile data.)]
ERROR NovorAdapter         0:9        Failing process stderr: []
ERROR NovorAdapter         0:9        Return code: 8
ERROR NovorAdapter         0:9        Execute failed: Failed to execute node NovorAdapter

**Comment by jpfeuffer** [comment]
Hi!

Hmm never realized this limitation. Seems to be related to our MGF writer, so I would assume that we might be able to increase it. Unfortunately it is a hard-coded limit: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/MascotGenericFile.cpp#L319

So it needs to be changed in the code.
You could try to remove 0 or low intensity peaks with ThresholdMower.

**Comment by giangiacomoberetta1** [comment]
Thanks a lot for the suggestion, I am testing it

**Comment by giangiacomoberetta1** [comment]
The first test using the default value 0.05 fixed the problem!

Just need to check the impact on the results and let you know

**Comment by giangiacomoberetta1** [comment]
Now I am experiencing another problem.

In parallel to Novor, I am running SpectraST. After the mzML correction with ThresholdMower, the IDFileConverter connected to SpectraST is now failing.

Is there any action I can take to fix it?


ERROR IDFileConverter      2:45       Failing process stdout: [Progress of 'Loading...':, Error: Unable to read file (While loading 'C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li65908\fs-Spect_2-44-65969\000\000\SpectraSTSearchAdapter_0\R24_IP9_20150520.pepXML': '<' character cannot be used in attribute value 'name'; use &lt; instead( in line 148648 column 33) in: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li65908\fs-Spect_2-44-65969\000\000\SpectraSTSearchAdapter_0\R24_IP9_20150520.pepXML)]
ERROR IDFileConverter      2:45       Failing process stderr: [C:\jenkins\ws\openms_release_packaging\9447518b\source\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(107): While loading 'C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li65908\fs-Spect_2-44-65969\000\000\SpectraSTSearchAdapter_0\R24_IP9_20150520.pepXML': '<' character cannot be used in attribute value 'name'; use &lt; instead( in line 148648 column 33)]
ERROR IDFileConverter      2:45       Return code: 3
ERROR IDFileConverter      2:45       Execute failed: Failed to execute node IDFileConverter

**Comment by giangiacomoberetta1** [comment]
Hi! I don't know how, but the problem is fixed, maybe a system refresh has been enough.

Thanks a lot !

G
