### ISSUE TITLE
Float-Denormal Elimination

### ISSUE THREAD

**Issue by taranehstrunk** [OpenMS/OpenMS#4679]
We tested the influence of float-denormals on OpenMS, using FeatureFinderCentroided to benchmark the performance. 
For locating denormals, you have to access float-execptions, with including` #include <cfenv>` and enable the exception with 
```
std::feclearexcept(FE_ALL_EXCEPT)
feenableexcept(FE_UNDERFLOW)
```
 We tracked denormals that are created e.g. when calling the function `getIntensity()` in `CoarseIsotopePatternGenerator()`. To avoid doing further calculations with a value that is to small, we've inserted an if-statement to check for a certain value.  We could fix the creation of denormals, but unfortunately because of the insertion of an if-statement, we couldn't further improve the runtime, which we checked in a benchmark of those functions we changed (`convolve_()`, `convolveSquare()`).
Additionally, we flushed all denormals to zero in main() of FeatureFinderCentroided.cpp. To do so, include` #include <immintrin.h>` and add `_MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON)` and `_MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON)`. This also didn't improve the runtime of FeatureFinderCentroided. 

Apparently the influence of denormals in the FeatureFinderCentroided is not big enough to improve the performance by eliminating those.

**Comment by cbielow** [comment]
Thanks for documenting this!

Maybe as a small additional motivator: When benchmarking operatations on floating point numbers we found the following penalties (factors!) in Intel CPUs (this is not dependend on OS or compiler):

  | division | multiplication
-- | -- | --
denormal | 46.9 | 39.8953
normal | 1.38 | 1

Thus, denormal floats (all floats below FLT_MIN ~ 1e-38) receive a hard computional penalty when used. Thus, avoiding these floats **could** have led to huge speedups.

btw: AMD CPUs (at least Ryzen and later) do not suffer from this penalty.
