### ISSUE TITLE
pyopenms 2.5.0 MacOS missing on pypi

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4683]
https://pypi.org/project/pyopenms/2.5.0/#files
MacOS.whls currently missing. 

@hroest Could you please upload the stable mac wheels to PyPI, when you have time?  

https://abibuilder.informatik.uni-tuebingen.de/archive/openms/pyopenms/macOS/%24%7BGITHUB_BRANCH_NAME%7D/

**Comment by jonas87** [comment]
There seems to be no version of pyopenms at all for MacOS on Python 3.8? Version 2.4.0 has  wheels for python 3.8 on Linux and Windows but MacOS is missing there as well.

**Comment by jpfeuffer** [comment]
Unfortunately, we are probably not going to fix this for older versions anymore. We will make sure to upload all recent pythons for the upcoming 2.6 however.
And we soon have fully working nightly pyopenms builds for the last three python versions, so this should not happen again.
