### ISSUE TITLE
FeatureFinderMetaboIdent takes up lots of memory loading all chromatograms

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#4687]
Similar issue to #4528 need to figure out a way to handle this under low memory conditions.

**Comment by hendrikweisser** [comment]
I'm working on adapting FeatureFinderIdentification (which has functionality for processing chromatograms in multiple chunks) to RNA data, in case that would help. Testing welcome.

**Comment by poshul** [comment]
I will take a look. Thanks!

**Comment by poshul** [comment]
Closing as stale.
