### ISSUE TITLE
RAII temporary directory class

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#4707]
implement a non-copyable class which creates a new temporary directory (as subdirectory of File::getTempDirectory()) -- see TOPPBase::makeTempDirectory_() for an example.

On destruction of the object, the temp-dir should get deleted. see `TOPPBase::removeTempDirectory_` for an example.

The goal is basically to move the functionality of TOPPBase::makeTempDirectory_() and TOPPBase::removeTempDirectory_ into a separate class and make TOPPBase smaller.

The constructor of the new class should have a bool option to not delete the temp-dir on destruction (for debug purposes).

**Comment by cbielow** [comment]
The new class should go into OpenMS/SYSTEM/File.cpp or be a separate class in that directory

**Comment by oliveralka** [comment]
@cbielow 
Should we mark this as Hacktoberfest task?
I guess this should have a similar structure as the "SiriusTemporaryFileSystemObjects" 
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/ANALYSIS/ID/SiriusAdapterAlgorithm.h#L53 https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/ANALYSIS/ID/SiriusAdapterAlgorithm.cpp#L139

**Comment by cbielow** [comment]
yes! my primary intention was to add a Hacktoberfest issue... which is what I forgot! Thanks for the heads up/

**Comment by Waschi97** [comment]
I'll work on that.
