### ISSUE TITLE
File::basename does not work for windows paths

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4714]
"C:\foo.txt" -> "C:\foo.txt" = wrong

**Comment by timosachsenberg** [comment]
I found this problem too. If Windows path are used on Linux or Mac platforms then the error occurs. A fix is to replace \ by / and then call it

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/MzTab.cpp#L2769

**Comment by ighosh98** [comment]
Can I work on this?

**Comment by timosachsenberg** [comment]
Sure! Hi ahead and assign yourself. Feel free to ask for advice.

**Comment by poshul** [comment]
fixed in https://github.com/OpenMS/OpenMS/pull/4694

**Comment by poshul** [comment]
should be: https://github.com/OpenMS/OpenMS/pull/5316
