### ISSUE TITLE
FeatureFinderMetaboIdent crashes - cause unclear

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#4728]
Tool crashes when negative charges are specified in the input TSV

**Comment by hendrikweisser** [comment]
I'd be very surprised by this because we always used this tool with RNA data with negative charges. I just tried the current build with an old file (with negative charges) and it worked.
I'm pretty sure your problem must be cause by something else.

**Comment by poshul** [comment]
Closing as stale.
