### ISSUE TITLE
export rt_start and rt_end for features

### ISSUE THREAD

**Issue by YasinEl** [OpenMS/OpenMS#4729]
I am trying to add rt_start and rt_end values to my #FEATURE output from [FeatureFinderMetabo -> TextExporter -> Output Folder]. However the values for both variables are always just -1. Everything else seems to work just fine.  

Worth noting: I did NOT set feature:minimal. 

Do I need to set specific parameters to get those variables or is this a bug?

Thank you for your time and efforts!

**Comment by jpfeuffer** [comment]
Hi,

you need to enable the export of convex hulls around the features in FFMetabo:
`report_convex_hulls true`

for this to work. It is disabled by default since the files can get much larger.

**Comment by YasinEl** [comment]
ah sorry missed that. 

Thank you or the quick response!
