### ISSUE TITLE
.vscode in source tree

### ISSUE THREAD

**Issue by Felix-Droop** [OpenMS/OpenMS#4735]
Regarding this commit: https://github.com/OpenMS/OpenMS/commit/a08d97d09725d4e21023eb0ead3a71e3a0aa3db4

It might be necessary to put the `.vscode` folder into the source tree to make gitpod work. I don't know anything about it.

I am working with VSCode locally and it's a little bit annoying. First of all, the config files are not working for my setup/workspace. Then, if I change something, it gets tracked by git. Since I don't want to commit these changes, changing branches for example is harder than it should be.

Maybe there is an easy way for me to work around this that I am missing. Otherwise I hope we can find a solution that works for everyone! The above commit also deleted `.vscode` from the `.gitignore` file. I guess that's not an option.

**Comment by timosachsenberg** [comment]
so it doesn't work at all?

**Comment by jpfeuffer** [comment]
It is in ".gitignore". Feel free to change ho it works for you. You can also write a script that initializes a .vscode folder and put it to .gitpod.yml init step

**Comment by Felix-Droop** [comment]
@jpfeuffer @timosachsenberg My solution would be to just delete the .vscode folder and all files in it from the index. Would that be ok?

**Comment by jpfeuffer** [comment]
Hm no, we really need it for gitpod, otherwise you always need to do dozens of settings after you login.

**Comment by Felix-Droop** [comment]
Okay, thank you and sorry for the inconvenience.
