### ISSUE TITLE
FeatureFindMetabo does not report isotopologues

### ISSUE THREAD

**Issue by YasinEl** [OpenMS/OpenMS#4738]
It appears to me that FeatureFinderMetabo does not report on isotopologues other than the monoisotopic peak. Is there some setting that can be set in order to keep them in subsequently exported peak lists?

Thank you for your time and efforts,
Yasin

**Comment by jpfeuffer** [comment]
There should be a list of intensities, rts and mzs per isotopic mass trace in each feature:
https://github.com/OpenMS/OpenMS/blob/develop/src/tests/topp/FeatureFinderMetabo_1_output.featureXML#L21

If it is not exported in TextExporter via the metavalues parameter, the quickest way to retrieve that is probably a pyOpenMS script.

**Comment by YasinEl** [comment]
Using the metavalues parameter I do get the variables for

> #FEATURE | rt | mz | intensity | charge | width | quality | rt_quality | mz_quality | rt_start | rt_end | FWHM | isotope_distances | label | legal_isotope_pattern | masstrace_centroid_mz | masstrace_centroid_rt | masstrace_intensity | num_of_masstraces

With that basically everything is fine and all columns I need are present. However, the rows reporting on heavy isotopologues are missing. Are they removed during the FeatureFinderMetabo-process or by the TextExporter? Can I prevent that from happening with some of your enabled parameters? I am using OpemMS via Knime. 
Thank you

**Comment by jpfeuffer** [comment]
What do you mean with heavy isotopologues?
I am not sure if I understand your problem but maybe this helps:
If I am not mistaken (I am not the author of the tool), the entries in the columns masstrace_* are lists in the form [monoisotopic, +1, +2, +3, ...]
Unfortunately, you have to split them yourself since they are optional output (you could use a String Manipulation with a Cell Splitter in KNIME)

**Comment by YasinEl** [comment]
M+1, +2 , etc are exactly what I meant thanks. Does that mean the reported rt_start and rt_end is valid/used for all of them since only one value is provided for all mass traces?

**Comment by jpfeuffer** [comment]
In OpenMS a "feature" is the bounding box around all the isotopic mass traces the algorithm assembles. So rt_max, rt_min, mz_max and mz_min define this rectangle.

See this image:
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/Spectrum2DWidget.png

**Comment by YasinEl** [comment]
Hmm at least in my outputs I have often something like:

> intensity | 3.60E+07
> masstrace_intensity | [3.604824109658472e07_ 1.285529456890381e06_   1.461316003483764e05_ 6.218641984457901e05_ 2.376374963029835e07_   4.562703011715674e05_ 1.331862614264136e07]

meaning that the intensity of the feature is the first mass trace_intensity = M0. Or am I reading that wrong?

**Comment by jpfeuffer** [comment]
Ah, good observation, my mistake. The default is to report the monoisotopic intensity. There is a parameter in FFM "report_summed_intensities" which would change that behaviour.

**Comment by YasinEl** [comment]
Ok thank you for the explanations!
