### ISSUE TITLE
Decoys less than target

### ISSUE THREAD

**Issue by srithegreat** [OpenMS/OpenMS#4739]
I have a spectral library which I am using to generate decoys using the OpenSwathDecoyGenerator with reverse option for decoys. I get the error, the number pf decoys are less than 80 % of target and it fails. Can you let me know whats is going wrong?

Regards,
Srikanth

**Comment by grosenberger** [comment]
The decoy generator in ``reverse`` mode often can't generate decoys that are different enough from the targets. Those are then by default removed. You could either use the recommended default settings or set the threshold of decoy / target ratio to a lower value. You can find all parameters by ``OpenSwathDecoyGenerator --helphelp``.

**Comment by hroest** [comment]
just to add to this: having fewer decoys than targets is not a problem in the OpenSwath analysis workflow - our statistical methods will factor this in and produce the correct FDR values.
