### ISSUE TITLE
Error in IDMerger

### ISSUE THREAD

**Issue by infusini** [OpenMS/OpenMS#4741]
Hi all,

I have been attempting to test Epifany and downloaded the example workflows for Knime.

I used the example mzMLs (iPRG2016 data B sample) as suggested from the https://www.openms.de/comp/epifany/ page. After running the CometAdaptor successfully the IDMerger showed the error below:

```
ERROR IDMerger             0:6        Failing process stdout: [Warning: Parameters file version (2.4.0-HEAD-2019-01-29) does not match the version of this tool (2.5.0)., Your current parameters are still valid, but there might be new valid values or even new parameters. Upgrading the INI might be useful., Error: Unexpected internal error (the value 'Cannot convert string to peptide modification. No terminal modification matches to term specificity and origin.' was used but is not valid; .(Gln->pyro-Glu)ETMGPIPPVHPC(Carbamidomethyl)TIM(Oxidation)GIYK)]
ERROR IDMerger             0:6        Failing process stderr: []
ERROR IDMerger             0:6        Return code: 8
ERROR IDMerger             0:6        Execute failed: Failed to execute node IDMerger
```

The error is caused by the variable modification `Gln -> pyroGlu (Q)` that I added to the parameters, removing that specific modification solves the problem, but it would be good to have the ability to select it in the future. 

Thank you,

Giuseppe

**Comment by jpfeuffer** [comment]
Hi! I think I found the error. It has to do with how we pass terminal modifications for specific amino acids.
You can wait for the new nightly version of the KNIME plugin under https://update.knime.org/community-contributions/trunk/

Or in the meantime you could probably use a user-specified comet.param file.

**Comment by infusini** [comment]
Hi, Thank you, I'll wait for the next nightly version of the KNIME plugin but the link posted sent me to a page that shows only this message:
```
Forbidden
You don't have permission to access this resource.
```

Apologies for the duplicated issue, I'm not sure what happened there.

**Comment by jpfeuffer** [comment]
Ah yes, you cannot access it in a browser but you need to specify it in the "Install New Software" dialogue of KNIME (i.e. register it as an additional "Update site")
