### ISSUE TITLE
pyprophet package installation issue

### ISSUE THREAD

**Issue by Clovernana** [OpenMS/OpenMS#4746]
Hi,
Following the instructions in the openswath tutorial,I have installed the Anaconda 3.7 and tried to use Anaconda prompt to install the pyprophet package but failed.
The error are displayed as below.Could you please help me check it out and give me some suggestions?Thanks so much!
![image](https://user-images.githubusercontent.com/50875585/82729849-8e9d8b00-9d2d-11ea-9ea3-5c185b880c2f.png)

**Comment by grosenberger** [comment]
It seems that you are trying to install a legacy PyProphet version, which is not compatible with Python 3. For most applications, we now recommend to use the current version (>2.0), which you can install by ``pip install pyprophet``.

**Comment by Clovernana** [comment]
![image](https://user-images.githubusercontent.com/50875585/84095029-bd577900-aa30-11ea-8c89-b231033dbc2e.png)
I used Anaconda Prompt3  to install the pyprophet with the command"pip install pyprophet"and the error is shown above.I just can't understand about the error.Could you please tell me the detail about the installation.

**Comment by oliveralka** [comment]
Please reopen if there are further questions.
