### ISSUE TITLE
Problem with SpectraST 

### ISSUE THREAD

**Issue by giangiacomoberetta1** [OpenMS/OpenMS#4764]
Hi !

I am experiencing a problem in the set up of SpectraST. The problem is related to its input port 2, for library splib file.

The node recognizes the file as exe file, and this issue is solved by overriding the file extension as splib.

However, the major problem arise when its needed to work on the identification of peptides from more than one species.

The filemerger node (KNIME node, not that from OpenMS nodes list) does not work on splib files with the override option activated, so SpectraST and merged libraries cannot be connected.

I tried to run two SpectraST in parallel, but in this case the IDfileconverters fail, sending the following type of error message:

ERROR IDFileConverter      2:65:45    Failing process stdout: [Progress of 'Loading...':, Error: Unable to read file (While loading 'C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li54828\fs-ZipLo_2-18-54840\000\000\7_0_SpectraSTSearchAdapter_0\20171104_ZL_HELA_K12_2_002_1.pepXML': expected end of tag 'msms_run_summary'( in line 53637 column 3) in: C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li54828\fs-ZipLo_2-18-54840\000\000\7_0_SpectraSTSearchAdapter_0\20171104_ZL_HELA_K12_2_002_1.pepXML)]
ERROR IDFileConverter      2:65:45    Failing process stderr: [C:\jenkins\ws\openms_release_packaging\9447518b\source\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(107): While loading 'C:\Users\Giangiacomo\AppData\Local\Temp\knime_LEONARDO 2_5_Li54828\fs-ZipLo_2-18-54840\000\000\7_0_SpectraSTSearchAdapter_0\20171104_ZL_HELA_K12_2_002_1.pepXML': expected end of tag 'msms_run_summary'( in line 53637 column 3)]
ERROR IDFileConverter      2:65:45    Return code: 3
ERROR IDFileConverter      2:65:45    Execute failed: Failed to execute node IDFileConverter

**Comment by jpfeuffer** [comment]
#4839 fixes the recognition of the extension.
I don't think our FileMerger supports the merging of splib (since we do not really have internal structures for that format), so a forcing will not help. I think you need to loop over the spectral libraries and then merge the resulting idXMLs.
