### ISSUE TITLE
PeptideIndexer needs option to annotate protein description [478]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#478]
Submitted by timosachsenberg on 2012-11-05 10:15:45

Annotation of protein description in idXML files is an important missing feature. Additionally, IDMapper should take protein descriptions over to featureXML.

**Comment by timosachsenberg** [comment]
@lars20070 is this still relevant?

**Comment by lars20070** [comment]
`write_protein_description` in `PeptideIndexer` now allows to include the descriptions in `idXML`.

**Comment by timosachsenberg** [comment]
and it is taken over to feature / consensusXML I guess?
