### ISSUE TITLE
sha in the realease is one, but the binaris are many

### ISSUE THREAD

**Issue by fabianegli** [OpenMS/OpenMS#4782]
There is a sha hash available for OpenMS, but it is only one and there are multiple releases. Would it be possible to provide sha256 hashes for all released software packages?

see: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/2.5.0/

**Comment by jpfeuffer** [comment]
Ah good point. Beware that currently this file is the Git commit SHA that OpenMS was built from.
You probably want file SHA's to avoid tampered files? I can add them.

**Comment by jpfeuffer** [comment]
We have a md5sum_checklist.chk for every release folder now.
