### ISSUE TITLE
Wrong peptide section in mzTab for TMT

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4793]
Column numbers do not match.

Header:
`PEH	sequence	accession	unique	database	database_version	search_engine	best_search_engine_score[1]	modifications	retention_time	retention_time_window	charge	mass_to_charge	spectra_ref	peptide_abundance_study_variable[1]	peptide_abundance_stdev_study_variable[1]	peptide_abundance_std_error_study_variable[1]	peptide_abundance_study_variable[2]	peptide_abundance_stdev_study_variable[2]	peptide_abundance_std_error_study_variable[2]	peptide_abundance_study_variable[3]	peptide_abundance_stdev_study_variable[3]	peptide_abundance_std_error_study_variable[3]	peptide_abundance_study_variable[4]	peptide_abundance_stdev_study_variable[4]	peptide_abundance_std_error_study_variable[4]	peptide_abundance_study_variable[5]	peptide_abundance_stdev_study_variable[5]	peptide_abundance_std_error_study_variable[5]	peptide_abundance_study_variable[6]	peptide_abundance_stdev_study_variable[6]	peptide_abundance_std_error_study_variable[6]	peptide_abundance_study_variable[7]	peptide_abundance_stdev_study_variable[7]	peptide_abundance_std_error_study_variable[7]	peptide_abundance_study_variable[8]	peptide_abundance_stdev_study_variable[8]	peptide_abundance_std_error_study_variable[8]	peptide_abundance_study_variable[9]	peptide_abundance_stdev_study_variable[9]	peptide_abundance_std_error_study_variable[9]	peptide_abundance_study_variable[10]	peptide_abundance_stdev_study_variable[10]	peptide_abundance_std_error_study_variable[10]	peptide_abundance_study_variable[11]	peptide_abundance_stdev_study_variable[11]	peptide_abundance_std_error_study_variable[11]	peptide_abundance_study_variable[12]	peptide_abundance_stdev_study_variable[12]	peptide_abundance_std_error_study_variable[12]	peptide_abundance_study_variable[13]	peptide_abundance_stdev_study_variable[13]	peptide_abundance_std_error_study_variable[13]	peptide_abundance_study_variable[14]	peptide_abundance_stdev_study_variable[14]	peptide_abundance_std_error_study_variable[14]	peptide_abundance_study_variable[15]	peptide_abundance_stdev_study_variable[15]	peptide_abundance_std_error_study_variable[15]	peptide_abundance_study_variable[16]	peptide_abundance_stdev_study_variable[16]	peptide_abundance_std_error_study_variable[16]	peptide_abundance_study_variable[17]	peptide_abundance_stdev_study_variable[17]	peptide_abundance_std_error_study_variable[17]	peptide_abundance_study_variable[18]	peptide_abundance_stdev_study_variable[18]	peptide_abundance_std_error_study_variable[18]	peptide_abundance_study_variable[19]	peptide_abundance_stdev_study_variable[19]	peptide_abundance_std_error_study_variable[19]	peptide_abundance_study_variable[20]	peptide_abundance_stdev_study_variable[20]	peptide_abundance_std_error_study_variable[20]	peptide_abundance_study_variable[21]	peptide_abundance_stdev_study_variable[21]	peptide_abundance_std_error_study_variable[21]	peptide_abundance_study_variable[22]	peptide_abundance_stdev_study_variable[22]	peptide_abundance_std_error_study_variable[22]	peptide_abundance_study_variable[23]	peptide_abundance_stdev_study_variable[23]	peptide_abundance_std_error_study_variable[23]	peptide_abundance_study_variable[24]	peptide_abundance_stdev_study_variable[24]	peptide_abundance_std_error_study_variable[24]	peptide_abundance_study_variable[25]	peptide_abundance_stdev_study_variable[25]	peptide_abundance_std_error_study_variable[25]	peptide_abundance_study_variable[26]	peptide_abundance_stdev_study_variable[26]	peptide_abundance_std_error_study_variable[26]	peptide_abundance_study_variable[27]	peptide_abundance_stdev_study_variable[27]	peptide_abundance_std_error_study_variable[27]	peptide_abundance_study_variable[28]	peptide_abundance_stdev_study_variable[28]	peptide_abundance_std_error_study_variable[28]	peptide_abundance_study_variable[29]	peptide_abundance_stdev_study_variable[29]	peptide_abundance_std_error_study_variable[29]	peptide_abundance_study_variable[30]	peptide_abundance_stdev_study_variable[30]	peptide_abundance_std_error_study_variable[30]	opt_global_feature_id	opt_global_precursor_intensity	opt_global_precursor_purity	opt_global_scan_id	opt_global_AssumedDissociationMethod	opt_global_CTermIonCurrentRatio	opt_global_ExplainedIonCurrentRatio	opt_global_MS2IonCurrent	opt_global_MS:1001491	opt_global_MS:1001492	opt_global_MS:1001493	opt_global_MS:1002049	opt_global_MS:1002050	opt_global_MS:1002052	opt_global_MS:1002053	opt_global_MSGF:Energy	opt_global_MSGF:MeanErrorTop7	opt_global_MSGF:ScoreRatio	opt_global_MSGF:StdevErrorTop7	opt_global_MSGF:lnCTermIonCurrentRatio	opt_global_MSGF:lnEValue	opt_global_MSGF:lnExplainedIonCurrentRatio	opt_global_MSGF:lnMS2IonCurrent	opt_global_MSGF:lnNTermIonCurrentRatio	opt_global_MSGF:sqMeanErrorTop7	opt_global_MeanErrorAll	opt_global_MeanErrorTop7	opt_global_MeanRelErrorAll	opt_global_MeanRelErrorTop7	opt_global_NTermIonCurrentRatio	opt_global_NumMatchedMainIons	opt_global_StdevErrorAll	opt_global_StdevErrorTop7	opt_global_StdevRelErrorAll	opt_global_StdevRelErrorTop7	opt_global_calcMZ	opt_global_end	opt_global_isotope_error	opt_global_pass_threshold	opt_global_protein_references	opt_global_start	opt_global_cv_MS:1002217_decoy_peptide`

"Features" without ID:
`PEP	null	null	null	null	null	null	null	null	null	null	null	1235.920867199999975	null	3	385.9599609375	null	4440.20947265625	null	null	4108.4248046875	null	null	4667.30810546875	null	null	5631.52734375	null	null	4717.31591796875	null	null	5668.90576171875	null	null	4253.14892578125	null	null	3148.69140625	null	null	5740.654296875	null	null	3604.9921875	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	16811589641642245936	6499.96630859375	1.0	controllerType=0 controllerNumber=1 scan=554	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null`

Features with ID:
`PEP	VGSHADAAQER	sp|Q91VJ2|PRDBP_MOUSE	1	null	null	null	0.0251915	0.0251915	null	null	0-UNIMOD:737	1238.816207040000109	null	0	457.239044189453011	ms_run[1]:controllerType=0 controllerNumber=1 scan=558	4533.1962890625	null	null	4439.720703125	null	null	3146.207763671875	null	null	2486.967529296875	null	null	3492.10791015625	null	null	3995.0830078125	null	null	2307.185302734375	null	null	2501.578125	null	null	2515.706787109375	null	null	2877.914794921875	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	15678579650140244579	2.0840484375e04	1.0	controllerType=0 controllerNumber=1 scan=560	CID	0.006075844	0.006231098	364065.25	0.0251915	-0.158713	0.263986	40.0	59.0	5.434193e-07	9.93291	19.0	41.114851999999999	0.677966101694915	29.263998000000001	-5.087109725646035	-2.295853486485435	-5.06228159815281	12.805088388795795	-8.273252252841681	6761.724219927616105	10.278713	10.278713	-9.4017105	-9.4017105	1.5525379E-4	3	7.3159995	7.3159995	8.413301	8.413301	457.238922119140625	98	0	1	unique	88	0`

**Comment by jpfeuffer** [comment]
I counted the number of tabs in the lines. Header = 145, Rows = 148.

**Comment by timosachsenberg** [comment]
hmm do you know by chance which ones are missing in the header?

**Comment by jpfeuffer** [comment]
It is the latest in KNIME. 12.06.2020.

No, I did not see yet, which one is missing.

**Comment by jpfeuffer** [comment]
Since 3 are missing, maybe it is a "one-off" in the study_variables?

**Comment by timosachsenberg** [comment]
can you provide me the input to MzTabExporter... I might want to look into that

**Comment by timosachsenberg** [comment]
Seems to be related to run level search engine scores:
PEH     sequence        accession       unique  database        database_version        search_engine   best_search_engine_score[1]     modifications
PEP     VGSHADAAQER     sp|Q91VJ2|PRDBP_MOUSE   1       null    null    null    0.0251915       0.0251915       null    null    0-UNIMOD:737

**Comment by timosachsenberg** [comment]
fixed in https://github.com/OpenMS/OpenMS/pull/4801
