### ISSUE TITLE
ExperimentalDesign TMT Technical Replicates Error 

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4794]
ExperimentalDesign check for `std::make_tuple(row.fraction_group, row.fraction, row.label);`
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/METADATA/ExperimentalDesign.cpp#L604

Technical replicates (techrepmixture) are currently modelled as mixture + fraction_group in the MSstatsExporter (iso-mode), which should identify technical replicates uniquely.  
`String techrepmixture = String(sampleSection.getFactorValue(sample, mixture)) + "_" + String(openms_fractiongroup);
`
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/MSstatsFile.cpp#L641

To represent multiple technical replicates one would start the fraction group from back form one (only label 126 shown in minimal example below).

Spectra_Filepath | Fraction | Label | Fraction_Group | Sample
-- | -- | -- | -- | --
161117_SILAC_HeLa_UPS1_TMT10_Mixture1_01.mzML | 1 | 1 | 1 | 1
161117_SILAC_HeLa_UPS1_TMT10_Mixture1_02.mzML | 1 | 1 | 2 | 11
161117_SILAC_HeLa_UPS1_TMT10_Mixture1_03.mzML | 1 | 1 | 3 | 21
161117_SILAC_HeLa_UPS1_TMT10_Mixture2_01.mzML | 1 | 1 | 1 | 31
161117_SILAC_HeLa_UPS1_TMT10_Mixture2_02.mzML | 1 | 1 | 2 | 41
161117_SILAC_HeLa_UPS1_TMT10_Mixture2_03.mzML | 1 | 1 | 3 | 51
  |   |   |   |  
  |   |   |   |  
Sample | MSstats_Condition | MSstats_BioReplicate | MSstats_Mixture | LabelName
1 | Norm | Norm | 1 | 126
11 | Norm | Norm | 1 | 126
21 | Norm | Norm | 1 | 126
31 | Norm | Norm | 2 | 126
41 | Norm | Norm | 2 | 126
51 | Norm | Norm | 2 | 126

Should we just check if a "Mixture" exists and use a different check, or am I overlooking something in terms of the design?

**Comment by timosachsenberg** [comment]
hmm I don't know if I get it but a different mixture can't have the same fraction group.

**Comment by jpfeuffer** [comment]
Yes, either this, or require the Techrepmixture column additionally. I think.

**Comment by oliveralka** [comment]
What would be more in line with our current experimental design idea? 
1) check if "mixture" exists in the header (to check if its an isobaric experiment) and allow the example above to match the technical replicates by mixture + fraction group
2) add an additional column, which depicts the Techreplicates (maybe breaks the MSstatsTMT OpenMS import?)

**Comment by oliveralka** [comment]
It can be specified in an increasing manner accross mixtures - so our current approach can be used and no further changes have to be made. 

`Yes, you can specify the TechRepMixture column in an increasing manner across mixtures. It is the same as a repeated manner as long as the TechRepMixture column belonging to the same mixture has different values.`

https://github.com/Vitek-Lab/MSstatsTMT/issues/9
