### ISSUE TITLE
TOPPView: Layers display not updated

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#4812]
In TOPPView, when a file is opened as a "new layer", it should appear in the "Layers" window. Due to a recent regression, this does not happen (immediately) any more. The layer is drawn in the main window, but the "Layers" window is not updated - that is, until I open another file, or minimise and un-minimise the TOPPView window. (There may be other triggers as well.)

Without knowing these workarounds, it is very confusing that the "Layer" entry is missing. This also prevents users from interacting with the layer (disabling it, setting it to active, removing it...).

This occurs with the current development version on Ubuntu 18.04.4.

**Comment by timosachsenberg** [comment]
maybe related to @cbielow changes?

**Comment by cbielow** [comment]
introduced in #4795
