### ISSUE TITLE
failure to execute database search 

### ISSUE THREAD

**Issue by pavel-shliaha** [OpenMS/OpenMS#4817]
I have installed openMS on LINUX KNIME and downloaded the latest proteomics_LFQ workflow. 

https://github.com/OpenMS/Tutorials/tree/master/Workflows

The modification I made is insert DecoyDatabase node. Both search engines in them fail. The console log is:

WARN  Input File           0:146      File does not exist.
WARN  FontStore                       Using the system default font for annotations: Font {140719039767808}
ERROR OMSSAAdapter         0:180:98   Failing process stdout: [Warning: Parameters file version (2.3.0) does not match the version of this tool (2.5.0)., Your current parameters are still valid, but there might be new valid values or even new parameters. Upgrading the INI might be useful., OMSSAAdapter took 0.07 s (wall), 0.00 s (CPU), 0.00 s (system), 0.00 s (user).]
ERROR OMSSAAdapter         0:180:98   Failing process stderr: [Input database '/tmp/knime_Proteomics_LFQ21238/fs-Decoy_0-181-21239/000/000/DecoyDatabase_0/Human_rev_can_uniprot_24_09_15.fasta.psq' not found (the file '/tmp/knime_Proteomics_LFQ21238/fs-Decoy_0-181-21239/000/000/DecoyDatabase_0/Human_rev_can_uniprot_24_09_15.fasta.psq' could not be found). Make sure it exists (and check 'OpenMS.ini:id_db_dir' if you used relative paths. Aborting!, Unable to find database '/tmp/knime_Proteomics_LFQ21238/fs-Decoy_0-181-21239/000/000/DecoyDatabase_0/Human_rev_can_uniprot_24_09_15.fasta.psq' (searched all folders). Did you mistype its name?]
ERROR OMSSAAdapter         0:180:98   Return code: 6
ERROR OMSSAAdapter         0:180:98   Execute failed: Failed to execute node OMSSAAdapter
ERROR XTandemAdapter       0:180:96   Failing process stdout: [Warning: Parameters file version (2.3.0) does not match the version of this tool (2.5.0)., Your current parameters are still valid, but there might be new valid values or even new parameters. Upgrading the INI might be useful., Progress of 'loading spectra list':, ,   5.53 %               ,   10.84 %               ,   16.08 %               ,   19.41 %               ,   22.64 %               ,   25.81 %               ,   28.90 %               ,   31.88 %               ,   34.54 %               ,   37.28 %               ,   39.77 %               ,   42.33 %               ,   44.77 %               ,   47.41 %               ,   50.15 %               ,   52.82 %               ,   55.51 %               ,   58.58 %               ,   61.74 %               ,   64.83 %               ,   68.32 %               ,   72.05 %               ,   76.08 %               ,   80.39 %               ,   84.38 %               ,   87.41 %               ,   91.12 %               ,   94.17 %               ,   94.33 %               ,   96.12 %               ,   97.87 %               , -- done [took 30.04 s (CPU), 31.07 s (Wall)] -- , Progress of 'loading chromatogram list':, , -- done [took 0.00 s (CPU), 0.00 s (Wall)] -- , Executing: /media/pavel_shliaha/storage/knime_4.2.0/plugins/de.openms.linux.x86_64_2.5.0.202002201806/payload/bin/XTandem/tandem.exe, FATAL ERROR: External invocation of /media/pavel_shliaha/storage/knime_4.2.0/plugins/de.openms.linux.x86_64_2.5.0.202002201806/payload/bin/XTandem/tandem.exe failed. Standard output and error were:, Standard output: , X! TANDEM Vengeance (2015.12.15.2), , Loading spectra (mzML)., Fatal error: unsupported CODEC used for mzML peak data (CODEC type=zlib compression)., , Standard error: , Exit code: 246, XTandemAdapter took 31.83 s (wall), 30.53 s (CPU), 0.93 s (system), 29.60 s (user).]
ERROR XTandemAdapter       0:180:96   Failing process stderr: []
ERROR XTandemAdapter       0:180:96   Return code: 9
ERROR XTandemAdapter       0:180:96   Execute failed: Failed to execute node XTandemAdapter

**Comment by jpfeuffer** [comment]
Hi Pavel,

Sorry, I thought I answered on the mailing list.

OMSSA needs an index of the database created with NCBI’s makeblastdb tool. See the documentation here: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/TOPP_OMSSAAdapter.html

XTandem does not seem to handle zlib compressed mzML files (I am a bit surprised as well). Either uncheck zlib compression during conversion (with msconvert?) or run our FileFilter without any filtering options but with 
`-peak_options:zlib_compression`
set to false.

HTH
Julianus

**Comment by pavel-shliaha** [comment]
I can see OMSSA support has been discontinued, so I think that I will just stick wit XTandem and mgf+ then. I will check your suggestions and report back

**Comment by pavel-shliaha** [comment]
mgf+ works for identifications
