### ISSUE TITLE
ID mapper failure in LFQ method

### ISSUE THREAD

**Issue by pavel-shliaha** [OpenMS/OpenMS#4819]
I am running openMS  2.5.0 installed through KNIME. I am attempting to run an LFQ pipeline with MGFPlusAdapter as search engine and FeatureFinderCentroided to detect features. I am getting the following error from the IDMapper node. 

ERROR IDMapper             0:226      Failing process stdout: [Warning: Parameters file version (2.4.0-nightly-2019-04-21) does not match the version of this tool (2.5.0)., Your current parameters are still valid, but there might be new valid values or even new parameters. Upgrading the INI might be useful., Unassigned peptides: 14909, Peptides assigned to exactly one feature: 22821, Peptides assigned to multiple features: 24, Unassigned and unidentified precursors: 0, Unidentified precursor assigned to exactly one feature: 0, Unidentified precursor assigned to multiple features: 0, Feature annotation with identifications:,     no ID: 47218,     single ID: 19751,     multiple IDs (identical): 1409,     multiple IDs (divergent): 103, , , Error: Unable to write file (the file '/tmp/knime_Identification_36954/fs-ZipLo_0-5-36958/000/000/20_0_IDMapper_0/HLB_01_185min_5to27_600nl_min_01.consensusXML' could not be created; invalid file extension, expected 'featureXML')]
ERROR IDMapper             0:226      Failing process stderr: []
ERROR IDMapper             0:226      Return code: 5
ERROR IDMapper             0:226      Execute failed: Failed to execute node IDMapper

**Comment by jpfeuffer** [comment]
Hi,

you probably just have to change the output file type in the "Output Types" tab of the Configuration dialog of the IDMapper
to featureXML.

**Comment by pavel-shliaha** [comment]
you are right. Thanks!
