### ISSUE TITLE
Variable Modification "Met-loss (Protein N-term M)" yields error in CometAdapter

### ISSUE THREAD

**Issue by Waschi97** [OpenMS/OpenMS#4830]
This error is thrown:
```
Error: Unexpected internal error (the value 'Met-loss (Protein N-term M)' was used but is not valid; Retrieving the modification failed. It is not available for the residue '' and term specificity 'N-term'. )
Error occurred in line 265 of file C:\Development\OpenMS\src\openms\source\CHEMISTRY\ModificationsDB.cpp (in function: const class OpenMS::ResidueModification *__cdecl OpenMS::ModificationsDB::getModification(const class OpenMS::String &,const class OpenMS::String &,enum OpenMS::ResidueModification::TermSpecificity) const) !
```

This modification is supported by Comet as the 'clip_nterm_methionine' parameter in its param file and can also be passed to CometAdapter as a flag.
Maybe CometAdapter should check for this modification in the 'variable_modifications' parameter and set 'clip_nterm_methionine' accordingly instead of writting the modification.

**Comment by jpfeuffer** [comment]
Additionally, it seems like it already fails during the lookup of the modification.

**Comment by jpfeuffer** [comment]
We have to decide what we allow:
1) M(Met-loss)PEPTIDER
2) PEPTIDER
3) both

Currently, in PeptideIndexer we harcode XTandem as a search-engine that automatically includes that modification. Maybe we should not look up the search engine, but the search params to see if that modification is present to set the corresponding parameters in PeptideIndexer.

**Comment by jpfeuffer** [comment]
Actually @Waschi97 I cannot reproduce this error. Can you please double-check?

**Comment by jpfeuffer** [comment]
Another problem that I see when using the actual modification:
`<aminoacid_modification aminoacid="M" massdiff="-131.040000" mass="0.000485" variable="Y" symbol="@"/>`
The actual resulting mass of the amino acid will not be exactly "0" in pepXML. Not sure how much trouble that will be.

**Comment by jpfeuffer** [comment]
The problem with choosing one of the approaches is that they actually will have different outcomes. The parameter allows all terminal modifications to be searched at the cleaved terminus as well, while the mod will only allow one.

**Comment by jpfeuffer** [comment]
I think we should support both. We are investigating the initial problem now (which I cannot yet reproduce).
Then I will wait for a PR with extended search engine settings from @Waschi97 and we can parse the parameter in PeptideIndexer if set.

**Comment by jpfeuffer** [comment]
Unconformable. See #4870
