### ISSUE TITLE
OMSSAAdapter writes incomplete idXML

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#4834]
all `<PeptideIdentification>` nodes are missing the `spectrum_reference="controllerType=0 controllerNumber=1 scan=11608"` attribute

all `</ProteinIdentification>` nodes are missing the`<UserParam type="stringList" name="spectra_data" value="[....]"/>`
		

Thus, downstream tools such as `QualityControl` will fail

**Comment by jpfeuffer** [comment]
I assume it is fixed with the PR. Please reopen if not.

**Comment by cbielow** [comment]
confirmed fixed.
