### ISSUE TITLE
mzTabExporter cannot deal with custom modifications

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#4835]
When generating a cXML with custom mods, currently (at least two) issue prevent the exporter to write an mzTab:

1)
```
const class OpenMS::ResidueModification *__cdecl OpenMS::ModificationsDB::searchModificationsFast(const class OpenMS::String &,bool &,const class OpenMS::String &,enum OpenMS::ResidueModification::TermSpecificity) constModification not found: C+58.018500
Error: Unexpected internal error (the value 'C+58.018500' was used but is not valid; Retrieving the modification failed. It is not available for the residue '' and term specificity 'none'. )
```

occurs because it tries to find a modification `C+58.018500` as obtained from `      <FixedModification name="C+58.018500" />`
which does not exist...
Error is raised here: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/MzTab.cpp#L1497

2)
After (hackily) deleting the line from the input, one gets yet another error:

```
Error: Unexpected internal error (Modification or Substitution identifier MUST NOT be null or empty in MzTabModification)

```

since the modification obviously also appears in PepIDs as custom mod, e.g. `<PeptideHit score="0.039528211667198" sequence="GC[161.027684999999991]TPEPTID" ...`.

I cannot really track what the actual problem is though...

[error.zip](https://github.com/OpenMS/OpenMS/files/5012508/error.zip)

Exemplary consensusXML attached (note: heavily reduced in size to reproduce the bug -- maybe some other downstream things do not work with this consensusXML...); the error should be easy to reproduce though using any other cxml by adding a custom mod anywhere.

**Comment by jpfeuffer** [comment]
Regarding 1) Not sure if this is an mztab problem. I think we nowhere handle unknown modifications in the SearchParams object. I assume most if not all pieces of code will call getModification like in your first code snippet and fail. I think getModification needs to be adapted to parse these kinds of strings and add the missing mod to the DB if not present yet.
Regarding 2) the main problem is that mztab usually expects a unimod identifier for a mod which we were enforcing. It needs to be discussed how to handle that.

**Comment by jpfeuffer** [comment]
@cbielow By the way, where did you get these unknown Modifications from? Comet with own params file?

**Comment by cbielow** [comment]
> @cbielow By the way, where did you get these unknown Modifications from? Comet with own params file?
> Because if those mods are in unimod, you should properly look them up during pepXML parsing if possible.

Something along those lines yes: I fixed CometAdapter to support multiple mods per AA. And then you get user defined mods back...

**Comment by jpfeuffer** [comment]
This is solved for the mzTabExporter in general. For parsing such idXML files, please open another ticket if not already present (as it is much more of a general problem)
