### ISSUE TITLE
MSFraggerAdapter tests fail

### ISSUE THREAD

**Issue by Waschi97** [OpenMS/OpenMS#4886]
When running the MSFraggerAdapter tests this error is thrown:

`Error: Unexpected internal error (the element 'No accession  test2_rev ##1 found in run 'X! Tandem_2020-08-14_16:44:55' for PSM DFASSGGYVLHLHR_3. Please contact the maintainer of this tool e.g. on GitHub as this should not happen.' could not be found)`

**Comment by jpfeuffer** [comment]
Fixed in https://github.com/OpenMS/OpenMS/pull/4874

Reason was untrimmed (whitespaces) protein identifiers in pepXML. We trim them during parsing now, such that they can be mapped correctly.
