### ISSUE TITLE
pyopenms anaconda installation: python version compatibility

### ISSUE THREAD

**Issue by sibiyes** [OpenMS/OpenMS#4891]
Hello

I am trying to install the pyopenms package from conda library (https://anaconda.org/bioconda/pyopenms). But it looks like there is some sort of compatibility issue with the python version that conda is running. I currently have python 3.7.6 running on my instance and the package installation raises compatibility error as shown below

-----------------------------------------------------------------

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyopenms -> python[version='>=3.5,<3.6.0a0|>=3.8,<3.9.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

(base) [a-vvj3281@KRFT.Net@mznaplaprdq003 ~]$ UnsatisfiableError: The following specifications were found
  - pyopenms -> python[version='>=3.5,<3.6.0a0|>=3.8,<3.9.0a0']

Your python: python=3.7

------------------------------------------------------------------

Please advise

Thanks !

**Comment by jpfeuffer** [comment]
Hi,

this seems odd. Bioconda builds pyopenms for python 2.7, 3.6 and 3.7 (as you can see in the file suffices here: https://anaconda.org/bioconda/pyopenms/files)

Maybe it is better to create a fresh conda environment with all the requirements that you need.
```bash
conda create -n mypyoms python=3.6
conda activate mypyoms
conda config --env --add channels bioconda
conda config --env --add channels conda-forge
conda install pyopenms
```

**Comment by sibiyes** [comment]
creating a separate conda environment worked. 

Thanks !
