### ISSUE TITLE
Problem about convert the raw format to mzXML

### ISSUE THREAD

**Issue by sjtuyf** [OpenMS/OpenMS#4899]
Hi, thank you so much for the great tool developed by you. I want to use the tool for convert the data format. The software i installed is OpenMS Version: 2.5.0 by conda. The command I run is as below, but got the error information:

 FileConverter -in 121204_V2_P6_CH_SM_Chimney_3a_1.raw -in_type raw -out 121204_V2_P6_CH_SM_Chimney_3a_1.mzXML -out_type mzXML -force_MaxQuant_compatibility 
Error: Unexpected internal error (Only conversion to mzML supported at this point.)

I read the manual carefully, and think the parameter is no problem. So how to trackle this problem? 
Because I want to convert the raw format to mzXML, and converted mzXML file can be used  for Maxquant next. So this step is important for me. And I really need your help. Thanks again.

Best regards
Yafei

**Comment by timosachsenberg** [comment]
We internally use ThermoRawFileConverter which afaik only supports mzML.
So you might need to convert to mzML first and then to mzXML using the max quant compatibility option in FileConverter

**Comment by cbielow** [comment]
I guess .raw can only be converted to mzml at this point...even though this restriction could be worked around internally.. @timosachsenberg ?

Solution for now: call Fileconverter twice. Raw to mzML and then mzML to MZML with Maxquant options

**Comment by sjtuyf** [comment]
> We internally use ThermoRawFileConverter which afaik only supports mzML.
> So you might need to convert to mzML first and then to mzXML using the max quant compatibility option in FileConverter

Hi, 
     Thanks for your quick reply. 
     I tried to convert to the mzML, but got error. it notice some path are not found, so i change the command, but got other error ,such as lack of mono.

 The commands I tried are:
$ FileConverter -in 121204_V2_P6_CH_SM_Chimney_3a_1.raw -in_type raw -out 121204_V2_P6_CH_SM_Chimney_3a_1.mzML -out_type mzML 
RawFileReader reading tool. Copyright 2016 by Thermo Fisher Scientific, Inc. All rights reserved
Input file 'ThermoRawFileParser.exe' could not be found (by searching on PATH). Either provide a full filepath or fix your PATH environment! Since this file is not strictly required, you might also pass the empty string "" as argument to prevent it's usage (this might limit the usability of the tool).
Error: File not found (the file 'ThermoRawFileParser.exe' could not be found)

$ FileConverter -in 121204_V2_P6_CH_SM_Chimney_3a_1.raw -in_type raw -out 121204_V2_P6_CH_SM_Chimney_3a_1.mzML -out_type mzML -ThermoRaw_executable ''
RawFileReader reading tool. Copyright 2016 by Thermo Fisher Scientific, Inc. All rights reserved
Executing: mono
Process 'mono' failed to start. Does it exist? Is it executable?
FileConverter took 0.00 s (wall), 0.00 s (CPU), 0.00 s (system), 0.00 s (user).
    
    So i don not know which is the complete command to run the command? Could you shown me a complete example to convert the raw format to mzML, and convert the mzML to mzxML？Because I search the similar problem online, but only got few information.

   By the way, I install the OpenMS Version: 2.5.0 by conda in the linuk, the command is 'conda install -c bioconda openms', and it installed successfully with no error, so do i need to install other tools to complete the data format conversation ?

   I hope to got your instruction and reply if you are free, and thanks again.


Best
Yafei

**Comment by timosachsenberg** [comment]
If you use conda you need to install either ThermoRawFileParser or the OpenMS thirdparty package
https://anaconda.org/bioconda/openms-thirdparty

**Comment by sjtuyf** [comment]
> If you use conda you need to install either ThermoRawFileParser or the OpenMS thirdparty package
> https://anaconda.org/bioconda/openms-thirdparty

ok, i will install  the OpenMS thirdparty package, and try again.
Thanks.

Yafei

**Comment by jpfeuffer** [comment]
Unfortunately, you also might need to adapt your Path or pass the path to the ThermoRawFileParser.exe to the FileConverter.
Conda only includes a wrapper script in the Path.

**Comment by sjtuyf** [comment]
> Unfortunately, you also might need to adapt your Path or pass the path to the ThermoRawFileParser.exe to the FileConverter.
> Conda only includes a wrapper script in the Path, not the exe.

Thanks for your reply. I have installed the OpenMS thirdparty package as timosachsenberg told. And it converted successfully.

**Comment by sjtuyf** [comment]
Hi,
    The method of convert raw to mzXML is great. Thanks again.
    Another question is i want to pull out a subset of data from an mzXML file to run using maxquant (for instance, to re-run any non matching spectra against another protein database). I tried to filter some spectra by the scan number that identified using my script, and the remainning spectra in the mzXML are used for maxquant. However, the reduced mzXML file could not run in the maxquant regularly, the error information notice the data format. So are there other tools in the OpenMS to get a subset of data from an mzXML file, and the subset can also be used for maxquant?  
    This is the error information caused by maxquant:

id    0
start    28/08/2020 15:56:01
title    Testing_raw_files (1/1)
description    D:\project\project_2020\em_2020_reanalysis\maxquant\openms_data\fir\121204_V2_P6_CH_SM_Chimney_3a_1_filtered.mzXML
error    D:\project\project_2020\em_2020_reanalysis\maxquant\openms_data\fir\121204_V2_P6_CH_SM_Chimney_3a_1_filtered.mzXML_System.Exception: The file 'D:\project\project_2020\em_2020_reanalysis\maxquant\openms_data\fir\121204_V2_P6_CH_SM_Chimney_3a_1_filtered.mzXML' appears to be corrupt. Try to open it with vendor software. ---> System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PluginRawMzXml.MzXml.GetIndexData()
   在 PluginRawMzXml.MzXml..ctor(String filename)
   在 PluginRawMzXml.MzXmlRawFile.PreInit()
   在 BaseLibS.Ms.RawFile.InitFromRawFile()
   在 BaseLibS.Ms.RawFile.Init(String path1)
   在 MsLib.Raw.RawFileUtil.CreateRawFile(String path)
   在 MaxQuantPLibS.Basic.MaxQuantTasks.TestFile1(String rawFilePath)
   在 MaxQuantPLibS.Basic.MaxQuantTasks.TestFile(Int32 taskIndex, String mqparFile)
   --- 内部异常堆栈跟踪的结尾 ---_   在 MaxQuantPLibS.Basic.MaxQuantTasks.TestFile(Int32 taskIndex, String mqparFile)__   在 MaxQuantPLibS.Work.RawFileTester.Calculation(String[] args)__   在 MaxQuantPLibS.Work.MaxQuantWorkDispatcherUtil.PerformTask(Int32 taskType, String[] args)__   在 MaxQuantTask.Program.Function(String[] args)__   在 Utils.Util.ExternalProcess.Run(String[] args, Boolean debug)
end    28/08/2020 15:56:01
    
     I also upload three files, one is unfiltered "121204_V2_P6_CH_SM_Chimney_3a_1.mzXML.gz",which is format-corrrect. One is the scan number I want to remove. And the third is filtered "121204_V2_P6_CH_SM_Chimney_3a_1_filtered.mzXML.gz",which is filtered by myself, but caused the error in the maxquant. 
Because the files are too big to upload, so i email you at the same time. I hope you could understand this. Could you help me to check those files if you have tools to finish this step? or have some tools to recommend?
     
     I hope to got your instruction  if you are free, and thanks again.

Best
Yafei

**Comment by timosachsenberg** [comment]
Hi Yafei,
in OpenMS you can use
FileFilter with the Option
-id:blacklist <file>                                         Input file containing MS2 identifications whos
                                                               e corresponding MS2 spectra should be removed
                                                               from the mzML file!
                                                               Matching tolerances are taken from 'id:rt' an
                                                               d 'id:mz' options.
                                                               This tool will require all IDs to be matched
                                                               to an MS2 spectrum, and quit with error otherw
                                                               ise. Use 'id:blacklist_imperfect' to allow
                                                               for mismatches. (valid formats: 'idXML')

but I don't know if the MaxQuant then reads the XML files.

Do you need to rely on MaxQuant for that task? Because you could achieve these things rather easily relying on the supported search engines in OpenMS and OpenMS tools

**Comment by sjtuyf** [comment]
> Hi Yafei,
> in OpenMS you can use
> FileFilter with the Option
> -id:blacklist Input file containing MS2 identifications whos
> e corresponding MS2 spectra should be removed
> from the mzML file!
> Matching tolerances are taken from 'id:rt' an
> d 'id:mz' options.
> This tool will require all IDs to be matched
> to an MS2 spectrum, and quit with error otherw
> ise. Use 'id:blacklist_imperfect' to allow
> for mismatches. (valid formats: 'idXML')
> 
> but I don't know if the MaxQuant then reads the XML files.
> 
> Do you need to rely on MaxQuant for that task? Because you could achieve these things rather easily relying on the supported search engines in OpenMS and OpenMS tools

Hi, 
     Thanks for your reply.
     I will try the method you told later. For my project, i need to use maxquant to identify proteins. And i also need to perform the two-stage search. My plan is searching against one database firstly, and use the remaining spectra to search using maxquant. So that is the reason why i choose to do the data conversation and spectra filtered. 
    For my purpose, do you have other good suggestions?
    Thanks in advance.

Best
Yafei

**Comment by cbielow** [comment]
Hi Yafei,

depending on how you removed the spectrum from the file, you might have invalidated the `index` at the very end (which stores byte-offsets into the file; and those will obviously change if you remove/insert spectra anywhere in the file).
Using our FileFilter is a better choice, since it will keep the index intact (you have to run FileConverter afterwards again to get mzXML with the index).
If that still does not work, it might very well be that MaxQuant cannot deal with missing spectra (they are numbered). One could dig into this, because their parsing code is online somewhere, but I'm not sure its worth the trouble.
Another option is to do a search with a combined FASTA file and only use the evidence.txt to build the protein groups on your own. The protein grouping step of MaxQuant is rather crude (compared to other methods), so you should be able to reproduce it, but giving it only partial evidence (removing PSMs which were matched against the first part of the combined DB).

**Comment by sjtuyf** [comment]
> Hi Yafei,
> 
> depending on how you removed the spectrum from the file, you might have invalidated the `index` at the very end (which stores byte-offsets into the file; and those will obviously change if you remove/insert spectra anywhere in the file).
> Using our FileFilter is a better choice, since it will keep the index intact (you have to run FileConverter afterwards again to get mzXML with the index).
> If that still does not work, it might very well be that MaxQuant cannot deal with missing spectra (they are numbered). One could dig into this, because their parsing code is online somewhere, but I'm not sure its worth the trouble.
> Another option is to do a search with a combined FASTA file and only use the evidence.txt to build the protein groups on your own. The protein grouping step of MaxQuant is rather crude (compared to other methods), so you should be able to reproduce it, but giving it only partial evidence (removing PSMs which were matched against the first part of the combined DB).

Hi,  
     Thank you very much for your kindly reply and good suggestions. I will try them later.

Best regards
Yafei
