### ISSUE TITLE
IdentificationDataInternal classes need default and copy constructors for wrapping in PyOpenms

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#4904]
Even if we are not exposing constructors to Cython, the code generation requires them to exist. So far all of my modifications have been limited to my wrapper class, but adding constructors requires changes to some of the ID code. I am opening this issue to discuss.

**Comment by timosachsenberg** [comment]
I was aware of the copy constructors but what about the nullary? Can you elaborate?

**Comment by poshul** [comment]
> Cython initializes C++ class attributes of a cdef class using the nullary constructor. If the class you’re wrapping does not have a nullary constructor, you must store a pointer to the wrapped class and manually allocate and deallocate it. A convenient and safe place to do so is in the __cinit__ and __dealloc__ methods which are guaranteed to be called exactly once upon creation and deletion of the Python instance.
From https://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html

Autowrap will wrap them happily without the constructor, but the actual code generation fails.

**Comment by hendrikweisser** [comment]
Copy c'tors makes sense, but many ID classes don't have nullary c'tors for a good reason - you're not supposed to create an instance with missing data (e.g. peptide without sequence, protein without accession, PSM without P or S).
How about the pointer alternative described in the Cython docs?

**Comment by jpfeuffer** [comment]
Doesn't autowrap try to do the alternative route anyway? `you must store a pointer to the wrapped class and manually allocate and deallocate it.`

Here: https://github.com/autowrap/autowrap/blob/79d916f86d5eeb47a10d1ab3cfb039e53e5c5c58/autowrap/CodeGenerator.py#L934

**Comment by poshul** [comment]
@jpfeuffer I would think so but this is the output I get when DataProcessingStep has no default constructor:
`pyopenms/pyopenms_7.cpp: In function ‘PyObject* __pyx_pf_8pyopenms_10pyopenms_7_25IdentificationDataWrapper_38pythonNewDataProcessingStep(__pyx_obj_8pyopenms_10pyopenms_7_IdentificationDataWrapper*, PyObject*, PyObject*, PyObject*, __pyx_obj_8pyopenms_10pyopenms_5_DateTime*, PyObject*)’:
pyopenms/pyopenms_7.cpp:88239:58: error: no matching function for call to ‘OpenMS::IdentificationDataInternal::DataProcessingStep::DataProcessingStep()’
   OpenMS::IdentificationDataInternal::DataProcessingStep __pyx_t_15;
                                                          ^~~~~~~~~~`

I haven't tried the manual alternative that Hendrik mentions above. I am about to do that and see if it is kosher for Autowrap to handle.

**Comment by hendrikweisser** [comment]
I think it's worth checking with @hroest:
- Are any non-default-constructible OpenMS classes handled by Autowrap already? If so, how?
- Is the whole "store a pointer to the wrapped class and manually allocate and deallocate it" something that could be done automatically by Autowrap, based on some annotation in the pxd file?

**Comment by poshul** [comment]
The issue in the C++ side of the python code seems to be __init__ calling the default constructor. I see that for a couple of *DB classes (ResideDB, RibonucleotideDB, etc.) we have pyx files that manually declare the __init__ functions. This seems to be done for singleton classes mainly, can any of y'all speak to how those were written?

**Comment by poshul** [comment]
I resolved this with Hendrik at the retreat.

**Comment by timosachsenberg** [comment]
can you comment on the resolution?

**Comment by poshul** [comment]
It was agreed that A) Its necessary to add these for wrapping, and B) its
ugly and should be clearly documented so they are not used in other C++
code.

**Comment by timosachsenberg** [comment]
ok so it is necessary to add them to the c++ code (e.g., we couldn't annotate is somehow in the pxd and let autowrap generate it?)

**Comment by jpfeuffer** [comment]
No autowrap can of course not add to the cpp code.
The only thing you can do is to implement an annotation that tells you that something does not have a copy constructor. But then you need to figure out how you wrap return statements of this class without doing copies.
