### ISSUE TITLE
How to pull precursor m/z and charge for MS/MS spectra? .getPrecursors() 

### ISSUE THREAD

**Issue by alhigaylan** [OpenMS/OpenMS#4906]
Hello, 

 I'm a beginner user in Python and openMS package. I'm trying to extract the precursor ion m/z and charge for a specific ms/ms spectrum. I'm hoping I can up-scale this code to extract precursor ion of thousands of ms/ms for down-stream analysis. But the primary issue I'm facing right now is how to extract that info for one spectrum? Here is what I have tried so far:

`# First, import my raw data in mzML format`
`from pyopenms import *`
`exp = MSExperiment()`
`MzMLFile().load("/Users/Desktop/file.mzML", exp)`

`# check if the spectrum is MS/MS `
`exp[5].getMSLevel()`

`Out[104]: 2`

`# Attempt to extract precursor m/z and charge`
`exp[5].getPrecursors()`
`Out[105]: [<pyopenms.pyopenms_3.Precursor at 0x12b00c0f0>]`

 I don't understand why I'm not getting numbers from this code? .getMSLevel(), get_peaks() and others report numbers or numpy arrays I can play with. What am I missing with the getPrecursors() command? Thank you for your help!!

**Comment by jpfeuffer** [comment]
Hi!
The difference is that getPrecursor**s**() will return a list of objects (implied with the square brackets of the string representation []).
But even if you select the first object with exp[5].getPrecursors()[0] you will only get a memory address of the object.
You still need to query a specific member of the object that can be nicely displayed.
E.g. `exp[5].getPrecursors()[0].getMZ()` or `exp[5].getPrecursors()[0].getCharge()`

The member functions that you can call for a precursor can be found here: https://github.com/OpenMS/OpenMS/blob/d17cc251fd0c4068eb253b03c9fb107897771fdc/src/openms/source/METADATA/Precursor.cpp

**Comment by alhigaylan** [comment]
@jpfeuffer Thank you!!!! This worked really well and I was able to confirm the numbers I'm getting with my readable mgf file! @timosachsenberg thank you for stopping by! Another thing that the pyopenMS tutorials show is how to built your own extracted ion chromatogram (XIC). But what if I want to get the XIC of a specific precursor ion? 
 If I use:
`exp[5].getPrecursors()[0].getMZ()`
`Out[19]: 698.591113269329`

 How to use that output to filter the LC chromatogram plot and only show the profile of my ion of interest?
