### ISSUE TITLE
DecoyDatabase should detect already decoy'd DBs

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#4917]
our example FASTA files in `share` sometimes contain outdated Decoy symbols (e.g. `_rev` as suffix).
If one is not careful, this can lead to subtle errors which are a bit tricky to find when a downstream tool crashes.

At least our DecoyDatabase tool should check if its consuming a decoy'ed DB (the above example is currently happily reversed **again**).

This is already mentioned in  #4662, but I think its very important to fix and to prevent accidental errors with high potential for frustration.

**Comment by timosachsenberg** [comment]
there is some code in PeptideIndexer I think that recognizes decoy preifx/suffix.
Might be possible to reuse that code.

**Comment by Leon-Bichmann** [comment]
I can try to take a look at this
