### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by ozgurdemir** [OpenMS/OpenMS#4920]
First of all thx for this great library. However, I think the documentation could be much better. There are great quick start guides for openms and pyopenms showing the basic usage. That said when diving deeper I'd like to know how specific algorithms work. In the [api](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/modules.html) most algorithms and data structures are almost not documented at all. For an open source library I'd expect a short description of how the algorithm works (whenever it makes sense using images) and what their input parameters mean. Together with some examples of input data and results. Without good documentation users will struggle using any library even the best one ;)

As an example it's really hard to understand what the differences between the multiple alignment algorithms are and what their input arguments mean. Another example is the [InternalCalibration](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1InternalCalibration.html#details).

**Comment by timosachsenberg** [comment]
Dear @ozgurdemir we totally agree that documentation can be improved.

In this particular case it is a good idea to look into:
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/TOPP_InternalCalibration.html
The documentation for the command-line tool that calls the internal algorithm is much more extensive
and I think we just took a short-cut and documented important parameters there.

If that doesn't help, I usually look at the class tests:
https://github.com/OpenMS/OpenMS/blob/develop/src/tests/class_tests/openms/source/InternalCalibration_test.cpp
which sometimes provide additional information.

Or if that doesn't help I usually go back to the source code.

For some of the alignment algorithms, we also have associated tools that might provide more information (some with links to publications).
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/TOPP_MapAlignerIdentification.html
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/TOPP_MapAlignerPoseClustering.html

We are happy to suggest alignment algorithms for specific use cases and if you point out a relevant algorithm we can try to contact the original author or improve the documentation ourselves. 

Maybe not relevant but for a more high-level, user-centric handout you may also check out: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Handout/master/handout.pdf
