### ISSUE TITLE
SwathWizard Icon Same as TOPPView (macOS) - OpenMS 2.6.0 RC

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#4923]
Trying the OpenMS 2.6.0 RC installer - it seems there are some hickups with the SwathWizard.

The macOS icon ".icns" from TOPPView is used as icon for SwathWizard.

Maybe you can have a look @cbielow.

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/SwathWizard-resources/SwathWizard.icns

**Comment by jpfeuffer** [comment]
Also the Path workaround thingy does not seem to work

**Comment by cbielow** [comment]
ahh classic vendo-lock-in problem:
I would have fixed that in the beginning but I could not find a way to create an .icns file without MacOSX (I do not have access to macs), see https://stackoverflow.com/questions/6337787/how-can-i-set-the-icon-for-a-mac-application-in-xcode
`iconutil` is not available on any system I have...

So, can someone with a Mac do the conversion?

**Comment by oliveralka** [comment]
Trying to run SwathWizard either form outside the Contents directory or inside I get the following error:

Try to run the .app:
![Screenshot 2020-09-09 at 11 09 29](https://user-images.githubusercontent.com/15729190/92596342-f9a3ab00-f2a5-11ea-9edc-e9fd963015a2.png)
Try to run from inside the bundle (unix executable)
![Screenshot 2020-09-09 at 11 13 47](https://user-images.githubusercontent.com/15729190/92596353-fc060500-f2a5-11ea-827b-4d377062d0e9.png)

**Comment by cbielow** [comment]
the wizard expects the OpenSwathWorkflow to be next to the current executable:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/DIALOGS/SwathTabWidget.cpp#L80

**Comment by jpfeuffer** [comment]
I assume executable path is the path of the app on macOS

**Comment by jpfeuffer** [comment]
If I fix the path with the app, it still does not work. So executable is executable and you need to introduce an if/else for macOS.

**Comment by jpfeuffer** [comment]
Workaround for paths: Adapt info.plist, add path, run lsregister:
`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -v -f /Users/pfeuffer/git/OpenMS-fixes-src/cmake-build-debug/bin/SwathWizard.app`

Why not hardcode a few common paths? python is always preinstalled in /usr/bin

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/blob/3e7e3f38e0c7650552ae1cbe53ca42a4f959fa5d/src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/SwathWizard-resources/SwathWizard.plist.in

**Comment by jpfeuffer** [comment]
Remove the searchengine stuff please

**Comment by oliveralka** [comment]
@cbielow Do you have a high-quality icon (.png) - I can use for the .icns - I am not yet happy with the resolution.

**Comment by cbielow** [comment]
I took the image from here http://openswath.org/en/latest/_images/OpenSWATH_Workflow.svg
by cutting out the `W`

**Comment by jpfeuffer** [comment]
#4924
