### ISSUE TITLE
OpenMS DecoyDatabase KNime Node does not work.

### ISSUE THREAD

**Issue by baranme** [OpenMS/OpenMS#4925]
Hi there. Currently i am givin a fasta file, which i need fpr my identification. The fasta file does not contain any decoys. So i wanted to generate some. The fasta file is not that big (100MB aprox.). When i read in the file i get the error output: 
ERROR DecoyDatabase        3:891      Failing process stderr: []
ERROR DecoyDatabase        3:891      Return code: -1073741515
ERROR DecoyDatabase        3:891      Execute failed: Failed to execute node DecoyDatabase
Could you please help me? Greetings!

**Comment by jpfeuffer** [comment]
Hi,

did you install the [prerequisites](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/PrerequisitesInstaller/OpenMS-2.5-prerequisites-installer.exe) as usually pointed out in the console during startup?

**Comment by baranme** [comment]
Well, that was easy. Thank you very much!
