### ISSUE TITLE
Picking (HiRes) IM data looses IM information

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4959]

**Comment by poshul** [comment]
This is still open and marked critical what is the state of it?

**Comment by jpfeuffer** [comment]
@cbielow You were the last one working on IM data. Can you comment?

**Comment by cbielow** [comment]
How easy this can be fixed depends on what kind of input data is given. If only a single IM is annotated for the whole spec, it would be easy to set it again on the picked spec.
If IM is given as metadata array, its at bit harder 
 1) split by IM
 2) do PP
 3) merge again

Functions for 1) and 3) are available.

**Comment by timosachsenberg** [comment]
k how should we go forward here?
I think it is stored in a metadata array.
How feasible would be a detection in the peak picking methods?
Splitting by e.g. non-overlapping IM bins could also easily split peaks and we don't know how to set IM tolerances here.
