### ISSUE TITLE
[BUILD] Building OpenMS with C++17 with MSVC 14.2 (VS19)

### ISSUE THREAD

**Issue by ahmedskhalil** [OpenMS/OpenMS#4962]
**Description**
We would like to start building OpenMS with the C++17 standard as we are currently migrating to C++17 for SmartPeak. Unfortunately it doesn't seem viable on Windows as some of the removed functions in the standard are still existent in OpenMS (i.e. `std::binary_function`)

**Objectives**
In conjunction with #4624 ,  are there any other solutions for integrating OpenMS in C++14 with applications that use C++17? When is it expected to have OpenMS fully supporting C++17?

**Comment by jpfeuffer** [comment]
Hi! We would love to provide this and are happy to start working on this after the shortly upcoming release. After the release I can switch the nightly builds to C17 for testing but it would be great if you could send us/upload the full error log. Hopefully we can see some easy to solve issues right away.

**Comment by ahmedskhalil** [comment]
Hi, Thanks, we'd love to participate in the migration cycle by providing the necessary error log and other related info. Once the switch has been through, we will integrate and test it into our current application.

**Comment by ahmedskhalil** [comment]
Hi @jpfeuffer , are there any updated regarding the C++17 build?

**Comment by jpfeuffer** [comment]
Yes, we are currently in the process of moving the "master" build server and upgrading our build agents (we also need a Java upgrade).
We need to find out the minimal GCC, AppleClang and MSVC versions for C++17. And the corresponding minimal Ubuntu/CentOS version where these GCCs are available.

**Comment by jpfeuffer** [comment]
Related to: https://github.com/OpenMS/OpenMS/issues/4624

**Comment by ahmedskhalil** [comment]
Are there any updates?

**Comment by jpfeuffer** [comment]
@cbielow is currently testing the CMake settings, and our IT has a ticket to upgrade the Windows build machines.

**Comment by cbielow** [comment]
Windows CI machines have VS2019 installed now.
Shall we switch over?
We could force C17 using CMake, but that's not strictly required for now. Maybe later to make sure we are not using a C20 feature by accident because our CI happens to support it...

**Comment by jpfeuffer** [comment]
Side-by-side installation? Cause CI is still using 14.0. Could be hard to force the usage of a specific VS. CMake toolset files etc.

**Comment by cbielow** [comment]
mhh.. VS Version can be selected by the Cmake generator, right? Contrib and Qt should not matter, since even a VS2015build should be ABI-compatible to VS2019.
Correct shell environment is the only thing I imagine could be trouble...

**Comment by jpfeuffer** [comment]
any branch with c17 features to test?

**Comment by jpfeuffer** [comment]
Fixed by #c17 PR.
