### ISSUE TITLE
IDMapper should support mapping by native_id

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#4965]
to avoid magic rt,m/z constants
used in, e.g., `LayerData::annotate`

**Comment by timosachsenberg** [comment]
To be added here: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/ANALYSIS/ID/IDMapper.cpp#L98

Currently, we map precursors in the peak data structure (peakmap) to the precursors in the identification data structure. Right now, we only compare if the RT and MZ dimension are close enough together and if so the IDs gets mapped and stored in the peakmap.
These costly comparisons are not necessary if we already have the native spectrum identifiers stored in the ID data. In that case we can just store the ID in the corresponding spectrum.

So we need to:
1. retrieve native id from ID peptide_ID.getMetaValue("spectrum_reference")
2. Use the SpectrumLookup class [1] to locate the spectrum with said native id
3. store the id in that spectrum


[1] https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/METADATA/SpectrumLookup.h#L150

**Comment by timosachsenberg** [comment]
Probably only fall back to the old behavior (comparison of mz/RT) if the metaValueExists("spectrum_reference") == false or if we are not able to locate the native id

**Comment by RobertDeibel** [comment]
I'm unsure if the tests cover this. How would one go about writing test for this issue? Also see related PR.
