### ISSUE TITLE
TOPPView No SVG support for MS1 peak maps

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4970]
Therefore relatively useless for publication images.

**Comment by timosachsenberg** [comment]
The 2D view draws a lot of points. representing them in svg just takes huge amounts of memory afaik.
I think currently ImageCreator is the preferred option for that as it uses interpolation to create high res images.

**Comment by jpfeuffer** [comment]
Makes sense, but I think it would be useful for small excerpts or pure feature box representations.
Especially since we cannot yet get rid of the grey border.

**Comment by timosachsenberg** [comment]
I mean you can probably just set the background color of the axis widget to white? would that help?

**Comment by jpfeuffer** [comment]
Yes, in the settings or in the code?

**Comment by timosachsenberg** [comment]
I think in the code.
Setting background color to white in https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/AxisWidget.cpp
may work.

**Comment by jpfeuffer** [comment]
Where is the code for the config dialog for the colors? One should add it there for configurability.

**Comment by timosachsenberg** [comment]
I think if it looks good then we just keep as default and don't need to make it configurable (always a bit painful to if I recall correctly). Or just set the background to white during export.

**Comment by timosachsenberg** [comment]
kind of fixed with recent changes to set background to white on export
