### ISSUE TITLE
Funding of development

### ISSUE THREAD

**Issue by fkromer** [OpenMS/OpenMS#4978]
Have you guys ever thought about using something like [LibreSelery](https://github.com/protontypes/libreselery) to fund development?

**Comment by timosachsenberg** [comment]
Sounds interesting but raises many questions. I would like to learn how this works from the legal side in the context of people partly funded by third-party sources, being employed in academics, or people working in industries etc. Also, what the legal requirements for a project like OpenMS would be.
I think it might be even difficult to accept donations to the project at all.
Do you have any experience with that?

**Comment by fkromer** [comment]
@timosachsenberg I would recommend to reach out to [Ly0n](https://github.com/Ly0n). I discussed this topic with him recently and I think they have a solution or they are at least working at a solution w.r.t. especially for devs from germany where tax related stuff is quite nasty.

**Comment by Ly0n** [comment]
@timosachsenberg:
> I would like to learn how this works from the legal side in the context of people partly funded by third-party sources, being employed in academics, or people working in industries etc
LibreSelery will send the donation to the public email address of your GitHub account. In case his email address is a business or academics address you need to talk to your organization what to do with the donation. If you have entered a private email address here, you can accept the donations (In case you also using the GitHub Account for private usage and not for business contributions). In case stay under the "tax-free amount" (in Germany about 250€ per year) you do not have to pay additional tax on this income. You can also not accept the donation and it will expire in 30 days.

> I think it might be even difficult to accept donations to the project at all.
I totally understand this. It looks like most contributors of OpenMS are funded by different universities. LibreSelery makes sense when you collect a larger pot of donations and want to distribute that over a project. If one day the support of universities and the financed jobs for the development should fall away, then it could be interesting to open a donation pot. The money from this pot can then be distributed to the contributors via LibreSelery to keep the community active.

**Comment by poshul** [comment]
Since this was opened, we've created an OpenCollective account. I think we will use this for now, and keep an eye out for when we get to the scale where LibreSelery makes sense for us.

Thanks!
