### ISSUE TITLE
Epifany: export error while exporting results with MzTabExporter

### ISSUE THREAD

**Issue by giangiacomoberetta1** [OpenMS/OpenMS#4982]
Hi!

while exporting protein inference results generated with Epifany, I got the following error:

ERROR MzTabExporter        4:45       Failing process stdout: [Error: Unexpected internal error (Protein header and content differs in columns. Please report this bug to the OpenMS developers.)]
ERROR MzTabExporter        4:45       Failing process stderr: []
ERROR MzTabExporter        4:45       Return code: 8
ERROR MzTabExporter        4:45       Execute failed: Failed to execute node MzTabExporter

**Comment by jpfeuffer** [comment]
Hmm this is usually just a small exporting problem due to our new stricter mzTab formatting standard.
Could you upload the affected id/consensusXML file, or at least a significant portion of its header?

**Comment by giangiacomoberetta1** [comment]
Thank you ! I noticed that after combination of results from Xtandem and MSGF+ using IDmerge, some downstream nodes receive something equivalent to 2 runs (MzTabExporter but also PIA and ProteinInference fail probably because of this) , so cannot proceed.

As it is the first time I notice this characteristic, I was wondering whether this may result from a modification from previous versions...

**Comment by giangiacomoberetta1** [comment]
Great, thanks!
