### ISSUE TITLE
Improve onboarding of developers with chat?

### ISSUE THREAD

**Issue by fkromer** [OpenMS/OpenMS#4986]
Hi guys, what do you think about creating a chat for OpenMS related questions?

Onboarding new people into the project is really hard. The OpenMS C++ API is documented in a very minimalistic manner. For the [Python bindings](https://pyopenms.readthedocs.io/en/latest/) there does not even exist an API. [There is just a note about how C++ classes are wrapped into Python automatically.](https://pyopenms.readthedocs.io/en/latest/wrap_classes.html) From a developer point of view I fully understand the minimalistic documentation. I wouldn't do it differently. However even using the common "learning by asking" approach via Stackoverflow is not possible: On stackoverflow there are only [18 questions tagged "openms"](https://stackoverflow.com/search?q=openms). Of course there are [2 mailing lists](https://sourceforge.net/p/open-ms/mailman/). However I think mailing lists have a lot of disadvantages in comparison to chat rooms like e.g. like provided via Gitter. What do you think about setting up a gitter chat room?

**Comment by timosachsenberg** [comment]
Hi, we already have a Gitter chat channel in place (small button on repo main page).
Do you have suggestions on how to make it more prominent? Where would you have looked for the link?

**Comment by fkromer** [comment]
> Where would you have looked for the link?

Oh, that's great. Sorry. My fault. Did not recognize it in the bottom part of https://www.openms.de/support/ in the "Reach us on GitHub" section. I expected it right in front of or after the "Mailing Lists" section.

**Comment by timosachsenberg** [comment]
I moved it up on the page. Thanks
