### ISSUE TITLE
Support for msconvert --srmAsSpectra specific getSpectrum()?

### ISSUE THREAD

**Issue by fkromer** [OpenMS/OpenMS#4992]
The OpenMS API provides the method [`MSSpectrum& getSpectrum ( Size id)`](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1MSExperiment.html#a5df83113e1be59bc07ae5fb41d652609) to get a spectrum from a [MSExperiment](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1MSExperiment.html#a5df83113e1be59bc07ae5fb41d652609). If one reads a mzML file containing SRMs, e.g. 2 SRMs into the experiment which has been converted from raw data into a mzML file with `msconvert` command line option `--srmAsSpectra` set results in a mapping between spectrum, TIC chromatogram (`getChromatogram(0)`) and SRM chromatograms (`getChromatogram(1)`, `getChromatogram(2)`) as follows:

```
getSpectrum(0) <-> TIC chromatogram, intensity @ first retention time <-> SRM1 chromatogram, intensity @ first retention time
getSpectrum(1) <-> TIC chromatogram, intensity @ first retention time <-> SRM2 chromatogram, intensity @ first retention time
getSpectrum(2) <-> TIC chromatogram, intensity @ first retention time <-> SRM1 chromatogram, intensity @ second retention time
getSpectrum(3) <-> TIC chromatogram, intensity @ first retention time <-> SRM2 chromatogram, intensity @ second retention time
...
```

If one want's to get a spectrum from a single SRM this implies the need for further processing. What do you think about adding support with e.g. a signature like `MSSpectrum& getSpectrum ( ? srm_id, Size id)`?

**Comment by timosachsenberg** [comment]
I think the MSExperiment class would probably not be the right place for that method. I would probably build a simple mapping between SRM transitions and spectrum native id + peak indices in the spectrum and work on that.

**Comment by fkromer** [comment]
@timosachsenberg Yes, thanks for the hint. That's exactly what I've going to do right now. The issue was meant for documentation purposes cause this behavior is not intuitive but does not really fit into the official docs. Hopefully this will save other people some time.
