### ISSUE TITLE
Update tools that can be directly run in TOPPView

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5001]
Bonus points for determining those tools automatically

**Comment by timosachsenberg** [comment]
Basically updating the lists in https://github.com/OpenMS/OpenMS/blob/d17cc251fd0c4068eb253b03c9fb107897771fdc/src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp#L73

**Comment by timosachsenberg** [comment]
You can get the list of registered tools here:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/APPLICATIONS/ToolHandler.h#L80
Now we need to find out to what layer (= kind of data) these tools are compatible with.
This can be determined from the information in the .ini files these tools produce.
Right now, we only produce the ini file once we already selected a tool: https://github.com/OpenMS/OpenMS/blob/d17cc251fd0c4068eb253b03c9fb107897771fdc/src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp#L233
but in our case we would need to 

1. generate all ini files of registered tools first
2. load it into a param object as done above 
3. if an in parameter exists we can decide what type of layer it is based on the file extension of the input file

**Comment by dvdvgt** [comment]
I'd like to work on this.

**Comment by timosachsenberg** [comment]
pseudo code:
```
ToolsDialog::ToolsDialog(QWidget* parent, String ini_file, String default_dir, LayerData::DataType type) :
    QDialog(parent),
    ini_file_(ini_file),
    default_dir_(default_dir)
  {
    QGridLayout* main_grid = new QGridLayout(this);
    QLabel* label = new QLabel("TOPP tool:");
    main_grid->addWidget(label, 0, 0);
    QStringList list;

    Map<String, Internal::ToolDescription> tools = ToolHandler::getTOPPToolList();
    for (const auto& name2description : tools)
    {
        const String& name = name2description.first;
        Param p = getParamFromIni_(name);
        // determine data type from param
        LayerData::DataType tool_type = getTypeFromParam_(p);
        if (tool_type == type)
        {
          list << name;
        }        
    }

    //sort list alphabetically
    list.sort();
   ...
   ...
```

**Comment by dvdvgt** [comment]
So I was able to generate the ini file and extract the file extensions for each tool. However doing so takes a considerable amount of time - around **5 seconds**. This seems a bit too much.

Regardless of that this is my current approach:
```c++
    const auto& tools = OpenMS::ToolHandler::getTOPPToolList();
    for (const auto& tool : tools)
    {
        const String& toolName = tool.first;
        Param p = getParamFromIni_(toolName);
        LayerData::DataType toolType;
        // Find "in" entry
        for (const auto& entry : p)
        {
            if (entry.name == "in") {
                // valid_strings contains the valid file extensions
                for (auto& s : entry.valid_strings);
            }
        }
        list << toolName.toQString();
     }
```
`entry.valid_string` yields all valid file extensions as `String` though it is not comparable with `LayerData::DataType layer_type`. Is there away to map the file extensions to `LayerData::DataType` or vice versa?

**Comment by timosachsenberg** [comment]
I think we will find a way to speed that up later, so I think it is fine for now.
Regarding:
> entry.valid_string yields all valid file extensions as String though it is not comparable with LayerData::DataType layer_type. Is there away to map the file extensions to LayerData::DataType or vice versa? Is there way to find out what kind of files a LayerData::DataType accepts?

I think we can map to the DataType like this:
mzML  or mzXML -> DT_PEAK,            ///< Spectrum profile or centroided data
featureXML ->  DT_FEATURE,         ///< Feature data
consensusXML -> DT_CONSENSUS,       ///< Consensus feature data
idXML or mzIdentML ->  DT_IDENT,           ///< Peptide identification data

Probably also best to put this into an extra method

>Is there a way to directly fetch the "in" entry in order to avoid looping over all entries? There's a function Param::getEntry but I don't know what kind of key it expects (getEntry("in") yields an error).

I think how you do it is fine. The loop can't be really avoided I think. 
But I think this is not a performance problem (should only take a fraction of a second to iterate for all files). Most time is probably spend in executing, writing and reading back from hard disc.

**Comment by dvdvgt** [comment]
I implemented all the changes but there are some things left I'd like to discuss:

- Refactoring because of duplicate code.
- DataType map as class attribute or only locally inside `getTypesFromParam_` (with the disadvantage that it'd need to be reinitialized at every function call).
- How to handle write errors in `getParamFromIni_`

It's probably easier if I open a PR so you can have a look at all the changes, no?

**Comment by timosachsenberg** [comment]
Yeah please open a PR so we easily comment. Thanks!
