### ISSUE TITLE
Conversion of mzidentML into idXML not supported in IdFileconverter [501]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#501]
Submitted by wernber on 2012-12-12 16:06:46

Hello all,

Unfortunately it seems, that the import of mzidentML files via IdFileconverter and their conversion into idXML is not supported currently.

I think, the implementation of an import feature would be extremely important.

With best regards,

Wernber

**Comment by hroest** [comment]
@timosachsenberg is this still an issue? I think IDFileConverter now supports this, see http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/TOPP_IDFileConverter.html
