### ISSUE TITLE
Tools without category

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#5014]
- DatabaseSuitability
- GNPSExport
- ProteomicsLFQ

**Comment by oliveralka** [comment]
Do you mean in the documentation?

Since it seems they are registered in the ToolHandler with a category:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/APPLICATIONS/ToolHandler.cpp#L77
e.g. `tools_map["GNPSExport"] = Internal::ToolDescription("GNPSExport", "File Handling");`

**Comment by oliveralka** [comment]
Hi @bernt-matthias,
could you shortly specify what you mean? Doxygen documentation or code? 

It seems that the tools have a registered category at least in the ToolHandler.
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/APPLICATIONS/ToolHandler.cpp#L77
e.g. `tools_map["GNPSExport"] = Internal::ToolDescription("GNPSExport", "File Handling");`

**Comment by timosachsenberg** [comment]
ok strange. @oliveralka can you check if they are wrongly registered as util or tool?

**Comment by bernt-matthias** [comment]
At least in the generated ctd the category is missing. Also in the knime Screenshot that @timosachsenberg sent me on gitter the three tools were outside of the categories.

**Comment by timosachsenberg** [comment]
It is registered as a util  https://github.com/OpenMS/OpenMS/blob/develop/src/topp/GNPSExport.cpp#L83
and here as a tool https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/APPLICATIONS/ToolHandler.cpp#L77
so I guess this is the issue

**Comment by jpfeuffer** [comment]
This happens a lot. Can we maybe introduce a check? E.g. in the TOPPBase constructor? There were remnants of a check in the getDocumentationURL method but I removed it since it was non-functional and kind of out-of-place.

**Comment by timosachsenberg** [comment]
How would this work in TOPPBase?
Is better to place the check into ToolHandler?

**Comment by jpfeuffer** [comment]
No, you need the classification from TOPPBase. if official, then check ToolHandler::TOPP else check ToolHandler::Utils

**Comment by jpfeuffer** [comment]
plus check that it is not double, etc

**Comment by jpfeuffer** [comment]
Or yes, better, put the check for duplication in toolhandler and the check for matching in ToppBase

**Comment by timosachsenberg** [comment]
Check for matching in TOPPBase we get a dependency on ToolHandler. Not nice but I don't think it can be done the other way.
Better would be if ToolHandler could ask every tool (=instantiate and call isTool) in the list. But tools are not instantiable.
