### ISSUE TITLE
Export Triqler output from consensusMap

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5023]
https://www.biorxiv.org/content/10.1101/2020.09.24.311605v1.full

Specifically fig.1

**Comment by jpfeuffer** [comment]
Use the MSstatsExporter for a baseline. It will be very similar.

**Comment by timosachsenberg** [comment]
see also the readme on https://github.com/statisticalbiotechnology/triqler for the format

**Comment by timosachsenberg** [comment]
Emil will take a look

**Comment by timosachsenberg** [comment]
I think this is done?
