### ISSUE TITLE
TOPPView: Preferences greyed out on startup

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5029]
After loading a file it is enabled and I get an exception: 'Caught exception: 'ElementNotFound' with message 'the element 'preferences:tmp_file_path' could not be found'

**Comment by cbielow** [comment]
Partially fixed by #5031

**Comment by timosachsenberg** [comment]
Fixed: exception disappeared
Not fixed: greyed out AND crash in TOPPViewIdentificationView
