### ISSUE TITLE
Pyopenms 2.6 builds

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5039]
Problem is that we did not have a pip token when the release was generated. The secrets are stored now but manually triggering the workflows does not pick them up correctly. The usual trigger is a trigger based on a release tag, which we should not change anymore.
Another problem is, that the workflow currently fails due to changes in conda probably.

Steps:
- Fix nightly builds
- Push fixes plus a branch or manual trigger to release/2.6.0
- Make sure a release type build is triggered and check the results on pip

**Comment by oliveralka** [comment]
pyopenms 2.6.0 is now available (manually upload to pypi)
https://pypi.org/project/pyopenms/

**Comment by oliveralka** [comment]
@jpfeuffer I think we can close this since pyopenms 2.6.0  (pypi) is up-to-date now. 
And we are working on a nightly fix https://github.com/OpenMS/OpenMS/pull/5053
