### ISSUE TITLE
reported ConsensusID error in OpenMS 2.6

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5050]
I am facing this error while analyzing MS data from phosphoproteomic (in mzML file type):

ERROR ConsensusID          0:279      Failing process stdout: [Progress of 'Linking features':, ,   56.86 %               , -- done [took 1.95 s (CPU), 1.96 s (Wall)] -- ,
Error: Unexpected internal error (the element 'No accession sp|Q15582|BGH3_HUMAN found in run '' for PSM .(iTRAQ4plex)TLFELAAESDVSTAIDLFR_3. Please contact the maintainer of this tool e.g. on GitHub as this should not happen.' could not be found).

This node worked well for proteomics analysis (on windows 10, in KNIME).

The google search did not give me anything, so I have no idea how I can rectify this? Any help in this regard is much appreciated.

**Comment by jpfeuffer** [comment]
Fixed in #5024

**Comment by timosachsenberg** [comment]
you find updated installer in our nightly build archive: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/

**Comment by jpfeuffer** [comment]
Or just use "--per_spectrum", or filter proteins.

**Comment by manwarA** [comment]
Thank you. "--per_spectrum" works.
