### ISSUE TITLE
Test if function declarations match the existing on in test files

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5088]
e.g., we have no way to automatically test if the function has the same parameters as provided in the macro: START_SECTION((AASequence shufflePeptides(const AASequence& aas, const String& protease, const int max_atempts, int seed)))

**Comment by jpfeuffer** [comment]
But isnt this because you are allowed to put arbitrary Strings there?

section 1: method1 with string input
section 2: method1 with empty input

and so on. Therefore you can make more fine-grained tests.

**Comment by timosachsenberg** [comment]
yeah I guess. I just saw a few cases where the current parameters did not match the ones in the test file
