### ISSUE TITLE
Remove dependencies to non standard code in Param object

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5090]
- replace usage of Map with map
- replace usage of String with string

from Param.h and Param.cpp

**Comment by guptaaman70659** [comment]
Hi, @timosachsenberg I am interested in open source. Would you please give the path where these two files **Param.h** and **Param.cpp** are present in the code.

**Comment by jpfeuffer** [comment]
Hi @guptaaman70659 
The affected parts are here:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/DATASTRUCTURES/Param.cpp#L40
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/DATASTRUCTURES/Param.h#L39

Of course the usage throughout the class needs to be adapted as well.

**Comment by timosachsenberg** [comment]
Hi, nice to hear that you want to help. Feel free to ask any questions. Here or in our gitter chat.  https://gitter.im/OpenMS/OpenMS

**Comment by guptaaman70659** [comment]
Thank you very much @timosachsenberg and @jpfeuffer for response :)

I have forked and cloned **OpenMS** Repository and done the following changes

1. I have replaced **Map** with **map** at line 40 in **Param.cpp** file
![Param_cpp](https://user-images.githubusercontent.com/33172355/102206852-3e695e80-3ef3-11eb-8955-a32c5d3d9756.png)

2.  I have replaced **String** with **string** at line 39 in **Param.h** file
![Param_h](https://user-images.githubusercontent.com/33172355/102206977-61940e00-3ef3-11eb-9c06-9a7e4adf7fb3.png)

At last, I have renamed the file name **Map.h** to **map.h** and **String.h** to **string.h** present at `https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/DATASTRUCTURES/`

Would I commit these changes or is there anything left where changes are to be done?

**Comment by timosachsenberg** [comment]
Hi,
sorry for not being super precise in the issue description but renaming our files is not what we want.

The goal is to use std::map and std::string instead of our OpenMS::Map and OpenMS::String implementation.
The reason is that another project wants to use our Param class but doesn't want to use our custom String and Map implementation.
See e.g., this PR where I also got rid of using Map https://github.com/OpenMS/OpenMS/pull/5102/files

**Comment by guptaaman70659** [comment]
OK, Then I have to replace **Map** with **map** from at line **39** and replace at line **889** in **Param.cpp** and same in **Param.h** file

![Update_Line_889](https://user-images.githubusercontent.com/33172355/102220387-bee58a80-3f06-11eb-93c1-d51ca24880d9.png)

**Comment by timosachsenberg** [comment]
yes, and then make it compile again :P

**Comment by guptaaman70659** [comment]
Ok cool, I have done the change for building, and compiling is taking a lot of time. as I go through the below link 
[https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/install_linux.html#install_linux_openms](url)

**Comment by guptaaman70659** [comment]
@timosachsenberg I have a question for recompilation has to run **make** or **make OpenMS**  ?

**Comment by timosachsenberg** [comment]
I usually call just: make -j4 (where -j means the number of parallel jobs, e.g., cores that you want to use)

**Comment by timosachsenberg** [comment]
Hi, this issue recently became a bit more urgent. @guptaaman70659 did you make any progress? I don't want to take it away from you but we kind of need to move this forward.

**Comment by guptaaman70659** [comment]
Sorry for the delay But I am getting a compilation error and trying to fix it.
