### ISSUE TITLE
CometAdapter node mislabels TMTpro as iTRAQ8plex

### ISSUE THREAD

**Issue by mmelake** [OpenMS/OpenMS#5095]
Hi, 

I've noticed that the TMTpro modifications in the CometAdapter result file are mislabelled as iTRAQ8plex. 
I've selected TMTpro under variable_modifications in the node configuration as well as in the default_params_file.
There were no error messages.

I'm using OpenMS from within KNIME 4.2.2 on Windows Server 2016 Standard.

Could this potentially be a bug?

Thanks,
Miriam

**Comment by jpfeuffer** [comment]
Hmm might be a problem, that those two modifications are close in mass.
Can you upload an affected mzML file and your Comet settings/param file?

**Comment by jpfeuffer** [comment]
Ah but first: Which version of the OpenMS plugin? TMTpro was unfortunately first added in 2.6.0.

**Comment by mmelake** [comment]
[2019.01 CometSearch.params.txt](https://github.com/OpenMS/OpenMS/files/5654143/2019.01.CometSearch.params.txt)

I've uploaded the param file. Currently inquiring if I can share the affected mzML file.
I'll get back to you with the OpenMS plugin version shortly.

Thanks!

**Comment by mmelake** [comment]
> Ah but first: Which version of the OpenMS plugin? TMTpro was unfortunately first added in 2.6.0.

Yes, we are using plugin version 2.6.

**Comment by jpfeuffer** [comment]
Hmm ok. A filtered mzML (e.g. a small subset of the MS2 scans, in a particular RT region, where you know there is a TMT labelled peptide) would suffice as well.

**Comment by mmelake** [comment]
I've managed to find a suitable file. 
Here's some info on it: human cells, iodocatamide, trypsin, TMTpro, HCD-MS2 high res spectra

I couldn't upload the mzML file here. Would you like me to send it to you?

**Comment by jpfeuffer** [comment]
Perfect, sounds reasonable. Yes you can send it to me. Can you see my email in the github profile?

**Comment by mmelake** [comment]
Yes, I can. It looks like the mzML is too large to email (~1.8GB) though. Any alternative ways of sending that work for you?

**Comment by jpfeuffer** [comment]
Hmm, I could setup an FTP but if you are allowed to upload it to any cloud, it would probably be quicker.

**Comment by mmelake** [comment]
Ok, I've managed to send you a filtered version of the original mzML now.

**Comment by jpfeuffer** [comment]
Thanks. I could reproduce the problem. I will have a deeper look. Short question: Do you expect any advantages from the TMT modifications as variable modifications? I think we usually set them as fixed since you cannot (comparably) quantify unlabelled peptides anyway. Just asking because it increases Comet's search space and runtime quite a bit.

**Comment by mmelake** [comment]
Yes, for this file you can set TMT as a fixed modification. The params_file was for another sample, where we weren't interested in quantification and didn't expect 100% TMT labelling. I should have updated the file. Thanks!

**Comment by jpfeuffer** [comment]
Hi @mmelake If you have a test instance, you can try the nightly update site (in the next days) to see if this fixed the issue for you:
http://update.knime.com/community-contributions/trunk

**Comment by mmelake** [comment]
Thanks @jpfeuffer . Unfortunately I "don't have permission to access this resource" once I click on the link.

**Comment by jpfeuffer** [comment]
Hi! Yes, that is a so-called "update site" that you cannot view in your browser. It should work when you enter it in KNIME under "Help->Install New Software->Add software update site" (or something like that).
Then select OpenMS under Bioinformatics and update. I recommend doing it in a non-production KNIME first of course.

**Comment by mmelake** [comment]
That fixed it. Thank you!
