### ISSUE TITLE
Recent changes break Luciphor

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5109]
Error here for Tyrosin Y:
https://github.com/OpenMS/OpenMS/blob/faeda8ce9ce8c266672efb10134651f52756a220/src/topp/LuciphorAdapter.cpp#L425

https://github.com/nf-core/proteomicslfq/pull/119/checks?check_run_id=1563748891

Not sure which recent changes. ResidueDB? searchModByDiffMass?

**Comment by jpfeuffer** [comment]
Actually I think it might be the change for the short name in ResidueDB.

**Comment by timosachsenberg** [comment]
might be related to PSI-MOD "O4&apos;-(phospho-5&apos;-RNA)-L-tyrosine (Y)"
