### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#5110]
Greetings,

I know that this might look like something superfluous, but when packaging OpenMS for Debian our routine checks discovered the following potential typos in the source code. If anybody has some spare time :). Feel free to close this issue...

O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 "allow to" "allow one to"
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 Therefor Therefore
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 Unkown Unknown
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 adviced advised
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 ambigious ambiguous
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 colums columns
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 doesnt doesn't
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 enought enough
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 modifcation modification
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 neccessary necessary
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 occured occurred
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 occurences occurrences
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 occuring occurring
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 parallely parallelly
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 seperate separate
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 simulataneously simultaneously
O: libopenms2.6.0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libOpenMS.so.2.6.0 transistions transitions

Regards,
Filippo

**Comment by oliveralka** [comment]
Hi Filippo, 

thanks for pointing them out! 

Cheers
Oliver
