### ISSUE TITLE
Build failure with Debian testing

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#5123]
Greetings, 
upon building of OpenMS on Debian testing, we get these errors:

Relevant part (hopefully):
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/openms && /usr/bin/c++ -DBOOST_ALL_NO_LIB -DOpenMS_EXPORTS -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/openms -I/<<PKGBUILDDIR>>/src/openms -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/openms/OpenMS_autogen/include -I/<<PKGBUILDDIR>>/src/openms/include -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/openms/include -isystem /usr/lib -isystem /usr/lib/x86_64-linux-gnu/include -isystem /<<PKGBUILDDIR>>/src/openms/thirdparty/evergreen/src -isystem /usr/include/hdf5/serial -isystem /usr/include/libsvm -isystem /usr/include/eigen3 -isystem /usr/include/libwildmagic -isystem /<<PKGBUILDDIR>>/src/openswathalgo/include -isystem /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/openswathalgo/include -isystem /<<PKGBUILDDIR>>/src/openswathalgo/thirdparty/MIToolbox/include -isystem /<<PKGBUILDDIR>>/src/openswathalgo/thirdparty/MIToolbox/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /<<PKGBUILDDIR>>/src/openms/thirdparty/eol-bspline -isystem /<<PKGBUILDDIR>>/src/openms/thirdparty/IsoSpec -isystem /<<PKGBUILDDIR>>/src/openms/thirdparty/json -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2    -O3 -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wno-non-virtual-dtor -Wno-unknown-pragmas -Wno-long-long -Wno-unused-function -Wno-variadic-macros -fPIC -fopenmp -o CMakeFiles/OpenMS.dir/source/DATASTRUCTURES/LPWrapper.cpp.o -c /<<PKGBUILDDIR>>/src/openms/source/DATASTRUCTURES/LPWrapper.cpp
> In file included from /<<PKGBUILDDIR>>/src/openms/source/DATASTRUCTURES/LPWrapper.cpp:63:
> /usr/include/glpk.h:36:16: error: using typedef-name ‘glp_prob’ after ‘struct’
>    36 | typedef struct glp_prob glp_prob;
>       |                ^~~~~~~~
> In file included from /<<PKGBUILDDIR>>/src/openms/source/DATASTRUCTURES/LPWrapper.cpp:37:
> /<<PKGBUILDDIR>>/src/openms/include/OpenMS/DATASTRUCTURES/LPWrapper.h:58:3: note: ‘glp_prob’ has a previous declaration here
>    58 | } glp_prob;
>       |   ^~~~~~~~
> In file included from /<<PKGBUILDDIR>>/src/openms/source/DATASTRUCTURES/LPWrapper.cpp:63:
> /usr/include/glpk.h:36:25: error: conflicting declaration ‘typedef int glp_prob’
>    36 | typedef struct glp_prob glp_prob;
>       |                         ^~~~~~~~
> In file included from /<<PKGBUILDDIR>>/src/openms/source/DATASTRUCTURES/LPWrapper.cpp:37:
> /<<PKGBUILDDIR>>/src/openms/include/OpenMS/DATASTRUCTURES/LPWrapper.h:58:3: note: previous declaration as ‘typedef struct glp_prob glp_prob’
>    58 | } glp_prob;
>       |   ^~~~~~~~
> /<<PKGBUILDDIR>>/src/openms/source/DATASTRUCTURES/LPWrapper.cpp: In member function ‘void OpenMS::LPWrapper::readProblem(const OpenMS::String&, const OpenMS::String&)’:
> /<<PKGBUILDDIR>>/src/openms/source/DATASTRUCTURES/LPWrapper.cpp:472:69: warning: unused parameter ‘format’ [-Wunused-parameter]
>   472 |   void LPWrapper::readProblem(const String& filename, const String& format) // format=(LP,MPS,GLPK)
>       |                                                       ~~~~~~~~~~~~~~^~~~~~
> /<<PKGBUILDDIR>>/src/openms/source/DATASTRUCTURES/LPWrapper.cpp: In member function ‘OpenMS::Int OpenMS::LPWrapper::solve(OpenMS::LPWrapper::SolverParam&, OpenMS::Size)’:
> /<<PKGBUILDDIR>>/src/openms/source/DATASTRUCTURES/LPWrapper.cpp:529:37: warning: unused parameter ‘solver_param’ [-Wunused-parameter]
>   529 |   Int LPWrapper::solve(SolverParam& solver_param, const Size
>       |                        ~~~~~~~~~~~~~^~~~~~~~~~~~
> make[5]: *** [src/openms/CMakeFiles/OpenMS.dir/build.make:1168: src/openms/CMakeFiles/OpenMS.dir/source/DATASTRUCTURES/LPWrapper.cpp.o] Error 1

One Fellow Developer, from Ubuntu, Logan Rosen has suggested this patch to fix the build error. 

8< ~~~~~~

diff --git a/src/openms/include/OpenMS/DATASTRUCTURES/LPWrapper.h b/src/openms/include/OpenMS/DATASTRUCTURES/LPWrapper.h
index 83c81d78..289fbd7e 100644
--- a/src/openms/include/OpenMS/DATASTRUCTURES/LPWrapper.h
+++ b/src/openms/include/OpenMS/DATASTRUCTURES/LPWrapper.h
@@ -51,7 +51,7 @@ class CoinModel;
 #define GLP_PROB_DEFINED
 // depending on the glpk version
 // define glp_prob as forward or struct
-#if OPENMS_GLPK_VERSION_MINOR < 48
+#if OPENMS_GLPK_VERSION_MAJOR == 4 && OPENMS_GLPK_VERSION_MINOR < 48
 typedef struct
 {
   double _opaque_prob[100];

~~~~~~ >8

Do you think this patch is correct and addresses the problem in the right way ?

I'll use it for the moment, waiting for your comments.

Sincerely,
Filippo Rusconi

**Comment by cbielow** [comment]
Hey Filippo,

So you are using GLPK 5?
The fix looks good.
