### ISSUE TITLE
smartFileNames_() in TOPPAS not mature enough [513]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#513]
Submitted by johannes_junker on 2013-02-25 11:54:14

The renaming of output files that is supposed to happen under certain circumstances is not mature enough yet.

E.g., when a "Collect" node is involved (as in the BSA quantitation example), the old and the new naming scheme are mixed, resulting in file names like "out_to_BSA3_OMSSA.consensusXML".

---

Commented by johannes_junker on 2013-02-25 11:58:16:
An attempt to implement this properly would be too dangerous at the moment, as we need a release candidate today.

Temporarily commented out the functionality of smartFileNames_() in r10768.

Proper implementation postponed to 1.11 / 2.0.

---

Commented by hroest on 2013-06-24 10:03:06:
Is not critical and will not make it into 1.11

**Comment by hroest** [comment]
seems like its fixed - by commenting out
