### ISSUE TITLE
Unable to access documentation

### ISSUE THREAD

**Issue by saifulbkhan** [OpenMS/OpenMS#5131]
Hello. OpenMS is awesome!

But I have noticed for the past 4 days, that trying to visit the [documentation page](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/index.html) results in a "connection timed out" status after a while (location: India, browser: Firefox 84).

I am not sure if this is the best place to report the issue (since it seems like a problem with the host and not with this repository). But thought I would open this as a record to inform the relevant parties. If it has migrated to another site that I am not aware of, please let me know. Until then, I will try to build the docs locally and use that.

**Comment by oliveralka** [comment]
Hello @saifulbkhan, 

thank you very much for letting us know!
 
Unfortunately, we currently have problems with our infrastructure and are working on the issue. 

As you already stated people in need are welcome to use the local HTML version of the documentation.

The documentation can usually be found at the following locations:

Installed:
```OpenMS-2.6.0/share/doc/index.html```

Compiled:
```openms_build/doc/index.html```

**Comment by timosachsenberg** [comment]
should be fixed now

**Comment by saifulbkhan** [comment]
It is working. Thanks!
