### ISSUE TITLE
The link to the latest release appears to be dead.

### ISSUE THREAD

**Issue by Rooster17678** [OpenMS/OpenMS#5139]
The link: [https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/2.6.0](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/2.6.0) times out.

**Comment by oliveralka** [comment]
Thanks for pointing that out!
We currently have problems with our infrastructure and are working on the issue.

**Comment by oliveralka** [comment]
Should be working again!
