### ISSUE TITLE
get rid of Seqan1,2,3

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#5151]
currently, we are using Seqan1, which serves us well (but does not support all amino acids, which would be nice, see https://github.com/OpenMS/OpenMS/issues/1313), but its not compatible to C++17, which we will switch to shortly.
Thus, we will need to ship a patched version of Seqan1 to keep OpenMS running (not ideal).

Switching to Seqan2 is not easily possible, since its FASTA Reader cannot read from arbitrarily named files (they must be named `.fasta`, which is a showstopper, see https://github.com/seqan/seqan/issues/2054).

Switching to Seqan3 is not possible, since it required C++20, which we do not want to support (yet), for many reasons (mostly availability on platforms).

So: reimplementing the few things we actually need from Seqan seems a good way forward:
We need:
 - fast(a|q)-reader
 - Sequence-alignment 
 - a trie structure (actually just a table, i.e. 2D matrix) for Aho-corasick in PeptideIndexer

**Comment by timosachsenberg** [comment]
just an idea:
we currently use
```
#include <seqan/index.h>
#include <seqan/align.h>
#include <seqan/graph_align.h>

#include <seqan/basic.h>
#include <seqan/stream.h>
#include <seqan/seq_io/guess_stream_format.h>
#include <seqan/seq_io/read_fasta_fastq.h>
```
We could use one of the existing tools that create a single header file from these headers to get something we could include like we do for msnumpress. That way we would remove that dependency from contrib but still have something that we can ship until fully replaced?

**Comment by cbielow** [comment]
sounds like a good solution!

**Comment by mr-c** [comment]
Some additional urgency here: SeqAn 1 has been removed from Debian which affects the openms package https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982567

**Comment by timosachsenberg** [comment]
A quick attempt with existing tools didn't work out well. Seqan seems to be to complex for them.

**Comment by jpfeuffer** [comment]
Also seqan is not c17 compatible in conda, so our conda package will not be updateable until we found a solution.

**Comment by timosachsenberg** [comment]
ok I think the low hanging fruit would be to get stuff running by including seqan similar to MSNumpress  and fix the C17 issues.
And in a second step hopefully get rid of it.

**Comment by jpfeuffer** [comment]
TODO after #5214:
  - [ ] Check documentations
  - [ ] Check dockerfiles
  - [ ] Check conda dependencies

**Comment by timosachsenberg** [comment]
I reopen because we still need to get rid of seqan in the source tree and there was some nice progress.

**Comment by cbielow** [comment]
https://github.com/OpenMS/OpenMS/pull/5776 allows to remove seqan entirely now

**Comment by cbielow** [comment]
done in #5779
