### ISSUE TITLE
FeatureFinderMetaboIdent spectrum type

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5165]
Does FFMI require centroided spectra? Did not find it in the documentation.

**Comment by hendrikweisser** [comment]
It should work with either, so no requirement. Just uses OpenSWATH underneath for chromatogram extraction.

**Comment by cbielow** [comment]
maybe it's worth to explicitly mention that in the docs?

**Comment by timosachsenberg** [comment]
will add
