### ISSUE TITLE
KNIME AccurateMassSearch mass_error_value not taken correctly

### ISSUE THREAD

**Issue by sonial** [OpenMS/OpenMS#5175]
Hi all,

I have been using the AccurateMassSearch node in my pipeline for a long time with no issues, but yesterday I noticed that the resulting annotations fall outside the ppm error value defined in the dialogue.

More specifically, I normally use mass_error_value = 10 and mass_error_unit = ppm, but the annotations go up to 20-30 ppm!
I also tried to change the mass error value using a flow variable, but the result did not change.

I am currently working on win10, KNIME 4.3.1, OpenMS nodes v2.6.0.202009301213, OpenMS v2.6.0, but the issue did not seem to occur on my old win10 pc with KNIME and OpenMS 2.1

Any idea why this is happening?

Thanks,
Sonia

**Comment by oliveralka** [comment]
Hi Sonia, 

sorry for the late reply!

Could you share some example data with us, that we can try to reproduce the problem? 

Thanks,
Oliver

**Comment by sonial** [comment]
Hi Oliver,

in the attached [AccurateMassSearch_test.zip](https://github.com/OpenMS/OpenMS/files/6043677/AccurateMassSearch_test.zip) you'll find the input edta, output both as mzTab and converted to csv, and the node std output. 
In this example I used the HMDB and adduct files provided with OpenMS, and the following parameters:

AccurateMassSearch
- version = 2.6.0
- log =
- debug = 0
- threads = 1
- no_progresss = false
- force = false
- test = false

Algorithm
- mass_error_value = 10.0
- mass_error_unit = ppm
- ionization_mode = positive
- isotopic_similarity = false


- use_feature_adducts = false
- keep_unidentified_masses = true

MzTab

- exportIsotopeIntensities = false

De let me know if I can help you in any other way!
Sonia

**Comment by FabianAicheler** [comment]
Hi Sonia,

we think that the problem occurs only with proposed candidate complexes of multiple compounds M (i.e. you should always see assumed modifications like "2M+H;1+", (with adducts not being consequential, the important part being the 2M, 3M, etc).

We're in the process of investigating exactly how this happens. Currently, it seems that the search window gets relaxed/multiplied by the amount of assumed Ms', causing such candidates like 2M+.. with absolute ppm errors <= 20

**Comment by sonial** [comment]
Thanks for the update Fabian!

I removed the wrong annotations by adding a row filter, but I'd be happy to try a new solution once you have it.

Cheers,
Sonia
