### ISSUE TITLE
How could I add user-defined RNA digestion enzyme?

### ISSUE THREAD

**Issue by mhjc01** [OpenMS/OpenMS#5182]
I would like to change the NASE module parameter which is an RNA digestion enzyme such as 'RNase T1'. 

If I want to add other enzymes, for example, like colicinE5(G|U) and mazF(N|ACA), from which file should I modify?

Thank you.

**Comment by jpfeuffer** [comment]
Hi,

This would be:
https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/CHEMISTRY/Enzymes_RNA.xml

**Comment by mhjc01** [comment]
Thank you for replying.

I could add the enzymes to `share/OpenMS/CHENISTRY/Enzymes_RNA.xml`.

And I want to share my implementation for your interest.

``` xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<PARAMETERS>
  <NODE name="Enzymes">
    <NODE name="mazF">
      <ITEM name="Name" value="mazF" type="string" />
      <ITEM name="RegEx" value="(?&lt;=ACA)" type="string" />
      <ITEM name="RegExDescription" value="mazF cuts before ACA." type="string" />
      <ITEM name="CutsAfter" value=".*(?!m)$" type="string" />
      <ITEM name="CutsBefore" value="ACA" type="string" />
      <ITEM name="ThreePrimeGain" value="p" type="string" />
      <ITEM name="FivePrimeGain" value="" type="string" />
    </NODE>
    <NODE name="colicin_E5">
      <ITEM name="Name" value="colicin_E5" type="string" />
      <ITEM name="RegEx" value="(?&lt;=G)U" type="string" />
      <ITEM name="RegExDescription" value="colicin E5 cuts after G followed by U." type="string" />
      <ITEM name="CutsAfter" value="G(?!m)" type="string" />
      <ITEM name="CutsBefore" value=".*" type="string" />
      <ITEM name="ThreePrimeGain" value="p" type="string" />
      <ITEM name="FivePrimeGain" value="" type="string" />
    </NODE>
     ...
  </NODE>
</PARAMETERS>
```

**Comment by timosachsenberg** [comment]
@poshul  would it make sense to add it to our default enzymes?

**Comment by poshul** [comment]
@timosachsenberg  yup, I will add them.

**Comment by poshul** [comment]
I've added the enzymes to our defaults and submitted a PR, thanks @mhjc01!

**Comment by poshul** [comment]
Also, for anyone who adds enzymes in the future, be aware that if you have both an installed OpenMS instance, and the development instance, the Enzymes_RNA.xml file may be read from the installed package first (likely depending on how your PATH is ordered).

**Comment by poshul** [comment]
As a heads up to @mhjc01 , I just found out that the mazF parsing fails due to how we implemented the digestion code. I've opened a issue https://github.com/OpenMS/OpenMS/issues/5215
