### ISSUE TITLE
[BUILD ERROR] - Compiling OpenMS on macOS 10.15.4 fails with contrib package

### ISSUE THREAD

**Issue by ahmedskhalil** [OpenMS/OpenMS#5183]
Building OpenMS with [macOS/10.15.4/x64/appleclang-11.0.0/contrib_build](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/contrib/macOS/10.15.4/x64/appleclang-11.0.0/contrib_build.tar.gz) fails due to `'auto_ptr` being deprecated : 

`/Users/distiller/OpenMS/contrib_build/include/seqan/basic/test_system.h:92:10: error: no template named 'auto_ptr' in namespace 'std'
    std::auto_ptr<Test> instance;`

Has seqan been built using different standard lately? We're attempting to build OpenMS with C++14 and that has worked out well so far.

**Comment by jpfeuffer** [comment]
Yes you need to "rebuild" seqan in the contrib. It had to be changed for c17.

**Comment by jpfeuffer** [comment]
See also #5151 and related contrib PR.

**Comment by ahmedskhalil** [comment]
Worked by changing it to `unique_ptr<Test>`.
