### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5184]
Hi,

I am trying to load mzML files with 500MB approximate size and I am constantly getting this segmentation fault error. However, when I use smaller files, this doesn't occur and my workflow runs as it is supposed to. This is not a memory issue since I am using a machine that has a lot of space. Is this a c++ error? 

import numpy as np
import pandas as pd
import pyopenms
from pyopenms import *

exp = MSExperiment()

import sys
print("Loading")
MzMLFile().load(sys.argv[1], exp)
print("Loaded")

**Comment by jpfeuffer** [comment]
Hi,

Yes, this is an error from the underlying C++ code. But I cannot say if it is an error in the code or in your file.
Can you upload one of the failing mzML files?

**Comment by eeko-kon** [comment]
Hi. So it just got fixed , at least with one of the files. This is very weird to me so hear this out: I am converting all my files through msconvert on my bash shell. I also thought that it could be a problem with the file this time since we are talking about MSMS spectra of a standard compound. So I added the .raw files to the msconvert software directly (application) and I got files of 200MB size this time. Pyopenms doesn't crash now.

**Comment by eeko-kon** [comment]
Are you having the same issues? What is the best way to convert raw data to mzML? Is mgf better?

**Comment by jpfeuffer** [comment]
With "application" you mean the application with the user interface? It might well be that the user interface has some different defaults than the command-line tool but in theory this should not produce invalid mzMLs.
However, we heard about similar problems before. If you want, you could upload the fixed file and the failing file and we have a look at the differences.

**Comment by eeko-kon** [comment]
Yes, I mean UI. I see. I am trying to upload the files here but it says that GitHub doesn't support the file type (mzML). I will create a repository and invite you. Is that the easiest?

**Comment by jpfeuffer** [comment]
Yes, or upload it to a trusted hosting service of your choice and paste or send me a link.

**Comment by eeko-kon** [comment]
Even if I compress them, they are too big to upload. :S

**Comment by eeko-kon** [comment]
https://drive.google.com/drive/folders/1yfbZ2SjfFS02Yeq1maFgktZcNR-IpOn2?usp=sharing

**Comment by jpfeuffer** [comment]
Hi! Sorry, took some time until I got to it.
It seems like your Standard_sample.mzML contains empty wavelength arrays which do confuse our reader (many warnings) but actually do not lead to an error when running it through the C++ part of the code.
The other mzML however does not contain those arrays, so there must be some implicit difference between the two ways in which you are calling/running msconvert.
I will have a look if I can reproduce the Segmentation fault in python.

**Comment by eeko-kon** [comment]
You are correct that those files differ a bit because they were ran with different methods (either MS1 and MS2 profile data or MS1 profile and MS2 centroid). I only realized it recently. However, I corrected the -what I thought was- the issue (msconvert) but the seg fault still persists. I am in contact with Oliver also, trying to understand what the problem is. It comes up exactly at the command sirius.store(...) . I m still trying to figure out what is happening. Thanks for helping out!

**Comment by jpfeuffer** [comment]
Ah I see. Okay then it is not directly an error during parsing probably. But it could be that if those -- let's say "irregular" -- wavelength spectra are tried to be accessed that something (unexpected) is going wrong there.

**Comment by eeko-kon** [comment]
Yes I can see that if I open both mzml files (the ones I sent you vs the ones I have now), the ones I sent you have a lot of non readable data. The "fixing" was primarily because I was converting them wrongly (centroid MS1 when it was already centroid) plus for some reason, all the Thermo files have negative intensities, which Oliver noticed and we had to use also FileFilter from openMS to get rid of the negative ones. Still, whatever we do, there's the seg fault that persists in the sirius.store function. Thank you so much for helping! I can also add you in the repository.

**Comment by oliveralka** [comment]
Regarding the segfault in the `sirius.store()` function. 
Everything works on the C++ side when using the tools either with bash or KNIME. So my best guess is that there is either something wrong with the currently python script or with the SiriusMSFile.pxd (python wrapper.)

**Comment by jpfeuffer** [comment]
@hroest Do you know why in `item2.inst = shared_ptr[_FeatureMap](new _FeatureMap(deref(it_v_fp)))` a new memory location is allocated, instead of copying the shared_ptr and increasing its "usage count"?

**Comment by jpfeuffer** [comment]
Although your wrapping of the pointers is by far the better solution, I took the liberty to change autowrap to only initialize additional list elements and re-use memory for the rest. Might lead to less errors and a little bit more speed in general.
https://github.com/uweschmitt/autowrap/pull/100
