### ISSUE TITLE
Nightlies fail

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5189]
1) @oliveralka New abibuilder8 has no signing information yet, therefore the signing target does not work.
solutions:
 - Add signing info
 - Make signed_dist target fall back to normal dist if not present
 - exclude abibuilder as nightly agent

2) Gcc on our linux too old. upgrade.

**Comment by oliveralka** [comment]
@jpfeuffer 
1) Is there more to it than adding the "SIGNING_IDENTITY" variable to the agent?

**Comment by oliveralka** [comment]
http://cdash.openms.de/viewBuildError.php?buildid=115649

**Comment by jpfeuffer** [comment]
I saw it. I think NSIS might be missing for building the installer.

**Comment by oliveralka** [comment]
edit: http://cdash.openms.de/viewBuildError.php?buildid=115649

Yes, but that was on "experimental", in nightly it seems to have worked.

The Linux machines are docker only, or? 
Which gcc version do you think should they have?

**Comment by jpfeuffer** [comment]
Everything needs gcc7+ now. Timo just upgraded some of them (18.04).
Yes somehow "Packaging" and "KNIME" is categorized to experimental. This is normal but they are nightlies too.

**Comment by jpfeuffer** [comment]
Still failing due to new Ubuntu containers not supporting trace.

**Comment by jpfeuffer** [comment]
Seems like LSAN is just completely broken recently. Half a dozen related reports on the repo:
https://github.com/google/sanitizers/issues/1170

We should try the workaround often described otherwise, we need to disable it.

`ASAN_OPTIONS=intercept_tls_get_addr=0`

**Comment by jpfeuffer** [comment]
Also regarding Windows packaging on the new machine @oliveralka :
```
CUSTOMBUILD : CPack error : Problem running NSIS command: "C:/ProgramData/NSIS/Bin/makensis.exe" "/.../build/_CPack_Packages/win64/NSIS/project.nsi" [C:\jenkins\ws\openms\ntly\TstPkg\9447518b\build\dist.vcxproj]
  Please check /.../build/_CPack_Packages/win64/NSIS/NSISOutput.log for errors
CUSTOMBUILD : CPack error : Problem compressing the directory [C:\jenkins\ws\openms\ntly\TstPkg\9447518b\build\dist.vcxproj]
CUSTOMBUILD : CPack error : Error when generating package: [C:\jenkins\ws\openms\ntly\TstPkg\9447518b\build\dist.vcxproj]
```

**Comment by oliveralka** [comment]
`C:\jenkins\ws\openms\ntly\TstPkg\9447518b\build\dist.vcxproj` looks already fishy. 
jenkins is on E: on this windows machine.

**Comment by jpfeuffer** [comment]
Ah yes, sorry forgot to mention. Maybe even the LongString NSIS is needed. Let's see. Did we document how to setup NSIS?

**Comment by oliveralka** [comment]
I actually have not found any documentation regarding the setup of a windows agent and the NSIS setup.
Only the template: https://github.com/OpenMS/OpenMS/blob/55598cf39c73a2092365fbdb51e63defa9b29c6f/cmake/Windows/NSIS.template.in

**Comment by oliveralka** [comment]
http://cdash.openms.de/buildSummary.php?buildid=122681#!#Build
Still an issue with NSIS

**Comment by jpfeuffer** [comment]
Yes, short-term we can revert the version or patch the ".nsh" but long-term switching to the new EnvVarUpdate plugin is the way to go.

**Comment by jpfeuffer** [comment]
New error: the Windows debug builds still run on VS2017. We just need to update the label.
