### ISSUE TITLE
Links to documentation not up to date

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#5194]
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/index.html
Developer Python Quickstart Guide (online) links to 2.4.0 documentation instead of latest.

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/public/Main.doxygen#L103

**Comment by jpfeuffer** [comment]
Might be cool to use a variable I guess. So it points to the same version.

**Comment by cbielow** [comment]
> 
> 
> Might be cool to use a variable I guess. So it points to the same version.

that only works if there is a pyopenms release. right now, there is no 2.6 release. so the link would be dead (which is somewhat worse than outdated, i guess? )
