### ISSUE TITLE
PyOpenMS/TOPPView failing to load Orbitrap data via ms-convert without first santizing with FileConverter (mzml to mzml)

### ISSUE THREAD

**Issue by C-Townsend** [OpenMS/OpenMS#5201]
Hello,

I've been using ms-convert 3.0.20140-aaf841559 to convert thermo raw files from our Orbitrap LCMS. This works fine for the pymzml Python package (and the MzMine viewer program) but TOPPView and PyOpenMS crash when attempting to load them. Running them through FileConverter as mzml input to mzml output allows them to be loaded, but I'd like to be able to use them directly without having to call FileConverter via subprocess.

I'm on Ubuntu 20.04.2 using OpenMS 2.6.0 installed via the .deb file and PyOpenMS 2.6.0 installed with pip.
Here's a [google drive link](https://drive.google.com/file/d/1KfkdzznBuLYiElxc4Gq4vzrDtSLhc5VS/view?usp=sharing) to an mzml file demonstrating this problem (the diagnostics below are on this file).

The following code results in a "free(): double free detected in tcache 2" error using the linked mzml file:
`from pyopenms import * `
`options = PeakFileOptions()`
`options.setMSLevels([1])`
`fh = MzMLFile()`
`fh.setOptions(options)`
`input_map = MSExperiment()`
`fh.load(fpath, input_map)`

where _fpath_ is the absolute path to the mzml file in question. The latest version of ms-convert produces identical behavior.
Both conversions show the following error with FileInfo -v:
#
-- General information --

File name: T25MIX_Std_1.mzml
File type: mzML

Validating mzML file against XML schema version 1.1.0
Validation error in file 'T25MIX_Std_1.mzml' line 60 column 25: element 'detector' is not allowed for content model '(source+,analyzer+,detector+)'
Failed - errors are listed above!

Semantic validation is not performed due to previous errors!
FileInfo took 2.25 s (wall), 2.24 s (CPU), 0.09 s (system), 2.15 s (user); Peak Memory Usage: 40 MB.
#
Using an older version of ms-convert (3.0.10) seems to only result in further problems. The resulting mzml files validate semantically but result in many errors resembling a line reading offset mismatch for all spectra in the file, which seems to be caused by some problem with a processingMethod term.

I have thus far found no combination of ms-convert versions or parameters that produces mzml files palatable to OpenMS from my Orbitrap data without first passing through FileConverter, so any suggestions would be appreciated!

**Comment by timosachsenberg** [comment]
Sounds a bit like it could be an error in msconvert?
you could try options.setSkipXMLChecks(true) at least in pyOpenMS

**Comment by timosachsenberg** [comment]
```
    <instrumentConfigurationList count="2">
      <instrumentConfiguration id="IC1">
        <referenceableParamGroupRef ref="CommonInstrumentParams"/>
        <componentList count="4">
          <source order="1">
            <cvParam cvRef="MS" accession="MS:1000073" name="electrospray ionization" value=""/>
            <cvParam cvRef="MS" accession="MS:1000057" name="electrospray inlet" value=""/>
          </source>
          <analyzer order="2">
            <cvParam cvRef="MS" accession="MS:1000081" name="quadrupole" value=""/>
          </analyzer>
          <analyzer order="3">
            <cvParam cvRef="MS" accession="MS:1000484" name="orbitrap" value=""/>
          </analyzer>
          <detector order="4">
            <cvParam cvRef="MS" accession="MS:1000624" name="inductive detector" value=""/>
          </detector>
        </componentList>
        <softwareRef ref="Xcalibur"/>
      </instrumentConfiguration>
      <instrumentConfiguration id="IC2">
        <referenceableParamGroupRef ref="CommonInstrumentParams"/>
        <componentList count="1">
```
error:
```
          <detector order="1">  
            <cvParam cvRef="MS" accession="MS:1000621" name="photodiode array detector" value=""/>
          </detector>
        </componentList>
        <softwareRef ref="Xcalibur"/>
      </instrumentConfiguration>
    </instrumentConfigurationList>
```

**Comment by timosachsenberg** [comment]
Another option to try would be to use FileConverter to convert the raw file to mzML.
This requires mono or .NET installed on the computer though.

**Comment by C-Townsend** [comment]
Thanks for the suggestions.

options.setSkipXMLChecks(true) reproduced the double free error.

Converting with FileConverter and ThermoRawFileParser produces functional mzml files but removes all UV data (may not be an issue). Ideally all scan types would be preserved. Are any other data types stripped by this conversion? 

The UV data registers as MSLevel 1 and ScanMode 12 (electromagnetic) in sanitized msconvert-generated mzml files, which is possibly a different kind of incorrect.

**Comment by jpfeuffer** [comment]
According to the mzML standard, there has to be at least one entry for source, analyzer and detector for each instrumentConfiguration so I think your mzML is not valid.
```
  <xs:complexType name="ComponentListType">
    <xs:annotation>
      <xs:documentation>List with the different components used in the mass spectrometer. At least one source, one mass analyzer and one detector need to be specified.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="source" type="dx:SourceComponentType">
        <xs:annotation>
          <xs:documentation>A source component.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element maxOccurs="unbounded" name="analyzer" type="dx:AnalyzerComponentType">
        <xs:annotation>
          <xs:documentation>A mass analyzer (or mass filter) component.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element maxOccurs="unbounded" name="detector" type="dx:DetectorComponentType">
        <xs:annotation>
          <xs:documentation>A detector component.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="count" type="xs:nonNegativeInteger" use="required">
      <xs:annotation>
        <xs:documentation>The number of components in this list.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
```

TRFP probably does not support electromagnetic scan types yet and omits them. I cannot say how complete TRFP is with the rest of the scan types.

**Comment by C-Townsend** [comment]
Will do. Thanks for the help!
