### ISSUE TITLE
ProteomicsLFQ exits with segfault *in the end* when experimental design numbering is not correct

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5224]
I.e. not consecutive or not starting from 1.
We have seen cases where it worked but this was probably lucky.
This needs to be safer. And even if it cant be made much safer since we need to assume that ordering, then we need to check very carefully and very early, already during reading, or better the construction of an experimental design object.

**Comment by timosachsenberg** [comment]
yes probably best to put test into experimental design class
