### ISSUE TITLE
FFM Request: peak height

### ISSUE THREAD

**Issue by rickhelmus** [OpenMS/OpenMS#5232]
Hi guys,

Currently the `FeatureFinderMetabo` tool reports the feature intensity as the peak area. I was wondering if it would be possible to _also_ include the peak height for each feature? I'm currently loading this from the data files afterwards, but I feel this could be done much more efficient if this data was already available in the `featureXML` files.

Thanks,
Rick

**Comment by jpfeuffer** [comment]
Hey!
Do you mean having multiple quantities and one "main" quantity?
Because FFM already has a setting: 
`mtd:quant_method` which can be one of "area, median, max_height"

**Comment by FabianAicheler** [comment]
So from my understanding, the combination of report_summed_ints='false' and mtd:quant_method='max_height' should return the max peak of the monoisotopic trace.

So as @jpfeuffer said, the question becomes whether the requested features is about this (should already be possible), or about changing the reporting to include multiple intensity types in the same file.

**Comment by rickhelmus** [comment]
Hi guys,

Thanks for the quick replies!

Strange, I completely missed that option! In any case, my request is indeed to have _both_ values (peak area and max intensity).

**Comment by timosachsenberg** [comment]
Hi, I added a PR that now always annotates the maximum height of all isotopic peaks.
Should be available in our nightly builds as well
