### ISSUE TITLE
Sirius parameters 

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5255]
I am trying to change some parameters to get correct results from SiriusAdapter and I noticed that there are a few that don't work in pyOpenMS:

 -sirius:elements_considered     Set the allowed elements for rare element detection. 
                                                       Write SBrClBSe to allow the elements S,Br,Cl,B and
                                                       Se.
  -sirius:elements_enforced        Enforce elements for molecular formula determination. 
                                                       Write CHNOPSCl to allow the elements C, H, N, O, P, S
                                                       and Cl. Add numbers in brackets to restrict the minima
                                                       l and maximal allowed occurrence of these elements:
                                                       CHNOP[5]S[8]Cl[1-2]. When one number is given then it
                                                       is interpreted as upper bound. Default is CHNOP
  -sirius:db                                    Search formulas in given database. (default: 'all' 
                                                       valid: 'all', 'pubchem', 'mesh', 'hmdb', 'knapsack',
                                                       'chebi', 'pubmed', 'bio', 'kegg', 'hsdb', 'maconda',
                                                       'metacyc', 'gnps', 'zincbio', 'train', 'undp', 'pantcy
                                                       c', 'ymdb', 'keggmine', 'ecocycmine', 'ymdbmine', 'cus
                                                       tom', 'custom_0', 'custom_1', 'custom_2', 'custom_3',
                                                       'custom_4')

I cannot change the elements. For example: I don't want to consider F,P and B for example and I am calling:

sirius_algo_par = sirius_algo.getDefaults()
sirius_algo_par.setValue("sirius:elements_enforced", "CHNO") or sirius_algo_par.setValue("sirius:elements_enforced", "CHNOP[5]Cl[1-2]B[0]F[0]")
sirius_algo.setParameters(sirius_algo_par)

and I am still getting "weird" formulas with multiple borons, fluorines, sulfurs, etc.

Also, sirius:db cannot accept more than two databases (if I don't want to use "all" but only gnps and pubchem it works , but if I add also pubmed or any other, it crashes).

**Comment by oliveralka** [comment]
Hi @eeko-kon , 

could you please test that on the KNIME/C++ side as well and let me know if it works there? 

Maybe you could add a minimal example for testing to your github. 

Then I will take a look!

**Comment by oliveralka** [comment]
I had a look at the `sirius:elements_enforced` parameter. The parameter is correctly forwarded to SIRIUS. 
Command given to SIRIUS: 
```
sirius --processors=2 --input /private/var/folders/t7/x82jn_jd09vc_hlq_sqs2jlw0000gn/T/20210329_094156_Olivers-MBP.fritz.box_94098_2.ms --project /private/var/folders/t7/x82jn_jd09vc_hlq_sqs2jlw0000gn/T/20210329_094156_Olivers-MBP.fritz.box_94098_1/sirius_out sirius --db=all **--elements-enforced=CHNOP[5]Cl[1-2]B[0]F[0]** --tree-timeout=0 --candidates=2 --profile=orbitrap --ppm-max=10.0 --compound-timeout=100 --ppm-max-ms2=10.0 --ions-considered=[M+H]+
```

You can also try to use SIRIUS directly and see if there is a difference. If the parameter does not work as intended, you should contact the SIRIUS team in Jena. If you give me an example (.ms), the command as .sh (see above), the mzTab output. I can also forward that to the developers.  

In terms of databases. It seems that there is an error when parsing. In the previous version, only one database was given. Now you can add multiple ones. This has to be changed - Nice catch! :)

**Comment by eeko-kon** [comment]
Hey @oliveralka ! Thanks again for the help:D 

The parameter is correctly forwarded to sirius indeed, but the results I am getting are the same before and after the parameters. I am uploading the files to my repository now :) I tried with SIRIUS GUI so far and I am getting the correct data - when choosing different elements, it works very well. I ll also upload that one so that you can see the difference.

**Comment by oliveralka** [comment]
Hm, maybe there is something wrong with the command-line version of SIRIUS? Could you please try the THIRDPARTY sirius 4.6.2 version with your data and the .ms file from the command line? And see if there is a difference in the output.

**Comment by eeko-kon** [comment]
Can you copy the part that predicts the mass 183.10...? :)

**Comment by oliveralka** [comment]
I just used a SIRIUSAdapter_test file for the test, so I do not have your masses/formulas available - sorry.

**Comment by eeko-kon** [comment]
No worries! 

Ok so when I feed sirius either from GUI or THIRDPARTY with the mzml file, I am getting the correct hit:


C10H14O3	[M + H]+	C10H14O3	157.4542845500138	156.1407650768085	1.313519473205294	26	0.464969785761992	12.385322940132744	12.385322940132744	-9.574994459669293	183.0998175803516	525.181	27_20201204_DR_UMETAB169_EEK_POS_GermicidinBstandar_2845

**Comment by oliveralka** [comment]
Could you always add the file you are using to your standards directory in your github, then I can reproduce it far easier.

**Comment by eeko-kon** [comment]
Ok so I See your point. The results seem to be consistent when I use FeatureFinder , etc in KNIME with the results I am getting in my workflow. But when I just feed Sirius with only the mzml file, I am actually getting the right data... :S

**Comment by oliveralka** [comment]
The mzML, or the .ms file?

**Comment by eeko-kon** [comment]
.mzml

**Comment by oliveralka** [comment]
As a reference, it seems to be a combination of feature detection (FFM) parameters and `--elements-enforced=CHNOP[5]Cl[1-2]B[0]F[0]`. Changing both resulted in the correct identification at rank 1.

**Comment by eeko-kon** [comment]
Let me try a few things and I will get back to you. I am uploading the standard file.
