### ISSUE TITLE
mzTAB export fails after merging multiple fractions

### ISSUE THREAD

**Issue by oliverschilling** [OpenMS/OpenMS#5257]
When merging multiple fraction (consensusxml; collect->FileMerger-> MzTabExporter), I get the foloiwng error message:  "Error: Unexpected internal error (PSM controllerType=0 controllerNumber=1 scan=18249 does not map to an MS file registered in the quantitative metadata. Check your merging and filtering steps and/or report the issue, please.)" 

I think that this problem has been previously reported - has there been any progress?

Thanks

**Comment by jpfeuffer** [comment]
Hi!
Can you try to set the append_method in FileMerger to "append_cols", or is it set this way already?
The default "append_rows" more or less assumes that the files come from the same MS run which could lead to problems here.

**Comment by oliverschilling** [comment]
Thanks; that solved it. Would it be possible to add this explanation to the tool?
