### ISSUE TITLE
add --abort_on_alignment_failure set by default to true to MapAlignment tools [526]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#526]
Submitted by witek96 on 2013-05-11 19:43:30

Currently both MapAligment tools abort if the number of points to fit a model is'nt sufficient. Introduce an option  --abort_on_alignment_failure  default true, so this behaviour could be disabled if option set to false.

**Comment by hendrikweisser** [comment]
There's no justification for why this would be needed and no activitiy in five years. Closing this issue.
