### ISSUE TITLE
SiriusAdapter issues

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5278]
Hello :)

I ve been using a few files from standards (compounds that are pure) to validate the workflow:
FFM - MetaboAdductDecharger and then SiriusAdapter 
and I would get the desired results. Now I m trying to check whether the workflow can handle larger datasets, so I am using a larger file with basically very typical crude extract LC-MS data from Streptomyces. I know what this strain is producing. When I directly insert the mzML file to SIRIUS GUI, it can detect the peaks (however, it predicts the formulas a bit off). When I run them with the pyopenms workflow, I am not getting any of the expected peaks (561.3604 , 797.4214 ) even though I can clearly detect them in the deconv.featureXML file. I also played around with the parameters using ToppView and then fed the FeatureXML file to SiriusAdapter nightly version but I am getting an error :

Error: Unexpected internal error (Could not convert non-integer DataValue to unsigned int)
Error occurred in line 535 of file /Users/builder/jenkins/ws/openms/ntly/TstPkg/87227eb0/source/src/openms/source/DATASTRUCTURES/DataValue.cpp (in function: unsigned int OpenMS::DataValue::operator unsigned int() const) !
[Scollinus.zip](https://github.com/OpenMS/OpenMS/files/6294459/Scollinus.zip)

I'll send you the files zipped

**Comment by eeko-kon** [comment]
Also, another general question is: why am I getting mass traces with so many decimals from FFM? e.g.:
mz 297.963010538224467
Is that normal?

**Comment by eeko-kon** [comment]
Another question :D Sorry for the spam: TextExporter- is there a pyOpenms function?

**Comment by oliveralka** [comment]
Hi @eeko-kon,

could you please let me know how exactly you processed the mzML, to construct the featureXML? Did you manually add a additional feature. 

It seems there is an error in the featureXML file. 
Usually a feature looks like this: 
The UserParam have different types e.g. `num_of_masstraces` should be `int`.
```
		<feature id="f_14106453246400956269">
			<position dim="0">369.97272504</position>
			<position dim="1">584.338147972508523</position>
			<intensity>5.813745e06</intensity>
			<quality dim="0">0.0</quality>
			<quality dim="1">0.0</quality>
			<overallquality>9.498014e-05</overallquality>
			<charge>1</charge>
			<UserParam type="string" name="label" value="T1169_T1791.2"/>
			<UserParam type="float" name="FWHM" value="4.198156356811523"/>
			<UserParam type="int" name="num_of_masstraces" value="2"/>
			<UserParam type="floatList" name="masstrace_intensity" value="[5.813744933621427e06, 1.112300725914833e06]"/>
			<UserParam type="floatList" name="masstrace_centroid_rt" value="[369.97272504, 369.97272504]"/>
			<UserParam type="floatList" name="masstrace_centroid_mz" value="[584.338147972508523, 585.342083889000719]"/>
			<UserParam type="floatList" name="isotope_distances" value="[1.003935916492196]"/>
			<UserParam type="int" name="legal_isotope_pattern" value="-1"/>
		</feature>
```
One feature shows has the type `string` for all `UserParams`, due to that SiriusAdapter::preprocessing fails, since it awaits and different type for `num_of_masstraces`. 
```
                 <feature id="f_9320142221925562649">
			<position dim="0">291.604524672000025</position>
			<position dim="1">585.328829848481973</position>
			<intensity>1.46324e08</intensity>
			<quality dim="0">0.0</quality>
			<quality dim="1">0.0</quality>
			<overallquality>2.623158e-03</overallquality>
			<charge>1</charge>
			<UserParam type="string" name="label" value="T44_T179_T796"/>
			<UserParam type="string" name="FWHM" value="2.986996173858643"/>
			<UserParam type="string" name="num_of_masstraces" value="3"/>
			<UserParam type="string" name="masstrace_intensity" value="[1.463240065474621e08, 3.715824984046559e07, 7.769145114697459e06]"/>
			<UserParam type="string" name="masstrace_centroid_rt" value="[291.604524672000025, 291.604524672000025, 291.604524672000025]"/>
			<UserParam type="string" name="masstrace_centroid_mz" value="[585.328829848481973, 586.3305927435066, 587.334047956180257]"/>
			<UserParam type="string" name="isotope_distances" value="[1.001762895024626, 1.003455212673657]"/>
			<UserParam type="string" name="legal_isotope_pattern" value="-1"/>
		</feature>
```

**Comment by eeko-kon** [comment]
[Scollinus 2.zip](https://github.com/OpenMS/OpenMS/files/6313267/Scollinus.2.zip)
Oliver, 

I attached the parameters.ini file too. There shouldn't be a "string" issue now.

**Comment by eeko-kon** [comment]
With the parameters I have through pyOpenMS, sirius recognizes 54 features. But it skips this one: (why??) Shouldn't it pass all parameters?

`		</feature>
		<feature id="f_861700408266386759">
			<position dim="0">493.597315231980019</position>
			<position dim="1">797.436959805664969</position>
			<intensity>1.600522e07</intensity>
			<quality dim="0">0.0</quality>
			<quality dim="1">0.0</quality>
			<overallquality>3.308904e-04</overallquality>
			<charge>1</charge>
			<UserParam type="string" name="label" value="T293_T462"/>
			<UserParam type="float" name="FWHM" value="2.487667083740234"/>
			<UserParam type="int" name="num_of_masstraces" value="2"/>
			<UserParam type="floatList" name="masstrace_intensity" value="[1.600521710728969e07, 8.14029823728162e06]"/>
			<UserParam type="floatList" name="masstrace_centroid_rt" value="[493.597315231980019, 493.597315231980019]"/>
			<UserParam type="floatList" name="masstrace_centroid_mz" value="[797.436959805664969, 798.43893893859331]"/>
			<UserParam type="floatList" name="isotope_distances" value="[1.001979132928341]"/>
			<UserParam type="int" name="legal_isotope_pattern" value="-1"/>
			<UserParam type="int" name="map_idx" value="0"/>
			<UserParam type="string" name="dc_charge_adducts" value="H1"/>
			<UserParam type="stringList" name="adducts" value="[[M+H]+]"/>
			<UserParam type="float" name="dc_charge_adduct_mass" value="1.0078250319"/>
			<UserParam type="int" name="is_backbone" value="1"/>
			<UserParam type="string" name="Group" value="15555270346449002845"/>`

**Comment by oliveralka** [comment]
> [Scollinus 2.zip](https://github.com/OpenMS/OpenMS/files/6313267/Scollinus.2.zip)
> Oliver,
> 
> I attached the parameters.ini file too. There shouldn't be a "string" issue now.

Thanks, now the nightly version should work without an issue - is that correct? 

> With the parameters I have through pyOpenMS, sirius recognizes 54 features. But it skips this one: (why??) Shouldn't it pass all parameters?

That depends if there is no MS2 spectrum on the monoisotopic trace in the mapping space (RT: 5 s default). It is not able to process anything since SIRIUS needs the MS2 information - you can have a look in TOPPView if that is the case. You can try to use the `feature` algorithm in the `HighResPrecursorMassCorrector` to correct the precursor annotation in regard to a feature. You can use the `adduct grouping and accurate mass search` node in the DIAMetAlyzer workflow as a reference.

**Comment by eeko-kon** [comment]
...Of course. So embarrassing, sorry Oliver! Thanks for that. I will check. I checked the raw data of course and it fragments, but not the converted in Toppview. I will try the DIAMEtAlyzer workflow yes :)

**Comment by eeko-kon** [comment]
Hi,

So I checked the fragmentation and the feature I am looking for (797) is detected in MS1 of course, but when it fragments, it looks like the parent ion is 779. So the water loss is chosen for fragmentation, instead of the M+H ion (RT is the same or very similar at least).  I am moving to a different file.

**Comment by eeko-kon** [comment]
Alright, so my persistent issues come from the fact that 
1) Almost all files from thermo have negative intensities and need filtering
2) HighResMassPrecursorCorrector is necessary in the workflow :) Will integrate it this week hopefully and test it but it works perfectly in KNIME+Sirius GUI
