### ISSUE TITLE
pyOpenMS - templated std::vector return types [528]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#528]
Submitted by hroest on 2013-05-17 09:25:52

There seems to be an issue with Cython and templated std::vector return types:

pyOpenMS/pxds/LinearInterpolation.pxd 
libcpp_vector[ValueType]  getData() 

pyOpenMS/pxds/LinearInterpolation.pxd 
libcpp_vector[ValueT] row(size_t i)
libcpp_vector[ValueT] col(size_t i)

we get the error

pyopenms/pyopenms.cpp: error: redefinition of PyObject\* __pyx_convert_vector_to_py_double(const std::vector<double>&)
    pyopenms/pyopenms.cpp: error: PyObject\* __pyx_convert_vector_to_py_double(const std::vector<double>&) previously defined here

strangely Cython defines a std::vector<double> converter twice

**Comment by hroest** [comment]
at the moment templated std::vector return is not supported to my knowledge
