### ISSUE TITLE
pyopenms featureXML

### ISSUE THREAD

**Issue by mafreitas** [OpenMS/OpenMS#5281]
I am testing Bruker's univeral feature finder to map features to data from their timsTOF Pro.  The output from this program gives feature m/z, rt, charge, intensity and mobility (plus more).  I wrote a small pyopenms script to create a featurexml using the example in the documentation. I was wondering if it is possible to add the mobility and other metadata to the featurexml.

**Comment by timosachsenberg** [comment]
Hi. That sounds a cool application of pyOpenMS.

You can add meta data e.g., 
feature.setMetaValue(b"NAME_OF_THE_CV_TERM", 50.5)

We currently use:
"ion mobility drift time"  (accession="MS:1002476")
(unit is "millisecond")

"inverse reduced ion mobility" (accession="MS:1002814")
(unit is "volt-second per square centimeter")

but we did not decide yet if using the term name or accession is better.

@hroest @enetz this is something we could decide now to make it consistent across tools / scripts.

**Comment by mafreitas** [comment]
Thanks. Once I get the mobility in the featureXML, I was hoping to pyopenms to replicate similar functionality as our current pipeline but to take advantage of the mobility to correctly assign and quantify peptides hits.  Our current pipeline is: 

IDMapper -> MapAlignerPoseClustering -> FeatureLinkerUnlabeledQT -> IDConflictResolver -> ConsensusMapNormalizer -> ProteinQuantifier

Any guidance would be helpful.  I could move that discussion to gitter.

**Comment by mafreitas** [comment]
Forgot to mention that the metadata is now in the featureXML.  One other item of note is that it always gives the warning:

FeatureXMLFile::store():  found 2615 invalid unique ids.

My featureXML looks like:

<?xml version="1.0" encoding="ISO-8859-1"?>
<featureMap version="1.9" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/OpenMS/OpenMS/develop/share/OpenMS/SCHEMAS/FeatureXML_1_9.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<featureList count="2614">
		<feature id="f_0">
			<position dim="0">920.64813232421875</position>
			<position dim="1">1221.990614235131716</position>
			<intensity>5.296032e04</intensity>
			<quality dim="0">0.0</quality>
			<quality dim="1">0.0</quality>
			<overallquality>10.0</overallquality>
			<charge>1</charge>
			<UserParam type="float" name="ion mobility drift time" value="1.257033228874207"/>
			<UserParam type="float" name="inverse reduced ion mobility" value="1.257033228874207"/>
		</feature>
               ...

At this point I added placeholders for both CV Terms.  The feature finder does not report a quality score so I just assigned a value of 10 to everything.

**Comment by timosachsenberg** [comment]
I think you can update the unique ids calling ensureUniqueId() on every feature
Is it intentional that both have the same value?
If you don't want to touch C++ I guess one way could be binning the ion mobility (similar to the MaxQuant approach) and running the algorithms separately. We have some example code in python that does that (prototyped by a student). @hroest  can we share it?

**Comment by timosachsenberg** [comment]
If you don't want to touch C++ I guess one way could be binning the ion mobility (similar to the MaxQuant approach) and running the algorithms separately. We have some prototype code in python that does that. 

github.com/chen-jy/feature-finder-im

and the maxquant paper: https://www.biorxiv.org/content/10.1101/651760v2

**Comment by mafreitas** [comment]
C++ is rusty.  The script is working great now, no warnings. I will look over the feature-im code for inspiration.  It will also serve as a comparison for Bruker's 4d uff util.

**Comment by timosachsenberg** [comment]
Haha. We would be happy if you could share some insights...
