### ISSUE TITLE
PrecursorCorrection.correctToNearestFeature

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5292]
I am trying to use PrecursorCorrection.correctToNearestFeature in pyOpenMS
`
correctToNearestFeature(...)
    Cython signature: libcpp_set[size_t] correctToNearestFeature(FeatureMap & features, MSExperiment & exp, double rt_tolerance_s, double mz_tolerance, bool ppm, bool believe_charge, bool keep_original, bool all_matching_features, int max_trace, int debug_level)
`

However, when I introduce the FeatureMap file from MetaboAdductDecharger I am getting an error:

`
TypeError: descriptor 'correctToNearestFeature' for 'pyopenms.pyopenms_6.PrecursorCorrection' objects doesn't apply to a 'pyopenms.pyopenms_4.FeatureMap' object
`
Same applies when I introduce a consensus map file and a featureXML file.

**Comment by jpfeuffer** [comment]
Thanks for reporting. Hm yes, this method seems to have been wrongly wrapped to Python

@timosachsenberg it should be declared static I guess

**Comment by timosachsenberg** [comment]
yes needs to be static. Hmm we should check why this doesn't cause autowrap to fail

https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/PrecursorCorrection.pxd
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FILTERING/CALIBRATION/PrecursorCorrection.h

**Comment by timosachsenberg** [comment]
I can fix that

**Comment by eeko-kon** [comment]
Thank you!
