### ISSUE TITLE
ID score switcher error

### ISSUE THREAD

**Issue by Maithy15** [OpenMS/OpenMS#5307]
I am trying openms for the first time and I am always getting error with the ID score switcher. It says Meta value '' not found for peptide hit with sequence 'WLVEPQIDDPNSNLEEAINEAEAITSVNSLGSK', charge 3, score 1.80488e-04). I could find a similar issue here (#2941) but in their error output, it clearly says it cannot find posterior probability score. Am I doing something wrong here?

**Comment by timosachsenberg** [comment]
Hi, can you provide the ID file? Has this been generated by a search engine?
Best, Timo

**Comment by Maithy15** [comment]
Thanks for the quick reply! yes it is generated from mgsf+ but passes through peptide indexer, psm feature extractor, ID merger, Percolator adaptor then to the ID score switcher. When I set the score type in Percolator as pep and new_score in ID score switcher as pep I get the same error Meta value 'pep' not found for peptide hit with sequence 'GGSQAGGSGSAGQYGSDQQHHLGSGSGAGGTGGPAGQAGR', charge 4, score 7.321120000000001e-11. The idxml files are too large to upload.

**Comment by Maithy15** [comment]
I was able to get a .txt output from the percolator. Please find the attached files.
[M10_Rest_Pellet_1926.txt](https://github.com/OpenMS/OpenMS/files/6415004/M10_Rest_Pellet_1926.txt)
[M10_Rest_Soup_1935.txt](https://github.com/OpenMS/OpenMS/files/6415005/M10_Rest_Soup_1935.txt)

**Comment by jpfeuffer** [comment]
It looks like Percolator was run with protein-level FDRs. In this case we do not annotate the peptide/PSM results.

**Comment by Maithy15** [comment]
I am getting the same error with protein and peptide level fdr switched off in the percolator. what should be the score type in the percolator?

**Comment by jpfeuffer** [comment]
It does not need to be a specific type. It depends on how you want to continue your analysis.

"new_score" just needs to match one of the secondary scores. (Btw. it does not make sense to choose "pep" as the main score and then trying to switch to new_score "pep")

Let's say you choose "pep" as the main score in Percolator. Percolator's other scores (qvalue, svm) are then annotated under their controlled vocabulary terms (e.g. MS:1001491). So you could choose "MS:1001491" as new_score and pick its human-readable name as new_score_type (i.e. "q-value"; but this naming is up to you).

**Comment by Maithy15** [comment]
I am now able to run ID score switcher without any error. But I am still unable to get the correct posterior probability for Fido input. Say, if I choose q value in percolator as a score which meta value is PEP?? There are two columns that say MS:1002049 and MS:1002050 how to know which one is PEP so that I can switch it to posterior probability using ID score switcher.

**Comment by jpfeuffer** [comment]
Great. The controlled vocabularies are following the PSI-MS ontology: https://www.ebi.ac.uk/ols/ontologies/ms
In the ScoreSwitcher, make sure that the new name of the score is "PosteriorErrorProbability" or "pep", then you should be done.

**Comment by Maithy15** [comment]
MS:1002049 - is the raw score and MS:1002050 - is the Denovo score for MSGF plus. I do not get a column for MS:1002056 which is the MSGF PEP. I think I am still doing something wrong with percolator settings.

**Comment by jpfeuffer** [comment]
Hmm can you upload the idXML file that comes out of PercolatorAdapter?

**Comment by Maithy15** [comment]
Please find the attached Percolator idxml output https://drive.google.com/file/d/1Hr4aOA5lNSO7L0w7UK1ID5XEs26velv6/view?usp=sharing

**Comment by jpfeuffer** [comment]
```
				<UserParam type="float" name="MS:1001492" value="-0.163178"/>
				<UserParam type="float" name="MS:1001491" value="0.0286796"/>
				<UserParam type="float" name="MS:1001493" value="0.564086"/>
```
Those are the Percolator scores. MS:1001493 should be the PEP.

**Comment by Maithy15** [comment]
I am actually following the quantification workflow given in this book chapter https://pubs.rsc.org/en/content/chapterpdf/2020/9781788019880-00201?isbn=978-1-78801-721-3&sercode=bk 
I hope that it will work now

**Comment by jpfeuffer** [comment]
Ah! You can just open it in any text editor (preferably with XML support). Warning: it is a bit verbose ;)

**Comment by Maithy15** [comment]
Thank you very much for your help!! Finally, I was able to execute the pipeline without any errors for the first time. I have one more question though, I did this workflow in Knime and used ziploops. How does this work in Toppas? Can Toppas automatically do the work of ziploops? Our ultimate aim is to establish this workflow in our supercomputer using Toppas. Thanks again for your help.

**Comment by timosachsenberg** [comment]
By the way we have a nextflow implementation of the label-free workflow ready https://nf-co.re/proteomicslfq . It is a bit more modern/advanced. Let me know if you are interested in it, and we can provide additional information.

**Comment by Maithy15** [comment]
Hi Timo,

Thanks for the suggestion. I will look into it. Is there a way to test it in a windows system?  Otherwise, I will discuss this with our supercomputer guy and let you know.

**Comment by jpfeuffer** [comment]
You could try the Windows Subsystem for Linux 2, which should be part of / easily installable on newer Windows 10 versions.

**Comment by Maithy15** [comment]
Now I have gotten a new error in FIDO adapter in TOPPAS - Error: Unexpected internal error (At least two maps must be given!).

**Comment by jpfeuffer** [comment]
Hmm that does not sound like FidoAdapter. Can you confirm that this happens in this node?

This is probably due to some wrong "recycling" setting. #2382

**Comment by jpfeuffer** [comment]
But I really suggest having a look at the nextflow pipeline. No pipeline building involved there. Everything is setup and ready for HPC systems.

**Comment by Maithy15** [comment]
I will definitely look into it. But, would like to see open ms working at least once. This error "Error: Unexpected internal error (At least two maps must be given!)" is happening at both Fido adapter and Feature linker unlinked QT. I think the files are not merged here. In Knime I used Ziploop and in that case, I get only one file after Ziploop end. So in Toppas should I use file merger in the place of Ziploop end right?

**Comment by Maithy15** [comment]
Just found out that ziploop end function is done by collector.

**Comment by hendrikweisser** [comment]
Looks like the original problem was resolved. Closing this issue.

**Comment by toanlhp** [comment]
> Thank you very much for your help!! Finally, I was able to execute the pipeline without any errors for the first time. I have one more question though, I did this workflow in Knime and used ziploops. How does this work in Toppas? Can Toppas automatically do the work of ziploops? Our ultimate aim is to establish this workflow in our supercomputer using Toppas. Thanks again for your help.

Hello Maithy15,
I'm running openMS on KNIME and got the same problem like you.
ERROR IDScoreSwitcher      3:11       Failing process stdout: []
ERROR IDScoreSwitcher      3:11       Failing process stderr: [Error: Unexpected internal error (Meta value '' not found for peptide hit with sequence 'HVGDLGNVTAGKDGVATVYIEDSVIALSGDHSIIGR', charge 4, score 6.25035e-15)]
ERROR IDScoreSwitcher      3:11       Return code: 8
ERROR IDScoreSwitcher      3:11       Execute failed: Failed to execute node IDScoreSwitcher
Could you please help me how to solve i? Thank you in advance.

**Comment by toanlhp** [comment]
Hi,
I found the way to solve it. Now I had a new problem that the result that after I ran Proteinquantifier node is 0 abundance in all groups. I'm running the workflow again and will update the result tomorrow for you. Thank you.

**Comment by toanlhp** [comment]
My workflow was running well. Thank you so much.
