### ISSUE TITLE
ConsensusID supports MaxQuant?

### ISSUE THREAD

**Issue by yiling0210** [OpenMS/OpenMS#5309]
Hi I am trying to combine peptide identification results from Mascot and MaxQuant. The consensusID paper claims that it supports all search engines. But from the online documentation, it seems that MaxQuant is not part of the pipeline. Could I apply consensusID to MaxQuant?

**Comment by timosachsenberg** [comment]
I think you could ConsensusID to Andromeda output, but you would probably need to convert the MaxQuant output into either mzIdentML or idXML. You could do this relatively quickly by writing a script in pyOpenMS that reads the results and writes e.g. idXML.
See e.g., https://pyopenms.readthedocs.io/en/latest/datastructures_id.html to get you started
