### ISSUE TITLE
PyOpenMS Nightly Whl Actions Broken (Again)

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#5320]
It seems pyopenms nightlies are broken again. 

https://github.com/OpenMS/OpenMS/actions/runs/837144590

**Comment by jpfeuffer** [comment]
Windows is just a broken CMake version.
For Linux I do not have an idea. The container did not change yet. The wheel package version is fixed. Maybe we can just remove the cp libssl command?

**Comment by oliveralka** [comment]
Hm, I am wondering what is different. It seems to build without an issue on my local linux machine.

**Comment by jpfeuffer** [comment]
It's this weird manylinux container and those fixup-wheel things I guess. Or do you build it in docker?

**Comment by oliveralka** [comment]
Yeah, I will try to disable the auditwheel fix code and see what happens. I am compiling in ubuntu (Windows 10 WSL 2).

**Comment by oliveralka** [comment]
For cmake we can probably use that action for windows or all systems to set it to 3.18 or do you have something else in mind?
https://github.com/marketplace/actions/actions-setup-cmake

**Comment by jpfeuffer** [comment]
Yes maybe. I would be fine. I think @Leon-Bichmann had to do some workaround for the general OpenMS build, too.

**Comment by Leon-Bichmann** [comment]
yes maybe the general actions file (https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/openms-ci.yml) can help, but looking at the current errors I also wouldn't be able to tell where it comes from.
