### ISSUE TITLE
Github Actions OpenMS-CI not testing THIRDPARTY tests

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#5359]
Hi everyone, 

as far as I have seen the THIRDPARTY tests are not included in the action.
https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/openms-ci.yml

Was that on purpose or should that be added later on?

**Comment by jpfeuffer** [comment]
See https://github.com/OpenMS/OpenMS/issues/5223
