### ISSUE TITLE
missing metadata in FeatureLinkerUnlabeledQT

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#5361]
`FeatureFinderUnlabeledQT` does not write `name` and `label` metadata [1] resulting in subsequent `MzTabExporter` and `ProteinQuantifier` crashes.

[1] https://github.com/OpenMS/OpenMS/blob/develop/src/tests/topp/FeatureLinkerUnlabeledQT_4_output.consensusXML#L54

**Comment by timosachsenberg** [comment]
hi Lars. The current FeatureLinkerUnlabeledQT should transfer the spectra_data from featuremap to consensusmap.
Do you know which FeatureFinder generated the data? The tests in the repo might be outdated and was probably generated with an older OpenMS version

**Comment by lars20070** [comment]
`FeatureFinderMultiplex`. The feature finder writes `spectra_data` to `featureXML`.

```
<UserParam type="stringList" name="spectra_data" value="[C:\Users\Lars\AppData\Local\Temp\20210604_000342_11772_1\peptides_20210601\003_HighResPrecursorMassCorrector\out\2021-03-02-yj-140min-200nl-4-1-B.mzML]"/>
```

**Comment by lars20070** [comment]
`FeatureFinderMultiplex` needs to set `PrimaryMSRunPath` as in [2]. And `FeatureLinkerUnlabeledQT` needs to set the `label-free` label. That should fix the issue. Correct?

[2] https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FeatureFinderIdentification.cpp#L247

**Comment by timosachsenberg** [comment]
I think spectra_data already stores the primary ms run. And I thought I just tested that FLQT sets the path (but not the label-free)

**Comment by jpfeuffer** [comment]
but from the test data, it seems like FFMultiplex does not set primaryMSRun aka spectra_data

**Comment by timosachsenberg** [comment]
So maybe adding label-free is sufficient
