### ISSUE TITLE
Error of Openms in KNIME

### ISSUE THREAD

**Issue by hello-lei** [OpenMS/OpenMS#5370]
![Uploading image.png…]()
There is a error in KNIME Extension ,I try solve it using sugeestion.

**Comment by oliveralka** [comment]
@hello-lei Hi, we would like to help, but it seems that the image was not uploaded correctly. Could you try to upload it again, and/or copy the error message?

**Comment by hello-lei** [comment]
| |
雷元洛
|
|
***@***.***
|
    ok ，this is the picture. Also, my friend meet it.
On 6/10/2021 19:50，Oliver ***@***.***> wrote：

@hello-lei Hi, we would like to help, but it seems that the image was not uploaded correctly. Could you try to upload it again, and/or copy the error message?
