### ISSUE TITLE
File::find returns files from installed OpenMS first

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#5387]
When building on a machine with an existing install of OpenMS, File::find returns files in the installed version, rather than the build tree. This causes tests to fail if important files have been updated in the build tree but not in the stable installed version (for example building on a machine with 2.6 installed after https://github.com/OpenMS/OpenMS/pull/5211 `FileHandler_test` fails because it loads the old version of `psi-ms.obo`). I believe File::find should be updated to prefer files in build tree.

**Comment by timosachsenberg** [comment]
I think this is not a bug though sometimes unexpected. 
Note that installing OpenMS will put it into the path so it is found first.
There is no easy way to include the build folder as search path into File::find as it could be everywhere (in source / out of source). We would need to use some cmake magic to hardcode that path and it would only work on the computer it was build on.

**Comment by jpfeuffer** [comment]
@timosachsenberg this is done already, I think it is the order that @poshul "complains" about

**Comment by timosachsenberg** [comment]
ah ok I see. What is better? Give the environment precedence (e.g. I just have a .bashrc that sets the path to my build folder).
So the user can choose.
Or use the baked in build foder?
Note that giving precedence to the build folder (as Sam suggests) might also result in hard to trace errors e.g., if the installed OpenMS looks first in its build folder that - if it exists - unexpectedly results in different files loaded than the installed ones.

**Comment by jpfeuffer** [comment]
Yeah, unfortunately, I think we should keep the environment variable as the highest priority. If you have a build folder, you most likely know what you are doing.
Maybe the documentation should be improved in that regard.

**Comment by poshul** [comment]
> If you have a build folder, you most likely know what you are doing.
That is true most days at least. 

Ok, it sounds like we keep it as is.
