### ISSUE TITLE
Missing wrap-inherits in enzymes

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5395]
https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/DigestionEnzymeProtein.pxd#L10

**Comment by oliveralka** [comment]
Seems to be the same here:
https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/DigestionEnzymeRNA.pxd

**Comment by timosachsenberg** [comment]
https://pyopenms.readthedocs.io/en/latest/digestion.html
so this Code does not work?

**Comment by oliveralka** [comment]
@timosachsenberg The Code seems to work fine (in binder). 

If I would like to use the two classes individually in a pyopenms script that should not work without the inheritance.

**Comment by jpfeuffer** [comment]
I'd like to avoid the conversion to AAsequence and use EnzymaticDigestion.unmodifiedDigestion.
This only works for the baseclass.

**Comment by jpfeuffer** [comment]
Ok at least there is another way.
Why do we have the two different ways?

**Comment by timosachsenberg** [comment]
> Ok at least there is another way.
> Why do we have the two different ways? And why are they in different classes?

Don’t know. Maybe @hroest or @hendrikweisser  can comment

**Comment by hendrikweisser** [comment]
> Why do we have the two different ways?

The difference is to what extent modified residues have to be considered during digestion. If they can be ignored, you can use the string method for both proteins and RNA - hence it's in the base class. But if you want to consider modifications, the interfaces and mechanisms differ between proteins and RNA, so there are separate implementations in the derived classes. (The background is that mods are generally ignored for proteins, but are important to consider for RNA.)
