### ISSUE TITLE
Docu failing on linux

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5435]
`! LaTeX Error: Command \@backgroundbox already defined.
               Or name \end... illegal, see p.192 of the manual.`

**Comment by poshul** [comment]
Which version of doxygen was this failing with?

**Comment by jpfeuffer** [comment]
Doxygen 1.8.16, TL 2021, ubuntu 18.04
http://cdash.openms.de/viewBuildError.php?buildid=171411

**Comment by jpfeuffer** [comment]
Also fails in the nightlies now. Seems to be a very recent failure.

**Comment by jpfeuffer** [comment]
Probably someone messed up this package in a recent update, which is transitively included by us: https://mirror.clientvps.com/CTAN/macros/latex/contrib/stackengine/stackengine.pdf

Great timing.

**Comment by poshul** [comment]
How does that get delivered to us? I don't see any updates of texlive-latex-extra recently (at least on 20.04).

**Comment by jpfeuffer** [comment]
We are not using apt packages but install directly from texlive. This package had an update 6 days ago, exactly when the builds started breaking.

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/build-scripts/blob/master/platformScripts/shell/linux/installLatex.sh

**Comment by poshul** [comment]
backgroundbox collides with a previous definition in the adjustbox package. I've emailed the maintainer to try to get that resolved.

**Comment by poshul** [comment]
Stackengine has been updated and should propagate to CTAN in the next 48 hours.

**Comment by jpfeuffer** [comment]
Awesome! Thank you!
