### ISSUE TITLE
Include Deuterium and Tritium as Elements

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5446]
Now that we have ElementDB.cpp, can we try to include D and T? Supposedly it was causing memleaks before.
getElement(atomicnumber) has to go or be adapted of course.

**Comment by jpfeuffer** [comment]
E.g. just add D and T first, then H should overwrite them at pos 1 of the atomnumber map.
Then the atomnumber lookup returns H, which should be fine. At least we can formulate compounds with the symbol D then.

**Comment by timosachsenberg** [comment]
hacky but might work :) but this would need to be really well documented. Would putting this in a parser better?

**Comment by jpfeuffer** [comment]
They can be used in EmpiricalFormula now due to changes in parsing.
For other use cases one might still need to use (2)H or (3)H.
