### ISSUE TITLE
pyOpenMS: Problem with StringDataArrays() after calling set_peaks()

### ISSUE THREAD

**Issue by nietsch** [OpenMS/OpenMS#5452]
Hi,

I'm generating theoretical spectra using `TheoreticalSpectrumGenerator()` as described in the [documentation](https://pyopenms.readthedocs.io/en/latest/theoreticalspectrumgenerator.html).
Afterwards, I want to replace the default peak intensities by previously predicted ones and add the spectra to a new `MSExperiment()` similar to the [documentation for filtering spectra and peaks](https://pyopenms.readthedocs.io/en/latest/data_manipulation.html#filtering-spectra-and-peaks).
After that, with the older wheel version of pyOpenMS I was using until now (version: 2.6.0-pre-py-nightly-test-2021-05-20), it was possible to access the ion names stored in the StringDataArray() using the following loop:
```
for ion in s.getStringDataArrays()[0]:
    print(ion.decode())
```

But now, after installing a newer version (version: 2.6.0-pre-nightly-2021-07-14, pip installed with pyopenms_nightly-2.6.0.dev20210714-cp38-cp38-manylinux2014_x86_64.whl), `StringDataArrays()` is empty after setting the peaks with `set_peaks()`, such that the ion names could no longer be accessed this way.

A small example, showing the problem:

```
for s in exp:                             # Iterate over spectra in MSExperiment

    new_mz = []                           # Set lists for the new mz and intensity values
    new_int = []

    for mz, i in zip(*s.get_peaks()):     # Just set the same values
        new_mz.append(mz)
        new_int.append(i)

    print(s.getStringDataArrays())        # StringDataArrays() contains StringDataArray

    s.set_peaks((new_mz, new_int))        # Set the new peaks (the same as before actually)

    print(s.getStringDataArrays())        # StringDataArrays() is empty
```

So here, the first `print(s.getStringDataArrays())` call prints StringDataArray objects:

```
[<pyopenms.pyopenms_6.StringDataArray object at 0x7f1cf43a9db0>]
[<pyopenms.pyopenms_6.StringDataArray object at 0x7f1cf43a9570>]
[<pyopenms.pyopenms_6.StringDataArray object at 0x7f1cf43a9570>]
[<pyopenms.pyopenms_6.StringDataArray object at 0x7f1cf43a9050>]
...
```

While the second `print(s.getStringDataArrays())` call only prints empty lists:
```
[]
[]
[]
[]
...
```

With this, I assume that `set_peaks()` somehow deletes the StringDataArrays or just doesn't maintain it.

Environment: Ubuntu 20.04.2 LTS with Python 3.8.10

Best regards,
Tobias Nietsch

**Comment by oliveralka** [comment]
Hi Tobias,

it seems that the StringDataArray is not copied over using the get_peaks() and set_peaks() which only returns the numpy array of m/z and intensity. 

What you can do here, is to copy the StringDataArray for each spectrum to the new data structure with your changes to the peaks (e.g. by using the predicted intensities). 

I tested with the current nightlies from the Github action (MacOS 10.15.7, python 3.9):
https://github.com/OpenMS/OpenMS/actions/runs/1057891380

```
from pyopenms import *

tsg = TheoreticalSpectrumGenerator()
spec1 = MSSpectrum()
peptide = AASequence.fromString("DFPIANGER")
# standard behavior is adding b- and y-ions of charge 1
p = Param()
p.setValue("add_b_ions", "false")
p.setValue("add_metainfo", "true")
tsg.setParameters(p)
tsg.getSpectrum(spec1, peptide, 1, 1)


print(spec1.getStringDataArrays())
for ion in spec1.getStringDataArrays()[0]:
    print(ion.decode())

    new_mz = []                         
    new_int = []

    s_arry = spec1.getStringDataArrays() # copy the corresponding array

for mz, i in zip(*spec1.get_peaks()):
        new_mz.append(mz)
        new_int.append(i)



spec1.set_peaks((new_mz, new_int)) 
spec1.setStringDataArrays(s_arry) # add the corresponding array

print(spec1.getStringDataArrays())
for ion in spec1.getStringDataArrays()[0]:
    print(ion.decode())
```

Output:
```
Determination of memory status is not supported on this 
 platform, measuring for memoryleaks will never fail
[<pyopenms.pyopenms_1.StringDataArray object at 0x7fa9d2dfd3b0>]
y1+
y2+
y3+
y4+
y5+
y6+
y7+
y8+
[<pyopenms.pyopenms_1.StringDataArray object at 0x7fa9d2dfd590>]
y1+
y2+
y3+
y4+
y5+
y6+
y7+
y8+
```

Please be careful, that the m/z, intensity and the StringDataArray have the same length. 

Was the StringDataArray automatically copied by the previous "2.6.0-pre-py-nightly-test-2021-05-20" version?

**Comment by oliveralka** [comment]
Addition:
I tested my code without the copy statements of the StringDataArray with a pyopenms version from 3 months ago https://github.com/OpenMS/OpenMS/actions/runs/794272912 (MacOS only).

You are correct, at that time the StringDataArray was retained after using `set_peaks()`.

We will have to investigate further, why this is not possible anymore. Thanks for letting us know!
In the meantime, you can use the copy method mentioned above.

**Comment by jpfeuffer** [comment]
@cbielow https://github.com/OpenMS/OpenMS/blame/a9e07f0a5440aac1ed7fe26cf23f9e5ccd0e9574/src/openms/source/KERNEL/MSSpectrum.cpp#L179

Can you elaborate on your decision to always clear, even though clear_meta_data is off?

**Comment by cbielow** [comment]
this is simply done to maintain the invariant, i.e. the arrays should always have the same length, including the meta-data arrays. Otherwise the behaviour would be suprising at best IMHO. So, if you would clear the actual peaks, but not the meta data, what would the metadata actually annotate? This would be inconsistent and should be avoided.

**Comment by jpfeuffer** [comment]
I agree, IF the arrays _always_ correspond to annotations per peak. At least it seems to be documented like this:
https://github.com/OpenMS/OpenMS/blob/a9e07f0a5440aac1ed7fe26cf23f9e5ccd0e9574/src/openms/include/OpenMS/KERNEL/MSSpectrum.h#L258

Things to consider for the future:
If they are always annotations _per peak_, why are the methods not called getStringPeakAnnotations or similar?
And why is the invariant not enforced during the set methods?

**Comment by nietsch** [comment]
@oliveralka Yes, with this workaround it works. Thank you!
