### ISSUE TITLE
TextExporter output inconsistent

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5456]
https://github.com/OpenMS/OpenMS/blob/develop/src/tests/topp/TextExporter_7_consensus_tsv.tsv#L394

Why does it not have the "new" start and end columns? Will break everything!

**Comment by jpfeuffer** [comment]
It was the limited abilities of java to split with empty fields.

**Comment by jpfeuffer** [comment]
ridiculous: https://stackoverflow.com/questions/13939675/java-string-split-i-want-it-to-include-the-empty-strings-at-the-end/13939902

**Comment by timosachsenberg** [comment]
buuuh Java buuh
