### ISSUE TITLE
IDPosteriorErrorProbability  Tool - Implementation of Comet and MS-GF Plus ID search engines [547]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#547]
Submitted by wernber on 2013-06-20 16:32:38

Comet and MS-GF Plus are two very powerful search engines.

In order to even increase the peptide identification rate using the strategy of combining search results from different database search engines, it is highly recommended to add parameters for calculation of Posterior error probabilities for both ID search engines.

See also previous tickets for more information

**Comment by hendrikweisser** [comment]
Done for MS-GF+ (see Timo's reference above).

**Comment by jpfeuffer** [comment]
Also supports Comet by now.
