### ISSUE TITLE
The question of the screening the  lipidomics data

### ISSUE THREAD

**Issue by hello-lei** [OpenMS/OpenMS#5491]
Hi,
When I analysis the data, I need to consider to delete the repetitive row.
such as the internal standard marked yellow.Because I know it is it,I can delete others.However,other row like this repetition.What should I do?
![image](https://user-images.githubusercontent.com/83147334/129123003-203e27e5-0cf5-4806-a83c-168284c8424a.png)

**Comment by jpfeuffer** [comment]
Hi.

You already received a reply here: https://forum.knime.com/t/the-question-of-the-screening-the-data/35247
Please answer first, why this would not be enough and preferably continue the discussion there.

Thanks!
