### ISSUE TITLE
Documentation parsing errors with doxygen >= 1.8 [550]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#550]
Submitted by aiche on 2013-06-24 16:20:45

The OpenMS documentation, if generated if doxygen >= 1.8 generates a lot of weird looking pages, e.g.,

http://ftp.mi.fu-berlin.de/OpenMS/documentation/html/TOPP_ProteinQuantifier.html

(as of 2013/06/24).

---

Commented by aiche on 2013-06-25 12:03:41:
fixed for a couple of tools in [11416]; doxygen seems to be a bit picky with indentation

**Comment by hroest** [comment]
@timosachsenberg @aiche @jpfeuffer  is this fixed now?

**Comment by jpfeuffer** [comment]
ProteinQuantifier page looks fine. Reading indentation: Probably related to https://github.com/OpenMS/OpenMS/issues/1755
We should probably go over the whole documentation and enforce a certain indentation but this seems quite tedious.

**Comment by hendrikweisser** [comment]
I'm not aware of any such issues that still persist. Closing the ticket.
