### ISSUE TITLE
The workflow of identification compound

### ISSUE THREAD

**Issue by hello-lei** [OpenMS/OpenMS#5506]

**Comment by oliveralka** [comment]
Hello, 
have you tried to combine the MS1 and MS2 identification information based on precursor mz and precursor rt?

**Comment by hello-lei** [comment]
Thank you very much!
Now, I have the result of the AccurateMassSearch node and the MetaboliteSpectralMatcher.I can't combine the result of the rt and mz.I have excuted the two workflow

**Comment by hello-lei** [comment]
Or may I have your email,I can email the data and the workflow to you. Do you have other methods?
