### ISSUE TITLE
Integrate clang-format into github action

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5534]
https://github.com/marketplace/actions/clang-format-lint

**Comment by oliveralka** [comment]
Doing a quick search, I have not found anything, that would allow that. 

It seems that most actions allow for automatic add/commit, without manual review/intervention. 
e.g. https://github.com/marketplace/actions/add-commit, https://github.com/EndBug/add-and-commit

We probably could check the format on a nightly basis and add a new PR if fixes are necessary. So only one commit would be in that new PR and the changes could be reviewed manually. 

Even better might be a scheduled monthly workflow on the develop branch, which will trigger new PR. 

What is your take on that?

**Comment by oliveralka** [comment]
Ok, just for my understanding. The linting would have to be run twice then, or? 

Basically once, for the reviewer to check the changes in the action itself and then a second time using a `@github_action comment`[1] to add and commit the proposed changes. 

[1] https://github.com/marketplace/actions/comment-run-actions
