### ISSUE TITLE
Incomplete mzTab metadata for Metabolomics

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5543]
![Bildschirmfoto 2021-09-20 um 13 05 11](https://user-images.githubusercontent.com/8102638/133992313-56dc43eb-99f5-4e1e-820a-c2f4fad50f43.png)

This is all we have. At least filenames should be there.

**Comment by oliveralka** [comment]
Yeah, that should be changed:
```
    // Since we don't have information on experimental design we just assume one source file that is not further specified ("null")
    MzTabMSRunMetaData run_md;
    MzTabString null_location;
    run_md.location = null_location;
    md.ms_run[1] = run_md;
```
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp#L964

**Comment by jpfeuffer** [comment]
Does FFM not propagate the input filenames?
MapAligner should then collect the filenames in the ConsensusHeader. Then AMS should have access to everyting.

**Comment by oliveralka** [comment]
Yes, it has all the information needed - currently working on it.
