### ISSUE TITLE
KNIME workflow for label-free Metabolites

### ISSUE THREAD

**Issue by ichrak97** [OpenMS/OpenMS#5552]
I am currently doing my Bachelor thesis at the University Erlangen-Nürnberg and the topic is to compare two tools for metabolome analysis which are OpenMS and Metaboanalyst. My Problem is that with OpenMS i get sometimes 0 significant metabolites (with respect to FDR) in a certain sample despite the fact that with respect to p value i get around 3500 significant ones (p_value < 0.05) which is a litte bit weird and also when i run the same sample in Metaboanalyst i get more significant Metabolites with respect to FDR. I am quite sure that the Algorithms of OpenMS are robust but i think i am doing something wrong in the pipline in KNIME. I will be so grateful if someone can help me .

**Comment by jpfeuffer** [comment]
Hi,

IIRC the FDR calculation in the KNIME workflow is very conservative.
To be able to compare the two tools I would try to use the same statistical analysis. It seems like Metabo Analyst uses siggenes https://www.bioconductor.org/packages/release/bioc/html/siggenes.html

It should be rather easy to replace the rudimentary t-test+FDR with siggenes in the R node of the KNIME workflow.
