### ISSUE TITLE
pyOpenMS: getModification not working properly with unimod record IDs

### ISSUE THREAD

**Issue by matteopilz** [OpenMS/OpenMS#5567]
getModification works fine when using names ("Oxidation") and unimod accession ("UniMod:35"). However, using the unimod record ID ("35") will give another modification:

```
ox = ModificationsDB().getModification("Oxidation")
oxacc = ox.getUniModAccession()
oxid = ox.getUniModRecordId()
mod_from_oxid = ModificationsDB().getModification(oxacc).getUniModRecordId()
id_from_oxid = ModificationsDB().getModification(oxid).getUniModRecordId()
print(f'ID from "Oxidation": {oxid}')
print(f'ID from "Oxidation" accession: {mod_from_oxid}')
print(f'ID from "Oxidation" record ID: {id_from_oxid}')
```

```
ID from "Oxidation": 35
ID from "Oxidation" accession: 35
ID from "Oxidation" record ID: 6
```

**Comment by timosachsenberg** [comment]
Thanks for the report. Let's see if this is a bug, misdocumentation or both.

maybe it just calls:
    /**
       @brief Returns the modification with the given index.
    */
    const ResidueModification* getModification(Size index) const;

which is not related to the UniMod record ID (we have also PSI-mod, XL-mod in ModificationsDB)
