### ISSUE TITLE
Linux dependency missing for KNIME nodes 2.7.0

### ISSUE THREAD

**Issue by julianu** [OpenMS/OpenMS#5568]
With the recent release of 2.7.0, almost all nodes in KNIME fail on my laptop with the following error:

`/path/to/knime_4.4.1/plugins/de.openms.linux.x86_64_2.7.0.202109131426/payload/bin/FileFilter: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory`

I am running Manjaro with everything up-to-date. I already googled a bit and the name  `libpcre.so.3` seems to be a Debian (Ubuntu?) speciality and might break on other Linuxes?

**Comment by thommohr** [comment]
I can confirm this is a problem in OpenSUSE also. OpenMS does not work due to this dependency. Please resolve.

**Comment by timosachsenberg** [comment]
any hint on how we should resolve that?

**Comment by jpfeuffer** [comment]
Build Qt without regex support?
Check why the lib is not copied here https://github.com/OpenMS/OpenMS/blob/develop/cmake/knime_package_support.cmake#L219? Make sure the lib is even compatible on other Linuxes.

**Comment by poshul** [comment]
Is this going to be an issue in 3.0?

**Comment by jpfeuffer** [comment]
Not sure. We have a more complete dependency copying mechanism now. Could be fixed but I do not have access to Linux machines with GUI.

**Comment by poshul** [comment]
I can give it a shot on my Ubuntu box and see.

**Comment by jpfeuffer** [comment]
Hmm Ubuntu is unfortunately not the problem.
