### ISSUE TITLE
Deprecate MascotAdapter? [559]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#559]
Submitted by hendrikweisser on 2013-07-03 15:36:43

MascotAdapterOnline seems to be the primary way for performing a Mascot search with OpenMS. The plain MascotAdapter appears outdated (it still uses mzData as input format for raw data).

A decision should be made whether MascotAdapter is still useful/usable in its current state, whether an effort should be made to update it, or whether it can be deprecated/removed (together with the "PepXMLFileMascot" class, which isn't used anywhere else).

**Comment by jpfeuffer** [comment]
What do usage statistics say? Imho deprecate or remove.

**Comment by timosachsenberg** [comment]
Adapter vs AdapterOnline
11 vs 83 uds

**Comment by hendrikweisser** [comment]
Any new thoughts on this?

**Comment by timosachsenberg** [comment]
I will get some updated statistics

**Comment by timosachsenberg** [comment]
I think we should remove the non online version
