### ISSUE TITLE
FeatureFinderIdentification in OpenMS 2.7.0

### ISSUE THREAD

**Issue by giangiacomoberetta1** [OpenMS/OpenMS#5592]
Hi !

While reproducing previous files analysis, I noticed that feature extraction by FeatureFinderIdentification node does not work as before.

The computational stage seems to go on indefinetely.

With previous versions the process was usually concluded in 20-40 min depending on the individual file structure. In the current version, after 24 hours this step is still running

Thanks in advance !

**Comment by timosachsenberg** [comment]
We recently had a regression that led to an infinite loop (deadlock caused by the logging mechanism in KNIME).
Can you tell us which version of the OpenMS plugin you have installed?

**Comment by giangiacomoberetta1** [comment]
Hi!

 

I am running OpenMS 2.7.0.202109131426 in KNIME 4.4.1.

 

Thanks!

 

G

**Comment by jpfeuffer** [comment]
Thanks, Can you also send us the GenericKnimeNodes version (it is usually installed at the same time as a dependency)?

**Comment by jpfeuffer** [comment]
Hmm this sounds a bit old. Did you download the update very early or just recently? In the beginning (until a few days after release) we had a problem that the new GKN version did not ship together with OpenMS 2.7

**Comment by giangiacomoberetta1** [comment]
@timosachsenberg @jpfeuffer thank you guys, after installing GenericKnimeNodes from the KNIME Install new software, the feature finder nodes are now working fine
