### ISSUE TITLE
Qt min version

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#5604]
currently our cmake file says `SET(QT_MIN_VERSION "5.5.0")` however OpenMS doesnt compile any more with Qt 5.5 due to changes introduce over a year ago. Either we fix these changes or we figure out what the latest Qt version is that works again and check against current Linux distros what they ship.

**Comment by jpfeuffer** [comment]
So what about the original issue? I'd rather not revert the changes. 5.6 should really cover 95% of our users.
It is default in CentOS7, Ubuntu 18.04, Debian 9

Older distributions are not even listed anymore on pkgs.org.

**Comment by timosachsenberg** [comment]
Hannes does the system you are talking about support other ways of running OpenMS e.g. in a containerized environment. I am with Julianus on trying to keep the change
