### ISSUE TITLE
Evaluate mzML support in X!Tandem [561]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#561]
Submitted by timosachsenberg on 2013-07-03 20:22:56

According to the X!Tandem homepage mzML is supported. This might save some conversion time in XTandemAdapter if it can directly read our mzML files.

---

Commented by wernber on 2013-07-16 19:05:23:
I tested mzML on X!Tandem some time ago (The last version of X!Tandem) with another GUI and it worked fine. The mzML had been generated with msconvert.

**Comment by jpfeuffer** [comment]
Fixed in #2428
