### ISSUE TITLE
Use MSGFPlusAdapter, PeptideIndexer, IDMerger, FalseDiscoveryRate, IDFilter and TextExporter independently?

### ISSUE THREAD

**Issue by ptnaimelmm** [OpenMS/OpenMS#5623]
Hi there,

I try to run the cptac.py [https://github.com/ylab-hi/ScanExitron/blob/master/Applications/cptac.py], in which MSGFPlusAdapter, PeptideIndexer, IDMerger, FalseDiscoveryRate, IDFilter and TextExporter are used. I tried to install and build up OpenMS, but failed. Do you think whether I can adopt these programs without installing OpenMS? Thanks in advance.

Best regards,

Mingming

**Comment by ptnaimelmm** [comment]
Thank you so much for your suggestions. It truly works. These programs can be invoked.  I got some errors attached when using MSGFPlusAdapter. It seemed there was something wrong with java. Could you give me any suggestions? Thanks.

FATAL ERROR: External invocation of /home-3/mliu63@jhu.edu/Scanexitron_env/bin/java failed. Standard output and error were:
Standard error: Exception in thread "main" java.lang.ExceptionInInitializerError
        at uk.ac.ebi.jmzml.xml.Constants.<clinit>(Constants.java:56)
        at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:82)
        at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:52)
        at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory.buildIndex(MzMLIndexerFactory.java:49)
        at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:121)
        at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:100)
        at edu.ucsd.msjava.mzml.MzMLAdapter.<init>(MzMLAdapter.java:27)
        at edu.ucsd.msjava.msutil.SpectraAccessor.getSpecMap(SpectraAccessor.java:38)
        at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:217)
        at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:105)
        at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:56)
Caused by: javax.xml.bind.DataBindingException: javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
        at javax.xml.bind.JAXB.unmarshal(JAXB.java:186)
        at uk.ac.ebi.jmzml.MzMLElement.loadProperties(MzMLElement.java:609)
        at uk.ac.ebi.jmzml.MzMLElement.<init>(MzMLElement.java:564)
        at uk.ac.ebi.jmzml.MzMLElement.<clinit>(MzMLElement.java:83)
        ... 11 more
Caused by: javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:241)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:455)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:652)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
        at javax.xml.bind.JAXB$Cache.<init>(JAXB.java:127)
        at javax.xml.bind.JAXB.getContext(JAXB.java:154)
        at javax.xml.bind.JAXB.unmarshal(JAXB.java:183)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:573)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:239)
        ... 20 more

Exit code: 1
![javaerror](https://user-images.githubusercontent.com/30491288/139555586-e9f2da2f-bca6-46c1-9da6-a27346e7783c.png)

**Comment by jpfeuffer** [comment]
This could be an error in your MzML input file.
Can you run `FileInfo -in your.mzml`?

**Comment by ptnaimelmm** [comment]
Hi,

The following information showed when I ran FileInfo -in Tutorial_TOFCalibration_raw.mzML.

(/home-3/mliu63@jhu.edu/Scanexitron_env) [mliu63@jhu.edu@compute0784 testTof]$ ~/Scanexitron_env/bin/FileInfo -in Tutorial_TOFCalibration_raw.mzML
Progress of 'loading spectra list':
-- done [took 0.00 s (CPU), 0.01 s (Wall)] --
Memory usage (loading MS data): 12 MB (working set delta)
-- General information --
File name: Tutorial_TOFCalibration_raw.mzML
File type: mzML

MS levels: 1
Total number of peaks: 137887
Number of spectra: 1
Number of spectra per MS level:
  level 1: 1
Ranges:
  retention time: 1.00 .. 1.00
  mass-to-charge: 30371.00 .. 99314.00
  intensity:      0.00 .. 19307.00
Peak type metadata (estimated)
  level 1: Unknown (Centroid)

FileInfo took 0.12 s (wall), 0.10 s (CPU), 0.02 s (system), 0.08 s (user).

Actually, I download this input file from OpenMS example datasets (https://github.com/OpenMS/OpenMS/tree/develop/doc/code_examples/data)

**Comment by jpfeuffer** [comment]
Ah. But this test data does not have any fragment spectra. This unfortunately won't work. But it looks like in general MSGF is working.

**Comment by ptnaimelmm** [comment]
I got the same error when I use my sample data. The file information is as follows.
Progress of 'loading mzXML file':
-- done [took 8.03 s (CPU), 8.08 s (Wall)] --

Memory usage (loading MS data): 1684 MB (working set delta)

-- General information --

File name: NeuroLINCS_170127_SWATH_6600_01_00iCTR_A.mzXML
File type: mzXML

MS levels: 1, 2
Total number of peaks: 102496830
Number of spectra: 119921

Number of spectra per MS level:
  level 1: 1191
  level 2: 118730

Ranges:
  retention time: 0.17 .. 3358.38
  mass-to-charge: 100.02 .. 1499.97
  intensity:      0.04 .. 20059.70

Peak type metadata (estimated)
  level 1: Centroid (Centroid)
  level 2: Centroid (Centroid)

FileInfo took 8.73 s (wall), 8.69 s (CPU), 1.66 s (system), 7.03 s (user).

**Comment by jpfeuffer** [comment]
Can you try it with the real test data like here:
https://github.com/OpenMS/OpenMS/blob/ddfbb579815265a7273ac99e59605db66555c662/src/tests/topp/THIRDPARTY/third_party_tests.cmake#L154

Other than that, the file has SWATH in its name. I am not sure if MSGF is compatible with SWATH acquisition. But I also don't know your protocol.

**Comment by jpfeuffer** [comment]
Maybe it is also a java version issue, but then I think MSGF wouldn't even start to load the database.
I think this version needs java 8.

**Comment by ptnaimelmm** [comment]
Thank you so much for your suggestion. I got the input spectra.mzML and even the proteins.fasta database as you suggested. However, I got the same error as attached. The java I used is java 11.0.1.
![java_error](https://user-images.githubusercontent.com/30491288/139696005-6ce0cadd-4e71-43aa-a8c5-80792a79280c.png)

**Comment by jpfeuffer** [comment]
Can you try java 8? Otherwise I am afraid I am out of suggestions. This seems to be an MSGF+ problem.

**Comment by jpfeuffer** [comment]
https://github.com/MSGFPlus/msgfplus/issues/95

**Comment by ptnaimelmm** [comment]
Hi,
I tried to use java 8 (openjdk version "1.8.0_181" OpenJDK Runtime Environment (build 1.8.0_181-b13) OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode))to run this program, but still got errors as attached. Just want to make sure that I used the right version of java 8. Anyway, I wanna thank you so much for your kind support and suggestions.
![Java8Error](https://user-images.githubusercontent.com/30491288/139733264-3f4cb7e5-7871-4a8f-9c30-32c8c8c9420d.png)

**Comment by jpfeuffer** [comment]
It looks like it is trying to load an HTML file. Probably something went wrong with your download.

If you downloaded via command line, make sure there were no redirects or error Pages that are downloaded.
If you download from the website, try to find a correct link instead of downloading with something like "Save as"

**Comment by ptnaimelmm** [comment]
Hi,
I downloaded the spectra.mzML and proteins.fasta database and ran MSGFPlusAdapter with Java 8. No previous java errors occurred. However, it showed "No DatabaseName element found" and no output idXML file was generated. What do you think the problem is? Thanks.

Best regards,

Mingming

**Comment by ptnaimelmm** [comment]
(/home-3/mliu63@jhu.edu/Scanexitron_env) [mliu63@jhu.edu@compute0784 exitron_NeurolinC]$ MSGFPlusAdapter -ini ~/privatemodules/ScanExitron/Applications/config/config.ini -in Masspec/testTof/spectra.mzML -out test.idXML -database testdatabase/proteins_decoy.fasta -executable ~/Scanexitron_env/share/msgf_plus-2017.07.21-1/MSGFPlus.jar -java_memory 20000 -threads 16
Warning: Parameters file version (2.4.0-HEAD-2018-10-26) does not match the version of this tool (2.5.0-HEAD-HASH-NOTFOUND-HEAD-HASH-NOTFOUND).
Your current parameters are still valid, but there might be new valid values or even new parameters. Upgrading the INI might be useful.
Running MSGFPlus search...
Executing: /software/centos7/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java
Executed /software/centos7/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java successfully!
No DatabaseName element found, use read in results at own risk.
MSGFPlusAdapter took 1.84 s (wall), 0.03 s (CPU), 0.00 s (system), 0.03 s (user).
(/home-3/mliu63@jhu.edu/Scanexitron_env) [mliu63@jhu.edu@compute0784 exitron_NeurolinC]$

**Comment by jpfeuffer** [comment]
Hi,

the DatabaseName warning can be ignored.
Can you try to remove your config.ini? I am not sure what kind of settings are inside there.

**Comment by ptnaimelmm** [comment]
Hi there,

Thanks so much for your help. I ran MSGFPlusAdapter successfully after removing config.ini with java/1.8. Thanks again.
