### ISSUE TITLE
Support PRIDE XML format [563]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#563]
Submitted by hendrikweisser on 2013-07-09 11:21:02

The PRIDE repository uses an XML format to store raw data and identifications together (see http://www.ebi.ac.uk/pride/schemaDocumentation.do).
It would be helpful if OpenMS could support this format, especially to allow reading/conversion of results downloaded from PRIDE.

The raw data seems to be stored in mzData format within the PRIDE XML, so this should be easy to extract and convert (but it is also available as a separate download). For the IDs, a parser would have to be added.

(It is possible that such functionality may become unnecessary in the future, when both PRIDE and OpenMS support mzIdentML as a format for the IDs.)

---

Commented by hendrikweisser on 2013-07-09 17:59:39:
Clarification: The mzData part of the PRIDE XML seems to contain only MS2 spectra (maybe only those that gave rise to identifications).

**Comment by hendrikweisser** [comment]
Seems like nobody actually needs this - closing the issue.
