### ISSUE TITLE
Hyphenation of tool names not optimal [566]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#566]
Submitted by hendrikweisser on 2013-07-09 17:54:15

Long tool names within nodes in TOPPAS are broken over multiple lines and hyphenated now (which I think is pretty cool). However, the results are not quite optimal yet:
"OpenSwathFeatureXMLToTSV" is displayed as follows:

OpenSwath-
Feature- XMLToTSV

I.e. there is an unnecessary hyphen and space inserted without a line break.

(This is on the development version of OpenMS 1.11, rev. 11491, on Ubuntu 11.04.)

**Comment by hendrikweisser** [comment]
It looks like this has been solved in the meantime.
