### ISSUE TITLE
XTandemInfile::load doesn't load correctly [567]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#567]
Submitted by aiche on 2013-07-09 20:21:45

The load function of the XTandemInfile class simply parses the infile and stores everything as XTandemInfileNote without actually transferring its content in the corresponding member variables.

**Comment by timosachsenberg** [comment]
@hendrikweisser is this still an issue (major defect)?

**Comment by hendrikweisser** [comment]
No, `XTandemInfile::load` was deemed unnecessary and removed.
