### ISSUE TITLE
Question: ElutionModelFitter imputation

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5678]
On orbitrap data it happens that e.g. a single peak (one m/z peak in one spectrum) get's picked up but nothing else.
Fitting a model fails of course but imputation then put's in a reasonable looking value. But even without imputation the single value is kept.
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/ElutionModelFitter.cpp#L432

Would it make sense to discard the feature in the case of a single e.g. noise peak? I am asking because we see some elevated background intensity in orbitrap data. @oliveralka what do you think?

**Comment by hroest** [comment]
I agree that a single point in RT should not be used and should probably be filtered out

**Comment by timosachsenberg** [comment]
where would be the best place? in the ElutionModelFitter it is already too late I guess?

**Comment by hroest** [comment]
It should be earlier, the feature should never be created in the first place

**Comment by hroest** [comment]
see #5677 and #5668

that would probably be in the MRMTransitionGroupFinder::pickTransitionGroup where we should never pick such a group in the first place. I am a bit surprised since this uses the PeakPickerHiRes internally and it should not pick a single peak flanked by zeros or would it?

**Comment by timosachsenberg** [comment]
> that would probably be in the MRMTransitionGroupFinder::pickTransitionGroup where we should never pick such a group in the first place. I am a bit surprised since this uses the PeakPickerHiRes internally and it should not pick a single peak flanked by zeros or would it?

PeakPickerHiRes also picks single peaks, as this can in rare cases happen (I think we tested it once, and we got slightly worse ID results).

Ok so setting min_peak_width_  to a very small value (1e-3) would probably solve the "single peak" issue.

What happens e.g., if we get for example: 0090000000900  (9= some high intensity, 0=zero in chromatogram) here? Would this also be removed (e.g. how is peak width here calculated)? 
What about 00000099000000 ? This would probably get a proper width and be picked?

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.cpp#L55
checkend in
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.h#L277

Ok, any objections to setting it to 0.001 as default?

**Comment by jpfeuffer** [comment]
IFF this means that single intensity peaks get filtered by default, I agree with it.
