### ISSUE TITLE
TMTpro 18plex

### ISSUE THREAD

**Issue by glormph** [OpenMS/OpenMS#5693]
Hi, I have been warned that TMTpro 18plex is coming (to our lab), and I wanted to ask if there is planned or existing support for it in OpenMS, as I could not find a mention of it in github issues. Thank you :)

https://www.thermofisher.com/order/catalog/product/A52045
https://pubmed.ncbi.nlm.nih.gov/33900084/

**Comment by timosachsenberg** [comment]
Hi,
We currently don't have a project using TMTpro 18plex so we did not allocate resources to add support, yet.
If you feel familiar with C++ or want to get into it, you can take a look at: https://github.com/OpenMS/OpenMS/pull/4295/files
those were the changes applied to add TMT16plex.
Another possibility would be to ask the author of that PR @poshul if he could add it.

**Comment by radusuciu** [comment]
Is adding support for this basically copying `TMTSixteenPlexQuantitationMethod` to `TMTEighteenPlexQuantitationMethod`, adding a few constants, new tests and making sure it builds? If so, I can probably do this!

**Comment by timosachsenberg** [comment]
Yes exactly! That would be awesome

**Comment by radusuciu** [comment]
Alright! I'm planning on using IsobaricAnalyzer for 18-plex data in the next couple of weeks so I can contribute to that if no one beats me to it.
