### ISSUE TITLE
Issue with OpenSwathWorkflow failing on HDX DIA data.

### ISSUE THREAD

**Issue by ksantone** [OpenMS/OpenMS#5695]
I've been trying to run the OpenSwathWorkflow algorithm with the following program arguments:

-in /Users/kassimsantone/Desktop/Undeuterated/2021-07-08-DIA-Pho-B-50pmol-NepII-0,67ug-UNDEUTERATED-Rep1.mzML /Users/kassimsantone/Desktop/Undeuterated/2021-07-08-DIA-Pho-B-50pmol-NepII-0,67ug-UNDEUTERATED-Rep2.mzML /Users/kassimsantone/Desktop/Undeuterated/2021-07-08-DIA-Pho-B-50pmol-NepII-0,67ug-UNDEUTERATED-Rep3.mzML -tr /Users/kassimsantone/Desktop/data_dia/phoB-dia.pqp -force -readOptions cache -out_osw undeuterated.osw

It seems as though it fails with a SIGABRT and if you look at the callstack the exception handler is called by the loadSplit function in SwathFile.cpp. I'm not sure what is causing this, can someone else run OpenSwathWorkflow on the same program arguments and succeed? Any ideas what could be causing this issue?

![Screen_Shot_2021-12-01_at_1 03 01_PM](https://user-images.githubusercontent.com/6486410/144457332-5b5f00ad-e8e1-4b0a-927a-842cd5b73302.png)
)
![Screen_Shot_2021-12-01_at_1 02 47_PM](https://user-images.githubusercontent.com/6486410/144457324-b8c19bd6-0d2a-48e9-9284-b6e0b5256db7.png)
![Screen_Shot_2021-12-01_at_1 13 11_PM](https://user-images.githubusercontent.com/6486410/144457738-fdb91c55-efc2-4952-8754-f71f9aa6666e.png)

Data can all be found here:

https://www.dropbox.com/s/q637u5dapgx9dqm/2021-07-12-HDX%20SWATH%20Sample%20Data.zip?dl=0

**Comment by oliveralka** [comment]
Hi @ksantone,
I have not tried it yet, but it seems you are missing the `tempDirectory` parameter. 

`"Whether to run OpenSWATH directly on the input data, cache data to disk first or to perform a data reduction step first. If you choose cache, make sure to also set tempDirectory."`

For example:
```
-readOptions cacheWorkingInMemory 
-tempDirectory path_where_temporary_mzMLs_should_be_stored 
```

**Comment by cbielow** [comment]
not sure that is the problem. The parameter has a default of `File::getTempDirectory()`, so it should be fine (unless you run out space in `/tmp` or whatever your system temp dir is...)
In any case, the error message above suggests `Scan 1 has different precursor isolation window than the first scan`.
This suggests the grouping of SWATH isolation windows went wrong.
Sounds like a bug to me which needs fixing.

**Comment by hroest** [comment]
the error is an exception as Chris explained, it seems `checkSwathMap` fails https://github.com/OpenMS/OpenMS/blob/c2555c3278de34a5f261df9a0915f42a8bfada3c/src/openms/source/ANALYSIS/OPENSWATH/OpenSwathHelper.cpp#L56 where the precursor info do not match the expected one from the respective swath window

**Comment by ksantone** [comment]
So I was sent an ini file by the Calgary team with the program arguments they used when they ran this data on OpenSwathWorkflow successfully (it includes a -swath_windows_file, which I did not include so that I believe fixed the issue Chris was referring to). I've updated my program arguments to:

-in /Users/kassimsantone/Desktop/Undeuterated/2021-07-08-DIA-Pho-B-50pmol-NepII-0,67ug-UNDEUTERATED-Rep1.mzML /Users/kassimsantone/Desktop/Undeuterated/2021-07-08-DIA-Pho-B-50pmol-NepII-0,67ug-UNDEUTERATED-Rep2.mzML /Users/kassimsantone/Desktop/Undeuterated/2021-07-08-DIA-Pho-B-50pmol-NepII-0,67ug-UNDEUTERATED-Rep3.mzML -tr /Users/kassimsantone/Desktop/data_dia/phoB-dia.pqp -swath_windows_file /Users/kassimsantone/Desktop/data_dia/bins.csv -sort_swath_maps -enable_ms1 true -enable_ipf true -min_upper_edge_dist 0 -tr_irt "" -force -readOptions cache -out_osw undeuterated.osw

But now it's complaining about "Swath window file contains illegal ranges". Error log is included in the image (I cannot see any other variables in the ini file related to SWATH windows). Any ideas? (I can also include the ini file if you want, but I don't see any other variables related to SWATH windows so I'm not convinced that's the issue)

<img width="1332" alt="Screen Shot 2021-12-03 at 11 41 47 AM" src="https://user-images.githubusercontent.com/6486410/144641001-d1e54a78-ff37-4121-a62c-ea2f6be6c41f.png">
e)

**Comment by ksantone** [comment]
Okay, so I reran it with these program arguments (added a temporary directory):

-in /Users/kassimsantone/Desktop/Undeuterated/2021-07-08-DIA-Pho-B-50pmol-NepII-0,67ug-UNDEUTERATED-Rep1.mzML /Users/kassimsantone/Desktop/Undeuterated/2021-07-08-DIA-Pho-B-50pmol-NepII-0,67ug-UNDEUTERATED-Rep2.mzML /Users/kassimsantone/Desktop/Undeuterated/2021-07-08-DIA-Pho-B-50pmol-NepII-0,67ug-UNDEUTERATED-Rep3.mzML -tr /Users/kassimsantone/Desktop/data_dia/phoB-dia.pqp -swath_windows_file /Users/kassimsantone/Desktop/data_dia/bins.tsv -sort_swath_maps -enable_ms1 true -enable_ipf true -min_upper_edge_dist 0 -tr_irt "" -force -readOptions cache -out_osw undeuterated.osw -tempDirectory /Users/kassimsantone/Desktop/temp_folder

And it is still failing with the original "Scan 1 has a different precursor isolation window than the first scan." so I will investigate that bug more.

**Comment by jpfeuffer** [comment]
If I read the tool description
```
Input: SWATH maps and assay library (transition list) </h3>
  SWATH maps can be provided as mzML files, either as single file directly from
  the machine (this assumes that the SWATH method has 1 MS1 and then n MS2
  spectra which are ordered the same way for each cycle). E.g. a valid method
  would be MS1, MS2 [400-425], MS2 [425-450], MS1, MS2 [400-425], MS2 [425-450]
  while an invalid method would be MS1, MS2 [400-425], MS2 [425-450], MS1, MS2
  [425-450], MS2 [400-425] where MS2 [xx-yy] indicates an MS2 scan with an
  isolation window starting at xx and ending at yy. OpenSwathWorkflow will try
  to read the SWATH windows from the data, if this is not possible please
  provide a tab-separated list with the correct windows using the
  -swath_windows_file parameter (this is recommended). Note that the software
  expects extraction windows (e.g. which peptides to extract from
  which window) which cannot have overlaps, otherwise peptides will be
  extracted from two different windows.
  Alternatively, a set of split files (n+1 mzML files) can be provided, each
  containing one SWATH map (or MS1 map).
```
it feels to me as if OSWWorkflow does not work with replicates this way.
