### ISSUE TITLE
How to get the header file OpenMSconfig.h?

### ISSUE THREAD

**Issue by bluwind1023** [OpenMS/OpenMS#5698]
I created a project with cpp file, and the compiler reported an error and couldn't find the file of OpenMSconfig.h.Where can i find it or how can i creat it?

**Comment by timosachsenberg** [comment]
Hi,
can you provide additional information how you created your project?
As part of OpenMS or as external project by linking to the OpenMS library?

**Comment by bluwind1023** [comment]
Thank you for your reply! I created a new project with Visual Studio, and then added the cpp file in SRC without any change. At the same time, find the absolute path of other header files and add them to the project property settings.The compiler reported an error : couldn't find the file OpenMSconfig.h and config.h.#include <OpenMS/OpenMSConfig.h>#include <OpenMS/config.h>.
I can't find these header files.I only find the corresponding cmake file, which means that the package only supports compiling projects with cmake?

**Comment by bluwind1023** [comment]
Thank you for your reply! I created a new project with Visual Studio, and then added the cpp file form SRC without any change. At the same time, find the absolute path of other header files and add them to the project property settings.The compiler reported an error : couldn't find the file OpenMSconfig.h and config.h.#include <OpenMS/OpenMSConfig.h>#include <OpenMS/config.h>.
I can't find these header files.I only find the corresponding cmake file, which means that the package only supports compiling projects with cmake?

**Comment by timosachsenberg** [comment]
Yes, OpenMS is cmake based and it uses cmake to generate the visual studio project files.

Did you already build OpenMS like described here?
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/install_win.html

You can then create a new tool following this documentation:
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/tutorial.html#tutorial_topp

May I ask what you want to do / develop? This might help giving more targeted advice. E.g., did you also try out pyOpenMS? https://pyopenms.readthedocs.io/en/latest/ it is a bit easier to set up than compiling OpenMS and for many tasks and prototyping sufficient.
