### ISSUE TITLE
Jenkins fails

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#5699]
Jenkins is continuously failing on new PRs with similar errors to the following:
 `  Error when uploading file: /Users/builder/jenkins/ws/openms/PR/bldtst/85c1a982/build/Testing/20211209-1542/Test.xml
   Error message was: Operation too slow. Less than 1 bytes/sec transferred the last 120 seconds
   Problems when submitting via HTTP`

**Comment by timosachsenberg** [comment]
I don't know. I thought it works for most PRs. Results seem to be uploaded (available in CDASH) but failure is reported. Do you have additional information?

**Comment by jpfeuffer** [comment]
See https://github.com/OpenMS/OpenMS/issues/5641
The builds are fine. Only the upload fails. Let's track in the other issue.
