### ISSUE TITLE
Test of Wrapper tools [57]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#57]
Submitted by andreas_bertsch on 2009-11-20 18:07:19

We need unit test for our wrappers, e.g. OMSSA, XTandem, PepNovo, Mascot,....

Can be done similar to database tests, using variable in the build system
---

Commented by cbielow on 2010-01-07 15:45:39:
use cmake/TestConfig.cmake for that.
The DB testing stuff is already in there.
---

Commented by aiche on 2012-09-18 13:28:28:
TODO: 
- install tools on berlin build machines (stephan)
- integrate into build system (stephan, chris)
- write minimal tests (Timo)
---

Commented by cbielow on 2012-09-21 09:41:44:
- fixed [partially] in r10030 (added infrastructure to CMake + tests for OMSSA)

TODO:
- install for nightly builds
- add test data for X!Tandem + Myrimatch
---

Commented by timosachsenberg on 2013-02-22 16:40:56:
tests added for X!Tandem and MyriMatch

TODO:
install for nightly builds
---

Commented by cbielow on 2013-06-18 20:49:03:
ok, mostly done
Test cases are at
source\TEST\TOPP\SEARCHENGINES

for OMSSA, XTandem, MyriMatch

Missing: pepnovo, Mascot (hard to do)

**Comment by jpfeuffer** [comment]
We do this by now.
