### ISSUE TITLE
Toppview splash screen missing after upgrade to OpenMS 1.11 [571]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#571]
Submitted by witek96 on 2013-07-16 13:25:01

When starting Toppview the splashscreen is not shown (see attached png) and a warning is printed on the command line:

witold@witold-MacBookPro:~$ TOPPView 
Warning: TOPPViewBase received the unknown parameter 'preferences:idview:is_relative_tolerance'!

Manually removing the TOPPView.ini resolves the issue.

**Comment by jpfeuffer** [comment]
I would think this is resolved by now? Or was it a spuriously occuring error?

**Comment by timosachsenberg** [comment]
I think this is resolved.
