### ISSUE TITLE
MapAlignerPoseClustering error 

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5710]
Any idea what that is? I looked at the file but don't understand it a lot.

```
---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type IllegalArgument occurred in line 72, function OpenMS::TransformationModelLinear::TransformationModelLinear(const DataPoints&, const OpenMS::Param&) of /home/jenkins/ws/openms/RC/openms_release_packaging/a9154670/source/src/openms/source/ANALYSIS/MAPMATCHING/TransformationModelLinear.cpp
error message: no data points for 'linear' model
---------------------------------------------------
```

File reference:
```
  throw Exception::IllegalArgument(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION,
                                         "no data points for 'linear' model");
```

**Comment by timosachsenberg** [comment]
ok this is probably related to your blank without any feature. MapALingerPoseClustering should be more robust here

**Comment by eeko-kon** [comment]
Hmm, that shouldn't be the issue I think or perhaps I am misunderstanding what you wrote. This is an error generated from MapAlignerPoseClustering that is trying to align features from the raw mzml files. My blanks should have features.

MapAlignerPoseClustering -in {input} -out {output} -algorithm:max_num_peaks_considered 3000

**Comment by timosachsenberg** [comment]
but didn't you have one blank that doesn't have any feature?

**Comment by eeko-kon** [comment]
No, that was after using a MetaboIdent.csv file with only 7 features and then running FeatureMetaboIdent :) During this "mock" requantification , there was a few blank files that were not assigned any features (which made sense)

**Comment by timosachsenberg** [comment]
ok can you reproduce this one e.g. two files?

**Comment by eeko-kon** [comment]
Let me try, but I don't think so. It is probably an issue only in one out of all the files

**Comment by eeko-kon** [comment]
No, I will need to look into the files in pairs...

**Comment by timosachsenberg** [comment]
The error indicates that no common features have been found.
A good guess would be to look into those with few features (e.g., small featureXMLs)

**Comment by eeko-kon** [comment]
hm alright! I will check and get back to you!

**Comment by eeko-kon** [comment]
There is no file with zero features. One with 17 which is quite low, but the mzml has a <spectrumList count="3448">.

**Comment by eeko-kon** [comment]
[SomeFile.txt](https://github.com/OpenMS/OpenMS/files/7734007/SomeFile.txt)

Output of MapAlignerPoseClustering.

**Comment by timosachsenberg** [comment]
I merged a PR for debugging and a fall-back to no alignment for the failing file

**Comment by eeko-kon** [comment]
I m trying it out in 5 min! Thank you Timo!

**Comment by eeko-kon** [comment]
Not working (at least without a flag)

**Comment by timosachsenberg** [comment]
Did it say which file?

**Comment by eeko-kon** [comment]
No, unfortunately not!

**Comment by timosachsenberg** [comment]
ok output works "on-my-machine" and we tracked the problem down to some files with high level of contamination.

**Comment by jpfeuffer** [comment]
But then, why wouldn't your fail-safe check hit?

**Comment by timosachsenberg** [comment]
there was a problem with the build on azure. The check (and GNPS on disc experiment PR) now also for works for @eeko-kon

**Comment by eeko-kon** [comment]
It works - there was a problem with my OpenMS build, sorry for the trouble. Probably a booster issue that wasn't fixed properly. Some of my files seem to have some large contaminants throughout the whole chromatogram. It is very strange, but it is only something that comes up in app. 15 samples or so of consecutive runs (somehow a compound that binds to the column and elutes in several RTs- almost the whole chromatogram). So this generates convexhulls that maybe start at 43 seconds and end at 660 sec which of course cannot be aligned.
