### ISSUE TITLE
MacOS 10.13 does not fully support C++17

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#5714]
currently code in https://github.com/OpenMS/OpenMS/pull/5713 does not not compile on MacOS 10.13 and below, due to an implementation bug on their side.
compile error is: `std::__1::variant<...> &>' is unavailable: introduced in macOS 10.14`
explanation: https://stackoverflow.com/questions/52310835/xcode-10-call-to-unavailable-function-stdvisit

Can we assume 10.14 or higher (and update our build machines accordingly)  or should i write a workaround.
Note that working around `std::visit()` might become tedious if we start using it more and more. And I'm afraid we will not go back to all the hacky versions and fix them, once we require 10.14 and higher...

Any opinions (or solutions?) :)

**Comment by cbielow** [comment]
Personally, i'd favour https://stackoverflow.com/a/53868971, solution 2), because its non-invasive and easily revertable

**Comment by timosachsenberg** [comment]
yeah please go for it

**Comment by cbielow** [comment]
ok
