### ISSUE TITLE
How to create MassTrace objects with pyopenms

### ISSUE THREAD

**Issue by jtprince** [OpenMS/OpenMS#5736]
I've implemented all the behavior of FeatureFinderMetabo and FeatureLinkerUnlabeled (KD and QT) using pyopenms, so I'm learning my way around the code and documentation.  This isn't documented anywhere, AFAICT.

We want to do elution peak detection on mass traces.  Typically, mass traces are derived from subjecting a MSExperiment to mass trace detection (which I can do in pyopenms).  However, in our current work we have mass traces **already generated from an external source** (each trace is composed of m/zs, retention times, and intensities).

I'd like to be able to generate MassTrace objects (specifically `pyopenms.pyopenms_4.Kernel_MassTrace` objects which are the objects being returned from mass trace detection and which I know work for elution peak detection).  How to create a MassTrace object from scratch is not obvious to me, even after staring at the c++ and template code for a while.

It looks like MassTrace objects are composed of a list of peaks, and then the object is updated with meta-data about that set of peaks (or maybe it is calculated on the fly when requested).  It's a little awkward, but I can create Peak2D objects like this:

```python
import pyopenms as oms

peak = oms.Peak2D()
peak.setRT(13.0)
peak.setMZ(433.2)
peak.setIntensity(13441)
```

That's cumbersome, but it works.  Getting a mass trace to accept that list of peaks is where I am stuck.  I've tried a lot of things, but the closest thing I have to working is this (assuming that setting smoothed intensities is how to initialize this):

```python
mass_trace = oms.Kernel_MassTrace()
mass_trace.setSmoothedIntensities([peak, peak2])
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-27-2fe5f8be378b> in <module>
----> 1 mass_trace.setSmoothedIntensities([peak, peak2])

pyopenms/pyopenms_4.pyx in pyopenms.pyopenms_4.Kernel_MassTrace.setSmoothedIntensities()

AssertionError: arg db_vec wrong type
```
That error message (triangulated with the template code for a Kernal MassTrace) suggests that I need to submit the peaks in vector form, but even after googling around for a bit it's not obvious to me how I can generate something like a libcpp.vector object in python.

Then, after I set the data, I think I'll need to call a bunch of methods to update the calculated data from the peaks.  This is the kind of code I'm seeing in C++, but I'm assuming it's similar in pyopenms.

```python
new_trace.updateWeightedMeanRT();
new_trace.updateWeightedMeanMZ()
new_trace.updateWeightedMZsd();
```

Any help is appreciated!

**Comment by jpfeuffer** [comment]
Hi!

Unfortunately it seems that the class is kind of broken since the only useful constructor was not yet wrapped in python.
I hopefully fixed it with the linked PR. Then it should be available tomorrow in the nightly version.

Regarding setSmoothedIntensities. I think it expects a list of floats (i.e. just the intensities), not Peak2D. Not sure if you can create a useful object with this though.

**Comment by jtprince** [comment]
Thanks for your help with this @jpfeuffer!  I'll check out the nightly build.  Sounds like I need one of the constructors that you have wrapped.

**Comment by jtprince** [comment]
@jpfeuffer - Can you point me to how I get a nightly build of a .whl file (I'm assuming that's what I need).  The [files under pyopenms-nightly](https://pypi.org/project/pyopenms-nightly/#files) on pypi look out of date to me. Thanks.

**Comment by timosachsenberg** [comment]
https://pyopenms.readthedocs.io/en/latest/installation.html#nightly-ci-wheels

**Comment by timosachsenberg** [comment]
Thanks for the report. I will close this issue assuming that it is fixed. Please reopen if that is not the case.

**Comment by alhigaylan** [comment]
I ran into this problem despite having pyopenms version 3.0 installed. Took a minute to realize how this was fixed. 

MassTrace() class still refuse to accept peaks. But there is a new class 'Kernel_MassTrace()' that functions properly. Just adding this comment to potential future readers.
