### ISSUE TITLE
NASequence does not support phosphorothioate linkages

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#5745]
While we can add modifications to handle the mass shift for O->S the location of the S replacement makes fragmentation difficult. I'm open to suggestions on how to implement this. @hendrikweisser  any thoughts?

**Comment by hendrikweisser** [comment]
I'm afraid I don't know enough about "phosphorothioate linkages" to be of much help. Questions that may be relevant:
- Would this be a variable modification (may be present) or fixed modification (always present in a relevant experiment)?
- Is it known how the fragmentation patterns are affected or not?

It may be necessary to just add special cases in all the relevant places (like for the interaction between variable inosines and RNase T1 cleavage sites), even it that isn't elegant.

**Comment by poshul** [comment]
This has been fixed in https://github.com/OpenMS/OpenMS/pull/6337
