### ISSUE TITLE
MSFraggerAdapter does not support `max_variable_mods_per_peptide`

### ISSUE THREAD

**Issue by zhuchcn** [OpenMS/OpenMS#5747]
MSFragger has a `max_variable_mods_per_peptide` parameter which defaults to 3 (see here: https://github.com/Nesvilab/MSFragger/wiki/Setting-the-Parameters#max_variable_mods_per_peptide). By any change this could be supported by `MAFraggerAdapter` in a future version? Btw, the paramter `max_variable_mods_per_mod` is supported by MSFraggerAdapter but does not seem to be supported by MSFragger.

**Comment by tillenglert** [comment]
Hi, 

this seems to be a depracated parameter which changed in MSFragger. I will look into it to change it.

**Comment by tillenglert** [comment]
I created a PR for this issue updating the max_variable_mods_per_mod option to max_variable_mods_per_peptide!

https://github.com/OpenMS/OpenMS/pull/5749

**Comment by zhuchcn** [comment]
Also confirm that this works! Really appreciate your fast response!
