### ISSUE TITLE
IdentificationData conversion

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5752]
In the case that a protein/accession is present twice in the idXML we get the following error:
```
(pyopenms) /nfs/wsi/abi/projects/RNPXL/RNPXL/opti_results/2021-12-20_19:21$ IDFileConverter -in entrapment_autotune_perc.idXML -out omstest.oms
Progress of 'Loading...':
-- done [took 01:19 m (CPU), 01:19 m (Wall)] --
Progress of 'Storing...':

  Progress of 'converting protein identification runs':

    Progress of 'converting protein hits (run 1/1)':
Error: Unexpected internal error (the value 'Histone H1.4 OS=Homo sapiens OX=9606 GN=HIST1H1E PE=1 SV=2' was used but is not valid; Trying to overwrite ParentSequence description 'Histone H1.4 OS=Homo sapiens GN=HIST1H1E PE=1 SV=2' with conflicting value.)
```
I think a better error message would be good (e.g., "Same sequence and accession but different description encountered. This might indicate that duplicated sequences were present in a protein database.")

**Comment by timosachsenberg** [comment]
Another issue I found is that file size tend to increase:
1633079296 Jan 18 13:21 my.oms
BSstaff 1323070721 Jan 18 13:18 my.idXML
I once thought that the oms files are much more memory efficient?

**Comment by timosachsenberg** [comment]
Cancelled after more than two hours

**Comment by hendrikweisser** [comment]
> I think a better error message would be good

I think the message is appropriate for `ParentSequence::merge`, where it originates. You could catch it in `IdentificationDataConverter` and throw an error (or write a log message) that gives more context.

**Comment by hendrikweisser** [comment]
> Another issue I found is that file size tend to increase:
> 1323070721 Jan 18 13:18 my.idXML
> 1633079296 Jan 18 13:21 my.oms
> I once thought that the oms files are much more memory efficient?

What's that in human-readable numbers?
`IdentificationData` in-memory tends to be more efficient than the legacy data structures, .oms files not so much. In both cases it depends a lot on how much redundancy there is in data in the old formats. The new data structures (and file format, I guess) have more overhead, but less redundancy.

**Comment by hendrikweisser** [comment]
> Loading oms is still going on ... 120 min + (!!!)

Ouch. Are you able to look into where it hangs?

**Comment by timosachsenberg** [comment]
not yet... build in release mode

**Comment by timosachsenberg** [comment]
I think the problem are the subqueries of the peak annotations.
Adding OM (sum): 0.178266s
  meta took: 0.00043
  step took: 4.1e-05
  peak annotation took: 0.177166
 
Do you see any obvious inefficiency regarding the current query of peak annotations?

**Comment by timosachsenberg** [comment]
My guess is (if it is not something trivial like a missing index) that the subquery performed to select all peak annotations of the current match id has quite some overhead.
1. the query gets executed for every match.
2. the query result can be quite big (a peak annotation consists of several fields, and we might have e.g. 30 or more of them per ObservationMatch.

**Comment by timosachsenberg** [comment]
@hendrikweisser do we need a PRIMARY KEY here?
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/OMSFileStore.cpp#L1234-L1254

**Comment by hendrikweisser** [comment]
Nice job, Timo!

> do we need a PRIMARY KEY here?

No, because the rows aren't referenced anywhere else.

What we do need is an index on the "parent_id" column in that table, because that's how the peak annotations are queried:
https://github.com/OpenMS/OpenMS/blob/aa03c7f187069d9e7aaeca78a3ac453ec4c7c6d6/src/openms/source/FORMAT/OMSFileLoad.cpp#L836-L842

**Comment by hendrikweisser** [comment]
> I just went the wrong route and added an autoincrement id. Will quickly test that approach too ;)

SQLite does that automatically ("ROWID" column): https://www.sqlite.org/autoinc.html

**Comment by hendrikweisser** [comment]
> Just to clarify... this would then be a column that is both primary as well as foreign key?

What do you mean by "this"? "parent_id" in the "PeakAnnotation" table can't be a primary key, because the values aren't unique (potentially many peak annotations per spectrum match).

**Comment by hendrikweisser** [comment]
Can you try adding an index by running the following query:
`CREATE INDEX PeakAnnotation_parent_id ON ID_ObservationMatch_PeakAnnotation (parent_id)`

It should be most efficient to do that once all the data is in the table, so I would add it after this line:
https://github.com/OpenMS/OpenMS/blob/aa03c7f187069d9e7aaeca78a3ac453ec4c7c6d6/src/openms/source/FORMAT/OMSFileStore.cpp#L1284

**Comment by timosachsenberg** [comment]
k will try

**Comment by hendrikweisser** [comment]
It may be useful to run this query before and after you add the index to a file:
`EXPLAIN QUERY PLAN SELECT * FROM ID_ObservationMatch_PeakAnnotation WHERE parent_id = ...` (with a valid ID)

At the moment it should say "SCAN", which is slow. If it works correctly, it should say "SEARCH USING INDEX".

**Comment by timosachsenberg** [comment]
Nice! it worked
```
om took: 0.000433
  mi took: 0.000317
  as took: 2.5e-05
  pa took: 2.4e-05 <- peak annotations
  swrg took: 7e-06
```

**Comment by timosachsenberg** [comment]
```
IDFileConverter -in omstest_index.oms -out test.idXML
Progress of 'Loading...':
-- done [took 01:34 m (CPU), 01:34 m (Wall)] --
Progress of 'Storing...':
-- done [took 27.39 s (CPU), 30.95 s (Wall)] --
IDFileConverter took 02:06 m (wall), 02:02 m (CPU), 3.30 s (system), 01:59 m (user); Peak Memory Usage: 2307 MB.
```

**Comment by timosachsenberg** [comment]
@hendrikweisser do you think we need an index here as well:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/OMSFileStore.cpp#L314-L321

**Comment by hendrikweisser** [comment]
> do you think we need an index here as well:

Probably. In that case we could replace the `UNIQUE (parent_id, name)` with `PRIMARY KEY (parent_id, name)` to get an index that includes the parent ID.

**Comment by timosachsenberg** [comment]
Sorry I am a total noob but will sqlite then create a proper index on parent_id? or only on parent_id, name tuples? which I guess wouldn't help

**Comment by hendrikweisser** [comment]
> Sorry I am a total noob but will sqlite then create a proper index on parent_id? or only on parent_id, name tuples?

My understanding is this:
- Primary key columns function as indexes.
- If an index covers multiple columns, it should work for a subset of those columns *as long as they are at the beginning of the column list* (i.e. the order matters).
- I assume this applies to composite primary keys, too.

It should be easy to test using "EXPLAIN QUERY PLAN" as mentioned above.

**Comment by timosachsenberg** [comment]
@hendrikweisser what about subqueries vs joins.
I think the subqueries in the load are executed for every parent_id which might result in the bad
performance.
https://stackoverflow.com/questions/141278/subqueries-vs-joins?rq=1

**Comment by hendrikweisser** [comment]
> what about subqueries vs joins.

Would need to be tested. I found it conceptually easier to do things "one by one" when loading data, i.e.:
- Run a query for all instances of a particular data type,
- Generate one object per row returned,
- Use "subqueries" to get additional data for the current object.

It may be quicker to do this using a join, but that may differ from case to case, and you lose the simplicity of "one row -> one object" if any of your "subqueries" (that now get joined) return multiple rows.
