### ISSUE TITLE
Feature detection for MS peaks without isotopes

### ISSUE THREAD

**Issue by hykw2b** [OpenMS/OpenMS#5758]
Hi all, 

I am trying to use feature detection function (pyOpenMS 2.7.0) to detect "low abundant" small molecules in non-targeted analysis data (I do not have any list of target m/z. Trying to collect mass features of unknown compounds present in LC-MS).

The tutorial works just fine to detect majority of mass features in my LC-MS data.
https://pyopenms.readthedocs.io/en/latest/feature_detection.html
However I noticed that low abundant molecules that only show monoisotopic peaks (their second isotope peaks were not detected due to low abundance) were not detected as features. 

I have changed several parameters related to isotopic pattern setting(
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1FeatureFinderAlgorithmPicked.html), but haven't managed to get the low-abundant molecules with only monoisotope peaks. 

Is there any way/workaround to detect mass features that have no isotopic pattern information ?

**Comment by timosachsenberg** [comment]
@eeko-kon is doing a very similar workflow in her research. She uses the FeatureFinderMetabo tool which is better suitable for small molecule data. You can also run it through python. Maybe  @eeko-kon or @axelwalter can fill in some detail (and maybe open an issue for the pyopenms tutorial so we can extend documentation on that).

**Comment by axelwalter** [comment]
Hi @hykw2b 
For small molecules you could try the FeatureFindingMetabo together with MassTraceDetection and ElutionPeakDetection.
There you can also set a parameter for FeatureFindingMetabo to not remove single mass traces.

Can you try the following example and tell me if that works for you, so I can update the tutorial.

```
from pyopenms import *


def feature_detection(exp, mtd_custom_params={}, epd_custom_params={}, ffm_custom_params={}, mzML_file_name=''):
    """Feature detection with the FeatureFinderMetabo.

    Parameters
    ----------
    exp : pyopenms.MSExperiment
        MSExperiment to detect features from.
    mtd_params : dict
        Custom parameters for MassTraceDetection.
    epd_params : dict
        Custom parameters for ElutionPeakDetection.
    ffm_params : dict
        Custom parameters for FeatureFinderMetabo.
    mzML_file_name : str
        Path to experiment mzML file to set as PrimaryMSRunPath in FeatureMap.

    Returns
    -------
    pyopenms.FeatureMap
        FeatureMap with detected features.
    """
    exp.sortSpectra(True)
    mass_traces = []
    mtd = MassTraceDetection()
    mtd_params = mtd.getDefaults()
    for k, v in mtd_custom_params.items():
        mtd_params.setValue(k, v)
    mtd.setParameters(mtd_params)
    mtd.run(exp, mass_traces, 0)

    mass_traces_split = []
    mass_traces_final = []
    epd = ElutionPeakDetection()
    epd_params = epd.getDefaults()
    for k, v in epd_custom_params.items():
        epd_params.setValue(k, v)
    epd.setParameters(epd_params)
    epd.detectPeaks(mass_traces, mass_traces_split)

    if (epd.getParameters().getValue("width_filtering") == "auto"):
        epd.filterByPeakWidth(mass_traces_split, mass_traces_final)
    else:
        mass_traces_final = mass_traces_split

    feature_map_FFM = FeatureMap()
    feat_chrom = []
    ffm = FeatureFindingMetabo()
    ffm_params = ffm.getDefaults()
    for k, v in ffm_custom_params.items():
        ffm_params.setValue(k, v)
    ffm.setParameters(ffm_params)
    ffm.run(mass_traces_final, feature_map_FFM, feat_chrom)
    feature_map_FFM.setUniqueIds()
    feature_map_FFM.setPrimaryMSRunPath([mzML_file_name.encode()])

    return feature_map_FFM


mzML_file_path = 'path/to/mzML'

exp = MSExperiment()
MzMLFile().load(mzML_file_path, exp)

fm = feature_detection(exp,
                       mzML_file_name=mzML_file_path,
                       mtd_custom_params={"mass_error_ppm": 5.0,
                                          "noise_threshold_int": 1000.0
                                          },
                       epd_custom_params={"width_filtering": "fixed"
                                          },
                       ffm_custom_params={"isotope_filtering_model": "none",
                                          "remove_single_traces": "false",
                                          "mz_scoring_by_elements": "false",
                                          "report_convex_hulls": "true"
                                          })
```

**Comment by eeko-kon** [comment]
Is there any way/workaround to detect mass features that have no isotopic pattern information?

There is, but you will of course get quite a lot of noise and a high number of features in your data. I never used the algorithm you are currently using, but what Axel posted is a good workflow for feature detection.
Those singleton mass traces should be detected if the parameter remove_single_traces is set to false in FeatureFindingMetabo like what Axel is using in the script. 

`"remove_single_traces": "false"
`
Also at the `mtd_custom_params`, pay attention to the `noise_threshold_int` and make sure that `1000.0` is low enough to detect the peak of interest.

**Comment by hykw2b** [comment]
Hi @axelwalter,
> Hi @hykw2b For small molecules you could try the FeatureFindingMetabo together with MassTraceDetection and ElutionPeakDetection. There you can also set a parameter for FeatureFindingMetabo to not remove single mass traces.
> 
> Can you try the following example and tell me if that works for you, so I can update the tutorial.

Thank you very much for the code and it worked perfectly for my LC-MS data (centroided LC-MS containing low-abundant unknown molecules in mzML) on my current environment (Python 3.8.8  and pyOpenMS 2.7.0). Your code successfully detected trace amounts of molecules that I suspected their presence as mass features.


Hi @eeko-kon,

Indeed `"remove_single_traces": "false" ` was the parameter I have been looking for  `FeatureFinder()`.  Is there same parameter for `FeatureFinder()` ? (I couldn't find though)  Anyway I will start using FeatureFindingMetabo more often for my applications. 


Thank you very much for your help.

**Comment by eeko-kon** [comment]
Great that it worked! 

Hm. It doesn't look that straightforward for sure. Perhaps `mass_trace:min_spectra` set to zero. Do you see any other smoking guns @axelwalter? 

https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1FeatureFinderAlgorithmPicked.html#a78c58de775e1c31c4bb5cd3271bae268

**Comment by timosachsenberg** [comment]
No unfortunately the other feature finders always expect multiple isotopic traces (they are mainly focused for proteomics data).
