### ISSUE TITLE
GNPSexport workflow - connection to IIMN

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5774]
I think it would be awesome if we could add the adduct information in the workflow so that we can use it in FBMN IIMN:
1) the adduct information is lost after FeatureLinkerUnlabeledKD (clustering MS1 data to a consensusXML)
2) TextExporter will convert the consensusXML to a FeatureQuantificationTable.txt that is missing the "best ion" column for every feature 

Could you pass that info to the cpp code? I will add this info to the python workflow 

IIMN workflow:
https://ccms-ucsd.github.io/GNPSDocumentation/fbmn-iin/#iimn-networks-with-collapsed-ion-identity-edges

**Comment by timosachsenberg** [comment]
Ok so we need:
- keep the adduct information during linking

How is the "best ion" defined? I can take a look what it takes to export that information

**Comment by eeko-kon** [comment]
[quantification_table-00000.csv](https://github.com/OpenMS/OpenMS/files/7976772/quantification_table-00000.csv)

Best ion is simply the type of adduct that matched best with the feature. So the adduct information (see feature quant table generated from mzmine)

**Comment by timosachsenberg** [comment]
I think if we currently restrict linking to the same adduct so the best ion would just be the adduct information of the feature I guess?

**Comment by eeko-kon** [comment]
True. So `adduct_merging` should be set to `identical` when linking.

**Comment by timosachsenberg** [comment]
I think so... but maybe also "With_unknown_adducts"

**Comment by axelwalter** [comment]
So we would need to select the best adduct match from the features that get matched to a consensus feature, annotate that in the ConsensusMap and let TextExporter export that informatioN?

**Comment by timosachsenberg** [comment]
As I understood it we just need to make sure that the adduct information is also reported in the consensusXML (e.g., as meta value). And then let TextExporter export that meta value

**Comment by axelwalter** [comment]
Ok, what if there are two consensus features with different adducts annotated. Is there a score we can check to select the best one?

**Comment by timosachsenberg** [comment]
I am not sure if we need to. Isn't that selection only if you have different adducts in one consensus feature (which we don't support)?

**Comment by axelwalter** [comment]
I see, then we don't need that selection.

**Comment by eeko-kon** [comment]
Could MetaboAdductDecharger be used after FeatureLinking? I think Timo is right, but perhaps we can limit the confusion of linking different adducts or features with unassigned adducts if we first link and then annotate?

**Comment by axelwalter** [comment]
If you have a input FeatureMap the output ConsensusMap will have grouped features without charge. Will this happen also with an input ConsensusMap?

**Comment by timosachsenberg** [comment]
I don't know, but we should definitely document this if missing

**Comment by axelwalter** [comment]
Just checked it can only take FeatureMap as input.

**Comment by jpfeuffer** [comment]
@axelwalter tag PR and close?

**Comment by axelwalter** [comment]
solved with #5884
