### ISSUE TITLE
Unable to use fidoAdapter from percolatorAdapter after perform a FDR filter 

### ISSUE THREAD

**Issue by katrina-uw** [OpenMS/OpenMS#5784]
I want to filter the peptides (generate from percolatorAdapter) according to 1% FDR, and then pass the results to fidoAdapter. However, I got the following error:
Error: Unexpected internal error (Error: Unsuitable score type for peptide-spectrum matches detected (problem: lower scores are better).
Fido requires probabilities as scores, e.g. as produced by IDPosteriorErrorProbability with the 'prob_correct' option.)

The flow I use is:
![image](https://user-images.githubusercontent.com/45520179/152271828-01345b3b-0b0e-45c0-9b71-80ecb7a84e81.png)

I understand that FIDO requires posterior probability as the input, but FalseDiscoveryRate will delete the pep score and replace it with FDR instead. However, what's the best way to perform a 1% FDR filter on the peptide results without deleting the pep score?

And also can you tell me how to perform a filter purely on pep score? For example, I want to filter all peptides with pep score larger than 0.99 (after the percolatorAdapter step).

Thank you!

**Comment by jpfeuffer** [comment]
Yes correct. There is an IDScoreSwitcher node that should be able to switch your main score.
The score names are "pep"/"qval"/"svm" for the Percolator scores and "Posterior Error Probability"/"q-value" for OpenMS scores.

IDFilter filters for whatever score is the main score currently. You can also switch back. IDFilter filters for "better than". It knows the orientation.
Same for FDR. Note that Percolator already outputs its own "qval" score.

**Comment by timosachsenberg** [comment]
Also consider using Epifany instead of Fido

**Comment by katrina-uw** [comment]
Thank you for the reply!

I got a new error by using IDSCoreSwitcher, here is my error:
Error: Unexpected internal error (Meta value 'pep' not found for peptide hit with sequence 'KKPTWGRPSR', charge 4, score 7.681760000000001e-03)

my workflow is:
![image](https://user-images.githubusercontent.com/45520179/152342212-824c556a-9253-4202-8376-7ee56fb3ed14.png)

The setting of the IDScoreFilter is:
![image](https://user-images.githubusercontent.com/45520179/152342301-34a2897f-700a-425a-ae71-77536494f74e.png)

The setting of my percolatorAdapter is:
![image](https://user-images.githubusercontent.com/45520179/152342401-f2a2d01a-5ea4-4354-b0b5-97dc07ccac9e.png)

The setting of IDFilter is:
![image](https://user-images.githubusercontent.com/45520179/152342535-853f9216-06ef-4121-996e-e9eae3e5776b.png)

Is this because IDFilter deletes all the other scores from percolator and only keep the main score which is q-value in this case?

Thank you!

**Comment by jpfeuffer** [comment]
This might also be related to your IDMerger problem. Try it again after that.

**Comment by katrina-uw** [comment]
Yes actually my IDMerger has already set psm_merge to be True:
![image](https://user-images.githubusercontent.com/45520179/152589882-abe71076-143f-4ca5-b619-af4c11c9158d.png)

However, I still cannot perform the IDScoreSwitcher, the flow is like the following:
![image](https://user-images.githubusercontent.com/45520179/152589142-e0fbd586-a57f-4e55-907f-bc083e113843.png)

The setting is:
![image](https://user-images.githubusercontent.com/45520179/152589213-f71f5588-b1dc-4ee4-9724-1b4099f6cad5.png)

I wonder is it because when I choose the score in percolatorAdapter ( for example, set to pep), it will delete all the other scores like q-value anyway?

Thanks!

**Comment by jpfeuffer** [comment]
Hmmm.. I am out of ideas right now.
It really looks correct. Percolator Adapter should always annotate all three scores: "pep", "qval" and "svm" and sets one of them as main score (depending on your score parameter).
FalseDiscoveryRate takes the main score  and decoy annotations, overwrites the main score with "FDR" or "q-value" based on your setting and saves the old scores as "$OLDSCORE_score".
IdFilter only filters complete IDs. The ones it keeps should be left complete with all scores.

**Comment by jpfeuffer** [comment]
You could have a look at the idXML files in each step with a TextEditor to see what's going on.

**Comment by jpfeuffer** [comment]
Aaah no I forgot! PercolatorAdapter annotates with the ontology identifiers instead of the names! Let me search the identifiers. They are like MS:123456

**Comment by katrina-uw** [comment]
Ahh yes, I found the pep score as MS:1001493.  Thank you so much!
