### ISSUE TITLE
"Generate theoretical spectrum" in TOPPView is broken

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#5787]
![image](https://user-images.githubusercontent.com/6008722/152424817-45808e3c-f807-4685-92e1-80e9ef4bab88.png)

- Not all items have checkboxes
- the checkboxes are not what they are labeled, i.e. checking b/y does not create b/y ions
- integration into TOPPView is not ideal (checks for missing peptide sequence etc should happen before the dialog is closed etc, i.e. the `TheoreticalSpectrumGenerationDialog` should be more feature-rich itself and return a spectrum plus other metadata, if desired).
- maybe also keep an instance of the class as member of toppview so re-opening the dialog preserves the previous settings.

PS: working on it. Please stand by :)

**Comment by timosachsenberg** [comment]
Dump of ideas for further improvements:
- get rid of the intensities and relative loss. this should be something dealt with e.g. colors
- if we want intensities, we should definitely use a web api or static deep learning model to retrieve predicted spectra with proper intensities
- allow different modes of display, e.g. flipped theoretical spectrum and/or peaks of an experimental spectrum annotated with the predicted ones (especially handling flipped spectra is particularly chaotic in ToppView)
