### ISSUE TITLE
How to Specify TMT Experiments with "Virtual Reference" in IsobaricAnalyzer?

### ISSUE THREAD

**Issue by zhuchcn** [OpenMS/OpenMS#5788]
Hi, this should be a simple question. We have a TMT experiment that does not have an actual reference channel, so all channels are real samples. IsobaricAnalyzer requires the reference channel to be specified, but I looked at the source code, it seems like the reference channel is only used when `-quantification:normalization` is true. So is it true that, as long as we don't use normalization in IsobaricAnalyzer, we don't need to care about the reference channel?

**Comment by cbielow** [comment]
true indeed.

**Comment by zhuchcn** [comment]
Thanks for confirming!
