### ISSUE TITLE
Wrap omp_set_num_threads in pyopenms

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5794]
Also maybe get max nr threads. It should be the last issue to close #4939

**Comment by timosachsenberg** [comment]
Why is this needed (e.g., https://github.com/OpenMS/OpenMS/pull/5839 ) if most users use all threads? Just for completeness and to be able to restrict thread use?

**Comment by jpfeuffer** [comment]
exactly.

**Comment by jpfeuffer** [comment]
you can have your own parallelization outside in python. so you need to be able to restrict how many threads are used inside the functions you call.

**Comment by jpfeuffer** [comment]
It is a first start to start testing such stuff.
