### ISSUE TITLE
TOPPView tables not properly drawn / updated

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5804]
Are there some signals missing?
![image](https://user-images.githubusercontent.com/5803621/153266147-c7496bf5-a462-4843-8dc3-cc7e927dee3e.png)

**Comment by jpfeuffer** [comment]
I think it's a Qt bug

**Comment by timosachsenberg** [comment]
hmm I would think this is unlikely (e.g., maybe rather something like gui was locked / update swallowed) but could be

**Comment by timosachsenberg** [comment]
I think the problem is here:

```
    tables_splitter_ = new QSplitter(Qt::Horizontal);
    QHBoxLayout* tables = new QHBoxLayout(tables_splitter_);
    table_widget_ = new TableView(tables_splitter_);
```
but according to the documentation:
```
Note: Adding a [QLayout](https://doc.qt.io/qt-5/qlayout.html) to a QSplitter is not supported 
(either through [setLayout](https://doc.qt.io/qt-5/qwidget.html#setLayout)() or making the QSplitter a parent of the [QLayout]
(https://doc.qt.io/qt-5/qlayout.html)); use [addWidget](https://doc.qt.io/qt-5/qsplitter.html#addWidget)() instead (see example above).
```

This probably mean we need to add a dummy widget which get's the QHBoxLayout?

**Comment by jpfeuffer** [comment]
I dont know. Maybe just remove the layout. I just tried 1000s of things because resizing never worked.

**Comment by timosachsenberg** [comment]
I can give it a try
