### ISSUE TITLE
mzML File Handler does not write indexed mzML [581]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#581]
Submitted by wernber on 2013-07-18 12:13:11

As I have learned some minutes ago, indexing of mzML files is currently not implemented into the various nodes of OpenMS/TOPPAS.

As this is a requirement of other (external) downstream tools, which are able to handle mzML files as input, I highly recommend to include indexing into the mzML output (at least as option).

Hopefully, the developers agree....

-------------------------------------------------
Commented by hroest on 2013-08-05 23:16:05:
initial support in r11636 and r11637 - it is possible to add a FileFilter node with "-peak_options:indexed_file true" enabled and it should write indexed mzML files. Can you please try that to see whether it solves your problem?

**Comment by hroest** [comment]
this is now resolved with #1355
