### ISSUE TITLE
SiriusAdapter .ms file location

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5812]
Hello! I noticed that the temporary .ms files generated from OpenMS are automatically saved to the` /tmp/` folder and sometimes (e.g. if the process is interrupted) are not removed after shutdown. If I use a specific `-out_ms` output, it seems that `sirius` will still look for those files in the `/tmp/ `directory and will be unable to find them. So there is lack of communication there (I also tried   `-out_project_space <directory>` to specify as the same as the .ms but I think this is a parameter for the whole project (mzTab files).

 ```
-out_ms <file>                             Internal SIRIUS .ms format after OpenMS preprocessing 
                                                       (valid formats: 'ms')
```

It's not a huge issue, just letting you know because now I m working in a VM and those files were accumulated in the root directory, occupying 25% of the memory.

**Comment by jpfeuffer** [comment]
I think the out_ms parameter is only for the file _type_ (and is only used in workflow systems that benefit from knowing an output type). 

But otherwise, I agree, an optional temp directory parameter would be good. Can you elaborate on what happened when you used out_project_space?

**Comment by cbielow** [comment]
I would suggest using the functionalities which are already in place to set a temporary directory:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/SYSTEM/File.cpp#L576

I also had to dig a little to remember the full story, but essentially, this is poorly documented, but should work fine (maybe some internal tweaking of the SiriusAdapter is needed; but please no extra parameters which would make things inconsistent: imagine a full workflow using OPENMS_TMP_DIR and some TOPP tools deviating by custom parameters...).

**Comment by cbielow** [comment]
also, the last fallback using `QDir::tempPath()` (https://doc.qt.io/qt-5/qdir.html#tempPath) should respect environment variables, so this is somehow even duplicated effort already.

**Comment by cbielow** [comment]
And I vaguely remember we had a similar discussion already, but I cannot find it atm.

**Comment by jpfeuffer** [comment]
True I forgot about environment variables for this.
@eeko-kon Can you try setting TMP_DIR or OPENMS_TMP_DIR before you are calling the adapter.
Maybe there is even a setting for environment variables globally in snakemake.

**Comment by eeko-kon** [comment]
When I use `out_project_space`, a directory is made exactly in the place I specified with all the files that one would normally get if they used sirius directly (ms files, frag trees, etc). However, both this directory and the .ms file are still also saved temporarily at the tmp directory (the directory is deleted if the run is completed successfully). 

When I specify the `out_ms` file , sirius was looking for the `.ms` file in the tmp directory, it actually saves the `.ms` file again in both places (tmp and wherever I specified). 

No matter where I specify that the `.ms` file should be saved or the `out_project_space`, sirius always expects to retreive it from the tmp directory and SiriusAdapter always saves everything there. 

No harm done in the end, except from the fact that if the run is interrupted, there s a lot of stuff saved in the tmp dir. 

(Yesterday I had an error about sirius not being able to find some files in the tmp dir but this was my mistake since I was frantically deleting files saved in root cause it was 97% full- my bad )

**Comment by eeko-kon** [comment]
True, I will take a look! Thank you!

**Comment by eeko-kon** [comment]
It worked perfectly, thank you sooo much :D 

Example:

```
rule sirius:
    input: 
        var1= "resources/Sirius/sirius/bin/sirius",
        var2= "results/{samples}/interim/sirius/PCfeature_nch_{samples}.mzML", 
        var3= "results/{samples}/interim/sirius/MFD_nch_{samples}.featureXML"        
    output:
        "results/{samples}/interim/sirius/formulas_{samples}.mzTab"
    threads: 16
    resources: tmpdir="/datadrive/snakemake/snakemake-metabolomics/tmpdir"
    shell:
        """
        SiriusAdapter -executable {input.var1} -in {input.var2} -in_featureinfo {input.var3} -out_sirius {output[0]} -preprocessing:filter_by_num_masstraces 2 -preprocessing:feature_only -sirius:profile orbitrap -sirius:db none -sirius:ions_considered "[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+" -sirius:elements_enforced CHN[15]O[40]S[4] -project:processors 2 -debug 3 -threads {threads}
        """
```
