### ISSUE TITLE
Remove Map class

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5814]
the only difference is the "defaultdict" behavior for the bracket operator..

**Comment by timosachsenberg** [comment]
Mind the pyopenms bindings / special handling

**Comment by jpfeuffer** [comment]
Yes especially also because of this. Right now, we need to keep the conversion providers and pxd in-sync for nothing.

**Comment by jpfeuffer** [comment]
If you really want wrappers for std classes, this should be done generally for all of them in autowrap.

**Comment by timosachsenberg** [comment]
I am totally for replacing Map, but wasn't there some special handling of Map on pyOpenMS side that would potentially be more difficult if we only rely on the standard (unwrapped) ones? Maybe something related to key type / string conversion?

**Comment by hroest** [comment]
@timosachsenberg @jpfeuffer there is this 

https://github.com/OpenMS/OpenMS/blob/0c47724e5bcc5c3f2eaf0c3ab3558934d4e18d22/src/pyOpenMS/converters/special_autowrap_conversionproviders.py#L620

which we would have to port to std::map but that should be reasonably straight forward. As far as I can tell this is the only special treatment in autowrap.

**Comment by timosachsenberg** [comment]
isn't the only difference to the std::map on the C++ side that we provide an operator[] for const maps? e.g. something .at is made for but was previously not properly supprted in older VS versions

**Comment by timosachsenberg** [comment]
I will take a quick look.
