### ISSUE TITLE
Migrate docker builds to GitHub docker registry

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5815]
Docker killed free builds 👎🏻 
Important for our python builds, container distribution to collaborators, gitpod, and more

**Comment by timosachsenberg** [comment]
Would this be https://github.com/features/packages#pricing ? Not free though

**Comment by jpfeuffer** [comment]
Yes, github docker registry would be my first choice. It is free for open source.
Actually, dockerhub is free too, but they don't offer container builds anymore. Sadly we had some variable settings and were sending triggers from jenkins. This means it is not straightforward to replicate everything to Github Actions + a registry

**Comment by jpfeuffer** [comment]
We would probably need builds for contrib, library, and tools, as before.
Builds should be triggered for every push to nightly, release branch or manually via workflow_dispatch_trigger.
We can use the following tutorial (or similar ones):
https://codesalad.dev/blog/push-to-github-container-registry-using-github-actions-7

Our dockerfiles are here:
https://github.com/OpenMS/dockerfiles

We have some parameterization in place here, that worked together with the dockerhub builds:
https://github.com/OpenMS/dockerfiles/blob/master/library/hooks/build
We have to translate that to github actions. It specifies which contrib base image the library build uses. This might even be unnecessary if we build everything in one job.

Note that we should probably follow some kind of schema for the docker tags:
https://forums.docker.com/t/what-is-the-naming-conventions-of-docker-tag/34042/2

E.g. latest for nightly on the newest base container, 2.7.0-ubuntu1804 for releases

**Comment by jpfeuffer** [comment]
Done. See the dockerdeploy.yml files in OpenMS/contrib and OpenMS/OpenMS.
Packages are here: https://github.com/orgs/OpenMS/packages

**Comment by timosachsenberg** [comment]
@KyowonJeong just for reference: a typical infrastructure task in OpenMS
