### ISSUE TITLE
IsobaricAnalyzer lack reporter information

### ISSUE THREAD

**Issue by lbwfff** [OpenMS/OpenMS#5818]
Hi,
I'm having some issues running the IsobaricAnalyzer to analyze TMT11 data. In the code I only modify the correction_matrix and keep the other parameters at their defaults. But the result seems less than ideal，it seem to be missing a lot of information, how should I modify my command.
The following is my report.
```
Calibration stats: Median distance of observed reporter ions m/z to expected position (up to 0.5 Th):
  ch 126  (~126.127): 0.0184368 Th
  ch 127N (~127.124): <invalid data (>0.003 Th channel tolerance)>
  ch 127C (~127.131): <invalid data (>0.003 Th channel tolerance)>
  ch 128N (~128.128): <invalid data (>0.003 Th channel tolerance)>
  ch 128C (~128.134): <invalid data (>0.003 Th channel tolerance)>
  ch 129N (~129.131): <invalid data (>0.003 Th channel tolerance)>
  ch 129C (~129.137): <invalid data (>0.003 Th channel tolerance)>
  ch 130N (~130.134): <invalid data (>0.003 Th channel tolerance)>
  ch 130C (~130.141): <invalid data (>0.003 Th channel tolerance)>
  ch 131N (~131.138): 0.0253414 Th
  ch 131C (~131.144): 0.0316613 Th

IsobaricQuantifier: skipped 36809 of 41136 selected scans due to lack of reporter information:
IsobaricQuantifier: channels with signal
  ch 126 : 1373 / 41136 (3%)
  ch 127N: 849 / 41136 (2%)
  ch 127C: 698 / 41136 (1%)
  ch 128N: 404 / 41136 (0%)
  ch 128C: 199 / 41136 (0%)
  ch 129N: 534 / 41136 (1%)
  ch 129C: 801 / 41136 (1%)
  ch 130N: 495 / 41136 (1%)
  ch 130C: 572 / 41136 (1%)
  ch 131N: 395 / 41136 (0%)
  ch 131C: 220 / 41136 (0%)
```
Thanks,
LeeLee

**Comment by cbielow** [comment]
Hi Lee,

the default search window is 0.002 Th around each expected reporter ion m/z (see documentation https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_IsobaricAnalyzer.html), but it seems that for the majority of channels no signal could be found.
It seems that the signals which are picked up are at ~0.02 or ~0.03 from the expected position, which is a whopping 150ppm off target. 
Can you confirm that you indeed have a signal at the correct positions?
Maybe there is a calibration issue, either directly from the instrument, or maybe a in-silico calibration tool did something wrong?!

**Comment by lbwfff** [comment]
Thanks for the inspiration, I tried IsobaricAnalyzer without steps like PeakPickerHiRes, and got better results. I think it's because I lost most information in Signal Processing and Preprocessing that caused the previous results.

**Comment by timosachsenberg** [comment]
Feel free to share your workflow with us if you want us to take a quick look (e.g., to check search engine settings).

**Comment by cbielow** [comment]
Also, depending on the peakpicker used, it should not pick data twice (which would lead to a lot of peaks lost).
So, in order to avoid such a configuration, it would be nice know yours and add proper checks.
