### ISSUE TITLE
Nightlies on GHActions failing

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5835]
https://cdash.openms.de/viewBuildError.php?buildid=9055

Let's fix the warnings. There was a PR by @timosachsenberg that had to be reverted since it broke compilation.

**Comment by jpfeuffer** [comment]
Linux was fixed by @timosachsenberg with an unknown commit.
For Windows, the path for the tests does not seem to be correct. We should fix this in CMake anyway so that we do not have to worry about settings paths before build on CI. E.g. by setting the environment in add_test or copying the DLLs into the test folders.

**Comment by jpfeuffer** [comment]
we need someone with windows to test what goes wrong there

**Comment by timosachsenberg** [comment]
is Linux fixed? https://github.com/OpenMS/OpenMS/runs/5578687137?check_suite_focus=true#step:7:1167
```
-- Looking for numpy - found
-- Looking for setuptools - found setuptools 60.10.0, version ok
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
CMake Error at src/pyOpenMS/CMakeLists.txt:624 (Python_add_library):
-- Py extra args 
  Unknown CMake command "Python_add_library".
```

on Windows https://github.com/OpenMS/OpenMS/runs/5578687324?check_suite_focus=true#step:10:2467
```
-- Found PythonLibs: C:/hostedtoolcache/windows/Python/3.10.2/x64/libs/python310.lib (found suitable version "3.10.2", minimum required is "3.5") 
-- Py extra args 
CMake Error at src/pyOpenMS/CMakeLists.txt:628 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


CMake Error at src/pyOpenMS/CMakeLists.txt:628 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


CMake Error at src/pyOpenMS/CMakeLists.txt:628 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```

**Comment by jpfeuffer** [comment]
No. But Linux is specific for the manylinux container, so it is harder to test. We might need to make some blind changes.

Windows can be tested locally. This error should be visible right away.

**Comment by jpfeuffer** [comment]
We can also make some blind changes for windows. E.g. catch all potentially empty variables that go into set target properties.

**Comment by timosachsenberg** [comment]
Ok so the issue is that at least one empty variable is passed as part of the set_target_properties call in https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/CMakeLists.txt#L628-L662 ?

**Comment by jpfeuffer** [comment]
Yes most likely

**Comment by timosachsenberg** [comment]
For linux my guess is that the python executable has a different name. E.g., python3 instead of python
but looking at the log it could even by that they are python3.9 etc.
Will attempt a fix in: https://github.com/OpenMS/OpenMS/pull/5958

**Comment by enetz** [comment]
I am able to reproduce the error in Windows locally with Python 3.9.7
I tried to print out the values given to `set_target_properties` with this code (tested the "" because that is actually one of the arguments: `PREFIX ""`):
```
      message(STATUS "PROPERTY: pyopenms_${nr}")
      message(STATUS "PROPERTY: ${PYTHON_EXT_SUFFIX}")
      message(STATUS "PROPERTY: ${VIS_PRESET}")
      message(STATUS "PROPERTY: ${INLINES_HIDDEN}")
      message(STATUS "PROPERTY: ${PY_RPATH}")
      message(STATUS "PROPERTY: """)
      message(STATUS "PROPERTY: ${CMAKE_BINARY_DIR}/pyOpenMS/pyopenms")
```

this is the output:
```
-- Py extra args
-- PROPERTY: pyopenms_1
-- PROPERTY: .cp39-win_amd64.pyd
-- PROPERTY: hidden
-- PROPERTY: 1
-- PROPERTY:
-- PROPERTY:
-- PROPERTY: E:/Development/OMS/OpenMS_win64_release/pyOpenMS/pyopenms
CMake Error at src/pyOpenMS/CMakeLists.txt:637 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```
So the empty string is of course an empty string, `PY_RPATH` is empty as well in my case. Is one of them maybe causing the issue?

**Comment by jpfeuffer** [comment]
The problem might be that they are not passed as an empty string but completely empty in that case. Maybe we need to add quotes

**Comment by enetz** [comment]
tried replacing `INSTALL_RPATH ${PY_RPATH}` with `INSTALL_RPATH "${PY_RPATH}"`
this worked, cmake configuration was successful

**Comment by timosachsenberg** [comment]
k I will add this quickly

**Comment by jpfeuffer** [comment]
I fixed Linux yesterday I think. You have to reduce the search to Python Development.Module since the embedding libraries are missing on manylinux. Worst error messages ever, though.

**Comment by timosachsenberg** [comment]
ah ok but would it still make sense to put the quotes there?
https://github.com/OpenMS/OpenMS/pull/5966

**Comment by jpfeuffer** [comment]
Sure. Quotes are for windows.

**Comment by jpfeuffer** [comment]
We just have to make sure no double quotes occur on nonwindows. But I think it should be fine.

**Comment by timosachsenberg** [comment]
ah ok this fails on linux / mac then? is there no unified way in cmake to handle quoting for different platforms=

**Comment by jpfeuffer** [comment]
No I am not sure. You have to keep an eye on it. It is also not about quoting in general but about empty variables vs empty string. So a bulletproof solution would be if cases but I feel like adding the quotes is correct.

**Comment by jpfeuffer** [comment]
Fixed in #5966 #5970 and more
Only thing left are failing tests in new issue.

**Comment by rwst** [comment]
I got this with `cmake ... -DPython_EXECUTABLE:=/usr/bin/python3.6` 
Does that mean that 3.6 is not supported?

**Comment by jpfeuffer** [comment]
No, I think it means your CMake version is too old. But we recently switched test frameworks since nose was deprecated. We are using pytest now, which requires 3.7. That might show up as a problem later. In theory, we could make that optional since it is just the testing framework, however, 3.6 reached end-of-life, and therefore we will probably not do fixes for it (but accept contributions as pull request).

**Comment by rwst** [comment]
But
```
ralf@ark:~> cmake --version
cmake version 3.17.0
```

**Comment by rwst** [comment]
Still appears with Py39:
```
ralf@ark:~/OpenMS> cmake -DOPENMS_CONTRIB_LIBS="/home/ralf/contrib-build" -DBOOST_USE_STATIC=ON -D PYOPENMS=ON -DPython_EXECUTABLE:=/opt/python/bin/python3.9 ../OpenMS
...
-- Adding library OpenMS - SUCCESS
-- Could NOT find Python (missing: Interpreter Development.Module) (found version "3.9.13")
-- Python found at /opt/python/bin/python3.9 with version 3.9.13 (if this is wrong, see https://cmake.org/cmake/help/latest/module/FindPython.html and configure with e.g. -DPython_EXECUTABLE:=/path/to/python)
-- Looking for Cython - found Cython version 0.29.32. Version ok
-- Looking for autowrap - found autowrap 0.22.8, version ok
-- Looking for pytest testing framework - found
-- Looking for numpy - found
-- Looking for setuptools - found setuptools 65.3.0, version ok
-- Found OpenMP_CXX: -fopenmp  
-- Py extra args 
CMake Error at src/pyOpenMS/CMakeLists.txt:627 (Python_add_library):
  Unknown CMake command "Python_add_library".
```

**Comment by jpfeuffer** [comment]
Yes because the problem is most likely the CMake version.
I just meant you will have problems later in the build with 3.6.

**Comment by jpfeuffer** [comment]
Although I thought the following line will take care of that and fail.

https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/CMakeLists.txt#L35

**Comment by rwst** [comment]
Works now with cmake-3.24.1. Thanks!

**Comment by jpfeuffer** [comment]
I saw that the FATAL_ERROR option is ignored these days by CMake. We might either need to raise the overall minimum version or add a manual check in the pyopenms Cmakelists.
