### ISSUE TITLE
error in MapAlignmentAlgorithmPoseClustering()

### ISSUE THREAD

**Issue by quarksome** [OpenMS/OpenMS#5842]
Hi all

I am trying to run MapAlignmentAlgorithmPoseClustering() in pyOpenMS but I keep getting this error:

> RuntimeError: the value '-nan' was used but is not valid; Superimposer could not compute an initial transformation!You can try to increase 'max_num_peaks_considered' to solve this.

I tried changing the value of the 'max_num_peaks_considered' but it does not solve it.

Here is a snippet of my code:

```
#feature RT alignment
# get in index of feature map with highest number of features in feature map list
ref_index = [i[0] for i in sorted(enumerate([fm.size() for fm in feature_maps]), key=lambda x:x[1])][-1]

aligner = MapAlignmentAlgorithmPoseClustering()

aligner.setReference(feature_maps[ref_index])

# aligner_params = Param()
# aligner_params.setValue('max_num_peaks_considered', feature_maps[ref_index].size())
# aligner.setParameters(aligner_params)

for feature_map in feature_maps[:ref_index] + feature_maps[ref_index+1:]:
    print(feature_map.size())
    trafo = TransformationDescription()
    aligner.align(feature_map, trafo)
    transformer = MapAlignmentTransformer()
    transformer.transformRetentionTimes(feature_map, trafo, True) # store original RT as meta value
```
Error appears on line 16: aligner.align(feature_map, trafo).

**Comment by eeko-kon** [comment]
Have you tried with "max_num_peaks_considered", -1 (infinite)?

**Comment by quarksome** [comment]
Hi,

Yes, I have tried setting that to -1 but it gave the same error. I have used the default (1000) too but they all don't work.

**Comment by eeko-kon** [comment]
Could you perhaps share your data? I might be able to help

**Comment by quarksome** [comment]
Hi, yes that would be great! How do I go about sharing some mzml files?

**Comment by eeko-kon** [comment]
Google drive or zenodo would be great :)

**Comment by quarksome** [comment]
So I ran some other set of files and this time the aligner worked! I'm guessing something with my previous data files are causing this error. 

Anyway, I've uploaded a set of files which results to this error here: https://zenodo.org/record/6321368#.Yh6x-OrMKUk

**Comment by eeko-kon** [comment]
hmmm I am not getting this error. Here are my parameters (used from the CLI):

`MapAlignerPoseClustering  -algorithm:max_num_peaks_considered -1 -algorithm:superimposer:mz_pair_max_distance 0.05 -algorithm:pairfinder:distance_MZ:max_difference 10.0 -in {input} -out {output}`

Can you try with these? I also tried out with yours and it also worked fine.. That's strange.

**Comment by eeko-kon** [comment]
p.s. I Also used pyopenms with your params and it worked fine

**Comment by jpfeuffer** [comment]
Which version are you all using?

**Comment by eeko-kon** [comment]
hmm I used the latest wheels but I can try with the regular import

**Comment by quarksome** [comment]
I am using pyopenms 2.5.0. 

Do you mind sharing the code you used to generate the feature_maps? I am using a combination of MassTraceDetection(), ElutionPeakDetection(), and FeatureFindingMetabo() to generate my list of feature maps.

**Comment by eeko-kon** [comment]
I have version 2.7.0 - can you update yours and check again? It works for me with the latest version also (and wheels). And of course, here is the code I m using:
The parameters depend on the instrument/data and they are set up for my data specifically :) 

```
input_mzml_files= glob.glob("path/to/*.mzML")

# 2) Mass trace detection

for filename in input_mzml_files:
    exp = MSExperiment()
    MzMLFile().load(filename, exp)
    exp.sortSpectra(True)
    mass_traces = []
    mtd = MassTraceDetection()
    mtd_par = mtd.getDefaults()
    mtd_par.setValue("mass_error_ppm", 10.0) 
    mtd_par.setValue("noise_threshold_int", 1.0e04) #for orbitrap instruments
    mtd.setParameters(mtd_par)
    mtd.run(exp, mass_traces, 0)

# 3) Elution peak detection

    mass_traces_split = []
    mass_traces_final = []
    epd = ElutionPeakDetection()
    epd_par = epd.getDefaults()
    epd_par.setValue("width_filtering", "fixed")
    epd.setParameters(epd_par)
    epd.detectPeaks(mass_traces, mass_traces_split)
     
    if (epd.getParameters().getValue("width_filtering") == "auto"):
          epd.filterByPeakWidth(mass_traces_split, mass_traces_final)
    else:
          mass_traces_final = mass_traces_split

# 4) Feature finding metabo
  
    feature_map_FFM = FeatureMap()
    feat_chrom = []
    ffm = FeatureFindingMetabo()
    ffm_par = ffm.getDefaults() 
    ffm_par.setValue("isotope_filtering_model", "none")
    ffm_par.setValue("remove_single_traces", "true")
    ffm_par.setValue("mz_scoring_by_elements", "false")
    ffm_par.setValue("report_convex_hulls", "true")
    ffm.setParameters(ffm_par)
    ffm.run(mass_traces_final, feature_map_FFM, feat_chrom)
    feature_map_FFM.setUniqueIds()
    feature_map_FFM.setPrimaryMSRunPath([filename.encode()])  

    featurefile = os.path.join(path, 'FFM_' + os.path.basename(filename)[7:-5] +".featureXML")
    FeatureXMLFile().store(featurefile, feature_map_FFM)
```

**Comment by eeko-kon** [comment]
Let me know how it goes.

**Comment by quarksome** [comment]
Hi, I tried to use some of your parameters here that I think is also applicable to my data, and it worked now! 

Specifically, I added the "mass_error_ppm" and "noise_threshold_int" params to the mtd, and "remove_single_traces" to the ffm method.

**Comment by eeko-kon** [comment]
That's great to hear! It's because I set my param according to my samples and both mine and yours were analyzed with an Orbitrap, so the noise threshold and mass_error_ppm should be similar.
