### ISSUE TITLE
Nodes not working on OpenMS - Knime workflow

### ISSUE THREAD

**Issue by pchirania** [OpenMS/OpenMS#5849]
Hi,

I am following the tutorial for using OpenMS in Knime.
I have installed OpenMS following the instructions and getting the startup warning "Some of the OpenMS FileConverter requirements might be missing. Double click for details." When I click, download, and install the prerequisites installer- nothing changes. Perhaps, I am not installing it the right way? I am using openMS 2.8 - present in Knime and the latest installer for prerequisites I could find is 2.7.
If I ignore this error and run the tutorial workflows - they fail and I get the following error for any of the nodes:
ERROR FileInfo             4:3        Failing process stdout: []
ERROR FileInfo             4:3        Failing process stderr: []
ERROR FileInfo             4:3        Return code: -1073741515
ERROR FileInfo             4:3        Execute failed: Failed to execute node FileInfo
ERROR FileInfo             4:3        Failing process stdout: []
ERROR FileInfo             4:3        Failing process stderr: []
ERROR FileInfo             4:3        Return code: -1073741515
ERROR FileInfo             4:3        Execute failed: Failed to execute node FileInfo
ERROR DecoyDatabase        3:56       Failing process stdout: []
ERROR DecoyDatabase        3:56       Failing process stderr: []
ERROR DecoyDatabase        3:56       Return code: -1073741515
ERROR DecoyDatabase        3:56       Execute failed: Failed to execute node DecoyDatabase

Please help.

Thanks!

**Comment by jpfeuffer** [comment]
Hi,

Sorry, 2.8 was not meant for a Knime release. Please revert and stay with 2.7 for now. I will remove it from the update site.

**Comment by pchirania** [comment]
Hi,

Thank you for the quick response. I am uninstalling the 2.8 version. However, how do I install the 2.7 version, I do not see an option for that in the community contributions site?

**Comment by jpfeuffer** [comment]
The next release for knime will be 3.0. We will investigate until then.

**Comment by pchirania** [comment]
How do I use openMS until then? I want to use MetaproSIP in openMS

**Comment by pchirania** [comment]
All options on KNIME are for openMS 2.8, please help

**Comment by jpfeuffer** [comment]
This will take some time. And it is probably best to reinstall Knime

**Comment by jpfeuffer** [comment]
It should be removed now. Please try again. At least restart, better reinstall KNIME

**Comment by pchirania** [comment]
Thank you for the update! I restarted and was able to install openMS 2.7 However, I am still getting the same error that "Some of the OpenMS FileConverter requirements might be missing. Double click for details." I downloaded the prerequisites installer and ran the .exe file but it does not solve the issue. Can you please advice? Is there an alternate way to run the installer for it to be recognized?

**Comment by jpfeuffer** [comment]
Do the nodes work now? The warning is only for special functions of FileConverter

**Comment by pchirania** [comment]
Hi,
 Yes some of the nodes are working now. But, I am still getting error in some. 
One of the issues is the following error:
Standard error: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

I am trying to run MSGFPlusAdapter node, the input database is large..Can this be resolved by increasing memory? If yes, how can I do that?
