### ISSUE TITLE
New Docker containers not working?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5866]
As reported on gitter, there might be some problems with validating the SHA hash of some of the layers.
Can someone confirm that?
Maybe just a reupload helps?

**Comment by jpfeuffer** [comment]
They seem to be downloadable now but the binaries might not be in the path

**Comment by Arslan-Siraj** [comment]
@jpfeuffer how to proceed with this?

**Comment by jpfeuffer** [comment]
It needs to be tested if it is true.

**Comment by jpfeuffer** [comment]
I actually think they are fine. We also have singularity images now, so there is not even a conversion needed anymore.
This can be closed.
