### ISSUE TITLE
SiriusAdapter test misses argument value

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#5869]
`-in_featureinfo` misses the value here: 

https://github.com/OpenMS/OpenMS/blob/ec3250d20e318cd569356ffee5fd976433b19aa2/src/tests/topp/THIRDPARTY/third_party_tests.cmake#L364

Should it be ` ${DATA_DIR_TOPP}/AssayGeneratorMetabo_decoy_generation_input_multids.featureXML` as in the previous test or should the parameter be omitted?

**Comment by jpfeuffer** [comment]
Oh wow, I guess it is equivalent to being omitted. Not sure if this was intended though.

**Comment by oliveralka** [comment]
That looks like a nasty copy-paste error. The test is supposed to use all ms2 available, so no feature input should be given. `-in_featureinfo` should be removed.

**Comment by bernt-matthias** [comment]
Will this be all ms2spectra in `${DATA_DIR_TOPP}`? Not sure how I should treat this in the automatic generation of the Galaxy tests...

**Comment by oliveralka** [comment]
Ah, no sorry for the misunderstanding. Basically, SIRIUS will process all valid MS2 spectra, which are in the .mzML file `(`-in` ${DATA_DIR_TOPP}/AssayGeneratorMetabo_decoy_generation_input.mzML`). The `-in_featureinfo` should not be a part of the arguments for this specific test scenario.
