### ISSUE TITLE
The wrong in the workflow/KNIME

### ISSUE THREAD

**Issue by hello-lei** [OpenMS/OpenMS#5871]
Hello,every one today I use the workflow to process my data,it occurred the wrong.
There are two workflow have different errors.
a) ERROR ZipLoopEnd           15:4       Execute failed: Encountered duplicate row ID "Row_0_0"
b) ERROR MapAlignerPoseClustering 9:268      Execute failed: Failed to execute node MapAlignerPoseClustering
![image](https://user-images.githubusercontent.com/83147334/156124227-00d3b470-2ab6-4f3e-a849-c1716cfb7d94.png)
![image](https://user-images.githubusercontent.com/83147334/156124254-1a6f4ed1-c21b-433d-bbbc-39c6ba0a41bd.png)
Thank you very much!

**Comment by jpfeuffer** [comment]
Sorry, but you need to paste the errors.
Picture 2: You cannot have two LoopEnds for one LoopStart.

**Comment by jpfeuffer** [comment]
`error message: One of the input maps is empty! This is not allowed!`

I assume you found the error by now. Please reopen if necessary with more information
