### ISSUE TITLE
Duplicated modification

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#5874]
The `fixed_modifications` parameter (e.g. in CometAdapter) contain a duplicated entry: `Glu->pyro-Glu+Methyl (N-term E)`

**Comment by jpfeuffer** [comment]
If it is exactly the same, I think it can just be removed.

**Comment by bernt-matthias** [comment]
@jpfeuffer I could not find out where they are defined. Otherwise I would have opened a PR.

**Comment by timosachsenberg** [comment]
I found it once in unimod (light and heavy version)
```
      <umod:mod title="Glu->pyro-Glu+Methyl"
        full_name="Pyro-gly from E + Mono-Methylation"
        username_of_poster="Weng"
        group_of_poster="admin"
        date_time_posted="2015-07-06 12:00:00"
        date_time_modified="2015-07-06 12:00:00"
        approved="0"
        record_id="99988">
        <umod:specificity hidden="1" site="E" position="Any N-term" classification="Artefact"
        spec_group="1"/>
        <umod:delta mono_mass="-3.9949149358" avge_mass="-3.98872" composition="O(-1) C(1)">
          <umod:element symbol="O" number="-1"/>
          <umod:element symbol="C" number="1"/>
        </umod:delta>
      </umod:mod>
      <umod:mod title="Glu->pyro-Glu+Methyl:2H(2)13C"
        full_name="Pyro-gly from E + Mono-Methylation-Medium"
        username_of_poster="Weng"
        group_of_poster="admin"
        date_time_posted="2015-07-06 12:00:00"
        date_time_modified="2015-07-06 12:00:00"
        approved="0"
        record_id="99989">
        <umod:specificity hidden="1" site="E" position="Any N-term" classification="Artefact"
        spec_group="1"/>
        <umod:delta mono_mass="-0.979005" avge_mass="-0.983746" composition="H(-2) O(-1) 2H(2) 13C(1)">
          <umod:element symbol="H" number="-2"/>
          <umod:element symbol="O" number="-1"/>
          <umod:element symbol="2H" number="2"/>
          <umod:element symbol="13C" number="1"/>
        </umod:delta>
      </umod:mod>
```

**Comment by timosachsenberg** [comment]
https://raw.githubusercontent.com/OpenMS/OpenMS/develop/share/OpenMS/CHEMISTRY/unimod.xml
Seems to be a unimod problem.

**Comment by timosachsenberg** [comment]
ok how do deal with it? Removing it manually from unimod is not ideal because we will likely forget if someone else updates it.

**Comment by bernt-matthias** [comment]
> ok how do deal with it? Removing it manually from unimod is not ideal because we will likely forget if someone else updates it.

Is there an upstream repo where we could file an issue?

**Comment by timosachsenberg** [comment]
Maybe first check if they already fixed it here:
https://www.unimod.org/downloads.html
https://www.unimod.org/xml/unimod.xml

and issues can be sent to: [unimod@unimod.org](mailto:unimod@unimod.org).

**Comment by bernt-matthias** [comment]
`<umod:mod title="Glu->pyro-Glu+Methyl"` seems to be gone from the online file.

Also `grep "umod:mod title" unimod.xml | sed 's/^\s*//'| sed 's/&gt;/>/'| sed 's/full_name.*//' | sed 's/\s*$//' | sort  | uniq -c | sort -n`  verifies that there is no more duplicate...

The `diff` with the new file has 1700 lines.

**Comment by timosachsenberg** [comment]
Can you post it as gist? I can take a quick look for a sanity check.

**Comment by bernt-matthias** [comment]
Like so: https://gist.github.com/bernt-matthias/55cf070d46543c69e0a404b854606beb

**Comment by timosachsenberg** [comment]
Yes that helps.
Seems we can take the new one but need to add this:
https://gist.github.com/bernt-matthias/55cf070d46543c69e0a404b854606beb#file-gistfile1-txt-L864-L1213
to allow custom modifications to be added by users
