### ISSUE TITLE
Some boolean parameters are not rendered as booleans in CTD outputs

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#5880]
Here an example from `CompNovo`:

```
      <ITEM name="log" value="" type="string" description="Name of log file (created only when specified)" required="false" advanced="true" />
        <ITEM name="tryptic_only" value="true" type="string" description="if set to true only tryptic peptides are reported" required="false" advanced="false" />
```

**Comment by jpfeuffer** [comment]
But isn't that normal? How would you represent a boolean parameter with a default of true?

**Comment by bernt-matthias** [comment]
Good point, but shouldn't it have `restrictions="true,false"`?

**Comment by jpfeuffer** [comment]
You could do:
bool = checkbox
string with true,false = checkbox
string with other restrictions = drop-down
string without restrictions = text field

**Comment by jpfeuffer** [comment]
You could do:
bool = checkbox
string with true,false = checkbox
string with other restrictions = drop-down
string without restrictions = text field

But make sure to translate to string param or flag later on when passing on command line. Or write an ini.
