### ISSUE TITLE
GNPSMGFFile pyopenms

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5885]
@timosachsenberg the input consensus somehow does not accept a string or a consensusMap(). Anything I m missing?

```
consensus= "results/interim/GNPSexport/filtered.consensusXML"
cmap=ConsensusMap()
ConsensusXMLFile().load(consensus, cmap)

input_mzml_files=sorted(glob.glob("results/interim/PCfeature_*.mzML"))
out_file= "results/GNPSexport/MSMS.mgf"
param= "resources/GNPSExport.ini"

spectra_clustering= GNPSMGFFile()
cluster= spectra_clustering.getDefaults()
cluster.setValue("cos_similarity", 0.9)
spectra_clustering.setParameters(cluster)

spectra_clustering.run(cmap, input_mzml_files, out_file)
```

**Comment by eeko-kon** [comment]
Ops, sorry did not post the error:

```
[---> ]()[14](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/3_GNPSExport.ipynb#ch0000010?line=13)[ spectra_clustering.run(cmap, input_mzml_files, out_file)

File ~/openms-develop/openms_build/pyOpenMS/pyopenms/pyopenms_1.pyx:4640, in pyopenms.pyopenms_1.GNPSMGFFile.run()


AssertionError: arg consensus_file_path wrong type]()
```

**Comment by timosachsenberg** [comment]
Hi, I think you pass a consensus map instead of the file name
https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/GNPSMGFFile.pxd#L17

**Comment by eeko-kon** [comment]
I tried that too .. 
```

[---> ]()[14](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/3_GNPSExport.ipynb#ch0000010?line=13)[ spectra_clustering.run(consensus, input_mzml_files, out_file)

File ~/openms-develop/openms_build/pyOpenMS/pyopenms/pyopenms_1.pyx:4640, in pyopenms.pyopenms_1.GNPSMGFFile.run()

AssertionError: arg consensus_file_path wrong type]()
```

**Comment by hroest** [comment]
the argument should be 

- String
- list of strings (bytes)
- String

so something like 
```
spectra_clustering.run(b"test", [b"test"], b"test") 
```
should work

**Comment by eeko-kon** [comment]
`spectra_clustering.run(String(consensus), [b"input_mzml_files"], String(out_file))
`
This is the only version that runs without an argument error. 

There is one (other) issue though:
When I run it now, the job is crashing. It managed to run once "successfully" and produced an empty MGF file. 

Here is the error:
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyopenms/pyopenms_1.pyx", line 4649, in pyopenms.pyopenms_1.GNPSMGFFile.run
MemoryError: std::bad_alloc
```

**Comment by jpfeuffer** [comment]
Does it run on the command line with this file and settings?

**Comment by jpfeuffer** [comment]
Ah there is no tool for just the file writing.

**Comment by jpfeuffer** [comment]
Can you check the memory usage of that part? Not that it runs out.

**Comment by eeko-kon** [comment]
It instantly crashes. I m not sure how to check the memory usage if it runs out that fast (I normally use top or htop)- I deleted some large files from my laptop to make space and now I m getting a seg fault. Is there anything else I can do?

**Comment by jpfeuffer** [comment]
Ok then it probably is actually something else.

**Comment by timosachsenberg** [comment]
Can you provide me a minimal test file and python code. I can try to reproduce in C++ and debug into it.

**Comment by eeko-kon** [comment]
Absolutely

python code:

```
consensus= "results/interim/GNPSexport/filtered.consensusXML"
input_mzml_files=sorted(glob.glob("results/interim/mzML/PCfeature_*.mzML"))
out_file= "results/GNPSexport/MSMS.mgf"

spectra_clustering= GNPSMGFFile()

spectra_clustering.run(String(consensus), [b"input_mzml_files"], String(out_file))

```
Files:
[Archive.zip](https://github.com/OpenMS/OpenMS/files/8331257/Archive.zip)

[filtered.consensusXML.zip](https://github.com/OpenMS/OpenMS/files/8331253/filtered.consensusXML.zip)

**Comment by timosachsenberg** [comment]
The tool seems to work
```
GNPSExport -in_cm filtered.consensusXML -in_mzml PCfeature_20210826_UMETAB219_POS_ISP2_Plate-1_MDNAWGS11_rep1.mzML PCfeature_20210827_UMETAB219_POS_ISP2_Plate-2_MDNAWGS14_rep1.mzML -out test.mgf
```

**Comment by eeko-kon** [comment]
Yes the CLI works, it 's the binding that doesn't !

**Comment by jpfeuffer** [comment]
Ah you need to use `[s.decode() for s in input_file_mzmls]` for your second argument.

**Comment by eeko-kon** [comment]
Worked with a small correction:
`[s.encode() for s in input_mzml_files]`
