### ISSUE TITLE
Monoisotopic mass of elements is wrong in OpenMS

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#5889]
See https://en.wikipedia.org/wiki/Monoisotopic_mass

The theoretical monoisotopic mass of a molecule is computed by taking the sum of the accurate masses (including [mass defect](https://en.wikipedia.org/wiki/Nuclear_binding_energy#Mass_defect)) of the *most abundant* naturally occurring stable [isotope](https://en.wikipedia.org/wiki/Isotope) of each [atom](https://en.wikipedia.org/wiki/Atom) in the molecule.

Currently OpenMS reports the first isotope of an element, not the most abundant one:

```
pyopenms.ElementDB().getElement("He").getMonoWeight()
>>> 3.0160293191
```

see also here https://pubchem.ncbi.nlm.nih.gov/compound/Helium  

Monoisotopic Mass | 4.002603254

**Comment by timosachsenberg** [comment]
Good find
