### ISSUE TITLE
FeatureFinderMetaboIdent fix

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5894]
The spectral data information is not passed in the requantified .featureXML files like it does in FeatureFinderMetabo for example (under FeatureMap - UserParam):

`	<UserParam type="stringList" name="spectra_data" value="[path/to/rawfile.mzML]"/>
`

As a result, the requantified Feature matrix (TextExporter output) has "UNKNOWN" written next to every MAP #

**Comment by timosachsenberg** [comment]
thanks for reporting. I can take a look

**Comment by eeko-kon** [comment]
Fixed :)
