### ISSUE TITLE
More cleavage-rules for PeptideIndexer [590]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#590]
Submitted by cbielow on 2013-07-31 15:11:01

When using X!Tandem, some peptides are reported which are not strictly valid when only considering the usual KR|^P rule.

An example is:
"(Acetyl)DDAGAAGGPGGPGGPGMGNR" should match the protein (N-term)MA'DDAGAAGGPGGPGGPGMGNR'

Asking on the X!Tandem ML we got the following answer and thus believe its worth implementing the extended set of rules, such that PeptideIndexer regards these peptides as valid hits.
#### ML

The discovery of the N-terminal peptides are governed by two X!
Tandem commands.

The first command, "protein, quick acetyl" (description), can be
either "yes" (default) or "no". The purpose of this command is to
allow the detection of the most common types of eukaryotic
intracellular protein N-terminal processing: removal of one or more
N-terminal residues and acetylation of the final N-terminal
residue. An explanation of the biological processes involved can be
found in this review. It is strongly recommended that the value
should be set to "yes" for most analyses, as failure to do so will
result in 2-4% false negative assignments

The second command, "protein, quick pyrolidone" (description), can
also be either "yes" or "no".  Any free N-terminal glutamine
residue will undergo a cyclization reaction resulting in a blocked
N-terminus (reference). This reaction occurs at the protein
N-terminus (where is it usually complete) as well as at glutamine
N-terminii generated by tryptic cleavage (where it is usually
partial). N-terminal cysteines modified by iodoacetimide undergo a
similar reaction. It is also strongly recommended that this value
should be set to "yes", as this reaction is a simple first order
rate reaction which cannot be easily slowed in the storage
conditions normally used in proteomics. Failure to check for this
reaction can lead to unacceptably high numbers of false negative
assignments.

Other types of N-terminal modifications can be found iteratively
using the refine, potential N-terminus modifications command.

Ron Beavis
###### 

This ticket is related to #580.

---

Commented by johannes_junker on 2013-08-01 14:05:43:
=== References ===
- "protein, quick acetyl": http://thegpm.org/TANDEM/api/pqa.html
- Biological reference: http://www.plosbiology.org/article/info%3Adoi%2F10.1371%2Fjournal.pbio.1001074
- "protein, quick pyrolidone": http://thegpm.org/TANDEM/api/pqp.html
- Biological reference: http://books.google.ca/books?id=HdB-MXyo2ewC&pg=PA129&lpg=PA129&dq=pyrrolidone+glutamine+protein&source=bl&ots=YbY8VjvkhF&sig=uc-rhLhdXNfnoi9bh4t6YN8P_eY&hl=en&sa=X&ei=U8z3UdimKemoiALV4YGQDw&ved=0CCgQ6AEwADgK#v=onepage&q=pyrrolidone%20glutamine%20protein&f=false

"refine, potential N-terminus modifications": http://thegpm.org/TANDEM/api/refpntm.html

**Comment by hendrikweisser** [comment]
Is this issue still relevant after the updates to enzymes/digestion by @liangoaix?

**Comment by mwalzer** [comment]
Mh, I don't think the regex in [EnzymesDB.xml ](https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/CHEMISTRY/Enzymes.xml#L6) does fix this. Would be more something like  ```(?<=[^\D+{1,2}]|[KR])(?!P)```

**Comment by timosachsenberg** [comment]
The regex in EnzymesDB is the default one. But I guess in principle it should be possible using a new RegEx that covers the case.

**Comment by jpfeuffer** [comment]
Not sure if I like the closed wontfix status.
