### ISSUE TITLE
Fix for FeatureLinkerUnlabeledKD

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5906]
The pyOpenMS version of FeatureLinkerUnlabeledKD saves the map ID as the basename of the file, which is perfect. The CLI though saves it in the consensusXML as the whole path which is causing issues to the visualization of GNPS FBMN unfortunately. Is it possible to fix this? Thanks a lot!

**Comment by timosachsenberg** [comment]
I think having the whole path in the consensusXML would actually be the way to go for proper tracing of file origins. Where does the long file name end up? Is it written out in GNPSExport? Then we could change the output there

**Comment by eeko-kon** [comment]
Ok, I spotted the problem. All good. The file path does make things a bit more complicated in terms of creating the metadata table, so if we can fix that it would be perfect! 

It ends up in TextExporter (conversion of consensus to a feature quantification file). Yes, you are right that the whole path is necessary at least up to a point (it is conserved to MapAlignment, MetaboAdductDecharger, etc), but in the consensus file there is a list of Map IDs which is information that doesn't make sense to be defined by the whole path, e.g.

```
<mapList count="24">
		<map id="0" name="results/Interim/mzML/PCpeak_20210607_UMETAB211_POS_00029_DNPM_HLB70_Pl10_32.mzML" unique_id="370043800796780792" label="" size="463">
		</map>
		<map id="1" name="results/Interim/mzML/PCpeak_20210607_UMETAB211_POS_00029_ISP2_HLB70_Pl10_8.mzML" unique_id="14128626200336746421" label="" size="344">
		</map>
		<map id="2" name="results/Interim/mzML/PCpeak_20210607_UMETAB211_POS_00029_MA_HLB70_Pl10_56.mzML" unique_id="6943097361636206032" label="" size="241">
		</map>
		<map id="3" name="results/Interim/mzML/PCpeak_20210607_UMETAB211_POS_00029_soyM_HLB70_Pl10_80.mzML" unique_id="3644744885282995119" label="" size="341">
		</map>
```

That's what TextExporter takes as info :)
