### ISSUE TITLE
Deactivate DatabaseSuitability_test by default

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5907]
Only activate on our infrastructure where we have novoR.
We basically need a CMake option for that, like for CSIFingerID.

**Comment by Waschi97** [comment]
Should I also move the whole test to thirdparty testing since all tests are calling novoR internally?

**Comment by jpfeuffer** [comment]
Yes, probably a good idea.

**Comment by Waschi97** [comment]
wait... it doesn't call novoR - it calls the CometAdapter for the internal search

**Comment by Waschi97** [comment]
Using DatabaseSuitability might only be sensible if one has novoR, but the test are not depending on that. However, the tests are depending on Comet...

**Comment by jpfeuffer** [comment]
Is it depending on finding the comet executable?

**Comment by Waschi97** [comment]
yes

**Comment by Waschi97** [comment]
For suitabililty correction an additional identification search is needed. This is done by calling CometAdapter internally. And since CometAdapter is depending on the Comet executable DatabaseSuitability is as well.

**Comment by Waschi97** [comment]
However, novoR is not needed for any testing. All novoR depending files are already precalculated test files.

**Comment by Waschi97** [comment]
Since DatabaseSuitability allows for disabling the correction (nullifies the dependency on Comet) I'll also add an additional test for this.
