### ISSUE TITLE
zlib.dll not found

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5910]
User report.
DependencyWalker indiciates that we are looking for it (and in my case it was found in an unrelated folder).
![image](https://user-images.githubusercontent.com/5803621/157686965-e31fab52-bd17-4020-98c8-dd01b920fa55.png)
On my system it finds it in the contrib build folder.
D:\development\OpenMS\contrib_win64_build\lib

**Comment by timosachsenberg** [comment]
Should probably be included via:
https://github.com/OpenMS/OpenMS/blob/develop/cmake/Windows/NSIS.template.in#L241-L244

**Comment by timosachsenberg** [comment]
Our solution will be to patch the zlib cmake file to be able to choose static vs dynamic library.
Then FindZLIB should only have the correct library to pick up.

**Comment by timosachsenberg** [comment]
for documentation purposes:
changed the zlib CMakeList to either build shared or dynamic.
Created patch with:
```
diff -Naur zlib-1.2.11/CMakeLists.txt ../src/zlib-1.2.11/CMakeLists.txt > zlib_mind_libtype.patch
```
and copied to patches folder in contrib.

added:
```
set(_PATCH_FILE "${PATCH_DIR}/zlib/zlib_mind_libtype.patch")
set(_PATCHED_FILE "${ZLIB_DIR}/CMakeLists.txt")
OPENMS_PATCH( _PATCH_FILE ZLIB_DIR _PATCHED_FILE)
```
to our libraries.cmake/zlib.cmake in contrib

- commit and push to OpenMS/contrib

**Comment by timosachsenberg** [comment]
if it turns out that zlib.dll is needed by some thirdparty lib or dll we could also copy it to https://github.com/OpenMS/THIRDPARTY/tree/master/Windows/64bit and add to our windows NSIS installer / KNIME plugins

**Comment by jpfeuffer** [comment]
close until the contrary is proven
