### ISSUE TITLE
fix compile warnings on mac

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5940]
Please mark (or copy the warning if you can't tick checkboxes) the warning that you are planning to fix. If you run into troubles or don't manage to fix it in e.g. one day please uncheck the box again so someone else can take the sub issue.

- [ ] src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathOSWWriter.h:122:10: warning: private field 'sonar_' is not used [-Wunused-private-field]
- [x] src/openms/include/OpenMS/DATASTRUCTURES/Utils/MatrixUtils.h:53:3: warning: unused function 'convertOpenMSMatrix2EigenMatrixXd' [-Wunused-function]
- [x] src/openms/include/OpenMS/DATASTRUCTURES/Utils/MatrixUtils.h:67:3: warning: unused function 'matrixIsIdentityMatrix' [-Wunused-function]
- [ ] src/openms/include/OpenMS/FILTERING/DATAREDUCTION/SplineInterpolatedPeaks.h:160:16: warning: private field 'pos_min_' is not used [-Wunused-private-field]
- [ ] src/openms/include/OpenMS/KERNEL/RangeUtils.h:187:23: note: place parentheses around the '!=' expression to silence this warning - warning: ^ has lower precedence than !=; != will be evaluated first [-Wparentheses]
- [ ] src/openms/source/ANALYSIS/OPENSWATH/TransitionPQPFile.cpp:61:14: warning: unused function 'callback' [-Wunused-function]
- [ ] src/openms/source/FILTERING/CALIBRATION/TOFCalibration.cpp:198:23: warning: unused variable 'spec_iter' [-Wunused-variable]
- [x] src/openms/source/QC/DBSuitability.cpp:377:107: note: use array indexing to silence this warning - warning: adding 'OpenMS::Int' (aka 'int') to a string does not append to the string [-Wstring-plus-int]
- [x] src/openms/source/QC/DBSuitability.cpp:397:107: note: use array indexing to silence this warning - warning: adding 'OpenMS::Int' (aka 'int') to a string does not append to the string [-Wstring-plus-int]
- [ ] src/openms_gui/include/OpenMS/VISUAL/TOPPASVertex.h:191:10: warning: 'OpenMS::TOPPASVertex::paint' hides overloaded virtual function [-Woverloaded-virtual]
- [x] src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp:354:35: warning: comparison of integers of different signs: 'int' and 'OpenMS::Size' (aka 'unsigned long') [-W                                        sign-compare]
- [x] src/tests/class_tests/openms/source/AhoCorasickAmbiguous_test.cpp:431:30: warning: array subscript is of type 'char' [-Wchar-subscripts]  and 431:38: warning: array subscript is of type 'char' [-Wchar-subscripts]
- [ ] src/tests/class_tests/openms/source/LibSVMEncoder_test.cpp:543:30: warning: unused variable 'it' [-Wunused-variable]
- [x] src/tests/class_tests/openms/source/MSChromatogram_test.cpp:901:10: warning: moving a temporary object prevents copy elision [-Wpessimizing-move] - NOTE: disable the warning in the test as we intentionally use std::move here
- [x] src/tests/class_tests/openms/source/MSSpectrum_test.cpp:496:10: warning: moving a temporary object prevents copy elision [-Wpessimizing-move] - NOTE: disable the warning in the test as we intentionally use std::move here

**Comment by matchy233** [comment]
Thank you for providing those tasks for the students to start with! I think I'm going to work on the two issues related to `-Wpessimizing-move` first.

**Comment by pranavich18** [comment]
Thank you for the tasks.  I will start working on the 2nd and 3rd issue at first.

**Comment by satvik-tha-god** [comment]
Thanks!

I will handle the tasks dealing with -Wunused-variable first

**Comment by matchy233** [comment]
Maybe I'll also start to fix `-Wunused-private-field` if nobody else is gonna take it. (Also @timosachsenberg please check the issues about `-Wpessimizing-move` since the PR is merged. Thanks!)

**Comment by timosachsenberg** [comment]
sounds good! thanks!

**Comment by satvik-tha-god** [comment]
https://github.com/OpenMS/OpenMS/pull/5975

**Comment by satvik-tha-god** [comment]
#5975
