### ISSUE TITLE
Segfaults in FeatureDeconvolutionTest [595]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#595]
Submitted by hroest on 2013-08-10 12:48:21

Randomly segfaults happen in FeatureDeconvolutionTest on multiple platforms (Max OSX and Linux, gcc 4.6.3)

---

Commented by hroest on 2013-08-10 14:00:18:
Here is a backtrace done on the code of the 1.11 Release

```
#0  0x00002aaaad2cb993 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00002aaaabc447cf in std::_Rb_tree_const_iterator<unsigned long>::operator++ (this=0x2aaab5463b70)
    at /usr/include/c++/4.6/bits/stl_tree.h:269
#2  0x00002aaaabe44a86 in OpenMS::ILPDCWrapper::computeSlice_ (this=0x7fffffffb590, fm=..., pairs=..., margin_left=0, 
    margin_right=1001) at /home/hr/openmsall/gitsvn/Release1.11/source/ANALYSIS/DECHARGING/ILPDCWrapper.C:301
#3  0x00002aaaabe467e1 in OpenMS::ILPDCWrapper::compute(OpenMS::FeatureMap<OpenMS::Feature>, std::vector<OpenMS::ChargePair, std::allocator<OpenMS::ChargePair> >&, unsigned long) const [clone ._omp_fn.0] ()
    at /home/hr/openmsall/gitsvn/Release1.11/source/ANALYSIS/DECHARGING/ILPDCWrapper.C:213
#4  0x00002aaaafb37eea in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#5  0x00002aaaad77ee9a in start_thread (arg=0x2aaab5464700) at pthread_create.c:308
#6  0x00002aaaada88ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#7  0x0000000000000000 in ?? ()

```

---

Commented by hroest on 2013-08-10 15:29:37:

Here is my gdb output (4 threads are working):

```
(gdb) set print pretty on

(gdb) info threads
  Id   Target Id         Frame 
* 4    Thread 0x2aaab5464700 (LWP 30029) "FeatureDeconvol" 0x00002aaaabe44a86 in OpenMS::ILPDCWrapper::computeSlice_ (
    this=0x7fffffffb590, fm=..., pairs=..., margin_left=0, margin_right=1001)
    at /home/hr/openmsall/gitsvn/Release1.11/source/ANALYSIS/DECHARGING/ILPDCWrapper.C:301
  3    Thread 0x2aaab5263700 (LWP 30028) "FeatureDeconvol" 0x00002aaaafb39591 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  2    Thread 0x2aaab5062700 (LWP 30027) "FeatureDeconvol" 0x00002aaaafb39591 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  1    Thread 0x2aaab2e2ce40 (LWP 30015) "FeatureDeconvol" 0x00002aaaafb39591 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgomp.so.1
```

It seems that the iterator it_e that should go from iti->second.begin() to
iti->second.end() is not even in the correct range:

```
(gdb) p iti->second.begin()
$49 = {
  _M_node = 0x2aaab80be450
}
(gdb) p iti->second.end()
$50 = {
  _M_node = 0x2aaab80be930
}
(gdb) p iti->second.size()
$51 = 4
(gdb) p it_e
$52 = {
  _M_node = 0x2aaab812c7a0
}
```

Also the iterator seems to have increased already 5 times even though there are
only 4 elements in the set. Not surprisingly is the fifth element added to
columns_e corrupted, not part of the set. Next, the operation ++it_e fails with
the error from above: 

```

(gdb) p elements_e.size()
$53 = 5
(gdb) p columns_e.size()
$54 = 5
(gdb) print *(columns_e._M_impl._M_start)@columns_e.size()
$55 = {192, 198, 202, 203, -1206738464}
(gdb) print *(elements_e._M_impl._M_start)@elements_e.size()
$56 = {-1, -1, -1, -1, -1}
(gdb) p *it_e
$57 = (const unsigned long &) @0x2aaab812c7c0: 46912721035744
```

So one conclusion one could draw is that the iti->second std::set has been
moved and is not the same as when the iteration started (e.g. elements got
added and it got moved, invalidating the iterator it_e. Still, it_e now gets
compared to iti->second.end() which is the _new_ end of the std::set and it_e
will never reach it legally).

So my intuition was that another thread was modifying iti->second while it_e
was iterating over it and I have thus tried to disable threading to see whether
this removes the problem. Indeed I found that

i) with multi-threading: FeatureDeconvolution_test failed 4 / 22 times
ii) without multi-threading: FeatureDeconvolution_test failed 0 / 1212 times

One quick fix would be to comment out the OpenMP lines 208-210 in source/ANALYSIS/DECHARGING/ILPDCWrapper.C

---

Commented by cbielow on 2013-08-13 15:38:15:
temporarily fixed in [11685] by disabling OMP

thus moving to good ideas milestone, since re-enabling it would be an enhancement

**Comment by hendrikweisser** [comment]
I can't recall seeing any failures of this test, so it looks to me like the problem has been resolved.
