### ISSUE TITLE
GitHub Actions for building on Mac OS X always fails

### ISSUE THREAD

**Issue by matchy233** [OpenMS/OpenMS#5950]
It seems that the step **Fix contrib install names** in `.github/workflows/openms-ci.yml` always fails. The `*.dylib` downloaded cannot be found.

The error log is as follows:

```
error: /Applications/Xcode_[13](https://github.com/matchy233/OpenMS/runs/5569881472?check_suite_focus=true#step:7:13).2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /Users/runner/work/OpenMS/OpenMS/OpenMS/contrib/lib/*.dylib (No such file or directory)
```
Screenshot in Github Actions CI execution tab:

![image](https://user-images.githubusercontent.com/32197833/158596001-ad8d7aed-44c8-4bd5-a18f-b12de7f36b8b.png)

**Comment by timosachsenberg** [comment]
should be fixed by: https://github.com/OpenMS/OpenMS/pull/5952/files
stupid bash logic

**Comment by timosachsenberg** [comment]
probably fixed
