### ISSUE TITLE
Update manylinux2014 container

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#5964]
We should update our manylinux container since it contains python 3.10.

**Comment by timosachsenberg** [comment]
What needs to be done here?

**Comment by timosachsenberg** [comment]
In our org I find:
https://github.com/search?q=org%3AOpenMS+manylinux2014&type=code
https://github.com/search?q=org%3AOpenMS+manylinux&type=code

So I think you refer to: https://github.com/OpenMS/dockerfiles/blob/1c3fe86807fb7d8b19b6f1fbb77bb485b5f9880d/pyOpenMS/manylinux/Dockerfile
Which pulls:
https://github.com/OpenMS/dockerfiles/blob/1c3fe86807fb7d8b19b6f1fbb77bb485b5f9880d/pyOpenMS/manylinux/Dockerfile#L2
I think the default is already the latest so the first step can probably be skipped.

**Comment by timosachsenberg** [comment]
added an action to update the container https://github.com/OpenMS/dockerfiles/pull/22

**Comment by timosachsenberg** [comment]
done
