### ISSUE TITLE
MzMLHandler doesn't handle MS:1000023 isolation width [597]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#597]
Submitted by aiche on 2013-08-12 12:02:18

While the term "MS:1000023" is purgatory it still seems to be used by ProteomeDiscoverer (not sure which version was used) when exporting mzML

**Comment by hroest** [comment]
for how many people is this really an issue?

**Comment by timosachsenberg** [comment]
I think we can close it. If it is reported again we should contact Thermo but imho it is more a PD than  OpenMS issue.
