### ISSUE TITLE
Re: questions about some parameters in Open MS featurefindermetabo

### ISSUE THREAD

**Issue by JianFelixGuo** [OpenMS/OpenMS#5972]
Dear developer,

I recently found OpenMS featurefindermetabo is very useful and have been using KNIME to implement the algorithm for processing  some data. But I have some questions about certain parameters. 
1. Chrom_fwhm: Expected chromatographic peak width (in seconds). Is this the minimum or maximum peak width? Or is it an expected average peak width?
2. Trace termination outlier: default is 5. May I use this value for most cases?
3. Minimum sample rate: the default is 0.5. May I use this value for most of my data processing?

It would be greatly appreaciated if you could kindly enlighten me on these questions. Thank you!

Best,

Jian

**Comment by eeko-kon** [comment]
Hi Jian,

1) `chrom_fwhm`: (expected peak width at half maximum) it should be the expected mean, so if set to 5 it should also detect a peak with 4 or 6 sec fwhm. This means that the algorithm expects that the width of a peak at half of its maximum will be (retained over) 5 seconds. Setting this strongly depends on your chromatography. If `width_filtering` is set at `fixed`, you can set a minimum and maximum fwhm (default at 1 up to 60 seconds) at elution peak detection parameters (`epd`).

2) Trace termination outliers: This means that if on either side of a mass trace, the 5 consecutive spectra do not contain the expected m/z, the trace terminates there. If I would manually my data, I would assume that if the 5 consecutive spectra after a mass trace do not contain the expected m/z the mass trace ended. So it is reasonable, but you can of course change that parameter and see how your data behaves.

3) Min sample rate: This means that at least half of the scans along a mass trace should contain a peak for it to be recognized as part of a real mass trace. Half is reasonable, but you could be more strict or more "relaxed", depending on your data. 

I hope that helps!
Efi

**Comment by JianFelixGuo** [comment]
Hi Eeko,

Thanks for your quick reply. I am still a bit confused about chrom_fwhm. 
1. "chrom_fwhm" seems just to be an estimated mean peak width of all the peaks in my data, not a cut-off for any function. Am I right? In this case, changing this value won't affect the results much?
2. If I know the peak widths of my data is within a range of 5 sec to 60 sec. What is the best way to set this parameter in the algorithm? FWHM is not the retention time difference between two peak edges, so I cannot put the min and max peak widths values into "width_filtering" parameter. But I noticed a parameter in "mtd", min_trace_length and max_trace_length. Can I set these two values using my min and max peak width in seconds? And I will just turn off "width_filtering", and leave "chrom_fwhm" a mean peak width 32.5. Do you think it is legit?

Thanks very much!

Best,

Jian

**Comment by timosachsenberg** [comment]
Hi,
1. exactly. chrom_fwhm is mainly used internally to choose a smoothing window / kernel for the chromatogram.
2. I think I would need to check again in the source code but it could well be that setting a hard upper limit will remove peaks with very long tails (over the 60s). This might happen for a few peaks and removing those completely might not be what you want. I would probably either turn off width_filtering or set it to a higher value so that contaminant traces are removed.

**Comment by JianFelixGuo** [comment]
Thank you for your feedback.
