### ISSUE TITLE
MapAlignerPoseClustering FATAL: uncaught exception!

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5981]
This algorithm crashes from the develop-version with a specific dataset, but in TOPPAS there seems to be no problem at all (2.7.0). The error is :
```

Picking a reference (by size) ... done
Progress of 'Aligning input maps':
  20.44 %               
---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type InvalidValue occurred in line 1040, function virtual void OpenMS::PoseClusteringAffineSuperimposer::run(const std::vector<OpenMS::Peak2D>&, const std::vector<OpenMS::Peak2D>&, OpenMS::TransformationDescription&) of /home/eeko/data/OpenMS_build/OpenMS/src/openms/source/ANALYSIS/MAPMATCHING/PoseClusteringAffineSuperimposer.cpp
error message: the value '-nan' was used but is not valid; Superimposer could not compute an initial transformation!You can try to increase 'max_num_peaks_considered' to solve this.
---------------------------------------------------
Aborted
```

My parameters:

`MapAlignerPoseClustering -algorithm:max_num_peaks_considered -1 -algorithm:superimposer:mz_pair_max_distance 0.05 -algorithm:pairfinder:distance_MZ:max_difference 10.0 -algorithm:pairfinder:distance_MZ:unit ppm `

Exactly the same params were used in TOPPAS.

**Comment by enetz** [comment]
@eeko-kon can you share the input files?

**Comment by eeko-kon** [comment]
Hi @enetz , 

https://drive.google.com/drive/folders/1Z0_w_JniliNrcSwv2z5sY-cTnh7DWpIM?usp=sharing

Here you go. A bit more than 1000 files..

**Comment by enetz** [comment]
I could reproduce the error. Your input files have a large range of sizes, from < 19 kB to > 15 MB. The crash happens when the first of the very small < 1 MB files is processed. For me it was `MFD_20210618_UMETAB211_POS_00024_MA_HLB40_P7_54.featureXML`

I think some of the featureXMLs just don't have enough common features and the error message tells you what happens: `Superimposer could not compute an initial transformation!`

Possible reasons for the change between versions: in #5742 `boost::math::isnan` was replaced with `std::isnan` in the code that triggers the exception. That shouldn't give a different result, but so far I couldn't find other differences that could cause this.

**Comment by eeko-kon** [comment]
Thanks for explaining!

**Comment by enetz** [comment]
Btw. how do the results look like with TOPPAS and 2.7? Do you get the same number of result files as input files? What is the output of e.g. the file I mentioned above? If it runs through and the map was actually updated / aligned, then there might still be something wrong with the current version.

**Comment by eeko-kon** [comment]
That's a great point. Only 827 files out of 1047 were actually aligned.

**Comment by eeko-kon** [comment]
It looks like the file MFD_20210618_UMETAB211_POS_00024_MA_HLB40_P7_54 has only 5 features. It was however aligned with TOPPAS

**Comment by enetz** [comment]
I ran a Diff on the two files and the only thing that changed was an added `dataProcessing` bock with the parameters from the MapAligner. The rest of the content is exactly the same. 

I don't use TOPPAS, but it looks like it just fails more quietly, by writing out unchanged files or skipping files completely.

**Comment by eeko-kon** [comment]
Ah ok, good catch. I will try to eliminate or separate the files that create those errors then.

**Comment by eeko-kon** [comment]
Can I ask how you spotted the specific files that produce the error? I have such a large output on my terminal that it is impossible to trace the origin of the error. Plus using < out.txt to save the terminal output doesn't give me any information. Thanks again!

**Comment by enetz** [comment]
Yes, I also don't know any simple way.
The way I did it: Output files had same names as input, I looked at the last written file of the output, found it in the input list and inferred that the next file must have caused the crash.
Simple to do once, but sounds annoying to automate, and may not apply e.g. if multi-threading is used
