### ISSUE TITLE
TOPPBase: ini file plus cmd line parameter mix [599]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#599]
Submitted by timosachsenberg on 2013-08-14 13:26:32

Currently, cmd line parameters are ignored without further notice if  an ini file is provided via the -ini parameter.

---

Commented by hendrikweisser on 2013-08-15 11:34:58:
Are you sure that's generally true, and not just for generating INI files with "-write_ini"? If yes, that should be quite high priority - but it would surprise me.

**Comment by hendrikweisser** [comment]
I can't confirm the problem. Parameters passed via command line override parameters passed via .ini file.
