### ISSUE TITLE
FeatureFinderRaw and SILACAnalyzer don't write meta data to featureXML [600]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#600]
Submitted by hendrikweisser on 2013-08-15 11:40:23

Both FeatureFinderRaw and SILACAnalyzer don't include the "data processing" sections in their featureXML outputs (parameters "out" and "out_features", respectively).

**Comment by hendrikweisser** [comment]
Those tools have both been removed, making this a non-issue.
