### ISSUE TITLE
Deprecated (doxygen) Doc pages notice does not work

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6003]
Should be like in the header of https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/2.4.0/html/index.html
but on every page.

Currently does not work. The idea was to have the following:
https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/common/header.html#L42

So it gets automatically included if it is in the folder. Our jobs should add the "deprecation" file to old releases, whenever there is a new one.

Currently it seems like it needs a JS script to actually include that file. I thought it was an included HTML feature.
Probably requires an adaption of the above header.html.

**Comment by Amit0617** [comment]
however if that's small html part which i expect it would be then it should be directly added there but if you really want it to include from external html file than embed or iframe tags can be used.
Js script can also be used if you want it to happen dynamically for all the html files at once.

**Comment by jpfeuffer** [comment]
It cannot be added directly because the websites are generated automatically. We want to update the htmls only if there is a newer release. And we would need to touch EVERY html file because they all have the same header.

**Comment by timosachsenberg** [comment]
Hi @jpfeuffer can you add some more details here.
Sounds a bit difficult to automatize.
Only way might be through jenkins that adds:
1. the deprecation file to the old releases in the release action
2. figure out how the JS needs to be added such that it gets actually included?

would it make sense to add this JS everywhere and let it query if it is the latest version?

**Comment by jpfeuffer** [comment]
Yes everything works.

**Comment by jpfeuffer** [comment]
Added a version selector instead:
https://github.com/OpenMS/OpenMS/commit/27ae821b1e163f18d44668dedba6b335fc6a47e0
