### ISSUE TITLE
DatabaseSuitability tests fail on Github Actions

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6008]
Linux: Seems like they are disabled on Linux. Third-party in path?
MacOS: On macos they fail completely? No idea why. Executable name universal? Executable rights on the runner (although comet test works I think)?

**Comment by timosachsenberg** [comment]
- the name seems to be correct https://github.com/OpenMS/THIRDPARTY/tree/52b731c4677fd445a2a13cde609a42c55bff9d51/MacOS/64bit/Comet
- According to CDASH the comet tests were executed and passed but not 100% sure
e.g. this one seems to fail but the test is marked as success?
![image](https://user-images.githubusercontent.com/5803621/160561157-b8467968-ce3a-4243-b924-34ae4be2fc3b.png)

**Comment by timosachsenberg** [comment]
BTW the Comet test passes the path to the executable. Maybe this is not done in the DatabaseSuitability ?
```
/Users/runner/work/OpenMS/OpenMS/OpenMS/bld/bin/CometAdapter "-test" "-ini" "/Users/runner/work/OpenMS/OpenMS/OpenMS/src/tests/topp/THIRDPARTY/CometAdapter_1.ini" "-database" "/Users/runner/work/OpenMS/OpenMS/OpenMS/src/tests/topp/THIRDPARTY/proteins.fasta" "-in" "/Users/runner/work/OpenMS/OpenMS/OpenMS/src/tests/topp/THIRDPARTY/spectra_comet.mzML" "-out" "CometAdapter_1_out1.tmp" "-pin_out" "CometAdapter_1_out2.tmp.tsv" "-comet_executable" "/Users/runner/work/OpenMS/OpenMS/_thirdparty/Comet/comet.exe"
```

**Comment by Waschi97** [comment]
To execute the CometAdapter DatabaseSuitability reads the parameters from the given idXML and writes a temporary .ini file. This includes the path to the comet executable.

`Standard error: Process 'CometAdapter' failed to start. Does it exist? Is it executable?`
Sounds to me like the binary isn't in PATH and that's why trying to execute it fails.

**Comment by timosachsenberg** [comment]
yes but can we make it work without setting the path?

**Comment by Waschi97** [comment]
Oh, yeah.. the idXML in the test also assumes thaat the comet executable is in PATH.. It just has 'comet.exe' as its value.

We could just add two additional parameters to the DBSuitability class to pass the paths to both comet and CometAdapter.

**Comment by Waschi97** [comment]
As for Linux:
I'm not sure why all tests are disabled... At least this one should be performed:
https://github.com/OpenMS/OpenMS/blob/d39eb52eb4272bcb12190f8496be3cc28d827897/src/tests/topp/CMakeLists.txt#L227-L233
The others are disabled because comet isn't found, right? Since CometAdapter tests are also disabled.

**Comment by jpfeuffer** [comment]
> yes but can we make it work without setting the path? e.g, have a comet_executable parameter? or how can we make sure the idXML contains the correct path in the test?

I am just wondering: I thought we enabled the DBSuit test only if Comet is found in the PATH, right?
So why does it not find Comet by just calling comet.exe?




> As for Linux: I'm not sure why all tests are disabled... At least this one should be performed:
> The others are disabled because comet isn't found, right? Since CometAdapter tests are also disabled.

Not all are disabled. Yes @timosachsenberg you probably need to add Thirdparty to the action or the base container.

**Comment by Waschi97** [comment]
> Not all are disabled.
You're right. The one DatabaseSuitabilty test, that is supposed to be executed without comet, is performed. I missed it.

> I am just wondering: I thought we enabled the DBSuit test only if Comet is found in the PATH, right?
> So why does it not find Comet by just calling comet.exe?
We did! But DatabaseSuitability doesn't call 'comet.exe'. It calls the CometAdapter to skip the parsing of arguments.

**Comment by Waschi97** [comment]
We could move the argument parsing to somewhere (?) in the library and then let DatabaseSuitability also just call comet. That should fix the tests.

**Comment by Waschi97** [comment]
... and the pepxml conversion.
Hm, I remember why we decided to call the Adapter rather than comet itself.

**Comment by jpfeuffer** [comment]
Yes let's check if in PATH. Just let it be fixed.

**Comment by timosachsenberg** [comment]
@Waschi97 can you provide this fix?

**Comment by Waschi97** [comment]
Sure.
