### ISSUE TITLE
Highlight parameters that differ from defaults [601]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#601]
Submitted by hendrikweisser on 2013-08-15 12:36:29

TOPPAS (and INIFileEditor) already highlights (in yellow) parameters of a node that are being changed - but only until the changes are accepted with "OK". An option to highlight parameters that were changed from their default values (or to hide all other parameters?) would also be very useful, to make it easier to focus on the really relevant settings in a workflow. This concerns especially tools like FileFilter, with very many parameters, most of which can be ignored in any given situation.

**Comment by jpfeuffer** [comment]
I like that. Also for Knime dialogs.
