### ISSUE TITLE
Nightly pypi repo

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6045]
Promised by Tübingen almost 2 years ago. Would be much cleaner than letting people download from actions artifacts..

**Comment by jpfeuffer** [comment]
also our actions are failing because of the upload, which looks bad and leads to workarounds since we cannot use latest successful.

**Comment by timosachsenberg** [comment]
can you resend and cc us?

**Comment by jpfeuffer** [comment]
I never was in touch with anyone. This was Oliver.

**Comment by timosachsenberg** [comment]
I wrote Andreas an EMail

**Comment by poshul** [comment]
> does https://abi-services.informatik.uni-tuebingen.de/pypi/ work now?

Looks good to me.

**Comment by timosachsenberg** [comment]
hi I recall someone briefly tested that. Can that person comment?

**Comment by poshul** [comment]
`pyopenms-wheels` now runs correctly. This should mean that it get's uploaded from tonight's nightly

**Comment by poshul** [comment]
The upload step for the nightly fails with the following:
`ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         Invalid API Token: project-scoped token is not valid for project:      
         'pyopenms-nightly'    `
Is the secret we have stored up to date @jpfeuffer?

**Comment by jpfeuffer** [comment]
Probably not. Probably expired or something. We do not need a token for our own pypi server anyway. Different authentication.

**Comment by poshul** [comment]
Looks like the pypi server isn't set up right:
`WARNING  Received "500: Internal Server Error"                                  
         Package upload appears to have failed. Retry 5 of 5.                   
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 500 Internal Server Error from                              
         https://abi-services.informatik.uni-tuebingen.de/pypi/                 
         Internal Server Error                                                  `

**Comment by poshul** [comment]
I've emailed Andreas and Martin about this.

**Comment by jpfeuffer** [comment]
Not sure if they can help. I set up the server.

**Comment by poshul** [comment]
wheels action and upload now works. Downloading with PIP does not due to https://github.com/pypiserver/pypiserver/issues/155 .

**Comment by jpfeuffer** [comment]
We have no access to the webserver. I think the IT needs to do it.

**Comment by timosachsenberg** [comment]
any update here @poshul  ?

**Comment by poshul** [comment]
I've pushed IT about it, but they insist it's not an apache issue. I need to sit down with them about it.

**Comment by poshul** [comment]
I talked to Martin about this. He offered to change how the proxy was working, and set it up as something like pypi.cs.uni-tuebingen.de  @jpfeuffer would that require any changes to the server?

**Comment by jpfeuffer** [comment]
Sorry I don't know. Too long ago since I set this up.

**Comment by poshul** [comment]
fixed in https://github.com/OpenMS/OpenMS/pull/6532
