### ISSUE TITLE
The wrong of the SiriusAdapter node

### ISSUE THREAD

**Issue by hello-lei** [OpenMS/OpenMS#6047]
Hi,all
I have the question about the SiriusAdapter.
![image](https://user-images.githubusercontent.com/83147334/163957512-8a09e350-f8fb-4557-ad12-55a5e85c6335.png)
The data come from the MTBLS2018

**Comment by eeko-kon** [comment]
Can you send us the link for the data deposit? I cannot find it in MetaboLights.

**Comment by hello-lei** [comment]
of course.https://www.ebi.ac.uk/metabolights/MTBLS2108/files

**Comment by eeko-kon** [comment]
Are you sure that they provide MS2 information? From the description, I can only see that they used LC-MS to acquire the data. SIRIUS needs MS2 information to work

**Comment by hello-lei** [comment]
![image](https://user-images.githubusercontent.com/83147334/163962877-825efb7b-aef0-4def-9260-c7336159b6cd.png)
I think may be it is the data. I can't use the MSConvert to excute it.

**Comment by hello-lei** [comment]
![image](https://user-images.githubusercontent.com/83147334/163966623-eef5e1c1-ed63-40e1-a94a-7f01ff1c5b9e.png)

**Comment by hello-lei** [comment]
![image](https://user-images.githubusercontent.com/83147334/163967294-53761cb5-93d9-4842-a14f-4001eafb6411.png)

**Comment by hello-lei** [comment]
Does it have MS2 ?

**Comment by eeko-kon** [comment]
It does. Let me check the data one moment.

**Comment by eeko-kon** [comment]
If you directly download the mzml files, mind that they are in profile mode (both MS1 and MS2 data) - so you need to convert them. You can do that through msconvert or just use the FileConverter node in KNIME. 

https://hub.knime.com/openms-team/extensions/de.openms.feature/latest/de.openms.knime.nodes.FileConverter.FileConverterNodeFactory

**Comment by hello-lei** [comment]
Ok,I will try it.Thank you!

**Comment by hello-lei** [comment]
The problem became this.
![image](https://user-images.githubusercontent.com/83147334/164014872-2636cccd-4197-4365-8111-a4f775b40bd6.png)

**Comment by eeko-kon** [comment]
Hm.. ok I have one question which I don't think I'd the real problem , but why are you splitting the workflow in two parts? Meaning that you are re running File converter and peak picker twice. 

Also: it seems like you still have zero features to be processed. So Sirius has nothing to process, that's why it is probably failing. Can you send me your featureXML files and the converted mzml? You should be able to send them here compressed

**Comment by hello-lei** [comment]
ok,I will send you later



---- 回复的原邮件 ----
| 发件人 | Efi ***@***.***> |
| 日期 | 2022年04月19日 22:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [OpenMS/OpenMS] The wrong of the SiriusAdapter node (Issue #6047) |

Hm.. ok I have one question which I don't think I'd the real problem , but why are you splitting the workflow in two parts? Meaning that you are re running File converter and peak picker twice.

Also: it seems like you still have zero features to be processed. So Sirius has nothing to process, that's why it is probably failing. Can you send me your featureXML files and the converted mzml? You should be able to send them here compressed

**Comment by hello-lei** [comment]
sorry,when I send the data,It always can't upload.

**Comment by jpfeuffer** [comment]
You need to upload it somewhere else and send the link.
E.g. myairbridge.com

**Comment by eeko-kon** [comment]
I'm actually not sure if you can convert profile mzml files to centroid mzml through FileConverter (OpenMS) - it uses the thermorawfile parser exe and by default, it can convert a raw file to a centroid mzml, but it might not be able to convert mzml profile to centroid. Unfortunately, this group does not provide the raw data. 

I'm also trying to convert the files through msconvert and it fails:

`Failed - System.Exception: [References::resolve()] Failed to resolve reference. object type: struct pwiz::msdata::Software reference id: MSDK referent list: 0 at pwiz.CLI.msdata.ReaderList.read(String filename, MSDataList results, ReaderConfig config) at MSConvertGUI.MainLogic.processFile(String filename, Config config, ReaderList readers, Map`2 usedOutputFilenames) at MSConvertGUI.MainLogic.Go(Config config, Map`2 usedOutputFilenames)`

At least in my windows machine, proteowizard seems to not be able to recognize the file reference (something that also happens with .wiff files)

**Comment by hello-lei** [comment]
Yes,I have the same  problem.May be I should change the data.
Thank you very much!I will try other data.

**Comment by eeko-kon** [comment]
Yes, perhaps you should contact the authors if you need their data. They could upload the raw files (they have a directory "RAW FILES" but it is empty). No problem!
