### ISSUE TITLE
error message when reading mzML file with mzXML extension. [605]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#605]
Submitted by witek96 on 2013-09-03 14:11:09

When opening an valid mzML file with an mzXML extension the error message one gets is:

Warning: TOPPViewBase received the unknown parameter 'preferences:idview:is_relative_tolerance'!
/home/witold/prog/OpenMS/OpenMS2/source/FORMAT/HANDLERS/XMLHandler.C(103): While loading '/media/witold/data/testdata/ludovic/lgillet_L121127_001_p_msconvert.i.c.mzXML': Required attribute 'msLevel' not present!
Probable cause: The file suffix (mzXML) does not match the file content (mzML).Rename the file to fix this.

This is quite verbose and actually the relevant part comes at the end. How about such an error message layout:

Error : The file suffix (mzXML) does not match the file content (mzML).Rename the file to fix this.

TOPPViewBase received the unknown parameter 'preferences:idview:is_relative_tolerance'!
/home/witold/prog/OpenMS/OpenMS2/source/FORMAT/HANDLERS/XMLHandler.C(103): While loading '/media/witold/data/testdata/ludovic/lgillet_L121127_001_p_msconvert.i.c.mzXML': Required attribute 'msLevel' not present!
Probable cause: The file suffix (mzXML) does not match the file content (mzML).Rename the file to fix this.

**Comment by hendrikweisser** [comment]
This is such an obscure problem that I don't think it's worth keeping the ticket open.
