### ISSUE TITLE
Unable to build OpenMS library

### ISSUE THREAD

**Issue by greengypsy** [OpenMS/OpenMS#6056]
When I try and build the OpenMS library, the TOPP tools, tests and this documentation, with the "make" command, I get the following error

[  0%] Built target OpenSwathAlgo
[  0%] Automatic MOC for target OpenMS
[  0%] Built target OpenMS_autogen
[  0%] Linking CXX shared library ../../lib/libOpenMS.dylib
ld: library not found for -lzstd
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libOpenMS.dylib] Error 1
make[1]: *** [src/openms/CMakeFiles/OpenMS.dir/all] Error 2
make: *** [all] Error 2

Does anyone know how to fix this?

**Comment by jpfeuffer** [comment]
Hi!
Something is looking for the compression library zstd.
This should not happen. You have to look through all CMake logs of both contrib and OpenMS to see where this comes from.

**Comment by greengypsy** [comment]
Where are the logs stored? Sorry I'm not the best at programming.

**Comment by greengypsy** [comment]
This is in my CMakeError.log file:
/openms-development/openms_build/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx:1:10: fatal error: 'process.h' file not found
#include <process.h>
         ^~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_75fe4.dir/CheckIncludeFile.cxx.o] Error 1
make: *** [cmTC_75fe4/fast] Error 2

**Comment by jpfeuffer** [comment]
Yes, this is one of the logs but the error is unrelated.

The problem lies much deeper. You probably used some brew libraries. Some of them probably started to use zstd and forgot to update their dependencies.
Sorry but I don't know more.
It is probably boost or Qt.

**Comment by jpfeuffer** [comment]
All I can say is that the zstd dependency is not coming from us.

**Comment by jpfeuffer** [comment]
Maybe this: https://github.com/Homebrew/homebrew-core/issues/39111

But you should have an uptodate brew, right?

**Comment by greengypsy** [comment]
I tried updating brew but that am still getting the same error.

**Comment by jpfeuffer** [comment]
Then I am unfortunately out of ideas.

**Comment by greengypsy** [comment]
No worries, thanks for your help.

**Comment by timosachsenberg** [comment]
two ideas:
1. try to install zstd using brew brew install zstd
2. using boost from contrib (without brew)

**Comment by greengypsy** [comment]
Tried the first option, not sure how to implement the second option.

**Comment by greengypsy** [comment]
When I enter the cmake command, I get this message: 

-- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
-- HDF5 CXX compiler wrapper is unable to compile a minimal HDF5 program.

**Comment by jpfeuffer** [comment]
Unfortunately this is just a warning.

After CMake, you need to find a link.txt in the build folder. This tells what the compiler will try to link.
Then go through all the libraries (.dylib files) that it is trying to link and run the built-in command `otool -L` on them to see which one is pulling in libzstd.

Sorry but there is no other way to figure this out.

**Comment by greengypsy** [comment]
No worries, I appreciate your help. There is only one dylib file called **libOpenSwathAlgo.dylib**

**Comment by greengypsy** [comment]
I only found this in the link.txt file:
-o ../../lib/libOpenMS.dylib -install_name /Users/christinakumar/openms-development/openms_build/lib/libOpenMS.dylib 

This file doesn't exist

**Comment by jpfeuffer** [comment]
In Which link.txt did you look?

**Comment by greengypsy** [comment]
openms-development/openms_build/src/openms/CMakeFiles/OpenMS.dir/link.txt
and a few others...
I really don't know what I'm doing at this point...

**Comment by jpfeuffer** [comment]
sorry, but then something is completely wrong. You should have dozens of links in src/openms/CMakeFiles/OpenMS.dir/link.txt

```
../../lib/libOpenSwathAlgo.dylib /usr/local/lib/libsvm.dylib /usr/local/lib/libxerces-c.dylib /usr/local/opt/qt/lib/QtNetwork.framework/QtNetwork /usr/local/opt/qt/lib/QtSql.framework/QtSql -framework CoreFoundation -framework CoreServices /usr/local/lib/libglpk.dylib /usr/local/lib/libboost_iostreams-mt.a /usr/local/lib/libboost_date_time-mt.a /usr/local/lib/libboost_math_c99-mt.a /usr/local/lib/libboost_regex-mt.a /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libbz2.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libsqlite3.tbd /usr/local/opt/qt/lib/QtCore.framework/QtCore /usr/local/lib/libomp.dylib /Users/pfeuffer/git/contrib-build/lib/libWm5Core.a /Users/pfeuffer/git/contrib-build/lib/libWm5Mathematics.a /usr/local/lib/libCbc.dylib /usr/local/lib/libCgl.dylib /usr/local/lib/libClp.dylib /usr/local/lib/libCoinUtils.dylib /usr/local/lib/libOsi.dylib /usr/local/lib/libOsiClp.dylib /usr/local/Cellar/hdf5/1.12.0/lib/libhdf5.dylib /usr/local/opt/szip/lib/libsz.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libdl.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libm.tbd /usr/local/Cellar/hdf5/1.12.0/lib/libhdf5_cpp.dylib /usr/local/Cellar/hdf5/1.12.0/lib/libhdf5.dylib /usr/local/opt/szip/lib/libsz.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libdl.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libm.tbd /usr/local/Cellar/hdf5/1.12.0/lib/libhdf5_cpp.dylib 
```

**Comment by greengypsy** [comment]
I must have not followed the instructions properly.

**Comment by jpfeuffer** [comment]
Can you please send the complete link.txt?

**Comment by greengypsy** [comment]
[link.txt](https://github.com/OpenMS/OpenMS/files/8539640/link.txt)

**Comment by jpfeuffer** [comment]
Ah you built everything from contrib now? Ok. Then it must be Qt.
Can you run `otool -L /usr/local/opt/qt@5/lib/QtCore.framework/QtCore` ?

**Comment by greengypsy** [comment]
I just ran it and got the following output:
/usr/local/opt/qt@5/lib/QtCore.framework/QtCore:
	/usr/local/opt/qt@5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.15.0, current version 5.15.3)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2113.20.111)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60157.60.19)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 56.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1141.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1856.105.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1856.105.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)

**Comment by jpfeuffer** [comment]
hm.. can you run:
`cmake --graphviz=dependencygraph.dot .` in the build folder and then send the dot file?

**Comment by greengypsy** [comment]
[dotfile.txt](https://github.com/OpenMS/OpenMS/files/8539847/dotfile.txt)

**Comment by jpfeuffer** [comment]
Ok. It is boost::iostreams. The issue is here: https://github.com/OpenMS/contrib/issues/112

Did you ever try it with libraries from brew instead of contrib? I actually assumed you were using brew

**Comment by greengypsy** [comment]
Is it the part in bold that I need to change to run it with libraries from brew?
**cmake -DOPENMS_CONTRIB_LIBS="../contrib_build"** -DCMAKE_PREFIX_PATH="$(brew --prefix);$(brew --prefix qt5)" "../OpenMS"

**Comment by jpfeuffer** [comment]
Yes. IIRC the documentation recommends to only build libraries with contrib that are not available via brew.

**Comment by jpfeuffer** [comment]
You need to clear your build folder though

**Comment by greengypsy** [comment]
I actually did try to use the "system libraries" alternative but it doesn't have the coin library.
"Note
Until the CoinMP complete package is migrated to the coin-or-tools tap, we suggest to use our contrib version. You will then additionally need gfortran as a Fortran compiler to build.
The compression libraries bzip and zlib should come with your macOS/XCode/commandline tools."

**Comment by jpfeuffer** [comment]
Yes so just build CoinOR from contrib. Not the rest.

**Comment by greengypsy** [comment]
what command do I need to run?

**Comment by jpfeuffer** [comment]
![Bildschirmfoto 2022-04-22 um 14 02 37](https://user-images.githubusercontent.com/8102638/164710602-90fc92a7-1339-4d22-937e-091c9988ee87.png)

**Comment by greengypsy** [comment]
cmake -DBUILD_TYPE=COINOR . ?

**Comment by greengypsy** [comment]
ld: library not found for -licudata

**Comment by jpfeuffer** [comment]
Whats your cmake call for openms now?

**Comment by greengypsy** [comment]
It is still:
cmake -DOPENMS_CONTRIB_LIBS="../contrib-build" -DCMAKE_PREFIX_PATH="$(brew --prefix);$(brew --prefix qt5)" "../OpenMS"
because contrib-build is where all my libraries are

**Comment by greengypsy** [comment]
I got this from the instructions:
3. Call cmake to create the build system there

cd <path_to_OpenMS_build>
cmake -DOPENMS_CONTRIB_LIBS=<path_to_contrib_build> -[DCMAKE_PREFIX_PATH](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/common-cmake-parameters_8doxygen.html#a645302863648b762cbb5b085eb4fd8c4)="$(brew --prefix);$(brew --prefix qt5)" <path_to_OpenMS>

**Comment by jpfeuffer** [comment]
what does `brew info boost` say?

**Comment by jpfeuffer** [comment]
did you clear your contrib before building only the two missing libraries?

**Comment by jpfeuffer** [comment]
how does your link.txt look now?

**Comment by greengypsy** [comment]
Yeah I rebuilt the project from scratch.

boost: stable 1.78.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
/usr/local/Cellar/boost/1.78.0_1 (15,400 files, 463MB) *
  Poured from bottle on 2022-04-22 at 10:24:27
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/boost.rb
License: BSL-1.0
==> Dependencies
Required: icu4c ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 102,526 (30 days), 322,597 (90 days), 967,742 (365 days)
install-on-request: 28,263 (30 days), 83,363 (90 days), 224,567 (365 days)
build-error: 36 (30 days)

**Comment by greengypsy** [comment]
[link.txt](https://github.com/OpenMS/OpenMS/files/8541342/link.txt)

This is better isn't it?

**Comment by jpfeuffer** [comment]
Yes. Can you try with 
`cmake -DBOOST_USE_STATIC="OFF" -DOPENMS_CONTRIB_LIBS="../contrib-build" -DCMAKE_PREFIX_PATH="$(brew --prefix);$(brew --prefix qt5)" "../OpenMS"`
