### ISSUE TITLE
Brew boost links to ICU by default

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6057]
Brew dropped support for ALL options in ALL formulae. https://github.com/Homebrew/homebrew-core/pull/35735
-> ICU support is the default for boost
-> Linking to static boost means linking to ICU (without having any warning for it and since newer boosts 1.75? even if we do not use any ICU functionality)

We need to come up with a solution.

**Comment by jpfeuffer** [comment]
The minimum we have to do is update the documentation that you cannot build with static boost anymore

**Comment by jpfeuffer** [comment]
https://github.com/boostorg/boost_install/issues/47

**Comment by poshul** [comment]
Need to update docs to say that we use dynamic linking of libs instead.
