### ISSUE TITLE
compressed mzXML leads to NaNs on Windows [607]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#607]
Submitted by witek96 on 2013-09-05 10:37:34

Plaese see attached image. On the left TOPPView 1.11 under windows on the right TOPPView 1.11 on Linux displaying exactly the same file.
I do not attach the mzXML, but can provide it to the ticket taker.

regards

---

Commented by cbielow on 2013-09-05 11:28:37:
So, your picture is trying to say that both the intensities and even the presence of peaks is different?! Or is it the axis labeling or what?

The spectrum selection indicates that you might compare apples with oranges (#8 on Win, #9 on Linux), but it might just be a pre-selection. Impossible to tell just from the picture.

So, can you please confirm that we see the exact same spectrum. If its just this spectrum, you can easily attach it, since its just a few KBs.

---

Commented by witek96 on 2013-09-05 11:43:53:
Hi Chris,

I see you doubt. I doubted too but. Please find attached the 2D view of the same dataset on windows and linux.

---

Commented by witek96 on 2013-09-05 11:54:04:
It is not fun creating tickets attaching screenshots (especially having a limit of 250K). 

---

Commented by witek96 on 2013-09-05 11:58:13:
I send you the mzXML file with our Cifex download. regards

---

Commented by cbielow on 2013-09-05 14:17:46:
I can confirm the screenshots (both 1D and 2D).
The reason is that the data in the mzXML file is partially interpreted as 'nan' by our parser -- but only on Windows. Linux seems fine.
This leads to this weird display behaviour.

Workaround: convert this mzXML file using PWiz to mz(X)ML (both work) WITHOUT COMPRESSION, which OpenMS can then read.

When converting the original mzXML to mzML using FileConverter, the nan's remain. Creating dta2D gives data like
# SEC    MZ  INT

3000.06 nan 2.59712
3000.06 nan nan
3000.06 nan nan
3000.06 nan nan
3000.06 69.0713154294649    15.8147

So, the reason is that the spectra in the original mzXML are zlib compressed by PWiz and our Windows implementation cannot correctly uncompress.

---

Commented by witek96 on 2013-09-05 15:42:26:
The reason is that the data in the mzXML file is partially interpreted as 'nan' by our parser -- but only on Windows. Linux seems fine.
This leads to this weird display behaviour.

??? are there nans in the data actually (? I am just checking with mzR and can't see any).

**Comment by timosachsenberg** [comment]
still marked as major defect. any update on this or change to minor defect?

**Comment by cbielow** [comment]
this is major IMHO and warrants fixing.

**Comment by poshul** [comment]
What's the status on this? Is it still an issue in 2021?

**Comment by poshul** [comment]
Closed. Stale
