### ISSUE TITLE
`spectrum_reference` in MSFraggerAdapter output 

### ISSUE THREAD

**Issue by zhuchcn** [OpenMS/OpenMS#6071]
The `spectrum_reference` of PeptideIdentifications in MSFraggerAdapter's output idXML are set to the scan number, as `scan=XXX` but not the original ID, so the `spectrum_reference` is no longer consistent with the mzML file. This may affect downstream tools such as IDMapper or ConsensusID?

**Comment by timosachsenberg** [comment]
@tillenglert can you comment?

**Comment by zhuchcn** [comment]
Actually yes! It's stored as an attribute of `native_id` in the `spectrum_query` tag. Should be an easy fix.

**Comment by tillenglert** [comment]
I can include the native_id as spectrum reference later today and create a PR. I was mainly using the pepXML for my results, which is probably the reason it did not create a problem for me.

**Comment by timosachsenberg** [comment]
solved in https://github.com/OpenMS/OpenMS/pull/6078
