### ISSUE TITLE
Conversion to New ID Data structure not complete

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#6096]
Conversion of an IDXML file to the sqllite format (OMS) does not work out of the box.

**To reproduce**: use a PeptideIndexer run from the TOPP tests:

```
IDFileConverter -in openms/src/tests/topp/PeptideIndexer_10_output.idXML -out bla.oms
Progress of 'Loading...':
-- done [took 2.09 s (CPU), 2.12 s (Wall)] --
Progress of 'Storing...':

  Progress of 'converting protein identification runs':
Error: Unexpected internal error (score type must have a name (as part of its CV term))
```

**Comment by timosachsenberg** [comment]
Maybe it is good to enforce a score type. Using the force flag we could allow missing ones e.g. set to unknown score

**Comment by jpfeuffer** [comment]
But I mean they do not really have a score. They only have a score because our idXML requires a score. And it is a nonsense score

**Comment by jpfeuffer** [comment]
I would say if a protein does not have a score name, don't add this nonsense score.

**Comment by timosachsenberg** [comment]
But only if force is set or always? Because discarding it "always" could be very unexpected if someone just forgot to set a score name. I think in this case we should probably still fail or at least warn.

**Comment by jpfeuffer** [comment]
Warn but per default discard. If you want you can force the loading with "unknown" as a name.

**Comment by timosachsenberg** [comment]
Score type creation:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/METADATA/ID/IdentificationDataConverter.cpp#L66
Exception is thrown on registering the score type:
https://github.com/OpenMS/OpenMS/blob/52e6c131b633ff26302d10f6e04f78fb83f58270/src/openms/source/METADATA/ID/IdentificationData.cpp#L195

@hendrikweisser what is the proper way here? omit the applied processing step? or just not set a score?
```
        ID::AppliedProcessingStep applied(step_ref);
        applied.scores[prot_score_ref] = hit.getScore();
        parent.steps_and_scores.push_back(applied);
        id_data.registerParentSequence(parent);
```
in https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/METADATA/ID/IdentificationDataConverter.cpp#L125-L128

**Comment by hendrikweisser** [comment]
> what is the proper way here? omit the applied processing step? or just not set a score?

Just not set a score. You can have a processing step (with associated information, input files etc.) without a score.

**Comment by timosachsenberg** [comment]
I can make a quick PR on Gitpod that e.g. @cbielow could test.

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/pull/6097

**Comment by cbielow** [comment]
Conversion now proceeds a few steps more, but for a large file aborts with
```
 Progress of 'converting peptide identifications':
Error: Unexpected internal error (score type already exists with opposite orientation)
```

**Comment by cbielow** [comment]
ok, the problem is that both ProteinIdentification and PeptideIdenfication are both of score type 'XTandem' with opposite orientations.

Apart from that, the benchmark looks very promising on this one large dataset:
```
  Loading a 317 MB idXML: 24 seconds
  Writing the corresponding OMS file: 13 seconds with 112 MB
```

Thus, reduction in size to `30%` while writing OMS is `2x` as fast as reading idXML - however writing the same dataset as idXML only takes 7 seconds, so writing vs. reading idXML is already `4:1`.

**Comment by jpfeuffer** [comment]
Those are very unspecific score names and they should be changed. And they should not have opposite orientations. I guess the converter is fine complaining about that. We might want to prefix score types with "protein-level" since for idXML it is implied and not at all common or supported to prefix.
