### ISSUE TITLE
Prerequisites installer SSL support missing

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6099]
```
There has been an error.  
SSL support was not enabled for this installer
The application will exit now.
```
https://forum.knime.com/t/openms-prerequisite-installer-shows-ssl-not-enabled-for-this-installer/39340

**Comment by jpfeuffer** [comment]
Please regenerate for 2.7 and make sure it works as soon as we release 3.0

**Comment by timosachsenberg** [comment]
I am renewing our open source license. Might be good to convert this https://github.com/OpenMS/OpenMS/issues/6100
to wix .

**Comment by timosachsenberg** [comment]
I uploaded an updated 2.7 installer and the 3.0 installer here https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/PrerequisitesInstaller/
can we get someone to test it?
