### ISSUE TITLE
[DOXYGEN] Move non-internal wiki entries to doxygen to reduce #docs

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6111]
Try to include as Markdown first and see if doxygen support is complete enough.

Move

- [ ] coding conventions
- [ ] faq

**Comment by tapaswenipathak** [comment]
Ref: https://github.com/OpenMS/OpenMS-docs/issues/4#issuecomment-1125150286.

**Comment by greengypsy** [comment]
There are some pages which we have decided to transfer to openms-docs that have links to pages that we want to keep in the original repository. Can we transfer all pages that are linked to openms-docs?

**Comment by jpfeuffer** [comment]
Sorry, I don't understand the question. Can you elaborate?
