### ISSUE TITLE
pyOpenMS stuck at 2.7.0 on PyPI

### ISSUE THREAD

**Issue by Kastakin** [OpenMS/OpenMS#6115]
I don't know if this is an issue or it is intended but the pyOpenMS package on PyPI is stuck at version 2.7.0 while the docs are referring to 2.8.0 with some of the feture presented not appearing until 3.0 (i.e. Pandas DataFrame conversion).

**Comment by jpfeuffer** [comment]
2.8 is indeed missing but 3.0 is the dev version and only available via conda or our nightly wheels.

**Comment by jpfeuffer** [comment]
We need to fix the action on the release branch and retrigger. Or upload manually.
https://github.com/OpenMS/OpenMS/actions/runs/1882314295
