### ISSUE TITLE
Question: FloatDataArrays create dummy dataProcessing for every spectrum?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6118]
Why?
https://github.com/jpfeuffer/OpenMS/blob/5f35554242dab269a291bdfdfa564657093fe822/src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp#L5016-L5016

You get thousands of:
```
>               <dataProcessing id="dp_sp_39_bi_0">
>                       <processingMethod order="0" softwareRef="so_default">
>                               <cvParam cvRef="MS" accession="MS:1000544" name="Conversion to mzML" />
>                               <userParam name="warning" type="xsd:string" value="fictional processing method used to fulfill format requirements" />
>                       </processingMethod>
>               </dataProcessing>
```

**Comment by timosachsenberg** [comment]
hmm not sure. I think it would be sufficient to create one and just reference it.
I thought we did that and use a shared ptr for that.

**Comment by timosachsenberg** [comment]
another idea is that this is to make the multiple DTA files to single mzML conversion work

**Comment by jpfeuffer** [comment]
I don't understand the second comment about DTA. Would that change the fact that it is completely useless to have thousands of dummy processing steps?
I would understand if they had different information in them (e.g. an ID). But like this?
