### ISSUE TITLE
Implement peptide-level FDR

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6129]
Just use "annotate_best_per_peptide" and only use annotated PeptideHits for FDR calculation.
Or just filter best_per_peptide completely. I don't think second-best PeptideHits/PSMs make much sense after peptide FDR.

**Comment by timosachsenberg** [comment]
where should this be added? Can you add some details? or do take on this

**Comment by jpfeuffer** [comment]
Yes FalseDiscoveryRate.
Just give each PSM of the same peptide the same score.
PSM q-value will be a metavalue if both exist.
I think you can even call it peptide q-value. We should not have any/many dependencies on scores being called q-value.
Make sure it is categorized correctly in IDScoreSwitcher.

**Comment by timosachsenberg** [comment]
best per run or per all runs?

**Comment by jpfeuffer** [comment]
Whatever we do for the other modes

**Comment by jpfeuffer** [comment]
I think it is per run

**Comment by jpfeuffer** [comment]
But you don't have to care. The score extractor etc. will do everything. You just have to add the tagging and update the score extractor to only collect the tagged scores.

**Comment by timosachsenberg** [comment]
k I can give it a shot
