### ISSUE TITLE
"no cleavage" not supported for X!Tandem and Comet

### ISSUE THREAD

**Issue by zhuchcn** [OpenMS/OpenMS#6133]
Currently "no cleavage" isn't supported for X!Tandem and Comet. We are doing some peptide searching so we don't want any enzyme cleavage at all. For Comet, this can be done by specifying the enzyme as "No_cut" and adding an additional entry of "No_cut" to the end of the comet params file. This is suggested by the Comet developer ([see here](https://groups.google.com/g/comet-ms/c/HzhSreCUm_E/m/vQV5kYLLBQAJ)) and also is supported in the latest Comet release. For X!Tandem, we asked the developers but we lost the reference. So it can be done using `[Z]|[Z]`. We already implemented these changes (see below) and had tested it on our test data. Let me know how you guys think and we are happy to submit a PR!

https://github.com/OpenMS/OpenMS/compare/89dd3df90df49d5374c4920b28210de125e2154c...zhuchcn:uclacds-develop

**Comment by timosachsenberg** [comment]
Hi, sounds like a great addition! Yes, please open a PR. The code looks fine on a quick look.

**Comment by cbielow** [comment]
please feel free to submit a PR.
Thanks!
