### ISSUE TITLE
XTandemAdapter not compatible with mzML files from FileConverter

### ISSUE THREAD

**Issue by enetz** [OpenMS/OpenMS#6135]
Windows 10, (almost) current develop build.
Converted a Thermo RAW file into mzML with the `FileConverter` (ThermoRawFileParser).
Tried running an X!Tandem search with our XTandemAdapter (using the `tandem.exe` from our THIRPARTY repo)
and got this error message:

```
X! TANDEM Vengeance (2015.12.15.2)
Loading spectra| (mzML).
> occurred 2 times
Fatal error: unsupported CODEC used for mzML peak data (CODEC type=zlib compression).

Standard error: Process 'C:/DATA/Development/THIRDPARTY/bin/tandem.exe' did not finish successfully (exit code: ├Â). Please check the log.
```

**Comment by jpfeuffer** [comment]
Yes xtandem does not support compression. Please deactivate it in the converter.

**Comment by timosachsenberg** [comment]
k sound like this is an X! Tandem problem.
What we could do:
- Expose the 
ThermoRawFileParser
 -z, --noZlibCompression    Don't use zlib compression for the m/z ratios and
                               intensities. By default zlib compression is
                               enabled.
flag in FileConverter so users can still use the FileConverter tool.

**Comment by enetz** [comment]
I made a fix for this by adding a flag to FileConverter, and wanted to add a test, but noticed that currently we don't have any tests for FileConverter that use RAW files as input. Does anyone have a very small RAW file, with only a few spectra for such tests? I don't think we can filter an mzML and convert it to a Thermo RAW file, right?

**Comment by timosachsenberg** [comment]
No and I think it is hard to get so small raw files unfortunately.

**Comment by timosachsenberg** [comment]
I think we need to omit the test. the smallest one I found was still 80mb
