### ISSUE TITLE
Mac: KNIME plugins fail to install

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6146]
An error occurred while installing the items
session context was:(profile=KNIMEProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]de.openms.macosx.x86_64 2.7.0.202109131426, action=org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.ChmodAction).
The action chmod failed - file /Applications/Massspec_tools_softwares/KNIME 4.5.2.app/Contents/Eclipse/plugins/de.openms.macosx.x86_64_2.7.0.202109131426/payload/bin/SequenceCoverageCalculator does not exist.

I have checked the folder…./payload/bin and there is no such file “SequenceCoverageCalculator

**Comment by yhsongk** [comment]
The solution was there in the OpenMS tutorial booklet on p. 17: 
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/knime-plugin/updateSite/nightly/

**Comment by timosachsenberg** [comment]
Thanks for the feedback. Just to confirm - it now works with the nightly builds?

**Comment by yhsongk** [comment]
> Thanks for the feedback. Just to confirm - it now works with the nightly builds?

Yes, now I can download OpenMS workflows in KINME, however after doing so, there are other issues, like:
 Some "Entry parameters are not found": in detail, it looks like as following:

Entry for parameter MSGFPlusAdapter.1.reindex not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.decoy_string not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.decoy_string_position not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.missing_decoy_action not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.write_protein_sequence not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.write_protein_description not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.keep_unreferenced_proteins not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.unmatched_action not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.aaa_max not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.mismatches_max not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.IL_equivalent not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.allow_nterm_protein_cleavage not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.enzyme.name not found in settings.xml.
- Entry for parameter MSGFPlusAdapter.1.PeptideIndexing.enzyme.specificity not found in settings.xml.

WARN  XTandemAdapter       0:304:0:5  Errors loading flow variables into node : 
GenericKNIMENodes:
Maybe you are loading node settings (or a complete workflow) generated with an older version of the tool.
If you do not reconfigure the node (marked with an exclamation mark),
the current defaults will be loaded instead. 
- Entry for parameter XTandemAdapter.1.reindex not found in settings.xml.
- Entry for parameter XTandemAdapter.1.PeptideIndexing.decoy_string not found in settings.xml.
- Entry for parameter XTandemAdapter.1.PeptideIndexing.decoy_string_position not found in settings.xml.
- Entry for parameter XTandemAdapter.1.PeptideIndexing.missing_decoy_action not found in settings.xml.
- Entry for parameter XTandemAdapter.1.PeptideIndexing.write_protein_sequence not found in settings.xml.
- Entry for parameter XTandemAdapter.1.PeptideIndexing.write_protein_description not found in settings.xml.

and goes on to ...
WARN  CometAdapter         0:304:0:116 Errors loading flow variables into node : 
GenericKNIMENodes:
Maybe you are loading node settings (or a complete workflow) generated with an older version of the tool.
If you do not reconfigure the node (marked with an exclamation mark),
the current defaults will be loaded instead. 

Where do I get those entry parameters?
Thanks for your help!

**Comment by timosachsenberg** [comment]
Writing this here as well so it gets documented:
Can you reconfigure the node in question and save the workflow?
If you close and open the workflow again, do you still get the same warnings?
Can you then execute the workflow (assuming that you selected input files on your PC)?

**Comment by yhsongk** [comment]
Yes, I reconfigured and saved the workflow and I even exited the program Knime and restarted. I have the data "BSA1_F1.mzML" on my computer (MacOS) and executed. I get the same error messages. Thanks for your help!

**Comment by jpfeuffer** [comment]
I think you need to reconfigure every node separately and click "apply". You might need to change something in the dialog and change it back (not sure).
