### ISSUE TITLE
Remove wildmagic dependency

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6155]
Wildmagic is a dependency of OpenMS that is usually poorly supported by distributions/package repositories.
This means we always need to ship it with out code (currently in the OpenMS/contrib repository).

As we only use a handful of functions it would be great to just implement those (e.g., in the Math namespace of OpenMS and get rid of the dependency).

Current use:
https://github.com/OpenMS/OpenMS/search?q=Wm5

Replace our current use of Wm5 with own implementation.
Our own implementation could use the eigen library (if needed) as this dependency is already in OpenMS.

**Comment by matteopilz** [comment]
Should we use the Eigen library or do something ourselves? Matrix is already an OpenMS datastructure, should we add vector2d as well?

**Comment by timosachsenberg** [comment]
I think one of the HiWi students is already looking into it. I would say one can use eigen if needed or if it would reduce the length of the implementation.

**Comment by jpfeuffer** [comment]
I think the only thing that is missing was some kind of regression function.
Yes you probably need eigen for that.

**Comment by jpfeuffer** [comment]
And an interpolation I see. Both nothing fancy IMHO, so could be reimplemented or use some header only code.
