### ISSUE TITLE
Evaluate if we can replace QSql with a modern library

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6161]
See https://github.com/OpenMS/OpenMS/issues/5781
and the trouble QSql causes.
List of potential libraries contained in the linked issue

**Comment by poshul** [comment]
I took a look at this yesterday, https://github.com/keramer/sqlite_modern_cpp appears to have the functionality necessary, but the coding style for it is very different than qsql (using >> and << operators). https://github.com/iwongu/sqlite3pp looks more similar to QSQL. The https://github.com/fnc12/sqlite_orm requires us paying 50$ in order to get the BSD license. Most of the others (I haven't been exhaustive in my searching) look quite old.

**Comment by timosachsenberg** [comment]
what about https://github.com/SRombauts/SQLiteCpp ?

**Comment by poshul** [comment]
That looks good actually, I missed that one since it was right above the giant list.

**Comment by hendrikweisser** [comment]
> what about https://github.com/SRombauts/SQLiteCpp?

That one doesn't support "named binds" in queries (only by index), which I see as a major downside.

**Comment by hendrikweisser** [comment]
I would also mention SOCI (https://github.com/SOCI/soci), which supports many DB systems -  not just SQLite. That one uses stream operations (`<<`) a lot, too.

**Comment by cbielow** [comment]
just a few thoughts:
some of the libs mentioned above have a) not been touched for a few years (which probably means they are dead) b) are not cross platform (no cmake). If any of these is true, I would not touch them.

SOCI looks nice -- there are even unit tests for sqlite3.. whohoo. It requires the sqlite3 C library -- but I guess this is true for all of them?! (this makes managing dependencies a bit more tricky though.)

**Comment by jpfeuffer** [comment]
But that is the reason why we are switching. We are already depending on the SQLite3 C library for OSW. We just need to make sure that the same one that is compiled into OpenMS is used. At least we have control over that, when not using Qt.

**Comment by cbielow** [comment]
It may be worth to find a header only Lib and put that directly into OpenMS, similar to Evergreen. Then the build system would be much simpler to set up. Ideally a BSD3 licensed lib.

**Comment by jpfeuffer** [comment]
Yes that would be easiest but we could also use the ExternalProject commands from CMake, make sure we find a common unique SQLite3 first then build the wrapper library and use the produced target to easily link against it.

We could in general think about moving the contrib scripts into the OpenMS build script. We could try to find installed libraries first and only download and build them on demand when not available.

**Comment by timosachsenberg** [comment]
I think this can be closed... right?
