### ISSUE TITLE
Delete uncrustify config and uncrustify_branch.sh file

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/OpenMS#6165]
file: https://github.com/OpenMS/OpenMS/blob/develop/tools/uncrustify.cfg and https://github.com/OpenMS/OpenMS/blob/develop/tools/uncrustify_branch.sh.

Ref: https://github.com/OpenMS/OpenMS-docs/pull/65#issuecomment-1146649107.

cc @jpfeuffer.

**Comment by jpfeuffer** [comment]
I vote yes.

**Comment by matteopilz** [comment]
Do we not need the [uncrustify_branch.sh](https://github.com/OpenMS/OpenMS/blob/develop/tools/uncrustify_branch.sh) anymore as well?

**Comment by tapaswenipathak** [comment]
what does 👎 mean? is it required or not?

**Comment by jpfeuffer** [comment]
@timosachsenberg ping. He probably means no, it is not needed anymore.

**Comment by timosachsenberg** [comment]
Can go
