### ISSUE TITLE
Rename "The OpenMS Proteomics Pipeline" to "The OpenMS PiPeline"

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6168]
Rename "The OpenMS Proteomics Pipeline" to "The OpenMS PiPeline" (except in citations) to better address that we also do other research fields.

**Comment by Abdullah-Afzal-00** [comment]
Can I do this contribution?

**Comment by timosachsenberg** [comment]
Yeah sure! The only places I think it shouldn't be replaced is when citing the original publication (which used the old name). Would be great if you could do a search across the OpenMS repositories to get an overview what needs to be changed.

**Comment by Telomelonia** [comment]
@timosachsenberg 
I added the PR for this.
