### ISSUE TITLE
MSSimulator (MS2): wrong m/z values for overlapping precursors [617]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#617]
Submitted by hendrikweisser on 2013-10-24 18:15:36

When "regular" MS2 spectra are simulated by MSSimulator (parameter: "RawTandemSignal:status=precursor"), multiple overlapping features may contribute to the MS2 (controlled by parameter "RawTandemSignal:precursor:selection_window"). Multiple precursors are recorded for the MS2 in this case.

The problem: The m/z values stored for these precursors are the (monoisotopic/centroid) m/z values of the features, which may be quite far away from the position of the actual precursor peak (much farther than "selection_window"). To add to the inconsistency, the precursor intensity that is stored seems to come from the peak, not the feature, and it can apparently be zero.

---

Commented by hendrikweisser on 2013-10-24 18:19:22:
Addendum: This leads to problems in TOPPView, where the position for displaying an MS2 precursor comes from the first precursor that is stored for the MS2 - which may be one with a misleading m/z value. In other words, the MS2 is not shown where it should be.

**Comment by jpfeuffer** [comment]
I think this is worth fixing at some point. Seems like the Simulator needs quite some rework in general. Maybe we can collect issues with it in a merged issue or project.

**Comment by timosachsenberg** [comment]
MS simulator has been removed
