### ISSUE TITLE
TextExporter extra information

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#6170]
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/TextExporter.cpp

Could you possibly add `out.writeValueOrNan(best ion)` to pass the **adduct** information from the consensusXML to the tsv file? Like in GNPSexport for the FeatureQuantificationTable. That is of course called dc_charge_adducts in a featureXML... So it complicates things a little..

**Comment by axelwalter** [comment]
That's of course possible. Another option would be to set an extra flag to export meta values for consensusXML files. This can already be done with a featureXML file with the `-feature:add_metavalues` flag.
Let's ask other opinions on this topic, maybe @jpfeuffer or @timosachsenberg can comment?

**Comment by eeko-kon** [comment]
That's a great idea actually. Then we could also avoid the confusion between the featureXMLs and consensusXMLs.

**Comment by axelwalter** [comment]
Solved with #6208
