### ISSUE TITLE
Check KNIME 4.6 compatibility

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6175]
What needs to be done here?

**Comment by jpfeuffer** [comment]
Probably not much, but they require no security risks in community plugins and we have too many dependencies in GKN.
Will be a very long process.

**Comment by jpfeuffer** [comment]
I reduced dependencies in GKN to a minimum and updated them.
Still Knime also checks nonJava DLLs and external jars.
And especially Sirius has many old ones. Let's check with Sirius 5 but we should really really split it from the rest of third-party also because of licensing.

**Comment by jpfeuffer** [comment]
IMHO even in our installers.

**Comment by jpfeuffer** [comment]
Works. Even with 5.0
