### ISSUE TITLE
Check if dashboards for github actions would work for our CI use cases

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6176]
E.g., we now have many actions in different repos.
Having a single page a maintainer needs to check would simplify things a lot.
https://github.com/chriskinsman/github-action-dashboard

**Comment by rahul799** [comment]
I will take this issue.

**Comment by rahul799** [comment]
@timosachsenberg @jpfeuffer in order to deploy the dashboard, we will be needing a server that can run docker or is compatible to nodejs applications. Do we have access to any servers ?

**Comment by timosachsenberg** [comment]
I see… I was hoping that would work with some webhook etc. magic that updates a GitHub io page. E.g. without infrastructure that needs to be maintained by us

**Comment by rahul799** [comment]
Ni issues, so can we close this issue?

**Comment by timosachsenberg** [comment]
Other idea:
![image](https://user-images.githubusercontent.com/5803621/174242688-1b3ce4bd-0577-4d42-ad49-f0be171f7b5d.png)
can this status be used? Maybe it would already be good enough to just have one page (e.g., one .md file in a repo) with tables and the buttons in there?

**Comment by rahul799** [comment]
Great Idea. I will investigate further.
