### ISSUE TITLE
Indentation on developer faq is incorrect

### ISSUE THREAD

**Issue by greengypsy** [OpenMS/OpenMS#6177]
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/developer_faq.html
<img width="1116" alt="Screen Shot 2022-06-13 at 8 28 27 pm" src="https://user-images.githubusercontent.com/31978630/173339465-477949c8-7336-45a3-b49f-4840b3e97d99.png">

**Comment by tapaswenipathak** [comment]
Please use `closes #issue-number` or `fixes #issue-number` to close the issue as soon as the pr is merged.

ref: https://github.com/OpenMS/OpenMS/pull/6186.
