### ISSUE TITLE
Add stable link per platform to latest nightly on archive

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6184]
Jenkins ntly job needs to relink to the newest date right after upload.
See https://github.com/OpenMS/OpenMS-docs/issues/101

**Comment by poshul** [comment]
add post-build action to create/update links in `openmsinstaller/latest.[dmg,exe,deb]` and `documentation/latest.[dmg,exe,deb]` to the nightly deploy Jenkins setup https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/job/deploy/configure

**Comment by jpfeuffer** [comment]
@poshul What do you mean with documentation/latest.exe?

**Comment by poshul** [comment]
I was referring to which folder relative to the openms build archive. I've had a try at getting this working today. The good news is that the documentation does upload in such a way that the latest version is at a stable link. I've added a post-build exec command to the nightly deploy script:
```sh
for SUFFIX in 'macOS.dmg' 'Debian-Linux-x86_64.deb' 'Win64.exe'
do
    pwd
    echo OpenMS-$VERSION-pre-nightly-$DATE-$SUFFIX
    ln -f -s OpenMS-$VERSION-pre-nightly-$DATE-$SUFFIX OpenMS-$VERSION-pre-nightly-latest-$SUFFIX
done
```
It executes, but doesn't appear to create the links like it is supposed to. Any insights?

**Comment by jpfeuffer** [comment]
A post script will run in the workspace. You need to use the SCP/SSH post command to do this on the archive.
Please call the binaries OpenMS-nightly-$OS.xyz or something like that. No one will remember what the installer is for, after it was downloaded, if it is only called macOS.dmg

**Comment by poshul** [comment]
This is with the script running in a SSH post command. It definitely runs because when I fed it the wrong directory it returned an exit code. I'm just gonna move it to a separate action to see if there's something weird.

**Comment by jpfeuffer** [comment]
But it seemed to work right? What are you trying now?

**Comment by poshul** [comment]
I set the action to log verbosly, and the ln command itself to output on success. Here's what I get:
```sh
SSH: EXEC: STDOUT/STDERR from command [for SUFFIX in 'macOS.dmg' 'Debian-Linux-x86_64.deb' 'Win64.exe'; do	ln -v -f -s OpenMS-$VERSION-pre-nightly-$DATE-$SUFFIX OpenMS-$VERSION-pre-nightly-latest-$SUFFIX; done
] ...
SSH: EXEC: connected
'OpenMS--pre-nightly-latest-macOS.dmg' -> 'OpenMS--pre-nightly--macOS.dmg'
'OpenMS--pre-nightly-latest-Debian-Linux-x86_64.deb' -> 'OpenMS--pre-nightly--Debian-Linux-x86_64.deb'
'OpenMS--pre-nightly-latest-Win64.exe' -> 'OpenMS--pre-nightly--Win64.exe'
SSH: EXEC: completed after 201 ms
```
So there's clearly an issue with the variables (do they not persist between Jenkins steps?), but I flat out can't find the files it refers to, or the links that it creates on the build-archive.

**Comment by jpfeuffer** [comment]
They do persist across steps. But you are creating variables in the shell script. 
I don't think any build automation will ever reuse the complete environment without explicitly exporting the variable. Different steps may even be executed on different computers.
Therefore you need an EnvInject step or something like that.
Or just link to the latest artifact and don't use date.

**Comment by poshul** [comment]
I ended up reverting Jenkins, and just doing this with the Crontab instead.

**Comment by jpfeuffer** [comment]
@poshul I added a corrected Exec command to the Jenkins job. You can delete the crontab entry.

**Comment by poshul** [comment]
> @poshul I added a corrected Exec command to the Jenkins job. You can delete the crontab entry.

Done.

**Comment by poshul** [comment]
> @poshul I added a corrected Exec command to the Jenkins job. You can delete the crontab entry.

This is not working. Latest still points to the 15.2 version

**Comment by poshul** [comment]
Scratch that, there's just leftovers with slightly different names from the cronjob. I'll clean them up now.
