### ISSUE TITLE
Pyopenms builds failing

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6192]
home/jenkins/ws/openms/PR/pyOMSDckr/OpenMS-build/pyOpenMS/pyopenms/pyopenms_4.cpp: In function 'PyObject* __pyx_pf_8pyopenms_10pyopenms_4_24TargetedSpectraExtractor_46storeSpectraTraML(__pyx_obj_8pyopenms_10pyopenms_4_TargetedSpectraExtractor*, PyObject*, __pyx_obj_8pyopenms_10pyopenms_3_FeatureMap*, __pyx_obj_8pyopenms_10pyopenms_3_FeatureMap*)': /home/jenkins/ws/openms/PR/pyOMSDckr/OpenMS-build/pyOpenMS/pyopenms/pyopenms_4.cpp:228184:31: error: 'boost::shared_ptr<OpenMS::TargetedSpectraExtractor>::element_type {aka class OpenMS::TargetedSpectraExtractor}' has no member named 'storeSpectraTraML'; did you mean 'storeSpectraMSP'?

This was not caught since pyopenms builds are failing since half a year.

**Comment by jpfeuffer** [comment]
@bertrandboudaud Is that related to your changes?

**Comment by bertrandboudaud** [comment]
yes, storeSpectraTraML has been renamed into constructTransitionsList and one parameter has been added. 
I'm going to fix that asap.

**Comment by bertrandboudaud** [comment]
Please apologize this error.
the PR is in there:
https://github.com/OpenMS/OpenMS/pull/6193

I don't know really how to check that part of build, let me know if something can be done from my side: if I can see that at early stage on the CI, or if I can build locally and check that easily.
