### ISSUE TITLE
Not able to install pyopenms in Python3.10

### ISSUE THREAD

**Issue by chinmayaNK22** [OpenMS/OpenMS#6199]
Hello,

Can you please upgrade the pyopenms to get installed in Python version 3.10?

--
Chinmaya

**Comment by jpfeuffer** [comment]
Hi. 
Which OS, which repository/channel (pypi, conda::bioconda, conda::openms)?

**Comment by chinmayaNK22** [comment]
Hi,

I am trying to install it in Windows 10 through pypi. Not tried in conda.

**Comment by chinmayaNK22** [comment]
Thank you for the information.

I will try installing using Conda.

**Comment by jpfeuffer** [comment]
I just checked. Since we are using the bioconda dependencies etc. I think conda will be stuck with 3.9 for now, too.
It is probably best to use the nightly wheels. https://pyopenms.readthedocs.io/en/latest/installation.html#nightly-ci-wheels

**Comment by chinmayaNK22** [comment]
Thank you, that was quite helpful. I was able to install the nightly version of pyopenms compatible with Python==3.10.
