### ISSUE TITLE
GNPSExport FeatureLinkerUnlabeledKD error

### ISSUE THREAD

**Issue by xiaoyaozhuangzi** [OpenMS/OpenMS#6211]
Problem: 
NOTICE: FeatureLinkerUnlabeledKD of node #7 started. Processing ...
Linking 1 featureXMLs.
Progress of 'reading input':

  0.00 %               
-- done [took 8.03 s (CPU), 8.03 s (Wall)] -- 
Error: Unexpected internal error (At least two maps must be given!)
ERROR: FeatureLinkerUnlabeledKD failed!
How to resolve this error?

**Comment by axelwalter** [comment]
Are you giving only one `featureXML` file as input? For feature linking at least two `featureXML` files are required.

**Comment by xiaoyaozhuangzi** [comment]
I have given two featureXML files. as the following figture. 



***@***.***
 
From: axelwalter
Date: 2022-07-06 19:42
To: OpenMS/OpenMS
CC: xiaoyaozhuangzi; Author
Subject: Re: [OpenMS/OpenMS] GNPSExport FeatureLinkerUnlabeledKD error (Issue #6211)
Are you giving only one featureXML file as input? For feature linking at least two featureXML files are required.

**Comment by xiaoyaozhuangzi** [comment]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/108784543/177551732-6510c2f4-cde5-4d5b-ad30-13b8fdb2ec4d.png">
<img width="909" alt="image" src="https://user-images.githubusercontent.com/108784543/177552303-96160b80-8777-48f8-b1b0-f91d45743492.png">

**Comment by eeko-kon** [comment]
You probably need some sort of zip loop to input both files simultaneously at FeatureLinker. Now the pipeline inputs the files one by one. Maybe "Merger"? Not sure which node works at TOPPAS.

**Comment by cbielow** [comment]
The current pipeline is effectively doing this for your two input files `a.featureXML` and `b.featureXML`:
```
$ FeatureLinkerUnlabeledKD -in a.featureXML -design a.tsv ...
$ FeatureLinkerUnlabeledKD -in b.featureXML -design b.tsv ...
```
(you also specified two design files, but there should really be just one)

However, what you really want is this
```
$ FeatureLinkerUnlabeledKD -in a.featureXML b.featureXML -design global.tsv ...
You need to insert a `Collect` node between nodes 6/8 to achieve this.

Here is some more examples (See bottom of the page):
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPPAS_examples.html

I would also suspect that node 3 (MapAlignerPoseClustering), is not doing what you intended it to do.
It will also run on single files, effectively not aligning anything.

I'll attach a pipeline which works as intended (and does a bit more, i.e. some mass recalibration via `InternalCalibration` and some downstream QualityControl), but I hope the idea is clear :)
![image](https://user-images.githubusercontent.com/6008722/177559613-80103142-3773-4dd5-933a-19eee9ba8e42.png)


Alternatively, you can use https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/UTILS_ProteomicsLFQ.html as an all-in-one tool if this is indeed unlabeled data -- note the documentation is somehow incomplete -- we will fix that :)

**Comment by xiaoyaozhuangzi** [comment]
Thank you for your help. I will try these supports. Thank&nbsp; you very much.



---Original---
From: "Chris ***@***.***&gt;
Date: Wed, Jul 6, 2022 21:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OpenMS/OpenMS] GNPSExport FeatureLinkerUnlabeledKD error (Issue #6211)




 
The current pipeline is effectively doing this for your two input files a.featureXML and b.featureXML:
 $ FeatureLinkerUnlabeledKD -in a.featureXML -design a.tsv ... $ FeatureLinkerUnlabeledKD -in b.featureXML -design b.tsv ...  
(you also specified two design files, but there should really be just one)
 
However, what you really want is this
 $ FeatureLinkerUnlabeledKD -in a.featureXML b.featureXML -design global.tsv ... You need to insert a `Collect` node between nodes 6/8 to achieve this. Here is some more examples (See bottom of the page): https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPPAS_examples.html I would also suspect that node 3 (MapAlignerPoseClustering), is not doing what you intended it to do. It will also run on single files, effectively not aligning anything. I'll attach a pipeline which works as intended (and does a bit more, i.e. some mass recalibration via `InternalCalibration` and some downstream QualityControl), but I hope the idea is clear :) ![image](https://user-images.githubusercontent.com/6008722/177559613-80103142-3773-4dd5-933a-19eee9ba8e42.png) Alternatively, you can use https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/UTILS_ProteomicsLFQ.html as an all-in-one tool if this is indeed unlabeled data -- note the documentation is somehow incomplete -- we will fix that :)

**Comment by xiaoyaozhuangzi** [comment]
@cbielow 
FeatureLinkerUnlabeledKD was well. Thank you for your help. But  the GNPSExport  was error. How to improve? 

<img width="715" alt="image" src="https://user-images.githubusercontent.com/108784543/177755458-9c70e96e-2b4d-46cb-991b-94022e5176df.png">

**Comment by eeko-kon** [comment]
GNPSexport now generates a new error. It should work unless the output of the `FileFilter` is incorrect. Could you post the parameters of the node?

One comment:
You are aligning the featureXML files, but then using the non-aligned mzML files as input for GNPSexport. 
I would also align the mzML files using the **trafoXML** files generated from MapAlignerPoseClustering (algorithm: MapRTTransformer).

**Comment by axelwalter** [comment]
IDMapper needs the MS2 spectra information from the mzML files as input via `-spectra:in` e.g.
`
IDMapper -id emptyfile.idXML -in MapAlignerPoseClustering_inputFile0.featureXML -spectra:in MapRTTransformer_inputFile0.mzML -out IDMapper_inputFile0.featureXML`

Also you could map align your mzML files based on the feature map alignments with MapRTTransformer. Therefore you need the trafoXML files (-trafo_out from MapAlignmenerPoseClustering)

**Comment by eeko-kon** [comment]
Good catch Axel

**Comment by axelwalter** [comment]
Same :)

**Comment by matteopilz** [comment]
@xiaoyaozhuangzi, was this issue resolved?

**Comment by xiaoyaozhuangzi** [comment]
No. the GNPSexport still failed.  Could you help me resovle this error? Thank you.

<img width="758" alt="image" src="https://user-images.githubusercontent.com/108784543/186689850-baafb461-e326-45b3-a2d1-8d0e22b8df55.png">

Here, this is parameters of GNPSexport node.
<img width="349" alt="image" src="https://user-images.githubusercontent.com/108784543/186690388-7a0b687d-db52-4cce-8aff-f3d63e3d0879.png">

**Comment by axelwalter** [comment]
GNPSExport needs all mzML files together with the consensusXML file. So you would need to set them as input. 
Also you should map align your mzML files based on the feature map alignments using the MapRTTransformer tool. Therefore you need the trafoXML files (-trafo_out from MapAlignmenerPoseClustering).

So for each mzML file run MapRTTransformer (input: trafoXML file, mzML file), collect them and pass them to GNPSExport.
