### ISSUE TITLE
[TOPPView] 3D view crashes in MacOS

### ISSUE THREAD

**Issue by JeeH-K** [OpenMS/OpenMS#6215]
![Screen Shot 2022-07-07 at 10 15 27 AM](https://user-images.githubusercontent.com/7207883/177725567-1bbe6934-ad09-4dbe-bfd0-38f66dd3f73e.png)

I tried to open an mzml file with Toppview, and this is the error message I got. 
Both "Switch to 3D view" and opening an mzML file in 3D seem to crash.

**Comment by jpfeuffer** [comment]
Hi! Which macOS l, which OpenMS version?
I hope it's not OpenGL being completely deprecated now.

**Comment by JeeH-K** [comment]
For macOS, Monterey 12.4 version.
For OpenMS, I've tested with 2.8 and commit ([e5d7f19e6ac2d3e21e6bf11300f540095fca1f90](https://github.com/$user/$repo/commit/e5d7f19e6ac2d3e21e6bf11300f540095fca1f90) version.
The latter one is from the develop branch that I've used to merge with FLASHDeconv branch. (for jenkins builder)

**Comment by jpfeuffer** [comment]
Might also be a Qt bug. Do you build yourself? If so, which Qt version is important too.

**Comment by JeeH-K** [comment]
This problem appeared initially to Christina who's working with the OpenMS doc tutorial, so I've tested it with my laptop. We both experienced this.. maybe we should other MacOS users for tests?

**Comment by JeeH-K** [comment]
Ofc. Somehow I didn't realize I wasn't using the debugger mode. So it seems like OpenGL failed.
![Screen Shot 2022-07-08 at 9 57 01 AM](https://user-images.githubusercontent.com/7207883/177945344-432e0a1b-df81-41b7-9d9b-857f54e06c2a.png)

**Comment by jpfeuffer** [comment]
I am assigning @timosachsenberg as the only one who might have at least some knowledge about OpenGL.

**Comment by jpfeuffer** [comment]
I dont think this is easily solvable. We should remove the 3D functionality for macOS.

**Comment by jpfeuffer** [comment]
I randomly had a TOPPView 2.5 here (e.g., before we added QtWebEngine) and the 3D View works.
It is definitely a Qt bug https://bugreports.qt.io/browse/QTBUG-104871

(whose bugfix, if ever, we will not receive until in at least 1.5 years due to the EOL of open source Qt5)

@timosachsenberg what should we do?

**Comment by timosachsenberg** [comment]
disable QtWebEngine in TOPPView on MacOS?
