### ISSUE TITLE
FeatureFinderMetabo crashes [622]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#622]
Submitted by uweschmitt on 2013-10-30 23:07:22

I attached a small mzML file  which crashes the FeatureFinderMetabo when running as

 ./FeatureFinderMetabo -algorithm:epd:width_filtering off -in ./ff_metabo_problem.mzML -out test.featureXML

I get

   Error: Unexpected internal error (The value '0 0' was used but is not valid! FWHM beginning/ending indices not computed?  
   Aborting...)

which is caused by an exception thrown in MassTrace.C

**Comment by timosachsenberg** [comment]
can't test this with recent version because file is not accessible anymore. Will close. Please reopen if you can produce with same or other file.

**Comment by jpfeuffer** [comment]
We just received a question on the mailing list about that error.

**Comment by timosachsenberg** [comment]
version?

**Comment by jpfeuffer** [comment]
release 2.3

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/blob/release/2.3.0/src/openms/source/KERNEL/MassTrace.cpp#L285

**Comment by jpfeuffer** [comment]
could be fixed by recent changes but if someone knows the reason why this happened, maybe we can suggest a workaround

**Comment by hendrikweisser** [comment]
Impossible to reproduce without an example file. Closing.
