### ISSUE TITLE
TOPPView crashes when opening (when many tools are missing)

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6235]
E.g. when you only build TOPPView. You get cluttered with hundreds of "Tool executable missing" warnings.
And then it crashes because our logger is not thread-safe.

**Comment by jpfeuffer** [comment]
this is annoying and actually hinders my development right now. Will declare as blocker.

**Comment by jpfeuffer** [comment]
@timosachsenberg Your student did it. Maybe you or they can fix it quicker.

**Comment by timosachsenberg** [comment]
k I can give it a quick try...
