### ISSUE TITLE
TOPPView crashes when right-clicking layer of a view that was closed

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6236]
If you close a view and then right click on the still available layer, it crashes hard.

**Comment by timosachsenberg** [comment]
can't reproduce

**Comment by jpfeuffer** [comment]
I also cannot reproduce it anymore. I am not even able to find layers for views that were closed anymore. Not sure what happened.

**Comment by timosachsenberg** [comment]
Let’s assume it got fixed ;)
