### ISSUE TITLE
Split KNIME plugin into OpenMS and Thirdparty

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6244]
a) Sirius is huge since it ships its own JRE (why??).. 
b) KNIME is doing dependency security checks and especially Sirius with its gazillion dependencies has a bunch of security issues.
We would be thrown out of "trusted" extensions.

TODOs:
- [ ] In Jenkins, run plugin generation twice. Once for Adapter CTDs, once for rest.
- [ ] Name the plugins differently.
- [ ] Adapt the openms update site under https://github.com/genericworkflownodes/buildresources/blob/master/de.openms.knime.update/feature.xml to add the new third-party feature

**Comment by jpfeuffer** [comment]
A better way with shared libraries and only one automatic update site generation depends on https://github.com/genericworkflownodes/GenericKnimeNodes/pull/294

**Comment by jpfeuffer** [comment]
still depends on GKN fixes #

**Comment by poshul** [comment]
> still depends on GKN fixes [genericworkflownodes/GenericKnimeNodes#294](https://github.com/genericworkflownodes/GenericKnimeNodes/pull/294)

Are we good to go once this is merged?

**Comment by jpfeuffer** [comment]
Yes, I am changing the Jenkins job in parallel

**Comment by jpfeuffer** [comment]
Done. Rewrote plugin generation to generate multiple plugins at once and also generate the update site feature.
Changed our jenkins jobs.
Changed jenkins jobs at KNIME.

We now need to wait for KNIME to check security in the core plugin and distribute the plugins to different update sites (trusted and other).

Unsolvable issue: KNIME will not be able to suggest the new third-party plugin for old nodes in old workflows. But once you installed it on your own, old nodes will work with the new plugin.
