### ISSUE TITLE
SiriusAdapter has weird parameter handling of defaults

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6249]
It uses an empty string and -1 to omit passing parameters to the underlying Sirius executable.
Therefore empty and -1 are used in our interface to specify that the default of Sirius will be used.
Wouldn't it be much more self-explanatory if we would list the actual defaults and omit the parameter if its value is the default?
Yes you might need to update them from time to time, but you would kind of need to do the same right now in the documentation of the parameter (which is the only way to see the actual defaults, if they are even listed there).

**Comment by axelwalter** [comment]
solved in #6357
