### ISSUE TITLE
Apply clang lint fails with "argument list too long"

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#6262]
see https://github.com/OpenMS/OpenMS/runs/7456319408?check_suite_focus=true for an example.

**Comment by jpfeuffer** [comment]
I guess it's just too many files. We could split it into multiple chunks probably but I don't think it is worth the effort.
We just don't support fixing huge PRs.

**Comment by poshul** [comment]
Makes sense, closing.
