### ISSUE TITLE
Allow MGF files for MetaboliteSpectralMatcher

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#6269]
MetaboliteSpectralMatcher currently only accepts mzML files as library input files, but it would be great to have the option to add MGF files. GNPS for example only gives you the option to download their libraries in MGF, MSP and JSON.

**Comment by eeko-kon** [comment]
Error with pyOpenMS:
I am using pyOpenMS 3.0 (build-version) and it seems like the MetaboliteSpectralMatcher cannot pass important info for the hits it finds to the mzTab file (I am using the exact same files that I used yesterday with the CLI version). 
[Archive.zip](https://github.com/OpenMS/OpenMS/files/9638326/Archive.zip)

Important information that are NaN: chemical_formula, smiles, description	

Code that I used:

```
mgf_file= os.path.join("results", "GNPSexport", "MSMS.mgf")
exp = MSExperiment()
MascotGenericFile().load(mgf_file, exp)

database= glob.glob(os.path.join("resources", "GNPS-LIBRARY.mgf"))
speclib = MSExperiment()
MascotGenericFile().load(mgf_file, speclib)

mztab= MzTab()

out_merged= ""

MSMS_match= MetaboliteSpectralMatching()
MSMS_match_par = MSMS_match.getDefaults()
MSMS_match_par.setValue('merge_spectra', 'false')
MSMS_match.setParameters(MSMS_match_par)
MSMS_match.run(exp, speclib, mztab,  String(out_merged))

output_mztab= os.path.join("results", "interim", "annotations", "MSMS.mzTab")
MzTabFile().store(output_mztab, mztab)
```

**Comment by jpfeuffer** [comment]
Hmm not sure. Did you see that you are loading the same mgf twice, was that intentional?
Also, I wonder how the `run` method does not complain, it should only expect three parameters:
https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/MetaboliteSpectralMatching.pxd#L20

**Comment by eeko-kon** [comment]
AAAAh :sob: very true, I was loading an MSExperiment in the same filename! Thank you so much!

Also, Axel made some changes so now it requires 4 arguments for run. 

```
Help on built-in function run:

run(...) method of pyopenms.pyopenms_2.MetaboliteSpectralMatching instance
    Cython signature: void run(MSExperiment & exp, MSExperiment & speclib, MzTab & mz_tab, String & out_merged_spectra)
```
