### ISSUE TITLE
PrecursorPurity fails with negative charge

### ISSUE THREAD

**Issue by michaelmarty** [OpenMS/OpenMS#6280]
Hi Team,
I've been running pyopenms, and the PrecursorPurity function seems to be failing with negative charge states. The code freezes up. Looking at the source code, I think I can see why it's failing. It think changing:

` int charge = pre.getCharge();`

to 

` int charge = abs(pre.getCharge());`

will fix it. At the same time, I'd also recommend putting in some kind of check to make sure that the charge state isn't zero, which I think should also kill it as written. Personally, I'd default to 1 if 0. Hope this is helpful. Thanks,
MTM

**Comment by timosachsenberg** [comment]
good catch. I think I can provide a quick fix

**Comment by michaelmarty** [comment]
Awesome! Thanks!
