### ISSUE TITLE
New Doxygen theme still not displaying parameters correctly

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6282]
![Bildschirmfoto 2022-08-03 um 11 47 25](https://user-images.githubusercontent.com/8102638/182578838-f2b3ca85-a7fa-40a1-af7b-a03c8886eb78.png)

either the CSS update did not work, or something else is wrong.

**Comment by jpfeuffer** [comment]
blocker for release

**Comment by jpfeuffer** [comment]
Ok, no, we just did not have a successful nightly build for two weeks.

**Comment by poshul** [comment]
This is currently downstream of https://github.com/OpenMS/OpenMS/issues/6293 getting solved.
