### ISSUE TITLE
Build infrastructure update

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6293]
- [x] https://abibuilder.cs.uni-tuebingen.de/archive/openms/ empty
- [x] update links to old archive/jenkins in wiki, docs, source, pyopenms #6307
- [x] update links on website openms.de (done for permalinks)
- [x] update all links to old infra in jenkins (if there are any)
- [x] update all links to old infra in buildscripts
- [x] due to Jenkins update and new Java of the controller -> update Java on all workers (wrote FUB IT for WinVMs, updated dockerhost, updated buildscripts for containers, macOS was new enough)
- [x] pyopenms container needs to be rebuild (Java version too old for Jenkins connection)
- [x] update macMinis. WARNING: Catalina is the last supported OS for them!!
- [x] make sure that macMinis have a running XServer. Currently, GUI tests are failing. Usually means builder needs to be logged in via the GUI.
- [x] update labels and jobs that use those labels. Then rebuild contrib packages.
- [x] update public dockerfiles to 20.04 as well (the contrib one is even used in CI)
- [x] maybe docker host, too (16.04)
- [x] docker containers cannot resolve IPs anymore (done. see emails)

**Comment by jpfeuffer** [comment]
@OpenMS/core

**Comment by timosachsenberg** [comment]
some notes: 

- from ibminode2 node I get access to /nfs/wsi/abi/buildarchive/projects/openms
- from abibuilder I don't see nfs mounted abibuilder6

**Comment by timosachsenberg** [comment]
![image](https://user-images.githubusercontent.com/5803621/184332198-5cd8d364-d3fc-44a4-bfd8-3696477f332f.png)

**Comment by timosachsenberg** [comment]
btw: abiadmin@abibuilder6:/local enthält das buildarchive with files.

**Comment by jpfeuffer** [comment]
that's why I was wondering if abibuilder6 even is the HTML server

**Comment by jpfeuffer** [comment]
I have no idea where this thing is

**Comment by timosachsenberg** [comment]
I will ask Philipp. I think he set it up

**Comment by timosachsenberg** [comment]
abibuilder7 (home of buildarchive) wasn't accessible via ssh anymore.

**Comment by timosachsenberg** [comment]
pyopenms dkr works again
github actions are also fixed https://github.com/OpenMS/OpenMS/pull/6300

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/actions/runs/2878865966

pyopenms actions failing completely though

**Comment by timosachsenberg** [comment]
k probably same issue... will take a look

**Comment by jpfeuffer** [comment]
related: #6307

**Comment by jpfeuffer** [comment]
Also, we should update our Docker containers to 20.04
