### ISSUE TITLE
INSTALL_CMAKE_DIR ignored, default cmake install directory invalid

### ISSUE THREAD

**Issue by StefanBruens** [OpenMS/OpenMS#6313]
There is a CACHEd variable to set the directory, but unfortunately, this is not used:

https://github.com/OpenMS/OpenMS/blob/959e0d585ae64fe99ca5833307abd7d59e582b81/CMakeLists.txt#L366-L374

The actual used path is:
https://github.com/OpenMS/OpenMS/blob/959e0d585ae64fe99ca5833307abd7d59e582b81/cmake/export_macros.cmake#L55

Comparing this with:
https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure

```
<prefix>/                                                       (W)
<prefix>/(cmake|CMake)/                                         (W)
<prefix>/<name>*/                                               (W)
<prefix>/<name>*/(cmake|CMake)/                                 (W)
<prefix>/(lib/<arch>|lib*|share)/cmake/<name>*/                 (U)
<prefix>/(lib/<arch>|lib*|share)/<name>*/                       (U)
<prefix>/(lib/<arch>|lib*|share)/<name>*/(cmake|CMake)/         (U)
<prefix>/<name>*/(lib/<arch>|lib*|share)/cmake/<name>*/         (W/U)
<prefix>/<name>*/(lib/<arch>|lib*|share)/<name>*/               (W/U)
<prefix>/<name>*/(lib/<arch>|lib*|share)/<name>*/(cmake|CMake)/ (W/U)

```

the only two matching patterns are:
```
<prefix>/(lib/<arch>|lib*|share)/cmake/<name>*/                 (U)
<prefix>/<name>*/(lib/<arch>|lib*|share)/cmake/<name>*/         (W/U)
```

i.e. `INSTALL_LIB_DIR` must  be `/usr/lib*` (or maybe `/opt/openms/lib*`), otherwise `OpenMSConfig.cmake` won't be found.

Please reenable `INSTALL_CMAKE_DIR`.

**Comment by jpfeuffer** [comment]
While I think you are right that we should use the variable if it is there, I can't really follow why the current setup does not work.
Usually you only set the Install prefix. From this as the root, there will be lib, bin, etc.
AFAIK Install lib dir should be specified without parent folders and is relative to the install prefix.
When you want to find (lib)OpenMS installed to a nonstandard location, you just specify another entry in your cmake_prefix_path of your dependent code.

But yeah, this config export is pretty new and only tested in a very specific environment so far. So maybe there are cases where it does not work.
