### ISSUE TITLE
RTModel uses wrong outputnames, preventing RTPredict from working [632]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#632]
Submitted by faicheler on 2013-11-11 22:20:23

RTModel writes output into wrong files, resulting in:
Error: File not found (the file 'C:/Users/Test/AppData/Local/Temp/2013-11-11_132323_Test-PC_4732_1/TOPPAS_tmp/Untitled_workflow/002_RTModel/out/BSA1_OMSSA.unknown_additional_parameters' could not be found)

Output Files by RTModel for my test workflow are named by OpenMS:
BSA1_OMSSA.idXML_tmp1_additional_parameters
BSA1_OMSSA.idXML_tmp1_samples
BSA1_OMSSA.unknown

Renaming the files in their temp folder is useless because they are overwritten..

Copying the files into a non temporary folder and renaming them to
BSA1_OMSSA.unknown_additional_parameters
BSA1_OMSSA.unknown_samples
BSA1_OMSSA.unknown
fixes the Problem with RTPredict, but the workflow has to be changed (i.e. reading the Model from a file, instead of as output from the RTModel node)

---

Commented by johannes_junker on 2013-11-11 23:10:28:
Changed component from TOPPAS to TOPP; reassigned.

This is not a bug in TOPPAS but rather a severe bug in RTModel / RTPredict if they rely on certain filenames for their input / output parameters. Part of the contract between TOPPAS and any TOPP tool is that TOPP tools can have different input and output parameters, each with a well-defined set of valid file types. But TOPP tools aren't allowed to make assumptions about the actual file names that are used. This must be up to the user (or TOPPAS, in this case). In this particular case, it seems to be even worse: RTPredict is looking for hardcoded file names for which there isn't even an input parameter.

To fix this, I suggest to add input and output parameters for all those files that are at the moment implicitly loaded from or stored to some certain hard-coded file name, as in 'training_samples.load(svmfile_name + "_samples");'. This will also require to register these new file types in OpenMS and add the methods for determining the file type by extension (and content, if possible). See OpenMS/source/FORMAT/FileTypes.C, OpenMS/source/FORMAT/FileHandler.C, etc.

---

Commented by johannes_junker on 2013-11-11 23:10:36:
Changed component from TOPPAS to TOPP; reassigned.

This is not a bug in TOPPAS but rather a severe bug in RTModel / RTPredict if they rely on certain filenames for their input / output parameters. Part of the contract between TOPPAS and any TOPP tool is that TOPP tools can have different input and output parameters, each with a well-defined set of valid file types. But TOPP tools aren't allowed to make assumptions about the actual file names that are used. This must be up to the user (or TOPPAS, in this case). In this particular case, it seems to be even worse: RTPredict is looking for hardcoded file names for which there isn't even an input parameter.

To fix this, I suggest to add input and output parameters for all those files that are at the moment implicitly loaded from or stored to some certain hard-coded file name, as in 'training_samples.load(svmfile_name + "_samples");'. This will also require to register these new file types in OpenMS and add the methods for determining the file type by extension (and content, if possible). See OpenMS/source/FORMAT/FileTypes.C, OpenMS/source/FORMAT/FileHandler.C, etc.

---

Commented by cbielow on 2013-11-13 16:10:45:
my 50cents:

.model_additional_parameters --> looks like an .ini file to me
.model_samples -->  has .csv format
.model -->  also .csv 

CSV has a more broad meaning in OpenMS, also covering separators other than just ","
So all file extensions are present already. Just need to be added properly to the interface of RTModel / RTPredict as Hannes suggested.

**Comment by FabianAicheler** [comment]
Seems this got lost in the transition from sourceforge to github.

The problem still exists in this form (meaning people could get it working in TOPPAS using hardcoded input into RTPredict. Or on command line level). 

Maybe related to the filepath mechanics, I couldn't get KNIME workflows using RTPredict to work. Errors either 
'Two input parameters given, only one allowed! Use either -in_id:file or -in_text:file!' or
'You cannot perform peptide retention time prediction with a model trained for, peptide separation prediction.'

**Comment by cbielow** [comment]
I would not regard this as a blocker -- it's certainly not desriable, but can be postponed to a bugfix release. RTModel is not used that often IMHO.

**Comment by timosachsenberg** [comment]
@jpfeuffer any update on this? You recently used the prediction...

**Comment by jpfeuffer** [comment]
Yes I think with KNIME optional inputs and my changes in the tool that registered the outputs, it should be working fine now.
