### ISSUE TITLE
FIleConvertr changes nativeID format

### ISSUE THREAD

**Issue by starling13** [OpenMS/OpenMS#6320]
After running ThermoRawFileParser on raw files it creates mzML file with following native ID format element (**mzML::fileDescription::sourcefileList::sourceFile**):
`<cvParam cvRef="MS" accession="MS:1000768" value="" name="Thermo nativeID format" />`

FileConverter, processing this file creates indexed mzML file with different format element:
`<cvParam cvRef="MS" accession="MS:1000777" name="spectrum identifier nativeID format" />`

But the id attribute values in **mzML::run::spectrumList:spectrum** elements stay unchanged:
`<spectrum id="controllerType=0 controllerNumber=1 scan=1" index="0" defaultArrayLength="1397">`

**Comment by starling13** [comment]
I'm sorry, I'v found that in 2.8.0 error was fixed

**Comment by jpfeuffer** [comment]
Thanks for double-checking. Yes I remember changes there.
