### ISSUE TITLE
PyOpenMS: Converting Pandas DataFrame to FeatureMap object?

### ISSUE THREAD

**Issue by eliseneedham** [OpenMS/OpenMS#6321]
Hi,

Thanks for making and maintaining PyOpenMS!

In the documentation, it shows how to convert a FeatureMap object into a Pandas DataFrame. Is it possible to do the reverse, e.g. take the df object in the example code below and covert it into a FeatureMap object? 

Code from the documentation:
[https://pyopenms.readthedocs.io/en/latest/pandas_df_conversion.html](url)

```
import pandas as pd
from urllib.request import urlretrieve

urlretrieve(url+'BSA1_F1_idmapped.featureXML', 'BSA1_F1_idmapped.featureXML')
feature_map = FeatureMap()
FeatureXMLFile().load('BSA1_F1_idmapped.featureXML', feature_map)

df = feature_map.get_df() # default: meta_values = None
```

Thank you.

Best wishes,
Elise

**Comment by axelwalter** [comment]
Hi Elise,

There is no specific function for that right now, however, you could easily recreate that, by initializing an empty FeatureMap object and filling it with one Feature object per row in the dataframe. I will post an example later.

**Comment by axelwalter** [comment]
So as an example you could use this function:
```
def df_to_fm(df):
    fm = FeatureMap()
    for index, row in df.iterrows():
        f = Feature()
        f.setIntensity(row["intensity"])
        f.setRT(row["RT"])
        f.setMZ(row["mz"])
        f.setOverallQuality(row["quality"])
        f.setCharge(row["charge"])
        ch = ConvexHull2D()
        points = [ [row["RTstart"], row["MZstart"]], 
                    [row["RTstart"], row["MZend"]],
                    [row["RTend"], row["MZstart"]],
                    [row["RTend"], row["MZend"]]]
        for p in points:
            ch.addPoint(p)
        f.setConvexHulls([ch])
        f.setUniqueId(int(index))
        fm.push_back(f)
    return fm
```
If you need to include the peptide info as well, you can attach them to feature, here are [some examples how to do that](https://pyopenms.readthedocs.io/en/latest/datastructures_id.html).

**Comment by eliseneedham** [comment]
Hi Axel,

Thanks so much! That is very helpful.

Best wishes,
Elise
________________________________
