### ISSUE TITLE
PyOpenMS build fails with single submodule

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#6322]
Setting PY_NUM_MODULES to 1 causes:
`[100%] Building CXX object src/pyOpenMS/CMakeFiles/pyopenms_compile.dir/__/__/pyOpenMS/pyopenms/pyopenms.cpp.o
cc1plus: fatal error: /home/samuel/git/OpenMS/pyOpenMS/pyopenms/pyopenms.cpp: No such file or directory`

`pyopenms_1.cpp` does exist, but the build system seems to only look for `pyopenms.cpp` if there is the one module.

This is a regression from the earlier pyopenms build system

**Comment by jpfeuffer** [comment]
are you uptodate with develop?

https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/CMakeLists.txt#L623

this should do it. But I never test with 1 module.

**Comment by poshul** [comment]
It still does this with develop.

**Comment by poshul** [comment]
I can take a look at the CMakeLists tomorrow and see if I come up with a solution.

**Comment by jpfeuffer** [comment]
just call everything pyopenms_1.cpp
Although this is weird. The create_cpp script should not give it that suffix!

**Comment by poshul** [comment]
Changing https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/CMakeLists.txt#L658 and line 479 to specify pyopenms_1.cpp seems to fix that problem. Unfortunately it crashes later with the following:

`      In file included from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1969,
                       from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /usr/lib/python3/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                       from pyopenms/pyopenms_1.cpp:783:
      /usr/lib/python3/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      In file included from pyopenms/pyopenms_1.cpp:897:
      /home/samuel/git/OpenMS/src/openms/include/OpenMS/FORMAT/Base64.h:53:10: fatal error: QByteArray: No such file or directory
         53 | #include <QByteArray>
            |          ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/c++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyopenms
  Running setup.py clean for pyopenms
Failed to build pyopenms
ERROR: Failed to build one or more wheels`

**Comment by jpfeuffer** [comment]
Sounds like missing or mismatching Qt includes. That there are differences between the number of modules used, is unlikely to be the issue. Maybe something changed between your CMake reconfigure commands.

**Comment by poshul** [comment]
Following up on this, I still see the behavior after cleaning and redoing CMake.
I also can trigger this behavior with the standard 8 module version by calling `create_cpp_extension.py` followed by `setup.py bdist_wheel`.

**Comment by jpfeuffer** [comment]
these scripts do not work anymore

**Comment by jpfeuffer** [comment]
correct linking is only guaranteed via CMake

**Comment by poshul** [comment]
https://github.com/OpenMS/OpenMS/pull/6328 should fix this.
