### ISSUE TITLE
Jenkins Yet another Docker plugin deprecated and useless

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6323]
We are using a deprecated Docker plugin, that does not let us whitelist syscall for the hardened runtimes of newer dockers.
Since Qt 5.10 the MOCing relies on syscall statx.
Therefore we cannot use docker anymore on Jenkins.
Therefore no Linux builds anymore.

**Comment by jpfeuffer** [comment]
https://stackoverflow.com/questions/51195528/rcc-error-in-resource-qrc-cannot-find-file-png

and

https://github.com/KostyaSha/yet-another-docker-plugin/issues/144

(of the useless unmaintained plugin)

**Comment by poshul** [comment]
Switched to the normal docker plugin
