### ISSUE TITLE
macOS workers do not have running Xserver

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6331]
This usually means that the build user is not logged in on the GUI.
Someone from Tübingen please fix.

**Comment by timosachsenberg** [comment]
I will ask Martin. Just to clarify. User is "builder" and there is no PW?

**Comment by jpfeuffer** [comment]
PW should be the one from the sheet as usual.

Would be good if someone tries to build while someone is there. Not sure if Martin can do that.
I am not 100% sure what the exact requirements were for GUI apps to work. I think it was just logging in.

**Comment by poshul** [comment]
@timosachsenberg this looks to be fixed. Is it?
