### ISSUE TITLE
[NASE] No terminal 3' -OH option

### ISSUE THREAD

**Issue by herbercr** [OpenMS/OpenMS#6351]
Is there a way to do a _in-silico_ digestion in Nucleic acid search engine with a terminal 3'-OH instead of a p?

**Comment by poshul** [comment]
With no specified 5' and 3' mods NASE defaults to terminal OH's. You can add the terminal phosphates by adding [5'-p] or [3'-p] at the 5' and 3' end of your sequence respectively.

**Comment by herbercr** [comment]
Are these 3- OHs for the digestion products? Based on my data, the fasta's predicted digestion products containing 3'-ps due to the digestion RNase I chose. For example, I digested my samples with RNase T1 so I should have predicted digestion products containing 3'- Gps. However, my sample was further treated with BAP which removes terminal ps. Is there a way that I can create predicted digestion products of RNase T1 that contain 3'-OHs instead of ps?


Cassandra Herbert

Ph.D. Candidate | Research Assistant

Limbach Group

Rieveschl Laboratories for Mass Spectrometry

Department of Chemistry

University of Cincinnati

LinkedIn: https://www.linkedin.com/in/cassandraherbert/

________________________________

**Comment by poshul** [comment]
Ah, okay this is slightly different. The best way to do this would be to add a new enzyme to the Enzymes_RNA.xml file in share/openms/CHEMISTRY with the following:
```

    <NODE name="RNase_T1_BAP">
      <ITEM name="Name" value="RNase_T1_BAP" type="string" />
      <ITEM name="RegEx" value="(?&lt;=G)" type="string" />
      <ITEM name="RegExDescription" value="RNase T1 cuts after G. BAP cuts off 3' P" type="string" />
      <ITEM name="CutsAfter" value="G(?!m)" type="string" />
      <ITEM name="CutsBefore" value=".*" type="string" />
      <ITEM name="ThreePrimeGain" value="" type="string" />
      <ITEM name="FivePrimeGain" value="" type="string" />
    </NODE>
```

**Comment by poshul** [comment]
Closed as stale.
