### ISSUE TITLE
Code analysis: Coverty [636]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#636]
Submitted by hroest on 2013-11-17 09:50:03

Analyse the report generated by coverty https://en.wikipedia.org/wiki/Coverity 

Improve the code

Let it run on a regular basis on our code

**Comment by hroest** [comment]
@timosachsenberg @jpfeuffer can we do a coverty run at some point again?

**Comment by timosachsenberg** [comment]
I think we can do so for a release candidate. Let's keep this in mind.

**Comment by jpfeuffer** [comment]
Yes I requested admin rights on coverity at some point. @aiche had to confirm.
I'll need to check if it worked, otherwise make a new account and put a job into the CI server.

**Comment by timosachsenberg** [comment]
I think we have now several static checkers in place that are easier to use.
