### ISSUE TITLE
[pyopenms] MSExperimentDF not working with PeakPickerHiRes

### ISSUE THREAD

**Issue by jpruyne-mw** [OpenMS/OpenMS#6367]
Trying to adapt code from https://pyopenms.readthedocs.io/en/latest/centroiding.html

However this no longer works and the following error is produced when running either as listed or with a simply utility function

> def centroid_exp(exp: MSExperiment):
>     centroid_data = MSExperiment()
>     PeakPickerHiRes().pickExperiment(exp, centroid_data)
>     return centroid_data

`Exception: can not handle type of (<pyopenms.dataframes.MSExperimentDF object at 0x13fc1ae40>, <pyopenms.dataframes.MSExperimentDF object at 0x13f7b97c0>)`

Version info:
Version: 3.0.0-pre-nightly-2022-09-28
OpenMP: True
Build type: Release
Architecture: 64 bit

**Comment by axelwalter** [comment]
Hi, the function needs a third argument (check_spectrum_type: bool)
https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/PeakPickerHiRes.pxd#L28

**Comment by jpfeuffer** [comment]
True. Please also have a look at our "newish" API documentation which at least contains the Cython types:
https://pyopenms.readthedocs.io/en/latest/apidoc.html

Unfortunately, documentation tools cannot handle C extensions very well.
