### ISSUE TITLE
Imaging MS "imzml" reading

### ISSUE THREAD

**Issue by nh012** [OpenMS/OpenMS#6368]
Dear OpenMS Team, 

I am using pyopenms and I have problem reading the imzml file by IndexedMzMLFileLoader()
I get False when I load the file, and if I try reading the Spectrum for example I get runtime error:
RuntimeError:  in: Parsing was unsuccessful, cannot read file

if I read the file with normal mzml reader it reads all 0 values! 

The file itself is not the problem because I also tried it with sample files available online, both continuous and processed imzml files.  
could you please send me some more information on how to deal with imzml files? 

These are the information you requested:
Version: 2.7.0-pre-py-nightly-test-2021-08-24
OpenMP: True
Build type: Release
Architecture: 64 bit

Thank you for your time and consideration. 

Kind regards,
NH

**Comment by jpfeuffer** [comment]
Hi!

I think you might be mixing up `imzml` for imaging MS (which is not supported by OpenMS)
and `mzML` with an index (aka indexed mzML, which is not visible in the filename ending).

**Comment by nh012** [comment]
Thanks for your response. yes it's imaging mzml. I saw that there is imzml parser in C++ version, any possibility I can process data from imzml files with pyopenms?
