### ISSUE TITLE
SiriusAdapter issue with re-quantified files only

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#6374]
I am running my workflow with the requantification step and SiriusAdapter crashes with the output (again):

```
2022-10-08 12:16:10 SiriusAdapter:1:: Error: Unexpected internal error (Sirius was executed, but an empty output was generated)
2022-10-08 12:16:10 SiriusAdapter:1:: Error occurred in line 256 of file /home/eeko/data/OpenMS_build/OpenMS/src/utils/SiriusAdapter.cpp (in function: virtual OpenMS::TOPPBase::ExitCodes TOPPSiriusAdapter::main_(int, const char**)) !
```

No other valuable information as an output. However, if I do not requantify, then it runs fine. What I assume happened is that during the last changes somehow the featureXML input from the requantification is no longer readable perhaps? It is a little different that the typical one generated from FFM. I am attaching the input files for both commands (maybe @axelwalter could you try to run the command on your pc? :) )

Sirius version (SNAPSHOT) 5.6.1 in linux
(login was successful with email and password)

Command:
(Requantified)
`SiriusAdapter -sirius_executable resources/sirius/bin/sirius -sirius_user_email *** -sirius_user_password *** -in Aligned_20220103_UMETAB241_POS_ISP2_MC1_100.mzML -in_featureinfo Requant_MFD_20220103_UMETAB241_POS_ISP2_MC1_100.featureXML -out_sirius formulas_20220103_UMETAB241_POS_ISP2_MC1_100.mzTab -out_fingerid structures_20220103_UMETAB241_POS_ISP2_MC1_100.mzTab -preprocessing:filter_by_num_masstraces 2 -preprocessing:feature_only -sirius:profile orbitrap -sirius:db none -sirius:ions_considered "[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+" -sirius:elements_enforced CHN[15]OS[4]Cl[2]P[2] -sirius:compound_timeout 100 -debug 3 -read_sirius_stdout  -threads 1 -log SiriusAdapter_20220103_UMETAB241_POS_ISP2_MC1_100.log`

Command:
(Preprocessed)
`SiriusAdapter -sirius_executable resources/sirius/bin/sirius -sirius_user_email *** -sirius_user_password *** -in Aligned_20220103_UMETAB241_POS_ISP2_MC1_100.mzML -in_featureinfo Preprocessed_MFD_20220103_UMETAB241_POS_ISP2_MC1_100.featureXML -out_sirius formulas_20220103_UMETAB241_POS_ISP2_MC1_100.mzTab -out_fingerid structures_20220103_UMETAB241_POS_ISP2_MC1_100.mzTab -preprocessing:filter_by_num_masstraces 2 -preprocessing:feature_only -sirius:profile orbitrap -sirius:db none -sirius:ions_considered "[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+" -sirius:elements_enforced CHN[15]OS[4]Cl[2]P[2] -sirius:compound_timeout 100 -debug 3 -read_sirius_stdout  -threads 1 -log SiriusAdapter_20220103_UMETAB241_POS_ISP2_MC1_100.log`

Only the MFD (MetaboliteFeatureDeconvolution) file is different. 

https://drive.google.com/drive/folders/1jaed-0JMoOl7AJ4yr0vnv1esCbj6dvoC?usp=sharing

**Comment by axelwalter** [comment]
Just tested, and both cases run without issues with the latest 5.6.1 snapshot.

**Comment by axelwalter** [comment]
Could you post the stdout of the sirius command which produces the empty output?

**Comment by eeko-kon** [comment]
```
Executing command: /scratch/hdd/eeko/new_snakemake/snakemake-UmetaFlow/resources/sirius/bin/sirius --noCite --processors=1 --input /tmp/20221010_101159_nbc04_263680_2.ms --project /tmp/20221010_101159_nbc04_263680_1/sirius_out --no-compression sirius --db=none --ions-considered=[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+ --compound-timeout=100 --profile=orbitrap --elements-enforced=CHN[15]OS[4]Cl[2]P[2] --candidates=5 fingerprint structure write-summaries
Standard output and error of SIRIUS were:
########################################
## Computed 0 instances in 00:00:00.004(NaN instances/minute).

Oct 10, 2022 10:12:10 A.M. org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
<########################################> occurred 2 times
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
Oct 10, 2022 10:12:11 A.M. de.unijena.bioinf.ms.frontend.core.ApplicationCore <clinit>
INFO: Sirius Workspace Successfull initialized at: /home/eeko/.sirius-5.6
INFO: You run SIRIUS 5.6.1-SNAPSHOT
INFO: You run SIRIUS in 'CLI' mode.
INFO: Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO: Treebuilder priorities loaded from 'sirius.properties' are: [CLP, GUROBI, CPLEX]
INFO: CPU check done. 28 cores that handle 56 threads were found.
<Oct 10, 2022 10:12:11 A.M. de.unijena.bioinf.ms.frontend.core.ApplicationCore <clinit>> occurred 6 times
Oct 10, 2022 10:12:13 A.M. de.unijena.bioinf.ms.frontend.core.ApplicationCore <clinit>
INFO: Web API initialized.
Oct 10, 2022 10:12:13 A.M. de.unijena.bioinf.ms.frontend.Run parseArgs
INFO: Running with following arguments: [--noCite, --processors=1, --input, /tmp/20221010_101159_nbc04_263680_2.ms, --project, /tmp/20221010_101159_nbc04_263680_1/sirius_out, --no-compression, sirius, --db=none, --ions-considered=[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+, --compound-timeout=100, --profile=orbitrap, --elements-enforced=CHN[15]OS[4]Cl[2]P[2], --candidates=5, fingerprint, structure, write-summaries]
Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions setNumOfCores
INFO: Adjusted JobManager CPU threads to '1' by command line.
Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <0>[InputExpanderJJob-0] Running post processing
FINE: <0>[InputExpanderJJob-0] Running cleanup
<Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.jjobs.JJob lambda$logDebug$13> occurred 2 times
Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <1>[InputExpanderJJob-1] Expanding Input Files: '/tmp/20221010_101159_nbc04_263680_2.ms'...
INFO: <1>[InputExpanderJJob-1] ...Input Files successfully expanded!
<Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.jjobs.JJob lambda$logInfo$9> occurred 2 times
Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <1>[InputExpanderJJob-1] Running post processing
FINE: <1>[InputExpanderJJob-1] Running cleanup
<Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.jjobs.JJob lambda$logDebug$13> occurred 2 times
Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.ms.frontend.workflow.ToolChainWorkflow run
INFO: Workflow has been finished in 00:00:00.107
INFO: Executing Postprocessing...
<Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.ms.frontend.workflow.ToolChainWorkflow run> occurred 2 times
Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.ms.frontend.subtools.summaries.SummarySubToolJob compute
INFO: Writing summary files...
INFO: Project-Space summaries successfully written in: 00:00:00.156
<Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.ms.frontend.subtools.summaries.SummarySubToolJob compute> occurred 2 times
Oct 10, 2022 10:12:14 A.M. de.unijena.bioinf.ms.frontend.SiriusCLIApplication lambda$configureShutDownHook$1
INFO: CLI shut down hook: SIRIUS is cleaning up threads and shuts down...

SiriusAdapterAlgorithm.cpp(395): Deleting temporary directory /tmp/20221010_101159_nbc04_263680_1. Set debug level to 9 or higher to keep it.
SiriusAdapterAlgorithm.cpp(400): Deleting temporary msfile /tmp/20221010_101159_nbc04_263680_2.ms. Set debug level to 9 or higher to keep it.
Error: Unexpected internal error (Sirius was executed, but an empty output was generated)
TOPPBase.cpp(1605): Error occurred in line 256 of file /home/eeko/data/OpenMS_build/OpenMS/src/utils/SiriusAdapter.cpp (in function: virtual OpenMS::TOPPBase::ExitCodes TOPPSiriusAdapter::main_(int, const char**)) !
```

**Comment by jpfeuffer** [comment]
Not yet. Did you compare the produced .ms files. And what do OpenMS logs say about how many features were eligible for export to Sirius?

**Comment by eeko-kon** [comment]
This is also happening in my MacOS, with the same exact files and SIRIUS 5.6.1. snapshot.

The .ms file generated from the requantified one is empty (that's the problem).

**Comment by eeko-kon** [comment]
Good point. Number of features to be processed: 0. So the re-quantified file is not readable by SiriusAdapter somehow again. I will re-build everything but it s weird that it happens in both my operating systems.

**Comment by axelwalter** [comment]
Could you remove the convex hulls/subordinates in the feature map? We have done that before with FFMID output.
```python
fm_no_sub = FeatureMap(fm)
fm_no_sub.clear(False)
for f in fm:
    f.setConvexHulls([])
    f.setSubordinates([])
    fm_no_sub.push_back(f)
sirius_feature_path = os.path.join(no_convex_hulls_dir, feature_file)
FeatureXMLFile().store(sirius_feature_path, fm_no_sub)
```

**Comment by eeko-kon** [comment]
This is a pyOpenMS SiriusAdapter bug. The convex hulls should be readable from SiriusAdapter (CLI). I tried that nevertheless, and again, it says that 0 features are going to be processed and crashes. Let's look at it through zoom. I will re-build OpenMS until then. 

(Tried with other files too to make sure it is consistent and it is).

**Comment by eeko-kon** [comment]
I did not have the latest changes in SiriusAdapter (Axel's branch). Everything works fine now.
