### ISSUE TITLE
Update list of algorithm classes with parameters in DefaultParamHandlerDocumenter

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6385]
https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/parameters/DefaultParamHandlerDocumenter.cpp

Just list more classes that derive from ParamHandler and therefore have parameters to be documented.

**Comment by AmandaWein** [comment]
Does anything special need to be done for classes derived from DefaultParamHandler that are abstract base classes?

**Comment by jpfeuffer** [comment]
I am not sure. There are some exceptions mentioned in the file:
https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/parameters/DefaultParamHandlerDocumenter.cpp#L350
https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/parameters/DefaultParamHandlerDocumenter.cpp#L482

If in doubt or it does not work, just leave them out for now or leave them there commented-out.

**Comment by AmandaWein** [comment]
Thanks! I just commented out the lines that are causing errors.
