### ISSUE TITLE
Update ALL github actions in ALL repos

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6391]
Github is changing stuff again..

- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
   affecting at least actions/checkout, actions/cache, actions/checkout

**Comment by timosachsenberg** [comment]
does this also affect echos in e.g. .sh files  ?

**Comment by jpfeuffer** [comment]
No only echo "::set-output" or how it was called.

**Comment by poshul** [comment]
I've done this. PRs:
https://github.com/OpenMS/pyopenms-docs/pull/309
https://github.com/OpenMS/contrib/pull/120
https://github.com/OpenMS/autowrap/pull/169
https://github.com/OpenMS/OpenMS/pull/6406

**Comment by jpfeuffer** [comment]
This did not work:
jurplel/install-qt-action/action@v3 changed syntax

**Comment by poshul** [comment]
I've updated to match the new syntax, but the windows build still fails. https://github.com/OpenMS/OpenMS/actions/runs/3328920720/jobs/5505493286. Any thoughts?

**Comment by poshul** [comment]
As long as https://github.com/OpenMS/OpenMS/issues/6417 isn't downstream of these changes. This should be fixed now.

**Comment by jpfeuffer** [comment]
not yet complete: https://github.com/OpenMS/OpenMS/actions/runs/3547952335

**Comment by poshul** [comment]
With the closure of https://github.com/OpenMS/contrib/issues/123 this _should_ be all of them.
