### ISSUE TITLE
IDMapper match by native ID for featureXML

### ISSUE THREAD

**Issue by zhuchcn** [OpenMS/OpenMS#6403]
Currently IDMapper doesn't use the spectrum native ID for mapping like it for ConsensusXML. Any plan for implementing it for featureXML?

**Comment by jpfeuffer** [comment]
Hi! What would be a use case? How would the native IDs be assigned to the features? That is usually the goal of IDMapper (only that the spectra already have IDs). The only exception is TMT. But there you only work with consensusXMLs.
