### ISSUE TITLE
Make HDF5 optional until we actually use it

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6429]
It is not the biggest dependency but the change would be minor.

**Comment by poshul** [comment]
HDF5 is defined as REQUIRED in cmake/cmake_findExternalLibs.cmake . Remove the required tag, and set hdf5_test to only build if HDF5 is found.

**Comment by timosachsenberg** [comment]
just for reference:
also only add HDF5Connector sources and includes if build with HDF5
