### ISSUE TITLE
CDASH certificate expired

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6437]

**Comment by jpfeuffer** [comment]
seqan guys already wrote IT

**Comment by jpfeuffer** [comment]
You can disable the SSL check in the cdash config

**Comment by timosachsenberg** [comment]
Where?

**Comment by jpfeuffer** [comment]
Multiple locations
https://github.com/OpenMS/build-scripts/blob/master/cmakeScripts/run_tests.cmake#L91

The one for actions is in tools. I am not gonna look for it.

**Comment by timosachsenberg** [comment]
so basically adding a set CTEST_CURL_OPTIONS CURLOPT_SSL_VERIFYHOST_OFF ?
is this a good idea? should we do that?

**Comment by jpfeuffer** [comment]
I guess it's ok but we should add it back once it is fixed.

**Comment by timosachsenberg** [comment]
do you know how long the fix will take?

**Comment by jpfeuffer** [comment]
should be working again. you can remove the ssl exception

**Comment by timosachsenberg** [comment]
thanks! I can, but is there any vulnerability here? Otherwise, I would just keep it without the check. I mean if someone is able to get internal credentials then he can also submit them somewhere else and probably doesn't need to rely on the server.
