### ISSUE TITLE
pyopenms tests failing on macOS

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6444]
Maybe related to RPATH and fix_dependency script changes in #6421

**Comment by poshul** [comment]
Is this the Github actions build?

**Comment by jpfeuffer** [comment]
yes

**Comment by poshul** [comment]
At first glance it looks like the "Library not loaded error" stems from looking for the library in `/Users/runner/work/OpenMS/Qt/5.12.7/clang_64/lib/QtNetwork.framework` rather than `/Users/runner/work/OpenMS/Qt/5.12.7/clang_64/lib/pkgconfig`

**Comment by jpfeuffer** [comment]
It should not even be looking there. The libraries should be in the wheel and referenced relative to the @loader_path or @rpath

**Comment by jpfeuffer** [comment]
```
> Skipped /Users/runner/work/OpenMS/OpenMS/bld/pyOpenMS/pyopenms/_pyopenms_2.cpython-38-darwin.so -- Otool not executable on it.
> Skipped /Users/runner/work/OpenMS/OpenMS/bld/pyOpenMS/pyopenms/_pyopenms_7.cpython-38-darwin.so -- Otool not executable on it.
> Skipped /Users/runner/work/OpenMS/OpenMS/bld/pyOpenMS/pyopenms/_pyopenms_3.cpython-39-darwin.so -- Otool not executable on it.
> Skipped /Users/runner/work/OpenMS/OpenMS/bld/pyOpenMS/pyopenms/_pyopenms_8.cpython-38-darwin.so -- Otool not executable on it.
> Skipped /Users/runner/work/OpenMS/OpenMS/bld/pyOpenMS/pyopenms/_pyopenms_6.cpython-39-darwin.so -- Otool not executable on it.
> Skipped /Users/runner/work/OpenMS/OpenMS/bld/pyOpenMS/pyopenms/_pyopenms_2.cpython-310-darwin.so -- Otool not executable on it.
> Skipped /Users/runner/work/OpenMS/OpenMS/bld/pyOpenMS/pyopenms/_pyopenms_8.cpython-310-darwin.so -- Otool not executable on it.
> Skipped /Users/runner/work/OpenMS/OpenMS/bld/pyOpenMS/pyopenms/libOpenSwathAlgo.dylib -- Otool not executable on it.
```

This is not good. And why are there so's for multiple python versions? Maybe we should remove them between builds.

**Comment by poshul** [comment]
So, it was not correcting the dependencies unless the plugin dir was explicitly given?

**Comment by jpfeuffer** [comment]
It still does not. I won't have time until in like two weeks to look at it.

**Comment by jpfeuffer** [comment]
Giving a plugin dir is not an option. Would be very confusing.

**Comment by poshul** [comment]
Do you have a minute to do a quick call on this?

**Comment by poshul** [comment]
Looks like the latest updates didn't fix it.
`
cp: @rpath/QtCore.framework/Versions/5/QtCore: No such file or directory
chmod: /Users/runner/work/OpenMS/OpenMS/bld/pyOpenMS/pyopenms/QtCore: No such file or directory
error: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: @rpath/QtCore.framework/Versions/5/QtCore (No such file or directory)
Exception `NoMethodError' at ./mac_fix_dependencies.rb:94 - undefined method `strip' for nil:NilClass
./mac_fix_dependencies.rb:94:in `extractInstallName': undefined method `strip' for nil:NilClass (NoMethodError)
	from ./mac_fix_dependencies.rb:265:in `handleFramework'
	from ./mac_fix_dependencies.rb:147:in `block in handleDependencies'
	from ./mac_fix_dependencies.rb:122:in `each'
	from ./mac_fix_dependencies.rb:122:in `handleDependencies'
	from ./mac_fix_dependencies.rb:272:in `handleFramework'
	from ./mac_fix_dependencies.rb:147:in `block in handleDependencies'
	from ./mac_fix_dependencies.rb:122:in `each'
	from ./mac_fix_dependencies.rb:122:in `handleDependencies'
	from ./mac_fix_dependencies.rb:322:in `handleDyLib'
	from ./mac_fix_dependencies.rb:149:in `block in handleDependencies'
	from ./mac_fix_dependencies.rb:122:in `each'
	from ./mac_fix_dependencies.rb:122:in `handleDependencies'
	from ./mac_fix_dependencies.rb:322:in `handleDyLib'
	from ./mac_fix_dependencies.rb:440:in `block (2 levels) in <main>'
	from ./mac_fix_dependencies.rb:433:in `each'
	from ./mac_fix_dependencies.rb:433:in `block in <main>'
	from ./mac_fix_dependencies.rb:431:in `chdir'
	from ./mac_fix_dependencies.rb:431:in `<main>'
make[3]: *** [src/pyOpenMS/CMakeFiles/pyopenms] Error 1
make[2]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/all] Error 2
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/rule] Error 2
make: *** [pyopenms] Error 2
Error: Process completed with exit code 2.
`
