### ISSUE TITLE
Evaluate aqt 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6447]
Tool used by a friend to install Qt on their CI machines:
https://aqtinstall.readthedocs.io/en/latest/index.html
https://aqtinstall.readthedocs.io/en/latest/cli.html#list-qt-command
https://github.com/vslotman/docker-aqtinstall/blob/master/Dockerfile

**Comment by jpfeuffer** [comment]
Our github actions already use it.

**Comment by jpfeuffer** [comment]
For the jenkins workers, we could also do it. But since we do not reinstall for every build, the UI installer/brew/apt works fine.
