### ISSUE TITLE
TOPPview goes down when opening a document

### ISSUE THREAD

**Issue by MigRibe** [OpenMS/OpenMS#6474]
Hi, when I am trying to open a file, toppview goes down with any explanation. Can you please help me?

**Comment by cbielow** [comment]
Hi, thanks for reporting.

We'd need a few more pieces of information in order to fix:
What version of OpenMS are you using?
On what Operating system?
And ideally, a download link to the file if possible.
(if the data is private, feel free to send the link to chris.bielow[ at ]fu-berlin.de)

Thanks!

**Comment by MigRibe** [comment]
Many thanks for your email.

Kind regards

Miguel

We'd need a few more pieces of information in order to fix:
What version of OpenMS are you using? 2.8
On what Operating system? Windows 10
And ideally, a download link to the file if possible.
(if the data is private, feel free to send the link to chris.bielow[ at ]fu-berlin.de) https://we.tl/t-GmQvkcHGgu

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Chris ***@***.***>
Enviado: 16 de novembro de 2022 15:29
Para: ***@***.***>
Cc: José Miguel Silva Ferreira ***@***.***>; ***@***.***>
Assunto: Re: [OpenMS/OpenMS] TOPPview goes down when opening a document (Issue #6474)

Não costuma receber e-mails de ***@***.*** Saiba por que motivo isto é importante<https://aka.ms/LearnAboutSenderIdentification>

Hi, thanks for reporting.

We'd need a few more pieces of information in order to fix:
What version of OpenMS are you using?
On what Operating system?
And ideally, a download link to the file if possible.
(if the data is private, feel free to send the link to chris.bielow[ at ]fu-berlin.de)

Thanks!

**Comment by cbielow** [comment]
I did only realize now that you attached the requested information below your signature.
The download link does not work anymore. 
Could you please re-send the data.
Thanks!
