### ISSUE TITLE
TOPPView log-view broken

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#6475]
Whenever I try to switch to the log-view of a spectrum, TOPPView starts to use an insane amount of memory

Replicate as follows

1. open TOPPView (version 2.8 c26d432c31e94edd74bc67e8dabdbf8fbd92eaff)
2. load peakpicker_tutorial_2_picked.mzML
3. click on the "log" button
4. TOPPView uses > 10 GB of memory suddenly:
![Screenshot from 2022-11-16 15-08-25](https://user-images.githubusercontent.com/464014/202284906-46b349d4-d7e4-4b08-810c-be7177e166e6.png)

**Comment by jpfeuffer** [comment]
@cbielow Do you know if that is related to or fixed by your recent changes. Sounds like the snapshot tested may have been before them. Could you check anyhow as an expert? ;)

**Comment by hroest** [comment]
I have tried to reproduce this behavior on a newer build and not the release version and I cannot reproduce this on current builds. Not sure if the bug has been fixed or if it was an issue with my Qt library setup but I would appreciate other people checking if they have this bug as well.

**Comment by timosachsenberg** [comment]
Hmm I don't see that effect in the current version.
In debug mode, I can see a pretty high virtual memory consumption, which I guess is fine.
In release mode, it never goes beyond 800mb.
