### ISSUE TITLE
Remove svn keywords and versions from OpenMS

### ISSUE THREAD

**Issue by aiche** [OpenMS/OpenMS#648]
OpenMS currently has some usage of svn keywords
- test system uses Id in START_TEST
- checker tests for id 

We also have the svn version integration. Those need to be removed now that we work on git.

**Comment by timosachsenberg** [comment]
@jpfeuffer close?

**Comment by jpfeuffer** [comment]
So the "$Id$" attribute still exists in the test macros but seems to be unused. Otherwise SVN only occurs in comments.

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/pull/3652
