### ISSUE TITLE
Undefined behavior in MetaInfoInterface

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6480]
I think the following code might be UB:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/METADATA/MetaInfoInterface.cpp#L150-L166
when called with a temporary.

as in:
```
const DataValue& m = hit.getMetaValue("target_decoy"), DataValue("target"));
```

You can verify compiler behavior with something easier like this:
```
#include <string>
#include <vector>
#include <iostream>

class A
{
    public:
    int value=0;
    A(int t):value(t) {};
    ~A() { std::cout<< "~A" << std::endl; }
    const int& getValue() const { return value;} 
};

class T
{
    public:
    const A& get(const A&  a) { return a;}
    ~T() { std::cout << "~T" << std::endl; }
};

int main() {
  const int& test = T().get(A(5)).getValue();
  return test;
}
```
For gcc this returns 0, for clang 5.
The reason is that the lifetime of the temporary A(5) and of T() ends and frees the internal variable that is referenced.

Any suggestions what to do here?

**Comment by cbielow** [comment]
Maje the two argument function return a copy?

Am 17.11.2022 17:52 schrieb Timo Sachsenberg ***@***.***>:

Assigned #6480<https://github.com/OpenMS/OpenMS/issues/6480> to @cbielow<https://github.com/cbielow>.

**Comment by timosachsenberg** [comment]
Sounds like a good solution with some additional overhead (copy) that is probably fine
