### ISSUE TITLE
Adjust pyOpenMS setup.py to different contrib locations

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#650]
The pyOpenMS setup.py should be configurable to allow for multiple locations of headers and libraries.

A partial fix was addressed in issue #643 where at least the svm.h header will be found on certain linux systems.

**Comment by hendrikweisser** [comment]
@hroest: Is this issue still relevant?

**Comment by oliveralka** [comment]
I don't think this is still relevant. Most should be resolved via cmake.
