### ISSUE TITLE
Boost spirit karma < 1.67 is bugged

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6507]
https://godbolt.org/z/77Tovo6MG

we need to raise minimum version and update all our machines, contrib, dockerfiles.

**Comment by jpfeuffer** [comment]
@cbielow @timosachsenberg or any other workaround ideas?

**Comment by jpfeuffer** [comment]
I updated the dockerfile. I think for docker there is no real reason to use older ubuntus.

**Comment by timosachsenberg** [comment]
good find... and quite annoying.

**Comment by jpfeuffer** [comment]
We first have to decide how to go forward. Require higher boost or find a workaround?

**Comment by jpfeuffer** [comment]
I updated docker because this was urgent. If we require an update we need to check each build machine and actions that do not use our contrib. Fortunately our contrib is uptodate enough.

**Comment by timosachsenberg** [comment]
While C17 it is only supported in GCC > 8.1 and probably clang >10

I leave this here as reference as this could replace/remove the boost karma code
```
    template <typename T>
    void append(T f, String& target, int precision)
    {   
      const double abs_f = std::abs(f);
      if (abs_f < std::numeric_limits<T>::min()) { target = "0.0"; return; }

      std::array<char, 32> str; // sufficiently large buffer
      auto format = (abs_f >= 1e4 || abs_f < 1e-2) ? std::chars_format::scientific : std::chars_format::fixed;

      if (auto [ptr, ec] = std::to_chars(str.data(), str.data() + str.size(), f, format, precision); ec == std::errc())
      {
        target.append(str.data(),  ptr - str.data());
      }
      else
      {
        target = "conversion error";
      }
      return;
    }

    template <typename T>
    inline String toString(const T& i, int precision)
    {
      String str;
      append(i, str, precision);
      return str;
    }
    
```

**Comment by timosachsenberg** [comment]
another possibility that could work is to add  if (abs_f < std::numeric_limits<T>::min()) { target = "0.0"; return; } in our code as a workaround

**Comment by cbielow** [comment]
just to amend what the original problem was: `Program terminated with signal: SIGSEGV` when using KARMA with subnormals
