### ISSUE TITLE
DOPENMS_CONTRIB_LIBS

### ISSUE THREAD

**Issue by DrBoothTJ** [OpenMS/OpenMS#6509]
I am trying to build OpenMS for linux and at this step:

`cmake -DOPENMS_CONTRIB_LIBS="../contrib-build" -DBOOST_USE_STATIC=OFF -DCMAKE_PREFIX_PATH="/usr;/usr/local" ../OpenMS
`
I am getting the following error:

```
CMake Error in src/tests/class_tests/openms/CMakeLists.txt:
  Imported target "CoinOR::CoinOR" includes non-existent path

    "COIN_INCLUDE_DIR-NOTFOUND"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

Any suggestions?

Thanks a lot!! :)

**Comment by jpfeuffer** [comment]
Hi!

Can you try using an absolute path for the OPENMS_CONTRIB_LIBS parameter?
If this does not help, you need to debug and check if coinor was actually correctly built.

**Comment by DrBoothTJ** [comment]
Hi!

Thanks for the quick response.  I tried that and checked that the coinor was correctly built. The problem is it is built correctly, but the makefile doesn't find it properly. Any more ideas?

Thanks!

**Comment by jpfeuffer** [comment]
Hi,

can you reset the CMakeCache by deleting the corresponding file in the build dir?
