### ISSUE TITLE
New openms-executables container with latest tag...

### ISSUE THREAD

**Issue by edwardsnj** [OpenMS/OpenMS#6513]
18 hours ago, a new openms-executables container with the tag "latest" was pushed to the container repository.

My use of the IDFileConverter tool fails because it cannot read the input files in a directory mounted as a volume.

The container with tag 2.8.0 still works, no problems, same volume setup. 

What changed? I suspect some kind of user-permission issue - but I can't find the docker files these containers are built from in github to see if that might explain the difference. 

I've learned my lesson and will specify an explicit version number from here on out - I can't rely on "latest" pointing to a stable version of the container, I guess. 

Thanks for any insight you can provide. 

- n

**Comment by jpfeuffer** [comment]
Hi!

True. Latest will pass our CI tests but is not guaranteed to be stable.
We updated the base image to ubuntu 22.04 and boost to 1.74 due to bugs in boost.
That should have been everything.

**Comment by jpfeuffer** [comment]
docker files are here: https://github.com/OpenMS/dockerfiles
builds here: https://github.com/OpenMS/OpenMS/actions/workflows/dockerdeploy.yml

**Comment by edwardsnj** [comment]
I suspect something deeper is afoot - I've checked that the user running docker can see the files from a running docker container with it mounted in this fashion.

+ ls -l AP1_QEHF1_AP1_2_02.mzML.gz AP1_QEHF1_AP1_2_02.mzid
-rw-r--r-- 1 galaxy users  89874219 Nov 29 20:27 AP1_QEHF1_AP1_2_02.mzid
-rw-r--r-- 1 galaxy users 132037333 Nov 29 20:27 AP1_QEHF1_AP1_2_02.mzML.gz
+ docker run -u 10010:100 -v /mnt/galaxy/tmp/job_working_directory/006/6499/working:/data/ --rm ghcr.io/openms/openms-executables:latest IDFileConverter -in /data/AP1_QEHF1_AP1_2_02.mzid -out /data/AP1_QEHF1_AP1_2_02.idXML -mz_file /data/AP1_QEHF1_AP1_2_02.mzML.gz
Cannot read input file given from parameter '-in'!
Error: File empty (the file '/data/AP1_QEHF1_AP1_2_02.mzid' is empty)

Hmmmmmm

**Comment by edwardsnj** [comment]
Yes, of course I found them once I submitted the ticket - looks like the docker files haven't changed. I can't tell if the issue is the program itself (maybe due to boost) or something about how the container is built (looks like the deploy strategy has changed a bit recently). The error message is so basic, seems unlikely to be due to the program itself.

**Comment by jpfeuffer** [comment]
Could you try without mounting?
Login to the container into a bash, maybe download the file with wget and try to run that from inside the container.

**Comment by edwardsnj** [comment]
Here is what happens when I run the "latest" container with bash:

docker run -it --rm ghcr.io/openms/openms-executables:latest /bin/bash
ls -l
d????????? ? ? ? ?            ? OpenMS
l????????? ? ? ? ?            ? bin
d????????? ? ? ? ?            ? boot
d????????? ? ? ? ?            ? contrib
d????????? ? ? ? ?            ? contrib-build
d????????? ? ? ? ?            ? dev
d????????? ? ? ? ?            ? etc
d????????? ? ? ? ?            ? home
l????????? ? ? ? ?            ? lib
l????????? ? ? ? ?            ? lib32
l????????? ? ? ? ?            ? lib64
l????????? ? ? ? ?            ? libx32
d????????? ? ? ? ?            ? media
d????????? ? ? ? ?            ? mnt
d????????? ? ? ? ?            ? openms-build
d????????? ? ? ? ?            ? opt
d????????? ? ? ? ?            ? proc
d????????? ? ? ? ?            ? root
d????????? ? ? ? ?            ? run
l????????? ? ? ? ?            ? sbin
d????????? ? ? ? ?            ? srv
d????????? ? ? ? ?            ? sys
d????????? ? ? ? ?            ? thirdparty
d????????? ? ? ? ?            ? tmp
d????????? ? ? ? ?            ? usr
d????????? ? ? ? ?            ? var


docker run -it --rm ghcr.io/openms/openms-executables:2.8.0 /bin/bash                                    
I have no name!@5dba3943bff0:/$ ls -l
total 84
drwxr-xr-x   1 root  root  4096 Feb 21  2022 OpenMS
drwxr-xr-x   2 root  root  4096 Jan 28  2022 bin
drwxr-xr-x   2 root  root  4096 Apr 24  2018 boot
drwxr-xr-x   6 root  root  4096 Feb 16  2022 contrib
drwxr-xr-x   1 root  root  4096 Feb 16  2022 contrib-build
drwxr-xr-x   5 root  root   360 Nov 29 22:21 dev
drwxr-xr-x   1 root  root  4096 Nov 29 22:21 etc
drwxr-xr-x   2 root  root  4096 Apr 24  2018 home
drwxr-xr-x   1 root  root  4096 Feb 16  2022 lib
drwxr-xr-x   2 root  root  4096 Jan 28  2022 lib64
drwxr-xr-x   2 root  root  4096 Jan 28  2022 media
drwxr-xr-x   2 root  root  4096 Jan 28  2022 mnt
drwxr-xr-x   1 root  root  4096 Feb 21  2022 openms-build
drwxr-xr-x   2 root  root  4096 Jan 28  2022 opt
dr-xr-xr-x 253 root  root     0 Nov 29 22:21 proc
drwx------   1 root  root  4096 Feb 16  2022 root
drwxr-xr-x   5 root  root  4096 Jan 28  2022 run
drwxr-xr-x   2 root  root  4096 Jan 28  2022 sbin
drwxr-xr-x   2 root  root  4096 Jan 28  2022 srv
dr-xr-xr-x  13 root  root     0 Nov 29 22:21 sys
drwxr-xr-x  16 root  root  4096 Feb 21  2022 thirdparty
drwxrwxrwt   1 root  root  4096 Feb 21  2022 tmp
drwxr-xr-x   1 root  root  4096 Jan 28  2022 usr
drwxr-xr-x   1 root  root  4096 Jan 28  2022 var

Something is messed up with the users and/or filesystem....

**Comment by jpfeuffer** [comment]
I can reproduce with an old docker. Already the ubuntu:22.04 base image has completely broken permissions.
My suggestion: update docker
