### ISSUE TITLE
update conda thirdparties

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6515]
we removed thirdparties and updated them but no one changed conda

**Comment by timosachsenberg** [comment]
we can also remove sqlite here right? https://github.com/bioconda/bioconda-recipes/compare/master...timosachsenberg:bioconda-recipes:patch-2

**Comment by jpfeuffer** [comment]
Yes but I think bumbershoot too, right?

**Comment by timosachsenberg** [comment]
I don't even know what we used that for. can remove

**Comment by jpfeuffer** [comment]
It contains myrimatch or omssa or something

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/bioconda-recipes/pull/3
