### ISSUE TITLE
TOPPView issues unrelated to refactoring

### ISSUE THREAD

**Issue by enetz** [OpenMS/OpenMS#6521]
- Glitched ID table, some cells aren't visualized sometimes. Can be triggered by resizing ID table.
![ID_table](https://user-images.githubusercontent.com/15832022/205084917-56e4b9e3-979f-4637-a6a5-9a6de6e5c47b.png)

- Warnings during PSM visualization:
`Warning: SpectrumAlignment received the unknown parameter ':tolerance'!`
`Warning: SpectrumAlignment received the unknown parameter ':is_relative_tolerance'!`
`Warning: SpectrumAlignmentScore received the unknown parameter ':tolerance'!`
`Warning: SpectrumAlignmentScore received the unknown parameter ':is_relative_tolerance'!`
Maybe the `:` in front of the names makes trouble somewhere.

- `Peak color array size (58) doesn't match number of peaks (1566) in spectrum.` when clicking on `precursor m/z` values. But not sure whether this actually breaks anything.

**Comment by timosachsenberg** [comment]
@enetz can you investigate this a bit further. I think the second issue is fixed now?

**Comment by jpfeuffer** [comment]
I am pretty sure the missing entries is a qt bug in auto sizing. I tried a lot.

**Comment by cbielow** [comment]
saving IDs was fixed in https://github.com/OpenMS/OpenMS/pull/6519, see https://github.com/OpenMS/OpenMS/commit/83580fb35e65a12d062a3b40c031da84fe4d04a2

the resizing seems a Qt bug.

Closing this issue; reopen if there is evidence that the resize bug can be fixed in our side.
