### ISSUE TITLE
Packaging not working on Windows and macOS

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6528]
See cdash

**Comment by jpfeuffer** [comment]
macOS because of the changes in the fix_dep script
Win because of the new automated dependency copying with CMake. Apparently, it is not as automatic as it seems, you still need to give the Directories where Windows should look for dependencies and create regex to exclude system dependencies. Useless...

**Comment by poshul** [comment]
since https://github.com/OpenMS/OpenMS/pull/6478 we don't need qt's sqlite any more. Would rolling back the changes relating to including it make sense?

**Comment by jpfeuffer** [comment]
It is not about the sqlite plugin.
Packaging/installation was generalized to be platform-independent and ideally soon without any fix_dependency script.

**Comment by jpfeuffer** [comment]
Independent

**Comment by jpfeuffer** [comment]
Maybe now with https://github.com/OpenMS/OpenMS/commit/6700c89e4e9492d45a0062ce654fe7946cfe28a2
and a correct installation of NSIS UMUI plugin @timosachsenberg
