### ISSUE TITLE
ProteomicsLFQ and Sirius test failures

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6529]
see Cdash

**Comment by timosachsenberg** [comment]
I don't see any tests running

**Comment by jpfeuffer** [comment]
https://cdash.openms.de/index.php?project=OpenMS&date=2022-12-02

**Comment by timosachsenberg** [comment]
yeah I know these. but these are only timeouts and I am not sure if they are "real" issues or do I miss something?

**Comment by jpfeuffer** [comment]
Aaah test timeouts. You are correct. Probably not real issues then.
