### ISSUE TITLE
windows build instruction rendering issue 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6533]
![image](https://user-images.githubusercontent.com/5803621/205895714-39b6d503-2860-41b8-883e-0f376bc03a91.png)

**Comment by timosachsenberg** [comment]
https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/install_win.html

**Comment by cbielow** [comment]
I cannot reproduce this on Windows :/
using 
 **doxygen 1.8.16**
on my machine

**Comment by timosachsenberg** [comment]
thanks for checking... let's wait for next nightlies

**Comment by jpfeuffer** [comment]
nightlies are not working due to packaging

**Comment by cbielow** [comment]
I can reproduce this with the latest doxygen (1.9.5). Fixed in #6540 (do not use pipes :) )
