### ISSUE TITLE
NSIS updates necessary

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6534]
Newer CMakes need newer NSIS 3.03+
Needs to be updated and tested on all Windows machines.

**Comment by jpfeuffer** [comment]
I could do that if abibuilder8 were running.

**Comment by timosachsenberg** [comment]
We updated it. Just need confirmation that it works now.

**Comment by poshul** [comment]
Okay, I will give it a shot.

**Comment by poshul** [comment]
I get:
`CMake Error at cmake/package_general.cmake:79 (install):
  install unknown error.` 
with last night's nightly. I assume that https://github.com/OpenMS/OpenMS/commit/b804acf66fdbb884f704ff8be11d8a009fb0c171 fixes this so I'm going to try again tomorrow

**Comment by poshul** [comment]
todo: anchor to UT machine

**Comment by jpfeuffer** [comment]
Depends on #6570 now
