### ISSUE TITLE
The error of proteomics_LFQ workflow

### ISSUE THREAD

**Issue by hello-lei** [OpenMS/OpenMS#6536]
Hi, all. The following is the wrong.
Warning: Parameters file version (2.6.0) does not match the version of this tool (2.7.0).
Your current parameters are still valid, but there might be new valid values or even new parameters. Upgrading the INI might be useful.

  Progress of 'loading spectra list':

   5.69 %               
   21.26 %               
   36.31 %               
   51.38 %               
   66.30 %               
   80.71 %               
   96.19 %               

  -- done [took 6.53 s (CPU), 6.55 s (Wall)] -- 

  Progress of 'loading chromatogram list':

  -- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
Standard output: Running: C:/Program Files/KNIME_4.6.1/../../Users/leiyuanluo/.eclipse/4491160_win32_win32_x86_64/plugins/de.openms.win32.x86_64_2.7.0.202109131426/payload/bin/XTandem/tandem.exe C:/Users/leiyuanluo/AppData/Local/Temp/20221207_102610_LAPTOP-95OADKP6_151336_1/tandem_input.xml

X! TANDEM Vengeance (2015.12.15.2)
Loading spectra| (mzML).
<
> occurred 2 times
Fatal error: unsupported CODEC used for mzML peak data (CODEC type=zlib compression).

Standard error: Process 'C:/Program Files/KNIME_4.6.1/../../Users/leiyuanluo/.eclipse/4491160_win32_win32_x86_64/plugins/de.openms.win32.x86_64_2.7.0.202109131426/payload/bin/XTandem/tandem.exe' did not finish successfully (exit code: 枚). Please check the log.

XTandemAdapter took 7.35 s (wall), 6.84 s (CPU), 0.45 s (system), 6.39 s (user); Peak Memory Usage: 130 MB.
![image](https://user-images.githubusercontent.com/83147334/206079651-becfbd8b-5129-45aa-a637-bd73225737c2.png)

**Comment by jpfeuffer** [comment]
Hi
Xtandem does not support zlib compressed mzml.
Please convert your files differently.

**Comment by hello-lei** [comment]
Yeah, How convert the files? I dowload the workflow from the https://abibuilder.cs.uni-tuebingen.de/archive/openms/Tutorials/Data/. I just excuted the flow.
Thank you!

**Comment by jpfeuffer** [comment]
which files did you exactly download?

**Comment by hello-lei** [comment]
ehh, I dowload the data file（.mzML, .fasta file）from this web. https://abibuilder.cs.uni-tuebingen.de/archive/openms/Tutorials/Data/.
The workflow from this web. https://hub.knime.com/openms-team/spaces/Blog%20workflows/latest/Protein%20label-free%20quantification~Q8TgAl_OAuerfhES.

**Comment by hello-lei** [comment]
Now, I add the fileconvert node to sove this problem. It can be excuted.

**Comment by jpfeuffer** [comment]
Ok good. I was wondering which subfolder of Data you were using.
