### ISSUE TITLE
GitPod rebuilding during init

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6538]
Should not happen!
Sqlite stuff??

**Comment by timosachsenberg** [comment]
I think this is fixed. Did load the prebuild for me.

**Comment by jpfeuffer** [comment]
of course it was a clash of options between us and the rudimentary included sqlitecpp.
#6576

**Comment by timosachsenberg** [comment]
just for the newbies from a pro persepctive... what would a proper include of sqlitecpp entail?

**Comment by jpfeuffer** [comment]
Almost everything, except copy and paste where every variable leaks into/out from the different build systems.

FetchContent, ExternalProject, add_custom_command, contrib, external dependency manager, ...
