### ISSUE TITLE
AddressSanitizer issues with FlashDeconv

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6544]
There seems to be a small memory leak:
https://cdash.openms.de/test/22397705
https://cdash.openms.de/test/22394831
https://cdash.openms.de/test/22394978
(all pointing to the same array in calculateAveragine)

**Comment by KyowonJeong** [comment]
Fixed!

**Comment by cbielow** [comment]
there are two more (new ones?)
https://cdash.openms.de/viewTest.php?onlyfailed&buildid=48609

**Comment by jpfeuffer** [comment]
PR was closed. It was never fixed.

**Comment by KyowonJeong** [comment]
OK. I fixed this locally at some point... But maybe it has been revoked when there were big mingle in FLASHDeconv FLASHDeconvDevelop etc. branches and I lost this fix... I will recheck this issue.

**Comment by jpfeuffer** [comment]
Hopefully closed in the linked PR
