### ISSUE TITLE
Documentation is not up to date with latest pypi release

### ISSUE THREAD

**Issue by PierreSnell** [OpenMS/OpenMS#6560]
The latest pypi release is 2.7.0. 

However, in the documentation, at the end we can see `consensus_map.get_df()` which is not present in the 2.7.0 version (but is if we install the nightly build). 

Could you update pypi to the latest (2.7.0 or 2.8.0) ? 

Thanks a lot for this wonderful library. 
Have a great day :)

**Comment by jpfeuffer** [comment]
Yes, that is unfortunate.

First of all, 2.7 should be there.
2.8 was basically forgotten because it was our first conda release. Now our infrastructure does not allow for an automated build of that branch and no one volunteered to do it.

We usually tell people to use conda, self-build, or wait for 3.0 which is coming very soon.

**Comment by PierreSnell** [comment]
Hi @jpfeuffer, Thanks for the fast replies! Really appreciated. 

Indeed 2.7 is here but is lacking some features of the doc (like get dataframe and type hints which are really useful). Maybe pushing a 2.7.1 could fix the problem? 

Else, for the nightly build, having a .zip does not allow me to install it directly via poetry or pip. 
Is there a possibility for the team to host directly the .whl files somewhere? 

Again sorry for asking things for my specific workflow, and thanks again for all your hard work on this amazing toolbox! 
If that's not planned, I'll wait for the 3.0 version. 
Have a great day.

**Comment by jpfeuffer** [comment]
Hi! Good that you mention. Yes, we have a pypi repo since last week or so.
But it also still has some problems as it seems https://github.com/OpenMS/pyopenms-docs/issues/323
This will make it more convenient to pull for all of us.
