### ISSUE TITLE
Conda builds broken

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6563]
`ImportError: /opt/conda/lib/python3.9/site-packages/pyopenms/_pyopenms_2.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK6OpenMS12MSExperiment14areaBeginConstEdddd`

**Comment by timosachsenberg** [comment]
hi @cbielow did not look into detail but the area iterator rang a bell

**Comment by jpfeuffer** [comment]
Can also be due to mismatches in library vs pyopenms on our conda channel. @timosachsenberg can you check that everything is in sync?

**Comment by jpfeuffer** [comment]
Yep. Problem is that @timosachsenberg reduced the python versions to build for. Some of them are out-of-date now.

**Comment by timosachsenberg** [comment]
I think I build for 9,10,11 .
Which one is out of date now?

**Comment by jpfeuffer** [comment]
Maybe we can force an EXACT match of the build hash.

**Comment by jpfeuffer** [comment]
Last upload 7 days ago: https://anaconda.org/openms/pyopenms

**Comment by jpfeuffer** [comment]
lib was updated tonight.

**Comment by jpfeuffer** [comment]
They work again with the recent changes in the build-config.yml on our nightly bioconda-recipes fork. We still need a little fix the build status logic though.

**Comment by timosachsenberg** [comment]
the upload variable return code is apparently 0... it seemed to work though

**Comment by jpfeuffer** [comment]
0 is good.

**Comment by timosachsenberg** [comment]
yeah, but the other ones aren't:
openms-meta built: 1
pyopenms built: 1
upload: 0
but I guess this is the problem you mentioned with the conda build command
