### ISSUE TITLE
IDRipper stalls on large idXML file

### ISSUE THREAD

**Issue by zhuchcn** [OpenMS/OpenMS#6579]
Hi, we are trying to split an idXML file that was merged from fractionated ones, and IDRipper stalls on it. The file is about 2.5G, with 31 fractions. The last run was submitted about 9 hours ago. The message being printed out is below. I tried it with a subset of the idXML with only 100 PSMs from each fraction and it finishes in 2 minutes.

```
Value of string option 'test': 0
The OpenMS team is collecting usage statistics for quality control and funding purposes.
We will never give out your personal data, but you may disable this functionality by
setting the environmental variable OPENMS_DISABLE_UPDATE_CHECK to ON.
Connecting to REST server successful.
Debug level (after ini file): 2
Value of string option 'no_progress': 0
Value of string option 'in': Liver_Comet_idswitch_pep.idXML
Checking input file 'Liver_Comet_idswitch_pep.idXML'
Value of string option 'out': split
Checking output file 'split'
Value of string option 'numeric_filenames': 0
Value of string option 'split_ident_runs': 0
IDRipper.cpp(192): Detected file origin annotation format: id_merge_index
```

I'm guessing it is because the block below so the two layer for loop makes it really inefficient. So it needs to go thought all ProteinHits for every PeptideIdentification, which makes it n x m. Maybe can consider using a Map from accession to protein hits to quickly get the ProteinHit object from key?

https://github.com/OpenMS/OpenMS/blob/e1d5db34907273658e9c8c585be3557cebb1ace7/src/openms/source/ANALYSIS/ID/IDRipper.cpp#L388-L400

**Comment by jpfeuffer** [comment]
Similar quadratic implementation in #6072 which has a bit higher priority imho. If you have some time, maybe start there?

**Comment by jpfeuffer** [comment]
Maybe IDRipping is not even necessary it mapping is finally done file-aware and efficienctly

**Comment by zhuchcn** [comment]
> Maybe IDRipping is not even necessary if mapping is finally done file-aware and efficienctly

IDRipper would still be helpful for fractionated label free, that we want to calculate FDR/PEP with all fractions combined and then split back to fraction specific and do feature detection & peptide quantitation on fraction level. So will be really thankful if this can be fixed if it's quick! 🙏

**Comment by timosachsenberg** [comment]
Wouldn't that be something that the ProteomicsLFQ tool already does? It takes as input the identifications and an experimental design that specifies the fraction numbers and groups (usually samples) and performs feature detection, quantification, and FDR. Information in which fraction a peptdide was quantified is still present in the output.

**Comment by jpfeuffer** [comment]
PLFQ does not do experiment wide peptide FDR. Everything else, yes.

**Comment by zhuchcn** [comment]
Yup we are leaning towards peptide FDR across all fractions. Another reason that we choose running the steps separately is that we can skip steps that we don't necessarily need. For example we are doing custom DB searching, so I think this allows us to customize our pipeline better.

**Comment by timosachsenberg** [comment]
k thanks for testing. I will give it a closer look...

**Comment by timosachsenberg** [comment]
I think I found abug that led to many, slow internal copies. Preparing a fix.

**Comment by timosachsenberg** [comment]
k I think this one is good for testing: https://github.com/OpenMS/OpenMS/pull/6590

**Comment by zhuchcn** [comment]
Seems like the speed is drastically improved! But I saw this error message unfortunately and not all fractions were successfully written. It could be that my idXML is somehow messed up. Will try a different one later and update it here!

```
Error: Unexpected internal error (the element 'No accession ENSMUSP00000074724.6 found in run 'Percolator_2023-01-05T09:17:30_14144901395523701363' for PSM SGEIEPVSVK_2. Please contact the maintainer of this tool e.g. on GitHub as this should not happen.' could not be found)
```

**Comment by timosachsenberg** [comment]
It could well be that I introduced an error. If you have anything to share to reproduce it I am happy to look at it.

**Comment by timosachsenberg** [comment]
I think I now added handling of identical search identifiers. Can you give this a try? If that one still fails I would probably need a test file that you can send me in private.

**Comment by zhuchcn** [comment]
It worked! Finished in 3 min! Thank you @timosachsenberg ! 🥳 

```
IDRipper took 02:59 m (wall), 02:48 m (CPU), 6.46 s (system), 02:41 m (user); Peak Memory Usage: 5330 MB.
```

**Comment by timosachsenberg** [comment]
Awesome. Thanks for testing and reporting the issue!
