### ISSUE TITLE
Windows installer incredibly slow, due to logging of doc Files to uninstall 

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6588]
We use an AdvUninstaller plugin which is crap. Even in its second iteration. Increases installation time from 30 seconds to 5-10 minutes.
Do we need this feature?
@timosachsenberg @poshul

**Comment by timosachsenberg** [comment]
hmm no clue. I think it was there forever. :)

**Comment by jpfeuffer** [comment]
Yes, but do we need it? We can just delete the whole folder. Unless someone puts user data in the installation folder, it wont make a difference

**Comment by timosachsenberg** [comment]
I don't know the details what NSIS does. e.g. adding registry keys etc. but I think we can just remove it and try if it makes such a big difference.

**Comment by jpfeuffer** [comment]
The functionality that I mean, It just creates an uninstall.dat that lists all the files we installed.
This will be used to uninstall.
I have NO idea how this can be so slow but it is.

**Comment by timosachsenberg** [comment]
and it is not related to anti malware services etc? because I recall that in older windows versions it wasn't that slow

**Comment by jpfeuffer** [comment]
It might be some misuse of the plugin. I will do some further testing tomorrow. See my PR.

**Comment by poshul** [comment]
Have we updated this?

**Comment by jpfeuffer** [comment]
Yes, it should be better now. I think now the slowness is mostly from Antivirus programs.
