### ISSUE TITLE
GH Actions tests show wrong exit code

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6596]
After my caching changes.

**Comment by timosachsenberg** [comment]
I think I recall in Chris PR that some CDash entries fit another PR.

**Comment by jpfeuffer** [comment]
"fit another PR"?

**Comment by timosachsenberg** [comment]
the fix by chris submitted a failing fuzzydiff test that indicate that add_decoy option is missing. something that was part of the MSGF PR

**Comment by timosachsenberg** [comment]
ah yeah I see it:
Total Test time (real) = 334.86 sec
e.g.:
The following tests FAILED:
	2463 - UTILS_FeatureFinderMetaboIdent_1_out1 (Failed)
	2536 - UTILS_PSMFeatureExtractor_2_out (Failed)
Submit files
   Send to group: Continuous

but the run shows as successful

**Comment by timosachsenberg** [comment]
is this related to the launcher?
https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/openms-ci.yml#L279
e.g., does the return value get lost here?

**Comment by jpfeuffer** [comment]
the exit status depends on the exit status of the cmake script.
https://github.com/OpenMS/OpenMS/blob/develop/tools/ci/cibuild.cmake#L114
With a "message" in the end it will never fail. You either need to check the cmake output files or add logic in the cmake script to fail.
