### ISSUE TITLE
Nightly Windows installer throws errors about package installation

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#6598]
![Screenshot 2023-01-17 084745](https://user-images.githubusercontent.com/146827/212843296-60264c79-a0bf-4be7-a9cd-5db6ac759fdc.png)
![Screenshot 2023-01-17 084855](https://user-images.githubusercontent.com/146827/212843314-350f4297-cce6-46dc-9e8e-f6791bb6e332.png)

The latest (16.1) nightly throws errors when trying to install .net 3.5 (top), .net 4.0 (not pictured), and the VSRedistributable (above). The installation does complete despite the errors on a windows machine which had the .net and VSRedist. packages installed already.

**Comment by timosachsenberg** [comment]
maybe because of the removed UAC plugin?

**Comment by jpfeuffer** [comment]
Yes you need to:
1) deactivate proteowizard (it is mentioned in the components that it needs admin)
2) install for all users which triggers an admin request
3) run as admin from the start

**Comment by jpfeuffer** [comment]
Which means this is intended.
.Net is installed on newer Windows machines anyway.
Regarding VSRedist: Pwiz ships so many VSRedist DLLs. I honestly think all those redist installers are unnecessary.
But no one volunteers to test it. See my Pwiz issue.

And lastly there are 4 workarounds.

**Comment by poshul** [comment]
The other vcredist packages correctly generate a UAC pop-up, its just the 2010 one that does not. I've tracked that down to a bug: https://github.com/jberezanski/ChocolateyPackages/issues/102 a newer version of the 3.5 x86 redist should correctly ask for elevation. I'm going to dig around and see if I can find newer .net installers that correctly request escalation as well.

I don't think the current behavior is going to be acceptable for windows users. Someone who just wants to try out OpenMS should be able to install with as little friction as possible. To me that means that we either need to install for all users by default, disable proteowizard by default for un-elevated installation, or fix the packages as I propose above.

**Comment by jpfeuffer** [comment]
Sure. We could do all.
I actually have exactly the opposite opinion. If you just want to "try", you do NOT want to call your local admin.
And I think most of our users might not have admin rights (companies, university computers).
But yes, changing the defaults wont hurt.

**Comment by jpfeuffer** [comment]
Did you check if it works with All users/run as admin?

**Comment by poshul** [comment]
Yup. Looks to work fine with All users.
