### ISSUE TITLE
Testing of TOPPView of current develop branch on Windows

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6602]
Putting this into an issue, so it is easier assignable on a per-platform basis.
Please add an issue and link it here if you encounter a new bug (one that is not listed here: https://github.com/OpenMS/OpenMS/issues?q=is%3Aissue+is%3Aopen+label%3ATOPPView )

Test TOPPView 1D, 2D, 3D. mzML, FeatureXML, consensusXML. IdentificationView. Running a tool (preferably with new functionality, like NASE).

**Comment by KyowonJeong** [comment]
In windows as well, Input files for TOPP tools can not be loaded https://github.com/OpenMS/OpenMS/issues/6637
Tested for FLASHDeconv, FIleInfo, and a few more tools.

**Comment by KyowonJeong** [comment]
"log" intensity button is not deselected (unless it is not intended).

**Comment by KyowonJeong** [comment]
Chromatogram open crashs

1. File -> Open example file -> Chromatograms -> Syogenes.chrom.mzML
2. In the bottom windows, select "views" and if any item  (e.g., Peptide 0 559.788 AAGGISSLEDAK 0" is selected, it crashes.

Screenshot: https://capture.dropbox.com/yuwwrOdfxNGFWHns

**Comment by KyowonJeong** [comment]
Ctrl + w is not working (to close a tab).

**Comment by KyowonJeong** [comment]
Ctro + A does not select annotations but opens a window to read a featureXML file in 1-D mode.
https://capture.dropbox.com/hmRtKKFYKmx4Amdd

**Comment by timosachsenberg** [comment]
If you have time please check out new version by Chris in develop and test the old issues you foud to confirm they are gone (and report new ones ;) .

**Comment by KyowonJeong** [comment]
I will recheck the bugs!
