### ISSUE TITLE
Testing of TOPPView of current develop branch on Linux

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6603]
Putting this into an issue, so it is easier assignable on a per-platform basis.
Please add an issue and link it here if you encounter a new bug (one that is not listed here: https://github.com/OpenMS/OpenMS/issues?q=is%3Aissue+is%3Aopen+label%3ATOPPView )

Test TOPPView 1D, 2D, 3D. mzML, FeatureXML, consensusXML. IdentificationView. Running a tool (preferably with new functionality, like NASE).

**Comment by axelwalter** [comment]
Input files for TOPP tools can not be loaded #6637

**Comment by axelwalter** [comment]
Clicking in the identifications list can crash TOPPView #6638

**Comment by timosachsenberg** [comment]
Please check out new version by Chris (current develop) and test the old issues you foud to confirm they are gone (and report new ones ;) .

**Comment by axelwalter** [comment]
The old issues are gone in current develop.
