### ISSUE TITLE
IDMapper. Contradicting usage instructions.

### ISSUE THREAD

**Issue by ivandatasci** [OpenMS/OpenMS#6614]
Hello everyone.

Please visit
https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/release/2.8.0/html/TOPP_IDMapper.html

Notice that those instructions say "Additional options for mzML input:".

That is contradicting the beginning of the document where it lists the acceptable input formats, none of which is .mzML.

Would it be possible to add some clarity so that I can understand the purpose of the tool and how to use it?

Thank you.

**Comment by jpfeuffer** [comment]
Hi!

Yes, this is well-structured. Can you check #6615 if this helps your understanding?

**Comment by ivandatasci** [comment]
> Hi!
> 
> Yes, this is not well-structured. Can you check #6615 if this helps your understanding?

Hi Julianus.
I checked [#6615](https://github.com/OpenMS/OpenMS/pull/6615). There is no apparent contradiction and _I think_ that I understand the purpose of the tool a little better.
Thank you.
