### ISSUE TITLE
FileConverter. Option to switch off zlib compression is not shown in the usage message.

### ISSUE THREAD

**Issue by ivandatasci** [OpenMS/OpenMS#6625]
The documentation for [XTandemAdapter](https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/release/2.8.0/html/TOPP_XTandemAdapter.html) includes a very visible note saying that the tool only accepts plain (no zlib compressed) .mzML files.

The note advises the use of [FileConverter](https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/release/2.8.0/html/TOPP_FileConverter.html) to create those .mzML without zlib compression.

Could the proper option be added to FileConverter's usage message?

Thank you for OpenMS.

**Comment by poshul** [comment]
@AmandaWein would you have a chance to take a look at this?

**Comment by poshul** [comment]
@ivandatasci We've integrated this option into our documentation on the nightly version (we are hoping to do a major release shortly which will also include this change) you can get the nightly at https://abibuilder.cs.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/OpenMS-3.0.0-pre-nightly-2023-02-01-Win64.exe
