### ISSUE TITLE
PercolatorAdapter. Bug in usage message.

### ISSUE THREAD

**Issue by ivandatasci** [OpenMS/OpenMS#6628]
Issuing the command `PercolatorAdapter --helphelp` produces the expected message.

However, doing so in v2.8.0 produces two conflicting instructions for using `-post-processing-tdc`.

    -post_processing_tdc <value>                 Use target-decoy competition to assign q-values and PEPs. (default: 'true' valid: 'true', 'false')
    -post_processing_tdc                         Use target-decoy competition to assign q-values and PEPs.

**Comment by cbielow** [comment]
I will look into that.
Thanks for bringing this to our attention!
