### ISSUE TITLE
Pyopenms doc errors in plotting

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6636]
```

/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/pyopenms/plotting.py:docstring of pyopenms.plotting.mirror_plot_spectrum:4: CRITICAL: Unexpected section title.

Parameters
----------
/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/pyopenms/plotting.py:docstring of pyopenms.plotting.mirror_plot_spectrum:22: CRITICAL: Unexpected section title.

Returns
-------
/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/pyopenms/plotting.py:docstring of pyopenms.plotting.plot_chromatogram:4: CRITICAL: Unexpected section title.

Parameters
----------
/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/pyopenms/plotting.py:docstring of pyopenms.plotting.plot_spectrum:4: CRITICAL: Unexpected section title.

Parameters
----------
/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/pyopenms/plotting.py:docstring of pyopenms.plotting.plot_spectrum:29: CRITICAL: Unexpected section title.

Returns
-------
```

**Comment by matteopilz** [comment]
Where do you get this error?

**Comment by jpfeuffer** [comment]
GitPod, cd docs && make html in my case.

**Comment by matteopilz** [comment]
I don't have this error. So you call `make html` inside the doc folder of OpenMS-build?

**Comment by jpfeuffer** [comment]
no, doc errors show in pyopenms-docs. But the code is here, so I opened the issue here.

**Comment by matteopilz** [comment]
Do I have to link OpenMS somehow to pyopenms-docs?

**Comment by jpfeuffer** [comment]
pyopenms-docs uses pyopenms-nightly from our pypi to parse documentation.

**Comment by jpfeuffer** [comment]
If you really really need to test it, I would suggest to run the docs and edit the plotting.py module right in your pip site-packages folder. Then re-run docs etc.

**Comment by matteopilz** [comment]
I have tested it so far and it looks strange. The docstrings are from Wout's original implementation and as far as I can see it, look perfectly normal. I removed the section underlines for `Parameter` and `Return`, which got rid of some of the errors, but now some indentation errors and missing blank line warnings pop up.

**Comment by jpfeuffer** [comment]
If you are using non-sphinx docstrings you will need extensions.
Either he has those extensions or he does not use sphinx.
