### ISSUE TITLE
TOPPView: Crash when clicking in identifications list

### ISSUE THREAD

**Issue by axelwalter** [OpenMS/OpenMS#6638]
Tested on Ubuntu 22.10.
Hard to reproduce therefore I included the video. Opening a random idXML file with matching mzML file will annotate identifications. Clicking on one in the list will open a new tab. Going back to the original tab and clicking on another identification will crash TOPPView with Segmentation fault.

[Screencast from 2023-01-31 13-41-55.webm](https://user-images.githubusercontent.com/72203175/215764673-f050e641-972e-44b7-a7ee-1cac30e40236.webm)

**Comment by JeeH-K** [comment]
#6637

**Comment by JeeH-K** [comment]
Kinda similar in MacOS as well. TOPPView crashes far more often at .idXML file.
