### ISSUE TITLE
IDScoreSwitcher. Bug in documentation.

### ISSUE THREAD

**Issue by ivandatasci** [OpenMS/OpenMS#6649]
The usage message shows the `-protein` option twice.

    IDScoreSwitcher --helphelp
    ...
    Usage:
      IDScoreSwitcher <options>

    Options (mandatory options marked with '*'):
      -in <file>*                      Input file (valid formats: 'idXML')
      -out <file>*                     Output file (valid formats: 'idXML')
      -proteins                        Apply to protein scores instead of PSM scores
      -new_score <text>                Name of the meta value to use as the new score
      -new_score_orientation <choice>  Orientation of the new score (are higher or lower values better?) (valid: 'lower_better', 'higher_better')
      -new_score_type <text>           Name to use as the type of the new score (default: same as 'new_score')
      -old_score <text>                Name to use for the meta value storing the old score (default: old score type)
      -proteins                        Apply to protein scores instead of PSM scores
    ...

**Comment by cbielow** [comment]
Thank you for taking the time to teport this.

The bug is already fixed in #6632 along with the duplicate param in PercolatorAdapter (and others) which you teported :-)
