### ISSUE TITLE
Sirius fails in ALL nightlies

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6659]
https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/job/TstPkg/

**Comment by axelwalter** [comment]
@jpfeuffer Could you post a link to the failing Sirius tests? Can't find them in the link above.

**Comment by axelwalter** [comment]
Sirius servers are down right now, could be the issue here.

**Comment by axelwalter** [comment]
We are still on the 5.6.3 snapshot, will update to release soon.

**Comment by eeko-kon** [comment]
Worker instances seem to be available today - they had a huge backlog the past few days so I had issues on and off too.

**Comment by jpfeuffer** [comment]
Thanks for reporting. We also decided yesterday to wait 2-3 days more and close if it stops failing.
