### ISSUE TITLE
ImportError: cannot import name 'plotting' from 'pyopenms'

### ISSUE THREAD

**Issue by phage-GP** [OpenMS/OpenMS#6666]
**ImportError**

ImportError: cannot import name 'plotting' from 'pyopenms'

An error occurred when I tried to use 'plot_spectrum' function according to pyopenms document
>https://pyopenms.readthedocs.io/en/latest/_autosummary/pyopenms.plotting.plot_spectrum.html#pyopenms.plotting.plot_spectrum

Here is my code:

```python
from pyopenms import MSSpectrum
from pyopenms import plotting
import matplotlib.pyplot as plt
import pandas as pd
```

and error report message
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [39], in <cell line: 2>()
      1 from pyopenms import MSSpectrum
----> 2 from pyopenms import plotting
      3 import matplotlib.pyplot as plt
      4 import pandas as pd

ImportError: cannot import name 'plotting' from 'pyopenms' 
```

I want to know whether the API has changed.

**Comment by phage-GP** [comment]
After reviewing the source code, you can find that the relevant api has indeed changed.

Here is the source code file `Anaconda\envs\xxx\Lib\site-packages\pyopenms\Plotting.py`
```python
def plotSpectrum(s):
    import pylab
    x, y = s.get_peaks()
    pylab.bar( x, y )
    pylab.xlabel("m/z")
    pylab.ylabel("Intensity")
    pylab.show()
```

So the modified code can run successfully,
```python
from pyopenms.Plotting import plotSpectrum
```

**Comment by matteopilz** [comment]
The documentation https://pyopenms.readthedocs.io/en/latest/_autosummary/pyopenms.plotting.html#module-pyopenms.plotting is for pyOpenMS 2.8 and up. The old plotting functions are only supported in 2.7 and lower. The new pyOpenMS version (3.0) can be installed for example using our nightly builds: https://pyopenms.readthedocs.io/en/latest/installation.html#nightly-ci-wheels.
