### ISSUE TITLE
TOPPView on windows log intensity button not deactivated

### ISSUE THREAD

**Issue by KyowonJeong** [OpenMS/OpenMS#6667]
"log" intensity button is activated by clicking but not deactivated when again clicking. Maybe it is intended. But It seems a bit inconvenient.

**Comment by timosachsenberg** [comment]
ah I think this is expected... e.g., there are actually 4 drawing modes (%, etc...) between one can choose the scaling. So there is no logic for untoggling.

**Comment by KyowonJeong** [comment]
Oh thanks! I did not know. And makes sense :)

**Comment by timosachsenberg** [comment]
thanks for reporting. maybe this is not ideal from a user interface perspective ...
