### ISSUE TITLE
TOPPView on windows : Measure mode not working properly for MS2 spectrum

### ISSUE THREAD

**Issue by KyowonJeong** [OpenMS/OpenMS#6669]
In MS1, shift + mouse dragging gives me the m/z distance easily. 
In MS2 spectrum, some times this function seems deactivated. And dragging from left to right does not work all the time.

**Comment by timosachsenberg** [comment]
I can annotate in MS2 on linux.
![image](https://user-images.githubusercontent.com/5803621/216951884-2485df17-e813-4bb8-8197-aaf3d02e64d4.png)

Do you mean dragging of an existing distance annotation?  I think this is intended as it indicates the distance between two peaks (thus should only work vertically)

**Comment by timosachsenberg** [comment]
@KyowonJeong just to confirm that this is a bug.
In MS2 you can't sometimes connect two peaks when you start the arrow on a left peak and drag it to a right peak?

**Comment by timosachsenberg** [comment]
ping @KyowonJeong

**Comment by KyowonJeong** [comment]
Tried new version and it works fine now. BUT One more issue here:
1. If you select a peak to measure distance between to anther, it works.
2. But if you want to measure distance from the previously selected peak to a different peak, the measurement does not start.

**Comment by timosachsenberg** [comment]
hmm what I observe is that: if one doesn't hover over a peak (e.g., no peak is marked with the red cross) when starting a distance measurement, then only a vertical red line is plotted. - this is kind of a bug but not so serious.

Could it be that the previous peak was not selected (e.g., the mouse was a bit off) when you started distance measurement?

**Comment by KyowonJeong** [comment]
Oh you are right. So I need to make sure the red cross appears on top of the second peak in any measure. Then the measure completes without any error. Thanks @timosachsenberg !
