### ISSUE TITLE
TOPPView on windows : some hot key mappings may be incorrect.

### ISSUE THREAD

**Issue by KyowonJeong** [OpenMS/OpenMS#6670]
1. Ctrl + w is supposed to close a tab according to the tutorial https://openms.readthedocs.io/en/latest/openms-applications-and-tools/visualize-with-openms/hotkeys-table.html.  But it does not working.
2. Ctrl + a does not select annotations but opens a window to read a featureXML file in 1-D mode.
<img width="1495" alt="Screenshot 2023-02-06 at 10 41 20 AM" src="https://user-images.githubusercontent.com/38280645/216944016-d4103ea1-0058-4c1b-a650-06218020031d.png">

**Comment by timosachsenberg** [comment]
@cbielow do you think the tutorial or TOPPView needs an update here?

**Comment by axelwalter** [comment]
Confirmed on Ubuntu 22.10, closing tabs with ctrl+w is very convenient and should work.

**Comment by cbielow** [comment]
Weirdly, `Qt::Key_W` is only used in TOPPViewMenu (and TOPPAS, but thats a different application).
On the console it says: `QAction::event: Ambiguous shortcut overload Qt::Key_W`. But I dont see where the second overload is registered.
Also, when you focus other parts of the app (e.g. click the log window), then Ctrl-W works flawlessly. So the overload happens in the Canvas/Widget2D?! But I cannot find it...

**Comment by jpfeuffer** [comment]
CtrlW is defined internally by QMdiArea (the multi window thingy).

https://itecnote.com/tecnote/c-qt-remove-shortcut-ambiguous-shortcut-overload/
