### ISSUE TITLE
"pattern and collected intensities don't match" error in MetaproSIP

### ISSUE THREAD

**Issue by xyz1396** [OpenMS/OpenMS#6690]
I am currently using MetaproSIP to benchmark my 25% 13C labeled E. coli peptide mass spectra data. I used the unlabeled peptide feature XML from an unlabeled search, as the MS2 search engine of OpenMS is unable to function under high 13C abundance levels. However, I encountered a "pattern and collected intensities don't match" error in MetaproSIP. I have included the workflow and error details in the attachment for your reference.
[metaprosip error.txt](https://github.com/OpenMS/OpenMS/files/10703095/metaprosip.error.txt)
[C13test.knwf.zip](https://github.com/OpenMS/OpenMS/files/10703097/C13test.knwf.zip)

**Comment by xyz1396** [comment]
![image](https://user-images.githubusercontent.com/17617241/217986584-b726cabb-585d-4ee6-bd17-9cb3b7c7cd07.png)
it seems the checkpoint for this error.

**Comment by timosachsenberg** [comment]
Thanks! Iwill look into it. The error sounds a bit familiar to me so and it could be related to some modification on a peptide (in that case the number of maximum isotopes for 100% labelling was calculated differently.)
I will look into it.

**Comment by timosachsenberg** [comment]
I was able to successfully run MetaProSIP in the newest OpenMS version and it finished without error.
I still get the warning for some entries regarding the mismatch in patterns and this seems to indeed involve peptides with modifications that influence the number of potentially labelled elements (e.g., Carbamidomthylation H(3) C(2) N O changes the number of carbon.
Looking at the code I think it doesn't have a negative impact as it just collects more intensities than required.
Would it be possible for you to try out MetaProSIP from our OpenMS installer (not integrated into KNIME)? You can get it at  https://abibuilder.cs.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly (just choose one of the recent .exe installer for windows).
```
MetaProSIP -in_mzML X09.mzML -in_fasta EcoliWithCrapNodup.fasta -in_featureXML X01.featureXML -out_csv proteins.csv -out_peptide_centric_csv peptides.csv
```
should produce two output files after about 3h.

**Comment by xyz1396** [comment]
Spectra with / without isotopic peaks 2086/11426
Create CSV report.
Creating peptide centric report: peptides.csv
Writing 1680 peptides to peptide centric csv.
MetaProSIP took 47.25 s (wall), 45.70 s (CPU), 0.56 s (system), 45.14 s (user); Peak Memory Usage: 592 MB.
<Error: size of pattern and collected intensities don't match!: (pattern 232) (intensities 220)> occurred 215 times
<Error: size of pattern and collected intensities don't match!: (pattern 82) (intensities 71)> occurred 66 times

The running time on my computer is much less than 3h. Thanks so much

**Comment by xyz1396** [comment]
The CSV output is sometimes empty randomly even if the input file is the same. It may be the reason why the knime workflow does not work.

**Comment by timosachsenberg** [comment]
Ok that is strange. So this also happens with the nightly installer?

**Comment by xyz1396** [comment]
Yes. I am using the nightly installer.

**Comment by xyz1396** [comment]
I remade the MetaproSIP workflow in TOPASS. MetaproSIP output csv file smoothly in TOPASS. And all nodes can run parallel in TOPASS, which is much faster than KNIME.

**Comment by timosachsenberg** [comment]
Thanks for the feedback!

**Comment by jpfeuffer** [comment]
> I remade the MetaproSIP workflow in TOPASS. MetaproSIP output CSV file smoothly in TOPASS. And all nodes can run raw files parallel in TOPASS, which is much faster than KNIME.

You can use parallel loops in KNIME as well. If you need to scale I would suggest nextflow or KNIME server anyhow. TOPPAS might work for now but is not actively supported anymore.
If I am not mistaken there is someone working with nextflow and MetaproSIP in the nf-core Slack channel.
