### ISSUE TITLE
Doxygen docs badly colored

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#6697]
looking at the current docs, it looks bad:
![image](https://user-images.githubusercontent.com/6008722/218516644-0d4dd28c-2176-43e5-a8ef-0e3007ff1dd7.png)

https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/index.html

needs fixing for release!
@poshul ?

**Comment by jpfeuffer** [comment]
You are on dark mode.
The css for our overview and tool params etc. would need to be adapted for the theme to add a color scheme for dark mode. Maybe we should disable dark mode for release only.

**Comment by jpfeuffer** [comment]
https://github.com/jothepro/doxygen-awesome-css/blob/main/docs/tricks.md

**Comment by timosachsenberg** [comment]
I think this was fixed by Julianus?

**Comment by poshul** [comment]
Yup.

**Comment by jpfeuffer** [comment]
Didn't see it was assigned, I was just very annoyed by it. One can fix the erroneous entries on the Main page instead. I think every tool and algorithm except for TOPPView and SwathWizard should not be there.
