### ISSUE TITLE
create action to update version numbers

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6710]
Double-check Version Number (should have been updated on develop after the last release) in:

CMakeLists.txt of OpenMS (three OPENMS_PACKAGE_VERSION_* variables, and the contrib version check)

   set(OPENMS_PACKAGE_VERSION_MAJOR "2")
   set(OPENMS_PACKAGE_VERSION_MINOR "0")
   set(OPENMS_PACKAGE_VERSION_PATCH "1")

In /src/tests/class_tests/openms/source/VersionInfo_test.cpp the method test:

   START_SECTION((static VersionDetails getVersionStruct()))
In source/src/tests/topp/WRITE_INI_OUT.ini and src/tests/topp/INIUpdater_1_noupdate.toppas

Optionally, in the ini files of the tests in OpenMS/src/tests/topp/ (gets rid of warnings during tests. )

In src/pyOpenMS/doc/Manual.tex (TODO: check if this still exists...)

**Comment by jpfeuffer** [comment]
There might be a duplicate issue somewhere.

**Comment by jpfeuffer** [comment]
Python manual can probably be deleted if it still exists. Everything is in API docs and RTD

**Comment by JeeH-K** [comment]
Double-checking and updating files can be done, but what should we do to commit&push the change? Do I use my github ID and email? https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457

**Comment by timosachsenberg** [comment]
good question... user should work but I think I might need to set up a so called GitHup app  https://github.com/OpenMS/OpenMS/issues/6716
let me check if I can do this quickly...

**Comment by jpfeuffer** [comment]
The generic GitHub token may work. You can try it how you currently do it.
Btw, pull request is better than direct push.
