### ISSUE TITLE
OpenMS Website not reachable

### ISSUE THREAD

**Issue by nilshoffmann** [OpenMS/OpenMS#6730]
Hi there,

the OpenMS website at https://www.openms.de/ seems to be unreachable at the moment. 

Kind regards
Nils

**Comment by timosachsenberg** [comment]
Thanks Nils. Classic admin on vacation situation … we are working on it

**Comment by timosachsenberg** [comment]
at least http://www.openms.org/ works again

**Comment by timosachsenberg** [comment]
should work now...

**Comment by nilshoffmann** [comment]
@timosachsenberg Can confirm. Thanks!
