### ISSUE TITLE
Check PhospoScoring topp tool

### ISSUE THREAD

**Issue by aiche** [OpenMS/OpenMS#674]
Currently PhospoScoring is listed as topp tool but not contained in the ToolHandler and there are no topp tests. Either we 
- remove it
- move it to utils
- add tests

**Comment by timosachsenberg** [comment]
@PetraGutenbrunner I heard that you are working on PhospoScoring so this issue might be of interest.

**Comment by timosachsenberg** [comment]
the issue of precursor charge was fixed by me at some time

**Comment by PetraGutenbrunner** [comment]
Yes, that's interesting for me, thank you! I already made a few changes in the AScore algorithm and also added some tests. The changes are in my branch https://github.com/PetraGutenbrunner/OpenMS/tree/fix-PhosphoScoring

**Comment by timosachsenberg** [comment]
sounds great!

**Comment by timosachsenberg** [comment]
branch has been merged so I close this issue
