### ISSUE TITLE
Move de.openms.knime repository to OpenMS

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6741]
I think they logically belong here. At least the first one, since it depends on the output formats of our tools. And we always version it together with OpenMS.
https://github.com/genericworkflownodes/de.openms.knime
https://github.com/genericworkflownodes/de.openms.knime.dynamicJSViewers

**Comment by timosachsenberg** [comment]
any additional changes needed to moving the repo?
jenkins?

**Comment by jpfeuffer** [comment]
Yes

**Comment by timosachsenberg** [comment]
updated:
[OpenMS](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/)
[openms_general_knime_plugin_stable](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/openms_general_knime_plugin_stable/)

[OpenMS](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/)
[ntly](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/)
[KNIMEPlugin](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/job/KNIMEPlugin/)

[OpenMS](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/)
[usr](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/usr/)
[KNIMEPlugin](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/usr/job/KNIMEPlugin/)

for JSViewer repo I did not have the access right. but I think it could also be kept in genericworkflownodes
