### ISSUE TITLE
Rewrite bioconda recipe with jinja templates to not have conflicts when syncing with upstream

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6742]
If version contains dev, disable linting and download from github.
Else download from archive or github release. Problem: SHA still has to be adapted. Could be done in the release/create PR action.

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#templating-with-jinja

**Comment by timosachsenberg** [comment]
which one? https://github.com/bioconda/bioconda-recipes/blob/master/recipes/openms-meta/meta.yaml ?

**Comment by jpfeuffer** [comment]
all of ours

**Comment by poshul** [comment]
PR merged still needs testing

**Comment by jpfeuffer** [comment]
We need to merge back changes from bioconda

**Comment by axelwalter** [comment]
OpenMS/bioconda has been updated and merge conflicts resolved.
