### ISSUE TITLE
Test new split KNIME plugin

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6743]
https://abibuilder.cs.uni-tuebingen.de/archive/openms/knime-plugin/updateSite/nightly/

**Comment by timosachsenberg** [comment]
any update here? does it work?

**Comment by poshul** [comment]
Nope.

**Comment by jpfeuffer** [comment]
@poshul Still? The day after we talked there should have been some fixes. I'm back on my windows tomorrow.

**Comment by jpfeuffer** [comment]
@enetz Can you retry? 1 and 2 should be fixed. I could never reproduce 3.

**Comment by enetz** [comment]
The issues seem to be fixed now. Used the new split plugin for a while and didn't encounter any issues.
