### ISSUE TITLE
KNIMEUpdateSite_maven failing

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#6746]
We've almost got the whole multibuild action working, the only outstanding bit is [KNIMEUpdateSite_maven](https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/job/KNIMEUpdateSite_maven/).

**Comment by jpfeuffer** [comment]
Hi! I developed the new KNIMEUpdateSite_mvn in parallel for the new plugin structure. It was replaced today in the multijob. I will delete or move the old jobs as soon as it looks stable.
