### ISSUE TITLE
From form: I can't get the software to work or i don't understand the instructions

### ISSUE THREAD

**Issue by rahul799** [OpenMS/OpenMS#6747]
I followed the tutorial to install open ms and to install knime. i am considering using openms for a new project after having used TF software

*This issue was autogenerated by the Google Form for [Features](https://forms.gle/QVcA3NktyGmxm2CZ7)*

Name: Brandon

Email: bcm14@albion.edu

**Comment by timosachsenberg** [comment]
I will answer
