### ISSUE TITLE
IDMapper broken for unmerged TMT

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6755]
https://github.com/bigbio/quantms/pull/262

Probably due to #6580 or related changes
We also need to do another conda release after that manually.

**Comment by timosachsenberg** [comment]
IDMapper will just use the native id I guess which is not unique anymore in merged files.
Can you give me the link to the unmapped  consensusXML and the idXML. I can give it a look...

**Comment by jpfeuffer** [comment]
See the PR comments

**Comment by jpfeuffer** [comment]
Nothing is merged here.

**Comment by timosachsenberg** [comment]
k found the issue... preparing a fix and test files
