### ISSUE TITLE
NASE fails with adducts enabled

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#6757]
Inclusion of properly specified adducts results in the following error:
`Invalid parameter: Charge of 0 is not allowed for an adduct (Na1)`

**Comment by poshul** [comment]
This fails on windows, but not linux with the current develop. @timosachsenberg any idea if a difference parsing strings could make the difference here?

**Comment by timosachsenberg** [comment]
that strange... can you isolate and put this into a class test to reproduce in our CI that it is indeed a platform issue?

**Comment by timosachsenberg** [comment]
if you can point me to the relevant lines in NASE I can give it a quick look.Maybe something jumps to my eyes.

**Comment by jpfeuffer** [comment]
Good catch. You can probably just store the original size before those statements.
I wonder if there is a clang warning for that.
