### ISSUE TITLE
Help MapConversion() pyopenms

### ISSUE THREAD

**Issue by lfnothias** [OpenMS/OpenMS#6770]
Hi, I am trying to generate a MzTab from  a `consensus_map` object with pyopenms 3.0

```
mz_tab = MzTab()
MapConversion().convert(consensus_map, mz_tab)
MzTabFile().store("output.mzTab", mz_tab)

```
And I am getting this exception:
`Exception: can not handle type of (<pyopenms.dataframes.ConsensusMapDF object at 0x7fd6e32270a0>, <pyopenms.pyopenms_3.MzTab object at 0x7fd6de189250>)`

Presumably, I am overlooking something, could someone advise ? Thank you

**Comment by jpfeuffer** [comment]
MapConversion is only for conversion between Map types. FeatureMap and Consensus map (and MSExperiment).
https://pyopenms.readthedocs.io/en/latest/_autosummary/pyopenms.MapConversion.html

Unfortunately the new interfaces for mztab are not yet wrapped in python. None of them.
Neither the functions of the in memory Mztab class, nor of mztabfile.
But wrapping is not hard. Just adding some stubs of the missing functions of the .h files to the corresponding .pxd files.

**Comment by jpfeuffer** [comment]
You will want this:
https://github.com/OpenMS/OpenMS/blob/04dc4d4bb7977533a8b5b2eb4413dee4b4dfac65/src/openms/include/OpenMS/FORMAT/MzTab.h#L603

In MzTab.pxd. If you give it a try, I am sure we can finish it.

**Comment by lfnothias** [comment]
Thanks a lot !
Then it is just easier if I export a dataframe instead MzTab of file. All good. Thanks again.
