### ISSUE TITLE
CDASH certificate error

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6772]
see https://cdash.openms.de/index.php?project=OpenMS

**Comment by poshul** [comment]
There isn't really a neat solution here. FU-Berlin pulled our cert (or more accurately removed cmake.openms.de as an altname on the cert). We can either update all of our references to point directly to cdash.seqan.de, or run our own CDASH server. I've tried a couple of work-arounds via DNS or http forwarding, but these either break CI or result in the certificate errors.

**Comment by timosachsenberg** [comment]
thanks for looking into that. can they quickly readd **cdash**.openms.de as long as they host the cdash server?

**Comment by poshul** [comment]
@cbielow can you check with FU IT? My guess is that the answer is going to be no, since its no longer a domain that they control (that would be my answer if someone asked me to issue a cert for a domain that I didn't control).

**Comment by cbielow** [comment]
resolved successfully
