### ISSUE TITLE
Update Linux build-from-source documentation

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#6789]
I'm following the instructions for building OpenMS from source under Linux (Ubuntu 22.04 on WSL) here:
https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/install_linux.html

I've noticed the following issues:
- List of commands to install required libraries via package manager only goes up to "Ubuntu/Debian (= 19.10)"
- "libboost-[...]1.67-dev" packages are not available on Ubuntu 22.04. Newer versions (1.74) can be installed by removing the version numbers from the package names.
- ~~The instructions say "Note: installing libglpk-dev is optional", but without it the initial CMake build step fails with:~~
```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR
  GLPK_PROPER_VERSION_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindGLPK.cmake:66 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/cmake_findExternalLibs.cmake:84 (find_package)
  CMakeLists.txt:436 (include)
```
- ~~"libwildmagic-dev", "libsqlite3-dev" are required, but not listed in the documentation. Not having them causes the build to fail with CMake errors (like for "libglk-dev").~~
- I get the following warning during the build (I assume the relevant package that should be installed is "qtwebengine5-dev"):
```
CMake Warning at cmake/cmake_findExternalLibs.cmake:208 (message):
  Qt5WebEngineWidgets not found, disabling JS Views in TOPPView!
Call Stack (most recent call first):
  CMakeLists.txt:436 (include)
```
~~(If GLPK is indeed optional, maybe it could be handled in the same way as this.)~~

EDIT: Updated to reflect dependencies that are no longer required in the current development version.

**Comment by hendrikweisser** [comment]
The documentation also mentions using "ccmake" for configuration. This requires another package that isn't listed ("cmake-curses-gui").

**Comment by timosachsenberg** [comment]
Hi Hendrik. Thanks for checking. Can you confirm that the contrib submodule is up to date.
e.g. "libwildmagic-dev", "libsqlite3-dev" is integrated into the OpenMS source tree and should not fail.

**Comment by hendrikweisser** [comment]
I did not use the contrib. I prefer to use system packages when they're available, which should be fine according to the documentation. If the contrib is required for some libraries, that needs to be clarified in the documentation.

**Comment by timosachsenberg** [comment]
Sure that should work. Just to clarify: was this a clean build or could there be some cmake files or caches still around? 

e.g. dependency on sqlite was removed in this PR:

https://github.com/OpenMS/OpenMS/pull/6478/files#diff-d93d6eef7cb6d735ad09c4de827e1cdcedbd9c701da39b72cdd9bb52f6a315d2L129-L131

**Comment by hendrikweisser** [comment]
> Just to clarify: was this a clean build or could there be some cmake files or caches still around?

Hm, good point. It was the first build, but from an old version of "develop" (before I remembered to do a `git pull upstream`).

**Comment by hendrikweisser** [comment]
I've tried it again with the up-to-date "develop" branch, after removing the "libwildmagic-dev", "libsqlite3-dev", and "libglk-dev" packages - and it works without them. I'll update the top post accordingly.

**Comment by jpfeuffer** [comment]
Yes, I vote for version-less Qt package names unless absolutely necessary. Without versions we can probably call the instructions: Ubuntu >= 19.10

We could reduce the QtWebEngine warning to an Info I guess. WebEngine is optional since it is huge.

**Comment by hendrikweisser** [comment]
One more point: We list packages for old Ubuntu versions (16.04, 17.04/18.04) in the current (nightly) documentation. Do we support/test these with the current OpenMS version? If not, I think they should be removed from the documentation. (The installation instructions for older OpenMS versions will remain available.)
