### ISSUE TITLE
SiriusAdapter terminal output (email and password reveal)

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#6790]
Is there a way to suppress printing out all the SiriusAdapter output, especially the email, and password details? 

Both the Sirius executable, SiriusAdapter, and snakemake print the email and password login details, so I am trying to eliminate them one by one 👯

**Comment by oliveralka** [comment]
Seems to be a general sirius issue: https://github.com/boecker-lab/sirius/issues/110
Will probably be changed in the next release. Workarounds seems to be available.

**Comment by eeko-kon** [comment]
Ops yes sorry I forgot to close it - indeed there are workarounds

**Comment by eeko-kon** [comment]
This is not fixed with the env variable - SiriusAdapter or the sirius executable itself prints out the sirius executable command with the email and password shown in the terminal output and the log file. I am investigating which algorithm is responsible but could be both

**Comment by eeko-kon** [comment]
Sorry about that - 

I used ENV variables for the logins but SiriusAdapter log is saving the email and password (even though I only ask that the error output is written to the log file). Even if I omit the log, it is still printing it on the terminal output. 

I will check if with the new sirius release this is omitted but I think that SiriusAdapter should probably be adapted to the new changes?

**Comment by eeko-kon** [comment]
I downloaded the new sirius executable (5.7.0 snapshot) and re-ran the files with SiriusAdapter
I selected the `no progress` flag and no log files and still on my terminal output I get
```
TOPPBase.cpp(1605): Value of string option 'sirius_user_email': **@***.dtu.dk
TOPPBase.cpp(1605): Value of string option 'sirius_user_password': ****
```

`Executing command: resources/sirius/bin/sirius login --email=***@***.dtu.dk --password=****`

For every file

If I use a log file, it is also printed there 3 times per file :')

**Comment by jpfeuffer** [comment]
Hmm did you remove the password from the ini-file or the command line?
Or does it fail then?

**Comment by eeko-kon** [comment]
You are right, they removed the logins from the snapshot completely. It works perfectly! Thank you!

So logins are no longer necessary to run SIRIUS?

**Comment by jpfeuffer** [comment]
Ah ok I have read the linked issue now :D 

I think you need to pass the name of the environment variables to use on the command line or in the ini of the adapter,
e.g.:
`SiriusAdapter -in foo -out bar -sirius:pw MY_SIRIUS_PW_ENV_VAR_ON_PATH -sirius:user MY_SIRIUS_USER_ENV_VAR_ON_PATH`
Mind that you should not put a "dollar sign" otherwise it will get expanded before being passed to the command line.

AFAIK Sirius "caches" the login on the same computer for some time so maybe you are seeing that, too.


In any case, we should not print these variables either in our Adapter :(

**Comment by eeko-kon** [comment]
This is exactly what I did - I am using ENV variables. Perhaps I am not doing it the right way? 
In `python`, I defined new env variables:
```
os.environ["SIRIUS_EMAIL"]=input("Please enter your SIRIUS email: ")
os.environ["SIRIUS_PASSWORD"]= getpass("Please enter your SIRIUS password: ")
```
Then I define them as USER_ENV and PSWD_ENV in snakemake to call them at the command line:
```
USER_ENV=os.environ["SIRIUS_EMAIL"]
PSWD_ENV=os.environ["SIRIUS_PASSWORD"]
```
Then I call those params at the command line:

`SiriusAdapter -sirius_executable {params.exec_path} -sirius_user_email {params.USER_ENV} -sirius_user_password {params.PSWD_ENV} -in {input.var1} -in_featureinfo {input.var2} -out_sirius {output.out1} -out_fingerid {output.out2} -preprocessing:filter_by_num_masstraces 2 -preprocessing:feature_only -sirius:profile {params.instrument} -sirius:db {params.database} -sirius:ions_considered {params.ions} -sirius:elements_enforced CHN[15]OS[4]Cl[2]P[2] -sirius:compound_timeout 100 -debug 3 -threads {params.threads} -no_progress -log {log} 2>> {log}`

Then both my email and password are printed out and saved in the log files

Am I doing smth wrong?

**Comment by eeko-kon** [comment]
Alright, I completely removed all cached files from SIRIUS, and followed your advice and indeed it works :) 
No password or email is being printed out or shown anywhere and SIRIUS is running completely fine :) 

Thank you, Julianus!

**Comment by eeko-kon** [comment]
@jpfeuffer here we go again: somehow SiriusAdapter or Sirius is **not** crashing with a wrong email/password and I suppressed all the outputs so I THOUGHT it ran fine with the new environments but it did not. 

My command:

`SiriusAdapter -sirius_executable resources/sirius.app/Contents/MacOS/sirius -sirius_user_email USER_ENV -sirius_user_password PSWD_ENV -in results/Interim/mzML/Aligned_Regul_Pert_02524_2_c19_B_10d_RB6_01_63424.mzML -in_featureinfo results/Interim/Preprocessed/MFD_Regul_Pert_02524_2_c19_B_10d_RB6_01_63424.featureXML -out_sirius results/Interim/Sirius/formulas_Regul_Pert_02524_2_c19_B_10d_RB6_01_63424.mzTab -preprocessing:filter_by_num_masstraces 2 -preprocessing:feature_only -sirius:profile orbitrap -sirius:db none -sirius:ions_considered [M+H]+,[M-H2O+H]+,[M+Na]+,[M+NH4]+ -sirius:elements_enforced CHN[15]OS[4]Cl[2]P[2] -sirius:compound_timeout 100 `

```
INFO    14:38:09 - Running with following arguments: [login, --email=USER_ENV, --password=PSWD_ENV]
SEVERE  14:38:09 - Unexpected Error!
com.github.scribejava.core.model.OAuth2AccessTokenErrorResponse: {"error":"invalid_grant","error_description":"Wrong email or password."}
```
So SiriusAdapter requires a string - it cannot take a variable as an input. Could that be easily changed? Otherwise, there is no workaround to avoid printing the email and password...

**Comment by jpfeuffer** [comment]
Hmm.. can you try:
`SiriusAdapter -sirius_executable {params.exec_path} -sirius_user_email SIRIUS_EMAIL -sirius_user_password SIRIUS_PASSWORD -in {input.var1} -in_featureinfo {input.var2} -out_sirius {output.out1} -out_fingerid {output.out2} -preprocessing:filter_by_num_masstraces 2 -preprocessing:feature_only -sirius:profile {params.instrument} -sirius:db {params.database} -sirius:ions_considered {params.ions} -sirius:elements_enforced CHN[15]OS[4]Cl[2]P[2] -sirius:compound_timeout 100 -debug 3 -threads {params.threads} -no_progress -log {log} 2>> {log}`

I.e. your environment variables are actually called SIRIUS_EMAIL and SIRIUS_PASSWORD, due to:

```
os.environ["SIRIUS_EMAIL"]=input("Please enter your SIRIUS email: ")
os.environ["SIRIUS_PASSWORD"]= getpass("Please enter your SIRIUS password: ")
```

I hope the environment is passed to the subprocess.

**Comment by jpfeuffer** [comment]
Have you checked https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#environment-variables?
This might be even a bit more secure and scalable than letting users type the password on request.

**Comment by eeko-kon** [comment]
> I hope the environment is passed to the subprocess.

Unfortunately, it is not. It literally passes the string "SIRIUS_EMAIL" and "SIRIUS_PASSWORD" (I tried that before opening the issue, but tried it again now)

**Comment by jpfeuffer** [comment]
Do you/we have a recent enough Sirius version for this?
From my understanding Sirius should expand those variables inside their program if you pass the name. Maybe we should follow up on the Sirius issue then?

Regarding printing to the logs by the openms adapter, this should only happen in debug mode. Is it enough if you deactivate debug by default? Unfortunately we always print the command line deep down in a base class, so there is no way of checking if something is a password without large restructuring or deactivating the whole functionality by default.
Printing parameters could be easily solved by adding a tag "hidden" but that does not matter if the password is printed in the passed command line.

**Comment by eeko-kon** [comment]
Old version was accidentally re-used. 🥇 So sorry!
