### ISSUE TITLE
PSMFeatureExtractor features for Percolator are differing compared to pin file of Comet

### ISSUE THREAD

**Issue by jonasscheid** [OpenMS/OpenMS#6795]
The `extra_features` listed in the idXML output file of PSMFeatureExtractor are these (Search done by Comet's newest version after [this fix](https://github.com/UWPR/Comet/issues/33)):

`<UserParam type="string" name="extra_features" value="isotope_error,COMET:deltCn,COMET:deltLCn,COMET:lnExpect,MS:1002252,MS:1002255,COMET:lnNumSP,COMET:lnRankSP,COMET:IonFrac"/>`

As I found out recently, everything that starts with `MS` comes from the metadata of the `pep.xml` that is parsed into openMS. The rest is derived and/or computed internally in the PSMFeatureExtractor.
In comparison to the pin file that comet gives, these values look quite different.

E.g.
COMET:deltCn -> always 1
COMET:deltLCn -> always 0

Probably because of running comet with `num_hits = 1`.

So the solution would be to parse the pin file https://github.com/OpenMS/OpenMS/issues/6787, or compute them as Jimmy suggested here https://github.com/UWPR/Comet/issues/34? :)

**Comment by jpfeuffer** [comment]
The problem/question is: If there is only one hit in the pepXML, how do we calculate the delta? This is not mentioned in the linked issue.

**Comment by jonasscheid** [comment]
Well, the delta is computed in Comet internally 🤔 would that be sufficient to just parse this value or what is the purpose of computing the delta differently?

**Comment by jpfeuffer** [comment]
Yep. If it is reported in the pepXML now we can parse it.

**Comment by timosachsenberg** [comment]
should be fixed now
