### ISSUE TITLE
Previous docker containers do not exist?

### ISSUE THREAD

**Issue by jcharkow** [OpenMS/OpenMS#6796]
I'm trying to pull the OpenMS docker container for version 2.7 as per the command 

`docker pull ghcr.io/openms/openms-library:2.7.0` in the documentation but it seems that this does not exist. 
Replacing 2.7.0 with 2.9.1 fixes this (latest version at this time). 
Are previous versions suppose to be available? If not maybe the documentation should be updated to reflect this?

**Comment by jpfeuffer** [comment]
Hi! Yes, I think we did not transfer the old containers to ghcr.io. You could try to get them from the old dockerhub (if they have not shut it down yet for free projects) and manually upload them to ghcr.io.

**Comment by jcharkow** [comment]
Maybe this is more of a documentation issue because in the docs https://openms.readthedocs.io/en/latest/installations/installation-on-gnu-linux.html#run-via-a-bio-container It 2.7.0 as the example but that specific command does not work for me. I'm not sure if 2.7.0 is available, if not should probably be updated to 2.9.0?
