### ISSUE TITLE
M2 chip: successfully built pyopenms but failed all tests. Process are killed when importing pyopenms

### ISSUE THREAD

**Issue by YuanyeChi** [OpenMS/OpenMS#6797]
I followed the [this page](https://pyopenms.readthedocs.io/en/latest/build_from_source.html) to build pyopenms from source on Apple M2 chip. It shows build successfully. 
![](https://user-images.githubusercontent.com/37322570/228112942-1003ee0b-1f26-4436-9899-900ff906aea5.png)
However, I failed all the test due to subprocess killed. 
![](https://user-images.githubusercontent.com/37322570/228113094-176b6136-37a9-4080-94e2-3290ca24a50b.png)
Also, python broke down when I tried to import pyopenms.
![](https://user-images.githubusercontent.com/37322570/228113257-05e04971-0dc5-45a1-85e7-7e79c9de7fda.png)

**Comment by YuanyeChi** [comment]
When I switch python from 3.9 to 3.7 and recompile. I failed all the tests and get the following error when importing pyopenms.
![](https://user-images.githubusercontent.com/37322570/228119842-ffd877f4-a61b-4729-a595-c7563e6f93bf.png)

**Comment by jpfeuffer** [comment]
It feels like you have the Intel-only version of Python. Can you try to upgrade your python?

**Comment by YuanyeChi** [comment]
> It feels like you have the Intel-only version of Python. Can you try to upgrade your python?

I think this is beecause I downgrade python from 3.9 to 3.7. When I am using python 3.9, 3.10 and 3.11, no such error happend.

**Comment by jpfeuffer** [comment]
But without messages from the exceptions or a clear reason *why* the processes are killed, I cannot help much since we do not have a Silicon Mac.

**Comment by YuanyeChi** [comment]
Thank you for your advice. Now it directly shows the .whl file is not compatible with this platform. 

```
(pyopenms_venv) ➜  pyOpenMS pip install dist/*.whl
ERROR: pyopenms-3.0.0-cp311-cp311-macosx_13_0_arm64.whl is not a supported wheel on this platform.
```

I suspected it may be because my M2 have rosetta installed, so I come to x86 .whl file, it also failed. 

```
(pyopenms_venv) ➜  pyOpenMS pip install dist/*.whl
ERROR: pyopenms-3.0.0-cp37-cp37m-macosx_13_0_x86_64.whl is not a supported wheel on this platform.
```

> > `pip install .`
> 
> I don't recommend installing pyopenms like that. The setup.py is not designed to be used outside of CMake. You build the wheels with `make pyopenms`, then you install the wheel with `pip install dist/*.whl`.

**Comment by YuanyeChi** [comment]
> Did you make sure to pip install with a python version matching the one from the wheel? E.g. `cp311-...-arm64` needs to be loaded by a python 3.11 executable built for arm/M1. `cp37-...-x86_64` has to be loaded by a python 3.7 for Intel. Use `python -m pip install dist/*.whl` to make sure you are using the correct python.


Ah yes, after I switch to proper python, the result becomes the same as previous one. I will let you know if things has some progress.
```
(pyopenms_venv) ➜  pyOpenMS python3
Python 3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopenms
Determination of memory status is not supported on this
 platform, measuring for memoryleaks will never fail
[1]    73720 killed     python3
```

**Comment by jpfeuffer** [comment]
So, I could reproduce this.
You need to re-sign a bunch of third-party libraries apparently.
I have no idea why.

See 
https://stackoverflow.com/questions/61168329/how-can-i-sign-a-dylib-using-just-a-normal-apple-id-account-no-developer-accou
how to set up a self signed certificate.

Then codesign QtCore, QtNetwork and all the dylibs in your wheel. Then it should work.

We will have to check how to automate that and why that happens.

**Comment by YuanyeChi** [comment]
> So, I could reproduce this. You need to re-sign a bunch of third-party libraries apparently. I have no idea why.
> 
> See https://stackoverflow.com/questions/61168329/how-can-i-sign-a-dylib-using-just-a-normal-apple-id-account-no-developer-accou how to set up a self signed certificate.
> 
> Then codesign QtCore, QtNetwork and all the dylibs in your wheel. Then it should work.
> 
> We will have to check how to automate that and why that happens.

I really appreciate your help on my issue. I will try to do this. It seems not a work can be finished in a short time, but i will let you know once there are some changes happen.

**Comment by pesavent** [comment]
I don't know if this will help others who have had issues when importing pyopenms, but I'll share how I got it to work on my system. After talking with Kyowon about this, he mentioned that I should try both 'pip install pyopenms' which gave this error: 
![Screenshot 2024-06-22 at 3 42 51 PM](https://github.com/OpenMS/OpenMS/assets/77235020/a5fc0dfa-6c65-4a58-b92a-1e782d063b69)

I then tried his second advise which was to install through anaconda3 using 'conda install -c bioconda pyopenms', then  got this error:
![Screenshot 2024-06-22 at 3 40 11 PM](https://github.com/OpenMS/OpenMS/assets/77235020/fb0f629f-2ff6-4d70-8e7a-543972b6d4c2)

I saw a dependency on 'boost', so after running 'pip install boost' i decided to once again do 'pip install pyopenms'... and it worked! I'm also attaching my shell history in case that helps.
[shellhistory.txt](https://github.com/user-attachments/files/15941971/shellhistory.txt)

**Comment by timosachsenberg** [comment]
@jpfeuffer seems as if boost is pinned to 1.78.0
Do you think we can replace boost-cpp with boost-cpp >= 1.78.0
in https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pyopenms/meta.yaml
and
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/openms-meta/meta.yaml

**Comment by jpfeuffer** [comment]
That will always be the case with bioconda. Boost is pinned whenever you build something.
I think the problem here was:
pip was used with a wrong python version in the beginning.
Then conda was used. Conda-forge channel was forgotten.
pip inside conda was used with a supported python version.
Works.

**Comment by timosachsenberg** [comment]
ah ok so it should work out of the box if the conda-forge channel is enabled?

**Comment by jpfeuffer** [comment]
I hope so, yes. It even suggests "perhaps a missing channel".

**Comment by jpfeuffer** [comment]
Please note, bioconda does not build for Apple Silicon. You will need a Rosetta emulated x86_64 version of conda. (but if it finds pyopenms, it means you have one)
