### ISSUE TITLE
CometAdapter pin file label always 1

### ISSUE THREAD

**Issue by jonasscheid** [OpenMS/OpenMS#6819]
The pin file `Label` column describes if the hit is a decoy (-1) or not (1).

Pin files from CometAdapter always have 1 despite Decoy annotation in `Proteins` column. So the pin file cannot be plugged into percolator by default.

This occurs because in the params file `decoy_prefix =--decoysearch-not-used--`. But if I set `decoy_prefix = DECOY_`, then we get the correct label for decoys.

**Comment by timosachsenberg** [comment]
I think the issue is that CometAdapter doesn't know about the decoy prefix (e.g., if REV_ or DECOY_ is used).
I will check if it we can add it.

**Comment by jpfeuffer** [comment]
This is a bit weird since you just removed decoy support from msgfplus.
Not sure if we should support that.
This will create problems with reindexing.

**Comment by timosachsenberg** [comment]
yeah I think so as well. It also adds the prefix internally in comet so maybe we probably would need to change the pin entries manually.

**Comment by timosachsenberg** [comment]
look like we would need to read in the pin file, change the column entries and write it out again. This is currently not implemented.

**Comment by jonasscheid** [comment]
We would not need to give comet support for decoy generation. This is handled by the [decoy_search](https://uwpr.github.io/Comet/parameters/parameters_202301/decoy_search.html) parameter. If you only would parse [decoy_prefix](https://uwpr.github.io/Comet/parameters/parameters_202301/decoy_prefix.html) with `decoy_search = 0` (I guess the latter one is already the implemented), it could also be a solution 🤔

**Comment by jpfeuffer** [comment]
It does not really hurt to add it when using idXML since the mappings will be overwritten but may lead to very slightly different outputs when using pin vs idXML with reindexing.

**Comment by timosachsenberg** [comment]
@jonasscheid can you just remove this line: https://github.com/OpenMS/OpenMS/blob/develop/src/topp/CometAdapter.cpp#L529

default is already DECOY_ so maybe this will already lead to the expected behavior

**Comment by jpfeuffer** [comment]
Can we take the decoy_prefix from the reindexing algorithm parameters?
Or maybe remove that and expose it at the general level? @timosachsenberg does that make sense?
