### ISSUE TITLE
Pyopenms wheels contain so's for multiple python versions

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6826]
Something went wrong when changing the github action to use the version file.
Old "so" files need to be deleted or something.

**Comment by matteopilz** [comment]
Can you provide additional information about "so" files?

**Comment by jpfeuffer** [comment]
They are shared objects (dynamic libraries) and their extension is ".so".
You just need some cleanup that is as least invasive as possible. Maybe just `rm pyopenms/pyopenms*.so`

**Comment by matteopilz** [comment]
Where do they show up and what is the issue when they occur?

**Comment by jpfeuffer** [comment]
When you install and go to your pythonpath/site-packages/pyopenms you will have 8 so's in 3.9, 16 so's in 3.10, 24 so's in 3.11.

I think the problem is only the size but it's a serious, unnecessary, easy-to-avoid size increase.

**Comment by matteopilz** [comment]
Isn't the issue, that all python versions are installed? From what I read, I figure .so files themselves are relatively standard.

**Comment by jpfeuffer** [comment]
Not all versions have all versions.
Every version has all previous versions because they are not deleted.

**Comment by matteopilz** [comment]
So we should only delete the .so files of previous versions?

**Comment by matteopilz** [comment]
Did somebody test this on Mac or Windows? In both, there is a cleanup line at the end of the code:
`
# clean previous pyopenms libs
find . -name "pyopenms*.so" -exec rm -rf {} \;
`

**Comment by jpfeuffer** [comment]
No, tested on binder=linux. You can also just download the wheels from other platforms and unzip.
