### ISSUE TITLE
master thesis to apply some implementations/ideas from sage-ms

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6832]
e.g. PEP with KDE
FDR for match between runs in FFID / MetaboID etc.

**Comment by timosachsenberg** [comment]
@cbielow what is your assessment. I think there are some nice, proven implementations in it (though in rust).
Would probably make sense to translate some to C++ and include in OpenMS.

**Comment by jpfeuffer** [comment]
I agree, I really like the simplicity of the implementations. This will also make it easier for students to re-implement.

**Comment by timosachsenberg** [comment]
Are you looking for an exciting and challenging project for your master thesis? Do you have experience with programming languages such as Rust and C++ and a passion for bioinformatics? If so, we have the perfect opportunity for you!

We are seeking a motivated and talented student to port and implement key ideas and algorithms from the SAGE mass spectrometry open-source peptide search engine, written in Rust, to our open code base in C++. SAGE is a cutting-edge tool for analyzing protein data, and we believe that incorporating its innovative algorithms into our existing codebase will enable us to advance our research and deliver even more accurate results.

As a master's student in this project, you will work closely with our team of experienced researchers and programmers to understand the existing codebase and the key algorithms and ideas from SAGE. You will then be responsible for porting these algorithms to C++, testing and optimizing their performance, and integrating them into our open codebase.

This project will provide you with an excellent opportunity to develop your programming and bioinformatics skills, as well as gain valuable experience working on a real-world research project. You will have access to state-of-the-art equipment and resources, as well as guidance and support from our team of experts.

If you are a self-motivated, independent thinker with strong programming skills and a passion for bioinformatics, we encourage you to apply for this exciting master thesis project. Join us and help us push the boundaries of protein data analysis!

**Comment by cbielow** [comment]
certainly a nice project!
small spoiler: we are currently implementing the fragment+precursor filter as part of the `Optimizing C++` course. So that part will be solved soonish. So far it looks really promising.

**Comment by timosachsenberg** [comment]
any update here?

**Comment by KyowonJeong** [comment]
I am reviewing SAGE now to see what could be done..

**Comment by cbielow** [comment]
Expect a PR for the fragment index in the next week :-)

**Comment by lazear** [comment]
I am also happy to answer any questions or explain something if it's not clear. And hopefully I can learn from any improvements or bugs you guys discover 😁

**Comment by timosachsenberg** [comment]
@lazear thanks! I am curious how much slower a fragment index implementation is if we tie it to our more general/less specialized datastructures. So don't expect too much in terms of performance. ;)
