### ISSUE TITLE
evaluate the panel framework for more advanced web apps

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6834]

**Comment by axelwalter** [comment]
streamlit advantages:
- easy to use and great for quick prototyping
- file upload functionality much better then panel (especially for larger files such as mzML)
- deployment via streamlit cloud - anyone can easily share their pyopenms apps

disadvantage: 
plotting of big data such as MS peak maps
- possible to certain extent with plotly webgl support
- would be great to use datashader -> redraw plot based on zoom level
- figures in streamlit don't report on zoom level/selections/click events by default
- streamlit-bokeh-events component not working right now

working on right now:
- figuring out how to build a custom component

If this issue can be solved, I would suggest streamlit based on the listed advantages.

**Comment by axelwalter** [comment]
Streamlit OpenMS template has been [updated](https://github.com/axelwalter/openms-streamlit-template) with documentation and example workflow.
