### ISSUE TITLE
FR: specify input files via text file for FeatureLinker*, MapAligner* etc

### ISSUE THREAD

**Issue by rickhelmus** [OpenMS/OpenMS#6845]
Hello,

Windows has [an unfortunate limitation for command line execution](https://stackoverflow.com/a/28452546), which at some point becomes problematic when processing many data files with e.g. `FeatureLinkerUnlabeled`, `MapAlignerPoseClustering` etc. To go around this, one option would be to specify the input files via a simple text file, e.g. line separated:

```
file1.mzML
file2.mzML
...
```

This file would serve as an alternative to the `-in` option.

Of course, other workarounds are also of interest (besides switching operating systems... ;-)

Thanks,
Rick

**Comment by timosachsenberg** [comment]
Hi,
You can also specify the input files in the ini file (if that is an option for you).
e.g., write a default ini with FeatureLinkerUnlabeled -write_ini fl.ini
then add the files to the "in" parameter in the ini.

I think you can then just use the ini with FeatureLinkerUnlabeled -ini ff.ini + other options.
Alternatively, you can specify all option in the ini and just use -ini ff.ini without additional command line parameters.

**Comment by cbielow** [comment]
Our GUI tool [IniFileEditor](https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_INIFileEditor.html) may come in handy to fill an INI file generated by, e.g., `FeatureLinkerUnlabeled -write_ini fl.ini` and see how it looks like.

**Comment by rickhelmus** [comment]
Excellent, many thanks guys! I think this should work.

PS: the ini files suspiciously look very much like XML ;-)
