### ISSUE TITLE
AssayGeneratorMetabo .featureXML compound annotations

### ISSUE THREAD

**Issue by karlssoc** [OpenMS/OpenMS#6848]
I have a question regarding the .featureXML that is used as input for AssayGeneratorMetabo (along with the MS-data). 

This library file [https://github.com/OpenMS/OpenMS/blob/develop/src/tests/topp/AssayGeneratorMetabo_ams_sirius_ukn_output.tsv] has compound annotations (headers 'CompoundName' & 'TransitionGroupId').  If I understand correctly these ids are from the .featureXML file [https://github.com/OpenMS/OpenMS/blob/develop/src/tests/topp/AssayGeneratorMetabo_ams_input.featureXML]. 

How do I generate .featureXML with compound annotations? 

What search engine results and which OpenMS tool can be used to create annotated .featureXML? 

Thanks

**Comment by karlssoc** [comment]
I just realised that the OpenMS FeatureFinderMetaboIdent should be used and not FeatureFinderMetabo. Sorry it was right there, but I missed it. I would still appreciate guidelines on how to generate the tsv (Input file: Metabolite identifications (valid formats: 'tsv')) for FeatureFinderMetaboIdent.

**Comment by axelwalter** [comment]
Hi @karlssoc 
You can find more information on FeatureFinderMetaboIdent and the tsv input table [here](https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/UTILS_FeatureFinderMetaboIdent.html) and [here for the pyopenms implementation](https://pyopenms.readthedocs.io/en/latest/user_guide/feature_detection.html#metabolomics-targeted). The latter contains an example tsv table as well. In general you should create the table with retention times from metabolite standards measured on your machine. Also from the standards you should know the most abundant charge states and common adducts. With this information you can either pass in the sum formulas including adducts **or** you can enter the exact neutral mass.
You could also add multiple retention time values separated by comma. This can be useful if you have compounds eluting in a double peak, e.g. sugars in alpha and beta conformation.
Hope that helps, if you have any further questions let me know.
