### ISSUE TITLE
Add macOS ARM CI

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6849]
We had 6-7 people asking for ARM builds now. I think someone should start setting up CI in Jenkins.
At least for pyopenms pip wheels.

- fix codesigning issues #6797 on abibuilder9
- add abibuilder9 to jenkins
- add another config to all matrix builds, to additionally use abibuilder9
- create a new nightly pyopenms wheels job on jenkins, by copying from github actions. Preferably with a Jenkinsfile

**Comment by assafkacen1** [comment]
Make it 8 people, thanks

**Comment by poshul** [comment]
We started work on this, and got abibuilder9 added as a Jenkins node. Homebrew is installed in `/opt/HomeBrew` on the new MacOS version, rather than '/usr/local' unfortunately after extensive testing it appears that the handing for custom OPENMS_BREW_FOLDER is broken in our build scripts. @jpfeuffer can you advise how to set the environmental variable in a way that Jenkins respects?

**Comment by jpfeuffer** [comment]
Did you try to reconnect the node? AFAIR env vars set via the node settings only appear after a reconnect of the worker.

**Comment by jpfeuffer** [comment]
you can also put a
`if VAR not set then brew_exe = brew else brew_exe = VAR/brew`in the build scripts

**Comment by jpfeuffer** [comment]
The problem is even simpler. You did not change the configuration in the first place:
![Screenshot 2023-05-22 at 16 09 55](https://github.com/OpenMS/OpenMS/assets/8102638/11cce8dc-5794-4235-b979-f2ce660a9405)

**Comment by jpfeuffer** [comment]
Where does the broken CMake under /usr/local/bin/cmake come from? This should not be there.

**Comment by jpfeuffer** [comment]
Btw, you need to make sure that the build user is logged in into a window server session at all times, otherwise you will not be able to run/test any GUI apps.

**Comment by jpfeuffer** [comment]
I think I logged in our build user remotely. Might have been enough.
It does not look like GUI tests that are failing.
Latex is failing due to missing pkgs. Either install or finally disable Latex.
TRFP is failing due to missing mono.
Third-party logic is wrong. There is no arm64bit folder.
Rest of the tests are probably std lib differences.

**Comment by poshul** [comment]
There are currently 5 tests failing. 2 of these are because mono wasn't installed. I'm working on the other 3

**Comment by poshul** [comment]
One of the other failing tests was due to floating point issues in IsobaricQuantifier, a fix is proposed https://github.com/OpenMS/OpenMS/pull/6914

**Comment by poshul** [comment]
We've fixed all but two of the tests, and are deferring fixing them.
