### ISSUE TITLE
MapAlignerPoseClustering

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#6860]
Hi,

When I use MapAlignerPoseClustering with many files and I run into an issue, it is usually because one of the files is either empty, corrupted, or has too few features so I assume the algorithm cannot find features for alignment (correct me if I am wrong).

However, I cannot find a way to detect which file is the cause of the error through MapAlignerPoseClustering (from the output, or adding -debug 9). I can only manually work this out, by removing some files, re-running, and eliminating the ones that align until I narrow it down to the one with the issue. Is there another way? 

Could you add a printout so that MapAlignerPoseClustering generates an output of which file it aligns in real-time, so one can easily see from the log files which one to leave out of the analysis? 

Thanks a lot!
Efi

**Comment by axelwalter** [comment]
The issue happened with featureXML files which are empty or have no overlapping features. However, with recent develop an appropriate error message is shown.
