### ISSUE TITLE
jenkins builds broken

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6875]
probably because of changes related to M1 addition

**Comment by jpfeuffer** [comment]
It does not find qt anymore.

`Using as CMAKE_PREFIX_PATH: /usr/local/openms/Homebrew/opt/qt@5/usr/local/openms/Homebrew` is obviously wrong.

Probably related to the unconditional prefixing of OPENMS_BREW_FOLDER.

**Comment by poshul** [comment]
I only see changes to `installBuildTools.sh` any idea why that would have an effect on finding QT.

**Comment by poshul** [comment]
> It does not find qt anymore.
> 
> `Using as CMAKE_PREFIX_PATH: /usr/local/openms/Homebrew/opt/qt@5/usr/local/openms/Homebrew` is obviously wrong.
> 
> Probably related to the unconditional prefixing of OPENMS_BREW_FOLDER.

I can only surmise that it comes from https://github.com/OpenMS/build-scripts/blob/51efa96bd711bb4eaceee6c3962e5001817ef65a/platformScripts/shell/macOS/installQT5.sh#L2 .

**Comment by jpfeuffer** [comment]
that looks correct. I dont know about the setup anymore. Maybe it expects a Qt from the systemwide brew there and therefore you should not have changed the installBuildTools.sh. All changes will be propagated to all following scripts of course.

**Comment by poshul** [comment]
CMake got updated last night on abibuilder1 (independently of any of the changes I made). I wonder if the parsing behavior changed.

**Comment by poshul** [comment]
Should be fixed in https://github.com/OpenMS/build-scripts/commit/21fcbc3246995dc112974db58fa411ace041b80a @timosachsenberg or @jpfeuffer if you can confirm that I didn't break anything else with this, I will close this.

**Comment by poshul** [comment]
yup https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/job/TstPkg/compiler=appleclang-12.0.0,os_label=catalina/

**Comment by timosachsenberg** [comment]
not in cdash
https://cdash.seqan.de/index.php?project=OpenMS&date=2023-05-24
not in buildarchive though

**Comment by jpfeuffer** [comment]
Last commit was 4d ago.
You need to trigger the full multijob to make a deploy.
You also need to trigger with the GitHub branch trigger to pass the correct variables such that Cmake know s in which Dashboard to push. You can find them in Experimental now.

**Comment by jpfeuffer** [comment]
Someone messed up the nightly branch. It is not cleanly mergeable anymore.

**Comment by timosachsenberg** [comment]
ah ok sorry - my bad. I tried to trigger via github by adding a space. btw why does nightly need a merge and is not a hard reset on the develop branch?

**Comment by timosachsenberg** [comment]
I fixed the nightly branch...let's see

**Comment by jpfeuffer** [comment]
It does an ff-only merge so it should be essentially the same thing. You just have to make sure the nightly branch stays clean.

**Comment by jpfeuffer** [comment]
You can do a hard reset but then it will silently delete changes that people accidentally might have made to nightly.
