### ISSUE TITLE
Installation of OpenMS on Mac M1

### ISSUE THREAD

**Issue by CM-07** [OpenMS/OpenMS#6885]
Hello!
How to install OpenMS in macOS Monterey version 12.5.1. I tried different ways but it shows that my device is incompatible.

**Comment by jpfeuffer** [comment]
Hi!

Which ways did you try?
M1/2 or Intel Mac?
Do you have a screenshot/log of the error?

**Comment by azaznaev** [comment]
I also failed in installing pyOpenMS on my MacBook with Apple M1 Pro chip. The following error occurred:

```Error when loading pyOpenMS libraries!
Libraries could not be found / could not be loaded.

Note: when using the Spyder IDE, this error may be triggered when
the 'Automatic' backend is used. Please change this in Tools ->
Preferences -> IPython -> Graphics to 'Inline'.

To debug this error, please run ldd (on linux) or dependency walker (on windows) on 

/Users/andrey/anaconda3/envs/pyopenmsenv/lib/python3.8/site-packages/pyopenms/pyopenms.so

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from pyopenms import *
  File "/Users/andrey/anaconda3/envs/pyopenmsenv/lib/python3.8/site-packages/pyopenms/__init__.py", line 80, in <module>
    raise e
  File "/Users/andrey/anaconda3/envs/pyopenmsenv/lib/python3.8/site-packages/pyopenms/__init__.py", line 43, in <module>
    from .all_modules import *
  File "/Users/andrey/anaconda3/envs/pyopenmsenv/lib/python3.8/site-packages/pyopenms/all_modules.py", line 1, in <module>
    from .pyopenms_1 import *

ImportError: dlopen(/Users/andrey/anaconda3/envs/pyopenmsenv/lib/python3.8/site-packages/pyopenms/pyopenms_1.cpython-38-darwin.so, 0x0002): tried: '/Users/andrey/anaconda3/envs/pyopenmsenv/lib/python3.8/site-packages/pyopenms/pyopenms_1.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

I used a Conda virtual environment with Python 3.8 and installed pyOpenMS with `pip`. This was my script that didn't work:
```python
import sys
sys.path.append("/Users/andrey/anaconda3/envs/pyopenmsenv/lib/python3.8/site-packages")
from pyopenms import *
```

**Comment by jpfeuffer** [comment]
Hi, 

Yes most likely. The amount of work depends a bit on which parts of OpenMS you need though?

C++ library?
Python library (pyopenms)?
Command line tools?
Or user interfaces?

**Comment by Prabina07** [comment]
I am not quite sure. I think I need command line tools. At this stage, I would like to work on converting raw metabolomics data to the usable form in R package (metaboanalyst R) such as preprocessing and normalizing. 

Thank you for your prompt response.

**Comment by jpfeuffer** [comment]
Could you show which errors you are getting? I assume you tried the nightly DMG installer?

If you just want command line tools you could use Mambaforge:
https://github.com/conda-forge/miniforge#mambaforge

Choose the Intel installer and set it up. Then follow the conda/mamba instructions for OpenMS.

**Comment by Prabina07** [comment]
I will try this one. 

Regarding errors that I have received, I did not keep track of what errors in particular I was facing before. But now I am trying to work on MAPNormalizer to normalize my .mzXML raw data. I was able to open MAPNormalizer (I had to change settings on my system preferences for that), but now it does not allow me to open QtNetwork.framework thing. For some reason I am not able to  make changes to system preferences to force open QtNetwork.framework.

Documents/Practice_Met -out 1a.mzXML -method median -target_intensity 1000
dyld[14062]: Library not loaded: '@executable_path/../lib/QtNetwork.framework/Versions/5/QtNetwork'
  Referenced from: '/Applications/OpenMS-2.8.0/bin/MapNormalizer'
  Reason: tried: '/Applications/OpenMS-2.8.0/bin/../lib/QtNetwork.framework/Versions/5/QtNetwork' (code signature in <7C449550-8880-3C41-B131-388DCC0585FA> '/Applications/OpenMS-2.8.0/lib/QtNetwork.framework/Versions/5/QtNetwork' not valid for use in process: library load disallowed by system policy), '/System/Library/Frameworks/QtNetwork.framework/Versions/5/QtNetwork' (no such file)
zsh: abort      ./MapNormalizer -in /Documents/Practice_Met -out 1a.mzXML

I tried to do force open by going directly to the finder and doing right-click thing to open the QtNetwork. I am not sure if it worked and still trying to figure steps needed to move forward. Also to add, I am very new on using openMS or Mac terminal, so I might be doing things completely wrong.

Thank you!

**Comment by Prabina07** [comment]
Hi,
I managed to install nightly version of OpenMS and was able to access TOPPview. However I am not able to apply TOPP tools as the drop-down menu does not show any tools for me to select. 
<img width="745" alt="Screen Shot 2023-06-11 at 4 57 50 PM" src="https://github.com/OpenMS/OpenMS/assets/96707542/252356f3-6579-4598-a8a7-b91c45154e76">

Does it mean that the OpenMS is not properly installed which is why all the tools are not in the my TOPPview system?

Thank you

**Comment by timosachsenberg** [comment]
I don't have a Mac.

**Comment by jpfeuffer** [comment]
It's not really about Mac but also how to troubleshoot this. And there are always the build machines where developers can test issues. Also, feel free to reassign.

**Comment by jpfeuffer** [comment]
I assigned you because you did this tool stuff with the students and I still have the feeling it is not working reliably, especially on macOS.

**Comment by timosachsenberg** [comment]
I think we need to find out if:
- this is an installer issue (e.g., only happens if installed)
- related to some platform (e.g., M1)
- related to the certificates

**Comment by jpfeuffer** [comment]
@Prabina07 In any case, I would suggest running the tools from the command line for now. E.g. with the TOPPshell program in the same folder.
You can still visualize the results in ToppView after the tool completed.

**Comment by timosachsenberg** [comment]
@KyowonJeong or @Ayesha-Feroz does anyone have an M1, bulit OpenMS and can check if you can execute the tools from TOPPView?

**Comment by KyowonJeong** [comment]
Yes. It is built on my M1. And now I tried Toppview and failed. The symptom is strange. It starts, but it freezes for a long... time. And sometimes it opens after, say, 10 min. But in most cases, it fails.

**Comment by jpfeuffer** [comment]
Yep. Known issue
https://github.com/OpenMS/OpenMS/issues/6433

**Comment by timosachsenberg** [comment]
@KyowonJeong can you check https://github.com/OpenMS/OpenMS/issues/6433 and try again?

**Comment by CM-07** [comment]
Well, I get error while using the command line as well.

-MacBook-Air:~ Username$ FileConverter -in input.mzML -out output.mzXML
bash: FileConverter: command not found

It says command not found. Is that related to incomplete installation or sthg like that?  

Thank you!

**Comment by CM-07** [comment]
> @Prabina07 In any case, I would suggest running the tools from the command line for now. E.g. with the TOPPshell program in the same folder.
> You can still visualize the results in ToppView after the tool completed.

Well, I get error while using the command line as well.

-MacBook-Air:~ Username$ FileConverter -in input.mzML -out output.mzXML
bash: FileConverter: command not found

It says command not found. Is that related to incomplete installation or sthg like that?

Thank you!

**Comment by jpfeuffer** [comment]
Which command line? Did you use the TOPPshell to start up your command line?
On a normal Terminal, you need to add the tools to your path or navigate to the OpenMS/bin folder first.

**Comment by eeko-kon** [comment]
Hello :) Just adding up here with a new MacBook with M2 chip: 

Building pyopenms failed (DPYOPENMS=ON produced the error: `Cython import failed for the given Python executable.`) 

But it works with:

`pip install --index-url https://pypi.cs.uni-tuebingen.de/simple/ pyopenms`

Which is now 3.0.0devel version

**Comment by jpfeuffer** [comment]
Hi @eeko-kon 
did you make sure that you are in the correct environment for building pyopenms?
Also, to make sure that the correct python executable (with its associated pip packages) is used, please additionally use `-DPython_EXECUTABLE=/path/to/the/python/you/want/to/use`
