### ISSUE TITLE
MSstatsconverter removes peptides found in less than 3 runs from MSstats input

### ISSUE THREAD

**Issue by Roman-Si** [OpenMS/OpenMS#6887]
Hi is the removal of features/peptides that are present in less than 3 runs the expected behavior for MSstatsconverter? I noticed recently that the file that quantms outputs to be used with MSstats did not contain peptides present in 1 or 2 runs https://github.com/nf-core/quantms/issues/102 . 
I installed openMS v2.9.1 via conda and run MSstatsconverter using the consensusXML and the openMS_design.tsv and noticed that it removes these peptides by default. I can not find any relevant option to disable this behavior.

**Comment by jpfeuffer** [comment]
Hi! Hmm, do you think you can upload a potentially "anonymized" example?
MSStatsConverter itself should not remove anything. The only filtering it does is picking the best feature per charge state and run and to make sure that only group-unique peptides are exported.
The removal of feature from 1 or 2 runs should only happen in the preprocessing of MSstats itself. There we should have a parameter to deactivate that.

**Comment by Roman-Si** [comment]
In the link I attached the consensusXML, the experimental design and the proteomicsLFQ
https://drive.google.com/file/d/1AjT20h8s7NlJedBPSygZ1XX-0sv-FPLT/view?usp=sharing

**Comment by jpfeuffer** [comment]
Thanks a lot. I can indeed see features that are present in less than 3 maps/runs in the consensusXML. I have to investigate why they are not exported.

Were you able to check the contents of the csv before it goes into the `OpenMStoMSstatsFormat` function in the R step/script?
I wonder if there those feature are still present.

**Comment by Roman-Si** [comment]
Yes, you are right, these features are still present there so the MSstats functions are responsible for their removal. I reported this in the MSstats Google group. 
Thank you very much, I'll close the issue now.

**Comment by jpfeuffer** [comment]
That is very good to know, also for our own analyses. Thanks for reporting back. Keep us updated about MSstats, if possible.

**Comment by jpfeuffer** [comment]
As a quick follow-up: If I saw it correctly, it might be that MSstats in version 4.x does the filtering in the dataPreprocess function instead of the OpenMStoMSstats function.
We might need to adapt that in the code.
Could you quickly try moving the `removeFewMeasurements` argument to the preprocess function instead?

**Comment by jpfeuffer** [comment]
On the other hand it also looks a bit hardcoded here:
https://github.com/Vitek-Lab/MSstatsConvert/blob/7be7bce82d7cd31880f10502e52a67b121454645/R/MSstatsConvert_core_functions.R#L351

Maybe we wait for input from the MSstats devs

**Comment by Roman-Si** [comment]
Yes, the dataPreprocess function outputs "Features with one or two measurements across runs are removed." so it filters as well. Adding this option in the dataProcess function throws an error for unused argument.

This is the link to the google group discussion, I will post here any further updates
https://groups.google.com/g/msstats/c/p018V5WZGLk/m/MlQrRcrEAQAJ

**Comment by jpfeuffer** [comment]
Perfect, I have a good feeling that this can be solved quickly.
