### ISSUE TITLE
Seqan use in the new version

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#6901]
Greetings,

seqan has been in the past a bit of a pain with respect to packaging OpenMS. I have configured the software and got no mention of seqan not being available on my build system. Instead, a number of other tools are searched for and reported like this:
-- Searching for third party tools...
--   - MaRaCluster not found
--   - Comet not found
--   - OMSSA not found
--   + X! Tandem binary found at tandem -> Enabling corresponding tests.
--   + X! Tandem version: 2017.2.1.4.
--   - Myrimatch not found
--   - MS-GF+ not found
--   - MSFragger not found
--   - Percolator not found
--   - Fido not found
--   - FidoChooseParameters not found
--   - Sirius not found
--   - Novor not found
--   - Crux not found
--   - SpectraST not found
--   - ThermoRawFileParser not found
--   - LuciPHOr2 not found

What is the status of seqan use in OpenMS at the moment ?
Sincerely,
Filippo

**Comment by jpfeuffer** [comment]
Hey! Good news, we removed our dependency on SeqAn, as well as WildMagic.
Those "tools" are tools for which we provide adapter to call them and to postprocess their output. If they are missing they won't be tested, that's all (and I think it is totally fine for a distro package).

**Comment by lopippo** [comment]
Great, 

I see that WM is still checked:
-- Found WM5: /usr/include/libwildmagic  

?

**Comment by jpfeuffer** [comment]
Ah! maybe it was not yet done for the release you are building?

**Comment by lopippo** [comment]
Seems indeed, because I removed it from my system and the check now fails.

**Comment by lopippo** [comment]
I think the test is there, but I cannot grep for wm5 in the source tree.

**Comment by lopippo** [comment]
If you could check that and fix the test, then I'd be grateful. I think we should try to fix all the issues I am reporting and then I'll make the Debian package without hassle :-)

**Comment by jpfeuffer** [comment]
Ah I meant the dependency to WM5 probably was only removed on the develop branch. So you probably still need it.
But SeqAn should have been gone for a while now.

**Comment by lopippo** [comment]
No, it is still used !

**Comment by cbielow** [comment]
closing since the SeqAn confusion was resolved :)
Please reopen if required
