### ISSUE TITLE
Building pyopenms 3.0.0.dev wheel for M1 Pro

### ISSUE THREAD

**Issue by lfnothias** [OpenMS/OpenMS#6903]
Hi OpenMS team, can you advise on the method/status of building this whl ?

**Comment by jpfeuffer** [comment]
Hey! It should be as easy as configuring  CMake with all the pyopenms related configuration options (mainly -DPYOPENMS=ON) and doing `make pyopenms`.
Like here: https://pyopenms.readthedocs.io/en/latest/community/build_from_source.html

You might get some issues when running it, when loading the dependency libraries that we copy into the wheel.
In that case you unfortunately need to re-sign some of them with a self-signed certificate. See my comment here
https://github.com/OpenMS/OpenMS/issues/6797#issuecomment-1490942847

We are still investigating this. We might need to include the frameworks as a whole and not extract single dylibs. Or we resign during packaging. We have a Silicon build machine now.

**Comment by jpfeuffer** [comment]
You also could avoid copying dependencies by adding -DNO_DEPENDENCIES but then it won't be portable.

Or you build with "no dependencies" and fix up the wheel yourself with something like delicate: https://pypi.org/project/delocate/
which we are considering to use as well.

**Comment by lfnothias** [comment]
Thanks a lot for the help @jpfeuffer. I have tried for few hours, but I am getting issues over issues and don't see the end (I am a noob in building code - so it could be doable) ... I will just do my dev on a linux system 'til there is a easier solution. Thanks again.

**Comment by jpfeuffer** [comment]
My signing suggestion worked pretty straightforwardly. You can confirm by checking the tiny changes in the linked PR if you want.

**Comment by jpfeuffer** [comment]
Wheels are available on our private pypi.
https://pypi.cs.uni-tuebingen.de

**Comment by elfxxx** [comment]
I have tried and it works perfectly for arm with python 3.9 ! Thanks a lot

**Comment by lfnothias** [comment]
This works perfectly for the whl for arm64 and python 3.9. Thanks a lot !
