### ISSUE TITLE
Floating point issues on apple silicon

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#6918]
Testing has identified that there is enough difference between floating point on x86 and apple ARM to cause some of our tests to fail. Several tools check if the intensity of peaks is exactly 0.0 rather than checking that it is less than some very small value. We've added fixes to the specific tools (https://github.com/OpenMS/OpenMS/pull/6916 https://github.com/OpenMS/OpenMS/pull/6914). Where we use an arbitrary value to count as "basically zero" for existing instrument precision. This is somewhat of a piece-meal approach, and @cbielow has identified that we should standardize this.

**Comment by cbielow** [comment]
> enough difference between floating point on x86 and apple ARM 

This seems a bit too speculative. Both implement IEE754 without the x87 part (80bit internal precision). The different results could very well be due to something else.

I'd love to help, but would need access to a Apple Silicon...

**Comment by poshul** [comment]
@cbielow okay, let me see what I can do about getting you access to ours.

**Comment by cbielow** [comment]
solved here: https://github.com/OpenMS/OpenMS/pull/6960/files
(TL;DR: fused-multiply-add operations performed by AppleClang by default on M1/M2 hardware change the numeric results. We need to force Clang to avoid FMA and everything is fine, i.e. comparable to other platforms).
