### ISSUE TITLE
Error: could not open sqlite db

### ISSUE THREAD

**Issue by Tlicknack** [OpenMS/OpenMS#6923]
Hello. I'm trying to convert a spectral library (tsv from Fragpipe) to pqp format using the following command:

C:\Program Files\OpenMS-2.8.0\bin>TargetedFileConverter.exe -in C:\library.tsv -in_type tsv -out C:\Users\Admin -out_type pqp

But I'm getting the following error: 

Progress of 'conversion to internal data representation':
-- done [took 0.11 s (CPU), 0.17 s (Wall)] --
Error: Unexpected internal error (an sql operation failed ('Could not open sqlite db 'C:\Users\Admin' in mode 2'))

I'm guessing this is a general Windows issue, but I'm hoping to get some help resolving it here. 

Thank you!

**Comment by jpfeuffer** [comment]
Hi! I think the pqp is stored as a single file. Have you tried giving a filename as out instead of a folder name?
E.g. C:\Users\Admin\outout.pqp

**Comment by Tlicknack** [comment]
Yep, it works--easy fix! I tried the command a few different ways in different folders and forgot that the -out had to be a file on this one^. Thanks!

**Comment by jpfeuffer** [comment]
Great. No problem!
