### ISSUE TITLE
Cmake 3.24 not available on Ubuntu LTS

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#6931]
https://github.com/OpenMS/OpenMS/commit/7289c783a34ce646a003796a1a1893a2755b1465 bumps `cmake_minimum_required` to 3.24 which is ahead of the system installed version on Ubuntu LTS release. Do we need features that are not available in 3.22?

**Comment by cbielow** [comment]
yes, its required unfortunately:
https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_TARGETS_GLOBAL.html#variable:CMAKE_FIND_PACKAGE_TARGETS_GLOBAL
(otherwise we cannot build a package on conda_forge).

we could move that code up to the main CMakeLists.txt tough. That would allow to omit the `global` keyword.
@jpfeuffer ?

**Comment by timosachsenberg** [comment]
Getting the newest cmake is easy as it can just be downloaded. No package or installation required.
We do this in our CI.

**Comment by timosachsenberg** [comment]
or via package manager: https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line

**Comment by cbielow** [comment]
the question is, if we want to make every user go through this or move 10 lines of code (plus making the build system a tiny bit more messy)

**Comment by jpfeuffer** [comment]
The thing is that then third-party libraries would be distributed across Cmake in two places at least.

**Comment by timosachsenberg** [comment]
I think cmake is one of the things developers got used to "live at head".

**Comment by jpfeuffer** [comment]
I agree, thats why VS and CLion, etc. all come with the newest CMake packaged.
If you want, you can move the add_subdirectory for thirdparty way up in the parent CMakeLists and just use include instead of add_subdirectory.

**Comment by poshul** [comment]
Okay. You're right it isn't to hard to update, and if we do get something out of the newer version thats fine.
