### ISSUE TITLE
Start converting some jobs to jenkinsfiles

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6968]
Having our build jobs in text form on GitHub would make a lot of processes more maintainable (and reusable)

@jpfeuffer already started to convert one pyOpenMS job to a jenkinsfile: https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/Jenkinsfile

As a first step and learning experience, it would make sense to convert this jenkins job to a jenkins file:
https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/job/FullMultijob/

And see if we can switch to it for our nightly builds.

Some things to consider:
- don't check in a jenkinsfile with a security token or password hard-coded (see https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/Jenkinsfile#L103 on how to use credentials). Possible credentials can be found in the global jenkins settings.

**Comment by timosachsenberg** [comment]
@jpfeuffer and me can try to answer questions

**Comment by jpfeuffer** [comment]
Closed because of the decision to try GitHub Actions first.
