### ISSUE TITLE
Link to toppas tutorial not working

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6986]
https://openms.de/develop_doxygen/html/TOPP_TOPPAS.html

**Comment by jpfeuffer** [comment]
Please check all the links on this page!
Several are wrong or not existing

**Comment by cbielow** [comment]
```
Page not found
Unfortunately we couldn't find the content you were looking for. 
```
when I click on https://openms.readthedocs.io/en/latest/docs/tutorials/TOPPAS/TOPPAS-tutorial.html

So where is this resolved?

**Comment by matteopilz** [comment]
This should have been resolved in https://github.com/OpenMS/OpenMS/pull/7018
I removed the line, because we don't have a TOPPAS tutorial in our readthedocs (anymore).
Either I missed something, or abibuilder is showing an outdated version.
