### ISSUE TITLE
Nightly conda failing or version wrong

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6989]
All I know is that the badge still shows 3.0.0dev
Should be 3.1.0dev

**Comment by timosachsenberg** [comment]
```
Rebasing (1/9)
Auto-merging recipes/openms-meta/meta.yaml
CONFLICT (content): Merge conflict in recipes/openms-meta/meta.yaml
Auto-merging recipes/pyopenms/meta.yaml
CONFLICT (content): Merge conflict in recipes/pyopenms/meta.yaml
error: could not apply 8dc74c0019... check if dev in version
...
...
...
    raise value.with_traceback(tb)
  File "<unknown>", line 26, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'else'. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'.
```

**Comment by timosachsenberg** [comment]
seems the versions strings are also wrong 

need to update these?
https://github.com/OpenMS/bioconda-recipes/blob/nightly/recipes/pyopenms/meta.yaml
https://github.com/OpenMS/bioconda-recipes/blob/nightly/recipes/openms-meta/meta.yaml

but not those right?
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pyopenms/meta.yaml
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/openms-meta/meta.yaml

**Comment by jpfeuffer** [comment]
I usually first sync master with upstream via GitHub website.
Then force update nightly to the same as master.
Then apply changes to intialize new dev cycle.

**Comment by timosachsenberg** [comment]
https://anaconda.org/search?q=OpenMS still shows 3.0.0dev
because we get the jinja2 error
```
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'else'. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'.
```
I reset nightly and will try again... maybe there were some rebase issues.

**Comment by timosachsenberg** [comment]
fixed 
![image](https://github.com/OpenMS/OpenMS/assets/5803621/f128d948-d491-4ae6-9fb2-c66f44bdb84d)
