### ISSUE TITLE
Fatal Error When Packaging with Pyinstaller

### ISSUE THREAD

**Issue by lingjunli-research** [OpenMS/OpenMS#7006]
Hello,

I wrote a program that uses OpenMS (v 3.6.2) to calculate a hyperscore as one component. When using the program from the command line (Anaconda), it works perfectly. I am nearing publication, so I have attempted to package my program using Pyinstaller (v5.1), and encounter a fatal error. I am running on Windows 10. A minimal reproducible script:

```
from urllib.request import urlretrieve

from pyopenms import *
gh = "https://raw.githubusercontent.com/OpenMS/OpenMS/develop"
urlretrieve (gh +"/src/tests/topp/SimpleSearchEngine_1.mzML", "searchfile.mzML")
urlretrieve (gh +"/src/tests/topp/SimpleSearchEngine_1.fasta", "search.fasta")
protein_ids = []
peptide_ids = []
SimpleSearchEngineAlgorithm().search("searchfile.mzML", "search.fasta", protein_ids, peptide_ids)

tsg = TheoreticalSpectrumGenerator()
thspec = MSSpectrum()
p = Param()
p.setValue("add_metainfo", "true")
tsg.setParameters(p)
peptide = AASequence.fromString("RPGADSDIGGFGGLFDLAQAGFR")
tsg.getSpectrum(thspec, peptide, 1, 1)

for ion, peak in zip(thspec.getStringDataArrays()[0], thspec):
    print(ion, peak.getMZ())

e = MSExperiment()
MzMLFile().load("searchfile.mzML", e)
print ("Spectrum native id", e[2].getNativeID() )
mz,i = e[2].get_peaks()
peaks = [(mz,i) for mz,i in zip(mz,i) if i > 1500 and mz > 300]
for peak in peaks:
  print (peak[0], "mz", peak[1], "int")
```

Running this script alone works fine. But after running through pyinstaller using:
this error message is tossed: 

```
OpenMS FATAL ERROR!
  Cannot find shared data! OpenMS cannot function without it!
  The environment variable 'OPENMS_DATA_PATH' currently points to 'C:\Users\user\Documents\DBpep_v2\python_scripts\gui_min_ex\dist\example\pyopenms\share/OpenMS', which is incorrect!
  To resolve this, set the environment variable 'OPENMS_DATA_PATH' to the OpenMS share directory (e.g., 'c:\Program Files\OpenMS\share\OpenMS').
Exiting now.
```

Here is the run log from the pyinstaller packaging:
[pyinstaller_log.txt](https://github.com/OpenMS/OpenMS/files/12324245/pyinstaller_log.txt)

Any help or guidance with this issue would be greatly appreciated

**Comment by jpfeuffer** [comment]
Hi! It could be that the `share` folder is missing or the OPENMS_DATA_FOLDER environment variable is set to a wrong location.

Usually the __init__.py tries to infer the location for this share folder and sets the environment variable for the process.
But this is only tested for pypi wheels and conda packages. You might need to adapt this for pyinstaller.

**Comment by timosachsenberg** [comment]
@Arslan-Siraj did you already manage to package the share folder? I recall that you did some experiments for the web apps.

**Comment by Arslan-Siraj** [comment]
Here, it is https://github.com/OpenMS/streamlit-template/pull/10

**Comment by timosachsenberg** [comment]
Can you point to how to include the share folder? @lingjunli-research seems to deploy a pure pyopenms package not a web app so there is probably a lot that is not needed.

**Comment by Arslan-Siraj** [comment]
I just did on my local window machine (working fine) via venv:

1.create an environment
  python -m venv <myenv>
  .\myenv\Scripts\Activate.bat 
  pip install pyinstall pyopenms

2.create hook
   \hooks\hook_.py 
   from PyInstaller.utils.hooks import copy_metadata
   datas = []
   datas += copy_metadata('pyopenms') 

3. pyinstaller --onefile --additional-hooks-dir ./hooks test.py --clean
4. add datas in .spec
    datas=[
        ("new_env/Lib/site-packages/pyopenms", "./pyopenms/"),
    ],
5. pyinstaller test.spec --clean  
--> test.exe created with pyopenms features

**Comment by Arslan-Siraj** [comment]
*pip install pyinstaller pyopenms

**Comment by timosachsenberg** [comment]
ah nice. As I don't know much about pyinstaller inner workings... does this package the share folder as well? e.g., through this copy_metadata call?

**Comment by Arslan-Siraj** [comment]
yes, I test above provided  script. not getting error of share folder (working fine)

**Comment by timosachsenberg** [comment]
can you look into the installer file? is the share in there? just asking because if you have the OPENMS_DATA_PATH set somewhere else on your system it might pick than one

**Comment by Arslan-Siraj** [comment]
yes you right, before was fetching from there .
     - so if not share folder there then error, was not included in executable
     
Now, I just remove the OPENMS path from system path
  fetching from share via pyinstaller (copy_metadata worked):
  for example: 
  ('pyopenms\\share\\OpenMS\\CHEMISTRY\\MetaboliteIsoModelNoised5.svm',
     'D:\\test_streamlit_exe\\pyopenm_fix\\my_env\\Lib\\site-packages\\pyopenms\\share\\OpenMS\\CHEMISTRY\\MetaboliteIsoModelNoised5.svm',
     'DATA'),
   - so share folder included in executable (not need to provide separately)

**Comment by lingjunli-research** [comment]
Thank you so much for all of your help, the advice from @Arslan-Siraj worked perfectly.
