### ISSUE TITLE
IDFilter: KeepBestPerPeptide available via pyopenms but not as CLI flag in IDFilter

### ISSUE THREAD

**Issue by jonasscheid** [OpenMS/OpenMS#7020]
Hi!

I want to filter an idXML such that only the best peptide is kept, meaning duplicates are filtered out.

In Pyopenms there is this handy function [keepBestPerPeptide](https://pyopenms.readthedocs.io/en/latest/apidocs/_autosummary/pyopenms/pyopenms.IDFilter.html#pyopenms.IDFilter.keepBestPerPeptide), e.g.:

>filter = IDFilter()
>filter.keepBestPerPeptide(peptide_ids, ignore_mods=False, ignore_charges=True, nr_best_spectrum=1)

Maybe I am missing something but I cannot find this functionality in the [IDFilter](https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_IDFilter.html)

**Comment by timosachsenberg** [comment]
I can take a quick look how much work that would be...

**Comment by timosachsenberg** [comment]
seems easy... I can provide a quick PR

**Comment by jonasscheid** [comment]
🚀 I'll try it out today
