### ISSUE TITLE
nightly OpenMS documentation seems to have issues (not updated?)

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7026]
https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/index.html

doesn't look up to date

**Comment by jpfeuffer** [comment]
What is not up-to-date? Did you refresh browser cache?

**Comment by jpfeuffer** [comment]
Nightlies are failing for a long time, so it might well be the case.
Last deploy was 3 months ago.

**Comment by jpfeuffer** [comment]
See #6970

**Comment by jpfeuffer** [comment]
Alternatives:
- Do silicon in a different job
- Add exceptions for silicon everywhere

Also windows seems to fail from time to time. Probably because the FU machines are too full/slow?

**Comment by poshul** [comment]
This is working now (when the build archive is up)
