### ISSUE TITLE
Building packages with the new Matrix based Github actions CI doesn't work.

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#7028]
It fails in different ways across the different OS/Compiler combos:
On Ubuntu 22.04 G++ It marks the Build step as failed (despite reporting 0 errors):
```
 Build project
   Each symbol represents 1024 bytes of output.
   '!' represents an error and '*' a warning.
    ......................................*...........  Size: 49K
    ....*.............**..............*...............  Size: 99K
    .*****.*****.....................**.... Size of output: 139K
Error(s) when building project
   0 Compiler errors
   27 Compiler warnings
Submit files
   SubmitURL: https://cdash.openms.de/submit.php?project=OpenMS
   Uploaded: /home/runner/work/OpenMS/OpenMS/OpenMS/bld/Testing/20230821-1323/Build.xml
   Submission successful
Please check the build results at: https://cdash.openms.de/index.php?project=OpenMS&begin=2023-01-01&end=2030-01-01&filtercount=1&field1=buildname&compare1=63&value1=develop-Linux-g++-class-topp-47
Error: Process completed with exit code 255.
```
Reading the CDASH tea leaves I see:
```
FAILED: doc/CMakeFiles/doc_param_internal /.../OpenMS/bld/doc/CMakeFiles/doc_param_internal 
```
But that looks like it was caught by the output of another warning https://cdash.openms.de/build/145263

On Windows and Mac:
It gets through the builds (much much slower than without the package type set) but reports that there are no tests to run:

@jpfeuffer any suggestions on where to go next?

**Comment by jpfeuffer** [comment]
Linux: Problem is the difference in handling Qt5 leading to a messed up CMAKE_PREFIX_PATH for setting up the environment to TOPPDocumenter when Qt5_DIR is not set
macOS: I cannot see large differences in build time
win: Differences in build time comes from the fact that ccache cache could not be restored. Did not check why.

"No tests found" was fixed by me. Setting PACKAGE_TYPE automatically disables tests. Debatable if that is a good idea but I avoided it by re-configuring CMake in the package step instead.

**Comment by jpfeuffer** [comment]
Mostly fixed. Please check again

**Comment by jpfeuffer** [comment]
Remaining:
macOS: https://github.com/actions/runner-images/issues/7522

**Comment by poshul** [comment]
looks like MUI isn't installed on the windows runner. " !include: could not find: "MUIEx.nsh"
"
hdiutil is too dumb to take the debug argument before the verb.

**Comment by jpfeuffer** [comment]
1. Tried to replicate from our build machine. But it's down.
2. Nothing we can do. We won't be able to debug then. We should switch to pkg. GitHub people are also not very useful.

**Comment by poshul** [comment]
How do we install NSIS on the GHA runner anyhow? I don't see it anywhere in the yml.

**Comment by jpfeuffer** [comment]
It's preinstalled: https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

**Comment by jpfeuffer** [comment]
Only the github actions dmg problems left. But if the current run with the kills does not succeed, I do not have any hope for a stable dmg creation process on github.

**Comment by jpfeuffer** [comment]
Ok did not work, so dmg is not an option anymore.

**Comment by poshul** [comment]
Okay. Thanks for fighting with it. I'm still going back and forth with IT about a long term solution for uploading through our firewall.

**Comment by jpfeuffer** [comment]
@poshul We get many errors with:
```
[172/177] Running utility command for create_ctds
RT window size calculated as 240 seconds.
Average mass of t6A differs substantially from its formula mass.
Average mass of m7GpppN differs substantially from its formula mass.
Average mass of m2,7GpppN differs substantially from its formula mass.
Average mass of m2,2,7GpppN differs substantially from its formula mass.
Average mass of mpppN differs substantially from its formula mass.
Average mass of pppN differs substantially from its formula mass.
Average mass of GpppN differs substantially from its formula mass.
Average mass of CoApN differs substantially from its formula mass.
Average mass of acCoApN differs substantially from its formula mass.
Average mass of malonyl-CoApN differs substantially from its formula mass.
Average mass of succinyl-CoApN differs substantially from its formula mass.
Average mass of ppN differs substantially from its formula mass.
Average mass of NADpN differs substantially from its formula mass.
Average mass of pG(pN) differs substantially from its formula mass.
Average mass of m3C differs substantially from its formula mass.
Average mass of cmnm5se2U differs substantially from its formula mass.
Average mass of mnm5se2U differs substantially from its formula mass.
Average mass of se2U differs substantially from its formula mass.
```

When running (probably?) NASE with create_ctd. Can you fix that?

**Comment by poshul** [comment]
> 

Okay, just fixed it.

**Comment by jpfeuffer** [comment]
Ok. Is ignoring the warning enough? Why does it even warn, if it is not an issue?

**Comment by poshul** [comment]
I included it as a warning earlier from when the ribonucleotide database we imported from had masses for all of the mods. They ceased doing that, so there are a bunch of mods that only have a formula and no mass. This should have been changed to a debug message at that time, since it can be useful if something suddenly changes.

**Comment by jpfeuffer** [comment]
Last thing missing are the upload steps. Did you come to an agreement?

After that, everything should be carefully tested and the jenkins jobs deactivated. Otherwise they will probably overwrite each other.

**Comment by poshul** [comment]
> Last thing missing are the upload steps. Did you come to an agreement?

Still working on that. The issue right now is that in order to connect through the ssh gateway with a key the user's home directory needs to be mounted, which doesn't happen until the user logs in (by necessity using a password). IBMI IT is currently negotiating opening a port in the firewall to connect directly to our upload server, but that's taking a while. In the meantime, I'm just setting up a cronjob on one of the abibuilders to keep the user's home directory mounted on the ssh machine. I'll keep you updated on a less brittle solution.

**Comment by poshul** [comment]
This should be sorted out now. If it works on the nightlies tonight I'll go ahead and deactivate the Jenkins jobs tomorrow and close this.

**Comment by poshul** [comment]
@jpfeuffer looks like steps.extract_branch.outputs.RUN_NAME is blank during the deploy steps. How do I make sure it persists from the earlier steps?

**Comment by jpfeuffer** [comment]
You cannot preserve them over "jobs" how they are called. You can make an output from the previous job or replicate the logic.
I thought I did that (at least for KNIME). I did it as an environment variable though

**Comment by poshul** [comment]
Hmm, can you double check the KNIME upload? It does get uploaded to the correct directory (I will sort that out for the installer as well), but the permissions are such that the webserver can't access it.

**Comment by jpfeuffer** [comment]
I am not sure if this has to do with the workflow. I would be surprised if the permissions that I see on the archive are the ones that we have in the workflow (we could double-check in the next run with an "ls -la"). This is probably due to how rsync is set up on the machine, or some UMASKs on the mounted archive. I would need to dig here as well.

**Comment by jpfeuffer** [comment]
You can try rsyncing by hand and see which permissions folders receive after uploading.

**Comment by poshul** [comment]
Okay, it keeps the permissions from the source of the files. I've just added some `chmod` to the yml to correct it before sending.

**Comment by poshul** [comment]
This part of the GHA porting at least is finished.
