### ISSUE TITLE
abibuilder8 not working for a long long time

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7029]
doesn't even show up as a possible site in Cdash anymore

**Comment by jpfeuffer** [comment]
I would strongly suggest status checks either by ibmi users or the IT. The repeated failures are IMO very annoying.

**Comment by poshul** [comment]
I've sent IT a message about this. There is a reason I'm keen to move to github's infrastructure.

**Comment by poshul** [comment]
Abibuilder8 is back, on jenkins at least. What do I need to do to make sure it's added to CDash?

**Comment by jpfeuffer** [comment]
It comes automatically if it is chosen for a build again.

**Comment by poshul** [comment]
It's back
