### ISSUE TITLE
SIMD nightly build errors on macOS ARM

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7048]
https://cdash.openms.de/viewBuildError.php?buildid=147699

**Comment by cbielow** [comment]
can we get an ARM64 CI, so this cannot happen anymore?

**Comment by jpfeuffer** [comment]
Not if moving to GHA-only since they don't have ARM runners yet. But it can be done in Jenkins, yes.

**Comment by jpfeuffer** [comment]
You could cross-compile on macOS Intel runners but probably not run the tests.

**Comment by jpfeuffer** [comment]
Should be on jenkins now.
