### ISSUE TITLE
GHA and Jenkins overwriting each other

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7054]
I thought the upload paths were set to something different until we double-checked the artifacts?
@poshul 

In any case, we still need to find a solution for macos Silicon before we switch, or drop the support before doing the transition.
Until then, they should not overwrite each others artifacts.

**Comment by timosachsenberg** [comment]
@poshul can you respond. This could be the reason why the jenkins builds are not working.

**Comment by timosachsenberg** [comment]
deactivated

**Comment by poshul** [comment]
Jenkins is now disabled.
