### ISSUE TITLE
GHA Upload of docs missing

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7056]
Needs to be uploaded as artifact by one of the matrix jobs.
Then downloaded and rsynced to our archive in the deploy step.

**Comment by timosachsenberg** [comment]
@poshul is this done? otherwise will keep it for the current sprint

**Comment by poshul** [comment]
I believe it still needs to be done.

On Monday, October 16, 2023, Timo Sachsenberg ***@***.***>
wrote:
> @poshul is this done? otherwise will keep it for the current sprint
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci6.googleusercontent.com/proxy/oZ8Rut01hAAt8xy2kfqKM63G1mgmGEuLa_BPoiEvvGMwn8V-yWIZFV5JhFHhXG7rCsYkU67d_vJLFPZhRQeMTfOHbd37ivjSS3Os4LgQ4X61VkIdaG0Ok1WeQFYVkb-dlZJBdpOL8jX2XzmLc4GPHo9cHe35eaOzgSUInsb8scqOnmO66giehDrlDZc0XilQhYp7N044K3psiuIUWrInUTZJgIdP4l4lV-raqzaTFtItr1xIfw=s0-d-e1-ft#https://github.com/notifications/beacon/AABD3C6UTEZOM55QPA3RCATX7UJHRA5CNFSM6AAAAAA4EROUACWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTJFBA5A.gif>Message
ID: ***@***.***>

**Comment by poshul** [comment]
Fixing in https://github.com/OpenMS/OpenMS/pull/7193
