### ISSUE TITLE
MzTab crashes in PLFQ if experimental design is not given

### ISSUE THREAD

**Issue by jonasscheid** [OpenMS/OpenMS#7059]
Command:
```bash
ProteomicsLFQ -in PBMC009_msms37.mzML PBMC009_msms36.mzML PBMC009_msms35.mzML -ids 1_PBMC009_A_idx_filtered2_idx.idXML 2_PBMC009_A_idx_filtered2_idx.idXML 3_PBMC009_A_idx_filtered2_idx.idXML -out PBMC009_quant.mzTab -proteinFDR 0.01 -psmFDR 0.01 -FDR_type 'PSM+peptide' -PeptideQuantification:extract:mz_window 5.0 -Alignment:model_type 'linear' -threads 50 -fasta UP000005640_9606_decoy.fasta -ProteinQuantification:top:N 1 -debug 1000 -out_cxml PBMC009_quant.consensusXML > proteomicslfq.log
```

Error:
>terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)

The consenxusXML is written without issues, however the mzTab file writes only the protein entries.
Last info in log before crash is
>MzTab.cpp(964): Initializing study variables:3
-->[Here](https://github.com/OpenMS/OpenMS/blob/45f80f4a851ba6b588b1d9fe8589fec27f7148ab/src/openms/source/FORMAT/MzTab.cpp#L965C15-L965C29)

I think that means that the `-design` flag should be documented as mandatory in PLFQ or there might be a way around this, which I don't know .Trying it out with design flag.

Files: https://drive.google.com/drive/u/0/folders/1QOw4no6bNlLd6JJY9itcRqR39cLqMUVw

**Comment by jonasscheid** [comment]
Ok same error with two conditions and design tsv:

Design tsv:
>Fraction_Group 	Fraction 	Spectra_Filepath 	Label 	MSstats_Condition 	MSstats_BioReplicate
1	1	PBMC009_msms37.mzML	1	Female	1
2	1	PBMC009_msms36.mzML	1	Female	1
3	1	PBMC009_msms35.mzML	1	Female	1
4	1	PBMC007_msms31_cleaned.mzML	1	Male	1
5	1	PBMC007_msms30_cleaned.mzML	1	Male	1
6	1	PBMC007_msms29_cleaned.mzML	1	Male	1

Command:
```bash
ProteomicsLFQ -in PBMC009_msms37.mzML PBMC009_msms36.mzML PBMC009_msms35.mzML PBMC007_msms31_cleaned.mzML PBMC007_msms30_cleaned.mzML PBMC007_msms29_cleaned.mzML -ids 1_PBMC009_A_idx_filtered2_idx.idXML 2_PBMC009_A_idx_filtered2_idx.idXML 3_PBMC009_A_idx_filtered2_idx.idXML 4_PBMC007_B_fdr_filtered2.idXML 5_PBMC007_B_fdr_filtered2.idXM
L 6_PBMC007_B_fdr_filtered2.idXML -out plfq.mzTab -proteinFDR 0.01 -psmFDR 0.01 -FDR_type 'PSM+peptide' -PeptideQuantification:extract:mz_window 5.0 -Alignment:model_type 'linear' -threads 50 -fasta UP000
005640_9606_decoy.fasta -ProteinQuantification:top:N 1 -debug 1000 -out_cxml plfq.consensusXML -design design.tsv > proteomicslfq.log
```

But this time I have some PEP entries in mzTab 🤔 
[plfq.mzTab.zip](https://github.com/OpenMS/OpenMS/files/12498131/plfq.mzTab.zip)

**Comment by jpfeuffer** [comment]
Hmm something is wrong. Your first idXML has `<UserParam type="stringList" name="spectra_data" value="[PBMC009_msms35_cleaned.mzML,PBMC009_msms37_cleaned.mzML,PBMC009_msms36_cleaned.mzML]"/>`.
So it probably is not really from PBMC009_msms37.mzML only.
In general, PLFQ is untested for merged IDs (unless merged by consensusID).

**Comment by jonasscheid** [comment]
Oh, I uploaded the wrong file in that case. Sorry about that.. The right one only has `<UserParam type="stringList" name="spectra_data" value="[PBMC009_msms37.mzML]"/>` (also the other idxmls have this). I updated the file in drive

I basically only did

`IDFilter -in run123_merged_pout_fdrfiltered.idXML -out run1_fdr_filtered2.idXML -whitelist:peptides run1.idXML -delete_unreferenced_peptide_hits -remove_decoys -best:spectrum_per_peptide 'sequence+modification'`

for each run and then manually assigned the corresponding mzml in `spectra_data` to circumvent [this](https://github.com/OpenMS/OpenMS/blob/45f80f4a851ba6b588b1d9fe8589fec27f7148ab/src/topp/ProteomicsLFQ.cpp#L829) 😁 I'm sure there is a better way 😆 

I got the `consensusXML` because that file is written before mzTab. So I'll experiment a bit how that looks like

**Comment by jpfeuffer** [comment]
Oh, yes, there has to be a better way. Reducing just the list of origins to one will let you continue in PLFQ but I am not surprised that you get errors after that. The error has a reason 😄 
How and why are you merging files? You probably just need to split them with IDRipper for now.

Have a look at https://github.com/nf-core/quantms/pull/105/files#diff-75e614ece10f3f6c89b64a2da267e15567c5548d4e9f63a71384d1d14e801b60R57

and related changes in the workflow.

**Comment by jonasscheid** [comment]
:D thanks! Initially I had IDRipper but somehow discarded the idea. I tried it now and it did the job! 🤝 

I want to merge idxmls of runs (technical replicates of a sample) before percolator, rescore, and then I want to separate them again into runs with percolator annotations to align RTs of and quantify peptides. Kind of what you described here https://github.com/OpenMS/OpenMS/issues/7057

I'll test my idea with some MHC spike-in data and comment the news in https://github.com/OpenMS/OpenMS/issues/7057

Thanks again!

**Comment by jpfeuffer** [comment]
The IDRipper functionality with "-split_ids" or how it was called, is fairly new (3.0.0+).
I would love to support merged idXMLs per default and it should not be hard but currently dont find the time.
If anyone with a liiiittle C++ experience volunteers I can give some tips ;)

But yes, I am also using that workaround for now and will make sure it works.

**Comment by jonasscheid** [comment]
Sound great! I see what I can do ;D
