### ISSUE TITLE
operator== vs. copare() function

### ISSUE THREAD

**Issue by mcmenace** [OpenMS/OpenMS#706]
I have noticed that OpenMS contains a range of cases in which operator== triggers a computational expensive comparison of the content of two objects. That is in general the right way to go but in my opinion might lead to an overusage of operator==. As a developer I would always consider operator== as fast. If a 'slow' comparison of content is needed a function named compare() or even compareByContent() or slowCompare() will communicate the cost of comparison much clearer.

Here I want to trigger a discussion if it is worth the go over OpenMS code and change or replace operator== when it is computational expensive.

**Comment by timosachsenberg** [comment]
I close this issue to archive the discussion
