### ISSUE TITLE
MzIdentML parser error for DatabaseName/userParam

### ISSUE THREAD

**Issue by elrubio** [OpenMS/OpenMS#7099]
While #7098 already fixes a related bug, I came across one more:

According to the examples in the [mzIdentML docs](https://github.com/HUPO-PSI/mzIdentML/blob/master/specification_document/specdoc1_2/mzIdentML1%202.0-release.pdf), only the `name` attribute seems to be relevant for `DatabaseName/userParam` elements.

In [MzIdentMLDOMHandler::parseUserParam_](https://github.com/OpenMS/OpenMS/blob/f958a6bc954de76f373ea5bf659c04c11b0fce38/src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp#L611), you return the pair `<name, value>` for *userParams*, but later on, (only) the `value` is used:

https://github.com/OpenMS/OpenMS/blob/f958a6bc954de76f373ea5bf659c04c11b0fce38/src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp#L1233-L1237

This should rather be `dbname = param.first.toString();`. 

In fact, with the currect code, when I rename the `name` attribute to `value`, the warning `No DatabaseName element found, use read in results at own risk` disappears.

**Comment by jpfeuffer** [comment]
Hmm this is awful design since all other userParams on the specification are name-value pairs.
I think this should be reported at mzIdentML.
The only thing I can offer is to set value to the same string as name in case this happens, as a fallback. But then how do you distinguish between an actually missing value and the special case just for this element..
I am not happy with this change however.

**Comment by elrubio** [comment]
> Hmm this is awful design

Yes, but it's rather the published examples than the specs. And since the `value` attribute is declared _optional_ for `userParam`, the common existence of both `name` and `value` follows more a (very logical) convention than a specification.

> The only thing I can offer is to set value to the same string as name in case this happens, as a fallback. But then how do you distinguish between an actually missing value and the special case just for this element..

I don't know how and when the value of that `DatabaseName` element is used, if at all, by the parser. But I think, given the examples in the specs, that it should handle this specific case and use the value from the `name` attribute only for `DatabaseName/userParam` and only if `value` is missing. Maybe there are even more examples like this in the specs?

Also, you could issue a corresponding warning like "no 'value' attribute found, using content of 'name' attribute instead".
