### ISSUE TITLE
Wrong m/z calculation when loading sage/percolator files

### ISSUE THREAD

**Issue by elrubio** [OpenMS/OpenMS#7111]
In `PercolatorInfile:load()`, the conversion *mass* to *m/z* is done incorrectly, leading to wrong m/z values in all idXML files produced by `SageAdapter` and potentially other tools.

https://github.com/OpenMS/OpenMS/blob/b18b52e0b8219830bef780b5c67a1035b70aeb91/src/openms/source/FORMAT/PercolatorInfile.cpp#L203

The charge must be **added** to the mass instead of subtracted:

`mz = (mass + z * mass_proton) / z`

which can be simplified to

`mz = mass/z + mass_proton`

Now I know why InternalCalibration reported 100% of peptides being outside the 25 ppm range. 🥴

**Comment by jpfeuffer** [comment]
I agree. And proposed a fix. I guess test data needs to be adapted after that.

**Comment by jpfeuffer** [comment]
I think percolator **input** files are not parsed anywhere else so luckily this probably "just" affects SageAdapter

**Comment by elrubio** [comment]
Thanks for the quick fix 👍
