### ISSUE TITLE
MASCOT:uniqueToProt is added by PSMFeatureExtractor but can potentially leak td-information

### ISSUE THREAD

**Issue by jonasscheid** [OpenMS/OpenMS#7118]
Needs to be removed, else target-decoy leakage can happen
https://github.com/OpenMS/OpenMS/blob/342f6524e76a2bab3dcb428ba2f4aa2d6bfe8483/src/openms/source/ANALYSIS/ID/PercolatorFeatureSetHelper.cpp#L261

**Comment by timosachsenberg** [comment]
Thanks. Feel free to open a PR e.g. via online edit.
