### ISSUE TITLE
Newly created folders in build archive no accessible

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#7126]
https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/developer_tutorial.html is marked as forbidden when I try to access it.

**Comment by jpfeuffer** [comment]
which job created this version of the docs? the new GHA job? If so, probably permissions are wrong for new files. Overwriting is apparently still working.

**Comment by timosachsenberg** [comment]
Seems that permissions are wrong. Maybe because of change to ceph and some changes in user or default permissions?

**Comment by timosachsenberg** [comment]
chmod 777 on the folder seems to fix it
e.g. had to do it here as well : https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/RC/3.1.0/html/index.html

**Comment by timosachsenberg** [comment]
I contacted Martin. This is related to the new file system. He will set new defaults but we might need to manually update the ones that have already been created.

**Comment by timosachsenberg** [comment]
k this is fixed. was related ot default umask
