### ISSUE TITLE
Ini files have duplicate option names

### ISSUE THREAD

**Issue by SGSSGene** [OpenMS/OpenMS#7127]
There are three tools in OpenMS that are reusing the name of an option. First use is always as an value and the second one as a group/section. This causes the XML to be not as precise as maybe assumed and causes trouble with other system like CWL which assume the name of an option is unique (at least in its group).

As an example the important parts of FeatureFinderCentroided.ini, to see the issue.
The parameter `FeatureFinderCentroided:1:algorithm:debug` exists twice.
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<PARAMETERS version="1.7.0" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/OpenMS/OpenMS/develop/share/OpenMS/SCHEMAS/Param_1_7_0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NODE name="FeatureFinderCentroided" description="Detects two-dimensional features in LC-MS data.">
     <NODE name="1" description="Instance &apos;1&apos; section for &apos;FeatureFinderCentroided&apos;">
     <NODE name="algorithm" description="Algorithm section">
        <ITEM name="debug" value="false" type="bool" description="When debug mode is activated, several files with intermediate results are written to the folder &apos;debug&apos; (do not use in parallel mode)." required="false" advanced="false" />
        <NODE name="debug" description="">
          <ITEM name="pseudo_rt_shift" value="500.0" type="double" description="Pseudo RT shift used when ." required="false" advanced="true" restrictions="1.0:" />
        </NODE>
      </NODE>
    </NODE>
  </NODE>
</PARAMETERS>
```

Similar issues exists in PeakPIckerWavelet.ini with `PeakPickerWavelet:1:algorithm:optimization`
and TOFCalibration.ini with `TOFCalibration:1:algorithm:optimization`

Feedback on this issue would be appreciated.

**Comment by timosachsenberg** [comment]
I think in OpenMS the second is not ```FeatureFinderCentroided:1:algorithm:debug``
 ```FeatureFinderCentroided:1:algorithm:debug`:pseudo_rt_shift"

**Comment by mr-c** [comment]
@SGSSGene in the release meeting, it was decided that these conflicts should be fixed now and mentioned in the release notes; no upgrader needed
