### ISSUE TITLE
Windows installer hangs when installing VS runtime

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#7143]
when installing the VS runtime dependencies for msconvert (which is the default and independent of the 'VS runtime' installation which can independently be activated), then the installer hangs after the third (=last?) runtime tried to install.
I usually abort the redist-install, because they are already on my system, but no matter if aborted or not, the installer should not hang afterwards.
Tested on Win10 with the latest 3.1RC installer.

**Comment by jpfeuffer** [comment]
Does it affect user, global or both?

**Comment by cbielow** [comment]
I tried User. May affect global as well, not tested.

**Comment by jpfeuffer** [comment]
I think user install is not elevated so if any of the redist installers
require admin, problems are to be expected. In that case the install should
be skipped and the user warned that they or their admin needs to install
the redists separately

Chris Bielow ***@***.***> schrieb am Do., 19. Okt. 2023,
17:29:

**Comment by cbielow** [comment]
Selecting a user install does not necessarily mean that the user cannot provide admin credentials. 
We should allow user-only install of Openms plus redistinstall with admin rights. 
I would guess the problem is on the NDist side or the way we handle the return values of the redist attempts?!

**Comment by jpfeuffer** [comment]
Sure. One can try.

Note that it will be weird in a silent install.

And I would recommend to check if these redists are even needed. I have the feeling since years, that there are versions of pwiz out there that come with the redist dlls inside their installation dir.

**Comment by cbielow** [comment]
I see a lot of familiar dll names in the pwiz bin directory... so it seems your intuition is correct.
Also their installation instructions only mention .NET, no vsruntime.

We could do the same actually, if we put all executables (incl. THIRDPARTY) in one bin-folder. They could also stay separate, but then the folder of the vsruntimes needs to be in PATH.. wherever we put them.

**Comment by jpfeuffer** [comment]
Yes. The only downside are potential updates to the redists.
If you use the ones from the registry/system wide, they automatically get
updated with Windows update.

Chris Bielow ***@***.***> schrieb am Fr., 20. Okt. 2023,
15:20:

**Comment by cbielow** [comment]
closing since the new installers (backported to 3.0 and 3.1) do not require redists anymore.
