### ISSUE TITLE
MzQuantMLHandler error when <Modification> element has no "massDelta" attribute

### ISSUE THREAD

**Issue by elrubio** [OpenMS/OpenMS#7145]
I have *mzQuantML* files from label-free experiments (produced by [Dinosaur](https://github.com/fickludd/dinosaur)) containing the following section:

```
<AssayList id="AssayList_1">
  <Assay rawFilesGroup_ref="the-file-group" id="the-assay">
    <Label>
      <Modification>
        <cvParam accession="MS:1002038" cvRef="PSI-MS" name="unlabeled sample"/>
      </Modification>
    </Label>
  </Assay>
</AssayList>
```

Running `IDMapper` on them leads to :

```
Error: Unexpected internal error (Could not convert string '' to a double value)
```

Turns out, `MzQuantMLHandler` expects the `<Modification>`  element to have a `deltaMass` attribute with a numeric value. 

https://github.com/OpenMS/OpenMS/blob/55094ca9c98949c8d8657d233267a56978f3de8d/src/openms/source/FORMAT/HANDLERS/MzQuantMLHandler.cpp#L166-L177

To my understanding, according to the specs, the `deltaMass` attribute is optional since it's not annotated as required:

https://github.com/HUPO-PSI/mzQuantML/blob/0dd30fd070b8c71ad94e1df8094e626687f8fe28/schema/mzQuantML_1_0_0.xsd#L1167-L1171

May I suggest to expand the guard and check not only for "145" but also for the empty string?

**Comment by cbielow** [comment]
thanks for reporting!
our mzQuantML implementation is not 100% fleshed out I must say...
Fixed in #7145

**Comment by elrubio** [comment]
Thank you @cbielow! I truly appreciate that these bugs get fixed so quickly. 

On the other hand, I am quite surprised to still [encounter](https://github.com/OpenMS/OpenMS/issues/7097) [issues](https://github.com/OpenMS/OpenMS/issues/7099) related to basic data file parsing some 15+ years after the v1.0 release. These issues came up right away while performing the most basic tasks, using files created by well-known software containing data from boring standard DDA label-free experiements. They were all blockers for me and I surely wasn't the first to stumble over them.

I recognize that parsing these XML-based formats with all their CV stuff is neither fun nor trivial, but it is a very fundamental part of OpenMS, it's the entrance point. Especially non-developer users are easily put off by this and too quickly turn away from the software, as I can witness in my own team (_"If it already fails loading standard data files, how about the rest?"_).

From a user perspective, I wish for a future version of OpenMS to be rock-solid when it comes to reading _valid_ HUPO-PSI files like _mzIdentML_, _mzQuantML_ or _mzML_. These files should (ideally) never trigger an error unless they are _invalid_. But even then, the error message should state the exact cause of the problem and the location of the offending file content. With the help of the schemata, valid and invalid files could even be created programmatically and tested automatically.

**Comment by cbielow** [comment]
Fully agree on all the points you mentioned.
My feeling is that the core developers usually stay within the OpenMS ecosystem (from Raw file to mzTab/Excel), and hence mzML is battle-tested over and over, but side entries like mzQuantML and mzIdentML can easily fail, since, as you say, they are complex beasts and hard to get right -- for both readers and writers.
However, we will usually try to fix those issues rather quickly, once we get to know about them.
So thanks again for reporting this and keep 'em coming :)
