### ISSUE TITLE
MSFragger does not work with relative pathnames

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#7152]
```
Checking database...

Database src/tests/topp/THIRDPARTY/proteins.fasta does not exist.
```

Can't remember that this failed for 2.x, maybe in 3.x the MSFragger subprocess is executed using the tmp dir as working dir? Alternatively one could make the path absolute.

**Comment by cbielow** [comment]
nice find!
Thanks for reporting.
Fixed in #7155
