### ISSUE TITLE
suggestion: rename PeakPickerMRM to PeakPickerChromatogram

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7181]
From a user perspective: if I want to pick an e.g., MS1 MSChromatogram, I have a hard time finding this function.
I might find ElutionPeakDetection from FeatureFinderMetabo, but that one works on MassTraces

**Comment by jcharkow** [comment]
Yes I agree! Would any other files also be useful on the MS1 level? E.g.  MRMFeatureFinderScoring.cpp has the option to compute chromatogram scores only on the MS1 level. Also would there be a more appropriate location to place these files as right now they are hidden in OpenSwath

**Comment by timosachsenberg** [comment]
This is an excellent suggestion and I think this would be really useful.

I think everything that is low level chromatogram related could go into its own namespace e.g., “Chromatogram”, "Chrom". "ChromatogramProcessing".
From a library perspective, it would even be better if we could have a folder CHROMATOGRAM somewhere - given our current folder structure (which could imho be improved) it would probably go to the FILTERING folder (which is more like a processing folder).
![image](https://github.com/OpenMS/OpenMS/assets/5803621/2460f84c-c903-4eb7-8ec0-cc753ecaa510)
.
