### ISSUE TITLE
Expose MetaboliteAdductDecharger functionality in pyOpenMS

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7188]
via user request in the metabolomics channel of CompMS in slack.
"MetaboliteAdductDecharger is exactly what I am looking for. Are you planning to integrate it into pyOpenMS? It would be fantastic if it could, for example, take a pyopenms.MSExperiment object as input and return a pandas.DataFrame with clustered features."

I see we already have a python wrapper https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/MetaboliteFeatureDeconvolution.pxd

Looking at the C++ code it seems it is just calling the MetaboliteFeatureDeconvolutionalgorithm:
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MetaboliteAdductDecharger.cpp

so maybe this is already doable (and just lacks some documentation / an example)?

**Comment by timosachsenberg** [comment]
e.g. have a 
small tutorial that does
- feature detection from MSExperiment and then decharging? 
- and make sure where to find the parameters (e.g., to configure adducts)

**Comment by axelwalter** [comment]
[Added tutorial here](https://pyopenms.readthedocs.io/en/latest/user_guide/adduct_detection.html).
