### ISSUE TITLE
Resampler uses Da instead of PPM

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#7211]
in this configuration:
![image](https://github.com/OpenMS/OpenMS/assets/6008722/4d24c22c-13ad-4cf5-9562-ede1dcf02f74)
i.e. when `align_sampling` is false

**Comment by timosachsenberg** [comment]
Only the LinearResamplerAlign has this parameter:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/FILTERING/TRANSFORMERS/LinearResampler.h
