### ISSUE TITLE
how to build pyopenms 

### ISSUE THREAD

**Issue by JKVISION1101** [OpenMS/OpenMS#7217]
Hi my name is jaekwan kim

I got stuck in building pyopenms.

My goal is to  wrap flashdeconv to be used in python.

First, i tried to build pyopenms by refering to  pyopenms documentation 

> "https://pyopenms.readthedocs.io/en/latest/community/build_from_source.html"

the document said that `cmake -DPYOPENMS=ON`

I added -DPYOPENMS=ON in the middle of code which was previously build successfully.

In visual studio command line, i typed below code
`cmake -D OPENMS_CONTRIB_LIBS="C:\Users\KBSI\Desktop\openms_development\contrib_build" -D CMAKE_PREFIX_PATH="D:/Qt/5.15.2/msvc2019_64/" -DPYOPENMS=ON -G"Visual Studio 16 2019" -A x64 -T host=x64 "C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\OpenMS"`

and build succeeded.

In the next,

document says do `make pyopenms`

I did but it `make: Nothing to be done for 'pyopenms'.` came  out.

So, i opened OpenMS_host.sln file and tried to build pyopenms 

It failed too.

My qustion is after cmake, what should i do for wrapping new classes(Flashdeconv)?

If you have any guide please let me know.

Sincerely regards

Jaekwan Kim

**Comment by jpfeuffer** [comment]
Hi Jaekwan!

What was the error with Visual Studio?

Note that "make" will indeed not work with Visual Studio. That is an error in the docs.
You need to either build it from the VisualStudio UI or run `cmake --build $buildfolder --target pyopenms --config Release`


@timosachsenberg the docs should be updated to use cmake --build to be platform/generator independent.

**Comment by jpfeuffer** [comment]
Btw: If you want to use make or ninja on Windows, you can do that but you must make sure that the Visual Studio command line variables are available.

**Comment by timosachsenberg** [comment]
I updated it in https://github.com/OpenMS/pyopenms-docs/blob/master/docs/source/community/build_from_source.rst

**Comment by KyowonJeong** [comment]
Let me try from my machine and will get back to you @JKVISION1101

**Comment by JKVISION1101** [comment]
@jpfeuffer Thank you for reply.


In the OpenMS_host.sln file. i build pyopenms target 

However, many error came out.



`Severity	Code	Description	Project	File	Line	Suppression State`

`Error	C1189	#error:  Do not use this file, it is the result of a failed Cython compilation.	pyopenms_2	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\pyOpenMS\pyopenms\_pyopenms_2.cpp	1`	

`Error	C1189	#error:  Do not use this file, it is the result of a failed Cython compilation.	pyopenms_1	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\pyOpenMS\pyopenms\_pyopenms_1.cpp	1`

`Error	C1189	#error:  Do not use this file, it is the result of a failed Cython compilation.	pyopenms_5	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\pyOpenMS\pyopenms\_pyopenms_5.cpp	1`
	
`Error	C1189	#error:  Do not use this file, it is the result of a failed Cython compilation.	pyopenms_8	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\pyOpenMS\pyopenms\_pyopenms_8.cpp	1`
	
`Error	C1189	#error:  Do not use this file, it is the result of a failed Cython compilation.	pyopenms_4	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\pyOpenMS\pyopenms\_pyopenms_4.cpp	1`
	
`Error	C1189	#error:  Do not use this file, it is the result of a failed Cython compilation.	pyopenms_3	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\pyOpenMS\pyopenms\_pyopenms_3.cpp	1`
	
`Error	C1189	#error:  Do not use this file, it is the result of a failed Cython compilation.	pyopenms_6	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\pyOpenMS\pyopenms\_pyopenms_6.cpp	1`
	
`Error	C1189	#error:  Do not use this file, it is the result of a failed Cython compilation.	pyopenms_7	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\pyOpenMS\pyopenms\_pyopenms_7.cpp	1`
	
`Error		subprocess-exited-with-error	pyopenms	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\src\pyOpenMS\CUSTOMBUILD	1`
	
`Error	C1189	#error:  Do not use this file, it is the result of a failed Cython compilation.	pyopenms	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\src\pyOpenMS\pyopenms\_pyopenms_1.cpp	1	`

`Error		command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2	pyopenms	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\src\pyOpenMS\CUSTOMBUILD	1`
	
`Error		Failed building wheel for pyopenms	pyopenms	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\src\pyOpenMS\CUSTOMBUILD	1`
	
`Error		Failed to build one or more wheels	pyopenms	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\src\pyOpenMS\CUSTOMBUILD	1`
	
`Error	MSB8066	Custom build for 'C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\CMakeFiles\e05b09f6e0d99bd4530ce177776211df\pyopenms.rule;C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\OpenMS_OpenMS\OpenMS\src\pyOpenMS\CMakeLists.txt' exited with code 1.	pyopenms	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241`	


There are 14 Errors.

and Error 1~8, they said that failed cython comilation pyopenms_1,2,3,4,5,6,7,8 file.

and other is wheel problem. (i installed wheel library)

**Comment by JKVISION1101** [comment]
@timosachsenberg Thank you.  i read it.

**Comment by JKVISION1101** [comment]
@KyowonJeong Thank you.

**Comment by jpfeuffer** [comment]
Unfortunately none of them are the reason for the failure. The real error must have occured earlier.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

I cloned the lateset version OpenMS source code and did cmake before building pyopenms.

At what stage do you think an error might occur?

**Comment by jpfeuffer** [comment]
When you build pyopenms but during the cythonize/create_cpp steps and not during compilation.
You need to delete your cpp files since as the compiler tells youy they are a product of a failed cython compilation.
CMake does not know that.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

Thanks for reply.

you mean i need to delete _pyopenms_1,2,3,4,5,6,7,8.cpp file?

When i open OpenMS_host.sln file, there are many build targets such as pyopenms, pyopenms_1~8.

and there is _pyopenms_1.cpp file in the pyopenms_1 build target. and also pyopenms_2,3,4,5,6,7,8.

if i opened pyopenms_1.cpp file in visual studio, "could not find file error" came out

Although Visual studio showed that these cpp files's directory is in the pyopenms folder, however there are no cpp files there..

**Comment by jpfeuffer** [comment]
Yes, correct, the _pyopenms_x.cpp files
You probably have to delete them by hand in the explorer.

They won't be reachable via Visual Studio since they are no source files but build products.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

yes, I deleted all _pyopenms_x.cpp files.

and among 14 errors, 8 errors disappeared.

and 6 errors still remains.

Severity	Code	Description	Project	File	Line	Suppression State
1) `Error	MSB8066	Custom build for 'C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\CMakeFiles\e05b09f6e0d99bd4530ce177776211df\pyopenms.rule;C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\OpenMS_OpenMS\OpenMS\src\pyOpenMS\CMakeLists.txt' exited with code 1.	pyopenms	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	`


2) `Error		subprocess-exited-with-error	pyopenms	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\src\pyOpenMS\CUSTOMBUILD	1	
Error	C1189	#error:  Do not use this file, it is the result of a failed Cython compilation.	pyopenms	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\src\pyOpenMS\pyopenms\_pyopenms_1.cpp	1	`


3) `Error		command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2	pyopenms	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\src\pyOpenMS\CUSTOMBUILD	1	`


4) `Error		Failed building wheel for pyopenms	pyopenms	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\src\pyOpenMS\CUSTOMBUILD	1`

	
5) `Error		Failed to build one or more wheels	pyopenms	C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\src\pyOpenMS\CUSTOMBUILD	1	`


6) `Error	MSB8066	Custom build for 'C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123\CMakeFiles\e05b09f6e0d99bd4530ce177776211df\pyopenms.rule;C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\OpenMS_OpenMS\OpenMS\src\pyOpenMS\CMakeLists.txt' exited with code 1.	pyopenms	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	`


As you see second error, there is also _pyopenms_1.cpp error.

Weirdly , the error said that _pyopenms_1.cpp file is in the 
 C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\build_20231123/src/pyOpenMS/pyopenms


above directory. However, there is no pyopenms folder in the src/pyOpenMS folder in my computer.

**Comment by jpfeuffer** [comment]
Hmm unfortunately, there is again no error that says **why** compilation failed. I'm sure that it usually reports that.
You probably must search some logs manually then.
Unfortunately I don't know from far which logs would be the best to start.
Hopefully somewhere in the pyOpenMS folder. Maybe pyOpenMS/CMakeFiles.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

Have you built pyopenms before?

If you have succeeded before, what is your machine mac or windows or linux?

**Comment by jpfeuffer** [comment]
Hi! Yes I did. Currently on macOS but I have built it on Windows and Linux as well before. Unfortunately, Windows with visual studio has been some time ago, so I cannot say how to enable better logging. Maybe @cbielow knows a bit more about Visual Studio?

**Comment by JKVISION1101** [comment]
@jpfeuffer 

I am windows user :(.

I appreciated your time and many suggstion.

Thank you so much.

**Comment by jpfeuffer** [comment]
I would suggest to start over with a new source and build folder.
Then use visual studio from the command line.

`cmake -DPYTHON_EXECUTABLE:FILEPATH=$CURRENT_PYTHON_EXECUTABLE -DPYOPENMS=ON .`
`cmake --build . --config Release --target pyopenms`

If that does not work, start again and use the ninja makefile generator in a visual studio x64 command line.


A third option would be to use the Windows Subsystem for Linux but I am pretty sure it should build with Visual Studio. (It does so every night on the university computers and on GitHub)

**Comment by jpfeuffer** [comment]
I would also suggest to schedule a  video call with one of the developers on discord. This should be easily solved with a direct look into it.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

You mean i pull OpenMS code again and make new build folder.

and i configure pyopenms build system in that folder

`cmake -DPYTHON_EXECUTABLE:FILEPATH=$C:\Users\KBSI\AppData\Local\Programs\Python\Python37 -DPYOPENMS=ON `
only this code without other code such as 
`-D OPENMS_CONTRIB_LIBS="C:\Users\KBSI\Desktop\openms_development\contrib_build" -D CMAKE_PREFIX_PATH="D:/Qt/5.15.2/msvc2019_64/" -G"Visual Studio 16 2019" -A x64 -T host=x64 "C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\OpenMS`???



then build pyopenms in the build folder
`cmake --build . --config Release --target pyopenms`
or build Visual studio UI right

isn't it right?

**Comment by jpfeuffer** [comment]
Yep! Sounds completely correct. But I would highly recommend command line over UI. As we have seen, the UI is not great at logging. Make sure the command line output is saved somewhere

**Comment by jpfeuffer** [comment]
Wait, I misunderstood. You need your computer specific CMake options of course. E.g. where you installed Qt etc
So please put all options.

**Comment by JKVISION1101** [comment]
yes.. i
only typed `cmake -DPYTHON_EXECUTABLE:FILEPATH=$C:\Users\KBSI\AppData\Local\Programs\Python\Python37 -DPYOPENMS=ON`

and.. `CMake Error: The source directory "C:/Users/KBSI/Desktop/openms_development/pyFLASHDeconv/build_20231129" does not appear to contain CMakeLists.txt`

this error came out..... 

below is rihgt?

 `cmake -DPYTHON_EXECUTABLE:FILEPATH=$C:\Users\KBSI\AppData\Local\Programs\Python\Python37 -DPYOPENMS=ON -D OPENMS_CONTRIB_LIBS="C:\Users\KBSI\Desktop\openms_development\contrib_build" -D CMAKE_PREFIX_PATH="D:/Qt/5.15.2/msvc2019_64/" -G"Visual Studio 16 2019" -A x64 -T host=x64 "C:\Users\KBSI\Desktop\openms_development\pyFLASHDeconv\OpenMS`

**Comment by jpfeuffer** [comment]
You have a $ sign too much in the python path

**Comment by jpfeuffer** [comment]
And try to always put your paths in quotes ""

**Comment by JeeH-K** [comment]
This actually seems like Cython and other library problems. I had a chat with Jaekwan and we both had similar error messages during pyopenms target build (after a successful openms build). The messages were regarding cython compiling error with undeclared builtin "nogil". I set up a clean virtual env for pyopenms build (with the latest Cython version) and the errors went away. I tried this in Mac OS and shared the info with Jaekwan to see if it works for Windows.

**Comment by jpfeuffer** [comment]
Ok that makes sense. I just never saw this message in the log reports here, that's why I was confused.
If you see that error again, please post it here so we can fix it or change the minimum required Cython version.

**Comment by JeeH-K** [comment]
Unfortunately, I don't have a copy of the error message, but it was something like

`Error compiling Cython file:`
`/OpenMS/src/pyOpenMS/pxds/InterfaceDataStructures.pxd:12:41: undeclared name not builtin: nogil`

Similar messages were repeated almost indefinitely because the same error occurred from almost all pxd files. 
The Cython version I used before was 0.28 or something, and the updated version of 3.0.0 gave no error.
Adding the minimum required Cython version (at least in the doc) would for sure avoid this problem.

**Comment by jpfeuffer** [comment]
Ok. I will close here for now. Please re-open if it does not work with newest Cython also. I will open a separate issue to investigate

**Comment by JKVISION1101** [comment]
@JeeH-K @jpfeuffer 

Yesterday, Jeehyung tried to find out what makes pyopenms error.

and she commented that cython version could be reason. So today i checked my cython version 0.29.34 (i don't know why this version was installed...)

Today i build again with updated cython version(>3.0)

and __pyopenms_1,2,3,4,5,6,7,8.cpp error disappeared without deleting these file.

I think it is very big progress.. 

However, 6 errors remains still..

I will write new issue about this problem.


Thanks all again.
