### ISSUE TITLE
OpenSWATH: Differences Between OSW and TSV File Contents

### ISSUE THREAD

**Issue by bruadi** [OpenMS/OpenMS#7222]
Hello everyone,

I'm using OpenSwath for small molecule analysis. When generating results in OpenSwath as OSW and TSV files, I've noticed that they do not contain exactly the same content. I can convert the OSW file to a TSV format using Pyprophet, but then this TSV file only includes the columns from the OSW file and not all the columns from the TSV file directly from OpenSwath.

For example, the TSV files contain columns like masserror_ppm, rt_fwhm, aggr_Peak_Apex, aggr_Peak_Area, aggr_prec_Peak_Apex, aggr_prec_Peak_Apex, etc., which provide information for each individual feature of a molecule. These columns are not included in the OSW file. However, the OSW file does contain columns or scores such as var_ms1_xcorr_coelution_contrast, var_ms1_xcorr_coelution_combined, var_ms1_xcorr_shape_contrast, var_ms1_xcorr_shape_combined, which describe how well the precursor and fragment ion traces match (if I've understood correctly. I found this information about the score here: "[https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/release/3.1.0/html/classOpenSwath_1_1MRMScoring.html#a45bffdb3e0ec0fc80b6cca528224db03"](https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/release/3.1.0/html/classOpenSwath_1_1MRMScoring.html#a45bffdb3e0ec0fc80b6cca528224db03%E2%80%9D)). However, these  very important "contrast and combined" columns are not found in the TSV file. Would it be possible to include all these aforementioned columns in the OSW file as well? These columns and data are very important to me...

Best regards

**Comment by jcharkow** [comment]
Hi Braudi,

Many of the columns that you mentioned that are only in the .tsv file are in the .osw file but they are named differently. 

Most of the transition level columns (aggr_peak_apex, aggr_peak_area, rt_fwhm) are hidden in the `FEATURE_TRANSITION` table. Most of the precursor level information (aggr_prec_peak_apex, aggre_prec_peak_area) is in the  `FEATURE_MS1` table.  A sample sql statement fetching this information is provided below. 

```
select DISTINCT
group_concat(FEATURE_TRANSITION.AREA_INTENSITY, ';') as aggr_Peak_Area,
group_concat(FEATURE_TRANSITION.APEX_INTENSITY, ';') as  aggr_Peak_Apex,
group_concat(FEATURE_MS1.APEX_INTENSITY,';') as aggr_prec_Peak_Apex,
group_concat(FEATURE_MS1.AREA_INTENSITY, ';') as aggr_prec_Peak_Area,
group_concat(TRANSITION.TRAML_ID, ';') as aggr_Fragment_Annotation
from FEATURE
INNER JOIN FEATURE_TRANSITION on FEATURE_TRANSITION.FEATURE_ID = FEATURE.ID 
INNER JOIN TRANSITION on TRANSITION.ID = FEATURE_TRANSITION.TRANSITION_ID
INNER JOIN FEATURE_MS1 on FEATURE_MS1.FEATURE_ID = feature.ID
group by FEATURE_TRANSITION.FEATURE_ID
```

However, I could not find the transition level `masserror_ppm` and the `rt_fwhm` in the .osw file so I am currently working on a PR to address this.  

Please let me know if there are any other columns in the `.tsv` column that you would want to also see in the `.osw` file. 

Best,

Josh

**Comment by bruadi** [comment]
Hello @Josh,

You are right! When I analyzed the OSW file, I converted it into a TSV format using Pyprophet. Unfortunately, it seems that all the specific information I had requested got lost in this TSV file... Now, when I revisit the OSW file with SQL statements, everything is there as you mentioned, except for masserror_ppm and rt_fwhm. I'm sorry, I hadn’t noticed that earlier...

The TSV file also includes sn_ratio and var_log_sn_score values. I am unsure whether var_log_sn_score is just the logarithm of the sn_ratio column, or if sn_ratio pertains to MS1 and var_log_sn_score to MS2...

I am not sure about the effort it would entail for you, but it would be generally very nice if the OSW file or OpenSwath could output S/N values, values for left and right width, rt_fwhm values, and masserror_ppm (like rt_fwhm only for transitions in the tsv file), as well as Rt at the peak maximum (In theory, with correct identification, every feature should have the same Rt, but with correct identification, the xcorr coelution score is not always perfect. A consensus Rt value is, of course, also important, but that is already included) for each feature, i.e., ### for precursor + isotope and transitions. These are important data for describing the quality of a peak, such as the tailing factor. In the "Feature" table, there are columns for "Left width" and "Right width," but I believe they refer to the width of the consensus peak and not each individual feature. Would it also be possible for OpenSwath to include these details in the OSW file? I think OpenSwath already generates all these values to calculate the various scores...

Best regards

**Comment by jcharkow** [comment]
A lot of the information from the .osw file is excluded from the .tsv file exported by pyprophet in order to reduce the size of the .tsv file. To address this issue, I have been working on a .parquet export for pyprophet https://github.com/PyProphet/pyprophet/pull/111. Parquet files can be loaded column-wise into python/R for analysis and exported to .tsv if necessary. 

Yes, the `var_log_sn_score` is just the logarithm of the `sn_ratio` column in the .tsv file. 

I will look into how feasible it is to include the left-right width for each transition but I think this should be possible.

**Comment by bruadi** [comment]
Thank you for taking care of my requested inquiries, it would be really awesome if the missing data from the OpenSwath TSV file are now also found in the OSW files, as well as my extra wishes :D

The OSW to Parquet formatting is nice, and I would even prefer it over OSW. However, when I tried, I encountered a problem again: `'File "/opt/anaconda3/envs/py3/lib/python3.9/site-packages/pyprophet/export_parquet.py", line 471, in export_to_parquet if check_sqlite_table(con, "GENE") and pd.read_sql('SELECT GENE_NAME FROM GENE', con).GENE_NAME[0]!='NA’:"` Since I work with small molecules, I cannot use this. I also had to use the export-compound function for the OSW to TSV file...
Will the Parquet also be adapted for small molecules?

Best regards

**Comment by jcharkow** [comment]
> Thank you for taking care of my requested inquiries, it would be really awesome if the missing data from the OpenSwath TSV file are now also found in the OSW files, as well as my extra wishes :D
> 
> The OSW to Parquet formatting is nice, and I would even prefer it over OSW. However, when I tried, I encountered a problem again: `'File "/opt/anaconda3/envs/py3/lib/python3.9/site-packages/pyprophet/export_parquet.py", line 471, in export_to_parquet if check_sqlite_table(con, "GENE") and pd.read_sql('SELECT GENE_NAME FROM GENE', con).GENE_NAME[0]!='NA’:"` Since I work with small molecules, I cannot use this. I also had to use the export-compound function for the OSW to TSV file... Will the Parquet also be adapted for small molecules?
> 
> Best regards

I can look into adding small molecule support in the future!

**Comment by bruadi** [comment]
Hi!

I have another question or rather I am a bit confused. When I look at the OSW file, there are some columns where the values within the tables of the OSW file do not match.

When I compare the FEATURE_PRECURSOR table with the FEATURE_MS1 table, there are discrepancies in the values of AREA_INTENSITY and APEX_INTENSITY. This problem also occurs with FEATURE_TRANSITION & FEATURE_MS2, although I don't quite understand how the individual transitions of a precursor can have different TOTAL_AREA_INTENSITY values. I understand that in FEATURE_MS1 & FEATURE_MS2 the data for each characteristic of a target is not specified as in FEATURE_PRECURSOR & FEATURE_TRANSITION, but I'm a bit confused as to how this discrepancy occurs and which values are the correct ones...?

![image](https://github.com/OpenMS/OpenMS/assets/104862427/d11ec229-f733-4279-9a6b-3a3eaead330e)
![image](https://github.com/OpenMS/OpenMS/assets/104862427/88eb32a6-8fe3-43c5-8a4a-39df6e546829)


Kind regards

**Comment by jcharkow** [comment]
In general, the values in FEATURE_MS2 and FEATURE_MS1 are an amalgamation of the values of all the transitions in FEATURE_TRANSITION or FEATURE_PRECURSOR respectively. The total area intensity refers to the total ion current across that chromatogram (note the chromatogram is only as wide as the preset `rt_extraction_window` which by default does not span the entire retention time range.

 e.g. 
`FEATURE_MS2.AREA_INTENSITY` = SUM(`FEATURE_TRANSITION.AREA_INTENSITY`)
`FEATURE_MS2.APEX_INTENSITY` = SUM(`FEATURE_TRANSITION.APEX_INTENSITY`)
`FEATURE_MS1.APEX_INTENSITY` = SUM(`FEATURE_PRECURSOR.APEX_INTENSITY`)
`FEATURE_MS1.AREA_INTENSITY` = SUM(`FEATURE_PRECURSOR.AREA_INTENSITY`)

**Comment by bruadi** [comment]
Ahh, I understand, thank you very much. 
Sorry, it can sometimes be a bit confusing without detailed descriptions. Do you have any more general information on how all the values and scores are calculated and described? Sometimes it is quite difficult to understand certain values or scores. In the TOPP documentation, I often find at most one sentence about a certain value, if I find anything at all, even if some details are described in the mProphet paper. As an analytical chemist, I can only trust values and data or interpret them correctly if I understand them. It would be extremely helpful, as this would prevent me from having to frequently ask and would provide me with more overall clarity.

Best regards

**Comment by jcharkow** [comment]
No problem! Unfortunately, current documentation for OpenSwath is lacking and this is something that we are actively working on.   

For the time being here are some resources which may be helpful:
1. I have previously worked on this rough documentation which goes into more detail about how OpenSwath works which may be of interest for the time being https://github.com/Roestlab/OpenMS/wiki/OpenSwath
2. The official OpenSwath-Pyprophet website https://openswath.org/en/latest/docs/openswath.html
3.  Supplementary material for the original Rost, 2014 publication https://pubmed.ncbi.nlm.nih.gov/24727770/
4. Looking at the source code, in general, it is fairly well documented

Also, please don't hesitate to ask questions as we are happy to help.

**Comment by bruadi** [comment]
Hi @jcharkow, 
I just wanted to ask when I can expect the patch? 
Best regards

**Comment by jcharkow** [comment]
> Hi @jcharkow, I just wanted to ask when I can expect the patch? Best regards

Sorry for the delay have been busy with other things but patch should be out soon. In the meantime the code is functional just some tests have to be added before merging so you can use the https://github.com/OpenMS/OpenMS/pull/7249 branch.

**Comment by bruadi** [comment]
Hi,
nice, thank you!

**Comment by bruadi** [comment]
Hi,
I'm currently trying to use the branch. When compiling I get this error message: `/Users/openms/src/openms/source/DATASTRUCTURES/LPWrapper.cpp:23:14: fatal error: 'coin/CoinModel.hpp' file not found
    #include "coin/CoinModel.hpp"
                    ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/openms/CMakeFiles/OpenMS.dir/source/DATASTRUCTURES/LPWrapper.cpp.o] Error 1
make[1]: *** [src/openms/CMakeFiles/OpenMS.dir/all] Error 2
make: *** [all] Error 2 `

I cannot find the file "CoinModel.hpp" anywhere in the branch. Sorry, I'm not that familiar with it yet... .
Am I doing something wrong or is this file really missing?
Best regards

**Comment by jcharkow** [comment]
I believe COIN is a dependency. Please take a look at https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/install_win.html for more details on installation. 

All changes are ready just waiting for a review before it can be merged. 
Also there was a bug in the branch that I just fixed yesterday so be sure to use the most up to date version.

**Comment by jpfeuffer** [comment]
> Hi,
> I'm currently trying to use the branch. When compiling I get this error message: `/Users/openms/src/openms/source/DATASTRUCTURES/LPWrapper.cpp:23:14: fatal error: 'coin/CoinModel.hpp' file not found
>     #include "coin/CoinModel.hpp"
>                     ^~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [src/openms/CMakeFiles/OpenMS.dir/source/DATASTRUCTURES/LPWrapper.cpp.o] Error 1
> make[1]: *** [src/openms/CMakeFiles/OpenMS.dir/all] Error 2
> make: *** [all] Error 2 `
> 
> I cannot find the file "CoinModel.hpp" anywhere in the branch. Sorry, I'm not that familiar with it yet... .
> Am I doing something wrong or is this file really missing?
> Best regards

Yes CoinOR is a dependency.
This error usually hints at an old CMakeCache that needs to be updated to reflect changes in our dependency finding mechanisms.
It's probably safest to try and delete your build folder. If the problem persists please open a new issue (if possible with some reproducible steps).

**Comment by jcharkow** [comment]
.OSW file has been extended to include peak shape metrics in https://github.com/OpenMS/OpenMS/pull/7249. Should be available in next release!

**Comment by bruadi** [comment]
Hi @jcharkow,
 sorry, I missed your message. Great, thanks a lot for your effort! Best regards.
