### ISSUE TITLE
The incomplete documentation makes beginners feel extremely difficult.

### ISSUE THREAD

**Issue by liuxiawei** [OpenMS/OpenMS#7252]
I would like to thank all the developers for their hard work in providing us with OpenMS. As an open-source enthusiast, I decisively chose OpenMS for learning protein data processing. However, as a beginner, I faced significant difficulties in getting started. I understand the challenges of open-source work and the high level of expertise required in this field. I believe that comprehensive documentation is crucial for the usability and promotion of software. I have also felt the enthusiasm of the developers. However, in the documentation of OpenMS, outdated part such as OMSSA is still being referenced.  Also as the abandon of Fido. At one point, I even doubted whether the software was still functional. I strongly believe that comprehensive documentation is essential for software, and I hope that the hard work of the developers can be discovered by more users. I kindly request timely updates to the documentation to assist more people in using OpenMS.

**Comment by timosachsenberg** [comment]
Hi @liuxiawei,
thanks for your feedback. While documentation has always been an issue in the last years, we actually hoped that the recent documentation update improved that situation a bit :( . 
May you can point us to the places where, e.g., OMSSA and Fido are still being referenced so I can at least fix this quickly?
And also what you want to achieve with OpenMS (there are so many applications ranging from algorithm development to large scale analysis on HPC infrastructure)? We certainly can't fix everything at once, but having more details on where documentation was lacking most would help us a lot focusing the very limited resources we have.

**Comment by timosachsenberg** [comment]
Needs update: https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/public/TOPPAS.doxygen

**Comment by liuxiawei** [comment]
Thank you for your response. I am willing to contribute to the open-source community. Currently, I have identified the aforementioned issue, and I am also in the early stages of learning the relevant content. I am currently using Snakemake to build a pipeline for batch protein identification from PRIDE data. If I encounter any problems in the future, I hope to provide assistance to the best of my abilities.

**Comment by timosachsenberg** [comment]
We have a pretty well documented (https://docs.quantms.org/en/latest/)  workflow https://nf-co.re/quantms/1.2.0
which is nextflow (not snakemake).
It also supports spectral counting, feature based label-free quantification, TMT, DIA etc. so it is pretty complete.
I think it is also possible (if not feel free to request it!) to just do identification with it.

**Comment by cbielow** [comment]
Hi @liuxiawei,

thanks for sharing your thoughts.
I've updated the TOPPAS tutorial, which referred to OMSSA (now replaced by Comet).
I will dedicate some considerable time to improve user and developer experience, especially tutorials, in the near future.
If you encounter more weirdness, please do not hesitate to let us know!

**Comment by liuxiawei** [comment]
Thank you for your help, everyone! I love OpenMS.
