### ISSUE TITLE
TOPPView: Running TOPP tools fails

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#7254]
Trying to run PeakPickerHiRes on an mzML layer
![image](https://github.com/OpenMS/OpenMS/assets/6008722/1bcd758c-c830-4e29-8cbe-ae44d3a9d321)

results in 
![image](https://github.com/OpenMS/OpenMS/assets/6008722/2122a774-086c-4031-9e10-860c4888db21)

This is probably due to the latest FileHandler changes and needs fixing!

Also: the `-in` and `-out` parameters should probably be hidden from the user, since they will be overridden automatically.

**Comment by timosachsenberg** [comment]
if it is FileHandler related then probably Sam knows how to fix it. added him

**Comment by poshul** [comment]
The issue here is that TOPPViewBase tries to create a temp file that doesn't have an extension. This was fine before FileHandler, but now we enforce extension/content matching.

**Comment by cbielow** [comment]
fixed in #7462
