### ISSUE TITLE
Error report in XTandemAdapter, IDScoreSwitcher, and ProteomicsLFQ

### ISSUE THREAD

**Issue by liuxiawei** [OpenMS/OpenMS#7260]
Thank you to all the developers for their hard work! Recently, I have been learning the basics of OpenMS, and I have been using the data PXD015828 from PRIDE as a practice dataset. During this process, I have encountered the following issues. I referenced quantms（https://github.com/nf-core/quantms/tree/master） to build a set of scripts, and I encountered three issues during testing.
（OpenMS 3.1 installed from bioconda）
![image](https://github.com/OpenMS/OpenMS/assets/5093541/b6544bca-8d92-40b4-8f58-b1c16c524728)

### 1. xtandem Error
Error log:
```
XTandemAdapter -in mzml/20170510_Joshi_9129.mzML -out work/xtandem/20170510_Joshi_9129/dbsearch_20170510_Joshi_9129.idXML -database work/database/target_decoy_database.fasta -xtandem_executable ~/lzy/micromamba/envs/openms/bin/xtandem  -PeptideIndexing:unmatched_action warn -precursor_mass_tolerance 10 -precursor_error_units ppm -fragment_mass_tolerance 0.02 -fragment_error_units Da -enzyme Trypsin/P -missed_cleavages 2 -fixed_modifications "Carbamidomethyl (C)" -variable_modifications "Oxidation (M)" "Phospho (S)" "Phospho (T)" "Phospho (Y)" -threads 48 -debug 0 
    Progress of 'loading mzML':
      Progress of 'loading spectra list':
        2.14 %               
..........            
        95.80 %               
      -- done [took 30.56 s (CPU), 27.43 s (Wall)] -- 
      Progress of 'loading chromatogram list':

      -- done [took 0.02 s (CPU), 0.01 s (Wall)] -- 

    -- done [took 30.60 s (CPU), 27.44 s (Wall) @ 126.3 MiB/s] -- 
Error: Unexpected internal error (the value 'Phospho (S)' was used but is not valid; Modification not found: )
```
And also  'Carbamidomethyl (C)' error report. Other programs like Comet did not encounter any errors, but the XTandemAdapter consistently shows the error Modification message like "the value 'Carbamidomethyl (C)' was used but is not valid; Modification not found." 
### 2. Error in ProteomicsLFQ
I tried to add PeptideIndexer before ConsensusID, but it still error.
Error Report:
```
Error: Unexpected internal error ( ProteinHits do not contain a protein sequence. Cannot compute coverage! Use PeptideIndexer to annotate proteins with sequence information.)
```
More detail log are upload. 
[ProteomicsLFQ_2.log](https://github.com/OpenMS/OpenMS/files/13624126/ProteomicsLFQ_2.log)

### 3. IDScoreSwitcher
I faced error when I use IDScoreSwitcher, I just skipped it Is it allowed to skip the IDScoreSwitcher?
Errorlog:
```
IDScoreSwitcher -in work/20170510_Joshi_9119/consensusID.idXML -out work/20170510_Joshi_9119/idscoreswitcher.idXML -new_score_orientation higher_better -threads 48 -debug 0 
Error: Unexpected internal error (Meta value '' not found for peptide hit with sequence 'SETNDS(Phospho)S(Phospho)S(Phospho)GS(Phospho)QS(Phospho)HQDASAASSAPPR', charge 2, score 1.0)
```
For other quantms problems, I would submit in quantms

**Comment by jpfeuffer** [comment]
Hi! Cool project!

1. This looks indeed strange. It could be some weird error regarding the share directory where the modifications "database" is stored. Have you tried to run this step (or all) in containers to make sure their environment is separated?

2. Did you activate --write_protein_sequence while using PeptideIndexer?

3. You apparently did not specify which scores you want to switch, so it makes sense that it does not work. If you need it, depends on your settings. The problem is: a peptide/PSM can only have one main score. But different tools may need different scores. Percolator for example outputs three scores and you can specify which one will be the main score. ConsensusID needs a probability so you must use the percolator pep score. FDR works on any score but some scores are more discriminative than others.But using whatever comes out of ConsensusID should be fine. Proteomicslfq needs probabilities for inference again but this one is able to look for multiple score types. So I don't think you need an IDScoreSwitcher in your workflow.

Other things:

All search engine adapters should have an indexing step included these days. (Not sure about MSFragger). And even if they don't, you probably want to do the indexing right after search. Percolator needs that information already.

**Comment by liuxiawei** [comment]
Thank you for your prompt reply. I made adjustments based on your suggestions, but there are still some issues that persist.
**1. xtandem Error**
Modification not found is also existed, new Error occur: Error: Unexpected internal error (the given index was too large: 23 (size = 23))
I have tried on a new computer and in different conda environments and even remove all params, but the issue still persists.

**2. It solved with  "--write_protein_sequence "**
As you said,  `All search engine adapters should have an indexing step included these days. `, but I found it errors if omit the  `PeptideIndexer` step. So I decided to include the step, and now I can get the final table! Thanks!

**3. IDScoreSwitcher problem is still existed.**
I  specify the scores type as pep, the problem is still. I decided to omit the step. But it is still strange for me  .

----
And I have some other problem, I hope you can help me answer these questions. Thank you!

1.What is the difference of ProteomicsLFQ pipe,  ProteinQuantifier pipe, and Fido pipe ？ How to judge when to use it ? 
2. Could the abundance of ProteomicsLFQ result be used directly in research?

**Comment by jpfeuffer** [comment]
1. I never saw this problem and have no explanation. You have to:
- wait for input from others
- try containers
- double-check your command line for weird whitespaces or newlines

3. I need to know which score you want to switch and need to see the new error. As I said, if it is just for ProteomicsLFQ you do not need to switch.


New 1.
- Fido is not supported anymore
- ProteinQuantifier only quantifies proteins based on peptides, ProteomicsLFQ contains ProteinQuantifier but also does feature finding, alignment, peptide quantification and inference. See its documentation.

New 2.
What kind of research? It's a simple top3 quantification like many software packages do.

**Comment by liuxiawei** [comment]
Thank you for your response! I would like to skipped switch score. And I want to assess the differences in protein abundance between different samples from various LFQ experiments sourced from PRIDE. Can I directly compare the abundance results after normalize them ?

**Comment by jpfeuffer** [comment]
Ok! Does it currently work without switching scores or do you have an error? If there is no error, skipping should be fine.

Yes, you could use it this way but you have to make sure that only comparable experiments are processed together in one run of the pipeline (for alignment etc.).
Also normalization across different experiments is not always straightforward but can be tried.

**Comment by liuxiawei** [comment]
Thank you for your enthusiastic support and assistance. I will continue using OpenMS for my research and hope to contribute to the community!
