### ISSUE TITLE
Move CWL outputs to own build subfolder

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7261]
I think the root build folder is not the best place for this. I regularly lose overview over my build artifacts among those hundreds of files.

**Comment by timosachsenberg** [comment]
Agree.
Also I think we whould have a way to warn if there are cwls in the source folder that are not generated in the build folder. E.g. because a tool got removed

**Comment by cbielow** [comment]
do you mean this:
https://github.com/OpenMS/OpenMS/pull/6156/files#diff-ea1e6fb46d8eb225471d5345d95a1b5fc9e6919359c904f8d5c3e277f9372942R34

should be easy to fix

**Comment by cbielow** [comment]
> Agree. Also I think we whould have a way to warn if there are cwls in the source folder that are not generated in the build folder. E.g. because a tool got removed

yeah, there is a comment in the PR #6156, which never got addressed unfortunately.

**Comment by timosachsenberg** [comment]
@SGSSGene

**Comment by timosachsenberg** [comment]
Create a cwl build subfolder here and copy it here?
https://github.com/OpenMS/OpenMS/blob/develop/cmake/cwl_generation.cmake#L30

**Comment by jpfeuffer** [comment]
I'm not sure. This kind of looks ok.
Maybe it's the tests in line 34?

**Comment by jpfeuffer** [comment]
Am I understanding it correctly that it produces two cwl files with the same command, just to different outputs folders, to compare them afterwards?
This does not sound like a meaningful test anyways.

**Comment by timosachsenberg** [comment]
@SGSSGene @mr-c any insight why this is done this way?

**Comment by SGSSGene** [comment]
Yes, we can't recall any specific reasons, here is an alternative: https://github.com/OpenMS/OpenMS/pull/7275
