### ISSUE TITLE
Is there an elegant way to present the ProteomicsLFQ results?

### ISSUE THREAD

**Issue by liuxiawei** [OpenMS/OpenMS#7276]
I have processed 6 files simultaneously using OpenMS, and the resulting output in "out.mzTab" shows as 
protein_abundance_assay[1] 
protein_abundance_assay[2] 
protein_abundance_assay[3] 
protein_abundance_assay[4] 
protein_abundance_assay[5] 
protein_abundance_assay[6]
. 

What changes should I make to improve its readability and distinguishability?

**Comment by jpfeuffer** [comment]
Hi! According to the mztab standard (https://github.com/HUPO-PSI/mzTab)
you can look up the meaning of the assays in the metadata header.

You can read mztab with e.g. pyteomics or just simply grep the subtables and read it with any csv reader.

You can try pmultiqc (https://github.com/bigbio/pmultiqc) to visualize the results in a report but I'm afraid that you might need more information than just the mztab for a full report.

**Comment by liuxiawei** [comment]
Thank you so much, I was foolish enough to forget the information I had already seen. I apologize for that.
