### ISSUE TITLE
After building pyopenms, ctest failed, although importing pyopenms worked well, 

### ISSUE THREAD

**Issue by JKVISION1101** [OpenMS/OpenMS#7281]
Hi OpenMS teams. 

I built pyopenms successfully in my windows laptop.

and i did `ctest -R pyopenms` in the [build folder].

There are 24 out of 26 tests  failed.

---------------------------------------------------------
However, import pyopenms did very well without error.

I made pytest.py file( which only contain "import pyopenms print("comleted")") in the [build folder]/PyOpenMS.

and excute pytest.py file in the python and it run very well.

and i also tested

`import pyopenms as oms
tsg = oms.TheoreticalSpectrumGenerator()
spec1 = oms.MSSpectrum()
peptide = oms.AASequence.fromString("DFPIANGER")
p = oms.Param()
p.setValue("add_b_ions", "false")
p.setValue("add_metainfo", "true")
tsg.setParameters(p)
tsg.getSpectrum(spec1, peptide, 1, 1)  # charge range 1:1
print("Spectrum 1 of", peptide, "has", spec1.size(), "peaks.")
for ion, peak in zip(spec1.getStringDataArrays()[0], spec1):
    print(ion.decode(), "is generated at m/z", peak.getMZ())` 

this code is from https://pyopenms.readthedocs.io/en/latest/user_guide/fragment_spectrum_generation.html

and it also run very well.

-------------------------------------------

in this situation, is it okay to proceed pyopenms wrapping project or should i execute all the tests (ctest) and return with all tests passing.

Happy new year.

Jaekwan Kim  in korea.

**Comment by jpfeuffer** [comment]
Hi and Happy new year! What's the error when you run `ctest -R pyopenms -V`? And where exactly in the build folder do you run it from?

**Comment by JKVISION1101** [comment]
@jpfeuffer 



Hi, this is error report when i run  `ctest -R pyopenms -C Release --rerun-failed
--output-on-failure`

[ctest error.txt](https://github.com/OpenMS/OpenMS/files/13842747/ctest.error.txt)

and ctest was performed in the same folder which cmake was done.

In my case, `C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development_2`

this folder I did cmake `cmake -D OPENMS_CONTRIB_LIBS=C:\Users\qlcsk\Desktop\jkvision\openms\openms_development\contrib_build -D CMAKE_PREFIX_PATH=C:\Qt\5.15.2\msvc2019_64 -G "Visual Studio 16 2019" -A x64 -T host=x64 C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\OpenMS -DPYTHON_EXECUTABLE:FILEPATH="C:\Users\qlcsk\AppData\Local\Programs\Python\Python310\python.exe" -DPYOPENMS=ON`

and then I built pyopenms in the Visual studio UI.

and then I ctest in the `C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development_2`

----------------------------------------------


Jaekwan Kim

**Comment by jpfeuffer** [comment]
Can you try to run ctest from the pyOpenMS subdirectory?
`C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development_2\pyOpenMS`

**Comment by jpfeuffer** [comment]
Fixed in the PR above. You can try to make the changes yourself and try again.

**Comment by JKVISION1101** [comment]
@jpfeuffer 


I run ctest in the C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development_2\pyOpenMS. 
following what you told me to do.


and the message 

`Test project C:/Users/qlcsk/Desktop/jkvision/openms/pyFLASHDeconv/pyopenms_development_2/pyOpenMS
No tests were found!!!` came out.

I made the changes of CMakeLists.txt file in the pyopenms folder.
[CMakeLists.txt](https://github.com/OpenMS/OpenMS/files/13848761/CMakeLists.txt)


however, the same result came out. 

If I did wrong, please tell me. 

Thank you.

**Comment by jpfeuffer** [comment]
You will need to re-configure first with `cmake .` for ctest to pick it up.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

I did `cmake .` in the folder `C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development_2` where i run cmake before.

and, i I built target pyopenms in the Visual studio UI.

I ran ctest `ctest -R pyopenms` in the pyOpenMS subdirectory `C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development_2\pyOpenMS`

However `Test project C:/Users/qlcsk/Desktop/jkvision/openms/pyFLASHDeconv/pyopenms_development_2/pyOpenMS
No tests were found!!!`

this message came out. 


[CMakeLists.txt](https://github.com/OpenMS/OpenMS/files/13855311/CMakeLists.txt)
This is CMakeList.txt file which i made changed following what you did.
this file directory is [OpenMS source file folder]/[src]/[pyOpenMS].

**Comment by jpfeuffer** [comment]
In theory, after the changes it should work from the normal build folder. That was only a potential suggestion to try.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

I execute all the tests (ctest) and return with all tests passing.

`C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development_2>ctest -R pyopenms -C release`


Test project C:/Users/qlcsk/Desktop/jkvision/openms/pyFLASHDeconv/pyopenms_development_2
    Start 305: test_pyopenms_unittests
 1/26 Test #305: test_pyopenms_unittests ....................................   Passed   12.40 sec
      Start 306: pyopenms_unittest_test000.py
 2/26 Test #306: pyopenms_unittest_test000.py ...............................   Passed    3.26 sec
      Start 307: pyopenms_unittest_test_tutorial.py
 3/26 Test #307: pyopenms_unittest_test_tutorial.py .........................   Passed    1.33 sec
      Start 308: pyopenms_unittest_test_BaselineFiltering.py
 4/26 Test #308: pyopenms_unittest_test_BaselineFiltering.py ................   Passed    1.26 sec
      Start 309: pyopenms_unittest_test_ChromatogramExtractor.py
 5/26 Test #309: pyopenms_unittest_test_ChromatogramExtractor.py ............   Passed    1.35 sec
      Start 310: pyopenms_unittest_test_ChromatogramExtractorAlgorithm.py
 6/26 Test #310: pyopenms_unittest_test_ChromatogramExtractorAlgorithm.py ...   Passed    1.22 sec
      Start 311: pyopenms_unittest_test_Convexhull.py
 7/26 Test #311: pyopenms_unittest_test_Convexhull.py .......................   Passed    0.99 sec
      Start 312: pyopenms_unittest_testCVTermList.py
 8/26 Test #312: pyopenms_unittest_testCVTermList.py ........................   Passed    0.98 sec
      Start 313: pyopenms_unittest_test_DIAScoring.py
 9/26 Test #313: pyopenms_unittest_test_DIAScoring.py .......................   Passed    1.08 sec
      Start 314: pyopenms_unittest_test_FileIO.py
10/26 Test #314: pyopenms_unittest_test_FileIO.py ...........................   Passed    1.30 sec
      Start 315: pyopenms_unittest_test_Isobaric_Quantitation.py
11/26 Test #315: pyopenms_unittest_test_Isobaric_Quantitation.py ............   Passed    1.02 sec
      Start 316: pyopenms_unittest_testLightTargetedExperiment.py
12/26 Test #316: pyopenms_unittest_testLightTargetedExperiment.py ...........   Passed    1.06 sec
      Start 317: pyopenms_unittest_test_MRMFeatureFinderScoring.py
13/26 Test #317: pyopenms_unittest_test_MRMFeatureFinderScoring.py ..........   Passed    1.47 sec
      Start 318: pyopenms_unittest_test_MSNumpressCoder.py
14/26 Test #318: pyopenms_unittest_test_MSNumpressCoder.py ..................   Passed    1.07 sec
      Start 319: pyopenms_unittest_test_MSSpectrumAndRichSpectrum.py
15/26 Test #319: pyopenms_unittest_test_MSSpectrumAndRichSpectrum.py ........   Passed    0.96 sec
      Start 320: pyopenms_unittest_test_OpenSwathDataStructures.py
16/26 Test #320: pyopenms_unittest_test_OpenSwathDataStructures.py ..........   Passed    1.11 sec
      Start 321: pyopenms_unittest_test_Smoothing.py
17/26 Test #321: pyopenms_unittest_test_Smoothing.py ........................   Passed    1.17 sec
      Start 322: pyopenms_unittest_testSpecialCases.py
18/26 Test #322: pyopenms_unittest_testSpecialCases.py ......................   Passed    1.01 sec
      Start 323: pyopenms_unittest_test_SpectraFilter.py
19/26 Test #323: pyopenms_unittest_test_SpectraFilter.py ....................   Passed    4.68 sec
      Start 324: pyopenms_unittest_test_SpectrumAccessOpenMS.py
20/26 Test #324: pyopenms_unittest_test_SpectrumAccessOpenMS.py .............   Passed    1.21 sec
      Start 325: pyopenms_unittest_test_TraML.py
21/26 Test #325: pyopenms_unittest_test_TraML.py ............................   Passed    1.05 sec
      Start 326: pyopenms_unittest_test_MzMLConsumer.py
22/26 Test #326: pyopenms_unittest_test_MzMLConsumer.py .....................   Passed    1.22 sec
      Start 327: pyopenms_unittest_test_MzXMLConsumer.py
23/26 Test #327: pyopenms_unittest_test_MzXMLConsumer.py ....................   Passed    1.02 sec
      Start 328: pyopenms_unittest_test_AcquisitionInfo.py
24/26 Test #328: pyopenms_unittest_test_AcquisitionInfo.py ..................   Passed    1.13 sec
      Start 329: pyopenms_integrationtest_test_MRMRTNormalizer.py
25/26 Test #329: pyopenms_integrationtest_test_MRMRTNormalizer.py ...........   Passed    1.47 sec
      Start 330: pyopenms_test_memoryleaktests
26/26 Test #330: pyopenms_test_memoryleaktests ..............................   Passed   25.15 sec

100% tests passed, 0 tests failed out of 26

Total Test time (real) =  71.39 sec


This is result.

I did what you suggested that it should be run in the normal build folder.
`C:/Users/qlcsk/Desktop/jkvision/openms/pyFLASHDeconv/pyopenms_development_2`
not pyopenms subdirectory.

and i did  `ctest -R pyopenms -C release` not `ctest -R pyopenms` (this is what you suggested before for me.)
https://github.com/OpenMS/OpenMS/issues/6855


Thank you for your suggestion.

Have a good day.

**Comment by jpfeuffer** [comment]
Cool. Thanks for testing. Have a nice day, too!
This issue will close when the PR is merged.
