### ISSUE TITLE
When making pxd file for wrapping class, question about cimport.

### ISSUE THREAD

**Issue by JKVISION1101** [OpenMS/OpenMS#7283]
Hi, I am Jaekwan Kim.

I am trying to wrap run function method in the FLASHDeconvAlgorithm.h and .cpp file.

So I am reading the pyopenms documentation.

https://pyopenms.readthedocs.io/en/latest/community/wrapping_workflows_new_classes.html

In the documentation, It said that cimport should be used not import.

**First question is that can i cimport only pxd file in the OpenMS\src\pyOpenMS\pxds folder?**

------------------------------------------------------------
In my case, FLASHDeconvAlgorithm.h and .cpp file have many #includes preprocessor directives which doesn't have pxd file.

For example,

FLASHDeconvAlgorithm.h have these include preprocessor which don't have pxd file.

`#include <OpenMS/ANALYSIS/TOPDOWN/DeconvolvedSpectrum.h>
#include <OpenMS/ANALYSIS/TOPDOWN/FLASHDeconvHelperStructs.h>
#include <OpenMS/ANALYSIS/TOPDOWN/PeakGroup.h>
#include <OpenMS/ANALYSIS/TOPDOWN/SpectralDeconvolution.h>`

**In this case, should i make pxd files of these files (DeconvolvedSpectrum FLASHDeconvHelperStructs etc..) first? and then make pxd file of FLASHDeconvAlgorithm?**

**Comment by jpfeuffer** [comment]
Hi @JKVISION1101 
Yes you can only reference other pxds in a pxd.
If you need to wrap other .h files in a .pxd depends on if the functions that you want to wrap in your initial pxd, are using types/classes/objects in their public interface.
I would suggest to only wrap the most important/useful functions and then go down from there.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

you mean If the function which i want to wrap is using other types/classes/objects, I should wrap other types/classes/objects .h files first?

**Comment by JKVISION1101** [comment]
@jpfeuffer 

I will wrap most useful classes .h file first.

after than, will wrap target .h file

Thank you for suggestion. 

I will close this issue.

**Comment by jpfeuffer** [comment]
I actually meant it a bit differently:

Try to wrap the most useful functions and classes in the target.h.
Then if and only if a dependency is missing, also wrap the dependency.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

I got it Thank you.

I will try to wrap classes in the target first

and then I will wrap the class that the compiler said needs to be wrapped.

Your suggestion will save time so much.

Thank you.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

I succeeded in wrapping the FLASHDeconvHelperStructs. (my target is FLASHDeconvAlgorithm, however, i tested it first as i made FLASHDeconvHelperStructs pxd file  before)

and i can use this class in the pyopenms.
![image](https://github.com/OpenMS/OpenMS/assets/120628409/c3ea24a9-6af0-4892-9cc6-3ffb98db2bdc)



Thank you so much for your suggestion.
