### ISSUE TITLE
when cythonize,  No such file or directory error (wrapping class for pyopenms)

### ISSUE THREAD

**Issue by JKVISION1101** [OpenMS/OpenMS#7285]
Hello.

I am trying to wrap run method of FLASHDeconvAlgorithm.h.

before wrapping that method, I am trying to wrap FLASHDeconvHelperStructs.h first.

as i am beginner, i referenced two documentation.

https://github.com/OpenMS/autowrap/blob/master/docs/README.md
https://pyopenms.readthedocs.io/en/latest/community/wrapping_workflows_new_classes.html

--------------------------------------------
First, i made pxd file of FLASHDeconvHelperStructs.h.
[FLASHDeconvHelperStructs.txt](https://github.com/OpenMS/OpenMS/files/13868259/FLASHDeconvHelperStructs.txt)
(as uploading problem, i changed pxd extension to the txt extenstion)

-----------------------------------------
Second, autowrap step
`autowrap --out py_FLASHDeconvHelperStructs.pyx FLASHDeconvHelperStructs.pxd`

and it succeeded.

autowrap made 3files (pyx, pyi, cpp file)

---------------------------------------
Third. cythonize step.( I failed at this step)
[setup.txt](https://github.com/OpenMS/OpenMS/files/13868289/setup.txt)
(as uploading problem, i changed py extension to the txt extenstion)

when i run `python setup.py build_ext --inplace`

this error came out.
`py_FLASHDeconvHelperStructs.cpp(1243): fatal error C1083: Cannot open include file: OpenMS/ANALYSIS/TOPDOWN/FLASHDeconvHelperStructs.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
`
I think relative path "OpenMS/ANALYSIS/TOPDOWN/FLASHDeconvHelperStructs.h" was not 
recognized...

I think this problem occured as i created a separate folder to work in not in the openms folder.

Could you tell me which folder of file should i work on and how to solve this probelm?

Thank you all.

**Comment by jpfeuffer** [comment]
I would suggest working with the cmake workflow that is already in-place.
It is a bit slower because it will compile whole pyopenms but it is quite hard to separate only the things you need.

That means, add your pxd, delete the pyopenms.cpps, run `cmake --build build_folder  --target pyopenms` (or however you're currently building pyopenms). It will only perform the steps that changed.

**Comment by JKVISION1101** [comment]
@jpfeuffer 

I don't need second(autowrap), third(cythonize) step myself 

as cmake did these steps when i put target pxd file in the pxds folder?


---------------------------------------------------------

and also, you said that delete pyopenms.cpps.

you mean delete these pyopenms.cpps is in the [build folder]/pyOpenMS/pyopenms?

There is `_pyopenms_1~8.cpp` file.

**Comment by jpfeuffer** [comment]
Yes, CMake does all that for you.

Yes, you need to delete the `_pyopenms_1~8.cpp` files because otherwise CMake does not know that it has to regenerate them. (We do not have the pxd files as dependency, yet)

**Comment by JKVISION1101** [comment]
@jpfeuffer 

I succeeded in wrapping the FLASHDeconvHelperStructs. (my target is FLASHDeconvAlgorithm, however, i tested it first as i made FLASHDeconvHelperStructs pxd file  before)

and i can use this class in the pyopenms.
![image](https://github.com/OpenMS/OpenMS/assets/120628409/9bbb294f-4553-4fb1-ab13-01d6829b51f7)




Thank you so much for your suggestion.
