### ISSUE TITLE
Where is MSSimulator? 

### ISSUE THREAD

**Issue by Ministreliya131** [OpenMS/OpenMS#7289]
Greetings!

For my research work, it is necessary to select the optimal algorithm for processing proteomic data based on the results of simulated data. Previously, OpenMS supported the ability to simulate LC-MS/MS data using the MSSimulator module. Please tell me, are you going to update the MSSimulator?
If not, what software solutions for simulating raw proteomic data are more relevant now?

I hope for a quick reply

Kind regards,
Ann

**Comment by timosachsenberg** [comment]
Dear @Ministreliya131 the MSSimulator in OpenMS was not updated for a long time and removed it in one of the newer releases. You still can use it using one of our older OpenMS versions https://abibuilder.cs.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/2.9.1/

I don't know which one is currently the most suitable MS simulator right now and think this is a great question to ask in the CompMS (the community for computational mass spectrometry) slack channel. If you write me a short email I can share the invite link (see email on https://kohlbacherlab.org/teams/timo-sachsenberg/ )
Best,
Timo

**Comment by Ministreliya131** [comment]
Thank you very much!
I'll be in touch soon!

Best regards,
Ann
