### ISSUE TITLE
Fix Windows installer's extra Dll's from GHA

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#7290]
see https://discourse.cmake.org/t/cpack-adds-weird-dlls-to-the-installer/9667

**Comment by jpfeuffer** [comment]
Just for reference, the blacklist is here:
https://github.com/OpenMS/OpenMS/blob/60e2905a7571d7b6a479dcd69141dfd2ea220b66/cmake/package_general.cmake#L72

I would be surprised if CMake has a solution for that. IIRC there are multiple requests about that already.
You can use a regex based on file location, e.g., system32 or wherever those come from.

**Comment by jpfeuffer** [comment]
E.g. https://discourse.cmake.org/t/get-runtime-dependencies-has-difficulties-with-windows-api-sets/1768/22
A lot of people request an EXCLUDE_SYSTEM_LIBS

**Comment by timosachsenberg** [comment]
I just got a report from an external user that "dll file names that seem to be missing; namely, dxgi.dll, Uxtheme.dll, d3d11.dll and WINNMM.dll. " from the github action installers.

**Comment by timosachsenberg** [comment]
So there are extra dlls and missing dlls?

**Comment by JeeH-K** [comment]
Adding to this issue, is there any chance that the NSIS problem from the Windows installer file(https://github.com/OpenMS/OpenMS/issues/7316) is related to this issue?

**Comment by JeeH-K** [comment]
The nightly installer file from Jan 24 was tested, and I confirmed it works (https://abibuilder.cs.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightlyGHA/). However, no nightly installer has been deployed since then. Could this lead us to answer some questions?

**Comment by jpfeuffer** [comment]
I don't know how to move forward with this.
If we leave them out, some people with maybe a bare minimum windows will not be able to run. Would be nice to know which parts/updates/software (Dx3D?) install those things.

I guess we need to make sure that everything is compiled with the same vs version?
https://stackoverflow.com/questions/65672356/what-is-cxxframehandler4-and-what-does-linker-error-unresolved-external-symbo

**Comment by cbielow** [comment]
> I just got a report from an external user that "dll file names that seem to be missing; namely, dxgi.dll, Uxtheme.dll, d3d11.dll and WINNMM.dll. " from the github action installers.

how is that possible? Those are the files that the GHA installer ships `extra`(!), which are not needed.
See our discord discussion:
![image](https://github.com/OpenMS/OpenMS/assets/6008722/9ed31d58-ce83-4dc4-be46-443012511caf)
https://discord.com/channels/832282841836159006/1174598643353915422/1178675638484344902

Removing/blacklisting them from the installer should fix the problem.
I tested on a bare Win10 and these Dlls were not required.

**Comment by timosachsenberg** [comment]
No clue but he also sent me the screenshots so I guess he is not making this up ;).

**Comment by jpfeuffer** [comment]
Windows (Update) Version differences?
Anyone tried in the Windows sandbox? I used to test it there.

https://learn.microsoft.com/de-de/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview

**Comment by cbielow** [comment]
> No clue but he also sent me the screenshots so I guess he is not making this up ;).

can you post it here?
upper/lowercase Dll names may be a thing (even though its NTFS...)

**Comment by timosachsenberg** [comment]
![error_installer](https://github.com/OpenMS/OpenMS/assets/5803621/7bd36406-e0ff-47f4-8229-7d2f31fed19d)
![image](https://github.com/OpenMS/OpenMS/assets/5803621/d2f3e5dc-6a1d-48db-ac1c-eb8819bffaff)
![image](https://github.com/OpenMS/OpenMS/assets/5803621/37d04fc0-b99a-437b-9227-cf340c59b832)
![image](https://github.com/OpenMS/OpenMS/assets/5803621/f0d39f6d-edcb-45e7-89a1-7e95eab4ea31)

**Comment by jpfeuffer** [comment]
Ah but that means the dlls are there and not working (as in this issue).
So the fix is and stays to remove them via the blacklist.

**Comment by timosachsenberg** [comment]
k will add
