### ISSUE TITLE
nightly merge action fails

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7309]
https://github.com/OpenMS/OpenMS/actions/runs/7605528354/job/20709928714

**Comment by poshul** [comment]
Hmm, it fails with a 'fatal: refusing to merge unrelated histories'. I've copied the merge mode "ff-only" from the Jenkins version. Any idea what the issue could be?

**Comment by timosachsenberg** [comment]
This usually indicates that histories differ. e.g. there was some rebasing or something going on (e.g., a push to nightly to trigger something) that led to the nightly not being fast forwarded to the current develop branch.

**Comment by jpfeuffer** [comment]
I agree with @poshul. Why should it work on Jenkins but not here? Both seem to do a merge --ff-only and github tells me, develop is only one commit ahead of nightly, so no divergence etc.

**Comment by jpfeuffer** [comment]
Of course it's a bug in the action. https://github.com/robotology/gh-action-nightly-merge/issues/10
Maybe just avoid actions for such a simple task.

**Comment by jpfeuffer** [comment]
Or, to use the action, checkout all commits in the beginning.

**Comment by poshul** [comment]
Looks to be fixed now via the expedient of just checking out all commits from develop.
