### ISSUE TITLE
MyriMatch adapter - N-terminal modifications

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#731]
Reported by Oliver Schilling on the mailing list, 2013-12-30:

I have now used the MyriMatch adapter for searches with fixed N-terminal peptidic modifications, i.e. every peptide has an N-terminal modification. The results are nice - but in contrast to the X! tandem adapter, the N-terminal modification is not reported.

Example tandem output: (Dimethyl)EADSAVHGAPR 
Example MyriMatch output: EADSAVHGAPR

In both cases, N-terminal dimethylation was a fixed modification so I suspect that the MM adapter “fails” to report N-terminal modifications. Could this be a minor bug?

**Comment by timosachsenberg** [comment]
sounds like this could be fixed by now.can anyone confirm?

**Comment by timosachsenberg** [comment]
was removed
