### ISSUE TITLE
folders in build archive no accessible

### ISSUE THREAD

**Issue by saassli21** [OpenMS/OpenMS#7312]
Hello,
I'm trying to test this tutorial : https://pyopenms.readthedocs.io/en/latest/user_guide/identification_accurate_mass.html
but I can't download the input folder : https://abibuilder.cs.uni-tuebingen.de/archive/openms/Tutorials/Example_Data/Metabolomics/
![image](https://github.com/OpenMS/OpenMS/assets/131655435/134c17ce-ba97-4d68-a29a-32a3fe1c34f8)

**Comment by timosachsenberg** [comment]
hi thanks! server is up running again. please reopen if this did not resolve your problem
