### ISSUE TITLE
MyriMatch adapter - missing protein IDs

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#732]
Reported by Oliver Schilling on the mailing list, 2014-02-17:

The Myrimatch adapter fails to report protein IDs. This is in contrast to the XTandem adapter. The “accessions” column in the output (through text-exporter) is empty for the MyriMatch adapter. In an identical pipeline for XTANdem, accessions are correctly reported. Would it be possible to fix this this bug?

**Comment by timosachsenberg** [comment]
do we want to deprecate MyriMatch in this release? it is basically not used anymore
