### ISSUE TITLE
SIRIUS output reader fails (SiriusMzTabWriter.read, CsiFingerIdMzTabWriter.read)

### ISSUE THREAD

**Issue by NilouJ** [OpenMS/OpenMS#7372]
## Issue Description

I've encountered an `IndexError: map::at: key not found` error while executing a Python script that integrates the OpenMS `SiriusAdapterAlgorithm` for processing mass spectrometry data. This error occurs during the reading of results with `SiriusMzTabWriter.read`. The expected behavior was for the script to complete successfully and generate output files with sirius report.mztab and formula identification.tsv. The issue seems to be related to accessing result data, suggesting a potential problem with result mapping or an unexpected data format.

## Code Snippet

```python
sirius_algo = oms.SiriusAdapterAlgorithm()
            sirius_algo_par = sirius_algo.getDefaults()
            sirius_algo_par.setValue("sirius:compound_timeout", 100)
            sirius_algo_par.setValue("preprocessing:filter_by_num_masstraces", 2)
            # Number of mass traces each feature has to have to be included
            sirius_algo_par.setValue("preprocessing:feature_only", "true")
            # Uses the feature information from in_fm_no_sub to reduce the search space to MS2
            sirius_algo_par.setValue("sirius:profile", "orbitrap")
            sirius_algo_par.setValue("sirius:db", "none")
            sirius_algo_par.setValue("sirius:ions_considered", "[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+")
            sirius_algo_par.setValue("sirius:elements_enforced", "CHN[15]OS[4]Cl[2]P[2]")
            sirius_algo_par.setValue("project:processors", 2)
            sirius_algo.setParameters(sirius_algo_par)
            fm_info = oms.FeatureMapping_FeatureMappingInfo()
            feature_mapping = oms.FeatureMapping_FeatureToMs2Indices()
            sirius_algo.preprocessingSirius(featureinfo,
                                            exp,
                                            fm_info,
                                            feature_mapping)
            sirius_algo.logFeatureSpectraNumber(featureinfo,
                                                feature_mapping,
                                                exp)
            msfile = oms.SiriusMSFile()
            debug_level = 3
            sirius_tmp = oms.SiriusTemporaryFileSystemObjects(debug_level)
            siriusstring = oms.String(sirius_tmp.getTmpMsFile())
            feature_only = sirius_algo.isFeatureOnly()
            isotope_pattern_iterations = sirius_algo.getIsotopePatternIterations()
            no_mt_info = sirius_algo.isNoMasstraceInfoIsotopePattern()
            compound_info = []
            msfile.store(exp,
                         oms.String(sirius_tmp.getTmpMsFile()),
                         feature_mapping,
                         feature_only,
                         isotope_pattern_iterations,
                         no_mt_info,
                         compound_info)
            out_csifingerid = os.path.join(path, "structures_" + os.path.basename(filename)[11:-5] + ".mzTab")
            executable = find_exec("/Applications/sirius.app/Contents/MacOS/", "sirius")
            subdirs = sirius_algo.callSiriusQProcess(oms.String(sirius_tmp.getTmpMsFile()),
                                                     oms.String(sirius_tmp.getTmpOutDir()),
                                                     oms.String(executable),
                                                     oms.String(out_csifingerid),
                                                     False)
            candidates = sirius_algo.getNumberOfSiriusCandidates()
            sirius_result = oms.MzTab()
            siriusfile = oms.MzTabFile()

            oms.SiriusMzTabWriter.read(subdirs,
                                       filename,
                                       candidates,
                                       sirius_result)

            csi_result = oms.MzTab()
            oms.CsiFingerIdMzTabWriter.read(subdirs,
                                            filename,
                                            sirius_algo.getNumberOfSiriusCandidates(),
                                            csi_result)
            oms.MzTabFile().store(out_csifingerid, csi_result)
```
            
            
## Output:

Number of features to be processed: 174
No MS1 spectrum for this precursor. Occurred 0 times.
1 spectra were skipped due to precursor charge below -1 and above +1.
Mono charge assumed and set to charge 1 with respect to current polarity 57 times.
2 features were skipped due to feature charge below -1 and above +1.
Executing command: /Applications/sirius.app/Contents/MacOS/sirius --noCite --processors=2 --input /private/var/folders/ny/8scj7qld1bd1cp804bslxjzh0000gq/T/20240215_113137_SCI-CJXY2FXWR3_51247_2.ms --project /private/var/folders/ny/8scj7qld1bd1cp804bslxjzh0000gq/T/20240215_113137_SCI-CJXY2FXWR3_51247_1/sirius_out --no-compression sirius --elements-enforced=CHN[15]OS[4]Cl[2]P[2] --profile=orbitrap --ions-considered=[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+ fingerprint structure write-summaries
Traceback (most recent call last):
  File "/Users/MQ10005295/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app.plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/MQ10005295/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app.plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/MQ10005295/Library/CloudStorage/OneDrive-MacquarieUniversity/Nilou/Galaxy/4_SIRIUS.py", line 111, in <module>
    oms.SiriusMzTabWriter.read(subdirs,
  File "pyopenms/_pyopenms_2.pyx", line 228, in pyopenms._pyopenms_2.__static_SiriusMzTabWriter_read
IndexError: map::at:  key not found

##### *** any possible problem/solution?

**Comment by axelwalter** [comment]
Hi @NilouJ 
We have removed SiriusAdapter and replaced it with SiriusExport recently.
Are you using pyopenms nightlies?
With pyopenms 3.1.0 your scripts should work as expected.

**Comment by jpfeuffer** [comment]
I assume an incompatible Sirius version is used, since it is called externally.

The only time .at is used in the code is when looking up columns in the Sirius output tsv.

So probably the expected columns are not the same.

https://github.com/OpenMS/OpenMS/blob/17a07f8bdf78e471a26e7869a33004fd046ec510/src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp#L153

Maybe the output is also empty or something.
In any case, you probably need to check the created Sirius workspace to see what's going on.

**Comment by axelwalter** [comment]
@jpfeuffer is right, the column names for ranks are slightly different in SIRIUS versions 4 ("rank") and 5 ("formulaRank").
Compatible versions are OpenMS 3.1 and SIRIUS 5.

**Comment by NilouJ** [comment]
@jpfeuffer yes, I see exactly the problem is difference in characters/spelling between the header columns in the tsv output of SIRIUS 5 (the version I used) and the reference code for MzTabWriter. @axelwalter I would try to downgrade both SIRIUS and OpenMS and try if it fixes the problem.

**Comment by NilouJ** [comment]
> @jpfeuffer is right, the column names for ranks are slightly different in SIRIUS versions 4 ("rank") and 5 ("formulaRank").
> Compatible versions are OpenMS 3.1 and SIRIUS 5.

Still the same error appears with pyopenms 3.1.0 and Sirius 5.8.6

**Comment by NilouJ** [comment]
> I assume an incompatible Sirius version is used, since it is called externally.
> 
> The only time .at is used in the code is when looking up columns in the Sirius output tsv.
> 
> So probably the expected columns are not the same.
> 
> https://github.com/OpenMS/OpenMS/blob/17a07f8bdf78e471a26e7869a33004fd046ec510/src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp#L153
> 
> Maybe the output is also empty or something. In any case, you probably need to check the created Sirius workspace to see what's going on.

yes, the tsv output has different number of header columns/keys and mismatched spelling compared to MzTabWriter source code

**Comment by axelwalter** [comment]
My bad, there were many changes recently I got confused when they happend. Just checked the release code for 3.1.0. It is looking for a "rank" column which is generated by Sirius 4. Does that work for you?

**Comment by NilouJ** [comment]
> My bad, there were many changes recently I got confused when they happend. Just checked the release code for 3.1.0. It is looking for a "rank" column which is generated by Sirius 4. Does that work for you?

@axelwalter , I have tried several versions of SIRIUS 4, the problem is that SIRIUS 4 does not produce any results for me (however the formatting is compatible output/reader). here are the execution commands produced by pyopenms:

SIRIUS 4.9.15

Executing command: /Applications/sirius-gui.app/Contents/MacOS/sirius --noCite --processors=2 --input /private/var/folders/ny/8scj7qld1bd1cp804bslxjzh0000gq/T/20240222_194816_SCI-CJXY2FXWR3_72867_2.ms --project /private/var/folders/ny/8scj7qld1bd1cp804bslxjzh0000gq/T/20240222_194816_SCI-CJXY2FXWR3_72867_1/sirius_out --no-compression sirius --elements-enforced=CHN[15]OS[4]Cl[2]P[2] --profile=orbitrap --ions-considered=[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+ fingerprint structure write-summaries


SIRIUS 5.8.6

Executing command: /Applications/sirius.app/Contents/MacOS/sirius --noCite --processors=2 --input /private/var/folders/ny/8scj7qld1bd1cp804bslxjzh0000gq/T/20240223_093607_SCI-CJXY2FXWR3_97169_2.ms --project /private/var/folders/ny/8scj7qld1bd1cp804bslxjzh0000gq/T/2
0240223_093607_SCI-CJXY2FXWR3_97169_1/sirius_out --no-compression sirius --elements-enforced=CHN[15]OS[4]Cl[2]P[2] --profile=orbitrap --ions-considered=[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+ fingerprint structure write-summaries


only SIRIUS 5.8.6 produces the results, a sample csv file attached (formula_identification.tsv).

[formula_identifications.csv](https://github.com/OpenMS/OpenMS/files/14380480/formula_identifications.csv)
[formula_identifications.csv](https://github.com/OpenMS/OpenMS/files/14380484/formula_identifications.csv)


even if I change the formulaRank to rank, I still get the map::at error!

**Comment by NilouJ** [comment]
new version of SIRIUS 6 works OK
