### ISSUE TITLE
Use v4 artifacts in GHA

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7373]
Just saw this:
https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/

Would be a nice to have and probably quick if they did not completely change the API.
Maybe they have glob download now?? That would simplify a lot.

**Comment by timosachsenberg** [comment]
Cool. Especially the ability to download from other workflow runs and repos seems useful.
Also worth to consider:
- Now, in v4, the artifact becomes immediately available in the UI and the API. Even better, the actions/upload-artifact action now has [outputs](https://github.com/actions/upload-artifact#outputs) for both the ID of the artifact, and the URL for the artifact. This allows for even more powerful workflows that use artifacts. For instance, you now have the ability to create an approval gate and inspect an artifact’s content manually via the UI before approving for a release. Artifact URLs can also be embedded using bots and comments in pull requests for easy sharing.
- Cross-run (or repository) downloads. The action to download artifacts has some new addons as well. In the [list of inputs](https://github.com/actions/download-artifact#inputs), we now have github-token, repository and run-id. Given a [properly scoped token](https://docs.github.com/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) with actions:read, artifacts can now be downloaded from other workflow runs and repositories. By default with no token specified, the action will only be able to download from the current workflow run and any previous run attempts.
- In v4, users lose the ability to upload to the same named artifact multiple times. Once an artifact is uploaded cannot be altered, and there cannot be multiple v4 artifacts with the same name, in the same workflow run. An example scenario where this would cause friction is a job matrix where multiple jobs would concurrently push uploads to the same artifact. In v4, this would cause an error. To make this scenario possible, artifacts can have the matrix attributes suffixed to the name, and then all the artifacts can be downloaded to the same directory.

**Comment by poshul** [comment]
I'd already gotten this into the ci-full. I'm working on getting it into the pyopenms-wheels action now.

**Comment by poshul** [comment]
PyOpenMS wheels is updated as well now.
