### ISSUE TITLE
GCC Flags

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#738]
There might be some gcc flags mentioned in this article of which we could also profit 

http://blog.httrack.com/blog/2014/03/09/what-are-your-gcc-flags/

specifically, we might want to look into `-fvisibility=hidden` to catch errors about not-exported symbols in Windows already in the travis builds. Maybe also `-Wl,--no-undefined` would be an option and finally, at some point, maybe `-Werror`

**Comment by hendrikweisser** [comment]
Has this been addressed in the meantime? Can the ticket be closed?
