### ISSUE TITLE
MacOS CI failing due to brew+GHA python conflict

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7398]
@poshul I remember you solved something regarding that already?

**Comment by poshul** [comment]
Yes. But I had thought it was permenantly solved, so I need to take another
look to see what broke. I'll try to get to this tomorrow afternoon.

Sam

On Thursday, March 14, 2024, Julianus Pfeuffer ***@***.***>
wrote:
> @poshul I remember you solved something regarding that already?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci3.googleusercontent.com/meips/ADKq_NZVcRIIvYUwIX2V3QWuJTtN-xEPQJ-FhbGdWnBWTASGnk3v1O8RiOCKlZL91ImNNKMOqjpPoRvkLzo_3p7nnctZuUQELQaj_w8N226E4lE2FdklPACsiXZ1k8hs28l_HhziLf95jRmfS5RtiSY-RGf3Akxsk2N8STcD7s_UGolu-8UBUW1TrxMTM7G7aYlEo9Qj90RDeaT-VXDr-oZlSbTwAL_gOv5f_tk8z8OA=s0-d-e1-ft#https://github.com/notifications/beacon/AABD3C4P4MJXALJL4E6RAMDYYFXYHA5CNFSM6AAAAABEVYKAF6WGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHIESUNNM.gif>Message
ID: ***@***.***>
