### ISSUE TITLE
pyopenms build failing in windows. (unresolved external symbol "__declspec(dllimport) public:)

### ISSUE THREAD

**Issue by JKVISION1101** [OpenMS/OpenMS#7416]
Hi.

When i tried to build pyopenms, error related with LINK came out.

Error said that OpenMS::AAindex::get...... has some problem.

below is all error message

`_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::getKHAG800101(char)" (__imp_?get
KHAG800101@AAIndex@OpenMS@@SAND@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_10getKHAG800101(struct __pyx_obj_8py
openms_11_pyopenms_1_AAIndex *,struct _object *)" (?__pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_10getKHAG800101@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_
1_AAIndex@@PEAU1@@Z) [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::getVASM830103(char)" (__imp_?get
VASM830103@AAIndex@OpenMS@@SAND@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_12getVASM830103(struct __pyx_obj_8py
openms_11_pyopenms_1_AAIndex *,struct _object *)" (?__pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_12getVASM830103@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_
1_AAIndex@@PEAU1@@Z) [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::getNADH010106(char)" (__imp_?get
NADH010106@AAIndex@OpenMS@@SAND@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_14getNADH010106(struct __pyx_obj_8py
openms_11_pyopenms_1_AAIndex *,struct _object *)" (?__pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_14getNADH010106@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_
1_AAIndex@@PEAU1@@Z) [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::getNADH010107(char)" (__imp_?get
NADH010107@AAIndex@OpenMS@@SAND@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_16getNADH010107(struct __pyx_obj_8py
openms_11_pyopenms_1_AAIndex *,struct _object *)" (?__pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_16getNADH010107@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_
1_AAIndex@@PEAU1@@Z) [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::getWILM950102(char)" (__imp_?get
WILM950102@AAIndex@OpenMS@@SAND@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_18getWILM950102(struct __pyx_obj_8py
openms_11_pyopenms_1_AAIndex *,struct _object *)" (?__pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_18getWILM950102@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_
1_AAIndex@@PEAU1@@Z) [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::getROBB760107(char)" (__imp_?get
ROBB760107@AAIndex@OpenMS@@SAND@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_20getROBB760107(struct __pyx_obj_8py
openms_11_pyopenms_1_AAIndex *,struct _object *)" (?__pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_20getROBB760107@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_
1_AAIndex@@PEAU1@@Z) [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::getOOBM850104(char)" (__imp_?get
OOBM850104@AAIndex@OpenMS@@SAND@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_22getOOBM850104(struct __pyx_obj_8py
openms_11_pyopenms_1_AAIndex *,struct _object *)" (?__pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_22getOOBM850104@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_
1_AAIndex@@PEAU1@@Z) [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::getFAUJ880111(char)" (__imp_?get
FAUJ880111@AAIndex@OpenMS@@SAND@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_24getFAUJ880111(struct __pyx_obj_8py
openms_11_pyopenms_1_AAIndex *,struct _object *)" (?__pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_24getFAUJ880111@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_
1_AAIndex@@PEAU1@@Z) [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::getFINA770101(char)" (__imp_?get
FINA770101@AAIndex@OpenMS@@SAND@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_26getFINA770101(struct __pyx_obj_8py
openms_11_pyopenms_1_AAIndex *,struct _object *)" (?__pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_26getFINA770101@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_
1_AAIndex@@PEAU1@@Z) [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::getARGP820102(char)" (__imp_?get
ARGP820102@AAIndex@OpenMS@@SAND@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_28getARGP820102(struct __pyx_obj_8py
openms_11_pyopenms_1_AAIndex *,struct _object *)" (?__pyx_pf_8pyopenms_11_pyopenms_1_7AAIndex_28getARGP820102@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_
1_AAIndex@@PEAU1@@Z) [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
_pyopenms_1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static double __cdecl OpenMS::AAIndex::calculateGB(class OpenMS::AASequ
ence const &,double)" (__imp_?calculateGB@AAIndex@OpenMS@@SANAEBVAASequence@2@N@Z) referenced in function "struct _object * __cdecl __pyx_pf_8pyopenms_11_pyopenms
_1_7AAIndex_30calculateGB(struct __pyx_obj_8pyopenms_11_pyopenms_1_AAIndex *,struct __pyx_obj_8pyopenms_11_pyopenms_1_AASequence *,double)" (?__pyx_pf_8pyopenms_1
1_pyopenms_1_7AAIndex_30calculateGB@@YAPEAU_object@@PEAU__pyx_obj_8pyopenms_11_pyopenms_1_AAIndex@@PEAU__pyx_obj_8pyopenms_11_pyopenms_1_AASequence@@N@Z) [C:\User
s\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]
C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\pyOpenMS\pyopenms\_pyopenms_1.cp310-win_amd64.pyd : fatal error LNK1120: 11 unresolved e
xternals [C:\Users\qlcsk\Desktop\jkvision\openms\pyFLASHDeconv\pyopenms_development\src\pyOpenMS\pyopenms_1.vcxproj]`

Thanks.

**Comment by jpfeuffer** [comment]
Should be fixed in #7424 by @cbielow

**Comment by JKVISION1101** [comment]
Thanks for the fixing the code!
