### ISSUE TITLE
pyopenms and nightly update CI broken

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7417]
pyopenms uses outdated contrib.
nightly update suffers from the fact that pushes from a workflow do not trigger other workflows.

**Comment by timosachsenberg** [comment]
contrib for macos and windows is currently down. maybe up again before easter
contrib for linux https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/pyopenms-wheels.yml#L280 seems to use our container ghcr.io/openms/contrib_manylinux2014:latest 
Will try to update with: https://github.com/OpenMS/contrib/actions/workflows/deploy-manylinux-docker.yml

**Comment by jpfeuffer** [comment]
You probably can get rid of contrib for pyopenms as well. Except for windows (unless a binary pkg manager is tested).
I hope the installation time is not too long.

**Comment by jpfeuffer** [comment]
Broken again. Probably due to IT infrastructure since Rsync fails.

**Comment by timosachsenberg** [comment]
I think this is fixed now?
