### ISSUE TITLE
Debian package download stalling

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7428]
Hi!

Unfortunately the 3.1.0 debian package is currently not downloadable. Stalls at 230 MB.
Since the official debian package is quite outdated, there is currently no way to run GUI apps on Debian without self-building.

**Comment by jpfeuffer** [comment]
Nightly packages stall at 183MB for me.

**Comment by poshul** [comment]
This is an issue with the Ceph storage that our IT infrastructure uses. They are working on rebuilding it now.

**Comment by poshul** [comment]
Ceph is back up (for now). Please re-open if you experience this again in the future.
