### ISSUE TITLE
question: feasible to update to newer manylinux? 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7434]
Do you think it is feasible to update from manylinux2014.
This could make life a bit easier regarding actions, packages, etc.
I don't recall the implications, e.g., would this break anything? I recall that we had this discussion before quite a while ago.
e.g., does this also affect the pyopenms documentation or conda stuff?

**Comment by timosachsenberg** [comment]
another issue:
python 3.12 support seems to be broken because a package "imp" was removed. @poshul do you have additional information e.g. from where this is imported?

**Comment by jpfeuffer** [comment]
Yes we can update to 2_28. But it will not help much. Coin is also not available on AlmaLinux 8. It would break things for users on a Linux with a glibc < 2.28.
There are finally some requests to have coin on EPEL9 but I am sure it will take a long long time: https://bugzilla.redhat.com/buglist.cgi?quicksearch=coin-or

I am not aware of the usage of an "imp" package.

**Comment by jpfeuffer** [comment]
Imp issue was because of a fixed "wheel" package version.
I think I updated manylinux.
