### ISSUE TITLE
What IDE do you recommend for developing and building openMS(C++) under macOS

### ISSUE THREAD

**Issue by suhande** [OpenMS/OpenMS#7494]
What IDE do you recommend for developing openMS(C++) under macOS

**Comment by jpfeuffer** [comment]
Hi @suhande 

I think both VSCode and JetBrains CLion are actively used by some of the developers.

In theory, any IDE should do. Of course, IDEs with CMake and LSP (e.g. for clang-analyzer) support might be preferable.
