### ISSUE TITLE
Wrong retention time values 

### ISSUE THREAD

**Issue by luca-annecchino** [OpenMS/OpenMS#7495]
Hello,

I am working on .mzML files converted from .raw files acquired on a Water’s QTOF.

When loading these files in python using the class MzMLFile() or OnDiscMSExperiment() the retention time values for each spectrum and for the TIC are much higher than what was experimentally observed and what is correctly shown in other software (i.e., Water’s MassLynx and Proteowizard).

All the retention time values seem to be around 30 times higher when opening the files with pyOpenMS. Any idea where the problem could be?

Thanks,

**Comment by jpfeuffer** [comment]
Hi Luca!

Could the ratio be 60 as in minutes vs seconds. Maybe 30 if windows are interpreted differently?
I don't recall which unit we enforce but it should be somewhere in the specification of the format.
