### ISSUE TITLE
How to select ETCID activation for a TRFP mzML file? 

### ISSUE THREAD

**Issue by rolivella** [OpenMS/OpenMS#7499]
Hello 

For instance, at my mzML converted using ThermoRawFileParser there's this activation: 

```xml
          <activation>
                <cvParam cvRef="MS" accession="MS:1000045" value="146.42219543457" name="collision energy" unitAccession="UO:0000266" unitName="electronvolt" unitCvRef="UO" />
                <cvParam cvRef="MS" accession="MS:1000598" value="" name="electron transfer dissociation" />
                <cvParam cvRef="MS" accession="MS:1002680" value="15" name="supplemental collision energy" unitAccession="UO:0000266" unitName="electronvolt" unitCvRef="UO" />
                <cvParam cvRef="MS" accession="MS:1002678" value="" name="supplemental beam-type collision-induced dissociation" />
              </activation>
```

If I want to select those `supplemental beam-type collision-induced dissociation` spectras, I would use `FileFilter` like this: 

`FileFilter -in QC03_2bf4293c4d1c8c891fab774cf973f7e9.mzML -spectra:select_activation "supplemental beam-type collision-induced dissociation" -out QC03_2bf4293c4d1c8c891fab774cf973f7e9_ETCID.mzML`

But I got: 

```
Invalid string parameter value 'supplemental beam-type collision-induced dissociation' for parameter 'select_activation' given! Valid values are: 'Collision-induced dissociation,Post-source decay,Plasma desorption,Surface-induced dissociation,Blackbody infrared radiative dissociation,Electron capture dissociation,Infrared multiphoton dissociation,Sustained off-resonance irradiation,High-energy collision-induced dissociation,Low-energy collision-induced dissociation,Photodissociation,Electron transfer dissociation,Pulsed q dissociation,trap-type collision-induced dissociation,beam-type collision-induced dissociation,in-source collision-induced dissociation,Bruker proprietary method'. Updating failed!
Parameters passed to 'FileFilter' are invalid. To prevent usage of wrong defaults, please update/fix the parameters!
```

It seems that the `supplemental beam-type collision-induced dissociation` is not in the list of valid values so what I can do? 

Thanks!

**Comment by timosachsenberg** [comment]
DONE: updated psi-ms obo in OpenMS https://github.com/OpenMS/OpenMS/pull/7500
TODO: check if supported in FileFilter

**Comment by timosachsenberg** [comment]
hmm might be a bug in TRFP
we seem to support etcid. See:
https://github.com/OpenMS/OpenMS/blob/595811c7c27a8115b79d9c8c6257bbd68257edea/src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp#L1788-L1795
Do you know why this is not annotated with this CV term?

**Comment by rolivella** [comment]
@timosachsenberg I don't know why is not annotated with this CV term, we should ask TRFP devs...

I believe that, overall, having controlled vocabulary (CV) terms is beneficial, but maintaining them is quite challenging. Due to this, I frequently encounter difficulties when using open source proteomics tools. It's something we should consider addressing! I mean, as a proteomics bioinformatics community.

**Comment by timosachsenberg** [comment]
can you ask - I can jump in if there are some OpenMS related questions? @rolivella maybe there is a good reason for it.
Agree, I think even seasoned devs sometimes get them wrong :)
But I guess if properly used it would have worked out of the box...

**Comment by caetera** [comment]
I would argue that both ways to describe supplemental activation are correct.
`MS:1003182` i.e. `Dissociation process combining electron-transfer dissociation (ETD) and collision-induced dissociation (CID)` and a combination of `MS:1000598` (`electron transfer dissociation`) and `MS:1002679` (`supplemental collision-induced dissociation`) are the same thing. 
It would be better if the vocabulary had only one way of _expressing_ a concept. Besides, neither of the terms marked as _obsolete_. Honestly, I did not know that `MS:1003182` even existed. Is there any way to see which version of PSI-MS it has been introduced in? 

TRFP follows along with Proteowizard, which uses a combination of terms (tested with relatively recent 3.0.24061).

**Comment by timosachsenberg** [comment]
hi @rolivella I added a quick fix to this PR https://github.com/OpenMS/OpenMS/pull/7512
that should allow filtering by:
"electron-transfer/collision-induced dissociation"
"electron-transfer/higher-energy collision dissociation"

**Comment by rolivella** [comment]
@timosachsenberg could you please remember me where can I find the last openms builds? Thank you

**Comment by timosachsenberg** [comment]
hi @rolivella sure: https://abibuilder.cs.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/
has our nightly builds.

**Comment by rolivella** [comment]
Thanks @timosachsenberg but I meant the docker/singularity images. Thanks.

**Comment by timosachsenberg** [comment]
Deploying them right now. They should show up here in a bit https://github.com/orgs/OpenMS/packages

**Comment by rolivella** [comment]
Sorry @timosachsenberg but I can't find it here: https://github.com/orgs/OpenMS/packages

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS/pkgs/container/openms-executables Maybe this one? Latest

**Comment by rolivella** [comment]
@timosachsenberg now I have it! 

However, after applying FileFilter for CID, for instance, I got only MS2 spectra. How can I prevent to remove the MS1? I tried a FileFilter with MS1 and then FileMerger with the MS2 with CID, but it puts all MS1 first and then all MS2 and I cannot do an identification search with this mzML...Thanks.

**Comment by timosachsenberg** [comment]
Ah that's a good point. Hmm can you try to remove the unwanted activation? -spectra:remove_activation <activation> 
I think this should then also keep the MS1

**Comment by rolivella** [comment]
@timosachsenberg this strategy works for CID and HCD but not for ETCID (and probably not for ETHCD). The problem is, for instance, in the filtered mzML I have this kind of activation: 

```xml
<activation>
	<cvParam cvRef="MS" accession="MS:1000598" name="electron transfer dissociation" />
	<cvParam cvRef="MS" accession="MS:1003182" name="electron transfer and collision-induced dissociation" />
	<cvParam cvRef="MS" accession="MS:1000045" name="collision energy" value="65.076530456542997" unitAccession="UO:0000266" unitName="electronvolt" unitCvRef="UO"/>
</activation>
```

Running FileInfo I get: 

```
Activation methods
    MS-Level 2 & ETD (Electron transfer dissociation): 6356
    MS-Level 2 & ETciD (Electron transfer and collision-induced dissociation): 6356
```

I want to remove "ETD (Electron transfer dissociation)" and only keep "ETciD (Electron transfer and collision-induced dissociation)" because some search engines does not like this configuration. But If try it, the FileFilter removes both ETD and ETCID. What can I do? Thanks.

**Comment by timosachsenberg** [comment]
That's why I hate these "two cv terms" for one thing...
I think we can do multiple things to solve this, but it requires some coding:
- add an option in FileFilter that only applies filters to spectra that have activation modes annotated (e.g., not MS1)
- use pyopenms (should be easy to adapt from the examples here: https://pyopenms.readthedocs.io/en/latest/user_guide/ms_data.html#filtering-mass-spectra-by-ms-level) if that is viable I can help with that 

@OpenMS/core any other ideas?

**Comment by rolivella** [comment]
@timosachsenberg any news? Thanks!

**Comment by caetera** [comment]
Just an update, I have opened the issue with PSI-MS people, and they seem to favor two CV representation.
https://github.com/HUPO-PSI/psi-ms-CV/issues/285
