### ISSUE TITLE
TOPPAS & SageAdapter

### ISSUE THREAD

**Issue by TheB1307** [OpenMS/OpenMS#7507]
Dear community
I am a new user for OpenMS and TOPPAS.
My goal is to use Sage (so the SageAdapter) to re-analyse proteomics data to find PTMs. 
I am struggeling in setting up the pathway. I tried with different parameter settings to run the algorithm but all the time it says that it was created an empty list as output.
I also tried to change the batch-size but this is also not working. 
In TOPPAS I also don't know how to use the '--help' tool. 
I think, I am totally lost. 
Is there anyone who could help me? How I use the SageAdapter to get useful parameters?
Have a great weekend
TheB

**Comment by TheB1307** [comment]
FYI: This is the error I get:

15:18:37 NOTICE: SageAdapter of node #5 started. Processing ...
Found Sage version string: Version 0.14.6
Creating temp file name...
Creating Sage config file...C:/Users/AppData/Local/Temp/20240614_151838_Poste-LSMBO-30_1052_1.json
Sage command line: Y:\sage.exe C:/Users/AppData/Local/Temp/20240614_151838_Poste-LSMBO-30_1052_1.json -f C:\Users\AppData\Local\Temp\20240613_114741_23380_1\SageAdapter_workflow_20240613\004_DecoyDatabase\out\uniprot-human-reviwed-withisos-trypsin-june-2024.fasta -o C:\Users\AppData\Local\Temp\20240613_114741_23380_1\SageAdapter_workflow_20240613\005_SageAdapter\out --write-pin Y:\Test data_Cohort transversal serie 1 and 2\Raw-files\N19453LMU.mzML
Reading sage output...
Using prefix decoy string 'DECOY_'
Peptide identification engine: SAGE
Enzyme: Trypsin
Warning: An empty set of peptide identifications was provided. Output will be empty as well.
SageAdapter took 25.58 s (wall), 3.92 s (CPU), 0.39 s (system), 3.53 s (user); Peak Memory Usage: 101 MB.

**Comment by timosachsenberg** [comment]
Your result did not seem to yield any peptide identifications.
Can you try to run sage (without OpenMS) from the command line and see if it did not result in any hits? We are running it quite successfully here, so I guess that there might be an issue with the search settings or the fasta database.

**Comment by TheB1307** [comment]
Thank you for your answer! I had a closer look again at the experiments and realized that they were measured in targeted mode. I checked a example file in DDA mode and then it worked. I am sorry for that...
