### ISSUE TITLE
Support or avoid numpy 2.0 in pyopenms

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7511]
https://github.com/OpenMS/OpenMS/actions/runs/9546642799/job/26309975306

**Comment by jpfeuffer** [comment]
Probably setup.py needs to be made configurable by cmake and the numpy dependency adapted based on which numpy version was found during build time.

https://github.com/OpenMS/OpenMS/blob/f1cff0e159d5c978ac8bb69126a71ffa601e1d14/src/pyOpenMS/setup.py#L257

**Comment by timosachsenberg** [comment]
@matteopilz can you give this a shot? not sure if chatgpt is hallucinating but could work in principle ;)  https://chatgpt.com/share/c9ae625b-cf1a-423b-a311-d2a1256ecac0

maybe add the check for the version here? https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/CMakeLists.txt#L239

**Comment by jpfeuffer** [comment]
As a first step, one could just not support numpy 2. Therefore make sure that during build only numpy <2 is installed and that setup.py is restricted to <2.

**Comment by timosachsenberg** [comment]
ok change in setup.py
```
pip install numpy<2.0
```
and
```
	install_requires=[
          'numpy<2.0',
          'pandas',
          'matplotlib>=3.5'
    ],
```
and as well in all places here: https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/pyopenms-wheels.yml

**Comment by matteopilz** [comment]
https://github.com/OpenMS/OpenMS/pull/7515

**Comment by timosachsenberg** [comment]
I think some part is not correct: /Users/runner/work/_temp/a9072bd9-9ab2-468b-a873-ef501f2fe837.sh: line 32: **=1.26.4**: No such file or directory

**Comment by mr-c** [comment]
Yep, all of those `numpy<2.0` need to be inside quotes to not be considered a input redirection

**Comment by timosachsenberg** [comment]
Thanks. I think Matteo was able to fix it. seems to run now...
