### ISSUE TITLE
Trouble copying MSVC runtime libraries as part of build / package process

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7528]
Hi,
in our streamlit applications we need to copy all windows dependencies (msvcrt etc.) into a build folder to package it using python.
We figured that e.g., package_nsis does this via some cmake includes.
@jpfeuffer any idea what the right way would be to implement that?
One idea we had was to have a "copy/install" or "portable" package type (not sure if that makes sense):
https://github.com/t0mdavid-m/OpenMS/blob/d7bf59024390675b48c9524d515a5752a6413a78/CMakeLists.txt#L491C1-L512C8

that uses cmake to get those dlls and copy them to the build folder (or some install folder).

Or simply speaking: is it possible to create an install target / step in cmake that just copies everything instead of creating an archive like the other packaging stuff.

**Comment by jpfeuffer** [comment]
You can set the install folder and then install the needed components with cmake --install COMPONENT. As we do in conda build.sh.

**Comment by timosachsenberg** [comment]
ah cool and this should also work with the redistributables?
because we use include(InstallRequiredSystemLibraries) there

**Comment by timosachsenberg** [comment]
@t0mdavid-m  https://github.com/bioconda/bioconda-recipes/blob/master/recipes/openms-meta/build.sh

**Comment by jpfeuffer** [comment]
You might need to set CMAKE_INSTALL_SYSTEM_RUNTIME_COMPONENT
https://cmake.org/cmake/help/latest/module/InstallRequiredSystemLibraries.html

to get an installable component just for the dependencies.

**Comment by jpfeuffer** [comment]
It might make sense to double-check the necessity of InstallRequiredSystemLibraries. We also install dependencies here:
https://github.com/OpenMS/OpenMS/blob/27a46abba2dedf9ebc9aeb826074faa030297a09/cmake/package_general.cmake#L83
which is I think more complete since it iterates actively through all runtime linked libraries of all binaries and libraries.

**Comment by t0mdavid-m** [comment]
I figured out you can just set `CPACK_GENERATOR` to `ZIP` to create a zip file, which contains the binaries including all dependencies. This could be used for portable installation and enabled via an environment variable. I am currently preparing a PR, which should make this more clear. 

In a next step I will also evaluate whether `include(InstallRequiredSystemLibraries)` is still needed.

Thanks a lot for your quick reponses! This was a tremendous help for me in figuring out how the packaging is done.
