### ISSUE TITLE
Comet v2024.01.0 gives empty results

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#7531]
Do NOT use the latest COMET, since it will not yield any PSMs when wrapped using CometAdapter.

Reason: Comet introduces two new parameters for fragment mass tolerance:

From their release notes:
"""
Add the parameters “[peptide_mass_tolerance_lower](https://uwpr.github.io/Comet/parameters/parameters_202401
/peptide_mass_tolerance_lower.html)” and “[peptide_mass_tolerance_upper](https://uwpr.github.io/Comet/parameters
/parameters_202401/peptide_mass_tolerance_upper.html)” to allow the specification of non-symmetric precursor mass 
tolerances. This means that “peptide_mass_tolerance” is retired and you should start with a fresh comet.params with this release
 and not re-use an old parameters file.
"""

We currently only write the outdated 'peptide_mass_tolerance' which Comet simply ignores (correction: does not handle correctly).
Omitting the two new parameters is also silently ignored by Comet and leads to empty results - at least for this dataset I have at hand.

Fix:
 - determine comet version and either add the old, or the two new parameters. We probably could also extend our INI to allow for asymetric mass tolerances, but this would require more code (and error handling), in case an older Comet version is installed which does not support this feature. Also, this would mean that common parameter names between adapters get out of sync a bit.

**Comment by cbielow** [comment]
after some debugging with Comet, it's a bug on their side.
https://github.com/UWPR/Comet/issues/60

There are other issues with v2024.01 (see https://github.com/UWPR/Comet/issues/63 etc). So do not use it - even after our CometAdapter was updated we should warn against using this version.

**Comment by timosachsenberg** [comment]
just to summarize what needs to be done for all future versions of comet. We de need to use the peptide_mass_tolerance_upper/lower instead? And as a temporary workaround (e.g., if we don't want to change our adapter parameter too much) we would add current **precursor**_mass_tolerance for both parameters (or 0.5 of them?)?

**Comment by cbielow** [comment]
> We de need to use the peptide_mass_tolerance_upper/lower instead?

Until the backwards compatibility is removed, we are fine. After that, yes, we need to use the new parameters.

>  And as a temporary workaround (e.g., if we don't want to change our adapter parameter too much) we would add current precursor_mass_tolerance for both parameters (or 0.5 of them?)?

Not sure I understand. Can you elaborate?

**Comment by timosachsenberg** [comment]
Just meant if we don't want to change the OpenMS adapter parameter right now (e.g., to not break workflows) we could pass a single OpenMS tolerance parameter to the two new comet upper/lower parameters. Not sure if having different lower + upper tolerances makes a huge difference in practice (regarding results)

**Comment by cbielow** [comment]
ah, sure. This is how it it currently implemented in #7540
