### ISSUE TITLE
require boost 1.78?

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#7542]
when compiling OpenMS with Boost 1.74 (default on our Debian), I get
```
.../openms/src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp:757:34: error: ‘OpenMS::IdentificationDataInternal::AppliedProcessingSteps’ {aka ‘class boost::multi_index::multi_index_container<OpenMS::Identificati
onDataInternal::AppliedProcessingStep, boost::multi_index::indexed_by<boost::multi_index::sequenced<>, boost::multi_index::ordered_unique<boost::multi_index::member<OpenMS::IdentificationDataInternal::AppliedProcessingStep, std::optional
<OpenMS::IdentificationDataInternal::IteratorWrapper<std::_Rb_tree_const_iterator<OpenMS::IdentificationDataInternal::ProcessingStep> > >, &OpenMS::IdentificationDataInternal::AppliedProcessingStep::processing_step_opt> > > >’} has no me
mber named ‘emplace_back’
  757 |         applied_processing_steps.emplace_back(applied_processing_step);
```

among other things.
Using Boost 1.78 compiles just fine.

Can anyone confirm?

**Comment by cbielow** [comment]
we'd need to increase our minimal required boost version to 1.78 (any volunteers?)

**Comment by timosachsenberg** [comment]
Checked contrib: here it is already 1.78 https://github.com/OpenMS/contrib/blob/b786ca3996192a727fa74eb4df846ce43d3e0e4d/CMakeLists.txt#L229
- need to check support on manylinux/conda?
- vcpkg
- basically all other places that install boost via package managers

**Comment by jpfeuffer** [comment]
It's 1.84 on bioconda

**Comment by cbielow** [comment]
since all builds are running fine, we just need to find the minimal Boost version currently used.
My guess was 1.78, since this what the Contrib uses and it runs fine.

**Comment by jpfeuffer** [comment]
Ubuntu 22.04 and therefore GitHub actions uses 1.74 and it runs fine. Something is fishy

**Comment by cbielow** [comment]
Could be compiler version and indirect consequences, such as different #include structure.

**Comment by timosachsenberg** [comment]
Did you check that this member exists in 1.74? Maybe some header inclusion order messes up something with the template instantiation?

emplace was likely already added in 1.55 https://www.boost.org/doc/libs/1_74_0/libs/multi_index/doc/release_notes.html#boost_1_55

**Comment by cbielow** [comment]
On a fresh build, I cannot reproduce the initial error anymore (although my conda env changed in the meantime) and Boost 1.74 works fine.
However, if:
> emplace was likely already added in 1.55 https://www.boost.org/doc/libs/1_74_0/libs/multi_index/doc/release_notes.html#boost_1_55

then we should still update requirements, since now we only require Boost 1.48.
Updating to Boost 1.74 (which is 4 years old at this point), should be a reasonable requirement?!

**Comment by jpfeuffer** [comment]
Yes, 1.74 seems fine I think.
