### ISSUE TITLE
CometAdapter & neutral loss

### ISSUE THREAD

**Issue by rolivella** [OpenMS/OpenMS#7543]
Hello

Is there a way to define the neutral loss for variable modifications using `CometAdapter`? 

In the Comet documentation ([link](https://comet-ms.sourceforge.net/parameters/parameters_202101/variable_mod01.php)), you can define the neutral loss of a variable modification like this: 

`variable_mod02 = 79.966331 STY 0 3 -1 0 0 97.976896     ... possible phosphorylation on any S, T, Y residue with a neutral loss of 98`

I've seen some options at the `CometAdapter` documentation but I don't know if they're what I'm searching for. 

Thanks!

**Comment by timosachsenberg** [comment]
@cbielow do you know by heart?

**Comment by cbielow** [comment]
Its currently not possible to define NLs:
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/CometAdapter.cpp#L430

**Comment by timosachsenberg** [comment]
we have this information in our residue db... would it make sense to write it out?

**Comment by rolivella** [comment]
which residue db?

**Comment by timosachsenberg** [comment]
Sorry this was mainly intended for @cbielow . We store this information already in OpenMS (from unimod). So it would be easy to write it out to the comet file (I think).
