### ISSUE TITLE
Building pyopenms on a Mac with M3 chip for Docker deployment

### ISSUE THREAD

**Issue by JohannesvKL** [OpenMS/OpenMS#7548]
Hi everybody, 
I'm trying to download pyopenms to use in a Docker image I'm building on an M3 Mac. 

I've tried downloading it via pip which resulted in an error message that no version satisfying the requirement was found. I've taken a look at https://github.com/OpenMS/OpenMS/issues/6797 but the trick with installing boost beforehand didn't work when I tried it in the Docker file. 

I then also tried building it from source, but this again failed, without an error being clearly visible to me, and trying to access the link https://pyopenms.readthedocs.io/en/latest/user_guide/build_from_source.html on the docs site led to an Error 404. 

I've attached screenshots of both reports below and also my Dockerfile + .yaml files as .txt files. 

I assume the problems are being caused by the Arm64 architecture, so if anyone has any ideas I'd be very grateful for any help/advice. 

<img width="1470" alt="Screenshot 2024-07-15 at 15 17 03" src="https://github.com/user-attachments/assets/e3687389-e079-46ce-a3c6-c73da9ebf22e">

<img width="1470" alt="Screenshot 2024-07-15 at 15 49 48" src="https://github.com/user-attachments/assets/7a3e8e96-89f1-476b-afcf-b7707addd95e">

[DockerasText.txt](https://github.com/user-attachments/files/16236261/DockerasText.txt)
[dockeryml.txt](https://github.com/user-attachments/files/16236262/dockeryml.txt)
[streamlityml.txt](https://github.com/user-attachments/files/16236263/streamlityml.txt)

**Comment by jpfeuffer** [comment]
Hi,

Yes the workaround in the linked issue should not have been needed. Also, your problem most likely lies somewhere else.

Unfortunately I cannot see any errors. Your logs in the screenshots only show the "notes" from the compiler.


Contributor/developer docs moved here btw:
https://pyopenms.readthedocs.io/en/latest/community/build_from_source.html
(But your commands seem correct in general)

**Comment by jpfeuffer** [comment]
Regarding installing a prebuilt distribution, you might be out of luck.
On global pypi (pip) we do not have a release that was built for Apple Silicon. https://pypi.org/project/pyopenms/#files

Bioconda just started building silicon a few days ago, you won't find a distribution there either.
https://anaconda.org/bioconda/pyopenms/files

Your only chance is our own pypi repository
https://pypi.cs.uni-tuebingen.de/packages/pyopenms-3.1.0-cp311-cp311-macosx_14_0_arm64.whl#md5=fd09eac11c94698ac6288e45090c91fd

In that case just change your reqs in your streamlit yml:

Add a --extra-index-url https://pypi.cs.uni-tuebingen.de
And move pyopenms from conda dependency to pip. Hope that none of our shared libraries clash with whatever you are loading into python at the same time.

**Comment by jpfeuffer** [comment]
Wait, you are building a Linux image. Do you really need an arm image for your deployment?
I would just emulate a normal x86_64 image with Rosetta on your Mac and use normal conda.

**Comment by jpfeuffer** [comment]
@JohannesvKL Did this work for you with platform=amd64 and Rosetta?

**Comment by JohannesvKL** [comment]
Hi @jpfeuffer I forgot to answer, yes it works very well now, thank you very much!

**Comment by jpfeuffer** [comment]
For the future, a Linux arm package would be nice (either on bioconda or our own GitHub actions and then pypi) but we currently don't have the capacity.
