### ISSUE TITLE
Tutorials missing from doc/ for release 3.0.0

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#7555]
Greetings,
in my packaging of OpenMS for Debian, I remember there used to be tutorials (produced as PDF files) in the doc/ directory. That does not seem to be the case anymore ? Or is it an oversight ?
Sincerely
Filippo Rusconi

**Comment by cbielow** [comment]
correct, PDF tutorials were outdated and they have been removed: https://github.com/OpenMS/OpenMS/pull/6936

**Comment by lopippo** [comment]
Sad, but ok :-)
