### ISSUE TITLE
Plugin installation directory

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#7556]
Greetings,

I am having a hard time understanding what you are trying to achieve with this CMake code (main list file):

set(INSTALL_PLUGIN_SUBDIR plugins CACHE PATH "Installation subdirectory under the lib dir for QT plugins")
set(INSTALL_PLUGIN_DIR ${INSTALL_LIB_DIR}/${INSTALL_PLUGIN_SUBDIR})
file(RELATIVE_PATH INSTALL_LIB_PATH_REL_TO_BIN /${INSTALL_BIN_DIR} /${INSTALL_LIB_DIR})
set(QT_PLUGIN_PATH_REL_TO_BIN ${INSTALL_LIB_PATH_REL_TO_BIN}/${INSTALL_PLUGIN_SUBDIR})

Where should the plugins be installed *in the end* ?
Further, I checked the big Debian package that you provide and did not find a single plugin. Are there plugins built in the source tree, I did not see any shared library produced other than the OpenMS and Swath libraries  (usually plugins are produced in the form of shared libraries)?

Thank you 
Filippo

**Comment by lopippo** [comment]
When searching for plugins related to Qt, I find this in my Debian box:
/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/thumbnail.so
That might be what you are trying to achieve:
/usr/lib/x86_64-linux-gnu/qt5/plugins/OpenMS/<shared libs> ?
But I do not see any Qt path component in the CMake code.

I would install the plugins in /usr/lib/x86_64-linux-gnu/OpenMS/plugins, that is:

set(INSTALL_PLUGIN_SUBDIR plugins CACHE PATH "Installation subdirectory under the lib dir for QT plugins")
set(INSTALL_PLUGIN_DIR ${INSTALL_LIB_DIR}/OpenMS/${INSTALL_PLUGIN_SUBDIR})

**Comment by lopippo** [comment]
And then compute a relative path between the install dir for binaries to find plugins:

/usr/bin/ versus /usr/lib/x86_64-linux-gnu/OpenMS/plugins: with a relative path from bin/<program> to plugins/<plugin> like

../lib/x86_64-linux-gnu/OpenMS/plugins

Did I understand correctly (in the end ?)

**Comment by lopippo** [comment]
So, this is what I came up with, what do you think ?

set(DEF_INSTALL_CMAKE_DIR ${CMAKE_INSTALL_LIBDIR}/cmake/OpenMS)
`# Not sure what we need the DEF_INSTALL_LIB_DIR variable... What does DEF stand for "default" ?`
set(DEF_INSTALL_LIB_DIR ${CMAKE_INSTALL_LIBDIR}) (that is, on Debian /usr/lib/x86_64-linux-gnu)
`# Another variable...`
set(INSTALL_LIB_DIR ${DEF_INSTALL_LIB_DIR} CACHE PATH "Installation directory for libraries")
set(INSTALL_PLUGIN_SUBDIR plugins CACHE PATH "Installation subdirectory under the lib dir for QT plugins")
set(INSTALL_PLUGIN_DIR ${INSTALL_LIB_DIR}/OpenMS/${INSTALL_PLUGIN_SUBDIR})
file(RELATIVE_PATH INSTALL_LIB_PATH_REL_TO_BIN /${INSTALL_BIN_DIR} /${INSTALL_LIB_DIR}/OpenMS)
`# /usr/bin versus /usr/lib/x86_64-linux-gnu`
set(QT_PLUGIN_PATH_REL_TO_BIN ${INSTALL_LIB_PATH_REL_TO_BIN}/${INSTALL_PLUGIN_SUBDIR})
`#Which, in the end, if I understand correctly should look like ../lib/x86_64-linux-gnu/OpenMS/plugins`

Sincerely,
Filippo

**Comment by jpfeuffer** [comment]
Hi Filippo!

I think the plugin dir is completely irrelevant when building a package for package managers. The Qt plugins will all be located in a folder findable by the Qt libraries if not relocated.

This is only for standalone packages where we need to relocate both Qt and its plugins next to our libs and binaries and package them. The path to the plugins is hardcoded in the Qt libraries unless overwritten in a qt.conf file. We write this qt.conf file and re-build the plugin structure in the target location to make our package relocatable.

Also, I think the DEF variables actually could go. I never understood their use myself.

**Comment by lopippo** [comment]
Hello, Julianus,
Great! Thank you,
Filippo
