### ISSUE TITLE
Logic of directory functions and naming

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#7557]
Greetings, 

in my quest to better understand the logic behind the build system and the source tree structure I would like to know what are the functions of the following directories:

$(top_src)/THIRPARTY
$(top_src)/contrib
$(top_src)/src/openms/thirdparty

Capitalization, name, what is the logic behind these directories and the names ?

Thank you
Filippo

**Comment by jpfeuffer** [comment]
Hi!

- $(top_src)/THIRPARTY

  This is a submodule with optional thirdparty **tools** for which wrappers exist in our binaries. E.g. If you use CometAdapter for an alternative peptide search engine, it will try to find comet.exe (which is from another developer), call it, convert input, output, etc.
  It is a submodule to make sure that CI, tests, release tagging etc stays in sync

- $(top_src)/contrib
  A submodule with CMake scripts to build all (large) dependency libraries (except Qt). Not all dependencies are available on all distros and OSes. These days, Ubuntu's repos and Homebrew should have enough dependencies to skip building anything from contrib. Most other repos are missing at least COIN-OR.
 Another use-case is that we sometimes also reduce their transitive dependencies by disabling some compile flags (to have an easier time when building installers on Windows etc.).
  Also here, we need to make sure that a specific commit is tested and therefore it is a submodule.

- $(top_src)/src/openms/thirdparty
  Thirdparty libraries that are small enough to be compiled into our libs and binaries from their source. Usually but not exclusively header-only libraries. Many of them not available on package managers.

**Comment by lopippo** [comment]
Thank you very much! Closing, as the answer does the job :-)
