### ISSUE TITLE
Use before define ?

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#7558]
Greetings,

I might be wrong, but I seem to see that, in src/openms/CMakeLists.txt, this code uses CF_OPENMS_DATA_PATH, that is defined in configh.cmake before including that file. Or not ?

```#------------------------------------------------------------------------------
# At this point make a summary of where data and doc will be located:
message(STATUS "Info: CF_OPENMS_DATA_PATH: ${CF_OPENMS_DATA_PATH}")
message(STATUS "Info: CF_OPENMS_DOC_PATH: ${CF_OPENMS_DOC_PATH}")

#------------------------------------------------------------------------------
# configure config.h
#------------------------------------------------------------------------------
include(${PROJECT_SOURCE_DIR}/configh.cmake)```

Filippo

**Comment by cbielow** [comment]
true. nicely spotted.
The bug will vanish when calling `cmake` again. That's probably why it was not spotted before.
It's 'only' a small nuisance, since only the output on the console during configuration is affected, but worth a fix nevertheless.
PR coming up and thanks for reporting!
