### ISSUE TITLE
Configure so that TOPPAS documentation is accessible from help tutorial menu

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#7562]
Greetings,

I can't succeed in getting TOPPAS's help->TOPPAS tutorial F1 menu to point to the installed documentation.

I configued the software:

```
cmake -DUSE_EXTERNAL_SQLITECPP=ON -DUSE_EXTERNAL_JSON=ON -DHAS_XSERVER=OFF -DCMAKE_SKIP_RPATH=ON -DCMAKE_INSTALL_PREFIX="/usr" -DGIT_TRACKING=OFF -DENABLE_UPDATE_CHECK=OFF -DOPENMS_CONTRIB_LIBS=$(CUR_DIR)/src/openms/extern -DCMAKE_BUILD_TYPE=Release -DBOOST_USE_STATIC=OFF ../../development
```

then

```DESTDIR=/home/rusconi/tmp make -j20 install```

The build was perfect, the install also. 

Then I try to run TOPPAS:

```LD_LIBRARY_PATH=~/tmp/usr/lib/ ./TOPPAS```
and then show the tutorial.

The URL is:

```/home/rusconi/devel/openms/build-area/unix/doc/html/TOPPAS_tutorial.html```

that is, the build directory, not the install directory.

Where should I configure the final destination of the documentation so that the program, once installed in /usr/bin knows where to find it.

I used to do that configuration but I'm not sure why I can't succeed anymore.

Any ideas ?

Sincerely,
Filippo

/home/rusconi/devel/openms/build-area/unix/doc/html/TOPPAS_tutorial.html

**Comment by lopippo** [comment]
I have configured configh.cmake this way:

```
## define some source directories
set(CF_OPENMS_DATA_PATH ${CMAKE_INSTALL_PREFIX}/share/openms CACHE INTERNAL "Path to the shared documents of OpenMS.")
set(CF_OPENMS_DOC_PATH ${CMAKE_INSTALL_PREFIX}/share/doc/openms CACHE INTERNAL "Path to the documentation of OpenMS.")
## and the corresponding ones when installed (careful, you have to rebuild if you change -DCMAKE_PREFIX_PATH). Also, does not work after deployment.
set(CF_OPENMS_INSTALL_DATA_PATH ${CMAKE_INSTALL_PREFIX}/share/openms CACHE INTERNAL "Path to the installed shared documents of OpenMS.")
set(CF_OPENMS_INSTALL_DOC_PATH ${CMAKE_INSTALL_PREFIX}/share/doc/openms CACHE INTERNAL "Path to the installed documentation of OpenMS." )
```

Right after CMake configuration, the ```${CMAKE_BINARY_DIR}/src/openms/include/OpenMS/openms_data_path.h``` file contains the following:

```
#ifndef OPENMS_DATA_PATH_H
#define OPENMS_DATA_PATH_H

// The path to the directory where OpenMS data is installed
#define OPENMS_DATA_PATH "/usr/share/openms"

// The path to the directory where OpenMS doc is installed
#define OPENMS_DOC_PATH "/usr/share/doc/openms"

// The directory where OpenMS is build
#define OPENMS_SOURCE_PATH "/home/rusconi/devel/openms/development/src/openms"

// The directory where the OpenMS sources are located
#define OPENMS_BINARY_PATH "/home/rusconi/devel/openms/build-area/unix/src/openms"

// The directory containing the installed shared documents of OpenMS
#define OPENMS_INSTALL_DATA_PATH "/usr/share/openms"

// The directory containing the installed documentation of OpenMS
#define OPENMS_INSTALL_DOC_PATH "/usr/share/doc/openms"

#endif // #ifndef OPENMS_DATA_PATH_H
```

It seems to me that this kind of configuration tweak used to work time ago. Or am I wrong ? What am I doing bad, here ?

Thank you for your help,
Filippo

**Comment by cbielow** [comment]
The code which decides which path to open is here:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/SYSTEM/File.cpp#L448

It prefers the developer location (maybe it should not do that; and we should inverse the order).
However, on a clean install in a user machine, it will not find the developer docs and use the installed docs.

Do you think this is sufficient? Otherwise we can quickly fix it.

**Comment by lopippo** [comment]
Greetings, for some reason I do not get the notifications by email. I'm looking into that as soon as possible :-)

**Comment by lopippo** [comment]
Thank you, moving doc/html to doc/washtml in the build directory made TOPPAS to find the proper documentation. One glitch, however: the program that is launched to view the html/index.html page is not a browser, but an editor, but I guess this is on my system part ?

So for the moment let's close this issue. I'll check that the behaviour continues to be the same upon creation and installation of Deb packages when the build/doc/html directory is absent.

**Comment by cbielow** [comment]
> however: the program that is launched to view the html/index.html page is not a browser, but an editor, but I guess this is on my system part ?

We use Qt internally, which does exactly what you already guessed: https://doc.qt.io/qt-6/qdesktopservices.html

**Comment by lopippo** [comment]
> > however: the program that is launched to view the html/index.html page is not a browser, but an editor, but I guess this is on my system part ?
> 
> We use Qt internally, which does exactly what you already guessed: https://doc.qt.io/qt-6/qdesktopservices.html

Yes, indeed, I did see this. Oddly enough my Applications config in KDE says that text/html should use Firefox... Anyways.

As for the TOPPAS tutorial html/index.html file, that is now found properly with my Deb packages installed canonically.

No, this comment is for a problem I have with TOPPAS (once installed) to find the examples directory when the File->Open example file menus is selected. The file opening dialog box opens in the $(top_src) directory. I try to find a location where the *installed* directory for examples is set...


[EDIT] Getting to it: the path to the examples is constructed using `File::getOpenMSDataPath().toQString()` from /OpenMS/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp.
Keep investigating :-)

[EDIT] Keeping you informed: I guess, it was a glitch in my packaging. Trying to fix it.

[EDIT] Solved :-)
