### ISSUE TITLE
Question: UNASSIGNEDPEPTIDE in tsv output of TextExporter(consensusXML)

### ISSUE THREAD

**Issue by jonasscheid** [OpenMS/OpenMS#7564]
@jpfeuffer are UNASSIGNEDPEPTIDE entries in this output format all PSMs?

Follow-up question: If I have a tsv output from TextExporter(idXML) I get a "flat" tsv table with only the peptide information, not all PSMs right? Params for the IDfilter pre Textexporter(idXML): https://github.com/nf-core/mhcquant/blob/1b3069246d10ec305ec2f478f490ec05aa734ce5/conf/modules.config#L94
Does `delete_unreferenced_peptide_hits ` also remove PSMs?

Thanks in advance!!

**Comment by jpfeuffer** [comment]
Hi! I think it depends a bit. Our FeatureMap and ConsensusMap classes have a member unassignedPeptideIdentifications.
This is a collection of identified spectra and their associated PSMs that could not be assigned to a feature. Sometimes they do not fall into a feature, sometimes they are not the best sequence for the feature and we unassign them manually.

If everything works correctly and defaults are used, they are filtered in the same way as the PeptideIdentifications in the features.
In your linked example this is what the docs say about the param:
`Peptides not referenced by any protein are deleted in the IDs. Usually used in combination with 'score:protein' or 'thresh:prot'.`

If you filter for PSM-level scores, this will not have any effect. You will only get unreferenced PSMs when you remove proteins. The equivalent for (not) propagating changes to the protein level when you filter on PSM level is "keep_unreferenced_proteins"

**Comment by jonasscheid** [comment]
Thanks for the explanation! That explains things more 🙏🏼 
I wanted to obtain the number of PSMs per peptide and in the the whole spectrum file. So as far as I understood it would be valid to call UnassignedPeptideIdentifications PSMs, right?

For a ID-only run I don't have featureMaps or ConsensusMaps. There its Percolator (with all PSMs) -> IDFilter -> TextExporter. IDFilter somehow filters out the PSMs and keeps only the best. Would it make sense to add a #PSM UserParam or am I missing something here 🤔

**Comment by jpfeuffer** [comment]
Yes if you don't care about if an ID or pam was associated to a feature, I would count it as well.

Is it because you use best:spectrum_per_peptide in idfilter?

Yes I think there is currently no way to annotate that information when it is removed.
You will have to store it in a separate place (in code or in file) before filtering.

I guess an optional "best:annotate_n_removed" or something would make sense.

**Comment by jonasscheid** [comment]
Ok perfect 👍🏼 

No I don't us that flag: [IDfilter flags](https://github.com/nf-core/mhcquant/blob/1b3069246d10ec305ec2f478f490ec05aa734ce5/conf/modules.config#L94) I need to check again the codebase of IDFilter what is happening exactly and I'll try to implement this flag 👍🏼
