### ISSUE TITLE
libsvm cmake configuration errors on mac

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7574]
CMake Error at /usr/local/Cellar/cmake/3.30.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find LIBSVM (missing: LIBSVM_LIBRARIES) (found suitable version
  "3.3.4", minimum required is "2.91")

**Comment by jpfeuffer** [comment]
I guess a breaking change in brew or cmake since I think nothing changed here. It finds the header but no libsvm.dylib
Since when is this?

**Comment by timosachsenberg** [comment]
must be quite recent according to github actions 1-3 weeks?

**Comment by timosachsenberg** [comment]
maybe this change? https://github.com/Homebrew/homebrew-core/commit/1bf1dd6893ee09497e15c93778b56762cd0922bf

**Comment by jpfeuffer** [comment]
Yep. This completely breaks that recipe. There will be no symlink anymore since v3 does not exist anymore.

**Comment by jpfeuffer** [comment]
https://github.com/Homebrew/homebrew-core/issues/183421

**Comment by timosachsenberg** [comment]
still an issue`? https://cdash.seqan.de/build/297760/configure

**Comment by jpfeuffer** [comment]
Nah, I think it doesnt use the correct bottles yet.
Not sure why? Maybe the action needs a `brew update`?

**Comment by jpfeuffer** [comment]
Maybe GHA uses some cache for brew bottles? Unlikely?

**Comment by poshul** [comment]
Looks like adding `brew update` worked: https://github.com/OpenMS/OpenMS/pull/7580

**Comment by poshul** [comment]
But, there's still an error:
`  Reason: tried: '/opt/homebrew/opt/libsvm/lib/libsvm.so.4' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libsvm/lib/libsvm.so.4' (no such file), '/opt/homebrew/opt/libsvm/lib/libsvm.so.4' (no such file), '/opt/homebrew/Cellar/libsvm/3.35/lib/libsvm.so.4' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/libsvm/3.35/lib/libsvm.so.4' (no such file), '/opt/homebrew/Cellar/libsvm/3.35/lib/libsvm.so.4' (no such file)`

**Comment by jpfeuffer** [comment]
Yep, the install_name is also broken:

```
/opt/homebrew/Cellar/libsvm/3.35/lib/libsvm.4.dylib:
	/opt/homebrew/opt/libsvm/lib/libsvm.so.4 (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1700.255.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)
```

**Comment by poshul** [comment]
Fixed now
