### ISSUE TITLE
FR: report non-smoothed intensities with FFM

### ISSUE THREAD

**Issue by rickhelmus** [OpenMS/OpenMS#7582]
Hello,

This is somewhat related to #5232. FFM now reports the peak intensity through the `max_intensity` output param. I would like to use this value for e.g. plotting purposes, so it would make most sense to use non-smoothed data. From the code, I gather that setting `use_smoothed_intensities=false` should get me there, but then smoothing will also be disabled for e.g. isotope selection and scoring. So I was wondering if `use_smoothed_intensities` could be split in two flags: one for internal calculations and another for reporting data?

Thanks,
Rick

**Comment by timosachsenberg** [comment]
I think this should be possible. I did not dive deep into the code but it might mean (not sure about that) that we need to keep both smoothed and non-smoothed intensities in the internal data structures. While not difficult it seems like a bit of work. Would you be interested in implementing this (e.g., with some help / advice from us)?

**Comment by rickhelmus** [comment]
Hi @timosachsenberg ,

Thanks for your reply! The changes needed are actually quite limited. I made a small PR (https://github.com/OpenMS/OpenMS/pull/7594), but as noted in the comments I could use a few hints to finish things up :-)

Thanks,
Rick
