### ISSUE TITLE
OpenMS 3.2 Dockerfiles

### ISSUE THREAD

**Issue by prvst** [OpenMS/OpenMS#7591]
Hi, thanks for the update. Is there a prediction on when the Dockerfiles will be available?

**Comment by jpfeuffer** [comment]
I think somehow the Release tag was changed in the recent release from Release3.2.0 to release/3.2.0

Therefore the docker deploy action does not trigger.
https://github.com/OpenMS/OpenMS/blob/18687629f4d8221209a16c4cb8d3f9d49eb0237f/.github/workflows/containerdeploy.yml#L8
@timosachsenberg Any idea why? I think it can have more implications than just this action.

**Comment by jpfeuffer** [comment]
@timosachsenberg Btw I think due to the new GHA triggered sync of nightly, the push trigger of the deploy container action will not work anymore. You need to trigger the action manually from the syncing action.
(GH policy)

**Comment by timosachsenberg** [comment]
I manually triggered a container deploy now https://github.com/OpenMS/OpenMS/actions/runs/10940008384 . Not why the tag has been changed.

**Comment by prvst** [comment]
Thank you so much!

**Comment by poshul** [comment]
> I think somehow the Release tag was changed in the recent release from Release3.2.0 to release/3.2.0
> 
> Therefore the docker deploy action does not trigger.
> 
> https://github.com/OpenMS/OpenMS/blob/18687629f4d8221209a16c4cb8d3f9d49eb0237f/.github/workflows/containerdeploy.yml#L8
> 
> @timosachsenberg Any idea why? I think it can have more implications than just this action.

Hmm, that's probably due to the switch to GHA, I'll put that on my list of things to check when I get back.

**Comment by prvst** [comment]
Thanks for working on this. I'm particularly interested in building the images locally, is the v3.2.0 Dockerfile also available?

**Comment by poshul** [comment]
Sorry for the delay on this. There is now a branch and a PR to update the files. https://github.com/OpenMS/dockerfiles/pull/30

**Comment by prvst** [comment]
Thank you, I will pull them once they are merged.

**Comment by poshul** [comment]
@prvst They are merged now.

**Comment by prvst** [comment]
Thank you again!
