### ISSUE TITLE
Can't store peptide identification with spectrum to mzml file using pyopenms 3.1.0

### ISSUE THREAD

**Issue by ghost** [OpenMS/OpenMS#7596]
Hi & thanks for your reply,
I am trying to use pyopenms 3.1.0 to store spectrum (read from .mzml file) and its corresponding peptide identification (identified by other software or manually validation) to .mzml file on windows system, and the python version I use is 3.11. The relative codes are listed below. The spectrum is stored successfully, but the identification result is not shown in the .mzml file I stored.

Here are my codes:
`
```
import pyopenms as oms
from pyopenms import MSExperiment, MzMLFile, PeptideIdentification, PeptideHit

file = MzMLFile()
exp = MSExperiment()
file.load("D:\Test_Files\Thermo011.mzML", exp)

spectrum = exp[4270]

peptide_id = PeptideIdentification()
peptide_id.setIdentifier("example_identifier")
peptide_id.setRT(1234.5)
peptide_id.setMZ(567.89)

peptide_hit = PeptideHit()
peptide_hit.setScore(42.0)
peptide_hit.setCharge(2)
peptide_hit.setSequence(oms.AASequence.fromString("PEPTIDESEQ"))

peptide_id.setHits([peptide_hit])

spectrum.setPeptideIdentifications([peptide_id])

exp_export = MSExperiment()
exp_export.addSpectrum(spectrum)

mzml = MzMLFile()

mzml.store("path_to_your_new_file.mzML", exp_export)
````

I wonder if there is something wrong with my codes and can the identification results be stored together with spectrum in .mzml file?

Thanks again.

Best Wishes,

Jim

**Comment by ghost** [comment]
I have noticed that IdXMLFile can store identification results, but I wonder if I can match these results with spectrum? Since I don't find a setSpectrum() function in PeptideHit() class.

Much thanks again

**Comment by jpfeuffer** [comment]
Hi!
What is your ultimate goal after "matching" them to the spectra? To view them in e.g. TOPPView?
Or do another analysis?

**Comment by ghost** [comment]
Hi!
I wanna try to preserve the spectra and identifications in one file. Just for the convenience of latter analysis and review. 
If this can't be done with pyopenms now, store the spectra and the identifications in different files is ok.

And by the way, could you please take a look at my another question about feature extraction:
https://github.com/OpenMS/pyopenms-docs/issues/444

which will help me a lot.

Much thanks

**Comment by timosachsenberg** [comment]
Hi. We store them in separate files (e.g., we frequently have multiple identification files (different search engines etc.) per run).
