### ISSUE TITLE
Wheel action tries to delete wrong libraries

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7608]
https://github.com/OpenMS/OpenMS/blob/a37ef4ff8daf7dec4492f12443aab430e2a7a5d6/.github/workflows/pyopenms-wheels.yml#L138

Should be something like _pyopenms*.pyd on windows.

And probably _pyopenms*.so on other platforms. Double-check that this find actually works. And double-check all wheels after this change.

**Comment by timosachsenberg** [comment]
what about:
![image](https://github.com/user-attachments/assets/e23eb97a-8da2-428a-a466-06df80902162)
does this mean it is also packages for different python versions?

**Comment by jpfeuffer** [comment]
This is what I mean. It loops the build over multiple versions but does not delete the built libs from the last iteration.
