### ISSUE TITLE
PyOpenMS 3.2.0 build fails on bioconda due to Eigen3 not found

### ISSUE THREAD

**Issue by jonasscheid** [OpenMS/OpenMS#7614]
Related PR: https://github.com/bioconda/bioconda-recipes/pull/51014

conda build log: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=71098&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=583

Error:
>12:33:44 BIOCONDA INFO (OUT) CMake Error at /opt/conda/conda-bld/pyopenms_1728390567959/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/cmake/OpenMS/OpenMSTargets.cmake:78 (set_target_properties):
12:33:44 BIOCONDA INFO (OUT)   The link interface of target "OpenMS" contains:
12:33:44 BIOCONDA INFO (OUT) 
12:33:44 BIOCONDA INFO (OUT)     Eigen3::Eigen
12:33:44 BIOCONDA INFO (OUT) 
12:33:44 BIOCONDA INFO (OUT)   but the target was not found.  Possible reasons include:
12:33:44 BIOCONDA INFO (OUT) 
12:33:44 BIOCONDA INFO (OUT)     * There is a typo in the target name.
12:33:44 BIOCONDA INFO (OUT)     * A find_package call is missing for an IMPORTED target.
12:33:44 BIOCONDA INFO (OUT)     * An ALIAS target is missing.
12:33:44 BIOCONDA INFO (OUT) 
12:33:44 BIOCONDA INFO (OUT) Call Stack (most recent call first):
12:33:44 BIOCONDA INFO (OUT)   /opt/conda/conda-bld/pyopenms_1728390567959/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/cmake/OpenMS/OpenMSConfig.cmake:111 (include)
12:33:44 BIOCONDA INFO (OUT)   CMakeLists.txt:39 (find_package)

Error related to this:
https://github.com/OpenMS/OpenMS/blob/f47d834cdd692f90aaa9e336a28a0220b5fa3e2c/src/pyOpenMS/CMakeLists.txt#L39

Comment underneath:
> #TODO when separating pyopenms from OpenMS, specify a pyopenms version and the compatible OpenMS version to be searched above.
> For now we just hope that the right OpenMS version from this same git repo is installed and found and
> therefore give pyopenms here the same version. CF_OPENMS_PACKAGE_VERSION is used in env.py for setup.py

Could it be that the hard coded link
https://github.com/jonasscheid/bioconda-recipes/blob/4c2eace48dfdd6efc2f70a419b26058ae2b6cd88/recipes/pyopenms/meta.yaml#L14

is causing that `that the right OpenMS version from this same git repo is` NOT found?

**Comment by poshul** [comment]
I don't think this is related to the OpenMS version, but rather that there isn't an eigen3 conda package.

**Comment by jonasscheid** [comment]
I tried multiple of these eigen packages. I tried everyone of them (see commits), including the one used to build the OpenMS conda env https://anaconda.org/conda-forge/eigen

None of them worked, same error the whole time :/

In a previous commit [it is also installed by conda](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=71106&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=383), but somehow not in `find_package(OpenMS)`

**Comment by jpfeuffer** [comment]
@timosachsenberg https://github.com/OpenMS/OpenMS/blame/dacaf8bd6b8bf4add608820886aa44482a3456ae/src/openms/CMakeLists.txt#L84

This commit exposed Eigen in our interface. You will need to notify downstream libs about this.
https://github.com/OpenMS/OpenMS/blob/dacaf8bd6b8bf4add608820886aa44482a3456ae/cmake/OpenMSConfig.cmake.in#L61

**Comment by timosachsenberg** [comment]
ok is it sufficient to uncomment it? with or without version number?

**Comment by jpfeuffer** [comment]
Yes, just uncomment. Ideally a compatible version is inferred from the one used at build time but Eigen should be relatively lenient.

**Comment by jonasscheid** [comment]
Thanks for taking care of that!
@timosachsenberg I think `https://github.com/OpenMS/OpenMS/releases/download/release%2F3.2.0/OpenMS-3.2.tar.gz` needs to be updated as well 🤔 ...

**Comment by timosachsenberg** [comment]
k let me see if I can do this quickly

**Comment by timosachsenberg** [comment]
k I uploaded the file with that single line fix.
You need to calculate a new checksum though.

**Comment by jonasscheid** [comment]
Crashing again with 3.4.0 with same error as described above. Probably because 3.3.4 is fixed in OpenMS and this version is not published on conda. Only 3.3.5, [but that did not work as well](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=71351&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=478). What about setting Eigen in OpenMS to 3.4.0 or >=3.3.5 or sth?

**Comment by timosachsenberg** [comment]
I thought in cmake it just means minimum version required. @jpfeuffer ?

**Comment by jpfeuffer** [comment]
Is the tar already updated?

**Comment by jpfeuffer** [comment]
It is not even looking for Eigen so it is probably not up-to-date.

Ideally the libopenms exposes Eigen as a downstream dependency now, too, such that version conflicts do not arise anymore

**Comment by timosachsenberg** [comment]
let me check... I think I updated it (just commented out the line we talked about)

**Comment by timosachsenberg** [comment]
Its in the OpenMSConfig.cmake.in

**Comment by jpfeuffer** [comment]
Ah no, you need a new release of a built libOpenMS, too.

**Comment by jonasscheid** [comment]
Looks like eigen is no problem anymore! Only bioconda blocking because of memory limitations. I guess we need to wait that some core member includes it in a bulk PR. But this is another issue.

Thanks for helping me out here! :)
