### ISSUE TITLE
Upgrade numpy in pyopenms 

### ISSUE THREAD

**Issue by uweschmitt** [OpenMS/OpenMS#7634]
Dear all,

the numpy version you are using for pyopenms https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/setup.py#L257 is quite outdated and incompatible with recent numpy versions on a binary level.

This forces me to downgrade or limit the numpy versions I'm able to use. This constraint may also restrict the Python versions which are compatible with pyopenms in the future, especially on systems without a pre-compiled installer.

The details about Numpy binary API stability are documented here: https://numpy.org/doc/1.22/user/depending_on_numpy.html

Thanks!

Uwe

**Comment by timosachsenberg** [comment]
Hi Uwe,
@poshul already prepared https://github.com/OpenMS/OpenMS/pull/7539
we just did not get around to testing it yet.
Do you want to give it a try?
If you dont want to compile pyOpenMS we might also be able to create a whl to test.
