### ISSUE TITLE
Wrap static AASequence::fromString() for easier use in python

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7647]
e.g.., to just call
a = AASequence(b"PEPTIDER");
a.toMZ(2);

**Comment by jpfeuffer** [comment]
Probably not worth the trouble.
Python is an OOP language. Most people should be familiar with static methods.

You need to do either:
a) add functionality in autowrap to use different functions as alternative/dispatched constructors
b) create a new python based class that inherits from AA sequence, add new functionality there and then overwrite the old one for backwards compatibility. Will have weird docs, performance penalties etc.

**Comment by timosachsenberg** [comment]
Some python team found this as one of the first pitfalls new users might have. Maybe because static methods are less common in python.
Another alternative would be adding a String constructor to AASequence on the C++ side that by default uses the most versatile / generic fromString static to construct the object?

**Comment by jpfeuffer** [comment]
Can't you do AAsequence(const String&, bool modified) or AASequence(const String&, SequenceTypeEnum type)?

**Comment by jpfeuffer** [comment]
But note, it will still have minor performance impacts because overloaded methods will be dispatched after type checking in python.
