### ISSUE TITLE
Unit and TOPP tests are only being run on Ubuntu-22.04-Clang not any of the other matrix entries for CI

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#7682]
openms-ci-full only runs unit tests and TOPP tests on a single configuration of the matrix job (see https://github.com/OpenMS/OpenMS/actions/runs/11855726562/job/33040541215 where the **only job** run on the other hosts is Doxygen_Warning_test).

**Comment by poshul** [comment]
any suggestions @jpfeuffer ?

**Comment by jpfeuffer** [comment]
Yes, someone added the package target to the build step already. One has to wait until the package step to set the package type:
https://github.com/OpenMS/OpenMS/blob/a82b7746c4f394cc46ef188c725a7c7289b8c906/src/tests/CMakeLists.txt#L45

**Comment by poshul** [comment]
Thanks, I've added a warning to the cmake file so that it doesn't just discard user input silently: https://github.com/OpenMS/OpenMS/pull/7683/files

**Comment by poshul** [comment]
Removing the package_type specification fixed the issue.
