### ISSUE TITLE
Mac OS not supported?

### ISSUE THREAD

**Issue by btemoshir** [OpenMS/OpenMS#7690]
While trying to pull the docker image, I get the following error. The docs say that MacOS is supported, but its doesn't seem like it. Can you also ship the appropriate build?

`Error response from daemon: no matching manifest for linux/arm64/v8 in the manifest list entries: no match for platform in manifest: not found`

Thank you.

**Comment by jpfeuffer** [comment]
We only build for amd64. If you want to run it on macOS silicon (arm64/V8) you will need to request the amd64 platform specifically and let it run with Rosetta.
You can build the container yourself also.

**Comment by btemoshir** [comment]
Thank you :) I closed the issue now.
