### ISSUE TITLE
Current pyOpenMS errors

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7691]
web apps:
platforms: Windows embedded python 3.11
- pyopenms pyopenms-3.1.0.dev20240507-cp311-cp311-win_amd64.whl still works
- pyopenms-3.1.0.dev20240621-cp311-cp311-win_amd64.whl fails with dll import error if pyopenms is imported in page script
- workaround:
- import pyopenms in app.py

also tested: currently nightly whl 3.3dev doesn't work

easypqp:
https://github.com/Nesvilab/FragPipe/issues/1431
https://github.com/Nesvilab/FragPipe/issues/1543#issuecomment-2435555771 points to some issue with python installed as admin and packages as user
https://github.com/OpenMS/OpenMS/issues/7333 here one issue was avx;

another one using the base conda environment (creating a new one and using that to install easypqp in fragpipe worked) on windows
```
I was using a freshly installed Anaconda base (root) environment which caused it not to work.
I created a new environment. Within fragpipe, clicking 'Install/Upgrade EasyPQP,' all dependencies and versions will be installed properly.
```

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dtabb\AppData\Local\Programs\Python\Python311\Scripts\easypqp.exe\__main__.py", line 4, in <module>
  File "C:\Users\dtabb\AppData\Local\Programs\Python\Python311\Lib\site-packages\easypqp\main.py", line 9, in <module>
    from .convert import conversion, basename_spectralfile, conversion_psm, drop_psm_columns
  File "C:\Users\dtabb\AppData\Local\Programs\Python\Python311\Lib\site-packages\easypqp\convert.py", line 18, in <module>
    import pyopenms as po
  File "C:\Users\dtabb\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopenms\__init__.py", line 109, in <module>
    raise e
  File "C:\Users\dtabb\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopenms\__init__.py", line 67, in <module>
    from ._all_modules import *  # pylint: disable=wildcard-import; lgtm(py/polluting-import)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dtabb\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopenms\_all_modules.py", line 1, in <module>
    from ._pyopenms_1 import *  # pylint: disable=wildcard-import; lgtm(py/polluting-import)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _pyopenms_1: A dynamic link library (DLL) initialization routine failed.
Traceback (most recent call last):
  File "H:\software\fragpipe-22.0\tools\speclib\gen_con_spec_lib.py", line 580, in <module>
    main()
  File "H:\software\fragpipe-22.0\tools\speclib\gen_con_spec_lib.py", line 552, in main
    main_easypqp(params, irt_df, allcmds, easypqp_convert_cmds)
  File "H:\software\fragpipe-22.0\tools\speclib\gen_con_spec_lib.py", line 306, in main_easypqp
    subprocess.run([os.fspath(params.easypqp), '--version'], check=True)
  File "C:\Users\dtabb\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\dtabb\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\easypqp.exe', '--version']' returned non-zero exit status 1.

======================================================================
Error when loading pyOpenMS libraries!
```

**Comment by t0mdavid-m** [comment]
Minimal example:

```
import pandas
import pyopenms
```
Output:
```
======================================================================
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Z:\TemplateWindows\OpenMS-App(41)\OpenMS-AppStripDown\python-3.11.0\Lib\site-packages\pyopenms\__init__.py", line 109, in <module>
    raise e
  File "Z:\TemplateWindows\OpenMS-App(41)\OpenMS-AppStripDown\python-3.11.0\Lib\site-packages\pyopenms\__init__.py", line 67, in <module>
    from ._all_modules import *  # pylint: disable=wildcard-import; lgtm(py/polluting-import)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\TemplateWindows\OpenMS-App(41)\OpenMS-AppStripDown\python-3.11.0\Lib\site-packages\pyopenms\_all_modules.py", line 1, in <module>
    from ._pyopenms_1 import *  # pylint: disable=wildcard-import; lgtm(py/polluting-import)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _pyopenms_1: A dynamic link library (DLL) initialization routine failed.
```
So this seems to be related to pandas.

Weirdly enough:
```
import pyopenms
import pandas
```
does not result in errors.

Pandas Version: `2.2.3`

**Comment by jpfeuffer** [comment]
Cannot reproduce on Win11. Works for me. Both nightly and pypi versions of pyopenms. Both import orders. More information needed.
I assume you are doing weird python embedded/pyinstaller stuff? We would need clear instructions on how to reproduce.

**Comment by t0mdavid-m** [comment]
Sorry - this was just meant to be a quick update while I was figuring out on which platforms it can be reproduced myself. Actually this problem does not seem to be bound to weird embedded python stuff. I was able to reproduce it in a normal `python 3.11.0` environment (only on windows, linux seems to work) when installing these dependencies via pip:

```
streamlit>=1.38.0
pyopenms==3.2.0
```

Then doing:

```
import pandas
import pyopenms
```

Results in the error. I assume it is caused by some weird dependency interactions but I will investigate further.

**Comment by jpfeuffer** [comment]
which pypi url? openms-internal or public pypi?

**Comment by t0mdavid-m** [comment]
Public pypi in this case. Previously, I experimented with installing different wheels from our internal pypi and found that `pyopenms-3.1.0.dev20240507-cp311-cp311-win_amd64.whl ` was the last one that seemed to work.

**Comment by t0mdavid-m** [comment]
Update: `pyarrow>=7.0`, which is a dependency of streamlit seems to be causing the issue, which makes total sense as it integrates with pandas.

**Comment by t0mdavid-m** [comment]
```
import pyarrow
import pyopenms
```
shows the same behavior as pandas. Version is `18.0.0`.

**Comment by jpfeuffer** [comment]
I really hope that pyarrow 7 is NOT a dependency of anything recent. I believe you have some other things installed that force such an old version.

When I install streamlit 1.38+ in a fresh environment I get 1.40 and pyarrow 18 with it.

It makes sense that our new pyopenms does not work with such an old pyarrow as this old pyarrow will not have been compiled with a recent enough numpy C API.

**Comment by jpfeuffer** [comment]
Which pyarrow do you actually get installed when you do this? That would be the more important question

**Comment by t0mdavid-m** [comment]
`18.0.0`, `7` is just the minimum requirement from streamlit. I am creating fresh environments, so it should not be due to other packages.

**Comment by jpfeuffer** [comment]
Yes with pyarrow 11 I get that error.

**Comment by t0mdavid-m** [comment]
The `msvcp140.dll` that ships with `pyarrow` seems to be the issue. Deleting it from `miniconda3\envs\test_env\Lib\site-packages\pyarrow` and hence loading it from `miniconda3\envs\test_env\` resolves the import problems. 

Related to vcpp dlls and thus `msvcp140.dll` seems to be this change between the functioning and non-functioning nightly wheels:

https://github.com/OpenMS/OpenMS/commit/13d0c4b#diff-084f20ae9727db0905c5fbbc32ef797e048c87887ccfc57b0f89b2bf82f45979R35

I am still puzzled why this suddenly broke our imports. Some observations: 
- Dropping pyarrow to really old versions (e.g. 12.0) still results in the same issue. 
- Deleting the vcpp dlls from `miniconda3\envs\test_env\Lib\site-packages\pyopenms` does not resolve the issue

@poshul as you fixed the GA and authored the above commit - do you have any ideas that would explain this?

**Comment by jpfeuffer** [comment]
Great insights! Thank you!
@timosachsenberg and me will be testing another cause.
The RibonucleotideDB initialization at load of the dll might not be thread safe (windowsdbg stops at mutex locks in that class when the failures occur). This might explain the irregular occurrence a bit better. It would not really explain the connection to pyarrow though.

**Comment by poshul** [comment]
I've checked the dlls that @t0mdavid-m sent over:
pyarrow uses: 14.28.29334.0
pyopenms 3.2/3.3 uses: 14.40.33810.0
pyopenms 3.1 uses: 14.36.32532.0
Which is consistent with everything working fine if we load first, since 14.40... is backwards compatible with 14.28... but 14.28 isn't forwards compatible with the later version.

**Comment by jpfeuffer** [comment]
This:
https://github.com/microsoft/STL/issues/4730

?

**Comment by poshul** [comment]
Yup. Looks like it's by design. Where does that leave us? Clearly something is messed up, in that python doesn't load the newer dll version if it already has the old one loaded, but I'm not sure who to open a bug report with there.

**Comment by jpfeuffer** [comment]
Try with the proposed solution when compiling OpenMS on win: `You can define _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR as an escape hatch.`

**Comment by jpfeuffer** [comment]
We can also check already loaded libraries maybe and warn. Tell users, to import pyopenms first.
https://stackoverflow.com/questions/26529147/python-ctypes-get-handle-to-already-loaded-shared-libraries

Not sure if you can unload and reload a library.

**Comment by jpfeuffer** [comment]
You apparently can with dlclose, but this feels very dangerous ☠️ 
https://stackoverflow.com/questions/359498/how-can-i-unload-a-dll-using-ctypes-in-python

**Comment by jpfeuffer** [comment]
All of this could go into our `__init__.py`

**Comment by timosachsenberg** [comment]
could we also do a force reload of pyarrow with import?
```
import importlib
import pyarrow 

# Reload the module
importlib.reload(pyarrow )
```
and inject that in the pyi files or ```__init__.py?```

**Comment by t0mdavid-m** [comment]
> could we also do a force reload of pyarrow with import?
> 
> ```
> import importlib
> import pyarrow 
> 
> # Reload the module
> importlib.reload(pyarrow )
> ```
> 
> and inject that in the pyi files or `__init__.py?`

This would be specific to pyarrow though. If another Python library uses an outdated dll, the same issue would be triggered.

**Comment by jpfeuffer** [comment]
It won't be just pyarrow that might be compiled with that.


Funnily enough, recent cpython distributions come with C++ runtimes, so no one would actually need to ship it these days.
But you would need to make sure that your code is compatible with whatever python ships.
Also not sure if this is defined in a PEP or if I am just lucky on my windows. I can delete those for both pyarrow and pyopenms and they fallback to the python ones and work.

**Comment by t0mdavid-m** [comment]
> It won't be just pyarrow that might be compiled with that.
> 
> Funnily enough, recent cpython distributions come with C++ runtimes, so no one would actually need to ship it these days. But you would need to make sure that your code is compatible with whatever python ships. Also not sure if this is defined in a PEP or if I am just lucky on my windows. I can delete those for both pyarrow and pyopenms and they fallback to the python ones and work.

Yup same for me! Unfortunately if another library ships an outdated dll and it is imported first, the outdated version is not reloaded. I.e. not shipping these dlls with pyopenms wont help.

**Comment by t0mdavid-m** [comment]
In my opinion the preferred solution would be to ship pyopenms with reasonable backwards compatibility - so it doesnt break when used together with common packages. So if #7699 works, I think that would be a good permanent solution (for the next years).

**Comment by jpfeuffer** [comment]
Could you test it already?

**Comment by t0mdavid-m** [comment]
I tested the built wheel and can confirm it works!

**Comment by timosachsenberg** [comment]
Awesome!
