### ISSUE TITLE
Docker containers broken

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7695]
https://github.com/OpenMS/OpenMS/blob/3cea808f260c57790eebfe86b89f4788b50be8fd/dockerfiles/Dockerfile#L112

Both tools and tools-thirdparty should copy lib/bin/share  like we do for library.

**Comment by ypriverol** [comment]
@timosachsenberg Also make sure that the singularity image is well formated: 

```
sif:latest [cache /hps/nobackup/juan/pride/reanalysis/singularity/ghcr.io-openms-openms-tools-thirdparty-sif-latest.img]
ERROR ~ Error executing process > 'NFCORE_QUANTMS:QUANTMS:TMT:ID:DATABASESEARCHENGINES:MSGFDBINDEXING (1)'

Caused by:
  Failed to pull singularity image
    command: singularity pull  --name ghcr.io-openms-openms-tools-thirdparty-sif-latest.img.pulling.1732437055781 docker://ghcr.io/openms/openms-tools-thirdparty-sif:latest > /dev/null
    status : 255
    hint   : Try and increase singularity.pullTimeout in the config (current is "3h")
    message:
      INFO:    Converting OCI blobs to SIF format
      INFO:    Starting build...
      INFO:    Fetching OCI image...
      WARNING: OCI image doesn't declare a platform. It may not be compatible with this system.
      INFO:    Extracting OCI image...
      FATAL:   While making image from oci registry: error fetching image: while building SIF from layers: packer failed to pack: while unpacking tmpfs: no extractable OCI/Docker tar layers found in this image
```

**Comment by jpfeuffer** [comment]
It is not a docker image. You should not pull it as docker://..

**Comment by ypriverol** [comment]
What is the then for the singularity in ghcr.io?

**Comment by jpfeuffer** [comment]
I am not sure if the new docker file with stages supports the sif format correctly.

**Comment by timosachsenberg** [comment]
@poshul hmm can we take a look at this? Seems we broke singularity with the staged builds.

**Comment by timosachsenberg** [comment]
@radusuciu before we try to mess with that. Can you give it a quick look?

**Comment by jpfeuffer** [comment]
@ypriverol try to pull from oras:// or library://

**Comment by jpfeuffer** [comment]
@timosachsenberg I see now that we are converting the docker to sif in the action instead of converting the docker file and building it from scratch with singularity. So in theory this might work  to build a sif.
Still, the COPY statements are missing already in the dockerfiles so this must be fixed.

**Comment by timosachsenberg** [comment]
I think I recall that @radusuciu tested this at some point… not 100% sure though

**Comment by jpfeuffer** [comment]
Nope. I have to correct myself. The runpath was messed up. @poshul Probably related to your recent changes.

**Comment by radusuciu** [comment]
> I think I recall that @radusuciu tested this at some point… not 100% sure though 

We did test this as it was a concern at the time as well and the singularity image worked as expected.

I will try to replicate the issue first

**Comment by jpfeuffer** [comment]
I think it was solved by https://github.com/OpenMS/OpenMS/commit/decb5c832cbf4e8fc85583fb6e44375150cdb3d4! Let me test this first. Thanks for offering! I will let you guys know tomorrow!

**Comment by jpfeuffer** [comment]
Yes! Solved. Works for me.
Rpath was solved by above commit.

@ypriverol
Download for apptainer/singularity works with oras:// scheme (prefix).
Only biocontainer adds the msgfplus "executable". Officially MSGF+ only distributes its MSGFPlus.jar. Please run  `java -jar /opt/OpenMS/thirdparty/MSGFPlus/MSGFPlus.jar` if not using the Adapter.
