### ISSUE TITLE
Generate and publish the CWL tool descriptors for all OpenMS tools

### ISSUE THREAD

**Issue by mr-c** [OpenMS/OpenMS#7706]
`TOOLNAME --write_cwl ${target_directory}`

The CWL files should be installed to `$XDG_DATA_DIRS/commonwl/` (usually `/usr/share/commonwl/`) as per https://www.commonwl.org/v1.2/CommandLineTool.html#Discovering_CWL_documents_on_a_local_filesystem

See also https://specifications.freedesktop.org/basedir-spec/0.6/#referencing

**Comment by poshul** [comment]
@mr-c writing the CWL files is done, but cwltool outputs all warnings to stderr (even if I pass it --no-warning), so right now I can't use that in our CI. Can you take a look at fixing which pipe errors and warnings get redirected to, and I'll merge the CWL generation, but not the validation?

**Comment by poshul** [comment]
@mr-c I've opened an issue for this at https://github.com/common-workflow-language/cwltool/issues/2083 . For 3.3.0 I'm just gonna go ahead and run the validation manually and add it to our checklist.

**Comment by poshul** [comment]
Related, we run into https://github.com/common-workflow-language/cwltool/issues/1696 . WSL is not enabled in the windows runners we use. Do we need to be running the validator on all OS's or do you think skipping windows would be okay?

**Comment by mr-c** [comment]
> Related, we run into https://github.com/common-workflow-language/cwltool/issues/1696 . WSL is not enabled in the windows runners we use. Do we need to be running the validator on all OS's or do you think skipping windows would be okay?

The result will be the same anywhere, don't worry about it 😀

**Comment by mr-c** [comment]
@poshul I don't understand the issue with the output to `stderr`; isn't cmake only looking at the exit code?

**Comment by poshul** [comment]
> @poshul I don't understand the issue with the output to `stderr`; isn't cmake only looking at the exit code?

Looking into this further, it looks like ctest uses a set of internal regexes to determine what counts as a warning versus an error these are stored here: https://gitlab.kitware.com/cmake/cmake/-/blob/v3.31.2/Source/CTest/cmCTestBuildHandler.cxx?ref_type=tags and we can modify them in our setup. I'm still trying to find which regex the cwltool output matches as an error.

**Comment by poshul** [comment]
@mr-c the issue is that the output matches a wildly generic regex in CTest: https://gitlab.kitware.com/cmake/cmake/-/blob/v3.31.1/Source/CTest/cmCTestBuildHandler.cxx?ref_type=tags#L41
