### ISSUE TITLE
TOPPView crashing on MacOS 14 with code signing issue

### ISSUE THREAD

**Issue by RonanDaly** [OpenMS/OpenMS#7734]
On MacOS 14.6, with MacBook M2 Pro, TOPPView crashes on launch. The issue appears to be a code signing one as evidenced in the crash log attached.
[TOPPViewCrash.txt](https://github.com/user-attachments/files/18007595/TOPPViewCrash.txt)

**Comment by jpfeuffer** [comment]
Yep. See #7689 and associated PR #7733. Closing as duplicate.
Thanks for reporting, though.
