### ISSUE TITLE
TOPPView run tool on visible area

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#7779]
11:02:55 ERROR: Cannot create temporary file
Cannot write to 'C:/Users/sachs/AppData/Local/Temp/TOPPView_20241218_110237_sachsenberg_10432_148_out.*.featureXML'!

probably related to FileHandler chagne

**Comment by cbielow** [comment]
this broke it:
https://github.com/OpenMS/OpenMS/pull/7462/files#diff-de3321ce3896ccc73240b41d43c08ec2d579b25b65b789281a585b8a8d9ed463R1693
since the file extension is `*.something` (and has been for the last 12 years AFAICT)

**Comment by poshul** [comment]
> this broke it: https://github.com/OpenMS/OpenMS/pull/7462/files#diff-de3321ce3896ccc73240b41d43c08ec2d579b25b65b789281a585b8a8d9ed463R1693 since the file extension is `*.something` (and has been for the last 12 years AFAICT)

To clarify, where is the * coming from?

**Comment by timosachsenberg** [comment]
probably the extension is *.featureXML ?

**Comment by poshul** [comment]
Okay, so the problem then seems to be https://github.com/OpenMS/OpenMS/blob/4f2d5fd392bc81bed07399d1cd4fdbc0f140adec/src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp#L443 getExtension reads the literal valid file types. This should work fine on linux, as * is a perfectly valid (if inadvisable) character in a filename, but on Windows it chokes.

I can fix it to strip the leading *. pretty easily. What I'm more concerned about here is the behavior of getExtension() when there are multiple possible extensions. It just naively takes the first. Is this intended behavior?

**Comment by cbielow** [comment]
> > this broke it: https://github.com/OpenMS/OpenMS/pull/7462/files#diff-de3321ce3896ccc73240b41d43c08ec2d579b25b65b789281a585b8a8d9ed463R1693 since the file extension is `*.something` (and has been for the last 12 years AFAICT)
> 
> To clarify, where is the * coming from?

here https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/APPLICATIONS/TOPPBase.cpp#L2147

**Comment by cbielow** [comment]
> Okay, so the problem then seems to be
> 
> https://github.com/OpenMS/OpenMS/blob/4f2d5fd392bc81bed07399d1cd4fdbc0f140adec/src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp#L443
> getExtension reads the literal valid file types. This should work fine on linux, as * is a perfectly valid (if inadvisable) character in a filename, but on Windows it chokes.
> 
> I can fix it to strip the leading *. pretty easily. What I'm more concerned about here is the behavior of getExtension() when there are multiple possible extensions. It just naively takes the first. Is this intended behavior?

Ask the author :)
But seriously: probably not, since will cause trouble with TOPP tools which support an `out_type` param.
Why not simply use `.unknown` as an extension for the output? This should work just fine.
It would also work for the input actually:
```
FileFilter.exe -in c:\temp\raw\SR_20230903_8_SRLA11_filt.unknown -out bla.unknown
``` 

runs just fine.

**Comment by poshul** [comment]
Okay, I've changed it a bit so that it assigns an extension if its clear, and leaves it unknown otherwise.
