### ISSUE TITLE
Remove old Spline2d implementation

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#815]
CubicSpline2d replaced the Eigen implementation Spline2d which should be removed.

(src/openms/include/OpenMS/MATH/MISC/Spline2d.h)

**Comment by cbielow** [comment]
what's wrong with the Spline2d implementation? because it used unsupported/Eigen?

**Comment by aiche** [comment]
AFAIK the old Spline2d implementation was by orders slower

**Comment by hroest** [comment]
Yes I think the Eigen implementation was really slow and having two
implementations where one is better than the other creates confusion

sent from my smartphone -- you may keep any typos you find.

**Comment by hroest** [comment]
I think we can / should go ahead with this. No point in having an old implementation and confusing parallel code lying around

**Comment by timosachsenberg** [comment]
I think it has been removed
