### ISSUE TITLE
complete protein names in ProteinQuantifier output

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#829]
ProteinQuantifier writes in its output not the complete protein name. That makes it for biologists difficult to interpret the results (unlike in other software packages).

For example, in the fasta database a protein appears as
sp | P61983 | 1433G_RAT 14-3-3 protein gamma
In the final protein list it appears only as
sp | P61983 | 1433G_RAT

ProteinHit should either be extended or the complete protein name stored.

**Comment by ursker** [comment]
As a biologist I agree it would be grat to have the protein names!

**Comment by timosachsenberg** [comment]
I think we should use a meta value in idXML for onw until the transition is complete.
This weould be set by PeptideIndexer as it currently allows to set the sequence.

**Comment by lars20070** [comment]
MzTabExporter and TextExporter now do report protein descriptions. But ProteinQuantifier still does not.
The issue will be resolved once ProteinQuantifier also writes mzTab.

**Comment by lars20070** [comment]
The issue will be resolved once ProteinQuantifier also writes mzTab, see #1443.
