### ISSUE TITLE
removing (unnecessary) zeros from spectra

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#839]
While working on the PeakPickerHiRes I came across peaks with intensities such as

0 0 0 0 0 0 0 0 156.375 201.917 235.194 239.809 180.625 0 0 0 0 0 0 0 0

I wonder if we could remove data points of zero intensity which are themselves preceded and followed by zeros as early as possible from the spectra. I cannot see that such data points contain any information. We would gain speed and a lower memory profile.

When working on algorithms, it would be useful if we could make basic assumptions about the spectral data such as ordering in m/z, or no sequence of three or more zeros occuring.
0 0 0 ...

**Comment by timosachsenberg** [comment]
Yep, could go into peakfileoptions

**Comment by cbielow** [comment]
see https://github.com/OpenMS/OpenMS/pull/4680/files for a workable solution

**Comment by cbielow** [comment]
we could actually make this the default?!
