### ISSUE TITLE
OMSSA documentation unavailable

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#849]
The OMSSA homepage (pubchem.ncbi.nlm.nih.gov/omssa/), to which the OMSSAAdapter documentation links for further information, is no longer available (since OMSSA has been discontinued by the NCBI).

In light of this and to avoid headaches for users, it would be helpful to introduce a list of enzyme names for the "-e" parameter, instead of using OMSSA's "magic numbers"-based system. (It might also be a good idea to replace the one-character parameter names in the adapter with actual descriptive names.)
The OMSSAAdapter documentation page mentions that the list of enzymes can be shown by running "omssacl -el", but the parameter documentation for "-e" refers to "omssacl -help", which does NOT give the relevant information.

**Comment by timosachsenberg** [comment]
I think we could also think about deprecating OMSSA in this release

**Comment by hendrikweisser** [comment]
![openms_meme](https://user-images.githubusercontent.com/2251068/43468344-9e02b3ba-94db-11e8-99de-79cc32af53a6.jpg)

See also https://github.com/OpenMS/OpenMS/issues/732#issuecomment-409178559. ;-)

**Comment by timosachsenberg** [comment]
I'll count that as a yes ;)
No seriously, that's not meant as a hasty solution to all our problems but IMHO a valid suggestion in the light of that we currently increase maintenance efforts from release to release. Why should we do that for tools that are already deprecated and basically not used?

**Comment by hendrikweisser** [comment]
Yep, no disagreement from my side.
