### ISSUE TITLE
MascotAdapterOnline crashes on big data file

### ISSUE THREAD

**Issue by PetraGutenbrunner** [OpenMS/OpenMS#871]
MascotRemoteQuery can't send mgf file content via request what is bigger than 2GB

In the MascotAdapterOnline the mgf file content is stored in a `stringstream;`

```
MascotGenericFile mgf_file;
writeDebug_("Writing Mascot MGF file to stringstream", 1);
stringstream ss;
mgf_file.store(ss, in, exp);
```

This `stringstream` is then used in `MascotRemoteQuery::execQuery()` and will be added with additional header information in a `QByteArray` object:

```
QByteArray querybytes;
querybytes.append("--" + boundary + "--\n");
querybytes.append("Content-Disposition: ");
querybytes.append("form-data; name=\"QUE\"\n");
querybytes.append("\n");
querybytes.append(query_spectra_.c_str());
querybytes.append("--" + boundary + "--\n");
querybytes.replace("\n", "\r\n");
```

The problem here is, if the content in the stringstream is bigger than 2GB, it exceeds the 2GB limit of the `QByteArray`.

The input file I used for the search where the problem occurred had 100665 spectra.

Are there any possibilities to solve this problem? One solution we thought about is to store the file content first in a temporary file and this file would be send in the http request.

**Comment by hendrikweisser** [comment]
OpenMS has switched to Qt5 and MascotAdapterOnline (via `MascotRemoteQuery`) now uses `QNetWorkAccessManager`. I therefore expect this issue to be fixed (but haven't tested it).
