### ISSUE TITLE
Mac install instructions

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#912]
Can some mac people update the mac install instructions for OpenMS 1.12 developer version, here it still says to install gsl and coinmp which is true for 1.11 but not for 1.12 any more and all reference to wildmagic and eigen is missing: http://ftp.mi.fu-berlin.de/OpenMS/documentation/html/install_mac.html#using_system_libs

related to #642

**Comment by jpfeuffer** [comment]
Seems to be updated. Close?

**Comment by mwalzer** [comment]
I'm afraid not: https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/install/install-macs.doxygen#L127

**Comment by jpfeuffer** [comment]
Ok seems to be semi-finished:
* Eigen and Wildmagic is mentioned
* gsl removed

From grepping the code, I think that only coinmp is a deprecated dependency, right?

**Comment by hroest** [comment]
is this done?

**Comment by hendrikweisser** [comment]
See also #1839. Should all be fixed in #1945.
