### ISSUE TITLE
Threadsafe OpenMS

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#957]
It would be nice if OpenMS would in general be threadsafe, e.g. if there were no side effects on global states when calling functions. Some of the main obstacles may be
- global variables (hope we dont have any of those)
- singletons and static members

To address singletons and static members we need to either i) remove them or ii) wrap them into an OpenMP `critical` section. 

Currently we seem to have 100+ static variables if I counted correctly:

```
$ grep -R "static " src/openms | grep -v "static void" | grep -v "static const"  | grep -v "//.*static" | grep -v "(" | grep -v NNLS | wc -l
115
```

Explanation of grep command
- remove all `static void` functions (static functions are not a problem)
- remove all `static const` - when it is not mutable its fine
- remove all static in comments
- remove all lines that have a opening paranthesis since they are likely static functions (some false positives here)
- remove NNLS because honestly, nobody will touch that thing

we are left with 115 occurences of static somethings which probably need to be looked at (plus 379 instances of static and an opening paranthesis `grep -R "static " src/openms | grep -v "static const"  |  grep -v "static void"  | grep -v "//.*static" | grep  "(" | wc` which are hopefully mostly static functions and thus not a problem). This issue will track the progress of making OpenMS threadsafe.

**Comment by timosachsenberg** [comment]
could something like: https://github.com/facebook/folly/blob/master/folly/AtomicHashMap.h be part of a solution?
