### ISSUE TITLE
Implement high (arbitrary) resolution isotope pattern generator

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#974]
Currently, we only support nominal mass isotope pattern creation.

See e.g. 2014 publication of MIDAs:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3880471/
c++ code is provide and public domain

**Comment by hendrikweisser** [comment]
Looks to me like this was resolved by adding support for "IsoSpec" in #3766.
