### ISSUE TITLE
Write mzML index by default

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#979]
since we now can write indexed mzML, there is no reason not do so by default. The overhead is minimal and most algorithms could profit from this if an index is available (especially if the file is larger than system memory). 

Indexed mzML is part of the standard http://www.psidev.info/mzml_1_0_0 and most tools should parse indexedMzML as well as mzML

**Comment by hroest** [comment]
After the release is done and closing #1302 we should start thinking about this. What is necessary is to change the default flag for writing indexedmzML and we will have to change all of our test output files 

It would be a nice world if every TOPP tool can assume by default that it is only fed indexed mzML files ...

**Comment by timosachsenberg** [comment]
status?

**Comment by hroest** [comment]
I think we merged it in #1355, it is now true by default in  src/openms/source/FORMAT/OPTIONS/PeakFileOptions.cpp
