### ISSUE TITLE
PeakPickerHiRes "not sorted" error

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#982]
From a discussion on the developers mailing list.

@hendrikweisser wrote:

I wanted to use PeakPickerHiRes on some mzML files and got this error:
"Not all spectra are sorted according to peak m/z positions. Use FileFilter to sort the input!"

Two points about this:
1. Wouldn't it be preferable to give only a warning and automatically correct the problem in this case? (I'd like to avoid the overhead of reading/writing the file again with FileFilter.)
2. I've noticed that the "lowmemory" variant of the tool doesn't perform the check or give the error. There doesn't seem to be any sorting, either. Might the "lowmemory" variant thus produce incorrect results on unsorted inputs?

**Comment by timosachsenberg** [comment]
I think this issue is resolved by sorting the spectra during load?
